### ISSUE TITLE
persist: code movement refactoring

### ISSUE THREAD

**Issue by danhhz** [MaterializeInc/materialize#10005]
Motivations:

- persist::indexed::runtime has grown pretty big
- persist::indexed has a bunch of stuff in it that just as easily could be at the top level
- persist::encoding doesn't make much sense in a world where we've moved this to proto+parquet

# Refactor 1: Split persist::indexed::runtime

Runtime things
- [x] Cmd -> persist::runtime
- [x] start -> persist::runtime
- [x] RuntimeId -> persist::runtime
- [x] RuntimeHandles -> persist::runtime
- [x] RuntimeCore -> persist::runtime
- [x] RuntimeImpl -> persist::runtime
- [x] RuntimeConfig -> persist::runtime
- [x] tests -> persist::runtime

Client things
- [x] RuntimeClient -> persist::client
- [x] StreamWriteHandle -> persist::client
- [x] WriteReqBuilder -> persist::client
- [x] MultiWriteHandle -> persist::client
- [x] DecodedSnapshot -> persist::client
- [x] DecodedSnapshotIter -> persist::client
- [x] StreamReadHandle -> persist::client

# Refactor 2: Remove now unnecessary BlobMeta
- [ ] we can convert directly between AppliedState and ProtoMeta, no need for the middleman
- [ ] move BlobMeta::validate to be on AppliedState

# Refactor 3: Split and flatten persist::indexed

Flatten module structure
- [ ] arrangement -> persist::arrangement
- [ ] background -> persist::background
- [ ] cache -> persist::cache
- [ ] columnar -> persist::columnar
- [ ] metrics -> persist::metrics

Move things in indexed
- [ ] AppliedState -> persist::state
- [ ] PendingResponse -> persist::machine
- [ ] Pending -> persist::machine
- [ ] Indexed -> persist::machine
- [ ] ListenEvent -> persist::machine
- [ ] Snapshot -> persist::machine
- [ ] SnapshotExt -> persist::machine
- [ ] tests -> persist::machine

Move things in encoding
- [ ] encoding::LogEntry -> persist::storage (or persist.proto?)
- [ ] encoding::StreamRegistration -> persist::state
- [ ] encoding::ArrangementMeta -> persist::arrangement (or also remove this in Refactor 2?)
- [ ] encoding::UnsealedBatchMeta -> persist::arrangement
- [ ] encoding::TraceBatchMeta -> persist::arrangement
- [ ] encoding::BlobUnsealedBatch -> persist::arrangement::UnsealedBatch (the Blob prefix was from when it was being directly serialized/deserialized)
- [ ] encoding::BlobTraceBatch -> persist::arrangement::TraceBatch (the Blob prefix was from when it was being directly serialized/deserialized)
- [ ] encoding::PrettyBytes -> persist::arrangement
- [ ] encoding::PrettyRecord -> persist::arrangement
- [ ] tests -> (various, as appropriate)

**Comment by danhhz** [comment]
Hey @ruchirK @aljoscha here's a strawman for a src/persist cleanup I'd like to do (maybe this Friday). I'd love feedback on the above, it's something I threw together quickly to get a discussion started, not anything I'm tied to.

**Comment by aljoscha** [comment]
For now I just have questions, no useful feedback:

I never bothered to ask but just assumed: is `indexed` a remnant from a time where we thought we might have different underlying implementations?

What's the difference between `state` and `machine`? Is `machine` referring to "state machine"?

:100: on splitting `runtime` into `runtime` and `client`.

**Comment by danhhz** [comment]
> I never bothered to ask but just assumed: is indexed a remnant from a time where we thought we might have different underlying implementations?

Intended as a reference to the fact that we store the data in an indexed way (though we don't yet expose that to users)

> What's the difference between state and machine? Is machine referring to "state machine"?

Yeah, definitely looking for feedback on the naming here. "machine" is indeed a reference to a state machine. "state" is the applied state maintained by the machine. Basically, for a bit now, I've been talking about persist as a state machine over a log of commands, but the code doesn't really reflect that. This package naming is a bit forward looking: e.g. really it's a state machine over a log of Cmd::Register, Cmd::Write, Cmd::Seal, Cmd::AllowCompaction and not the read stuff. https://github.com/MaterializeInc/materialize/pull/9574 (which you should familiarize yourself with as well at some point) is another step in this direction and clarifying the bit around cmds that modify state vs ones that don't. Another name I've considered for "machine" is "applier", but it's worth brainstorming all this for sure.

**Comment by danhhz** [comment]
No longer relevant to new persist (whose module structure is still clean "enough")
