### ISSUE TITLE
Add SQL Query for Parsing mz_kafka_source_statistics

### ISSUE THREAD

**Issue by nmeagan11** [MaterializeInc/materialize#10013]
### What pages are affected?

Related to [this](https://materialize.com/docs/sql/system-catalog/#mz_kafka_source_statistics) system catalog table, but unsure that's the best location in the docs to add this request.

### What needs to be changed or added?

Users regularly ask us how to parse out the information in <code>mz_kafka_source_statistics</code> in order to determine if a source is caught up. You used to be able to look at <code>mz_kafka_consumer_partitions</code> for this, but that table has been deprecated. We'd like to add the following query to the docs so we can easily point users to the solution. The query is: <pre><code>CREATE VIEW partition_statistics AS
	SELECT
		s.id AS source_id,
		s.name AS source_name,
		stats.worker,
		topic,
		partition::INT8 AS partition,
		(partition_statistics->>'app_offset')::INT8 AS app_offset,
		(partition_statistics->>'consumer_lag_stored')::INT8 AS consumer_lag_stored,
		(partition_statistics->>'rxmsgs')::INT8 AS rxmsgs,
		(partition_statistics->>'hi_offset')::INT8 AS hi_offset
	FROM
		mz_sources AS s
		JOIN mz_kafka_source_statistics AS stats ON s.id = split_part(stats.source_id, '/', 1),
		ROWS FROM (jsonb_each(statistics->'topics')) AS topics (topic, topic_statistics),
		ROWS FROM (jsonb_each(topic_statistics->'partitions')) AS partitions (partition, partition_statistics);</code></pre>

We also need to make sure https://github.com/MaterializeInc/materialize/pull/10011 lands before safely adding this to the docs, as this query caused a catalog corruption bug upon restart.

### Engineering tracking ticket

https://github.com/MaterializeInc/materialize/issues/7172

### Feature description

We re-designed the system tables for librdkafka statistics some time back. Users now struggle to parse out some information as compared to how they used to be able to.

### Design documents

N/A

**Comment by ruchirK** [comment]
just to be clear - that's not the exact query and doesn't fully replicate the old table. That was just for purposes of demonstration of how to do this
