### ISSUE TITLE
What is the license?

### ISSUE THREAD

**Issue by mardonet** [MaterializeInc/materialize#10042]
### Feature request

Hello. I tried to use the demo but there is no license specified in the code.

**Comment by frankmcsherry** [comment]
Hello. The license is available in the root of the repository:

https://github.com/MaterializeInc/materialize/blob/main/LICENSE

**Comment by mardonet** [comment]
ups my apologies. I was looking ecommerce-demo, but posted here by mistake. https://github.com/MaterializeInc/ecommerce-demo
