### ISSUE TITLE
pg-cdc: compute `CREATE VIEWS FROM SOURCE` using catalog information

### ISSUE THREAD

**Issue by petrosagg** [MaterializeInc/materialize#10121]
Once #6739 is resolved we will have everything we need already stored in the catalog to compute the views during a `CREATE VIEWS FROM SOURCE` statement. Currently we rely on the purification step to reach out to the upstream postgres database to re-read the schemas but we should just use the information in our catalog.

**Comment by benesch** [comment]
I believe this was resolved by the move to subsources.
