### ISSUE TITLE
Optimization: MapFilterProject::optimize needs to alternate with expression simplication.

### ISSUE THREAD

**Issue by wangandi** [MaterializeInc/materialize#10130]
### What version of Materialize are you using?

latest main

### How did you install Materialize?

Built from source

### What was the issue?

```
materialize=> EXPLAIN SELECT (COALESCE(record, ROW(NULL, NULL))).f2 FROM (SELECT ROW(a, a) AS record FROM t1);
          Optimized Plan           
-----------------------------------
 %0 =                             +
 | Get materialize.public.t1 (u11)+
 | Map #0                         +
 | Project (#2)                   +
```

The above plan is suboptimal. The optimal plan would look like:

```
 %0 =                             +
 | Get materialize.public.t1 (u11)+
 | Project (#0)                   +
```

How the suboptimal plan is happening:

The plan that comes into `CanonicalizeMFP` looks like this:
```
          Optimized Plan           
-----------------------------------
 %0 =                             +
 | Get materialize.public.t1 (u11)+
 | Map record_create(#0, #0), record_get[1](#2)+
 | Project (#3)                   +
```

`CanonicalizeMFP` calls `MapFilterProject::optimize()`, which detects that the first mapped expression can be inlined into the second mapped expression.
```
          Optimized Plan           
-----------------------------------
 %0 =                             +
 | Get materialize.public.t1 (u11)+
 | Map record_get[1](record_create(#0, #0))+
 | Project (#2)                   +
```
`CanonicalizeMFP` does not reduce the expression `record_get[1](record_create(#0, #0)`, though. Expression reduction happens later in `FoldConstants`:
```
          Optimized Plan           
-----------------------------------
 %0 =                             +
 | Get materialize.public.t1 (u11)+
 | Map #0                         +
 | Project (#2)                   +
```

But we don't go back to `CanonicalizeMFP` to convert the `| Map #0 | Project (#2)` back into `Project(#0)`.

It is possible to construct queries which require multiple optimization-reduction loops. For example, this query, which currently plans as:
```
explain SELECT (record3).f2
FROM (
  SELECT ROW((record2), d) as record3
  FROM (
    SELECT (record2).f1 as d, record2
    FROM (
        SELECT ROW(c, (record)) as record2
        FROM (
            SELECT (record).f2 as c, record
            FROM (
                SELECT ROW(a, b) as record FROM t1)))));
                                    Optimized Plan                                    
--------------------------------------------------------------------------------------
 %0 =                                                                                +
 | Get materialize.public.t1 (u11)                                                   +
 | Map record_create(#0, #1), record_create(record_get[1](#2), #2), record_get[0](#3)+
 | Project (#4)                                                                      +
```

would need three optimization-reduction passes to get down to an optimal plan:

```
                                    Optimized Plan                                    
--------------------------------------------------------------------------------------
 %0 =                                                                                +
 | Get materialize.public.t1 (u11)                                                   +
 | Project (#1)
```

To see why, notice how in
```
 | Map record_create(#0, #1), record_create(record_get[1](#2), #2), record_get[0](#3)
```
the first map expression is not inlined because the second expression has two references to it. The first map expression only gets inlined after the second map expression gets inlined into the third and gets reduced down to `record_get[1](#2)`.

**Comment by wangandi** [comment]
Three options for fixing this issue:
1) Have `MapFilterProject::optimize` call `MirScalarExpr::reduce` in a loop with `MapFilterProject::inline_expressions`. The problem with this is that `MirScalarExpr::reduce` requires providing column types as an argument, but `MapFilterProject::optimize` does not take column types as an argument and is called from a location where the column types cannot be obtained:
https://github.com/MaterializeInc/materialize/blob/b8473191f5800fb18ba0e5da4a10e475b235ce67/src/dataflow/src/render/context.rs#L535
(Personally, I think the above line should be moved or removed. For one, it should be redundant with `CanonicalizeMfp` once this and #10000 are fixed. Two, it runs after the LIR is created, which means that changes it makes cannot be seen using `EXPLAIN PHYSICAL PLAN FOR...`)

2) Have `CanonicalizeMfp` call `MirScalarExpr::reduce` in a loop with `MapFilterProject::optimize`. Code for this option can be found in #9968.

3) Have `CanonicalizeMfp` run in a fixpoint together with `FoldConstants`. I am against this because `CanonicalizeMfp` and map expression reduction should not change whether a constant can be folded into a Map/Filter/Project.

**Comment by ggevay** [comment]
This got solved in the meantime:

```
materialize=> 
create table t1(a int, b int);

EXPLAIN SELECT (COALESCE(record, ROW(NULL, NULL))).f2 FROM (SELECT ROW(a, a) AS record FROM t1);

CREATE TABLE
            Optimized Plan             
---------------------------------------
 Explained Query:                     +
   Project (#0)                       +
     ReadStorage materialize.public.t1+
                                      +
 Source materialize.public.t1         +
                                      +
 Target cluster: quickstart           +
 
(1 row)
```

```
materialize=> explain SELECT (record3).f2
FROM (
  SELECT ROW((record2), d) as record3
  FROM (
    SELECT (record2).f1 as d, record2
    FROM (
        SELECT ROW(c, (record)) as record2
        FROM (
            SELECT (record).f2 as c, record
            FROM (
                SELECT ROW(a, b) as record FROM t1)))));
            Optimized Plan             
---------------------------------------
 Explained Query:                     +
   Project (#1)                       +
     ReadStorage materialize.public.t1+
                                      +
 Source materialize.public.t1         +
                                      +
 Target cluster: quickstart           +
 
(1 row)
```

I'm not exactly sure how, but two things that seem relevant:
- The looping in `MapFilterProject::optimize()`: https://github.com/MaterializeInc/materialize/blob/af2c81fa322e25b706684fd7cf0da45465fb1204/src/expr/src/linear.rs#L896
- The "We have an annoying pattern" comment in `MapFilterProject::optimize()`.
