### ISSUE TITLE
Support JSON-formatted consistency topics

### ISSUE THREAD

**Issue by elindsey** [MaterializeInc/materialize#10163]
### Feature request

At the moment, exactly-once sinks can only write/consume their consistency topics in Avro (even if the sink is writing JSON to the data topic).

The consistency topic is primarily used by mz itself, so this has little customer impact (except that the users must explicitly specify an avro formatted consistency topic for json formatted sinks). If we do come across use cases where people would like to consume the consistency topic then it would make sense to prioritize this work - it would be more convenient for the consistency and data topics to be in the same format if a user is consuming both.

**Comment by bkirwi** [comment]
As part of #11216, we're replacing the consistency topic with a new internally-facing-only "progress topic", so it's no longer necessary to support multiple formats.
