### ISSUE TITLE
Single-materialization sources are under-documented documentation

### ISSUE THREAD

**Issue by benesch** [MaterializeInc/materialize#10219]
### What pages are affected?

https://github.com/MaterializeInc/materialize/commit/6a1375697f6fa7a8d8c90c8c8fc3bc56d2bf1c7b#diff-ab5bcc4083a449943016440c1d090df36d4753313bef2efb32e20e6ae8ab0700 added a smidge of documentation about the new source types that can only be materialized once (PostgreSQL sources and S3 sources when SQS notifications are enabled).

If these sorts of sources stick around for a while, they probably need more documentation. "Materialized by a single set of views" is unlikely to be enough documentation for a user to understand the situation.

### Engineering tracking ticket

#9576

**Comment by morsapaes** [comment]
This has been addressed in #10528 and in the source documentation reorg (IMO to enough extent!), so closing the issue.
