### ISSUE TITLE
remove references to `username` and `password` WITH options from CSR docs

### ISSUE THREAD

**Issue by guswynn** [MaterializeInc/materialize#10235]
Only in the avro docs: https://materialize.com/docs/sql/create-source/avro-kafka/#connecting-to-a-kafka-broker-using-sasl-authentication

and as far as I can tell, they are unused

**Comment by morsapaes** [comment]
Isn't HTTP basic authentication still supported?

https://github.com/MaterializeInc/materialize/blob/3751539bebb6a2dab13b63154600ed0fdd95900f/src/ccsr/src/client.rs#L54

**Comment by guswynn** [comment]
@morsapaes it seems that it is, but I need to take some time to actually setup a test for it and document it better!

**Comment by morsapaes** [comment]
Closing due to #10150.
