### ISSUE TITLE
pg-cdc: use more efficient COPY query during initial snapshot

### ISSUE THREAD

**Issue by petrosagg** [MaterializeInc/materialize#10241]
When ingesting a postgres source we're currently issuing a `SELECT *` to the target table in order to receive the current snapshot.

Using a `COPY` query would be much better suited for this type of bulk transfer that should improve initial loading times.

**Comment by umanwizard** [comment]
Relevant `TODO` here:  https://github.com/MaterializeInc/materialize/blob/fdfeada5328f74028c1d346f03185a83282565e3/src/dataflow/src/source/postgres.rs#L200

**Comment by pH14** [comment]
Will take a look here!
