### ISSUE TITLE
ENVELOPE NONE sources always contain a mz_offset column, preventing compaction

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#10274]
### What version of Materialize are you using?

v0.18.1-dev (f07ca46b1)

### How did you install Materialize?

Built from source

### What was the issue?

`ENVELOPE NONE` sources always have an `mz_offset` column tacked on to them.

This has two implications:
- compaction on such materialized sources is prevented as each record is now effectively unique, the arrangement is being built on top of `(value, mz_offset)` column pair, as seen in the `mz_index_columns` table.
- When the same value is ingested N times, TAIL will return N separate rows of the value, each with a `diff` = 1, because each row is considered unique now that it has a unique `mz_offset` tacked on it.

In practical terms:
- memory blows up
- ingestion slows down over time even if ingesting identical records
- simple SELECT COUNT(*) queries over the materialized source take time to execute proportional to the number of records, not the number of unique records 

```./src/dataflow-types/src/types.rs``` contains the following comment:

```
    /// Legacy logic included something like an offset into almost data streams
    ///
    /// Eventually we will require `INCLUDE <metadata>` for everything.
```

**Comment by philip-stoev** [comment]
Benchmarking scenario illustrating the problem:

```
diff --git a/test/feature-benchmark/scenarios.py b/test/feature-benchmark/scenarios.py
index cd8b0fc82..eb84c975c 100644
--- a/test/feature-benchmark/scenarios.py
+++ b/test/feature-benchmark/scenarios.py
@@ -877,3 +877,34 @@ $ kafka-ingest format=avro topic=sink-input key-format=avro key-schema=${{keysch
 """
             + str(self.n())
         )
+
+@parameterized_class(
+    [{"SCALE": i} for i in [5,6,7,8]], class_name_func=Scenario.name_with_scale
+)
+class GH10271(ScenarioBig):
+    def shared(self) -> Action:
+        return TdAction(
+            f"""
+$ kafka-create-topic topic=kafka-envelope-none-bytes
+
+$ kafka-ingest format=bytes topic=kafka-envelope-none-bytes repeat={self.n()}
+12345678901234567890123456789012345678901234567890
+"""
+        )
+
+    def benchmark(self) -> MeasurementSource:
+        return Td(
+            f"""
+> DROP SOURCE IF EXISTS s1;
+
+> CREATE MATERIALIZED SOURCE s1
+  FROM KAFKA BROKER '${{testdrive.kafka-addr}}' TOPIC 'testdrive-kafka-envelope-none-bytes-${{testdrive.seed}}'
+  FORMAT BYTES
+  ENVELOPE NONE
+  /* A */
+
+> SELECT COUNT(*) = {self.n()} FROM s1
+  /* B */
+true
+"""
+        )
```

Run as :

```
bin/pyactivate --dev
cd test/feature-benchmark
 ./mzcompose run default --root-scenario=GH10271 --max-runs=1
```

**Comment by frankmcsherry** [comment]
This is exactly the sort of issue that pushing down `MapFilterProject` is meant to solve. We are able to drop unused columns with `LinearOperator` at the moment, but most sources do not do this.

**Comment by frankmcsherry** [comment]
Is this issue still the case? We are documented as having a `WITH OFFSET` option, and if it is not set and yet we are durably recording the offset and preventing compaction, that sounds like either a bug or something in need of very clear explanation.

**Comment by benesch** [comment]
This is no longer the case. As @frankmcsherry mentioned, you now must explicitly request an offset column, via `INCLUDE OFFSET`.
