### ISSUE TITLE
Make sure CCSR basic auth is fixed.

### ISSUE THREAD

**Issue by umanwizard** [MaterializeInc/materialize#10286]
### What version of Materialize are you using?

n/a

### How did you install Materialize?

Built from source

### What was the issue?

PR #10129 landed on main, which broke CCSR basic auth. Luckily, it has not yet gone out for release. A candidate fix landed in #10283, but we haven't had time to thoroughly test it.

We should do so before releasing v0.19.0, either with an automated test if it's not too much work to spin one up in time for the Monday cut, or manually otherwise.

**Comment by guswynn** [comment]
closed by https://github.com/MaterializeInc/materialize/pull/10292

**Comment by guswynn** [comment]
more thorough followup: https://github.com/MaterializeInc/materialize/issues/10295
