### ISSUE TITLE
Test full matrix of Kafka + Schema Registry auth configurations

### ISSUE THREAD

**Issue by benesch** [MaterializeInc/materialize#10295]
Presently we've got three separate compositions that test Kafka + CSR in various authentication configurations.

  * [test/kafka-krb5](https://github.com/MaterializeInc/materialize/tree/main/test/kafka-krb5) is an old-style mzcompose.yml file that tests Kerberos auth against both Kafka + CSR.
  * [test/kafka-sasl-plain](https://github.com/MaterializeInc/materialize/tree/main/test/kafka-sasl-plain) is an old-style mzcompose.yml file that tests SASL username/password auth against Kafka. I'm not sure what it does with CSR, maybe no auth?
  * [test/kafka-ssl](https://github.com/MaterializeInc/materialize/tree/main/test/kafka-ssl) is a new-style mzcompose.py file that tests SSL _and_ basic auth against both Kafka + CSR.

These tests are a bit confused about who should be testing what. Part of that confusion stems from the fact that the `CREATE SOURCE` syntax defaults to using the Kafka SSL configuration, which... I'm not even sure it makes sense in general? It made sense for the test case we wrote, but I'm not sure it's even valid for Confluent Cloud? Someone should check me on that. cc @elindsey because I know you were thinking about this.

These tests could all be unified into a single test matrix over `kafka_auth_type={none|tls|sasl|kerberos}` and `csr_auth_type={none|tls|basic|tls+basic|kerberos}`. Note that `tls` here means client auth (mTLS), not just enabling TLS encryption. The actual test, then, is:

1. Turn on Kafka and CSR with the configured authentication.
2. Write a sample Avro datum to Kafka with a schema published in the CSR.
3. Run a valid `CREATE SOURCE` command and assert that it passes.
4. Run an invalid `CREATE SOURCE` command (using a wrong password or a wrong cert or a wrong whatever for the auth type) and assert that it fails.

I assert that there is a way to write that test cleanly in one mzcompose.py using the right balance of testdrive and mzcompose.py, though I don't claim that that solution will be easy to find. But whoever finds it will deeply understand the auth possibilities here, and can hopefully use that knowledge to orthogonalize both our docs and syntax.

One other thing to note: these tests waste some time currently by configuring Kafka and the CSR for internal communication over SSL/Kerberos. That's a big chunk of the complexity. If it's possible to create a separate unauthed listener, that would be a huge reduction in complexity. We could point testdrive's internal stuff at that unauthed listener too, and then testdrive wouldn't need to be informed of the right certs and passwords. Put another way: we don't care about configuring Kafka and the CSR to talk over Kerberos. That's Confluent's problem, and we can assume that it works.

**Comment by benesch** [comment]
Here is a candidate proposal for what that matrix test would look like:

```
# good.td
$ set schema=
int

$ kafka-create-topic topic=data

$ kafka-ingest format=avro topic=data schema=${schema} publish=true
1

> CREATE MATERIALIZED SOURCE data
  FROM KAFKA BROKER 'kafka:9092' TOPIC 'testdrive-data-${testdrive.seed}'
  WITH (${var.kafka-options})
  FORMAT AVRO USING CONFLUENT SCHEMA REGISTRY '${testdrive.schema-registry-url}'
  WITH (${var.csr-options})
  ENVELOPE NONE

> SELECT * FROM data
1
```

```
# bad.td
$ set schema=
int

$ kafka-create-topic topic=data

$ kafka-ingest format=avro topic=data schema=${schema} publish=true
1

! CREATE MATERIALIZED SOURCE data
  FROM KAFKA BROKER 'kafka:9092' TOPIC 'testdrive-data-${testdrive.seed}'
  WITH (${var.kafka-options})
  FORMAT AVRO USING CONFLUENT SCHEMA REGISTRY '${testdrive.schema-registry-url}'
  WITH (${var.csr-options})
  ENVELOPE NONE
contains:${var.expected-error}
```

```py
@dataclass
class TestCase:
    schema_registry_env_extra: List[str]
    schema_registry_with_options: Dict[str, str]
    kafka_env_extra: List[str]
    kafka_with_options: Dict[str, str]
    expected_error: Option[str]

test_cases = [
    TestCase(
        schema_registry_env_extra=["..."],
        # ...
    )
]

def workflow_default(c: Composition):
    for test_case in test_cases:
        kafka = Kafka(env=[..., test_case.kafka_env_extra])
        schema_registry = SchemaRegistry(env=[..., test_case.schema_registry_env_extra])
        with c.override(kafka, schema_registry):
            kafka_options = make_with_options(tc.kafka_env_extra)
            schema_registry_options = make_with_options(tc.schema_registry_options)
            if test_case.expected_error:
                c.run("testdrive", f"--var=kafka-with-options={tc.kafka_env_extra}", f"--var=expected-error={tc.expected_error}", "bad.td")
            else:
                c.run("testdrive", f"--var=kafka-with-options={tc.kafka_env_extra}", "good.td")

def make_with_options(options: Dict[str, str]) -> str:
    # Some kinda gross code to turn a dict into a WITH clause.
```

There's a good albeit simpler example of this pattern in https://github.com/MaterializeInc/materialize/blob/main/test/proxy/mzcompose.py.

**Comment by guswynn** [comment]
@benesch `kafka-sasl-plain` is VERY confusing to me lol, it seems to setup CSR to use a password file...but we don't actually pass in a password/username into the client config? Ill have to look closer

**Comment by benesch** [comment]
Yeah, isn't it _thoroughly_ baffling? Something is broken there, for sure.
