### ISSUE TITLE
persist: trace compaction seems broken

### ISSUE THREAD

**Issue by danhhz** [MaterializeInc/materialize#10300]
I just fired up some long running s3 tests on cloud and noticed that they don't seem to be compacting trace? the number of batches/bytes in trace is increasing linearly (for hours now, well past the 5m metric retraction window). I've spun up a fresh instance via the web ui and got v0.18.0, which seems fine (phew!)

**Comment by danhhz** [comment]
this bug means that the background system tables test no longer uses a bounded amount of disk, so until we find the issue and either fix the bug or revert the offending PR, this should probably be a release blocker. at the moment, it's only affecting HEAD, so as far as I know right now there's no issue on cloud's currently running background tests

 cc @ruchirK @elindsey

**Comment by danhhz** [comment]
I _think_ it's pretty easy to triage if a commit is good or bad by starting it up with --retain-prometheus-metrics=1s and watching the mz_persist_compaction_bytes metric. if it increments above 0 (should happen within a minute with the 1s flag) then that commit is good. I'll start a bisect

**Comment by danhhz** [comment]
The git bisect identified 3c0694c8297b697d279ff784e7860d095a0d3826 which was part of https://github.com/MaterializeInc/materialize/pull/10230. I'm going to stand up a couple instances right before and after this commit to make sure my mz_persist_compaction_bytes proxy was correct. I'm also going to look at that commit and see if I can spot the bug

**Comment by danhhz** [comment]
The running 3c0694c8297b697d279ff784e7860d095a0d3826 pretty clearly exhibits the problem while the commit before it aad2be996b78b840fb2596ca367f438a3e99c8b4 (also from the same PR) doesn't. cc @aljoscha

**Comment by danhhz** [comment]
I have a very hand-wavey theory. The allow compaction updates for tables are hooked up to the single index we always render for a table not to the table itself. It was unclear at the time that this was the right thing to do, but it also wasn't clear how to hook them up to tables For Reasons (tm).

The commit in question splits `ComputeCommand::AllowCompaction` into `ComputeCommand::AllowIndexCompaction` and `StorageCommand::AllowSourceCompaction`. After the commit, persist compaction is hooked up to the receiver side of StorageCommand::AllowSourceCompaction, but I bet the messages it needs are being sent to the other one because of the hack I mention above.

One possible hack to fix this until someone who knows what they are doing can look at it is to hook persist up to both of them. I'll prototype it quickly to try to confirm my theory.

**Comment by danhhz** [comment]
I think that works! The following diff applied on top of 3c0694c seems to fix the issue

```diff
diff --git a/src/coord/src/coord.rs b/src/coord/src/coord.rs
index b1b0783a6..414cea13b 100644
--- a/src/coord/src/coord.rs
+++ b/src/coord/src/coord.rs
@@ -1574,6 +1574,7 @@ where
             .collect();
 
         if !index_since_updates.is_empty() {
+            self.persisted_table_allow_compaction(&index_since_updates);
             self.dataflow_client
                 .allow_index_compaction(index_since_updates)
                 .await;
```

It's gross, but probably worth merging to unbreak the background system tables test in main. I go ahead an PR it

**Comment by danhhz** [comment]
Alex H confirms that we're not seeing full disks on cloud. This is expected given that this commit isn't in the latest release, but I wanted to be double sure

**Comment by danhhz** [comment]
merged a temporary fix, so removing the release blocker label

there's definitely some missing test coverage here. brainstormed briefly with ruchir and will do more brainstorming on monday, but one option is to base a test on the metrics system table (write a big thing in test drive, wait until it shows up, delete it, wait until the metrics are what we expect) but perhaps it's time to philip's ask for system tables to introspect into persist. it wouldn't be hard to pass a channel into persist at start time that it dumps info into. we'd probably just want to mirror what's already being reported about arrangements. this would also be a great time to feed info about the since and upper of each persisted collection back to coord, which will be useful for many things

**Comment by ruchirK** [comment]
I added a test for trace compaction based on metrics in https://github.com/MaterializeInc/materialize/pull/10541 as this happened again in https://github.com/MaterializeInc/materialize/issues/10533

I think we should close this issue and open a new one to track better introspection / more testing as needed

**Comment by danhhz** [comment]
> I think we should close this issue and open a new one to track better introspection / more testing as needed

Agreed
