### ISSUE TITLE
List all users using \du hits syntax error

### ISSUE THREAD

**Issue by chenjiayuan** [MaterializeInc/materialize#10305]
### What version of Materialize are you using?

v0.17.0

### How did you install Materialize?

Homebrew tap

### What was the issue?

Just downloaded materialize and trying out some basic stuff. My muscle memory typed `\du` to list all the users in the postgres catalog, but it hits:
```
materialize=> \du
ERROR:  Expected left square bracket, found left parenthesis
LINE 4:   ARRAY(SELECT b.rolname
               ^
```
Please advice if this is a known issue.

**Comment by morsapaes** [comment]
Hey, @chenjiayuan! We're working on expanding the support for `psql` meta-commands (see #9721), but `\du` hasn't been added yet. You can subscribe to the tracking issue (#9730) to follow the progress!

**Comment by morsapaes** [comment]
@andrioni, would it make sense to throw a more sensible error for unsupported meta-commands, in the meantime?

**Comment by andrioni** [comment]
@morsapaes, not sure how viable that is: meta-commands just execute regular queries, so we would have to sort of pattern match against some kinds of queries and display different error messages just for those cases.

@chenjiayuan, until we support `\du`, you can run `SELECT * FROM pg_roles` or `SELECT * FROM mz_roles`. Support the main psql meta-commands (as listed in #9721) is being currently worked on, so `\du` should be working fine in the next coming weeks.

**Comment by morsapaes** [comment]
Closing this in favour of the mentioned tracking issues. Thanks again for pinging us about it, @chenjiayuan!
