### ISSUE TITLE
invalid encoding name

### ISSUE THREAD

**Issue by rafa-aptitude** [MaterializeInc/materialize#10378]
### What version of Materialize are you using?

v0.18.0 (ea47db099)

### How did you install Materialize?

APT package

### What was the issue?

I am consuming from a topic with the following schema
```JSON
{
  "fields": [
    {
      "name": "AGREEMENT_ID",
      "type": "string"
    },
    {
      "default": null,
      "name": "AGREEMENT_TYPE",
      "type": [
        "null",
        "string"
      ]
    },
    {
      "default": null,
      "name": "AGREEMENT_STATUS_CD",
      "type": [
        "null",
        "string"
      ]
    },
    {
      "default": null,
      "name": "AGREEMENT_START_DT",
      "type": [
        "null",
        {
          "connect.name": "org.apache.kafka.connect.data.Date",
          "connect.version": 1,
          "logicalType": "date",
          "type": "int"
        }
      ]
    },
    {
      "default": null,
      "name": "AGREEMENT_END_DT",
      "type": [
        "null",
        {
          "connect.name": "org.apache.kafka.connect.data.Date",
          "connect.version": 1,
          "logicalType": "date",
          "type": "int"
        }
      ]
    },
    {
      "default": null,
      "name": "table",
      "type": [
        "null",
        "string"
      ]
    },
    {
      "default": null,
      "name": "scn",
      "type": [
        "null",
        "string"
      ]
    },
    {
      "default": null,
      "name": "op_type",
      "type": [
        "null",
        "string"
      ]
    },
    {
      "default": null,
      "name": "op_ts",
      "type": [
        "null",
        "string"
      ]
    },
    {
      "default": null,
      "name": "current_ts",
      "type": [
        "null",
        "string"
      ]
    },
    {
      "default": null,
      "name": "row_id",
      "type": [
        "null",
        "string"
      ]
    },
    {
      "default": null,
      "name": "username",
      "type": [
        "null",
        "string"
      ]
    }
  ],
  "name": "ConnectDefault",
  "namespace": "io.confluent.connect.avro",
  "type": "record"
}
```

When I try this

```SQL
CREATE SOURCE agreements_source
FROM KAFKA BROKER 'localhost:9092' TOPIC 'ORCLPDB1.C__MYUSER.AGREEMENT_TEST'
FORMAT BYTES;

CREATE VIEW agreements_view AS
  SELECT
    (agreements_data->'agreement_id')::STRING as agreement_id,
    (agreements_data->'AGREEMENT_TYPE')::STRING as AGREEMENT_TYPE,
    (agreements_data->'AGREEMENT_STATUS_CD')::STRING as AGREEMENT_STATUS_CD,
    to_timestamp((agreements_data->'AGREEMENT_START_DT')::INT) as AGREEMENT_START_DT,
    to_timestamp((agreements_data->'AGREEMENT_START_DT')::INT) as AGREEMENT_END_DT
  FROM (
    SELECT convert_from(data, 'iso-8859-5')::jsonb AS agreements_data
    FROM agreements_source
  );
  CREATE MATERIALIZED VIEW agreements_view_materialized AS
    SELECT
      AGREEMENT_ID,
      AGREEMENT_TYPE,
      AGREEMENT_STATUS_CD,
      AGREEMENT_START_DT,
    AGREEMENT_END_DT
    FROM agreements_view;

SELECT AGREEMENT_TYPE FROM agreements_view_materialized LIMIT 100;
```
I get this `Evaluation error: invalid encoding name 'iso-8859-5'`. I got the same type of error with other formats, like iso_8859_5, iso88595, latin1, utf16 and some more combinations. None of them works. 

### Relevant log output

ERROR:  Evaluation error: invalid encoding name 'iso-8859-5'

**Comment by benesch** [comment]
The only encoding name we support is 'utf-8'. Is your data actually encoded as ISO-8859-5?

**Comment by rafa-aptitude** [comment]
Hi benesh!
   Thank you for answering. 
   I tried the following what is stated in this link in the official documentation: https://materialize.com/docs/sql/functions/length/#encoding-details. I also looked into this function: https://github.com/lifthrasiir/rust-encoding/blob/4e79c35ab6a351881a86dbff565c4db0085cc113/src/label.rs, which is referred to on that page or on a linked one. 
I was trying this to solve a problem with the utf8 encoding. I got the following message when processing my data: 

> _Evaluation error: invalid byte sequence 'invalid utf-8 sequence of 1 bytes from index 16' for encoding 'utf8'_

We have checked the messages in the control centre and they appear properly formated. Of course, we have not checked all but only a sample of them, but they have been created with faker, the python library and the English locale. That is why I find it strange that they are not utf-8.  Any idea of how to solve that initial problem if it is not by changing the encoding?

**Comment by benesch** [comment]
Oh, apologies, I didn't look very closely at your full bug report. That's an Avro schema, no? But it seems you are trying to decode it as JSON. You should use `FORMAT AVRO` instead of `FORMAT BYTES`, and then you won't need to create a view on top of the source at all. There are some examples here: https://materialize.com/docs/sql/create-source/avro-kafka/#using-a-confluent-schema-registry

**Comment by rafa-aptitude** [comment]
@benesch, thank you for your answer again. No need to apologise. We tried that first but we encountered a second problem described in this other ticket: https://github.com/MaterializeInc/materialize/issues/10399. Now that other approach works. we have a path to follow. Thank you!

**Comment by benesch** [comment]
Great! Supporting additional encodings in `convert_from` is tracked by #2282, so I'm going to close this out. Glad we got it sorted!
