### ISSUE TITLE
kafka-exactly-once-sink.td is failing with --workers 32 after "Fence consistency topics before determining latest ts (#10094)" 

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#10398]
### What version of Materialize are you using?

4159a4b5c577099bf40efd611a11a5e63209899c

### How did you install Materialize?

Built from source

### What was the issue?

After this revision:

```
4159a4b5c577099bf40efd611a11a5e63209899c is the first bad commit
commit 4159a4b5c577099bf40efd611a11a5e63209899c
Author: Chae Jubb <chae@materialize.com>
Date:   Fri Jan 28 11:08:41 2022 -0500

    [kafka exactly once sink] Fence consistency topics before determining latest ts (#10094)
```

the `kafka-exactly-once-sink.td` test has started failing when run in Nightly with --workers 32:

```
bin/mzcompose --find testdrive run default --workers 32 kafka-exactly-once-sink.td
```

The test has a feature that queries the number of timestamp bindings and the number never seems to converge to the desired one. I did not try increasing the timeout as the numbers reported do not trend down, but are all over the place.

The same failure has been seen previously in the Antithesis environment, where processes are being executed very slowly. Maybe Mz became slower due to this commit and the test has started to fail because of that in our own CI?

### Relevant log output

```source
Verifying timestamp binding compaction for "input_csv".  Found 1 vs expected 3.  Progress: false
Verifying timestamp binding compaction for "rt_binding_consistency_test_source".  Found 16 vs expected 3.  Progress: false
Verifying timestamp binding compaction for "rt_binding_consistency_test_source".  Found 3 vs expected 3.  Progress: true
Verifying timestamp binding compaction for "input_kafka_no_byo".  Found 14 vs expected 3.  Progress: false
Verifying timestamp binding compaction for "input_kafka_no_byo".  Found 4 vs expected 3.  Progress: false
Verifying timestamp binding compaction for "input_kafka_no_byo".  Found 11 vs expected 3.  Progress: false
Verifying timestamp binding compaction for "input_kafka_no_byo".  Found 11 vs expected 3.  Progress: false
Verifying timestamp binding compaction for "input_kafka_no_byo".  Found 18 vs expected 3.  Progress: false
^^^ +++
kafka-exactly-once-sink.td:366:1: error: There are 18 bindings compared to max size 3
     |
 365 | $ verify-timestamp-compaction source=rt_binding_consistency_test_source max-size=3 permit-progress=true
 366 | $ verify-timestamp-compaction source=input_kafka_no_byo max-size=3
     | ^
```

**Comment by philip-stoev** [comment]
Test was added by @aljoscha so he can provide more context.

**Comment by philip-stoev** [comment]
Apologie,s I thought `verify-timestamp-compaction` was added by @aljoscha but apparently this is not the case. So he is off the hook.

**Comment by cjubb39** [comment]
yes he is off the hook! I'll take looking into this

**Comment by cjubb39** [comment]
Chatted in internal slack and this test being flaky should not block the release:

flaky: likely just taking slightly longer to compact but the compaction is still happening.  This is behavior I’ve seen before especially on the 32 worker test
always failing: possibly indicative of an issue with compaction actually happening.

That said, flaky tests are bad so I'll disable immediately and then look into reproing and fixing!
