### ISSUE TITLE
CI: support symbiosis mode in CI/tests

### ISSUE THREAD

**Issue by quodlibetor** [MaterializeInc/materialize#1039]
DoD:

* we can use symbiosis mode in the various integration tests (i.e. the `tests/*` files)
* we have some sane messaging/setup story around getting pg set up for people/skipping tests that require symbiosis mode.

**Comment by benesch** [comment]
Symbiosis mode is on the way out. Most of what folks need out of symbiosis mode is provided via tables, though of course we don't support UPDATE and DELETE yet. But those are on the roadmap and are the way forward!
