### ISSUE TITLE
sql: `pg_catalog` views do not limit to the current database

### ISSUE THREAD

**Issue by benesch** [MaterializeInc/materialize#10391]
The views in `pg_catalog` ought to be limited to the current active database, but instead they expose the data from all available databases.

None of the views in `pg_catalog` include a `database_id` field, so you can't even filter it down after the fact. (Not that any of the tools that are introspecting these views would be prepared to do that anyway.)

The naive approach of adding a `JOIN mz_databases d ON d.id = input.database_id WHERE (d.id IS NULL OR d.name AND current_database())` doesn't work because `current_database` gets resolved at plan time, not execution time. And... hm.. that's probably not right. Probably `current_database` needs to be a function that's banned in indexes, but allowable in views, and replaced at the moment right before we go to build a dataflow.

**Comment by mjibson** [comment]
A solution to this problem could also be connection aware and filter out temp objects created by different connections. This probably requires a separate conn_id field in mz_objects and a new conn_id() function?

**Comment by benesch** [comment]
Oof, yeah, the temp table stuff is busted too. Sounds right to me.

**Comment by necaris** [comment]
OK, so I've been digging into this trying to understand how it all hangs together, and how I might approach implementing it. Here are some thoughts / queries -- please forgive the incoherence, I'm still finding my way around.

 - The "naive" approach, as @benesch points out, would be to add SQL to the built-in views' definitions -- presumably in https://github.com/MaterializeInc/materialize/blob/main/src/coord/src/catalog/builtin.rs#L1576 and similar places.
   - This SQL would have to use a `current_database()` or similar function which doesn't right now exist. Where are functions that can be called at execution time defined? What I could find was `UnmaterializableFunc`, but that is definitely resolved at plan time.
 - It seems to me that adding connection awareness as @mjibson suggested would mean adding columns to the built-in views so they could be filtered on, but that would seem to be a no-no for Postgres compatibility?

**Comment by benesch** [comment]
> * The "naive" approach, as @benesch points out, would be to add SQL to the built-in views' definitions -- presumably in https://github.com/MaterializeInc/materialize/blob/main/src/coord/src/catalog/builtin.rs#L1576 and similar places.
>   
>   * This SQL would have to use a `current_database()` or similar function which doesn't right now exist. Where are functions that can be called at execution time defined? What I could find was `UnmaterializableFunc`, but that is definitely resolved at plan time.

Yes, precisely! That function does actually exist! It's defined here: https://github.com/MaterializeInc/materialize/blob/d9c8f6d5fed36fc4f055f56cf5c5caf20986a0ea/src/sql/src/func.rs#L1757-L1758

> * It seems to me that adding connection awareness as @mjibson suggested would mean adding columns to the built-in views so they could be filtered on, but that would seem to be a no-no for Postgres compatibility?

Ah, so @mjibson's suggestion was to add a `conn_id` field to the _Materialize-specific_ views, like `mz_views`. (You can create a temporary view that lasts only for the duration of your connection.) Then we could teach the _Postgres views_ (e.g., `pg_views`), which are defined as views over the underlying `mz_views`, to filter by both the current database and the current connection ID. But that query would be invisible to the user; they'd just see a `pg_views` relation that correctly showed them only the views in their current database/connection.

**Comment by necaris** [comment]
> >   * This SQL would have to use a `current_database()` or similar function which doesn't right now exist. Where are functions that can be called at execution time defined? What I could find was `UnmaterializableFunc`, but that is definitely resolved at plan time.
> 
> Yes, precisely! That function does actually exist! 

Apologies for the lack of clarity -- I see that the `current_database()` function does exist, and that other functions in a similar mold could be defined, but they are all resolved when the plan is created. Am I understanding that correctly? So the function that doesn't (yet?) exist is a version that is called at execution time -- I don't see where those might be defined.

> Ah, so @mjibson's suggestion was to add a conn_id field to the Materialize-specific views, like mz_views. (You can create a temporary view that lasts only for the duration of your connection.) Then we could teach the Postgres views (e.g., pg_views), which are defined as views over the underlying mz_views, to filter by both the current database and the current connection ID. But that query would be invisible to the user; they'd just see a pg_views relation that correctly showed them only the views in their current database/connection.

I think I see how that would work -- thank you for clarifying!

**Comment by benesch** [comment]
> Apologies for the lack of clarity -- I see that the `current_database()` function does exist, and that other functions in a similar mold could be defined, but they are all resolved when the plan is created. Am I understanding that correctly? So the function that doesn't (yet?) exist is a version that is called at execution time -- I don't see where those might be defined.

Oh man, I'm so sorry... I see the confusion now. 

> Probably current_database needs to be a function that's banned in indexes, but allowable in views, and replaced at the moment right before we go to build a dataflow.

I did exactly this in #10449. So the issue description is now wrong. The described "naive" approach of...

> adding a `JOIN mz_databases d ON d.id = input.database_id WHERE (d.id IS NULL OR d.name AND current_database())`

...to each `pg_catalog` view should actually work swimmingly now.

The tl;dr is that those `UnmaterializedFunction`s are resolved at (I hope!) exactly the right moment now. Let's say you add a `JOIN` like the above to `pg_views`. The catalog will store a plan like

```
Get mz_views (s1)
Get mz_schemas (s2)
Get mz_databases (s3)
Join [s1, s2, s3] on [...]
Filter UnmaterializedFunction::CurrentDatabase = s3.name
```

where that `UnmaterializedFunction::CurrentDatabase` call is a "hole" that needs to be filled in. When a user shows up and types `SELECT * FROM pg_views`, we'll fill that hole with the value of the `database` session parameter from the user's session, and it should all just work out!

What we'll disallow, then, is the user typing something like:

```
CREATE INDEX ON pg_views;
```

The reason is that we can't maintain an index over a view that contains `UnmaterializedFunction::CurrentDatabase`, because we have no idea _which_ current database to use. (Unlike `SELECT` statements, which can execute plans that are only valid for the one user executing the `SELECT`, `CREATE INDEX` statements need to create indexes on plans that are valid for all users, not just the one user who types the `CREATE INDEX`.)

**Comment by necaris** [comment]
>> Probably current_database needs to be a function that's banned in indexes, but
>> allowable in views, and replaced at the moment right before we go to build a
>> dataflow.

> I did exactly this in #10449. So the issue description is now wrong. 

Ah, now I understand! I was struggling to figure out where plan-time and execution-time differed here, when it _looked_ like all the right values were being pulled out of the `Session`.

> adding a `JOIN mz_databases d ON d.id = input.database_id WHERE (d.id IS NULL
> OR d.name AND current_database())`

I'll give that a go, then!

**Comment by necaris** [comment]
Draft PR open at https://github.com/MaterializeInc/materialize/pull/11292 but would appreciate some help figuring out the appropriate route for testing this. I _imagine_ this should go in an `sqllogictest` but I'm not sure where yet.
