### ISSUE TITLE
Testing DSL for specifying QGM graphs

### ISSUE THREAD

**Issue by wangandi** [MaterializeInc/materialize#10518]
Initial thoughts on this:

A query graph model for unit testing may only need a few boxes, but each box may have multiple `BoxScalarExpr`s, and the `BoxScalarExpr`s may involve multiple layers of nesting and involve many different functions. So I think the highest priority is to support the testing DSL for `BoxScalarExpr`.
* It should be a quick initial task can be to just derive the trait for `MzReflect` for `BoxScalarExpr` and create a test utility method that deserializes a `BoxScalarExpr` from a string. The only thing non-trivial about this is creating a `BoxScalarExpr::Literal`, but the code for this can pretty much be copied from the code for creating a `MirScalarExpr::Literal`.
* There can be a follow on task to figure out and add convenient short-hand syntax for columns. Like how `MirScalarExpr::Column(i)` can be created by specifying `#i`.

The next priority to me would be to enable testing of rewrites and attributes in separate datadriven files because I think it is very useful to allow:
* tests to self document by printing out the image of the "before" so we can see the test case.
* printing out the image of the "after" to compare to the image to the before.

**Comment by wangandi** [comment]
datadriven testing is blocked by #9144

**Comment by antiguru** [comment]
QGM work has been suspended.
