### ISSUE TITLE
Plumb AWS external ID to `AwsConfig::load` directly

### ISSUE THREAD

**Issue by benesch** [MaterializeInc/materialize#10522]
To prevent new constructors of `dataflow_types::sources::AwsCredentials` from thinking it's ok to set `external_id` arbitrarily, rather than to whatever the user specified on the command line.

See: https://github.com/MaterializeInc/materialize/pull/9894/files#r801293531

**Comment by quodlibetor** [comment]
How about a struct (e.g. `CliProvidedExternalId(String)` or `MaterializeProvidedISwearThisDidntComeFromUserSql(String)` instead of the proposed enum?
