### ISSUE TITLE
sql: Support more mathematical operators

### ISSUE THREAD

**Issue by sploiselle** [MaterializeInc/materialize#1053]
[PostgreSQL](https://www.postgresql.org/docs/9.1/functions-math.html) supports a number of mathematical operators that we should support as well, including things like exponentiation.

**Comment by frankmcsherry** [comment]
Exponentiation was added in https://github.com/MaterializeInc/materialize/pull/5885. Are there other specific functions to consider? Trig functions, anything specific?

**Comment by sploiselle** [comment]
Sorry I wasn't clear; my intention was to say that we should support all of the operators on that page. Will turn this into a matrix that explicitly states what work this should cover.
