### ISSUE TITLE
Support all date/time unit aliases

### ISSUE THREAD

**Issue by jkosh44** [MaterializeInc/materialize#10536]
### Feature request

Postgres supports many aliases for each date/time unit. For example both of the following queries give back the same result
```
postgres=# SELECT INTERVAL '2 years 5 days';
    interval    
----------------
 2 years 5 days
(1 row)

postgres=# SELECT INTERVAL '2 yrs 5 days';
    interval    
----------------
 2 years 5 days
(1 row)
```

Materialize however does not support all of the same aliases:
```
materialize=> SELECT INTERVAL '2 years 5 days';
    interval    
----------------
 2 years 5 days
(1 row)

materialize=> SELECT INTERVAL '2 yrs 5 days';
ERROR:  invalid input syntax for type interval: Cannot determine format of all parts. Add explicit time components, e.g. INTERVAL '1 day' or INTERVAL '1' DAY: "2 yrs 5 days"
```

The Postgres date/time units can be found [here](https://github.com/postgres/postgres/blob/ba15f16107bea8a93edc505f3013cd7df4ac90fc/src/include/utils/datetime.h#L48-L63) and all of the aliases can be found [here](https://github.com/postgres/postgres/blob/ba15f16107bea8a93edc505f3013cd7df4ac90fc/src/backend/utils/adt/datetime.c#L166-L233).

I think the only thing needed to fully support these is to extend all of our `FromStr` implementations to include all aliases. Those can be found [here](https://github.com/MaterializeInc/materialize/blob/1f2a17612a33f848daf3e9cc52d19acf3494ee2f/src/repr/src/adt/datetime.rs#L86-L119), [here](https://github.com/MaterializeInc/materialize/blob/1f2a17612a33f848daf3e9cc52d19acf3494ee2f/src/repr/src/adt/datetime.rs#L155-L170), and [here](https://github.com/MaterializeInc/materialize/blob/1f2a17612a33f848daf3e9cc52d19acf3494ee2f/src/sql-parser/src/ast/defs/value.rs#L163-L178).

**Comment by sunisdown** [comment]
I would like to pick it up as my first issue :)

**Comment by jkosh44** [comment]
@sunisdown Go ahead, let me know if you have any questions.

**Comment by sunisdown** [comment]
@jkosh44  I can't trigger the build process because I'm not `member of the build-authorized team`

**Comment by jkosh44** [comment]
> @jkosh44 I can't trigger the build process because I'm not `member of the build-authorized team`

@sunisdown Just replied on the PR itself. Let's add some tests, then I'll send it through the build.
