### ISSUE TITLE
Possible persistence disk usage growth without bounds

### ISSUE THREAD

**Issue by quodlibetor** [MaterializeInc/materialize#10533]
### What version of Materialize are you using?

dev

### How did you install Materialize?

Built from source

### What was the issue?

https://materializeinc.slack.com/archives/C011P87EL2V/p1644335700550929

**Comment by philip-stoev** [comment]
I get unbounded growth in UUID-named files if I have an idle Kafka topic -- https://github.com/MaterializeInc/materialize/issues/10425 . But I do not see the same if there is only system-tables-test persistence going on.

**Comment by ruchirK** [comment]
I see unbounded growth of files if I run latest main with

```
cargo run -- --dev -w 8 --log-file=stderr --timestamp-frequency=100ms --introspection-frequency=100ms --retain-prometheus-metrics=3s
```

but i do not see the same behavior if I run v0.19.0 with the same commands in parallel. BIsecting to try to find a single commit to look at now.

**Comment by ruchirK** [comment]
The bisection is pointing to `c435f1af447b15bee42cf9b3af13b94125375e5b` as the commit where things went south. Still investigating.
