### ISSUE TITLE
panic: Kafka Source persistence not yet implemented for envelope CdcV2  when running the full testdrive with source persisence

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#10586]
### What version of Materialize are you using?

 v0.20.1-dev (d6329387a)

### How did you install Materialize?

Docker image

### What was the issue?

It is not possible to run the full testdrive test with source persistence enabled as it panics with 
```
panic: Kafka Source persistence not yet implemented for envelope CdcV2  prevents running the full testdrive with source persisence
```

As I understand from @ruchirK , this should not be the case. I personally think it should be a source error or an error at `CREATE TIME`.

**Comment by aljoscha** [comment]
I believe this should "work" now. We don't panic for non-implemented envelopes but instead always re-ingest them on restart.

Also, I think implementing proper support for CDCv2 sources is a ways away.
