### ISSUE TITLE
sql: support `lead` and `lag`

### ISSUE THREAD

**Issue by benesch** [MaterializeInc/materialize#10601]
### Feature request

These are window functions that return the preceding and succeeding rows, respectively.

PostgreSQL docs: https://www.postgresql.org/docs/current/functions-window.html

To unblock the remaining two materialize-dbt-utils macros. See: https://github.com/MaterializeInc/materialize-dbt-utils/issues/17

**Comment by morsapaes** [comment]
Fixed in #11891, #11785.
