### ISSUE TITLE
regression: decrease in baseline performance / increase in variance for the KafkaUpsert feature benchmark

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#10605]
### What version of Materialize are you using?

b1b54fb719c8ebbf162c4cb5ad7934618e918bf7

### How did you install Materialize?

Docker image

### What was the issue?

This commit appears to have caused a regression in the KafkaUpsert feature benchmark:

```
commit b1b54fb719c8ebbf162c4cb5ad7934618e918bf7 (HEAD)
Author: Frank McSherry <fmcsherry@me.com>
Date:   Sat Feb 5 15:01:07 2022 -0500

    Hold back source frontiers to durable bindings (#10453)
```

The benchmark numbers have changed as follows:
- the miniumum time it takes to ingest 1M and 10M values from a Kafka upsert source has increased about 10%
- the variance in the results has increased substantially for the scale=6 = 1M

That benchmark scenario:
- uses just a single topic that is fed the same value over and over again
- uses the default number of workers
- can reproduce the problem with the default timestamp frequency as well

By design, the feature benchmark takes the minimum measurement obtained, which may hide the magnitude of the problem. The raw numbers are provided below. As you can see, the numbers with `latest` are quite stable whereas the numbers with `HEAD` are all over the place.

The variance problem is **not reproducible** at higher scales, but the performance regression is:

```
NAME                      |    THIS     |    OTHER    |  Regression?  | 'THIS' is:
----------------------------------------------------------------------------------------------------
KafkaUpsert               |      13.087 |      11.912 |      no       | 9.9 pct   slower
```

### To reproduce:

```
git checkout b1b54fb719c8ebbf162c4cb5ad7934618e918bf7
bin/mzcompose --dev --find feature-benchmark run default --other-tag=v0.19.0 --root-scenario=KafkaUpsert
```

### Relevant log output

```source
with "HEAD":
Measurement: 1.8783347606658936
Measurement: 1.8126232624053955
Measurement: 1.6431152820587158
Measurement: 1.7347991466522217
Measurement: 1.7853507995605469
Measurement: 1.7692022323608398

with the "latest" container/release :
Measurement: 1.4294567108154297
Measurement: 1.4286587238311768
Measurement: 1.432774305343628
Measurement: 1.4312303066253662
```

**Comment by quodlibetor** [comment]
> bin/mzcompose **--dev** --find feature-benchmark run default --other-tag=v0.19.0 --root-scenario=KafkaUpsert

Feature benchmarks probably shouldn't ever be run with non-release binaries? I'm checking now to see if I can reproduce without the `--dev` flag.

**Comment by philip-stoev** [comment]
@quodlibetor  --dev in this context means load the python modules from `requirements-dev.txt`, which includes `scipy` and `numpy`. It does not imply the use of non-release binaries.

**Comment by quodlibetor** [comment]
Interesting. I am getting results around the 5% mark regularly, most recently:

```text
NAME                      |    THIS     |    OTHER    |  Regression?  | 'THIS' is:
----------------------------------------------------------------------------------------------------
KafkaUpsert               |      21.355 |      20.862 |      no       | 2.4 pct   slower
```

As you mentioned, this test is flaky, so I think it's probably fine.

**Comment by elindsey** [comment]
I'm going to close this one out - we need to revisit all the benchmarks once the new ingest pipeline lands
