### ISSUE TITLE
Rows returned with ENVELOPE DEBEZIUM are different between partitioned and non-partitioned topics

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#10661]
### What version of Materialize are you using?

V0.20.0

### How did you install Materialize?

Built from source

### What was the issue?

If a part of `kafka-avro-sources.td` is patched to use multiple partitions:

```
diff --git a/test/testdrive/kafka-avro-sources.td b/test/testdrive/kafka-avro-sources.td
index f2b141188..be4b48c18 100644
--- a/test/testdrive/kafka-avro-sources.td
+++ b/test/testdrive/kafka-avro-sources.td
@@ -477,7 +477,7 @@ $ set new-dbz-schema={
     ]
   }
 
-$ kafka-create-topic topic=new-dbz-data
+$ kafka-create-topic topic=new-dbz-data partitions=5
 
 # We don't do anything sensible yet for snapshot "true" or "last", so just test that those are ingested.
```

it fails as follows:

```
> SELECT * FROM new_dbz
rows didn't match; sleeping to see if dataflow catches up 50ms 75ms 112ms 169ms 253ms 380ms 570ms 854ms 1s 2s 3s 4s
^^^ +++
test/testdrive/kafka-avro-sources.td:498:1: error: non-matching rows: expected:
[["-1", "7"], ["11", "11"], ["14", "6"], ["2", "3"], ["9", "10"]]
got:
[["-1", "7"], ["1", "1"], ["11", "11"], ["2", "3"], ["9", "10"]]
Diff:
extra row: ["1", "1"]
row missing: ["14", "6"]
```

But if `deduplication=ordered` is explicitly used, the test passes again:

```
diff --git a/test/testdrive/kafka-avro-sources.td b/test/testdrive/kafka-avro-sources.td
index f2b141188..73dc03045 100644
--- a/test/testdrive/kafka-avro-sources.td
+++ b/test/testdrive/kafka-avro-sources.td
@@ -477,7 +477,7 @@ $ set new-dbz-schema={
     ]
   }
 
-$ kafka-create-topic topic=new-dbz-data
+$ kafka-create-topic topic=new-dbz-data partitions=5
 
 # We don't do anything sensible yet for snapshot "true" or "last", so just test that those are ingested.
 
@@ -492,6 +492,7 @@ $ kafka-ingest format=avro topic=new-dbz-data schema=${new-dbz-schema} timestamp
 
 > CREATE MATERIALIZED SOURCE new_dbz
   FROM KAFKA BROKER '${testdrive.kafka-addr}' TOPIC 'testdrive-new-dbz-data-${testdrive.seed}'
+  WITH (deduplication='ordered')
   FORMAT AVRO USING SCHEMA '${new-dbz-schema}'
   ENVELOPE DEBEZIUM
```

@petrosagg thinks that this may be a bug.

**Comment by philip-stoev** [comment]
There is something fishier going on: this Nightly run: https://buildkite.com/materialize/nightlies/builds/668#98c9b920-fdbd-455e-afe8-4a1af3d74a83/3222

has the following failure:

```


> SELECT * FROM pg_dbz
--
  | rows didn't match; sleeping to see if dataflow catches up 50ms 75ms 112ms 169ms 253ms 380ms 570ms 854ms 1s 2s 3s 4s 6s 10s 890ms
  | github-5668.td:103:1: error: non-matching rows: expected:
  | [["baz"], ["hello,"], ["world!"]]
  | got:
  | [["baz"], ["hello,"], ["too late"], ["world!"]]
  | Diff:
  | extra row: ["too late"]

```
Which seems to indicate that a record "too late" that should have been discarded was not . And this particular source already has `WITH (deduplication = 'ordered') `

I am patching `github-5668.td` and `kafka-avro-sources.td` to explicitly use `partitions=1` so that they can run in the Nightly partitions=5 build. Please consider removing the `partitions=1` in the tests that no longer need it once this bug is fixed.

**Comment by philip-stoev** [comment]
Apparently Debezium ingestion correctness can only be ensured if the messages have an explicit key, so that all messages about a particular record fall into the same partition. All the failures above were in `kafka-ingest` operations that did not provide an explicit key.

All the tests have been adjusted to use `partitions=1` explicitly so that they can also run in the Nightly partitions 5 test.

**Comment by aljoscha** [comment]
Wouldn't it be better to instead add keys to the data we use in tests. With `partitions=1` we remove coverage for multi-partition topics, it seems.
