### ISSUE TITLE
S3 download objects in parallel

### ISSUE THREAD

**Issue by quodlibetor** [MaterializeInc/materialize#10717]
### Feature request

Currently each S3 source can only download objects one at a time, in serial. But it is known that S3 gets maximal throughput if you download multiple objects in parallel.

**Comment by andrioni** [comment]
Note: you can also parallelize the download of a single object by using [byte-range fetches](https://docs.aws.amazon.com/whitepapers/latest/s3-optimizing-performance-best-practices/use-byte-range-fetches.html), which is something that we should consider as well for larger files (e.g. recommended Parquet file sizes for S3 are usually around 64MB).

**Comment by benesch** [comment]
Closing as stale, as we no longer support S3 sources.
