### ISSUE TITLE
Remove `Table` special-cases throughout coord/storage

### ISSUE THREAD

**Issue by frankmcsherry** [MaterializeInc/materialize#10720]
Tables are currently a special case of source that 1. one can insert into, and 2. must be immediately materialized. The first part makes total sense, and the second part is an artifact of us not knowing how best to maintain tables other than via an `Arrangement`.

Going forward, we will want to have tables maintained in storage, likely "persistently" as in https://github.com/MaterializeInc/materialize/issues/6155. We have abstractions like `Stash` that allow this today. Even failing that, a `Vec<(Row, Time, Diff)>` dangled off of `StorageState` would suffice, without having to solve "table persistence".

With such a change, we can decouple Table instantiation from index building, which removes some amount of complexity from the coordinator (which builds this up as a transaction). We could also advance the design discussion around `CREATE TABLE` in the platform world, where the "automatic materialization" introduces a false coupling to a compute instance, that I think we want to avoid.

cc: @mjibson

**Comment by frankmcsherry** [comment]
A specific concrete ask is that the table `SourceConnector` should be able to be used more than once, as there could be dataflows on independent compute instances that want to read the table. At the moment, re-use of this source connector probably results in some form of error condition, as it is only meant to be used in the dataflow that builds an index on it, and the index used from that point onward.

**Comment by frankmcsherry** [comment]
Another potential implementation is to leave the table dataflow construction in place, resulting in an arrangement, but to have this happen as a result of `CreateSource` rather than "on use of `SourceConnector::Local`". Uses of the source connector would then hook up to the in memory arrangement, which could be streamed out or for bonus points presented as the arrangement that it is.

The main difference in this implementation is that the coordinator needn't create a dataflow immediately after creating the source, and the source could be used multiple times. The downside is a potential lack of clarity around the availability of the underlying arrangement, but as soon as STORAGE and COMPUTE are not co-located this goes away anyhow. That last point is up for discussion, but if folks are using tables for high-volume data storage, we explicitly asked them not to and ... yeah.

**Comment by danhhz** [comment]
Using a Stash (or Vec) and then swapping in src/persist later makes sense to me. Can you go into a bit more detail on what the ADAPTOR/STORAGE/COMPUTE interfaces look like here? Concretely, I'd love an example of what the API traffic looks like when a table is created+given some data in a SQL transaction including other tables+used in a dataflow. Something like the following but...y'know...not my wild speculation :)

```
ADAPTOR to STORAGE: CreateTable -> StorageId(1);
ADAPTOR to STORAGE: InsertTableData(vec![(StorageId(1), <foo data>)]) -> Ok(());
ADAPTOR to STORAGE: CreateTable -> StorageId(2);
ADAPTOR to STORAGE: InsertTableData(vec![(StorageId(1), <bar data>), (StorageId(2), <baz data>)]) -> Ok(());
ADAPTOR to STORAGE: InsertTableData(vec![(StorageId(2), <qux data>)]) -> Err("s3 is on fire");
ADAPTOR to COMPUTE: CreateDataflow(ComputeInstance(A), StorageId(1).concat(StorageId(2)).map(...).arrange()...);
ADAPTOR to COMPUTE: CreateDataflow(ComputeInstance(B), StorageId(1).concat(StorageId(2)).map(...).arrange()...);
```

**Comment by frankmcsherry** [comment]
The existing API is `Controller` whose has methods (in `controller.rs`) to create tables (under `create_source`), drop tables (under `drop_source`), to `table_insert`, and `advance_all_table_timestamps` which probably wants to change to at least allow table-specific frontier advances. The coordinator is currently written in terms of these, but .. might need some help as we force it to reason about things it hasn't previously expected.
