### ISSUE TITLE
qgm: wrong result with aggregates, dataflow graph missing branch dealing with empty collections

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#10800]
### What version of Materialize are you using?

v0.20.1-dev (ca980c050)

### How did you install Materialize?

Built from source

### What was the issue?

With QGM enabled, the plan is missing the branch that deals with empty collections:

```
materialize=> explain SELECT  COUNT( * )  FROM t1  ;
           Optimized Plan           
------------------------------------
 %0 =                              +
 | Get materialize.public.t1 (u289)+
 | Project ()                      +
 | Reduce group=()                 +
 | | agg count(true)               +
```

so, the result is incorrect:
```
materialize=> SELECT  COUNT( * )  FROM t1  ;
 count 
-------
(0 rows)
```

should have returned zero.

**Comment by aalexandrov** [comment]
At first glance the problem is that the QGM path does not generate the SQL-specific machinery for handling empty aggregates when lowering to MIR.

<table style="text-align: center;">
  <thead>
  <tr>
    <td>Decorrelated Plan (+QGM)</td>
    <td>Decorrelated Plan (-QGM)</td>
  </tr>
  </thead>
  <tbody>
  <tr>
    <td><img src="https://user-images.githubusercontent.com/1071946/155317146-6e82c289-c043-4c64-9d91-feef777190fa.svg" alt="decorrelated-plan+qgm" style="width: 100%" /></td>
    <td><img src="https://user-images.githubusercontent.com/1071946/155317154-f2311d60-b13d-4082-ba28-f11bf1c97ea7.svg" alt="decorrelated-plan-qgm" style="width: 100%" /></td>
  </tr>
  </tbody>
</table>
