### ISSUE TITLE
Add something like a `stream_now()` function for dataflows

### ISSUE THREAD

**Issue by quodlibetor** [MaterializeInc/materialize#1080]
In #1020 we created some `now()` functions that are only really meaningful for _queries_, but when creating views we believe that we will want to be able to do something like:

```sql
CREATE VIEW recent_transactions AS
SELECT * FROM transactions
WHERE transaction.last_update_time > (streaming_now() - INTERVAL '5 minutes')
```

There are logs of complications around this, though.

**Comment by benesch** [comment]
Can we close this in favor of #2439, or vice-versa?

**Comment by rjnn** [comment]
I’m in favor of #2439, as it has specific product direction (what we need to expose is a source, not a function) but I’m biased.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by benesch** [comment]
I agree! And I think it gives as much power as the `stream_now()` function does here. @quodlibetor, what say you?

**Comment by rjnn** [comment]
Closing in favor of #2439.

**Comment by quodlibetor** [comment]
Ah yeah I support this closure.
