### ISSUE TITLE
Unify `Controller::drop_foo` with `Controller::allow_compaction`

### ISSUE THREAD

**Issue by frankmcsherry** [MaterializeInc/materialize#10818]
The controller provides methods that allow users to independently "allow compaction" of collections, and to "drop" the collections. Allowing compaction is equivalent to downgrading a read capability, and I assert that dropping a collection is very similar to dropping a read capability. We could unify the two, and make `fn drop_foo` commands turn in to `allow_compaction([])` commands.

The benefit of doing this is a reduction in complexity in `Controller` and its per-collection state / state machine. Retaining the distinction requires us to track pending drops that are blocked on compaction from others, and somewhat confuses the issue of who gets to be the authority on whether a collection is *dropped* in a way that capabilities resolve for whether a collection can be read (there can be multiple capabilities; it is fine).

This removes the distinction between a collection that is compacted to `[]` and a dropped collection, which might be important to retain if we want to be able to close out collections without e.g. dropping introspection information about them. However, it seems right that the STORAGE and COMPUTE layers should be able to e.g. reclaim resources when there are no readers for a collection. They don't have to, but they should be able to. So, much of the response to `drop_foo` would/should be an acceptable response to `allow_compaction([])`.

I think this is probably fine, as long as the `Controller` remains the source of truth on the information we might want to retain (e.g. source creation parameters, other metadata not housed in the data plane).

**Comment by benesch** [comment]
@frankmcsherry did you complete this to your satisfaction in #10842?

**Comment by frankmcsherry** [comment]
I complete this to my satisfaction!
