### ISSUE TITLE
storage/sinks: support writing metadata to Kafka headers

### ISSUE THREAD

**Issue by nmeagan11** [MaterializeInc/materialize#10859]
### Feature request

Relevant Use Case and Internal Discussion: https://materializeinc.slack.com/archives/C01CFKM1QRF/p1645606997350319

**Comment by bkirwi** [comment]
#14678 (if merged) will introduce a `mz-timestamp` header on kafka messages that go out to the sink. We could also easily add headers if we wished for the source collection name, the uid of the sink, or the environment id of the materialize instance if/when that gets threaded through.

**Comment by bkirwi** [comment]
Or perhaps we'll use `materialize-timestamp` for the header instead, for consistency with the topic naming.

**Comment by rjnn** [comment]
It would be great if we could have them set the name of the column using a field rather than just going with `materialize-timestamp`. Separately, this isn't documented in the reference docs.

**Comment by sploiselle** [comment]
@bkirwi this worth keeping?

**Comment by bkirwi** [comment]
> It would be great if we could have them set the name of the column using a field rather than just going with materialize-timestamp.

Just to clarify: this is not set as a column at all; it's a header on the Kafka message. (Kafka headers are similar to HTTP headers.)

I don't think it's useful to set the name of a header; it will never collide with any user data. It's conceivable that a user might want this to be promoted to an ordinary data field, but I'm not aware of any use case. @rjnn, any context to share on why this popped up on your radar?

> Separately, this isn't documented in the reference docs.

We should fix this!

> this worth keeping?

I think it's worth getting documentation on the existing header before closing. I think we could decide not to do any other headers for now, only adding them if users ask. Putting metadata as part of the user-facing schema sounds like a larger change and may be worth it's own ticket.
