### ISSUE TITLE
JWK-based authentication: log the reason for failure

### ISSUE THREAD

**Issue by antifuchs** [MaterializeInc/materialize#10879]
### Feature request

Right now, we silently reject login attempts, and it's great to be silent to the person requesting the login! But it would be great if the server could log that a login attempt failed, and why it failed. I'd love to see the following things in the log:

* reason for failure, as close as we can get it (mismatching JWK, tenant, email?)
* remote IP address

**Comment by benesch** [comment]
Fixed in MaterializeInc/materialize#11807.
