### ISSUE TITLE
regression: ORDER BY ... LIMIT no longer executed optimally by the FastPath 

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#10884]
### What version of Materialize are you using?

18562fb90462deac0984b247ff4738dd6837d66a

### How did you install Materialize?

Docker image

### What was the issue?

The `FastPathOrderByLimit` benchmark shows a massive performance regression:

```
FastPathOrderByLimit      \|      23.259 \|       0.333 \|    !!YES!!    \| 69.9 TIMES slower
```

Bisection reports this is the revision this happened at:

```
18562fb90462deac0984b247ff4738dd6837d66a is the first bad commit
commit 18562fb90462deac0984b247ff4738dd6837d66a
Author: Brennan Vincent <brennan@umanwizard.com>
Date:   Wed Feb 23 10:05:07 2022 -0500

    Move unrolling of peek multiplicities to coordinator. (#10673)
    
    This makes dataflow return `Vec<(Row, Diff)>`, rather than the unary `Vec<Row>` as it did before. The former representation is unrolled to the latter on the coordinator, after receiving the response in `implement_fast_path_peek`.
```

My initial thought is that too much sorting is happening before just a LIMIT number of records are returned.  Maybe this part:

https://github.com/MaterializeInc/materialize/pull/10673/files#:~:text=if%20let%20Some(limit)%20%3D%20self,offset_nth_row%2C%20offset_kth_copy)%20%3D%20self.find_offset(%26rows)%3B

is what causes more sorting to happen than it did before?

**Comment by umanwizard** [comment]
This is in unreleased code, so I'm marking this as release blocker, rather than P1.
