### ISSUE TITLE
regression: Failure during snapshot not retried properly, source never advances

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#10938]
### What version of Materialize are you using?

v0.19.1-dev (89f9dfdc2)

### How did you install Materialize?

Docker image

### What was the issue?

The pg-cdc-resumption test has started to fail in its `restart_pg_during_snapshot` subtest:

```
verify-data.td | 1m 0s
-- | --
  | > SELECT COUNT(*) = 500000 FROM t1;
  | rows didn't match; sleeping to see if dataflow catches up 50ms 75ms 112ms 169ms 253ms 380ms 570ms 854ms 1s 2s 3s 4s 6s 10s 15s 16s
  | verify-data.td:10:1: error: executing query failed: db error: ERROR: At least one input has no complete timestamps yet: [User(28)]: ERROR: At least one input has no complete timestamps yet: [User(28)]
  | \|
  | 9 \|
  | 10 \| > SELECT COUNT(*) = 500000 FROM t1;


```

This output essentially means that absolutely no data was received from Postgres whatsoever and the test waited for 60 seconds for progress to be made.

Git bisect reports that the test started failing after the following commit. It may be that the faster speed of `COPY` caused the timing of the events to change.

```
89f9dfdc20e4547e90ca97599089a73553b6b365 is the first bad commit
commit 89f9dfdc20e4547e90ca97599089a73553b6b365
Author: Paul Hemberger <paul@materialize.com>
Date:   Mon Feb 7 08:42:02 2022 -0500

    pg-cdc: switch from `SELECT *` to `COPY TO` for faster initial loading (#10299)

```

Simplified test coming up shortly.

### Relevant log output

No errors in Mz log

**Comment by philip-stoev** [comment]
To reproduce

1. Clone `gh10938-test` from `git@github.com:philip-stoev/materialize.git`
2. Start some unrelated background load
```
while bash -c "cargo clean ; cargo build --release" ; do : ; done
```
3. Run the problematic test in a loop:
```
bash -e -c 'for i in $(seq 1 10) ; do bin/mzcompose --find pg-cdc-resumption down -v ; bin/mzcompose --find pg-cdc-resumption run default ; done'
```

4. Wait for the test to fail.

The test in this branch is a simplified version of the specific scenario within `pg-cdc-resumption` that is failing. It has been modified to **not** use Toxyproxy in any way, it just restarts PG immediately after creating the Mz pg source.

**Comment by philip-stoev** [comment]
@petrosagg  @pH14

**Comment by philip-stoev** [comment]
I am putting this as a P1, as it is a regression.

**Comment by pH14** [comment]
Hmm interesting... my initial thought was that we're problematically swallowing Errs here https://github.com/MaterializeInc/materialize/blob/23f42733a4c5630a549db48fdd7c6674b618b484/src/dataflow/src/source/postgres.rs#L256 (which still seems to be the case, but not the causal issue here)

but it actually looks like we're waiting indefinitely on `reader.next().await` after the postgres connection initially shuts down. Will dig into what's happening here under the hood

**Comment by pH14** [comment]
Definitely perplexing. I can repro this locally when running via Docker `bin/mzcompose --find pg-cdc-resumption down -v ; bin/mzcompose --find pg-cdc-resumption run default`, and the client gets stuck waiting on its receiver indefinitely: https://github.com/MaterializeInc/rust-postgres/blob/5ae9ff03d1b8085fe026c7d179226b1d169ef6c6/tokio-postgres/src/client.rs#L47 From what I can tell, at no point does the `CopyOutStream` get any error, so it just hangs. The replication stream resumes fine separately, so it's specifically the copy out stream that gets jammed.

Unfortunately I have not been able to repro running Materialize directly. When I do so, and kill Postgres mid-copy, it immediately receives an error and retries as one would hope.
