### ISSUE TITLE
sql: introduce a `CoercibleScalarType` enum

### ISSUE THREAD

**Issue by benesch** [MaterializeInc/materialize#10934]
We currently don't handle coercion of `ROW` literals correctly in some contexts. See #8597 and #10422.

#10868 is one attempt to fix this by changing the typing of `CoercibleScalarType` so that a `ROW` literal is typed as `Some(ScalarType::Record { ... })`.  I don't think this is quite right, though!

Here's the background. PostgreSQL has an explicit `unknown` type that it uses throughout planning. It slowly converts expressions from `unknown` type to known types during planning... usually. Sometimes an unknown type will slip through, and the execution pathway is resilient to that. Unknown types get special coercion behavior; e.g., a string literal has type `unknown` so that it can be freely cast to any type.

Requiring every part of the system to be prepared for `unknown` types is a very C way of doing things. We've opted instead to represent `unknown` types with proper typestates. `unknown` types only exist for a brief moment in the planner, and then are transformed away.

`CoercibleScalarExpr` is the way we do this. Any type of expression that _would_ be typed as `unknown` in PostgreSQL is instead held as a `CoercibleScalarExpr`; this makes the transformation to a known `ScalarExpr` explicit. Forgetting to coerce a `CoercibleScalarExpr` becomes a compile time error of `materialized`.

We currently use `Option<ScalarType>` to represent the type of a `CoercibleScalarExpr`. `None` is used to mean "unknown" and `Some` is used to mean "known". I think we instead need to expand this out into:

```rust
enum CoercibleScalarType {
    Unknown,
    Record,
    Known(ScalarType),
}
```

The idea is that `ROW` literals get typed as their own special `unknown`-like type called `CoercibleScalarType::Record`. PostgreSQL causes this type `record`. Note that we do _not_ have an exact analog to `record`; our `ScalarType::Record { custom_oid: None, ... }` is not quite as squishy as the PostgreSQL `record` psuedotype. `ScalarType::Record` without an OID behaves _exactly_ like a named composite type in PostgreSQL except that it lacks a name. Whereas the `record` pseudotype has some notable differences from a proper composite type, like the fact that its type category is `TypeCategory::Pseudo` rather than `TypeCategory::Composite`.

This latter point is actually exactly what makes `coalesce(row(1, 2), row(1, 2)::some_equivalent_named_type)` fail. The first expression has `TypeCategory::Pseudo`, while the second expression has `TypeCategory::Composite`.

I've teed up this work with #10911. If we add the `CoercibleScalarType` enum as described above, then it will be easy to match PostgreSQL's behavior in `guess_best_common_type` by declaring that `CoercibleScalarType::Record`'s type category is `TypeCategory::Pseudo` while `CoercibleScalarType::Known(ScalarType::Record { .. })`'s type category is `TypeCategory::Record`.

**Comment by benesch** [comment]
cc @pH14 @sploiselle

**Comment by sploiselle** [comment]
Came up with a diff I'm putting at the bottom that does a lot of this work. The
idea being that you look at `ScalarType::Record` with custom elements as a
`composite` type and others as `record` types.

Came up with this because I couldn't figure out what type `ROW` expressions
should ultimately resolve to if not `ScalarType::Record { custom_oid: None, ...
}`.

Seems like `record` is not quite a pseudo-type in the way that parameter types
are. For example, `pg_get_keywords` and `information_schema._pg_expandarray`
[return
`record` itself](https://github.com/postgres/postgres/blob/master/src/include/catalog/pg_proc.dat):

```
sean=# SELECT pg_typeof(pg_get_keywords());
 pg_typeof 
-----------
 record
 ...

SELECT pg_typeof(information_schema._pg_expandarray(ARRAY[1]::int[]));
 pg_typeof 
-----------
 record
```

You can also define `record` as a valid return type from UDFs:

```
sean=# CREATE FUNCTION get_record() RETURNS record AS '
sean'#     SELECT ROW(1);
sean'# ' LANGUAGE SQL;
```

Seems like its pseudo-ness is simply that it allows ~any schema within it.
Contrasts clearly with the idea of a composite type, which has a defined schema.

To reinforce this, it isn't possible to create a `record` with a specific schema
afaict, i.e. `record` doesn't accept typmods.

```
sean=# select row(1)::record(int);
ERROR:  type modifier is not allowed for type "record"
```

However, I did find that you cannot use `record` as a component in a schema:

```
sean=# create view record_view as select pg_get_keywords();
ERROR:  column "pg_get_keywords" has pseudo-type record

sean=# create view row_view as SELECT ROW(1) AS f1;
ERROR:  column "f1" has pseudo-type record
```

[We currently support DDL using `record`](https://github.com/MaterializeInc/materialize/blob/main/test/upgrade/check-from-any_version-row.td) but shouldn't.

PG prohibits this using [`CheckAttributeType`](https://github.com/postgres/postgres/blob/ad4f2c47de440cdd5d58cf9ffea09afa0da04d6c/src/backend/catalog/heap.c#L513), which ensures `record` types never make it into any object's schema. Makes sense if you assume `record` means "no fixed schema."

I hear the apprehension about these "unknown" types slipping into places we
don't want them, but I think that we already need to add checks to ensure that
they don't get through.

Using this diff, you can e.g. solve the `coalesce` issue:

```diff
diff --git a/src/coord/src/catalog.rs b/src/coord/src/catalog.rs
index a5880f27c..3a9c15098 100644
--- a/src/coord/src/catalog.rs
+++ b/src/coord/src/catalog.rs
@@ -2643,13 +2643,7 @@ impl ExprHumanizer for ConnCatalog<'_> {
                 custom_name: Some(name),
                 ..
             } => name.clone(),
-            Record { fields, .. } => format!(
-                "record({})",
-                fields
-                    .iter()
-                    .map(|f| format!("{}: {}", f.0, self.humanize_column_type(&f.1)))
-                    .join(",")
-            ),
+            Record { .. } => format!("record"),
             PgLegacyChar => "\"char\"".into(),
             ty => {
                 let pgrepr_type = mz_pgrepr::Type::from(ty);
diff --git a/src/sql/src/func.rs b/src/sql/src/func.rs
index de1924d61..35c6cddb4 100644
--- a/src/sql/src/func.rs
+++ b/src/sql/src/func.rs
@@ -64,6 +64,7 @@ impl<'a> fmt::Display for FuncSpec<'a> {
 pub enum TypeCategory {
     Array,
     Bool,
+    Composite,
     DateTime,
     List,
     Numeric,
@@ -110,7 +111,17 @@ impl TypeCategory {
             | ScalarType::String
             | ScalarType::Char { .. }
             | ScalarType::VarChar { .. } => Self::String,
-            ScalarType::Record { .. } => Self::Pseudo,
+            ScalarType::Record {
+                custom_name,
+                custom_oid,
+                ..
+            } => {
+                if custom_name.is_some() || custom_oid.is_some() {
+                    Self::Composite
+                } else {
+                    Self::Pseudo
+                }
+            }
             ScalarType::Map { .. } => Self::Pseudo,
         }
     }
@@ -138,7 +149,7 @@ impl TypeCategory {
     /// ```
     pub fn preferred_type(&self) -> Option<ScalarType> {
         match self {
-            Self::Array | Self::List | Self::Pseudo | Self::UserDefined => None,
+            Self::Array | Self::Composite | Self::List | Self::Pseudo | Self::UserDefined => None,
             Self::Bool => Some(ScalarType::Bool),
             Self::DateTime => Some(ScalarType::TimestampTz),
             Self::Numeric => Some(ScalarType::Float64),
```

LMK if you see any issues with this approach.

**Comment by benesch** [comment]
I'm still a bit sketched out, but if I understand correctly, your contention is that a value of "pseudo" type `record` _can_ actually exist, unlike values of e.g. `anycompatible`. I find that argument quite compelling. I'm not 100% on it, but if you're up for owning the fallout let's do it! (I can't find anything wrong with the approach; I'm just worried that I'm missing something!)

**Comment by benesch** [comment]
What do we need `custom_name` for, btw? To make `pg_typeof` display the right name, or something? 

@sploiselle did you ever write up that issue for type global IDs in platform? If `custom_name` exists for the reasons that I think it does, it'd be great if part of the type global ID work replaced _both_ `custom_name` and `custom_oid` with a single `custom_id` field on `ScalarType::Record`, with the conversion to name/OID somewhere in SQL/coord land.

**Comment by sploiselle** [comment]
Yeah, exactly!

```
sean=# select pg_typeof(1::anycompatible);
 pg_typeof 
-----------
 integer

sean=# select pg_typeof(row(1)::record);
 pg_typeof 
-----------
 record
```

**Comment by benesch** [comment]
🎉 

Are you up for PR'ing that first to reduce the weight of #11453? Will it also fix #8597/#10422/#10868? That's so cool if so.

**Comment by benesch** [comment]
If the tininess of the diff you posted is in fact _dependent_ on #11453... no sweat!

**Comment by sploiselle** [comment]
@benesch that work is identified in #11344. I think that `custom_name` is a little bogus and should probably register a composite type in the catalog, which we can refer to with an OID. It's used in a few spots to generate the type of a record for schemas we inherit from sources, but I don't think it _has_ to be used.

re: landing this diff, I'll have to look in the morning but I'd clearly prefer to get it out from underneath the polymorphic type refactor.

**Comment by benesch** [comment]
> @benesch that work is identified in #11344. I think that `custom_name` is a little bogus and should probably register a composite type in the catalog, which we can refer to with an OID. It's used in a few spots to generate the type of a record for schemas we inherit from sources, but I don't think it _has_ to be used.

Oho, `custom_name` _already_ exists. D'oh. Apparently I even suggested it: https://github.com/MaterializeInc/materialize/pull/5028#issuecomment-763944290

Thanks for the pointer to the issue link. I'll go drop a note there!

**Comment by sploiselle** [comment]
Fixed in https://github.com/MaterializeInc/materialize/pull/10868
