### ISSUE TITLE
sql: support new polymorphic types

### ISSUE THREAD

**Issue by benesch** [MaterializeInc/materialize#10935]
### Feature request

PostgreSQL v13 introduced some new [polymorphic types](https://www.postgresql.org/docs/current/extend-type-system.html#EXTEND-TYPES-POLYMORPHIC):

  * `anycompatible`
  * `anycompatiblearray`
  * `anycompatiblenonarray`
  * `anycompatiblerange`
  * `anycompatiblemultirange`

These are like the existing polymorphic types that don't mention `compatible` in their names, except that they don't constrain their arguments to be literally identical, but only to share a common type that both arguments can be promoted to (as determined by `guess_best_common_type`).

Many existing functions in PostgreSQL were redefined to take e.g. `anycompatible` where they used to take `any`. I think our [`resolve_polymorphic_types`](https://github.com/MaterializeInc/materialize/blob/c608ae71b4814f53ea9aff75aa39fbaa5ce4084f/src/sql/src/func.rs#L626) function is understandably a bit confused on this point, and is currently a hybrid of `compatible` and non-`compatible` behavior.

I'm also pretty thoroughly confused by our breakdown of types into "custom", "built-in", "complex", and "simple": https://github.com/MaterializeInc/materialize/blob/c608ae71b4814f53ea9aff75aa39fbaa5ce4084f/src/sql/src/func.rs#L554-L560

I think quite a bit of this complexity can vanish by properly implementing the new `compatible` polymorphic types. Then we won't need special handling to allow e.g. `int4 list` and `int4_list_as_custom_type` to be interchanged; we can just use the new `compatible` polymorphic types in function signatures. 

cc @sploiselle

**Comment by sploiselle** [comment]
@benesch lol sorry about that

**Comment by benesch** [comment]
All good! Classic GitHub.
