### ISSUE TITLE
Add more documentation around what our logs mean

### ISSUE THREAD

**Issue by ruchirK** [MaterializeInc/materialize#1094]
This probably only makes sense as an internal doc for now

Right now we have 13 different logs (e.g. logs_parks, logs_arrangement, etc) and its hard to suss out what information they have / whether they have the correct semantics that we expect them to

for example: you would think that logs_dataflows would have one line for each dataflow, but it actually has lines for all views in a dataflow so if a dataflow had no views it wouldn't be logged and conversely if it had multiple views (unclear if thats possible it would be logged multiple times)

I think its also important to note that some of the logs are directly populated from the materialize repo and thus may be subject to a lot of change, but others seem to come from the timely / differential codebases and may be more stable

**Comment by benesch** [comment]
The "System catalog" docs now cover this! https://materialize.com/docs/sql/system-catalog/#details
