### ISSUE TITLE
row_num - Document limitations

### ISSUE THREAD

**Issue by krishmanoh2** [MaterializeInc/materialize#10944]
### What pages are affected?

https://materialize.com/docs/sql/functions/

### What needs to be changed or added?

Materialize implementation of row_num can lead to higher than expected memory usage. Recommend that anyone trying this function out understand the limitations.

**Comment by benesch** [comment]
We've done a comprehensive overhaul of window functions. Part of that work will be explaining the remaining limitations. See #16367.
