### ISSUE TITLE
Improve robustness of timestamp binding compaction

### ISSUE THREAD

**Issue by frankmcsherry** [MaterializeInc/materialize#10957]
Our `sqlite` timestamp binding compaction uses the following logic:
```rust
        let latest_not_beyond_compaction: Option<Timestamp> = self
            .inner
            .prepare_cached(
                "SELECT max(timestamp) FROM timestamps WHERE sid = ? AND timestamp <= ?",
            )?
            .query_row(params![SqlVal(&source_id), frontier], |row| row.get(0))?;

        if let Some(latest_not_beyond_compaction) = latest_not_beyond_compaction {
            let result = match self
                .inner
                .prepare_cached("DELETE FROM timestamps WHERE sid = ? AND timestamp < ?")?
                .execute(params![SqlVal(&source_id), latest_not_beyond_compaction])
            {
                Ok(_) => Ok(()),
                Err(err) => Err(err.into()),
            };

            result
        } else {
            Ok(())
        }
```
It selects the maximum timestamp less or equal to the input argument, and deletes bindings at strictly lower timestamp. However, there are bindings for each of various subdivisions of the `sid` collection: kafka topics have multiple parts, for example. Instead, I believe we should use the minimum across maximum values for parts (or whatever the subdivisions are).

The current thinking is that this doesn't manifest as a bug at present because we ensure that some other invariants are maintained on the data, relating the skew of the bound timestamps in each of the parts.

**Comment by benesch** [comment]
@petrosagg did your timestamp binding refactor address this?

**Comment by petrosagg** [comment]
Yes, we are compacting correctly now :)
