### ISSUE TITLE
Update frontier management in the coordinator

### ISSUE THREAD

**Issue by frankmcsherry** [MaterializeInc/materialize#10953]
The coordinator's frontier tracking logic dates back to the time when it was the source of truth on this information. Currently, the `Controller` presents the most current information known to the Compute and Storage layers, and is able to handle several of the tasks the coordinator has historically managed. For example, of:

1. Acquire read capabilities to issue queries, start transactions,
2. Downgrade read capabilities in response to write frontiers (`upper`) advancing,
3. Hold back read capabilities for inputs that sinks have dependencies on,
4. Control the advance of read capabilities as a function of the read and write timestamps.

The third of these is already being performed by the controller, and the second could easily be done as well (with some invention of compaction policies). The first and fourth are related, and the coordinator should probably choose either and do it. The trade off is that if the controller accepts (2.) the coordinator loses its implied read capabilities, and could be surprised that collections are compacted. To rectify that, the coordinator would need to do (4.) which is code that does not yet exist.

**Comment by mjibson** [comment]
I am not able to come up with an example of why coord would want 4. I'm in favor if 1, where coord can show up and say "i'd like to read from X,Y,Z, please give me a valid read capability at a timestamp of your choosing until I release it". Maybe the timestamp can come with some minimum requirement also (for linearizability). But going back, what problem does 4 solve?

**Comment by frankmcsherry** [comment]
I think 4. solves the problem of:
ADAPTER: "Please create Source(foo) for me".
STORAGE: "Ok".
ADAPTER: "Please create view SELECT COUNT(*) FROM foo for me".
COMPUTE: "Ok".
ADAPTER: "I would like to read either of these"
BOTH: "We compacted them up until next week, sorry".

**Comment by mjibson** [comment]
Is that a description that compute and storage would, on their own, prefer to compact as much as possible all the time? And we must decide on some layer to be in charge of holding things back, and that layer could be adapter?

**Comment by frankmcsherry** [comment]
I think that is right. At least, in the absence of any other controls, STORAGE and COMPUTE aren't sure what the collections they manage need to provide in terms of valid times. Should they never compact things, hold stuff open for a second, a minute, a week. They have their own internal takes on this, for example COMPUTE prevents compaction of dataflow inputs for the same reason coord does with EOS sinks, but I anticipate that ADAPTER wants to express some constraints along the lines of "Our current timeline timestamp is `time`; please don't compact past it or I may not be able to answer questions without advancing `time` to whatever out-of-control `since` frontier you compacted to".

**Comment by frankmcsherry** [comment]
Flagging that https://github.com/MaterializeInc/materialize/pull/10999 is up for review, which is meant to be the basis of allowing the coordinator to start doing less explicit frontier management. I haven't gone as far as actually removing anything from the coordinator, but now that it exists one could hop in and see what happens if we start to use it (and, I expect, complain when it turns out the interface is not yet what would be best).

**Comment by frankmcsherry** [comment]
I believe this is now "fixed" in that the coordinator maintains a compaction policy and as many transaction read holds as it would like.
