### ISSUE TITLE
Modernize coordinator use of `Controller`

### ISSUE THREAD

**Issue by frankmcsherry** [MaterializeInc/materialize#10955]
Historically the coordinator has interacted with `dataflow` via a shared channel. The `Controller` is a "smart" shared channel that maintains reference state for read and write frontiers, source description, which identifiers are available in storage and in compute instances. It is meant to be a useful source of truth for this information, and the coordinator could remove some of its own state that mirrors this data.

The task is complicated by the absence of transactional updates to `Controller`, so e.g. transactions that create sources and then use them in dataflows (traditionally, how we create tables) would find references to that source missing until the `create_source` command is issued, which the coordinator does not want to do within a transaction. The `Controller` may eventually present a transactional facade, but in the meantime the coordinator could start to pivot less sensitive bits of its state away if it is non-erroring to do so.

**Comment by mjibson** [comment]
I don't see any members of the coord struct that have read or write frontiers, source descriptions, or available storage and compute identifiers. Is this done?

**Comment by frankmcsherry** [comment]
I think maybe let's wait for @benesch to devolve "enabled indexes" to `ComputeController` and then yes!
