### ISSUE TITLE
Coordinator should explicitly pilot storage collection compaction

### ISSUE THREAD

**Issue by frankmcsherry** [MaterializeInc/materialize#10954]
Storage collections, including sources and tables, are not explicitly compacted by the coordinator. Instead, their presence in a running dataflow drives their compaction, through the return of write frontiers (`upper`) and the application of logical compaction policies.

This is problematic when the input is not running, as would be the case for a table without an index backing it. You might say: "we never have that!", but in fact we want this but cannot have it for this reason.

Compaction involves both communication with the `Controller` but also with the `persist` module that may be maintaining the input in the coordinator.

**Comment by frankmcsherry** [comment]
If the coordinator wants to be able to access a source as of some `time`, it needs to prevent the compaction by holding a read capability and calling `allow_compaction` whenever its needs advance. At the moment, it relies on the fact that some dataflow is dangled off of that source, and that bits of the persistence code sniff out messages sent back from these dataflows (either timestamp bindings or table index frontiers), to initiate any `allow_compaction` calls. If we removed the default index from tables, for example, the coordinator would continually insert into these tables and never allow compaction on them.

So I think the coordinator either wants to discard its read capability for each source (`allow_compaction([])`) which probably deletes the source, or more intentionally manage the allowed compaction (perhaps, `allow_compaction([now()])`).

This is perhaps a storage-specific version of https://github.com/MaterializeInc/materialize/issues/10953, which presents differently (as non-management, rather than over-management).

**Comment by frankmcsherry** [comment]
Maybe differently: in a world where Compute is really slow, doesn't do a great job, etc. the current coordinator will continue to feed data into e.g. `persist` and never allow it to compact, eventually running it out of resources. The slowness of Compute 1. sucks but 2. shouldn't prevent the coordinator from clearly communicating with Storage. Similar issues with a not hypothetical relocation of timestamp bindings from the coordinator to the controller: if there isn't a dataflow up and running, this resource will fill up and may eventually exhaust itself, unless the coordinator says "it's all good; I don't need information other than from `time` onwards".

**Comment by mjibson** [comment]
Is this issue relevant anymore? I think it all got done.

**Comment by frankmcsherry** [comment]
Well, it is currently in the state that the coordinator awaits statements from STORAGE about the state of collections, and then repeats whatever STORAGE's take is at the `persist` client. That's probably somewhat backwards, but perhaps the fix is instead to extricate it from the coordinator. The coordinator currently says to STORAGE "here is a compaction policy for sources" rather than manually pilot the compaction, but I think you are right there is not much left to do at the moment.
