### ISSUE TITLE
Materialize is inconsistent about the version of PG it "broadcasts"

### ISSUE THREAD

**Issue by mkysel** [MaterializeInc/materialize#10958]
### What version of Materialize are you using?

v0.21

### How did you install Materialize?

Built from source

### What was the issue?

When running PSQL, MZ announces itself to be both 9.5.0 and 9.6.0

``` 
$ psql postgres://materialize@localhost:6875/materialize
psql (14.2, server 9.5.0)
Type "help" for help.

materialize=> select version();
                             version                             
-----------------------------------------------------------------
 PostgreSQL 9.6 on x86_64-apple-darwin (materialized 0.21.1-dev)
(1 row)
```

There two variables are hardcoded in:
https://github.com/MaterializeInc/materialize/blob/main/src/coord/src/session/vars.rs#L94
https://github.com/MaterializeInc/materialize/blob/main/src/coord/src/coord/dataflow_builder.rs#L428

It would be nice if these were the same value.

**Comment by benesch** [comment]
Thanks for the spot. I sent #10960. For issues as small as these, if you go to the trouble of digging in to the detail that you did, I'd encourage you to just submit the PR with the fix!
