### ISSUE TITLE
sql: support arrays in named composite types

### ISSUE THREAD

**Issue by pH14** [MaterializeInc/materialize#10975]
### What version of Materialize are you using?

master

### How did you install Materialize?

Built from source

### What was the issue?

Looks like arrays aren't handled properly in named composite types:

```
materialize=> create type x as (a integer[]);
CREATE TYPE
materialize=> select ROW(ARRAY[1, 2])::x;
ERROR:  CAST does not support casting from record(f1: integer[]) to x
```

The issue comes from planning where we map a record to the type IDs of its fields: https://github.com/MaterializeInc/materialize/blob/3f628d84241dbde356095527246ae07ea5448052/src/sql/src/plan/statement/ddl.rs#L2179-L2182

`dt_ids` contains the array _element_ type (e.g. `integer` in the case above), but not the array type itself. This leads to some unfortunate behavior:

```
## were this bug fixed, this should fail
materialize=> select ROW(1)::x;
(1)
```

Not sure if it's as simple as this, but maybe the answer is mapping each field to the GlobalId of `data_type` rather than `dt_ids`.

**Comment by benesch** [comment]
> Not sure if it's as simple as this, but maybe the answer is mapping each field to the GlobalId of data_type rather than dt_ids.

So, on the one hand, this is exactly right. `dt_ids` contains the transitive closure of IDs accessed. If you want info about the root data type, you want to look at `data_type`. 

On the other hand... we probably shouldn't be recording the element type ID in `dt_ids`. The array's type ID should be sufficient, if we make sure that array types and map types and list types all correctly record their own dependencies in the catalog.
