### ISSUE TITLE
doc/user: PHP guide + cheatsheet

### ISSUE THREAD

**Issue by ruf-io** [MaterializeInc/materialize#10988]
### What needs to be changed or added?

Start with the node.js guide structure. https://materialize.com/docs/guides/node-js/

Look for PHP-standard postgres libraries and vet that they can interact with Materialize in all the required ways (especially `TAIL WITH FETCH`)

**Comment by ruf-io** [comment]
Might be nice to include some notes about the other PHP frameworks (Laravel) you've tested.

**Comment by bobbyiliev** [comment]
> Might be nice to include some notes about the other PHP frameworks (Laravel) you've tested.

Sounds good! I have the Laravel example ready and tested. Just working on the pure PHP one now.

**Comment by bobbyiliev** [comment]
Just prepared an example for PHP PDO which includes an example with `TAIL` as well:

https://gist.github.com/bobbyiliev/7880e636115336afc11c5cf69c29ad9c

I will prepare the description today.

This example can be extended to show how to use SSE with just PHP and Materialize as described [here](https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events/Using_server-sent_events).
