### ISSUE TITLE
doc/user: SQL Server via Debezium CDC Guide

### ISSUE THREAD

**Issue by ruf-io** [MaterializeInc/materialize#10989]
### What needs to be changed or added?

Create a variant of https://materialize.com/docs/guides/cdc-mysql/ for SQL Server via Debezium.

See helpful notes from Mark here: https://materializecommunity.slack.com/archives/C0157GZ7UKF/p1646142131506359

**Comment by morsapaes** [comment]
@bobbyiliev confirmed that this works, so assigning it as a low-prio task to get this in the `/unstable` docs! There are some known limitations laid out in #8054.
