### ISSUE TITLE
Handle Origin messages in Postgres replication

### ISSUE THREAD

**Issue by nharring-adjacent** [MaterializeInc/materialize#11020]
### Feature request

Postgres logical replication has a message type which enables clients to determine whether the source of a transaction is "local" or "remote" to the Postgres server, but these messages are currently ignored in the Postgres source. 

The primary motivation for implementing a handler for this message type is as a pre-requisite to supporting Postgres logical replication as a sink, use of the Origin message would allow Materialize to discard replication events which actually originated from Materialize in a circulation replication setup.

**Comment by benesch** [comment]
Closing as too hypothetical. We don't yet support a PostgreSQL sink (#1077), so there's no way to do circular replication today.
