### ISSUE TITLE
coord: build confidence in new transaction handling

### ISSUE THREAD

**Issue by benesch** [MaterializeInc/materialize#11041]
In the interest of making forward progress on platform, @frankmcsherry and I pressed forward with a number of reasonably scary PRs to the coordinator over the weekend. It would be great to get post-merge reviews (or at least quick skims) on the following PRs:

  * #11019 (@frankmcsherry added)
  * #11035
  * #11036 (@aljoscha you might want to take a look at this one too)
  * #11037
  * #10883 / #11039
  * #11069

More PRs may be added over the course of the weekend.

I'm marking this as a release blocker in an attempt to _relieve_ pressure. I want to make it clear that we won't ship the next release until we've got more consensus that we didn't miss something major in these PRs. We should 100% skip the release this week if y'all need more time to review.

## Potential regressions

* [x] #11071
* [ ] #11072
* [ ] #11137
* [x] #11134
* [ ] #11155

**Comment by frankmcsherry** [comment]
The release notes for #10883 are one thing I'd like to call out, as the removal of indexes has the potential to disrupt a variety of user query plans.

**Comment by aljoscha** [comment]
:eyes:

**Comment by philip-stoev** [comment]
There has been a regression with user tables after #10883  - https://github.com/MaterializeInc/materialize/issues/11071

**Comment by philip-stoev** [comment]
There has been a regression with unmaterialized sources after #11072: 11072

**Comment by philip-stoev** [comment]
Regression with `CREATE INDEX` in a commit that comes after the PRs listed: #11134

**Comment by philip-stoev** [comment]
Regression (performance) with `CREATE INDEX` and persistent user tables after https://github.com/MaterializeInc/materialize/pull/10883 : #11137 . This one is a realistic scenario, one index per table only.

**Comment by philip-stoev** [comment]
The case where there are many non-identical indexes over the same table has been opened as #11155 . I am going to edit the top-level description of this ticket to list all the regressions in a list form.

**Comment by benesch** [comment]
@philip-stoev what do you think about calling this closed once we track down https://github.com/MaterializeInc/materialize/issues/11072? #11137 and #11155 don't seem like blockers to me. (#11155 in particular has actually fixed a bug; it's just that fixing that bug has a performance cost until #4887 gets fixed.)

**Comment by philip-stoev** [comment]
Yes, I would agree. I am happy that all the individual issues have now had they five minutes of fame and are understood.

**Comment by benesch** [comment]
Calling this one closed. #11072 has been triaged; a mitigation is landing in #11244.
