### ISSUE TITLE
Validate order of correlated quantifiers.

### ISSUE THREAD

**Issue by wangandi** [MaterializeInc/materialize#11081]
See discussion at https://github.com/MaterializeInc/materialize/pull/10901#discussion_r819167043 and https://github.com/MaterializeInc/materialize/pull/10901#discussion_r819153981.

Currently, a Query Graph Model is structured such that post-order visitation will visit the input box of a particular quantifier `Qi` before the input box of the correlated quantifier `Qj` that depends on it. This is quite convenient because it means that we know that attributes have already been computed for `Qi` when we are trying to perform an operation on `Qj`.

We should ensure that the structure preserves this property as we add more features to QGM by adding a constraint to the QGM validator.

**Comment by ggevay** [comment]
Closing, because QGM was abandoned.
