### ISSUE TITLE
Combine `SHOW CREATE INDEX` and `pg_get_indexdef` implementations

### ISSUE THREAD

**Issue by jkosh44** [MaterializeInc/materialize#11109]
In #10980 I added support for the `pg_get_index` function which recreates the command used to create the index. I was not aware that [`SHOW CREATE INDEX`](https://materialize.com/docs/sql/show-create-index/) already existed with the same functionality. Ideally the `pg_get_indexdef` implementation should be refactored to re-use the `SHOW CREATE INDEX` implementation.

Note: `pg_get_indexdef` adds the `USING <index-type>` syntax to the output to match PostgreSQL behavior and so that the meta-command `\d <object>` can properly parse the output. `SHOW CREATE INDEX` does not contain this syntax in the output currently. Since Materialize only supports a single index type, it's valid syntax to include `USING arrangement` when creating an index, but it's ignored. I think this output should be added to `SHOW CREATE INDEX`, still it's something to consider.

**Comment by teskje** [comment]
@jkosh44 Could you elaborate more on how re-using the `SHOW CREATE INDEX` implementation for `pg_get_indexdef` would work?

AFAICT, `SHOW CREATE INDEX` is implemented by `plan_show_create_index`, which receives the index name. In contrast `pg_get_indexdef` receives an arbitrary SQL expression, so we'd somehow need to convert that to (first an OID and then) the index name, if we want to use `plan_show_create_index` here. Given that the OID expression can also reference relations (e.g. `select pg_get_indexdef((select oid from [mz_catalog.mz](http://mz_catalog.mz/)_indexes limit 1))`) I assume it cannot be resolved during query planning already.

We have a similar issue in #11591.
