### ISSUE TITLE
Error handling for file sources that can't be read properly.

### ISSUE THREAD

**Issue by umanwizard** [MaterializeInc/materialize#1112]

**Comment by rjnn** [comment]
This has come up several times in conversations with users - making a typo in the filename is a really common mistake (one I've made myself several times!) and it's really hard to diagnose. We really should be surfacing _something_ (I don't care what) when we add a file source to a file that doesn't exist.

**Comment by umanwizard** [comment]
I *think* this is easy to do given the current state of the code, let me see if I can whip something up.

**Comment by benesch** [comment]
Wait, wait, wait, I really think this is dependent on runtime errors. How is it not?

**Comment by umanwizard** [comment]
@benesch Perfectly accounting for edge-cases probably is, but I think during schema-purification we can just try to open the file and bail if it can't be opened, no?

**Comment by umanwizard** [comment]
Closing this because the 99% fix for the interactive case is in. Making a follow-up issue for doing something sensible with sources we read from mzdata on startup: #2802
