### ISSUE TITLE
performance regression: Index creation with `--persistent-user-tables` is 2.5-5x slower 

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#11137]
### What version of Materialize are you using?

v0.22.1-dev (253c608b1)

### How did you install Materialize?

Docker image

### What was the issue?

```
CreateIndex               \|       0.588 \|       0.256 \|    !!YES!!    \| 2.3 TIMES slower
```

The regression:
- seems specific to `--persistent-user-tables`
- is proportional to the size of the table, that is, it is not a one-time startup cost
- the test uses a single table 
To reproduce:

```
./mzcompose run default --this-tag=unstable-$THIS_SHA --other-tag --root-scenario=CreateIndex --max-runs=
```

Bisection reports the following commit:

```
3f7aedf33e91b8497c2f1622a4333da15a37de10 is the first bad commit
commit 3f7aedf33e91b8497c2f1622a4333da15a37de10
Merge: 588a9e720 253c608b1
Author: Nikhil Benesch <nikhil.benesch@gmail.com>
Date:   Sat Mar 5 19:50:34 2022 -0500

    Merge pull request #10883 from benesch/table-unspecial
    
    coord,dataflow: remove special cases for table indexes
```

**Comment by guswynn** [comment]
@benesch didn't you mention that pr might have been wrong?

**Comment by benesch** [comment]
If I did, didn't mean to! That PR is definitely doing a desirable thing. Definitely has some bugs, or exposed some bugs, though.

**Comment by benesch** [comment]
Unassigning myself from this one! I think we can consider this one a "don't care" for now? At least, I'm personally comfortable with this taking .5s instead of .25s because it's not a config that users enable by default. Perhaps it makes @aljoscha or @ruchirK or @danhhz uncomfortable, though, and one of them might want to take a look?

**Comment by philip-stoev** [comment]
Moving to the Persistence team then for possible further action.

**Comment by aljoscha** [comment]
I don't think we care, because so much is in flux right now and all this code will likely change. Which... does make me feel nervous but I have accepted that! :sweat_smile:

**Comment by danhhz** [comment]
I agree with @aljoscha on both counts. The reality is that a lot of things are going to regress between now and platform. If experimental persisted tables get slow, incorrect, or otherwise unreliable during that period, we've always got the option to turn off the background system tables test.

**Comment by aljoscha** [comment]
Closing this because current persist/storage architecture has moved quite a bit beyond this.

@philip-stoev Please yell at me if you'd like to keep this open.

fyi @danhhz
