### ISSUE TITLE
regression: Creating many indexes over DIFFERENT columns of same table causes OOM

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#11155]
### What version of Materialize are you using?

v0.22.1-dev (0b34555fb)

### How did you install Materialize?

Built from source

### What was the issue?

Even with the fix in https://github.com/MaterializeInc/materialize/pull/11154 , the case where many different indexes are being created on the same table still causes OOM. The memory consumption is 100MB/index even in the case where the table has no data.

To reproduce, pipe the output of this through `testdrive -`:

```
print(f"> CREATE TABLE t (f1 INTEGER)")
for i in range (1,1000):
    print(f"> CREATE INDEX i{i} ON t(f1+{i})")
```

This same case works like charm on `v0.22.0 (a7c727ac4)` , so it appears different from #4887 that has been there forever. Note that the test case does not ingest any data nor it runs any `SELECT`s.

**Comment by antiguru** [comment]
This problem has several facets, but concerning the dataflow construction we seem to be importing all available indexes and retain their tokens, even if we're only reading from a subset of the indexes. Specifically, the following code states this behavior: https://github.com/MaterializeInc/materialize/blob/350e79f51c33a5b243cd18b27f9866f44bf5e72d/src/dataflow-types/src/types.rs#L317-L319

While fixing this wouldn't prevent the quadratic behavior for constructing a dataflow plan, it would avoid the quadratic cost while rendering and maintaining the index.

**Comment by frankmcsherry** [comment]
> This same case works like charm on v0.22.0 (a7c727ac4) , so it appears different from https://github.com/MaterializeInc/materialize/issues/4887 that has been there forever. Note that the test case does not ingest any data nor it runs any SELECTs.

I believe what has changed since 0.22 is that we now import more than one index for sources (e.g. tables). Imo, that is now *good*, and what is bad is that we do not remove the indexes we do not use. I believe that addressing #4887 would address this problem.

**Comment by teskje** [comment]
I tested this today on staging, and creating the 1000 indexes made the memory usage jump from ~33MiB to ~220MiB. This amounts to less than 200kiB per index, which seems acceptable. It's certainly way less than the 100MB reported above.
