### ISSUE TITLE
The field 'TABLE_SCHEMA' has a type currently unknown to Npgsql (OID 25)

### ISSUE THREAD

**Issue by nharring-adjacent** [MaterializeInc/materialize#11158]
### What version of Materialize are you using?

v0.21.1

### How did you install Materialize?

Built from source

### What was the issue?

Using PowerBI Desktop I attempted to add a new datasource with the postgresql driver to connect to the materialize instance. Received the error when the driver attempted to connect, happens regardless of Import or DirectQuery setting and whether or not "Include Relationship Columns" or "Navigate using full hierarchy" were checked.

This looks like the same issue reported with CockroachDB in https://github.com/npgsql/npgsql/issues/1321 and https://github.com/cockroachdb/cockroach/issues/63146

**Comment by bobbyiliev** [comment]
I've just tested this out again and it still seems to be the case.

```sql
select * from pg_type where oid = 25;
```

- In materialize:

```sql
 oid | typname | typnamespace | typowner | typlen | typtype | typcategory | typrelid | typelem | typarray | typinput | typreceive | typnotnull | typbasetype | typtypmod | typcollation | typdefault 
-----+---------+--------------+----------+--------+---------+-------------+----------+---------+----------+----------+------------+------------+-------------+-----------+--------------+------------
  25 | text    |        20005 |    20013 |        | b       | S           |        0 |       0 |     1009 |          |            | f          |           0 |        -1 |            0 | 
(1 row)
```

- In Postgres:

```sql
 typname | typnamespace | typowner | typlen | typbyval | typtype | typcategory | typispreferred | typisdefined | typdelim | typrelid | typelem | typarray | typinput | typoutput | typreceive | typsend  | typmodin | typmodout | typanalyze | typalign | typstorage | typnotnull | typbasetype | typtypmod | typndims | typcollation | typdefaultbin | typdefault | typacl 
---------+--------------+----------+--------+----------+---------+-------------+----------------+--------------+----------+----------+---------+----------+----------+-----------+------------+----------+----------+-----------+------------+----------+------------+------------+-------------+-----------+----------+--------------+---------------+------------+--------
 text    |           11 |       10 |     -1 | f        | b       | S           | t              | t            | ,        |        0 |       0 |     1009 | textin   | textout   | textrecv   | textsend | -        | -         | -          | i        | x          | f          |           0 |        -1 |        0 |          100 |               |            | 
(1 row)
```

Code in npgsql:

https://github.com/npgsql/npgsql/blob/main/src/Npgsql/NpgsqlTypes/NpgsqlDbType.cs#L150

https://github.com/npgsql/npgsql/blob/main/src/Npgsql/TypeMapping/PostgresTypeOIDs.cs#L37

**Comment by morsapaes** [comment]
I stumbled upon this query ([source](https://community.crate.io/t/problem-with-powerbi-desktop-and-permissions/722/2)), which seems to be what Power BI executes to load types:

```sql
SELECT ns.nspname, a.typname, a.oid, a.typrelid, a.typbasetype, 
    CASE WHEN pg_proc.proname='array_recv' THEN 'a' ELSE a.typtype END AS type, 
    CASE 
      WHEN pg_proc.proname='array_recv' THEN a.typelem 
      WHEN a.typtype='r' THEN rngsubtype 
      ELSE 0 
    END AS elemoid, 
    CASE 
      WHEN pg_proc.proname IN ('array_recv','oidvectorrecv') THEN 3    /* Arrays last */ 
      WHEN a.typtype='r' THEN 2                                        /* Ranges before */ 
      WHEN a.typtype='d' THEN 1                                        /* Domains before */ 
      ELSE 0                                                           /* Base types first */ 
    END AS ord 
    FROM pg_type AS a 
    JOIN pg_namespace AS ns ON (ns.oid = a.typnamespace) 
    JOIN pg_proc ON pg_proc.oid = a.typreceive 
    LEFT OUTER JOIN pg_class AS cls ON (cls.oid = a.typrelid) 
    LEFT OUTER JOIN pg_type AS b ON (b.oid = a.typelem) 
    LEFT OUTER JOIN pg_class AS elemcls ON (elemcls.oid = b.typrelid) 
    LEFT OUTER JOIN pg_range ON (pg_range.rngtypid = a.oid)  
    WHERE 
      a.typtype IN ('b', 'r', 'e', 'd') OR         /* Base, range, enum, domain */ 
      (a.typtype = 'c' AND cls.relkind='c') OR /* User-defined free-standing composites (not table composites) by default */ 
      (pg_proc.proname='array_recv' AND ( 
        b.typtype IN ('b', 'r', 'e', 'd') OR       /* Array of base, range, enum, domain */ 
        (b.typtype = 'p' AND b.typname IN ('record', 'void')) OR /* Arrays of special supported pseudo-types */ 
        (b.typtype = 'c' AND elemcls.relkind='c')  /* Array of user-defined free-standing composites (not table composites) */ 
      )) OR 
      (a.typtype = 'p' AND a.typname IN ('record', 'void'))  /* Some special supported pseudo-types */ 
    ORDER BY ord 
    ; 
```

This doesn't return any results in Materialize, though it does return if you change the `JOIN` to `LEFT JOIN`. My hunch is that this might be specific to how we implemented support for one of these `pg_catalog` tables?

**Comment by morsapaes** [comment]
We default to `NULL::pg_catalog.oid` for `pg_type. typreceive`, so the join condition will never succeed. @benesch @mjibson, is there some prior context that prevents us from extending `pg_proc` and populating `typreceive` with the corresponding `pg_proc.oid`?

**Comment by mjibson** [comment]
The [docs](https://www.postgresql.org/docs/current/catalog-pg-type.html) say:

> typreceive regproc (references [pg_proc](https://www.postgresql.org/docs/current/catalog-pg-proc.html).oid)
> Input conversion function (binary format), or zero if none

Pretty sure we can change that NULL to 0. I'm not familiar with what "Input conversion function" refers to. I think it's referencing the sql function that can convert binary format bytes to a datum. We don't expose those in pg_proc, so 0 might be ok for all of them? @sploiselle might know about this too.

**Comment by benesch** [comment]
>  I think it's referencing the sql function that can convert binary format bytes to a datum.

That's correct.

> We don't expose those in pg_proc, so 0 might be ok for all of them?

That alone won't make the join condition succeed, though! There's no `pg_proc` with OID 0:

<img width="808" alt="image" src="https://github.com/MaterializeInc/materialize/assets/882976/39a9f429-1609-4e4b-8e31-3973d4508b1e">

> is there some prior context that prevents us from extending `pg_proc` and populating `typreceive` with the corresponding `pg_proc.oid`?

Don't think so. Someone just needs to do the thankless work of adding a stub entry to `pg_proc` for each type's receive input conversion function, and then linking up the OIDs in `pg_type`.

**Comment by morsapaes** [comment]
From the post linked above, one other compat issue we might run into and can also get out of the way is `information_schema.character_sets` (#9182):

```sql
SELECT character_set_name FROM information_schema.character_sets;
```
