### ISSUE TITLE
sql: `coalesce` with `char` returns wrong result

### ISSUE THREAD

**Issue by benesch** [MaterializeInc/materialize#11166]
### What version of Materialize are you using?

ccd258eff

### How did you install Materialize?

Built from source

### What was the issue?

In Materialize:

```
materialize=> select coalesce(null::char(1), 'abc');
 coalesce 
----------
 a
(1 row)
```

In PostgreSQL:

```
benesch=# select coalesce(null::char(1), 'abc');;
 coalesce 
----------
 abc
(1 row)
```

cc @sploiselle

**Comment by philip-stoev** [comment]
Possibly connected to https://github.com/MaterializeInc/materialize/issues/8597
