### ISSUE TITLE
Remove Consistency Topic in Kafka Sinks

### ISSUE THREAD

**Issue by andrioni** [MaterializeInc/materialize#11216]
### Feature request

Right now, `CREATE SINK` statements have `FORMAT` for both the main output destination (Avro OCF or Kafka topic) and consistency topic (in case of Kafka topic) defaulting to Avro if not explicitly set.
We would like to remove this default value and make these clauses mandatory for all `CREATE SINK` calls, with ideally a migration in the catalog to explicitly add the `FORMAT` clause when it's absent, as to not break existing installations of Materialize.

**Comment by aljoscha** [comment]
@nmeagan11 & @morsapaes & @sjwiesman: What do you think of this one? If we want to do it, we should do it now. And I would again do it without a migration path.

**Comment by sjwiesman** [comment]
seems like a good idea to me!

**Comment by morsapaes** [comment]
The usability question for me IWRT consistency topic formats is more #10163. If we only support Avro (even for JSON-formatted sources), what is the upside of having users explicitly define the format, @aljoscha?

**Comment by aljoscha** [comment]
This might even be obsoleted if we go more towards https://github.com/MaterializeInc/materialize/issues/14267. Thought I think in that case it might be good to keep both options, in case users need that consistency topic.

I can definitely see a world where we only support an Avro-formatted consistency, though. Which also makes the syntax tighter. I can't say what users would want here though, and would have to defer to @nmeagan11  @morsapaes @sjwiesman .

**Comment by benesch** [comment]
> This might even be obsoleted if we go more towards https://github.com/MaterializeInc/materialize/issues/14267. Thought I think in that case it might be good to keep both options, in case users need that consistency topic.

The consistency topic != sidecar topic though, right?

**Comment by aljoscha** [comment]
Right now the consistency topic _is_ the sidecar topic.

**Comment by sjwiesman** [comment]
I'm thinking about this from a user ops perspective. 

1. Ideally there is no sidecar topic by default and everything "just works (tm)"
2. If we have to have a side car topic we need to support formats that don't rely on a schema registry. It would be unfortunate for an application that only uses JSON to need a schema registry for consistency. 
3. If we do have a side car topic that supports multiple formats, being explicit around the format is easier to reason about. You always know what format is being used.

**Comment by benesch** [comment]
> Right now the consistency topic _is_ the sidecar topic.

Well, no kidding! That seems like we're conflating two things that don't strictly need to be conflated? One of these things is our internal metadata that will be in whatever format _we_ want; the other is external-facing metadata that's under the control of the user.

Does anyone use the consistency topic for its intended purpose today? I.e., relating events in the same transaction. Or is it just the topic that you have to deal with if you want EOS with Materialize sinks?

**Comment by sjwiesman** [comment]
> Does anyone use the consistency topic for its intended purpose today? I.e., relating events in the same transaction.

First time I’ve heard of that use case

**Comment by morsapaes** [comment]
> Does anyone use the consistency topic for its intended purpose today? I.e., relating events in the same transaction. 

I can think of [at least one user](https://materializecommunity.slack.com/archives/C015KDVS7EV/p1616165529004800) that has brought this up in the past (and that more recently reinforced that he was waiting for either `ENVELOPE MATERIALIZE` to be supported in sinks or Debezium transaction support). But my feeling is also that most users were dealing with this as collateral damage of enabling EOS.

**Comment by benesch** [comment]
Well, I propose then that we deprecate/remove the consistency topic for the forseeable future in Materialize Platform. One less thing to worry about.

**Comment by aljoscha** [comment]
So, is the conclusion that we remove the consistency topic? It sounded like @morsapaes would like to keep it but @benesch and @nmeagan11 would remove it.

And then #14267 introduces (really massages the current sidecar topic) into an offsets topic. But our messaging/documentation/philosophy around that is very different from the current sidecar/consistency topic?

**Comment by benesch** [comment]
> So, is the conclusion that we remove the consistency topic? It sounded like @morsapaes would like to keep it but @benesch and @nmeagan11 would remove it.

That's my preference, yeah! I think we could bring it back any time given user demand; I just like the idea of the consistency topic being entirely orthogonal to the offsets topic.

**Comment by morsapaes** [comment]
> It sounded like @morsapaes would like to keep it.

On the contrary, I'm a big +1 on getting rid of it!

**Comment by bkirwi** [comment]
Great - the addition of the new progress tracking topic will happen as part of https://github.com/MaterializeInc/materialize/issues/14488, and we'll track the removal of the old one here. (Though it may be easiest to do as a single change.)

**Comment by bkirwi** [comment]
The consistency topic was removed in #14526, and some related code was cleaned up in #14339 and #14679.
