### ISSUE TITLE
doc/user: Overview

### ISSUE THREAD

**Issue by joacoc** [MaterializeInc/materialize#11276]
### What pages are affected?

[What is Materialize](https://materialize.com/docs/overview/what-is-materialize/)
[Architecture](https://materialize.com/docs/overview/architecture/)
[API Components](https://materialize.com/docs/overview/api-components/)
[Arrangements](https://materialize.com/docs/overview/arrangements/)
[Volatility](https://materialize.com/docs/overview/volatility/)

### What needs to be changed or added?

These are all critical Materialize pieces, the first interactions as a user, and thus they can constantly be improved.

**Changes**

- What Is Materialize?
   - Should be short
   - Avoid talking about stuff that adds more overhead to a user's knowledge.
- Architecture 
   - Talks about concepts and SQL statements defined in the next section. A join could be made. 
- API Components
   - Reframe API and SQL API concepts.
   - One of the most critical sections where all the core components are explained goes under the radar.
- Arrangements
   - As a **USER**, are arrangements as crucial as they are? When does a **user** explicitly interact with one besides troubleshooting cases? I'm skeptical about this section. Arrangements are core important for Materialize, but how important are they for the user when making a critical decision? Aren't Indexes the face of the arrangements? Then it should be the Index section and abstracted under it. Arrangements should be presented as the underhood mechanism.
- Volatility
   - There are multiple questions around what happens when Materialize goes down or how Postgres as a source will behave. This is a perfect place to improve.  

Additionals: 
- Reducing/unifying jargon 
- Restructure/renaming/removing/adding sections (E.g.: API Components and Architecture)
- Polish critical concepts (Materialization, Volatility, etc..)

**Comment by morsapaes** [comment]
Linking to #8664, #8663, #8665.

**Comment by joacoc** [comment]
Closing. New docs solve all these topics, and linked issues (except GH) have been completed.
