### ISSUE TITLE
Testing for CLUSTER commands

### ISSUE THREAD

**Issue by antiguru** [MaterializeInc/materialize#11288]
### Goal(s)

Currently, the `CREATE/DROP CLUSTER` commands only have limited coverage, as the presence of https://github.com/MaterializeInc/materialize/issues/11278 shows. We need to have better to make sure that the commands behave as expected.

The commands and changes are documented in https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/20220214_create_cluster.md

### Steps

We'd need to test:
* `CREATE CLUSTER`
* `DROP CLUSTER`
* `SHOW CLUSTERS`
* On top of this, all other commands that accept a `CLUSTER` parameter needs testing.

**Comment by philip-stoev** [comment]
We now have CREATE/DROP cluster in multiple testing frameworks, so I think this ticket can be closed.
