### ISSUE TITLE
Postgres CDC Per Source metrics not reliably reporting

### ISSUE THREAD

**Issue by nharring-adjacent** [MaterializeInc/materialize#11280]
### What version of Materialize are you using?

v0.21.1

### How did you install Materialize?

Built from source

### What was the issue?

The mz_postgres_per_source_* stats are not reliably reporting for Postgres CDC sources in either the Prometheus endpoint or the `mz_metrics` system table. 

I verified by inserting logs in source startup and metrics struct creation that these things are happening correctly and also that increments are being made but the metrics never show up.

**Comment by benesch** [comment]
Closing as stale. We have a totally different approach to PostgreSQL stats/metrics post platform.
