### ISSUE TITLE
sql: remove OIDs from `ScalarType`

### ISSUE THREAD

**Issue by sploiselle** [MaterializeInc/materialize#11344]
### Feature request

Currently, `repr::scalar::ScalarType` passes oids around for custom types. However, oids are unstable (e.g. across restarts), which causes problems in a world where the coordinator/adapter and `dataflow` are distributed. For example, `dataflow` relies on derived equality to determine if it already has a dataflow built for a `RelationDesc`; with oids in the `RelationDesc`, Materialize would wind up building more and unnecessary dataflows.

To resolve this issue, we can instead replaced oids with `GlobalId`s widely, and offer an oid-backed representation only where it's necessary, i.e. in the pgrepr crate. An important note in this, though, is that the GlobalId -> oid conversion must happen with catalog access, i.e. in the coordinator/adapter. This might necessitate creating something like a `PgRelationDesc` or `PgScalarType` that has oids.

- [x] #11627 
- [x] delete `custom_name` field from `ScalarType` (see related discussion in #10934)

**Comment by benesch** [comment]
As part of this work, it'd be great to also delete the `custom_name` field from `ScalarType`. Some discussion here! https://github.com/MaterializeInc/materialize/issues/10934#issuecomment-1082563412

**Comment by heeringa** [comment]
@sploiselle - does merging #11627 resolve this issue?

**Comment by sploiselle** [comment]
@heeringa The work Nikhil mentions [here](https://github.com/MaterializeInc/materialize/issues/11344#issuecomment-1082565099) still isn't done, but I can write up a separate issue for it and close this ticket.

**Comment by heeringa** [comment]
@sploiselle I understand.  I updated this issue to include links to the closed PR as well as the work that needs to be done to close this issue out.

Right now I have https://github.com/MaterializeInc/materialize/issues/11575 as an M1 Epic.  But I think this issue actually covers all the work listed there.  Is that true in your opinion?  If so, I'll make this issue the epic and close the other one out and update our tracker.

Finally, can you give me an estimate on when deleting the `custom_name` from `ScalarType` will happen?

**Comment by benesch** [comment]
> Right now I have https://github.com/MaterializeInc/materialize/issues/11575 as an M1 Epic. But I think this issue actually covers all the work listed there. Is that true in your opinion? If so, I'll make this issue the epic and close the other one out and update our tracker.

I had to dig in to get comfortable answering "yes" here. The answer is in fact "yes", but by the time I got there I was far enough along that it was easier to just knock this work item out: #12088. We can call #11575 closed!

> Finally, can you give me an estimate on when deleting the custom_name from ScalarType will happen?

Tomorrow, I hope!

**Comment by heeringa** [comment]
The work here is done!
