### ISSUE TITLE
kafka exactly-once sink: expose a transactional id prefix option

### ISSUE THREAD

**Issue by bobbyiliev** [MaterializeInc/materialize#11357]
### Feature request

Some Kafka clusters use permissions and explicitly permission transactional producers for certain transactional id prefixes. At the moment the producer seems to be using Kafka transactions with some transactional id that is unknown in advance.

### Suggestion

For that to work, we would need to expose a transactional id prefix option so that we can permission the user to use any transactional id with that prefix in advance.

**Comment by cjubb39** [comment]
> to allow the users to set a prefix for the transactional id that we use - a lot of kafka permissions management is based on prefixes that the application can then append arbitrary suffixes onto as needed. we do something very similar today in the kafka consumer group code where the user can specify a prefix for the group to easily set ACLs on the broker
