### ISSUE TITLE
sql: add `typcategory` column to `pg_catalog.pg_type`

### ISSUE THREAD

**Issue by bobbyiliev** [MaterializeInc/materialize#11427]
### Feature request

Some PostgreSQL like [Postgres.js](https://github.com/porsager/postgres), which is a PostgreSQL client for Node.js and Deno, reach out to the `typcategory` column, which is currently missing from the `pg_catalog.pg_type` table.

The query that is executed is the following:

```sql
select b.oid, b.typarray
      from pg_catalog.pg_type a
      left join pg_catalog.pg_type b on b.oid = a.typelem
      where a.typcategory = 'A'
      group by b.oid, b.typarray
      order by b.oid
```

**Comment by bobbyiliev** [comment]
A bit more context specifically to Postgres.js, we can still make it work by disabling types when defining the connection string:

```javascript
const sql = postgres('postgres://materialize:materialize@localhost:6875/materialize', {
    fetch_types: false
})
```

**Comment by morsapaes** [comment]
Support for `pg_type.typcategory` was added in #11797, so closing the issue!
