### ISSUE TITLE
STORAGE `ComputeReplay` interface does not error if invalid `as_of` requested

### ISSUE THREAD

**Issue by frankmcsherry** [MaterializeInc/materialize#11437]
### What version of Materialize are you using?

v0.22

### How did you install Materialize?

Built from source

### What was the issue?

The STORAGE layer presents to COMPUTE through the `ComputeReplay` trait, which accepts an `as_of: Antichain<T>` as an argument, which communicates a requirement on the replayed collection: that it must accumulated correctly for times greater or equal to the frontier, and cannot be compacted past it.

At the moment, STORAGE does not error if an `as_of` is supplied that cannot be satisfied, and the COMPUTE layer proceeds forward potentially producing incorrect results. It should provide such an error, or even just panic and force the compute instance to restart. Ideally it is a non-fatal error, and the compute instance can choose to fail or not when it sees the output.

**Comment by aljoscha** [comment]
This has been fixed! The new "interface" for compute to read from storage is `persist_source`, which does check the `as_of`.
