### ISSUE TITLE
Nightly cluster tests avro failure

### ISSUE THREAD

**Issue by antiguru** [MaterializeInc/materialize#11468]
### What version of Materialize are you using?

ca1fbefda746098823234e8a64b9cefd76ef28fc

### How did you install Materialize?

Docker image

### What was the issue?

In recent nightly tests, the clustered test fails to decode avro from files. See https://buildkite.com/materialize/nightlies/builds/756#92e6e1c6-46cd-4dab-875a-6115336d9a18/6142-6210 for an example.

### Relevant log output

```source
> CREATE SINK basic_sink_1429000584 FROM basic INTO AVRO OCF '/share/tmp/.tmp36Uw7s/basic-sink.ocf'
--
  | rows match; continuing at ts 1648555068.9890623
  | Verifying results in file /share/tmp/.tmp36Uw7s/basic-sink-u1203-1648554335-17067242562186804640.ocf
  | testdrive/avro-ocf.td:191:1: error: reading avro values from file: Decode error: Decoding error: Block marker ([70, 65, 22, 2c, 22, 66, 69, 65, 6c, 64, 73, 22, 3a, 5b, 7b, 22]) does not match header marker ([98, 89, e7, ea, 98, 5a, 20, df, ca, 5a, 25, cb, 92, 4e, 14, 15])
  | \|
  | 190 \|
  | 191 \| $ avro-ocf-verify sink=materialize.public.basic_sink_${testdrive.seed}
  | \| ^
  |  
```
```

**Comment by elindsey** [comment]
I'm seeing some new failures in the cluster test related to s3 bucket creation, but I'm not seeing this failure in any newer runs. I'm going to close this out and we'll see if it repros again once storage has settled a bit.
