### ISSUE TITLE
doc/user: Document minimum required ACLs for Confluent Cloud Kafka Source and Sinks 

### ISSUE THREAD

**Issue by ruf-io** [MaterializeInc/materialize#11487]
### What pages are affected?

https://materialize.com/docs/sql/create-source/kafka/
https://materialize.com/docs/sql/create-sink/
https://materialize.com/docs/third-party/supported-tools/

### What needs to be changed or added?

Document the minimum required ACL permissions required to properly configure confluent cloud Kafka as a SOURCE and as a SINK

<img width="651" alt="image" src="https://user-images.githubusercontent.com/11527560/161046893-aac2c84d-63f9-43a6-9759-823015d8d995.png">

Confluent Cloud Kafka ACL docs: https://docs.confluent.io/cloud/current/access-management/access-control/acl.html

**Comment by chuck-alt-delete** [comment]
Looks like the api key for the service account also needs DESCRIBE_CONFIGS at the cluster level and transactional id permissions.

**Comment by jseldess** [comment]
See https://github.com/MaterializeInc/materialize/blob/ea33f3cb13c826bc31a2efd23e1478b6253a0ded/src/storage/src/sink/kafka.rs#L463

**Comment by chuck-alt-delete** [comment]
I’ll also note that these are general Kafka ACLs, not Confluent specific.

**Comment by bkirwi** [comment]
The hard dependency on describe_configs should be going away in the current release, but everything else described above will likely stick around!
