### ISSUE TITLE
Support `SHOW FULL CLUSTERS`

### ISSUE THREAD

**Issue by antiguru** [MaterializeInc/materialize#11492]
### Feature request

Currently, Materialize can list clusters but it cannot reveal how each cluster is configured. For this purpose, add a `SHOW FULL CLUSTERS` command that approximately represents the following information:

* Cluster name
* Cluster type (virtual, managed, remote)
* Cluster replicas (this is denormalized, so either have it in a separate `SHOW` or present as JSON/list/idk.)

**Comment by antiguru** [comment]
This is related to #11778 which suggests a `SHOW CLUSTER REPLICAS`. It's probably better to have the two commands so that data can be presented normalized.

**Comment by likzn** [comment]
Hi, i want try this. And i find we already have `SHOW CLUSTERS` and it wil return all Cluster names. How about extending it based on it?

**Comment by antiguru** [comment]
I think we should extend the `SHOW CLUSTER REPLICAS` command to take `FULL` instead of presenting denormalized data in `SHOW CLUSTERS`.

**Comment by benesch** [comment]
We got rid of `FULL` as a concept for `SHOW` commands, and taught `SHOW CLUSTERS` and `SHOW CLUSTER REPLICAS` to produce useful data by default!
