### ISSUE TITLE
platform: if you drop the equipped cluster the error message is not helpful

### ISSUE THREAD

**Issue by rjnn** [MaterializeInc/materialize#11495]
### What version of Materialize are you using?

 v0.25.1-dev (f7c3601dc)

### How did you install Materialize?

Materialize Platform Alpha

### What was the issue?

materialize=> drop cluster blue;
DROP CLUSTER

materialize=> show clusters;
ERROR:  unknown cluster 'blue'

**Comment by benesch** [comment]
Fixed by @chaas in #16144.
