### ISSUE TITLE
[Epic] Store Data from Tables in STORAGE

### ISSUE THREAD

**Issue by nmeagan11** [MaterializeInc/materialize#11499]
### Description

Use the updated API to store data in tables in `STORAGE`. Constraints:

- `STORAGE` is not committing to low latency writes
- We are not supporting multi-table transactions (for now).

For additional context, see [this internal doc](https://docs.google.com/document/d/1ZgWZs1jrDeIu0ZxSRG_TnOHLmy-YmrKC_GBso7dJkK0/edit#heading=h.yfhfylrbuznd).

### Tasks

TBD

**Comment by elindsey** [comment]
@petrosagg is this actually covered by your current work? It sounded like you were already having to get into table persistence.

**Comment by nmeagan11** [comment]
Closing in favor of https://github.com/MaterializeInc/materialize/issues/11774.
