### ISSUE TITLE
cluster: SELECTs issues to a non-functional cluster can not be Ctrl+C-ed

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#11507]
### What version of Materialize are you using?

v0.25.1-dev (64e7ea273)

### How did you install Materialize?

Built from source

### What was the issue?

If a `CREATE CLUSTER` is provided with , for example, incorrect hostnames, any SELECTs will hang in a way that is not Ctrl+C-able. This is in contrast with the other ways a `SELECT` can hang, e.g. if the chosen timestamp has not yet arrived, which (mostly) react to Ctrl+C as expected.

```
materialize=>  CREATE CLUSTER default REMOTE replica1 ('dataflowd_compute_1:6876', 'dataflowd_compute_2:6876');
CREATE CLUSTER
materialize=> select * from t1;
^CCancel request sent
^CCancel request sent
^CCancel request sent
^CCancel request sent
^CCancel request sent
^CCancel request sent
^CCancel request sent
^CCancel request sent
^CCancel request sent
^CCancel request sent
^CCancel request sent
^CCancel request sent
^CCancel request sent
^CCancel request sent
^CCancel request sent
^CCancel request sent
^CCancel request sent
^CCancel request sent
^CCancel request sent
^CCancel request sent
^CCancel request sent
^CCancel request sent
^CCancel request sent
^CCancel request sent
^CCancel request sent
^CCancel request sent
^CCancel request sent
^CCancel request sent
^CCancel request sent
^CCancel request sent
```

### Relevant log output

```source
...
2022-04-01T12:07:22.451615Z  WARN mz_dataflow_types::client::tcp: Error connecting to dataflowd_compute_2:6876: failed to lookup address information: Temporary failure in name resolution; reconnecting in 1s
2022-04-01T12:07:22.451647Z  WARN mz_dataflow_types::client::tcp: Error connecting to dataflowd_compute_1:6876: failed to lookup address information: Temporary failure in name resolution; reconnecting in 1s
...
```

**Comment by antiguru** [comment]
Relaying a discussion from Slack: The mechanism to block client cancellations on the dataflow layer acknowledging the cancellation was to make sure resources would be reclaimed before issuing another query. More abstractly, it was used as an indication for the health of a Timely instance. For Materialize platform with active replication, this mechanism fails to provide the same contract:
* For a cluster with no connected replicas, no replica can acknowledge the cancellation. We could fix this by handling cancellations in a specialized manner somewhere within the protocol layers, as shown by #11781, but it doesn't resolve the underlying question of how to determine that an instance is healthy.
* For a cluster with connected replicas, we could enforce that all accept the cancellation, ensuring resource reclamation on all replicas. The currently implementation ensures that _any_ replica acknowledged the receipt.
* Ideally, we separate the mechanism to determine a replica health from peek cancellations.

The interested audience should probably follow #11587 for updates on this issue, or its underlying concepts.
