### ISSUE TITLE
[Epic] CREATE SINK ... MATERIALIZE (CDCv2) in Platform

### ISSUE THREAD

**Issue by nmeagan11** [MaterializeInc/materialize#11502]
### Description

This is the tracker issue for the sinks design which will require writing data back to `STORAGE` (which we care to do for various reasons, including correctness, active replication, de-duplication, etc.).

Blocked by https://github.com/MaterializeInc/materialize/issues/11501

### Tasks

TBD!

**Comment by benesch** [comment]
Closing as stale. We have no current plans to bring back CDCv2.
