### ISSUE TITLE
cluster: SET CLUSTER does not validate cluster name

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#11509]
### What version of Materialize are you using?

v0.25.1-dev (64e7ea273)

### How did you install Materialize?

Built from source

### What was the issue?

`SET CLUSTER` does not check if the cluster exists. It always succeeds and I think it should error out instead.

```
materialize=> set cluster=no_such_cluster;
SET
materialize=> show clusters;
ERROR:  unknown cluster 'no_such_cluster' <- only errors here
```

**Comment by benesch** [comment]
Fixed with a notice in #16097. See #12926 for why producing a notice is more tenable than producing an error.
