### ISSUE TITLE
[Epic] Design for Writing a Storage Collection to Kafka

### ISSUE THREAD

**Issue by nmeagan11** [MaterializeInc/materialize#11501]
### Initiative and Theme

Materialize is Flexible; Materialize makes it easy to build new applications
Materialize is Friendly; Materialize makes it easy to add downstream data sinks

### Problem

External sinks do not work in Platform. We need a design in place in order to flesh out the implementation and UX. The design should cover `CREATE SINK ... INTO KAFKA` for storage. Additionally, exactly-once guarantees should be the default behavior (supported envelope types TBD).

Note that this just addresses Kafka, as that is what is in scope for M2. Other external sinks are TBD.

### Success Criteria

We have an agreed upon design document that is detailed enough for implementation.

### Time Horizon

Small

### Blockers

None

**Comment by elindsey** [comment]
I'm closing a number of old sink tasks since they won't be directly applicable as we redesign them for platform. They may still have a few relevant points/old context though, so cross linking here:
https://github.com/MaterializeInc/materialize/issues/1728
https://github.com/MaterializeInc/materialize/issues/7043
https://github.com/MaterializeInc/materialize/issues/2808
https://github.com/MaterializeInc/materialize/issues/6200

**Comment by elindsey** [comment]
Previously we had tasks around wanting materialize to be able to source its own sinks - https://github.com/MaterializeInc/materialize/issues/3618

Definitely we want be able to sink to and then source from storage collections (like Aljoscha's recent prototype). It's not clear to me that being able to source directly from eg. a Kafka, Kinesis, or whatever sink will still be a goal - something we'll want to think about from the product side.

**Comment by benesch** [comment]
Since we now have a separate issue for internal sinks, can we focus this one on taking a storage collection and writing it to external systems? E.g., a design for taking a storage collection and writing it to Kafka.

**Comment by uce** [comment]
The design in https://www.notion.so/materialize/Kafka-Sinks-9ba8f8c0ddc949d6b20a67a2558a7604 has been approved and work on it has started in #11503.
