### ISSUE TITLE
wrong result after Mz restart with kafka source persistence enabled

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#11506]
### What version of Materialize are you using?

 v0.25.1-dev (9886cdb19)

### How did you install Materialize?

Built from source

### What was the issue?

A mzcompose-based test that non-concurrently performs kafka ingestion, creation of materialized sources, materialized views on top of them, plus Mz kills/starts ends up in a situation where the materialized view no longer returns the expected result.

Creating a new, fresh, second materialized source over the same Kafka topic returns different results than the original source that was present across restarts. The numbers indicate that ~12K records are missing from the first source but appear when the entire topic is re-ingested in the second source.

Reproduction test case coming up shortly.

### Relevant log output

```source
There are no log entries about any source errors and such.
```

**Comment by philip-stoev** [comment]
To reproduce:

1. Clone `https://github.com/philip-stoev/materialize.git`, branch `gh11506-test`
2. Run 
```
cd test/zippy
./mzcompose run default
```

3. This will produce a series of actions, ingestions, SQL DDLs and SELECTs and will repeatably fail like this:
```
> SELECT * FROM view10;
rows didn't match; sleeping to see if dataflow catches up 50ms 75ms 112ms 169ms 253ms 380ms 570ms 854ms 1s 2s 3s 4s 6s 10s 15s 22s 33s 49s 74s 78s^^^ +++
tmp/tmp-n2b1te8a.td:10:1: error: deadline has elapsed
     |
   9 | 
  10 | > SELECT * FROM view10;
```

In other words, view10 does not return the expected results even though it did just a minute ago:

```
> SELECT * FROM view10;
rows match; continuing at ts 1648806755.291941
```

4. Log in the container with the psql client:

```
psql -p`docker port zippy_materialized_1 | rev | cut -d ':' -f1 | rev | head -1`   -h 127.0.0.1 -U materialize
```

and observe the current materialization of the source that view10 is based on:

```
materialize=> select count(*) from source10;
  count  
---------
 2396237
```

Then, recreate the same source under a new name:

```
show create source source10;

...

CREATE MATERIALIZED SOURCE "materialize"."public"."source10new" FROM KAFKA BROKER 'kafka:9092' TOPIC 'testdrive-topic10-1' FORMAT AVRO USING CONFLUENT SCHEMA REGISTRY 'http://schema-registry:8081/' SEED KEY SCHEMA '{"type":"record","name":"test","fields":[{"name":"f1","type":"long"}]}' VALUE SCHEMA '{"type":"record","name":"test","fields":[{"name":"f2","type":"long"}]}' ENVELOPE UPSERT
```
and select from it:

```
materialize=>  select count(*) from source10new;
  count  
---------
 2413655
(1 row)
```

The two counts are different, for two sources off the same kafka topic.

**Comment by aljoscha** [comment]
I _think_ this might be the same issues that https://github.com/MaterializeInc/materialize/pull/10556 was meant to fix. Though that PR is outdated by now and I don't know if we want to put in the time to fix the current persistence integration.

**Comment by philip-stoev** [comment]
This is no longer reproducible. The test in question, Zippy with the KafkaSources scenario is running in the CI.
