### ISSUE TITLE
[Epic] Make Sources Definite

### ISSUE THREAD

**Issue by nmeagan11** [MaterializeInc/materialize#11528]
### Description

The primary responsibility of the `STORAGE` layer is to [create and maintain definite collections](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/platform/architecture-db.md#storage). In order to achieve this, we will utilise the `persist` API as the mechanism by which we durably write down the contents of a source, explicitly timestamp these contents, and expose this information reliably and consistently.

Though we are only focused on successfully connecting a Kafka source in M1, we will be making all sources definite in M1.

### Goals for M1

- successfully connecting a source to the storage layer and writing down the contents via the `persist` API
- for Kafka sources, this must be durable and reliable enough that this version is unlikely to lose data except in some edge cases where Kafka goes down, S3 misbehaves, etc.

### Non-Goals for M1

- production-level guarantees, i.e. source of truth. Production-level support implies a strict level of correctness, such that even in edge cases we guarantee we will maintain the properties listed above, plus zero loss of data. This is, however a M2 goal.

### Tasks

- [x] #12209

**Comment by benesch** [comment]
We've scoped down the definition of "definite" to cover _just_ that data will be durably recorded. That means the one and only work item here is #12209! There's now a new epic, #12203, which tracks making Kafka sources with `ENVELOPE NONE` handle faults correctly.

**Comment by benesch** [comment]
PR merged, so this is done! 🎉

**Comment by benesch** [comment]
Gah, sorry, _this_ issue is about fault tolerance, not just definiteness. It's #11434 that's done.
