### ISSUE TITLE
Sinks do not all populate `sink_write_frontiers` and thereby prevent compaction

### ISSUE THREAD

**Issue by frankmcsherry** [MaterializeInc/materialize#11522]
### What version of Materialize are you using?

v0.24

### How did you install Materialize?

Built from source

### What was the issue?

The controller uses information extracted through `ComputeState::sink_write_frontiers` to allow compaction of the inputs on which sinks depend. This makes the most sense for Kafka "exactly once" sinks, which must be restartable, but was extended to all sinks under the belief that a sink should by default be restartable. When this happened, we didn't also ensure that all sink implementations populated `sink_write_frontiers`. In particular, TAIL does not appear to do this, and while a TAIL is active the inbound data will not be compacted (neither indexes used, nor the sources on which they depend).

Sinks that "do not care" could immediately release this ability, but realistically we should figure out for each sink on which basis they should be restarted, e.g. across replicas.

**Comment by frankmcsherry** [comment]
#11540 makes this not as much of a blocker (there is still a sink that does not populate the frontiers, `AvroOcf` files, but ... yeah).

**Comment by elindsey** [comment]
M2, unless this blocks API changes in other services

**Comment by aljoscha** [comment]
@nmeagan11 I'm removing this from STORAGE team tracking. Actual sinks have been redone, and the remaining "sinks" that this refers to, such as TAIL, live in compute now.

I'm not sure this is even a problem still in COMPUTE. @antiguru what do you think?

**Comment by antiguru** [comment]
I think the remaining item was TAIL not producing the uppers, which we fixed in #11540. From my perspective this is done. Also, there are no other sinks in Compute anymore!
