### ISSUE TITLE
[Epic] Display Meta Data (i.e. offset) for Sources

### ISSUE THREAD

**Issue by nmeagan11** [MaterializeInc/materialize#11530]
### Description

Building on displaying nouns, users should easily see meta data of their sources. Currently, it’s very challenging for users to learn certain meta information of their sources (i.e. what offset their Kafka source has been ingested up to in order to determine lag).

### Tasks

TBD! Tasks may also be dependent on the design resulting from https://github.com/MaterializeInc/cloud/issues/2472.

**Comment by benesch** [comment]
Are there things besides offset that folks are known to want? Offsets are covered by #11218!

**Comment by nmeagan11** [comment]
> Are there things besides offset that folks are known to want? Offsets are covered by #11218!

Not that I'm aware of! Closing in favor of #11218
