### ISSUE TITLE
Increase Interval range

### ISSUE THREAD

**Issue by jkosh44** [MaterializeInc/materialize#11544]
### Feature request

Postgres recently committed a patch to increase the total range of the Interval data type: https://github.com/postgres/postgres/commit/e39f9904671082c5ad3a2c5acbdbd028fa93bf35. Previously Interval's couldn't take advantage of the full range of their underlying memory representation due to parsing limitations. The updated code can now parse any Interval that fits into the underlying memory representation.

We have code that arbitrarily limits the total range of our Intervals to match the range of Postgres Intervals. Since our underlying memory representation is the same as Postgres it would be nice to remove this code to match PostgreSQL's new range.

That commit also has a bunch of good test cases that we can port over to our SLT tests.

**Comment by aalexandrov** [comment]
This will break compatibility with Postgres 9.5 (unless the Postgres patch ends in this line as well). I'm not sure if this is a major issue though.

**Comment by jkosh44** [comment]
I don't think that the Postgres patch will be applied to 9.5. I think it's probably not a huge deal though because the change would just mean that we don't error on certain interval's that Postgres would error on, and it would be strange (though not impossible) for someone's workflow to break because we don't error on an interval.

Also we actually already aren't compatible with 9.5 Interval ranges. We have a specific range for Intervals [-2147483648 hours -59 minutes -59.999999 seconds, 2147483647 hours 59 minutes 59.999999 seconds], while Postgres doesn't actually have a specific range, they just error out on certain Intervals due to parsing issues.

For example the following Interval is "out of range"
```
postgres=# SELECT INTERVAL '2147483648 seconds';
ERROR:  interval field value out of range: "2147483648 seconds"
LINE 1: SELECT INTERVAL '2147483648 seconds';
```

Even though the following Interval which is much bigger is in range
```
postgres=# SELECT INTERVAL '2147483647 minutes';
    interval    
----------------
 35791394:07:00
(1 row)
```

We'll accept both as in range
```
materialize=> SELECT INTERVAL '2147483648 seconds';
   interval   
--------------
 596523:14:08
(1 row)

materialize=> SELECT INTERVAL '2147483647 minutes';
    interval    
----------------
 35791394:07:00
(1 row)

```
