### ISSUE TITLE
[Epic] Support SQL table operations via storage layer including restarts

### ISSUE THREAD

**Issue by heeringa** [MaterializeInc/materialize#11578]
Principle: Materialize is Dependable
Initiative: Materialize stays up and running

Provide SQL support for tables [CREATE, INSERT, UPDATE, DELETE] that connects to the storage layer.
Problem: Wire up tables in SQL to the storage layer
Success: All table operations succeed at the storage layer including rehydration after a restart.

Background: [Tables: Use Cases and Ownership](https://docs.google.com/document/d/1ZgWZs1jrDeIu0ZxSRG_TnOHLmy-YmrKC_GBso7dJkK0/edit#heading=h.yfhfylrbuznd)

Blockers: 

- [ ] https://github.com/MaterializeInc/materialize/issues/11774

Blocks:

Issues:

- [x] https://github.com/MaterializeInc/materialize/issues/13007

**Comment by benesch** [comment]
This one's done! The blocker listed is still open, but all that remains in that epic is QA work; the actual blocking work has been completed.
