### ISSUE TITLE
Support `pg_get_viewdef` (function in `pg_catalog`)

### ISSUE THREAD

**Issue by aalexandrov** [MaterializeInc/materialize#11591]
For `\sv [view]`, we specifically need `pg_get_viewdef(view_oid, pretty_bool)` (`oid = 2506`).

**Comment by teskje** [comment]
I've looked at this a bit. The variants of the `pg_get_viewdef` function are:

- `pg_get_viewdef(view_name)` (1640)
- `pg_get_viewdef(view_oid)` (1641)
- `pg_get_viewdef(view_name, pretty_bool)` (2505)
- `pg_get_viewdef(view_oid, pretty_bool)` (2506, used by `\sv [view]`) 
- `pg_get_viewdef(view_oid, wrap_column_list)` (3159)

We already support `SHOW CREATE VIEW [view]`, which produces similar output. One major difference implementation-wise is that `SHOW CREATE VIEW` gets the view name as its argument, while `pg_get_viewdef` takes SQL expressions, e.g.:

- `select pg_get_viewdef('te' || 'st');`
- `select pg_get_viewdef('test'::regclass::oid);`
- `select pg_get_viewdef((select 16385));`
- `select pg_get_viewdef((select name from my_view_table limit 1));`

Unless I'm missing something, this means it won't be possible to materialize this function during query planning, but only during query execution.

According to @aalexandrov, we can currently only support unmaterializable functions that have zero arguments, so `pg_get_viewdef` cannot be implemented directly. He mentioned that maybe we could implement a helper function `mz_get_viewdefs()` that returns the defs of all existing views, and then implement `pg_get_viewdef` in terms of this helper function.

**Comment by benesch** [comment]
Oh! There is an easier way!

1. Add a new column to `mz_views` called `definition` that contains the SQL definition of the view.
2. Implement `pg_get_viewdef` as `sql_impl!(“SELECT definition from mz_views WHERE oid = $1”)`, adjusting the where clause for other variants. We’ll have to ignore the `pretty` bool for now, but that’s fine.

This way `pg_get_viewdef` doesn’t even need to be unmaterializable.
