### ISSUE TITLE
[adapter+storage] MZ should offer real-time recency for external sources

### ISSUE THREAD

**Issue by frankmcsherry** [MaterializeInc/materialize#11633]
### Feature request

The third of three consistency desiderata.

On SELECT commands, Materialize is in principle able to acquire the currentmost data of upstream sources, and ensure that any response reflects at least all of that data. This involves an interaction with the upstream source, but it ensures that the response to the SELECT command has a "real-time recency" guarantee: the answer is correct for a real-time moment greater than that at which the SELECT command was entered.

This is less than strict serializability for Materialize, as we are unable to ensure that *all* events have orders that respect their real-time orders. In particular, we are unable to ensure that we correctly order events in unrelated external sources, and misordering them relative to their real-time order would be a violation of strict serializability. This property is meant to be the appropriate weakening of strict serializability vis-a-vis this fundamental ambiguity.

---

This property relies on Storage providing a hook for each class of source for which we provide this property, and for Adapter to correctly invoke the hook and use the result for timestamp determination. It may be no more complicated than that, though. As a subtle property, the issues requires ownership to design and document why we have this property.

**Comment by heeringa** [comment]
@nmeagan11 can we fold this into #11531 and close?

**Comment by nmeagan11** [comment]
Closing in favor of https://github.com/MaterializeInc/materialize/issues/11531
