### ISSUE TITLE
[dbz tx] Reuse existing arrangement for transaction metadata source

### ISSUE THREAD

**Issue by cjubb39** [MaterializeInc/materialize#11667]
Currently we use `import_source` to recreate the transaction metadata source for each data source.  We could (should?) reuse this -- including from its initial source creation

**Comment by benesch** [comment]
I think this one's no longer relevant! The transaction metadata source is now in a separate process from the data source, so we _have_ to import the source (via persist). @cjubb39 I'm going to optimistically close this out, but please do reopen if I'm in error!
