### ISSUE TITLE
[dbz tx] Revisit error handling strategy?

### ISSUE THREAD

**Issue by cjubb39** [MaterializeInc/materialize#11669]
Currently we just keep emitting data rows even after we hit an error.  The collection is definite -- however, this can result in a lot of memory usage downstream as there will be a lot of data after the output frontier.  Fixing this could require some work to ensure the collection stays definite.  We'd likely want to do #11664 first.

Some notes I wrote up as I was working on the OG dbz tx PR: https://docs.google.com/document/d/1kJuDuja_5UbzStL8-2uYR6bQsVQDXqmZG4Wf5q3qYfc/edit#heading=h.i9b4r9wdze39

**Comment by benesch** [comment]
Closing as we no longer support Debezium's transaction topics.
