### ISSUE TITLE
Debezium for Oracle

### ISSUE THREAD

**Issue by lenhardtx** [MaterializeInc/materialize#11688]
### What version of Materialize are you using?

v0.25.0 (29f800881)

### How did you install Materialize?

Docker image

### What was the issue?

Can Materialize works with Debezium for Oracle?

materialize=> CREATE SOURCE pedidos
  FROM KAFKA BROKER 'x.x.x.x:9092' TOPIC 'oraprd.ocean.sbr_ped_venda'
  FORMAT AVRO USING CONFLUENT SCHEMA REGISTRY 'http://x.x.x.x:8081'
  ENVELOPE DEBEZIUM;
ERROR:  fetching latest schema for subject 'oraprd.ocean.sbr_ped_venda-value' from registry: subject not found

Another question, its possible update version of postgresql of Materilized? (current server 9.5.0)

**Comment by morsapaes** [comment]
> Can Materialize works with Debezium for Oracle?

We haven't tested Debezium with Oracle, but the error you're seeing suggests that the events aren't making it to Kafka in the first place; could you double check that there's data in the topic and the schema is correctly written out to the Schema Registry? I'll spin up a test environment in the meantime to check whether Materialize complains about how Oracle change events are formatted.

> Another question, its possible update version of postgresql of Materilized? (current server 9.5.0)

This is just the "self-reported" `server_version` that is advertised _e.g._ to drivers; in reality, Materialize supports features released in more recent versions of Postgres. Does this affect your usage of Materialize in some way?
