### ISSUE TITLE
Enable access to profiling functions for dataflowd

### ISSUE THREAD

**Issue by antiguru** [MaterializeInc/materialize#11710]
`materialized` offers memory profiling functions based on jemalloc, exposed through the multiplexed http endpoint on the psql port. Add similar functionality to `dataflowd` to enable separate memory profiling.

**Comment by benesch** [comment]
@umanwizard I finished the axum refactor of the HTTP server in #11807. You should be all set to pull the /prof endpoint into the `prof` crate. I recommend having the `prof` crate expose an `axum::Router`, which can then be mounted into HTTP servers in `materialized` and `dataflowd` using [`Router::nest`](https://docs.rs/axum/latest/axum/routing/struct.Router.html#method.nest).
