### ISSUE TITLE
Add protobuf support for `mz_dataflow_types::client::ComputeCommand`

### ISSUE THREAD

**Issue by aalexandrov** [MaterializeInc/materialize#11737]
Add protobuf support for [`mz_dataflow_types::client::ComputeCommand`](https://github.com/materializeinc/materialize/blob/d0749fc45496de0601370b9f482eb5c354dc3fa7/src/dataflow-types/src/client.rs#L108-L141).

Blocked by:
- #11971

**Comment by wangandi** [comment]
Protobuf support for Antichain<u64> can be found here: 
https://github.com/MaterializeInc/materialize/blob/d0749fc45496de0601370b9f482eb5c354dc3fa7/src/persist/src/indexed/encoding.rs#L841

**Comment by aalexandrov** [comment]
> Protobuf support for Antichain can be found here:

Let's move it to the obvious location.
