### ISSUE TITLE
Add protobuf support for `chrono*::*` dependencies

### ISSUE THREAD

**Issue by aalexandrov** [MaterializeInc/materialize#11756]
Identify (and if needed define dedicated) suitable `ProtoRepr::Repr` types for `chrono::NaiveDateTime`, `chrono::FixedOffset`, `chrono_tz::Tz` and implement `ProtoRepr` for each of these types.

**Comment by lluki** [comment]
I just realized, we already have the corresponding types in `row.proto` (@aalexandrov):

[`row.proto`](https://github.com/MaterializeInc/materialize/blob/cf089a6f87dfefc707abe53caad68209c8ed4173/src/repr/src/row.proto#L46-L48).

* Are there any other dependencies (other than via Row Datum) where we need the chrono types?

* Shall we re-use the types and simply implement the `FromProto` trait?

**Comment by aalexandrov** [comment]
> Are there any other dependencies (other than via Row Datum) where we need the chrono types?

Yes, for example `UnaryFunc` variants such as `ExtractInterval`, `TimezoneTimestamp`, and `TimezoneTime` depend on various `chrono*` types (sometimes indirectly). See [this comment](https://github.com/MaterializeInc/materialize/issues/11747#issuecomment-1097674546) for details.

> Shall we re-use the types and simply implement the `FromProto` trait?

Yes!
