### ISSUE TITLE
change server panics to graceful error messages

### ISSUE THREAD

**Issue by rjnn** [MaterializeInc/materialize#1177]
discussed in a meeting, issue created and assigned to frank to fill out

**Comment by rjnn** [comment]
I think this has mostly been done. What else do we need to do to close this issue out?

**Comment by frankmcsherry** [comment]
I'm not sure we've done any of this. For starters, we would assign the issue to someone to review /audit code for panics, and attempt to characterize the errors as recoverable or non. It's a bunch of debt to pay off.

**Comment by cuongdo** [comment]
@benesch points out that some ungraceful error handling has been addressed through his runtime errors work, and some has been addressed through Natacha's work on making our Kafka code more robust. 

@frankmcsherry: are there specific areas of the code that you are still concerned about?

**Comment by benesch** [comment]
> @frankmcsherry: are there specific areas of the code that you are still concerned about?

Bumping this question!
