### ISSUE TITLE
persistence: memory leak with persistent-user-tables -- memory not freed on DROP

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#11779]
### What version of Materialize are you using?

v0.19.0 all the way up to current main

### How did you install Materialize?

Docker image

### What was the issue?

If a persistent user table is created and dropped repeatedly, memory usage grows without bound.

To reproduce, run this td file in a loop:

```
> DROP TABLE IF EXISTS t1 CASCADE

> CREATE TABLE t1 (f1 INTEGER)

> INSERT INTO t1 SELECT * FROM generate_series(1,1000000)
```

like this:

```
while bash -c "target/release/testdrive oom2.td --no-reset --seed=1 " ; do : ; done
```

and observe unbounded memory growth. This seems to be even more pronounced when there are dataflows defined over the table. Issue is not reproducible unless persistent user tables is enabled.

The jmalloc heatmap shows allocations both on the persist and the timely side:
![Screenshot from 2022-04-13 11-29-43](https://user-images.githubusercontent.com/1279722/163134693-95ea9040-5fae-4aad-85d3-cb2cd22c7b77.png)

**Comment by elindsey** [comment]
This and https://github.com/MaterializeInc/materialize/issues/11598 look like issues we'll need to address once we have the initial version of platform persisted tables in place, but not actionable until then.

**Comment by aljoscha** [comment]
@philip-stoev Do you think this is still an issue? Quite a bit has changed since then.

**Comment by aljoscha** [comment]
Closing because the implementation underneath is quite different by now.
