### ISSUE TITLE
Loss of interactivity when cluster doesn't respond

### ISSUE THREAD

**Issue by umanwizard** [MaterializeInc/materialize#11775]
### What version of Materialize are you using?

main

### How did you install Materialize?

Built from source

### What was the issue?

Create a cluster with a garbage hostname and create a view on it

```
create cluster cluster1 remote replica1 ('fakehost:2100');
set cluster=cluster1;
create materialized view mv as values (1);
```

This succeeds.

Now try to select from the view:

```
select * from mv;
```

This can't be cancelled and causes the psql shell to hang forever

### Relevant log output

```source
2022-04-13T02:05:53.714222Z  WARN mz_dataflow_types::client::tcp: Error connecting to fakehost:2100: failed to lookup address information: Temporary failure in name resolution; reconnecting in 1s
```

repeated forever
```

**Comment by philip-stoev** [comment]
Dup of https://github.com/MaterializeInc/materialize/issues/11507
