### ISSUE TITLE
[dbz tx] Remove reliance on data stream timestamps

### ISSUE THREAD

**Issue by cjubb39** [MaterializeInc/materialize#11792]
The output frontier of the binary "merging" operator need only rely on the input frontier of the transaction metadata.  If the two inputs were to be in different time domains (e.g. not both real time timestamps as they currently are), we could unnecessarily hold back the output.  The current approach doesn't actually use the data stream frontier anywhere (except to output decoding errors for the data stream) but it does hold back the output frontier.

Could make sense to do this in conjunction with #11664 even though there's not a strict dependency (in either order) between the two

**Comment by benesch** [comment]
Closing as stale, as we no longer support Debezium's transaction topics.
