### ISSUE TITLE
sql: add `CREATE` and `DROP` replica

### ISSUE THREAD

**Issue by benesch** [MaterializeInc/materialize#11808]
This issue tracks adjusting the existing `CREATE CLUSTER` and `DROP CLUSTER` SQL statements to match the [new syntax in the replica design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/20220413_cluster_replica.md#sql-syntax-and-semantics).

The following work items are in scope:

  * Parsing and planning of `CREATE REPLICA`
  * Parsing and planning of `DROP REPLICA`
  * Removal of `ALTER CLUSTER`
  * Adjustment of `CREATE CLUSTER` to not take the options that are moved to `CREATE REPLICA`
  * Population of `mz_cluster_replicas`

Wiring up the size and availability zone options to the orchestrator is out of scope of this issue.

Part of epic #11240.

**Comment by sploiselle** [comment]
Closed by #12132` + #12313
