### ISSUE TITLE
controller: plumb cluster size configuration

### ISSUE THREAD

**Issue by benesch** [MaterializeInc/materialize#11810]
This issue tracks wiring up the [size option](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/20220413_cluster_replica.md#controller-changes) for cluster replicas.

The following work items are in scope:

  * Adding the `--cluster-replica-sizes` command-line flag
  * Converting the size to a CPU limit, memory limit, and number of processes in the controller

Choosing the correct size mapping to use in the cloud is out of scope.

Part of epic #11240.

**Comment by umanwizard** [comment]
I tentatively plan to take this
