### ISSUE TITLE
Support the persistence of input sources and, perhaps, indexes

### ISSUE THREAD

**Issue by cuongdo** [MaterializeInc/materialize#1182]
#997 gave us persistence of the catalog. The other aspect of persistence customers need is persistence of data.

Assigning to @rjnn for more product definition.

**Comment by bhoomit** [comment]
Hi @rjnn, 

I'm facing issue #2225 which is related to your point #3 

> We should be able to propagate back to the source what 'offset' we have made durable, so that we can inform kafka where we are as a consumer, so that upon restart we can pick up exactly where we left off.

@JLDLaughlin directed me to this issue. 

My team at GoIbibo wants to use Materialize on production and this is the biggest concern for us right now. 

Let me know if I can help you with coding the solution if you have a strategy in mind.

**Comment by ruchirK** [comment]
Closing this as enough code has landed that followups can now be tracked via #3305 and followup prs
