### ISSUE TITLE
Create DataGen alias for PubNub source for demos

### ISSUE THREAD

**Issue by sjwiesman** [MaterializeInc/materialize#11828]
### Feature request

The PubNub source is great for demos as it does not require users to bring external dependencies. The problem is it looks like a real system users need to understand to use materialize. It would be great to create a `DATAGEN` source (name open to bikeshedding) that is just an alias to PubNub and also provides the subscription key. 

We might also want to provide a few blessed channels instead of allowing all of PubNub. This would allow us to hide the actual channel name. 

Something like: 

```
CREATE SOURCE market_orders_raw
FROM DATAGEN
DATATYPE 'market-orders';
```

Would be translated to:

```
CREATE SOURCE market_orders_raw
FROM PUBNUB
SUBSCRIBE KEY 'sub-c-4377ab04-f100-11e3-bffd-02ee2ddab7fe'
CHANNEL 'pubnub-market-orders';
```

**Comment by benesch** [comment]
Fixed by removing PubNub as a source type (#13865) and adding built-in load generators instead (#13764).
