### ISSUE TITLE
Remove non-cloud sources and sinks

### ISSUE THREAD

**Issue by benesch** [MaterializeInc/materialize#11875]
This issue tracks the removal of sources and sinks that can't be used in Materialize Cloud. The work items are:

 * Removal of Avro OCF sinks
   * [x] Pivot dbt-materialize test suite to use a Kafka sink (it just needs _a_ sink)
   * [x] Remove sink parsing, planning, rendering and tests
 * Removal of Avro OCF sources
   * [x] Remove source parsing, planning, rendering, and tests
 * Removal of file sources
   * [x] Pivot dbt-materialize test suite to use a Kafka source (again, it just needs _a_ source)
   * [x] Pivot non-file-source specific tests to use S3 sources (this keeps the code paths as identical as possible), ideally over several PRs
   * [x] Remove parsing, planning, rendering, and file source-specific tests
 * [x] Remove safe mode (`--safe` CLI option)

I've tried to roughly break down the work into small, individually-PRable chunks. I'd like to avoid doing this in a single mega PR, as that will make it difficult to review whether we've preserved the appropriate tests.

**Comment by benesch** [comment]
I believe @guswynn has already started on some of this work, so please coordinate with him before starting any of the tasks above.

**Comment by guswynn** [comment]
@benesch ah I didnt realize the dbt reps had stuff too

**Comment by guswynn** [comment]
Additionally, a large number of file tests are best pivoted to kafka sources, whereas some of the csv sources will move under `esoteric/s3.*`

**Comment by morsapaes** [comment]
@guswynn, I can take care of the `dbt` test suite if you don't want to dabble in that.

**Comment by guswynn** [comment]
@morsapaes that sounds great! I was hoping to continue my work on the materialized side removal later this week!

**Comment by benesch** [comment]
I'm actually going to grab the dbt work to get this unblocked!

**Comment by benesch** [comment]
Done in #11979.
