### ISSUE TITLE
Protobuf support for `SourceDesc`

### ISSUE THREAD

**Issue by benesch** [MaterializeInc/materialize#11876]
This story is part of the overall versioning epic that spans all teams.

## Goals

* Introduce protobuf types for transitive dependencies of [`SourceDesc`](https://dev.materialize.com/api/rust/mz_dataflow_types/sources/struct.SourceDesc.html)
* Implement mapping between regular and Protobuf-variants of types

## Non-Goals

* End-to-end version upgrades

## Subtasks

* [ ] Scope this task a la #11735.

## See also

* #11735

**Comment by andrioni** [comment]
Dupe of #12358, which is done.
