### ISSUE TITLE
Expose reclocking information as a relation in Materialize

### ISSUE THREAD

**Issue by petrosagg** [MaterializeInc/materialize#11908]
The storage controller currently exposes collections identified by a `GlobalId`. These collections correspond 1-1 to a TVC that one can read by demonstrating its `id`.

We would like to change this relationship so that each storage collection correspond to two parts (maybe more in the future), its data and its timestamp binding TVCs. Users of storage will now need to specify which part of a storage collection they need by specifying an `(id, type)` tuple.

Implementing this depends storing the timestamp bindings in a `persist` collection (#11907) so that readers can read the data.

**Comment by benesch** [comment]
And there's a design nearing completion in #11718!

**Comment by sploiselle** [comment]
I have a [nitty-gritty design doc for this in Notion](https://www.notion.so/materialize/Queryable-remap-collections-8c0b8ee5953643599c7267a9d89867ae).

**Comment by sploiselle** [comment]
Note that before we do this we want to migrate this data to the more Timely-friendly format which Petros is already doing in memory

**Comment by aljoscha** [comment]
Implemented as #15813
