### ISSUE TITLE
regression: Kafka resumption tests reports record missing from sink

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#11920]
### What version of Materialize are you using?

8f031f42ea

### How did you install Materialize?

Docker image

### What was the issue?

The kafka resumption test reports that a record is missing from a sink:

https://buildkite.com/materialize/tests/builds/32374#ad557c92-5491-4dc8-bb8e-f96aaddbab19

This is the first known failure in this test, even though it is sporadic. The previous commits were also done by @benesch , so I am assigning to him.

**Comment by elindsey** [comment]
Unlikely that we'll get to this one soon given sinks are in M2

**Comment by philip-stoev** [comment]
Has not failed in the last 28 days - https://buildkite.com/organizations/materialize/analytics/suites/mzcompose/tests/1839461?branch=main so closing.
