### ISSUE TITLE
regression: memory consumed by dataflows not dropped on DROP

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#11921]
### What version of Materialize are you using?

v0.26.1-dev (10c8467d9)

### How did you install Materialize?

Docker image

### What was the issue?

Memory grows unbounded if a memory-consuming (e.g. `COUNT DISTINCT`) dataflow is created and then dropped repeatedly.

Memory appears to be OK if the dataflow does not have to hold intermediate state (e.g. `COUNT`), so this seems to be a different issue than the network protocol buffer one mentioned by @antiguru .

To reproduce, run the following fragment in a loop:

```
> DROP TABLE IF EXISTS t1 CASCADE

> CREATE TABLE t1 (f1 INTEGER)

> CREATE MATERIALIZED VIEW v1 AS
  SELECT COUNT(DISTINCT f1) AS f1
  FROM t1

> INSERT INTO t1 SELECT * FROM generate_series(1,1000000)

> SELECT f1 >= 0 FROM v1
true
```

e.g. like this:

```
while bash -c "target/release/testdrive  oom6.td " ; do : ; done
```

**Comment by antiguru** [comment]
This seems to be memory in arrangements. 
![image](https://user-images.githubusercontent.com/582946/164271854-e7f02c35-638e-4fe1-9757-303bbffac468.png)
@umanwizard would this match what you're observing in the other issue?

**Comment by frankmcsherry** [comment]
We appear to just not drop dataflows, for reasons that are not yet clear. But running @philip-stoev 's commands multiple times, we see
```
materialize=> select * from mz_arrangement_sizes order by operator;
 operator | worker | records | batches 
----------+--------+---------+---------
      461 |      0 | 1000000 |       3
      463 |      0 | 1000000 |       3
      474 |      0 |       1 |       2
      476 |      0 |       1 |       2
      934 |      0 | 1000000 |       3
      936 |      0 | 1000000 |       3
      947 |      0 |       1 |       2
      949 |      0 |       1 |       2
     1228 |      0 | 1000000 |       3
     1230 |      0 | 1000000 |       3
     1241 |      0 |       1 |       2
     1243 |      0 |       1 |       2
     1701 |      0 | 1000000 |       3
     1703 |      0 | 1000000 |       3
     1714 |      0 |       1 |       2
     1716 |      0 |       1 |       2
     1760 |      0 |       3 |       2
(17 rows)

materialize=> 
```
Each invocation introduces another pair of `1000000` records.

**Comment by frankmcsherry** [comment]
Also, for ease of experimentation you can do the above with `1000000` replaced with `10` if you like. It will still grow without bound, but selecting from the introspection view will reveal our failure!

**Comment by frankmcsherry** [comment]
I can see all of the tokens being dropped on the COMPUTE side of things. Next step is to look in to STORAGE and see if it receives the shutdown request and cleanly handles it!

**Comment by frankmcsherry** [comment]
The symptoms of this issue should be fixed by https://github.com/MaterializeInc/materialize/pull/11949, although it does not fix some of the underlying issues (a few bugs in STORAGE about shutting down source dataflows and communicating it back). I'm not sure if that counts as fixing the issue, but .. at least it would present differently with the above PR.

**Comment by frankmcsherry** [comment]
This is no longer P-1, as the symptoms have been removed. @guswynn is working on some changes that could remove some of the cause as well, and I'll leave it to him to close out the issue once sources are shut down to his satisfaction. We could probably close the issue now if we wanted, given the symptom removal.

**Comment by philip-stoev** [comment]
Memory consumption stays within bounds with the current `main` for all participating processes

> a few bugs in STORAGE about shutting down source dataflows and communicating it back

@frankmcsherry are there tickets for those bugs? If so, than this issue has served its purpose and can indeed be closed.

**Comment by philip-stoev** [comment]
> a few bugs in STORAGE about shutting down source dataflows and communicating it back

Oh, if I understand correctly, https://github.com/MaterializeInc/materialize/pull/12082 has taken care of those, so I am closing the ticket.
