### ISSUE TITLE
Add protobuf support for `mz_expr::relation::AggregateExpr`

### ISSUE THREAD

**Issue by aalexandrov** [MaterializeInc/materialize#11930]
- [x] Add protobuf support for [`mz_expr::relation::AggregateExpr`](https://github.com/MaterializeInc/materialize/blob/ca1fbefda/src/expr/src/relation/mod.rs#L1465-L1473).
- [x] Add protobuf support for [`mz_expr::relation::AggregateFunc`](https://github.com/MaterializeInc/materialize/blob/ca1fbefda/src/expr/src/relation/func.rs#L721-L799).
- [ ] Assign numbers 1-15 to the most common aggregations (probably sum/count).
- [x] Testing support will be complete when #11740 is closed.

**Comment by lluki** [comment]
Discussion for order in this [slack thread](https://materializeinc.slack.com/archives/CM7ATT65S/p1651753523689389)

**Comment by aalexandrov** [comment]
OK, leaving this as it is for now.
