### ISSUE TITLE
storage: adapt the Postgres source spill-to-disk for Platform

### ISSUE THREAD

**Issue by benesch** [MaterializeInc/materialize#11953]
The work item here is to simply crash on retriable errors:

> So I have an even easier solution to propose here: just crash. If we see a retryable error, we can just panic the storaged instance. That'll cause all the pending data to evaporate... and it'll get retried naturally when the orchestrator turns on a new copy.

The original issue description is retained below.

----

The Postgres source currently spills to disk during the snapshot phase. But in Materialize Platform, we're no longer going to have local disk available to the storage layer for this purpose.

A few questions to answer here:

* Why did the Postgres source need to learn to spill to disk? Is it possible we can just use more memory and CPU in platform?
* Can we spill to S3 instead?
* Better yet, can we avoid needing to buffer the snapshot entirely? Is there some other way we can retract all the data we've emitted if the snapshot fails with a recoverable error? 

cc @guswynn @petrosagg

**Comment by elindsey** [comment]
My recollection was the buffering was so we'd be able to issue retractions when errors occurred in the initial snapshot replication. We might be able to solve this with renditions? Abandoning any old renditions that had an error occur and cutting a new one.

**Comment by benesch** [comment]
Looking at the new persist API, I'm not entirely sure how to solve this, even with renditions. Since you need to present a fully formed batch in one shot, ISTM that we're stuck buffering all the data in memory anyway, in order to write it to persist in one go.

It looks to me like the way the current PostgreSQL code writes to disk doesn't actually have the desired effect. I haven't verified this with `printlns!`, but based on reading the current code, we write each row in the snapshot to disk, then emit it via `get_next_message`. But downstream of `get_next_message`, we're going to hang on to that source message in a queue somewhere... so we'll still be paying the memory cost.

@guswynn and @petrosagg, can you validate that theory?

Assuming it is correct, I propose we "solve" this problem by holding on to all snapshot messages locally in the PostgreSQL operator. Then, if the snapshot fails for a retriable reason, we just drop the messages locally, as we've never emitted them. That'll have the same unfortunate memory characteristics of the current approach, but at least we won't be lying to ourselves, and we won't be writing to the local disk anymore.

**Comment by benesch** [comment]
I filed #12893 to track the general problem of memory usage in the source ingestion pipeline.

**Comment by benesch** [comment]
Slack discussion: https://materializeinc.slack.com/archives/C01CFKM1QRF/p1654526968572039

**Comment by benesch** [comment]
Fixed by #13159.
