### ISSUE TITLE
storage: refactor `MzOffset` to be unsigned

### ISSUE THREAD

**Issue by benesch** [MaterializeInc/materialize#11954]
In the storage weekly meeting today, we discussed that `MzOffset` should use an unsigned type (probably `u64`) rather than  `i64`.

Counterpoint: using signed types for offsets makes them usable in the `diff` field (https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/20220411_reclocking_implementation.md#storage-layer-implementation), which we plan to do for reclocking. That might be a good reason _not_ to do this.

@guswynn, can you start shaking this out?

**Comment by elindsey** [comment]
Related discussion https://materializeinc.slack.com/archives/C02KE368L8P/p1651870501758999

**Comment by guswynn** [comment]
Oh yeah I need to still do this!
