### ISSUE TITLE
dbt-materialize: index config should allow optional `name` param

### ISSUE THREAD

**Issue by morsapaes** [MaterializeInc/materialize#11967]
### What version of `dbt-materialize` are you using?

`Unreleased`

### How did you install `dbt-materialize`?

Built from source

### What was the issue?

In #11538, we deprecated the custom index materialization and made index creation part of the model definition as a config. The macro follows the implementation of [`postgres__get_create_index_sql`](https://github.com/dbt-labs/dbt-core/blob/22416980d19888d7bbbcfcda639c16d37a80b948/plugins/postgres/dbt/include/postgres/macros/adapters.sql#L17-L30), where:

> For the index’s name, dbt uses a hash of its properties and the current timestamp, in order to guarantee uniqueness and avoid namespace conflict with other indexes.

This means that **users can no longer specify a custom index name**, and are instead stuck with the auto-generated name (see `104987`): 

![image (6)](https://user-images.githubusercontent.com/23521087/164468580-7359e354-d21f-476b-9982-ceb6b65538ba.png)

We should consider providing an optional `name` param to match the expected behaviour.

<hr>

🤟 Thanks to @markns for reporting this!

**Comment by ahelium** [comment]
Accomplished in https://github.com/MaterializeInc/materialize/pull/14195
