### ISSUE TITLE
multiple materialized can not coexist on the same host due to conflicting storaged/computed ports

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#11988]
### What version of Materialize are you using?

v0.26.1-dev

### How did you install Materialize?

Built from source

### What was the issue?

One can not have two materialized instances on the same physical machine, even if different `listen-addr` are provided. The storaged/computed spawned from materialized will still use the same default ports, so will fail to start up properly.

The ports used for storaged/computed should count up from the listen-addr port provided to materialized.

**Comment by antiguru** [comment]
Fixed in #11990.
