### ISSUE TITLE
Keep an eye on compile times

### ISSUE THREAD

**Issue by jamii** [MaterializeInc/materialize#1201]
Compile times seem to have gotten much worse in the last few months. Currently, making a change to `dataflow` and rebuilding `materialized` in release mode takes 11m49 on my machine. This made testing ideas about fast mode really slow.

It's not clear that we can do anything about it right now, but let's keep track of whether it's getting worse.

**Comment by benesch** [comment]
Closing as not actionable. https://github.com/MaterializeInc/materialize/blob/main/doc/developer/fast-compiles.md summarizes our attempts to make the situation manageable.
