### ISSUE TITLE
Monitoring for standalone binary download

### ISSUE THREAD

**Issue by cuongdo** [MaterializeInc/materialize#1202]
When running Materialize through the sample Docker Compose configuration we’ll provide, monitoring is available through metrics / Grafana.

Neither of those will be available when users download just the materialized binary. So, how will a user view QPS, query latency, and other useful metrics?

Cc @rjnn

**Comment by quodlibetor** [comment]
closing in favor of an issue to make that page fancy, we do currently have monitoring of standalone binaries via http /status
