### ISSUE TITLE
Panic when executing `SHOW CLUSTERS` on a non-default cluster

### ISSUE THREAD

**Issue by andrioni** [MaterializeInc/materialize#12031]
### What version of Materialize are you using?

 v0.26.1-dev (8464e3e47)

### How did you install Materialize?

Built from source

### What was the issue?

A thread panics whenever I try to run `SHOW CLUSTERS` or `SHOW VIEWS` in a non-default cluster, and after that this connection becomes unresponsive.

### Repro

Starting materialized via:
```
$ ./bin/materialized --log-file=stderr --experimental
```

```sql
materialize=> create cluster test size '2';
CREATE CLUSTER
materialize=> set cluster = test;
SET
materialize=> show views;
(hangs forever and the following panic happens)
```
Materialized logs:
```
thread 'tokio-runtime-worker' panicked at 'assertion failed: subscription.client_id.is_none()', /Users/alessandro/workspace/mz/materialize/src/storage/src/boundary/tcp_boundary.rs:246:29
```

### Relevant log output

```source
thread 'tokio-runtime-worker' panicked at 'assertion failed: subscription.client_id.is_none()', /Users/alessandro/workspace/mz/materialize/src/storage/src/boundary/tcp_boundary.rs:246:29
```

**Comment by antiguru** [comment]
I tried to reproduce this issue on b3edd76fb06d51dbe3c727b52be2d4eeafe2bdab and it doesn't seem to reproduce. Are the instructions complete?

**Comment by andrioni** [comment]
I can't reproduce it on newer versions, but it still fails in 8464e3e47c24c3bc501be731eecf70ea2976e553, so I guess something in the last week might have fixed it. Closing the issue.
