### ISSUE TITLE
Post-hoc observability

### ISSUE THREAD

**Issue by jamii** [MaterializeInc/materialize#1203]
Currently all our metrics are pre-aggregated to save memory. This means that when a new question comes up (eg are the latency spikes confined to a specific view or do they happen across all views) we can't answer it without modifying code, recompiling, restarting and hoping to reproduce the same situation. 

http://carlos.bueno.org/optimization/mature-optimization.pdf recommends storing atomic events for as long as possible to enable asking post-hoc questions without changing the system under observation. @frankmcsherry suggests that we could do this in materialized by having a sliding window of log events, so asking a new question is just a matter of installing a new view and polling it. 

It may be possible to use metabase as the UI tool for this, which would also give us some good dogfooding.

**Comment by sploiselle** [comment]
This has shifted w/ the move to cloud; we now have an internal suite of metrics available for post-hoc observability.
