### ISSUE TITLE
performance: Performance of Platform many times slower than the last released single-binary Mz across the board

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#12118]
### What version of Materialize are you using?

c91a45f

### How did you install Materialize?

Docker image

### What was the issue?

The feature benchmark reports substantial performance regressions after the introduction of Platform . I think there has also been one more regression point after that happened, and now the performance of many operations of various types is many times slower .

```

FastPathFilterNoIndex     |       1.561 |       0.205 |    !!YES!!    | 7.6 TIMES slower

FastPathFilterIndex       |       1.407 |       1.149 |    !!YES!!    | 22.4 pct   slower

FastPathOrderByLimit      |       0.685 |       0.119 |    !!YES!!    | 5.8 TIMES slower

Update                    |       2.092 |       1.139 |    !!YES!!    | 83.7 pct   slower

UpdateMultiNoIndex        |       3.958 |       1.427 |    !!YES!!    | 2.8 TIMES slower

InsertAndSelect           |       2.566 |       1.950 |    !!YES!!    | 31.6 pct   slower

OrderBy                   |      16.176 |       2.988 |    !!YES!!    | 5.4 TIMES slower

CountDistinct             |       1.888 |       0.489 |    !!YES!!    | 3.9 TIMES slower

MinMax                    |       7.365 |       1.157 |    !!YES!!    | 6.4 TIMES slower
```

**Comment by JLDLaughlin** [comment]
so Matt is currently working on identifying our most obvious performance issues.

@mjibson how would you like to think about Materialize Cloud performance against our binary performance as @philip-stoev has documented here? Maybe we can create a running doc with three columns: `Arjun's target performance`, `binary performance`, `current cloud performance`?

([Arjun's targets are here](https://docs.google.com/document/d/1_NUMlZCUkilYlvQU3O4UVya3shKJ1INrtVLM3c3FtXc/edit).)

**Comment by mjibson** [comment]
The hardest part about that question is: on what ec2 instance size should we run the local test, and on which cluster size should we run the cloud test, and is it meaningful to compare those? These results are kind of interesting if the whole envd stack is also running locally because it illustrates the additional serialization overhead (and other possible perf regressions), but beyond that I'm not sure it's meaningful to compare local to cloud. I think the stated targets are what we should be using.

**Comment by JLDLaughlin** [comment]
@philip-stoev are you okay with that assessment?

**Comment by philip-stoev** [comment]
I would defer to @mjibson on this, the performance goals and how to measure and achieve them. The Feature benchmark indeed runs everything on the same machine with a file-based blob back-end, so some of the numbers indeed show serialization overhead only. However, for other scenarios the slow down is more substantial than that.

Feel free to close this ticket if it serves no legitimate purpose.

My intention was to only file performance issues myself for the following situations:
- where there is a more recent performance regression , that is, things became slower between two revisions of Platform
- where the performance problem is too large to ignore, that is, when I think success of POCs and demos is under risk (e.g. hypothetically only able to ingest 1000 kafka messages per second v.s. 100K, DDL statements taking 10 secs, that sort of stuff.)
- if I observe any cpu cores churning at 100% when that was not the case previousy

**Comment by mjibson** [comment]
I agree with all of those and would like to keep hearing about them.

**Comment by philip-stoev** [comment]
This is tagged as "green builds" because it affects two CI jobs that were previously green and are now red:
- feature benchmark comparing to the latest released container
- the Nightly full SLT . Previously it completed in 3 hours, now even 10 hours are not sufficient

**Comment by uce** [comment]
This got assigned to @philip-stoev in order to break out sub issues.

**Comment by philip-stoev** [comment]
All the individual performance issues that are readily reproducible have their own tickets. I am closing this one as too broad.
