### ISSUE TITLE
Refactor the `Arbitrary` implementation for `repr::Row`

### ISSUE THREAD

**Issue by wangandi** [MaterializeInc/materialize#12125]
Currently, the methods for generating proptest `Row`s live in [src/repr/tests](https://github.com/MaterializeInc/materialize/blob/main/src/repr/tests/rows.rs), which cannot be accessed by other crates. 

Two places reference `Row`s:
* `MirScalarExpr::Literal`. 
* `dataflow_types::Plan::Constant`

The specific tasks here are:
- [x] Move `PropertizedDatum` & friends to a place where it can be used by other crates.
- [x] Adopt `PropertizedDatum` in the custom `Arbitrary` implementation for `Row`.
- [x] Fix `Arbitrary` implementations for `MirScalarExpr::Literal` and `dataflow_types::Plan::Constant`.

**Comment by lluki** [comment]
Some Types that are stored as datums inside row are also needed elsewhere, but with the current structure it is hard to do. We also already implemented the types in `chrono.proto` with their associated `From` and `TryFrom` traits.

I suggest that in `row.proto` we import the ones from `chrono.proto` and use them there.

This concerns at least the following types:
 * `ProtoTime` (`row.proto`) -> `NaiveProtoTime` (`chrono.proto`)
 * `ProtoTimestamp`
 * `ProtoDate`
 * .. and possibly more
