### ISSUE TITLE
mzcli: deprecate

### ISSUE THREAD

**Issue by benesch** [MaterializeInc/materialize#12188]
This issue tracks the deprecation of [mzcli](https://github.com/materializeInc/mzcli). 

Background: mzcli has had bugs in core product features like `TAIL` for most of its existence (#838, #3416, #12180). We don't have the engineering resources to maintain it properly. psql is where we'd like to focus our efforts instead. We would lose tab completion and syntax highlighting, but we're just a few pgcompat features away from supporting tab completion in psql, and we'll eventually support stock pgcli for users who want the syntax highlighting (#8229).

Work items:
  * [x] Add a note to the mzcli README announce its deprecation
  * [x] Archive the mzcli repository
  * [x] Remove all mention of mzcli from the docs
  * [x] Switch demos to use materialize/cli rather than mzcli

cc @morsapaes @ruf-io @JLDLaughlin

**Comment by morsapaes** [comment]
All demos already use `materialize/cli`! 

Even if we end up not deprecating it, it makes sense to temporarily remove it from user facing docs (which would entail just touching [this page](https://materializecommunity.slack.com/archives/C015KDVS7EV/p1651483833098599)) to avoid a bad first experience with Materialize, like what happened to this [user](https://materializecommunity.slack.com/archives/C015KDVS7EV/p1651483833098599).

**Comment by JLDLaughlin** [comment]
chatting with @benesch in person about this later today!

**Comment by JLDLaughlin** [comment]
chatted with @benesch, let's deprecate `mzcli`! Here's the plan:

Short term:

**Comment by necaris** [comment]
> https://github.com/MaterializeInc/materialize/issues/8229. This is a pg-compatibility issue that should be owned by the SQL team. Once we have that working, we can run psql in Kubernetes and embed a terminal in our web UI. This part should be owned by the Cloud team (probably @necaris or @joacoc?).

Happy to own the web terminal, not least because that means Websockets in `materialized` :smile: Also happy to work on `mzcloud` replacement.

> build out a custom web-based SQL editor

Have we looked at partnering with https://www.ycombinator.com/companies/popsql or someone?

**Comment by JLDLaughlin** [comment]
> Have we looked at partnering with https://www.ycombinator.com/companies/popsql or someone?

That's a great question! @ruf-io was asking me something similiar here: https://github.com/MaterializeInc/cloud/issues/2817#issuecomment-1115371385. I think whoever owns "SQL in web" should look at all the options more closely.

**Comment by benesch** [comment]
> > #8229. This is a pg-compatibility issue that should be owned by the SQL team. Once we have that working, we can run psql in Kubernetes and embed a terminal in our web UI. This part should be owned by the Cloud team (probably @necaris or @joacoc?).
> 
> Happy to own the web terminal, not least because that means Websockets in `materialized` 😄 Also happy to work on `mzcloud` replacement.

Just to make sure we're on the same page: I don't think the web terminal involves WebSockets in `materialized`! I was envisioning something like https://github.com/va1da5/xtermjs-for-k8s-pods, where we'd write a tiny WebSocket server that bridged xterm.js with `psql` running in a Kubernetes pod.

It'd be a wonky UI, for sure, and only worth doing if we can get it done in a week or so, vs. the many weeks it would require for even a basic web-based SQL editor.

> Have we looked at partnering with https://www.ycombinator.com/companies/popsql or someone?

popsql looks very cool! I was hoping it might work out of the box already, but it looks like they set `IntervalStyle` to something unusual:

<img width="1620" alt="image" src="https://user-images.githubusercontent.com/882976/166403173-20f2b546-6ed2-4d92-badc-b2c69bf80c9b.png">

**Comment by morsapaes** [comment]
> Have we looked at partnering with https://www.ycombinator.com/companies/popsql or someone?

Just for context: the folks at [Arctype](https://arctype.com/) are working on a `TAIL`-based integration with Materialize (though it already works out-of-the-box using the PostgreSQL connector).

**Comment by benesch** [comment]
Calling this one done.
