### ISSUE TITLE
to_jsonb() output in arrays

### ISSUE THREAD

**Issue by joacoc** [MaterializeInc/materialize#12181]
### What version of Materialize are you using?

v0.26.0

### How did you install Materialize?

Docker image

### What was the issue?

Braces when it should be brackets:

```sql
SELECT to_jsonb(array[1]::int[]);
 to_jsonb 
----------
 "{1}"
```

Correct output in Postgres:

```sql
postgres=# SELECT to_jsonb(array[1]::int[]);
 to_jsonb 
----------
 [1]
(1 row)
```

**Comment by benesch** [comment]
Looks to be a result of not having any special handling for arrays in `to_jsonb`: https://github.com/MaterializeInc/materialize/blob/1b1f5c59dadc5a560b451a1d4c0c4c984de136d6/src/sql/src/plan/typeconv.rs#L888-L938
