### ISSUE TITLE
[mzcli] TAIL produces no output from simple query; Ctrl+C has no effect

### ISSUE THREAD

**Issue by wizzard0** [MaterializeInc/materialize#12180]
### What version of Materialize are you using?

v0.26.0 (07670312b)

### How did you install Materialize?

Homebrew tap

### What was the issue?

0) watched the HYTRADBOI video where there was a lot of demos involving TAIL
1) installed materialize via brew and mzcli via docker image
2) created test.csv
```
col_a,col_b
a1,b1
```
3) `create source test_csv from file 'test.csv' with (tail=true) format csv with header;`
4) `CREATE materialized VIEW test_csv_m AS SELECT * FROM test_csv;`
5) confirmed `select * from test_csv_m` works
6) confirmed that after `echo a2,b2 >> test.csv` the SELECT query includes rows added
7) tried various combinations of TAIL:
- `tail test_csv`, `tail test_csv_m`, `tail (select * from test_csv)`, `tail (select * from test_csv_m)`, `COPY (TAIL test_csv) TO STDOUT`,`COPY (TAIL test_csv_m) TO STDOUT`
- No errors observed
8) but `echo a3,b3 >> test.csv` has no effect (but shows up in subsequent SELECTs)
9) and there is no way to abort query or exit mzcli other than killing the container

so... how does one test/use the streaming functionality?

### Relevant log output

```source
No errors in materialized console.
```

**Comment by wizzard0** [comment]
Update: `COPY (TAIL test_csv) TO STDOUT` with `psql` works, no success with `mzcli` so far, will update the issue title.

**Comment by philip-stoev** [comment]
@wizzard0 to get new data in the CSV file to show up in Materialize you need to use the `WITH (tail = true)` option:

https://materialize.com/docs/sql/create-source/file/#tailing-files

**Comment by wizzard0** [comment]
@philip-stoev yes, I use with(tail=true) as you can see from the **`Step 3`** :)

**Comment by morsapaes** [comment]
@philip-stoev, cross linking the [community thread](https://materializecommunity.slack.com/archives/C015KDVS7EV/p1651483833098599). It seems like an issue with the `mzcli` client.

**Comment by morsapaes** [comment]
Thanks for bringing this up, @wizzard0! Since `mzcli` it's not being actively maintained, we intend to deprecate it (see #12188). 

Please use the `materialize/cli` image, `psql` or one of the supported SQL clients listed in [Tools and integrations](https://materialize.com/docs/integrations/#sql-clients) instead. And sorry again for the bumpy start!
