### ISSUE TITLE
`dataflow-types`: split into STORAGE and COMPUTE

### ISSUE THREAD

**Issue by benesch** [MaterializeInc/materialize#12211]
The `dataflow-types` crate has confusing ownership because it contains half STORAGE types and half COMPUTE types. 

We should cleave the crate in half, moving the STORAGE types into a crate that clearly belongs to the STORAGE layer, and the COMPUTE types into a crate that clearly belongs to the COMPUTE layer. We should do this in two PRs, one for each layer.

The STORAGE layer is keeping all of its types in the `storage` crate, but putting server-only types behind a `server` feature flag. COMPUTE has no such policy yet. It could choose to do the same thing, or it could have two separate crates: `compute-types` and `compute`.

@frankmcsherry @antiguru do either of you have a take on what you'd prefer to do for COMPUTE?

**Comment by benesch** [comment]
@petrosagg has requested that we hold off on this refactor until #12216 lands.

**Comment by guswynn** [comment]
probably also good to wait for https://github.com/MaterializeInc/materialize/pull/12796 to merge as well

**Comment by aljoscha** [comment]
🎉
