### ISSUE TITLE
Performance of queries is erratic

### ISSUE THREAD

**Issue by antiguru** [MaterializeInc/materialize#12226]
### What version of Materialize are you using?

c1437d135bdd98fd70f984e1a103b719deb1e075

### How did you install Materialize?

Built from source

### What was the issue?

The performance of simple queries can be erratic. `show clusters` takes between 1ms and 80ms on release builds. This is with a default cluster of size 1.

```
DROP CLUSTER default CASCADE;
CREATE CLUSTER default SIZE '1';

SHOW CLUSTERS;
```

I tried to disable Nagle's algorithm on the various TCP connections (`set_nodelay`), but apparently this didn't help.

### Relevant log output

```source
materialize=> show clusters; show clusters; show clusters; show clusters; show clusters; show clusters; show clusters;
  name
---------
 default
(1 row)

Time: 1.989 ms
  name
---------
 default
(1 row)

Time: 76.348 ms
  name
---------
 default
(1 row)

Time: 1.626 ms
  name
---------
 default
(1 row)

Time: 1.477 ms
  name
---------
 default
(1 row)

Time: 44.165 ms
  name
---------
 default
(1 row)

Time: 1.629 ms
  name
---------
 default
(1 row)

Time: 1.586 ms
```
```

**Comment by benesch** [comment]
Looks to be the same as #14060. That issue has more details, so closing this one out!
