### ISSUE TITLE
Update scratch AMIs to 22.04

### ISSUE THREAD

**Issue by teskje** [MaterializeInc/materialize#12245]
The current default scratch configs (in `misc/scratch`) still use a Ubuntu 20.04 AMI. This leads to issues because mzcompose now requires at least Python 3.9 but the default Python version on Ubuntu 20.04 is 3.8. We should update the AMIs to the newest Ubuntu version, which is 22.04.

Unfortunately, this is not as simple as replacing the AMI string in the configs. Ubuntu 22.04 uses an updated version of OpenSSL that by default disallows the RSA SHA-1 algorithm for public keys, which EC2 instance connect seems to rely on. As a result, after creating a Ubuntu 22.04 instance with scratch, connecting to it fails. We need to solve this, either by making EC2 instance connect use a secure public key algorithm or, if that is not possible, configuring OpenSSL to allow ssh-rsa.

-----

# Workaround

Until we have fixed the above, you can install Python 3.9 (or higher) using the deadsnakes spa:

```shell
sudo add-apt-repository ppa:deadsnakes/ppa
sudo apt update
sudo apt install python3.9 python3.9-venv
```

You also might want to change the `/usr/bin/python3` symlink to point to Python 3.9 instead.

**Comment by benesch** [comment]
Looks like there's a way to get EC2 Instance Connect to use ECDSA keys instead: https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-instance-connect-methods.html

**Comment by teskje** [comment]
I've looked into this a bit more. ssh-rsa is actually not the reason why `mssh` fails to connect. I thought it was because that is what the error indicates when you try to use instance connect through the AWS console, but the error is different when using `mssh`:

```
AuthorizedKeysCommand /usr/share/ec2-instance-connect/eic_run_authorized_keys ubuntu SHA256:6rXetOwARtiRja9XNEdEjXDmAfQfdCLtIfZVAw+dstM failed, status 2
```

The actual error is eaten by questionable propagation of error messages, but some print debugging reveals that `eic_run_authorized_keys` eventually invokes `etc_parse_authorized_keys`, which fails [here](https://github.com/aws/aws-ec2-instance-connect-config/blob/master/src/bin/eic_parse_authorized_keys#L168).

The output of this `openssl verify` is:

```
C = US, O = "Starfield Technologies, Inc.", OU = Starfield Class 2 Certification Authority
error 89 at 4 depth lookup: Basic Constraints of CA cert not marked critical
C = US, O = "Starfield Technologies, Inc.", OU = Starfield Class 2 Certification Authority
error 92 at 4 depth lookup: CA cert does not include key usage extension
error /dev/shm/eic-gXrOF7mk/cert.pem: verification failed
```

The same error also occurs if I manually send a key with `aws ec2-instance-connect send-ssh-public-key` and then try to `ssh` to the instance.

I'm not sure what's going wrong. Does `mssh` generate a key that OpenSSL doesn't like? If that's the case I doubt we can fix anything ourselves and I should create an issue in [aws-ec2-instance-connect-config](https://github.com/aws/aws-ec2-instance-connect-config).

**Comment by teskje** [comment]
I opened https://github.com/aws/aws-ec2-instance-connect-config/issues/38.

**Comment by benesch** [comment]
Looks like this is fixed in ec2-instance-connect v1.1.17! See https://github.com/aws/aws-ec2-instance-connect-config/releases/tag/1.1.17. They didn't actually mark the issue as fixed for some reason.

**Comment by teskje** [comment]
Thanks for the hint! Maybe they are waiting for the new version to make it to the EC2 apt repo.

**Comment by benesch** [comment]
Oh, shoot, this is the _server_ side component. I didn't realize. I have no idea how that works, then—do we have to pray that Ubuntu backports the fix into Jammy?
