### ISSUE TITLE
Add protobuf support for `mz_dataflow_types::types::DataflowDescription`

### ISSUE THREAD

**Issue by wangandi** [MaterializeInc/materialize#12240]
Add protobuf support for [`mz_dataflow_types::types::DataflowDescription`](https://github.com/materializeinc/materialize/blob/d0749fc45496de0601370b9f482eb5c354dc3fa7/src/dataflow-types/src/client.rs#L108-L141).

- [x] translating `DataflowDescription` and its subtypes that are in src/dataflow-types/src/types.rs to and from protobuf.
- [x] Transfer information about `SourceDesc` and `SinkDesc` using `serde` temporarily until proper protobuf support is added.
- [x] Stub Protobuf support for `CollectionMetadata`.
- [ ] Implement `Arbitrary` for `DataflowDescription<CollectionMetadata, mz_repr::Timestamp>`.

Follow-up issues (can be handled after this issue is closed)
- #12358
- #12359

**Comment by lluki** [comment]
I suggest we wait with this until @andrioni et el. have the sources/sinks related types ready.
