### ISSUE TITLE
materialized should support a healthcheck exposed via http at /status

### ISSUE THREAD

**Issue by quodlibetor** [MaterializeInc/materialize#1225]
While for inside of docker-compose we can add arbitrary shell commands that should return 0/1 [docs](https://docs.docker.com/engine/reference/builder/#healthcheck), in general most tools are set up around HTTP healthchecks, so if we add a `/status` endpoint to our http server that checks things  we care about and returns `200 OK`/`500 Internal Server Error` we will be in a better position to use raw ec2/kubernetes/etc.

**Comment by awang** [comment]
okay to close now that we have https://materialize.io/docs/monitoring/?

**Comment by benesch** [comment]
I think this is about tools (EC2/k10s) that need an automated way to ask Materialize if it's healthy with a binary yes/no response, whereas the dashboard is more about humans visually inspecting graphs to determine if Materialize is healthy.
