### ISSUE TITLE
[persisted source ts] Downgrade since of timestamp collections

### ISSUE THREAD

**Issue by cjubb39** [MaterializeInc/materialize#12267]
Currently, we don't downgrade the `since` -- as doing so correctly requires watching the progress of the `since` of the actual data collection.  Follow-up to #11911 which won't contain this functionality

**Comment by elindsey** [comment]
@cjubb39 is the net effect of this that we may compact away source data but not compact the corresponding ts data? Are there other implications?

**Comment by aljoscha** [comment]
This is now outdated, and we do have compaction of the remap shard.
