### ISSUE TITLE
cluster isolation: the SELECT part of an INSERT ... SELECT is run by the default cluster

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#12294]
### What version of Materialize are you using?

v0.26.1-dev (9bec4dc26)

### How did you install Materialize?

Docker image

### What was the issue?

The test case from #12251 causes the computed of the default cluster to panic, even though the test explicitly sets `SET cluster=cluster1`:

```
> SET cluster=cluster1

> CREATE TABLE log_table (f1 TEXT);

> CREATE TABLE panic_table (f1 TEXT);

> INSERT INTO panic_table VALUES ('panic!');

> INSERT INTO log_table SELECT mz_internal.mz_panic(f1) FROM panic_table;
```

I would have expected that the `SELECT` will be run by `cluster` and cause the panic to happen there.

**Comment by sploiselle** [comment]
I believe there is an issue here, but the issue is not that the default cluster is running the panicking query.

All of this comes from running `bin/cluster-dev`.

Running this set of SQL:

```
create cluster foo replica bar (size '1');
set cluster to foo;
CREATE TABLE log_table (f1 TEXT);
CREATE TABLE panic_table (f1 TEXT);
INSERT INTO panic_table VALUES ('panic!');
INSERT INTO log_table SELECT mz_internal.mz_panic(f1) FROM panic_table;
```

These are the logs from the `foo` cluster's replica:

```
┌────────────────────────────── Logs(default/compute-cluster-2-replica-2-0:default)[1m] ───────────────────────────────┐
│                           Autoscroll:On     FullScreen:Off     Timestamps:Off     Wrap:Off                           │
│ computed: 2022-05-19T14:27:13.576709Z  INFO computed: about to bind to "0.0.0.0:2100"                                │
│ computed: 2022-05-19T14:27:13.576811Z  INFO computed: listening for coordinator connection on 0.0.0.0:2100...        │
│ computed: 2022-05-19T14:27:13.576830Z  INFO computed: serving computed HTTP server on 0.0.0.0:6875                   │
│ computed: 2022-05-19T14:27:13.577144Z  INFO mz_storage::boundary::tcp_boundary::client: About to connect to "storage │
│ computed: 2022-05-19T14:27:13.578379Z  INFO mz_storage::boundary::tcp_boundary::client: Connected to storage server  │
│ computed: 2022-05-19T14:27:43.099426Z  INFO computed: coordinator connection accepted                                │
│ thread 'timely:work-0' panicked at 'panic!', src/expr/src/scalar/func/impls/string.rs:717:9                          │
│ note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace                                        │
│ computed: 2022-05-19T14:28:20.261174Z  WARN mz_storage::boundary::tcp_boundary::client: Receiver hung up             │
│ computed: 2022-05-19T14:28:20.262756Z  INFO computed: coordinator connection gone; lingering                         │
│ computed: 2022-05-19T14:28:20.267009Z  INFO computed: coordinator connection accepted
```

So you can see here that the panic definitely occurs on the non-default cluster.

If I watch the logs from the default replica while running the same workload, I get:

```
┌────────────────────────────── Logs(default/compute-cluster-1-replica-1-0:default)[1m] ───────────────────────────────┐
│                           Autoscroll:On     FullScreen:Off     Timestamps:Off     Wrap:Off                           │
│ computed: 2022-05-19T14:35:42.057021Z  INFO computed: about to bind to "0.0.0.0:2100"                                │
│ computed: 2022-05-19T14:35:42.057133Z  INFO computed: listening for coordinator connection on 0.0.0.0:2100...        │
│ computed: 2022-05-19T14:35:42.057146Z  INFO computed: serving computed HTTP server on 0.0.0.0:6875                   │
│ computed: 2022-05-19T14:35:42.057475Z  INFO mz_storage::boundary::tcp_boundary::client: About to connect to "storage │
│ computed: 2022-05-19T14:35:42.058731Z  INFO mz_storage::boundary::tcp_boundary::client: Connected to storage server  │
│ computed: 2022-05-19T14:36:11.620895Z  INFO computed: coordinator connection accepted                                │
│                                                                                                                      │
```

Nothing occurs here.

However, when MZ is in a state where a cluster's replicas are crash looping, I can no longer e.g. get the logs from the default cluster if I stop watching them and try again. It behaves as if the crash looping cluster is dominating all of the resources available.

`k9s` also does not register that the crash-looping replica is crash looping, and doesn't report any restarts:
```
│ default       compute-cluster-2-replica-2-0      ●   1/1            0 Running   172.17.0.7     minikube    6m46s     │
```

I'm unfamiliar with `bin/cluster-dev`'s and K8's architectures, but it seems like the panicking replica isn't failing from K8's perspective.

**Comment by sploiselle** [comment]
At least part of this lack of responsiveness is that timely threads panic independently of `computed`, which means that the panicking invocation does not cause `computed` to fail, but does cause it to "internally crash loop. This seems to affect the performance of the system when all of the resources (i.e. replicas) are running locally.

This seems to take a step toward providing the behavior I expected:
```diff
diff --git a/src/compute/src/server.rs b/src/compute/src/server.rs
index b34fac761..bdb1348fa 100644
--- a/src/compute/src/server.rs
+++ b/src/compute/src/server.rs
@@ -157,6 +157,7 @@ where
 {
     /// Draws from `dataflow_command_receiver` until shutdown.
     fn run(&mut self) {
+        mz_ore::panic::set_abort_on_panic();
         let mut shutdown = false;
         while !shutdown {
             // Enable trace compaction.
 ```
 
 However, I am _not_ advocating for this as a solution, just reporting my investigation.

**Comment by sploiselle** [comment]
I filed #12583 to track the above issues, and I'm curious if resolving that resolves the issues @philip-stoev saw that caused him to conclude the the default cluster was the one panicking. Phillip, do you recall how you assessed which cluster panicked?

**Comment by philip-stoev** [comment]
I am not sure what happened here, but this is no longer reproducible. The panic happens on the exected computed. So closing this and apologies for the wild goose chase :-(
