### ISSUE TITLE
[Epic] Support GRPC as a transport layer for the compute command protocol

### ISSUE THREAD

**Issue by antiguru** [MaterializeInc/materialize#12292]
Currently, the compute command protocol is send over the network using the `framed` encoding. In the future, we would like to switch to a transport layer with more features, such as retries and reconnects. GRPC seems to fill this niche, with [tonic](https://crates.io/crates/tonic) providing an implementation for Rust.

### Goals

* Use gRPC and Protobuf types for compute command network protocol

### Non-Goals

* Use gRPC for _all_ network protocols

### Acceptance Criteria

The compute command protocol uses gRPC via [tonic](https://crates.io/crates/tonic). External behavior of participating processes is unchanged.

### Subtasks

- [x] #12516
- [x] Coordinate with storage team on other protocols

### Testing

GRPC/Protobuf testing will be implemented in the context of the upgrade testing, even though that will only cover "upgrades" from the current version to the current version at this time

- #12758

### Open Questions

* When to reconnect and when to die?
* Do gRPC streams fullfil all use cases we are targeting? Do we need an alternative approach such as having two separate server/client gRPC endpoints?
* How will reconciliation affect this?
* Do we need to support i64 as timestamp? @mjibson

### Resolved Questions

* Do we need support for TLS? No - kubernetes will automatically encrypt connections

### Related

* #11242 
* **Protobuf support**: #11735, #12358
* **Observability**: blocks #12230

**Comment by aalexandrov** [comment]
@uce can you assign this to the right epic?

**Comment by lluki** [comment]
Sorry, i had a "fixes" in the PR. I reopen it.
