### ISSUE TITLE
Won't the data in this table be persisted?   

### ISSUE THREAD

**Issue by ansjsun** [MaterializeInc/materialize#12312]
### Goal(s)

cargo build --release
and run
./materialized  
I used pg-cli 
create table person; and insert some data ;
but when restart server.
the table of person is empty. count is 0.

**Comment by philip-stoev** [comment]
@ansjsun Which version of materialized are you using? If using the `v0.26.1 LTS` version from the web site, you will need to start materialized with `--experimental --persistent-user-tables` to make sure the data in the tables survives a restart. As signified by the need for the `--experimental` flag, this is an experimental feature.

**Comment by ansjsun** [comment]
@philip-stoev thx , I build it by `main` branch , it version is `materialized v0.22.1-dev` .
I tried the v0.26 version with no problems
