### ISSUE TITLE
SELECT over a "cheap" view never returns until a more "expensive" dataflow has fully completed

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#12331]
### What version of Materialize are you using?

v0.26.1-dev (cfb711954)

### How did you install Materialize?

Built from source

### What was the issue?

I understand that timely is cooperatively scheduled, not guaranteed to be fair, and relying on the operators to yield on their own, but the following behavior appears to be pathological to me even in the above constraints:

```
\timing on
DROP SCHEMA IF EXISTS public CASCADE;
CREATE SCHEMA public;
CREATE TABLE large (f1 TEXT);
INSERT INTO large SELECT 'x' || generate_series::text FROM generate_series(1, 1000000);

CREATE TABLE small (f2 TEXT);
INSERT INTO small VALUES ('a');

CREATE MATERIALIZED VIEW expensive AS SELECT REPEAT(f1, 10000) LIKE '%y' FROM large;
CREATE MATERIALIZED VIEW cheap AS SELECT COUNT(*) FROM small;
SELECT * FROM cheap;
 count 
-------
     1
(1 row)

Time: 57692.015 ms (00:57.692)

```

In other words, it takes ~1 min calculate `COUNT(*)` over a one-row table and it only returns after the **entirety** of the `expensive` dataflow has been processed, as evidenced by the fact that, by the time the `SELECT` returns, CPU usage immediately goes down to zero.

I think the test case is realistic because:
- this does not use `mz_sleep` - a `LIKE` pattern is legitimately allowed to be unlucky and have nontrivial execution time
- the large table has 1M rows, so plenty of opportunity to yield
- the small table has 1 row, so it should have been possible to evaluate it before the expensive dataflow has run to completion.

I ran this with 1 and 4 workers, on Platform and on v0.26.1, with base tables and with kafka sources, and the behavior is the same.

I would have expected something more along the lines of:
- the `COUNT(*)` is given an opportunity to execute at some point and the `SELECT` against the cheap view is given the opportunity to return
- the `expensive` dataflow can then take its time and continue calculating

**Comment by philip-stoev** [comment]
Test case that does not use base tables:

```
$ set schema={
        "type" : "record",
        "name" : "test",
        "fields" : [
            {"name":"f1", "type":"string"}
        ]
    }

$ kafka-create-topic topic=small

$ kafka-create-topic topic=large

$ kafka-ingest format=avro topic=small schema=${schema} publish=true repeat=1
{"f1": " ${kafka-ingest.iteration}"}

$ kafka-ingest format=avro topic=large schema=${schema} publish=true repeat=1000000
{"f1": " ${kafka-ingest.iteration}"}

> CREATE MATERIALIZED SOURCE small
  FROM KAFKA BROKER '${testdrive.kafka-addr}' TOPIC
  'testdrive-small-${testdrive.seed}'
  FORMAT AVRO USING CONFLUENT SCHEMA REGISTRY '${testdrive.schema-registry-url}'
  ENVELOPE NONE

> CREATE MATERIALIZED SOURCE large
  FROM KAFKA BROKER '${testdrive.kafka-addr}' TOPIC
  'testdrive-large-${testdrive.seed}'
  FORMAT AVRO USING CONFLUENT SCHEMA REGISTRY '${testdrive.schema-registry-url}'
  ENVELOPE NONE

> SELECT COUNT(*) = 1 FROM small
true

> SELECT COUNT(*) = 1000000 FROM large
true

> CREATE MATERIALIZED VIEW expensive AS SELECT REPEAT(f1, 10000) LIKE '%y' FROM large;

> CREATE MATERIALIZED VIEW cheap AS SELECT COUNT(*) FROM small;

> SELECT * FROM cheap;
1
```

**Comment by frankmcsherry** [comment]
I believe this may be the same issue as called out in https://github.com/MaterializeInc/materialize/issues/8853.

**Comment by philip-stoev** [comment]
The plan in this case has a `Map` : 
``` | Get materialize.public.large (u3)+
 | Map "%y" ~~(repeat(#0, 10000))   +
 | Project (#1)                     +
```

**Comment by frankmcsherry** [comment]
Sorry, I should have said more. The issue in https://github.com/MaterializeInc/materialize/issues/8853 is that our operators are cooperatively scheduled and while they could be reimplemented to yield more frequently, they are not currently implemented this way. This is true of many operators implemented atop `unary_fallible`. That method could potentially be generalized to yield after some amount of time, records, etc., in the ways that some of our other operators have. That is the class of work to be done in https://github.com/MaterializeInc/materialize/issues/8853.

**Comment by philip-stoev** [comment]
This ticket does not bring any value over #8853, so I am closing it.
