### ISSUE TITLE
Add Protobuf support for `SourceDesc` and `SinkDesc`

### ISSUE THREAD

**Issue by aalexandrov** [MaterializeInc/materialize#12358]
Add Protobuf support for `mz_dataflow_types::SourceDesc` and `mz_dataflow_types::SinkDesc` and (transitively) required types.

## List of types
_(includes repeated types)_
- [x] SourceDesc
    - [x] SourceConnector
        - [x] ExternalSourceConnector
            - [x] KafkaSourceConnector
                - [x] KafkaAddrs
                - [x] IncludedColumnPos
            - [x] KinesisSourceConnector
                - [x] AwsConfig
                    - [x] AwsCredentials
                    - [x] AwsAssumeRole
                    - [x] SerdeUri
            - [x] S3SourceConnector
                - [x] S3KeySource
                - [x] Glob
                - [x] AwsConfig
                - [x] Compression
            - [x] PostgresSourceConnector
                - [x] PostgresSourceDetails
            - [x] PubNubSourceConnector
            - [x] PersistSourceConnector
                - [x] ShardId
        - [x] encoding::SourceDataEncoding
            - [x] DataEncoding
                - [x] AvroEncoding
                    - [x] Url
                    - [x] Certificate
                    - [x] Identity
                    - [x] Auth
                - [x] ProtobufEncoding
                - [x] CsvEncoding
                    - [x] ColumnSpec
                - [x] RegexEncoding
                    - [x] mz_repr::adt::regex::Regex
                - [x] RelationDesc
                    - [x] RelationType
                        - [x] ColumnType
                    - [x] ColumnName
        - [x] SourceEnvelope
            - [x] KeyEnvelope
            - [x] DebeziumEnvelope
                - [x] DebeziumMode
                    - [x] DebeziumDedupProjection
                        - [x] DebeziumSourceProjection
                        - [x] DebeziumTransactionMetadata
                            - [x] GlobalId
                    - [x] NaiveDateTime
            - [x] UpsertEnvelope
                - [x] UpsertStyle
                    - [x] KeyEnvelope
        - [x] IncludedColumnSource
        - [x] Duration
        - [x] Timeline
    - [x] RelationDesc
        - [x] RelationType
        - [x] ColumnName
- [x] SinkDesc
    - [x] GlobalId
    - [x] RelationDesc
    - [x] SinkConnector
        - [x] KafkaSinkConnector
            - [x] KafkaAddrs
            - [x] RelationDesc
            - [x] PublishedSchemaInfo
            - [x] KafkaSinkConsistencyConnector
            - [x] GlobalId
        - [x] TailSinkConnector
        - [x] PersistSinkConnector
            - [x] RelationDesc
            - [x] ShardId
    - [x] SinkEnvelope
    - [x] SinkAsOf
        - [x] Antichain<mz_repr::Timestamp>

**Comment by andrioni** [comment]
Closed by #12573, #12656 and #12676.
