### ISSUE TITLE
Support AWS Kinesis as a Materialize source

### ISSUE THREAD

**Issue by rjnn** [MaterializeInc/materialize#1239]
This is not actively scheduled, but I wanted to open an issue to refer back to it.

**Comment by JLDLaughlin** [comment]
A few notes:

- Updated the name of this ticket. Supporting Kinesis as "a streaming source on par with Kafka" is a moving target and, therefore, sort of an uncloseable ticket. Instead, explicitly want to use this ticket for tracking Kinesis V0 support and calling out next steps.

- V0 of Kinesis sources will be making it into the next release (`v0.1.3`)! Anything under `Future Improvements` above will be considered and worked on for future releases. 

So I'm going to close this ticket! Both user feedback and personal experience should dictate the order of the next tickets. For posterity, the next tickets I'm planning on working on are: testing, documentation, and supporting reading from multiple partitions.
