### ISSUE TITLE
`mz_catalog`: expose object dependencies in the system catalog

### ISSUE THREAD

**Issue by morsapaes** [MaterializeInc/materialize#12390]
### Feature request

It could be useful to provide an additional system catalog table that records dependencies between database objects. From @benesch: "We probably want to introduce `mz_depend`, a la [`pg_depend`](https://www.postgresql.org/docs/current/catalog-pg-depend.html)".

As an example, I was half expecting to find a `sink->object` mapping in `mz_sinks` while hacking something up for our dbt adapter.

**Comment by frankmcsherry** [comment]
We have two tables that do this for compute introspection sources: `mz_view_keys` and `mz_view_foreign_keys`. Those names seem a bit suspect, and I suspect their contents may not necessarily be up to date.

**Comment by frankmcsherry** [comment]
Related: https://github.com/MaterializeInc/materialize/issues/15037

**Comment by frankmcsherry** [comment]
Ah, I think I misunderstood the request! We have a different table that does this for compute: https://materialize.com/docs/sql/system-catalog/mz_internal/#mz_worker_compute_dependencies. It made a lot more sense in the binary where it referenced all views, but is now a replica local thing. But if you get the coordinator / controller to populate it instead, it is plausibly the right shape of thing. We use it for tracking down propagation delays in dataflows.

**Comment by benesch** [comment]
Here's a quick sketch of a design, written in terms of what we'd add to the user-facing docs.

----

### `mz_dependencies`

The `mz_dependencies` table contains a row for each dependency between database objects in the system.

Field         | Type       | Meaning
--------------|------------|--------
`depender_id` | [`text`] | The ID of the database object that depends on `dependee_id`. Corresponds to [`mz_objects.id`](#mz_objects).
`dependee_id`  | [`text`] | The ID of the database object that is depended upon by `depender_id`. Corresponds to [`mz_objects.id`](#mz_objects).

----

Column names subject to bikeshedding. "depender" and "dependee" aren't really English words, but they are much less confusing than "dependent", IMO.
