### ISSUE TITLE
cluster isolation: loss of interactivity across the entire instance with if one large cluster is running

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#12403]
### What version of Materialize are you using?

v0.26.1-dev (2b3f712dd)

### How did you install Materialize?

Docker image

### What is the issue?

Starting a healthy, non-panicking 32-node cluster results in the following symptoms:

- that cluster is unable to run any queries
- it is also very slow to process a Ctrl+Z request 

This on is own is worrisome, but the cluster isolation problem is that:
- Mz starts being very slow when accepting new incoming SQL connections taking up to 3 seconds to do so
- running `SELECT`s on the default, single-node cluster is also arbitrary slow , e.g. 7 seconds.

There is plenty of memory available and the CPU is idle at all times. No errors in the logs.

To reproduce:

1. Start a 32-node cluster:
```
bin/mzcompose --find limits run instance-size --clusters 1 --nodes 32 --workers 4 --replicas 1 
```
2. docker-compose may struggle a bit, but will eventually start all the required containers. If it fails after having started all the computeds but before it was able to issue a `CREATE CLUSTER`, help it along:
```
CREATE CLUSTER cluster_0 REPLICA replica_0_0 (REMOTE ("computed_0_0_0:2100", "computed_0_0_1:2100", "computed_0_0_2:2100", "computed_0_0_3:2100", "computed_0_0_4:2100", "computed_0_0_5:2100", "computed_0_0_6:2100", "computed_0_0_7:2100", "computed_0_0_8:2100", "computed_0_0_9:2100", "computed_0_0_10:2100", "computed_0_0_11:2100", "computed_0_0_12:2100", "computed_0_0_13:2100", "computed_0_0_14:2100", "computed_0_0_15:2100", "computed_0_0_16:2100", "computed_0_0_17:2100", "computed_0_0_18:2100", "computed_0_0_19:2100", "computed_0_0_20:2100", "computed_0_0_21:2100", "computed_0_0_22:2100", "computed_0_0_23:2100", "computed_0_0_24:2100", "computed_0_0_25:2100", "computed_0_0_26:2100", "computed_0_0_27:2100", "computed_0_0_28:2100", "computed_0_0_29:2100", "computed_0_0_30:2100", "computed_0_0_31:2100"));
```

3. At that point, Mz will become sluggish:

```
echo "SELECT 1;" | time psql -p 49468 -h 127.0.0.1 -U materialize
 ?column? 
----------
        1
(1 row)

0:03.07elapsed
```

and

```
echo "SELECT * FROM t1;" | time psql -p 49468 -h 127.0.0.1 -U materialize
 f1 
----
(0 rows)

0:07.28elapsed
```

and

```
\timing on
materialize=> SHOW CLUSTERS;
^[[A
   name    
-----------
 cluster_0
 default
(2 rows)

Time: 53758.092 ms (00:53.758)
```

will hang even if run against the default cluster. Running SQL against the `cluster_0` will also hang.

4. Observe that there have been no crashes in any container:
```
pstoev@Ubuntu-2004-focal-64-minimal:~/materialize$ docker ps  | grep computed | wc
     32     544    8278
```

**Comment by philip-stoev** [comment]
Not reproducible on the cloud with `2xlarge`. I could not try `4xlarge` because it never came up for me. Still worth trying the mzcompose test I think.

**Comment by antiguru** [comment]
I can observe that the configuration above is slow or doesn't respond when querying `cluster_0`. Querying the default cluster is usually fast, but can also take a moment. I'll keep digging to find out more.

Note to self: The testdrive hangs in `docker-compose port materialized 6875`. In order to proceed, use `docker ps` to determine the materialized port, and connect manually using `psql`.

**Comment by antiguru** [comment]
When running materialize outside of docker, it can start 32 processes of 4 workers each (minus port exhaustion, which needs to be fixed). Even though my machine has significantly less CPUs, it still works fine and doesn't show the hiccups that the docker-variant has. Concluding from this, I'd say it's likely an interaction of how docker constructs containers and how they interact with each other. Regarding the priority of this issue, we should check and see how this configuration behaves on a kubernetes cluster.

**Comment by philip-stoev** [comment]
@antiguru thanks for checking this out. I am assigning this back to myself to re-test as soon as 32-node clusters become possible in Kubernetes.

**Comment by benesch** [comment]
@philip-stoev: I think we can close this! We've done some light testing of 6xlarge in cloud, and they basically work, and there is no perf hit to envd while they are running. Would you like to do any additional testing to verify?
