### ISSUE TITLE
Support for SASL_SSL / SCRAM-SHA-256

### ISSUE THREAD

**Issue by heeringa** [MaterializeInc/materialize#12401]
### What version of Materialize are you using?

 v0.26.1-dev (3fcd00c07)

### How did you install Materialize?

Materialize Cloud

### What is the issue?

I was using Upstash as a managed Kafka Broker.  The [documentation and integration](https://docs.upstash.com/kafka/howto/connect-with-clients) guides suggest using `SASL_SSL` as the security protocol and `SCRAM-SHA-256` as the sasl mechanisms.

I tried doing this with the following `CREATE SOURCE` command

```
materialize=> create source upstash
from kafka broker 'honest-prawn-11405-us1-kafka.upstash.io:9092' topic 'primary-data' WITH (
      security_protocol = 'SASL_SSL',
      sasl_mechanisms = 'SCRAM-SHA-256',
      sasl_username = <REMOVED>,
      sasl_password = <REMOVED> 
  )
FORMAT BYTES;
```

which fails with the following:

```
ERROR:  Failed to create and connect Kafka consumer: Client creation error: No provider for SASL mechanism SCRAM-SHA-256: recompile librdkafka with libsasl2 or openssl support. Current build options: PLAIN
```

Switching `sasl_mechanisms = 'PLAIN'` did not solve the problem either:

```
ERROR:  Failed to create and connect Kafka consumer: librdkafka: [thrd:sasl_ssl://honest-prawn-11405-us1-kafka.upstash.io:9092/bootstr]: sasl_ssl://honest-prawn-11405-us1-kafka.upstash.io:9092/bootstrap: SASL authentication error: Authentication failed: Invalid username or password (after 208ms in state AUTH_REQ)
```

but removing both `sasl_mechanisms` and `security_protocol` did work:

```
materialize=> create source upstash
from kafka broker 'honest-prawn-11405-us1-kafka.upstash.io:9092' topic 'primary-data' WITH (
      sasl_username = <REMOVED>,
      sasl_password = <REMOVED>
  )
FORMAT BYTES;
CREATE SOURCE
```

My issue is that `SASL_SSL` as the security protocol and `SCRAM-SHA-256` as the sasl mechanisms should work according to our documentation.

**Comment by heeringa** [comment]
@elindsey - assigning to you to triage!  Let me know if that's the *wrong* next step!  :)

**Comment by elindsey** [comment]
@heeringa it'd be ideal to dump it on the Storage project board so it lands in the triage queue next time, but assigning to me works too. 🙂

**Comment by benesch** [comment]
I just looked at this for a second and it seems like a simple fix. Looks like the split of `storaged`/`computed`/`materialized` results in librdkafka getting compiled with different options in different binaries (!), and one of those binaries is not getting SCRAM support compiled in. I'll take this one since I've got all the context paged in already.

**Comment by JLDLaughlin** [comment]
we just hit this in cloud testing!

**Comment by benesch** [comment]
Will be fixed by #13024, but didn't have time to write a test, so leaving this open for now.

**Comment by bobbyiliev** [comment]
Neat! Just tested this and it seems to be working as expected now! Thank you @benesch!

**Comment by nmeagan11** [comment]
Is this issue complete? If so, can we close?

**Comment by benesch** [comment]
This still needs a test, unfortunately!

**Comment by philip-stoev** [comment]
I tried a quick and dirty copy of the `kafka-sasl-plain` workflow, however unfortunately Zookeeper does not support SCRAM so the Confluent services could not connect to each other :-( . I also could not find a single-one liner for Redpanda that would work.

I am afraid I do not have any bandwidth left to beat on this any further. The Storage team would need to own the test.

**Comment by benesch** [comment]
At long last, https://github.com/MaterializeInc/materialize/pull/22945 adds a test for this.
