### ISSUE TITLE
chbench: fancy orderline

### ISSUE THREAD

**Issue by quodlibetor** [MaterializeInc/materialize#1241]
Our chbench schema should look like:

```text
OL_O_ID         10,000,000 unique IDs
OL_D_ID         20 unique IDs
OL_W_ID         2*W unique IDs
OL_NUMBER       15 unique IDs
OL_I_ID         200,000 unique IDs
OL_SUPPLY_W_ID  2*W unique IDs
OL_DELIVERY_D   date and time, or null
OL_QUANTITY     numeric(2)
OL_AMOUNT       signed  numeric(6, 2)
OL_DIST_INFO    fixed text, size 24
```

In order of priority:

* getting OL_DELIVERY_DAY dates to be spread out over a year, or a user-specified time range.
* ensuring that all those things which claim to be N unique IDs are actually unique IDs from a pool of that size (starting with the ones with the smallest size, so `OL_NUMBER` then `OL_D_ID`, etc.
* OL_QUANTITY and OL_AMOUNT to support a finite range to select from (e.g. OL_QUANTITY is always between 1 and 500) just defaulting to a normal distribution.

**Comment by sploiselle** [comment]
No one has any plans in the foreseeable future to work on `chbench` and our other load generator sources (e.g. auctions) fill a lot of the roles mentioned in this set of issues.
