### ISSUE TITLE
sql: remove disable user indexes mode

### ISSUE THREAD

**Issue by benesch** [MaterializeInc/materialize#12412]
[Disable user indexes mode](https://materialize.com/docs/cli/#disable-user-indexes) has been obsoleted by clusters. We should remove it!

Background: disable user indexes mode was introduced to allow users to repair a `materialized` instance that was repeatedly OOMing due to an index. Users could boot Materialize with `--disable-user-indexes`, drop the expensive index, and then reboot Materialize without `--disable-user-indexes` to regain a functional system. But now that clusters run in their own processes that are isolated from the main `materialized` process, this is no longer an issue—users will always be able to drop indexes that are crashing their clusters, even if those clusters are unavailable.

**Comment by sploiselle** [comment]
Closed by #12414
