### ISSUE TITLE
Remove CONFLUENT from SCHEMA REGISTRY portion of statements

### ISSUE THREAD

**Issue by nharring-adjacent** [MaterializeInc/materialize#12426]
### Feature request

The CONFLUENT keyword is redundant due to the de facto standard status of the confluent API and it is a pretty long word to type without needing to. Should a future standard emerge as a contender it would be easy to add an optional property onto the SCHEMA REGISTRY clause which defaults to CONFLUENT but allows for other protocols to be supported.

**Comment by sploiselle** [comment]
This issue would be challenging to close by simply removing the keyword because of e.g. #12304 (h/t @andrioni)

**Comment by aljoscha** [comment]
the ship has probably sailed for this one? I'm inclined to just close it, in an effort to clean out our "Icebox".

cc @nmeagan11 or @uce
