### ISSUE TITLE
Migrate S3 source to path based configurations

### ISSUE THREAD

**Issue by sjwiesman** [MaterializeInc/materialize#12431]
### Feature request

The S3 syntax is very verbose, and I believe there are some easy wins to improve usability. This ticket builds on the ongoing connector work for handling credentials. 

While **S3 is not a filesystem**, it is widely understood as looking like one, especially within the dataspace. The core of my proposal is to make it look more like a file system source. Additionally, I believe all paths should follow the semantics of `MATCHING`. The matching characters are not valid object paths, so it is not ambiguous. Both these semantics have prior art in Spark, Flink, and many AWS products. 

```
CREATE SOURCE foo
FROM S3 CONNECTOR aws_connector 
PATH 's3://bucket/**/*.csv'
FORMAT BYTES;
```

If desired, we could retain the ability for one source to consume from multiple buckets by also supporting a PATH**S** option, which takes a list of paths. Though I'm dubious about how important this actually is to people. You can always union multiple sources together. 

Finally, I find SQS fine from a syntax perspective. The usability is still not great because one topic cannot be reused, but I'll consider that outside the scope of this issue 😉

**Comment by petrosagg** [comment]
Closing until we re-implement S3 sources
