### ISSUE TITLE
S3 source cannot read from a public bucket

### ISSUE THREAD

**Issue by sjwiesman** [MaterializeInc/materialize#12445]
### What version of Materialize are you using?

v0.26

### How did you install Materialize?

Docker image

### What is the issue?

The S3 source cannot read from public buckets. Amazon has a number of public S3 datasets that Materialize should be able to use. 

https://registry.opendata.aws

**Comment by sjwiesman** [comment]
I'm thinking this is a bug, but you could also make a case this is a feature. The problem is that public datasets are how many people test out the S3 source and so from their perspective it seems the source doesn't work.

**Comment by guswynn** [comment]
s3 sources have been deleted, and will likely be very different when we bring them back! we can reopen if we see this issue again!
