### ISSUE TITLE
chbench: support `--speedup` for timestamps

### ISSUE THREAD

**Issue by quodlibetor** [MaterializeInc/materialize#1246]
Most interesting analyses require time data to be spread out over more than the minutes to days that we run our load tests/demos for. It would be great to be able to generate a years worth of fake data in an hour by adding a `--speedup 8766` cli flag to chbench.

Optionally, allowing a start date to be set could be somewhat interesting.

**Comment by sploiselle** [comment]
No one has any plans in the foreseeable future to work on `chbench` and our other load generator sources (e.g. auctions) fill a lot of the roles mentioned in this set of issues.
