### ISSUE TITLE
Support postgres-style arrays

### ISSUE THREAD

**Issue by jamii** [MaterializeInc/materialize#1248]
Forked from https://github.com/MaterializeInc/materialize/issues/1133

Support typed multidimensional arrays following the [postgres api](https://www.postgresql.org/docs/current/arrays.html). 

Rough todo:

* [x] Sqlparser needs to parse array types and literals correctly (currently fails on eg `array[1+1]`)
* [x] ~Row already supports serializing arrays, but for postgres-style arrays we need a separate type that includes dimension information.~ Since we're only supporting 1d arrays we can reuse DatumList. 
* [x] Add ScalarType::Array
  * [x] Deal with the fallout from ScalarType no longer being Copy
* [ ] Implement all the basic array functions
  * [x] Subscript elements
  * [ ] Subscript slice
* [ ] Implement casts from text to arrays (requires a simple parser; should be roughly equivalent to, if not the same as, lists)
* [ ] Infer types for array literals and functions
  * [ ] Handle the awkward edge case where we can sometimes infer a type for `ARRAY[]`
* [ ] Figure out how to pass arrays over pgwire. This is complicated because the existing array support is basically just a boolean "is this an array" flag so can't handle nested arrays. 
* [ ] Turn on the cockroachdb array tests

**Comment by jamii** [comment]
After talking to @justinj I decided to just do 1d arrays, because the semantics for multi-dimensional arrays are hard to implement and not very useful. 

It might be possible to support nested arrays instead, although postgres kind of backs us into a corner there.

**Comment by rjnn** [comment]
What about the multidimensional avro sources?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jamii** [comment]
The postgres api doesn't support them unless they are rectangular.

**Comment by rjnn** [comment]
I'm happy with any solution that allows us to ingest nested avro types - if that is nested arrays, i'm fine with that.

**Comment by benesch** [comment]
This has largely been completed. There are more specific follow-ups for everything that remains.
