### ISSUE TITLE
Replica-targeted SELECTs

### ISSUE THREAD

**Issue by teskje** [MaterializeInc/materialize#12520]
## Feature request

Allow targeting SELECT queries to specific replicas. This will enable collecting useful compute introspection data in the face of replication.

This is meant as a stop-gap measure for making compute introspection work again for M1. The approach is relatively easy to implement but involves a number of drawbacks:
- Users are not able to join introspection data from multiple replicas in SQL.
- If a replica doesn’t respond to compute commands, introspection data is not available.
- Replica-targeted queries are controlled by a session variable, which introduces semi-obvious state, which might be confusing to users.

Finding a proper solution is tracked by #11782. It is currently blocked by the missing support for STORAGE compaction. 

### User Interface / SQL

Introduce a `cluster_replica` session variable that, if set, causes all SELECT queries to be directed to the specified replica. Only SELECT queries are affected by this selector. DDL statements for creating views and sinks continue to be executed on all replicas of the current cluster.

It is possible that dropping a replica while a SELECT/Peek is still pending for its response will make the request never return. We accept this as a known limitation.

Querying introspection sources is only allowed a) on single-replica clusters or b) if `cluster_replica` is set.

### Compute Controller

`ComputeCommand::Peek` receives a new field `target_replica: Option<ReplicaId>` that determines whether a Peek should be replica-specific or not. Peeks that have an `target_replica` specified are only handled by the specified replica.

The higher-level compute controller methods that (transitively) create a Peek command are extended by a new `target_replica` argument. ADAPTER uses this argument to direct compute peeks to specific replicas.

### Tasks

* [x] Enable targeting replicas via `cluster_replica` (#12568)
* [x] Disallow untargeted SELECTs on introspection sources (#12637)

**Comment by benesch** [comment]
This seems like a great stopgap solution!

One quick request: please call the session variable `cluster_replica` rather than `replica`! Trying to avoid use of the unqualified term "replica" to mean "compute replica", because we might want "source replicas" and "sink replicas" down the line.

**Comment by teskje** [comment]
Of course, thanks for catching this!

**Comment by antiguru** [comment]
> * Do we want to disallow SELECTs that depend on introspection sources if `cluster_replica` is not set? This would require us to analyze the dependencies of SELECTs accordingly, which might be non-trivial.

Not all clusters will be replicated. Requiring a `cluster_replica` session variable even if there's a single replica seems odd and adds a surprising layer of complexity I think. For the same reason, I think we should not analyze SQL queries for what kind of dependencies they have -- it adds debatable value to the user but creates a subtle maintenance burden for us.

**Comment by teskje** [comment]
That makes sense to me. Are we fine with the possibility that users might try to query introspection data on a multi-replica cluster without setting a target replica, and potentially receive inconsistent responses?

**Comment by benesch** [comment]
But the results are totally undefined if you query an introspection source on a cluster that has more than one replica, no? I'm strongly 👍🏽 on requiring `cluster_replica` when:

  * The query depends on at least one introspection source
  * The active cluster has more than one replica

It'd be quite easy to write the logic to check for this. It'd look similar to how `uses_tables`:

https://github.com/MaterializeInc/materialize/blob/ece5a520277980d57de8b7301f9267b642676f46/src/coord/src/coord.rs#L3472
