### ISSUE TITLE
In testdrive, allow publishing a schema, then creating a SQL statement that is able to interpolate the ID of that statement.

### ISSUE THREAD

**Issue by umanwizard** [MaterializeInc/materialize#12539]
### Feature request

Slack discussion here: https://materializeinc.slack.com/archives/C01LKF361MZ/p1652824993925139

Cc @guswynn

**Comment by guswynn** [comment]
After some discussion, we determined it may also be required to switch testdrive to parse-and-run _1_ statement at a time, so variable interpolation can happen at runtime!

to make this easier, we also decided it may be nice to just remove the concept of `Action::undo` and move the 3 non-trivial implementation of that into reset

**Comment by bkirwi** [comment]
This exists as `set-from-sql` AIUI! https://github.com/MaterializeInc/materialize/blob/5696f1f63adc3edc162ca1171a0dcbad76b44c5f/doc/developer/testdrive.md#-set-from-sql-varname
