### ISSUE TITLE
SET: Retain type information during planning

### ISSUE THREAD

**Issue by teskje** [MaterializeInc/materialize#12545]
#### The Problem

When planning the `SET <variable> = <value>` statement, [we currently always cast `value` to a string](https://github.com/MaterializeInc/materialize/blob/c0236926fb962a5ba4b389fd3195d6863e86e122/src/sql/src/plan/statement/scl.rs#L50-L54). This makes at least two desirable features impossible to implement:

- Optional string variables: `SET <variable> = NULL`
- Resetting string variables: `SET <variable> = DEFAULT` (see [Postgres docs](https://www.postgresql.org/docs/current/sql-set.html))

In both cases, it is not possible during planning to differentiate between the keyword (`NULL`/`DEFAULT`) and the string value (`'NULL'`/`'DEFAULT'`).

#### Proposed Solution

I propose that we retain the type information of variable values when parsing `SET` statements through planning. This way, variable parsing code is able to differentiate between literals, keywords, and identifiers.

Note that this is a breaking syntax change. This statement is currently valid:
```sql
SET cluster = foo;
```
After the proposed change, this must be written as:
```sql
SET cluster = 'foo';
```

**Comment by teskje** [comment]
We will specifically need this for https://github.com/MaterializeInc/materialize/issues/12520, which introduces the session variable `cluster_replica` of type `Option<String>`.

**Comment by teskje** [comment]
> Rather than retaining type information, it seems like these set values just need to be special-cased in parsing

I figured that might be more confusing to the user than just always requiring quotes for strings. But Postgres seems to handle it like you describe, so we should probably conform. I guess there is generally no expectation that SQL is user friendly 😬 

```
jan=# SET application_name TO test;
SET
jan=# SET application_name TO NULL;
ERROR:  syntax error at or near "NULL"
LINE 1: SET application_name TO NULL;
```

> I'd also posit that we don't need NULL, and the way to "unset" a new cluster_replica option would be to just use DEFAULT, but maybe I'm looking at this too narrowly.

I think that's fine for `cluster_replica`. But if at some point we want to introduce a session variable that is optional but does *not* default to `NULL`/`None`, we will run into this again. It's probably best to special-case `NULL` already now, so we don't have to break backwards-compatibility in the future.

**Comment by sploiselle** [comment]
I don't see how having a non-NULL default value for a nullable variable would break backward compatibility with `cluster_replica`. Can you explain? I would prefer to avoid adding unused features that aren't PG-compatible.

**Comment by teskje** [comment]
So, suppose we are not adding special-casing for `SET <variable> = NULL` now (meaning the value would still be interpreted as a string). Then something like `SET cluster = NULL` would be valid syntax to select the cluster named "NULL". Now, if we introduce a new nullable variable that doesn't default to `NULL`, we will have to retroactively add the special-casing for `NULL` values, since there would be no other way to set this variable to `NULL`. But as soon as we do that, `SET cluster = NULL` becomes invalid, since `cluster` is not a nullable variable. So this would be a breaking change.

> I would prefer to avoid adding unused features that aren't PG-compatible.

I agree! I had assumed that this would be PG-compatible and the `syntax error at or near "NULL"` above just meant that this specific config parameter doesn't accept `NULL` values. But it seems like `SET` simply can't have a `NULL` in value position. And since Postgres doesn't support it, we also should try to avoid it, now and in the future.

I'm going to close this issue and create a new one for adding `SET <variable> = DEFAULT` support instead.

**Comment by teskje** [comment]
Closing in favor of #12551.
