### ISSUE TITLE
isolation: terminated SQL clients do not result in cancellations

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#12546]
### What version of Materialize are you using?

v0.26.1-dev

### How did you install Materialize?

Docker image

### What is the issue?

If a panicking dataflow is installed, Ctrl+C will successfully break out of the crash loop (after #12536). However, killing the client does not have the same effect.

This is more of a bug than a feature request, as long-running sessions that hold up things are a bane to systems that require things to make forward progress for garbage-collection or serializability reasons, and Mz is such a system.

Every other system eventually acquires additional functionality in the area:
- a way to visualize current connections and kill them selectively
- an idle timeout where a connection is terminated if it has been idle for too long

As both of those would require extra speccing and coding, I think the easiest way to unblock stuck clients would be to terminate them externally and then have Mz react appropriately and clean up at the time of the TCP disconnect.

I have added "isolation" in the title because going forward I think stuck clients have the potential to impact the entire system, rather than a specific cluster, due to unforseen interactions between shared components such as coordinator or storage (again, based on experience with other database systems).

To reproduce, run this:

```
CREATE TABLE test(a text);
INSERT INTO test VALUES ('a');
SELECT mz_internal.mz_panic(a) FROM test;
```

and then use `kill -9` to kill the psql client. The crash loop will not go away.

**Comment by sploiselle** [comment]
Just noting that in [PG](https://www.postgresql.org/docs/current/runtime-config-client.html), this is handled with `idle_in_transaction_session_timeout` and `idle_session_timeout`.

**Comment by mjibson** [comment]
This is not yet fixed. See https://github.com/MaterializeInc/materialize/pull/12581#discussion_r877848355. When querying against a table, the crash loop is still evident.
