### ISSUE TITLE
Add support for `SET <variable> = DEFAULT`

### ISSUE THREAD

**Issue by teskje** [MaterializeInc/materialize#12551]
### Feature request

Postgres allows specifying the `DEFAULT` keyword in value-position of a `SET` statement, for specifying that a variable should be reset to its default value ([documentation](https://www.postgresql.org/docs/current/sql-set.html)). We need this feature in Materialize as well, as a dependency for https://github.com/MaterializeInc/materialize/issues/12520.

The `cluster_replica` session variable we want to introduce in #12520 needs to be nullable, so replica-targeting can be switched off. Currently, users have no way to set the variable back to `NULL` after having assigned a non-`NULL` value. Being able to `SET cluster_replica = DEFAULT` solves this.

We could also think about adding support for [`RESET <variable>`](https://www.postgresql.org/docs/current/sql-reset.html) while we are at it, since it is just syntactic sugar for setting a variable to `DEFAULT`.

**Comment by sploiselle** [comment]
This sounds great. As mentioned in https://github.com/MaterializeInc/materialize/issues/12545#issuecomment-1130193118, I believe this means we must prevent replicas from being named `DEFAULT` (which would be inaccessible from this flag).

**Comment by teskje** [comment]
Wouldn't `SET cluster_replica = 'DEFAULT'` still work?

**Comment by sploiselle** [comment]
Ah, that would still work--I was maybe too convinced by your explanation of needing to handle `NULL` as a special case. In the situation you describe in https://github.com/MaterializeInc/materialize/issues/12545#issuecomment-1130113854, then this same logic applies you would just require `SET cluster = 'NULL'`; `SET cluster = NULL` would become an error.

**Comment by teskje** [comment]
That's true. My point there was just that `SET cluster = NULL` becoming an invalid statement would be a breaking change, because it is a valid statement now. It could still easily be worked around by adding quotes as you note.
