### ISSUE TITLE
Don't buffer postgres sources messages as aggressively

### ISSUE THREAD

**Issue by guswynn** [MaterializeInc/materialize#12557]
In https://github.com/MaterializeInc/materialize/pull/11946, we buffer messages from the pg source in 2 places. We should strive to remove one or both of these:
- We buffer all `InProgress` in the reclocking process. The `ReclockOperator` can likely be adjusted to hand out a timestamp _but not seal off that timestamp_ for offsets that have not reached `Finalized` status cc @cjubb39 
- We buffer transactions in the postgres source itself, both in snapshots and replication. These can likely be made to aggressively emit `InProgress` messages and send `Finalized` messages at the end

**Comment by benesch** [comment]
Fixed by #13246.
