### ISSUE TITLE
Decide a proper name for `SerdeUri`

### ISSUE THREAD

**Issue by andrioni** [MaterializeInc/materialize#12578]
@guswynn noted the following in #12573:
>In the future, we should not be using serde to serialize this at all, we should name it something like SerializableUri or something, and eventually we can remove the Serialize and Deserialize impls and just use the Codec impl

We are free to refactor this whenever we'd like, as renaming fields in a Protobuf doesn't break compatibility (as long as the tag numbers stay the same).

**Comment by guswynn** [comment]
@andrioni honestly, thinking about it, because we are just using this wrapper struct as a way to add `Arbitrary` and `Codec` impls to it, maybe just
```
struct Uri(pub http::Uri)
```
is the best name?

**Comment by guswynn** [comment]
@andrioni this might a good warmup task for someone...
