### ISSUE TITLE
Improve the `mz_repr::proto::*` API

### ISSUE THREAD

**Issue by aalexandrov** [MaterializeInc/materialize#12579]
The [current `mz_repr::proto::*` API](https://dev.materialize.com/api/rust-private/mz_repr/proto/index.html) is more complicated that it needs to be. Some of the complexity is already visible in the [Command and Response Binary Encoding Developer Guide](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command_and_response_binary_encoding.md).

More specifically, the guide differentiates between [four classes of types](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command_and_response_binary_encoding.md#type-classes) and provides different guidelines on how to [implement the `$T ⇔ Proto$T` depending on the class of `$T`](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command_and_response_binary_encoding.md#implementing-t--protot-mappings).

To illustrate, consider the following Rust type

```rust
// `$T` is a struct
#[derive(Debug, PartialEq, Eq)]
pub struct MyStruct {
    pub field_1: u64,
    pub field_2: usize,
    pub field_3: CharLength,
    pub field_4: NaiveDate,
    pub field_5: Vec<CharLength>,
    pub field_6: Vec<Vec<CharLength>>,
    pub field_7: HashMap<GlobalId, NaiveDate>,
}
```

with a corresponding Protobuf message type:

```proto
message ProtoMyStruct {
    message ProtoField7Entry {
        mz_repr.global_id.ProtoGlobalId key = 1;
        mz_repr.chrono.ProtoNaiveDate value = 2;
    }
    uint64 field_1 = 1;
    uint64 field_2 = 2;
    mz_repr.adt.char.ProtoCharLength field_3 = 3;
    mz_repr.chrono.ProtoNaiveDate field_4 = 4;
    repeated mz_repr.adt.char.ProtoCharLength field_5 = 5;
    repeated mz_repr.adt.char.VecProtoCharLength field_6 = 6;
    repeated ProtoField7Entry field_7 = 7;
}
```

The `$T ⇔ Proto$T` mapping for this type already looks quite convoluted because of the accumulated boilerplate code.

```rust
impl From<&MyStruct> for ProtoMyStruct {
    fn from(x: &MyStruct) -> Self {
        ProtoMyStruct {
            field_1: x.field_1,
            field_2: x.field_2.into_proto(),
            field_3: Some((&x.field_3).into()),
            field_4: Some((&x.field_4).into_proto()),
            field_5: x.field_5.iter().map(|x| x.into()).collect(),
            field_6: x
                .field_6
                .iter()
                .map(|x| VecProtoCharLength {
                    value: x.iter().map(|x| x.into()).collect(),
                })
                .collect(),
            field_7: x
                .field_7
                .iter()
                .map(|(key, value)| proto_my_struct::ProtoField7Entry {
                    key: Some(key.into()),
                    value: Some(value.into_proto()),
                })
                .collect(),
        }
    }
}

impl TryFrom<ProtoMyStruct> for MyStruct {
    type Error = TryFromProtoError;

    fn try_from(x: ProtoMyStruct) -> Result<Self, Self::Error> {
        Ok(MyStruct {
            field_1: x.field_1,
            field_2: ProtoRepr::from_proto(x.field_2)?,
            field_3: x.field_3.try_into_if_some("ProtoMyStruct::field_3")?,
            field_4: x.field_4.from_proto_if_some("ProtoMyStruct::field_4")?,
            field_5: x
                .field_5
                .into_iter()
                .map(|x| x.try_into())
                .collect::<Result<Vec<_>, _>>()?,
            field_6: x
                .field_6
                .into_iter()
                .map(|x| {
                    x.value
                        .into_iter()
                        .map(|x| x.try_into())
                        .collect::<Result<Vec<_>, _>>()
                })
                .collect::<Result<Vec<_>, _>>()?,
            field_7: x
                .field_7
                .into_iter()
                .map::<Result<(GlobalId, NaiveDate), TryFromProtoError>, _>(|entry| {
                    Ok((
                        entry.key.try_into_if_some("ProtoField7Entry::key")?,
                        entry.value.from_proto_if_some("ProtoField7Entry::value")?,
                    ))
                })
                .collect::<Result<HashMap<_, _>, _>>()?,
        })
    }
}
```

I would therefore like to propose [a revision of the `mz_repr::proto::*` API](https://github.com/MaterializeInc/materialize/commit/7f9401aef2d88ce8a006f7f39c7d98fd5a62c760) that would allow us to simplify the code above as follows

```rust
impl RustType<ProtoMyStruct> for MyStruct {
    fn into_proto(&self) -> ProtoMyStruct {
        ProtoMyStruct {
            field_1: self.field_1,
            field_2: self.field_2.into_proto(),
            field_3: Some(self.field_3.into_proto()),
            field_4: Some(self.field_4.into_proto()),
            field_5: self.field_5.into_proto(),
            field_6: self.field_6.into_proto(),
            field_7: self.field_7.into_proto(),
        }
    }

    fn from_proto(proto: ProtoMyStruct) -> Result<Self, TryFromProtoError> {
        Ok(MyStruct {
            field_1: proto.field_1,
            field_2: proto.field_2.into_rust()?,
            field_3: proto.field_3.into_rust_if_some("ProtoMyStruct::field_3")?,
            field_4: proto.field_4.into_rust_if_some("ProtoMyStruct::field_4")?,
            field_5: proto.field_5.into_rust()?,
            field_6: proto.field_6.into_rust()?,
            field_7: proto.field_7.into_rust()?,
        })
    }
}
```

based on a more unified set of traits and a suitable set of blanket implementations.

The basic ideas are summarized below:

- Use `RustType` (with a blanket implementation for `ProtoType`, similar to what `Into` is for `From`) in order to define the pair of mappings for all classes of types in a single trait rather than choosing between `ProtoRepr` and `From + TryFrom` as it is at the moment.
- Provide implementations for common simple and complex external types (`usize`, `NaiveDate`).
- Provide blanket implementations for common container types: `Option`, `Vec`, `HashMap`.
- Provide a dedicated trait `ProtoRepr` that encodes the default `Proto$T` for a given `$T` (there can be many depending on the context), and use `ProtoRepr` as a trait bound in client code (for example, in #12516).

If there are no major objections, I will proceed with the following steps:

- [x] [Open a PR](12589) to first merge the new [revision of the `mz_repr::proto::*` API] into a dedicated `newapi` namespace.
- [x] Open PRs (#12594, #12632) that rework existing code based on the `mz_repr::proto::newapi` contents. The list of files that have to be fixed can be obtained with `find src -name '*.rs' | xargs -I{} grep -l -E 'impl From<&(.+)> for Proto|impl ProtoRepr for' {} | sort | uniq | grep -v 'src/persist'`. Currently, it is:
  - [x] `src/dataflow-types/src/client/controller/storage.rs`
  - [x] `src/dataflow-types/src/client.rs`
  - [x] `src/dataflow-types/src/errors.rs`
  - [x] `src/dataflow-types/src/logging.rs`
  - [x] `src/dataflow-types/src/plan/join/delta_join.rs`
  - [x] `src/dataflow-types/src/plan/join/linear_join.rs`
  - [x] `src/dataflow-types/src/plan/join/mod.rs`
  - [x] `src/dataflow-types/src/plan/mod.rs`
  - [x] `src/dataflow-types/src/plan/reduce.rs`
  - [x] `src/dataflow-types/src/plan/threshold.rs`
  - [x] `src/dataflow-types/src/plan/top_k.rs`
  - [x] `src/dataflow-types/src/types.rs`
  - [x] `src/expr/src/id.rs`
  - [x] `src/expr/src/linear.rs`
  - [x] `src/expr/src/relation/func.rs`
  - [x] `src/expr/src/relation/mod.rs`
  - [x] `src/expr/src/scalar/func.rs`
  - [x] `src/expr/src/scalar/like_pattern.rs`
  - [x] `src/expr/src/scalar/mod.rs`
  - [x] `src/kafka-util/src/addr.rs`
  - [ ] `src/persist/src/indexed/encoding.rs`
  - [x] `src/repr/src/adt/array.rs`
  - [x] `src/repr/src/adt/char.rs`
  - [x] `src/repr/src/adt/datetime.rs`
  - [x] `src/repr/src/adt/interval.rs`
  - [x] `src/repr/src/adt/numeric.rs`
  - [x] `src/repr/src/adt/regex.rs`
  - [x] `src/repr/src/adt/varchar.rs`
  - [x] `src/repr/src/chrono.rs`
  - [x] `src/repr/src/global_id.rs`
  - [x] `src/repr/src/proto.rs`
  - [x] `src/repr/src/relation.rs`
  - [x] `src/repr/src/row/encoding.rs`
  - [x] `src/repr/src/scalar.rs`
- [ ] Once I am done, I can open a final PR that (a) removes the old API, (b) moves the `newapi` code one level up, and (c) simplifies the [developer guide](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command_and_response_binary_encoding.md).

@andrioni Feel free to proceed with #12358 as usual. I will let you know when I am caught up so you can switch to the new API as well.

**Comment by guswynn** [comment]
@aalexandrov this looks great! Note that it also fixes an outstanding oddity I noticed in the original api, which that we implement `From<ProtoType> for RustType`, but `From<*&*RustType> for ProtoType`, which means there is a huge number of explicit `.clone()` callsites in all the `From<Rust> for Proto` impls. This, I believe, is an artifact of the `Codec::encode` api, but I believe with your suggestion, we can move all these `.clone()`'s into one single `.clone()` in `encode`, before we call `.into_proto()`. After that, we can look into adding `encode_owned` to `Codec` to avoid cloning for `encode` callsites that already have owned access to the rust struct! (cc @petrosagg and I were talking about this, but `into_proto` and `from_proto` look VERY nice to me!)

**Comment by andrioni** [comment]
At a first glance, I really like it! It’s really nice how the conversions become more uniform (no more mixing `.into()`/`into_proto()` depending on whether it’s a type we defined or not), as well as drastically reducing the boilerplate for collections. Removing all the `(&x.field).into()` is also another huge plus!

One question, though: what should be our convention for where to place `RustType` impls for external types? We use `mz-repr::proto` for types in the stdlib and `mz-repr::chrono` for the `chrono` ones, but it’s not that clear to me how to decide for other crates.

**Comment by benesch** [comment]
I only glanced, but strong 👍🏽 from me!

> One question, though: what should be our convention for where to place `RustType` impls for external types? We use `mz-repr::proto` for types in the stdlib and `mz-repr::chrono` for the `chrono` ones, but it’s not that clear to me how to decide for other crates.

I'd advocate for creating either per-crate sidecars, like `mz-proto-std` and `mz-proto-chrono`, or one `mz-proto` crate with modules for `std` and `chrono` and whatever else we discover needs to be protobuf'd.

**Comment by aalexandrov** [comment]
> Note that it also fixes an outstanding oddity I noticed in the original api, which that we implement `From<ProtoType> for RustType`, but `From<*&*RustType> for ProtoType`, which means there is a huge number of explicit `.clone()` callsites in all the `From<Rust> for Proto` impls. This, I believe, is an artifact of the `Codec::encode` api, but I believe with your suggestion, we can move all these `.clone()`'s into one single `.clone()` in `encode`, before we call `.into_proto()`.

I am not sure my proposal is fixing this, because the `into_proto` still acts on a referencce (`&self`), whereas `from_proto` acts on an owned instance of `P`, but now is a good time to discuss whether to do it or not.

I believe the reason it is done like that is because clients will often want to have serialization is a side effect rather than a sink. I can imagine that the following use cases fit that description:

- Maintaining a log of all commands for command reconciliation.
- Maintaining a log of all incoming row diffs for source persistence.

In other words, I expect to see situations where you want to further do something with the `RustType` value once it is serialized. CC @danhhz: can you should confirm that this was the original intention for the by-reference `encode`.

I am a bit worried about the performance overhead of calling `*.clone()` on the top-level `RustType` in `Code::encode` is that we will need to clone the entire structure only for the purpose of traversing the clone, whereas at the moment we traverse the structure by reference and clone only the leaf nodes.

For example, consider the plan for the query of adding `n` 32bit ints:

```sql
SELECT x1 + x2 + x3 + ... + xn FROM R;
```

At the moment, the `MirScalarExpr` for the `x1 + ... + xn` sum is a right-deep tree of `CallBinary` applications, so the number of objects in that tree is approximately `3n - 2` (modulo some `Box` overhead). However, the current `MirScalarExpr ⇒ ProtoMirScalarExpr` conversion will not clone anything:
- Leaf node `usize` parameters in `MirScalarExpr::Column` are converted to `u64`, 
- Leaf node `BinaryFunc::AddInt32` is converted to `proto_binary_func::Kind::AddInt32(())`, and
- Inner nodes (`MirScalarExpr::CallBinary` and `MirScalarExpr::Column`) are converted into `proto_mir_scalar_expr::Kind::CallBinary` and `proto_mir_scalar_expr::Kind::Column`).

If we change the API as you suggested, we will have to create a copy of these `3n - 2` objects in `Code::encode` for just to drop them a couple of moments later, which I guess might be a problem if `Code::encode` or similar client code ends up on the hot path of some operation mode.

**Comment by danhhz** [comment]
> In other words, I expect to see situations where you want to further do something with the RustType value once it is serialized. CC @danhhz: can you should confirm that this was the original intention for the by-reference encode.
>
> I am a bit worried about the performance overhead of calling *.clone() on the top-level RustType in Code::encode is that we will need to clone the entire structure only for the purpose of traversing the clone, whereas at the moment we traverse the structure by reference and clone only the leaf nodes.

Yeah, this is it.

The basic problem of serializing an in-mem representation of something into bytes basically never requires passing ownership. The only exceptions to that I can see would be something like a `String` or `Vec<u8>` which are serialized as themselves. It's really just an odd quirk of the way our proto stuff works that we clone all the string/vec leafs to construct an owned proto object, then encode it and throw it away.

This also came up in #12341, where I also mentioned that if the cloning becomes a performance issue (as you mention, it's only of the leaf nodes), then the correct fix is to make it possible to encode proto using only refs. Perhaps I have a nice friday project for myself. :)

**Comment by aalexandrov** [comment]
> then the correct fix is to make it possible to encode proto using only refs.
You mean like "tweak `prost` so it works on borrowed data in the message leafs".

**Comment by danhhz** [comment]
Yeah, exactly. Or otherwise code generate the prost::Message impl directly on our structs (similar to how prost's derive API works)

**Comment by danhhz** [comment]
Hmm, in fact, it seems like we're getting pretty close to it with ProtoType/RustType. To what extent are we converting various types to proto for the sake of Codec::encode vs to send it over grpc?

**Comment by aalexandrov** [comment]
`~Command` types are converted for both reasons (I assume that we will need to persist a log for command reconciliation, cc @antiguru let us know if you have other ideas). For `~Response` types I am not sure about `Codec::encode`. `Row` is subsumed by the `~Command` types because it's part of the rendered plans.

**Comment by aalexandrov** [comment]
> The fact that it takes a `&self` receiver had let to a proliferation of these From<&T> implementations that would be much better as an owned variant.

This is from [this comment](https://github.com/MaterializeInc/materialize/pull/12297/files#r867247774).

Do we have a call side in the codebase where `Codec::encode` *really needs* to pass the value by reference as opposed to moving the ownership at the moment?

**Comment by danhhz** [comment]
> Hmm, in fact, it seems like we're getting pretty close to it with ProtoType/RustType.

Nevermind on this thought. I tried playing with it for a sec and realized it's probably just re-inventing prost's derive API.

**Comment by danhhz** [comment]
> Do we have a call side in the codebase where Codec::encode really needs to pass the value by reference as opposed to moving the ownership at the moment?

Not that I know of, but my point is that moving the ownership is the wrong fix. I may have to bow to the practicality argument at some point, but IMO proto generated code being proscriptive about ownership is the issue, not Codec::encode taking a ref.

**Comment by aalexandrov** [comment]
I can summarize as follows:

1. We are currently interpreting the `RustType` structure to create a matching `ProtoType` structure.
1. Pretty much in all cases the immediate next step is going to be to interpret the `ProtoType` structure in order to encode it.
1. Step (1) is handled by the traits proposed here, while step (2) is handled by `prost`.
1. If we can fuse both steps we can obtain the serialized byte sequence without materializing `ProtoType` in memory.
1. It seems that `prost` being proscriptive about ownership in it's generated code is one of the main issues for achieving (4).

**Comment by guswynn** [comment]
@aalexandrov  oh i missed the `&self` in `into_proto`. My point that we should make it owned still stands, I believe:

> I am a bit worried about the performance overhead of calling *.clone() on the top-level RustType in Code::encode is that we will need to clone the entire structure only for the purpose of traversing the clone, whereas at the moment we traverse the structure by reference and clone only the leaf nodes.

I understand and now agree that `Codec::encode` should only take `&self`, as we ultimately are just copying bytes onto the wire using the `prost::Message` impl; However, in the code as it exists, we have to produce an _owned_ `ProtoStruct` from a `RustStruct`, which means we have to perform, in the `From` impl, the same number of allocations/clones as one top-level. In other words, we could save on this cloning if we were able to go from `&RustStruct -> &ProtoStuct`, but, because they don't have the same in-memory layout, we cant.

> It seems that prost being proscriptive about ownership in it's generated code is one of the main issues for achieving (4).

this is kindof the same problem, but I can understand the motivation here: its very difficult to get an entirely borrowed, recursive struct right, especially when you want to be own-able OR borrow-able, though my understanding is there an issue tracking this upstream in prost? Knowing that this limitation exists, for now, I think it makes it more clear to always be converting between owned and owned types, which allows at least some callsites to turn from clones into moves. This also does not preclude any future where 

If I am being unclear, happy to hop on slack!

**Comment by aalexandrov** [comment]
I created #12688 to track Q2 from above.
