### ISSUE TITLE
Explain: list indexes that would be used when creating a dataflow

### ISSUE THREAD

**Issue by wangandi** [MaterializeInc/materialize#12629]
### Feature request

As discussed with @rjnn:

It would be nice for `explain` to list which indexes are used. An acceptable output looks like:
```
materialize=> explain select action from foo where action = '2';
      Optimized Plan      
------------------------------------
 %0 =               +
 | Get materialize.public.foo (u10)+
 | Filter (#1 = "2")        +
 | Project (#3)          +

Indexes used: foo_idx3
```

A bonus would be if we could list the name of the index + source/view that the index is on + columns that the indexes are on, so it looks something like `foo_idx3(foo(action))`. Unfortunately, at first glance, it looks like listing stuff other than the name of index may be difficult.

If we fix #4887, getting a list of indexes used will be just a matter of reading `DataflowDescription::index_imports`.

**Comment by aalexandrov** [comment]
Resolved in #13894 and #14033.
