### ISSUE TITLE
Cease announcing log sources to storage

### ISSUE THREAD

**Issue by teskje** [MaterializeInc/materialize#12644]
During bootstrapping, the coordinator issues `CreateSources` commands to STORAGE for the built-in log sources. This seems unnecessary: The log sources are maintained by COMPUTE, so there shouldn't be a need for STORAGE to keep any state for them.

See this thread for context: https://github.com/MaterializeInc/materialize/pull/12637#discussion_r879373308

**Comment by antiguru** [comment]
One thing to consider is that storage still uses Timely as their runtime, which produces log data. We could try to integrate the data it produces into the introspection framework, but I think it'll require a different mechanism than the compute introspection sources. Before investing time, we should ask the storage team what they think of this.
