### ISSUE TITLE
compute,adapter: push introspection configuration down to replica

### ISSUE THREAD

**Issue by benesch** [MaterializeInc/materialize#12660]
In the switch to explicit cluster replica management, we didn't think through what to do with the options for the introspection sources. Currently introspection is configured per cluster:

```sql
CREATE CLUSTER c INTROSPECTION GRANULARITY '1s'
```

We have the ability to control introspection per _replica_ though, rather than per cluster. We probably want to expose that feature, since it might be nice to leave introspection disabled unless you're actively doing performance debugging, at which point you could turn on a new replica with introspection enabled.

~Does that seem right to folks?~ ~The specific proposal is to allow _overriding_ the introspection options per replica. They can still be configured at the cluster level, which sets the default for any replicas that do not otherwise have their introspection options configured.~

Abridged proposal: we should only allow configuring the introspection options per replica, not per cluster. We can later figure out if it makes sense to allow specifying them per cluster, and propagate that default down to replicas that didn't explicitly override them. But we're short on time. 

cc @sploiselle @jkosh44 @teskje @antiguru

**Comment by benesch** [comment]
If we _don't_ do this, we should make it possible to configure a default replica set and the introspection granularity simultaneously. This should work but is presently a parse error:

```
create cluster c replica default (size 'small'), introspection granularity 'off';
```

**Comment by benesch** [comment]
Oh! It's even funnier than that. The `WITH` is optional; you just have to not have a comma between the last replica and `INTROSPECTION`:

```
create cluster c replica default (size '1') introspection granularity 'off';
```

**Comment by benesch** [comment]
> I wonder if it makes sense to still keep the per-cluster config option around, so people can conveniently change the default on a whole cluster.

I was wondering that too! I sent #12663 to switch the SQL syntax to allow commas in between the options. I'll retitle the issue to be about overriding the introspection configuration per replica.

**Comment by jkosh44** [comment]
This all sounds reasonable to me. It might be a bit tricky to figure out how to represent the per replica indexes in the catalog, but I'm sure it's do-able.

**Comment by benesch** [comment]
> This all sounds reasonable to me. It might be a bit tricky to figure out how to represent the per replica indexes in the catalog, but I'm sure it's do-able.

I think it should actually be quite straightforward! I don't think the catalog needs to do anything special with the introspection indexes beyond what it already does—i.e., it can continue to create a unique set of introspection indexes for each _cluster_, but not cluster replica. (I suppose it should start doing this unconditionally, rather than conditionally based on the cluster's configured introspection granularity.) Ensuring that you only access the introspection indexes when targeting a replica with introspection enabled can be handled by adding an additional condition to [`check_no_invalid_log_reads`].

**Comment by jkosh44** [comment]
I think 1.5 weeks for the adapter side.

**Comment by benesch** [comment]
Given how close we are to the deadline, I think we should say that the introspection options are _only_ configurable per replica, and punt on the inheritance hierarchy.

**Comment by uce** [comment]
Given the approaching deadline, @teskje will pick this up later today or tomorrow. Jan is experienced with this part of the code base and should be able to move fast on this.

@ggnall This is at the compute/surfaces boundary. Any product questions to sort out before Jan picks this up?
