### ISSUE TITLE
Queries against disabled introspection relations hang forever

### ISSUE THREAD

**Issue by benesch** [MaterializeInc/materialize#12662]
If you create a cluster with introspection disabled and then attempt to query an introspection relation, the query hangs forever:

```
materialize=> create cluster c introspection granularity 'off';
CREATE CLUSTER
materialize=> set cluster = c;
SET
materialize=> create cluster replica c.default size '1';
CREATE CLUSTER REPLICA
materialize=> select * from mz_dataflow_operators;
# Hangs forever.
```

We should return a nice error message instead.

**Comment by teskje** [comment]
### What's Happening

When a cluster is created with introspection disabled, coord tells computed to not bother creating logging dataflows and also skips creating corresponding indexes in the catalog.

 So when a user performs something like `SELECT * FROM mz_dataflow_operators` on a cluster without introspection, there is no index to fulfill that query. Instead, query planning decides that we must read from the source directly. It installs an according dataflow with COMPUTE and peeks it. The dataflow reads the raw `mz_dataflow_operators` source from STORAGE. Coord has registered the source with STORAGE (see also #12644), so STORAGE knows the source. But coord doesn't consider it necessary to periodically advance the `upper` of introspection sources (like it does for user tables). So the `upper` of introspection sources always stays 0 and any dataflow reading from them waits forever. On the SQL-level, the `SELECT` hangs.

### Possible Fixes

1. Coord can return an error for peeks that read introspection sources and target replicas that have introspection disabled. This would also give us a nice error message.
2. Coord can tick along the `upper` of introspection sources in STORAGE, like it does for table sources. Users querying these sources would always get 0 records back, which might be a reasonable result for clusters that have introspection disabled.

Approach 1. provides the better UX and is easier to implement.

**Comment by teskje** [comment]
I observed some confusing behavior, that might be a symptom of another bug. To reproduce:

1. Create a cluster with introspection disabled. Queries to introspection sources are allowed, but hang.
    ```sql
    CREATE CLUSTER c REPLICA default (SIZE '1') INTROSPECTION GRANULARITY 'off';
    SET cluster = c;
    SELECT * FROM mz_dataflow_operators;  # hangs
    ```
2. Drop the default cluster. Queries to introspection sources are still allowed.
    ```sql
    DROP CLUSTER default;
    SELECT * FROM mz_dataflow_operators;  # hangs
    ```
3. Restart Materialize.
4. Try querying an introspection source on the custom cluster again.
    ```sql
    SET cluster = c;
    SELECT * FROM mz_dataflow_operators;
    ```

I get this error:
```
ERROR:  unable to automatically determine a query timestamp
DETAIL:  The query transitively depends on the following unmaterialized sources:
	mz_catalog.mz_dataflow_operators
HINT:
- Use `SELECT ... AS OF` to manually choose a timestamp for your query.
                - Create indexes on the listed unmaterialized sources or on the views derived from those sources
```

**Comment by benesch** [comment]
Approach 1 is exactly what I was thinking!

**Comment by teskje** [comment]
I created a follow-up issue for the confusing behavior I described above: https://github.com/MaterializeInc/materialize/issues/12674
