### ISSUE TITLE
sinks: primary key error does not log the sink which caused the issue

### ISSUE THREAD

**Issue by bobbyiliev** [MaterializeInc/materialize#12669]
### What version of Materialize are you using?

0.26.1

### How did you install Materialize?

Docker image

### What is the issue?

Currently, a Materialize panic caused by a [sink with not unique key](https://github.com/MaterializeInc/materialize/blob/main/src/interchange/src/envelopes.rs#L182-L189), doesn't print the sink which caused the issue. So if you have multiple sinks, it can be challenging to identify which sink cause the panic.

### Relevant log output

```source
ERROR materialized::mux: error handling connection in pgwire server: Connection reset by peer (os error 104)    
2022-05-19T01:48:30.560313Z ERROR panic: primary key error: expected at most one update per key and timestamp. This can happen when the configured sink key is not a primary key of the sinked relation
```
```

**Comment by cjubb39** [comment]
Ideally we don't want this panic to happen (we should enforce the invariant when creating the sink) -- but, for now, this is a strict improvement
