### ISSUE TITLE
Issue reporting tool

### ISSUE THREAD

**Issue by cuongdo** [MaterializeInc/materialize#1267]
When a user reports an issue, we will likely ask for common things such as:

* Linux distro
* Materialize parameters
* A subset of the data in the `mz_*` tables
* Some of the metrics currently visible in Grafana

This is likely to result in a lot of inefficient back-and-forth between us and users. We should create a way to:

1. Package up the data that helps us efficiently debug issues
2. Send the data to us

This would all require explicit user action but should require little or no additional work once triggered by the user.

**Comment by wangandi** [comment]
I vote for having
* definitely version of materialize
* query plan explanations. If the user is likely to have too many extant views/queries, we could have the tool specify a file listing the queries/views whose plans should be dumped.
* show index for dependent views of the query to be explained, especially when the query to be explained is a join.
* some information about the disk capacity/total memory of the machine.

**Comment by frankmcsherry** [comment]
Catalog contents would also certainly be good! I've had a few cases of the "problem" being that I forgot about an installed query, and materialized maintaining it in the background for me.

**Comment by ruchirK** [comment]
I would also vote for records used by each dataflow, total memory used by materialize currently, and a snapshot of the histogram of operator latencies (maybe filtered by latencies exceeding 0.1 second)

**Comment by benesch** [comment]
Fixed by platform, where we have direct access to the metrics we need from customer environments.
