### ISSUE TITLE
type with OID 200008 is unknown

### ISSUE THREAD

**Issue by kulame** [MaterializeInc/materialize#12689]
### What version of Materialize are you using?

v0.16.1

### How did you install Materialize?

Docker image

### What is the issue?

materialize=> create views from source npns_source;
ERROR:  type with OID 200008 is unknown

**Comment by morsapaes** [comment]
Hey, @kulame! Does your publication contain tables using enums? The error suggests that there's an unsupported type somewhere upstream that Materialize is unable to handle.

**Comment by kulame** [comment]
yes.. i use enum on postgresql.  

Is there any solution for postgresql enum?

**Comment by morsapaes** [comment]
Until we support the enum type, one option is to manually create the view for the affected table(s) casting the enum columns to a valid type like `::text`, using:

```sql
CREATE VIEW AS 
SELECT ... FROM "npns_source" WHERE oid = XXX AND ...
```

Could you give that a try and let us know if it's a reasonable workaround for you?

**Comment by jeandeducla** [comment]
Ok so for posterity I actually found a way to find out: I created a source from a publication containing a table with only supported types (no enum for instance), ran 
```
CREATE VIEWS FROM my_source_with_only_supported_data_type(table_with_only_supported_types)
```
 and finally ran
 ```
SHOW CREATE VIEW table_with_only_supported_types
```
 and you'll see how materialize creates a view from `row_data` (https://materialize.com/docs/sql/show-create-view/#syntax).

**Comment by morsapaes** [comment]
@jeandeducla, here's an example if it's still useful:

```sql
postgres=# CREATE TYPE mood AS ENUM ('sad', 'ok', 'happy');
CREATE TYPE
postgres=# CREATE TABLE person (name TEXT, current_mood mood);
CREATE TABLE
postgres=# INSERT INTO person VALUES ('Moe', 'happy');
INSERT 0 1
postgres=# SELECT * FROM person WHERE current_mood = 'happy';
 name | current_mood
------+--------------
 Moe  | happy
(1 row)

postgres=# CREATE ROLE repl REPLICATION LOGIN PASSWORD 'postgres';
CREATE ROLE
postgres=# GRANT SELECT ON PERSON TO repl;
GRANT
postgres=# ALTER TABLE person REPLICA IDENTITY FULL;
ALTER TABLE
postgres=# CREATE PUBLICATION mz_source FOR TABLE person;


materialize=> CREATE MATERIALIZED SOURCE "mz_source" FROM POSTGRES
materialize-> CONNECTION 'host=postgres port=5432 user=repl dbname=sportsdb password=postgres'
materialize-> PUBLICATION 'mz_source';
CREATE SOURCE
--Materialize will fail at parsing the `ENUM`
materialize=> CREATE VIEWS FROM SOURCE mz_source;
ERROR:  type with OID 18120 is unknown
--Manually create the view instead
materialize=> CREATE VIEW person AS SELECT row_data[1] AS name, row_data[2] AS current_mood FROM mz_source WHERE oid=18127;
CREATE VIEW
materialize=> select * from person;
 name | current_mood
------+--------------
 Moe  | happy
(1 row)

materialize=> SHOW COLUMNS FROM person;
     name     | nullable | type
--------------+----------+------
 name         | t        | text
 current_mood | t        | text
(2 rows)
```

This is kind of cumbersome if your upstream table has a lot of columns and you want to preserve every other type, but I'm afraid it's the way to work around it for now.

**Comment by benesch** [comment]
Closing in favor of #6818 and #15073.
