### ISSUE TITLE
Kafka timestamps cast to `u64`

### ISSUE THREAD

**Issue by frankmcsherry** [MaterializeInc/materialize#1268]
Kafka timestamps are signed integers, but we cast them to unsigned integers, and generally assume that they will be non-negative. This happens to be true for the data we've been looking at, but the timestamp can be populated by the user and we should handle the case that it is negative or warn users that negative timestamps are surprising to us.

**Comment by elindsey** [comment]
Closing this out - this task is from the time when Kafka timestamps were cast to u64 and used as the dataflow ts (ie. prior to rt) and is no longer relevant.

re: specific Kafka questions - it's safe to cast i32 kafka timestamps to u64 with the exception that a -1 can be used to signal 'unknown'. Often you only need to know this if you're processing timestamps off the wire though, and not through a Kafka library.

There was a separate, recent discussion about potentially using negative timestamps in other parts of the system, but that's only very tangentially related to this task and should be discussed elsewhere.
