### ISSUE TITLE
materialized: move HTTPS server to port 443

### ISSUE THREAD

**Issue by benesch** [MaterializeInc/materialize#12698]
### Overview

`materialized` currently hosts its HTTPS server _and_ its pgwire server on the Materialize port (6875). There have been at least two requests to change it:

  * @bobbyiliev would like to access `materialized` from a Cloudflare worker, which only permits outbound traffic on ports 80/443.
  * @elindsey networking background leads him to deeply dislike the complexity introduced by hosting two protocols on the same port.

Historically, we've multiplexed these services on the same port to simplify operations for on-premise deployments: there's only one port users need to open in their firewall. Now that we're going cloud native, that argument no longer applies. 

So: I propose that we move Materialize's public HTTPS server to port 443.

### Design

Replace the `--listen-addr` argument to `materialized` with three new arguments:

  1. `--sql-listen-addr`: the port on which `materialized` listens for incoming pgwire connections
  2. `--http-listen-addr`: the port on which `materialized`  listens for incoming HTTP connections for public endpoints (e.g., /api/sql and the dataflow visualizer)
  3. `--internal-sql-listen-addr`: the port on which `materialized` listens for incoming pgwire connections from the cloud system. 
  4. `--internal-http-listen-addr`: the port on which `materialized` listens for incoming HTTP connections to access internal APIs (e.g., Prometheus metrics and memory debugging). This will replace the existing `--metrics-listen-addr` option.

Ports 1 and 2 will be authenticated/encrypted if requested via `--frontegg-auth`/`--tls-mode`. Ports 3 and 4 will always be unauthenticated and are not intended to be publicly exposed in Materialize Cloud.

Note that this design also incorporates the unauthenticated SQL port originally described in https://github.com/MaterializeInc/cloud/issues/3082#issuecomment-1132127898. Not strictly part of this issue, but it's intertwined with this issue, so easiest to tackle all at once.

**Comment by JLDLaughlin** [comment]
@wangandi it looks like [this issue replaces](https://github.com/MaterializeInc/cloud/issues/3082#issuecomment-1138027479) the request for [`--unauthenticated-listen-addr`](https://github.com/MaterializeInc/cloud/issues/3082#issuecomment-1132127898). would you be able to pick this up instead?

(cc @uce !)

**Comment by wangandi** [comment]
So I have a separate port 443 for listening for HTTP connections, and the first thing that happens when I run `bin/materialized` is that `materialized` dies with "Permission denied (os error 13)" because [ports below 1024 are privileged](https://www.w3.org/Daemon/User/Installation/PrivilegedPorts.html). 

I then tried `sudo bin/materialized`. The script died with "psql: error: connection to server on socket "/tmp/.s.PGSQL.5432" failed: FATAL:  role "root" does not exist".

Should I modify `bin/materialized` to assign a different default HTTP port for testing locally? Should I modify `bin/materialized` to start up materialized as root but not run any other actions as root?

**Comment by benesch** [comment]
Ah, right. Let's just pick a port besides 443 to use by default for `--http-listen-addr`. I propose 6876!

Then, in Kubernetes, we can remap 6876 to 443 when we expose the port to the public, without needing root permissions: https://github.com/MaterializeInc/cloud/blob/de5da7465e579eded539831c0b92ad15a5e17061/mzcloud-environment-controller/src/main.rs#L211-L216

**Comment by benesch** [comment]
> Is there any difference between the types of pgwire connections allowed by the internal port vs external port (other than the fact that the internal address is always unanthenticated)? Is there any difference in the SQL API for the internal vs external address?

Nope!

> Should the pgwire server on the internal port be registered with the MetricsRegistry just like the pgwire server serving the external port? Should they share the same metrics? Is it worthwhile to collect metrics against the pgwire server on the internal port ?

I've never found those metrics useful. Now that we're wiring up distributed tracing they're even less important. Let's just remove them!

**Comment by benesch** [comment]
> I've never found those metrics useful. Now that we're wiring up distributed tracing they're even less important. Let's just remove them!

I sent https://github.com/MaterializeInc/materialize/pull/12869 to remove them.
