### ISSUE TITLE
sql: improve syntax and output of `SHOW INDEXES` 

### ISSUE THREAD

**Issue by rjnn** [MaterializeInc/materialize#12700]
## Proposal

Change the output of `SHOW INDEXES` to:

```
name | on | cluster | key
-----|----|---------|----
```

* `name` is the name of the index.
* `on` is the name of the relation upon which the index is built.
* `cluster` is the name of the cluster in which the index is maintained.
* `key` is a text array describing the expressions in the index key. Each expression is usually a simple column reference.

## Background and rationale

We've had several folks in the community mistake the output of `SHOW INDEXES` as showing multiple indexes when in fact it was showing only one multi-column index. Some representative examples:

* [Community Slack conversation 1](https://materializecommunity.slack.com/archives/C015KDVS7EV/p1653491449952359)
* [Community Slack conversation 2](https://materializeinc.slack.com/archives/C03V4NW8H1R/p1662285943669449?thread_ts=1662197230.527309&cid=C03V4NW8H1R)

**Comment by morsapaes** [comment]
Logging [one more thread](https://materializeinc.slack.com/archives/C03V4NW8H1R/p1662285943669449?thread_ts=1662197230.527309&cid=C03V4NW8H1R) where the user is confused by the output of `SHOW INDEXES`. @ggnall @chaas, something to take into account in the scope of #7174 and #11231.

**Comment by benesch** [comment]
Made a few edits here:

* I moved the request for improved documentation into its own issue (#14645).
* I added a concrete proposal for improving the output of `SHOW INDEXES`.
