### ISSUE TITLE
Support in a Postgres source table's primary keys as the materialized views indexes

### ISSUE THREAD

**Issue by joacoc** [MaterializeInc/materialize#12701]
### Feature request

As discussed [with a community user](https://materializecommunity.slack.com/archives/C015KDVS7EV/p1653508295764459?thread_ts=1653491449.952359&cid=C015KDVS7EV), materialized views indexes from a Postgres source don't match tables primary keys.

Probably someone else can confirm, but Debezium with Postgres uses the table's primary key in the schema registry, and then Materialize uses that to create the correct index for the materialized view.

We should have the same approach with Postgres sources, or at least when the user runs `CREATE MATERIALIZED VIEWS`

**Comment by morsapaes** [comment]
@nmeagan11, getting this in your radar.

**Comment by benesch** [comment]
Closing as stale. Things work very differently now (no `CREATE MATERIALIZED VIEWS`).
