### ISSUE TITLE
`ERROR:  No such file or directory (os error 2)` when reading CSV

### ISSUE THREAD

**Issue by mikkokotila** [MaterializeInc/materialize#12717]
### What version of Materialize are you using?

v0.26.1 (82caaed24)

### How did you install Materialize?

Docker image

### What is the issue?

First off, thanks for the amazing docs. I think sets a new standard for open source packages. 

Not really sure if this is a bug, but it seemed like the only category of tickets that might suit the case. 

After following the getting started instructions [here](https://materialize.com/docs/get-started/), from psql I run the following (albeit with the information reflecting my own file):

```
CREATE SOURCE dynamic_wo_header (col_foo, col_bar, col_baz)
  FROM FILE '/local/path/file.csv'
  WITH (tail = true)
  FORMAT CSV WITH 3 COLUMNS;
```

As a result, I get: 

`ERROR:  No such file or directory (os error 2)`

Materialize itself seems to be running smoothly.

**Comment by benesch** [comment]
Are you running Materialize in Docker? If so, does the Docker volume have that path mounted?

**Comment by mikkokotila** [comment]
![image](https://user-images.githubusercontent.com/7943188/170477805-77edfe2f-1083-4c9a-a467-1a08d43de94b.png)
