### ISSUE TITLE
Use `ScalarExpr` in `RelationExpr::{Reduce, Join}`

### ISSUE THREAD

**Issue by frankmcsherry** [MaterializeInc/materialize#1275]
Both `Reduce` and `Join` describe grouping keys by column identifiers, but with recent @wangandi work indices and such can now be keyed by `[ScalarExpr]` rather than only columns. This should allow us to move some temporary column computations into the operators, which simplifies and improves plans.

**Comment by wangandi** [comment]
Can we close this since #2235 is merged?

**Comment by frankmcsherry** [comment]
Great idea!
