### ISSUE TITLE
sql: make `CREATE CLUSTER` harder to misuse

### ISSUE THREAD

**Issue by benesch** [MaterializeInc/materialize#12769]
## The problem

The current `CREATE CLUSTER` syntax makes it easy to accidentally create an empty cluster:

```sql
CREATE CLUSTER foo;
```

Empty clusters are a niche feature that are not generally what users want. Attempting to run `SELECT` statements against an empty cluster will fail, for example, until you add a replica. So making the creation of an empty cluster so easy to type is a large footgun.

The reason for this design is that it is simply falls out of the syntax for creating clusters with one or more replicas:

```
CREATE CLUSTER foo;
CREATE CLUSTER foo REPLICA r1 (SIZE 'small');
CREATE CLUSTER foo REPLICA r1 (SIZE 'small'), REPLICA r2 (SIZE 'small');
```

See #12736 for even a bit more background.

## Proposal

One option is to redesign the syntax for specifying a replica set at cluster creation to look more like `CREATE TABLE`:

```
CREATE CLUSTER foo REPLICAS ();
CREATE CLUSTER foo REPLICAS (
    r1 (SIZE 'small')
);
CREATE CLUSTER foo REPLICAS (
    r1 (SIZE 'small'),
    r2 (SIZE 'small'),
)
```

It is still possible to type `CREATE CLUSTER REPLICAS ()` when a cluster with no replicas is truly desired, just like it is possible to type `CREATE TABLE t ()` to create a zero-arity table in PostgreSQL, but it is something that is nearly impossible to type accidentally.

Then we can make `CREATE CLUSTER foo;` an error that yields a nice hint about what you should type instead. (Or has some default behavior, though I'm skeptical of any such default behavior at the moment; see #12736 for details.)

----

cc @sploiselle @heeringa @JLDLaughlin

**Comment by heeringa** [comment]
@benesch - okay to close this with #12778 being merged?  @sploiselle has the documentation work mentioned in #12778 so I think we're good to go here!

**Comment by benesch** [comment]
Yep!
