### ISSUE TITLE
computed crashes on start after killing random processes

### ISSUE THREAD

**Issue by lluki** [MaterializeInc/materialize#12843]
### What version of Materialize are you using?

7f1def06846d63228b11fe7262eeb9a0ed455882

### How did you install Materialize?

Built from source

### What is the issue?

The following steps bring the system in a state that crashes computed on every startup.

## Steps to reproduce
Run `./bin/materialized` and `cargo run --bin computed -- --listen-addr=127.0.0.1:2300 --http-console-addr=127.0.0.1:2203` in two separate terminals. In psql do:
```
CREATE CLUSTER foo REPLICAS (r1 (REMOTE ('localhost:2300')));
SET CLUSTER TO foo;
CREATE MATERIALIZED VIEW v1 AS SELECT COUNT(*) AS c1 FROM t1;
```
-- kill materialized and computed. restart. computed crashes upon startup.

If the bogged state has not been produce, continue in sql creating more materialized views
```
SELECT * FROM v1;
CREATE MATERIALIZED VIEW v2 AS SELECT COUNT(*) AS c1 FROM t1;
```
... and kill again. 

## Relevant terminal output from computed
```
thread 'timely:work-0' panicked at 'called `Option::unwrap()` on a `None` value', src/compute/src/server.rs:204:41
```

## Reproducability 
The setup steps are not 100% reproducible, it seems important that `materialized` and `computed` are killed in rapid fashion. So far I always reached the broken state after max. 3 iterations.
Once the invalid state has been created, the crash happens 100% of the time.

## Full logs
I had a `dbg!` statement on the received commands in computed, might be useful, but logs are big:
[full-logs.tar.gz](https://github.com/MaterializeInc/materialize/files/8825300/full-logs.tar.gz)

**Comment by lluki** [comment]
It's probably the same as #12645 and #12233

**Comment by lluki** [comment]
Ok, I can still reproduce it on the following commit (of 2022-06-07 22:44) 24d4111f577ee3b29500a3823f9e8ae7c9605639 .

Just for clarification: `--reconcile` is not passed.

**Comment by lluki** [comment]
computed output with `COMPUTED_LOG_FILTER=mz_dataflow_types::client=trace` set

[COMPUTED_LOG_TRACE.txt](https://github.com/MaterializeInc/materialize/files/8861393/COMPUTED_LOG_TRACE.txt)

**Comment by lluki** [comment]
So here is what I'm seeing:

src/dataflow-types/src/client/replicated.rs:138: fn send(..) of Partitioned: returns "client is reconnecting" error.

This error is then swallowed in the `spawn_client_task`  of replicated.rs

and this is how we lose the CreateInstance command.

**Comment by lluki** [comment]
This fixes the issue, although in a very ugly way:

```
diff --git a/src/dataflow-types/src/client/partitioned.rs b/src/dataflow-types/src/client/partitioned.rs
index 0aed5d61e..08e7bd03e 100644
--- a/src/dataflow-types/src/client/partitioned.rs
+++ b/src/dataflow-types/src/client/partitioned.rs
@@ -134,8 +134,8 @@ where
     R: fmt::Debug + Send,
 {
     async fn send(&mut self, cmd: C) -> Result<(), anyhow::Error> {
-        if self.reconnect.is_some() {
-            anyhow::bail!("client is reconnecting");
+        while self.reconnect.is_some() {
+            tokio::time::sleep(Duration::from_secs(1)).await;
         }
         let cmd_parts = self.state.split_command(cmd);
         for (shard, cmd_part) in self.parts.iter_mut().zip(cmd_parts) {
         ```

**Comment by lluki** [comment]
I tried to add a Notify, unfortunately I wasn't able to figure yet out how to position the notifies such that the process never gets stuck. 

I attached here my script that i use to start the processes, it opens a computed and materialized in a byobu (tmux) session. Instructions how to use it are on top of the file.
[mzt-byobu-cluster.py.tar.gz](https://github.com/MaterializeInc/materialize/files/8863595/mzt-byobu-cluster.py.tar.gz)

**Comment by antiguru** [comment]
Another fix to synchronously establish connections. This is bad because it'll block the coordinator until the connections are up.
```diff
diff --git a/src/dataflow-types/src/client/controller.rs b/src/dataflow-types/src/client/controller.rs
index 5e9632094..4fcf39fcf 100644
--- a/src/dataflow-types/src/client/controller.rs
+++ b/src/dataflow-types/src/client/controller.rs
@@ -192,7 +192,9 @@ where
         match config {
             ConcreteComputeInstanceReplicaConfig::Remote { replicas } => {
                 let mut compute_instance = self.compute_mut(instance_id).unwrap();
-                let client = ComputedRemoteClient::new(&replicas.into_iter().collect::<Vec<_>>());
+                let mut client =
+                    ComputedRemoteClient::new(&replicas.into_iter().collect::<Vec<_>>());
+                client.connect().await;
                 let client: Box<dyn ComputeClient<T>> = Box::new(client);
                 compute_instance.add_replica(replica_id, client);
             }
@@ -264,7 +266,8 @@ where
                             },
                         )
                         .await?;
-                let client = ComputedRemoteClient::new(&service.addresses("controller"));
+                let mut client = ComputedRemoteClient::new(&service.addresses("controller"));
+                client.connect().await;
                 let client: Box<dyn ComputeClient<T>> = Box::new(client);
                 self.compute_mut(instance_id)
                     .unwrap()
```
