### ISSUE TITLE
Avoid pre-empting timely and differential logging

### ISSUE THREAD

**Issue by frankmcsherry** [MaterializeInc/materialize#1284]
We currently capture timely and differential logging information, which prevents folks from doing this themselves. It seems not unreasonable that these raw logs are something we might find useful in crash reports, or other reports of weird behavior. For sure it would be even better to pre-anticipate what to record, but ideally we should not prevent more detailed logging.

I'm not entirely sure what happens now if materialized is run without logging, whether we allow timely and differential to perform their own logging. Much of the pressure-relief there assumes that you can compile your own code, which .. isn't how we expect to get crash reports.

**Comment by antiguru** [comment]
Not relevant anymore.
