### ISSUE TITLE
[Epic] Continual Reconciliation in `persist_sink`/MATERIALIZED VIEWs

### ISSUE THREAD

**Issue by nmeagan11** [MaterializeInc/materialize#12854]
### Initiative and Theme

Materialize is dependable; Materialize stays up and running

### Problem

This is necessary in order to re-shard a storage collection, deal with bugs, version a storage collection, and provide us a way to truncate a storage collection.

We've already found one use case for renditions outside of the above: introspection data in compute.

See the [storage architecture doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/platform/architecture-storage.md#renditions) for more information.

Work items:

 * [ ] Document renditions-lite (https://github.com/MaterializeInc/materialize/issues/12854#issuecomment-1226590167)

### Success Criteria

The use cases listed above are satisfied.

### Time Horizon

Large

### Blockers

None

### Blocks

- Version upgrades
- Productionizing compute's introspection data features
- Sinks (TBD based on design doc)

**Comment by benesch** [comment]
> We've already found two use cases for renditions outside of the above: introspection data in compute, and moving Postgres CDC off of using local disk.

Note that I no longer think we need renditions for moving Postgres CDC off of local disk.

**Comment by aljoscha** [comment]
> When the new writer succeeds at recording the rendition transition it will now at exactly which timestamp it needs to start producing updates to. However, before doing so it needs to wait for the `data_shard` to reach the transition upper which is what the old writer will do (see previous section) before exiting.

What happens when the "old writer" crashes before it can advance the upper of the `data_shard` to the transition upper?

**Comment by aljoscha** [comment]
I think this is implicit in the design but maybe we should make it explicit: the schema of the rows contained in `data_shard` cannot be changed, right?

How would we rendition any additional state that ingest workers/`storaged` might have? I'm thinking about the "complex" debezium deduplication state, for example.

**Comment by benesch** [comment]
Status update: we're implementing "renditions-lite" as an insurance policy against "renditions-full" not being ready in time. Here's a blurb from @frankmcsherry about it:

> Renditions-lite are implemented by a "self-correcting" `persist-sink` implementation. In order to write to a shard, it receives as input both the goal state of the collection, and the current contents of the shard. Repeatedly, based on the `upper` frontier of its `WriteHandle`, it attempts to commit the interval `[write.upper, target.upper)`, where `write.upper` is determined from the `upper` of the write handle (and what it has read from `persist`) and target.upper is the upper bound of data it has received from both the goal state dataflow (so, the frontier through which it is certain it knows the correction to apply).
>
> Its repeated behavior is to attempt to commit `[write.upper, target.upper)` in to persist, over and over and over. As it hears back from `persist` about committed data, it effectively "commits" changes that it has landed, in that they no longer need to be subtracted.
>
> On a successful write, the contents of the persist shard for `[write.upper, target.upper)` are exactly the contents of `target` on that interval.

I've heard that @aljoscha's latest `persist_sink` PR (#14001) has an implementation of renditions-lite, but I'm not sure!

**Comment by aljoscha** [comment]
@benesch Yes, that sounds correct!

**Comment by nmeagan11** [comment]
Because #14001 is now merged (🎉, @aljoscha!), I've raised https://github.com/MaterializeInc/materialize/issues/15084 for tracking the remaining work to go from renditions-lite to renditions-full. I'd like to rename this epic to be something along the lines of "Renditions Foundation" so we can capture the remaining work in the new issue, and close this one out. Thoughts?

**Comment by aljoscha** [comment]
Title of this one could be sth like "continual reconciliation in persist_sink/MATERIALIZED VIEWs". That somewhat accurately describes what it does, we just continually make sure that what we store in persist matches the output of compute, be that during runtime or when (re-)starting up a new compute replica.

Also sounds vague and high-brow, though ... 😅

**Comment by nmeagan11** [comment]
I've gone with it for now!

**Comment by aljoscha** [comment]
@nmeagan11 should we close this one and mark as finished no the board? I don't think there's much Philip can test for this one. It doesn't change the externally visible behavior, but mostly makes us more resilient to errors.

**Comment by nmeagan11** [comment]
Sounds good, closing!
