### ISSUE TITLE
[Epic] Storage Reconciliation

### ISSUE THREAD

**Issue by nmeagan11** [MaterializeInc/materialize#12857]
### Initiative and Theme

Materialize is dependable; Materialize stays up and running

### Problem

This epic is simply recovery for `storaged`. In the event that `storaged` crashes and comes back up, the history of commands is replayed to it so that it can get back to a healthy state.

### Work items

* [x] https://github.com/MaterializeInc/materialize/issues/13132 is required for testing this feature
* [x] #13468
* [x] @philip-stoev's sign off

### Success Criteria

`storaged` crashes and can come back up into a healthy state.

### Time Horizon

Small

### Blockers

None

**Comment by guswynn** [comment]
Status:
- @benesch wrote #13444 which implements reconciliation for when environmentd restarts and reconnects to storaged
- @guswynn wrote #13360 which implements rehydration of storaged instances that are killed/restarted
  - It will need to be rebased after #13444 is merged
  - It will need to be adjusted to look more like https://github.com/MaterializeInc/materialize/blob/bca844c19192757b0c2de7d0236e797edfba4c4c/src/compute-client/src/controller/replicated.rs#L48-L208 to handle more complex failure modes (like a secondary failure DURING rehydration)

**Comment by philip-stoev** [comment]
I have added storaged killing and restarting to the Zippy and Platform Checks frameworks:
- Zippy will perform about a dozen kills+restarts of storaged-s during a 30-min test that ingests several millon rows from multiple kafka topics into materialized sources
- The Checks Framework performs 3 kills+restarts while manipulating Kafka sources of various shapes and sizes.
Both frameworks use ENVELOPE UPSERT and ENVELOPE NONE sources.

I think that is sufficient to consider this epic QA-complete, even though I will try to add additional scenarios going forward.

Please let me know if you have any questions or QA testing requests

**Comment by benesch** [comment]
Wonderful. Thanks very much, @philip-stoev!

**Comment by benesch** [comment]
Now that the `persist` connection pool is in, this is complete! h/t to @uce for calling this out. The one incomplete task that @guswynn mentioned above about `resume_upper` is tracked by https://github.com/MaterializeInc/materialize/issues/13534.
