### ISSUE TITLE
[Epic] Incremental State in `persist`

### ISSUE THREAD

**Issue by nmeagan11** [MaterializeInc/materialize#12862]
### Initiative and Theme

Materialize is Scalable; Materialize can maintain performance when data volumes increase

### Problem

Currently, persist gets slower as it accumulates more writes. This is due to the metadata (state) getting larger because it has to write to Aurora in entirety for each update. #11491 will mitigate this somewhat, but if compaction falls behind temporarily (or if we don't want to tie the compaction schedule tightly to the rate of incoming writes), we don't want persist latencies to spike.

### Success Criteria

- Allow persist to write out diffs to its state. Periodically roll that up into a full copy of the state to bound restart times.
- Persist write latencies remain constant as data accumulates.

### Time Horizon

Extra-Large

### Blockers

None

**Comment by benesch** [comment]
I added "in `persist`" to the title of this epic to make its scope clearer when scanning the project tracker.

**Comment by aljoscha** [comment]
@danhhz Should we close this one now, after https://github.com/MaterializeInc/materialize/pull/14250 and follow-up fixes merged?

We might add more metrics and tune things as we observe production workloads but the main work is done now.

**Comment by danhhz** [comment]
Yup! Closed by #14250
