### ISSUE TITLE
Leasing

### ISSUE THREAD

**Issue by nmeagan11** [MaterializeInc/materialize#12861]
### Initiative and Theme

Materialize is Scalable; Materialize can maintain performance when data volumes increase

### Problem

Part of #11491. At the moment, a crashed or partitioned reader can hold up compaction indefinitely.

### Success Criteria

Compaction is not blocked by a crashed or partitioned reader.

### Time Horizon

4 weeks

### Blockers

None

**Comment by benesch** [comment]
@aljoscha says this is done!
