### ISSUE TITLE
Harden the Storage/Compute Separation

### ISSUE THREAD

**Issue by nmeagan11** [MaterializeInc/materialize#12866]
### Initiative and Theme

Materialize is scalable; Materialize can maintain performance when data volumes increase

### Problem

In M1, we separated storage and compute (#11528). Improvements we'd like to make include:

- providing a better fat client to compute
- adapting the separation as we make storage collections more complicated (e.g. adding renditions, sharding, etc.)
- work around `since` and the API boundaries between `storaged` and the storage controller (which impacts restarts)

This should be covered across various M2 storage epics, but I'm keeping this issue open in case we want a centralized place to track outstanding tasks.

**Comment by benesch** [comment]
@nmeagan11 can we close this one out? It's been a few months and we haven't found anything to track here.
