### ISSUE TITLE
ci: cargo test has several ignored tests

### ISSUE THREAD

**Issue by benesch** [MaterializeInc/materialize#12886]
Several Cargo unit/integration tests have been ignored in the transition to platform:

  * test_pgtest
  * test_mz_pgtest
  * test_no_block
  * test_tail_progress
  * test_tail_progress_non_nullable_columns

We should figure out what's causing these tests to fail and get them turned back on ASAP.

@jkosh44 has several PRs out to this effect:

  * [ ] #12787
  * [ ] #12812
  * [ ] #12850

**Comment by jkosh44** [comment]
I have some more details on these test failures here: https://github.com/MaterializeInc/materialize/issues/12786

**Comment by benesch** [comment]
Oh way better! Thank you! I'll update #12887 with that.
