### ISSUE TITLE
storage: all data at the same offset must be buffered in memory during ingestion

### ISSUE THREAD

**Issue by benesch** [MaterializeInc/materialize#12893]
With the new design of the `persist` library, all data at the same timestamp must be presented to [`append`](https://dev.materialize.com/api/rust/mz_persist_client/write/struct.WriteHandle.html#method.append) in the same call.

This has grim memory characteristics for e.g. the PostgreSQL source, which presents all data in the initial snapshot at the same offset. See https://github.com/MaterializeInc/materialize/issues/11953#issuecomment-1146870618.

One proposal from @frankmcsherry is that the `persist` library could expose an API where the client can pre-stage chunks on S3, then provide those chunk references to the `append` call. Then the source ingestion pipeline could periodically send its buffered data to S3 and free it from memory.

@danhhz @aljoscha—is something like this in line with persist's direction?

No particular rush on this, I don't think—we can throw memory at the problem in Materialize Cloud for a bit—but wanted to flag ASAP!

**Comment by aljoscha** [comment]
The behaviour of `append()` is quite in line with how `Append` is described in `formalism.md`, BUT: we recently split uploading of updates and appending to a shard (#12477). With this new API, a source would call `WriteHandle::builder()`, then keep appending updates to the builder, and finally call `WriteHandle::append_batch()`. (fyi @cjubb39 & @guswynn & @petrosagg)

This solves the problem for source implementors, but we have this TODO in the persist code that would make it behave well behind the scenes: https://github.com/MaterializeInc/materialize/blob/9a010390d37c68c6ae5af53e1136fabd467cc0e8/src/persist-client/src/write.rs#L785.

**Comment by benesch** [comment]
Oho! Incredible!

**Comment by danhhz** [comment]
Yup! The append call is actually just sugar for doing the two operations at this point.

In fact, building on what aljoscha said, if a persist user hands us an iterator that isn't materialized in memory anywhere, the original `WriteHandle::append` call will also have bounded memory usage (once we do the TODO he mentioned of course, but that's slated for M2 and entirely internal to persist, it won't change the API.) The builder/append_batch split API he mentioned does make this a bit more ergonomic though, since that data being added only needs to live as long as the `BatchBuilder::add` call (if the iterator was non-materialized, it would have to be owned data).

**Comment by guswynn** [comment]
For postgres we already have an issue to fix this: https://github.com/MaterializeInc/materialize/issues/12557
There are 3 things going on:
- What that issue actually talks about, where we shouldn't need to buffer messages; once we pick a ts for an offset, we can just avoid closing that offset (ie, advancing the cap) until we get the finalized message
- The final API that we come up with for reclocking: https://github.com/MaterializeInc/materialize/issues/12600. This interacts with the first issue, as we need to make sure both problems are fixed
- Once those issues are fixed, the pg source itself needs to be changed to not self-buffer transactions AND the snapshot; for the same reasons outlined above, this is fine, as long as we ensure we don't close the transaction/snapshot ts until we are actually done. I believe this is fairly trivial, even if snapshotting fails, we are sending the retractions in the same timestamp

**Comment by benesch** [comment]
Sweet! Closing. I think it is not a duplicate—just a work item that you completed in #12980! I filed https://github.com/MaterializeInc/materialize/issues/13116 to track actually using this API in storage and linked it in #13039.
