### ISSUE TITLE
sql: remove `populate_connectors`

### ISSUE THREAD

**Issue by benesch** [MaterializeInc/materialize#12936]
Part of #11504.

The [`populate_connectors`](https://github.com/MaterializeInc/materialize/blob/da4de73bd8d8c764470dcd97ba411410afdfcfb9/src/sql/src/connectors.rs#L22-L250) function is a bit of a hack that sidecars connector data into the AST so that it is available to the `purify_create_source` function.

We should instead change `purify_create_source` to take a `Box<SessionCatalog>`. We can just clone the `ConnCatalog` to make the lifetimes work out. Then `purify_create_source` can just _look up_ connector references in the catalog, rather than doing this complicated pre-population.

To make this safe, we need to ensure that purification only looks at `GlobalId`s mentioned in the statement, and then double check that those `GlobalId`s still exist after the async purification task returns, as a `DROP` may have slipped in while the async task was running.

**Comment by cjubb39** [comment]
whoops -- need to make sure we check that the `GlobalId`s that we used in purification still exist afterwards.  Can't close yet!

**Comment by benesch** [comment]
Oh I ended up filing that separately as #12983! So we can close this!
