### ISSUE TITLE
stash: remove SQLite backend

### ISSUE THREAD

**Issue by benesch** [MaterializeInc/materialize#12949]
Once #12947 merges, we'll no longer have any users of the SQLite stash backend. Seems like we should remove it, as it's one less module to support and test. We can make `catalog_postgres_stash` a non-optional parameter of the coordinator configuration.

**Comment by benesch** [comment]
@mjibson points out that there are a few catalog tests that rely on the in memory stash: https://materializeinc.slack.com/archives/CMHDK0DK8/p1654572029266549?thread_ts=1654569815.352959&cid=CMHDK0DK8

We could swap those to use the `Memory` implementation of `Stash` instead. Would require a bit of elbow grease, as `Memory` is currently a _cache_ over a different `Stash` implementation—whereas we would need it to stand on its own.

**Comment by mjibson** [comment]
It's also used by storage:

https://github.com/MaterializeInc/materialize/blob/274d9f541b7349a535de56f64d506cd9ce5c1d71/src/dataflow-types/src/client/controller/storage.rs#L295

**Comment by JLDLaughlin** [comment]
I believe this is done, @mjibson can you confirm?

**Comment by mjibson** [comment]
Still used by some tests. Can't remove yet.

**Comment by mjibson** [comment]
I wrote up most of a working fully in memory implementation and realized that we gain almost nothing from removing sqlite as a backend if we still have to have some in memory (either sqlite in mem or non sqlite in mem) because there are catalog tests that use this, which are the actual problem. I'm closing this because I don't think those tests should depend on a running cockroach in order to work, so we do actually need this code.

**Comment by benesch** [comment]
Do you mind if we leave this open? `rusqlite` is a heavyweight dependency that I would love to get rid of some point. Doesn't need to be now, but I do think the long term maintenance burden of a from-scratch in-memory `Stash` implementation will be lower than the maintenance burden of the current sqlite code, since it won't require bringing in and upgrading the whole rusqlite dependency tree.

**Comment by benesch** [comment]
But it's definitely really low priority!

**Comment by mjibson** [comment]
Ah, yes, that's a good enough reason. I didn't know that. My memory impl is <1hour of work away from working.
