### ISSUE TITLE
Support `ALTER CLUSTER SWAP c1 c2`

### ISSUE THREAD

**Issue by frankmcsherry** [MaterializeInc/materialize#12972]
### Feature request

This is a hypothetical feature from @benesch that would allow users to atomically swap the binding of names to clusters, so that one can implement blue/green deployments, at least in the `SELECT` pipeline. This is not at the point of having a specific design in mind, but the intent would be you could type

```sql
ALTER CLUSTER SWAP blue green;
```
and have `blue` and `green` resolve to the swapped clusters, so that e.g. one can choose `blue` to be the production cluster, and continually modify `green` until it is in a stable state, and then swap it in.

Related to, but not the same as #5680

## See also

* https://github.com/MaterializeInc/materialize/issues/22250

**Comment by benesch** [comment]
One of our prospects notes that this should take into account clusters taht that are daisy chained via materialized views. Consider a cluster b1 and a cluster g1, writing to materialized views bv1 and gv1, respectively. Downstream clusters b2 and g2 read from bv1 and gv1. When you execute `ALTER CLUSTER SWAP b1 g1`, g1 will continue to write to bv1 and b1 will continue to write to gv1. That's confusing, if nothing else. It gets further misaligned with `ALTER CLUSTER SWAP b2 g2`.

One potential solution is to allow for bulk swapping of things:

```
BEGIN;
ALTER CLUSTER SWAP b1 g1;
ALTER CLUSTER SWAP b2 g2;
ALTER MATERIALIZED VIEW swap bv1 gv2;
COMMIT;
```

There may be a deeper issue here, which is that users will want to treat materialized views as abstraction boundaries. It'd be nice to be able to swap which cluster is writing into a materialized view _without_ dropping the materialized view. Then any downstream views would be able to keep reading the view unaffected. This is feasible, ish, if the new cluster and old cluster agree on the schema of the materialized view; it gets a whole lot more complicated if you want to entirely change its schema.

**Comment by morsapaes** [comment]
Also noting from a few of internal threads ([here](https://materializeinc.slack.com/archives/C048W6Q7SPL/p1668178060310969) and [here](https://materializeinc.slack.com/archives/C040V3UJLQP/p1672168167269379)) that `ALTER DATABASE...SWAP` and `ALTER SCHEMA...SWAP` (which depend on #3680) would be a pre-requisite for handling blue-green deployments using this approach. For reference, [this workflow](https://discourse.getdbt.com/t/performing-a-blue-green-deploy-of-your-dbt-project-on-snowflake/1349) is in line with the expectations of users for this operation.

**Comment by benesch** [comment]
@morsapaes notes that this feature overlaps with #17417. We should consider the implications of #17417 on this feature.
