### ISSUE TITLE
Setup the core of distributed tracing with mz

### ISSUE THREAD

**Issue by guswynn** [MaterializeInc/materialize#13019]
- [x] Prepare for a basic tracing demo next week
- [ ] #12878
- [x] Decide on the structure of traces inside a process. cc @andrioni, we are leaning towarding using `tracing::Span`'s and manually managing the parental structure when they cross queue/task boundaries
  - [x] Note this also reduces the total event rate 
- [x] Trace all types of queries (execute vs query vs etc) in pgwire
- [x] Manage the total event-rate being sent to honeycomb
  - [x] Note that the idea just above helps with this
  - [x] #13002
  - [x] Increase our contractual limit
  - [x] replaced with tempo
- [ ] Throughly document how to use tracing within `mz`
- [ ] upstream `tokio-postgres` event-ing to be `trace!` and not `debug!`
- [ ] Setup the span kind correctly: https://docs.rs/tracing-opentelemetry/latest/tracing_opentelemetry/#special-fields
- [ ] Document the `tracing-otel` -> otel conversion

etc:
- [ ] https://docs.rs/tower-http/latest/tower_http/trace/index.html for our http servers
- [ ] https://github.com/MaterializeInc/materialize/issues/12945
- [ ] fix https://github.com/MaterializeInc/materialize/issues/16422
- [ ] figure out why https://github.com/MaterializeInc/materialize/pull/16443 is required

**Comment by andrioni** [comment]
> Manage the total event-rate being sent to honeycomb

We might also want to control this by exposing better ways of sampling events in Honeycomb itself (cf. [this tweet](https://twitter.com/lizthegrey/status/1536611324179804161)).

**Comment by andrioni** [comment]
Question: is it viable to do something at the `RemoteClient`-level to automate passing spans around? For the cases I've seen/implemented so far, I had to ship tracing information manually with my payloads/commands, but in my experiences before Materialize, this would all happen transparently in the lower layers (e.g. just like serialization), and handlers could just assume that they are already being called with the proper tracing context.

(that said, I have no idea how this would look like in Rust-land or how to make it idiomatic)

**Comment by guswynn** [comment]
> We might also want to control this by exposing better ways of sampling events in Honeycomb itself (cf. [this tweet](https://twitter.com/lizthegrey/status/1536611324179804161)).

Wow, so honeycomb can do sampling server-side? Cause client-side causes problems when you need traces on different machines associated with each other to be useful

**Comment by guswynn** [comment]
> Question: is it viable to do something at the RemoteClient-level to automate passing spans around? For the cases I've seen/implemented so far, I had to ship tracing information manually with my payloads/commands, but in my experiences before Materialize, this would all happen transparently in the lower layers (e.g. just like serialization), and handlers could just assume that they are already being called with the proper tracing context.

> (that said, I have no idea how this would look like in Rust-land or how to make it idiomatic)

you know, its unclear HOW free it will be, I think https://github.com/MaterializeInc/materialize/pull/12828 can be cleaned up to use `Span` instead of `OpenTelemetryContext`'s. Its *possible* that each remote client can make sure the proper thread-local context is maintained, but I think that may just end up being more annoying. I think the interface to the controller/clients can be kept pretty simple tho...definitely something to play with

**Comment by andrioni** [comment]
I _think_ it's sort of in the middle between client-side and server-side: [Refinery](https://docs.honeycomb.io/manage-data-volume/refinery/) can ingest all the samples do the [more context-aware smart sampling](https://docs.honeycomb.io/manage-data-volume/refinery/sampling-methods/#intro-current-mode) before pushing them out to Honeycomb. It's client-side in the sense that we need to manage Refinery, but we don't need to worry about it in the code or manage it for each deployment separately.

@antifuchs did we ever deploy Refinery?

**Comment by guswynn** [comment]
TIL about refinery, seems cool!

**Comment by antifuchs** [comment]
> did we ever deploy Refinery?

Not yet! I'm gonna work on that next, it's gonna be especially important now that we send data into a system with a quota (:

**Comment by benesch** [comment]
Closing, as I don't think we're actively using this for tracking any more!
