### ISSUE TITLE
[Epic] Add the Rest of the Kafka Envelopes to Platform

### ISSUE THREAD

**Issue by nmeagan11** [MaterializeInc/materialize#13044]
### Initiative and Theme

Materialize is Friendly; Materialize works with your existing pipelines

### Problem

Some users do not use what we are supporting in M1 (`ENVELOPE NONE`). We need to bring back the envelopes from pre-Platform to make our Kafka sources useable for more folks. In order of Priority:

- None (any more work to do here?)
- Debezium
  - [ ] #13310
- Debezium Upsert
  - [x] #13311
- Upsert
  - [x] #13312

### Success Criteria

Users can successfully execute a CREATE SOURCE ... FROM KAFKA statement using the same envelopes they were able to use pre-Platform.

### QA Sign-off
- [x] Final sign-off that all envelopes are present in Zippy, Checks Framework, Feature Benchmark

### Time Horizon

Large

### Blockers

- https://github.com/MaterializeInc/materialize/issues/11772

**Comment by umanwizard** [comment]
I am closing this out now even though we haven't added `ENVELOPE DEBEZIUM`, because we've added everything that we plan on working on in the foreseeable future.
