### ISSUE TITLE
storage: incrementally write data at the same timestamp to persist

### ISSUE THREAD

**Issue by benesch** [MaterializeInc/materialize#13116]
Part of epic #13039. See #12893 for some additional background.

The source ingestion pipeline, if presented with data at the same timestamp, will buffer all that data in memory before writing it to `persist` in one shot:

https://github.com/MaterializeInc/materialize/blob/97a6139e21151669aaf6c3292a84b96c0b9c3e4e/src/storage/src/render/persist_sink.rs#L118

This is particularly a problem for PostgreSQL sources, which present the entire initial snapshot at the same timestamp. So even a relatively small PostgreSQL database (e.g. 10GB) will have hefty memory requirements in Materialize Cloud.

The `persist` API recently learned to incrementally build up batches and write them to S3 without committing the actual append operation. See #12980.

The work item here is to adjust the `persist_sink` linked above to use the new `BatchBuilder` API. We don't need to get too fancy with the batch sizing policy to start; anything rudimentary that bounds memory usage would be acceptable.

**Comment by guswynn** [comment]
note that this needs to be optimized still

**Comment by benesch** [comment]
Thanks for knocking this one out, @guswynn! I think we can call this one done for the purposes of M2 though. Can you file a new issue about the possibility of optimization and brain dump as much context as you have, so @nmeagan11 can prioritize appropriately?

**Comment by guswynn** [comment]
@benesch https://github.com/MaterializeInc/materialize/issues/13116 as is does cause certain nightly tests to timeout now, I think there is at least one relatively simple upgrade to the number of persist calls we can do that should be done; Ill write an issue talking about
