### ISSUE TITLE
doc/user: Sinks documentation (NOT ENFORCED)

### ISSUE THREAD

**Issue by joacoc** [MaterializeInc/materialize#13119]
### What pages are affected?

https://materialize.com/docs/sql/create-sink/

### What needs to be changed or added?

> Sinks let you stream data out of Materialize, using either sources or views.

Tables are also an option.

----

The `NOT ENFORCED` keys option should figure somewhere.

The documentation about `ENVELOPE UPSERT` in sinks redirects to the sources section about how to [handle upserts](https://materialize.com/docs/sql/create-source/kafka/#handling-upserts) and talks about primary keys and `NOT ENFORCED` from a source perspective and not in a sink perspective where primary keys are not so relatable like in sources.

Related community issue:
https://materializecommunity.slack.com/archives/C015KDVS7EV/p1655120646237569

**Comment by benesch** [comment]
Now being discussed in #19143.
