### ISSUE TITLE
Least common denominator ingestion

### ISSUE THREAD

**Issue by frankmcsherry** [MaterializeInc/materialize#1312]
It seems plausibly interesting to work out a least common denominator input ingestion story. Things like Kafka and files are swings at this, but come with pains (administration, on-disk footprint) that make them not appropriate for folks trying things out. Other hypotheses include HTTP endpoints, TCP connections, or other low-overhead stream-y interfaces.

**Comment by benesch** [comment]
Tables are now our answer to this, especially once we support table persistence. #1701 tracks the addition of an HTTP interface to tables.
