### ISSUE TITLE
Adding Persistence Earlier in the Pipeline

### ISSUE THREAD

**Issue by nmeagan11** [MaterializeInc/materialize#13121]
### Feature request

Today's pipeline roughly looks like the following:

`ingest` -> `decode format` -> `apply envelope` -> `persist`

We are thinking to add another persist layer in the pipeline immediately following `ingest`, i.e.:

`ingest` -> `persist_early` -> `decode format` -> `apply envelope` -> `persist_late`

`persist_early` represents the raw bytes received from the upstream source (e.g. Kafka). `persist_late` is the fully decoded, compacted data that compute reads from.

`persist_early` would only be re-read in cases where we had some kind of decode/envelope bug and a new version of `storaged` would be needed to reflow the `persist_early` data to rewrite a version of `persist_late`. The main advantage to adding this is to give us a way of protecting against bugs in ingest. For instance, if we only persist after decoding and we have a bug (meaning we persist bad data because of how an upsert is calculated, how Avro is decoded, etc.) and the upstream source has deleted data, there's nothing we can do. The main disadvantage is that this forces us to persist all incoming data with no compaction (which could be a compliance problem), and could create significant storage costs. We'd also have to figure out how we'd want to start up `storaged` and rewrite `persist_late`, which is challenging.

**Comment by danhhz** [comment]
>> The main disadvantage is that this forces us to persist all incoming data with no compaction (which could be a compliance problem), and could create significant storage costs.
>
> sorry if I'm being dense, but I'm not connecting the dots on how the compliance problem is easier for persist_late than for persist_early. any pointers?

oh I think I understand! is the thinking that because persist_late is compactable, if a user e.g. deletes the key corresponding to a user from kafka, then eventually it gets compacted out of persist_late? okay I think there's something we could do here but I'd have to mull it over before I could coherently articulate it

**Comment by nmeagan11** [comment]
> if a user e.g. deletes the key corresponding to a user from kafka, then eventually it gets compacted out of persist_late?

That is exactly the thinking, yes!

> also IMO I'm personally not convinced yet that the storage costs are a deal-breaker

TBH, I have no idea if it actually is. I just want to make sure it's something we think about in case it ends up being a massive difference.

**Comment by frankmcsherry** [comment]
> sorry if I'm being dense, but I'm not connecting the dots on how the compliance problem is easier for persist_late than for persist_early. any pointers?

I think there's GDPR/CPRA questions about "do we still have your data after you've asked us not to have it". Either for us, or if not use for the people using MZ. It becomes clearer in a compacted world, and less clear in a non-compacted world. IANAL, ofc, but that is probably part of the sensitivity.

> also IMO I'm personally not convinced yet that the storage costs are a deal-breaker. maybe others have seen some data I haven't?

In a not-hypothetical use case, one MZ user was turning over their collection of data roughly each 30s. Over a 3 month period (a hypothetical M3, say), this ends up being a 250,000x multiplier on volume of data we store for them, over what we would store in a compacted representation. So, in "high churn" workloads, there's a potentially scary limitation involved (one not present in append-only workloads).

**Comment by benesch** [comment]
Should we get a meeting on the books to talk through the tradeoffs here? The engineering and product considerations are even more intertwined than usual.

**Comment by aljoscha** [comment]
@nmeagan11 has a meeting scheduled for this on Thursday, maybe we should just add more people to that?

**Comment by benesch** [comment]
Oh great, yes, @nmeagan11 I'd love to join.

**Comment by benesch** [comment]
> Suppose we nail these three cases -- UPSERT, DEBEZIUM and DEBEZIUM UPSERT -- how much coverage does this get us in practice (probably a question for @nmeagan11 too)?

There are no other envelope types, if that is the question?

> And suppose we have 100% coverage on different envelope types -- does that reduce the benefits of early_persist to handling errors in our ingestion process?

Yes.

> Or is the probability of something sneaking through so high that we need this extra insurance policy?

Exactly.

**Comment by frankmcsherry** [comment]
I haven't seen much feasibility discussion here, which is the main thing that worries me. Each 1MB/s of data ingested is a monthly 2.5TB. We have plenty of folks hoping to ingest at rates that are many multiples of that. Let's say that folks are ingesting data at a reasonable rate, how much faster than realtime do we expect we'll go when we re-read all the data? Like, 30x? Each month you've been using MZ takes an additional full day to recover? Probably not 30x, though; probably .. pretty similar max throughput as there isn't any data reduction, and for folks who were nearly maxing out ingest throughput, they probably just won't get their data back because we can't re-read it in a reasonable time.

**Comment by aljoscha** [comment]
> I haven't seen much feasibility discussion here, which is the main thing that worries me. Each 1MB/s of data ingested is a monthly 2.5TB.

Very good point! That's already a problem with append-only sources, right? For those, updates would pile up similarly.

**Comment by frankmcsherry** [comment]
Yes, though I don't think they are equivalent. Append-only sources (`ENVELOPE NONE`) are imo pretty clear that they will pile up, whereas upsert and Debezium exist because folks want to communicate retractions and have the expectation that this can avoid unbounded growth.

**Comment by frankmcsherry** [comment]
Counter-proposal for to early persistence, from the point of view of "bug sensitivity": tell users that best practices are to retain your upstream data until you have confirmed that it has landed successfully in Materialize. This seems like a very easy story, and responsible behavior even with the backstop (maybe there are bugs in `rdkafka`; who knows).

**Comment by andrioni** [comment]
>Append-only sources (ENVELOPE NONE) are imo pretty clear that they will pile up

Yes, but most of them dealt with append-only sources pre-platform via temporal filters, and we don't have an equivalent for persisted collections yet. Early persist makes it worse, but it doesn't change the fundamental issue there.

(temporal filters/retention is a separate issue, I just wanted to raise that the situation right now for append-only sources is a bit limited overall, independent of early persist.)

**Comment by benesch** [comment]
> Counter-proposal to early persistence, from the point of view of "bug sensitivity": tell users that best practices are to retain your upstream data until you have confirmed that it has landed successfully in Materialize. This seems like a very easy story, and responsible behavior even with the backstop (maybe there are bugs in rdkafka; who knows).

The bugs that `persist_early` is most valuable for, IMO, are not the bugs that cause persist to fail to correctly write down the raw data, but bugs in e.g. debezium deduplication, like @aljoscha mentions:

> One more point about persisting envelope state: if we don't have persist_early we lock ourselves into the layout/representation of state that we initially chose (or at least make it very hard to change that). Say we notice that the way we do debezium deduplication doesn't work and we need to change it, that likely comes with changes in what state we keep. This has already changed a couple of times in the past.

----

> if we can support the three envelope types without persist_early then there are enough implicit retention policies in place then I don't worry about append-only envelopes being a problem with customers -- we just tell them what it means in the short term for storage (they may use a lot)

Well this is the big if! Without `persist_early`, we're not on track to have anything besides `ENVELOPE NONE` available in Materialize Cloud (https://github.com/MaterializeInc/materialize/issues/13044).

**Comment by frankmcsherry** [comment]
Tbh, "we will make a back-up copy of all of your input stream so that you are future proofed against mistakes we make" sounds a whole lot like an enterprise feature. There's risk that we have bugs, all up and down the stack, just like there is today. We are already planning not to present a source of truth for the first iteration, much like today, and .. it just doesn't seem like there is a fire doing the same thing ("we had bugs in our DBZ logic; we are very sad, apologize greatly, etc, and politely request that you drop and recreate your source").

**Comment by benesch** [comment]
@nmeagan11 ran a great meeting on this today. Notes here (internal only): https://docs.google.com/document/d/1eYXH2lghkK3YbEN8Bfe0AAybeHQl8a4VJVGSOvCqDHQ/edit#heading=h.xvb3zhypfavc

The following is my recollection of what we decided. @petrosagg suggested that we not think of `persist_early` as a separate stage of the pipeline that would be enabled irrespective of the envelope. Instead, we should think of `persist_early` as the most naive possible implementation of `ENVELOPE DEBEZIUM`'s internal state.

As @aljoscha [mentioned above](https://github.com/MaterializeInc/materialize/issues/13121#issuecomment-1160405970), here's what we need to do to enable each envelope in the new Materialize Cloud:

  * `ENVELOPE NONE` needs no state.
  * `ENVELOPE UPSERT` can rehydrate its state by looking at its own output collection. This is straightforward to do. The most naive implementation is also the most optimal.
  * `ENVELOPE DEBEZIUM` and `ENVELOPE DEBEZIUM UPSERT` would ideally store complicated state, along the lines laid out in @aljoscha's [draft PR](#10205). But we could instead say "eh, forget it, let's just write down the entire input collection as we see it and restart from the beginning" as a short term option to get us Debezium support in the M2 timeframe.

To state it another way: the key insight here is that we only need to consider whether to make a copy of the entire input collection or not in the context of `ENVELOPE DEBEZIUM`/`ENVELOPE DEBEZIUM UPSERT`. 

@nmeagan11, I propose that we close this issue, and file separate issues for `ENVELOPE UPSERT` and `ENVELOPE DEBEZIUM` that are part of the #13044 epic. In the `ENVELOPE DEBEZIUM` issue, we link this discussion. Then we can decide whether or not to take the shortcut when we get around to `ENVELOPE DEBEZIUM`.

**Comment by nmeagan11** [comment]
Closing in favor of #13310 and #13311.
