### ISSUE TITLE
Wire up `CREATE SOURCE ... REMOTE` for testing

### ISSUE THREAD

**Issue by benesch** [MaterializeInc/materialize#13132]
## Background

We have an `--unsafe-mode`-only option for creating clusters that are attached to existing `computed` processes:

```
CREATE CLUSTER REPLICA a.b REMOTE ['localhost:1234']
```

This is quite useful for @philip-stoev's testing, so that he can manually control the lifecycle of a `computed` process.

## Description

We should add the same option, again gated behind `--unsafe-mode` to sources:

```
CREATE SOURCE s FROM KAFKA ... REMOTE 'localhost:1234'
```

This would require an already-running, properly-configured `storaged` process at `localhost:1234`. As with clusters, `REMOTE` sources will allow @philip-stoev to manually control the lifecycle of a `storaged` process to test its fault tolerance, etc.

**Comment by philip-stoev** [comment]
Yes, such functionality is essential for testing and therefore very much appreciated! Note however that right now killing a `storaged` also brings down `materialized`, so this limitation also needs to move out of the way for full-blown testing to be possible. I guess this is what `storage reconciliation` is about, but I wanted to state it explicitly for the record.

**Comment by andrioni** [comment]
>As with clusters, REMOTE sources will allow @philip-stoev to manually control the lifecycle of a storaged process to test its fault tolerance, etc.

Is the idea here that Philip will create the remote source, and then manually kill the other process outside of `mz`, or that he would do a `DROP SOURCE`?

Also, what is the expected behavior for `DROP SOURCE` for a source created via `REMOTE`?

**Comment by philip-stoev** [comment]
> Is the idea here that Philip will create the remote source, and then manually kill the other process outside of mz, or that he would do a DROP SOURCE?

I would do both, if Mz would allow me. For `DROP SOURCE`, my personal expectation is that:
- if the storaged can safely be left behind, then I will try to reuse the same storaged for some other `CREATE SOURCE` and hope the right thing will happen;
- if the storaged can not be safely left behind, it will need to exit on its own accord
