### ISSUE TITLE
Sinks can produce duplicate output when logical compaction window is 0

### ISSUE THREAD

**Issue by teskje** [MaterializeInc/materialize#13198]
### What version of Materialize are you using?

v0.26.1-dev (6cc1340ec)

### How did you install Materialize?

Built from source

### What is the issue?

When you set the logical compaction window to zero (e.g. by starting `environmentd` with `--logical-compaction-window 0`), sinks can emit duplicate updates in the face of replica restarts. I've verified that this can happen both with TAILs and persist_sinks.

When you have a sink running and your compute replica is restarted, it gets re-hydrated with the sink dataflow having its `as_of` set to the previous `since` of the sink (determined by looking at `AllowCompaction` commands during history reduction). The first thing the sink dataflow does is send the current contents of the sinked collection at time `as_of`. Some instance (for TAIL it's `ActiveReplication`, for persist_sinks it's the persist library) keeps track of the sink's `upper` and ignores outdated updates accordingly. So if `since` (and therefore `as_of`) < `upper`, the collection snapshot is recognized as outdated and correctly ignored.

But if the compaction window is zero, then the sink’s `since` can be equal to its `upper` and therefore during re-hydration the dataflow’s `as_of` can also be equal to the previously reported `upper`. This means `ActiveReplication`/`persist` views the collection snapshot as new updates for the sink and doesn’t drop them. The sink output now includes duplicates.

Discussion: https://materializeinc.slack.com/archives/CM7ATT65S/p1655796360690279

**Comment by philip-stoev** [comment]
I am adding the C-triage to this one so that it is reconsidered as it is a potential correctness issue.

**Comment by teskje** [comment]
AFAICT it's not possible to specify a compaction window of 0 currently. The `environmentd` CLI option was removed in https://github.com/MaterializeInc/materialize/pull/13428, and in SQL there is only support for setting the compaction window for indexes. The later functionality is behind `--unsafe-mode`, and it shouldn't affect the `since`s of sinks anyway. Finally, @aljoscha self-healing persist sink should solve the issue for materialized views, even if it was possible to set a 0 compaction window for them.

So right now this is a non-issue. The only way it might become an issue in the future is if we introduce a way for users to specify an arbitrary compaction window for TAILS.
