### ISSUE TITLE
dbt-materialize: consider adding a Materialize dialect to `sqlfluff`

### ISSUE THREAD

**Issue by morsapaes** [MaterializeInc/materialize#13195]
### Feature request

[SQLFluff](https://github.com/sqlfluff/sqlfluff) is commonly used to lint dbt projects within CI processes. The PostgreSQL dialect doesn't work out-of-the-box with Materialize due to our subtle syntax deviations (_e.g._ `CREATE SOURCE`). 

We should evaluate how much effort it would be to add (and maintain) a Materialize dialect based on the existing [PostgreSQL one](https://github.com/sqlfluff/sqlfluff/blob/main/src/sqlfluff/dialects/dialect_postgres.py). This was a request in the [community Slack](https://materializecommunity.slack.com/archives/C015KDVS7EV/p1655799196993379) (thanks, Georg!).

**Comment by geoHeil** [comment]
Currently I am using `-- noqa` to skip the failures for parsing this particular line. And try to keep the sources/sinks simple and minimalistic.

Any lint failures need to be fixed manually in the impacted files (as they cannot be parsed). The linting still will generate warnings though.

**Comment by morsapaes** [comment]
This has been released as part of [SQLFluff 1.4.3](https://github.com/sqlfluff/sqlfluff/releases/tag/1.4.3). h/t to @bobbyiliev for contributing the first version of the Materialize dialect!
