### ISSUE TITLE
[Epic] Make Materialize robust for non-enterprise users

### ISSUE THREAD

**Issue by jkosh44** [MaterializeInc/materialize#13204]
Robustness issues, in rough priority order. We would like to fix these issues before M2:

**Must have for M2**

- [x] #13307
- [x] #13371
- [x] #12470 

**Nice to have**
- [x] #12760
- [x] #13650
- [x] #12355
- [x] #13205
- [x] #13007
- [x] #13303

Additional work items to consider have been moved to https://github.com/MaterializeInc/materialize/issues/15068

**Comment by benesch** [comment]
Adding #13650 to the list too.

**Comment by jkosh44** [comment]
Adding #11435 to the list.
