### ISSUE TITLE
Storage client in Compute should handle initial data distribution

### ISSUE THREAD

**Issue by frankmcsherry** [MaterializeInc/materialize#13224]
The storage layer presents to compute a timely stream on each worker, as a result of arguments identifying a collection. At the moment, all of the records are produced at one worker, rather than distributed across workers. This is a natural state for single-shard collections, but compute will need them distributed across workers. In discussion with @petrosagg it seemed that the storage client could own this responsibility, as it is positioned to understand whether the data are already distributed, rather than have the compute layer introduce a defensive (and potentially redundant) shuffle.

**Comment by aljoscha** [comment]
This has been resolved by https://github.com/MaterializeInc/materialize/pull/14177. Please re-open if you disagree!
