### ISSUE TITLE
storage: increase persist batch_size in `persist_sink`

### ISSUE THREAD

**Issue by guswynn** [MaterializeInc/materialize#13231]
See https://github.com/MaterializeInc/materialize/issues/13116

Currently, `persist_sink` uses `persist`'s `BatchBuilder` in a naive way: one batch per

Instead, we should do something like this:

- Hold onto a single batch and add all data to it, keep track of its upper
- When we receive a frontier change, create a new batch. if the frontier is high enough, close the original batch, otherwise, hold onto it, and continue to add data to it below its upper
- Close the original batch when the frontier makes it past its upper

**Comment by benesch** [comment]
I'm going to optimistically assume that this was fixed by #17589. If it wasn't, feel free to re-open.
