### ISSUE TITLE
Robust communication between Coordinator and STORAGE/COMPUTE

### ISSUE THREAD

**Issue by jkosh44** [MaterializeInc/materialize#13291]
### Feature request

Currently all communication from the Coordinator to STORAGE and COMPUTE is called with `unwrap()`. This means that if STORAGE or COMPUTE is not available, then the Coordinator will crash. Additionally, the Coordinator will enter a crash loop until they become responsive since communication to STORAGE and COMPUTE is required during the startup process.

While this is technically correct, it is not a good user experience. One potential solution is to return an error to the user and roll back the current operation. Another might be to sit and wait for STORAGE/COMPUTE to become available.

Part of #13204

**Comment by ggnall** [comment]
Dupe of https://github.com/MaterializeInc/materialize/issues/13306.
