### ISSUE TITLE
Ensure `DEBEZIUM UPSERT` does deduplication

### ISSUE THREAD

**Issue by guswynn** [MaterializeInc/materialize#13309]
Currently, its unclear whether or not the `DEBEZIUM UPSERT` envelope does debezium deduplication, when it probably needs to.

**Comment by benesch** [comment]
What goes wrong if we don't do Debezium deduplication? Is it that we'll emit some state changes that didn't actually happen as we read through a swath of duplicate entries? Is it right that if we don't do deduplication, we still end up with eventual consistency?

**Comment by petrosagg** [comment]
That's right, the problem is phantom states and it's correct that we have
eventual consistency if we don't do any dedup

**Comment by benesch** [comment]
I'm wondering if the current behavior might be just fine. The `ENVELOPE UPSERT` state is always going to present you with states that are not atomic wrt upstream transactions... telling you about duplicates twice seems no worse than that. I wrote up some more structured thoughts here: https://github.com/MaterializeInc/materialize/issues/11772#issuecomment-1169483963

**Comment by brennanvincent** [comment]
I agree with Nikhil that this is unnecessary, as long as we are messaging eventual consistency (which is already the case without the transaction topic)

**Comment by benesch** [comment]
Great, let's call this one done then!
