### ISSUE TITLE
coord: Handle peek responses that can't fit into memory

### ISSUE THREAD

**Issue by jkosh44** [MaterializeInc/materialize#13307]
### Feature request

All peek response are sent back to the Coordinator and returned to the client from the main Coordinator’s thread. This can end up eating a lot of the Coordinator’s memory and for large queries will crash the Coordinator due to OOM.

In the short term we should fix this by either truncating results that are too large or erroring out the query instead of crashing the Coordinator.

In the long term we probably want a solution that accommodates large results. One potential solution is some form of pagination, where results are sent back to the Coordinator in batches. Another idea is to not funnel peek responses through the Coordinator. When the Coordinator receives a peek response all it does is clean up some state and immediately forward the results to the client. There’s no reason that the Coordinator actually needs the results in memory. It might be beneficial if we found a way to forward the results directly from COMPUTE to the client or funnel the results through some other type of node.

Part of #13204

**Comment by frankmcsherry** [comment]
Yes!

**Comment by JLDLaughlin** [comment]
@frankmcsherry are you still looking at this?
