### ISSUE TITLE
Replace `unwrap()` with `expect()` in the Coordinator

### ISSUE THREAD

**Issue by jkosh44** [MaterializeInc/materialize#13306]
In `coord.rs` there are 79 calls to `unwrap()`. I think we should prefer `expect()` with a clear explanation of why it will never fail or why failure should cause a panic. The vast majority of these are calls to STORAGE/COMPUTE. Refactoring the `unwrap`s/`expect`s to helper methods would help reduce the total number and de-duplicate explanation strings in `expect`.

**Comment by JLDLaughlin** [comment]
@jkosh44 did you already do this?

**Comment by jkosh44** [comment]
No.

**Comment by jkosh44** [comment]
> @jkosh44 did you already do this?

No.
