### ISSUE TITLE
[Epic] Add Support for `ENVELOPE UPSERT` in Platform

### ISSUE THREAD

**Issue by nmeagan11** [MaterializeInc/materialize#13312]
### Initiative and Theme

Materialize is Friendly; Materialize works with your existing pipelines

### Problem

Subset of https://github.com/MaterializeInc/materialize/issues/13044 and related to https://github.com/MaterializeInc/materialize/issues/13121#issuecomment-1165140138. This is our second highest priority envelope to support in Platform, behind `ENVELOPE DEBEZIUM`.

### Success Criteria

Users can successfully execute a `CREATE SOURCE ... FROM KAFKA ... ENVELOPE UPSERT` statement.

### QA Sign-off

- [x] Make sure `ENVELOPE UPSERT` is present in all relevant tests and testing frameworks.

### Time Horizon

Medium

### Blockers

None

**Comment by brennanvincent** [comment]
The code for this has now landed, with the caveat that errors are un-retractable until https://github.com/MaterializeInc/materialize/issues/14084 lands.

Leaving the issue open pending QA signoff as the code is still only very lightly tested

**Comment by philip-stoev** [comment]
`ENVELOPE UPSERT` is now present in both Zippy and Platform Checks, so this is good to go.
