### ISSUE TITLE
QA: allow default storaged hostname to be specified via a environmentd command-line and env variable

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#13363]
### What version of Materialize are you using?

Platform

### How did you install Materialize?

Docker image

### What is the issue?

A command-line option is needed to environmentd to specify the default storaged to be used for all subsequent sources and sinks.

This is needed for testing in the Antithesis environment where a separate storaged container will be running and yet the existing, unmodified testdrive files will be used.

**Comment by philip-stoev** [comment]
Actually one storaged can not serve two sources at the same time -- environmentd will panic :-(

**Comment by benesch** [comment]
Heads up that I'm separately trying to remove CLI flags that are just for our internal use, to enforce a cloud-first discipline. See #13428 for example. This would make for a great `default_source_remote_addr` parameter if we get global configuration parameters: https://www.notion.so/materialize/Server-configuration-parameters-c9aa8050a2884f67a30b4a34aae2d1bd

**Comment by philip-stoev** [comment]
This is obsolete as Antithesis integration is no longer on the table.
