### ISSUE TITLE
`environmentd` can hang and oom when inserting into a table

### ISSUE THREAD

**Issue by antiguru** [MaterializeInc/materialize#13371]
`environmentd` executes `INSERT INTO .. SELECT` by
* Instructing computed to render a dataflow
* Peeking the result,
* Inserting the result into storage.

The problem here is that `environmentd`
* is blocked while the peek is outstanding and cannot process more requests, and
* needs to pass the result data as a single allocation back to the coordinator and from there to storage.

Ideally, compute writes the result directly back to storage, at a configured location and only provides a confirmation to the coordinator once the write has concluded.

The following example can trigger the OOM behavior when `environmentd` is provisioned with 512MiB RAM:

```
> CREATE TABLE gbs (x int, y text);
> INSERT INTO gbs SELECT *, '0123456789012345678901234567890123456789012345678901234567' FROM generate_series(27*2097152, 28*2097152-1);
SSL SYSCALL error: EOF detected
The connection to the server was lost. Attempting reset: Failed.
Time: 10683.754 ms (00:10.684)
```

**Comment by jkosh44** [comment]
There was some brief discussion about this as a part of this PR: https://github.com/MaterializeInc/materialize/pull/13373 (Though the discussion turned out was unrelated to the PR feature).

Just wanted to add the even if `environmentd` doesn't OOM, it still can hang for a very long time as it performs the insert.

**Comment by jkosh44** [comment]
> is blocked while the peek is outstanding and cannot process more requests, and

This is only half true. While the peek is outstanding `environmentd` can process any request that doesn't include a write. So only `UPDATE`, `DELETE`, and `INSERT` are blocked.

However, While the write is being processed, then `environmentd` is blocked and cannot process any requests.

**Comment by frankmcsherry** [comment]
This issue could plausibly be broken apart in the "system-wide write lock" (https://github.com/MaterializeInc/materialize/issues/13304) and the "could cause it to crash" (https://github.com/MaterializeInc/materialize/issues/13307) issues, which we are tracking. I suspect if those are resolved, some/all of the concerns here are .. idk reduced?

**Comment by jkosh44** [comment]
> This issue could plausibly be broken apart in the "system-wide write lock" ...(https://github.com/MaterializeInc/materialize/issues/13304)
It's actually slightly worse than that. When the write lock is acquired, we can still do a lot like execute `SELECT`s and accept new connections. However the insertion happens in `self.dataflow_client.storage_mut().append(appends).await` which is on the main Coord thread. So while that function is running, which can take a long time, the Coord cannot do anything else.

**Comment by jkosh44** [comment]
It looks like there has been some work to resolve the hanging issue. That is to just time the statement out. The provided query now looks like this
```
materialize=> CREATE TABLE gbs (x int, y text);
CREATE TABLE
Time: 144.421 ms
materialize=> INSERT INTO gbs SELECT *, '0123456789012345678901234567890123456789012345678901234567' FROM generate_series(27*2097152, 28*2097152-1);
ERROR:  canceling statement due to statement timeout
Time: 10148.995 ms (00:10.149)
```

This doesn't solve the OOM issue if we're ever able to generate enough data in less than the timeout.
