### ISSUE TITLE
storage: heartbeat source connections

### ISSUE THREAD

**Issue by sploiselle** [MaterializeInc/materialize#13453]
### Feature request

tl;dr STORAGE should develop a policy for handling failed connections in such a way that e.g. we can bail on creating the connection if it fails immediately.

From @benesch in #13440 

> Could you split [coord: attempt to use CONNECTION during sequencing](https://github.com/MaterializeInc/materialize/pull/13440/commits/8429b7112cbac02709f3e313284a5d3cfa183a42) out into its own PR? Sorry I didn't see @ruf-io's comment sooner! There's a larger design discussion to be had about whether we want connections and sources to eagerly fail or lazily fail. IMO the eager fail behavior for CREATE SOURCE has caused us to skimp on surfacing steady-state errors (you've been running a source for a few days and your Kafka broker suddenly goes away, for example). I think we should build the steady state error detection first, since it's the general purpose detection, and then figure out how to reuse that logic for eager error detection during CREATE CONNECTION or CREATE SOURCE. I'd also like us to structure the code so that the logic for error detection lives in storage, and is called in the adapter, rather than inline in the adapter or sql crates.

**Comment by benesch** [comment]
Folding this into #15082. I wrote up a big long [braindump here](https://www.notion.so/materialize/Connection-and-source-validation-477045065ef1481d90d25e06dbeca4b6#4b8ba2ccde974cb2807d93f6685bee49), which is also linked in #15082. The tl;dr is that we might not want to heartbeat connections if the source/sink runtime status collections turn out to be sufficient.
