### ISSUE TITLE
Table frontiers don't advance after environmentd restart

### ISSUE THREAD

**Issue by teskje** [MaterializeInc/materialize#13454]
### What version of Materialize are you using?

v0.26.1-dev (dd6b23bbd)

### How did you install Materialize?

Built from source

### What is the issue?

After a restart of `environmentd`, tables that were created before the restart don't get their frontiers advanced anymore. Specifically:
* The persist shard's `since` is not advanced (its `upper` is!)
* The storage controller's record of the `since` frontier is not advanced
* The storage controller's record of the `upper` frontier is always 0

It looks like the following happens:
1. During bootstrap, adapter calls the storage controller's `create_collection` for a table.
2. `create_collections` inspects the collection's persist shard (which may or may not have existed before) to get the current `since` (but not the `upper`).
3. `create_collections` instantiates a new `CollectionState` for the collection, initialized with the above `since`, and an `upper` of 0.

The assumption is that the first append to the table should retract the 0 `upper` and insert the correct one. However, this doesn't happen, because during `append`, the change batch for `upper` is generated based on the persist shard's previous `upper`, which is different from 0 if the shard existed before. So instead of retracting 0, the previous `upper` is retracted and the storage controller continues to believe that the collection's `upper` is 0. Because the `upper` doesn't advance, the storage controller also doesn't allow `since` to advance.

**Comment by frankmcsherry** [comment]
Should be fixed by https://github.com/MaterializeInc/materialize/pull/13784
