### ISSUE TITLE
regression: Postgres snapshot taking 2.5x longer after the "dont buffer the entire pg snapshot" PR

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#13450]
### What version of Materialize are you using?

208cd71152fab1313b0c08cab155a7ae17eba2be

### How did you install Materialize?

Docker image

### What is the issue?

The performance of Pg snapshots has fallen 2.5x after this commit:

```
208cd71152fab1313b0c08cab155a7ae17eba2be is the first bad commit
commit 208cd71152fab1313b0c08cab155a7ae17eba2be
Author: Gus Wynn <gus@materialize.com>
Date:   Thu Jun 23 14:45:28 2022 -0700

    storage: dont buffer the entire pg snapshot

 src/storage/src/source/postgres.rs | 146 ++++++++++++++++++++++---------------
 1 file changed, 86 insertions(+), 60 deletions(-)
```

This means that snapshotting 1M 2-integer rows now takes 20 seconds, or 50K rows/second . This will make it very difficult for Mz to be used for POCs on anything but the smallest datasets.

I am unable to observe any obvous CPU hogs with perf and top. So it seems to me that the communication overhead between the containers may have increased substantially.

To reproduce:

```
bin/mzcompose --find feature-benchmark down -v ;
bin/mzcompose --find feature-benchmark run default --scenario=PgCdcInitialLoad --max-measurements=2 --this-tag=unstable-208cd71152fab1313b0c08cab155a7ae17eba2be --other-tag=unstable-3c7d5287387507068ad0b77118aae6045d5ada2e
```

which will result in:

```
+++ Benchmark Report for cycle 3:
NAME                      |    THIS     |    OTHER    |  Regression?  | 'THIS' is:
----------------------------------------------------------------------------------------------------
PgCdcInitialLoad          |      18.289 |       7.928 |    !!YES!!    | 2.3 TIMES slower
```

@guswynn @petrosagg

**Comment by guswynn** [comment]
The offending pr bounded our memory usage during snapshotting. This will definitely have some effect, but 2.5x is definitely too big. The current pg source implementation is non-ideal: it spawns a task, and uses a _bounded_ channel to communicate messages (1 per row in the case of a snapshot) back to the `SourceReader`. It almost certainly `activate`s the timely worker running the source too often, likely leading to churn.

In general, it is hard to reason about the performance and execution of this split tokio-task/timely-worker architecture. I think it would be worthwhile to switch the source to not use a task, and instead implement it entirely as a `SourceReader::next` api. This is opposed to doing some sort of ad-hoc buffering in the snapshot before sending in the channel, and should take advantage of whatever optimizations timely is already doing. Additionally, it should avoid spurious wakeups, activating the timely worker exactly when the underlying postgres stream/snapshot has new data. (thanks to @petrosagg's `async_operator` operator)

The implementation of this likely requires using `async_stream!` to build a snapshot stream and a replication stream, and managing which is active in `SourceReader::next`

**Comment by benesch** [comment]
Thanks for the writeup, Gus! Would we expect excessive activations to present like this? I would expect that to result in 100% CPU usage. If we’re not seeing that… I’m inclined to think we’re synchronously waiting on an S3 upload, or something like that.

**Comment by aljoscha** [comment]
I did a native patch that doesn't activate that often a few days back. It didn't move the needle on the benchmark.

```
From 2f2a0ee4e176b542331fb4e163731ebd9b8d0d59 Mon Sep 17 00:00:00 2001
From: Aljoscha Krettek <aljoscha.krettek@gmail.com>
Date: Tue, 5 Jul 2022 15:05:05 +0200
Subject: [PATCH] storage: don't activate timely on every received postgres row

---
 src/storage/src/source/postgres.rs | 47 +++++++++++++++++++++---------
 1 file changed, 34 insertions(+), 13 deletions(-)

diff --git a/src/storage/src/source/postgres.rs b/src/storage/src/source/postgres.rs
index bbc6f01ae..5c197cf73 100644
--- a/src/storage/src/source/postgres.rs
+++ b/src/storage/src/source/postgres.rs
@@ -399,22 +399,43 @@ impl RowSender {
     }
 
     async fn send_row(&self, row: Row, lsn: PgLsn, diff: i64, end: bool) {
-        // a closed receiver means the source has been shutdown
-        // (dropped or the process is dying), so just continue on
-        // without activation
-        if let Ok(_) = self
-            .sender
-            .send(InternalMessage::Value {
-                value: row,
+        // TODO: Make this less yanky! Also, try and not clone!
+        loop {
+            match self.sender.try_send(InternalMessage::Value {
+                value: row.clone(),
                 lsn,
                 diff,
                 end,
-            })
-            .await
-        {
-            self.activator
-                .activate()
-                .expect("postgres reader activation failed");
+            }) {
+                Ok(yes) => {
+                    // All's well!
+                    return;
+                }
+                Err(send_error) => {
+                    match send_error {
+                        tokio::sync::mpsc::error::TrySendError::Full(_) => {
+                            // Try and take some pressure off the send queue by
+                            // activating the receiving end.
+                            // TODO: As it is, we only activate when the queue i
+                            // full. This would add more latency because we
+                            // don't immediately activate when some messages are
+                            // available.
+                            self.activator
+                                .activate()
+                                .expect("postgres reader activation failed");
+                            // Then retry...
+                            tokio::time::sleep(Duration::from_millis(5)).await;
+                        }
+                        tokio::sync::mpsc::error::TrySendError::Closed(_) => {
+                            // a closed receiver means the source has been shutdown
+                            // (dropped or the process is dying), so just continue on
+                            // without activation
+                            break;
+                        }
+                    }
+                    // todo
+                }
+            }
         }
     }
 }
-- 
2.37.0
```

**Comment by philip-stoev** [comment]
I am not seeing 100% cpu usage form a single process. Instead, the commulative cpu usage from all the processes is 50~100%. So I think stuff is bouncing between the processes.

**Comment by guswynn** [comment]
@danhhz you'll have to add a tracing span that covers the entire `persist_sink` (in each worker), and also one covers the snapshot function in the postgres source; associating these will be quite annoying I think

**Comment by guswynn** [comment]
@philip-stoev did we reduce the size of the pg-cdc-resumption tests? anecdotally, I feel these are running faster now, so if we didnt, it may be worth re-running this to see if the regression is still there

**Comment by guswynn** [comment]
@philip-stoev can you re-test this regression? I have a hunch this is actually no longer a regression, from various persist improvements

**Comment by philip-stoev** [comment]
Due to repeated changes to the CREATE SOURCE syntax , it is not possible to re-run a comparison test spanning commits six months apart. The window of opportunity to act on this regression has unfortunately now closed. I am closing the ticket as not reproducible.

**Comment by benesch** [comment]
Ah, ok, fair enough. I suspect the performance numbers today are not embarrassing, though!

**Comment by guswynn** [comment]
Yeah we have merged changes to the pipeline that should make the perf reasonable (in practice it seems customers are happy)
