### ISSUE TITLE
storage: remove legacy syntax

### ISSUE THREAD

**Issue by benesch** [MaterializeInc/materialize#13469]
There are a few TODOs scattered throughout the storage codebase about legacy code that exists only for backwards compatibility. See:

* [x] #13263
* [x] https://github.com/MaterializeInc/materialize/pull/13463
* [x] https://github.com/MaterializeInc/materialize/pull/13464
* [x] https://github.com/MaterializeInc/materialize/pull/13465

Removing these now is relatively easy, but removing them in a few weeks when we're again making backwards compatibility promises will be much harder.

There are more TODOs around. There are also likely a few things that can be/ought to be removed but _don't_ have TODOs. We should take a pass through the codebase and audit what could be removed, and then decide what we want to prioritize removing.

cc @petrosagg @aljoscha @nmeagan11

**Comment by nmeagan11** [comment]
@benesch, what is the user impact of #13465?

**Comment by benesch** [comment]
> @benesch, what is the user impact of #13465?

The `mz_offset` column that's included by default in Kafka sources will no longer be included by default. Users will have the option to request its inclusion via the already-existing `INCLUDE OFFSET` option, which also has the ability to rename the column (via `INCLUDE OFFSET AS`).

**Comment by benesch** [comment]
I went to update the docs for `mz_offset` but it is not documented anywhere. So, I guess we're good!
