### ISSUE TITLE
environment: Leader Election/Failover

### ISSUE THREAD

**Issue by jkosh44** [MaterializeInc/materialize#13461]
### Feature request

In the platform world, it's possible for multiple `environmentd` processes to exist at the same time. Since `environmentd` holds the ADAPTER layer, which is supposed to act as the leader/coordinator of the entire cluster, we need some mechanism that ensures that we still produce correct and consistent results in this scenario.

Part of #11631

**Comment by jkosh44** [comment]
Probably closely related to #13377

**Comment by jkosh44** [comment]
I think that once #13377 merges this issue will be complete. This is my rationale.

All commands sent to STORAGE/COMPUTE will contain the Coord's epoch number. If the receiving STORAGE/COMPUTE node has seen a higher epoch number previously, then the command is rejected.

When a new Coord boots up, it does the following:
1. Update the epoch number and persisted timestamp in Stash, this will fence out all older Coords from updating the catalog and getting a new timestamp.
2. During boostrapping a command is sent to all STORAGE/COMPUTE nodes when all CREATE X commands are re-run. This will fence out all older Coords from sending a command to all existing STORAGE/COMPUTE nodes.
3. At the end of bootstrapping all tables are advanced to the current global timestamp. This will fence out all older Coords from inserting into persist.
4. The new Coord is ready to start accepting client connections 

So by the time a new Coord is ready to actually start executing queries, all previous Coords are completely fenced from the stash, all COMPUTE/STORAGE nodes, and persist.

While the new Coord is fencing out all older Coords, the older Coord's operations may or may not succeed. I don't believe this is an issue. The older Coord can just abort any operation that doesn't succeed.

**Comment by benesch** [comment]
> 2. During boostrapping a command is sent to all STORAGE/COMPUTE nodes when all CREATE X commands are re-run. This will fence out all older Coords from sending a command to all existing STORAGE/COMPUTE nodes.

What if there is a network partition and the old coord can talk to one of the COMPUTE nodes but the new coord cannot? It doesn't seem in general possible for a coord to be sure that it has fenced off all possible STORAGE and COMPUTE nodes from writing to persist. Not sure if that's important or not.

**Comment by jkosh44** [comment]
If that is not sufficient then I have two potential designs:

1. Frank's proposal here: https://materializeinc.slack.com/archives/CMHDK0DK8/p1657041098185119
2. Whenever a Coordinator reserves a range of timestamps, it specifies a constant interval for that range. After a new Coordinator reserves it's first range of timestamps, it could sleep for that range plus some error bound. That way it would be sure that all previous Coordinator's would have run out of timestamps, tried to get more timestamps, and failed. This is a bit aggressive and slows down startup by a lot. We could have some special logic that if the Coord knows it's the first ever Coord, because the stash was previously empty, then it doesn't have to wait. Still this is probably not a great approach. I just wanted to mention it.

**Comment by pH14** [comment]
> If the new Coord can't talk to one of the COMPUTE nodes, then what would happen when the new Coord tries to create that node during bootstrapping or tries to create an index on that node during bootstrapping? Will Kubernetes just create a brand new duplicate node?

Coord does not create the COMPUTE nodes (or pods in Kube parlance) directly, it will tell Kube "please make `n` COMPUTE pods that look like this template". If that template, implemented as a Kube StatefulSet, already exists and its definition is unchanged, the existing COMPUTE pods will not change and no new pods will be created. Only if the template changes will Kube roll the COMPUTE pods to the new definition.

I think it'd be very possible to have a network partition scenario in which a second Coord spins up, can talk to Kube and confirm the COMPUTE StatefulSet exists and needs no changes, but cannot talk to some or all of the existing COMPUTE pods.

**Comment by jkosh44** [comment]
Some more of my thoughts on this:

- `CREATE COMPUTE INSTANCE...` and `CREATE COMPUTE INSTANCE REPLICA ...` may succeed without ever actually sending a message to a compute node/pod. However, I think that `CREATE TABLE`, `CREATE SOURCE`, `CREATE INDEX`, and `CREATE RECORDED VIEW` will either send a message to a COMPUTE/STORAGE node or fail. So once bootstrapping is complete then all non-empty COMPUTE/STORAGE nodes should be fenced off from older Coords. So old Coords will only be able to send messages to empty nodes. There's no meaningful commands that can be sent to an empty node except for DDL, which is fenced off by the catalog. So I believe that after bootstrapping older Coords will be fenced off from performing any commands.
- Due to (3) above, I think that all older Coords will be fenced out of doing any writes (`INSERT`, `UPDATE`, `DELETE`, etc).
- Advancing a table to timestamp `ts` prevents anyone else from writing to it at a timestamp less than `ts`. It would be useful to have something similar for reading. Maybe a new compaction policy that forces compaction up to `ts`, or rejects all reads less than `ts`. If a Coord was able to force compaction of all objects up to it's allocated timestamp, then it would effectively fence out all previous Coords from reading any object.

**Comment by benesch** [comment]
> * However, I think that `CREATE TABLE`, `CREATE SOURCE`, `CREATE INDEX`, and `CREATE RECORDED VIEW` will either send a message to a COMPUTE/STORAGE node or fail.

Unfortunately not! Communication with storage hosts and compute replicas is handled by a task per storage host/compute replica and errors are retried indefinitely. So the completion of any of these DDL commands does not mean that the controller has made contact with any of the underlying `storaged`/`computed` processes.

**Comment by jkosh44** [comment]
Another note that @frankmcsherry reminded me of, no matter how much fencing we do, queries that don't involve other nodes will still be an issue. For example `SELECT mz_logical_timestamp()` or reading from a view that has a definition of `SELECT 1` on an old leader but `SELECT 2` on a new leader.
