### ISSUE TITLE
storage: `persist` does not retry `postgres: connection closed` errors

### ISSUE THREAD

**Issue by benesch** [MaterializeInc/materialize#13468]
While working on storage reconciliation, I observed a storage pod silently stop ingesting data. The sequence of steps was this:

 1. Start `environmentd`.
 2. Start `storaged`.
 3. Create a Kafka source. Observe data being ingested.
 4. Turn off `environmentd` and the PostgreSQL server hosting the `persist` consensus implementation.
 5. Start `environmentd`.
 6. Read from the Kafka source. Observe that data is no longer being ingested.

The only error in the log message from persist. It was along these lines (from memory):

```
persist: postgres error: connection closed
```

I suspect that either persist or storage is not properly retrying on a "connection closed" error from PostgreSQL. Or, possibly, it _is_ retrying, and there was another bug in storage reconciliation. I'll file this as something to look into during the storage reconciliation epic.

cc @danhhz @aljoscha, who I described this bug to in the storage hangout today.

**Comment by philip-stoev** [comment]
Related issue on handling postgres errors https://github.com/MaterializeInc/materialize/issues/13379

**Comment by benesch** [comment]
In discussion with @danhhz, it turns out that this is actually expected until #12482 (adding a connection pool) lands! 

Once that goes in, @philip-stoev, we should get a test that restarting PostgreSQL is handled correctly by Materialize.

**Comment by benesch** [comment]
Calling this one done. We have #13872 to track the testing efforts now.
