### ISSUE TITLE
Implement `AS TEXT` output format

### ISSUE THREAD

**Issue by aalexandrov** [MaterializeInc/materialize#13472]
### Tasks

- Prerequisites
	- [x] #13581
	- [x] #13734
- Implement `AS TEXT` output format for `HIR`.
 	- [x] #13707
	- [x] #13733
	- [ ] #13732
	- [x] #13752
- Implement `AS TEXT` output format for `MIR`.
    - [x] #14033
- Implement `AS TEXT` output format for `LIR`.
    - [x] https://github.com/MaterializeInc/materialize/pull/14303
    - [ ] https://github.com/MaterializeInc/materialize/pull/14535

### Related
Currently discussed improvements can be found [in this notion doc](https://www.notion.so/materialize/EXPLAIN-usability-considerations-bce37d82abaa484fbb489cf72c1d37f3#13e11d55cae445b2b4105064330be052).

**Comment by wangandi** [comment]
A thing that I realized: If we are going to replace the TEXT format, we should ensure that we have documentation of the old text format so that people can interpret old github issues/design documents. Unless we're planning on updating every old github issue featuring the old text explain format...

**Comment by aalexandrov** [comment]
Related PR that makes `JSON` a more flexible output format for tests: #13238.
