### ISSUE TITLE
Remove extraneous internal identifiers.

### ISSUE THREAD

**Issue by wangandi** [MaterializeInc/materialize#13484]
Our explanations currently include the internal identifiers for objects, which should be removed because they are not useful to a cloud user who cannot add `println`s to their binary to trace the internal identifier through the system.

Example explanation. `u1` is the internal identifier.
```
materialize=> explain select f2 + f3 from (select f2, max(f1) as f3 from t1 group by f2);
           Optimized Plan           
------------------------------------
 Source materialize.public.t1 (u1):+
 | Project (#0, #1)                +
                                   +
 Query:                            +
 %0 =                              +
 | Get materialize.public.t1 (u1)
 | Reduce group=(#1)
 | | agg max(#0)
 | Map (#0 + #1)
 | Project (#2)
```

Incidentally, this removal will make it so that integration test results no longer change if the internal identifier changes.

If there was a serious need to know the internal identifier for an object, the user can look it up in introspection views like `mz_relations` and `mz_catalog_names`.

Object names in an explanation are added by an `ExprHumanizer` that looks up the name using the internal identifier. If the `ExprHumanizer` cannot find the name (this can happen in some unit tests), the explanation should continue to the internal identifier.

**Comment by aalexandrov** [comment]
Solved in the `EXPLAIN ... AS TEXT` for HIR plans, will be picked up for MIR and LIR when we carry it over.
