### ISSUE TITLE
sql: `SSL KEY` in `CONNECTION` should be `SSL KEY PEM`

### ISSUE THREAD

**Issue by sploiselle** [MaterializeInc/materialize#13500]
### Feature request

We could make the fact that we expect the key in PEM format.

h/t @aalexandrov

**Comment by chaas** [comment]
Updating this ticket to reflect https://github.com/MaterializeInc/materialize/pull/14045#issuecomment-1205606981.
New AI: change docs to specify PEM format, but leave syntax the same.

**Comment by chaas** [comment]
Docs change is merged
