### ISSUE TITLE
[Epic] Bounded input reliance

### ISSUE THREAD

**Issue by benesch** [MaterializeInc/materialize#13534]
## Background

As laid out in the [source ingestion recipe](https://github.com/MaterializeInc/materialize/pull/12109/files), sources in Materialize need to provide *bounded input reliance.*

Bounded input reliance means that when the source restarts, it does not re-read the data from the beginning of the source; instead, it begins re-reading data from "near" where it left off. The source must periodically advance this restart point as it ingests data, and communicate this restart point to the upstream source.

This work will provide us with [correctness property #4](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/platform/ux.md#correctness):

> Materialize provides durability guarantees with respect to acknowledgements of upstream sources. This means that any data from an upstream source that Materialize sends an acknowledgement for (e.g., the commit of an offset by a Kafka source, the acknowledgement of an LSN by a PostgresSQL source, etcetera), will be saved in durable storage.

## Design

Currently, the storage controller computes the restart point by setting the `resume_upper` field when it issues the initial `CreateSources` command:

https://github.com/MaterializeInc/materialize/blob/192e8a1d73ce8ac157ebb4a51926d4c9ea377bfa/src/storage/src/client/controller.rs#L513-L531

This logic is suboptimal in the face of storage reconciliation. When a `storaged` process crashes but `environmentd` does not, the `storaged` process will be rehydrated with the `resume_upper` from when `environmentd` was last restarted, which may be hours or days out of date.

This logic is also incorrect for PostgreSQL sources. Based on my read of the PostgreSQL source, we commit the latest LSN we've seen...

https://github.com/MaterializeInc/materialize/blob/192e8a1d73ce8ac157ebb4a51926d4c9ea377bfa/src/storage/src/source/postgres.rs#L634-L658

...before we have guaranteed that we have ingested that data.

In conversation with @petrosagg last week, we came up with the following sketch of a design to fix this:

  * We introduce a new `StorageCommand::RestartUppers` command.
  * The storage controller periodically recomputes the restart point (using the same logic it currently uses) and issues a new `StorageCommand::RestartUpper`s command.
  * The `storaged` process waits until it receives a `RestartUppers` command to issue a PostgreSQL status update or a Kafka commit.
  * The storage rehydration logic will compact `CreateSources` and `RestartUppers` commands together, producing a single `CreateSources` command with the restart upper set to the latest known restart upper. This is analogous to how the compute rehydration logic compacts the `as_of` field with `CreateDataflows` and `AllowCompaction` commands.

**Comment by benesch** [comment]
From Slack conversation with @petrosagg:

> Noting here in case the implementation is simpler, we could commit upstream offsets based on our AllowCompaction commands, which is not as tight a bound as directly computing restart_upper but since we don't allow compaction to trail too far back it might be a good approximation
>
> And in the command stream a IngestSource command followed by an AllowCompaction command would compact into a single IngestSource who's restart_upper is the new since

**Comment by benesch** [comment]
From Slack, the `RestartUppers` command is also what will allow compaction on reclocking collection (which is currently uncompactable): https://materializeinc.slack.com/archives/C01CFKM1QRF/p1657736032844889?thread_ts=1657735627.384569&cid=C01CFKM1QRF

**Comment by nmeagan11** [comment]
From @aljoscha:

> Afaik, we still need to put in the compaction logic for the remap shard. It shouldn't be much work, but we also shouldn't forget it.

**Comment by benesch** [comment]
> From @aljoscha:
> 
> > Afaik, we still need to put in the compaction logic for the remap shard. It shouldn't be much work, but we also shouldn't forget it.

Yep, that's what's described in my previous comment!

**Comment by benesch** [comment]
So, here's a rough smattering of thoughts:

  * I think I like `AllowResumption`, `AllowUpstreamCommit`, or `AllowUpstreamAcknowledgment` as a name for the command more than `AllowFastForward`.
  * Each upstream source has something equivalent to a replication slot. PostgreSQL literally calls them replication slots. Kafka calls them consumer groups. Each source _replica_ should get its own replication slot with its own name. For now, we don't need to worry about this too much, because we only support a single replica for sources. I think this maybe solves the issue that @petrosagg was worried about in the storage meeting today? If a source replica is unable to restart from the appointed frontier, it can just panic, under the assumption that it raced with another `storaged` process _of the same replica_ due to e.g. a network partition.
  * The storage controller is the natural place to determine the resumption frontier, because that is the natural place to take into account updates from any source replica.
  * The `RehydratingStorageClient` shouldn't recompute the resumption frontier. It should just compact down any `AllowResumption` commands that it sees, so that replay during rehydration uses the latest `AllowResumption` command.
  * We probably want `FrontierUppers` to include upper information for _both_ the remap shard and the data shard. That will allow us to trivially recompute the new resumption frontier on _every_ `StorageResponse::FrontierUppers`. The current `get_resume_upper` method fetches the latest uppers from persist, and is too slow to do in the main coordinator loop on every `StorageResponse::FrontierUppers`. We could alternatively call the current `get_resume_upper` implementation in a separate task for each source, say every minute, but that seems a bit silly.

**Comment by guswynn** [comment]
@benesch thanks for the notes, very helpful!

> We probably want FrontierUppers to include upper information for both the remap shard and the data shard. That will allow us to trivially recompute the new resumption frontier on every StorageResponse::FrontierUppers. The current get_resume_upper method fetches the latest uppers from persist, and is too slow to do in the main coordinator loop on every StorageResponse::FrontierUppers. We could alternatively call the current get_resume_upper implementation in a separate task for each source, say every minute, but that seems a bit silly.

My question is: how do we calculate the _resumption frontier_? Is it just the `Lattice::meet` of the remap and data `FrontierUppers`? Also, is the _resumption frontier_ **always** a safe frontier to compact to the resumption frontier? my guess is "yes"

> The storage controller is the natural place to determine the resumption frontier, because that is the natural place to take into account updates from any source replica.

This is true, but we could technically do this (this meaning compact the remap collection and give feedback to the upstreams) entirely in storaged right? the advantage of doing it in the controller is that we can avoid hitting persist to get the `resume_upper` during rehydration, right?

**Comment by benesch** [comment]
> My question is: how do we calculate the _resumption frontier_? Is it just the `Lattice::meet` of the remap and data `FrontierUppers`? 

Whatever `get_resume_upper` currently does is right!

> Also, is the _resumption frontier_ **always** a safe frontier to compact to the resumption frontier? my guess is "yes"

Yup!

> This is true, but we could technically do this (this meaning compact the remap collection and give feedback to the upstreams) entirely in storaged right? the advantage of doing it in the controller is that we can avoid hitting persist to get the `resume_upper` during rehydration, right?

Yup! I'd say the reason to do it in the controller is largely philosophical. The controller should be in charge of making decisions like "advance the resumption frontier."

**Comment by guswynn** [comment]
> Whatever get_resume_upper currently does is right!

So the idea is:
- For new sources, we use `get_resume_upper` to get the resumption upper, and add that to the 
- We store this `get_resume_upper` in the controller, and update it on `FrontierUppers` using the same logic as `get_resume_uppers` (merging the remap and data upper using `Antichain::insert`). On rehydration we use this upper, instead of talking to persist
  - A philosophically equivalent way is to store the most recent `AllowResumption` command and merge it on rehydration
- When the controller gets a `FrontierUppers`, it updates the `resume_upper`, as described above, and then sends a `AllowResumption` command back
- On `AllowResumption`, storaged calls `RemapOperator::compact` + forwards the upper (converted to source-specific offsets) back to the sources


Does this seem correct?

**Comment by guswynn** [comment]
After collecting feedback on my first pr from @aljoscha, @frankmcsherry, and @benesch, here is an overview of what I think the implementation of this epic entails, followed by some important points about the implementation:

Bounded input reliance is primarily about calculating a _resumption frontier_ for a source, and communicating it back to the source instance.
- A _resumption frontier_ is effectively the `Lattice::meet` of the _uppers_ of the data and reclock collection
  - In practice this is always going to be equal to the data collections upper
- We currently calculate this `resumption_frontier` once, when we start up the storage controller, by reading both uppers from persist, but we want to regularly re-calculate it and communicate it back to sources
- The _resumption frontier_ is in the "time" domain, but the reclock operator can be used to map it back into a source-specific _offset_.
  - This _offset_ can be committed to upstream, for example, committing the pg lsn, or the kafka offset
- The _resumption frontier_ is also a good candidate for a frontier to compact the remap collection to, so we will use it to drive `ReclockOperator::compact` (after the offset is committed to upstream)

The implementation should go as follows
1. Add a `StorageCollectionId` struct: https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/20220411_reclocking_implementation.md#storage-api-changes
  a. This is not strictly required, #2 is possible to implement without this change (see https://github.com/MaterializeInc/materialize/pull/14225), but this reduces some complexity of the `FrontierUppers` response, and also interacts well with future improvements (like access to the reclock collection in sql)
2. Communicate the upper of the reclock collection for a collection back the the storage controller, in the `FrontierUppers` response.
  a. Note that, we could do all this calculation in the storaged instance itself, as we are ultimately just transferring uppers between `StorageState` and the storage controller. The choice to do this is mostly **philosophical**
3. Ingest these uppers into the storage controller. It is so far unclear to me how difficult this, other than just writing the frontiers down. Reconciliation does some subtle tracking of frontiers that may be necessary for reclock uppers as well
4. Periodically calculate the _resumption fronter_ (as described above), and pass it along to the storaged instance.
  a. Mostly like this will be a timer in the core storage controller `select!`-loop that fans out to the managed storage instances with the resumption frontiers
  b. this will require a new `StorageCommand`, perhaps `AllowResumption` or something
  c. on startup, these uppers will have to be read from persist, like they are now.
  d. during rehydrating, the controller will need to merge `AllowResumption` and `IngestSources`
5. Ingest `StorageCommand::AllowResumption into the storaged instance
  a. We have to turn the frontier given to us in the command to an offset, using the `ReclockOperator`, and communicate that offset to the underlying source instance for that collection. This will require an API change to `SourceReader`(and likely some kind of coordination piping through the storage timely operators.
  b. AFTER the source instance confirms the commit of the offset, we can compact the reclock operator to the same frontier. This has some interesting consequences on crashes, but worst case the compaction will happen in the next `AllowResumption` frontier.

**Comment by guswynn** [comment]
closing this as the core behavior is implemented. the only followups are:
- noodling on writing a complex test: #15008 
- documenting that we commit kafka offsets. this requires we think about the wording: #15367
