### ISSUE TITLE
coord+compute: unknown peek handling delay

### ISSUE THREAD

**Issue by mjibson** [MaterializeInc/materialize#13586]
### What version of Materialize are you using?

main

### How did you install Materialize?

Built from source

### What is the issue?

While running a feature benchmark against a local mz, there is very reproducible 3 second peek. The trace doesn't help us to understand what is causing the delay. The bug is not that this takes 3 seconds, it's that we can't see the cause. (But there may also be a bug causing this to take 3 seconds, but we need to know why to figure out if that's the case.)

![ss_006](https://user-images.githubusercontent.com/41181/178390385-859373a4-3a03-4104-9996-a0d7e8112aa0.png)

To repro:

- Start a local jaeger tracing instance: `bin/mzcompose --find opentelemetry up -d`
- This works by running a bunch of stuff in docker that communicates to a locally running mz outside of docker. Replace `YOUR_PUBLIC_IP` below with the external IP address of your machine so the mz instance and testdrive can comminucate.
- Start mz with otel, unsafe mode, and binding to non-localhost (you may also need to add `--postgres blah` after `--reset` for your local postgres server): `bin/environmentd --reset -- --unsafe-mode --opentelemetry-endpoint=http://localhost:4317/ --opentelemetry-filter=debug,mz_adapter=trace --sql-listen-addr YOUR_PUBLIC_IP:6875`
- In another terminal, run feature benchmark at it: `bin/mzcompose --find feature-benchmark --preserve-ports run mzcloud --mzcloud-url "postgres://materialize@YOUR_PUBLIC_IP:6875/materialize" --test-filter kafka --external-addr YOUR_PUBLIC_IP  --max-measurements 1 --scale 4`
- Open up jaeger: http://localhost:16686/
- Set `Service` to `environmentd`, `Operation` to `execute`, and `Min Duration` to `2s`. Hit `Find Traces` until you see `enviromentd: execute` with a duration in the 2 to 10 second range.

**Comment by frankmcsherry** [comment]
From the functions called, specifically `handle_compute_command` being the first "late" method, it would seem that the command is in a queue and either not dequeued or not acted on immediately, owing to other work happening on a/the worker thread. I can't tell if that would be a satisfactory accounting (a span labeled "enqueued").

**Comment by mjibson** [comment]
That would satisfy me yes!

**Comment by antiguru** [comment]
I tried to reproduce the issue, and while doing so noticed that this tests Materialize in debug mode. I cannot observe the issue when running Materialize in release mode. Could this be the culprit?
The following image shows traces with a minimum duration of 128ms. The large section in the middle is Mz in release mode, the small part on the right is Mz in debug mode.
![image](https://user-images.githubusercontent.com/582946/178443221-46df1436-1ada-4843-8ae2-82f8ae23e2bf.png)

**Comment by mjibson** [comment]
For a real life example of this, here's a trace of exactly this problem running on 58c0803dcc52569c29933b73b8ba62f3c388bff3 on our staging cloud platform (and thus in release mode) with a full *2 minute* delay:
![ss_000](https://user-images.githubusercontent.com/41181/179150646-58fb20ed-a55c-4cad-9ead-f15a041c07e8.png)

**Comment by mjibson** [comment]
Oh, other real life problems this exposes: queries like `show objects` get real slow and have large variance:

```
materialize=> show objects;
 name 
------
 s1
(1 row)

Time: 6068.727 ms (00:06.069)
materialize=> show objects;
 name 
------
 s1
(1 row)

Time: 389.193 ms
materialize=> show objects;
 name 
------
 s1
(1 row)

Time: 2004.160 ms (00:02.004)
```

**Comment by antiguru** [comment]
I think this is not relevant anymore due to recent improvements within the Adapter.
