### ISSUE TITLE
Multi-process compute clusters can be out-of-sync on controller restarts

### ISSUE THREAD

**Issue by antiguru** [MaterializeInc/materialize#13603]
While re-working the command reconciliation logic for the coordinator-compute boundary, @frankmcsherry noticed that we have a potential problem of de-synchronizing cluster members. When the connection to a cluster fails while broadcasting a command, it could happen that some receive the command while others don't. Many bad things can follow: partially constructed dataflows, partial peeks and so on.

On restart, the controller does not know which subset of the processes received what instructions, which makes it impossible to provide a correct sequence of commands to bring them in a known-good state.

Related: [Discussion on Slack](https://materializeinc.slack.com/archives/C02PPB50ZHS/p1657694466677869)

## Suggestions to solve this issue
1. On connection, each process advertises its received command history back to the coordinator, from which the coordinator can at least learn if everyone is in sync (and if not, restart the group).
2. The controller just speaks with one process, who broadcasts the commands to other workers using timely's Sequencer dataflow (a built-in broadcast, whose failure results in the mesh failing).
3. The controller uses a more reliable mechanism to deliver the commands, such as recording them in a DB or putting them in Kafka.
4. The command reconciliation logic asserts that `num_workers == 1` on restart. This causes the compute cluster to restart, which leaves it in a clean state, at the cost of dropping maintained resources.

**Comment by frankmcsherry** [comment]
Afaiu, this is "solved" with option (4.). We might want to improve the ability of multi-process replicas to reconcile efficiently, but the issue is no longer that they will be out of sync.

**Comment by lluki** [comment]
I'm working on implementing also option 2)

**Comment by lluki** [comment]
Will probably lead to some merge conflicts with #14379
