### ISSUE TITLE
SELECTing from storage collections slows down over time

### ISSUE THREAD

**Issue by teskje** [MaterializeInc/materialize#13628]
### What version of Materialize are you using?

v0.26.1-dev (043f79b67)

### How did you install Materialize?

Built from source

### What is the issue?

SELECTing from a storage collection becomes significantly slower over time, even when compaction should keep the collection size roughly the same.

To reproduce:

```sql
CREATE SOURCE market_orders_source
    FROM PUBNUB
    SUBSCRIBE KEY 'sub-c-4377ab04-f100-11e3-bffd-02ee2ddab7fe'
    CHANNEL 'pubnub-market-orders';
CREATE RECORDED VIEW rv AS SELECT count(*) FROM market_orders_source;
\timing
SELECT * FROM rv;
SELECT * FROM rv;
...
```

On my local machine, this yields:
```
 count | time
-------|------------
   402 |   64.370 ms
  1080 |  463.546 ms
  1474 |  703.493 ms
  2424 | 1020.057 ms
```

(This is from a debug build. With a release build the times are lower but also increasing.)

Note that as long as compaction is working correctly, the size of the recorded view collection shouldn't increase.

The times of querying `market_orders_source` directly also increase, so this issue doesn't seem to be specific to recorded views. Although in this case the size of the source collection is actually increasing too.

Some additional observations:
* Tracing says that nearly all of the peek time is spent in compute's `handle_peek` function.
* Compute introspection indicates that the peek's `as_of` is not in the future, so we are waiting for the data to become available, not for the clock to advance.
* Creating an index on the recorded view completely removes the performance issue.
* Restarting environmentd also removes the performance issue! Or more specifically: The peek times start low again and increase barely afterwards.

**Comment by teskje** [comment]
This might have the same root cause as https://github.com/MaterializeInc/materialize/issues/13623. The scheduling histogram looks similar at least:
```
 id  |                        name                         | worker | elapsed_ns
-----+-----------------------------------------------------+--------+------------
 167 | Dataflow: 1.3.rv                                    |      0 | 1007934487
 245 | Dataflow: 1.3.rv                                    |      0 |  978991066
 168 | persist_source                                      |      0 |  676236237
```

**Comment by aljoscha** [comment]
@teskje What do you think about this one now? There have been many fixes in the area and I can't easily reproduce because we don't have Pubnub sources anymore ... :sweat_smile: I'd probably close, wdyt?

**Comment by teskje** [comment]
I tested this briefly on staging with a counter source, and while it seems like performance does vary over time, it doesn't strictly get slower anymore (in my test query times seemed to go up a bit and then down again). So it looks like this is indeed fixed :)

**Comment by aljoscha** [comment]
many thanks!
