### ISSUE TITLE
storage,persist: in persist_source, reading doesn't yield and blocks the Timely operator

### ISSUE THREAD

**Issue by antiguru** [MaterializeInc/materialize#13623]
### What version of Materialize are you using?

5c1c09d9247ef59090c63b1b2eac42551476e01e

### How did you install Materialize?

Built from source

### What is the issue?

UPDATE(aljoscha): Original title: `Persist-client snapshot reading doesn't yield and blocks the Timely operator`. I broadened the scope to cover reading in the `persist_source` in general. Some of these problems might have been mitigated by #14177.

We observed that sometimes the Timely operators do not process commands as fluently as they should. This shows up as gaps of nothing happening in tracing, such as reported in #13586.

Digging deeper, the root cause is that reading from a persist source takes a long time, and decodes all data in an uninterruptible action. The scheduling histogram shows this:
```
materialize=> select mdo.id, mdo.name, mdo.worker, mse.elapsed_ns
from mz_scheduling_elapsed as mse,
     mz_dataflow_operators as mdo
where
    mse.id = mdo.id and
    mse.worker = mdo.worker
order by elapsed_ns desc;
  id   |             name              | worker | elapsed_ns
-------+-------------------------------+--------+------------
 25484 | Dataflow: 7.11.s1_primary_idx |      0 | 6740352092
 25500 | Dataflow: 7.11.s1_primary_idx |      0 | 6636931879
 25485 | persist_source                |      0 | 6450979729
```

For tracing, this can be observed in the `fetch_batch::decode` span, as in the following image, where the span `fetch_batch::decode` is not async and actually blocks the caller.
![image](https://user-images.githubusercontent.com/582946/178982952-1ed86122-b34d-4220-96a7-cbac8168c27c.png)

(The times from the screenshot and the SQL result don't match because they're from different runs.)

**Comment by antiguru** [comment]
I tried to wrap the following code in `async`, but it didn't seem to help: https://github.com/MaterializeInc/materialize/blob/1f56f0ee502b34b5d43b0bc8c109956b58233a5f/src/persist-client/src/read.rs#L716-L731

**Comment by aljoscha** [comment]
Couple of findings:
 - I added simple logging to see when the `persist_source` operator is being activated. When the source is idle, no updates will come in from persist except frontier updates. There are some activations in the log that correspond with our listen backoff/retry interval. But there are many more activations in between. I don't know why they are happening.
 - We could put the decoding into a blocking task, that is move it off the main timely thread. Not sure that's a good idea, though.
 - We could periodically yield from decoding, to give other timely operators a chance to run. This seems smarter.
 - Currently, all `persist_source` related business happens on one worker. The work that Sean will be starting will eventually spread that across all timely workers. This should also help.

[0001-WIP-add-polling-logging.patch.txt](https://github.com/MaterializeInc/materialize/files/9112144/0001-WIP-add-polling-logging.patch.txt)
[polling-logs.txt](https://github.com/MaterializeInc/materialize/files/9112160/polling-logs.txt)

**Comment by danhhz** [comment]
I vote for

> We could put the decoding into a blocking task, that is move it off the main timely thread. Not sure that's a good idea, though.

as a temporary band-aid followed later by

> We could periodically yield from decoding, to give other timely operators a chance to run. This seems smarter.

as a better fix. This is also somewhat related to #12734

**Comment by danhhz** [comment]
@antiguru the PR I just merged should fix this issue. assigning back to you in case you want to verify the fix. feel free to go ahead and close it if you don't. fyi, in case you'd like to tune the threshold for when we yield _within_ the decoding of an s3 object (we always yield _between_ each s3 object), it's here https://github.com/MaterializeInc/materialize/blob/1a6a0c27450be50d6195ea543097dab78dc5a4fb/src/compute/src/render/mod.rs#L182-L183
