### ISSUE TITLE
Debezium transaction sources only work with CREATE MATERIALIZED SOURCE

### ISSUE THREAD

**Issue by teskje** [MaterializeInc/materialize#13629]
### What version of Materialize are you using?

v0.26.1-dev (043f79b67)

### How did you install Materialize?

Built from source

### What is the issue?

`CREATE MATERIALIZED SOURCE foo ...` is (supposed to be?) just syntactic sugar for `CREATE SOURCE foo ...; CREATE DEFAULT INDEX ON foo`. So creating a Debezium transaction source with the latter syntax should work.

However, if one adjusts `test/testdrive/kafka-avro-debezium-transaction.td` like this:

```diff
diff --git a/test/testdrive/kafka-avro-debezium-transaction.td b/test/testdrive/kafka-avro-debezium-transaction.td
index 37a93da51..a4e9bc513 100644
--- a/test/testdrive/kafka-avro-debezium-transaction.td
+++ b/test/testdrive/kafka-avro-debezium-transaction.td
@@ -159,11 +159,13 @@ $ set txschema-bad-schema={

 $ kafka-create-topic topic=data-txdata

-> CREATE MATERIALIZED SOURCE data_txdata
+> CREATE SOURCE data_txdata
   FROM KAFKA BROKER '${testdrive.kafka-addr}' TOPIC 'testdrive-data-txdata-${testdrive.seed}'
   FORMAT AVRO USING SCHEMA '${txschema}'
   ENVELOPE NONE

+> CREATE DEFAULT INDEX ON data_txdata
+

 $ kafka-ingest format=avro topic=data-txdata schema=${txschema} timestamp=4
 {"status": "BEGIN", "id": "1", "event_count": null, "data_collections": null}
```

... the test starts failing with:

```
kafka-avro-debezium-transaction.td:204:1: error: deadline has elapsed
     |
 203 | # Note that this should still work even if data2 (which shares the transaction metadata source) isn't able to progress!
 204 | > SELECT a, b FROM data_schema_inline
     | ^
```

The same is also true for other testdrive tests that exercise Debezium transaction sources.

**Comment by teskje** [comment]
There are three tests that are currently failing (and disabled) because of this bug:
* `test/debezium/mysql/40-check-smoke.td`
* `test/debezium/postgres/92-large-transaction.td`
* `test/testdrive/disabled/kafka-avro-debezium-transaction.td`

**Comment by uce** [comment]
It's unlikely that we'll support transaction sources going forward. We can revisit this issue in case we decide that we'll support them.

**Comment by aljoscha** [comment]
we no longer have the concept of non-materialized sources, but also, we have to track adding support for the transaction topic separately
