### ISSUE TITLE
adapter: `migrate` isn't transactional

### ISSUE THREAD

**Issue by mjibson** [MaterializeInc/materialize#13632]
https://github.com/MaterializeInc/materialize/blob/8e54ed5949634a4a0b57283f53c15bb96e74b15c/src/adapter/src/catalog/storage.rs#L63 isn't transactional and should a failure occur mid way through a migration it will have been partially committed. In the cloud land, we must do each migration including the "migration X has been applied" in a single transaction.

**Comment by jkosh44** [comment]
How does this sound as a fix? We update the `migrations` array, to be an array of closures. Each closure takes a `Transaction` object and updates the transaction with some migration. The `migrate` function then does the following:

1. Starts a new transaction.
2. Passes the transaction to all the new closures.
3. Updates the version in the transaction.
4. Commit the transaction.

**Comment by mjibson** [comment]
should work!
