### ISSUE TITLE
Tables are not selectable in cloud

### ISSUE THREAD

**Issue by frankmcsherry** [MaterializeInc/materialize#13649]
### What version of Materialize are you using?

 v0.27.0-alpha.1 (53dd925fa)

### How did you install Materialize?

Materialize Cloud

### What is the issue?

Logging in to cloud and creating a table and trying to select from it stalls. 
```
materialize=> create table tests (x int, y int, test int, user text);
CREATE TABLE
materialize=> explain timestamp for select * from tests;
                   Timestamp                    
------------------------------------------------
      timestamp: 1657902412751                 +
          since:[1657902399068]                +
          upper:[            0]                +
      has table: true                          +
  table read ts: 1657902412751                 +
                                               +
 source materialize.public.tests (u4, storage):+
  read frontier:[1657902399068]                +
 write frontier:[            0]                +
 
(1 row)

materialize=> 
```
What seems to be the case is that the reported write frontier is `0` which implies that data can still be written at `0` and consequently can not be read ever. It isn't clear whether this is ADAPTER failing to talk to the storage controller, or it failing to talk to `persist`, or the information failing to return.

If you `INSERT INTO` the table, this appears to "unstick", but it enters a different problematic-ish state where the target timestamp is several seconds ahead of what is immediately serviceable:
```
materialize=> explain timestamp for select * from flags;
                   Timestamp                    
------------------------------------------------
      timestamp: 1657902902741                 +
          since:[1657902900770]                +
          upper:[1657902900771]                +
      has table: true                          +
  table read ts: 1657902902741                 +
                                               +
 source materialize.public.flags (u1, storage):+
  read frontier:[1657902900770]                +
 write frontier:[1657902900771]                +
 
(1 row)

Time: 210.808 ms
materialize=>
```
This could be any manner of issue; it certainly isn't as obviously wedged as up above.

**Comment by JLDLaughlin** [comment]
Internal conversations about this are happening in #eng-wg-tables.

Looks like we're going to try a few things from @frankmcsherry, @jkosh44, and @danhhz / @petrosagg. The first related PR is out: https://github.com/MaterializeInc/materialize/pull/13708

**Comment by JLDLaughlin** [comment]
closing as per https://materializeinc.slack.com/archives/C03QLQK1Q3A/p1658175100411159!
