### ISSUE TITLE
CREATE SOURCE with invalid connection parameters blocks forever

### ISSUE THREAD

**Issue by sjwiesman** [MaterializeInc/materialize#13650]
### What version of Materialize are you using?

0.27.alpha-1

### How did you install Materialize?

Materialize Cloud

### What is the issue?

Creating a kafka source with invalid connection parameters blocks forever. The command cannot be killed via ctrl-c or other external methods. 

While this occurs, when connected to the same region via another terminal attempting to drop a secret referenced in the connection blocks forever. At this point, no other connections can be made to the environment.

**Comment by sjwiesman** [comment]
cc @benesch

**Comment by benesch** [comment]
Thanks very much, Seth! I suspect that dropping the secret is a key part of the problem. Dropping secrets that are referenced shouldn’t be allowed—though, remind me, did you DROP CASCADE or just normal DROP?

**Comment by sjwiesman** [comment]
DROP CASCADE but the CREATE SOURCE statement was still blocked in the other connection

**Comment by benesch** [comment]
Yeah, I suspect there are two separate issues here:

  * Ctrl-C cannot interrupt a `CREATE SOURCE` that is wedged on making a (failed) network call. I'll bet if you left that `CREATE SOURCE` hanging for a few minutes (without dropping secrets or anything) it would eventually fail with some sort of a timeout error.
  * Secrets do not properly track their dependencies, and dropping a secret that has dependencies causes Materialize to wedge up forever.

**Comment by benesch** [comment]
I added this to #13204 so that it doesn't get lost.

**Comment by benesch** [comment]
This turned out to be an issue with how we were using Tokio. Fixed by #13755.
