### ISSUE TITLE
Add connection type for PubNub

### ISSUE THREAD

**Issue by benesch** [MaterializeInc/materialize#13675]
We forgot to add a `CREATE CONNECTION` variant for PubNub. It should consist of just a `SUBSCRIBE KEY` as a secret; the `CHANNEL` should be specified in the `CREATE SOURCE` statement:

```
CREATE CONNECTION pubnub SUBSCRIBE KEY SECRET subscribe_key;
CREATE SOURCE pubnub_stonks FROM PUBNUB CONNECTION pubnub CHANNEL 'stonks';
```

**Comment by morsapaes** [comment]
Closing this after #13865.
