### ISSUE TITLE
storage/sources/kafka: regression: Kafka envelope none ingestion performance sporadically falls below 20K records/second 

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#13748]
### What version of Materialize are you using?

a5f9559

### How did you install Materialize?

Docker image

### What is the issue?

The `KafkaRecordsEnvelopeNone` scenario in the `limits` test attempts to ingest 10M kafka messages . More often than not, the test is able to do that in 30 sec, but sometimes it will need 10x that amount of time or more.

https://buildkite.com/materialize/nightlies/builds/1014#01821ae8-50fe-48db-94a6-de8864ab4711

```
Creating Kafka topic testdrive-kafka-records-envelope-none-3995407220 with partition count of 1
--
  | Ingesting data into Kafka topic testdrive-kafka-records-envelope-none-3995407220 with repeat 10000000
  | > CREATE SOURCE kafka_records_envelope_none             FROM KAFKA BROKER 'kafka:9092' TOPIC 'testdrive-kafka-records-envelope-none-3995407220'             FORMAT AVRO USING CONFLUENT SCHEMA REGISTRY 'http://schema-registry:8081/'             ENVELOPE NONE;
  | rows match; continuing at ts 1658309372.866048
  | > SELECT COUNT(*) FROM kafka_records_envelope_none;
  | rows didn't match; sleeping to see if dataflow catches up 50ms 75ms 112ms 169ms 253ms 380ms 570ms 854ms 1s 2s 3s 4s 6s 10s 15s 22s 33s 21s
  | tmpbo8p72sj:17:1: error: non-matching rows: expected:
  | [["10000000"]]
  | got:
  | [["2015401"]]
  | Poor diff:
  | - 10000000
  | + 2015401
```

In other words, for the problematic runs only 2M records could be ingested within the timeout of 120s, which is only 16K records/second.

It is not a question of the timeout of the test being insufficient -- it has been raised several times already. Either the entire ingestion completes within a very reasonable amount of time or it takes a very long time -- there seems to be a bimodal situation of sorts.

The issue is also reproducible on bare metal, so is not related to any AWS performance fluctuations.

To reproduce:

```
cd test/limits
while bash -c -e "./mzcompose down -v ; ./mzcompose run default --scenario=KafkaRecordsEnvelopeNone" ;  do : ; done
```

Each run in the loop will either look like this:

```
> SELECT COUNT(*) FROM kafka_records_envelope_none;
rows didn't match; sleeping to see if dataflow catches up 50ms 75ms 112ms 169ms 253ms 380ms 570ms 854ms 1s 2s 3s 4s
```
or like this:
```
> SELECT COUNT(*) FROM kafka_records_envelope_none;
rows didn't match; sleeping to see if dataflow catches up 50ms 75ms 112ms 169ms 253ms 380ms 570ms 854ms 1s 2s 3s 4s 6s 10s 15s 22s 33s 21s
^^^ +++
tmpbwu1whgm:17:1: error: non-matching rows: expected:
[["10000000"]]
got:
[["3350869"]]
Poor diff:
- 10000000
+ 3350869
```
and there is no middle ground.

All the records being ingested are identical : `{"f1": "123"}`

**Comment by philip-stoev** [comment]
This is tagged as "green builds" because it affects the Limits CI job. The respective timeout value has been increased several times already and I am afraid if the job is changed to only ingest 1M vs. 10M records, it will not be probing the limits of the product in that dimension, 1M records being a laughably small value to test with.

**Comment by uce** [comment]
This is low priority for now. We will want to revisit this towards the end of the current milestone.

**Comment by benesch** [comment]
Closing as stale. @nrainer-materialize reports that he hasn't seen any recent occurrences of this. Unfortunately, knowledge of what exactly the issue was that got fixed is lost to the sands of time.
