### ISSUE TITLE
doc/user: Rewrite "Getting Started" to highlight new concepts.

### ISSUE THREAD

**Issue by ruf-io** [MaterializeInc/materialize#13760]
### Documentation request

Materialize is introducing some new concepts and changing some old concepts, now is a good time to update the main "[Get Started](https://materialize.com/docs/get-started/)" guide to give new users the best possible 5 minute tour of Materialize, with the goal of making it "click."

### Current Script

1. [Install, Run, Connect](https://materialize.com/docs/get-started/#install-run-connect) - install the binary, run it, connect via psql
2. [Explore a streaming source](https://materialize.com/docs/get-started/#explore-a-streaming-source) - create a (PUBNUB) source, parse it from raw json to columns, create a materialized view, select from it continually.
   - [Joins](https://materialize.com/docs/get-started/#joins) - join with a table.
   - [Temporal Filters](https://materialize.com/docs/get-started/#temporal-filters) - filter to only events from the last minute.
 3. [Learn More](https://materialize.com/docs/get-started/#learn-more)

### Key Changes

- Going from local install to cloud account
- What's the best and simplest way to get a user into a psql session in Materialize? CLI? 
- Explore a streaming source
  - Datagen (see below) removes the JSON parse step
  - Multiple datagen sources could let us do stream-stream joins which would be nice.
  - :new: Materialized Views - what's the right level of detail for getting started?
- Destroy - don't forget to have them destroy everything to reduce waste!

### Future Script

@morsapaes to edit this.

### Related work

In parallel, @mjibson is creating a new "GENERATOR" source that sits in `storaged` and when activated via a statement like `CREATE SOURCE lg FROM LOAD GENERATOR 'counter';` begins dumping fake data into persist to give us the absolute simplest (no external dependency) path to giving users data to work with. This will replace PUBNUB in the current Get Started guide, and it gives us a bit more control and flexibility over the shape of the data generated, so we shouldn't feel limited by

**Comment by morsapaes** [comment]
Fixed in #15115.
