### ISSUE TITLE
Optimization: Modify MapFilterProject if filter is being sped up by index

### ISSUE THREAD

**Issue by wangandi** [MaterializeInc/materialize#13774]
#### What does the transformation do?

Currently, even if a predicate is being evaluated using an index, that predicate is going to be reevaluated the normal way afterwards. It would be nice to not re-evaluate.

```
explain select * from foo where action = 2 limit 1;
                    Optimized Plan                    
------------------------------------------------------
 %0 =
 | ReadExistingIndex materialize.public.foo_idx3
 | | Lookup value (2)
 | Filter (#0 = 2) <----- goal is to remove this line.
 | Project (#1, #0)
```

#### Why should we add it?
Remove unnecessary evaluation work

#### When would it be good to have?
Always.

#### What is the benefit of the transformation?

Saves the amount of work equal to (cost of evaluating the equality predicate) * (number of rows for which the predicate is true). equality is not an expensive operation, and most of the time, the predicate is pretty highly selective.

#### How often will users input a query that can be helped by the transformation?

It seems that people want an index to speed up a filter pretty frequently.

**Comment by ggevay** [comment]
This was resolved in https://github.com/MaterializeInc/materialize/pull/14353, see `CanonicalizeMfp::remove_literal_constraints`.
