### ISSUE TITLE
Expose connection type in `SHOW FULL CONNECTIONS`

### ISSUE THREAD

**Issue by morsapaes** [MaterializeInc/materialize#13800]
### Feature request

For `SHOW CONNECTIONS`, we're grabbing `mz_internal.mz_classify_object_id(t.id)` and exposing that as `type` when the `FULL` option is used:

```sql
materialize=> SHOW FULL CONNECTIONS;
       name       | type
------------------+------
 kafka            | user
 kafka_connection | user
 schema_registry  | user
```

Since the "actual" connection type is available in `mz_catalog.mz_connections`, should we expose that instead? It'd be more useful in this context.

```
materialize=> select * from mz_catalog.mz_connections;

  id  |  oid  | schema_id |       name       |           type
------+-------+-----------+------------------+---------------------------
 u43  | 20905 |         3 | kafka            | kafka
 u173 | 22349 |         3 | kafka_connection | kafka
 u174 | 22350 |         3 | schema_registry  | confluent-schema-registry
(3 rows)
```

Also, if connections are always user-created objects, is `SHOW EXTENDED CONNECTIONS` a redundant command?

**Comment by benesch** [comment]
Yeah, all the SHOW commands need a rethink! See #11231. We could make them all quite a bit more useful if we ditch some of the MySQL funniness. Personally I think both `FULL` and `EXTENDED` should go away.

**Comment by morsapaes** [comment]
> Personally I think both `FULL` and `EXTENDED` should go away.

Big +1. So glad that there's already a bigger plan for this! I'll close this issue, then. Thanks, @benesch!

**Comment by benesch** [comment]
Heh, ended up re-filing this as #14643. It's all comprehensively tracked in #11231 now, though!
