### ISSUE TITLE
performance regression: The "fast path" optimization has been lost with the introduction of new-style materialized views

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#13843]
### What version of Materialize are you using?

5279ca6381eb1ad71af0d469c22e6c9bc3c3b6f3

### How did you install Materialize?

Docker image

### What is the issue?

The feature benchmark reports that the "fast path" optimization has been lost. Queries are now up to two orders of magnitudeslower than they were before.

It is the stuff described here

https://docs.google.com/presentation/d/1Vwk26AnqcVfIQKTHScKy0ISgI3I_q-qn0nbuTXsGcvM/edit#slide=id.gfaec2acb62_0_129

The optimization improved the performance of queries such as:

```
SELECT * FROM v1 WHERE f1 = const
```

To reproduce:

```
in/mzcompose --find feature-benchmark down -v ; bin//mzcompose --find feature-benchmark run default --scenario=FastPathFilterNoIndex --max-measurements=1 --max-retries=1 --this-nodes 1 --this-workers 8 --other-tag=latest
```

The other "FastPath" scenarios in `test/feature-benchmark/scenarios.py` are also affected.

Git blame reports:

```
5279ca6381eb1ad71af0d469c22e6c9bc3c3b6f3 is the first bad commit
commit 5279ca6381eb1ad71af0d469c22e6c9bc3c3b6f3
Merge: e0abd1a3c 9053e35a9
Author: Jan Teske <jteske@posteo.net>
Date:   Sat Jul 23 12:53:01 2022 +0200

    Merge pull request #13706 from teskje/new-materialized-views
    
    New materialized views
```
@jan

**Comment by philip-stoev** [comment]
Compared to the prior commit:


```
bin/mzcompose --find feature-benchmark down -v ; bin//mzcompose --find feature-benchmark run default --scenario=FastPathFilterNoIndex --max-measurements=1 --max-retries=1 --this-nodes 1 --other-nodes 1 --other-tag=devel-e0abd1a3c0d56f81c254448600a88c8dcd17c22a
...
NAME                      |    THIS     |    OTHER    |  Regression?  | 'THIS' is:
----------------------------------------------------------------------------------------------------
FastPathFilterNoIndex     |       6.343 |       1.168 |    !!YES!!    | 5.4 TIMES slower

**Comment by teskje** [comment]
In `SELECT * FROM v1 WHERE f1 = const`, is `v1` a materialized view with or without an index?

If `v1` doesn't have an index, then the fast path not being applicable is expected, I think. The fast path works when we can directly peek from a compute arrangement/index (modulo some simple transformations on top of that). But in the case of the new materialized views there is no index created by default. So we have to do the work of creating a temporary dataflow that reads from the storage collection and exports an index, which can then be peeked.

A simple solution is to `CREATE DEFAULT INDEX ON v1`.

We could maybe also think about adding a fast path for materialized views. In theory at least, adapter could read from storage collections directly. I'm not sure if this sounds like a good idea though. @frankmcsherry probably has an opinion.

**Comment by philip-stoev** [comment]
`CREATE DEFAULT INDEX` causes the regression to go away. 

So before `MATERIALIZED` meant non-persistent-but-arranged but now `MATERIALIZED` means persistent-but-not-arranged ? Are we documenting this somewhere? Previously, we already caused the performance of tables to change radically by removing the creation of the default index that they had...

**Comment by frankmcsherry** [comment]
I do have an opinion, that we should not rush in to having adapter read directly from storage. Eventually having *someone* read from storage is great, but at the moment allowing compute to do that seems fine (it will handle it with multiple workers, etc).

I think we should add indexes to the tests where data expect to be indexed (e.g. any tests that are testing the fast path) but that we might not want to add indexes generally, to be sure we are testing all settings.

**Comment by teskje** [comment]
Btw, it's possible that the huge difference in query time is actually caused by something else than the usage of the "slow path". I'm not convinced that it should be that much slower. There are definitely other performance issues with reading from storage collections (tables + materialized views) right now, e.g.: https://github.com/MaterializeInc/materialize/issues/13840.

**Comment by philip-stoev** [comment]
I will fix the benchmark scenario.

**Comment by teskje** [comment]
> So before MATERIALIZED meant non-persistent-but-arranged but now MATERIALIZED means persistent-but-not-arranged ? Are we documenting this somewhere? Previously, we already caused the performance of tables to change radically by removing the creation of the default index that they had...

Yes, see [the internal sinks syntax design doc](https://www.notion.so/materialize/Internal-storage-sink-syntax-017251c532df465fb3a3ec7c344df54b) for more context (Stage 2 in particular). The devex team has been part of this discussion and we will document this change clearly. But I also hope that at GA reading from a materialized view doesn't take 600 times as long as reading from an index!

**Comment by jan** [comment]
I love that you value my input on this, @philip-stoev. I'm certain you are doing excellent work here. Keep it up.

Kind regards, @jan.
