### ISSUE TITLE
performance regression: multi-second delays when SELECTing from a nested materialized view

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#13840]
### What version of Materialize are you using?

environmentd v0.26.1-dev (452d930c6)

### How did you install Materialize?

Docker image

### What is the issue?

If a materialized view depends on another materialized view, selecting from said view make take several seconds. The longer the chain, the worse the peformance. I belive this was not the case prior to making materialized views recorded. @teskje 

To reproduce:

```
create table t1 (f1 integer);
create materialized view v1 as select f1 + 1 as f1 from t1;
create materialized view v2 as select f1 + 1 as f1 from v1;

materialize=> select * from v2;
 f1 
----
(0 rows)

Time: 1936.025 ms (00:01.936)
```

This is acompanied by the following log lines:

```
compute-cluster-1-replica-1: 2022-07-25T07:00:34.765023Z  INFO mz_persist_client::r#impl::machine: snapshot s4a36bfd9-2a8d-4586-ac94-c0fd69dbcf01 as of Antichain { elements: [1658732434400] } not yet available for upper Antichain { elements: [1658732433401] } retrying in 64ms
compute-cluster-1-replica-1: 2022-07-25T07:00:34.835137Z  INFO mz_persist_client::r#impl::machine: snapshot s4a36bfd9-2a8d-4586-ac94-c0fd69dbcf01 as of Antichain { elements: [1658732434400] } not yet available for upper Antichain { elements: [1658732433401] } retrying in 128ms
compute-cluster-1-replica-1: 2022-07-25T07:00:34.960048Z  INFO mz_persist_client::r#impl::machine: snapshot s4a36bfd9-2a8d-4586-ac94-c0fd69dbcf01 as of Antichain { elements: [1658732434400] } not yet available for upper Antichain { elements: [1658732433401] } retrying in 256ms
compute-cluster-1-replica-1: 2022-07-25T07:00:35.226771Z  INFO mz_persist_client::r#impl::machine: snapshot s4a36bfd9-2a8d-4586-ac94-c0fd69dbcf01 as of Antichain { elements: [1658732434400] } not yet available for upper Antichain { elements: [1658732433401] } retrying in 512ms
compute-cluster-1-replica-1: 2022-07-25T07:00:35.690682Z  INFO mz_persist_client::r#impl::machine: snapshot s4a36bfd9-2a8d-4586-ac94-c0fd69dbcf01 as of Antichain { elements: [1658732434400] } not yet available for upper Antichain { elements: [1658732433401] } retrying in 1.024s
```
This INFO message is seen in other contexts and was considered harmless, except that in this case the problem is not resolved after a single retry, but several are required which causes the back-off to become significant.

**Comment by teskje** [comment]
According to my brief local testing, querying `v2` above can be very fast, but it can also be very slow. When it is slow, that seems to be because we select a timestamp that is ahead of the current upper of the storage collection, so we need to wait for it to catch up:

```
materialize=> EXPLAIN TIMESTAMP FOR SELECT * FROM v2;
                  Timestamp
---------------------------------------------
      timestamp: 1658734293360              +
          since:[1658734291000]             +
          upper:[1658734292361]             +
      has table: true                       +
  table read ts: 1658734293360              +
                                            +
 source materialize.public.v2 (u3, storage):+
  read frontier:[1658734291000]             +
 write frontier:[1658734292361]             +
```

The issue also goes away when I opt out of strict serializability (`SET transaction_isolation = serializable`).

As far as I understand, what happens here is that we set the query `as_of` to the global table write timestamp, because strict serializability requires that the SELECT sees all previous writes to the table. And then we have to wait for that time to propagate through persist twice.

It seems to me that to improve this, we have to either make a change to the `as_of` selection (e.g., there shouldn't be a need to wait if there have not been any writes to the table) or make persist faster somehow. But that's just spit-balling. @jkosh44 and @danhhz probably have helpful input.

**Comment by jkosh44** [comment]
@teskje You're understanding is correct. Something like https://github.com/MaterializeInc/materialize/issues/13778 would hopefully fix this issue.

**Comment by frankmcsherry** [comment]
I just tried this out, and my experience was not (today) as bad as @philip-stoev's.
```
materialize=> create table t1 (f1 integer);
materialize=> create materialized view v1 as select f1 + 1 as f1 from t1;
materialize=> create materialized view v2 as select f1 + 1 as f1 from v1;
materialize=> select * from v2;
 f1 
----
(0 rows)

Time: 586.099 ms
```
This involves three trips through `persist`, the table being sealed at the query time, then `v1`, then `v2`. Tbh, I expected it would take longer. With more views it is worse, but it seems to be about 200ms per trip through `persist`.
```
materialize=> create materialized view v3 as select f1 + 1 as f1 from v2;
materialize=> create materialized view v4 as select f1 + 1 as f1 from v3;
materialize=> create materialized view v5 as select f1 + 1 as f1 from v4;
materialize=> create materialized view v6 as select f1 + 1 as f1 from v5;
materialize=> create materialized view v7 as select f1 + 1 as f1 from v6;
materialize=> create materialized view v8 as select f1 + 1 as f1 from v7;
materialize=> create materialized view v9 as select f1 + 1 as f1 from v8;
materialize=> select * from v9;
 f1 
----
(0 rows)

Time: 2168.534 ms (00:02.169)
materialize=> 
```

**Comment by philip-stoev** [comment]
A chain of 25 materialized views needs more than 120s to return a result.

**Comment by nmeagan11** [comment]
Adding to the Surfaces backlog as we believe it might be a timestamp selection issue with coord.

**Comment by frankmcsherry** [comment]
Additionally, I think recent changes have undone @teskje's observation that
> The issue also goes away when I opt out of strict serializability (SET transaction_isolation = serializable).

I think we acquire constraints from all collections in the "time domain" which will include the root of the MV chains, and whatever `since` it has (potentially advanced well beyond the uppers of the MVs).

**Comment by jkosh44** [comment]
I just want to provide some explanation of why this is happening and some potential approaches.

A large chain of materialized views will have a large propagation delay. Which means a write to a table will take a long time before it is applied to all materialized views. For example here's the timestamp info for the table `t1` and materialized view `v10` from @philip-stoev's example (in cloud)

```
materialize=> EXPLAIN TIMESTAMP FOR SELECT * FROM t1; EXPLAIN TIMESTAMP FOR SELECT * FROM v10;
                  Timestamp                  
---------------------------------------------
      timestamp: 1662051094979              +
          since:[1662051093000]             +
          upper:[1662051094980]             +
      has table: true                       +
  table read ts: 1662051094979              +
                                            +
 source materialize.public.t1 (u1, storage):+
  read frontier:[1662051093000]             +
 write frontier:[1662051094980]             +
 
(1 row)

                   Timestamp                   
-----------------------------------------------
      timestamp: 1662051094979                +
          since:[1662051085000]               +
          upper:[1662051086981]               +
      has table: true                         +
  table read ts: 1662051094979                +
                                              +
 source materialize.public.v10 (u11, storage):+
  read frontier:[1662051085000]               +
 write frontier:[1662051086981]               +
 
(1 row)

```
When comparing the two uppers we see the Materialized View is roughly 8 seconds behind the table.

So under Strict Serializability when we make a write we have a couple of options:
1. Block and don't return from the write until all Materialized Views are updated. That would mean in this scenario writes take roughly 8 seconds but reads are fast. The amount we block for writes would be unbounded and depend on the largest propagation delay of all Materialized Views.
2. Don't block writes and don't wait for Materialized Views to be updated (this is what we currently do). That would mean in this scenario writes are fast, but reads are as slow as the propagation delay of whatever you're reading from.

For queries that only involve tables, there are probably some optimizations we can make if there have been no writes. However, for queries that involve sources, the adapter doesn't really have any info on when the last non-empty write was.

Additionally trying to decrease the overall propagation delay of Materialized Views would make everything faster. 8 seconds is a bit of a large delay IMO considering the table is completely empty.

**Comment by jkosh44** [comment]
There is also the freshness vs latency tradeoff here for upstream sources. The staler the data we show from sources is, the more likely that materialized views have caught up and reads from them can be served immediately.

**Comment by teskje** [comment]
Just tried with a stack of 25 MVs (for which Philip reported a 120s delay above) on staging, and it is fast:
```sql
materialize=> create table t1 (f1 integer);
create materialized view v1 as select f1 + 1 as f1 from t1;
create materialized view v2 as select f1 + 1 as f1 from v1;
create materialized view v3 as select f1 + 1 as f1 from v2;
create materialized view v4 as select f1 + 1 as f1 from v3;
create materialized view v5 as select f1 + 1 as f1 from v4;
create materialized view v6 as select f1 + 1 as f1 from v5;
create materialized view v7 as select f1 + 1 as f1 from v6;
create materialized view v8 as select f1 + 1 as f1 from v7;
create materialized view v9 as select f1 + 1 as f1 from v8;
create materialized view v10 as select f1 + 1 as f1 from v9;
create materialized view v11 as select f1 + 1 as f1 from v10;
create materialized view v12 as select f1 + 1 as f1 from v11;
create materialized view v13 as select f1 + 1 as f1 from v12;
create materialized view v14 as select f1 + 1 as f1 from v13;
create materialized view v15 as select f1 + 1 as f1 from v14;
create materialized view v16 as select f1 + 1 as f1 from v15;
create materialized view v17 as select f1 + 1 as f1 from v16;
create materialized view v18 as select f1 + 1 as f1 from v17;
create materialized view v19 as select f1 + 1 as f1 from v18;
create materialized view v20 as select f1 + 1 as f1 from v19;
create materialized view v21 as select f1 + 1 as f1 from v20;
create materialized view v22 as select f1 + 1 as f1 from v21;
create materialized view v23 as select f1 + 1 as f1 from v22;
create materialized view v24 as select f1 + 1 as f1 from v23;
create materialized view v25 as select f1 + 1 as f1 from v24;
[...]
materialize=> \timing
Timing is on.
materialize=> select * from v25;
 f1
----
(0 rows)

Time: 143.737 ms
```

So I think this can be considered resolved.
