### ISSUE TITLE
Rename introspection source mz_materialization_dependencies to mz_worker_materialization_dependencies

### ISSUE THREAD

**Issue by vmarcos** [MaterializeInc/materialize#13851]
The introspection source `mz_materialization_dependencies` has the following schema description:

```
Table "mz_catalog.mz_materialization_dependencies"
  Column  |  Type  | Collation | Nullable | Default 
----------+--------+-----------+----------+---------
 dataflow | text   |           | not null | 
 source   | text   |           | not null | 
 worker   | bigint |           | not null | 
Indexes:
    "mz_materialization_dependencies_1_primary_idx" arrangement (dataflow,source,worker)
```

In the naming of our catalog objects for introspection, we have tended to use the prefix `mz_worker*` for objects that contain worker as a column. This naming convention is not followed by `mz_materialization_dependencies`. 

@antiguru For your attention, if we want to execute the renaming above, we should probably plan to solve this issue before we have to uphold strong standards of backwards compatibility. 

It might be worth it as part of this issue to go over our other catalog sources, tables, and views as well to check for naming inconsistencies.

**Comment by benesch** [comment]
Thanks! There's quite a few of these that we should tackle in platform. I added this to the list in #7174.
