### ISSUE TITLE
Storaged pods do not have any resource limits set, which causes the node to OOM

### ISSUE THREAD

**Issue by alex-hunt-materialize** [MaterializeInc/materialize#13853]
### What version of Materialize are you using?

materialize/storaged:devel-ea4d368301b07ef15a2f0bce98886689bae87487

### How did you install Materialize?

Materialize Cloud

### What is the issue?

The pods do not have any resource limits set (for either CPU or RAM). There are many pods running on the node, and it eventually ran out of memory and something important in the OS or the kubelet got killed by the OOM killer.

ALL pods MUST have resource limits for both CPU and RAM. Ideally they will also have CPU and RAM requests equal to that limit. Without these, K8S is free to schedule the pods anywhere and they can run amok, even to the point of breaking the node.

https://ui.honeycomb.io/materialize/datasets/production.kubernetes-metrics/result/J5X4nz54A6F

**Comment by alex-hunt-materialize** [comment]
@benesch What resources do these pods need?

**Comment by benesch** [comment]
Yes, sorry, this is known! Let's centralize discussion on #13125.
