### ISSUE TITLE
CI: sqllogictests flaky

### ISSUE THREAD

**Issue by benesch** [MaterializeInc/materialize#13867]
Our fast sqllogictests job is frequently failing in CI with the following crash:

```
thread 'tokio-runtime-worker' panicked at 'A Tokio 1.x context was found, but it is being shutdown.', /cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/time/driver/entry.rs:551:13
stack backtrace:
   0: rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::panicking::panic_display
   3: <tokio::time::driver::sleep::Sleep as core::future::future::Future>::poll
   4: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   5: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   6: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
   7: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   8: std::thread::local::LocalKey<T>::with
   9: tokio::park::thread::CachedParkThread::block_on
  10: tokio::runtime::handle::Handle::block_on
  11: <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll
  12: tokio::runtime::task::core::CoreStage<T>::poll
  13: tokio::runtime::task::harness::Harness<T,S>::poll
  14: tokio::runtime::blocking::pool::Inner::run
```

Example: https://buildkite.com/materialize/tests/builds/38329#01823726-a6d7-4550-8259-3b067b104489

As best as I can tell, the problem is that we have code that looks like this in Materialize:

```
let handle = tokio::runtime::Handle::current();
tokio::task::spawn_blocking(|| {
    handle.block_on(async {
        tokio::time::sleep(...).await;
    })
})
```

When the Tokio runtime is shut down, it can't abort the `spawn_blocking` closure (because it doesn't have await points). But it turns off the timer. So the call to `tokio::time::sleep` explodes. See https://github.com/tokio-rs/tokio/issues/4862 for a better explanation of this.

In particular, I suspect it's this code in persist compaction that is responsible, though I haven't actually validated this hypothesis:

https://github.com/MaterializeInc/materialize/blob/744940bfc3d161c8951b11671882a4cb1ff2ac9b/src/persist-client/src/impl/compact.rs#L243-L250

@danhhz @ph14, one solution suggested by the Tokio docs is to create a separate Tokio runtime for CPU-intensive tasks. Then you just call `cpu_bound_runtime.block_on` where you currently call `spawn_blocking`. Would that be a viable solution?

**Comment by danhhz** [comment]
Works for me, but I'm always surprised by tokio nuance so take that with a grain of salt.

**Comment by danhhz** [comment]
> one solution suggested by the Tokio docs is to create a separate Tokio runtime for CPU-intensive tasks. Then you just call cpu_bound_runtime.block_on where you currently call spawn_blocking. Would that be a viable solution?

@benesch do you have a link handy for this?

**Comment by philip-stoev** [comment]
See also https://github.com/MaterializeInc/materialize/issues/13930

**Comment by JLDLaughlin** [comment]
another instance of a panic on shutdown.

**Comment by JLDLaughlin** [comment]
we _think_ this might have been fixed, please reopen if you see this again!
