### ISSUE TITLE
[Epic] storage: distribute write work across all timely workers in persist_sink

### ISSUE THREAD

**Issue by sploiselle** [MaterializeInc/materialize#13886]
### Feature request

Currently, Materialize only uses a single Timely worker to read from persist (`persist_source`) and write to it (`persist_sink`). This leaves a lot of throughput on the table by not taking advantage of the available parallelism.

Design doc: https://www.notion.so/materialize/Distribute-write-work-across-all-timely-workers-in-persist_sink-d3d59834ed9d47d397143c738e9d6c9d

**Comment by aljoscha** [comment]
https://github.com/MaterializeInc/materialize/pull/14001

**Comment by nmeagan11** [comment]
Now that #14001 has merged, is this ready for QA? cc @aljoscha

**Comment by aljoscha** [comment]
I'd say it's ready, yes.

**Comment by aljoscha** [comment]
Is it enough to assign "QA Team" or is there also a label (didn't find one that would fit)?

**Comment by nmeagan11** [comment]
Adding it to the QA team project board is the way to go I believe!

**Comment by aljoscha** [comment]
@philip-stoev Some clarification: this change makes it so that `MATERIALIZED VIEWs`, which are backed by `persist_sink` can scale up to the number of available workers. It does not change how we write to persist from sources/ingestions, those use a different `persist_sink` that is not yet parallelized.

**Comment by philip-stoev** [comment]
Materialized views seem to work OK with `SIZE` > 1 , as far as I could test them, so I am closing this one . A test will be pushed once as the rest of the source/sink types become compatible with `SIZE` > 1.

**Comment by aljoscha** [comment]
tyty! at least one thing can be closed. Sorry for all the chaos otherwise! :sweat_smile:
