### ISSUE TITLE
test: Specifying an argument in `Composition.testdrive` can lead to duplicate arguments

### ISSUE THREAD

**Issue by jkosh44** [MaterializeInc/materialize#13890]
### What version of Materialize are you using?

v0.26.1-dev

### How did you install Materialize?

Built from source

### What is the issue?

When creating a `Testdrive` service many of the testdrive arguments are specified in the constructor:
https://github.com/MaterializeInc/materialize/blob/c5b9619ba852ec29a12f676f3121c1ca27b83df3/misc/python/materialize/mzcompose/services.py#L589-L614

These are directly converted into arguments for the testdrive program:
https://github.com/MaterializeInc/materialize/blob/c5b9619ba852ec29a12f676f3121c1ca27b83df3/misc/python/materialize/mzcompose/services.py#L637-L683

Later when invoking `Composition.testdrive()`, you can specify arguments to pass to the testdrive program:
https://github.com/MaterializeInc/materialize/blob/33143731de58e6a55d07466b79a0de9eeef70608/misc/python/materialize/mzcompose/__init__.py#L753-L772

These are eventually combined with arguments passed to the `Testdrive` service (look for `self.compose["services"][service]["entrypoint"]` and `*args`):
https://github.com/MaterializeInc/materialize/blob/33143731de58e6a55d07466b79a0de9eeef70608/misc/python/materialize/mzcompose/__init__.py#L498-L531

This can lead to specifying the same argument multiple times. For example if you call 
`c.testdrive("", args="--materialize-url=postgres://materialize@localhost:6876")` 
Then the following docker command will be executed (note the duplicate `--materialize-url` arg): 
`docker compose exec -T testdrive testdrive --kafka-addr=kafka:9092 --schema-registry-url=http://schema-registry:8081 --materialize-url=postgres://materialize@materialized:6875 --aws-endpoint=http://localstack:4566 --validate-data-dir=/mzdata --default-timeout=120s --materialize-url=postgres://materialize@localhost:6876`

**Comment by philip-stoev** [comment]
Yes, the last command line option value wins. This is how rust command-line option parsing works with `clap`. Is that OK with you? Or you prefer some other way?

**Comment by jkosh44** [comment]
Ahh if that's how rust does it then I suppose it's fine. I just found it a bit confusing on how to properly override the `materialize-url`.
