### ISSUE TITLE
sql-parser: move minor `CREATE SOURCE` options to `WITH` block

### ISSUE THREAD

**Issue by andrioni** [MaterializeInc/materialize#13919]
[More context in Slack](https://materializeinc.slack.com/archives/C01CFKM1QRF/p1658843321106399), but the main idea is to move options like `REMOTE` and `TIMELINE` to the new `WITH (OPT1 VAL1 OPT2 VAL2)` block that supports order-independent settings, similar to `CREATE CONNECTION` already works.

**Comment by benesch** [comment]
We should cleanly separate the options! Some of the legacy with options (like `start_offset`) ought to move to a Kafka-specific option block. Only the options that are unrelated to the connector, format, or envelope should move to the new top-level `WITH` block. I _think_ that's just `REMOTE`, `SIZE`, and `TIMELINE`, but not sure. `TIMELINE` is also not something we want to expose to users quite yet, I don't think, so no particular urgency to move it.

**Comment by bkirwi** [comment]
`REMOTE`, `SIZE`, and `TIMELINE` have been moved, and we've decided against moving `epoch_ms_timeline`... so it looks like we're done here!

There are a few other odds and ends that are moving to source- or envelope-specific option blocks; see https://github.com/MaterializeInc/materialize/issues/14341 for some related work.
