### ISSUE TITLE
storage controller does not retry failed persist writes

### ISSUE THREAD

**Issue by benesch** [MaterializeInc/materialize#13921]
The storage controller does not retry failed calls to `compare_and_append`. We observed a crash due to a persist consensus connection to a cockroach node that was shutting down; this caused a `PersistWorker` to take down `environmentd`.

I'm not entirely sure whether it's safe to retry this blindly, but there's surely some sort of check we can make to determine whether we can retry.

Backtrace: https://gist.github.com/benesch/7d74f73235973ef5d54d0d6dc8ffa26d

cc @danhhz @mjibson @pH14

**Comment by mjibson** [comment]
I'm pretty sure this is also https://github.com/MaterializeInc/materialize/issues/13210

**Comment by benesch** [comment]
This got fixed by #14003.
