### ISSUE TITLE
`true and` inserted at the beginning of join conditions

### ISSUE THREAD

**Issue by ggevay** [MaterializeInc/materialize#13927]
### What version of Materialize are you using?

v0.26.1-dev (0228369af)

### How did you install Materialize?

Built from source

### What is the issue?

`src/sql/src/plan/query.rs:plan_using_constraint` inserts a `true AND` at the beginning of join constraints (see e.g., `joins.slt:645`). This obviously does not affect the query semantics, so it should be removed.

However, if I remove it then some plans change in weird ways (e.g., column_knowledge.slt:117 and 558) which suggests some optimizer bug/brittleness somewhere else, so it would be good to investigate.

**Edit:** The optimizer tracing now makes investigating this considerably easier.

Note: The various reductions for variadic AND are not eliminating this, because I guess it's in the list of predicates (implicitly ANDed), outside an AND. (EXPLAIN conflates the implicit AND of the list of predicates, and an actual AND.)

**Comment by JLDLaughlin** [comment]
it's a cosmetic issue in the query plan!

**Comment by aalexandrov** [comment]
Downgrading this to `C-refactoring`, as this does not result in wrong plans. We should work on that, but it is not a "stop and do this immediately" kind of an issue.

**Comment by ggevay** [comment]
Solved in 8ad22299fc0305bda6753e9766f34fd88bbbe353
