### ISSUE TITLE
`persist` consensus and CockroachDB's default GC TTL uses a lot of storage

### ISSUE THREAD

**Issue by benesch** [MaterializeInc/materialize#13975]
I observed an environment in Materialize Cloud with no sources using ~3GB of space in `consensus.consensus` after leaving the environment on for about 20 hours. I suspect this is pileup from the introspection views in the default cluster.

The default garbage collection TTL in Cockroach is 24 hours. I suspect we want to turn that way, way down.

In theory, I think we want a GC TTL of zero seconds, because the `consensus` table does its own GC on top of Cockroach. Rows in the `consensus` table aren't updated in place. Rather, each row for each shard carries a sequence number. New state is written to a row with a higher sequence number. Rows with old sequence numbers are periodically garbage collected. So, I _think_ we could probably shut off Cockroach's GC entirely and be quite happy.

The wrinkle here is incremental backups. Setting the GC TTL to 0 for `consensus` will break the automatically-scheduled incremental backup job. It's almost surely fine to do only full backups of the `consensus` table, but that will require us configuring our own backup schedule in Cockroach Cloud, rather than relying on their default.

cc @danhhz

**Comment by benesch** [comment]
Here's the SQL traffic with the three environments we have running in production right now:
<img width="964" alt="image" src="https://user-images.githubusercontent.com/882976/182005389-d1e7c551-6a67-4e95-ba1f-e734e3aca0ce.png">

Works out to 20 inserts/s, 10 selects/s, and a bit under a delete every second.

I'm not sure precisely how many shards this is. But it seems reasonable for having three basically empty environments running. What's not so reasonable is the CPU usage. We're getting close to toppling two of the nodes in the cluster:

<img width="947" alt="image" src="https://user-images.githubusercontent.com/882976/182005512-1455fbe8-ed28-462c-a294-d26e8f73658e.png">

A quick look at node 3, which has it the worst in the above graph, shows quite a bit of time spent in `batcheval.Scan`:

<img width="1574" alt="image" src="https://user-images.githubusercontent.com/882976/182005589-00240c6e-f9ff-4eb6-8ac8-96158960aac2.png">

I believe this is consistent with the pileup of deleted rows. `SELECT count(*) FROM consensus.consensus` in my environment is painfully slow. I'll bet Cockroach is spending lots of time grinding over these to-be-GC'd rows with every one of the `DELETE` statements. Average execution for the `DELETE` statements is 300ms. Slow!

**Comment by benesch** [comment]
@danhhz, @mjibson, @alex-hunt-materialize: assuming y'all agree with my above assessment, who should own setting the GC TTL? Persist or cloud?

**Comment by danhhz** [comment]
Great find! My first reaction is that only doing full backups would in fact be desirable for consensus. Given the workload pattern, each Incremental backup would consist of deleting the entirety of the old contents and then putting in the new contents, so e.g. 1 full + 1 incremental would be 3x the data vs if the incremental was just a full backup.

I haven't actually typed it out, but from a scan of the docs, it feels like it should be pretty easy for persist to set the gc ttl for the consensus table. I assume cloud should be responsible for whatever backup tweaks fall out of this.

Fwiw, crdb does recommend that this not be set below 10m. https://www.cockroachlabs.com/docs/stable/configure-zone.html#variables

> It is not recommended to set this below 600 (10 minutes); doing so will cause problems for long-running queries.

**Comment by rjnn** [comment]
On long running queries, how things work is that the GC ttl sets a bit of a cap on query running time. So you _could_ set it to 1 minute, but then pretty much any query that takes longer than a minute to execute that might touch those rows is likely to fail.

As long as we're comfortable saying that we don't have query access patterns that take a minute that touch these rows, then we can set it to 1m.

Also note:

> Also, since all versions of a row are stored in a single range that never splits, it is not recommended to set this so high that all the changes to a row in that time period could add up to more than 512 MiB;

We might also want to change our access pattern so that we switch rows on a faster schedule.

Where is the schema documented in how we are using cockroach? I sense a lot of performance optimization low hanging fruit here and would love to take a look.

**Comment by danhhz** [comment]
This callsite is 99%+ of our usage by volume:

https://github.com/MaterializeInc/materialize/blob/a6a772e329a3b14b1ea750a2838e25625ac952ab/src/persist/src/postgres.rs#L278

cc @pH14 This 512 MiB thing might be an argument against switching to the head+history style schema we've discussed.

I definitely agree that there's something to be tuned here. Now that we've manage to keep persist from immediately falling over, it's pretty obvious that something about our usage is busted.

**Comment by pH14** [comment]
Seems reasonable to try this out! I've seen very similar scan/tombstone behavior before in other systems, so it would not surprise me if CRDB doesn't naturally like our usage pattern. Since the knob can be set per-table, it seems reasonable for persist to handle it, if it does turn out to be fruitful

**Comment by jordanlewis** [comment]
👋  I wanted to call to your attention the ability to run `EXPLAIN ANALYZE (VERBOSE)` on a query to see the amount of MVCC garbage a query encounters. That might help you further confirm hypotheses like the one you were looking at in the flamegraph.

**Comment by benesch** [comment]
😲 thanks for the protip, @jordanlewis!

**Comment by danhhz** [comment]
hi @jordanlewis :wave:! we'll definitely try that out. it might be a week or two before we do anything here tho, we've got a couple bigger fish to fry first

**Comment by benesch** [comment]
Reopening, because I think there's something to continue to look into here! `consensus.consensus` in my environment in the steady state (nothing going on but the introspection sources in the two empty replicas) is still using 4GB of data:

```
environment_1de0023fe2fa41059c873b1086e06b6e=> explain analyze (verbose) select shard, count(*) from consensus.consensus group by shard;
                                         info                                         
--------------------------------------------------------------------------------------
 planning time: 901µs
 execution time: 7.4s
 distribution: full
 vectorized: true
 rows read from KV: 2,787,124 (4.0 GiB)
 cumulative time spent in KV: 7.3s
 maximum memory usage: 10 MiB
 network usage: 0 B (0 messages)
 regions: aws-us-east-1
 
 • group (streaming)
 │ columns: (shard, count)
 │ nodes: n2
 │ regions: aws-us-east-1
 │ actual row count: 69
 │ vectorized batch count: 1
 │ estimated row count: 69
 │ aggregate 0: count_rows()
 │ group by: shard
 │ ordered: +shard
 │
 └── • scan
       columns: (shard)
       ordering: +shard
       nodes: n2
       regions: aws-us-east-1
       actual row count: 2,787,124
       vectorized batch count: 2,722
       KV time: 7.3s
       KV contention time: 0µs
       KV rows read: 2,787,124
       KV bytes read: 4.0 GiB
       estimated max memory allocated: 10 MiB
       MVCC step count (ext/int): 4,521,050/3,780,768
       MVCC seek count (ext/int): 854/854
       estimated row count: 2,630,778 (100% of the table; stats collected 1 hour ago)
       table: consensus@consensus_pkey
       spans: FULL SCAN
(38 rows)

Time: 7424.845 ms (00:07.425)
```

**Comment by danhhz** [comment]
from slack: looks like all of this is live persist data. I actually think this is good news! much easier to fix the problem if it's us than if it's crdb

```environment_1de0023fe2fa41059c873b1086e06b6e=> select sum(length(data)) from consensus.consensus;
    sum     
------------
 4322698011
(1 row)

Time: 13098.724 ms (00:13.099)```

**Comment by pH14** [comment]
More consensus state leakage! In order of most scary to least scary, here are more bugs we need to fix to control our consensus data:

- [ ] read handles stop receiving downgrade_since calls for introspection shards if computed restarts 
   * https://github.com/MaterializeInc/materialize/issues/14261
- [ ] read handles are not dropped when a source or table is dropped, so they heartbeat indefinitely and accumulate state   
  * https://github.com/MaterializeInc/materialize/issues/14251
  *  https://github.com/MaterializeInc/materialize/pull/14263
- [ ] there’s still an edge case in persist that deletes blobs that a reader still needs, so a reader gets stuck in a perma-retry-loop trying to access the blob 
  * https://github.com/MaterializeInc/materialize/pull/14101 
  * https://github.com/MaterializeInc/materialize/pull/14254 helps this symptom but doesn't solve the underlying issue
- [ ] a crash looping writer will fail to advance the frontier, so a read handle heartbeats indefinitely and accumulates state
  * https://github.com/MaterializeInc/materialize/issues/14265

**Comment by benesch** [comment]
Just wanted to say thanks again for the above, @pH14! It's been super helpful to have that list handy.

**Comment by nmeagan11** [comment]
@pH14, what's the current status of this one? Looks like all of the bugs above have been addressed?

**Comment by pH14** [comment]
All the changes have merged, but lemme take a look at our Cockroach numbers today to confirm everything is working as we expect!

**Comment by pH14** [comment]
Looked through the CRDB dashboards and our overall usage numbers are 👌 right now. Additionally checked the # of consensus states across all existing environments, and they're looking good! Down to 10-40MB worth of state, rather than gigs before, phew
