### ISSUE TITLE
environmentd: `show views` sitting in pending for half a second

### ISSUE THREAD

**Issue by mjibson** [MaterializeInc/materialize#14019]
`SHOW VIEWS` is taking half a second for 2 views over a load generator source (with a 1s tick interval so not loaded at all):

```
materialize=> show views;
   name   
----------
 auctions
 bids
(2 rows)

Time: 528.206 ms
```

Seems like this should be faster. But seems like the upper is still regularly behind the timestamp. Maybe this is just SS biting us?

```
materialize=> explain timestamp for select * from mz_views;
                  Timestamp                  
---------------------------------------------
      timestamp: 1659462992396              +
          since:[1659462990000]             +
          upper:[1659462991397]             +
      has table: true                       +
  table read ts: 1659462992396              +
                                            +
 source mz_catalog.mz_views (s263, storage):+
  read frontier:[1659462990000]             +
 write frontier:[1659462991397]             +
 
(1 row)
```

![ss_000](https://user-images.githubusercontent.com/41181/182441759-8e46ef57-ca9d-4360-8d73-1549cd169e52.png)

**Comment by jkosh44** [comment]
I think this is probably SS biting us. Is it faster in Serializable? Hopefully https://github.com/MaterializeInc/materialize/pull/13967 will fix this.

**Comment by ggnall** [comment]
Closing as outdated. We will revisit performance benchmarks/cases in #15811
