### ISSUE TITLE
Differential join applies de-permutation before the first join

### ISSUE THREAD

**Issue by ggevay** [MaterializeInc/materialize#14059]
### What version of Materialize are you using?

v0.26.1-dev (3a15e2389)

### How did you install Materialize?

Built from source

### What is the issue?

There are some issues around the `initial_closure` of the `LinearJoinPlan`:
1. A comment in `render_join` says "In the current code this should always be `None`". This doesn't seem to be true anymore. In fact, it's always `Some` if there is a `source_arrangement` in `LinearJoinPlan::create_from`, which leads to the real problem:
2. In the first `match` of `render_join` we never go into the first 2 cases. This means that even if the original starting collection is arranged, we lose that arrangement, and always re-arrange it, after applying the `initial_closure`. This can create a big performance issue when a zigzag join would avoid scanning the whole starting collection, but applying `initial_closure` in a flat_map scans the collection instead. For example, this happens if we try to implement `WHERE indexed_stuff.f1 IN (1,2,3)` with a differential join with `indexed_stuff` as the starting collection.
3. Currently, the `initial_closure` doesn't contain any pushed down MFP, but is just a de-permutation of the arrangement. We might want to push down some MFP into it. (Maybe this could be split off into a separate github issue.)

To fix 1. and 2., we could apply `initial_closure` after the first join, similarly as the other `JoinClosure`s in the `stage_plans` de-permute the other arrangements.

When fixing 3., we should make sure to not undo the fix for 2: Either push down only to after the first join, or push to before the first join only if there is no arrangement on the starting collection.

After fixing 3., we might have to rethink the `skip(1)` when computing `max_min_characteristics` in `differential::plan`.

**Comment by antiguru** [comment]
This is only a bug in terms of a missed opportunity to run a better plan than we currently do. I'll scope it as a P2, leaning towards P3 unless it blocks other items.

**Comment by antiguru** [comment]
cc @brennanvincent for awareness.

**Comment by brennanvincent** [comment]
Good catch @ggevay

**Comment by ggevay** [comment]
Also, if we happen to push down something like `<expr>=`<literal>` to the `initial_closure`, and we have an index on `<expr>`, then we could do an index lookup for `<literal>` instead of scanning the whole index.

Maybe this would help with this user query? https://materializeinc.slack.com/archives/C02PPB50ZHS/p1663093368931639

**Comment by ggevay** [comment]
An important special case is solved in https://github.com/MaterializeInc/materialize/pull/15139. The more general case is not happening in any of the TPC-H queries, so we can put it off for now.

**Comment by ggevay** [comment]
@frankmcsherry fixed this in https://github.com/MaterializeInc/materialize/pull/16036
