### ISSUE TITLE
`Threshold` elision

### ISSUE THREAD

**Issue by frankmcsherry** [MaterializeInc/materialize#14061]
#### What does the transformation do?
```
materialize=> explain select * from foo except all (select * from foo where a != 6);
           Optimized Plan            
-------------------------------------
 Source materialize.public.foo (u1):+
 | Project (#0)                     +
                                    +
 Query:                             +
 %0 =                               +
 | Get materialize.public.foo (u1)  +
                                    +
 %1 =                               +
 | Get materialize.public.foo (u1)  +
 | Filter (#0 != 6)                 +
 | Negate                           +
                                    +
 %2 =                               +
 | Union %0 %1                      +
 | Threshold                        +
 
(1 row)

materialize=> 
```

The `Threshold` operator can be removed when we can determine that we are subtracting a restriction of some relation from itself. This happens above, but also has happened for a prospect where they perform a `TopK` (producing a restriction of the input) and want to form the collection of input things that are not in the top k.

#### Why should we add it?

The `Threshold` operator requires maintaining the entire volume of data in the above query, where no other operator requires it. Removing it would be a dramatic reduction in memory requirement.

#### When would it be good to have?

Whenever it can be applied.

#### When would it be ineffectual?

Whenever it cannot be applied.

#### When would be bad to have?

Never.

#### In the worst case, how would it degrade performance?

It would not.

**Comment by aalexandrov** [comment]
Redundant join might have logic that we can reuse for the restriction test.

**Comment by philip-stoev** [comment]
Item No #1. The optimization does not kick in for the following case:

```
DROP TABLE IF EXISTS t1;
CREATE TABLE t1 (f1 INTEGER, f2 INTEGER);
EXPLAIN SELECT f1 FROM t1 EXCEPT SELECT f1 FROM t1 WHERE f1 = 5;
```

It does kick in for `f2=5` . For `f1=5`, the plan contains a `Map 5` , could this be the reason?
