### ISSUE TITLE
performance: spikes in latency (>0.5-1s) for simple , non-concurrent SELECT queries

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#14060]
### What version of Materialize are you using?

3dbcaada4147db206a46a381b88af3d52cf1834a

### How did you install Materialize?

Docker image

### What is the issue?

SLT tests are about 3x slower when run in Platform v.s. the single-binary Mz. There are various sources of delays: the absence of a default index, slower bootstrap, slower DDLs and INSERTs and generalized slower SELECT performance, but this particular bug is about latency spikes for simple SELECTs over very small tables that are not observed with the single binary.

To reproduce:

1. Clone `git@github.com:MaterializeInc/sqllogictest.git`
2. Run  
```
 target/release/sqllogictest ~/sqllogictest/test/random/select/slt_good_0.test --postgres-url=postgresql://postgres:postgres@localhost -vvv --auto-index-tables | ts -i  "%.T" > timings.platform
```

This records roughly the execution time of each query in a file. 

3. Find all queries that take more than 100ms to run:
```
grep -F -v '0.0' timings.platform  | grep SELECT
```

This gives us about 43 queries, whose total execution time accounts for about 1/3rd of the total SLT running time. Of those, there are several queries taking >500ms and one taking more than 1s. That query is in no way special, is in the middle of the file, and takes no time at all with the single binary.

The number of delayed queries is much larger than the total number of back-off related log lines that are also seen in the SLT output. Also, the slowest queries take more than 1 second and yet there are no "retrying in 1s" messages in the log. 

Contrast this with the timing from the same SLT file when run against single binary Mz:

```
~/materialize-bisect/target/release/sqllogictest ~/sqllogictest/test/random/select/slt_good_0.test  -vvv | ts -i  "%.T" > timings.single-binary
```
There will be no queries taking more than 100ms in this trace.

**Comment by antiguru** [comment]
I'll take a look into this; judging from the description this is not a blocker for other work so I'll scope it as a P2.

**Comment by antiguru** [comment]
Running the test with the wall clock ticking down my neck, it's obvious that we have a hiccup exactly at 1s intervals. Adding debug logging to `mz_persist_client` indicates that the hiccup occurs synchronized with persist's `downgrade_sice` and `gc_and_truncate`, as indicated by the following excerpt:

```
00:00:00.011127 2022-08-05T08:33:48.997225Z DEBUG downgrade_since{shard=sa5876fee-eaee-4373-b6ab-e83ca93186ab}:apply_unbatched_cmd::cas{payload_len=540}: mz_persist_client::r#impl::machine: external operation apply_unbatched_cmd::cas succeeded after failing at least once
00:00:00.000042 2022-08-05T08:33:48.997247Z DEBUG downgrade_since{shard=sa5876fee-eaee-4373-b6ab-e83ca93186ab}: mz_persist_client::r#impl::machine: apply_unbatched_cmd sa5876fee-eaee-4373-b6ab-e83ca93186ab downgrade_since lost the CaS race, retrying: v89 vs Some(SeqNo(90))
00:00:00.026300 2022-08-05T08:33:49.023562Z DEBUG downgrade_since{shard=scec7582a-0df1-43c3-bffd-872d57cf24bf}: mz_persist_client::r#impl::machine: apply_unbatched_cmd scec7582a-0df1-43c3-bffd-872d57cf24bf downgrade_since lost the CaS race, retrying: v79 vs Some(SeqNo(80))
00:00:00.142391 2022-08-05T08:33:49.165939Z DEBUG downgrade_since{shard=s91281fa8-b5a7-4e7b-9765-2365b2ce96f0}: mz_persist_client::r#impl::machine: apply_unbatched_cmd s91281fa8-b5a7-4e7b-9765-2365b2ce96f0 downgrade_since lost the CaS race, retrying: v96 vs Some(SeqNo(97))
00:00:00.004613 2022-08-05T08:33:49.170556Z DEBUG downgrade_since{shard=s762781d9-ed8f-45cb-9776-2861ce689e80}: mz_persist_client::r#impl::machine: apply_unbatched_cmd s762781d9-ed8f-45cb-9776-2861ce689e80 downgrade_since lost the CaS race, retrying: v97 vs Some(SeqNo(98))
00:00:00.000272 2022-08-05T08:33:49.170855Z DEBUG downgrade_since{shard=s60ec5652-c278-434a-afc3-13364bbd0562}: mz_persist_client::r#impl::machine: apply_unbatched_cmd s60ec5652-c278-434a-afc3-13364bbd0562 downgrade_since lost the CaS race, retrying: v97 vs Some(SeqNo(98))
0
```

Note the call to `downgrade_sice` which is more than 100ms after the last call. This doesn't proof that the delay is caused by persist, but I'd like to get someone's opinion on whether this is expected.

Command line:
```
MZ_LOG_FILTER=mz_persist_client=debug bin/sqllogictest --reset --release -- ~/dev/repos/sqllogictest/test/random/select/slt_good_0.test --postgres-url=postgresql://postgres:postgres@localhost -vvv --auto-index-tables | /usr/bin/ts -i  "%.T"
```

**Comment by antiguru** [comment]
@aljoscha Can you get someone to look into this to confirm or falsify my assumption that the delay is related to persist? Thank you!

One additional note: The hiccups are not caused by the actual queries, and adding an index doesn't change the behavior. Every time I run the test, a different set of queries show up with the large delay. This makes me believe it's likely a problem outside compute.

**Comment by aljoscha** [comment]
I asked @danhhz and/or @pH14 to quickly check if this is a persist problem. Based on that we can decide what to do.

**Comment by pH14** [comment]
@aljoscha this seems to be tied to the current `advance_local_inputs` behavior, which writes an empty batch + calls `downgrade_since` once a second on each table. The shorter we can make the roundtrip through persist for these advancements, the shorter the spike would be. I don't think I'd call this a problem in persist, the behavior is more an artifact of how the controllers and persist are currently built and glued together. Neither is doing something wrong, but their combined performance isn't well tuned for tables.


One observation with these advancements is that both the wrtier's `compare_and_append` and the reader's subsequent `downgrade_since` operations always retry, since in practice they alternate advancing the state. We could halve our roundtrips to consensus by having a way to push updates / share state between the read and write handles.

**Comment by aljoscha** [comment]
Hmm yes, I once referred to the retry pattern as "cas ping-ponging". :see_no_evil:

**Comment by aljoscha** [comment]
I'm still wondering why that spike shows up in the queries: both advancing and downgrading happen in separate tasks right now, so they should not block coordinator work. Hypothesis: with `SET transaction_isolation = 'strict serializable'
` we have to wait for those downgrade calls to go through. So with `SET transaction_isolation = 'serializable'` we might see an improvement.

I'm calling it a day for now, but I'll look at this again tomorrow with fresh eyes.

**Comment by mjibson** [comment]
https://github.com/MaterializeInc/materialize/pull/13967 is a PR out that will probably improve this. "strict serializable is slow, downgrade from strict to make things fast" is an understood result in adapter due to the correctness goals, and we're trying to make it faster by default now.

**Comment by pH14** [comment]
I've also been wondering - do tables need to have `downgrade_since`  called immediately after each `advance_local_inputs`, or could those calls be staggered from one another? e.g. calling `maybe_downgrade_since` would automatically rate limit their calls and reduce time spent in persist consensus.

**Comment by jkosh44** [comment]
@pH14 are you referring to #13967 or the current behavior? I'm not exactly familiar with the what will trigger a `downgrade_since` call. The Coordinator never needs to force compaction on tables, it just periodically updates it's read holds as an indication that it will no longer read at a certain time, so it's ok for that time to be compacted. So it sounds like using `maybe_downgrade_since` would be fine.

**Comment by aljoscha** [comment]
Just because I tried: when you run the tests with `SET transaction_isolation = 'serializable'` these slt tests fail.

**Comment by philip-stoev** [comment]
How do they fail exactly?

**Comment by aljoscha** [comment]
With things like
```
00:00:00.000114     INSERT INTO tab0 VALUES(89,91,82)
00:00:00.036554     INSERT INTO tab0 VALUES(35,97,1)
00:00:00.015608     INSERT INTO tab0 VALUES(24,86,33)
00:00:00.017627     INSERT INTO tab1 VALUES(64,10,57)
00:00:00.017020     INSERT INTO tab1 VALUES(3,26,54)
00:00:00.033883     INSERT INTO tab1 VALUES(80,13,96)
00:00:00.016787     INSERT INTO tab2 VALUES(7,31,27)
00:00:00.018159     INSERT INTO tab2 VALUES(79,17,38)
00:00:00.017124     INSERT INTO tab2 VALUES(78,59,26)
00:00:00.017919     SELECT ALL * FROM tab0 cor0 CROSS JOIN tab2 AS cor1
00:00:00.002687     OutputFailure:/home/aljoscha/Dev/sqllogictest/test/random/select/slt_good_0.test:43
00:00:00.000034             expected: Hashed { num_values: 54, md5: "018801f36b33d2fe82cb95918ba502d6" }
00:00:00.000011             actually: Hashed { num_values: 0, md5: "d41d8cd98f00b204e9800998ecf8427e" }
00:00:00.000008             actual raw: []
00:00:00.000008     ----

```

**Comment by philip-stoev** [comment]
so the query returns no rows with `serializable` ? That is not good

**Comment by aljoscha** [comment]
I mean it is correct. If you try for a bit more it will _eventually_ return the correct result.

Side note: I don't know much about how it should behave with `serializable` so I'm quite possibly wrong about this being correct. Paging @jkosh44.

**Comment by philip-stoev** [comment]
oh so tables are now hm "eventually consistent" under `serializable` TIL

**Comment by jkosh44** [comment]
This is correct under serializable, maybe undesirable, but correct.

**Comment by jkosh44** [comment]
I just pushed a commit that should have sped up reads under strict serializability (https://github.com/MaterializeInc/materialize/pull/13967). I'm not sure if it fixed this, but it might be worth retesting.

**Comment by mjibson** [comment]
I'm going to test main in the cloud testing session today, which will include this.

**Comment by nmeagan11** [comment]
Is this issue still outstanding?

**Comment by benesch** [comment]
Yes, definitely. You can easily observe this by connecting to a Materialize Cloud instance and running `SELECT` over and over again. You'll see highly variable latencies. As likely to be an adapter problem as a storage problem, though.

**Comment by benesch** [comment]
I added this to the surfaces team project board too.

**Comment by ggnall** [comment]
@chaas @mjibson should we include this in #15811

**Comment by mjibson** [comment]
Can we still repro it? Many perf improvements in the last 2 months.

**Comment by jkosh44** [comment]
@ggnall 
- Is that a table or source?
- If you switch to Serializable do the latencies all drop? (`SET TRANSACTION_ISOLATION TO serializable;`)

**Comment by ggnall** [comment]
@jkosh44 that was a materialized view. I've tested again with `serializable` on both a table:
```
materialize=> select count(*) from stuff;
 count
-------
     2
(1 row)

Time: 156.434 ms
materialize=> select count(*) from stuff;
 count
-------
     2
(1 row)

Time: 94.124 ms
materialize=> select count(*) from stuff;
 count
-------
     2
(1 row)

Time: 151.479 ms
materialize=> select count(*) from stuff;
 count
-------
     2
(1 row)

Time: 90.819 ms
materialize=> select count(*) from stuff;
 count
-------
     2
(1 row)

Time: 123.777 ms
materialize=> select count(*) from stuff;
 count
-------
     2
(1 row)

Time: 358.322 ms
```
And a source directly:
```
materialize=> select 1 from site_events limit 1;
 ?column?
----------
        1
(1 row)

Time: 2779.349 ms (00:02.779)
materialize=> select 1 from site_events limit 1;
 ?column?
----------
        1
(1 row)

Time: 2599.880 ms (00:02.600)
materialize=> select 1 from site_events limit 1;
 ?column?
----------
        1
(1 row)

Time: 2524.972 ms (00:02.525)
materialize=> select 1 from site_events limit 1;
 ?column?
----------
        1
(1 row)
```

**Comment by benesch** [comment]
Materialized view or indexed view?

**Comment by jkosh44** [comment]
> Materialized view or indexed view?

I guess both would be useful, but Materialized view would be more useful since that's where the variations were seen originally in Strict Serializable.

**Comment by ggnall** [comment]
Here is for a materialized view.

With Strict Serializability:
```
materialize=> select count (*) from mz_site_events;
 count 
-------
   245
(1 row)

Time: 373.679 ms
materialize=> select count (*) from mz_site_events;
 count 
-------
   245
(1 row)

Time: 487.627 ms
materialize=> select count (*) from mz_site_events;
 count 
-------
   245
(1 row)

Time: 322.967 ms
materialize=> select count (*) from mz_site_events;
 count 
-------
   245
(1 row)

Time: 805.272 ms
```

With Serializable:
```
materialize=> set transaction_isolation to 'serializable';
SET
Time: 22.514 ms
materialize=> select count (*) from mz_site_events;
 count 
-------
   245
(1 row)

Time: 482.366 ms
materialize=> select count (*) from mz_site_events;
 count 
-------
   245
(1 row)

Time: 242.721 ms
materialize=> select count (*) from mz_site_events;
 count 
-------
   245
(1 row)

Time: 387.342 ms
materialize=> select count (*) from mz_site_events;
 count 
-------
   245
(1 row)

Time: 456.190 ms
```

**Comment by jkosh44** [comment]
Interesting, it doesn't look like you were able to reproduce the high variations in strict serializable with materialized views.

If you are experiencing slow strict serializable queries and switching to serializable immediately makes them faster, then I'd pretty confidently say that the slowness is due to timestamp selection. In that case there wouldn't be much we could do to speed up queries except:
- Introduce a less consistent, faster isolation level.
- Do some form of https://github.com/MaterializeInc/materialize/issues/13778.
- Speed up propagation delay of Materialized views.
- Trade off source freshness for read latency.

I think the only free optimization left for timestamp selection in strict serializable is when querying a materialized view/index that includes only tables, has no temporal filters, and hasn't had any writes. Though this is probably a rare enough case right now that it's not worth implementing. Every other optimization requires trading off something else.

**Comment by benesch** [comment]
Is this still an issue? We haven't been getting many complaints about latency spikes when reading from an index lately.

**Comment by philip-stoev** [comment]
Latencies are now stable across the board (<50ms and no spikes), with and without a view, with and without a materialization , with and without an index, when measured via `\timing on` of the `psql` client.

The original reproduction scenario that is based on sqllogic continues to report spikes:

```
$ grep -F -v '0.0' timings.platform  | grep SELECT | cut -d" " -f 1 | awk -F: '{ print ($1 * 3600) + ($2 * 60) + $3 }'  | ministat
x <stdin>
+----------------------------------------------------------------------------------------------------------------------------------+
|    x     x                                                                                                                       |
|    x     x                                                                                                                       |
|    x     x                                                                                                                       |
|    x   x x        x                                                                                                              |
|  x x  xx xxx      x                                                                                                              |
| xx x  xx xxxx     x                                                                                                              |
| xx xx xx xxxx     x  x                                                                                                           |
|xxxxxxxxxxxxxx    xx  x x                                                                                                         |
|xxxxxxxxxxxxxx x xxxx x x                                                                                                         |
|xxxxxxxxxxxxxx xxxxxx x x                                                                                                         |
|xxxxxxxxxxxxxx xxxxxxxx x                                                                                                         |
|xxxxxxxxxxxxxxxxxxxxxxxxxxx                                                                                                       |
|xxxxxxxxxxxxxxxxxxxxxxxxxxxxx                                                                                                     |
|xxxxxxxxxxxxxxxxxxxxxxxxxxxxx                                                                                                     |
|xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx             x  x               x                                                      x           x|
||__________M_A_____________|                                                                                                      |
+----------------------------------------------------------------------------------------------------------------------------------+
    N           Min           Max        Median           Avg        Stddev
x 244      0.101829       1.99798      0.268871    0.29762046    0.19631164
```

But this must be a sqllogic-specific or an stdout-output-timestamping problem. So, I am closing this ticket as it has outlived its usefulness.
