### ISSUE TITLE
sql: support WebSockets via `api/sql`

### ISSUE THREAD

**Issue by sploiselle** [MaterializeInc/materialize#14068]
### Feature request

@necaris drafted #11833 to demo how we might support a WebSocket-based API to support e.g. `TAIL`. This issue just tracks that this work ought to be done.

**Comment by necaris** [comment]
Also chiming in to say I would love to help with this!

**Comment by sploiselle** [comment]
The specification of this implementation is in https://github.com/MaterializeInc/materialize/blob/main/doc/developer/platform/ux.md; search for `websocket`.

A few random notes:
- This implementation will likely need to live in `src/environmentd/src/http.rs`
- You can repurpose the vast majority of `AuthedClient::execute_stmt` to perform the actual execution of the statement. I think the most natural thing to do here is to change `execute_stmt` to return an `ExecuteResponse` instead of a `SimpleResult`, and then create new functions that handle `ExecuteResponses` appropriately for which API is getting called.
- This will likely need to perform a similar `check_prohibited_stmts`-type call; this takes statements into sets of plans, and those sets of plans into sets of execute responses. Glad to go into more depth about this, or you can take it on faith that it does the right thing.
- When generating `Ok` responses, you'll need to invent some of the OK tag values in your implementation, namely anything that generates a `SendingRows`, but also `Tailing`. Chatted with Matt about this and that's a-ok

cc @necaris

**Comment by benesch** [comment]
Mentioned to @RobinClowers but mentioning here too for posterity: we can develop this API as /api/experimental/sql, or something like that. Then we can use it in the web UI and validate its design before committing to it as part of the stable interface.

**Comment by chaas** [comment]
This is done and working!
Added https://github.com/MaterializeInc/materialize/issues/17145 to track moving it from experimental to part of our stable interface.
