### ISSUE TITLE
Determine/document memory bound guarantees for consolidation in Persist.

### ISSUE THREAD

**Issue by umanwizard** [MaterializeInc/materialize#14086]
### Feature request

See discussion in Slack beginning [here](https://materializeinc.slack.com/archives/C01CFKM1QRF/p1659063332027139).

In order to access the consolidated state of a persist shard at a given timestamp, consolidation is necessary. However, Persist does not guarantee anything about "how uncompacted" nor "how unconsolidated" data will be, nor anything about the order updates will be returned in.

For example, imagine a shard with a large number of updates that consolidate down to a small number of values. If all the `-1`s are emitted before all the `+1`s, consolidation will require memory proportional to the large number of updates.

**Comment by benesch** [comment]
Superseded by #16607.
