### ISSUE TITLE
Support logging sources in our builtin migration infrastructure

### ISSUE THREAD

**Issue by bkirwi** [MaterializeInc/materialize#14125]
### Feature request

Our builtin migraiton tooling [does not currently support logging sources](https://github.com/MaterializeInc/materialize/blob/d23b1a035d040ba1707b033e48640a763e1d96cb/src/adapter/src/catalog.rs#L2229-L2232).

This is a known TODO, but it's a bit more important than we realized. When we ran into this limitation as part of #14022, we believed that we should be able to work around it using some of our other migration tooling, but this turned out to not be the case.

**Comment by bkirwi** [comment]
@jkosh44 helped with a lot of the investigation here... any other detail to add on this one? (Feel free to edit!)

**Comment by jkosh44** [comment]
The biggest question for me was how to drop and recreate an introspection source in an already running COMPUTE cluster? I don't think we have the APIs needed for this.

It might also be the case that we need to special case introspection indexes, STORAGE objects, and views, though I'm not sure.

**Comment by bkirwi** [comment]
Dropping a link to the related issue: https://github.com/MaterializeInc/materialize/issues/14126

**Comment by parker-timmerman** [comment]
@jkosh44 it seems like this is already supported after you merged #15976? Off the top of your head is there any work that's still required here?

**Comment by jkosh44** [comment]
> @jkosh44 it seems like this is already supported after you merged #15976? Off the top of your head is there any work that's still required here?

No I think this can be closed.
