### ISSUE TITLE
PG Wire Tests Flaky with OS error

### ISSUE THREAD

**Issue by chaas** [MaterializeInc/materialize#14160]
### What version of Materialize are you using?

20220808 (commit 521a83ebf47b995f3600b9a756d3efa7c41bcb4)

### How did you install Materialize?

Docker image

### What is the issue?

Test failed with 
```
ERROR mz_adapter::coord::read_policy: Storage collection User(1) has read frontier Antichain { elements: [1660084246357] } not less-equal to read_hold.time: 1660084246039
```
followed by
```
thread 'test_pgtest' panicked at 'called `Result::unwrap()` on an `Err` value: Resource temporarily unavailable (os error 11): waiting for ReadyForQuery, saw []
```

Link to test run: https://buildkite.com/materialize/tests/builds/39205#018284a5-c940-4703-8e21-0f39c1d1add3

Note - a potentially similar issue with this test suite occurred in May. See slack discussion https://materializeinc.slack.com/archives/CM7ATT65S/p1654015540567839. This PR to disable the tests was the result https://github.com/MaterializeInc/materialize/pull/12782.

**Comment by mjibson** [comment]
The antichain error here is probably not related because it appears all the time. The pgtest panic feels like it's a envd crash that we aren't printing the logs for.

**Comment by chaas** [comment]
Thanks @mjibson !
