### ISSUE TITLE
Coord: Removing objects from a timeline is done non-transactionally

### ISSUE THREAD

**Issue by jkosh44** [MaterializeInc/materialize#14194]
### What version of Materialize are you using?

`main`

### How did you install Materialize?

Built from source

### What is the issue?

In the coordinator when executing a `DROP` statement, we remove objects from their timelines before we know if the `DROP` has succeeded or failed.
https://github.com/MaterializeInc/materialize/blob/2b31ab8e07b488f6a2950f3b87f47c9647c80aa0/src/adapter/src/coord/ddl.rs#L141-L167
That means that we might remove the object from the timeline, without actually dropping it. To fix this we should wait until after `catalog.transact` is called to remove the objects from the timeline. We'll have to figure out which timelines to drop without actually removing the objects from them.

**Comment by uce** [comment]
@jkosh44 I'm removing the triage label and moving to the surfaces board (cc @chaas). Is the priority P2 still correct here?

**Comment by jkosh44** [comment]
> @jkosh44 I'm removing the triage label and moving to the surfaces board (cc @chaas). Is the priority P2 still correct here?

Yes I think P2 is correct. This is only possible to surface if a user is using non-realtime timelines. I don't think this applies to any current or near-future users.
