### ISSUE TITLE
[kafka sink] Move consistency info from sidecar topic to headers 

### ISSUE THREAD

**Issue by cjubb39** [MaterializeInc/materialize#14203]
As described in https://www.notion.so/materialize/Kafka-Sinks-9ba8f8c0ddc949d6b20a67a2558a7604, we want to move the consistency info from a sidecar kafka topic to kafka headers.  This was not part of in #14009 (which is just moving the actual execution from a comptued to storaged process and the associated framework -- and not adjusting the kafka impl at all).

**Comment by cjubb39** [comment]
cc @aljoscha

**Comment by aljoscha** [comment]
We decided not to do this one. See discussion in https://www.notion.so/materialize/Kafka-Sinks-9ba8f8c0ddc949d6b20a67a2558a7604 and https://github.com/MaterializeInc/materialize/issues/14267.

cc @bkirwi @nmeagan11
