### ISSUE TITLE
sql: CREATE SINK parsing needs significant refactor

### ISSUE THREAD

**Issue by sploiselle** [MaterializeInc/materialize#14206]
### What version of Materialize are you using?

v0.26.1-dev (8b9c797ea)

### How did you install Materialize?

Built from source

### What is the issue?

This is valid syntax for a `CREATE SINK` statement:

```sql
CREATE SINK foo FROM bar INTO KAFKA BROKER 'baz' TOPIC 'topic' WITH
```

This should be refactored before we make sinks broadly accessible again.

**Comment by sploiselle** [comment]
One of the complexities of sinks and sources is their amalgamation of a number of different components:
- Connection to external system (e.g. Kafka)
- Format of incoming data, which can require a connection to an external system (e.g. CSR)
- Envelope to apply semantics to incoming data (e.g. Debezium)

On top of this, we also have additional options we might want to apply to e.g. the sink itself (i.e. `snapshot`).

Right now, `SINK` parsing:
- Requires a connection
- Allows an optional format that errors if not provided
- Allows an optional envelope that has a default value
- Uses non-standard `WITH` syntax for snapshot (i.e. disabled with `WITHOUT`, not `(OPTION = false)`

# Proposal

## Components
I propose we make the instead change `SINK` parsing to require an explicit definition of all of these components.

The only behavior this meaningfully impacts is requiring users to type `ENVELOPE DEBEZIUM`--to make this slightly less onerous we could also add an option, `ENVELOPE DEFAULT` that we could apply semantics to during planning (changing the default would require writing a migration, but ¯\\\_(ツ)\_/¯).

## Options
Right now, the parser breaks its abstraction barrier and semanticizes the absence of `WITH(OUT)? SNAPSHOT` to default to true, in addition to using non-standard syntax.

Instead, I recommend moving `SNAPSHOT` into a `WITH` option block at the end of `CREATE SINK` parsing. This lets us use the existing `WITH` option machinery, and makes this option consistent with the reset of Materialize.

## Misc.
Not making the above changes forces us into an awkward position w/r/t enabling config options on CSR `CONNECTION`s; they cannot specify their own `WITH` block without running into ambiguity with the `WITH SNAPSHOT` option, or any `WITH` option on `CREATE SINK`.

Materially, this impacts the `AVRO KEY FULLNAME` and `AVRO VALUE FULLNAME` options, which must currently reside as options on the `SINK`'s Kafka Connection, irrespective of the format it uses. This is awkward and not really semantically appropriate.

@benesch @ggnall @nmeagan11 @chaas  -- can I solicit feedback from y'all on this proposal?

**Comment by nmeagan11** [comment]
Overall, this SGTM! A couple comments:

> we could also add an option, `ENVELOPE DEFAULT` that we could apply semantics to during planning

I don't think we should require the user to explicitly type `ENVELOPE DEFAULT`. I recognize that's the opposite of the statement above regarding requiring explicit definitions, but it's in-line with what we currently do for sources (i.e. I don't have to type `ENVELOPE NONE`).

> I recommend moving `SNAPSHOT` into a `WITH` option block at the end of `CREATE SINK` parsing.

+1 !

**Comment by sploiselle** [comment]
@nmeagan11 Then maybe we should change it for sources. The implicit default features make some features unparseable, i.e. if we don't require an `ENVELOPE`, we cannot add `WITH` options to `CONFLUENT SCHEMA REGISTRY CONNECTION`s because the omission means we're no longer LL1--we don't know if the subsequent `WITH` is an option being applied to `FORMAT` or to `CREATE SINK`.

I guess another option is to move all of the `WITH` options into the terminal position in the statement. If we take this approach, which makes me a little queasy with the amount of typing it'd require, I'd suggest we make this a sweeping change so as to be rid of this complexity once and for all.

**Comment by guswynn** [comment]
@sploiselle what language is required to not require and ENVELOPE but still be able to parse `WITH` options to CSR? Is it just moving to LL2 or is it worse?

**Comment by sploiselle** [comment]
In the current code, I guess, it's LL3, but it's more rightly LL <max depth of common prefix of options> + 3. That code is challenging to maintain and buggy because you have to perform all sorts of gymnastics to do the checking, in addition to rewinding the parsing. I don't think the ergonomics of letting folks skimp on 2 keywrods is worth the inordinate complexity this pushes into the parser.

**Comment by nmeagan11** [comment]
> Then maybe we should change it for sources.

I'm onboard with this!

**Comment by ggnall** [comment]
LGTM. I would prefer consistency of experience across CREATE SINK and CREATE SOURCE and to get away from hidden defaults.
>Then maybe we should change it for sources. The implicit default features make some features unparseable,

**Comment by benesch** [comment]
Only the top level should use `WITH`! Other clauses like `FORMAT` and `ENVELOPE` that need to take options should just take them as parentheticals. I just fixed this for `CREATE SOURCE`, e.g.:

```
CREATE SOURCE crobat FROM KAFKA BROKER 'zubat' TOPIC 'hoothoot' FORMAT AVRO USING SCHEMA 'string' (CONFLUENT WIRE FORMAT = false) ENVELOPE NONE
```

I believe that neatly solves the ambiguity; if you see a `WITH` you _know_ that it's the final `WITH`, and not some intermerdiate `WITH`. It also avoids requiring `ENVELOPE DEFAULT`. 

Alos, huge +1 on moving `SNAPSHOT` into this final `WITH` block.

**Comment by sploiselle** [comment]
SGTM, @benesch

**Comment by sploiselle** [comment]
Just pinging folks here that #14539 is ready for review and green in CI.
