### ISSUE TITLE
[sinks] Move sink storage initialization into async task

### ISSUE THREAD

**Issue by cjubb39** [MaterializeInc/materialize#14220]
Followup from #14009.  Maybe `create_storage_export` (the function that spins up a new storaged, etc) ought to be in an async task -- maybe the same one where we create the kafka connection?

**Comment by cjubb39** [comment]
cc @aljoscha

**Comment by bkirwi** [comment]
For future reference, the specific comment that inspired this: https://github.com/MaterializeInc/materialize/pull/14009#discussion_r944505053

**Comment by cjubb39** [comment]
revert in #15176
