### ISSUE TITLE
[sinks] More helpful error message if persisted collection doesn't exist

### ISSUE THREAD

**Issue by cjubb39** [MaterializeInc/materialize#14221]
Currently we use `StorageError::IdentifierMissing` when looking up the from_collection to signify that you're trying to create a sink based on something that isn't a persisted collection.  That prints as "collection identifier is not present" which isn't super helpful to the user!

There are a few testdrive lines that have `contains:collection identifier is not present` that we'll want to update

**Comment by cjubb39** [comment]
cc @aljoscha

**Comment by bkirwi** [comment]
Fixed in #14283!
