### ISSUE TITLE
DEBEZIUM UPSERT deduplication fails with a large snapshot 

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#14236]
### What version of Materialize are you using?

510b6a9aa3da6253ca1f9773de9d27db9c07d57a

### How did you install Materialize?

Docker image

### What is the issue?

A test that kills and restarts the Postgres source database for a Debezium source works with smaller data volumes but fails with a larger snapshot in a way that indicates that dedupication did not properly kick in. Unlike #14211, here we:
- have ENVELOPE DEBEZIUM UPSERT
- do not modify the primary key.

**Comment by benesch** [comment]
Do you have reproduction instructions handy, Philip?

**Comment by philip-stoev** [comment]
I am on it. I filed a placeholder ticket in order to get a github number

**Comment by philip-stoev** [comment]
I am unable to reproduce this again, so I will close it until it becomes reproducible. Thank you.
