### ISSUE TITLE
persist read handles are not dropped when source/table is dropped

### ISSUE THREAD

**Issue by pH14** [MaterializeInc/materialize#14251]
### What version of Materialize are you using?

main

### How did you install Materialize?

Built from source

### What is the issue?

The storage controller heartbeats readers to keep them active, but will continue to do so even if the source or table has been dropped (`since` advanced to empty antichain):

https://github.com/MaterializeInc/materialize/blob/f9a4f2b63c5886a26979abd7b33f9629ea266622/src/storage/src/controller.rs#L1438-L1451

We should clean up these handles when the corresponding source/table has been dropped. Continuing to heartbeat can cause unbounded growth of the shard's consensus data

**Comment by aljoscha** [comment]
I _think_ we can drop handles in the `PersistWorker` when we notice that we're downgrading to the empty frontier.

**Comment by danhhz** [comment]
yeah, I think so too. we have to remain idempotent to a downgrade_since of empty antichain, so I think we actually have to replace the ReadHandle with an Option<ReadHandle> and then treat a none as a no-op for any downgrade_since. I have it mostly typed up locally but I'm working through a borrow checker error

**Comment by danhhz** [comment]
I'm still not sure what's going on with the borrow checker issue. Draft up at https://github.com/MaterializeInc/materialize/pull/14263

**Comment by pH14** [comment]
https://github.com/danhhz/materialize/commit/4a64df4f0cfa828bd993726f1db6c75b1f52dc6a should cover this for now, and we have a better long term fix in mind after
