### ISSUE TITLE
stash: Make stash data human-readable & accessible

### ISSUE THREAD

**Issue by chaas** [MaterializeInc/materialize#14264]
### Objective
Make stash data human-readable and accessible.
This will allow for easier debugging and is needed for billing.

### Solution
Either store stash data as JSON or build reader to map from protobuf to human-readable format (either JSON or protobuf text format https://developers.google.com/protocol-buffers/docs/text-format-spec).

Bonus: Ability to write sql queries against the data. This requires having read-only users & policies around data and account access.
Slack threads: https://materializeinc.slack.com/archives/CM7ATT65S/p1660657262291549 and https://materializeinc.slack.com/archives/CM7ATT65S/p1660661773609499

**Comment by necaris** [comment]
Note: per the [current design](https://www.notion.so/Billing-ce8515adc44847ef825cbcf99c15b319), this isn't a blocker for billing.
