### ISSUE TITLE
Storage controller should expose (introspection?) `GlobalId` and `ShardId` association

### ISSUE THREAD

**Issue by frankmcsherry** [MaterializeInc/materialize#14266]
### Feature request

The storage controller owns the creation of collections associated with `GlobalId` identifiers, and creates `persist` shards in response. This association is not published, which has complicated the debugging of various cross-cutting performance issues. It could be quick win to present this as a introspectable collection.

**Comment by benesch** [comment]
Would be very helpful with MaterializeInc/cloud#3726 too.

**Comment by danhhz** [comment]
I would also very much like this

**Comment by benesch** [comment]
We'll need to figure out what to call these system tables that are essentially entirely irrelevant for end users. There's nothing useful that an end user can do with a shard ID; it's pretty much only useful to Materialize engineers who are debugging.

One option is to name these tables something like `mz_debug_persist_shards`, and we can tell users that `mz_debug_*` is really only useful if support instructs you to look at it. Or we could go one step further, and restrict references to these tables to connections from the internal SQL port.

**Comment by pH14** [comment]
Not as familiar with the mechanics of exposing this type of data -- if we create a `BuiltinTable` for this data, what's the right way to propagate the mapping from the StorageController? The shard IDs are assigned in https://github.com/MaterializeInc/materialize/blob/181f1efeb262d27f7de7d449069f19d2b9b7d3ff/src/storage/src/controller.rs#L738-L747 should they be passed back to coord so they can be written into the catalog?

**Comment by benesch** [comment]
> should they be passed back to coord so they can be written into the catalog?

That's probably the least-lines-of-code-way, and would be my recommendation for what to do. It avoids needing to invent a new way to tick the upper forward when no changes have occurred to the shard. You may want to get @frankmcsherry's sign off on whether this an acceptable architectural decision though. 

IMO, in a perfect world, the persist shard backing the `mz_debug_persist_shard` table would _be_ the source of truth on the shard mapping, and the storage controller would just read out of that shard. I think that relies on `persist` being more of a source of truth than it is currently willing to be.

**Comment by frankmcsherry** [comment]
I think this association should already be part of the storage controller's durable state, right? Or .. is the catalog the source of truth on the `GlobalId -> ShardId` mapping? If it's the storage controller's state, I'd be tempted to have it be written by the storage controller, rather than rely on a user of the storage controller to write it for it.

**Comment by benesch** [comment]
> I think this association should already be part of the storage controller's durable state, right?

It is! It's written to the storage controller's stash. 

>  If it's the storage controller's state, I'd be tempted to have it be written by the storage controller, rather than rely on a user of the storage controller to write it for it.

I think that'd be nice too. The wrinkle is that, AFAICT, user-facing relation needs to function exactly like the system tables that the adapter already manages. I.e., it needs to have its upper frontier advanced periodically if there are no new writes. It seems likely to be real buggy to have two separate components in Materialize issuing these table downgrade commands. 

If the storage controller became responsible for ticking forward writes on all system tables, rather than the coordinator, it seems like that could be one way forward?

**Comment by frankmcsherry** [comment]
> If the storage controller became responsible for ticking forward writes on all system tables, rather than the coordinator, it seems like that could be one way forward?

I mean, the coordinator does ask the storage controller to do the writes, and the storage controller maintains all the persist write handles, and does the append calls and all that. The coordinator only understands `append(...)` on the controller, and doesn't have any other smarts about how things get written out.

I don't want to complicate things at the moment, but for sure in the future I think we'll want the storage controller to have a strong opinion on which global ids are bound to storage collections, and the coordinator just says "ah, is that so? I accept!".

**Comment by benesch** [comment]
Maybe easiest to get on a huddle whenever right before someone gears up to tackle this? I feel like I am not explaining things clearly over text!

**Comment by benesch** [comment]
> We'll need to figure out what to call these system tables that are essentially entirely irrelevant for end users. There's nothing useful that an end user can do with a shard ID; it's pretty much only useful to Materialize engineers who are debugging.
> 
> One option is to name these tables something like `mz_debug_persist_shards`, and we can tell users that `mz_debug_*` is really only useful if support instructs you to look at it. Or we could go one step further, and restrict references to these tables to connections from the internal SQL port.

I'm coming around to the idea of exposing these to users as a top-level concept. Maybe:

  * `mz_storage_shards`, with columns `object_id` and `shard_id`
  * `mz_storage_shard_size`, with columns `shard_id`, `size_bytes`, and `collection_timestamp`

Still an open question as to how to actually get the `object_id` -> `shard_id` mapping from the storage controller stash into `mz_storage_shards`. @sploiselle, @frankmcsherry, and I will try to sync up tomorrow.

**Comment by aljoscha** [comment]
Should `mz_storage_shards` also have a column `type` (name TBD) that says if this is the data shard, or remap shard, etc? This would make `(object_id, type)` a unique key and it seems helpful to know what the shard is used for.

**Comment by frankmcsherry** [comment]
It has a bit of a smell to jam a bunch of different shards associated with one id. Maybe that ship has sailed, but a reclocking collection, for example, seems like it should just have a different id, rather than sharing the same id but having some other way to access it. 

I'm not sure how the postgres "multi sources" are working out, but it seems like a natural thing is to have a "source" (with an id) publish multiple collections (also with their own ids). Data and reclocking seem like natural "multiple collections" for a source that needs to make reclocking information durable in addition to its data.

**Comment by benesch** [comment]
> It has a bit of a smell to jam a bunch of different shards associated with one id. Maybe that ship has sailed, but a reclocking collection, for example, seems like it should just have a different id, rather than sharing the same id but having some other way to access it.

It has not sailed! But the thing that will be awkward about assigning a distinct global ID to the data shard and the remap shard for each source is that the adapter is (at present) in charge of assigning global IDs. You'd end up with an ugly coupling between the adapter and the storage controller, where the adapter has to present the storage controller with exactly the right number of global IDs. This all works itself out when the storage controller becomes the source of truth on what sources exists, but I'm not sure how far we are away from that reality.

The solution I proposed to @sploiselle for now: just don't emit rows for reclocking collections yet. We can tackle that as part of making the reclocking collection a queryable relation.

**Comment by benesch** [comment]
After discussion with @frankmcsherry on Slack ([link](https://materializeinc.slack.com/archives/C01CFKM1QRF/p1663594776875709)), here's the new proposal:

  * Add a table named `mz_internal_storage_shards` with two columns: `shard_id` and `object_id`. We expect this mapping to be 1:1, but we leave the door open to future extensions. We only emit mappings for data shards to start. We'll figure out what to do with the reclocking shards when we tackle #12867.
  * Rename `mz_storage_usage` to `mz_internal_storage_usage`. Store usage information by `shard_id`, exactly as `persist` gives it to us.
  * Add a view named `mz_storage_usage` which joins `mz_internal_storage_shards` with `mz_internal_storage_usage` to expose storage usage by `object_id`. If persist shards and object IDs ever become many-to-one, we can adjust the view definition accordingly to avoid breaking users.

I propose that any tables whose name starts with `mz_internal` get marked as "unstable" (https://github.com/MaterializeInc/materialize/issues/14724) so that we can evolve their schema without worrying about breaking users views.

**Comment by danhhz** [comment]
dumb Q: the slack discussions have been assuming that we want the relocking remap shard to have its own globalid, but I haven't seen it explained why we want that? (not a disagreement, it's just not obvious to me)

also, relatedly, I'm curious how we want to model "internal" source ingestion shards here. the example that comes to mind is upsert evelope state, but for that we do clever things to reuse the output data shard. so perhaps the answer is we don't have "internal" source ingestions shards

**Comment by aljoscha** [comment]
> dumb Q: the slack discussions have been assuming that we want the relocking remap shard to have its own globalid, but I haven't seen it explained why we want that? (not a disagreement, it's just not obvious to me)

It's because we eventually want to expose these to users: https://github.com/MaterializeInc/materialize/issues/11908

> also, relatedly, I'm curious how we want to model "internal" source ingestion shards here. the example that comes to mind is upsert evelope state, but for that we do clever things to reuse the output data shard. so perhaps the answer is we don't have "internal" source ingestions shards

I think we'll have to think about how to expose them when we add them (internal shards), yes. 🙈

**Comment by sploiselle** [comment]
There's a design doc to support this in [Notion](https://www.notion.so/materialize/Storage-Collections-36014b5aa81d4637b9a7625955463a1f)
