### ISSUE TITLE
sources hang with no error if storaged uses --workers > 1

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#14273]
### What version of Materialize are you using?

e852e357c23043850cb235258048fd998079d664

### How did you install Materialize?

Docker image

### What is the issue?

If a storaged is started with --workers 2 , any attempts to select from a source will hang. The log has the stuff printed below.

To reproduce, clone https://github.com/MaterializeInc/materialize/pull/14272 and then run

```
bin/mzcompose --find testdrive run default testdrive.td
```

It works if `--workers 1` is passed to storaged:

```
bin/mzcompose --find testdrive run default --workers 1 testdrive.td
```

### Relevant log output

```source
compute-cluster-1-replica-1: 2022-08-17T08:59:20.334024Z  INFO mz_persist_client::r#impl::machine: snapshot s56d9b374-b447-4d42-ac9c-38fbdf380b12 as of Antichain { elements: [1660726744281] } not yet available for upper Antichain { elements: [1660726741001] } retrying in 16s
compute-cluster-1-replica-1: 2022-08-17T08:59:34.826653Z  INFO mz_persist_client::r#impl::machine: snapshot s56d9b374-b447-4d42-ac9c-38fbdf380b12 as of Antichain { elements: [1660726744281] } not yet available for upper Antichain { elements: [1660726741001] } retrying in 16s
```

**Comment by aljoscha** [comment]
I may be running into a similar thing with my work on the distributed `persist_sink`, where Zippy tests hang because data never becomes available. Still investigating, though.

**Comment by aljoscha** [comment]
@philip-stoev After https://github.com/MaterializeInc/materialize/pull/14355 this should just work! If you could maybe quickly confirm and then close this issue, that would be sweet! 🙏 

Also related: https://github.com/MaterializeInc/materialize/pull/14249

**Comment by aljoscha** [comment]
@philip-stoev gentle ping

**Comment by philip-stoev** [comment]
Now running a CI build with storaged workers 4 ...

**Comment by philip-stoev** [comment]
@aljoscha Unfrotunately a CI run where everyting is hard-coded to use 4 workers did not go well:

https://buildkite.com/materialize/tests/builds/41124#01831cb0-9c30-4ab9-b799-0cb9128e1d83

I did not check all the failures but the following seems to happen:

- data is ingested multiple times
- `platform-checks-materialized-1      | thread 'timely:work-2' panicked at 'cannot downgrade in reclock: DowngradeError(())', src/storage/src/source/source_reader_pipeline.rs:941:26`
- `platform-checks-materialized-1      | thread 'timely:work-2' panicked at 'The upsert state should have exactly one value per key', src/storage/src/render/upsert.rs:381:thread 'timely:work-3' panicked at 'The upsert state should have exactly one value per key', src/storage/src/render/upsert.rs:381:37`
- deadline has elapsed

The checks + restart storaged log contains several hundred individal panics...

Would you like individual follow-up ticket for all of those?

**Comment by aljoscha** [comment]
well... that's not good! I'll poke around a  bit locally to see if it's an obvious fix, but if that's not fruitful we should open an issue.

**Comment by philip-stoev** [comment]
@aljoscha please advise how would you like to move this forward. The multiple data ingested issue in particular would be a major bug, so I do not want to lose sight of it.

**Comment by aljoscha** [comment]
I was slowed down because of the offsite but I need to pick this up again. I'll try and fix this today and then report back what we should do if I don't manage to do it.
