### ISSUE TITLE
storage: PubNub connection

### ISSUE THREAD

**Issue by sploiselle** [MaterializeInc/materialize#14294]
### Feature request

We want to move to a world where we require a `CONNECTION` for all external systems. We have documentation around supporting PubNub, so if we plan to support it on platform, it should have a `CONNECTION` created for it.

**Comment by sploiselle** [comment]
When creating this `CONNECTION`, we should also mandate its use in sources; should be a small additional amount of work giving that they aren't widely used intests.

**Comment by benesch** [comment]
We removed PubNub sources, so nothing more to do here! https://github.com/MaterializeInc/materialize/commit/64d6f9a0f11c6cb1a088623245a9cfc6bbd2fd2f
