### ISSUE TITLE
update mz_peek_durations.duration_ns column

### ISSUE THREAD

**Issue by JLDLaughlin** [MaterializeInc/materialize#14312]
## What's wrong?
From @benesch:`mz_peek_durations.duration_ns` includes the units in the column name when nothing else does. Maybe ought to be an interval type?

## What should we do?
1. Rename `mz_peek_durations.duration_ns` to `mz_peek_durations.duration`.
2. Optionally update the column type from `bigint` to `interval`.

**Comment by JLDLaughlin** [comment]
@morsapaes or @sjwiesman - do you have a preference for `bigint` or `interval` here?

**Comment by morsapaes** [comment]
I...don't have a real opinion here, though it seems like this is also true for `mz_scheduling_elapsed.elapsed_ns` and `mz_scheduling_histogram.duration_ns`. 

From a quick look around, could changing the type to `interval` just make it less practical to put together this kind of troubleshooting query ([source](https://materializeinc.slack.com/archives/C02LJ9EJP9S/p1656451718397909))?

```sql
select
     mse.id,
     dod.name,
     mse.worker,
     elapsed_ns,
     avg_ns,
     elapsed_ns/avg_ns as ratio
 from
     mz_scheduling_elapsed mse,
     avg_elapsed_by_id aebi,
     mz_dataflow_operator_dataflows dod
 where
     mse.id = aebi.id and
     mse.elapsed_ns > 2 * aebi.avg_ns and
     mse.id = dod.id and
     mse.worker = dod.worker
     and dod.name like 'Dataflow%'
 order by ratio desc;
```

**Comment by frankmcsherry** [comment]
Fwiw, our `INTERVAL` type doesn't seem to support nanosecond precision (just down to microseconds).

**Comment by benesch** [comment]
> Fwiw, our INTERVAL type doesn't seem to support nanosecond precision (just down to microseconds).

Talked to Frank on Slack. Proposal is to split this into two views: one with the raw nanoseconds and one without. Perhaps something like:

  * `mz_raw_scheduling_histogram` (with `duration_ns` as `bigint`)
  * `mz_scheduling_histogram` (with `duration` as `interval`)

**Comment by chaas** [comment]
This original ticket was about `mz_peek_durations`, not `mz_scheduling_histogram` - should I split both of them into two views?
For that one I can do:
* `mz_raw_peek_duration_histogram`
* `mz_peek_duration_histogram`

**Comment by chaas** [comment]
And now that I think about it more, should it really be `mz_scheduling_histogram` or `mz_operator_duration_histogram`?

**Comment by vmarcos** [comment]
> This original ticket was about `mz_peek_durations`, not `mz_scheduling_histogram` - should I split both of them into two views? For that one I can do:
> 
> * `mz_raw_peek_duration_histogram`
> * `mz_peek_duration_histogram`
> 
> Should it be single or plural on `duration` - eg `mz_peek_durations_histogram` or `mz_peek_duration_histogram`
> 
> @benesch

Since we are referring to introspection sources capturing wall-clock time histograms, you will probably find the same problem in `mz_worker_compute_delays`.

**Comment by benesch** [comment]
Ah, I see, sometimes we use `histogram` in the name and sometimes we don't. I think it's a little cleaner to move in the direction of never including `histogram` in the name.

  * `mz_worker_compute_delays`
  * `mz_peek_durations`
  * `mz_compute_operator_durations`

**Comment by chaas** [comment]
Also, if we're going to make two tables for each, eg `mz_raw_worker_compute_delays` (delay_ns as bigint) and `mz_worker_compute_delays` (delay as interval), do we want them both to be builtin logs, such that we get the cluster prefixing, eg `mz_worker_compute_delays_1`? The alternative would be just creating a view for the delay as interval table, but it would only return data for the current cluster.

**Comment by benesch** [comment]
> Also, if we're going to make two tables for each, eg `mz_raw_worker_compute_delays` (delay_ns as bigint) and `mz_worker_compute_delays` (delay as interval), do we want them both to be builtin logs, such that we get the cluster suffixing, eg `mz_worker_compute_delays_1`? The alternative would be just creating a view for the delay as interval table, but it would only return data for the current cluster.

I think there's some way to have a cluster-suffixed view, no? I could be crazy, but I thought I saw that we already do that for one of the cluster-suffixed relations in `mz_internal`.

**Comment by chaas** [comment]
I also noticed some internal object renaming that I can clean up in logging.rs as part of this change, to be consistent with the new view names (e.g. `MzMaterializationSourceFrontiers` -> `MzComputeImportFrontiers`)
