### ISSUE TITLE
docs: CREATE CONNECTION

### ISSUE THREAD

**Issue by rjnn** [MaterializeInc/materialize#14319]
### Documentation request

Searching for "connection" surfaces "SHOW CREATE CONNECTION", "SHOW CONNECTIONS", and "DROP CONNECTION", but not "CREATE CONNECTION".

1. Either that page exists and search isn't indexing it right, or
2. That page doesn't exist and needs to be created.

<img width="495" alt="Screen Shot 2022-08-21 at 10 34 34 AM" src="https://user-images.githubusercontent.com/1565833/185796276-a80d5ce4-622b-4a91-a2bd-0f2c3eab8ad4.png">

**Comment by rjnn** [comment]
The page exists:
https://materialize.com/docs/unstable/sql/create-connection/

It just doesn't show up in search for some reason.

**Comment by morsapaes** [comment]
@ruf-io, since you're more familiar with how search is wired up, could you have a look?

**Comment by ruf-io** [comment]
This specific issue is fixed without a PR by forcing a re-crawl. Closing.
