### ISSUE TITLE
`CREATE VIEWS` uses `WHERE` rather than `CASE`

### ISSUE THREAD

**Issue by frankmcsherry** [MaterializeInc/materialize#14311]
### What version of Materialize are you using?

main

### How did you install Materialize?

Materialize Cloud

### What is the issue?

The views produced by `CREATE VIEWS` demultiplex the underlying data using `WHERE` constraints followed by casts that may error. Depending on optimization, the casts may be pushed below the `WHERE`, especially if the optimizer believes that multiple uses of the same data could benefit from casting first and demultiplexing second.

Instead, the columns should be extracted using `CASE` expressions, to ensure that the erroring casts will only be evaluated in the case of the specific tables.

Example: https://materializeinc.slack.com/archives/CU7ELJ6E9/p1660840604497659

**Comment by petrosagg** [comment]
fixed by #14305
