### ISSUE TITLE
ditch mz_materializations for mz_indexes?

### ISSUE THREAD

**Issue by JLDLaughlin** [MaterializeInc/materialize#14313]
## What's wrong?
According to @benesch, `mz_materializations` currently has an unclear purpose.

## What should we do?
Potentially ditch `mz_materializations` (delete it entirely!) in favor of `mz_indexes`. 

@ggnall - can you investigate if there are any outstanding usages of `mz_materializations` that we should be aware of?
@chaas  - can you take point on removing this table, if we decide we're good to go?

**Comment by JLDLaughlin** [comment]
tagging in @morsapaes and @sjwiesman for their opinions here!

**Comment by benesch** [comment]
In conversation with @rjnn last night, I think actually everything currently called `mz_materializations_*` should be instead called `mz_dataflows_*`. Possibly even a `SHOW DATAFLOWS` command. Need to consider whether we want to expose "dataflows" as a user-facing concept. I'll start a thread on Slack.

**Comment by benesch** [comment]
Slack link: https://materializeinc.slack.com/archives/C015RHB3LDR/p1661232153617589

**Comment by chaas** [comment]
The full suite of system tables using `materializations` is:
```
mz_materializations
mz_materialization_dependencies
mz_worker_materialization_frontiers
mz_worker_materialization_source_frontiers
mz_worker_materialization_delays
mz_materialization_frontiers
mz_materialization_source_frontiers
```

**Comment by frankmcsherry** [comment]
This may be in the slack thread, but it seems like there is no reason to have `materialization` or `dataflow` in there. The concepts, "frontiers" and "delays" and "dependencies" are for "collections"/"relations"/"tables" with the term depending on which school of thought you come from. So you could have instead `mz_collection_dependencies` and `mz_collection_frontiers`, etc.

**Comment by chaas** [comment]
Thanks @frankmcsherry !
@benesch Are you in agreement to use the `mz_collection` prefix? I'm going to go ahead and start these changes.
I agree it's not quite a relation (we define that as not including indexes in `mz_relations`) nor a table, since it includes both indexes and materialized views.

**Comment by chaas** [comment]
Finally getting to this now that #14559 is merged.
As per the conversation on that PR, the proposed prefix from @vmarcos is `mz_compute` with the use of `import` and `export` for storage sources and dataflow creators respectively.

> * Ensure that `mz_worker_materialization_source_frontiers` is renamed to `mz_worker_compute_import_frontiers`.
> * Ensure that `mz_materialization_dependencies` is renamed to `mz_compute_dependencies`.
> * Ensure that `mz_materialization_frontiers` and `mz_worker_materialization_frontiers` are renamed to `mz_compute_frontiers` and `mz_worker_compute_frontiers`.
> * Ensure that `mz_worker_materialization_delays` is renamed to `mz_worker_compute_delays` or alternatively to `mz_compute_delays`.
> * Ensure in all of the above that `source_id` is renamed to `import_id` and that `global_id` are renamed as `export_id`.

Also rename `mz_materializations` -> `mz_compute_exports`.

Thanks again @vmarcos for thinking this through!

@frankmcsherry if this sounds good I'll go ahead with the changes.

**Comment by chaas** [comment]
Synced offline - we're not sure about exposing the term "compute", but we'll move forward with these changes since this seems like the best option for now.

**Comment by benesch** [comment]
If I understand correctly, these are all getting moved into the `mz_internal` schema too, so we should be free to change them later!
