### ISSUE TITLE
Automate Adding Storage Issues to Project

### ISSUE THREAD

**Issue by nmeagan11** [MaterializeInc/materialize#14336]
### Feature request

Similar to https://github.com/MaterializeInc/cloud/issues/3822, we want to add a [GitHub Action](https://github.com/marketplace/actions/add-to-github-projects) such that when someone adds the `A-STORAGE` label to an issue, it automatically lands in our [project board](https://github.com/orgs/MaterializeInc/projects/26/views/1) for visibility and triaging.

**Comment by uce** [comment]
@nmeagan11 Do you still want this?

**Comment by nmeagan11** [comment]
Nope, I'll close it.
