### ISSUE TITLE
`mz_avro` encodes messages in the default namespace incorrectly

### ISSUE THREAD

**Issue by mrry** [MaterializeInc/materialize#14333]
### What version of Materialize are you using?

Latest main (f029b1410c1c181eea10e3910368a4639bff9853)

### How did you install Materialize?

Built from source

### What is the issue?

When the `mz_avro` crate serializes a schema, and it contains a type whose name is in the default (empty) namespace, the serialized schema will include a leading `.` before the type name. For example, a type named `"MyType"` will be serialized as `".MyType"`.

The logic for encoding type names appears to be here: https://github.com/MaterializeInc/materialize/blob/f029b1410c1c181eea10e3910368a4639bff9853/src/avro/src/schema.rs#L558

[This validation logic](https://github.com/apache/avro/blob/1008ce35bff83f7f98d5bd06b03b25c387efd4fc/lang/py/avro/name.py#L33-L47) (`_validate_fullname()`) in the Avro Python library fails on the serialized schema, because it splits the name on `'.'` and the regex chokes because the first component of the name is empty. Other tools in the Apache ecosystem appear to depend on the exact full-name string, and are sadly not robust to the presence of namespaces.

The easiest way to reproduce this is to add a `println!` in `mz_avro::schema::tests::test_schema_fingerprint()`. The fingerprinted schema has a name of `".test"`:

```
{"type":"record","name":".test","fields":[{"name":"a","type":"long","default":42},{"name":"b","type":"string"}]}
```

This may also imply a bug in the fingerprinting/canonicalization algorithm, since changing the schema to have `"name":"test"` will change the generated fingerprint. I haven't been bitten by this however!

**Comment by brennanvincent** [comment]
To be fair, this was allowed by the spec at the time the code was written 😂 

But, indeed, since Avro 1.10 there's now the following language: 

> The null namespace may not be used in a dot-separated sequence of names. So the grammar for a namespace is:
> 
>  \<empty> | \<name>[(\<dot>\<name>)*] 

So I agree that this is out of spec. Will put up a PR shortly to fix it.

**Comment by brennanvincent** [comment]
Actually, I'm now a bit confused. If the empty namespace is no longer allowed in a fully-qualified name, how are you supposed to refer to a type in the empty namespace from within another namespace?

E.g.

```
{
    "type": "record",
    "name": "r",
    "fields": [
        {
            "name": "f",
            "type": {
                "type": "record",
                "name": "r2",
                "namespace": "ns",
                "fields": [
                    {
                        "name": "f2",
                        "type": ["null", ".r"]
                    }
                ]
            }
        }
    ]
}
```

If we use `r` instead of `.r` in the field of `f2`, it would be interpreted as `ns.r`, since `ns` is the nearest enclosing namespace.

So unless I'm missing something, I think Apache has restricted the set of schemas that it's possible to encode by making this spec change...

**Comment by benesch** [comment]
Here's the discussion from the mailing list: https://lists.apache.org/thread/q0o58fxgvstvdlgpoyv2pcz53borp587

The point you raise does not appear to have come up.

**Comment by brennanvincent** [comment]
Yep, already found that! I'm composing a message to the mailing list now.

**Comment by mrry** [comment]
Thanks for the fast response @brennanvincent and @benesch! I'll confess to not having read the spec in detail, and ran into this when I was cobbling together third-party tools and trying to get them to work.

> So unless I'm missing something, I think Apache has restricted the set of schemas that it's possible to encode by making this spec change...

Your read on this makes sense to me. I can't think of how I'd refer to an empty-namespace type from within a namespace given that restriction! If I were defining the types myself, I would probably require a namespace, but unfortunately the toolset I am dealing with specifies _its_ types as being in the empty namespace!

**Comment by benesch** [comment]
Here's Brennan's post if anyone else would like to follow along: https://lists.apache.org/thread/n30tzzp9g8r01jl2om26z4cqkk843k2q.

**Comment by brennanvincent** [comment]
That archive page's threading logic is apparently broken, and misses my follow-up: https://lists.apache.org/thread/8qc45ry2g76f4lywckqxtodyhwposoz3

**Comment by brennanvincent** [comment]
By the way, it's possible to change our schema serializer to only emit the fully-qualified namespace _when necessary_, which would still allow the library to serialize schemas like my example, while emitting those that match the newest spec when that edge case doesn't arise. This would probably fix the particular issue @mrry is hitting. I have a draft PR: https://github.com/MaterializeInc/materialize/pull/14344

**Comment by brennanvincent** [comment]
Hey @mrry , can you try what you were doing again with latest main?

**Comment by brennanvincent** [comment]
Derek explicitly said that he was running on https://github.com/MaterializeInc/materialize/commit/f029b1410c1c181eea10e3910368a4639bff9853 in the issue description. Not sure exactly what he was trying to do but apparently it didn't require building a single-binary `materialized`.

That said, I'm happy to push a backport because we are probably going to want to do so anyway. In fact I'd probably want to backport this even if it _weren't_ useful for Lacework, just because keeping the two `mz_avro` branches in sync will make it easier to backport other (possibly critical) bugfixes in the future.

**Comment by mrry** [comment]
Thanks for getting this fix in so promptly! I think I should be able to test based on checking out `main`. Let me try that and I'll close this if it works?

**Comment by mrry** [comment]
It works for the schema I was using, thanks!
