### ISSUE TITLE
sql: enum-ify all `WITH` options in parsing

### ISSUE THREAD

**Issue by sploiselle** [MaterializeInc/materialize#14341]
### Feature request

There has been a history of the string-keyed `WITH` options causing subtle bugs (the PRs are hard to find, but will see if I can dredge them up). The problem being that there was never a means by which you could guarantee that a particular set of `WITH` options in the parser would get properly correlated with the _thing_ (whatever it was) that you were hoping to modify.

Over the last few months, we've been chipping away at fixing this by converting `WITH` options into a form that uses enums rather than strings as their keys. [Here is an example of the structure](https://github.com/MaterializeInc/materialize/pull/13665/files#diff-c39a98c6254290441be6a631cb806e3e68bab81b1f26e011d3bb5e5824b22364R691-R725), and [here is the template for how the options should be handled](https://github.com/MaterializeInc/materialize/pull/13665/files#diff-c840a7fbb6a642d6cbf71dddd92ec1b6dfa86310022ead5673e8fa509ba73dc4R3106-R3159).

This ticket is meant to track that this work should be seen through to completion; we'll know that it's done when we no longer need `sql-parser::ast::defs::statement::WithOption`.  Note that from this we have co-opted `WithOptionValue`, which is fine to keep around.

**Comment by guswynn** [comment]
Remaining options, note ALL are `unsafe`:
- [ ] `epoch_ms_timeline`
- [ ] `timeline`
- [ ] `timestamp_frequency_ms`
- [ ] kafka ones:
	- [ ] `group_id_prefix`
- [ ] aws ones:
	- [ ] `endpoint`
	- [ ] `region`
	- [ ] `role_arn`

(cc @benesch should the aws ones be unsafe?)

**Comment by benesch** [comment]
`timestamp_frequency_ms` should become `TIMESTAMP GRANULARITY, as a heads up!

The AWS ones should be implicitly unsafe because S3/Kinesis sources are unsafe!

**Comment by guswynn** [comment]
`epoch_ms_timeline` is only available for the cdcv2 envelope, are we just going to add it to the final WITH options and error out on other envelopes? or do we want to parse a new block after `ENVELOPE MATERIALIZE`? The former is likely way easier to maintain, so I'm inclined to do that!

**Comment by guswynn** [comment]
@benesch where do the aws ones go:
- `REGION` in the connector design doc specifies it is in the connection, but kinesis gets the region from the sources ARN? should kinesis sources just ignore the `REGION` in the connector they are using?
- `ROLE ARN` (which is now untested) should go in the connector?
- `ENDPOINT` should go in the connector?

**Comment by benesch** [comment]
> epoch_ms_timeline is only available for the cdcv2 envelope, are we just going to add it to the final WITH options and error out on other envelopes? or do we want to parse a new block after ENVELOPE MATERIALIZE? The former is likely way easier to maintain, so I'm inclined to do that!

Definitely the latter, now that you mention it! It should look like:

```
ENVELOPE MATERIALIZE (EPOCH MS TIMELINE = {true | false})
```

That matches how we handle options for `ENVELOPE DEBEZIUM` these days.

> should kinesis sources just ignore the REGION in the connector they are using?

Ugh. Yeah. I guess. Something to sort out later, when we un-unsafify these things.

`ROLE ARN` and `ENDPOINT` should go in the connector, yeah.

But! I'm starting to get worried about how quickly this yak is growing up. Is it time to abandon ship? We could do something quick and dirty, like rename `WITH (legacy_options)` to `LEGACYWITH (legacy_options)`. That would trivially solve the ambiguity, and we could punt the rest of the work to later.

**Comment by guswynn** [comment]
@benesch yes, its probably time to abandon ship on getting this done before the end of breaking changes; your idea to change it to `LEGACYWITH` is a good one, ill put up a pr for that today

**Comment by bkirwi** [comment]
> Definitely the latter, now that you mention it!

I don't have a strong opinion on this one, but it is a little weird that `epoch ms timeline` is now mutually-exclusive with `timeline` which lives in an entirely distinct option block. 

In any case, if we're not moving `epoch ms timeline` into the final with block, I think I'm done with the related issue https://github.com/MaterializeInc/materialize/issues/13919 ...will close that out unless I hear otherwise!

**Comment by benesch** [comment]
> I don't have a strong opinion on this one, but it is a little weird that epoch ms timeline is now mutually-exclusive with timeline which lives in an entirely distinct option block.

Ooh, that's a good point. Sticky. Why are these two distinct options anyway?
