### ISSUE TITLE
Remove `mz_catalog_names` system table

### ISSUE THREAD

**Issue by chaas** [MaterializeInc/materialize#14389]
## What's wrong?
According to @benesch, `mz_catalog_names ` no longer serves a good use.
Per comment in the code
```
// For historical reasons, this view does not properly escape identifiers. For
// example, a table named 'cAp.S' in the default database and schema will be
// rendered as `materialize.public.cAp.S`. This is *not* a valid SQL identifier,
// as it has an extra dot, and the capitals will be folded to lowercase. This
// view is thus only fit for use in debugging queries where the names are for
// human consumption. Applications should instead pull the names of individual
// components out of mz_objects, mz_schemas, and mz_databases to avoid these
// escaping issues.
```

## What should we do?
Delete `mz_catalog_names` entirely.

Existing uses of this table that need to be handled:
* `src/billing-demo/src/bin/billing-demo/mz.rs`  in `create_kafka_sink()`
    * @benesch is this demo still active?
* Tests (environmentd tests, testdrive)
For all of the above, I'll replace all queries with a combo of mz_objects, mz_schemas, and mz_databases

**Comment by benesch** [comment]
Fixed by #14516.
