### ISSUE TITLE
Remove  `mz_view_keys` and `mz_view_foreign_keys` system tables

### ISSUE THREAD

**Issue by chaas** [MaterializeInc/materialize#14390]
## What's wrong?
According to @benesch , `mz_view_keys` and `mz_view_foreign_keys` are only populated for system logs, which makes them fairly useless.

## What should we do?
Remove `mz_view_keys` and `mz_view_foreign_keys`.

Existing uses of these tables: only tests.

**Comment by frankmcsherry** [comment]
> Remove `mz_view_keys` and `mz_view_foreign_keys`.

Or we could use them. This is information that databases are meant to track, and can be of value presented to BI tools. That we .. I guess don't .. sounds like it could be a different bug!

**Comment by chaas** [comment]
Agreed, the updated plan is to:
1) Rename these tables (eg  `mz_relation_keys` or `mz_collection_keys`) and make documentation explicit that they are only populated for system tables.
2) Ideally add the data from user-defined relations into these tables down the road. That will be a separate "nice to have" follow up ticket, since it's non-breaking.

**Comment by chaas** [comment]
I revisited this @frankmcsherry  and it's not even populated for all system tables, just introspection sources. So right now these tables are pretty confusing and specific. I actually agree with the original plan, we're probably better off removing them for now and leaving the door open to add them back with more useful data down the road.
Otherwise we're stuck with them since we don't want to introduce breaking changes in the future.

**Comment by chaas** [comment]
Recording conversations held elsewhere - we will keep these tables but prevent them from being used in views via #14724 and document them as unstable/volatile, so that we can change them down the road.

**Comment by chaas** [comment]
Marked as volatile via https://github.com/MaterializeInc/materialize/pull/15018. We will want to revisit improving the contents of this down the road. I will open a separate ticket in the team backlog.
