### ISSUE TITLE
`mz_peek_active.id` of type uuid ought to be an i64 called `conn_id`

### ISSUE THREAD

**Issue by chaas** [MaterializeInc/materialize#14394]
## What's wrong?
According to @benesch, `mz_peek_active.id` of type uuid ought to be an i64 called `conn_id`. 

## What should we do?
This is a bit tricky, since the table is generated directly from a Compute Log.
https://github.com/MaterializeInc/materialize/blob/a8131a5cee3534432bbacab63909ad005543a646/src/adapter/src/catalog/builtin.rs#L984-L988
The `PeekCurrent` log model is used throughout compute.
Do we want to change it everywhere?
Or just in this table, by applying a transformation to the Compute Log model? (I'm not sure how to do that, but I can look into it).

**Comment by chaas** [comment]
@benesch I'm unsure about this one.
This is the Peek object definition
```
pub struct Peek {
    /// The identifier of the view the peek targets.
    id: GlobalId,
    /// The logical timestamp requested.
    time: Timestamp,
    /// The ID of the peek.
    uuid: Uuid,
}
```
Then the conversion to the table data is
```
Row::pack_slice(&[
                    Datum::Uuid(peek.uuid),
                    Datum::Int64(worker as i64),
                    Datum::String(&peek.id.to_string()),
                    Datum::Int64(peek.time as i64),
                ])
```
in `src/compute/src/logging/compute.rs`.
The table definition in `src/compute-client/src/logging.rs` is
```
            LogVariant::Compute(ComputeLog::PeekCurrent) => RelationDesc::empty()
                .with_column("id", ScalarType::Uuid.nullable(false))
                .with_column("worker", ScalarType::Int64.nullable(false))
                .with_column("index_id", ScalarType::String.nullable(false))
                .with_column("time", ScalarType::Int64.nullable(false))
                .with_key(vec![0, 1]),
```

So the peek's uuid is populating that first column and the type is a uuid. What would be the reason to rename to `conn_id` and change the type to i64?
The globalId is going into the `index_id` str field. Should that be changed to an i64?

**Comment by benesch** [comment]
> What would be the reason to rename to conn_id and change the type to i64?

Ah! We _used_ to use the `conn_id` as the peek ID. Now we actually have a separate `peek_id`. Nice. See #9521 and #11016 if you're interested in the historical context. 

> The globalId is going into the index_id str field, which seems correct?

Agreed! 

----

I'm just going to optimistically close this one, as it seems we made the peek implementation match the system catalog since I noted the issue.
