### ISSUE TITLE
Stop using `global_id` column name in system tables

### ISSUE THREAD

**Issue by chaas** [MaterializeInc/materialize#14407]
## What's wrong?
Per comment by @vmarcos, the catalog relations `mz_materializations`, `mz_materialization_frontiers`, `mz_worker_materialization_frontiers`, `mz_materialization_source_frontiers`, `mz_worker_materialization_source_frontiers`, and `mz_worker_materialization_delays` all use the term `global_id` for the same concept. However, it is unclear if `global_id` is a meaningful term or one that we wish to expose to users of the catalog.

## What should we do?
Potentially rename the column. What should that name be?

**Comment by chaas** [comment]
@benesch I've been thinking about this more, and I'm wondering if we need to expose the notion of a global id and can't get around it?

In `mz_materializations`, the `global_id` is described as " The ID of the index or materialized view that created the dataflow. Corresponds to `mz_indexes.id` or `mz_materialized_views.id`."

Both `mz_indexes.id` and `mz_materialized_views.id` correspond to `mz_objects.id`. This is a bit confusing, since you'd expect `mz_indexes.id` to refer to an index id and `mz_materialized_views.id` to refer to a materialized view id, based on SQL best practices. But really they both refer to an "object id" aka global id.

Perhaps this is a bigger rabbit hole, but it's non-obvious what we should replace the `global_id` column with here, other than `object_id`, which isn't much better.

I'm not sure our documentation is clear that these ids are all linked either.
`mz_objects` describes the id column as "Materialize's unique ID for the object."
`mz_indexes` describes the id column as "Materialize's unique ID for the index." etc

**Comment by benesch** [comment]
> Perhaps this is a bigger rabbit hole, but it's non-obvious what we should replace the global_id column with here, other than object_id, which isn't much better.

I _do_ think it's a bit better, because at least we don't have to explain _what_ it's global to (an environment; not global across environments).

> I'm not sure our documentation is clear that these ids are all linked either.
mz_objects describes the id column as "Materialize's unique ID for the object."
mz_indexes describes the id column as "Materialize's unique ID for the index." etc

Good point. We should add a few lines to the docs somewhere like:

> IDs for all objects represented in mz_objects ({indexes, views, ...exahustive list}) share a namespace. E.g., if there is a view with ID u1, there will never be a sink, index, ... with ID u1.
