### ISSUE TITLE
[Epic] Specialized evaluation / optimization for interactive `SELECT` queries

### ISSUE THREAD

**Issue by vmarcos** [MaterializeInc/materialize#14442]
### Feature request

Currently, one-shot `SELECT` queries are, generally speaking, planned as a regular dataflow that gets temporarily activated and then disposed of. This approach misses out on potential optimizations for one-shot `SELECT` queries given the observation that we will not have to maintain the results of these queries as updates stream in. 

This epic proposes to specialize the evaluation of one-shot `SELECT` queries by implementing a number of optimizations for their treatment. At a high level, we would like to mark a dataflow for a one-shot `SELECT` query with beginning (`as_of`) and end (`until`) times, then use this information towards snapshotting data and producing more efficient query plans.

### Goals

- Faster execution of one-shot `SELECT` queries than currently, supporting better user experience with Materialize.
- Reduction of resource usage by avoiding expensive plans when much simpler plans would suffice for one-shot `SELECT` queries.

### Acceptance Criteria

- We can demonstrate examples of one-shot `SELECT` queries where query execution time and/or resource usage are substantially reduced.

### Design Discussions

This epic raised many important design discussions, where a consensus towards an MVP approach based on an LIR-level plan refinement emerged. The following links are relevant:

-  https://github.com/MaterializeInc/materialize/pull/18546: This PR embodies the MVP approach agreed upon to make progress on this epic. At a high level, an LIR-level plan refinement step for single-time dataflows selects monotonic operators where possible.
- #18535 
- #18492 
- Slack discussions: [(1)](https://materializeinc.slack.com/archives/C041KPFCR98/p1680080591297539?thread_ts=1680080265.109899&cid=C041KPFCR98), [(2)](https://materializeinc.slack.com/archives/C02PPB50ZHS/p1680184793944929)

A design document discussing the work for stabilization of the feature based on the monotonic one-shot `SELECT` MVP is given in:

- #19250 

### Tasks
```[tasklist]
## Required Issues (Must Haves)
- [x] #14368
- [x] #13913
- [X] Evaluate possible alternatives for improved one-shot query planning, namely that one-off `SELECT` queries without `AS OF` specifications or where the dataflow can be annotated such that `until == as_of + 1`. The latter should allow all query inputs to become logically monotonic.
- [x] #3740
- [x] #14351
- [x] #18890
- [ ] #19290
- [ ] #18734 
- [ ] #17358
```

```[tasklist]
## Discretionary Issues (Nice to Haves)
- [ ] #18732 
```

Note that a complete solution to required issue #17358 depends on discretionary issue #18732. However, validation of the feature can start even before this latter issue is fully resolved.

### Related

This section lists issues that are related to this epic and unlocked, e.g., by the possibility to mark dataflows with a beginning and end time. These issues are not within the epic's scope.

- #8194
- #13761
 
### Future Work
If there are plans for allowing SELECT queries with `AS OF` specifications over a window `[as_of, until)` where `until > as_of + 1`, then we could think of creating a snapshot to make inputs monotonic again, taking advantage of the fact that the `SELECT` query is one-shot. However, we currently do not mark `until` to be greater than `as_of + 1` in one-shot `SELECT` queries, so we deemed this option could be left for future work.

The following issues could be revisited as part of future work:
- #6738
- #12604

It is unclear if they are still relevant and whether we'd be in a position to tackle them without more progress on cost-based optimization.

**Comment by antiguru** [comment]
Moving to icebox because our inputs don't guarantee compacted data, which doesn't allow us to treat one-off queries as monotonic.

**Comment by ggevay** [comment]
> Moving to icebox because our inputs don't guarantee compacted data, which doesn't allow us to treat one-off queries as monotonic.

This came up again, and a suggestion was to add `consolidate` operators, see https://github.com/MaterializeInc/materialize/issues/17358

**Comment by aalexandrov** [comment]
nit: the title is somewhat confusing as we currently have something which is already called "fast-path" / "one-off" SELECT query.

I think what the epic is proposing is to go through a different planning & optimization path for those queries, which includes more optimizations being enabled in:

1. The MIR optimizer step.
2. The MIR ⇒ LIR lowering step.
3. The LIR rendreing step.

I'm not sure which of the three steps we want to target as part of this epic.

**Comment by vmarcos** [comment]
Good point, and sorry about the confusion! Perhaps we should call it "Specialized evaluation for interactive `SELECT` queries" or something to that effect? Not sure if it helps, but most of the work that we originally thought about for this epic was related to giving a dataflow from an interactive `SELECT` a well-defined `until` and then leveraging that to consolidate data and leverage monotonicity. Not sure if there are plans to work on any different topics under this umbrella as well.

**Comment by aalexandrov** [comment]
> Specialized evaluation / optimization for interactive SELECT queries

Sounds great! In the optimization pipeline itself, there is opportunities to have specialized pipelines:

1. In the `global` phase, which consumes a `DataflowDescription<OptimizedMirRelationExpr>`), and after that 
2. in the `mir_to_lir` phase (a.k.a. lowering) which maps a `DataflowDescription<OptimizedMirRelationExpr>` to a `DataflowDescription<Plan>` (but only if the input cannot be executed as `FastPathPlan`).

Since both consume a `DataflowDescription<OptimizedMirRelationExpr>` we can lookup the `until` in both and act accordingly.

**Comment by vmarcos** [comment]
Frank's PR https://github.com/MaterializeInc/materialize/pull/14607 is of relevance here, and a good starting point to test execution of one-off `SELECT`s with monotonic variants in rendering.

**Comment by ggevay** [comment]
(I've added Frank's interesting point from https://github.com/MaterializeInc/materialize/pull/14607#issuecomment-1236394599 to https://github.com/MaterializeInc/materialize/issues/17358)

**Comment by vmarcos** [comment]
The scope planned for this epic has been completed. A follow-up item related to removing the corresponding feature flag should be done separately, after we observe stability of the feature for sufficiently long.
