### ISSUE TITLE
Progress-tracking topic for Kafka Sinks

### ISSUE THREAD

**Issue by nmeagan11** [MaterializeInc/materialize#14488]
### Feature request

In https://github.com/MaterializeInc/materialize/issues/14267, we made the decision to write progress messages in our sinks to a separate "offsets" topic (see [here](https://github.com/MaterializeInc/materialize/issues/14267#issuecomment-1220316011) for context). This issue is to track that work.

Internal design doc [here](https://www.notion.so/materialize/Kafka-Sinks-9ba8f8c0ddc949d6b20a67a2558a7604#adda53e7e7624d06965fbba63ed21195).

**Comment by aljoscha** [comment]
@bkirwi You might want to change this to reflect current thinking? I think it's meant to be called sth more akin to `TIMESTAMPS TOPIC`, because we don't really store offsets in there.

@nmeagan11 & @uce Sorry for not mentioning this earlier.

**Comment by benesch** [comment]
I propose `PROGRESS TOPIC` as the name!

**Comment by bkirwi** [comment]
The main PR #14526 is merged, and most of the followup work is either done or should land in the next day or two.

A few comments from @aljoscha that aren't tracked elsewhere yet:
- > I think the progress topic doesn’t yet show up in SHOW CONNECTION (and mz_connections). Should it?
- > I noticed that the way we choose default PROGRESS TOPIC names might be a bit of a footgun. We use _materialize-progress-{connection_id}, so if people create connections in two materialize installations that point at the same Kafka cluster they will get a clash.
  - Tentative plan: use a hash of the environment id and the connection's UID as the suffix, instead of the unhashed connection UID.

If either turn out to be large amounts of work, I'll fork out some new issues.

**Comment by benesch** [comment]
> I think the progress topic doesn’t yet show up in SHOW CONNECTION (and mz_connections). Should it?

Oh! The `PROGRESS TOPIC` ended up as a `CREATE CONNECTION`-time option, not a `CREATE SINK`-time option! That's the opposite of how I was envisioning it, but this makes a lot of sense. Food for thought: perhaps we should call it `SINK PROGRESS TOPIC` in that case, to indicate that it's _just_ about sinks that reference the connection, and not sources. 

But yeah, we probably want a new `mz_kafka_connections` table that has a `sink_progress_topic` column in it.

> Tentative plan: use a hash of the environment id and the connection's UID as the suffix, instead of the unhashed connection UID.

The hardest part will be plumbing the environment ID through. I think I said on Slack that you could use the Frontegg tenant ID, but that was wrong. The tenant ID identifies the organization, but an organization can have multiple environments. You want the environment ID. That may require a new CLI flag and some plumbing from Cloud.

**Comment by bkirwi** [comment]
> That may require a new CLI flag and some plumbing from Cloud.

Ah, the plot thickens! Will also need to think about how to handle tests / running locally... may need to eg. thread the moral equivalent of a testdrive id through to tests that expect some continuity across `environmentd` runs.

I had a quick look at how that's postgres manages the similar situation: the slot id is generated randomly during purification and stored as part of the statement, which IIUC has a bit of syntax just for this purpose. It might be wise to persist the topic even if we're generating it deterministically, to make it easier to detect errors or if we need to change the format in the future...

**Comment by bkirwi** [comment]
Made an issue for it! https://github.com/MaterializeInc/materialize/issues/14728

**Comment by aljoscha** [comment]
@bkirwi should we close this one now that you've spun out #14728?

**Comment by bkirwi** [comment]
This is still live, but I've been holding it since it's a breaking change: https://github.com/MaterializeInc/materialize/pull/14680

(I don't think we need this open just to track that, though, if you'd rather close.)

**Comment by bkirwi** [comment]
Everything for this has now merged and is running in the current release!
