### ISSUE TITLE
Predicate pushdown into arranged join inputs

### ISSUE THREAD

**Issue by ggevay** [MaterializeInc/materialize#14500]
### Feature request

When an input to a Delta join is already arranged, then we currently don't push down filters into that input, because that currently means that we lose the arrangement, so we would have to re-arrange before the join. (Differential join has other issues: https://github.com/MaterializeInc/materialize/issues/14059.) However, we could use `TraceFilter` to apply the filter before the join but still don't lose the arrangement.

I looked at 9 TPC-H queries, and 7 of those can probably benefit from this optimization: 2, 3, 4, 5, 7, 8, 19.

## Acceptance criteria

We can push down filters into delta join inputs without losing the arrangement. Measure speedup on TPC-H.

## Implementation

Currently, the following happens:
- [MIR] `PredicatePushdown` happily pushes down the predicate into a join input, regardless of whether an arrangement exists.
- [MIR] `join_implementation.rs` (e.g. `install_lifted_mfp`) lifts the filter up if the input was arranged, effectively undoing the filter pushdown in this case.
- [MIR -> LIR lowering] `DeltaJoinPlan::create_from` stuffs the filter into some `JoinClosure`. (I guess into `DeltaStagePlan::closure`.)

I think we could alter only the last step, and create one more step:
- We would create a new field in `DeltaPathPlan`, called `input_filter` (next to the `initial_closure`). `DeltaJoinPlan::create_from` would put the filter into this new field.
- `render_delta_join` would apply the `TraceFilter` magic with the `input_filter` as `logic`.

(This avoids adding new MIR/LIR node types or changing `ArrangeBy` in MIR/LIR.)

## Possible follow-ups

We could create a variant of `TraceFilter` that would accept not a general `bool` function, but instead a list of literal equality constraints (similarly to `command.rs::Peek::literal_constraints`). Then we could avoid a full scan of the index, and instead get only the relevant keys.

**Comment by frankmcsherry** [comment]
Heads up that any performance gains here are going to rely on fairly subtle implementation details of the `half_join` operator that delta joins use. The vanilla version of the operator acts on a stream of input tuples that provoke look-ups into the arranged input. Having a `TraceFilter` will not cause those look-ups to go any faster (they will result in a miss, as opposed to a hit that then gets discarded before being produced as output our current predicate logic).

We could look at `half_join` and see if it makes sense to coalesce work by key, but generally you might not want to group the streamed input by key, as this introduces some blocking that isn't strictly required. It might still be good to do, but I couldn't tell you know what the trade-offs would be!

**Comment by ggevay** [comment]
So the above comment refers to the lookup side of the half-joins, if I understand correctly, i.e., that applying `TraceFilter` to that side wouldn't speed up anything.

However, how about applying key-lookup filters to the streamed input, i.e., to the starting collection of a delta path? That is, if we have an `<expr> = <literal>` constraint where `<expr>` involves only one input, and we have an index on `<expr>` then we could look up `literal` from the index, and stream only the values for that key.

And maybe the same for Differential join? see https://github.com/MaterializeInc/materialize/issues/14059#issuecomment-1257179485

**Comment by ggevay** [comment]
I added the `workaround-exists` label, and wrote a workaround here: https://github.com/MaterializeInc/materialize/issues/14645#issuecomment-1266551760

**Comment by ggevay** [comment]
I'm closing this, because 
- https://github.com/MaterializeInc/materialize/pull/15302 solved it for the streamed input case (starting input of each Delta path);
- For the lookup side of each Delta stage, my initial idea doesn't work, as Frank explained here: https://github.com/MaterializeInc/materialize/issues/14500#issuecomment-1230890755
