### ISSUE TITLE
Join-Dependent Predicate Duplication

### ISSUE THREAD

**Issue by ggevay** [MaterializeInc/materialize#14501]
### Feature request

This is CP4.2b from the TPC-H choke points paper: https://homepages.cwi.nl/~boncz/snb-challenge/chokepoints-tpctc.pdf

Imagine if after a join we have a predicate of the form
`(a = <lit1> AND xxx) OR (a = <lit2> AND yyy)` with `xxx` and/or `yyy` referencing a different join input than from what `a` came from. In this case, we cannot push down `a`'s constraints into the join input, because whether we need to check `<lit1>` or `<lit2>` depends on data from the other join input. However, instead of a traditional predicate pushdown, we could put before the join a new filter (and not touch the above filter that is after the join), which has some parts of the above expression. Namely, the parts concerning `a`, that is `a = <lit1> OR a = <lit2>` .

The other TPC-H paper from HPI (http://www.vldb.org/pvldb/vol13/p1206-dreseler.pdf) claims a 673% speedup for Q07 and a 12% speedup for Q19. Currently, the big speedup for Q07 is not realized in Materialize. However, if I delete all the indexes except the one on `lineitem`, then we do a Differential join, in which case we get a 260% speedup from the new filter.

## Acceptance criteria

We can apply the optimization in TPC-H Q07 and Q19.

## Related

Goes together well with https://github.com/MaterializeInc/materialize/issues/14512, see https://github.com/MaterializeInc/materialize/issues/14501#issuecomment-1230952559

## Implementation 

- For each join input, do a recursion on the predicates's and/or tree. The recursive function returns an expression that is a logical consequence of the predicate on the columns from that input, or None if it didn't find any logical consequence for that input.
  - First just call `try_map_to_input_with_bound_expr`. If it succeeds, then return that expression.
  - If it's an OR, then call ourselves on each argument. Each call should return Some expression. Return the OR of these expressions.
  - If it's an AND, then call ourselves on each argument. If any of these calls return Some expression, then return the AND of these expressions.

**Comment by frankmcsherry** [comment]
Just a heads up that we can get a substantial improvement on Q07 today, afaict.

The vanilla Q07 executes for me as
```
        supp_nation        |        cust_nation        | l_year |    revenue    
---------------------------+---------------------------+--------+---------------
 FRANCE                    | GERMANY                   |   1995 | 54639732.7336
 FRANCE                    | GERMANY                   |   1996 | 54633083.3076
 GERMANY                   | FRANCE                    |   1995 | 52531746.6697
 GERMANY                   | FRANCE                    |   1996 | 52520549.0224
(4 rows)

Time: 9520.427 ms (00:09.520)
materialize=> 
```
However, if I add the two recommended filters, *and* change the join order to put `nation` first, like so:
```sql
SELECT
    supp_nation,
    cust_nation,
    l_year,
    sum(volume) AS revenue
FROM
    (
        SELECT
            n1.n_name AS supp_nation,
            n2.n_name AS cust_nation,
            extract(year FROM l_shipdate) AS l_year,
            l_extendedprice * (1 - l_discount) AS volume
        FROM
            nation n1,
            nation n2,
            supplier,
            lineitem,
            orders,
            customer
        WHERE
            s_suppkey = l_suppkey
            AND o_orderkey = l_orderkey
            AND c_custkey = o_custkey
            AND s_nationkey = n1.n_nationkey
            AND c_nationkey = n2.n_nationkey
            AND (
                (n1.n_name = 'FRANCE' AND n2.n_name = 'GERMANY')
                or (n1.n_name = 'GERMANY' AND n2.n_name = 'FRANCE')
            )
            AND l_shipdate BETWEEN DATE '1995-01-01' AND DATE '1996-12-31'
            AND (n1.n_name = 'FRANCE' OR n1.n_name = 'GERMANY')
            AND (n2.n_name = 'FRANCE' OR n2.n_name = 'GERMANY')
    ) AS shipping
GROUP BY
    supp_nation,
    cust_nation,
    l_year
ORDER BY
    supp_nation,
    cust_nation,
    l_year
LIMIT 10;
```
then the time improves to 
```
        supp_nation        |        cust_nation        | l_year |    revenue    
---------------------------+---------------------------+--------+---------------
 FRANCE                    | GERMANY                   |   1995 | 54639732.7336
 FRANCE                    | GERMANY                   |   1996 | 54633083.3076
 GERMANY                   | FRANCE                    |   1995 | 52531746.6697
 GERMANY                   | FRANCE                    |   1996 | 52520549.0224
(4 rows)

Time: 661.838 ms
materialize=> 
```

**Comment by frankmcsherry** [comment]
Perhaps I should have said, if you just change the join order you get
```
Time: 8343.940 ms (00:08.344)
```
and if you just add the filters (with the old join order) you get 
```
Time: 8137.817 ms (00:08.138)
```
By doing both at once, you drive the delta join with the `n1` relation which is immediately filtered, and it produces fewer keys along the way. If you put `n2` first you get instead
```
Time: 468.656 ms
```
which is even better, I suppose because restricting suppliers into lineitems is better than restricting customers into orders into lineitems.

**Comment by ggevay** [comment]
Great! Then I'll work on this next.

And for the join order: How about adding a join order heuristic that those inputs should come first for which we have a literal constraint?

**Comment by aalexandrov** [comment]
FYI #7409 this sounds like a duplicate or at least a closely related issue. It should be either updated or closed when closing this.

**Comment by frankmcsherry** [comment]
> And for the join order: How about adding a join order heuristic that those inputs should come first for which we have a literal constraint?

I'm personally conflicted on whether we want heuristics that make it impossible to correct the system's bad choices, in exchange for automatically correcting some of the user's bad choices. It means, for example, that we will no longer be able to see if other orders would be good without rebuilding source.
