### ISSUE TITLE
Move initial resumption frontier calculation into storaged

### ISSUE THREAD

**Issue by guswynn** [MaterializeInc/materialize#14520]
A non-blocking extension of https://github.com/MaterializeInc/materialize/pull/14314 is to _move the initial resumption_frontier calculation out of the controller_. The controller is the current and natural place to calculate a value that is required during initialization of storage dataflows, but now that _periodic_ calculation happens in storaged, we want to move this initialization logic into storaged. There are a few subtleties:

- https://github.com/MaterializeInc/materialize/pull/14461 attempted this, but it was hard to do this calculation without causing a deadlock, see that pr for more info
- We may consider not requiring this value during initialization. This would require some significant changes to the way operators work, as currently we setup persist sources that rely on having a frontier. This would have to be adjusted to wait until the `Resumption
- Doing this calculation in storaged means that different workers may end up with slightly different frontier values. We would need to convince ourselves that this is okay

**Comment by aljoscha** [comment]
This has been implemented as part of #16773
