### ISSUE TITLE
surfaces: rethink and streamline "SHOW [FULL] ___ "

### ISSUE THREAD

**Issue by rjnn** [MaterializeInc/materialize#14540]
Here's a list of things that one can `SHOW`, with optional `SHOW FULL` capabilities:

clusters, views, materialized views, cluster replicas (but not replicas), sources, connections.

All of them support `FULL` modifiers, except for clusters or cluster replicas. In many cases (views, connections, and others) it just adds an unhelpful "type" column that just says "user". In one case - sources, there are _two_ `type` columns (what?).

All of this needs a revamp, and a consistent, intuitive, and _discoverable_ flow. I don't know what the end result should be, but it should be less frustrating.

**Comment by rjnn** [comment]
One idea I had:
Drop the `full`, and roll all that information into the vanilla `SHOW` column. It's unclear why there should be two.

Additional bugs surfaced in slack:
1. `CREATE CLUSTER ...` replies with `CREATE CONNECTION`
2. `CREATE VIEWS` returns `CREATE VIEW`

**Comment by rjnn** [comment]
`SHOW CLUSTER REPLICAS` does not currently show the `AZ` or the `SIZE`, and given the fact that there isn't a `SHOW FULL CLUSTER REPLICAS` option, means I don't know how to surface this information.

**Comment by rjnn** [comment]
And finally, there needs to be a sweeping `SHOW` documentation page that walks you through all the things you can show.

**Comment by chaas** [comment]
Thanks @rjnn and @benesch ! That would be great to consolidate onto #11231. Let me know if I can help with anything. The plan is to tackle that ticket soon as part of the #7174 work that is ongoing.

**Comment by benesch** [comment]
#14556 will fix the incorrect `CREATE CLUSTER` and `CREATE VIEWS` command tags.

**Comment by benesch** [comment]
> Thanks, @rjnn. Most of this is already captured in #11231, though a bit more scattered. I'll try to take a pass later today to consolidate!

Took me a bit longer than I expected, but this is done now. #11231 is tracking all of the requests here, modulo the one bug that was fixed already in #14556.
