### ISSUE TITLE
Cloudtest flakiness in computed_shared_fate

### ISSUE THREAD

**Issue by lluki** [MaterializeInc/materialize#14569]
### What version of Materialize are you using?

4599e97f63

### How did you install Materialize?

Built from source

### What is the issue?

Cloudtest occasionally fails in computed_shared_fate. [Example CI run](https://buildkite.com/materialize/tests/builds/40723).

The test times out on one of the SELECTs, for example as follows:
```
> CREATE MATERIALIZED VIEW v1 AS SELECT COUNT(*) FROM t1 UNION ALL SELECT COUNT(*) FROM s1;

rows match; continuing at ts 1662039140.199881

Ingesting data into Kafka topic testdrive-shared-fate-2 with repeat 1000

> CREATE DEFAULT INDEX ON v1;

rows match; continuing at ts 1662039140.2369459

> SELECT COUNT(*) > 0 FROM s1;
^^^ +++
<stdin>:33:1: error: deadline has elapsed
     |
  32 | 
  33 | > SELECT COUNT(*) > 0 FROM s1;
     | ^
+++ !!! Error Report
```

The error can be reproduced locally by running cloudtest with `./pytest` in `test/cloudtest`.
Here are a couple of observations:

 * `./pytest -k test_computed_shared_fate` seems to always work. The difference to a bare `./pytest` is that it doesnt run the anti_affinity test first. Anti affinity essentially creates and removes a cluster
 * Adding a `CREATE CLUSTER foo REPLICAS (r (SIZE '1'))` followed by `DROP CLUSTER foo` as a first test to `test_computed_shared_fate` makes `./pytest -k test_computed_shared_fate` fail occasionally
 * The test does not always hang in the same place, it can also hang on the `SELECT COUNT(*) FROM t1;` in the prepare function. `t1` is a table and unrelated to kafka
 * However removing everything kafka related makes the test pass all the time.

The test was enabled in #14510

**Comment by lluki** [comment]
Another observation, the `SELECT COUNT(*) FROM t1` can take more than 10s, even when everything kafka related is removed. The amount of data (3000 rows of single ints) should be trivial.

**Comment by lluki** [comment]
* Removing v1 from the test still exposes the issue. 
 * Completely removing kafka makes the issue go away.

**Comment by brennanvincent** [comment]
Upgrading kubectl to 1.24 fixes some issues for me locally, but I think we are already using that in CI.

**Comment by lluki** [comment]
I'm on 1.24
```
$ kubectl version --short
Client Version: v1.24.4
Kustomize Version: v4.5.4
Server Version: v1.24.0
```

**Comment by lluki** [comment]
Some log from envd
[failing_environmentd.txt](https://github.com/MaterializeInc/materialize/files/9472591/FAILING_LOG.txt)

when the problem occurs, the following message (around line 300 in the log) appears more often:
```
2022-09-01T18:57:54.676963Z  INFO mz_persist_client::internal::machine: external operation gc::truncate failed, retrying in 128ms: determinate: db error: ERROR: could not serialize access due to read/write dependencies among transactions
DETAIL: Reason code: Canceled on commit attempt with conflict in from prepared pivot.
HINT: The transaction might succeed if retried.: ERROR: could not serialize access due to read/write dependencies among transactions
DETAIL: Reason code: Canceled on commit attempt with conflict in from prepared pivot.
HINT: The transaction might succeed if retried.
```

Until finally it gives up with:

```
2022-09-01T19:01:24.003707Z ERROR mz_environmentd::tcp_connection: error handling connection in pgwire server: connection closed
```

**Comment by lluki** [comment]
Test is currently disabled on main, see #14577

**Comment by philip-stoev** [comment]
I am toning down the test to make it pass. One specific reproducible reason for the failure is that it is not possible to start 8-node or 16-node clusters reliably -- https://github.com/MaterializeInc/materialize/issues/14689

I am not sure if the presence of sinks or tables is what is important here. If the cluster is unable to start properly, all queries against it will hang, tables or sources.

The "could not serialize access" error mentioned above is considered safe to ignore.
