### ISSUE TITLE
Postgres connections using SSL over SSH tunnels tend to cause connections to be closed

### ISSUE THREAD

**Issue by bobbyiliev** [MaterializeInc/materialize#14566]
### What version of Materialize are you using?

v0.27.0-alpha.17 (b453a34eb)

### How did you install Materialize?

Materialize Cloud

### What is the issue?

When connecting to a Postgres source with `SSL MODE 'require'` the initial snapshot fails due to the connection being closed.

The source creation works fine when removing the `SSL MODE 'require'` line from the Postgres connection DDL statement. 

### Relevant log output

```source
stack backtrace:
thread 'tokio-runtime-worker' panicked at 'replication snapshot for source u61 failed: connection closed', src/storage/src/source/postgres.rs:348:17
```

**Comment by benesch** [comment]
I wrote up repro instructions for anyone who might be looking at this locally: https://gist.github.com/benesch/a4f5be7404c2ec50a4a8a707bdc7eb36

**Comment by andrioni** [comment]
Tested with `devel-6b774647d07617adc16842dc27587c037ee947fd`, issue seems to be fully solved for now, closing this issue.
