### ISSUE TITLE
Stash storage is leaked when a compute instance is dropped

### ISSUE THREAD

**Issue by teskje** [MaterializeInc/materialize#14585]
### What version of Materialize are you using?

v0.26.1-dev (cf1510e5c)

### How did you install Materialize?

Built from source

### What is the issue?

The [stash API](https://dev.materialize.com/api/rust/mz_stash/index.html) currently does not provide a means to delete an existing collection. This was fine until now because all stash collections created by Materialize were permanent. However, with the introduction of compute command durability, compute controllers now also write to stash. A compute controller is created whenever a compute instance is created, and deleted whenever a compute instance is dropped. Consequently, compute stash collections are now also frequently created and deleted.

Currently, when a compute controller is deleted, its stash collection is cleaned up by compacting it to the empty antichain, followed by a consolidation. This has the effect that all data inside the collection is deleted. However, collection metadata (name, since, and upper) is not deleted and remains in stash storage forever.

We should extend the stash API by a method that deletes existing collections, then use that method in the compute controller during cleanup.

**Comment by teskje** [comment]
Context: I discussed with @mjibson that we can live with leaking some state for now and that this should be fixed whenever convenient for him.

**Comment by mjibson** [comment]
Is this still applicable? Unless I missed something, I don't see where the compute controller compacts these down and would need this API.

**Comment by teskje** [comment]
The compute command durability feature has been shelved for now, pending a broader architecture discussion about whether the controller should store state, and in what form. So I we can close this issue for now, and reopen/create a new one should the need come up again.
