### ISSUE TITLE
sql: remove `FULL` and `EXTENDED` from `SHOW`

### ISSUE THREAD

**Issue by benesch** [MaterializeInc/materialize#14639]
*Part of epic #11231.*

## Proposal

The `FULL` and `EXTENDED` modifier will be removed from all `SHOW` statements.

Statements for which `FULL` had an effect will unconditionally use `FULL` output. There is no replacement for the non-`FULL` output.

`SHOW EXTENDED SCHEMAS` will be removed:

  * SHOW SCHEMAS` will always show system schemas.
  * All other statements for which `EXTENDED` had an effect will unconditionally use _non_-`EXTENDED` output. For these statements, the behavior of `EXTENDED` can be emulated by specifying `FROM mz_catalog`, e.g., `SHOW OBJECTS FROM mz_catalog`.

## Background

Most of the various `SHOW` statements support two modifiers: `FULL` and `EXTENDED`. The `FULL` modifier typically adds additional columns to the output of the `SHOW` statement, while the `EXTENDED` modifier typically adds additional rows to the output of the `SHOW` statement with information about system objects.

These modifiers are not well loved by users. See, for example, #14540. The `FULL` modifier hides important information from users that ought to be displayed by default. The `EXTENDED` modifier shows system objects, but is redundant with showing objects `FROM mz_catalog`.

We inherited these modifiers from MySQL in the very early days. Back then, we were not all-in on emulating PostgreSQL; we tried to follow MySQL when we inherited a statement from MySQL, and PostgreSQL when we inherited a statement from PostgreSQL. So we tried to map MySQL's `FULL` and `EXTENDED` modifiers to Materialize as best as we could, to faithfully match MySQL.

Nowadays we're all in on PostgreSQL, and so we have the freedom to break this loose compatibility with MySQL to redesign the `SHOW` commands to our liking.

**Comment by jkosh44** [comment]
`SHOW FULL COLUMNS` was unsupported. Should we just keep the current implementation for `SHOW COLUMNS` or implement the `FULL` behavior?

**Comment by benesch** [comment]
> `SHOW FULL COLUMNS` was unsupported. Should we just keep the current implementation for `SHOW COLUMNS` or implement the `FULL` behavior?

What would `FULL` do for `SHOW COLUMNS`? I feel like what it currently shows you by default is pretty good!
