### ISSUE TITLE
storage: `transaction` key in sink output seems misnamed/misplaced

### ISSUE THREAD

**Issue by benesch** [MaterializeInc/materialize#14659]
## Proposal

Sinks in Materialize Platform always emit a `transaction` key in their output. Here's an example from our tests:

```
{"before": null, "after": {"row":{"a": "extra", "b": "row", "offset": 3}}, "transaction": {"id": "<TIMESTAMP>"}}
{"before": null, "after": {"row":{"a": "goofus", "b": "gallant", "offset": 2}}, "transaction": {"id": "<TIMESTAMP>"}}
{"before": null, "after": {"row":{"a": "jack", "b": "jill", "offset": 1}}, "transaction": {"id": "<TIMESTAMP>"}}
```

I propose that instead sinks emit that Materialize timestamp in a Kafka header named `mz-timestamp`. There are a few benefits:

  * It's out of the way if you're not looking for it. Most sink users are not sophisticated enough to use timestamps. As a header, it's tucked away somewhere where it won't raise questions for new users, but still easily accessible to power users.
  * The word "timestamp" matches the term we use in Materialize (e.g., `mz_logical_timestamp()`), and avoids bringing a new term ("transaction") into the mix. "transaction" only makes sense in the context of consistency topics.

## Background and rationale

I think the naming of this key as `transaction` is a historical accident. It was originally added as part of the consistency topic work, and only emitted when you enabled the consistency topic. The naming reflects that usage: the transaction ID that lets you relate the data in the data topic with the transaction metadata in the consistency topic. Then we added the `reuse_topic` option, which force-enabled the consistency topic as a side effect. 

Per #11216, we're now planning to temporarily _removing_ the consistency topic altogether, which means using `transaction` as the name for this field is just confusing!

cc @aljoscha @bkirwi

**Comment by bkirwi** [comment]
@aljoscha and i were just discussing something similar! should be a straightforward change, and simplify a bunch of tests. (though we'll want to train `kafka-verify` to look at headers for the few cases where the timestamp is relevant.)

**Comment by benesch** [comment]
Are we under any time pressure here? We're onboarding our first sink customer on the morning of Sep 21, which is a bit tricky, right? They'll be using our Sep 7 release, since we're skipping the Sep 14 release, and the Sep 21 release won't go out until the afternoon.

So if we were to land this change in the next two weeks, as I imagine is likely, that customer will get an unfortunate bit of whiplash.

I'm inclined to say that we should just plan to onboard that customer with the Sep 20 canary. That gives us two weeks to get these sink changes in without causing whiplash.

**Comment by bkirwi** [comment]
Re: Slack discussion, seems like we're going with the plan above -- should give us a little more time to tidy up without delaying onboarding for the user.
