### ISSUE TITLE
Progress topics can collide when multiple environments share a Kafka cluster

### ISSUE THREAD

**Issue by bkirwi** [MaterializeInc/materialize#14728]
### What version of Materialize are you using?

0.26.1-dev

### How did you install Materialize?

Built from source

### What is the issue?

By default, our new progress-tracking topics have the form `_materialize-progress-$ID`, where ID is the id of the connection. This allows us to share the same topic broadly within a source, but not have different sources collide.

However, this does not prevent collisions when multiple Materialize instances share the same cluster, and happen to allocate Kafka connections with the same ID. Normally this would be very rare... but it's somewhat more likely to happen in testing, where environments are frequently recreated without necessarily clearing Kafka state.

This issue was discussed at https://github.com/MaterializeInc/materialize/issues/14488#issuecomment-1239960697. Two viable approaches:
1. Generate a random nonce, and persist it as part of the sink DDL. (Maybe via purification?)
2. Hash the environment id and connection id. Nicely deterministic without needing persistence, but requires threading the environment id from the cloud layer through to the code that references the topic, which may be a significant lift.
3. The hybrid option: choose the topic as in 2, but persist it in the DDL as in 1. Still some environment threading, but less, and may help guard against errors if we pass in the wrong id from the environment or whatever.

Whether random or hashed, [the nonce doesn't need to be too large to be quite protective](https://en.wikipedia.org/wiki/Birthday_problem#Probability_table): sixteen hex chars would be enough to give a one-in-a-billion chance of collision for someone who pointed ~200k materialize instances at the same Kafka cluster.

**Comment by bkirwi** [comment]
Currently inclined to start with 1 and then evaluate 3; 1 seems quickest, and switching to 3 afterwards wouldn't cause any compatibility problems. Don't feel that strongly, though!

**Comment by aljoscha** [comment]
> Currently inclined to start with 1 and then evaluate 3; 1 seems quickest, and switching to 3 afterwards wouldn't cause any compatibility problems. Don't feel that strongly, though!

That sounds reasonable!

**Comment by benesch** [comment]
> Hash the environment id and connection id.

Any reason to hash it? I like the idea of just including the UUID and connection ID directly, e.g. `_materialize-progress-f3937e0a-d3d8-486e-82c1-ee0e8e19a46a-u10`. Might up being useful to someone downstream to be able to determine what Materialize environment a given progress topic belongs to.

**Comment by benesch** [comment]
One thing that's going to be difficult about (3), but not about (2), is that the connection ID is not known at purification time.

**Comment by benesch** [comment]
I just sent up https://github.com/MaterializeInc/materialize/pull/14752, which plumbs the environment ID around. That should make (2) much easier.

**Comment by bkirwi** [comment]
> Any reason to hash it?

Two not-very-strong ones:
- Shorter. (The topic name ends up about half as long.)
- Avoids exposing the implementation detail, in case it's something we didn't want users to rely on.

I don't feel especially strongly, and even the long version is much shorter than the max topic name length.

> One thing that's going to be difficult about (3), but not about (2), is that the connection ID is not known at purification time.

Point! That also means that going 2->3 won't be an option, so we need to be pretty confident that whatever format we settle on is something we're comfortable with ~indefinitely.

Am I right that you're leaning hard towards (2)? If so I'll close down my draft of (1) at https://github.com/MaterializeInc/materialize/pull/14744

**Comment by benesch** [comment]
> > One thing that's going to be difficult about (3), but not about (2), is that the connection ID is not known at purification time.
> 
>
> Am I right that you're leaning hard towards (2)? If so I'll close down my draft of (1) at #14744

Yes, but only because of the fact that the connection ID isn't available at purification time! Until I realized that, I agreed that (1) seemed like a useful waypoint to (3).

> That also means that going 2->3 won't be an option, so we need to be pretty confident that whatever format we settle on is something we're comfortable with ~indefinitely.

If it's any relief, it's a _little_ less dire than that! We just need to figure out how to write down the current format before we change it. Then we could do an evolution in two steps. Version 1 would write the current format into the catalog for all new and existing connections. Version 2 would change the default format computation.
