### ISSUE TITLE
Flakes due to cockroach not starting up properly: "cannot dial server"

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#14732]
### Buildkite link

https://buildkite.com/materialize/nightlies/builds/1140#_

### Relevant log output

```source
platform-checks-materialized-1     | ERROR: cannot dial server.
platform-checks-materialized-1     | Is the server running?
platform-checks-materialized-1     | If the server is running, check --host client-side and --advertise server-side.
platform-checks-materialized-1     | 
platform-checks-materialized-1     | read tcp 127.0.0.1:45700 -> 127.0.0.1:26257: i/o timeout
platform-checks-materialized-1     | Failed running "sql"
```

### Additional thoughts

The error log lines above come from the cockroach instance inside the environmentd container , not from Mz or environmentd itself.

**Comment by philip-stoev** [comment]
@mjibson FYI

**Comment by mjibson** [comment]
The logs suggest that mz needs to wait longer for cockroach to start up. For example, the error here is produced before the final log from cockroach. Might need to add a wait step in the common mz startup function.

**Comment by philip-stoev** [comment]
@mjibson from my reading of the documentation `cockroach start-single-node` only returns after the database is able to accept SQL connections ?

**Comment by mjibson** [comment]
Hmm yes that does appear to be the case. Then I'm very confused by the buildkite logs that have some cockroach log messages after the complaint about the address not being dialable.

**Comment by uce** [comment]
@chaas I've put this on the surfaces project to triage.

**Comment by chaas** [comment]
@philip-stoev is this still happening?

**Comment by benesch** [comment]
Optimistically closing this. I don't believe we've seen this in a long time.
