### ISSUE TITLE
Allow column selection on `CREATE VIEWS FROM SOURCE`

### ISSUE THREAD

**Issue by rotten** [MaterializeInc/materialize#14749]
### Feature request

Most of the time we don't need all of the columns in the source table.  As postgresql 15 rolls out, we will be able to configure logical replication on the postgresql server for selected columns.  Meanwhile, some of us could be stuck on older postgresql versions for years to come.

It would be great if we could add column lists to the CREATE VIEWS FROM SOURCE command that throws away the unwanted columns as the changes are read in.

In addition to having tables with 200 columns, and only need 3 of them in materialize, we have some tables with data types that are not supported in Materialize.  Being able to discard the columns with the unsupported data types instead of having to discard the whole table would be super useful.

**Comment by ggnall** [comment]
cc: @nmeagan11

**Comment by aljoscha** [comment]
This doesn't exist anymore, Postgres sources work differently now.
