### ISSUE TITLE
reuse_topic = true (bug?)

### ISSUE THREAD

**Issue by maqroll** [MaterializeInc/materialize#14780]
### What version of Materialize are you using?

 v0.26.4 (8e291a468)

### How did you install Materialize?

APT package

### What is the issue?

Following pipeline (number of different sessions per store over last five minutes) behaves totally different wether the sink is configured with reuse_topic or not.

```
CREATE SOURCE hits_raw
FROM KAFKA BROKER '__BROKER__' 
TOPIC 'mz_issue'
WITH (
  "security_protocol" = 'SASL_SSL',
  "sasl_mechanisms" = 'PLAIN',
  "sasl_username" = '__USER__',
  "sasl_password" = '__PWD__',
  "kafka_time_offset" = -300000
)
FORMAT BYTES;


CREATE MATERIALIZED VIEW hits_last_five_minutes AS
SELECT 
        session_id
        ,store_id
        ,ts
  FROM (
    SELECT 
      DATA->>'sessionId' AS session_id,
      (DATA->>'storeId') AS store_id,
      (DATA->>'ts')::double::bigint AS ts
    FROM ( 
      SELECT 
        CAST(convert_from(DATA, 'utf8') AS jsonb) AS DATA
      FROM hits_raw
    )
  )
  WHERE mz_logical_timestamp() < ts + 300000 AND mz_logical_timestamp() >= ts;

CREATE MATERIALIZED VIEW unique_sessions_last_five_minutes AS
SELECT 
        sum(sessions)::int as total_sessions,
        jsonb_agg(jsonb_build_object('store_id',store_id,'count',sessions::int) ORDER BY sessions DESC) as sessions
FROM (
        SELECT country.store_id store_id, sessions.unique_sessions sessions FROM
            (SELECT DISTINCT store_id FROM hits_last_five_minutes where store_id IS NOT NULL) country
            ,LATERAL (
                SELECT count(distinct session_id) as unique_sessions FROM hits_last_five_minutes
                WHERE store_id = country.store_id
            ) sessions
);

```

I feed the source topic with (one hit per second):

`while true; do date +%s000; sleep 1; done | awk '{print "{\"ts\":"$0", \"sessionId\":\""$0"\", \"storeId\":\""$0"\"}"}' | kcat -t mz_issue`

If reuse_topic = true, 

```
CREATE SINK sessions_sink
FROM unique_sessions_last_five_minutes
INTO KAFKA BROKER '__BROKER__' TOPIC 'mz_sessions'
KEY(total_sessions)
CONSISTENCY (TOPIC 'mz_sessions_consistency'
             FORMAT AVRO USING CONFLUENT SCHEMA REGISTRY '__SR__')
WITH ("security_protocol" = 'SASL_SSL',
  "sasl_mechanisms" = 'PLAIN',
  "sasl_username" = '__USER__',
  "sasl_password" = '__PWD__',
  "partition_count" = 1,
  "retention_ms" = 3600000,
  "reuse_topic" = true)
FORMAT AVRO USING CONFLUENT SCHEMA REGISTRY '__SR__'
ENVELOPE UPSERT WITHOUT SNAPSHOT;
```

both memory and number of arrangement records grows (even if 5 minute sliding window caps the total number of hits).

![image](https://user-images.githubusercontent.com/415742/189705223-4c9bc123-f62e-44a5-8d0f-839b5e9b4c1b.png)

![image](https://user-images.githubusercontent.com/415742/189705296-beb02ee9-4ce0-4d31-b2c9-a7d7004c132b.png)

![image](https://user-images.githubusercontent.com/415742/189705415-e43bb53f-42ab-4068-bf22-15fd147e36ab.png)

The same pipeline with reuse_topic = false
```
CREATE SINK sessions_sink
FROM unique_sessions_last_five_minutes
INTO KAFKA BROKER '__BROKER__' TOPIC 'mz_sessions'
KEY(total_sessions)
WITH ("security_protocol" = 'SASL_SSL',
  "sasl_mechanisms" = 'PLAIN',
  "sasl_username" = '__USER__',
  "sasl_password" = '__PWD__',
  "partition_count" = 1,
  "retention_ms" = 3600000,
  "reuse_topic" = false)
FORMAT AVRO USING CONFLUENT SCHEMA REGISTRY '__SR__'
ENVELOPE UPSERT WITHOUT SNAPSHOT;
```
, keeps both memory and number of arrangement records stable (in line with the input data).

![image](https://user-images.githubusercontent.com/415742/189705907-521dad3d-8e25-46ad-bc9e-38ac0cc73a6b.png)

![image](https://user-images.githubusercontent.com/415742/189706079-5a5e5fad-2abd-49e4-906b-f91b23e5da93.png)

![image](https://user-images.githubusercontent.com/415742/189707030-28d59ee6-7a87-47ff-b168-8e8dda11df3b.png)

![image](https://user-images.githubusercontent.com/415742/189718223-561fcde5-ca8e-4cbc-80b6-8a0f3b95acf2.png)

Both ensembles report accurate results.
I couldn't find any explanation for this behaviour in the docs. .

**Comment by bkirwi** [comment]
A puzzling behaviour!

At the timely-dataflow level, `reuse_topic` shouldn't have had an effect on the structure of the computation... only the performance. You'd expect some increase in memory usage etc. with `reuse_topic=true`, since the transactional producer is both marginally slower and occasionally has to pause during transaction commit. However, that shouldn't cause asymptotically different behaviour in the arrangements themselves. (Though from the charts above it's not totally clear that the behaviour is indeed asymptotically any different... the absolute numbers are pretty small.)

This issue doesn't have a direct equivalent in the platform version of Materialize, since the Kafka sinks and the arrangements in the view are in different processes, so the former can no longer impact the latter. I haven't looked into what the current behaviour of today's Materialized views is yet, though.

**Comment by nmeagan11** [comment]
Moving to the compute project board as we think this might be a compute issue (see @bkirwi's analysis above).

**Comment by antiguru** [comment]
Moving to the icebox because `reuse_topic=true` is the default, and we haven't observed this behavior in the new architecture with separate storage processes.

**Comment by benesch** [comment]
Marking as closed because we have many customers successfully using sinks in the new architecture, and `reuse_topic` is the _only_ supported behavior.
