### ISSUE TITLE
 Checks + DROP/CREATE replica: panicked at 'RehydratingStorageClient received FrontierUppers response for absent identifier

### ISSUE THREAD

**Issue by antiguru** [MaterializeInc/materialize#14791]
### Buildkite link

https://buildkite.com/materialize/tests/builds/41280#01832f00-d497-494b-a464-baddd0f877c2

### Relevant log output

```source
platform-checks-materialized-1      | environmentd: 2022-09-12T00:33:54.979122Z  INFO mz_adapter::catalog: drop source materialize.public.sink_view1 (u203)
platform-checks-materialized-1      | thread 'tokio:work-1' panicked at 'RehydratingStorageClient received FrontierUppers response for absent identifier u203', /var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0cae970e2a6f5e9a4-1/materialize/tests/src/storage/src/controller/rehydration.rs:309:25
```

### Additional thoughts

It seems this is a race condition where `environmentd` drops a source, cleans up its internal state and then receives a `FrontierUpper` for the source that was just dropped. This is fine because it's a correct interleaving of events. The error is that the storage controller assumes this situation cannot happen.

**Comment by aljoscha** [comment]
@antiguru did you see this recently? I think it can't happen anymore because we now only remove things from `self.uppers` when the worker instance reports back that dataflows (for IDs) have been dropped.

**Comment by antiguru** [comment]
Closing because the code has changed substantially.
