### ISSUE TITLE
storage: ingestion rate decreases over time

### ISSUE THREAD

**Issue by uce** [MaterializeInc/materialize#14798]
### What version of Materialize are you using?

v0.27.0-alpha.20 (9db27abd5)

### How did you install Materialize?

Materialize Cloud

### What is the issue?

(reported by @joacoc)

Joaquin ran an experiment that shows the data ingestion rate decreasing over time.

<img width="835" alt="Screen Shot 2022-09-13 at 11 12 14" src="https://user-images.githubusercontent.com/1756620/189960074-90c01ec6-2907-4ab7-a5a0-cc7a410f41c8.png">

**Setup**
- ~7.5M events (~22 GB data) from a pre-hydrated, static, single partition Kafka topic (i.e. no new data is being pushed into the topic while Materialize ingests)
- `ENVELOPE NONE`, `FORMAT BYTES`
- `XLARGE` cluster
- X axis is time
- Y axis is number of consumed events

**Expectation**
- The data ingestion rate should be somewhat constant while we read data in, i.e. we expect to a straightish line in the above figure

**Actual**
- We see the expected behavior during the first minute of ingestion
- Afterwards, there are repeated stretches of time when the number of consumed events stays constant (e.g. the ingestion rate gets close to zero?)

### Relevant log output

```source
–
```

### Context

https://materializeinc.slack.com/archives/CU7ELJ6E9/p1663080494658249

**Comment by andrioni** [comment]
Some initial investigation:
- Looking at [Grafana](https://g-2531aff0fb.grafana-workspace.us-east-1.amazonaws.com/d/m3U1U6ZVk/persist?orgId=1&var-datasource=cloud-production%20us-east-1&var-env=environment-23f2707d-5cbd-470c-8fd4-b2211c1d4a26-0&var-pod=All&var-shard=All&from=1663077553460&to=1663084254619), it does not seem that we are throttled on S3 operations: no errors are logged, max throughput is 11 MB/s.
- [CPU and memory utilization](https://ui.honeycomb.io/materialize/datasets/production.kubernetes-metrics/result/rntnwiLHjcQ?omitMissingValues) on `storaged` seemed completely fine as well: CPU never went even above 50%, memory never went above 4GB.

**Comment by dseisun-materialize** [comment]
Intuitively this feels like it must not be an issue given the scale of customers using materialize, but @aljoscha do you have any more recent context here?

**Comment by aljoscha** [comment]
I don't have recent context but no-one complained about it for quite some time now, so ... :man_shrugging:

**Comment by dseisun-materialize** [comment]
Going to close for now then
