### ISSUE TITLE
More graceful termination for storaged with the process orchestrator

### ISSUE THREAD

**Issue by andrioni** [MaterializeInc/materialize#14807]
Currently the process orchestrator SIGTERMs `storaged` processses when needed: while this is fine, in some cases (e.g. when running SSH tunnels) this can leak processes.

An alternative here would be to add a signal handler to clean up anything needed before exiting the process.

**Comment by benesch** [comment]
Closing as wontfix. While it would indeed be nice to prevent processes from leaking, it can't happen in production with the Kubernetes orchestrator, and I don't want to spend undue time on the process orchestrator.
