### ISSUE TITLE
storage: rename `ENVELOPE DEBEZIUM UPSERT` to `ENVELOPE DEBEZIUM`

### ISSUE THREAD

**Issue by benesch** [MaterializeInc/materialize#14805]
### Feature request

In Materialize Platform, we have shipped `ENVELOPE DEBEZIUM UPSERT` and no longer have near-term plans to support [`ENVELOPE DEBEZIUM`](#13310). So we propose to rename `ENVELOPE DEBEZIUM UPSERT` to `ENVELOPE DEBEZIUM`. Here's why:

  * `ENVELOPE DEBEZIUM UPSERT` implies the existence of a non-upsert Debezium envelope. But that won't exist for the next few months _at least_. By rebranding `DEBEZIUM UPSERT` as simply `DEBEZIUM`, we make things more logical and straightforward for our users. There is one obviously named option to use with Debezium data.
  * "Upsert" is a leaky implementation detail in this context—it describes how we're internally performing Debezium deduplication. But users don't care! They just want to tell us that the data is in "Debezium format", and have us sort it out.
  * When we get around to building ordered deduplication (i.e., what's currently called `ENVELOPE DEBEZIUM`), I think the odds are good that we can figure out how to enable it automatically iff a user is using a sufficiently new version of Debezium. In this case it will not require dedicated syntax. If we _really_ need to expose a manual toggle between our current upsert-based deduplication logic and something new, we can introduce syntax like `ENVELOPE DEBEZIUM (deduplication_mode = 'legacy-upsert')`, or something like that—but we'd expect 99% of users to never have to touch that option.

@nmeagan11 @morsapaes did I capture our conversation correctly? Also, @nmeagan11, wasn't sure how to prioritize this or link it into an epic. Ideally it goes into our next breaking change release on 9/28.

cc @uce @brennanvincent

**Comment by uce** [comment]
@brennanvincent I've tentatively assigned this to you. If it's straight forward enough that someone from storage can handle this, feel free to push it back to me. We can either prepare the PR early and leave it open until the week of the release or work on this closer to the release date. Is there another way to make sure it merges at the right time that I'm not seeing?

**Comment by benesch** [comment]
You can add it to the release playbook! https://www.notion.so/materialize/Playbook-3827577236a44cc39b885116554cf200#7c6cfc02733b4454ae7469dc284d87b8

**Comment by morsapaes** [comment]
> @nmeagan11 @morsapaes did I capture our conversation correctly?

💯, @benesch!

Since we're revisiting `ENVELOPE DEBEZIUM`, one thing that popped into my mind was whether this also impacts the expected behavior of `ENVELOPE DEBEZIUM` in the context of sinks (if this is still the default envelope there; I'm slightly out of the loop with the recent sink refactor).

**Comment by benesch** [comment]
> Since we're revisiting `ENVELOPE DEBEZIUM`, one thing that popped into my mind was whether this also impacts the expected behavior of `ENVELOPE DEBEZIUM` in the context of sinks (if this is still the default envelope there; I'm slightly out of the loop with the recent sink refactor).

It is still the default sink envelope. Don't think there's anything to do there, though—`ENVELOPE DEBEZIUM UPSERT` on sinks has never been supported

https://github.com/MaterializeInc/materialize/blob/1866e14c33fb4f37c60915a14b019db8304e2697/src/sql/src/plan/statement/ddl.rs#L1888

Just another reason that killing `ENVELOPE DEBEZIUM UPSERT` is a good move, IMO.

**Comment by aljoscha** [comment]
I think `ENVELOPE DEBEZIUM UPSERT` for sinks would never be a thing. `DEBEZIUM UPSERT` just changes how the source interprets the data. The producer of the data doesn't care (much) how it will be consumed.

**Comment by benesch** [comment]
Fixed by https://github.com/MaterializeInc/materialize/pull/14873.
