### ISSUE TITLE
sql: consider renaming `TAIL` to `SUBSCRIBE`

### ISSUE THREAD

**Issue by benesch** [MaterializeInc/materialize#14815]
@frankmcsherry proposed on Slack a while back that we consider renaming `TAIL` to `SUBSCRIBE`:

> Related to maybe repurposing CREATE MATERIALIZED ..., are there other things we might want to change before GA? One that leaps to mind is that TAIL is perhaps surprising to anyone not familiar with tail -f, and something like `SUBSCRIBE` could make more sense / line up with other systems. No thoughts myself, only that it felt weird that we were thinking of having COMPUTE use `Subscribe` to avoid name collision, and that seems like a better term for ADAPTER.

—https://materializeinc.slack.com/archives/C015RHB3LDR/p1657466645177949

I'd like us to consider this seriously before we commit to backwards compatibility on October 12.

cc @sjwiesman @morsapaes

**Comment by rjnn** [comment]
Why not both?

**Comment by benesch** [comment]
> Why not both?

This is our one chance to not have to litter the docs with "`SUBSCRIBE` (nee `TAIL`)"!

**Comment by hlburak** [comment]
I like the current terminology and find it pretty apt, even as a non-engineer. It might also be useful to keep the term "subscribe" free in the user-facing context for future, undeveloped use cases (alerts?).

Not a strongly held opinion though.

**Comment by benesch** [comment]
> It might also be useful to keep the term "subscribe" free in the user-facing context for future, undeveloped use cases (alerts?).

A slightly expanded version of `TAIL` _is_ the plan for alerting use cases. This strikes me as further evidence that `SUBSCRIBE` is the right name!
