### ISSUE TITLE
doc/user: document `ALTER CONNECTION`

### ISSUE THREAD

**Issue by morsapaes** [MaterializeInc/materialize#14879]
### Documentation request

#14197 implemented key rotation via `ALTER CONNECTION`, but this command is undocumented.

### Related work

* [SSH tunnels design document](https://www.notion.so/materialize/SSH-tunnels-ce8459f2265e4e46bf94929188b91d95#5f6c26a3077a44eab3eed76fb42a9cd6)

**Comment by alex-hunt-materialize** [comment]
I'm not sure `ALTER CONNECTION` exists at all. If it ever does exist, we'll need to also add support for modifying VpcEndpoints in the cloud repo.

**Comment by morsapaes** [comment]
Sorry, I don't think I follow, @alex-hunt-materialize! It was implemented in the issue mentioned above, and seems to still be in the code ([example](https://github.com/MaterializeInc/materialize/blob/be3f6295ff4ab2bc6a65e8b058934e599575e099/src/sql-parser/src/ast/defs/statement.rs#L1386))?

**Comment by alex-hunt-materialize** [comment]
Hmm, I stand corrected. Matt and I couldn't find it they other day, and assumed it wasn't implemented.

**Comment by morsapaes** [comment]
Documented in https://materialize.com/docs/sql/alter-connection/.
