### ISSUE TITLE
doc/user: Update RDS Guide to cover SSH Tunnel Process

### ISSUE THREAD

**Issue by ruf-io** [MaterializeInc/materialize#14871]
### Documentation request

Update RDS guide here: https://materialize.com/docs/unstable/integrations/aws-rds/ to document steps for setting up ssh tunnel connection.

**Comment by morsapaes** [comment]
Thanks, @ruf-io! Also needs to be updated for [Cloud SQL](https://materialize.com/docs/integrations/gcp-cloud-sql/) and [Aurora](https://materialize.com/docs/integrations/aws-aurora/).

**Comment by morsapaes** [comment]
Linking this [💯 guide](https://materialize.notion.site/Postgres-SQL-w-Bastion-SSH-9c0bae3fe6214926bfc39f2fa69e885f) that should be replicated in the documentation.

**Comment by jseldess** [comment]
Fixed by https://github.com/MaterializeInc/materialize/pull/19453.
