### ISSUE TITLE
improve developer experience for kafka connection object

### ISSUE THREAD

**Issue by sjwiesman** [MaterializeInc/materialize#14906]
### Feature request

The kafka connection object supports two ways of specifying your brokers. 

`BROKER` which accepts a single broker
`BROKERS` which accepts a list of one or more brokers in a comma-separated list

any real-world usage of Kafka requires the listing of multiple brokers for redundancy. the issue is the first option `BROKER` will accept any string (including a comma-separated list) and then fail silently. this will be improved when we surface source errors but it feels needlessly complicated to be more grammatically correct. we should either drop `BROKER` entirely or eagerly validate the input and fail with a proper error message if it contains a comma.

**Comment by sploiselle** [comment]
This is already the experience on `main`:

```
materialize=> CREATE CONNECTION foo FOR KAFKA BROKER = 'foo,bar';
ERROR:  invalid CONNECTION: cannot specify multiple Kafka broker addresses in one string
```

What did you use as input that permitted this to proceed w/ creating the source?

**Comment by sploiselle** [comment]
@heeringa `BROKERS` is already supported

**Comment by sjwiesman** [comment]
Hmm. That is not what we experienced on platform yesterday. Let me take a closer look and get back to you.

**Comment by sjwiesman** [comment]
Oh, you know what, we say that error and just assumed multiple brokers were not supported at all. I'm going to update this ticket to change the error message to direct users towards `BROKERS`.
