### ISSUE TITLE
storage: prevent selecting from a non-snapshotted pg source

### ISSUE THREAD

**Issue by guswynn** [MaterializeInc/materialize#14914]
Before platform, select's against pg sources had to wait until the snapshot is finished. Currently, select's now instantly return empty.

This is a sub-optimal UX, and forces us to deal with certain tests with sleeping (see https://github.com/MaterializeInc/materialize/pull/14893), so we should restore the old behavior

original flake issue: https://github.com/MaterializeInc/materialize/issues/14861

**Comment by dseisun-materialize** [comment]
@petrosagg seems like potential dupe of https://github.com/MaterializeInc/materialize/issues/11632

**Comment by sploiselle** [comment]
@petrosagg Is this correctness property 2 or 5? Can we close this?

**Comment by benesch** [comment]
> @petrosagg seems like potential dupe of #11632

Yeah, looks like a dupe of correctness property #2. Closing in favor of #11632.
