### ISSUE TITLE
`mzcli` should be named `mzctl`?

### ISSUE THREAD

**Issue by chaas** [MaterializeInc/materialize#14921]
Suggestion from @rjnn .

**Comment by benesch** [comment]
I'm not sure I understand! It's not named `mzcli`? It's named `mz`.

**Comment by ggnall** [comment]
Let's keep `mz`. Some open q's on repo name, and "marketing" name in this spec https://www.notion.so/materialize/Reintroduce-mz-00b684e3de7a416ca01e15464dd7313e
