### ISSUE TITLE
persist: quiesence of adapter-controlled collections' uppers' advancement

### ISSUE THREAD

**Issue by sploiselle** [MaterializeInc/materialize#14927]
### Feature request

@danhhz recently [mentioned](https://materializeinc.slack.com/archives/C01CFKM1QRF/p1663687731681819) that a lot of traffic to persist comes from simply bumping the timestamp of collections every second; not meaningful work, but is instead potentially/probably useless accounting.

I have a design doc for this [internally](https://www.notion.so/materialize/Quiesce-timestamp-updates-164ca2342bc14758a31f6cb90323118f)

**Comment by sploiselle** [comment]
Note: the first version of the comment above said we should awaken quiesced collections at the read timestamp; it should instead be at a time beyond the read timestamp.

**Comment by benesch** [comment]
Solved by persist-txn: https://github.com/MaterializeInc/materialize/pull/20954.
