### ISSUE TITLE
Mzcli should use the Apache 2 license

### ISSUE THREAD

**Issue by chaas** [MaterializeInc/materialize#14922]
Investigate which license we are currently using, and if it's not Apache 2 license, we should update it.

**Comment by rjnn** [comment]
just to chime in - what we probably want is to follow the logic behind `doctl` being open-source, and follow that rationale similarly. Apache 2 vs MIT isn't something I have a strong opinion on.

**Comment by chaas** [comment]
Thanks for the context @rjnn ! Sounds good.

**Comment by benesch** [comment]
It's Apache 2.0! https://github.com/MaterializeInc/materialize/blob/367430a16c3bce2e3105775a0307214ac9eec485/src/mz/Cargo.toml#L4

Also noted as such in the license headers.
