### ISSUE TITLE
Revisit internal versioning for persist state

### ISSUE THREAD

**Issue by arusahni** [MaterializeInc/materialize#14924]
### Feature request

When attempting to upgrade environments that are running unstable/development builds to a stable release, `environmentd` fails to start up due to it considering the persist version (`v0.xx.0-dev`) to be newer than the stable version (`v0.xx.0-alpha.xx`). 

> thread 'coordinator' panicked at '0.27.0-alpha.22 received persist state from the future 0.27.0-dev'

This is suboptimal as it can result in a painful upgrade process.

Since deploying dev releases is something we wish to be able to do, we should investigate using an alternate identifier for this version.

[Context in Slack](https://materializeinc.slack.com/archives/CTESPM7FU/p1663791669908779)

**Comment by benesch** [comment]
@danhhz I believe this will be fixed once we're out of previews period. Let's say we're releasing v0.28.0. Here's the release process:

  * Bump main to v0.29.0-dev
  * Cut v0.28.0-rc.1. Validate on canaries.
  * Cut v0.28.0. Roll prod.

If someone deploys latest main to a customer environment during the next week, that's fine. It's safe to upgrade from v0.28.0 -> v0.29.0-dev. It'll also be possible to upgrade v0.29.0-dev to v0.29.0-rc.1/v0.29.0 during the next release.

We could certainly do something more clever. Just wanted to flag that this problem fixes itself even if `persist` does nothing.

**Comment by danhhz** [comment]
I have to disagree a bit with the characterization of this as a persist issue (sorry, Aru, don't mean to nitpick, I appreciate you writing the issue up!). In fact, I think persist did exactly the correct thing here. By policy, we don't allow rollbacks (don't remember if we've written this down anywhere, but I've asked several times). According to semantic versions, 0.27.0-dev orders after 0.27.0-alpha.22 and so going from the former to the latter is a rollback.

My framing of this is that it's a "bug" in the way we're versioning dev releases during previews. IMO versions should sort in the following order:

- release X
- development builds for release X+1
- release X+1

As Nikhil mentions above, we'll have this property (again, we had it in the single binary days) once we get out of previews. 

As for the rest of previews, in practice 2 of the 3 remaining releases are backward incompatibility windows where we'll be wiping anyway. We can avoid doing anything about this "bug" if we're careful the week leading up to the single remaining backward compatible release (oct 5).

> Just wanted to flag that this problem fixes itself even if persist does nothing.

Again, sorry for the nitpick, but even if previews were extending a couple months, I'd argue that persist is doing the correct thing (preventing rollbacks from corrupting prod data). If we were to care about fixing this, I'd say we should come up with a scheme such that dev builds sort correctly during previews.

**Comment by benesch** [comment]
We've fixed the versioning scheme for the rest of previews by introducing a step to bump `main` to `v0.27.0-alpha.X.post` after each release. That will ensure you can upgrade any environment from the current release to the latest unstable version _and_ that you can upgrade any environment from the latest unstable release to the _next_ release.

Sorry for not catching this sooner!
