### ISSUE TITLE
persist: more robust handling of since capabilities

### ISSUE THREAD

**Issue by danhhz** [MaterializeInc/materialize#14949]
### Feature request

At the moment, we treat every ReadHandle's since capability as equal, but this may not be the best framing. During normal operation, the storage controller in environmentd holds back a number of critical since capabilities. If these advance unexpectedly, we may not be able to recover, see #14808 for an example of this in practice. During environmentd cutover (due to crash, release, k8s pod movement, etc), we have the duration of the read lease (15m at the time of writing) to get another copy of it up and register new ReadHandles. If that doesn't happen, we'll see similar problems as 14808.

A possibly better way to handle this is to give each ReaderId its own permanent since hold that never times out. Then, we also allow allow new copies of a ReaderId to fence out old ones with a lesser epoch. This would require (e.g. the storage controller would durably write down ReaderIds along with ShardIds) as well as much more careful usage of persist (a leaked ReaderId would permanently wedge the shard's since). However, it would allow us to remove the dependence on clocks and read lease times entirely. The complexity might be worth the robustness tradeoff, but it's not clear yet. This is something we'll continue to revisit as we get initial production experience running mz cloud.

**Comment by aljoscha** [comment]
Superseded by https://github.com/MaterializeInc/materialize/issues/15511?

**Comment by danhhz** [comment]
Ha, yup!
