### ISSUE TITLE
questdb is a awsome time series database supporting the Postgres wire protocol but it can't be a source  to materialize

### ISSUE THREAD

**Issue by Luyang2902** [MaterializeInc/materialize#14952]
### Feature request

questdb is a awsome time series database supporting the Postgres wire protocol but it can't be a data source for  materialize.

**Comment by rjnn** [comment]
Looking at questdb briefly, they do not appear support CDC in any form (https://github.com/questdb/questdb/issues/2252). That is a hard prerequisite to us implementing that as a direct source.

**Comment by Luyang2902** [comment]
thank you
