### ISSUE TITLE
Make upgrade tests run against last release & prepare to re-enable

### ISSUE THREAD

**Issue by chaas** [MaterializeInc/materialize#14950]
The existing [upgrade tests](https://github.com/MaterializeInc/materialize/tree/main/test/upgrade) are limited in their usefulness because:
1)  In CI they're being run with flag `--most-recent 0`, which means they're only testing upgrading from the current source to the current source.
2) The coverage of tests is likely not comprehensive.

To make these tests more useful we'd like to:
1) Have CI run them against the latest release cut (after the breaking change deadline)
2) Review coverage to ensure key functionality is tested

We might want to update the docs to clarify that the solution to a breaking test is writing a migration.

**Comment by mjibson** [comment]
I think we want something like: make 1 of everything at the most recent wipe'd version and each release tag thereafter, and test that we can upgrade from each version to the next. I also don't have a lot of context on the existing upgrade tests, so probably need to get input from others.

**Comment by philip-stoev** [comment]
The "mzcompose/upgrade" tests are the "old" upgrade tests. The new ones live in the "test/platform-checks" framework and they cover more stuff than the old ones.

Both of those need to be fixed as they currently only perform "upgrade" from current version to the current version :-) I am willing to take up on the tasks for fixing and enabling things, but I will need a clear policy as to what upgrade paths are supported.

**Comment by mjibson** [comment]
> I will need a clear policy as to what upgrade paths are supported

I think this is:

1. First version supported is the most recent release where backward compat is "not required" from https://www.notion.so/materialize/d4b554c5a5f240339985872f04a6aa1e?v=1107e57b8c9342068c707b7693244326 (because all deployments before this version have been destroyed).
2. Test every git tag with a higher version after that.
3. Add the current PR's git commit.

**Comment by benesch** [comment]
I would hesitate to go _too_ deep automating anything about the current state of affairs. After EA, the backwards compatibility is this: **version X must be backwards compatible with version X - 1.** That is, each version must be backwards compatible with just the _one_ preceding version.

**Comment by ggnall** [comment]
More info from @philip-stoev on our two test "styles" and what info is needed for QA to tackle:

A. "Old-style" upgrade tests, in test/upgrade. Those create some database objects using the "older" Mz version, then perform a whole-Mz restart to the "newer" version (that is, the one compiled from the latest main) and then perform some checks if the database objects still work.

To get those running, what is needed is some way to determine what the "older" supported Mz version to upgrade from is. It needs to be uploaded to Docker Hub and we need to be able to calculate its tag somehow. Previously, the versions were nicely numbered and it was possible to determine the version number and fetch it from Docker Hub. With the current "alpha" versions, I am not sure how to determine what the older supported version is.

**The test could previously also use the "latest" tag on DockerHub to fetch the latest relased version, but this tag is not being updated any more.**

B. The "new style" upgrade tests, also known as the "platform checks" framework . It is documented at doc/developer/platform-checks.md and can be used for all sorts of restart testing , including upgrades. The difference from the old style is that the new framework allows for more complex sequences of events, e.g. 1) create some objects 2) restart some part of the Mz instance ; 3) do some more stuff; 4) restart some more and 5) do final validation

**To get those tests to run as upgrade tests, what is needed is 1) again, as before, to know which version to upgrade from and 2) all the supported sequences of events that should be tested, e.g. "restart storaged first, then computed, then environmentd**" . If we do not have an external way to enforce any particular order or set of orders, I will be testing all possible orders, as any may be expected to happen naturally in K8s.

**Comment by ggnall** [comment]
+ @jonathan-k-shapiro @hlburak - these deployment labels and version labels might need to come from Cloud

**Comment by benesch** [comment]
> To get those running, what is needed is some way to determine what the "older" supported Mz version to upgrade from is. It needs to be uploaded to Docker Hub and we need to be able to calculate its tag somehow. Previously, the versions were nicely numbered and it was possible to determine the version number and fetch it from Docker Hub. With the current "alpha" versions, I am not sure how to determine what the older supported version is.

Ah, I actually described this in my last comment!

> After EA, the backwards compatibility is this: version X must be backwards compatible with version X - 1.

This is the release schedule for post EA:

![image](https://user-images.githubusercontent.com/882976/193353326-b22bb690-9f6f-4423-b606-e7a37bba86f1.png)

The list of versions will be derivable from the names of the files in doc/user/content/releases. The `known_materialize_versions` function has already been updated accordingly:

https://github.com/MaterializeInc/materialize/blob/8c4d5370498f2d14b1e5d6b8286c2fdb123f706f/misc/python/materialize/util.py#L31-L32

----

> +@jonathan-k-shapiro @hlburak - these deployment labels and version labels might need to come from Cloud

It's actually the other way around! This repository is the authoritative source on what versions exist, and on what order they must be deployed.

**Comment by philip-stoev** [comment]
@benesch There is a slight problem with the `known_materialize_versions` function. The doc/user/content/releases directory contains a file v0.27.md, but there is no such tag in DockerHub. I guess once v0.27 is released, a v0.28.md file will show up in this directory and the problem will happen again. Ideally `known_materialize_versions` should be `known_released_versions` . Can you suggest a way to achieve that that I could implement?

**Comment by benesch** [comment]
Ah, yes. Let's add a `released: true | false` field to the frontmatter of each page in doc/user/content/releases. We can have the last step of the release process be flipping that bool from false to true. We can also use it to render an "(UNRELEASED)" warning in the docs.

**Comment by philip-stoev** [comment]
Both legacy and new-style upgrade tests are now running in CI. I am closing this ticket as completed and will monitor the situation between this and the subsequent release.

**Comment by benesch** [comment]
Thank you! 🙌🏽
