### ISSUE TITLE
docs: Update Kafka `CREATE SOURCE` documentation

### ISSUE THREAD

**Issue by jkosh44** [MaterializeInc/materialize#14979]
### Feature request

The documentation for creating Kafka sources is a bit out dated and doesn't reflect the current syntax. https://materialize.com/docs/unstable/sql/create-source/kafka/
For example:
- `TOPIC` should be included with the other options.
- `WITH` has been replaced by `LEGACYWITH`

**Comment by andrioni** [comment]
I think `LEGACYWITH` isn't intended to be exposed to customers, and should be removed before we stabilize the syntax.
