### ISSUE TITLE
ci: flake "name is already in use by container"

### ISSUE THREAD

**Issue by teskje** [MaterializeInc/materialize#15000]
### Buildkite link

https://buildkite.com/materialize/tests/builds/42043#01837980-92ee-4ce7-8711-1321ea774119

### Relevant log output

```source
Error response from daemon: Conflict. The container name "/kafka-resumption-schema-registry-1" is already in use by container "38f042c464abd73b8f769b82b48c21a1299d423f5859571167095cf64ae83843". You have to remove (or rename) that container to be able to reuse that name.
mzcompose: test case workflow-default failed: running docker compose failed (exit status 1)
```

### Additional thoughts

This looks very similar to https://github.com/MaterializeInc/materialize/issues/14668. I think the same fix might apply?

**Comment by philip-stoev** [comment]
This has not been seen in a while. We are now applying a more aggressive cleanup of old docker containers at the start of the build.
