### ISSUE TITLE
Investigate whether any non-definite errors are exposed in the source's error collection

### ISSUE THREAD

**Issue by bkirwi** [MaterializeInc/materialize#15061]
#12864 gives us a principled way to expose transient errors for sources and sinks. Sources already have a way to expose definite (persistent, deterministic) errors via the error collection -- we should confirm that we don't include accidentally include any transient errors in that collection, and use the new error reporting mechanism if we do.

**Comment by bkirwi** [comment]
Looks like this is intentionally done here: https://github.com/MaterializeInc/materialize/blob/bfe0ce9c3b3c2ea923c9c278b6583d4ded97b1d2/src/storage/src/source/source_reader_pipeline.rs#L1167-L1186

I've tried changing this in [a draft PR](https://github.com/MaterializeInc/materialize/pull/15172). I'm seeing a few errors; one appears to be an unrelated bug I've exposed, one seems to be a test expectation for the old behaviour that's correctly firing, and one I'm not sure yet. I'll keep digging tomorrow.

**Comment by bkirwi** [comment]
This turned out to be a bit of a rabbit hole! Summary:
- The `SourceError` enum includes a few variants, like IO errors, that are non-definite and certainly shouldn't be included. We plan to deprecate these, and perhaps eventually remove them entirely.
- The only supported source that actually reports errors is the Postgres source. Many of the errors it emits are legitimate: we don't have anything better to do in those conditions than error out the source. (eg. there are invalid contents of the replication log.) However, some possibly-transient errors are likely included; we plan to remove them.

We think source-level errors are probably here to stay. However, they should be at least conceptually retractible, even if we don't have any way to do that yet. Future source errors should be highly-structured errors like we use for eg. decoding errors.

**Comment by nmeagan11** [comment]
@bkirwi checking in on this one - do we want to keep it open, or close out?

**Comment by bkirwi** [comment]
Calling this resolved in #15200!
