### ISSUE TITLE
storage: storaged OOMs if using an S3 back-end, works as expected with the file backend

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#15067]
### What version of Materialize are you using?

environmentd v0.27.0-alpha.22.post (cb86a8d48) listening...

### How did you install Materialize?

Docker image

### What is the issue?

If 100Mb worth of kafka upsert records are repeatedly modified, storaged will stay within reasonable memory if using the file back-end. But when using the `S3` back-end, it will consume enough memory to be OOM killed on an 8Gb machine. Virt will be `37.3g` and RSS will be in excess of 5Gb.

Test case coming up shortly.

**Comment by philip-stoev** [comment]
To reproduce:

1. Start a scratch instance with 8Gb of ram:
```
pstoev@Ubuntu-2004-focal-64-minimal:~/philip-stoev-bounded-memory-usage$ cat misc/scratch/8gb.json 
{
    "name": "c5.xlarge with 8Gb of ram",
    "launch_script": "true",
    "instance_type": "c5.xlarge",
    "ami": "ami-09d56f8956ab235b3",
    "size_gb": 50,
    "tags": {}
}
```
2. Run
```
cd test/bounded-memory
./mzcompose run default
```

Observe that the `storaged` memory goes up and down until it goes to 4Gb and is OOM killed. Observe that the test is unable to complete and OOMs are a repeated occurence:

```
ubuntu@ip-172-31-92-93:~$ sudo dmesg | grep Killed
[  468.356012] Out of memory: Killed process 23537 (storaged) total-vm:7115624kB, anon-rss:4302172kB, file-rss:0kB, shmem-rss:0kB, UID:999 pgtables:11956kB oom_score_adj:0
[  742.230333] Out of memory: Killed process 38868 (storaged) total-vm:6276388kB, anon-rss:4325864kB, file-rss:0kB, shmem-rss:0kB, UID:999 pgtables:10552kB oom_score_adj:0
```

This test reads from Redpanda, which is in C++ and writes to Localstack S3, which is written in Python. I believe the mismatch between reading and writing may be responsible for why storaged goes above the target memory consumption. I guess some sort of backpressure/flow control would be required to keep things running smoothly.

**Comment by danhhz** [comment]
initial thoughts are this is likely a storage backpressure bug more than a persist bug cc @guswynn

**Comment by guswynn** [comment]
I think its definitely possible that this is possible because of localstack slowness as compared to raw files

**Comment by benesch** [comment]
Closing as we seem to have a successful bounded memory test now: https://github.com/MaterializeInc/materialize/pull/16659.
