### ISSUE TITLE
Implement the Full Version of Renditions

### ISSUE THREAD

**Issue by nmeagan11** [MaterializeInc/materialize#15084]
### Feature request

In #12854, we implemented "renditions-lite" via #14001. More concretely, we built a "self-correcting" `persist_sink`, the design of which can be found [here](https://www.notion.so/materialize/distributed-self-correcting-persist_sink-d3d59834ed9d47d397143c738e9d6c9d).

We still have work to be done to fully implement renditions as per our designs. I need to write a lot more here, but for now, this is a placeholder issue.

**Comment by petrosagg** [comment]
Not doing renditions for the moment
