### ISSUE TITLE
persist: source blobs are not cleaned up on DROP SOURCE 

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#15131]
### What version of Materialize are you using?

environmentd v0.27.0-alpha.23.post (87e348f63) listening...

### How did you install Materialize?

Docker image

### What is the issue?

If a source is DROP-ed , the blobs that belonged to it remain in the storage. I gave it 15 min and the data is still there.

To reproduce:

```
$ set key-schema={
    "type": "string"
  }

$ set value-schema={
        "type" : "record",
        "name" : "test",
        "fields" : [
            {"name":"f1", "type":"string"}
        ]
    }

$ kafka-create-topic topic=bounded-memory

$ kafka-ingest format=avro key-format=avro topic=bounded-memory schema=${value-schema} key-schema=${key-schema} repeat=10000000
"${kafka-ingest.iteration}" {"f1": "A1234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890"}

> CREATE CONNECTION IF NOT EXISTS csr_conn
  FOR CONFLUENT SCHEMA REGISTRY
  URL '${testdrive.schema-registry-url}';

> CREATE CONNECTION kafka_conn
  FOR KAFKA BROKER '${testdrive.kafka-addr}';

> CREATE SOURCE bounded_memory_source
  FROM KAFKA CONNECTION kafka_conn (TOPIC 'testdrive-bounded-memory-${testdrive.seed}')
  FORMAT AVRO USING CONFLUENT SCHEMA REGISTRY CONNECTION csr_conn
  ENVELOPE UPSERT

> CREATE MATERIALIZED VIEW bounded_memory_view AS SELECT COUNT(*) FROM bounded_memory_source;

> SELECT * FROM bounded_memory_view;
10000000

> DROP SOURCE bounded_memory_source CASCADE;
```

If the storaged was supposed to clean them up, this is not going to happen as the storaged is no longer running.

**Comment by uce** [comment]
@philip-stoev Duplicat of https://github.com/MaterializeInc/materialize/issues/8185?

This is a known limitation that we'll address soonish. It's possible to detect and delete those blobs after the fact. @pH14, please correct me if I'm wrong.

**Comment by philip-stoev** [comment]
Ok, duplicate.

**Comment by pH14** [comment]
@uce that all sounds right to me -- Dan has been working on https://github.com/MaterializeInc/materialize/pull/14704 which gets us much closer to solving this one, and then we'll need to find a way to ensure we run a cleanup pass
