### ISSUE TITLE
Hydration backpressure: `storaged` crashlooping on ingest of kafka topic with default storage size

### ISSUE THREAD

**Issue by ggnall** [MaterializeInc/materialize#15135]
Memorializing a case from 9/23:

On an intitial ingest of a redpanda kakfa topic with ENVELOPE NONE, FORMAT BYTES:
 
Storaged pod was crash looping due to OOMs. It turns out that it needed at least 14GB of memory. After increasing size, ingest proceeded without crashing, but operation was abandoned by user before completion.

**Comment by ggnall** [comment]
cc @nmeagan11

**Comment by nmeagan11** [comment]
For context, [this](https://www.notion.so/materialize/Flike-62d4099dee214fa79f270718c720afed#5ef353f3f5f443bdb98160c4cdb0e515) was the case.

**Comment by benesch** [comment]
I'm not sure there's much to do here unfortunately? This is "in spec" at the moment. The short-term fix is to expose CPU and memory stats to the user (https://github.com/MaterializeInc/cloud/issues/4120); the long-term fix is to launch auto-scaling sources (kinda tracked in #13870).

**Comment by benesch** [comment]
Oh, or is the contention that this source should _not_ have required 14GB of memory for the particular source definition?

**Comment by ggnall** [comment]
Yes, this was unexpected according to [this thread](https://materializeinc.slack.com/archives/C040490DQ0N/p1663957239400619). We still don't know "why?" or if we need to adjust guidance on sizing for sources.
>is the contention that this source should not have required 14GB of memory for the particular source definition?

Though I'm not 100% sure that we can act on this immediately other than continued testing and monitoring of customer activity.

**Comment by benesch** [comment]
Do we know how many partitions were in this topic? There are at least two known memory issues with sources:

  * We don't have backpressure, so a fast source reader can cause buffers to fill up before we can flush the data to `persist`
  * librdkafka creates a large-ish buffer per topic partition, which can really add up for topics with thousands of partitions.

**Comment by ggnall** [comment]
cc @brennanvincent

**Comment by dseisun-materialize** [comment]
@guswynn not sure if you already have a ticket for hydration backpressure, otherwise happy to make this our anchor ticket until we decide to prioritize it

**Comment by guswynn** [comment]
@dseisun-materialize seems reasonable to me!

**Comment by benesch** [comment]
I'm going to close this in favor of #21989.
