### ISSUE TITLE
Memory visualizers cannot handle multiple clusters and multi-replica clusters

### ISSUE THREAD

**Issue by vmarcos** [MaterializeInc/materialize#15141]
### What version of Materialize are you using?

v0.27.0-alpha.23.post (f72aafbc0)

### How did you install Materialize?

Built from source

### What is the issue?

The memory visualizer, available locally at [port 6876](http://localhost:6876/memory), currently does not support obtaining introspection information from any cluster other than the default one and also is not prepared to handle multi-cluster replicas.

Consider the following scenario. First, we create a cluster with the following commands: 

```
materialize=> CREATE CLUSTER test
  REPLICAS (
    replica_a (SIZE '1'),
    replica_b (SIZE '2')
  );
CREATE CLUSTER
Time: 4027.255 ms (00:04.027)
materialize=> SET CLUSTER TO test;
SET
Time: 0.879 ms
```

Then, we create a few user-level objects in the new cluster so that we can observe introspection data for them:

```
materialize=> CREATE TABLE t (a int);
CREATE TABLE
Time: 129.883 ms
materialize=> CREATE MATERIALIZED VIEW mv AS SELECT * FROM t;
CREATE MATERIALIZED VIEW
Time: 366.471 ms
materialize=> CREATE DEFAULT INDEX ON mv;
CREATE INDEX
Time: 1086.988 ms (00:01.087)
materialize=> CREATE MATERIALIZED VIEW mv2 AS SELECT * FROM t JOIN mv USING (a);
CREATE MATERIALIZED VIEW
Time: 2307.158 ms (00:02.307)
```

To query the introspection sources and views, we can set the appropriate cluster replica with:

```
materialize=> SET cluster_replica = replica_a;
SET
Time: 0.670 ms
```

We expect that there be dataflows for the indexes and materialized views created. As evidenced by the query below, these dataflows produce introspection data that should be visible in the memory visualizer:

```
materialize=> SELECT dod.dataflow_name, dod.name, dod.id, mc.channel_id, dc.from_index, dc.to_index, da.address, da2.address, mc.sent, mc.received
FROM mz_internal.mz_dataflow_operator_dataflows dod,
   mz_internal.mz_dataflow_addresses da,
   mz_internal.mz_dataflow_addresses da2,
   mz_internal.mz_dataflow_channels dc,
   mz_internal.mz_message_counts mc
WHERE dod.dataflow_name LIKE '%mv%' AND
   da.id = dod.id AND
   da.worker_id = dod.worker_id AND
   CAST(da2.address AS text) = CAST(da.address[:list_length(da.address) - 1] as text) AND
   da2.worker_id = da.worker_id AND
   dc.id = da2.id AND
   dc.worker_id = da2.worker_id AND
   (dc.from_index = da.address[list_length(da.address):][1] OR dc.to_index = da.address[list_length(da.address):][1]) AND
   mc.channel_id = dc.id
ORDER BY dod.dataflow_name, dod.name, dod.id, dc.from_index, dc.to_index;
   dataflow_name   |                  name                   | id  | channel_id | from_index | to_index | address  | address | sent | received 
-------------------+-----------------------------------------+-----+------------+------------+----------+----------+---------+------+----------
 Dataflow: 1.3.mv  | Exchange                                | 876 | 877        | 20         | 21       | {6,1,21} | {6,1}   |  693 |      693
 Dataflow: 1.3.mv  | Exchange                                | 876 | 879        | 21         | 22       | {6,1,21} | {6,1}   |  693 |      693
 Dataflow: 1.3.mv  | FlatMap                                 | 874 | 875        | 17         | 20       | {6,1,20} | {6,1}   |  693 |      693
 Dataflow: 1.3.mv  | FlatMap                                 | 874 | 877        | 20         | 21       | {6,1,20} | {6,1}   |  693 |      693
 Dataflow: 1.3.mv  | InspectBatch                            | 871 | 872        | 17         | 18       | {6,1,18} | {6,1}   |  693 |      693
 Dataflow: 1.3.mv  | Map                                     | 878 | 879        | 21         | 22       | {6,1,22} | {6,1}   |  693 |      693
 Dataflow: 1.3.mv  | Map                                     | 878 | 880        | 22         | 19       | {6,1,22} | {6,1}   |  693 |      693
 Dataflow: 1.3.mv  | persist_sink u2 append_batches          | 885 | 886        | 17         | 24       | {6,1,24} | {6,1}   |  693 |      693
 Dataflow: 1.3.mv  | persist_sink u2 mint_batch_descriptions | 868 | 872        | 17         | 18       | {6,1,17} | {6,1}   |  693 |      693
 Dataflow: 1.3.mv  | persist_sink u2 mint_batch_descriptions | 868 | 875        | 17         | 20       | {6,1,17} | {6,1}   |  693 |      693
 Dataflow: 1.3.mv  | persist_sink u2 mint_batch_descriptions | 868 | 886        | 17         | 24       | {6,1,17} | {6,1}   |  693 |      693
 Dataflow: 1.3.mv  | persist_sink u2 write_batches           | 873 | 880        | 22         | 19       | {6,1,19} | {6,1}   |  693 |      693
 Dataflow: 1.3.mv2 | Exchange                                | 977 | 978        | 27         | 28       | {8,1,28} | {8,1}   |  689 |      689
 Dataflow: 1.3.mv2 | Exchange                                | 977 | 980        | 28         | 29       | {8,1,28} | {8,1}   |  689 |      689
 Dataflow: 1.3.mv2 | FlatMap                                 | 975 | 976        | 24         | 27       | {8,1,27} | {8,1}   |  689 |      689
 Dataflow: 1.3.mv2 | FlatMap                                 | 975 | 978        | 27         | 28       | {8,1,27} | {8,1}   |  689 |      689
 Dataflow: 1.3.mv2 | InspectBatch                            | 972 | 973        | 24         | 25       | {8,1,25} | {8,1}   |  689 |      689
 Dataflow: 1.3.mv2 | Map                                     | 979 | 980        | 28         | 29       | {8,1,29} | {8,1}   |  689 |      689
 Dataflow: 1.3.mv2 | Map                                     | 979 | 981        | 29         | 26       | {8,1,29} | {8,1}   |  689 |      689
 Dataflow: 1.3.mv2 | persist_sink u4 append_batches          | 986 | 987        | 24         | 31       | {8,1,31} | {8,1}   |  689 |      689
 Dataflow: 1.3.mv2 | persist_sink u4 mint_batch_descriptions | 969 | 973        | 24         | 25       | {8,1,24} | {8,1}   |  689 |      689
 Dataflow: 1.3.mv2 | persist_sink u4 mint_batch_descriptions | 969 | 976        | 24         | 27       | {8,1,24} | {8,1}   |  689 |      689
 Dataflow: 1.3.mv2 | persist_sink u4 mint_batch_descriptions | 969 | 987        | 24         | 31       | {8,1,24} | {8,1}   |  689 |      689
 Dataflow: 1.3.mv2 | persist_sink u4 write_batches           | 974 | 981        | 29         | 26       | {8,1,26} | {8,1}   |  689 |      689
(24 rows)

Time: 13.654 ms
```

However, if we navigate to the memory or the hierarchical memory visualizers, we cannot see any active user-level dataflow created. The conjecture is that this effect is caused by the visualizers not being cluster-aware.

So this issue is a request to fix the memory and hierarchical memory visualizers so that cluster / cluster replica selections can be made so as to obtain the relevant introspection data for the setup created by the user.

**Comment by benesch** [comment]
I think the fix is to add a "cluster replica" dropdown that shows all the available cluster replicas. When a new replica is selected, any further queries issued by the memory visualizer should change to `SET CLUSTER = <cluster>; SET replica = <replica>; <query>`.

**Comment by chaas** [comment]
Confirmed via debugging that it's because we're only querying the default cluster/cluster replica. I'll go with the "cluster replica" drop down solution.

Our existing SQL HTTP API doesn't allow `SET` commands https://github.com/MaterializeInc/materialize/blob/main/src/environmentd/src/http/sql.rs#L147-L153.
The workaround is we can point at the replica-suffixed tables instead, e.g. querying `mz_arrangement_sizes_2` in your example above, where `replica_a` has replica id 2.

Also, the query that powers the `/memory` page does not return results in your example because it depends on there being records in the materialized view. We need to add records by e.g. running `INSERT INTO t VALUES (9), (8), (7);` to test that page.

As an aside, I've noticed these API requests taking a really long time to return. Is that just because the queries themselves are known to be slow? Would indexing be the solution? I can look into that further after addressing this ticket if it's not already being tracked somewhere.

**Comment by benesch** [comment]
I think it should be fine to allow `SET` statements via the HTTP API. Now that the API supports multiple queries they actually make a lot of sense. They won't be _persistent_ across requests, but they'll apply to any following queries in the same request.

**Comment by vmarcos** [comment]
Agreed with both allowing `SET` statements via the HTTP API and with the `INSERT` to populate the example. It might be a good idea to separate the slowness issue into a separate ticket that we can reproduce independently? That way, we can test the queries also directly via `psql` to try to isolate the issue to the backend only, if that is the case.
