### ISSUE TITLE
Replica isolation is flaky

### ISSUE THREAD

**Issue by aalexandrov** [MaterializeInc/materialize#15167]
### Buildkite link

https://buildkite.com/materialize/tests/builds/42559#0183a3f6-5043-413d-a269-e6171f705fca

### Relevant log output

```source
Ingesting data into Kafka topic testdrive-source1-5 with repeat 1000000
# Received cancellation signal, interrupting
🚨 Error: The command exited with status -1
user command error: The plugin mzcompose command hook exited with status -1
```

### Additional thoughts

The test timed out after 10 minutes, with initial waiting time of ~90 seconds. The retry started after 11 seconds of waiting and finished within 9:30 minutes.

**Comment by philip-stoev** [comment]
The test needs its timeout increased, will do that.
