### ISSUE TITLE
Add a new status shard for sinks

### ISSUE THREAD

**Issue by bkirwi** [MaterializeInc/materialize#15163]
Previous work has added a new persist shard for source errors. We should make sure we do the equivalent for sink errors. (We could share, but it seems easier to multiplex later than to demultiplex if we decide we want to present the status separately.)

**Comment by nmeagan11** [comment]
@bkirwi what's the status of this issue?

**Comment by bkirwi** [comment]
@cjubb39 landed this last week!

**Comment by cjubb39** [comment]
Enabled and put behind unsafe mode in #15744!
