### ISSUE TITLE
Add builtin views to query the current status of a source or sink in `mz_internal`

### ISSUE THREAD

**Issue by bkirwi** [MaterializeInc/materialize#15166]
We're tracking "log" data in the status tables we're creating in #12864, since that preserves the full history of changes to our sources or sinks. However, many users just care about the current status of their data. We plan to expose views over the history tables that present the current status of the underlying table, perhaps with some additional data about the source/sink joined in for convenience.

**Comment by bkirwi** [comment]
These views are merged and available in the `mz_internal` catalog. I'll close this out once the frontend confirms that views include the data they need.

**Comment by RobinClowers** [comment]
@bkirwi This looks good, one question I have is how can we correlate these errors with a specific source (or sink)? I see there is an ID, but `show sinks` doesn't return IDs, so it's unclear how we can map between the two.

**Comment by bkirwi** [comment]
@RobinClowers - two ways:
- The id in the `mz_source_status_history` can be joined against the id in `mz_sources` to get lots of additional information.
- The `mz_source_status` table already does that join and includes additional info like the `name` etc. The intent was for this view to contain everything you'd want to see on the dashboard at a glance before drilling into logs; if it's missing something useful we can likely add it!

**Comment by ggnall** [comment]
Confirming this design is good to go from the surfaces side. cc: @nmeagan11

**Comment by bkirwi** [comment]
Great! Feel free to reopen this if anything comes up.
