### ISSUE TITLE
`current_time()` documented as unmaterializable, but is materializable

### ISSUE THREAD

**Issue by frankmcsherry** [MaterializeInc/materialize#15171]
### What version of Materialize are you using?

main

### How did you install Materialize?

Materialize Cloud

### What is the issue?

The `current_timestamp()` function is (rightly) documented as unmaterializable, but can be materialized, for example like so. I have no idea what this does. 
```
materialize=> create materialized view temp as select 1 where current_timestamp() > current_timestamp();
CREATE MATERIALIZED VIEW
materialize=> 
```

Selecting from the view produces an error, which is great but probably something we should have caught at view formation time:
```
materialize=> select * from temp;
ERROR:  Evaluation error: internal error: cannot evaluate unmaterializable function: CurrentTimestamp
materialize=> 
```

**Comment by ahelium** [comment]
Adding here that SUBSCRIBING to the temp view does not produce an error: 
```
materialize=> COPY (SUBSCRIBE temp) TO STDOUT;
```
Just hangs.

**Comment by mjibson** [comment]
One other thought here: if the original user reporting this was trying to use `current_timestamp()` to a timestamp field, we should produce an error message telling them to use `mz_now()` instead.
