### ISSUE TITLE
Error messages don't refer to usable types

### ISSUE THREAD

**Issue by jamii** [MaterializeInc/materialize#1519]
```
jamie=> select 1::timestamp;
ERROR:  CAST does not support casting from Int32 to Timestamp
jamie=> select 1::Int32;
ERROR:  Unexpected SQL type: Custom(ObjectName([Ident { value: "Int32", quote_style: None }]))
```

```
jamie=> select (1::numeric) || 'foo';
ERROR:  No overload for decimal(10, 0) || string
```

```
jamie=> select (1::numeric) + 'foo';
ERROR:  no overload for string + string
```

There are a bunch of related problems here:

* we often print ScalarType, which doesn't always correspond to a sql type
* the mapping from sql types to ScalarType is not bijective, so if we don't keep track of what the user actually typed we sometimes report a type that is equivalent but that doesn't appear in their query
* when overloading numeric operators, we report the coerced types and not the original types

**Comment by sploiselle** [comment]
Closed by #5175
