### ISSUE TITLE
Limit maximum cluster size

### ISSUE THREAD

**Issue by benesch** [MaterializeInc/materialize#15208]
### Feature request

@TSMaterialize has requested that we limit the maximum size of a cluster available in trials to `large`. 

I think the right way to implement this is as a [system configuration parameter](https://www.notion.so/materialize/Server-configuration-parameters-c9aa8050a2884f67a30b4a34aae2d1bd), which we use for [system limits](https://www.notion.so/materialize/Default-system-limits-f36a447644d9461f8665180fc5d7c505) already. Here's a rough sketch of the design:

  * Add a ` max_cluster_replica_size` system configuration parameter. When set, it names a size in the cluster replica size map. Creating cluster replicas whose size exceeds the maximum size is prohibited, though any cluster replicas that are already in the catalog are grandfathered in. 
  * Deciding whether one size is bigger than another is not entirely trivial, since there are multiple dimensions at play. We can cheat a bit and order by (cpu_limit, memory_limit, workers). That'll work perfectly for our current set of sizes, even though it is not robust against all possible size sets. 
  * Add a `bootstrap-set` command-line flag that sets system parameters on boot if they have not yet been set.
  * Teach cloud to pass `--bootstrap-set=max_cluster_replica_size=large`.

Open questions:

  * Do we want to similarly limit sources to a maximum size? This is somewhat less urgent, because the maximum source size we support at all right now is `large`.

Filing this under the compute team, though a fair amount of the work will fall under the purview of surfaces.

cc @ggnall @chaas @jkosh44 @antiguru

**Comment by heeringa** [comment]
Should we make this an account limit rather than a system limit so we could allow a specific customer to exceed the default max size?  Similar `source_limit` and `sink_limit` in [server configuration design doc](https://www.notion.so/materialize/Server-configuration-parameters-c9aa8050a2884f67a30b4a34aae2d1bd#9602255cb9ae456ea9de04d8f4e3f45d)?

**Comment by antiguru** [comment]
Thanks for bringing this up. It seems like we have different stakeholders that might want to have their own limits. What do you think about this following idea, with this issue being targeted at just the first part:
1. Materialize can impose a `max_cluster_replica_size` limit on a customer, which would only allow a customer to create replicas up to the specified size.
2. The customer can create its own limit strictly strengthening the outer limit for its own accounts. This way a customer could prevent accounts within its organization to consume too many resources.

Another take on limiting the possible instances is to provide an allow-list on top of all possible configurations. This would avoid the quirk of defining an order on replica sizes, where it really is just a partial order.

**Comment by benesch** [comment]
> Should we make this an account limit rather than a system limit so we could allow a specific customer to exceed the default max size? Similar source_limit and sink_limit in [server configuration design doc](https://www.notion.so/materialize/Server-configuration-parameters-c9aa8050a2884f67a30b4a34aae2d1bd#9602255cb9ae456ea9de04d8f4e3f45d)?

Er, sorry, I'm using "system configuration parameter" and "server configuration parameter" interchangeably. The command you type to change a server configuration parameter is `ALTER SYSTEM`—perhaps I should have just committed to calling them "system configuration parameters" from the start. So the proposal is already exactly what you are suggesting!

**Comment by benesch** [comment]
> Another take on limiting the possible instances is to provide an allow-list on top of all possible configurations. This would avoid the quirk of defining an order on replica sizes, where it really is just a partial order.

Now that you mention it, an `allowed_cluster_replica_sizes` parameter of type `text[]` sounds better to me!

**Comment by aalexandrov** [comment]
Also, currently a `SystemVar<V>` needs to be backed by `ServerVar<V>`, so if we want to fit into this design we need to come up with some sensible default for `V` provided by the backing `ServerVar<V>`. Conceptually, using I fell like `V = Option<Vec<String>>` is the right thing to do here, but this does not play nicely with the current code.

**Comment by jkosh44** [comment]
> The current `ALTER SYSTEM` syntax, as well as the one supported by Postgres does not provision for structured values like a list of literals. @benesch: I have to either add those to our `ALTER SYSTEM` parser & planner, or we need to agree on an encoding for allowed_cluster_replica_sizes as a string (maybe comma-separated)?

FWIW, I think that a comma separated list nicely matches the implementation of `SEARCH_PATH` which also uses a comma separated list in PostgreSQL and Materialize.

**Comment by benesch** [comment]
> FWIW, I think that a comma separated list nicely matches the implementation of SEARCH_PATH which also uses a comma separated list in PostgreSQL and Materialize.

You'd think so, but it's so much worse than that:

```
benesch=# create schema a;
CREATE SCHEMA
benesch=# create table a.foo ();
CREATE TABLE
benesch=# set search_path = a;
SET
benesch=# select * from foo;
--
(0 rows)

benesch=# set search_path = 'a, b';
SET
benesch=# select * from foo;
ERROR:  relation "foo" does not exist
LINE 1: select * from foo;
                      ^
benesch=# set search_path = a, b;
SET
benesch=# select * from foo;
--
(0 rows)

benesch=# 
```

PostgreSQL has the notion of sequence-valued parameters, which are kinda comma-separated lists but also very special and horrible. I have a local branch that starts to sort some of this out. 

It's ... probably? ... ok to press forward with the comma-separated string? They are stored on disk as comma-separated strings, but then they get all funky with the `SET` command.

**Comment by aalexandrov** [comment]
I think for this feature I will stick with 

```sql
ALTER SYSTEM SET allowed_cluster_replica_sizes = ['foo', 'bar', 'baz'];
```

which is already supported in the current framework in order to minimize the required changes.

**Comment by benesch** [comment]
> > PostgreSQL has the notion of sequence-valued parameters, which are kinda comma-separated lists but also very special and horrible.
> > I also discovered them yeseterday, 👍 I agree that they are horrible.
> 
> I think for this feature I will stick with this syntax
> 
> ```sql
> ALTER SYSTEM SET allowed_cluster_replica_sizes = ['foo', 'bar', 'baz'];
> ```
> 
> It is already supported in the current framework and seems more consistent with the rest of the SQL parser. It will also allow me get this the PR out faster and with a smaller diff.
> 
> This approach won't solve the `SET search_path` compatibility issue, but since we are going to rethink some of these aspects in #15230, I would rather punt on that within the scope this issue.

Ahh, sorry, weird coincidence, but that syntax _just_ got removed in 52e7b08. That `Value::Array` thing that you're using there is a weird vestige of the original SQL parser that should never have existed in the first place. It's not a thing that PostgreSQL supports. I'd like to avoid introducing our own nonstandard syntax for sequence-valued parameters given how complex the situation already is with PostgreSQL.

**Comment by aalexandrov** [comment]
> * Teach cloud to pass --bootstrap-set=max_cluster_replica_size=large.

I'll open a PR that does the above later today.
