### ISSUE TITLE
Adapter: `environmentd` can OOM when using a combination of `COPY` and `SUBSCRIBE`

### ISSUE THREAD

**Issue by jkosh44** [MaterializeInc/materialize#15202]
### What version of Materialize are you using?

v0.27.0-alpha.24.post

### How did you install Materialize?

Materialize Cloud

### What is the issue?

When running a command like `copy (subscribe my_view) to stdout`, if `my_view` is large enough, then `environmentd` can OOM when trying to form the initial snapshot for subscribe.

Relevant slack discussion: https://materializeinc.slack.com/archives/C03SXGGEN3Y/p1665002913840029

**Comment by mjibson** [comment]
I don't think this is related to COPY. My guess is it can happen with SUBSCRIBE in general: with COPY, without COPY, or DECLARE+FETCH.

**Comment by frankmcsherry** [comment]
I'm going to grab this to try and get it out today.
