### ISSUE TITLE
[Epic] Support dynamic environment configuration

### ISSUE THREAD

**Issue by antiguru** [MaterializeInc/materialize#15230]
Several use-cases require a specific configuration of Materialize, globally or per customer. For example:

-   We might want to impose limits on what resources a customer can allocate, or 
-   We might want to make certain features only available on request. A typical example are alpha-level features that don't yet have the level of support to make them broadly available (such as window functions). 

This issue aims at providing a common mechanism to configure Materialize environments with all its components.

## Goals

Design and implement a mechanism to provide configuration settings to `environmentd` and its dependents. The mechanism should serve as a means to manage configuration parameters both at startup and runtime.

## Tasks

- [x] #15954
- [x] #15955
- [x] #15956
- [x] #16583
- [x] #16586
- [x] #16621
- [x] #16249
- [x] #16765
- [x] #16708
- #16620
- [x] https://github.com/MaterializeInc/cloud/pull/5160

## External Issues

- launchdarkly/rust-server-sdk#29
- launchdarkly/rust-server-sdk#30

## Related
-   Prior design docs:
    -   [Server configuration parameters](https://www.notion.so/materialize/Server-configuration-parameters-c9aa8050a2884f67a30b4a34aae2d1bd)
    -   [Default system limits](https://www.notion.so/materialize/Default-system-limits-f36a447644d9461f8665180fc5d7c505) 
-   [LaunchDarkly](https://launchdarkly.com/) provides an infrastructure to manage flags. It seems to be focused more on front-end features and A/B testing, but it might be a good idea to learn more about it.

**Comment by benesch** [comment]
See also the "alternatives" section of the "Exposing egress IPs" design document: https://www.notion.so/materialize/Exposing-egress-IPs-103cc9f543144fc48f9bf245ce31137a#f425cfc417684f6abbc633e1d76ccfd7

**Comment by lluki** [comment]
Do you think this will be a suitable mechanism to inform processes about the end of a rollback compatible window? (see #14665)

To have a rollback window, all processes are essentially required to behave like one version earlier `vN-1`, until we determine the end of the rollback window, at which point all processes can start acting like `vN` and persisted state can be upgraded to a backwards incompatible form `vN`.

**Comment by benesch** [comment]
> Do you think this will be a suitable mechanism to inform processes about the end of a rollback compatible window? (see #14665)

I think the existing system configuration parameters are probably already sufficient. We can add an `mz_version` parameter that can only ever be incremented. The system itself—or the operator—can be responsible for advancing it during a version upgrade. I don't think we'd want to integrate that parameter with LaunchDarkly, Kubernetes ConfigMaps, or anything else like that.
