### ISSUE TITLE
Support "unmaterializing" a view

### ISSUE THREAD

**Issue by rjnn** [MaterializeInc/materialize#1527]
Currently we have two things: SOURCES and VIEWS. Sources are always unmaterialized (i.e. selecting from them returns an error saying `ERROR: <source> is not materialized`, and views are always materialized (i.e. you can select from them, but they cause arrangements to be maintained, and thus memory to be used on an ongoing basis).

The "best practices" for users, who might both want to have the things they want materialized, as well as maintain the minimal amount of arrangements necessary, are to create a single VIEW that simply extracts the specific thing they want. But this isn't how the natural data exploratory workflow happens. For instance:

I have a JSON source:
```
arjun=> show columns from wm;
 Field | Nullable | Type 
-------+----------+------
 val   | NO       | text
(1 row)
```

When I started this fun project, I had no idea about the data format. So I created a view of the source, paged through a few elements, and saw that it had a highly regular structure.  So I did the natural thing, created a view that just got all the columns out:

```
CREATE VIEW foo AS
SELECT
val->>'$schema' AS schema, 
(val->'bot')::bool AS bot, 
val->>'comment' AS comment, 
(val->'id')::float::int AS id,
(val->'length'->'new')::float::int AS length_new,
(val->'length'->'old')::float::int AS length_old,
val->'meta'->>'uri' AS meta_uri,
(val->'minor')::bool AS minor,
(val->'namespace')::float AS namespace,
val->>'parsedcomment' AS parsedcomment,
(val->'revision'->'new')::float::int AS revision_new,
(val->'revision'->'old')::float::int AS revision_old,
val->>'server_name' AS server_name,
(val->'server_script_path')::text AS server_script_path,
val->>'server_url' AS server_url,
(val->'timestamp')::float AS timestamp,
val->>'title' AS title,
val->>'type' AS type,
val->>'user' AS user,
val->>'wiki' AS wiki
FROM (SELECT val::jsonb AS val FROM wm);
```

Further exploration revealed that what I really cared about was some dashboard about the "user" column, so I created a "user" view just to extract that little column:

```
 create view useredits as select user, count(*)  from foo group by user order by count desc;
CREATE VIEW
```

OK, I have the view, and now turns out I only care about a "top 10 dashboard", so I do a little bit more pruning:
```
CREATE VIEW top10userdashboard AS SELECT * FROM useredits ORDER BY count DESC LIMIT 10
```

And finally, 

```
arjun=> select * from top10userdashboard order by count desc;
       user       | count 
------------------+-------
 "XabatuBot"      | 30900
 "GZWDer (flood)" | 17496
 "SuccuBot"       | 16839
 "Ghuron"         | 12040
 "Mr.Ibrahembot"  | 11967
 "Edoderoobot"    | 11515
 "Mahir256"       |  9004
 "Aosbot"         |  8482
 "Hogü-456"       |  6859
 "RudolphousBot"  |  6682
(10 rows)

Time: 0.777 ms
```

Awesome! This is the dashboard and now I have now decided that this is what I want. I want this view materialized, and now it's time to prune everything else, so that I get the memory footprint down.

```
> top -l1 | grep materialized
60714  materialized     0.0  16:40.21 10    0   31+    802M+ 
```

The problem is there are now a bunch of 'dangling' views which take up memory, and I can't get rid of them. The only thing I can do is to recreate a view DIRECTLY from the source, by manually pasting together everything, and then dropping the source. This is
a) annoying
b) totally not composable if there are, say 10 dashboards I want maintained.

Instead, what I propose is that we add support for the following syntax: we have a boolean field for each VIEW called "MATERIALIZED". Then we support the following syntax to toggle that field:

`ALTER VIEW foo SET materialized = false;`

This should then go ahead and junk all those JSON blobs that are currently sitting in memory and building up over time. It is my understanding, from a conversation with @frankmcsherry that this is totally possible.

As an aside, we should also support setting that field to `true` for sources.

Assigned to @cuongdo for triage.

**Comment by cuongdo** [comment]
Closing because the original requirement for this issue has been satisfied.
