### ISSUE TITLE
Support SHOW ... WHERE ...

### ISSUE THREAD

**Issue by rjnn** [MaterializeInc/materialize#1529]
```
arjun=> show views like '%mz%';
              VIEWS              
---------------------------------
 mz_arrangement_sharing
 mz_arrangement_sizes
 mz_catalog_names
 mz_dataflow_channels
 mz_dataflow_operator_addresses
 mz_dataflow_operators
 mz_materialization_dependencies
 mz_materializations
 mz_peek_active
 mz_peek_durations
 mz_scheduling_elapsed
 mz_scheduling_histogram
 mz_scheduling_parks
 mz_view_foreign_keys
 mz_view_frontiers
 mz_view_keys
(16 rows)
```

```
arjun=> show views not like '%mz%';
ERROR:  sql parser error: Expected end of statement, found: not
```

**Comment by benesch** [comment]
This will be a bit hairy, but doable. These are the things that generally need to happen:

  * A new scope needs to be created that introduces all of the columns in the `SHOW` pseudo relation in the correct order.
  * The WHERE expression needs to be planned against that scope.
  * The WHERE expression needs to be manually evaluated against that scope. Probably the best thing to do is to synthesize a `RelationExpr::Filter`, where the input relation is the constant output of the `SHOW` and the predicate is the WHERE expression, run the optimizer on that expression, assert that the output is a constant, and return that constant. That'll save us from writing the logic for `Filter` in yet another place, and also it doesn't hurt to let the optimizer clean up the WHERE expression a bit.

I think the SQL parsing bit is already done.
