### ISSUE TITLE
test: Fix process orchestrator port re-use

### ISSUE THREAD

**Issue by jkosh44** [MaterializeInc/materialize#15336]
### What version of Materialize are you using?

`main`

### How did you install Materialize?

Built from source

### What is the issue?

In https://github.com/MaterializeInc/materialize/pull/15316/files#diff-818d26f34fdb3ab6b0892e482b0a1231780a2321f7981fc96912e022bc1d6a6d we discovered an issue with the process orchestrator where we were seeing panics from attempting to re-use ports. We made a fix to just kill the existing process and restart it on another port. We should probably figure out why the port re-use was happening in the first place and fix it.

As per the PR comment:
> I also hacked in a fix for the process orchestrator that just kills the existing process and finds it new ports when it falls out of sync during port allocation. This worked well enough in my local testing—and also made the basic case of killall -9 environmentd still work as expected; all clusters are readopted. We should revisit this soon too, though.

**Comment by philip-stoev** [comment]
This is a product-side issue, so I am removing the QA team. A work-around has been implemented on the testing side as https://github.com/MaterializeInc/materialize/pull/15800
