### ISSUE TITLE
Storage sink code doesn't periodically heartbeat the write handle

### ISSUE THREAD

**Issue by petrosagg** [MaterializeInc/materialize#15333]
### What version of Materialize are you using?

a1a8f6ca4cdd495babd2e9c1a960708bd591a08b

### How did you install Materialize?

Built from source

### What is the issue?

Persist handles need regular heartbeats so that they don't expire. This was recently fixed for compute sinks (https://github.com/MaterializeInc/materialize/pull/15198) but the same needs to be done for storage.

### Relevant log output

```source
thread 'timely:work-0' panicked at 'cannot append updates: UnknownWriter(WriterId(d5b55884-7ecc-4600-95ed-8cd373bd2f7d))', src/storage/src/render/persist_sink.rs:187:30
```
```

**Comment by philip-stoev** [comment]
Possibly related:

- #15209

**Comment by cjubb39** [comment]
I _think_ that the Reader issue philip linked above is different (though related!) because this one is about write handles being heartbeated -- and the linked one is about readers, which seem to have this subtle heartbeating -- that's probably better discussed on the other issue
