### ISSUE TITLE
System objects are not correctly handled by SHOW and ALTER statements

### ISSUE THREAD

**Issue by teskje** [MaterializeInc/materialize#15357]
### What version of Materialize are you using?

main

### How did you install Materialize?

Built from source

### What is the issue?

Invoking `SHOW CREATE *` on system objects returns a confusing error message:

```
materialize=> show create source mz_internal.mz_dataflow_channels;
ERROR:  Expected a keyword at the beginning of a statement, found operator "<"
materialize=> show create source mz_internal.mz_dataflow_channels_1;
ERROR:  Expected a keyword at the beginning of a statement, found operator "<"
materialize=> show create source mz_internal.mz_storage_shards;
ERROR:  Expected a keyword at the beginning of a statement, found identifier "todo"
materialize=> show create table mz_tables;
ERROR:  Expected a keyword at the beginning of a statement, found identifier "todo"
```

This is caused by the fact that for these catalog item types we store a `create_sql` value of `"<builtin>"` or `"todo"`, and the planning of the SHOW CREATE command tries to parse this as a SQL string.

-----

Upon further investigation, this is a larger issue around handling of system objects by ALTER commands as well:

All of these crash environmentd with some variation of 
```
called `Result::unwrap()` on an `Err` value: ParserError { message: "Expected a keyword at the beginning of a statement,found identifier \"todo\"", pos: 0 }
```

```
alter table mz_tables rename to foo;
alter source mz_internal.mz_dataflow_channels rename to foo;
alter source mz_internal.mz_storage_shards rename to foo;
alter source mz_internal.mz_storage_shards reset (size);
```

**Comment by jkosh44** [comment]
This is almost certainly due to the fact that system tables hard code the string `"TODO"` as their create SQL statements. Therefore any attempt to parse it will fail.

**Comment by jkosh44** [comment]
`ALTER` should be pretty straightforward to fix, we just need to prevent altering any object in certain schemas. We currently do the same thing for creating objects in `catalog.rs`. Something like
```
                        if let ResolvedDatabaseSpecifier::Ambient = name.qualifiers.database_spec {
                            return Err(AdapterError::Catalog(Error::new(
                                ErrorKind::ReadOnlySystemSchema(name.to_string()),
                            )));
                        }
```
