### ISSUE TITLE
SQL: prevent indexes with no columns

### ISSUE THREAD

**Issue by jkosh44** [MaterializeInc/materialize#15359]
### What version of Materialize are you using?

`main`

### How did you install Materialize?

Built from source

### What is the issue?

In PostgreSQL indexes with no columns are not supported:
```
postgres=# CREATE TABLE t () ;
CREATE TABLE
postgres=# CREATE INDEX t_ind ON t () ;
ERROR:  syntax error at or near ")"
LINE 1: CREATE INDEX t_ind ON t () ;
```
However, in Materialize we allow this:
```
materialize=> CREATE TABLE t () ;
CREATE TABLE
materialize=> CREATE INDEX t_ind ON t () ;
CREATE INDEX
```

We should prevent these indexes to match PostgreSQL behavior.

Discovered in #15344

Note: The current behavior excludes indexes from 0 columns from `SHOW INDEXES`.

**Comment by frankmcsherry** [comment]
I'm not sure we should prevent this. There are legitimate reasons to want to have this / performance we may leave on the table if we prevent this. We have discussed this in the past (years back) and it came down as "not really a problem".

**Comment by chaas** [comment]
What about `CREATE DEFAULT INDEX ON t`?
