### ISSUE TITLE
 Change the replica creation API to return a `oneshot` which can be waited on in a separate thread

### ISSUE THREAD

**Issue by chaas** [MaterializeInc/materialize#15368]
Currently the replica creation request blocks the main coord thread, meaning `SUBSCRIBE` and all other queries hang until the creation is complete (issue #14729). The solution is to move the create replica operation to its own thread.
A blocker for that is the ability to await a response from the replica creation API on a separate thread.

The proposed compute solution is to change the replica creation API to return a `oneshot`.

**Comment by lluki** [comment]
Unfortunately this is not quite done, the compute controller is now able to do this, but the storage controller has (just recently) introduced another code path that does a orchestrator interaction. [See this comment](https://github.com/MaterializeInc/materialize/pull/15467#discussion_r1004487500).

I think we should pass this issue to the storage team.

**Comment by lluki** [comment]
Fixed by #16150
