### ISSUE TITLE
[Epic] Creating a new replica stalls the environment

### ISSUE THREAD

**Issue by antiguru** [MaterializeInc/materialize#15361]
Creating new replicas stalls the environment controller until the replica is created. This is due to the stash and orchestrator interactions that currently happen on the critical path. Specifically, the following actions require interaction with external systems:
* Creating persist shards for writing introspection data
* Interacting with the process orchestrator to acquire resources

#15245 improved the situation, and #15327 can improve it further.

## Tasks

* [ ] Identify the interactions that take significant time and reduce their impact. This can be achieved by optimizing calls, parallelized interactions, or moving interactions off the critical path.

## Acceptance criteria

All cluster should be created within X seconds. The environment should block for the duration of a single stash transaction.

## Related

* #14729

**Comment by chaas** [comment]
FYI we have this existing ticket https://github.com/MaterializeInc/materialize/issues/14729 with some conversation on the issue.

**Comment by antiguru** [comment]
Closed as a duplicate of #14729
