### ISSUE TITLE
mz: users should be able to set a default region 

### ISSUE THREAD

**Issue by rjnn** [MaterializeInc/materialize#15373]
### What version of Materialize are you using?

mz

### How did you install Materialize?

Materialize Cloud

### What is the issue?

just default to the last used region if one isn't specified

**Comment by sjwiesman** [comment]
I think using the last region could be subtle and confusing. how about having a default region similar to the aws cli. 

https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-quickstart.html#cli-configure-quickstart-region

**Comment by rjnn** [comment]
yes, that works too! maybe even an ENV var (eww) would suffice. just some way of "opting out" of specifying the region every single time.

**Comment by joacoc** [comment]
Issue fixed. This is now possible.
