### ISSUE TITLE
Strict serializability disscussion for controller durability features

### ISSUE THREAD

**Issue by jkosh44** [MaterializeInc/materialize#15388]
There are open tasks to implement compute and storage controller durability. The controllers would each use their own separate stash which is also separate from the stash that the Coordinator uses. Splitting up the durable state of a Materialize deployment across multiple separate stashes may open up new vectors of linearizability and fault tolerance issues.

**Comment by benesch** [comment]
Note that storage _already_ has its own stash, as it needs to remember the persist shard ID associated with the global ID for each source. So irrespective of when command durability lands, we should get a handle on this!

**Comment by jkosh44** [comment]
> Note that storage _already_ has its own stash, as it needs to remember the persist shard ID associated with the global ID for each source. So irrespective of when command durability lands, we should get a handle on this!

Can someone link the commit or design doc for this, so we have a reference?

**Comment by benesch** [comment]
I think the best I can do is link you at: https://github.com/MaterializeInc/materialize/blob/46b05715a831fd7843ec903bcf1e7caf42b05d9d/src/storage/src/controller.rs#L723-L726

**Comment by jkosh44** [comment]
I re-read the compute command durability design doc, and since there's no storage command durability design doc I'm going to assume the design would be similar. Here's my thoughts and notes. This focuses on command durability and not the persist shard and global ID mapping. I'll take a look at that later and share my thoughts.


## Design Overview

I will try and outline below what I understood to be the main idea. Currently DDL commands operate in the following way:
1. Command is durably written to (or deleted from) the Coordinator's stash, by the Coordinator.
2. Command is sent to (compute|storage).
3. (Compute|Storage) executes the command.

The Coordinator's stash is considered the source of truth for all commands. If Materialize crashes at any point after step 1, then it will replay the command from the stash (unless the command is a `DROP` which is a known bug). If Materialize crashes at any point before step 1, then the command is considered to have failed. The Coordinator's stash can be thought of as a consensus layer. All commands flow through the stash. If the command is accepted by the stash then the system has reached consensus that the command has/will happen. If the command is rejected by the stash then the system has reached consensus that the command will not happen.

The new logic for DDL Create commands will be:
1. Command is sent to (compute|storage).
2. Command is durably written to (compute|storage)'s stash, by (compute|storage).
3. (Compute|Storage) executes the command.
4. Command is durably written to the Coordinator's stash, by the Coordinator.

The new logic for DDL Drop commands will be:
1. Command is durably deleted from the Coordinator's stash, by the Coordinator.
2. Command is sent to (compute|storage).
3. Command is durably written to (compute|storage)'s stash, by (compute|storage).
4. (Compute|Storage) executes the command.

Now the source of truth is spread out between the compute, storage, and coordinator stashes depending on the type of object. For example indexes' source of truth is the compute stash, tables' source of truth is the storage stash, and function's source of truth is the coordinator stash. After a crash/restart, the list of compute and storage commands and catalog objects are inspected and re-executed to reach a consistent state.

NOTE: Currently the coordinator, storage controller, and compute controller all are part of the same process (`environmentd`). However, my understanding is that there might be some day where we want to separate these out into different processes on potentially different machines. Please correct me if I'm wrong.

I think that in general spreading the source of truth out over three separate durable stores is a bit scary. Below I have a couple of specific concerns/clarifications that I want to bring up.

## Fault Tolerance

For certain objects, such as indexes, I think this is actually fine. If the coordinator or the compute controller crash any time after writing the command in the compute stash, then they can replay the command from the compute stash. If the coordinator crashes before sending the command to compute or the compute controller crashes before writing the command in the compute stash, then the command can be considered as failed.

However for other objects, this isn't as clear. For example Materialized Views have both a storage and a compute component. So what happens if the command is written to the compute stash but not the storage stash, or vice versa? For each object, we could arbitrarily pick either the compute or storage stash to be the source of truth. Depending on what crashes when, the compute controller, storage controller, or coordinator would have to carefully replay commands from some stash. Though this seems easy to get wrong.

## Fencing

Currently fencing is done in the coordinator's stash through an epoch, which indicates the current generation of Coordinators. When a new Coordinator starts, one of the first thing it does is increment the epoch in the coordinator's stash. Every stash modification includes this epoch, if the epoch in the stash and in the modification don't match then the modification is rejected. 

The new design for compute durability has the following potential issue:
1. Coordinator A starts sets the epoch in the coordinator's stash to 1.
2. Coordinator B starts and sets the epoch in the coordinator's stash to 2.
3. Coordinator B creates a new table.
4. Coordinator A sends command to compute controller to create a new index. 
5. Compute controller accepts command, writes it in compute stash, and executes it.

Here we have two different Coordinators interleaving DDL, which might lead to an inconsistent state in the newer Coordinator.

One possibility is for all stashes to have this fencing token. When the Coordinator starts up, it fences off all three stashes, before accepting commands. Some objects might sneak into one of the stashes while the fencing is in progress, and we can consider that object to have been successfully created. However, for some objects this again becomes confusing. If a Materialized View sneaks into the compute stash during fencing but is rejected from the storage stash what do we do? We can take a similar approach to fault tolerance.

## Alternative Approach

I'm not entirely convinced that all of this extra complexity is worth it, though maybe I haven't seen the current motivation behind controller command durability. One alternative solution is to have a single place where all commands are made durable. The Coordinator is responsible for writing down all commands to some durable storage. When a compute controller restarts, it can read all the commands, filter out only the one's it cares about, and replay them. When a storage controller restarts, it can read all the commands, filter out only the one's it cares about, and replay them. When a Coordinator restarts, it can replay all commands and the controllers can use reconciliation to ignore repeat commands. These commands can either be stored in the coordinator's stash or replace the coordinator's stash as the source of truth. This would essentially be a coordinator WAL.

This somewhat accomplishes the goal of having the controllers not rely directly on the Coordinator for re-hydration. Instead they rely on the WAL. Though they are all somewhat coupled in that they must agree on the WAL structure.

In the far distant future, the Coordinator wouldn't even need to send commands to the controllers. The controllers could just constantly tail the WAL. This is similar to the way the FoundationDB Log Server works (https://www.foundationdb.org/files/fdb-paper.pdf)

**Comment by benesch** [comment]
Subscribing @frankmcsherry to this discussion!

**Comment by teskje** [comment]
Thanks for the write-up Joe! Unfortunately, the compute command durability doc is more a brain dump than a design doc, so things are not as clearly states as they should be. I think you mostly interpreted it correctly, except for maybe one detail:

> For certain objects, such as indexes, I think this is actually fine. If the coordinator or the compute controller crash any time after writing the command in the compute stash, then they can replay the command from the compute stash. If the coordinator crashes before sending the command to compute or the compute controller crashes before writing the command in the compute stash, then the command can be considered as failed.
>
> However for other objects, this isn't as clear. For example Materialized Views have both a storage and a compute component. So what happens if the command is written to the compute stash but not the storage stash, or vice versa? For each object, we could arbitrarily pick either the compute or storage stash to be the source of truth. Depending on what crashes when, the compute controller, storage controller, or coordinator would have to carefully replay commands from some stash. Though this seems easy to get wrong.

My idea actually was that the catalog still is the source of truth for what objects exists. The compute/storage stashes would be the source of truth for how objects are defined from a compute/storage pov. But they might contain objects that are not in the catalog, and therefore don't exist. This can happen if environmentd crashes:
* ... when an object is created, after it has been written to compute/storage, but not to the catalog.
* ... when an object is dropped, after it has been dropped from the catalog, but not from compute/storage.

This leads to an inconsistency in the stashes. To resolve it, some reconciliation needs to happen during adapter bootstrap.  We can simply drop all objects in the compute/storage stashes that adapter doesn't have in its current stash.

I think that resolves your concern regarding Fault Tolerance. Specifically, the question "So what happens if the command is written to the compute stash but not the storage stash, or vice versa?" would be answered with: "The object was not written to the catalog, so it is removed from the compute/storeage stash during adapter bootstrap."

I'm not sure if it answers the fencing concern. The above mechanism relies on the fact that the compute/storage stashes always contain a superset of the objects contained in the catalog. If a concurrent environmentd could cause objects appearing in the catalog that are not reflected in the compute/storage stashes, that would be bad.

I'll have to think more about your proposed alternative approach. Having a single durable storage would make maintaining consistency easier, but increase coupling between the components to some extend. I like the idea of having all the controllers simply tail a single WAL, but this would likely require a significant refactor first.

**Comment by benesch** [comment]
We ended up going with the alternative that @jkosh44 described here! Going to give this a close as a result. 🎉 

> I'm not entirely convinced that all of this extra complexity is worth it, though maybe I haven't seen the current motivation behind controller command durability. One alternative solution is to have a single place where all commands are made durable. The Coordinator is responsible for writing down all commands to some durable storage. When a compute controller restarts, it can read all the commands, filter out only the one's it cares about, and replay them. When a storage controller restarts, it can read all the commands, filter out only the one's it cares about, and replay them. When a Coordinator restarts, it can replay all commands and the controllers can use reconciliation to ignore repeat commands. These commands can either be stored in the coordinator's stash or replace the coordinator's stash as the source of truth. This would essentially be a coordinator WAL.
> 
> This somewhat accomplishes the goal of having the controllers not rely directly on the Coordinator for re-hydration. Instead they rely on the WAL. Though they are all somewhat coupled in that they must agree on the WAL structure.
> 
> In the far distant future, the Coordinator wouldn't even need to send commands to the controllers. The controllers could just constantly tail the WAL. This is similar to the way the FoundationDB Log Server works (https://www.foundationdb.org/files/fdb-paper.pdf)
