### ISSUE TITLE
[Epic] Review compute communication stack

### ISSUE THREAD

**Issue by teskje** [MaterializeInc/materialize#15382]
### Feature request

Recently we have seen an increased amount of bugs in the compute communication stack. For example:

* #15095
* #15181
* #15314

Those can in part be attributed to our collective lack of understanding of the compute command protocol. It makes it hard to deploy any changes to the components of the compute communication stack and be confident that they don't violate correctness in some way.

### Goals

* Develop a team-wide understanding of the compute command protocol
* Use that understanding to gain confidence in the implementation of the compute communication stack

### Acceptance Criteria

* There exists a specification document that describes the compute command protocol.
* The components of the compute communication stack have documentation that justifies their implementation based on the protocol specification.

### Tasks

* [x] #15192
* [x] #17096
* [x] #16086

### Questions

**Comment by antiguru** [comment]
Most work done, let's do another round to check that no clients are missing.
