### ISSUE TITLE
Error handling in Kafka sinks

### ISSUE THREAD

**Issue by JLDLaughlin** [MaterializeInc/materialize#1539]
Right now, we use a rdkafka::producer::FutureProducer to send Avro-encoded data out of Materialize and into Kafka topics. Messages sent with the FutureProducer result in a DeliveryFuture, which will eventually contain information about the success or failure of individual sends. 

We currently don't do anything with that information! To provide a better user experience/transparency, we should probably do the following: 
- Retry "retriable" failures x times (then notify users).
- Notify users about non-retriable failures.

**Comment by ruchirK** [comment]
I think I addressed at least part of this (doing something by logging the error) in https://github.com/MaterializeInc/materialize/pull/2909

**Comment by ruchirK** [comment]
Now that we have shutdown buttons tomorrow I'll try to get kafka sinks to a state where we shut down the producer, effectively shutting down the sink after the first non-recoverable error that drops data
