### ISSUE TITLE
Cluster Stuck in a Restart Loop

### ISSUE THREAD

**Issue by nmeagan11** [MaterializeInc/materialize#15412]
### What version of Materialize are you using?

v0.27.0

### How did you install Materialize?

Materialize Cloud

### What is the issue?

A customer is experiencing a cluster in a restart crash loop. The timing suggests it may be a `persist` time-out as we are not close to hitting OOM limits.

Internal context [here](https://materializeinc.slack.com/archives/C01CFKM1QRF/p1665697636633819), possibly related to https://github.com/MaterializeInc/materialize/issues/15402.

**Comment by benesch** [comment]
Closing, since we've released bandaid fixes for #15402.
