### ISSUE TITLE
Undesired Latency When Creating Views

### ISSUE THREAD

**Issue by nmeagan11** [MaterializeInc/materialize#15411]
### What version of Materialize are you using?

v0.27.0

### How did you install Materialize?

Materialize Cloud

### What is the issue?

A customer is experiencing high latency when trying to create a view. We should [enable tracing](https://www.notion.so/materialize/Logs-Traces-Metrics-in-Honeycomb-525208809baa41cf9639ed17ff618474#c5bf8124c347490ea5821d7f4219e8c0) and investigate.

Internal context can be found [here](https://materializeinc.slack.com/archives/C02LJ9EJP9S/p1665684184288829).

**Comment by benesch** [comment]
Closing in favor of our existing issue for this: #13772. I'll port the relevant context there.
