### ISSUE TITLE
Support sending protobuf data to Kafka sinks

### ISSUE THREAD

**Issue by JLDLaughlin** [MaterializeInc/materialize#1541]
Right now, we only support sending Avro-encoded data. This will likely expand the `CREATE SINK` syntax.

**Comment by ruchirK** [comment]
This is likely going to be pretty challenging as to the best of my knowledge there is no rust library at the moment that can generate protobuf data from a Rust object and a protobuf file descriptor set. The library we use - `serde_protobuf` can only read in protobuf messages + a file descriptor set and convert to rust objects at the moment

**Comment by nmeagan11** [comment]
Closing in favor of https://github.com/MaterializeInc/materialize/issues/8158
