### ISSUE TITLE
Add NOTICE to SHOW commands to use the introspection cluster

### ISSUE THREAD

**Issue by chaas** [MaterializeInc/materialize#15427]
In #15366 we added default indexes to `SHOW` commands in the `mz_introspection` cluster.

We should add a NOTICE to queries where there is an index available on the `mz_introspection` cluster and not in the active cluster. Something like:

NOTICE: This query may be faster if you switched to the `mz_introspection` cluster.

We should also update the docs/runbooks to recommend users run their `SHOW` commands in the `mz_introspection` cluster for faster speed, and notify devex/support of the change.

**Comment by mjibson** [comment]
Some description of why this is tricky is at https://github.com/MaterializeInc/materialize/pull/15432#issuecomment-1304980913.

**Comment by chaas** [comment]
This is no longer necessary because we now automatically run queries that depend only on system catalog relations in the mz_introspection cluster https://github.com/MaterializeInc/materialize/issues/17609
