### ISSUE TITLE
Set the cluster to `mz_system` when logging in as `mz_system`

### ISSUE THREAD

**Issue by benesch** [MaterializeInc/materialize#15441]
The `mz_system` user should use the `mz_system` cluster by default. That way we won't need to remember to configure every system service to set their cluster to `mz_system`.

We missed this [part of the system clusters design document](https://www.notion.so/materialize/System-clusters-26b20f5ecb93457a8164f1bd59650f91#963ef282906040ad979e96f40e7f758c) when we added the `mz_system` cluster. 

Possibly we should think bigger and address #14573 at the same time.

cc @jkosh44

**Comment by jkosh44** [comment]
We could check the user every time a new `Session` is created. If the user is `mz_system`, then we change the value of the `cluster` session variable to `mz_system`. That would be fairly simple but feels a bit like a band-aid.

**Comment by benesch** [comment]
Hmm, that _does_ seem a little hacky! I was hoping we'd be able to do this using the same mechanism by which parameters can be passed via the pgwire startup mechanism. Sec.

**Comment by benesch** [comment]
Never mind. What you did seems great. I left you a comment on that commit.

**Comment by jkosh44** [comment]
Why the change of heart? PR is here: https://github.com/MaterializeInc/materialize/pull/15497
