### ISSUE TITLE
SQL: `CREATE CONNECTION` does not show a warning/error if connection name already exists

### ISSUE THREAD

**Issue by bobbyiliev** [MaterializeInc/materialize#15478]
### What version of Materialize are you using?

v0.27.0 (218138173)

### How did you install Materialize?

Materialize Cloud

### What is the issue?

When trying to create a connection with the same name as an already existing connection, you don't get a warning or an error back, but just a success message. However, the existing connection does not get updated nor does the new one get created.

Example:

```sql
materialize=> CREATE CONNECTION kafka                              
FOR KAFKA BROKER 'my_kafka_broker:9092',   
    SASL MECHANISMS = 'PLAIN',                                     
    SASL USERNAME = SECRET up_sasl_password,                       
    SASL PASSWORD = SECRET up_sasl_username;
-- Output:
-- CREATE CONNECTION
-- Execute the statement again:
-- Output:
-- CREATE CONNECTION
```

**Comment by benesch** [comment]
This actually looks like a surfaces team issue to me. @chaas—I think we might want to prioritize this fairly high—it's kind of a "wrong result", in its way.

**Comment by chaas** [comment]
@ggnall @benesch The two options would be:
1) Show an error and fail to create the connection, or
2) Show a warning and update the existing connection object
I'm going to go forward with option 1 unless you think otherwise

**Comment by benesch** [comment]
Yeah, definitely (1)! We actually _can't_ update existing connection objects in place.

**Comment by benesch** [comment]
I'd look at what we do for, say, tables, and just do the exact same thing! We're probably mishandling an `if_not_exists` somewhere—but the `IF NOT EXISTS` logic should be exactly the same for tables and connections.

**Comment by chaas** [comment]
This is a new bug that was introduced in https://github.com/MaterializeInc/materialize/pull/15117.

The regression is here https://github.com/MaterializeInc/materialize/blame/f4ed657b7034660c28ef82083214405d7d929bca/src/adapter/src/coord/sequencer.rs#L616

where an `if plan.if_not_exists` check was dropped. I'll put up a PR for the fix now.

**Comment by chaas** [comment]
Hah @benesch same timing!

**Comment by benesch** [comment]
> Hah @benesch same timing!

I had a vague feeling it was my fault 🙈. I rushed #15117 a little to make the Oct 11 deadline. Sorry!

**Comment by chaas** [comment]
All good, it was an easy fix!
