### ISSUE TITLE
sql, adapter: expose `size` in `SHOW CLUSTER REPLICAS`

### ISSUE THREAD

**Issue by morsapaes** [MaterializeInc/materialize#15481]
### What version of Materialize are you using?

v0.27.0

### How did you install Materialize?

Materialize Cloud

### What is the issue?

The `size` column was added to the documentation of `SHOW CLUSTER REPLICAS` in #15092, but seems to never have made it to the code. My understanding is that `size` is exposed in `mz_cluster_replicas` ([builtin.rs](https://github.com/MaterializeInc/materialize/blob/2e3176c71e6ef22a4ed9e03fcc62cd64de34f902/src/adapter/src/catalog/builtin.rs#L1366)), but not in `mz_show_cluster_replicas` ([show.rs](https://github.com/MaterializeInc/materialize/blob/c88610320b633f02d8407bc176f0449ce8f08035/src/sql/src/plan/statement/show.rs#L546)).

### Relevant log output

```source
materialize=> SHOW CLUSTER REPLICAS;

     cluster      |    replica
------------------+----------------
 auction_house    | xsmall_replica
 default          | r1
 loadgen          | small
 loadgen          | xlarge
 mz_introspection | r1
 mz_system        | r1
(6 rows)
```

**Comment by chaas** [comment]
Thanks for catching!
The size column was added to the SHOW CLUSTER REPLICAS docs and to the SHOW SOURCES command in this change https://github.com/MaterializeInc/materialize/commit/d4cc666522098c4b056ba1a57be7a4f65d0b16b0, but not actually to SHOW CLUSTER REPLICAS command. I'll put up a fix

**Comment by morsapaes** [comment]
Thanks, @chaas! Hopefully, I'll start submitting actual PRs for this kind of trivial change whenever I'm not typing from some conference carpeted floor. It seems pretty straightforward to patch, sorry to burden you with it!
