### ISSUE TITLE
Add trace IDs to SQL statements

### ISSUE THREAD

**Issue by benesch** [MaterializeInc/materialize#15495]
### Feature request

It's difficult to link up the execution of a SQL statement to a particular trace in Tempo. It'd be awesome if each SQL statement had a trace ID attached that could be printed to the console (e.g., via a notice response) when some e.g. `debug_trace_ids` session parameter is set to true.

Suggested by @bkirwi on Slack: https://materializeinc.slack.com/archives/CL6H464R4/p1666043433475689?thread_ts=1666028473.258659&cid=CL6H464R4

**Comment by ggnall** [comment]
Is this still relevant with tempo transition? Assume something similar would be helpful, but not sure if already handled in that work. cc: @mjibson

**Comment by mjibson** [comment]
Yes, this would be super useful to my work. Current problem with tempo is the search is pretty much unusable, and so having this drop out a trace id would mean I can avoid using search.

**Comment by chaas** [comment]
@guswynn would you have any ideas on how to access the trace id in the adapter at query time?

**Comment by benesch** [comment]
(Linking in the Slack convo with the answer: https://materializeinc.slack.com/archives/C032AKCA1RA/p1671220146170919.)

**Comment by chaas** [comment]
As per the slack convo linked above, we can get the root trace id via
```
use tracing_opentelemetry::OpenTelemetrySpanExt;
use opentelemetry::trace::TraceContextExt;
tracing::Span::current().context().span().span_context().trace_id() 
```
I confirmed via manual testing that this produces the expected trace. See the slack thread for example screenshots of the traces.

One note: we only get tracing of `computed` for SELECT statements. For other statements, such as CREATE and DROP, we're only getting the `environmentd` trace. As per @guswynn, connecting across systems requires the trace id is put in every `ComputeRequest`, which was enough of a change to the protocol that we delayed that work.

The question for the adapter side is then, should we only emit the notice for SELECTs (e.g. in `src/adapter/src/coord/sequencer.rs` `sequence_peek`), or should we put it at the top of `sequence_plan` for all queries, knowing that the returned id may in some cases be only partial?
I'll make a PR adding the session parameter + putting at the top of `sequence_plan` for now.

**Comment by benesch** [comment]
Oh, definitely include the trace ID for all of them! It’s still very useful to be able to trace the execution of the CREATE statement itself through envd. E.g., woulda really helped with all of those massively slow stash transactions back in the day.
