### ISSUE TITLE
pg-cdc: `CREATE SOURCE` statement accepted without a `FOR` clause

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#15499]
### What version of Materialize are you using?

99c1ede02a2d09bb5de264082d5f3b6cfa2396f0

### How did you install Materialize?

Docker image

### What is the issue?

The `CREATE SOURCE` statement used to establish pg-cdc replication can run without a `FOR` clause, causing no tables to be replicated. @petrosagg reports that this is not correct.

**Comment by benesch** [comment]
It's even weirder when you attach a `FOR ALL TABLES` clause to a non Postgres non load generator source:

```
materialize=> create source s from kafka connection c (topic 'foo') format bytes for all tables with (size = '1');
ERROR:  [internal error] subsources should be resolved during purification
```

Going to assign this one to @petrosagg since even though this is technically surfaces' purview Petros is the one who is most familiar with this code.

**Comment by guswynn** [comment]
@moulimukherjee is going to take a look at this one. There are 2 different issues here, and I recommend doing them separately, in order:

1.  

```
materialize=> create source s from kafka connection c (topic 'foo') format bytes for all tables with (size = '1');
ERROR:  [internal error] subsources should be resolved during purification
```

Currently, the way statements are managed in mz is they are _parsed_ then _purified_ then _planned_. _purification_ is (https://github.com/MaterializeInc/materialize/blob/main/src/sql/src/pure.rs), which is when we need to do network IO (to do things like ask postgres about all the tables we are going to replicate). This (internal) error comes after purification, but its wrong: sources other than `POSTGRES` and `LOAD GENERATOR` sources are not compatible with `FOR ALL TABLES` and `FOR TABLES` clauses, so we should produce a user-facing error. I recommend adding various `println!`s here: https://github.com/MaterializeInc/materialize/blob/main/src/sql/src/plan/statement/ddl.rs#L860-L861, and to test out various different cases, like the one described above. Its likely that these 2 branches: `(None, Some(_)) | (Some(_), Some(ReferencedSubsources::All))` need to be handled differently! We can also talk in person about more detail here.

Note that you should write thorough tests, and a weird edge case you might need to test is: a postgres source whose publication contains no tables" I can help you figure out how to set that up!

2. The original issue: Basically, require that there is a `FOR TABLES` or `FOR ALL TABLES` clause in pg sources. Luckily this is already broken in a subtle way so we dont need a migration, as no instances of it will exist in production!
