### ISSUE TITLE
Improve error messaging for unknown types in postgres source

### ISSUE THREAD

**Issue by ggnall** [MaterializeInc/materialize#15502]
From the comments of #15073: 
We should consider improving the "type with OID ..." error message in the meantime. It could do two things better:

* Add a hint indicating that this is likely to be an unsupported type in Materialize.
* Indicate which column of which table uses the unsupported type.

**Comment by chaas** [comment]
@benesch The [Postgres error guide] (https://www.postgresql.org/docs/current/error-style-guide.html) recommends not using the word "unknown" at all, and suggests using "unrecognized" instead. Changing our error message would technically be "breaking", since a customer might have written logic expecting a specific error message. Are we ok with me changing the message, or should we just leave it, since it's not really an important fix?

**Comment by benesch** [comment]
> Are we ok with me changing the message, or should we just leave it, since it's not really an important fix?

Definitely okay with it. Locking in error messages would be too restrictive. I'll update the backcompat guide to explicitly allow changing error messages.

**Comment by chaas** [comment]
@morsapaes Do we have a guide somewhere on what to do with an unsupported type in a postgres source? I want to make the hint more actionable, by either suggesting a workaround or directing the user to a doc that explains more.

**Comment by morsapaes** [comment]
For the previous implementation, it was possible to use a workaround similar to [this](https://github.com/MaterializeInc/materialize/issues/12689#issuecomment-1183194711). Now that users have no control over the creation of sub-sources, AFAIU there isn't a way to handle unsupported types upstream other than excluding the table from the publication.

**Comment by benesch** [comment]
> AFAIU there isn't a way to handle unsupported types upstream other than excluding the table from the publication.

That's my understanding as well. Though note that PostgreSQL 15 will let you exclude columns from a table in a publication on a per-publication basis. It's probably worth writing these workarounds explicitly in the docs, with a link to #15073 that notes that we're working on letting you add `CAST`s in Materialize on a per-column basis.

**Comment by chaas** [comment]
Sounds good! @morsapaes if you or anyone else end up writing something up, let me know and I'll link to it into the hint as a follow up.
