### ISSUE TITLE
Add a mz_introspection system user

### ISSUE THREAD

**Issue by benesch** [MaterializeInc/materialize#15520]
### Feature request

We should add a new system user named `mz_introspection`. This user will be allowed limited read only access to the system via the internal SQL port.

Here is a proposed set of restrictions:

  * The user can only log in via the internal SQL port.
  * The user can execute only `SELECT` or `SUBSCRIBE` statements that involve objects in the `mz_internal`, `mz_catalog`, or `pg_catalog` schemas.
  * The user cannot execute DDL statements or DML statements, besides those allowed in the last bullet point.
  * The user can only execute queries on the system clusters (`mz_system` or `mz_introspection`, but possibly others in the future).

There will be no authentication required, beyond having access to the internal SQL port. I.e., you'll be able to freely connect with `psql -U mz_system -p 6877` or `psql -U mz_introspection -p 6877`. The idea is to reduce mistakes due to typos, etc, not to protect against malicious actors.

cc @jonathan-k-shapiro @chaas

**Comment by jkosh44** [comment]
Should `mz_introspection` user default to the `mz_introspection` cluster?

**Comment by benesch** [comment]
> Should `mz_introspection` user default to the `mz_introspection` cluster?

That makes sense to me!
