### ISSUE TITLE
Cast 'NaN' to float

### ISSUE THREAD

**Issue by jamii** [MaterializeInc/materialize#1553]
```
jamie=> select 'Inf'::float;
 ?column? 
----------
      inf
(1 row)

jamie=> select '-Inf'::float;
 ?column? 
----------
     -inf
(1 row)

jamie=> select 'NaN'::float;
 ?column? 
----------
         
(1 row)
```

The culprit is probably the `.to_lowercase` in parse_float64.

**Comment by rjnn** [comment]
Just a note to add that while this is tagged 'good first issue', it's also scheduled for 0.2, so we plan to have this merged in a matter of weeks.
