### ISSUE TITLE
Compute wrongly produces empty uppers for materialized views

### ISSUE THREAD

**Issue by teskje** [MaterializeInc/materialize#15535]
### What version of Materialize are you using?

main

### How did you install Materialize?

Built from source

### What is the issue?

@aljoscha reported a bug where compute incorrectly advances the uppers of materialized views to the empty frontier when they are dropped as part of reconciliation. He provided a repro here: https://github.com/MaterializeInc/materialize/pull/15528.

**Comment by frankmcsherry** [comment]
Thing to double check: is this true for all `DROP` commands for materialized views? Imo, we want to avoid this in that case also, to avoid miscommunication even transiently.

**Comment by teskje** [comment]
In https://github.com/MaterializeInc/materialize/pull/15099 we introduced that compute replicas emit a `FrontierUppers` response with the empty frontier for collections that are allowed to compact to the empty frontier. The reason was that the compute clients needs to know when a replica is done writing to a collection, so they can a) clean up frontier tracking state and b) drop their read holds on the storage collections the dropped compute collection depends on.

Reconciliation sometimes causes dataflows to get dropped. This also causes computed to emit `FrontierUppers` responses. This is a bug, at least in those cases where the dataflow is only dropped to be replaced by an equivalent one.

This bug is actually quite serious. It causes the compute controller to advance the respective compute collection's upper to the empty frontier. This probably has several bad effects. One is that, if the compute collection feeds a storage collection (like a materialized view), advancing its upper to the empty frontier disables compaction for that storage collection. This is because of [how our "lag write frontier by some compaction window" read policy is special-cased for the empty write frontier](https://github.com/MaterializeInc/materialize/blob/36d60b8d4e7199934044f76514712c2ae07d0f65/src/storage/src/controller.rs#L358-L359).

**Comment by teskje** [comment]
Here is a simple reproduction:

1. Run environmentd locally.
2. Create a materialized view:
    ```sql
    create table t (a int);
    create materialized view mv as select * from t;
    ```
3. Kill -9 environmentd, then start it again.
4. Observe the frontiers of the materialized view:
    ```sql
    materialize=> explain timestamp for select * from mv1;
                                  Timestamp
    ---------------------------------------------------------------------
               query timestamp: 1666692454654 (2022-10-25 10:07:34.654) +
                         since:[1666692385000 (2022-10-25 10:06:25.000)]+
                         upper:[]                                       +
              global timestamp: 1666692454654 (2022-10-25 10:07:34.654) +
       can respond immediately: true                                    +
                                                                        +
     source materialize.public.mv1 (u3, storage):                       +
                 read frontier:[1666692385000 (2022-10-25 10:06:25.000)]+
                write frontier:[]
    ```
