### ISSUE TITLE
sql: `uint4` and `int4`'s best common type is `double`

### ISSUE THREAD

**Issue by sploiselle** [MaterializeInc/materialize#15536]
### What version of Materialize are you using?

main

### How did you install Materialize?

Built from source

### What is the issue?

```
materialize=>
create table foo(a uint4);
create default index on foo;
explain select * from foo where a = 5;
CREATE TABLE
CREATE INDEX
                      Optimized Plan                      
----------------------------------------------------------
 Explained Query (fast path):                            +
   Filter (5 = uint4_to_double(#0))                      +
     ReadExistingIndex materialize.public.foo_primary_idx+
```

We will never choose to cast `i32` and `u32` to anything other than `float64` because they are not implicitly castable to each other, but are both castable to their type category's preferred type (`float64`)--this is done in `gess_best_common_type`.

In essence, this is a problem for us and not PG because we've introduced a kind of tree into our numeral types, where the signed and unsigned integers of the same size do not have parity with one another. In PG, there's a strictly linear relationship with the domain of numbers that can be presented.

**Comment by sploiselle** [comment]
Filing this as an issue because if you use any `uint` columns and compare them to most literal numerals (`int4`), the resulting cast to a float is expected.

**Comment by benesch** [comment]
What's our ideal alternative in this case? `i64`?

**Comment by sploiselle** [comment]
That would make some sense, but the problem then moves along to `i64` + `u64`, and then ideally you go to numeric?

**Comment by benesch** [comment]
> That would make some sense, but the problem then moves along to `i64` + `u64`, and then ideally you go to numeric?

Yeah, I guess? In any case it seems easy enough to jam in some special cases to `guess_best_common_type` or wherever to fix this. I think the hard part is figuring out what the right common type is for each pair of (signed type, unsigned type).

**Comment by sploiselle** [comment]
Ah, the right common types are just the `i` version of the next size up of the `u` type (`i16` + `u32` -> `i64`), except for `u64` numbers whose best common type with a signed int is numeric.
