### ISSUE TITLE
CREATE CONNECTION: Kafka SASL mechanisms should be case insensitive

### ISSUE THREAD

**Issue by rjnn** [MaterializeInc/materialize#15564]
### What version of Materialize are you using?

 v0.28.4 (200849889)

### How did you install Materialize?

Materialize Cloud

### What is the issue?

```
materialize=> create source pusher_events from kafka connection upstash (topic events) format text;       
ERROR:  Failed to create and connect Kafka consumer: Client creation error: Unsupported SASL mechanism: scram-sha-256
Time: 25.899 ms
```

This had me scratching my head for 5 minutes until I realized I should have been yelling `SCRAM-SHA-256`, and using my indoor voice wasn't sufficient.

**Comment by chaas** [comment]
@sploiselle I dug into the code and saw `SaslConfig.mechanisms` is a string.
https://github.com/MaterializeInc/materialize/blob/02b342a3333b0b4a4755c4e8e6e1e165361f9a65/src/storage-client/src/types/connections.rs#L176-L181

Should we make it an enum and apply validation on parsing? Is there a concern with backwards-compatibility in the case of pre-existing objects?

Another option is to add `.to_uppercase()` on the `mechanisms` line here
https://github.com/MaterializeInc/materialize/blob/02b342a3333b0b4a4755c4e8e6e1e165361f9a65/src/sql/src/plan/statement/ddl.rs#L2729-L2733

Happy to do either.

**Comment by sploiselle** [comment]
I would need some time to dig into the context for why the library insists on the casing of this field; I think the most conservative option would be to just check if the string is all uppercase and bail if it's not with direction to type in the same thing with the correct case, e.g.

```rust
if s.chars().any(|c| c.is_ascii_alphabetic() && !c.is_uppercase()) {
  bail!("invalid....please type it in more loudly");
}
```

If you can substantiate that it's totally cool to just uppercase it ourselves, I'm fine with that--just want something to acknowledge that approach is sane/blessed/has prior art.

**Comment by chaas** [comment]
Got it, thanks @sploiselle .

@mjibson mentioned when discussing this ticket that postgres has a precedent for being case insensitive. Here it's a little different b/c it's an option value string, aka the `'SCRAM-SHA-256'` in:
```
  CREATE CONNECTION kafka_connection TO KAFKA (
    BROKER 'unique-jellyfish-0000-kafka.upstash.io:9092',
    SASL MECHANISMS = 'SCRAM-SHA-256',
    SASL USERNAME = 'foo',
    SASL PASSWORD = SECRET kafka_password
  );
```
Matt, do you know if there's precedent for how to handle this scenario?

**Comment by mjibson** [comment]
That's a string, which are case sensitive, unlike identifiers which are only case-sensitive if double quoted. I concur with Sean.
