### ISSUE TITLE
Backpressured in-memory consolidation for persisted introspection sources

### ISSUE THREAD

**Issue by vmarcos** [MaterializeInc/materialize#15583]
### Feature request

In an [incident](https://materializeinc.slack.com/archives/C03SXN3KD5M/p1666274623459129), we observed the memory of a user-level `computed` cluster grow quickly while its CPU was at 100% in the presence of networking issues that prevented `computed` from talking through `persist` with storage. [Evidence](https://materializeinc.slack.com/archives/C03SXN3KD5M/p1666275270551829) indicated that CPU usage was caused by `persist` and memory build-up by introspection data.

We expect the following steps to cause the problem to manifest again:

1. Enable persisted introspection sources, e.g., with `--persisted-introspection`.
2. Partition the network between the COMPUTE and the STORAGE layer.
3. Watch introspection state build up without bounds in the COMPUTE clusters.

This issue is a request to devise and implement a mechanism to avoid introspection data from taking over resources in this fashion, e.g., by backpressure. A possible such mechanism could be to have `computed` perform local introspection update consolidation if there are too many outstanding writes to `persist` aimed at introspection shards.

**Comment by vmarcos** [comment]
Capturing a few further thoughts discussed with @antiguru: We could consider designing here a uniform _mechanism_ wherein COMPUTE could apply backpressure and compact any data to be sinked based on its knowledge of `AllowCompaction` frontiers. That way, we can handle both introspection sources as well as materialized views by the same mechanism.

What would differ is the _policy_ by which we advance the `since`s for these two different classes of objects. In the case of introspection sources, `since`s can be advanced as soon as possible and without interaction with external modules, as opposed to materialized views. That way, we would achieve the effect of aggressively compacting introspection data. At the same time, in the case of an asymmetric network partition to storage where we could read but not write, we would also opportunistically, but safely compact materialized views in-memory based on known `since` advancements.

**Comment by teskje** [comment]
I think this can be closed since the persisted introspection sources don't exist anymore. With other dataflows this shouldn't happen since if the persist connection fails we won't be able to ingest new data, so we also won't produce an unbounded amount of data on the dataflow outputs.
