### ISSUE TITLE
Postgres and ssh connection errors could be improved

### ISSUE THREAD

**Issue by guswynn** [MaterializeInc/materialize#15605]
Its unclear in general if:
`ERROR:  error communicating with the server: Connection reset by peer (os error 104): Connection reset by peer (os error 104)` comes from the postgres library or the ssh tunnel it self

Also, in some cases the pg library gets a `timeout` instead of a explicit reset, where there isnt actually network access (like trying to talk to an aws vpc). This could be improved by explaining what timeouts can mean (Note that the pg library doesnt really make these error's matchable in any simple way, so we will have to think about this

**Comment by materializesupport** [comment]
Copying this over from [Slack](https://materializeinc.slack.com/archives/C01CFKM1QRF/p1667340281154479?thread_ts=1667322873.455229&cid=C01CFKM1QRF)

Similar to the error mentioned above, when a connection from Materialize to a Postgres instance times out, customers will often receive the following error:

```
ERROR:  error connecting to server: Connection timed out (os error 110): Connection timed out (os error 110)
```

In its current state, the core error is duplicated, though the larger issue is that the error is unclear internally and would also be unclear to a customer that receives it.

Could we read in the error at the time of it being generated and convert it to something more descriptive? For example:

```
ERROR: The connection attempt to Postgres instance [postgres-hostname-or-ip] timed out after 120s (os error 110)
```

- Status is communicated and remains as it is today (ERROR:)
- We call out that the connection attempt to a Postgres instance timed out, while maintaining the core error
    - Additionally, we supply the hostname and/or IP of the instance we're attempting to connect to

For a customer-facing error (in Cloud, or any available logs), we could adjust this to include a link to /docs as a reference on what the error means (based on our knowledge and experience):

```
ERROR: The connection attempt to Postgres instance [postgres-hostname-or-ip] timed out after 120s -- Reference: https://materialize.com/docs/name-of-doc
```

For customer-facing errors, we should exclude the `(os error 110)` unless there's significance or multiple outcomes that relate to the same error code.
