### ISSUE TITLE
doc/user: split integration guides

### ISSUE THREAD

**Issue by joacoc** [MaterializeInc/materialize#15606]
### Documentation request

Integration guides already have many items. A few more are on the way. Splitting them as done in the sources section can improve the browsing.

E.g.:
* Sources
  * Postgres
    * AWS Aurora 
    * AWS RDS PostgresSQL
    * Azure DB for PostgreSQL
    * GCP Cloud SQL
  * MySQL 
  * Kafka/Redpanda
    * Redpanda
    * Redpanda Cloud
    * Confluent Cloud
    * AWS MSK  
    * Debezium
 * Metabase
 * dbt

**Comment by jseldess** [comment]
This is done for both Postgres direct and Kafka. Not done for Debezium, but I'm not sure if that's necessary. Closing this for now.
