### ISSUE TITLE
Add postgres connection example that includes ssh

### ISSUE THREAD

**Issue by heeringa** [MaterializeInc/materialize#15602]
### Documentation request

Let's add an example `CONNECTION` object for Postges to the [ssh section](https://materialize.com/docs/sql/create-connection/#postgres-ssh) of the documentation that directly incorporates the SSH tunnel.  

Right now one is absent.

![Screenshot by Dropbox Capture](https://user-images.githubusercontent.com/4967154/197294410-32b037b3-d20e-46f0-a576-15e3f4e5d2ce.png)

**Comment by joacoc** [comment]
Example added in https://github.com/MaterializeInc/materialize/pull/15607 as an integration guide. It covers setting up the connection, source, and public keys in the bastion server.

**Comment by benesch** [comment]
Got done in 770c748462959e47809ed7bb1db5708abf172b63.
