### ISSUE TITLE
Update Confluent Integration Guide

### ISSUE THREAD

**Issue by heeringa** [MaterializeInc/materialize#15629]
### Documentation request

Step 2(c) of the Confluent Integration Guide says "Click on the Data Integration tab and then choose API keys" but when I created a cluster, I didn't see such a tab nor do I see it now.  Perhaps it's because I created a cluster with a HTTP Source Connector, but here's what I see:

![Screenshot by Dropbox Capture](https://user-images.githubusercontent.com/4967154/197548019-1f361dcf-4285-4d34-8836-6682d3b4ad7d.png)

**Comment by bobbyiliev** [comment]
Indeed it seems like that their UI has changed. I've submitted a PR to change that in the doc:

https://github.com/MaterializeInc/materialize/pull/15634

**Comment by bobbyiliev** [comment]
Closing this one as we just merged https://github.com/MaterializeInc/materialize/pull/15634
