### ISSUE TITLE
persisted introspection shards can stop advancing `since`

### ISSUE THREAD

**Issue by pH14** [MaterializeInc/materialize#15628]
### What version of Materialize are you using?

0.28.4

### How did you install Materialize?

Materialize Cloud

### What is the issue?

We first saw on Frank's environment (and now others) introspection shards stop advancing `since`. From what was inferable at the time, we have two read handles open -- one in the originating `computed`, and one in `environmentd`. At some point, for reasons unknown, the `since` held back by `environmentd`'s read handle stops advancing, but it continues to heartbeat. This indefinitely holds back `since` for the shard, preventing logical compaction of the persisted data, so the shard will grow unboundedly.

Here's an illustrative chart of one customer's computed cluster, showing `since` across all shards. We'd expect all of the shards to progress at similar rates, but occasionally we see individual shards plateau at a given `since` indefinitely (or until 
`environmentd` restarts, relinquishing its stuck read handle):

<img width="1183" alt="Screen Shot 2022-10-24 at 9 50 47 AM" src="https://user-images.githubusercontent.com/785446/197541859-7b228cc1-90d4-46d6-8a80-358356bfd41f.png">

While I imagine the cause here is different, the symptoms are very similar to https://github.com/MaterializeInc/materialize/issues/14261. Short term, the remediation is simple: keep persisted introspection shards disabled. When the time comes to reenable them, we'll want to be sure we've fixed this one to avoid any unbounded shard growth.

**Comment by teskje** [comment]
Would be interesting to know if this still occurs after the recent frontier tracking refactor. I've enabled persisted introspection on my staging env, lets see how it goes: https://g-2531aff0fb.grafana-workspace.us-east-1.amazonaws.com/d/JH0BMxNVz/jans-playground
