### ISSUE TITLE
persist: fires

### ISSUE THREAD

**Issue by danhhz** [MaterializeInc/materialize#15638]
A meta issue to track all the known persist fires during stability period

# Tier 0 (sticky, no real mitigation)

- [x] #15493
  - Some cases fixed by #15596
  - More cases fixed by #15745
  - More cases fixed by #15837
  - If we find any additional cases, time to step back and explore another code structure
- [x] unexpected since advancement
  - [x] Bandaid #15645
  - [x] Real fix is #15511
  - [x] #15822
  - [x] #15961

# Tier 1 (panics, recoverable but unnecessary restarts)

- [ ] #15209
  - Maybe fixed by #15677
  - There are still a (smaller) stream of these happening. Spot checking them, Paul found that they seem "legitimate" in the sense that network was unavailable or cpu was pegged for a long period. This might be the justification we need to spend time on more graceful expired lease handling (for writers, TBD on readers)
  - Doesn't fix any fundamental issues, but should help volume: #15839
  - All recently spot-checked cases look to a node where cpu and/or network is pegged. Definitely seems worth doing something here, but the volume is down enough that it's more like a "smolder" now
- [x] #15590
  - Maybe fixed by #15677
  - Yup, fixed!
- [x] Indeterminate: connection closed
  - [x] #14046

# Tier 2 (bad behavior)

- [ ] #15937
  - mitigated by #16553. we shouldn't really see customer impact beyond data sticking around in s3 longer than necessary (so now it's more of a billing/cost issue)
- [ ] #15093
  - Patched this sufficiently that prod is limping along, which buys us time
  - Holding off on additional patches as much as possible until we have the more principled #16607
- [ ] https://github.com/MaterializeInc/materialize/issues/16161
  - New force-compaction tool should fix these as we find them

**Comment by benesch** [comment]
I added #16161 to this issue, because I didn't want it to get lost. Feel free to kick it to a more appropriate place.

**Comment by danhhz** [comment]
Nope, that's perfect, ty!

**Comment by danhhz** [comment]
As of the release that went out this week, everything here seems to be either mitigated or reduced to a smolder. There's lots of follow-up work to put out the smolders and some more principled fixes, but we'll move that to the normal persist planning process. Closing this
