### ISSUE TITLE
Update "Conceptual Framework" sections to be consistent with "Key Concept" sections

### ISSUE THREAD

**Issue by ruf-io** [MaterializeInc/materialize#15641]
### Documentation request

I like that we repeat the exact same content in "[Key Concepts > Cluster](https://materialize.com/docs/overview/key-concepts/#clusters)" and "[Create Cluster > Conceptual Framework](https://materialize.com/docs/sql/create-cluster/#conceptual-framework)".

It would be useful to do something similar for Sources, Materialized Views, Sinks, Replicas...

**Comment by jseldess** [comment]
@tr0njavolta, while you work on https://github.com/MaterializeInc/materialize/issues/18367, might be good to keep this issue in mind, in case there are easy related updates.
