### ISSUE TITLE
Allow setting default session variables per user

### ISSUE THREAD

**Issue by benesch** [MaterializeInc/materialize#15651]
### Feature request

Allow each user to define their own default value for each session parameter. This is a PostgreSQL feature:

```
ALTER ROLE worker_bee SET maintenance_work_mem = 100000;
```

Details in the [`ALTER ROLE` documentation](https://www.postgresql.org/docs/current/sql-alterrole.html).

The most commonly requested use case for this feature is setting a default `cluster` per user. This was called out as a desirable feature in our original platform design document: https://github.com/MaterializeInc/materialize/blob/main/doc/developer/platform/ux.md#cluster.

Being able to set session parameters in the connection string could be a decent workaround—see #14573.

**Comment by benesch** [comment]
This turns out to be pretty important for tools that don't have custom integrations with Materialize that allow users to set the `cluster` they want to use. Otherwise, if the user drops the `default` cluster, those tools won't be able to run queries against Materialize.

cc @ggnall @chaas

**Comment by mjibson** [comment]
What's the priority of this after supporting `options` in the connection string? Very low or zero?

**Comment by ggnall** [comment]
@morsapaes are there additional dbt or ide use cases where specifying a cluster in the connection string is insufficient? https://github.com/MaterializeInc/materialize/pull/17853

**Comment by benesch** [comment]
> @morsapaes are there additional dbt or ide use cases where specifying a cluster in the connection string is insufficient? #17853

I'm sure there are some IDEs that don't support the `options` parameter. It's fairly niche.

Separately from the question of whether this feature is needed for IDE support, I think it is important for DBA-type people. I can imagine that the admin of a Materialize org would want to set default clusters for users, so that those users don't need to think about clusters when they log in.

**Comment by morsapaes** [comment]
> I can imagine that the admin of a Materialize org would want to set default clusters for users, so that those users don't need to think about clusters when they log in.

This is the most immediate value. It'd be great to support default session parameter values as a close follow-up to RBAC, both at the user and role levels. If it serves as any signal, Snowflake only supports setting a default warehouse at the user level, but role-level is one of the most requested features in their [ideas forum](https://community.snowflake.com/s/ideas) (search for `Default Warehouse for Role` and you might even find a familiar face 👀).

**Comment by benesch** [comment]
At the role level! That sounds great, but I was chewing on it and I couldn't figure out how it would work with multiple roles. Say my user is `benesch` and I'm a member of both the `analyst` role (default cluster is `transforming`) and the `infra` role (default cluster is `scratch`). Which default cluster applies?

**Comment by benesch** [comment]
I think you'd need some sort of role priority system, which .. uf.

**Comment by benesch** [comment]
@aljoscha's work on platform v2 suggests that something like this would be useful if we introduce the concept of a `GATEWAY`, which would allow scaling/isolating SQL "serving". You'd choose a gateway like you choose a cluster, by saying `SET gateway = ...`. To hide this concept away from users until they need it, we'd want admins to be able to configure default gateways per user.

**Comment by jkosh44** [comment]
> At the role level! That sounds great, but I was chewing on it and I couldn't figure out how it would work with multiple roles. Say my user is benesch and I'm a member of both the analyst role (default cluster is transforming) and the infra role (default cluster is scratch). Which default cluster applies?

Just for reference, in PostgreSQL `ALTER ROLE <role> SET ...` only affects session's that have an authorization role of `<role>`. In other words, you do not inherit default variables from parent roles.

Here's an example of altering a role and it's parent role:
```
postgres=# CREATE ROLE r1 LOGIN;
CREATE ROLE
postgres=# CREATE ROLE r2 LOGIN;
CREATE ROLE
postgres=# GRANT r2 TO r1;
GRANT ROLE
postgres=# ALTER ROLE r1 SET search_path TO 'foo';
ALTER ROLE
postgres=# ALTER ROLE r2 SET search_path TO 'bar';
ALTER ROLE
postgres=# \q
joe@joe-ThinkPad-X1-Extreme-Gen-3:~$ psql -U r1 postgres
psql (15.3 (Ubuntu 15.3-1.pgdg22.04+1))
Type "help" for help.

postgres=> SHOW search_path;
 search_path 
-------------
 foo
(1 row)

postgres=> \q
joe@joe-ThinkPad-X1-Extreme-Gen-3:~$ psql -U r2 postgres
psql (15.3 (Ubuntu 15.3-1.pgdg22.04+1))
Type "help" for help.

postgres=> SHOW search_path;
 search_path 
-------------
 bar
(1 row)
```

Switching roles during a session doesn't change the value of any session variable either:
```
joe@joe-ThinkPad-X1-Extreme-Gen-3:~$ psql -U r1 postgres
psql (15.3 (Ubuntu 15.3-1.pgdg22.04+1))
Type "help" for help.

postgres=# SHOW search_path;
 search_path 
-------------
 foo
(1 row)

postgres=# SET ROLE r2;
SET
postgres=# SHOW search_path;
 search_path 
-------------
 foo
(1 row)

postgres=# SET SESSION AUTHORIZATION r2;
SET
postgres=# SHOW search_path;
 search_path 
-------------
 foo
(1 row)
```

If only the parent role is altered, then the child role is not affected:
```
postgres=# CREATE ROLE r1 LOGIN;
CREATE ROLE
postgres=# CREATE ROLE r2 LOGIN;
CREATE ROLE
postgres=# GRANT r2 TO r1;
GRANT ROLE
postgres=# ALTER ROLE r2 SET search_path = 'foo';
ALTER ROLE
postgres=# \q
joe@joe-ThinkPad-X1-Extreme-Gen-3:~$ psql -U r1 postgres
psql (15.3 (Ubuntu 15.3-1.pgdg22.04+1))
Type "help" for help.

postgres=> SHOW search_path;
   search_path   
-----------------
 "$user", public
(1 row)

```

> I think you'd need some sort of role priority system, which .. uf.

This also scares me.
