### ISSUE TITLE
Allow `CREATE CLUSTER` to front either `storaged` or `computed`. 

### ISSUE THREAD

**Issue by frankmcsherry** [MaterializeInc/materialize#15674]
### Feature request

We have been looking for an abstraction that allows users to bundle sources and sinks into a pod, or at least avoid forcing each into its own (not free) pod. The choices here have been either 1. bad or 2. hard:
1. Add some new syntax to `CREATE CLUSTER` to distinguish storage from compute cluster.
2. Unify `storaged` and `computed` into one binary.

It seems like there may be a third option, which is a facade in front of the second option: pretend that `CREATE CLUSTER` has created a hybrid pod, but lock down whether it is a `storaged` or a `computed` when you first add an object (e.g. a `CREATE SOURCE` or a `CREATE MATERIALIZED VIEW`, respectively).

**Comment by frankmcsherry** [comment]
Another recommendation, from @petrosagg, is to start up both a `storaged` and a `computed` on the same pod, and connect to both.

**Comment by aljoscha** [comment]
Closing this because it has been superseded by the Cluster Unification work (https://github.com/MaterializeInc/cloud/issues/4929). But please re-open if you disagree!
