### ISSUE TITLE
Recommended AWS VM class for Materialize

### ISSUE THREAD

**Issue by rjnn** [MaterializeInc/materialize#1568]
We should pick and recommend a single VM class for Materialize, as well as standardize on this for all our cloud customers.

Dimensions that matter are:
1) compute heavy vs balanced vs memory heavy.
2) Intel vs AMD CPUs.
3) attached storage configuration (EBS vs non-EBS)
4) AMI selection, including out-of-the-box drive configuration
5) default timely worker configuration

(Assigned to @cuongdo for triage). General opinions welcome. My initial thoughts are:

1) memory-heavy because that's what Materialize needs
2) Intel because nobody-got-fired-for-buying-IBM reasons
3) non-EBS local storage for latency reasons
4) Some Ubuntu AMI that has ludicrous amounts of swap space pre-configured
5) `workers=VCPU-count/2`. Alternatives are to leave some additional VCPUs around for parsing/IO/coordinator work, or to also use AMI configurations that disable hyperthreading, or things like that.

This puts us in the VM r5d class. We need to find/create an AMI configuration that has the swap space configured right.

assigned to @cuongdo to triage and assign someone to answer this definitively, but everyone feel free to chime in.

**Comment by quodlibetor** [comment]
We're moving to cloud-first, and sizing is very dependent on customer use, so we're unlikely to ever have a one-size fits all recommendation, I think we should close this.

**Comment by benesch** [comment]
Closing per @quodlibetor's compelling arguments.
