### ISSUE TITLE
2xlarge cluster in production does not respond to queries

### ISSUE THREAD

**Issue by benesch** [MaterializeInc/materialize#15691]
### What version of Materialize are you using?

v0.28.5

### How did you install Materialize?

Materialize Cloud

### What is the issue?

A 2xlarge cluster created in production does not seem to come up correctly. Here's what we observed in one customer environment:

* On the first boot, the processes were unable to connect to one another (one process experienced repeated "connection refused" errors). 

* After killing the pods manually, the individual `computed` processes appear to be healthy (judging by log lines and Grafana dashboards), but the cluster does not respond to even simple peeks of small system tables (e.g., `SHOW VIEWS`).

**Comment by benesch** [comment]
The first issue is likely https://github.com/MaterializeInc/materialize/issues/15598.

**Comment by brennanvincent** [comment]
The second part of this issue is unknown to me, unfortunately -- will investigate
