### ISSUE TITLE
persist: `environmentd` uses a lot of memory when many sources

### ISSUE THREAD

**Issue by benesch** [MaterializeInc/materialize#15720]
### Feature request

We've observed in production that `environmentd` uses quite a bit of memory (~6Gi steady state) for a customer with ~65 sources. A cursory investigation suggested that the memory was spent in `persist`.

We have a cloud-side mitigation for this issue: per-environment overrides of the amount of memory allocated to environmentd. See https://github.com/MaterializeInc/cloud/pull/4359.

[Additional context from @ph14 on Slack.](https://materializeinc.slack.com/archives/C047V8KSSQJ/p1666720373187609) tl;dr there are more important persist issues to be working on right now. But wanted to get this written down so we don't forget.

cc @danhhz @philip-stoev

**Comment by benesch** [comment]
Also, I believe this is different from #15680. This isn't about the case when `storaged` or `computed` has crashed and `envd` is picking up the load. This is about the steady state case, where `storaged` and `computed` are functioning correctly.

**Comment by danhhz** [comment]
> A cursory investigation suggested

suggested... persist? Or is there more nuance in the missing words? :)

**Comment by benesch** [comment]
Yes, oops, sorry!

**Comment by dseisun-materialize** [comment]
@danhhz doing some backlog cleaning. Before I look closer do you know if this ever got clarified/resolved?

**Comment by pH14** [comment]
@dseisun-materialize going to close this. We've rolled out a ton of memory usage fixes since this was filed
