### ISSUE TITLE
SSH tunnels use strict host key checking

### ISSUE THREAD

**Issue by benesch** [MaterializeInc/materialize#15722]
### What version of Materialize are you using?

v0.28.5

### How did you install Materialize?

Materialize Cloud

### What is the issue?

Our [SSH tunnels](https://materialize.com/docs/sql/create-connection/#postgres-ssh) configure OpenSSH with its default of strict host key checking, which does not provide the right behavior for our Kubernetes-based cloud environment. If the remote host changes—which happens frequently with the SSH bastions that many of our customers use, since they are _also_ using ephemeral cloud resources—the existing SSH tunnel will break. But it will magically heal at some point in the future, when the pods cycle out and the `known_hosts` file vanishes.

AFAICT this impacts both `storaged` and `environmentd`. When the former has a stale host key, existing SSH tunnels break. When the latter has a stale host key, attempting to create new sources against the connection to the host with the stale key will fail.

**Comment by uce** [comment]
@guswynn This should be straight forward. I've assigned P2 to not distract from other ongoing investigations, but it'd be great to get this out of the way as soon as possible.

**Comment by benesch** [comment]
I think the implementation is probably as simple as passing `-o UserKnownHostsFile=/dev/null -o StrictHostKeychecking=no` wherever we invoke `ssh`. Most of the work will be in writing a good test case for this.
