### ISSUE TITLE
Implement FILE SINKS

### ISSUE THREAD

**Issue by rjnn** [MaterializeInc/materialize#1572]
Just as we have file sources, Kafka sources, and Kafka sinks, we should also have file sinks.

One advantage of having file sinks is we can then install file sinks by default for all the logging views into `mzdata/logs/`. This will be useful for when people encounter performance bugs with Materialize and we want them to send us their logs.

cc @cuongdo for triage.

**Comment by cuongdo** [comment]
Correctly implementing this (and any other sink types) will require #1442

**Comment by cuongdo** [comment]
@ruchirK Putting this on your plate for 0.2, since this should be related to work for progress checkpoints for Kafka sinks.
