### ISSUE TITLE
Sink logging views to log files by default

### ISSUE THREAD

**Issue by rjnn** [MaterializeInc/materialize#1573]
Once we have #1572, we should install default sinks in the `mzdata/logs` directory for all our materialize logs. @frankmcsherry brought up that perhaps we should instead log the timely logs themselves. I'll let him continue his argument in this issue for what the tradeoffs are between the two approaches.

**Comment by benesch** [comment]
Cross-posting from https://github.com/MaterializeInc/materialize/issues/1696#issuecomment-587283859:

> The fact that you currently have to use Prometheus and Grafana in a production installation of Materialize is a feature, not a bug, in my opinion. Debugging a system with the system itself results in a world of pain. If someone installs a query that grinds the system to a halt—and there are a lot of such queries at the moment—Materialize's metric export and inspection pipeline will also grind to a halt, and you won't be able to debug.

Can we kick this out of v0.2? I think there are a lot of product questions to resolve here, and I'd much prefer that we push people towards Grafana/Prometheus instead.

**Comment by frankmcsherry** [comment]
I think we should kick it out too, but I think we should be able to capture timely, differential, and materialized logs. They contain a lot more information than Grafana or Prometheus can handle.

**Comment by benesch** [comment]
Capture how? Capturing to a file? If we're overwhelming Prometheus, won't we quickly be overwhelming disk space, too?

**Comment by frankmcsherry** [comment]
It's more the relational structure in the data. Afaik, both Grafana and Prometheus want univariate time series data.
