### ISSUE TITLE
regression: panic at rc/persist-client/src/fetch.rs:483 when upgrading from v0.29.0 

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#15733]
### What version of Materialize are you using?

9584dcf495df9c40099ae911069681d724fa3f68

### How did you install Materialize?

Built from source

### What is the issue?

```
platform-checks-materialized-1      | thread 'timely:work-3' panicked at 'key=w18a6b7ac-5b5c-4b13-8887-91f0664e64fc/p23d88289-ee88-45f0-bdda-18d1357fef93 inline=Description { lower: Antichain { elements: [0] }, upper: Antichain { elements: [1666870205535] }, since: Antichain { elements: [1666870203252] } } registered=Description { lower: Antichain { elements: [0] }, upper: Antichain { elements: [1666870249942] }, since: Antichain { elements: [1666870203252] } }', /var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-052cfcf1d49487607-1/materialize/tests/src/persist-client/src/fetch.rs:483:13
```

When running the "Platform Checks Upgrade + Restart Entire Mz" scenario , the computed enters into a crash loop with the panic message shown above.

The issue is **not** reproducible if:
- it is not an upgrade, but simple restart
- if only a few queries are run prior to the upgrade. The entire complimnent of Checks needs to run

To reproduce:
1. run:
```
cd tests/platform_checks
./mzcompose run default --scenario=UpgradeEntireMz
```
2. Wait until it hangs like this:
```
> INSERT INTO boolean_type_table SELECT * FROM boolean_type_table;
rows didn't match; sleeping to see if dataflow catches up 50ms 75ms
...
```

3. Observe crash loop in `docker logs`

### Relevant log output

```source
https://buildkite.com/organizations/materialize/pipelines/nightlies/builds/1292/jobs/0184192a-d37a-4631-bd10-86a28bdf7d23/artifacts/0184193b-4de0-4d6a-ac31-20c515ca06f5
```

**Comment by pH14** [comment]
This is 100% a bug, and a result of https://github.com/MaterializeInc/materialize/pull/15363 which has since been reverted for 0.29.2. This was caught during the release and confined to staging / internal envs, and all prod environments are already on 0.29.2 so I don't think we need to worry about this one further

**Comment by philip-stoev** [comment]
Not reproducible when upgrading from v0.29.3 , so closing.
