### ISSUE TITLE
`Checks + restart of the entire Mz` and `Checks + restart of environmentd & storaged` is flaky

### ISSUE THREAD

**Issue by lluki** [MaterializeInc/materialize#15742]
### Buildkite link

https://buildkite.com/materialize/tests/builds/44041

### Relevant log output

```source
It always times out, but always on the same SELECT


> SHOW CREATE MATERIALIZED VIEW monotonic_topk_view1;
rows match; continuing at ts 1666830237.5614054
> SELECT * FROM monotonic_topk_view1;
 
<stdin>:5:1: error: deadline has elapsed
     |
   4 |
   5 | > SELECT * FROM monotonic_topk_view1;
     | ^
!!! Error Report
```

Sometimes it also hits the `Checks + restart of environmentd & storaged` test,
for instance here [buildkite](https://buildkite.com/materialize/tests/builds/44030#01841607-e8a9-4e7a-ba1d-6e2963897a16):

```
> SELECT * FROM debezium_view1;
rows match; continuing at ts 1666818243.0603724
> SELECT * FROM debezium_view2;
 
<stdin>:10:1: error: deadline has elapsed
     |
   9 |
  10 | > SELECT * FROM debezium_view2;
     | ^
!!! Error Report
```

**Comment by philip-stoev** [comment]
Dup of https://github.com/MaterializeInc/materialize/issues/15155 . The process orchestrator fails to start all the storageds after having been restarted itself.
