### ISSUE TITLE
add support for upserts that follow the kafka topic compaction convention

### ISSUE THREAD

**Issue by rjnn** [MaterializeInc/materialize#1575]
details TBD.

**Comment by cuongdo** [comment]
Removing `M-milestone-blocker` per @rjnn

**Comment by wangandi** [comment]
Above src/interchange/avro.rs:validate_key_schema, the comment says
```
/// An Avro key schema is valid for our purposes iff every field
/// mentioned in the key schema exists in the specified relation
/// type with the same type. If the schema is valid, returns a
/// vector describing the order and position of the primary key
/// columns.
```
The "specified relation type" is the relation type generated from the value schema.

For the compaction envelope, do we still expect this to be true?

**Comment by wangandi** [comment]
In light of a prospect's desire to use non-avro keys but avro records for the values, here's a proposed syntax for upsert: 

`CREATE [MATERIALIZED] SOURCE yadda ... yadda ... ENVELOPE UPSERT [(FORMAT {TEXT | AVRO USING SCHEMA yadda ... yadda})]`

The `FORMAT` next to the UPSERT is used to specify the format of the keys that we need to decode. It is meant to be optional and default to whatever the `FORMAT` for the values are. In the future, we may want to expand the key formats supported.

There are supposed to be parentheses around the `FORMAT` in case we need to add certain words after the `FORMAT` in the future. I also envision that in the future, we could support upsert for non-key-value stores by having the contents of the parentheses be a column number or column name instead.
