### ISSUE TITLE
storage: be more strict (assertive) about state tracking in controller

### ISSUE THREAD

**Issue by aljoscha** [MaterializeInc/materialize#15761]
In https://github.com/MaterializeInc/materialize/pull/15734, we removed a panic/assert because our state tracking is currently somewhat loose and the panic/assert was being to "nervous". (see description of the PR)

We can enable stricter checks once we only remove controller-side state tracking when we hear back from `storaged`.

**Comment by benesch** [comment]
Now tracked by https://github.com/MaterializeInc/materialize/issues/23513.
