### ISSUE TITLE
[Epic] Customer Facing Observability for Storage

### ISSUE THREAD

**Issue by nmeagan11** [MaterializeInc/materialize#15763]
### Feature request

Placeholder epic while we flesh out what this means concretely.

**Principle:** Materialize is Flexible and Friendly
**Theme:** Observability
**Acceptance Criteria:** Users can onboard with confidence by being able to visualize, debug, and plan their operations and resources.
**Description:** This epic captures operational burdens (not errors) that we need to expose via queries to system tables and/or the UI so users understand what’s going on.

**Comment by sjwiesman** [comment]
Some metrics that would make sizing upsert and debezium sources easier:

1. The number of active keys
2. The rate of change / throughput

**Comment by ggnall** [comment]
Dropping this placeholder in favor of more targeted epics, e.g. https://github.com/MaterializeInc/materialize/issues/15896
