### ISSUE TITLE
Don't show cluster change status when creating and dropping replicas

### ISSUE THREAD

**Issue by sjwiesman** [MaterializeInc/materialize#15760]
### Feature request

The notices around cluster replica being not ready when creating and dropping replicas look scary even though they are expected and normal. We should not show them in these scenarios. 
```
materialize=> CREATE CLUSTER REPLICA auction_house.bigger SIZE 'small';
NOTICE:  cluster replica auction_house.5 changed status to: NotReady
NOTICE:  cluster replica auction_house.5 changed status to: NotReady
NOTICE:  cluster replica auction_house.5 changed status to: NotReady
CREATE CLUSTER REPLICA
materialize=> DROP CLUSTER REPLICA auction_house.bigger;
NOTICE:  cluster replica auction_house.bigger changed status to: NotReady
NOTICE:  cluster replica auction_house.bigger changed status to: NotReady
NOTICE:  cluster replica auction_house.bigger changed status to: NotReady
DROP CLUSTER REPLICA
```

**Comment by benesch** [comment]
Agreed on drop! I wonder if something is going wrong on create… like, are we flapping between ready and not ready? Or is it just that we have to emit “not ready” once, the first time, and we should suppress that? Not sure!

**Comment by benesch** [comment]
cc @mjibson; linking https://github.com/MaterializeInc/materialize/issues/15692
