### ISSUE TITLE
support FLOOR() and CEILING()

### ISSUE THREAD

**Issue by rjnn** [MaterializeInc/materialize#15793]
### Feature request

https://www.postgresql.org/docs/9.5/functions-math.html

**Comment by chaas** [comment]
These already exist as `FLOOR` and `CEIL`.
```
materialize=> select floor(1);
 floor 
-------
     1
(1 row)

materialize=> select ceil(1);
 ceil 
------
    1
(1 row)

materialize=> select floor(1.2);
 floor 
-------
     1
(1 row)

materialize=> select ceil(1.2);
 ceil 
------
    2
```
Is there additional functionality (e.g. the full name `CEILING`) that we should support?

**Comment by rjnn** [comment]
postgres supports `CEILING`, I suppose there's an alias or something we could support to close this out?

**Comment by aljoscha** [comment]
Grabbing this one for @dseisun-materialize, hoping to polish off some easy issues to get him started on the code base.

**Comment by aljoscha** [comment]
Implemented!
