### ISSUE TITLE
Separate sources, formats, and envelopes

### ISSUE THREAD

**Issue by rjnn** [MaterializeInc/materialize#1579]
E.g. support [tb](https://github.com/MaterializeInc/tb/) sources. CDC sources are something prospects have asked for independent of them being kafka-ified.

**Comment by rjnn** [comment]
We should file separate issues for each of the remaining tasks (e.g. supporting Debezium envelopes for files, etc), and then close this one out. It's difficult to follow as-is, and the title work has been done. @umanwizard

**Comment by rjnn** [comment]
@awang there's a little bit of a re-assess the situation required here - I think it just requires some fresh eyes. @sploiselle can help you with any diagnosis that might be required as to what is and is not supported.

**Comment by awang** [comment]
also looks related to:  https://github.com/MaterializeInc/materialize/issues/2537

**Comment by sploiselle** [comment]
This is done and [documented](https://materialize.io/docs/sql/create-source/) so I'm closing.
