### ISSUE TITLE
Calling mz_any or mz_all with an unexpected parameter crashes computed

### ISSUE THREAD

**Issue by teskje** [MaterializeInc/materialize#15805]
### What version of Materialize are you using?

main

### How did you install Materialize?

Built from source

### What is the issue?

Either of these two SQL snippets crash computed:

```sql
CREATE TABLE t (a int);
INSERT INTO t (1);
SELECT mz_internal.mz_any(a) FROM t;
```

```sql
CREATE TABLE t (a int);
INSERT INTO t (1);
SELECT mz_internal.mz_all(a) FROM t;
```

The panic is in both (!) cases:

```
thread 'timely:work-0' panicked at 'Invalid argument to AggregateFunc::Any: Int32(1)', src/compute/src/render/reduce.rs:1080:22
``` 

Note that the panic text is misleading in the case of `mz_all`.

### Initial Diagnosis

The issue appears to be that compute assumes that arguments to these functions must be booleans:
```rust
            AggregateFunc::Any | AggregateFunc::All => match datum {
                Datum::True => AccumInner::Bool {
                    trues: 1,
                    falses: 0,
                },
                Datum::Null => AccumInner::Bool {
                    trues: 0,
                    falses: 0,
                },
                Datum::False => AccumInner::Bool {
                    trues: 0,
                    falses: 1,
                },
                x => panic!("Invalid argument to AggregateFunc::Any: {:?}", x),
            },
```

It looks like query planning does not limit these function arguments to any type (or at least it allows integers as well).

**Comment by benesch** [comment]
Ah, interesting. I believe these functions are not meant to ever be called by the user directly, and only injected into the query as part of the planning process. We probably want a better way of doing that than `mz_internal`.
