### ISSUE TITLE
compute: canceling a peek can incorrectly release a read hold

### ISSUE THREAD

**Issue by benesch** [MaterializeInc/materialize#15843]
### What version of Materialize are you using?

v0.30.0

### How did you install Materialize?

Materialize Cloud

### What is the issue?

We observed the following crash in a customer environment in production:

```
thread 'tokio-runtime-worker' panicked at 's292: sc19c6be7-95f7-4577-8110-f009f557bdd5 cannot serve requested as_of Antichain { elements: [1667333327621] }: Since(Antichain { elements: [1667334687000] })', /var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0e6cbf91f9e0cd31c-1/materialize/tests/src/storage/src/source/persist_source.rs:230:24
stack backtrace:
thread 'tokio-runtime-worker' panicked at 's275: sb62087de-4d76-4505-99f4-97f2cf660bf4 cannot serve requested as_of Antichain { elements: [1667333777900] }: Since(Antichain { elements: [1667334715901] })', /var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0e6cbf91f9e0cd31c-1/materialize/tests/src/storage/src/source/persist_source.rs:230:24
```

The objects in question are `mz_views` and `mz_audit_events` which... were two tables I attempted to read from (e.g., `SELECT * FROM mz_views`) and then _canceled_.

@frankmcsherry and I suspect the reproduction is something like this:

1. Enable an `2xlarge` cluster in cloud. (Smaller might work too, but this is what we saw the issue on.)
2. Install an index that will ingest 10GB+ of data from persist.
3. Issue a `SELECT * FROM mz_views` query. Observe it hanging (because the cluster is so busy rehydrating).
4. Cancel it.
5. Wait 20m+ for the cluster to rehydrate.
6. Watch the cluster crash with the "cannot serve requested as of" error message. Hopefully.

Additional discussion in Slack: https://materializeinc.slack.com/archives/C02PPB50ZHS/p1667339624949869

Current working theory is that the `CreateDataflow` command gets stuck in a buffer somewhere and delivered to the replica _after_ the `CancelPeek` command has canceled out the peek command at the compute controller and released the read hold.

**Comment by teskje** [comment]
### Reproduction

Here is a reproduction for what @frankmcsherry and I think is the issue:

1. Apply the following diff to the codebase:
    ```diff
    diff --git a/src/persist-client/src/read.rs b/src/persist-client/src/read.rs
    index 06512fdbe..77c898101 100644
    --- a/src/persist-client/src/read.rs
    +++ b/src/persist-client/src/read.rs
    @@ -677,15 +677,8 @@ where
         /// This is communicating actual progress information, so is given
         /// preferential treatment compared to Self::maybe_heartbeat_reader.
         pub async fn maybe_downgrade_since(&mut self, new_since: &Antichain<T>) {
    -        // NB: min_elapsed is intentionally smaller than the one in
    -        // maybe_heartbeat_reader (this is the preferential treatment mentioned
    -        // above).
    -        let min_elapsed = self.cfg.reader_lease_duration / 4;
    -        let elapsed_since_last_heartbeat =
    -            Duration::from_millis((self.cfg.now)().saturating_sub(self.last_heartbeat));
    -        if elapsed_since_last_heartbeat >= min_elapsed {
    -            self.downgrade_since(new_since).await;
    -        }
    +        // always downgrade immediately
    +        self.downgrade_since(new_since).await;
         }
     
         /// Heartbeats the read lease if necessary.
    diff --git a/src/storage/src/source/persist_source.rs b/src/storage/src/source/persist_source.rs
    index ae69dc87d..4f7796d79 100644
    --- a/src/storage/src/source/persist_source.rs
    +++ b/src/storage/src/source/persist_source.rs
    @@ -237,6 +237,8 @@ where
                 return;
             }
     
    +        // simulate a slow source startup
    +        tokio::time::sleep(std::time::Duration::from_secs(10)).await;
             let read = persist_clients_stream
                 .lock()
                 .await
    ```

2. Run Materialize: `bin/environmentd --reset`
3. Execute a SELECT and cancel it before 10 seconds have passed:
    ```
    materialize=> select * from mz_views;
    ^CCancel request sent
    ERROR:  canceling statement due to user request
    ```
4. Observe computed crash with the "cannot serve requested as_of" panic.

### Diagnosis

The issue demonstrated by the above reproduction (and probably also by the crash seen in production) is that replicas can report the dropping of a dataflow (through a `FrontierUppers([])` response) before the dataflow is actually fully cleaned up. Currently, when a collection is allowed to compact to the empty frontier, computed handles that as follows:

* Drop the trace or sink token associated with that collection.
* Step the timely worker once.
* Report the collection as dropped by sending a `FrontierUppers([])` response.

It that stepping of the timely worker doesn't cause all involved operators to notice the dropping of the dataflow tokens, they might still be running even after computed has reported that the dataflow was dropped.

In the case of the `persist_source`, it appears that stepping the worker once is not enough.

**Comment by frankmcsherry** [comment]
Fixed (we believe) by https://github.com/MaterializeInc/materialize/pull/15845.

**Comment by benesch** [comment]
Can no longer reproduce this in the affected customer environment, so this seems wholly fixed!
