### ISSUE TITLE
testdrive: improve regex support

### ISSUE THREAD

**Issue by sploiselle** [MaterializeInc/materialize#15853]
### Feature request

When using testdrive, I'd like the following features:
- multiple regex statements, e.g. I need to perform a replacement of some values OIDs and an arbitrary byte string.
- storing statements' capture group values, e.g. I want to compare some randomly generated OID in one statement to another, but I want to ensure they're the same and not that they're both numbers.

**Comment by benesch** [comment]
Contention: you might not want `$ set-regex` at all, as it's a blunt instrument. What you might want is `$ set-from-sql`, which lets you set a variable to the result of an arbitrary SQL statement, and then you can stitch that variable in as you like.

**Comment by sploiselle** [comment]
Ah, I hadn't seen `set-from-sql`; that would work.
