### ISSUE TITLE
dbt-materialize: remove 63 character limitation for auto-generated object names

### ISSUE THREAD

**Issue by morsapaes** [MaterializeInc/materialize#15863]
The `dbt-postgres` adapter forces a limit of 63 characters on relation names (see [dbt #2197](https://github.com/dbt-labs/dbt-core/issues/2197) for context), which leads to an error for auto-generated names that exceed that limit:

```sql
dbt.exceptions.RuntimeException: Runtime Error
  Relation name 'default_branch_history__synthesized_repo_id_default_branch_started_at_ended_at_idx' is longer than 63 characters
```

Materialize does not have this limitation, so we should override the shimmed behaviour ([relation.py](https://github.com/dbt-labs/dbt-core/blob/8e28f5906e60f7c97e874e9dd5962625267d336e/plugins/postgres/dbt/adapters/postgres/relation.py#L8)) to avoid hitting this error when _e.g._ users don't specify the `name` config for indexes. One other thing we could improve is print the relation type the error refers to.

**Comment by benesch** [comment]
I'm surprised this comes up so often for our dbt users! Is it biting dbt-postgres users too, and the answer there is just "too bad, pick a custom name"? Or are we doing something different than dbt-postgres?

**Comment by benesch** [comment]
Vaguely recollecting that dbt-postgres uses some sort of hash as the index name?

**Comment by morsapaes** [comment]
Yeah, in `dbt-postgres` you get the runtime error and are expected to shorten the base relation name (for intermediate relations, the identifiers are truncated before being prepended with a suffix (see [dbt #4921](https://github.com/dbt-labs/dbt-core/pull/4921)).

> Vaguely recollecting that dbt-postgres uses some sort of hash as the index name?

This is used to address a different issue, described in [this discussion](https://discourse.getdbt.com/t/issue-with-post-hooks-not-running-with-dbt-0-16-1/1235/6). Since we don't handle relation recreation in a transaction, this isn't an issue for us.
