### ISSUE TITLE
Supporting Postgres Sources for `REPLICA IDENTITY DEFAULT`

### ISSUE THREAD

**Issue by nmeagan11** [MaterializeInc/materialize#15874]
### Feature request

When working with Postgres sources, users sometimes see the following error: ```ERROR:  Source error: X: Old row missing from replication stream for table with XXX = #####. Did you forget to set REPLICA IDENTITY to FULL for your table?```

For a Kafka + Debezium source, a user is free to leave the replica identity as `DEFAULT` because we have the upsert logic that can handle updates without the full row. However, for direct Postgres sources, we require all tables have `REPLICA IDENTITY` set to `FULL`, even if there's a primary key defined for the table. This is because we don't have any upsert logic and thus we need to stream in both the old and new row data whenever there is an update.

We've started to see examples where this is problematic for users. For example, they might not have `REPLICA IDENTITY` set to `FULL` on production due to potential impact on CPU usage and a larger volume of WAL logs (see the [official Postgres documentation](https://www.postgresql.org/docs/current/logical-replication-publication.html) for more information).

**Comment by guswynn** [comment]
This is a direct cpu-memory tradeoff right? I believe we have to be able to mirror their entire pg database in memory to offer upsert semantics, to avoid the cpu hit on the upstream database

**Comment by benesch** [comment]
That’s correct. We’re _really_ much better off if users can enable `REPLICA IDENTITY FULL` upstream. At least until we can spill upsert sources to disk.

**Comment by petrosagg** [comment]
Closing in favour of https://github.com/MaterializeInc/materialize/issues/17956
