### ISSUE TITLE
Better error messages for CREATE SOURCES

### ISSUE THREAD

**Issue by JLDLaughlin** [MaterializeInc/materialize#1588]
Testing in the demo environment, I hit two less-than-optimal error messages for `CREATE SOURCES`. Both are scenarios where we are ~correctly failing, but we're not giving the user enough context.

1. Creating a source from data that doesn't have the before/after wrapper. A user wouldn't reasonably know the required message format here. (Do we document the before/after wrapper anywhere at the moment @sploiselle @benesch?)
`jessicalaughlin=> CREATE SOURCES LIKE '%' FROM 'kafka://kafka:9092' USING SCHEMA REGISTRY 'http://schema-registry:8081';
ERROR:  source schema is missing 'before' field`

2. Creating a source from a bad schema type? It feels like this error message should include the actual schema name for the user to investigate.
`jessicalaughlin=> CREATE SOURCES LIKE 'mysql.%' FROM 'kafka://kafka:9092' USING SCHEMA REGISTRY 'http://schema-registry:8081';
ERROR:  Failed to parse schema: Unknown type: io.debezium.data.geometry.Geometry`

**Comment by rjnn** [comment]
Is the error message improved post source/envelope/format separation? @JLDLaughlin please re-test. I'm guessing that there's still improvements to be made here, but that we need a thorough re-diagnosis.

**Comment by JLDLaughlin** [comment]
A lot has changed since I created this ticket!

- `CREATE SOURCES` no longer exists as of [this commit](https://github.com/MaterializeInc/materialize/commit/5012eb2fd8ad5aad3c3b23573fc38fba5663bd72).
- `CREATE SOURCE` now explicitly requires a [`FORMAT` field](https://github.com/MaterializeInc/materialize/pull/1837/files#diff-ac3c8b6b533a02135b16a903ea3833d1) -- this eliminates the issue in the first bullet point.
- Since we can't `CREATE SOURCES` from a wildcard, there will be no ambiguity which schema failed to parse when creating a source -- this eliminates the issue in the second bullet point.

^ This is not meant to imply that `CREATE SOURCE` is bulletproof, but I can put testing `CREATE SOURCE` on my todo list and close this ticket in the meantime.
