### ISSUE TITLE
thread 'coordinator' panicked at 'Dataflow temp-view-t3 requested as_of (Antichain { elements: [1667501333584] }) not >= since (Antichain { elements: [1667501333950] })',

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#15887]
### What version of Materialize are you using?

d95dec641b

### How did you install Materialize?

Docker image

### What is the issue?

Previously seen as : https://github.com/MaterializeInc/materialize/issues/8241
Now seen in: https://buildkite.com/materialize/tests/builds/44464#01843ebc-9dec-40af-9026-84b388be7e7e

### Relevant log output

```source
thread 'coordinator' panicked at 'Dataflow temp-view-t3 requested as_of (Antichain { elements: [1667501333584] }) not >= since (Antichain { elements: [1667501333950] })', /var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-07409f6093c7cd99b-1/materialize/tests/src/adapter/src/coord/dataflows.rs:162:13
stack backtrace:
   0: rust_begin_unwind
   1: core::panicking::panic_fmt
   2: mz_adapter::coord::dataflows::<impl mz_adapter::coord::Coordinator<S>>::finalize_dataflow
   3: mz_adapter::coord::peek::<impl mz_adapter::coord::Coordinator<S>>::create_peek_plan
   4: mz_adapter::coord::sequencer::<impl mz_adapter::coord::Coordinator<S>>::sequence_peek::{{closure}}::{{closure}}
   5: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   6: mz_adapter::coord::sequencer::<impl mz_adapter::coord::Coordinator<S>>::sequence_plan::{{closure}}::{{closure}}
   7: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   8: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   9: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  10: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  11: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  12: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
  13: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  14: mz_adapter::coord::message_handler::<impl mz_adapter::coord::Coordinator<S>>::handle_message::{{closure}}
  15: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  16: std::thread::local::LocalKey<T>::with
  17: tokio::park::thread::CachedParkThread::block_on
  18: tokio::runtime::handle::Handle::block_on
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by philip-stoev** [comment]
@frankmcsherry said in Slack:
> It looks pretty [#team-surfaces](https://materializeinc.slack.com/archives/C02FWJ94HME) to me!
> coordinator tried to build a dataflow it knew that it shouldn't try to build

**Comment by philip-stoev** [comment]
@mjibson FYI

**Comment by jkosh44** [comment]
So this is fairly reproducible for me, I did some investigating and this is my initial analysis.

## Background
- `as_of` is the timestamp selected for the query by the Coordinator.
- `since` is the actual since of the collections used by the dataflow to execute the query.
- The error is saying that the since is not less than or equal to the selected timestamp of the collections so the query cannot be executed because the data has been compacted at that timestamp.
- The error happens in `cluster_log_compaction.slt`
- The specific query that errors is `SELECT * FROM mz_internal.mz_arrangement_batches_internal_4;`

## Example Reproduction
Here I will walk through an example failure and explain what's going on:

### Timestamp Selection
The Coordinator uses the following collections to determine a timestamp:
```
id_bundle: {
	storage: [
		mz_view_keys
		mz_view_foreign_keys
		mz_kafka_sinks
		mz_kafka_connections
		mz_databases
		mz_schemas
		mz_columns
		mz_indexes
		mz_index_columns
		mz_tables
		mz_sources
		mz_sinks
		mz_views
		mz_materialized_views
		mz_types
		mz_array_types
		mz_base_types
		mz_list_types
		mz_map_types
		mz_roles
		mz_pseudo_types
		mz_functions
		mz_clusters
		mz_secrets
		mz_connections
		mz_ssh_tunnel_connections
		mz_cluster_replicas
		mz_cluster_replica_statuses
		mz_cluster_replica_heartbeats
		mz_audit_events
		mz_storage_usage_by_shard
		mz_egress_ips
		mz_sink_status_history
		mz_source_status_history
		mz_storage_shards
		mz_dataflow_operators_1
		mz_dataflow_channels_1
		mz_scheduling_elapsed_internal_1
		mz_raw_compute_operator_durations_internal_1
		mz_dataflow_addresses_1
		mz_scheduling_parks_internal_1
		mz_message_counts_sent_internal_1
		mz_message_counts_received_internal_1
		mz_dataflow_operator_reachability_internal_1
		mz_arrangement_batches_internal_1
		mz_arrangement_records_internal_1
		mz_arrangement_sharing_internal_1
		mz_compute_exports_1
		mz_worker_compute_dependencies_1
		mz_worker_compute_frontiers_1
		mz_worker_compute_import_frontiers_1
		mz_raw_worker_compute_delays_1
		mz_active_peeks_1
		mz_raw_peek_durations_1
		mz_dataflow_operators_2
		mz_dataflow_channels_2
		mz_scheduling_elapsed_internal_2
		mz_raw_compute_operator_durations_internal_2
		mz_dataflow_addresses_2
		mz_scheduling_parks_internal_2
		mz_message_counts_sent_internal_2
		mz_message_counts_received_internal_2
		mz_dataflow_operator_reachability_internal_2
		mz_arrangement_batches_internal_2
		mz_arrangement_records_internal_2
		mz_arrangement_sharing_internal_2
		mz_compute_exports_2
		mz_worker_compute_dependencies_2
		mz_worker_compute_frontiers_2
		mz_worker_compute_import_frontiers_2
		mz_raw_worker_compute_delays_2
		mz_active_peeks_2
		mz_raw_peek_durations_2
		mz_dataflow_operators_3
		mz_dataflow_channels_3
		mz_scheduling_elapsed_internal_3
		mz_raw_compute_operator_durations_internal_3
		mz_dataflow_addresses_3
		mz_scheduling_parks_internal_3
		mz_message_counts_sent_internal_3
		mz_message_counts_received_internal_3
		mz_dataflow_operator_reachability_internal_3
		mz_arrangement_batches_internal_3
		mz_arrangement_records_internal_3
		mz_arrangement_sharing_internal_3
		mz_compute_exports_3
		mz_worker_compute_dependencies_3
		mz_worker_compute_frontiers_3
		mz_worker_compute_import_frontiers_3
		mz_raw_worker_compute_delays_3
		mz_active_peeks_3
		mz_raw_peek_durations_3
		mz_dataflow_operators_4
		mz_dataflow_channels_4
		mz_scheduling_elapsed_internal_4
		mz_raw_compute_operator_durations_internal_4
		mz_dataflow_addresses_4
		mz_scheduling_parks_internal_4
		mz_message_counts_sent_internal_4
		mz_message_counts_received_internal_4
		mz_dataflow_operator_reachability_internal_4
		mz_arrangement_batches_internal_4
		mz_arrangement_records_internal_4
		mz_arrangement_sharing_internal_4
		mz_compute_exports_4
		mz_worker_compute_dependencies_4
		mz_worker_compute_frontiers_4
		mz_worker_compute_import_frontiers_4
		mz_raw_worker_compute_delays_4
		mz_active_peeks_4
		mz_raw_peek_durations_4
	]
	compute: {
		u2: [
			mz_arrangement_sharing_internal_u2_primary_idx
			mz_arrangement_batches_internal_u2_primary_idx
			mz_arrangement_records_internal_u2_primary_idx
			mz_dataflow_channels_u2_primary_idx
			mz_dataflow_operators_u2_primary_idx
			mz_dataflow_addresses_u2_primary_idx
			mz_dataflow_operator_reachability_internal_u2_primary_idx
			mz_compute_exports_u2_primary_idx
			mz_worker_compute_dependencies_u2_primary_idx
			mz_message_counts_received_internal_u2_primary_idx
			mz_message_counts_sent_internal_u2_primary_idx
			mz_active_peeks_u2_primary_idx
			mz_raw_peek_durations_u2_primary_idx
			mz_scheduling_elapsed_internal_u2_primary_idx
			mz_raw_compute_operator_durations_internal_u2_primary_idx
			mz_scheduling_parks_internal_u2_primary_idx
			mz_worker_compute_frontiers_u2_primary_idx
			mz_worker_compute_import_frontiers_u2_primary_idx
			mz_raw_worker_compute_delays_u2_primary_idx
		]
	}
}
```
- **IMPORTANT**: `mz_arrangement_batches_internal_4` is one of many collections in that id bundle.
- It's not entirely clear to me why there are so many collections in there and not just `mz_arrangement_batches_internal_4`.
- The since of all those collections is `1667573951000`.
- The upper of all those collections is `0`.
  - This is somewhat concerning, but doesn't seem related to this specific error.
- The global timestamp is `1667573951336`.
- The timestamp selected is `1667573951336` (this is equal to the global timestamp which is larger than the since).

### Dataflow 1
A dataflow is created with the following collections:
```
id_bundle:{
	storage: [
		mz_databases
		mz_schemas
		mz_types
		mz_array_types
		mz_base_types
		mz_list_types
		mz_map_types
		mz_pseudo_types
		mz_functions
	]
	compute: {
		u2: [
		]
	}
}
```
- I'm not sure what this dataflow is for.
- The since of these collections is `1667573950000`.
- The selected timestamp (as_of) for this dataflow is `1667573951336` (This is the same value from timestamp selection).
- This dataflow can execute because the since is less than the selected timestamp.

### Dataflow 2
A dataflow is created with the following collections:
```
id_bundle:{
	storage: [
		mz_arrangement_batches_internal_4
	]
	compute: {
		u2: [
		]
	}
}
```
- This looks like the dataflow that will actually implement the peek.
- The since of these collections is `1667573952000`
  - **IMPORTANT**: This is larger than the since of the collections from timestamp selection. This should not be possible since this is strictly a subset of the collections used in timestamp selection.
- The selected timestamp (as_of) for this dataflow is `1667573951336` (This is the same value from timestamp selection).
- This dataflow CAN NOT execute because the since is NOT less than or equal to the selected timestamp.
  - This dataflow produces the error in the test.

## Possible Causes
- Somehow we compact `mz_arrangement_batches_internal_4` after the timestamp is selected, but before the dataflow is executed.
- Our logic to determine the since of collections is wrong.

**Comment by jkosh44** [comment]
Ok, I found the issue:

All read holds on an object get combined into a single ReadPolicy::ValidFrom(Antichain<T>) policy. When we update a read hold from ts to ts', we update the Antichain with (ts, -1) and (ts', +1).
If two people have a read hold on object o at the same time ts, the resulting Antichain will only have a single element ts. If one of them tries to update their read hold, it will implicitly drop the other read hold.
This specific error is happening when the transaction read hold is at the same time as the global timeline read hold. The global timeline updates their read hold, which implicitly drops the transaction's read hold, and allows the object to compact past what the selected timestamp is.

**Comment by jkosh44** [comment]
Ok, now I have actually found the issue.

Some (maybe all) introspection sources have a compute and storage component. However, those two components share the same global id. In the Coordinator we track read capabilities by global id, and make no distinction between compute and storage collections: https://github.com/MaterializeInc/materialize/blob/feb1194154f067b7ecd22b03d0069f7f5d3b0af4/src/adapter/src/coord.rs#L384-L392
An unintended consequence of this is that the storage and compute component of the introspection source share the same read capability. This leads to inconsistencies in what their read policies should be.

Here's a concrete example to show what's going on:
0. The `mz_arrangement_batches_internal_4` introspection source has global id `s553`.
1. A storage object with global id `s553` is created with a read hold at `ts`, initializing the read capability for `s553` to `[(ts, 1)]`.
2. A compute object with global id `s553` is created with a read hold at `ts`, overwriting the read capability for `s553` to `[(ts, 1)]`.
3. A transaction is started with query `SELECT * FROM mz_internal.mz_arrangement_batches_internal_4;`
4. A read hold is acquired for the compute object with global id `s553` at timestamp `ts`. This updated the read capability  for `s553` to `[(ts, 2)]`.
5. The global timeline advances it's read holds on all objects
  a. The read hold for the storage object with global id `s553` is updated from `ts` to `ts'`. This updates the read capability for `s553` to `[(ts, 1), (ts', 1)]`.
  b. The read hold for the compute object with global id `s553` is updated from `ts` to `ts'`. This updates the read capability for `s553` to `[(ts', 2)]`.
6. We've effectively dropped the transaction's read hold at `ts` before it has a chance to execute.

**Comment by teskje** [comment]
> Some (maybe all) introspection sources have a compute and storage component.

It applies to the persisted introspection sources, which have a compute collection (the persist_sink) and a storage collection. It doesn't apply to arranged introspection sources, which only have an index.

Aside from persisted introspection sources, materialized views also consist of a compute and a storage component. So I assume this issue impacts those too.

**Comment by jkosh44** [comment]
> Aside from persisted introspection sources, materialized views also consist of a compute and a storage component. So I assume this issue impacts those too.

I was thinking the same thing.
