### ISSUE TITLE
Improving Postgres Source Errors

### ISSUE THREAD

**Issue by nmeagan11** [MaterializeInc/materialize#15892]
### Feature request

We've seen an uptick in requests for improving Postgres source errors. This is the "catch-all" issue in order to bundle all of the requests together into one place.

- [x] https://github.com/MaterializeInc/materialize/issues/15889
- [ ] https://github.com/MaterializeInc/materialize/issues/15890
- [x] https://github.com/MaterializeInc/materialize/issues/15605
- [ ] https://github.com/MaterializeInc/materialize/issues/15499

**Comment by aljoscha** [comment]
Closing this one since the remaining issues are visible now when searching for the `T-PG` tag.
