### ISSUE TITLE
environmentd: health metrics

### ISSUE THREAD

**Issue by mjibson** [MaterializeInc/materialize#15906]
environmentd and its components (adapter, coord, controllers) should each determine their own health metrics for use when understanding problems. The best places to export those today are prometheus or via a sql query where the results of the query are the metric. (For example, an external measurement of how long it takes to execute a query does not qualify.)

Some ideas are:

- [ ] coordinator message processing times (histogram/other thing of latencies? largest time in some collection interval?)
- [ ] coordinator pending queue depth
- [ ] ^ is maybe very hard so: coord idle time waiting for new messages. we expect this to sometimes be greater than 0, otherwise it means we are falling behind on queue processing.
- [ ] coordinator queue delay for user queries (how long did a user request sit in the coord queue before being processed)
- [x] stash transaction times
- [ ] startup time, possibly with more detailed inner metrics for each step
- [ ] latency on an environmentd ping (to be able to see distribution of request latency generally, during/after upgrades)

cc @jpepin @hlburak

**Comment by mjibson** [comment]
I know little about how tokio works. Looking at that link I'm not sure I'd be able to use those metrics to help me understand problems with environmentd or the coordinator. If async folks think these are useful, is it possible they can be included in ore::metrics automatically so no one has to choose whether or not to include them?

**Comment by pH14** [comment]
Would love to collect tokio metrics, but they're still `unstable` right now 😞

**Comment by cove** [comment]
@mjibson since tokio is the core scheduler, that's also where we could see queue backups across the whole app is the thought. But sounds like it's not an option right now :(

**Comment by ggnall** [comment]
Added an item that I believe is related to this line of work that's needed for our availability "latency" measurements:
- Measure latency of `SELECT 1` with serializable isolation level across customer environments

**Comment by mjibson** [comment]
Constant queries (like `select 1`) aren't affected by transaction isolation mode, don't ever interact with computed or storaged, and always return immediately. They are an excellent metric for "is envd behind?" and total network+processing latency. We already collect them. See the "Environmentd Uptime" dashboard in grafana.

**Comment by mjibson** [comment]
We have enough of these done that we can close this.
