### ISSUE TITLE
storage: implement basic source/sink metrics

### ISSUE THREAD

**Issue by guswynn** [MaterializeInc/materialize#15904]
As part of M3, we want some basic metrics to be able to quickly determine the health of a source/sink. Below is the minimal list of metrics we feel are required, and their status

### K8s metrics
Many metrics come from k8s itself, so we already have these loaded in Prometheus and accessible in Grafana!

- [x] Pod network TX/RX
- [x] CPU utilization (both core count and % of limit)
- [x] Memory utilization (absolute and % of limit)
- [x] Uptime
- [x] Container restarts per-pod, edit: marking closed because we no longer halt in storage clusters
  - Its unclear if we distinguish panics/halts from upgrades, this needs to be checked
  - [x] Additionally, distinguishing panics and expected halts from each other requires inspecting the error code; its unclear if this is possible with k8s metrics

### Storage-specific metrics

- [x] "Source/Sink is active". This will likely be a Prometheus Counter of the last ts we progressed the source/sink too
- [x] Source ingestion rate
  - [x] commited vs uncommited
- [x] Sink push rate

## Additional required resolutions
- [x] Labeling by source name (edit, marking as done because its no longer relevant with cluster-unification
  - In Grafana/Prometheus currently we only have the pod name, which is just `storage-<source number>`. Ideally we could instead get metrics for a _source name_.
    - We could do this by adding k8s pod labels for the name, but this may not be a future-proof design, we will need to think about this!
  - [x] Additionally, we may want the pod name to include `sink` or `source`, like `storage-sink-u18`, etc; edit, marking as done because its no longer relevant with cluster-unification
- [x] change the container.name in honeycomb for `storaged` to `storaged` and not `default`

**Comment by aljoscha** [comment]
>  - "Source/Sink is active". This will likely be a Prometheus Counter of the last ts we progressed the source/sink too
>  - "Source/Sink health". May not be required if we have the "active" metrics

Aren't these two covered by the source/sink status/history collection and the exposed remap information?

**Comment by guswynn** [comment]
@aljoscha Yes! and when we expose them to users, will we use that information (modulo our team conversation today!); this issue is just tracking adding some basic _internal_ metrics!

**Comment by guswynn** [comment]
@aljoscha yes! I believe its all done!

**Comment by aljoscha** [comment]
I was wondering because many of the boxes are not yet ticked (but I also see that most of them would be ticked if we went through, but it seems not all of them?).

**Comment by guswynn** [comment]
Closing because cluster-unification has invalidated some of the list, and the rest of the list is implemented, both in `mz_sink/source_statistics` and duals in prometheus
