### ISSUE TITLE
Expose per-replica introspection queries in prometheus SQL exporter

### ISSUE THREAD

**Issue by umanwizard** [MaterializeInc/materialize#15921]
### Feature request

The Prometheus SQL exporter currently is provided with a hardcoded list of queries in a file, and periodically executes those queries.

For technical reasons which will probably not change anytime soon, queries that depend on introspection sources must be targeted at a specific replica, and in general, the set of replicas can change. When they change, we will need to update the Prometheus SQL exporter with a new set of queries.

One possible approach is as follows:
1. Run a pod in each environment that `SUBSCRIBE`s to a set of replicas; e.g.
```
SUBSCRIBE (
            SELECT c.name AS cluster_name, cr.name AS name
            FROM mz_cluster_replicas AS cr INNER JOIN mz_clusters AS c ON cr.cluster_id = c.id
        )
```
2. When a change in the set of replicas is detected, create a new `.yml` file and hit the `/reload` endpoint on the promsql-exporter. According to @jpepin : "we'd have to tweak the hash to prevent environment-controller restarting it anyway when the configs change."

**Comment by jpepin** [comment]
If we are willing to do the work to create a small service that reliably queries mz and takes action on the results, we might actually want to just fork or rewrite the prometheus sql exporter to be able to run dynamic queries. Then we can avoid this workaround entirely. I haven't dug into what that would require, but I don't think the sql exporter is too complex. It's also possible there are other off-the-shelf sql exporters that could do this.

**Comment by benesch** [comment]
Decision from our eng sync today: we'll write our own SQL exporter-like widget that's a bit smarter and capable of running queries dynamically against all cluster replicas that exist.

**Comment by benesch** [comment]
@umanwizard this got done with the new prom SQL exporter, no?

**Comment by teskje** [comment]
That's my understanding as well. Closing!
