### ISSUE TITLE
Measure impact of promsql queries on compute

### ISSUE THREAD

**Issue by umanwizard** [MaterializeInc/materialize#15922]
### Feature request

We do not want to cause compute to fall over because we're querying it for metrics.

We need to run a script like [this one](https://gist.github.com/umanwizard/61694876be96d798d73d5a9db73f767a) on compute with various workflows to see how much CPU load it generates. If it's too much, we may need to query less frequently or install some in-memory indexes for the queries in question.

This analysis will change once we start using persisted introspection queries, because then we will be executing all the queries on `mz_introspection`. This may require autoscaling the `mz_introspection` cluster, but until autoscaled clusters become available we can probably get away with just testing it on some huge set of replicas and verifying that it survives.

**Comment by teskje** [comment]
Closing because it seems to work fine in prod currently.
