### ISSUE TITLE
Pods not cleared despite dropping replica

### ISSUE THREAD

**Issue by umanwizard** [MaterializeInc/materialize#15947]
### What version of Materialize are you using?

staging

### How did you install Materialize?

Materialize Cloud

### What is the issue?

```
materialize=> select * from mz_audit_events where details::text like '%deleteme%' order by occurred_at desc;
 id | event_type |   object_type   |                                           details                                            |          user           |        occurred_at         
----+------------+-----------------+----------------------------------------------------------------------------------------------+-------------------------+----------------------------
 65 | drop       | cluster-replica | {"cluster_id":"u9","cluster_name":"btv1","replica_name":"deleteme"}                          | brennan@materialize.com | 2022-11-07 20:02:33.373+00
 64 | create     | cluster-replica | {"cluster_id":"u9","cluster_name":"btv1","logical_size":"6xlarge","replica_name":"deleteme"} | brennan@materialize.com | 2022-11-07 19:58:59.86+00
(2 rows)
```

But the pods for that giant replica are still around...

**Comment by benesch** [comment]
There's also #11616. If `environmentd` crashes after it commits the drop but before it tells Kubernetes to execute the drop, it'll orphan the cluster replica. Possibly exacerbated by the behavior of `run_message_loop`? Regardless—yes, we need to GC any unrecognized cluster replicas on startup! 

The [`Orchestrator::list_services`] exists to facilitate exactly this garbage collection. On `environmentd` startup, we should list all services, and delete any whose IDs are in the range [0, next_replica_id) that are not currently known to the catalog. (Don't want to delete anything above `next_replica_id` as those might have been created by an `environmentd` that just came online that we haven't yet detected.)

**Comment by lluki** [comment]
> But `run_message_loop` in `replica.rs` retries connecting forever, before it checks whether `DropInstance` has been sent and it should tell the orchestrator to shut down the statefulset.

Good catch, I think it was a mistake to inline the orchestrator interactions deep within the replica creation (see also me and @teskje comment thread: https://github.com/MaterializeInc/materialize/pull/15737#discussion_r1006936888 )

**Comment by teskje** [comment]
As noted in Slack: While we do want to clean up orphan pods during environmentd startup, we should also make sure that the bug described in this issue cannot occur in the first place. This bug enables leaking compute pods without an environmentd crash/restart involved, so it can take potentially a long time (until the next release) until those pods get cleaned up when environmentd eventually restarts.

On the plus side, we already have a good solution in mind (handling orchestrator calls on a separate task that is independent from the replica task) that would fix this issue and shouldn't be hard to implement.
