### ISSUE TITLE
computed, storage: computed leaks mem/cpu after drop materialized view

### ISSUE THREAD

**Issue by lluki** [MaterializeInc/materialize#15952]
### What version of Materialize are you using?

547ee465a580c1707d268df42f7544011a0bb404

### How did you install Materialize?

Built from source

### What is the issue?

After a sequence of `CREATE MATERIALIZED VIEW ..` + `DROP MATERIALIZED VIEW` computed keeps using more and more memory. An easy way to see that the state is not properly cleaned up is by looking at the running tokio tasks. For example by instrumenting `mz_ore::task_spawn` and printing the running tasks (as done for example [here](https://github.com/lluki/materialize/tree/dump-running-task) )

Computed also keeps using more and more CPU, which might caused by the same issue.

# Repro
Creating the remote replica is optional, but using an extra process is an easy way to get the logs only from that process:

Use or cherry-pick the last commit from this [tree](https://github.com/lluki/materialize/tree/dump-running-task) 
Run `./bin/environmentd`. Run in a separate pane:
```
cargo run --bin computed -- --secrets-reader=process --secrets-reader-process-dir=mzdata/secrets --controller-listen-addr=127.0.0.1:2300 --internal-http-listen-addr=127.0.0.1:2303 --pid-file-location=mzdata/compute-0.pid 2> >(tee -a stderr.log >&2)
```

```
CREATE CLUSTER c1 REPLICAS (r1 (REMOTE ['localhost:2300'], COMPUTE ['localhost:2301'], WORKERS 2));
SET CLUSTER TO c1;
CREATE TABLE t1 (f1 int);
```
Repeat `CREATE MATERIALIZED VIEW mv1 AS SELECT min(a) from t1; DROP MATERIALIZED VIEW mv1;`  

Check the running tokio tasks in `stderr.log`

# Initial diagnosis

The following tasks keep getting added:
```
LeaseStreamDrainer
PersistGcWorker
persist::heartbeat_read
persist::heartbeat_write
```

I don't know exactly what the heartbeat tasks are supposed to do, but it seems plausible that they should continue after a drop with some timeout. But even waiting for 30 minutes did not make these tasks disappear.

`PersistGcWorker` should stop immediately if the `ReadHandle` is dropped, because dropping the ReadHandle also drops the channel's sender and thus should propagate an error immediately which terminates the task. I haven't figure out yet why the read handles are not dropped in persist_source.

**Comment by teskje** [comment]
I looked at this with the tokio-console and can confirm that repeatedly creating and dropping materialized views causes a lot of mostly idle task to be created that seem to never be cleaned up. Of the ones mentioned above, I did not see `persist::heartbeat_write`, but I saw a couple unnamed ones.

The same behavior does not occur when creating and dropping indexes, or when doing simple selects from a table. It does occur if some time passes between creating the materialized view and dropping it, so this issue is not limited to quick create-drop sequences.

**Comment by teskje** [comment]
Removing `persist_source`'s `Drop` impl fixes the leak!

```diff
diff --git a/src/storage-client/src/source/persist_source.rs b/src/storage-client/src/source/persist_source.rs
index 5d2116a1b..aa8ed5f91 100644
--- a/src/storage-client/src/source/persist_source.rs
+++ b/src/storage-client/src/source/persist_source.rs
@@ -133,36 +133,6 @@ impl DropSafeLeaseStream {
     }
 }

-impl Drop for DropSafeLeaseStream {
-    fn drop(&mut self) {
-        let mut pin = self.pinned_stream.take().expect("pin only taken on drop");
-
-        mz_ore::task::spawn(|| "LeaseStreamDrainer", async move {
-            // Drain the remainder of the items from the stream; this ensures
-            // that nothing gets dropped while in flight.
-            //
-            // Note that at the end of this task, we expect the internal stream
-            // to have spawned another task that receives any leases returned to
-            // the subscribe.
-            while let Some(item) = pin.as_mut().next().await {
-                match item {
-                    Ok((parts, _)) => {
-                        for part in parts {
-                            // We don't expect this task to run for long, so we
-                            // don't bother sending leases back to `subscribe`;
-                            // this delays compaction slightly, so could instead
-                            // be optimized to meaningfully return batches
-                            // instead of dropping their leases on the floor.
-                            let _ = part.into_exchangeable_part();
-                        }
-                    }
-                    Err::<_, ExternalError>(_) => {}
-                }
-            }
-        });
-    }
-}
-
 /// Creates a new source that reads from a persist shard, distributing the work
 /// of reading data to all timely workers.
 ///
```

Of course the `Drop` impl is the whole point of `DropSafeLeaseStream`, so I'm pretty sure removing it is the wrong fix :D 

It seems like the stream reading from persist just never terminates, so the LeaseStreamDrainer can also never terminate?

**Comment by aljoscha** [comment]
nice find! @danhhz I seem to remember discussions about rolling back the logic we have around these leases and the drop impls (we recently changed something to make sure that the subscribe future can be dropped, I think?) should we maybe just remove this `Drop` impl and be also done with this one?

**Comment by petrosagg** [comment]
Removing that task entirely would be great, but how does the leak happen in the first place? A dropped sender should cause the task to exit

**Comment by teskje** [comment]
@petrosagg Some debug printing tells me that this loop never terminates: https://github.com/MaterializeInc/materialize/blob/df343265f17c35654fbec59270e76e7c6a45b3d5/src/storage-client/src/source/persist_source.rs#L321-L335

I assume what happens is that the `LeaseStreamDrainer` task keeps the stream alive (by continuing to read from it) and the stream keeps the `LeaseStreamDrainer` alive (by continually supplying new output). Or is there anything else that should abort the stream?

**Comment by danhhz** [comment]
> nice find! @danhhz I seem to remember discussions about rolling back the logic we have around these leases and the drop impls (we recently changed something to make sure that the subscribe future can be dropped, I think?) should we maybe just remove this `Drop` impl and be also done with this one?

yeah, after https://github.com/MaterializeInc/materialize/pull/15868, we shouldn't need this task anymore. delete away! (we're also happy to pick off the deletion PR if you like)

**Comment by aljoscha** [comment]
@teskje do you wan't to have the honours of removing it? 😅

**Comment by teskje** [comment]
Sure, removing code is what makes me happy :D

**Comment by teskje** [comment]
I wrote above:
> The same behavior does not occur when creating and dropping indexes, or when doing simple selects from a table.

I need to correct myself: The leak does not occur when doing SELECTs from tables, but it does occur when creating or dropping indexes. I guess I was confused by tokio-console somehow.

Basically, the leak always occurs when a dataflow instantiates a `persist_source` with `until` set to the empty frontier, because in this case there is nothing that would interrupt the persist reader loop. If `until` is not set to the empty frontier (as is the case for ad-hoc dataflows that are created to serve a single SELECT result), [the loop is interrupted as soon as the `until` frontier is reached](https://github.com/MaterializeInc/materialize/blob/df343265f17c35654fbec59270e76e7c6a45b3d5/src/storage-client/src/source/persist_source.rs#L328-L335), so the stream ends, so the LeaseStreamDrainer task terminates.

**Comment by danhhz** [comment]
@teskje, just wanted to confirm, did this fix all the task leaks?

**Comment by teskje** [comment]
Yes, as far as I can tell! I tested this by connecting to the tokio-console, running the create-then-drop-materialize-view statements a bunch of times, waited a while until the tokio-console would stop frantically adding and removing tasks, and verified that the total number of tasks afterwards was the same as before.

**Comment by danhhz** [comment]
> Of the ones mentioned above, I did not see persist::heartbeat_write

Oh just reread this whole issue and saw this. So I guess the theory is heartbeat_write was a false positive in OP?
