### ISSUE TITLE
Speed up `SELECT * FROM <source> LIMIT <small>`

### ISSUE THREAD

**Issue by rjnn** [MaterializeInc/materialize#15962]
**Original feature request.**

I have a 3xsmall load generator source that has run continuously for weeks.

```
materialize=> show sources;
     name      |      type      |  size   
---------------+----------------+---------
 ticker        | load-generator | 3xsmall
(1 row)

```

I ran

```
select * from ticker limit 5;
```

This has been running for ~15 minutes without returning, which is painful. All I wanted was a few results, and since i didn't specify an order, all the values didn't need to be loaded up - once the dataflow had 5 things streamed in, it had what it needed, and could have cancelled whatever was still running.

 v0.30.1 (85b85f6d1)

----

We have several prospects/customers who have implicitly asked for this by being frustrated by the performance of this class of query. Context for internal folks:

  * https://materializeinc.slack.com/archives/C04AW6GF29H/p1668715670392809 / https://materializeinc.slack.com/archives/CU7ELJ6E9/p1668715742811529
  * https://materializeinc.slack.com/archives/C02PPB50ZHS/p1668699840787169

**Comment by benesch** [comment]
Can you `EXPLAIN TIMESTAMP` on that query and post the results?

**Comment by rjnn** [comment]
```
materialize=> explain timestamp for select * from ticker limit 5;
                              Timestamp                              
---------------------------------------------------------------------
           query timestamp: 1667921891533 (2022-11-08 15:38:11.533) +
                     since:[1667921891000 (2022-11-08 15:38:11.000)]+
                     upper:[1667921892001 (2022-11-08 15:38:12.001)]+
          global timestamp: 1667921891533 (2022-11-08 15:38:11.533) +
   can respond immediately: true                                    +
                                                                    +
 source materialize.public.ticker (u2, storage):                    +
             read frontier:[1667921891000 (2022-11-08 15:38:11.000)]+
            write frontier:[1667921892001 (2022-11-08 15:38:12.001)]+
 
(1 row)

Time: 172.910 ms
```

**Comment by rjnn** [comment]
```
materialize=> select count(*) from mz_storage_usage where object_id = 'u2';
 count 
-------
   600
(1 row)
```

```
materialize=> select * from mz_storage_usage where object_id = 'u2' order by size_bytes desc;
 object_id | size_bytes  |    collection_timestamp    
-----------+-------------+----------------------------
 u2        | 50415130779 | 2022-11-08 15:18:10.088+00
 u2        | 50219840784 | 2022-11-08 14:14:51.775+00
 u2        | 50030808427 | 2022-11-08 13:11:32.115+00
 u2        | 49836166524 | 2022-11-08 12:08:10.943+00
 u2        | 49641863532 | 2022-11-08 11:04:54.793+00
 u2        | 49436382054 | 2022-11-08 10:01:39.779+00
```

**Comment by rjnn** [comment]
(creating a new issue for this one ^)

**Comment by mjibson** [comment]
Yes, it records snapshots for billing calculations.

**Comment by rjnn** [comment]
> This is the COUNTER generator? What's the tick interval?
Added more details in #15968. Let's discuss counter improvements there. We can use this issue to track the `LIMIT 1` optimization ask.

**Comment by benesch** [comment]
Migrated this to a feature request and added the compute team, since I think this optimization will happen in compute land.

**Comment by morsapaes** [comment]
Resurfacing this [comment](https://github.com/MaterializeInc/materialize/issues/12986#issuecomment-1149800717); it'd be helpful to have something akin to sampling for this exact purpose. During development and day-to-day debugging, it's really common that you just need to have a peek to see if data landed where it should + get a feel for how it looks.

**Comment by chuck-alt-delete** [comment]
Would it help to set isolation level to serializable first? That would mean the query can return a result more immediately at the cost of freshness. It’s more of a workaround, but it’s useful enough that it should be something we train our users to do in situations like these.

**Comment by benesch** [comment]
> Would it help to set isolation level to serializable first?

It wouldn't really move the needle on the issue at hand, I'm afraid. If you've got a 100GB shard, and you want to select one arbitrary row out of it, you might expect to only need to read in a few kilobytes or megabytes to find one such row, and then stop loading more data. But instead Materialize will read all 100GB, just to throw away 99.999GB. Whether you do that under serializable isolation or strict serializable isolation almost certainly doesn't matter; it's gonna be slow because we're reading 100GB of data when we could be reading a tiny fraction of that.

**Comment by benesch** [comment]
We believe that persist providing pre-consolidated output (https://github.com/MaterializeInc/materialize/pull/18244) is the next work item. Coupled with #17358, that would give us fast `SELECT ... LIMIT <small>` queries.

Slack conversations:

  * https://materializeinc.slack.com/archives/C01CFKM1QRF/p1682443354139019
  * https://materializeinc.slack.com/archives/C046X3RMWS0/p1683474121553749

@dseisun-materialize has agreed to figure out how to prioritize the required persist work and coordinate scheduling with the compute team.

**Comment by ggevay** [comment]
https://github.com/MaterializeInc/materialize/issues/21105 might also help with this somewhat: although it won't reduce the amount we read from Persist, but at least we won't be storing everything in memory before limiting it down. This can help avoid an OOM, and might also make things a bit faster.

**Comment by benesch** [comment]
Fixed by the new persist fast path for queries of this form: #21265.
