### ISSUE TITLE
Write blog post about "delta queries"

### ISSUE THREAD

**Issue by frankmcsherry** [MaterializeInc/materialize#1596]
Delta queries as a way to process multiway joins are an interesting, largely self-contained topic, and they have a few specific things they are supposed to do (maintain a low memory footprint, using common arrangements) that we should be able to observe (once they are working correctly). It also seems that there are some investigations to do, e.g. about ordering within each of the queries, that are a bit more of an interactive investigation rather than declarative exposition.

**Comment by rjnn** [comment]
deprecated in favor of the content calendar. please add this to the internal content calendar and then close this issue.

**Comment by frankmcsherry** [comment]
If the internal content calendar is that shared Google doc, it's already there. It's a bad way to mock up content though. (E.g. the text above wouldn't fly as a cell in a spreadsheet). What's the motivation for closing issues?
