### ISSUE TITLE
Write a blog post about the `materialized` architecture

### ISSUE THREAD

**Issue by frankmcsherry** [MaterializeInc/materialize#1597]
This is meant to be distinct from a post about the `materialized` "experience": this post covers the high-level architecture, giving names to the various modules, describes their responsibilities, and the ways in which they are different from traditional databases (e.g. SQL planning must fully decorrelate queries, IVM can be data-parallel because no transactions, etc).

The intended goal of the post is to set the reader up with an understanding of the moving parts that can then be invoked in follow-on posts that go in to more detail (for example, this post would be helpful reading before a delta-queries post, or a timestamp selection post, or a durability post).

For specific interesting content, my plan would be to cover arrangements, as a representative of "magical beans" present in `materialized`. But, could also punt on that if we think a "broad concepts, no specific detail" starter makes the most sense.

**Comment by rjnn** [comment]
deprecated in favor of the content calendar. please add this to the internal content calendar and then close this issue.
