### ISSUE TITLE
Stale load generator size options

### ISSUE THREAD

**Issue by ggevay** [MaterializeInc/materialize#15983]
### Documentation request

If I copy the [example code from the docs for the TPC-H load generator source](https://materialize.com/docs/sql/create-source/load-generator/#creating-a-tpch-load-generator)
it says 
```
ERROR:  unknown source size 3xsmall
HINT:  Valid sizes are: 1, 2, 4, 8, 16, 32
```
After changing from `'3xsmall'` to `'1'`, it works.

Also:
https://materialize.com/docs/sql/create-source/load-generator/#with-options

And I'm not sure if this affects other sources besides the load generator.

**Comment by benesch** [comment]
This one is working as intended, I'm afraid! The T-shirt sizes are only valid in Materialize Cloud. When running locally, you use numeric sizes that correspond directly to numbers of workers.

**Comment by ggevay** [comment]
Oh, ok, I see, thank you!
