### ISSUE TITLE
TAIL should have an optional 'no update' second-by-second watermark output

### ISSUE THREAD

**Issue by rjnn** [MaterializeInc/materialize#1600]
Currently `tail` gives no indication if there are no changes. It would be nice if `tail` gave us a sense of progress with watermarks.

**Comment by frankmcsherry** [comment]
TAIL related ping for @cirego: This seems plausible to have a null row, zero-diff ping every so often in order to confirm the absence of changes. This is also important for listeners who want to be certain that they have received all updates for a specific time. 

We could also just have an otherwise empty line with a timestamp to indicate a heartbeat
```
TIME
```

**Comment by cirego** [comment]
Is the idea that someone wants to know that query is still relevant as of a given timestamp? I'm still no clear on the proper terminology here, but something like a TIMESTAMP with no rows would allow the client to update a "Relevant AS OF timestamp" to their version of the view.

**Comment by frankmcsherry** [comment]
That, but also: if you wanted to use the diffs that you saw as output from TAIL, you would need to know when they were done for a timestamp. Until that happens, you might get another diff for the same time in just a moment. The occasional ping indicating "actually done; nothing else coming" clarifies that.

**Comment by cirego** [comment]
To handle "knowing when you can do something with the out of TAIL", could this not also be satisfied by having a record that indicates the closing of a `TIME` with records?

**Comment by rjnn** [comment]
Also to minimize the latency between when you get the results to when you get the notification that the records are closed out, you could push the close out message at `t+1` nanoseconds (or as @cirego suggests, at `t` records, depending on the semantics you want - i prefer `t+1`)

**Comment by awang** [comment]
assigning to @mjibson since this seems like it's part of your TAILv2 work

**Comment by cuongdo** [comment]
This can now be inferred using [FETCH](https://materialize.com/docs/sql/fetch/) with the following procedure:
1. `DECLARE c CURSOR  FOR TAIL t`
2. `FETCH ALL c WITH timeout='0s'` (example found [here](https://materialize.com/docs/sql/tail/)) returns all rows available now without waiting

If step 2 returns no rows, the TAIL has no new changes.
