### ISSUE TITLE
Unhelpful "mz_timestamp out of range" error message when casting a decimal to mz_timestamp

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#16023]
### What version of Materialize are you using?

 v0.32.0-dev (ae57dbcdd)

### How did you install Materialize?

Docker image

### What is the issue?

Our docs say that `mz_timestamp` can be produced out of `numeric`, but this errors out with a weird error message:

```
materialize=> select 1.51::mz_timestamp;
ERROR:  mz_timestamp out of range
```

It has to be a round number to work:

```
materialize=> select 1::mz_timestamp;
 mz_timestamp 
--------------
 1
```

@mjibson FYI

**Comment by mjibson** [comment]
This is known and by design. How did you encounter this?

**Comment by chaas** [comment]
@philip-stoev Would adding a detail or hint message to the error help?

Our docs for `mz_timestamp` do say "Integer, numeric, and text casts must be in the form of milliseconds since the Unix epoch", so that implies a round number.

I'm curious to see what the full query you were attempting to run that produced this error.

**Comment by mjibson** [comment]
We could add a hint/detail to https://github.com/MaterializeInc/materialize/blob/c385ad6efa5db9af0db7450151db8ca56235e78e/src/expr/src/scalar/func/impls/mz_timestamp.rs#L48 that says this!

**Comment by philip-stoev** [comment]
@chaas the original query that I tried had a fragment like this:

```
materialize=> select extract('epoch' from now())::mz_timestamp;
ERROR:  mz_timestamp out of range
```
Note that `extract 'epoch'` returns **seconds** with a fractional part so the query above is wrong in not multiplying the result from `extract` by 1000 in order to get rid of the fractions and produce **milliseconds**.

Once you multiply by 1000, it all works as expected, because in Mz the fractional part from extract epoch always has scale 3, so never more than 3 digits after he decimal point. I believe however this is an implementation artifact in Mz, as it is not the case in Postgres proper, where scale =6 is returned and multiplying such a number by 1000 does not get rid of the entire fractional part.

(If I am really creative, I could write a SQL expression that returns milliseconds and fractions, and that would error out.)

**Comment by philip-stoev** [comment]
@mjibson a HINT would be a good workaround, especially if there is already a known code block where it can be plugged. Maybe the documentation should also re-iterate that the number passed needs to be round, so that it is not implied, but stated right away.

**Comment by mjibson** [comment]
What's the motivation to use `extract('epoch' from now())::mz_timestamp` at all? `now()::mz_timestamp` is better!

**Comment by chaas** [comment]
Added a hint in #16207 , and created ticket #16219 to include failing conversion value in cast errors going forward.
