### ISSUE TITLE
S3 sources: CSV header not guaranteed to be ingested first (sporadic failure in csv-sources.td)

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#16048]
### What version of Materialize are you using?

b3b7dff

### How did you install Materialize?

Docker image

### What is the issue?

in `test/testdrive/csv-sources.td`, we have:

```
$ s3-put-object bucket=test key=static.csv
city,state,zip
Rochester,NY,14618
New York,NY,10004
"bad,
place""",CA,92679
```

And then we create a source that we expect to fail with an error that indicates that the header of the S3 key is different from the one provided in the `CREATE SOURCE` command:

```
> CREATE SOURCE mismatched_column_names
  FROM S3 CONNECTION s3_conn
  DISCOVER OBJECTS MATCHING 'static.csv' USING BUCKET SCAN 'testdrive-test-${testdrive.seed}'
  FORMAT CSV WITH HEADER (cities, country, zip)
! SELECT * FROM mismatched_column_names
contains:first mismatched column at index 1 expected=cities actual="city"
```

However, when running the same test in cloudtest/k8s, it sometimes fails as follows:

https://buildkite.com/materialize/nightlies/builds/1370#018470f9-6e18-491c-b8b0-ae44a96c25b4

```
testdrive/csv-sources.td:60:1: error: expected error containing "first mismatched column at index 1 expected=cities actual=\"city\"", got "Decode error: Text: CSV error at record number 2: expected 3 columns, got 1."
--
  | \|
  | 59 \|   FORMAT CSV WITH HEADER (cities, country, zip)
  | 60 \| ! SELECT * FROM mismatched_column_names
```

The error indicates that the previous-to-last row of the CSV data was ingested before the header row, which implies that ingestion is not fully deterministic.

**Comment by philip-stoev** [comment]
Another failure of the same mold:

```


CREATE SOURCE mismatched_column_names_count FROM S3 CONNECTION s3_conn DISCOVER OBJECTS MATCHING 'static.csv' USING BUCKET SCAN 'testdrive-test-2265584801' FORMAT CSV WITH HEADER (cities, state)
--
  | rows match; continuing at ts 1668109750.202957
  | > SELECT * FROM mismatched_column_names_count
  | query error didn't match; sleeping to see if dataflow produces error shortly 50ms 75ms 113ms 169ms 253ms 380ms 570ms 854ms 1s 2s 3s 4s 6s 10s 15s 22s 33s 22s^^^ +++
  | csv-sources.td:67:1: error: expected error containing "CSV error at record number 1: expected 2 columns, got 3", got "Decode error: Text: CSV error at record number 2: expected 2 columns, got 3."
  | \|
  | 66 \|   FORMAT CSV WITH HEADER (cities, state)
  | 67 \| ! SELECT * FROM mismatched_column_names_count
  | \| ^
```

The record number is different between the expected and the actual error message.

**Comment by philip-stoev** [comment]
Discussion regarding what non-determinism is acceptable and what is not -- https://materializeinc.slack.com/archives/C01CFKM1QRF/p1668412143815809 . It appears that @petrosagg thinks that the header should always be ingested first, regardless of the fact that multiple storaged workers are in effect, because it is a single S3 key/CSV file that is being processed.

**Comment by philip-stoev** [comment]
Something is truly wrong with the CSV + HEADER source. This is the failure on a CSV "file" that has 1 header and 1 data row:

```


csv-sources.td:69:1: error: expected error containing "first mismatched column at index 1 expected=cities actual=\"city\"", got "Decode error: Text: CSV error at record number 2: expected 3 columns, got 1."
--
  | \|
  | 68 \|   FORMAT CSV WITH HEADER (cities, country, zip)
  | 69 \| ! SELECT * FROM mismatched_column_names
  | \| ^
```
the error is about "record number 2" but there is no record number 2 in the CSV .

**Comment by philip-stoev** [comment]
Here is another failure:

```


csv-sources.td:173:1: error: expected error containing "Decode error: Text: CSV error at record number 2: invalid UTF-8", got "Decode error: Text: CSV error at record number 3: invalid UTF-8 (invalid utf-8 sequence of 1 bytes from index 7)"
--
  | \|
  | 172 \|
  | 173 \| ! SELECT * FROM bad_text_csv
  | \| ^

```
There is neither record number 3 in this CSV ... there is not even record number 2 -- it has 1 record and 1 header.

**Comment by benesch** [comment]
Closing as obsolete. We no longer have S3 sources.
