### ISSUE TITLE
[Epic] `persist` Performance

### ISSUE THREAD

**Issue by nmeagan11** [MaterializeInc/materialize#16062]
### Product Outcome

`persist` will meet performance SLAs for a given workload.
 
### Specification

TBBD

### Design

TBD

### Documentation

N/A

### Required Issues (Must Haves)

TBD

### Discretionary Issues (Nice To Haves)

TBD

### Blockers

None

**Comment by aljoscha** [comment]
Superseded by more fine-grained issues.
