### ISSUE TITLE
[Epic] Internal Observability for Storage

### ISSUE THREAD

**Issue by nmeagan11** [MaterializeInc/materialize#16061]
### Product Outcome

Engineering requires a more robust method to debug and troubleshoot the storage layer, particularly the source ingestion pipeline.

### Specification

TBD

### Design

TBD

### Documentation

Internal documentation as part of the tasks is required.

### Required Issues (Must Haves)

- [ ] Subset of https://github.com/MaterializeInc/materialize/issues/15904

Rest are TBD.

### Discretionary Issues (Nice To Haves)

TBD

### Blockers

None

**Comment by uce** [comment]
Closing as no work remains.
