### ISSUE TITLE
PrivateLink limit verification happens too late

### ISSUE THREAD

**Issue by benesch** [MaterializeInc/materialize#16072]
### What version of Materialize are you using?

v0.31.0-dev

### How did you install Materialize?

Materialize Cloud

### What is the issue?

Verification of `max_aws_privatelink_connections` happens too late. If the `CREATE CONNECTION` fails with a "limit exceeded" error, while the connection object is not installed in the catalog, the `VpcEndpoint` resource _is_. This means we actually try to initiate a connection to the PrivateLink endpoint... and because we don't have GC of these `VpcEndpoint` resources, they will never get cleaned up.

**Comment by jkosh44** [comment]
I don't think this is specific to the resource limits check. `catalog_transact` is not guaranteed to succeed and may return an error as per it's API. Limit exceeded is just one of those errors:
https://github.com/MaterializeInc/materialize/blob/75c66ac1a15f1be237a398ff27b530bd84781e6d/src/adapter/src/coord/ddl.rs#L54-L72

I'm assuming this is where the `VpcEndpoint` resource is being created:
https://github.com/MaterializeInc/materialize/blob/75c66ac1a15f1be237a398ff27b530bd84781e6d/src/adapter/src/coord/sequencer.rs#L613-L625

Which happens right before `catalog_transact` below:
https://github.com/MaterializeInc/materialize/blob/75c66ac1a15f1be237a398ff27b530bd84781e6d/src/adapter/src/coord/sequencer.rs#L640-L648

Which means that any error in `catalog_transact` will leak the resource. Could we just delete the endpoint in the error branch of `catalog_transact`?:
https://github.com/MaterializeInc/materialize/blob/75c66ac1a15f1be237a398ff27b530bd84781e6d/src/adapter/src/coord/sequencer.rs#L646

**Comment by jkosh44** [comment]
Better yet actually, I think that we should only be creating the `VpcEndpoint`, if `catalog_transact` was successful.

**Comment by benesch** [comment]
> Better yet actually, I think that we should only be creating the `VpcEndpoint`, if `catalog_transact` was successful.

That sounds exactly right to me!

**Comment by jkosh44** [comment]
Note, it looks like the exact same issue exists for SSH connection secrets as well. So I'll try and fix that at the same time.
