### ISSUE TITLE
storage: `persist_source` latency scales with number of workers

### ISSUE THREAD

**Issue by benesch** [MaterializeInc/materialize#16090]
We noticed in a customer environment that the latency of queries against a persist source seems to scale with the number of workers per-process in the cluster. Here are some timings:

```
2xsmall
materialize=> select * from mz_views;
Time: 484.473 ms
materialize=> select * from mz_views;
Time: 397.870 ms
materialize=> select * from mz_views;
Time: 604.381 ms
materialize=> select * from mz_views;
Time: 412.148 ms

xsmall
materialize=> select * from mz_views;
Time: 450.758 ms
materialize=> select * from mz_views;
Time: 400.150 ms
materialize=> select * from mz_views;
Time: 393.060 ms
materialize=> select * from mz_views;
Time: 429.285 ms

small
materialize=> select * from mz_views;
Time: 587.237 ms
materialize=> select * from mz_views;
Time: 608.190 ms
materialize=> select * from mz_views;
Time: 557.064 ms
materialize=> select * from mz_views;
Time: 482.227 ms
materialize=> select * from mz_views;
Time: 541.872 ms

medium
materialize=> select * from mz_views;
Time: 1037.786 ms (00:01.038)
materialize=> select * from mz_views;
Time: 1032.083 ms (00:01.032)
materialize=> select * from mz_views;
Time: 1065.255 ms (00:01.065)
materialize=> select * from mz_views;
Time: 1315.665 ms (00:01.316)

large
materialize=> select * from mz_views;
Time: 2104.311 ms (00:02.104)
materialize=> select * from mz_views;
Time: 1607.603 ms (00:01.608)
materialize=> select * from mz_views;
Time: 1862.535 ms (00:01.863)
materialize=> select * from mz_views;
Time: 2551.174 ms (00:02.551)

xlarge
materialize=> select * from mz_views;
Time: 3973.676 ms (00:03.974)
materialize=> select * from mz_views;
Time: 4989.184 ms (00:04.989)
materialize=> select * from mz_views;
Time: 4526.773 ms (00:04.527)
materialize=> select * from mz_views;
Time: 4216.659 ms (00:04.217)

2xlarge
materialize=> select * from mz_views;
Time: 4577.487 ms (00:04.577)
materialize=> select * from mz_views;
Time: 2157.412 ms (00:02.157)
materialize=> select * from mz_views;
Time: 5688.162 ms (00:05.688)
materialize=> select * from mz_views;
Time: 4961.007 ms (00:04.961)
materialize=> select * from mz_views;
Time: 3797.427 ms (00:03.797)
```

Of particular interest is the fact that the performance seems stable in a 2xlarge. This suggests that there is some sort of per _process_ bottleneck, rather than a per _worker_ bottleneck.

Initial hypothesis, from discussion with @danhhz, is that we are serially acquiring a mutex, worker by worker, while opening persist connections. This would explain why the latency scales up with number of workers _until_ you add another process, at which point the latency stays constant, as each process gets a fresh mutex.

This seems to reproduce readily in a fresh cloud environment. It may also reproduce locally—no one's tried yet!

@aljoscha @danhhz or @uce—could you prioritize this one?

**Comment by aljoscha** [comment]
There are (at least) two problems that are causing this bad scaling behaviour:

1. We lock on the `PersistClientCache` when creating the `ReadHandle`s and `BatchFetcher`s in the different operators and we hold the lock for longer than is necessary
2. The "fetcher operators" (the operators that are doing the actual data fetching) only need a `BatchFetcher`. Currently, only way of getting one of those is to create a `ReadHandle` and then turn that into a `BatchFetcher`. Creating the `ReadHandle` requires expensive `Consensus` operations while we could directly create a `BatchFetcher` from a `PersistClient`, with a slight risk of mis-usage.

I'll have a PR up shortly that fixes both issues in separate commits and we can see how much we like each fix.

**Comment by danhhz** [comment]
(Well I did say it was probably some dumb bug 😅.) Thanks for looking into this and typing up the fixes, @aljoscha!
