### ISSUE TITLE
persist: track who created each reader and writer in State

### ISSUE THREAD

**Issue by danhhz** [MaterializeInc/materialize#16091]
### Feature request

It would have been useful in various debugging sessions to have been able to see which process created each reader and/or writer.

This is pretty straightforward from the persist side, but I don't have a great sense for where we'd get the string that tells us the "who".

**Comment by danhhz** [comment]
> I don't have a great sense for where we'd get the string that tells us the "who".

Assigning to @benesch to route this part. Once we have it figured out, I'm happy to wire it up.

**Comment by danhhz** [comment]
Friendly ping! :) Any idea who might have ideas here?

**Comment by pH14** [comment]
I've generally wanted two things while debugging: which process owns the handle (e.g. `computed-u1-replica-1-0`), and a user-provided name for that usage (e.g. `compute::persist_sink`). If it's not already plumbed through some `clap` arg, the pod/process name is available when running on Kube as the `HOSTNAME` env var, and the user-provided name could be passed in to `PersistClient::open_(reader|writer)`

And once we have these available, I would also not mind if we tagged each state transition with the handle that performed the CaS. Then our changefeed will show a total history of all ops and who actually performed them!

**Comment by benesch** [comment]
So sorry, I think it's as easy for me to try to do this vs explain how to do it. I have some loosely formed thoughts. The service name is passed by the process orchestrator via `--log-prefix` and I think we can separate that into `--service-name` and `--enable-log-prefix` options, where the first is always provided and the second is conditionally enabled by the process orchestrator.

**Comment by benesch** [comment]
I didn't have the time this weekend that I'd hoped. Maybe the above is enough to go on? I'll try to get to it tomorrow am, but no promises.

**Comment by danhhz** [comment]
Let's see! Btw, is there an issue with using `HOSTNAME`?

**Comment by benesch** [comment]
It won't work with the process orchestrator. That's probably a 1000% fine
first pass, though, if you want to wire something up ASAP!

**Comment by benesch** [comment]
Perfect! Good thought on the HOSTNAME thing.
