### ISSUE TITLE
protobuf: support imported message types

### ISSUE THREAD

**Issue by quodlibetor** [MaterializeInc/materialize#1611]
Lower priority than well-known types (#1550), currently just a nice-to-have but long term it's part of protobuf support.

**Comment by elindsey** [comment]
This should also include support for imports when using schemas stored in the confluent schema registry - meaning we'll need support for chasing down schema references in csr responses (https://docs.confluent.io/platform/current/schema-registry/serdes-develop/index.html#referenced-schemas)

**Comment by cjubb39** [comment]
Fixed by #8720
