### ISSUE TITLE
storage: support using SSH tunnels with Kafka

### ISSUE THREAD

**Issue by benesch** [MaterializeInc/materialize#16125]
### Feature request

The work we recently did to allow using Kafka via AWS PrivateLink teed us up to also support using Kafka via an SSH tunnel. The key is the broker rewrite functionality that we added to librdkafka (https://github.com/edenhill/librdkafka/pull/4051). I haven't actually tried this, but as far as I can tell it is conceptually sound, and not very much work.

All we'd have to do is extend the `create_with_context` method here...

https://github.com/MaterializeInc/materialize/blob/bd023393318bfef078edd2e073d6778efeebec43/src/storage-client/src/types/connections.rs#L353

...to launch an SSH connection per broker...

https://github.com/MaterializeInc/materialize/blob/bd023393318bfef078edd2e073d6778efeebec43/src/ssh-util/src/tunnel.rs#L50-L54

...and then install the appropriate per-broker rewrite rules to route connections through the tunnel.

cc @uce @gus

**Comment by guswynn** [comment]
first step is `resolve_cb` support in rust-rdkafka

**Comment by guswynn** [comment]
Additionally, in the resolution callback we need to _create_ a ssh-tunnel, which requires doing io in a blocking context, so we will need to ensure that this runs on rdkafka threads

**Comment by benesch** [comment]
Got done in #16158!
