### ISSUE TITLE
storage: disable `statement_timeout` when snapshotting Postgres source

### ISSUE THREAD

**Issue by benesch** [MaterializeInc/materialize#16123]
We've observed evidence in a customer deployment of a replication snapshot timing out due to the configured server-side value of the `statement_timeout` parameter. The error message looks like this:

```
2022-11-17T04:33:16.352814Z  WARN mz_storage::source::postgres: halting process: replication snapshot for source up[redacted] failed: db error: ERROR: canceling statement due to statement timeout
```

I'm not 100% certain, but I suspect this only happens if you set `statement_timeout` in postgresql.conf on the server side. I can't imagine that _we're_ setting a `statement_timeout` anywhere.

PostgreSQL's documentation has this to say:

> Setting statement_timeout in postgresql.conf is not recommended because it would affect all sessions.

But we can't expect users to abide by that. We should explicitly set the `statement_timeout` to 0 (disabled) on the snapshot connection, to override any default the user might have set.

cc @guswynn @petrosagg @sploiselle @uce

**Comment by guswynn** [comment]
@benesch does pg actually respect the client's wishes if its configured on the server-side?

**Comment by benesch** [comment]
> @benesch does pg actually respect the client's wishes if its configured on the server-side?

I'd imagine so, based on how other configuration parameters work in PostgreSQL.
