### ISSUE TITLE
regression?: The long multi-node Maelstrom test has started failing

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#16149]
### What version of Materialize are you using?

c7911b6

### How did you install Materialize?

Docker image

### What is the issue?

This test never gave trouble previously, but is now failed twice before succeeding

https://buildkite.com/materialize/nightlies/builds/1393#01848ab9-7fb8-47ea-9307-8bdc272f4f42

There are pieces of a stack trace , but no topmost "panicked at" line.

**Comment by danhhz** [comment]
Looks like we got a copy of the untruncated stack trace in the node logs. This points at #15822 but I haven't looked at specifically what's going wrong yet. ```thread 'tokio-runtime-worker' panicked at 'assertion failed: self.read_ts >= since_ts', src/persist-client/examples/maelstrom/txn.rs:237:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/panicking.rs:142:14
   2: core::panicking::panic
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/panicking.rs:48:5
   3: persistcli::maelstrom::txn::Transactor::read::{{closure}}
             at /var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-031345435ea8355bb-1/materialize/tests/src/persist-client/examples/maelstrom/txn.rs:237:9
   4: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/future/mod.rs:91:19
   5: persistcli::maelstrom::txn::Transactor::transact::{{closure}}
             at /var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-031345435ea8355bb-1/materialize/tests/src/persist-client/examples/maelstrom/txn.rs:196:36
   6: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/future/mod.rs:91:19
   7: <persistcli::maelstrom::txn::TransactorService as persistcli::maelstrom::node::Service>::eval::{{closure}}
             at /var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-031345435ea8355bb-1/materialize/tests/src/persist-client/examples/maelstrom/txn.rs:564:57
   8: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/future/mod.rs:91:19
   9: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/future/future.rs:124:9
  10: persistcli::maelstrom::node::Node<S>::handle::{{closure}}
             at /var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-031345435ea8355bb-1/materialize/tests/src/persist-client/examples/maelstrom/node.rs:130:61
  11: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/future/mod.rs:91:19
  12: tokio::runtime::task::core::CoreStage<T>::poll::{{closure}}
             at /cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/task/core.rs:165:17
  13: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at /cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/loom/std/unsafe_cell.rs:14:9
  14: tokio::runtime::task::core::CoreStage<T>::poll
             at /cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/task/core.rs:155:13
  15: tokio::runtime::task::harness::poll_future::{{closure}}
             at /cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/task/harness.rs:480:19
  16: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/panic/unwind_safe.rs:271:9
  17: std::panicking::try::do_call
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:492:40
  18: std::panicking::try
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:456:19
  19: std::panic::catch_unwind
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panic.rs:137:14
  20: tokio::runtime::task::harness::poll_future
             at /cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/task/harness.rs:468:18
  21: tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at /cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/task/harness.rs:104:27
  22: tokio::runtime::task::harness::Harness<T,S>::poll
             at /cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/task/harness.rs:57:15
  23: tokio::runtime::task::raw::RawTask::poll
             at /cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/task/raw.rs:84:18
  24: tokio::runtime::task::LocalNotified<S>::run
             at /cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/task/mod.rs:381:9
  25: tokio::runtime::thread_pool::worker::Context::run_task::{{closure}}
             at /cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/thread_pool/worker.rs:435:13
  26: tokio::coop::with_budget::{{closure}}
             at /cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/coop.rs:102:9
  27: std::thread::local::LocalKey<T>::try_with
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/thread/local.rs:445:16
  28: std::thread::local::LocalKey<T>::with
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/thread/local.rs:421:9
  29: tokio::coop::with_budget
             at /cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/coop.rs:95:5
  30: tokio::coop::budget
             at /cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/coop.rs:72:5
  31: tokio::runtime::thread_pool::worker::Context::run_task
             at /cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/thread_pool/worker.rs:434:9
  32: tokio::runtime::thread_pool::worker::Context::run
             at /cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/thread_pool/worker.rs:401:24
  33: tokio::runtime::thread_pool::worker::run::{{closure}}
             at /cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/thread_pool/worker.rs:386:17
  34: tokio::macros::scoped_tls::ScopedKey<T>::set
             at /cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/macros/scoped_tls.rs:61:9
  35: tokio::runtime::thread_pool::worker::run
             at /cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/thread_pool/worker.rs:383:5
  36: tokio::runtime::thread_pool::worker::Launch::launch::{{closure}}
             at /cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/thread_pool/worker.rs:362:45
  37: <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll
             at /cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/blocking/task.rs:42:21
  38: tokio::runtime::task::core::CoreStage<T>::poll::{{closure}}
             at /cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/task/core.rs:165:17
  39: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at /cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/loom/std/unsafe_cell.rs:14:9
  40: tokio::runtime::task::core::CoreStage<T>::poll
             at /cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/task/core.rs:155:13
  41: tokio::runtime::task::harness::poll_future::{{closure}}
             at /cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/task/harness.rs:480:19
  42: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/panic/unwind_safe.rs:271:9
  43: std::panicking::try::do_call
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:492:40
  44: std::panicking::try
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:456:19
  45: std::panic::catch_unwind
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panic.rs:137:14
  46: tokio::runtime::task::harness::poll_future
             at /cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/task/harness.rs:468:18
  47: tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at /cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/task/harness.rs:104:27
  48: tokio::runtime::task::harness::Harness<T,S>::poll
             at /cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/task/harness.rs:57:15
  49: tokio::runtime::task::raw::RawTask::poll
             at /cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/task/raw.rs:84:18
  50: tokio::runtime::task::UnownedTask<S>::run
             at /cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/task/mod.rs:418:9
  51: tokio::runtime::blocking::pool::Task::run
             at /cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/blocking/pool.rs:91:9
  52: tokio::runtime::blocking::pool::Inner::run
             at /cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/blocking/pool.rs:325:17
  53: tokio::runtime::blocking::pool::Spawner::spawn_thread::{{closure}}
             at /cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/blocking/pool.rs:300:13
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.```

**Comment by danhhz** [comment]
Summary of below is that this is an issue in test code, not a prod bug 😅 

Ah, this was just a brainfart when updating maelstrom to try to maximally exercise critical since handles in https://github.com/MaterializeInc/materialize/pull/15822. Before that PR, each copy of Transactor had a ReadHandle and thus its own since capability. This allowed it to know and assert that it could read at read_ts because it only ever updated the since capability itself to things that were less than read_ts. 15822 changed it so all Transactors shared a single CriticalReaderId and thus a single since capability, so it's possible for some other Transactor to move it past your read_ts. If we _were_ able to proceed with this read_ts, we'd just find out in compare_and_append that it's out of date and we'd get a new read_ts that _is_ above the since_ts

Some initial ideas for fixing:
- Give each Transactor its own critical reader. This basically kills any interesting coverage we get from maelstrom of critical handles, so I'm gonna veto.
- Allow a Transactor to forward its read_ts to since_ts when it discovers that its read_ts is out of date. This I think would work, but I can't think of a way to detect that this only happened under the race I outlined above (vs say something bad happened that we want the test to detect and fail one).
- Maybe some variant of the second one where each Transactor uses its maelstrom node id as the opaque token for CaDS. Whenever it gets a token mismatch, it's free to update the read_ts to at least the since_ts.
