### ISSUE TITLE
storage: `persist_sink` uses excessive CPU

### ISSUE THREAD

**Issue by benesch** [MaterializeInc/materialize#16146]
We have evidence that `persist_sink` can use excessive CPU. It seemingly spends unnecessary time consolidating updates that don't actually consolidate, starting the rest of the system of the ability to do work.

Lots more detail on Slack: https://materializeinc.slack.com/archives/C01CFKM1QRF/p1668698182706039

Filing this issue so we don't forget. @uce @aljoscha — can one of you triage and prioritize this appropriately?

cc @frankmcsherry

**Comment by aljoscha** [comment]
Thanks, I'd have created this today myself! :bow:
