### ISSUE TITLE
Support using AZ-specific services when consuming a privatelink connection in kafka

### ISSUE THREAD

**Issue by alex-hunt-materialize** [MaterializeInc/materialize#16145]
### Feature request

Currently, a privatelink connection may support multiple AZs, but we only have a single K8S service directing to all of them. This is problematic for kafka, since it needs to directly talk to each of the brokers in their AZ. The single K8S service prioritizes the AZ of the pod to avoid cross-AZ traffic, so cannot reach brokers in other AZs.

We have a [ticket to add AZ-specific K8S services](https://github.com/MaterializeInc/cloud/issues/4656), but we also need to support specifying which AZ each kafka broker is in, and use these AZ-specific services for DNS.

**Comment by benesch** [comment]
Candidate syntax is:

```
CREATE CONNECTION privatelink_svc TO AWS PRIVATELINK (
    SERVICE NAME 'com.amazonaws.vpce.us-east-1.vpce-svc-0e123abc123198abc',
    AVAILABILITY ZONES ('use1-az1', 'use1-az4')
);

CREATE CONNECTION kafka_connection TO KAFKA (
    BROKERS (
        'broker1:9092' USING AWS PRIVATELINK privatelink_svc (AVAILABILITY ZONE 'use1-az1'),
        'broker2:9092' USING AWS PRIVATELINK privatelink_svc (AVAILABILITY ZONE 'use1-az4', PORT 9093)
    )
);
```

**Comment by chaas** [comment]
@alex-hunt-materialize Does the AZ listed in the `CREATE CONNECTION kafka_connection TO KAFKA...USING AWS PRIVATELINK` statement need to be one of the AZ values listed in the `CREATE CONNECTION privatelink_svc TO AWS PRIVATELINK` statement? E.g. do we need to do some sort of validation on the input?

**Comment by chaas** [comment]
Also should the `AVAILABILITY ZONE` option be optional or required?

**Comment by benesch** [comment]
> @alex-hunt-materialize Does the AZ listed in the `CREATE CONNECTION kafka_connection TO KAFKA...USING AWS PRIVATELINK` statement need to be one of the AZ values listed in the `CREATE CONNECTION privatelink_svc TO AWS PRIVATELINK` statement? E.g. do we need to do some sort of validation on the input?

Yes, it does!

> Also should the `AVAILABILITY ZONE` option be optional or required?

Optional. When an AZ is not is not specified, the behavior should be the same as it is currently: traffic is directed to the Kubernetes service that routes to any of the specified AZs. When an AZ is specified, traffic should be directed to the AZ-specific service.

**Comment by chaas** [comment]
Great thanks @benesch !

I have the parsing working such that the az is passed thru to the `AwsPrivatelink` `Tunnel` object in the `storage-client` (and is validated). What else needs to be changed to actually use the AZ to determine which AZ-specific services to use for DNS?

**Comment by benesch** [comment]
Ah, yeah, the service naming is:

* `<CONN-ID>` for all-AZ services
* `<CONN-ID>-<AZ>` for AZ-specific services

So it should be a simple matter of `format!("{conn_id}-{az}")` in the storage client. We can double check with @alex-hunt-materialize in the PR review.

**Comment by chaas** [comment]
Is that this logic
https://github.com/MaterializeInc/materialize/blob/5ce64d24889973dd30b459c8fe88ce36c654d5a9/src/cloud-resources/src/lib.rs#L152-L157

If so, does that mean we need to update all VPC logic that uses that function, e.g. `delete_vpc_endpoint` to handle az-specific vpc names?

**Comment by benesch** [comment]
Oh, we're conflating the name and the hostname right now. Something like this should do it! (Easier to explain with code than words.)

```diff
diff --git a/src/cloud-resources/src/lib.rs b/src/cloud-resources/src/lib.rs
index 77fd0edf9c..6cba0ce324 100644
--- a/src/cloud-resources/src/lib.rs
+++ b/src/cloud-resources/src/lib.rs
@@ -155,3 +155,12 @@ pub fn vpc_endpoint_name(id: GlobalId) -> String {
     // cloud infrastructure layer.
     format!("connection-{id}")
 }
+
+/// Returns the host to use for the VPC endpoint with the given ID and
+/// optionally in the given availability zone.
+pub fn vpc_endpoint_host(id: GlobalId, az: String) -> String {
+    let name = vpc_endpoint_name(id);
+    // This naming scheme is part of the contract with the VpcEndpointController
+    // in the cloud infrastructure layer.
+    format!("{name}-{az}")
+}
diff --git a/src/storage-client/src/types/connections.rs b/src/storage-client/src/types/connections.rs
index db83a0121e..0aee589cdb 100644
--- a/src/storage-client/src/types/connections.rs
+++ b/src/storage-client/src/types/connections.rs
@@ -328,9 +328,10 @@ impl KafkaConnection {
                     // By default, don't override broker address lookup.
                 }
                 Tunnel::AwsPrivatelink(aws_privatelink) => {
+                    let az = "todo".into();
                     context.add_broker_rewrite(
                         &broker.address,
-                        &mz_cloud_resources::vpc_endpoint_name(aws_privatelink.connection_id),
+                        &mz_cloud_resources::vpc_endpoint_host(aws_privatelink.connection_id, az),
                         aws_privatelink.port,
                     );
                 }
@@ -565,8 +566,9 @@ impl CsrConnection {
                     .url
                     .host_str()
                     .ok_or_else(|| anyhow!("url missing host"))?;
+                let az = "todo".into();
                 let privatelink_host =
-                    mz_cloud_resources::vpc_endpoint_name(connection.connection_id);
+                    mz_cloud_resources::vpc_endpoint_host(connection.connection_id, az);
                 let addrs: Vec<_> = net::lookup_host((privatelink_host, DUMMY_PORT))
                     .await
                     .context("resolving PrivateLink host")?
```

**Comment by alex-hunt-materialize** [comment]
There is only one VpcEndpoint object per connection, but there are multiple Services associated with the VpcEndpoint (one for each specific AZ, plus one AZ-agnostic).

As Nikhil put in his code snippet, we're currently equivocating on the DNS name of the service and the K8S object name of the VpcEndpoint. We need to split those up, and use the DNS name of the service when connecting.

**Comment by benesch** [comment]
I believe Cara’s latest version of the PR handles this correctly!

**Comment by benesch** [comment]
(Er, forgot to say explicitly: your eyes on the PR would be very much appreciated, @alex-hunt-materialize! We need someone (probably you or Bobby) to make sure that it actually works.)

**Comment by alex-hunt-materialize** [comment]
I'm currently stuck when trying to test this. Attempting to create a source using a kafka connection going through privatelink just hangs forever.

**Comment by benesch** [comment]
Recommend enabling librdkafka debug logs on the envd pod.
—log-filter=librdkafka=debug

**Comment by alex-hunt-materialize** [comment]
I'm not sure what I did, but it now has data and seems to be working. Perhaps the source only picks up data added to kafka after it has subscribed.

**Comment by chaas** [comment]
done via https://github.com/MaterializeInc/materialize/pull/17006
