### ISSUE TITLE
Expose AWS PrivateLink connection principal components in SQL

### ISSUE THREAD

**Issue by benesch** [MaterializeInc/materialize#16140]
### Feature request

To create an AWS PrivateLink connection, customers need to hand construct the AWS principal that Materialize will connect as, so that they configure their endpoint service to allow connections from this principal. Constructing the principal requires the "external ID" associated with their region. This is a UUID we generate randomly when we create their region. See [our PrivateLink connection documentation](https://materialize.com/docs/sql/create-connection/#permissions) for details.

We do not currently expose this ID to the user, and require that they contact support. As I helpfully demonstrated today, this is a very error prone process.

We should make the external ID available in SQL. There are two options here. We may want to do both:

  * Add a `mz_aws_external_id()` function, which returns the external ID associated with the region
  * Add a system catalog table named `mz_aws_privatelink_connections` with a `principal` column that exposes the fully rendered name of the AWS principal (`arn:aws:iam::664411391173:role/mz_eb5cb59b-e2fe-41f3-87ca-d2176a495345_u1234`). 

cc @ggnall @chaas @alex-hunt-materialize 

Update - this is the master tracker - tasks are:
- [x] #16446
- [x] #16447
- [x] #16448
- [x] #16449

**Comment by alex-hunt-materialize** [comment]
I definitely think we should at least include a way to get the fully rendered principal. We should not expect users to build the ARN themselves, even if we give them the external ID.

**Comment by ggnall** [comment]
We will pick up this work for release in the next cycle. If we're going surface ARN (latter option), should we also include `external_id` in the same table/query? From a pure ux perspective I would opt to.

**Comment by ggnall** [comment]
Open: is there additional data that needs to be surfaced from cloud? If not, the above holds true. If not we'll need help from @alex-hunt-materialize

**Comment by benesch** [comment]
> We will pick up this work for release in the next cycle. If we're going surface ARN (latter option), should we also include `external_id` in the same table/query? From a pure ux perspective I would opt to.

If we want to expose the external ID directly, I think we want to do so via a function like `mz_aws_external_id()`. The AWS external ID is a property of the region as a whole, not an individual PL connection, so it'd be a bit weird to add it as a column in the `mz_aws_privatelink_connections` table.

> Open: is there additional data that needs to be surfaced from cloud?

I think so. I think cloud needs to pass in the AWS account ID, so that `environmentd` can use it when constructing the ARN. Or, maybe we can just make an AWS STS get caller identity call, and pull the AWS ID out of that. 🤷🏽

**Comment by benesch** [comment]
Thinking about it more, we definitely want to accept the AWS account ID to use in the ARN as a CLI parameter. Otherwise it will be impossible to test this in cloudtest.

**Comment by chaas** [comment]
@alex-hunt-materialize let's sync up on this - I'm happy to add the system table & do the plumbing if you help w/ getting the AWS account id.
I see we already have the `aws_external_id_prefix` in the `ConnectionContext` of the adapter `Config`.

**Comment by benesch** [comment]
Since @alex-hunt-materialize is on vacation until next Monday, @chaas I'm happy to stand in for Alex and say that the cloud team can definitely pass a flag like `--aws-privatelink-account-id` to `environmentd` that contains the AWS account ID to use in the principal.

**Comment by alex-hunt-materialize** [comment]
Do we want the arg to be specific to privatelink (or even to AWS)? Perhaps something like `--cloud-provider-account-id`?

**Comment by benesch** [comment]
I think it's fine for the arg to be specific to AWS, because the `AWS PRIVATELINK` connection type is totally specific to AWS. We won't even provide that connection type and table when we build out our Azure/GCP support.

**Comment by alex-hunt-materialize** [comment]
Is there any other reason we might need to expose the account ID? Is this privatelink specific?

**Comment by benesch** [comment]
> Is there any other reason we might need to expose the account ID?

I think we'll eventually want it for S3 connections, to tell users what principal to allow.

**Comment by alex-hunt-materialize** [comment]
So, `--aws-account-id` then?

@chaas Is there anything you need from cloud right now? We can't pass the argument from the environment-controller until it's supported in environmentd.

**Comment by chaas** [comment]
@alex-hunt-materialize I can go ahead and get started on the envd changes assuming we'll have an `environmentd` flag like `--aws-account-id`. I'll keep you posted if I run into anything and add you to the PR.

**Comment by chaas** [comment]
I actually ran into one question - based on the example it looks like the format of the fully rendered principal is
`arn:aws:iam::{aws account id}:role/{aws external id prefix}_{global id}`.

Where is this global Id coming from and does it need to be included in the principal?

**Comment by alex-hunt-materialize** [comment]
The global ID is the ID of the `AWS PRIVATELINK CONNECTION` SQL object.
The full principal also has an `mz_` that you're missing.

`arn:aws:iam::{aws_account_id}:role/mz_{aws_external_id_prefix}_{global_id}`

**Comment by chaas** [comment]
Ah hmm so we probably want this table to have a column `connection id` in addition to `principal` and have one per privatelink connection.
I was originally thinking this was a static single value we could populate on startup.

**Comment by alex-hunt-materialize** [comment]
Exactly. Every connection has a unique principal.

**Comment by benesch** [comment]
Yeah! It should work just like the `mz_ssh_tunnel_connections` table!
