### ISSUE TITLE
Redundant NOTICE of status not ready on setting of cluster

### ISSUE THREAD

**Issue by heeringa** [MaterializeInc/materialize#16159]
### What version of Materialize are you using?

 v0.32.0 (b04623960)

### How did you install Materialize?

Materialize Cloud

### What is the issue?

I have an existing default cluster with a static TPC-H load generator, a counter load generator and one materialized view created from the counter load generator:

```
Time: 1444.237 ms (00:01.444)
materialize=> show materialized views;
       name       | cluster 
------------------+---------
 streaming_counts | default
(1 row)

Time: 442.867 ms
materialize=> show sources;
   name   |      type      |  size   
----------+----------------+---------
 counter  | load-generator | 3xsmall
 customer | subsource      | 
 lineitem | subsource      | 
 nation   | subsource      | 
 orders   | subsource      | 
 part     | subsource      | 
 partsupp | subsource      | 
 region   | subsource      | 
 supplier | subsource      | 
 tpch     | load-generator | 3xsmall
(10 rows)

Time: 686.873 ms
materialize=> show clusters;
       name       
------------------
 c2
 default
 mz_introspection
 mz_system
(4 rows)

Time: 173.219 ms
materialize=> 
```

I created a new cluster with two replicas:

```
materialize=> create cluster c2 replicas (r1 (size = '2xsmall'), r2 (size = 'xsmall'));
CREATE CLUSTER
Time: 589.573 ms
```

and when I switch to the cluster, there are redundant Notices:

```
materialize=> set cluster = c2;
NOTICE:  cluster replica c2.r1 changed status to: NotReady
NOTICE:  cluster replica c2.r2 changed status to: NotReady
NOTICE:  cluster replica c2.r2 changed status to: NotReady
NOTICE:  cluster replica c2.r1 changed status to: NotReady
NOTICE:  cluster replica c2.r1 changed status to: NotReady
NOTICE:  cluster replica c2.r2 changed status to: NotReady
SET
Time: 42.467 ms
materialize=> 
```

I would expect on a single NOTICE here on the switch.

**Comment by benesch** [comment]
Well that truly makes not a whole lot of sense. We thought we disabled this notice entirely in #16001. Baffling!

**Comment by benesch** [comment]
I just added this to the surfaces team and flagged @mjibson. cc @chaas @ggnall for triage. I'm going to poke for a second myself, too.

**Comment by benesch** [comment]
Oh, I see the bug. `Session::drain_notices` ought to be using `recv_notice`, but it is not.

**Comment by benesch** [comment]
@mjibson do you have the time to adjust `drain_notices` to call `recv_notices` in a loop? I think that explains all the duplicate notices we were seeing here, too: https://github.com/MaterializeInc/materialize/issues/15692#issuecomment-1292997641

If we fix this, I'm inclined to say we should turn these back on, since they'll be way less spammy this time around. )Would recommend the slight wording tweak I proposed in #16002, too.)

**Comment by mjibson** [comment]
Will do.
