### ISSUE TITLE
Creating views with built in limit statements doesn't work

### ISSUE THREAD

**Issue by ruchirK** [MaterializeInc/materialize#1624]
I encountered this while working with the billing demo but if I have a kafka source named billing_source thats actively receiving data and I do

`create view v1 as select * from billing_source;`
`create view v2 as select * from billing_source limit 10` and wait for both views to be installed

and then I do

`peek v2;` I get the empty set
`select * from v2 limit 10; i get the empty set
`select * from v1 limit 10` i get 10 rows of data

I didnt try `peek v1` because i had thousands of rows and I didnt want to wait forever and the underlying plans for the two select queries look the same

**Comment by rjnn** [comment]
Possibly higher priority than just 0.2 - we should look at this asap and maybe even get a fix in 0.1.1.

**Comment by ruchirK** [comment]
Ok. I'll look at this today

**Comment by ruchirK** [comment]
cannot repro with timestamping thread on -- likely this was an issue in the past if I created this view and didnt insert more data into kafka. I think its fine to close this now
