### ISSUE TITLE
Figure out how to do historical queries against the metrics tables

### ISSUE THREAD

**Issue by umanwizard** [MaterializeInc/materialize#16246]
### Feature request

We now (on git main -- not released yet) have the `mz_internal.mz_cluster_replica_metrics` table which reports the latest known CPU and RAM usage metrics.

However, I am guessing that the people working on customer-visible observability (e.g. @RobinClowers and @parkerhendo ) will want to show some graphs over time, not just the latest known value.

(Aside: this is in fact a very general problem in Materialize: people might want to know the result of queries at times other than the present. Materialize is designed under the hood to make this possible, but it is not currently exposed to users.)

Some possible solutions for the specific use case of the metrics UI:

1. Do the work to allow historical queries in Materialize. This first of all requires exposing the ability to control logical compaction. We would also probably want something richer than just `AS OF` queries, because we would want you to be able to get several values in one query, not have to repeat slight variations on the query several times.
2. Just hack around the limitation by adding timestamps to the table and keeping multiple rows per process, one at each timestamp (then we need to add some code to delete old data according to some policy, so we're basically simulating logical compaction in a crappier way).
3. Have a sidecar pod running that queries the table periodically and writes down the results somewhere (again, this seems like reinventing logic that Materialize could just offer natively).

As should be clear from the caveats I put on (2) and (3), my initial intuition is that (1) is the best solution, but curious what others think.

**Comment by RobinClowers** [comment]
Yep, the design is pretty similar to grafana, where you can select several different time ranges to see this data plotted as lines.

I agree it sounds like 1 is the ideal solution, but I'm curious what how long that approach would take vs 2.

**Comment by umanwizard** [comment]
@benesch pointed out in a DM that `SUBSCRIBE ... AS OF` used to exist, and would give us exactly what we want, if the logical compaction window of the source were tuned appropriately.

**Comment by benesch** [comment]
We might also want `SUBSCRIBE ... AS OF ... UNTIL`, to make it a bit more convenient to use `SUBSCRIBE` in contexts where you _just_ want historical data, and not an ongoing subscription.

**Comment by RobinClowers** [comment]
Seems like we landed on using `SUBSCRIBE ... AS OF` with a custom compaction window for this, right? Should we close this issue?

**Comment by ggnall** [comment]
I think we can rename this so that the issue represents the implementation of `SUBSCRIBE ... AS OF`
