### ISSUE TITLE
Improve reclocking observability

### ISSUE THREAD

**Issue by uce** [MaterializeInc/materialize#16264]
### Feature request

*Follow up from incident 23 (https://github.com/MaterializeInc/cloud/issues/4681).*

Providing more visibility into reclocking will help us to determine _within Materialize_ how we're making progress on source ingestion. This is helpful to pinpoint customer issues, e.g. determine that's it's not an issue with a source.

cc @guswynn

**Comment by benesch** [comment]
Superseded by this source progress epic: https://github.com/MaterializeInc/materialize/issues/23154.
