### ISSUE TITLE
testing: Improve debugability of cloudtest

### ISSUE THREAD

**Issue by lluki** [MaterializeInc/materialize#16269]
### Feature request

Cloudtest is a high level integration test that focuses on the interaction of `environmentd` with the orchestrator. Debugging failures in cloudtest is tedious as the test is slow and does not report all information it could. This hampers developer performance when debugging problems in cloudtest. 

The following two features would improve the reporting of cloudtest:

 * Collect services logs after each test run. Right now, we only collect once the `services.log` at the very end of the cloudtest run. Unfortunately these contain only the log of the last incarnation of a service and cloudtest continues after a failed sub-test. Hence if the last test in the run is successful, the log does not contain anything interesting. Alternatively we could stop cloudtest after first failure.
 * Logging of orchestrator events. Kubernetes can stream orchestrator events, for example with `kubectl get events --watch` or  `kubectl rollout status -w`.

Ideally we would not pipe the outputs of these commands into a separate file (like we do now with the `services.log`, but pipe the output of those in the the stdout of the `pytest`. That makes it easy to correlate an actual test command with the test being run.

**Comment by philip-stoev** [comment]
Follow up issue to capture K8s status and pod logs as they happen, rather than after-the-fact https://github.com/MaterializeInc/materialize/issues/16322
