### ISSUE TITLE
Introduce backpressure mechanism for sources/sinks

### ISSUE THREAD

**Issue by uce** [MaterializeInc/materialize#16265]
### Feature request

*Follow up from incident 23 (https://github.com/MaterializeInc/cloud/issues/4681).*

We currently ingest data from upstream external systems as fast as we can which can result in (among other things) OOMs due to excessive buffering on the source ingestion pipeline. A backpressure mechanism will allow us to bound resource usage by throttling data ingestion. There is a similar problem on the sink side that requires throttling consumption from persist.

We have a [braindump from @guswynn in Notion](https://www.notion.so/materialize/Backpressure-for-Storage-0e0ef20d2caa465d8e926fa6a95f8cf4) and various implementation approaches have been discussed internally.

Note that this is a separate problem from #15974.

**Comment by benesch** [comment]
Superseded by #21989.
