### ISSUE TITLE
UpdateConfiguration compute command

### ISSUE THREAD

**Issue by teskje** [MaterializeInc/materialize#16273]
The `UpdateMaxResultSize` compute command is the first one that dynamically changes a configuration option of compute replicas. It is likely that other such commands will follow. To future-proof the compute command protocol, we should replace `UpdateMaxResultSize` by a more generic `UpdateConfiguration` command that can accommodate additional configuration options in the future.

While doing this, we can also remove a bit of redundancy by removing the `max_result_size` field from the configuration distributed with `CreateInstance` and instead arranging for an `UpdateConfiguration` command to be sent immediately after `CreateInstance`.

**Comment by frankmcsherry** [comment]
Drive by comment, but in the case of `MaxResultSize`, is there a reason this must be a configuration setting, rather than a `Peek` and `Subscribe` argument?

**Comment by teskje** [comment]
I can't think of a reason for compute, but there might be one for adapter. @jkosh44 would know!

**Comment by jkosh44** [comment]
> I can't think of a reason for compute, but there might be one for adapter. @jkosh44 would know!

I can't think of a reason either. Both ways would work fine.

**Comment by teskje** [comment]
One reason that occurred to me is that we might want to be able to change the limit after we have already started the peek/subscribe. But not sure how useful that would be.
