### ISSUE TITLE
Expose cpu and memory metrics of storage hosts

### ISSUE THREAD

**Issue by uce** [MaterializeInc/materialize#16323]
### Feature request

@umanwizard introduced all the infrastructure required to collect cpu and memory metrics. For compute cluster replicas, we:
1. Expose absolute cpu/memory metrics information via `mz_cluster_replica_metrics` (see https://github.com/MaterializeInc/materialize/pull/16209)
2. Enable % utilization metrics for by exposing replica sizes via `mz_internal.mz_cluster_replica_sizes` (see: https://github.com/MaterializeInc/materialize/pull/16516). Note that @umanwizard is updating this to include mappings for all pod sizes (and not just sizes already active in the user's environment).

We need to expose the same information for sources and sinks.

**Comment by uce** [comment]
@umanwizard @ggnall In the linked PR (#16209), @benesch asked whether we should have the unit as a suffix rather than a prefix:

> nano_cpus and bytes_memory are inconsistent with the rest of the system catalog, which use units as suffixes, rather than prefixes.

The current code still has the prefix variant. Did ya'll decide that we want to keep it that way?

**Comment by ggnall** [comment]
Let's keep it consistent, using units as suffixes.
> @umanwizard @ggnall In the linked PR (#16209), @benesch asked whether we should have the unit as a suffix rather than a prefix

**Comment by umanwizard** [comment]
`nano` isn't a unit, though. We can change it to `nano_cpus` and `memory_bytes`.

**Comment by ggnall** [comment]
I see. Yes, that works. Is "usage" necessary if we're not using it for memory as well? I would opt for:
`cpu_nano_cores` and `memory_bytes`.

**Comment by benesch** [comment]
For posterity, @umanwizard fixed this up in #16330.

**Comment by ggnall** [comment]
@aljoscha I've added a requirement to the description to match our approach for replicas: exposing both absolute metrics and size mappings in order to calculate % based metrics.
