### ISSUE TITLE
Catch panics in the optimizer

### ISSUE THREAD

**Issue by teskje** [MaterializeInc/materialize#16324]
With https://github.com/MaterializeInc/materialize/pull/16263 merged, we are now able to catch panics in Materialize code. Use that ability to wrap optimizer calls in `catch_unwind`s, to prevent panics in the optimizer from crashing the entire `environmentd` process. Instead, such panics should be converted to optimization/query planning errors and reported to the user.

**Comment by teskje** [comment]
I think it makes sense to go through previous optimizer crashes to ensure that we add `catch_unwind`s in the right places to prevent similar crashes from taking down `environmentd` in the future.

Some recent examples:
* https://github.com/MaterializeInc/materialize/issues/15570
* https://github.com/MaterializeInc/materialize/issues/16128
* https://github.com/MaterializeInc/materialize/issues/16195

**Comment by aalexandrov** [comment]
With #24049, #24068, #24072, and #24092 now merged we can try adding `catch_unwind` calls to the optimization stages for each of the new multi-stage `sequence_~`methods.
