### ISSUE TITLE
storage: correlate subsources to parent source

### ISSUE THREAD

**Issue by morsapaes** [MaterializeInc/materialize#16345]
### Feature request

As is, there is no way to correlate a subsource to its parent source. This makes it hard to understand the hierarchy of objects for Postgres (and Load Generator) sources, in particular since subsources are listed as `subsource` in `mz_sources`, but as `source` in `mz_objects` (see [this thread](https://materializeinc.slack.com/archives/C01CFKM1QRF/p1669660209489769)).

```sql
materialize=> SHOW SOURCES;

         name         |   type    |  size
----------------------+-----------+---------
 antennas             | subsource |
 antennas_performance | subsource |
 mz_source            | postgres  | 3xsmall

materialize=> SELECT * FROM mz_sources WHERE id LIKE 'u%';

  id   |  oid  | schema_id |         name         |   type    | connection_id |  size
-------+-------+-----------+----------------------+-----------+---------------+---------
 u1731 | 20803 | 3         | antennas             | subsource |               |
 u1732 | 20804 | 3         | antennas_performance | subsource |               |
 u1733 | 20805 | 3         | mz_source            | postgres  | u1730         | 3xsmall
 
 materialize=> SELECT * FROM mz_objects WHERE id LIKE 'u%';
 
   id   |  oid  | schema_id |         name         |  type
 -------+-------+-----------+----------------------+-------
 u1731  | 20803 | 3         | antennas             | source
 u1733  | 20805 | 3         | mz_source            | source
 u1732  | 20804 | 3         | antennas_performance | source
```

We should provide a `source`->`subsource` mapping, and expose it in the system catalog through _e.g._ a `parent_source_id` column that is `NULL` for sources that aren't multi-output, and contains the parent source identifier otherwise.

**Comment by hlburak** [comment]
This is relevant to the modeling work @dehume is doing on DDL data in Snowflake (drawn from mz_audit_events and routed through Segment). It sounds like execution of CREATE SOURCE resulting in multiple audit table entries (one for the source and one for each sub-source) is the intended behavior. We need a way (using only the audit log events) to distill these to source level in modeling. Maybe adding `parent_source_id` in the details of the audit log is the solution?

**Comment by hlburak** [comment]
Also noting that for creating billing events from the audit log, we use size = Null to filter out subsource events. Works for now, but might be good to filter on a field intended for the purpose in the future. cc @necaris

**Comment by benesch** [comment]
I tried to whip this up, and it's kind of hard as proposed. Oops! At the time we add a subsource to the catalog, its parent source has not yet been added to the catalog, and so we actually can't populate `parent_source_id`. It'd be much easier if we instead exposed the mapping in the opposite direction, and added a `subsources: text[]` field to the table. Or maybe we should just add a dedicated `mz_depends` relation that we could use for all objects. Not sure!

**Comment by morsapaes** [comment]
> Or maybe we should just add a dedicated mz_depends relation that we could use for all objects.

Ah! There is an open issue for that, @benesch: #12390. This would be helpful in more than the specific case of multi-output sources.

**Comment by benesch** [comment]
We went with https://github.com/MaterializeInc/materialize/issues/12390, and that solves this issue!
