### ISSUE TITLE
compute: Add protocol handshake

### ISSUE THREAD

**Issue by lluki** [MaterializeInc/materialize#16348]
### What version of Materialize are you using?

v0.33.0-dev (9dbee9aaf)

### How did you install Materialize?

Built from source

### What is the issue?

The compute protocol does not do any version handshake, hence environmentd does not necessarily notices that it speaks to an old version of computed. This can lead to some (rare?) races while doing upgrades and can hide other bugs. If the new version of computed writes different data than the old one, we would observe conflicting writes to persist.

### Scenario 1
environmentd@N calls the orchestrator to make sure computed@N is started. We do this by updating a kubernetes StatefulSet. environmentd immediately starts connecting to the computed. It is possible that kubernetes has not yet caught up to the StatefulSet update (we don't wait for the kubernetes rollout) thus environmentd@N might be talking to computed@N-1 until kubernetes performs the rollout. 

### Scenario 2
See this [thread](https://github.com/MaterializeInc/materialize/issues/13739#issuecomment-1326394194). Some quotes
> Hm, it seems like the problem might be even worse than what you've described so far. Let's say we're upgrading environmentd and we have coord v1 and coord v2 both running at the same time for a brief moment. Right before the upgrade, someone shows up and creates a cluster. coord v1 commits the cluster to the stash, then goes out to lunch before creating the service in Kubernetes. Then coord v2 boots up, sees the Kubernetes service is missing, and creates it with some special v2 additions to the config. coord v1 comes back from lunch and overwrites the Kubernetes service without the special v2 additions to the config. coord v2 doesn't notice that coord v1 has changed the cluster service out from beneath it. Oops!

There has been some changes to the startup protocol since this comment and environmentd will reset the stateful set *if* envd notices it is talking to an out of date computed. One way of noticing immediately is a protocol handshake that includes the version of materialize

## Implementation
Add the materialize semantic version to the CreateTimely command. computed checks if the semantic version matches and panics if the requested version does not match the currently running version. Using the semantic version is probably better than using a build hash, because it allows us to deploy environmentd hotfixes.

**Comment by benesch** [comment]
> The compute protocol does not do any version handshake, hence environmentd does not necessarily notices that it speaks to an old version of computed. This can lead to some (rare?) races while doing upgrades and can hide other bugs. If the new version of computed writes different data than the old one, we would observe conflicting writes to persist.

Yes it does!

https://github.com/MaterializeInc/materialize/blob/6177894453b9ea990ff8adbb8825ebdd522294c6/src/service/src/grpc.rs#L320-L351

**Comment by lluki** [comment]
Ah excellent! Somehow my thinking started with the actual `ComputeCommand` (like `CreateTimely`) that we transmit. 

I think we can close this then, unless we see some benefit in moving the protocol handshake into the ComputeCommands, but I don't think theres a real benefit.
