### ISSUE TITLE
Avro schema generation can create an invalid schema

### ISSUE THREAD

**Issue by guswynn** [MaterializeInc/materialize#16372]
### What version of Materialize are you using?

v0.32.3

### How did you install Materialize?

Materialize Cloud

### What is the issue?

In the log lines below, `<name>` starts with a number, which points to a `CREATE SINK` that spits out a warning, then crashes envd. Validation here should not crash, and we should not make it to avro parsing before spitting out an error to user about naming requirements.

### Relevant log output

```source
2022-11-29T15:30:59.756466Z  WARN mz_sql::plan::statement::ddl: Verification of upsert key disabled for sink '<sink_name>' via 'NOT ENFORCED'. This is potentially dangerous and can lead to crashing materialize when the specified key is not in fact a unique key of the sinked view.
thread 'coordinator' panicked at 'valid schema constructed: ParseSchema(ParseSchemaError("Invalid name. Must start with [A-Za-z_] and subsequently only contain [A-Za-z0-9_]. Found: <name>"))', src/interchange/src/avro/encode.rs:138:56
```

**Comment by benesch** [comment]
I don't think that the name started with a number? It had the structure `foo_bar-baz`, and it looks like that hyphen is the issue.

Here's the Slack conversation with the unredacted name: https://materializeinc.slack.com/archives/C015RHB3LDR/p1669752528909109

**Comment by mjibson** [comment]
This is caused by a `.except` at https://github.com/MaterializeInc/materialize/blob/5ba0c8bc1b5e82107ac7921fc5247d43838f0a72/src/interchange/src/avro/encode.rs#L138 which is an infallible function, I think because the invariant is that it's supposed to have already been fully verified during planning and before it gets here.

**Comment by benesch** [comment]
I think the invariant is actually that `build_row_schema_json` should never produce an invalid schema!

**Comment by benesch** [comment]
Found the bug. PR incoming.
