### ISSUE TITLE
log flooded with WARN mz_persist_client::internal::state_versions: logic error: fetch_current_state refetch expects earliest live diff to advance: 

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#16385]
### What version of Materialize are you using?

 v0.34.0-dev (608b03430)

### How did you install Materialize?

Built from source

### What is the issue?

After running bin/environmentd with and without `--reset` a couple of times, I ran into a situation where:

```
environmentd: 2022-11-30T13:11:07.379438Z  WARN mz_persist_client::internal::state_versions: logic error: fetch_current_state refetch expects earliest live diff to advance: v58 vs v58
```

was printed in the log every **millisecond**, potentially exhausing disk space. @pH14 reports that this could happen on the cloud as well.

**Comment by pH14** [comment]
Reverting https://github.com/MaterializeInc/materialize/pull/16386 for now which is the likely culprit

**Comment by danhhz** [comment]
@pH14 I have a theory! one way we'd expect this to happen is if a ctrl-c happened partway through the reset. I just checked and --reset clears the blobs before it clears consensus. it's pretty counterintuitive, but if we're missing a rollup blob, this is exactly how it manifests (for Reasons). I tested this by adding a sleep between them and indeed if i ctrl-c there, we see exactly this log! luckily, if we swap the order in --reset in misc/python/materialize/cli/run.py and clear consensus before blob, we should avoid the race. something like the following diff

```diff
diff --git a/misc/python/materialize/cli/run.py b/misc/python/materialize/cli/run.py
index ecb554bad..7c09779bc 100644
--- a/misc/python/materialize/cli/run.py
+++ b/misc/python/materialize/cli/run.py
@@ -121,13 +121,17 @@ def main() -> int:
         if args.program == "environmentd":
             _handle_lingering_services(kill=args.reset)
             mzdata = ROOT / "mzdata"
-            if args.reset:
-                print("Removing mzdata directory...")
-                shutil.rmtree(mzdata, ignore_errors=True)
             for schema in ["consensus", "adapter", "storage"]:
                 if args.reset:
                     _run_sql(args.postgres, f"DROP SCHEMA IF EXISTS {schema} CASCADE")
                 _run_sql(args.postgres, f"CREATE SCHEMA IF NOT EXISTS {schema}")
+            # Keep this after clearing out Postgres. Otherwise there is a race
+            # where a ctrl-c could leave persist with references in Postgres to
+            # files that have been deleted. There's no race if we reset in the
+            # opposite order.
+            if args.reset:
+                print("Removing mzdata directory...")
+                shutil.rmtree(mzdata, ignore_errors=True)
 
             mzdata.mkdir(exist_ok=True)
             environment_file = mzdata / "environment-id"

```

**Comment by benesch** [comment]
Ha! What a funny and not at all scary bug. Thanks for tracking this one down, Dan. Excited to have Paul’s fix in the next release.
