### ISSUE TITLE
environmentd required more than 4GB to boot

### ISSUE THREAD

**Issue by benesch** [MaterializeInc/materialize#16404]
We had an environment fail to come up during this week's release due to OOM while resetting builtin table updates. We restarted with 16GiB of memory and it was successful. I captured a memory heap dump during startup that implicates the `builtin_table_updates` function:

[trace-4.mzfg.zip](https://github.com/MaterializeInc/materialize/files/10128033/trace-4.mzfg.zip)

Env ID is ba2697c2-7c88-44e0-9d4f-85e7b88ff831-0, which is an internal Materialize account.

**Comment by jkosh44** [comment]
According to the stack trace, 2GB was allocated from this call to `extend` (which is eventually called by `send_builtin_table_updates`):
https://github.com/MaterializeInc/materialize/blob/5ba0c8bc1b5e82107ac7921fc5247d43838f0a72/src/adapter/src/coord/appends.rs#L387-L391

That is a`Vec` of `PendingWriteTxn`s, each of which has a size of 1,896 bytes.
https://github.com/MaterializeInc/materialize/blob/5ba0c8bc1b5e82107ac7921fc5247d43838f0a72/src/adapter/src/coord/appends.rs#L60-L76

Looking at the logs for that environment, the total number of rows for all system tables was 504,847 rows. Each row corresponds to roughly 2 pending writes, one retraction and one addition.

That means we should expect that `Vec` to be (504,847 * 2 * 1,896) = 1,914,379,824 bytes or ~1.9 GB.

So while this is unfortunate, it is not a surprise once we do the math.

**Comment by jkosh44** [comment]
It seems like `PendingWriteTxn` is a much bigger struct than `BuiltinTableUpdate`, so one thing we can do to cut this roughly in half is to consolidate the `BuiltinTableUpdate` before converting them to a `PendingWriteTxn`, instead of after which is what we currently do.
