### ISSUE TITLE
Don't parse keywords as identifiers

### ISSUE THREAD

**Issue by jamii** [MaterializeInc/materialize#1643]
We currently have some limited cases where we are careful with keywords, but postgres is much stricter:

```
jamie=# select * from from;
ERROR:  syntax error at or near "from"
LINE 1: select * from from;
                      ^
jamie=# create table from(a int);
ERROR:  syntax error at or near "from"
LINE 1: create table from(a int);
```

This is probably worth copying because it leads to much better parser errors.

**Comment by cuongdo** [comment]
Adding a milestone of 0.3 as a placeholder. We will want a resolution on this by 1.0.

**Comment by benesch** [comment]
I think we've shaken out most of the issues here now with some targeted restricted keywords. We can add more ad-hoc as necessary, since the backwards-compatibility issues haven't proven too problematic.
