### ISSUE TITLE
Long hydration times and large memory consumption with TPC-H load generator source and PK/FK indexes

### ISSUE THREAD

**Issue by vmarcos** [MaterializeInc/materialize#16473]
As part of [Evaluating Arrangement Columnation](https://www.notion.so/materialize/Evaluating-Arrangement-Columnation-with-TPC-H-2f9cfe45a4794da2abb01cb59ba93034), we ran scenarios with a TPC-H load generator source at scale factors 32 and 64 in an `r6id.32xlarge` scratch instance. As detailed in the experimental setup of the referred internal document, all PK and FK indexes were created. 

In these scenarios, we observed what appears to be long hydration times for the basic PK/FK indexes as well large memory usage during this process. The specific behaviors are as follows. When running `environmentd --release` with a SF 32 load-generated TPC-H source and PK/FK indexes, it takes a long time for Materialize to become responsive to commands, e.g., `SELECT count(*) FROM lineitem`. When monitoring with `htop`, we see the memory allocation shoot up, sometimes reaching 500G-700G. However, when the system finally stabilizes and becomes responsive, memory usage is on the range of 250G-350G. When performing the same steps at SF 64, swap is required: The entire TB of RAM of the scratch instance is basically taken up, and swap space used gets to 265G out of 512G.

This issue is a request to investigate these effects further. In particular, we would like to confirm or refute the hypothesis that we are taking a lot of time and memory to rehydrate the PK/FK indexes at large TPC-H scale factors.

**Comment by frankmcsherry** [comment]
Historically, query 20 has had a cross join in it because of limitations in our decorrelation (doubly nested subqueries get suboptimally decorrelated). I'm not sure what the world is like now, but two years ago it was the case that that query burned a lot of time and swap but eventually finished.

**Comment by vmarcos** [comment]
I tried to minimize the repro for this issue by eliminating the step where TPC-H queries are created as indexed views. However, then hydration succeeded in a short time frame. It seems to be the case that bringing the results to all TPC-H queries live is particularly demanding, but it is not yet clear to me why/how.

**Comment by vmarcos** [comment]
A few more debugging points:

- With a 50% of maximum RSS memory constraint at scale factor 32 (50% of ~310G = ~155G for `computed`), hydration consumed through 512G of swap and caused the replica to crash. Here is an `htop` snapshot during that run: 
![Screen Shot 2022-12-08 at 10 45 57](https://user-images.githubusercontent.com/1850983/206750513-26251c46-ecd7-4802-a1c7-d0dd2365285e.png)
- With a 90% of maximum RSS memory constraint at scale factor 32 (90% of ~310 = ~280G for `computed`) and swap increased to 850G, hydration ran for 15 hours without finishing. Here is an `htop` snapshot during that run: 
![Screen Shot 2022-12-09 at 16 42 01](https://user-images.githubusercontent.com/1850983/206751158-dd6c2bed-4fbc-4fa1-bcdb-2586c9d70178.png)
By contrast, a sequential run of all of the TPC-H queries at scale factor 32 and a 90% memory constraint took only 2 minutes of query processing time in total. Even at a 50% memory constraint, we can process all queries sequentially in 30 minutes. So we should carefully consider if the lack of admission control here is causing a thrashing effect during hydration.

**Comment by vmarcos** [comment]
As it turns out, your intuition was correct here, @frankmcsherry. My scripts had a bug where the version of Q20 employed in indexed views was different from the one for query processing. So we were not using the manually decorrelated version in the former. I had a chance to revisit this behavior when validating out-of-core for compute with swap in cloud (observations in an [internal doc](https://www.notion.so/materialize/Validating-Out-of-Core-for-Compute-with-Swap-in-Cloud-0f7ea02814db46449d22f9db55ce365c)).

Given the above, I am closing this issue.
