### ISSUE TITLE
Expose percent utilization for clusters and storage hosts

### ISSUE THREAD

**Issue by benesch** [MaterializeInc/materialize#16477]
### Feature request

*Part of epic #15808.*

The `mz_cluster_replica_metrics` table added in https://github.com/MaterializeInc/materialize/pull/16209 exposes CPU and memory in absolute terms. But most customers are asking for CPU/memory in relative terms, so that they can alert on out of memory/out of CPU conditions.

The easiest solution is to add a table that exposes the size limits:

```
CREATE TABLE mz_internal.mz_cluster_replica_sizes (
    size text,
    memory_limit_bytes int8,
    cpu_limit_nano_cores int8,
)
```

Then users would be able to see the absolute metrics and compute the percentages on demand. We could expose a view in `mz_catalog` that performs the division, to make it more ergonomic to retrieve the percent.

There are a few design questions to shake out here. If we expose `mz_cluster_replica_sizes`, we're effectively publicly committing to the size -> resource allocation mapping. @rjnn has historically been opposed to that.

If we instead replaced the measurements in `mz_cluster_replica_metrics` with percentages rather than absolute measurements, we'd sidestep the public commitment to the size -> resource allocation mapping. But we'd also make it more difficult to compare CPU/memory usage of replicas of different sizes. When comparing multiple replicas of the same cluster of different sizes on a graph, it's probably more sensible to be looking at absolute usage, rather than percent of limit usage.

**Comment by ggnall** [comment]
@umanwizard just discussed this with @rjnn and @sjwiesman:
We're comfortable exposing resource limits in a table (e.g. `mz_internal.mz_cluster_replica_sizes`), pointing users to these tables to create their own views for calculating %s, but not publishing the size/limit values directly in our docs. 

Assuming we would need the same solution on the storage host side cc: @aljoscha.

**Comment by umanwizard** [comment]
@ggnall We can even write the view ourselves and expose it in the catalog -- we don't need users to do it.

**Comment by umanwizard** [comment]
This is not quite done, as we are still only exposing the raw values, not percentages.
