### ISSUE TITLE
sql: nesting `SUBSCRIBE` in a `SELECT` statement

### ISSUE THREAD

**Issue by benesch** [MaterializeInc/materialize#16476]
### Feature request

From @frankmcsherry:

> This has come up in a few spots now, so raising a thought provoking discussion: imagine there was a function `CHANGES(collection, as_of)` whose columns were the same as those of `SUBSCRIBE` (the columns of `collection` plus a timestamp and diff), which is an append-only collection that shows you a snapshot of `collection` at `as_of` and then all of the diffs from that point forward, with each diff occurring at the timestamp it indicates. I'm trying to think through what that thing is (a source, a view, a mv, .. ) and what if any frustration it introduces.
>
> For example, if it were to be a view, we would need to hold back compaction of `collection` to `as_of`, because anyone using it would need to be able to see the same results, which require playing out `collection` from that historical time. If we made it a MV then perhaps we don't need to do that because things are written down, but we would get stressed out when we recover and try and reproduce the contents. Perhaps it is more like a source which just writes data down and says "that's what I wrote; too bad if future me doesn't like it".
>
> It's a bit scary because it is hard to revise the output, as it is append only and speaks about changes potentially in the distant past. That fights a fair bit with our approach to upgrades (we will reflow your dataflows and correct them, because maybe we had a bug and want to get you in the correct state), but the value also drops a bit if `CHANGES` doesn't produce a history from which you could return to the original collection. Maybe "reconciliation" is a large utterance we would write out at some change if we saw it, but we'd want a sidecar `collection` persisted so that we could read back what we had efficiently.

From @benesch:

> Having `CHANGES(src, as_of)` hold back compaction on `src` to `as_of` is the thing that makes sense to me. Stressful to do that in an index or materialized view, for sure. Maybe we hard disallow doing that. Usable in one-off `SELECT`s only, say.
>
> Or maybe we let you peg `as_of` to a sliding window. Would be cool to have a view that shows you the last 30m of changes, say.
>
> `CHANGES(src, mz_now() - ‘30m’)`
>
> On the subject of persisting `CHANGES`: sounds like maybe we want `as_of` to be advisory, where we have permission to occasionally advance it to the source’s since frontier? If we need to basically start over due to a behavior change in Materialize, for example. If we’ve written down the change stream, we can retract the old one that we wrote down, then start a new one at the source’s current as of.

**Comment by frankmcsherry** [comment]
Related: https://github.com/MaterializeInc/materialize/issues/15754

**Comment by benesch** [comment]
D'oh.
