### ISSUE TITLE
Investigate issues with (large) rds sources

### ISSUE THREAD

**Issue by guswynn** [MaterializeInc/materialize#16484]
Recently, incident 25 has revealed some issues with rds sources. There are two core issues:

## Snapshot ingestion is extremely slow
RDS instances, with or without ssh tunnels, seemed to present a maximum of MB/s of data when doing snapshotting. It is unclear if this is just for certain tiers of rds machine size, or if this is an inherent problem. We have little visibility into this when a customer hits it, and our use of `COPY OUT` is likely non-standard for read-replicas.

## Low traffic patterns can temporarily stall the replication stream

Its known than RDS produces un-readable wal lag that we periodically are unable to peek ahead of https://github.com/MaterializeInc/materialize/pull/14734. While is normally works, in incident 25 it seemed that we were unable to jump ahead, but it took us more than 5 minutes to catch up to the next value in the replication stream. Its unclear whether or not this is related to the slow speed of snapshotting, and during incident 25, we have little visibility.

Note that even if the common case, where we periodically get stuck and unstuck, the user may see a temporary `Stalled` status in `mz_source_status`, which looks bad when things are operating as expecting. It may be that we just need to 

### Solutions

- To investigate snapshotting speeds, we probably want: https://github.com/MaterializeInc/materialize/issues/16596.
- If we see this again in production, https://github.com/MaterializeInc/materialize/pull/16393 will give us some extra info when a customer hits this issue in production
- We should consider only marking the source as `Stalled` if this error happens twice in a row (cc @petrosagg and @bkirwi), as we expect to periodically peek ahead in at least some cases
- Additionally, once LaunchDarkly support is added, the 5min and 10MB limits customers hit in production should be made into configs that can be changed at runtime, to investigate if any should be lifted to `CREATE SOURCE` level

**Comment by benesch** [comment]
We haven't had issues with RDS sources in a while! Going to assume the underlying issues here have been fixed.
