### ISSUE TITLE
Control the spine of arrangements in Materialize

### ISSUE THREAD

**Issue by antiguru** [MaterializeInc/materialize#16549]
Rendering often introduces intermediate arrangements to compute results. We only define the spine type for such arrangements only partially, leaving several arrangements using the default spine type.

This issue serves to list the call sites we need to change in order to never use the default spine.

**Comment by aalexandrov** [comment]
> leaving several arrangements using the default spine type.

I'm curious to learn more. Can we also expand the issue description with a list of the available spine types. Are we choosing only from [the ones available here](https://docs.rs/differential-dataflow/0.12.0/differential_dataflow/trace/implementations/index.html)?

**Comment by antiguru** [comment]
We should only be using the arrangement types managed by Materialize instead of relying on the default. Look at the definitions in `typedefs.rs`:
https://github.com/MaterializeInc/materialize/blob/08737713b1277778c6f6d29e17fb01c6373c1818/src/compute/src/typedefs.rs#L20-L26
