### ISSUE TITLE
Inconsistent naming on status tables

### ISSUE THREAD

**Issue by ggnall** [MaterializeInc/materialize#16550]
We have inconsistent naming for resourse status tables that we should unify:
`mz_cluster_replica_statuses` and `mz_[sink/source]_status`

- Update sources/sinks to use `statuses`. 
- Update tests for mentions of the old names

These tables are in `mz_internal`, but some coordination is needed with @RobinClowers since these tables are used by the UI.

**Comment by bkirwi** [comment]
Possibly we should duplicate the views and later drop the old ones, to avoid breaking the UI. @RobinClowers - let me know!

**Comment by RobinClowers** [comment]
@bkirwi that would be easiest for me if it's not too much trouble? Otherwise I could check for the existence of the new views on my end.

**Comment by bkirwi** [comment]
Not too much trouble... good to get in the habit in any case.
