### ISSUE TITLE
storage: support CSR connections over SSH tunnels

### ISSUE THREAD

**Issue by benesch** [MaterializeInc/materialize#16577]
### Feature request

In #16158, we added support for connecting to Kafka brokers over SSH tunnels, but not Confluent Schema Registry servers over SSH tunnels.

Most practical uses of Kafka involve the CSR, so our Kafka-over-SSH implementation likely isn't too useful until we add CSR-over-SSH.

cc @guswynn 

@uce or @aljoscha—could you triage? Likely not much work, and might be worth knocking out sooner rather than later as I imagine the first user to try Kafka-over-SSH will run right into this.

**Comment by guswynn** [comment]
@benesch this is on my list, probably for skunkworks this week!
