### ISSUE TITLE
DROP SINK|SOURCE not reflected in the mz_source|sink_status views

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#16579]
### What version of Materialize are you using?

v0.34.0

### How did you install Materialize?

Docker image

### What is the issue?

`DROP SOURCE|SINK` is not reflected in the source|sink status tables. The records for the source/sink are neither deleted, nor is a tombstone record of any kind emitted.

@bkirwi requested that a ticket is opened for this known limitation.

**Comment by bkirwi** [comment]
This should be resolved by the recently-unstuck https://github.com/MaterializeInc/materialize/pull/16206.
