### ISSUE TITLE
Passing wrong `MZ_LAUNCHDARKLY_SDK_KEY` blocks unsynchronized `environmentd` instances

### ISSUE THREAD

**Issue by aalexandrov** [MaterializeInc/materialize#16586]
### What version of Materialize are you using?

v0.35.0-dev (f195c1a94) 

### How did you install Materialize?

Built from source

### What is the issue?

The `ensure_initialized` implementation which is called in `Catalog::open` for `environmentd` instances that have not been synchronized at least once will block `environmentd` startup if the passed `MZ_LAUNCHDARKLY_SDK_KEY` credential is bad.

There is a high chance that the recently released 1.0.0 version of the SDK solves the issue ([see code for handling non-recoverable HTTP errors](https://docs.rs/launchdarkly-server-sdk/1.0.0/src/launchdarkly_server_sdk/data_source.rs.html#156)).

To reproduce, run

```bash
export MZ_LOG_FILTER='trace' 
export MZ_LAUNCHDARKLY_SDK_KEY='bad-key'
bin/environmentd --reset -- --config-sync-loop-interval 5s
```

The relevant log output is in the next section.

### Relevant log output

```source
environmentd: 2022-12-12T11:22:23.107589Z TRACE eventsource_client::client: ReconnectingRequest::poll loop(connecting(retry))    
environmentd: 2022-12-12T11:22:23.107741Z TRACE hyper::client::pool: put; add idle connection for ("https", stream.launchdarkly.com)
environmentd: 2022-12-12T11:22:23.107842Z DEBUG hyper::client::pool: pooling idle connection for ("https", stream.launchdarkly.com)
environmentd: 2022-12-12T11:22:23.107997Z DEBUG eventsource_client::client: HTTP response: Response {
    status: 401,
    version: HTTP/1.1,
    headers: {
        "date": "Mon, 12 Dec 2022 11:22:23 GMT",
        "content-length": "0",
        "connection": "keep-alive",
        "ld-region": "us-east-1",
        "strict-transport-security": "max-age=31536000",
    },
    body: Body(
        Empty,
    ),
}    
environmentd: 2022-12-12T11:22:23.108179Z ERROR launchdarkly_server_sdk::data_source: error on event stream: UnexpectedResponse(401)    
environmentd: 2022-12-12T11:22:23.108470Z DEBUG launchdarkly_server_sdk::data_source: unhandled error; break    
environmentd: 2022-12-12T11:22:23.109922Z TRACE hyper::client::pool: idle interval checking for expired
environmentd: 2022-12-12T11:22:26.265235Z DEBUG launchdarkly_server_sdk::events::dispatcher: waiting for a batch to send    
environmentd: 2022-12-12T11:22:31.265312Z DEBUG launchdarkly_server_sdk::events::dispatcher: waiting for a batch to send    
environmentd: 2022-12-12T11:22:36.265502Z DEBUG launchdarkly_server_sdk::events::dispatcher: waiting for a batch to send    
environmentd: 2022-12-12T11:22:41.265539Z DEBUG launchdarkly_server_sdk::events::dispatcher: waiting for a batch to send    
environmentd: 2022-12-12T11:22:46.265758Z DEBUG launchdarkly_server_sdk::events::dispatcher: waiting for a batch to send
```

**Comment by aalexandrov** [comment]
I can confirm that the issue is not present after upgrading to `1.0.0`. However, the 401 is not surfaced and the `while` loop in `ensure_initialized` is backing off to the max value.

**Comment by benesch** [comment]
Sorry, what is the question? The code you posted there looks good. Presumably there is some tracing log filter we could activate in order to get the LD SDK to be noisier about what's going wrong internally, but we'd only need to do that if LD gets stuck, and that seems fine!

**Comment by aalexandrov** [comment]
> Sorry, what is the question?

When LaunchDarkly is unavailable or misconfigured the `environmentd` boot (for unsynchronized `environmentd` instances) will block until we explicitly disable LaunchDarkly (by unsetting `MZ_LAUNCHDARKLY_SDK_KEY` for example). This means that LaunchDarkly becomes a hard dependency for Materialize availability (only for new instances, but still).

I just want to confirm that we are OK with that for the moment (@antifuchs has some concerns).

**Comment by antifuchs** [comment]
Eep, (I forgot that concern, but yep - valid!)

Ideally we'd have a way to continue without LD, but registering the error in a way that gets noticed quickly (metric & alert?). Being hard-down if the LD api isn't responsive would be pretty bad, even if it's only for envd startup.

**Comment by aalexandrov** [comment]
@antifuchs: sorry, the auto-complete pulled a trick on me, I meant @antiguru.

**Comment by aalexandrov** [comment]
> Presumably there is some tracing log filter we could activate in order to get the LD SDK to be noisier about what's going wrong internally, but we'd only need to do that if LD gets stuck, [...]

Yes, with `debug` turned on there are some events reported from the SDK that give some insight when a connection drops or the API returns 401.

**Comment by aalexandrov** [comment]
See the comment added in #16694 for a justification of closing this without further action.
