### ISSUE TITLE
Postgres snapshot errors are not reported in the source status tables

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#16581]
### What version of Materialize are you using?

 v0.35.0-dev (2f56c8b2f)

### How did you install Materialize?

Docker image

### What is the issue?

As reported by @bkirwi, if an error happens during the postgres snapshot, it is not reported in the source tables.

**Comment by bkirwi** [comment]
Fix is merged, and folks report getting the snapshot-time errors correctly.
