### ISSUE TITLE
storage: setup large rds postgres source canary environment

### ISSUE THREAD

**Issue by guswynn** [MaterializeInc/materialize#16596]
*Follow up from incident 25 (https://github.com/MaterializeInc/cloud/issues/4813).*

During incident 25 we did some initial testing with our own large rds instance. Ideally, we would continually exercise a large rds source, and ensure that we always can 1. snapshot in a reasonable amount of time, and 2. make progress during replication, even for weird (i.e. low) traffic patterns.

I imagine this would start off as a one-off test to figure out why rds instance snapshot so slowly, and eventually become a release-validation test.

**Comment by benesch** [comment]
The QA team has set this up! Calling this closed.
