### ISSUE TITLE
Known limitations for first release

### ISSUE THREAD

**Issue by sploiselle** [MaterializeInc/materialize#1660]
Along with the release, we should have a list of known limitations. Some random thoughts:

- An issue for each known limitation
  - Benefit here is atomicity: known issues can start off as some arbitrarily large work unit and can decompose in whatever way is necessary
  - Distributes work to each person/team to produce the things they know of that don't work
- A tag for known issues; would be nice to have a tag for the version to which it applies, as well, just to make them searchable
- Add a docs page, e.g. `/docs/known-limitations`; versioning here will be the same as everywhere else

**Comment by rjnn** [comment]
We should ship a first cut of the known limitations page soon.
