### ISSUE TITLE
panicked at 'failed to reclock time Partitioned((Point(None), MzOffset { offset: 0 }))

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#16616]
### What version of Materialize are you using?

8ea5387f07

### How did you install Materialize?

Docker image

### What is the issue?

@petrosagg that reclock panic showed up again after all the latest changes in the SLT test and is now seen in CI:

```
thread 'timely:work-0' panicked at 'failed to reclock time Partitioned((Point(None), MzOffset { offset: 0 }))
```

https://buildkite.com/materialize/tests/builds/46658#01850a59-e82e-435c-8631-d045f168c8c5

It does not seem to cause any queries to fail though, so the test ultimately passes.

**Comment by aljoscha** [comment]
@petrosagg mentioned to me that this cannot happen anymore with the current code
