### ISSUE TITLE
Generating release notes?

### ISSUE THREAD

**Issue by sploiselle** [MaterializeInc/materialize#1661]
To generate release notes after initial release, we need some kind of scalable process that lets individual contributors dictate whether or not a given change is worth a release note or not.

We could simply parse a string in commits and look for a release note comment, e.g.

```
rn(product area): comment
```

`product area` could be an ad hoc field that's made consistent by hand at the time we publish the docs.

@benesch @cuongdo Do either of you have opinions or expertise in a way that we can structure this to be both useful for the tech writing team and less-painful for engineering?

<hr/>

w/r/t Hugo, we could have `docs/release-notes` which is a `list` page that links to all of the release notes for the time being.

In the future, as we end up having different types of releases, Hugo can create arbitrarily nested directories here, so we'd be able to start off with everything in that directory, and layer in directories in the future as we saw fit.

**Comment by rjnn** [comment]
Let's get a v1 of the process in the next few weeks, so I've tentatively assigned a milestone of 0.2.
