### ISSUE TITLE
Add a reverse LaunchDarkly synchronization script

### ISSUE THREAD

**Issue by aalexandrov** [MaterializeInc/materialize#16620]
### Feature request

In order to safely roll this to production, we need a script that:

1. Ensures that the LaunchDarkly default variants (with targeting `off` and `on`) for all configuration parameters that do not represent an actual feature flag are consistent with the hard-coded system defaults.
1. Connects to all environments in a region, and for each `environmentd`:
	1. Polls the current `SystemVars` state with `SHOW ALL` using the `mz_system` port.
	2. Compares this against the variable that will be served for this `environmentd` instance by LaunchDarkly.
	3. If the two diverge, ensures that (a) a variant for the value in (2) and (b) a rule that targets the current `environmentd` are created in LaunchDarkly.

**Comment by benesch** [comment]
We just need to run this script once, right? To find any existing overrides, and make sure we have those represented in LD?

**Comment by aalexandrov** [comment]
Yes, but I can imagine that this might also come in handy if for some reason we have a somewhat longer LaunchDarkly outage.

**Comment by aalexandrov** [comment]
My plan is to add it to the `cloud` repo under a new `util/launchdarkly.py` folder. I will open a draft PR for that tomorrow so we can discuss whether this is the right place / framework to do it.

**Comment by benesch** [comment]
Is it just a command-line script? If so, `mzadmin` is the right tool! https://github.com/MaterializeInc/cloud/tree/main/infra/cli/mzadmin
