### ISSUE TITLE
adapter: Pull real time recency off of the main coord thread

### ISSUE THREAD

**Issue by jkosh44** [MaterializeInc/materialize#16651]
### Feature request

Currently the Coordinator waits for a real time recency timestamp on the main Coordinator thread which blocks the Coord from doing anything. The feature is gated behind unsafe mode so we won't experience any performance issues in production. Before removing unsafe mode we'll have to pull this logic off of the main Coord thread.

The main challenge will be after resuming the query to identify if the state of the catalog has changed and if so, is the query still valid. @mjibson points out that we can use the Catalog's `transient_revision` number to determine if something has changed. If so, then we'll probably need to verify that all the GlobalId's in the query still exist in the catalog.

Part of #11531

**Comment by mjibson** [comment]
I *think* it might be safe in this case (revision has changed) to call the original function again? It'll fail if something got deleted, and maybe isn't a correctness problem? Unclear.

**Comment by jkosh44** [comment]
What do you mean by the original function?

I think it's considered correct to fail in the case that something changed and the query is no longer valid.

**Comment by mjibson** [comment]
In this case the original function would be `sequence_plan_peek`. I agree that it's ok if something changed and the query is no longer valid. But in a lot of cases something will change and the query is still valid. It'll be annoying to users if a bunch of their SELECTs start failing anytime they run a CREATE just because the revision bumped. My argument is that if the catalog changed, we should just start over, and let the regular validity checking re-run.

**Comment by mjibson** [comment]
And with serializability (strict or not), we have the freedom to choose any timestamp during which the query is executing, so I think it's also safe from a txn correctness standpoint to do this.

**Comment by jkosh44** [comment]
Oh I see what you're saying. I think that's a good approach and I agree with you that's it's OK from a correctness standpoint.

**Comment by jkosh44** [comment]
Actually I'm not sure that it's ok to just call `sequence_plan_peek` again. The `sequence` method doesn't re-validate that all the GlobalIds still exist. To do that we'd need to either re-plan or re-execute name resolution. However at that point of sequencing we no longer have the statement necessary to do that.


On a separate note, this is slightly further complicated by the fact that both reads and read-then-writes will need to wait off of the main coord thread and be restarted where ever they left off. So we'll need a way to remember the context of the read we were doing potentially.
