### ISSUE TITLE
Create a histogram SQL pattern

### ISSUE THREAD

**Issue by sjwiesman** [MaterializeInc/materialize#16674]
### Documentation request

Some types of aggregates, such as medians are difficult to implement in streaming. We could document SQL patterns for workarounds such as hdrhistorgrams 

https://materializeinc.slack.com/archives/C015RHB3LDR/p1671129668486199

**Comment by morsapaes** [comment]
@sthm put together a thorough [document](https://materializeinc.slack.com/archives/C015RHB3LDR/p1673368301607039) that can be repurposed here.
