### ISSUE TITLE
Make pgwire connection setup as lightweight as possible

### ISSUE THREAD

**Issue by benesch** [MaterializeInc/materialize#16680]
If possible, we should adjust the `pgwire` connection setup logic to avoid a roundtrip through the coordinator main loop. The idea is to ensure that you can successfully connect to Materialize _even if_ the coordinator main loop is wedged. This makes for a better user experience, as Materialize is still baseline responsive even if the coordinator is stuck.

I _believe_ that right now the roundtrip through the main loop is required in order to verify that the user exists, and create it if it does not. When operating in `create_if_not_exists: true` mode, the pgwire protocol module could potentially defer that communication until the first query is executed on the connection; in other words, there is no need to chat with the coordinator to see if the user exists, because we know that the user will be created if it does not already exist.

**Comment by jkosh44** [comment]
Here's everything that happens in the Coordinator when a user creates a new connection: 
https://github.com/MaterializeInc/materialize/blob/50c0cb76e48803bcdfa7ad2f308d602d786be4fd/src/adapter/src/coord/command_handler.rs#L160-L232

Summarized in English this is:
1. Create a temporary schema for the user's session. An error is returned to the user if we've exhausted all OIDs (very unlikely).
2. Check if the user exists. If not either send an error to the user or create the user depending on `create_if_not_exists`
3. Generate a secret key.
4. Save session metadata in the Coord (connectin id, query cancel channel, connection notice channel, secret key, active subscribes).

**Comment by mjibson** [comment]
The startup fn does other things too:

- check the database exists and emit a notice
- generate a secret key that is returned to the client

The database check can be delayed. The secret key check cannot, so it'd have to be generated in pgwire and sent to the coordinator in order to early return.

**Comment by benesch** [comment]
> so it'd have to be generated in pgwire and sent to the coordinator in order to early return.

Or generated in the coord client! That'll keep the same logical boundary while still avoiding the communication with the coordinator.

**Comment by chaas** [comment]
Done via https://github.com/MaterializeInc/materialize/pull/16949
