### ISSUE TITLE
[Epic] Generalize Top1 to a TopQ operator

### ISSUE THREAD

**Issue by antiguru** [MaterializeInc/materialize#16698]
### Product Outcome

Currently, a top-1 query in a monotonic context has a special implementation that benefits from limited memory utilization since it's guaranteed to never see retractions. Many use-cases require a different limit, for example a `LIMIT k` with k > 1. This work aims at providing an efficient TopQ operator that provides an efficient implementation for constant and small k.

### Specification

**Problem description:** As outlined in an [internal doc](https://www.notion.so/materialize/TopK-Rendering-Current-State-and-Potential-Improvements-4b056abb89ce4cebb0283eab6d8a3aae), our current top-k rendering for both monotonic and non-monotonic sources is built such that we can gracefully handle large k and worst-case skew in the formation of top-k groups. However, it leaves opportunities for more efficient processing on the table for small k. Additionally, the current monotonic top-k reuses the non-monotonic top-k rendering with an additional dataflow subgraph that drops input rows that are no longer needed when the top-k are determined. This implementation strategy makes it differ substantially from the specialized monotonic top-1 implementation, which is based on moving rows to the difference field and performing a reduction.

**Queries for evaluation:** We would like to observe whether an implementation can provide improvements to rendering of top-k plans with small k, but at the same time not hurt performance of top-k plans with large k. Also, any changes made to improve monotonic top-k plan evaluation should not hurt performance of non-monotonic top-k plans. So at least the following queries extending the TPC-H benchmark should be used for performance evaluation:

_Non-Monotonic Top-K Queries_

_QTKL_: Performs a top-k computation with large k. Aggregates the total revenue of the upper 10% of orders by revenue. Below, the variable ${SF} refers to the scale factor. Since `LIMIT` syntax only accepts integer constants, the multiplication must instantiated as an integer constant before the query is issued.
```sql
SELECT
    sum(revenue) AS revenue
FROM (
    SELECT l_orderkey,
           sum(l_extendedprice * (1 - l_discount)) AS revenue
    FROM lineitem
    GROUP BY l_orderkey
    ORDER BY revenue DESC 
    LIMIT 150000 * ${SF}
);
```
_QTKS_: Performs a top-k computation with small k larger than 1. Aggregates the total revenue of the largest 10 orders by revenue.
```sql
SELECT
    sum(revenue) AS revenue
FROM (
    SELECT l_orderkey,
           sum(l_extendedprice * (1 - l_discount)) AS revenue
    FROM lineitem
    GROUP BY l_orderkey
    ORDER BY revenue DESC 
    LIMIT 10
);
```
_QTK1_: Performs a top-k computation with small k equal to 1. Obtains the revenue of the largest order.
```sql
SELECT
    revenue
FROM (
    SELECT l_orderkey,
           sum(l_extendedprice * (1 - l_discount)) AS revenue
    FROM lineitem
    GROUP BY l_orderkey
    ORDER BY revenue DESC 
    LIMIT 1
);
```

_Monotonic Top-K Queries_

The queries above perform a group-by aggregation, which breaks monotonicity prior to application of a top-k computation. We propose below the following alternate queries that do not break monotonicity for evaluation. In addition, the queries use group-by aggregation stacking sums to (currently) force top-k computation over large enough inputs while producing only one row as a result.

_QMKL_: Performs a monotonic top-k computation with large k. Aggregates the total discount given in the roughly upper 10% of line items with the largest discounts. Below, the variable ${SF} refers to the scale factor. Since `LIMIT` syntax only accepts integer constants, the multiplication must instantiated as an integer constant before the query is issued. Note that the computation assumes roughly 6 million line items per scale factor, but the true number may differ slightly depending on random number generation.

```sql
SELECT sum(total_discount) total_discount
FROM (
    SELECT l_orderkey, sum(l_discount) total_discount
    FROM (
        SELECT l_orderkey, l_linenumber, l_discount
        FROM lineitem
        ORDER BY l_discount DESC
        LIMIT 6000000 * ${SF}
    )
    GROUP BY l_orderkey
);

```
_QMKS_: Performs a monotonic top-k computation with small k larger than 1. Aggregates the total discount given in the top-10 line items with largest discounts.
```sql
SELECT sum(total_discount) total_discount
FROM (
    SELECT l_orderkey, sum(l_discount) total_discount
    FROM (
        SELECT l_orderkey, l_linenumber, l_discount
        FROM lineitem
        ORDER BY l_discount DESC
        LIMIT 10
    )
    GROUP BY l_orderkey
);
```
_QMK1_: Performs a monotonic top-k computation with small k equal to 1. Obtains the discount given in the line item with the largest discount.
```sql
SELECT sum(total_discount) total_discount
FROM (
    SELECT l_orderkey, sum(l_discount) total_discount
    FROM (
        SELECT l_orderkey, l_linenumber, l_discount
        FROM lineitem
        ORDER BY l_discount DESC
        LIMIT 1
    )
    GROUP BY l_orderkey
);
```
### Design and Documentation

A detailed design document that includes and refines our [internal analysis](https://www.notion.so/materialize/TopK-Rendering-Current-State-and-Potential-Improvements-4b056abb89ce4cebb0283eab6d8a3aae) is made available by PR #17039.

### Implementation and Measurements

* #16813
* Measurements collected in an [internal spreadsheet](https://docs.google.com/spreadsheets/d/1e19apd0_JPuDhgbQEqdxU3d56dmQ1S79Nq_60epVljE/edit#gid=0) indicate that for small k (here, k=10 as above) with the monotonic top-k queries in this epic, we get with 8 workers a factor of 14.6x better than main in time and a factor of 5.4x better than main in dataflow records (after stabilization) in a local development environment. The previously existing memory spike caused by excessive dataflow records is also largely gone, which turns out to be an orders-of-magnitude improvement.
* #17056, in lieu of #17058.
* https://github.com/MaterializeInc/materialize/pull/17379: This PR brought about streaming early aggregation improvements to `explode_one` that were observed as opportunities for further improvements to monotonic top-1. Integration of these improvements is left to the follow-up issue #17606, since they would not affect the monotonic top-k implementation.

**Comment by vmarcos** [comment]
Given the benefits obtained for the monotonic top-k implementation, we believe the objectives of this epic have been fulfilled. Work carried out here in PR #17379 can be integrated into monotonic top-1 rendering for further potential improvements. This work is now tracked by the follow-up issue #17606.
