### ISSUE TITLE
storage: investigate ```Failed to commit offsets``` warnings

### ISSUE THREAD

**Issue by materializekatrina** [MaterializeInc/materialize#16692]
### What version of Materialize are you using?

v0.36.2

### How did you install Materialize?

Materialize Cloud

### What is the issue?

Logs are getting flooded with warnings as seen below:

```
2022-12-16T16:05:44.820120Z  WARN mz_storage::source::commit: Failed to commit offsets for u5450 (1/31 e=Consumer commit error: WaitingForCoordinator (Local: Waiting for coordinator)
--
2022-12-16T16:05:40.854455Z  WARN mz_storage::source::commit: Failed to commit offsets for u5450 (27/31 e=Consumer commit error: WaitingForCoordinator (Local: Waiting for coordinator)
```

Honeycomb logs:
[https://ui.honeycomb.io/materialize/datasets/production.console-logs/result/z5xTkA4EaZj?tab=raw](url)

Related Slack threads: 
[https://materializeinc.slack.com/archives/C01CFKM1QRF/p1671206582192259](url)
[https://materializeinc.slack.com/archives/C01CFKM1QRF/p1670266735619309](url)

**Comment by philip-stoev** [comment]
those are `ERROR`s now

**Comment by guswynn** [comment]
These were erroneously made errors, we can downgrade them!

**Comment by aljoscha** [comment]
Is this now resolved? I seem to remember that Petros had a PR that downgrades these again?

**Comment by dseisun-materialize** [comment]
@guswynn you know if this ticket is still relevant?

**Comment by guswynn** [comment]
This should be closed
