### ISSUE TITLE
CRDB panics across the board in Nightly tests

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#16726]
### What version of Materialize are you using?

5448be7

### How did you install Materialize?

Docker image

### What is the issue?

The Nightlies have started failing across the board due to a repeated CRDB crash :

```
ERROR: internal error: the first bucket should have NumRange=0
testdrive-materialized-1  | DETAIL: stack trace:
testdrive-materialized-1  | github.com/cockroachdb/cockroach/pkg/sql/opt/props/histogram.go:211: filter()
testdrive-materialized-1  | github.com/cockroachdb/cockroach/pkg/sql/opt/props/histogram.go:354: Filter()
testdrive-materialized-1  | github.com/cockroachdb/cockroach/pkg/sql/opt/memo/statistics_builder.go:3583: updateHistogram()
testdrive-materialized-1  | github.com/cockroachdb/cockroach/pkg/sql/opt/memo/statistics_builder.go:3400: applyConstraintSet()
testdrive-materialized-1  | github.com/cockroachdb/cockroach/pkg/sql/opt/memo/statistics_builder.go:3163: applyFiltersItem()
testdrive-materialized-1  | github.com/cockroachdb/cockroach/pkg/sql/opt/memo/statistics_builder.go:3079: applyFilters()
testdrive-materialized-1  | github.com/cockroachdb/cockroach/pkg/sql/opt/memo/statistics_builder.go:3031: filterRelExpr()
testdrive-materialized-1  | github.com/cockroachdb/cockroach/pkg/sql/opt/memo/statistics_builder.go:1013: buildSelect()
testdrive-materialized-1  | github.com/cockroachdb/cockroach/pkg/sql/opt/memo/logical_props_builder.go:288: buildSelectProps()
testdrive-materialized-1  | github.com/cockroachdb/cockroach/bazel-out/k8-opt/bin/pkg/sql/opt/memo/expr.og.go:19827: MemoizeSelect()
testdrive-materialized-1  | github.com/cockroachdb/cockroach/bazel-out/k8-opt/bin/pkg/sql/opt/norm/factory.og.go:1451: ConstructSelect()
testdrive-materialized-1  | github.com/cockroachdb/cockroach/bazel-out/k8-opt/bin/pkg/sql/opt/norm/factory.og.go:23720: CopyAndReplaceDefault()
testdrive-materialized-1  | github.com/cockroachdb/cockroach/pkg/sql/opt/norm/factory.go:326: func2()
testdrive-materialized-1  | github.com/cockroachdb/cockroach/bazel-out/k8-opt/bin/pkg/sql/opt/norm/factory.og.go:25035: invokeReplace()
testdrive-materialized-1  | github.com/cockroachdb/cockroach/bazel-out/k8-opt/bin/pkg/sql/opt/norm/factory.og.go:23772: CopyAndReplaceDefault()
testdrive-materialized-1  | github.com/cockroachdb/cockroach/pkg/sql/opt/norm/factory.go:326: func2()
testdrive-materialized-1  | github.com/cockroachdb/cockroach/bazel-out/k8-opt/bin/pkg/sql/opt/norm/factory.og.go:25035: invokeReplace()
testdrive-materialized-1  | github.com/cockroachdb/cockroach/bazel-out/k8-opt/bin/pkg/sql/opt/norm/factory.og.go:23684: CopyAndReplaceDefault()
testdrive-materialized-1  | github.com/cockroachdb/cockroach/pkg/sql/opt/norm/factory.go:326: func2()
testdrive-materialized-1  | github.com/cockroachdb/cockroach/bazel-out/k8-opt/bin/pkg/sql/opt/norm/factory.og.go:25035: invokeReplace()
testdrive-materialized-1  | github.com/cockroachdb/cockroach/bazel-out/k8-opt/bin/pkg/sql/opt/norm/factory.og.go:23727: CopyAndReplaceDefault()
testdrive-materialized-1  | github.com/cockroachdb/cockroach/pkg/sql/opt/norm/factory.go:326: func2()
testdrive-materialized-1  | github.com/cockroachdb/cockroach/bazel-out/k8-opt/bin/pkg/sql/opt/norm/factory.og.go:25035: invokeReplace()
testdrive-materialized-1  | github.com/cockroachdb/cockroach/pkg/sql/opt/norm/factory.go:285: CopyAndReplace()
testdrive-materialized-1  | github.com/cockroachdb/cockroach/pkg/sql/opt/norm/factory.go:328: AssignPlaceholders()
testdrive-materialized-1  | github.com/cockroachdb/cockroach/pkg/sql/plan_opt.go:488: reuseMemo()
testdrive-materialized-1  | github.com/cockroachdb/cockroach/pkg/sql/plan_opt.go:521: buildExecMemo()
testdrive-materialized-1  | github.com/cockroachdb/cockroach/pkg/sql/plan_opt.go:231: makeOptimizerPlan()
testdrive-materialized-1  | github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:1432: makeExecPlan()
testdrive-materialized-1  | github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:1058: dispatchToExecutionEngine()
testdrive-materialized-1  | github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:687: execStmtInOpenState()
testdrive-materialized-1  | github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:129: func1()
testdrive-materialized-1  | 
testdrive-materialized-1  | HINT: You have encountered an unexpected error.
testdrive-materialized-1  | 
testdrive-materialized-1  | Please check the public issue tracker to check whether this problem is
testdrive-materialized-1  | already tracked. If you cannot find it there, please report the error
testdrive-materialized-1  | with details by creating a new issue.
testdrive-materialized-1  | 
testdrive-materialized-1  | If you would rather not post publicly, please contact us directly
testdrive-materialized-1  | using the support form.
testdrive-materialized-1  | 
testdrive-materialized-1  | We appreciate your feedback.
testdrive-materialized-1  | 
```

The crash occurs repeatedly and Materialize is unable to recover from it by retrying, so panics itself.

We recently bumped the version of CRDB that we use in the CI, but that was on Mon Dec 12  whereas the crash started happening on Friday Dec 16th. There were many clean runs before that.

I am opening this ticket and setting it to a release blocker until it is determined if it is going to impact cloud with CRDB SaaS or not.

**Comment by philip-stoev** [comment]
I opened a ticket against the CRDB tracker: https://github.com/cockroachdb/cockroach/issues/93892

**Comment by arusahni** [comment]
We are downgrading our CrDB version until this is fixed upstream: #16730

**Comment by philip-stoev** [comment]
cockroach is back to version 22.2 and now the issue has migrated to the Release Qualification Test:

```
zippy-materialized-1     | environmentd: 2022-12-28T00:56:25.430549Z ERROR mz_stash::postgres: tokio-postgres stash consolidation error, retry attempt 24685: stash error: postgres: db error: ERROR: internal error: the first bucket should have NumRange=0
```

environmentd is blocked and is unable to service queries.

@benesch

**Comment by benesch** [comment]
Ah, ok, then we should try the workaround they suggest:

```
SET CLUSTER SETTING sql.stats.forecasts.enabled = false;
```

I went to go work on this, but #16864 just went in, and I think that probably does not work as you intend! At least, I don't see where CockroachDB is actually getting started. 

I think we should take a step back and make some improvements to our infrastructure here:

  * Add a `cockroachdb-setup.sql` script somewhere in the repo that contains the essential startup commands:

    ```
    CREATE SCHEMA IF NOT EXISTS adapter;
    CREATE SCHEMA IF NOT EXISTS storage;
    CREATE SCHEMA IF NOT EXISTS consensus;
    -- And temporarily:
    SET CLUSTER SETTING sql.stats.forecasts.enabled = false;
    ```

  * Teach run.py to execute that script.
  * Have cloudtest mount that script into the initdb directory in the `cockroach` container it creates.
  * Add a `external_services: bool` parameter to the `Materialized` service in mzcompose. When set to true, the service gets a `depends_on: ["minio", "cockroach"]` and automatically passes the right arguments to use the external `Minio` and `Cockroach` services, instead of using the in-container Cockroach and the file storage. That way we won't need to reinvent this in every workflow that wants to use the external services. 

But going to hold off on doing/helping with the above until 1) I have your buy in, @philip-stoev, and 2) https://github.com/MaterializeInc/materialize/pull/16866 merges, since it'll conflict badly otherwise.

**Comment by philip-stoev** [comment]
> I think we should take a step back and make some improvements to our infrastructure here:

I agree 110% . We have the `CREATE SCHEMA ...` set of queries at one too many places already. 

> When set to true, the service gets a depends_on: ["minio", "cockroach"]

Unfortunately that is half the battle. Using `depends on` alone to start services has bitten us in the past as it simply fires up the containers in question but does not really wait for them to become available. That is why making the schema_registry dependent on kafka which in turn is made dependent on zookeeper did not make for reliable starts . Instead, the `start_and_wait_for_tcp` function was implemented which starts the services named as arguments **in order** waiting for it to start responding before moving to the next service. For starting cockroach , we may even need `wait_for_cockroach` on top of having the TCP port open, in case cockroach, like Postgres, has the habit of returning `ERROR Server is not really up yet` error on the first queries that are issued against it?

Maybe we can extend `start_and_wait_for_tcp` to go through the dependencies as well and recursively call itself on them as well? If there is any residual flakiness, we will need to find a separate way to plug in `wait_for_cockroach` in there as well.

**Comment by benesch** [comment]
Re your last point, Docker Compose natively supports arbitrary health checks with dependencies, as of early this year! https://github.com/MaterializeInc/materialize/issues/1224

**Comment by philip-stoev** [comment]
@benesch Can I fix the Release Qualification Test by using `SET CLUSTER SETTING sql.stats.forecasts.enabled = false;` one last time in Zippy alone? This will allow the test to go back to green in short order so that it is not blocked waiting for all the other dominoes of the comprehensive solution to fall in dependency order?

I agree that the health checks are the way to go, but the feature is a bit half-baked. That is, some command needs to be run to provide pass/fail indication, and from my reading of the documentation it runs in the context of the container. This invites more bashisms in very restrictive environments :-( . The cockroachdb container does not have a psql client, etc etc for every single service separately.

**Comment by benesch** [comment]
I don't think the healthchecks are half baked! I got it mostly working a year ago: #9905.

In any case, I don't think we need to block this on getting healthchecks working for all services, but I do think it's time to tamp down the complexity in the `Materialized` service. It's getting very hard to add new options to the `Materialized` service given the number of dead options. Working on this in https://github.com/MaterializeInc/materialize/pull/16888.
