### ISSUE TITLE
process orchestrator: mz_storage_client::controller::rehydration: error connecting to storage host /tmp/environmentd-mzcompose-test-

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#16746]
### What version of Materialize are you using?

5448be744465db97c165ab9003878892a1902d29

### How did you install Materialize?

Docker image

### What is the issue?

@benesch we have the following situation in the CI:

1. We were doing `rm -rf /mzdata/*.pid *.ports` in order to work around a bug in the old process orchestrator that failed to re-start storageds on occasion
2. However, the `rm -rf` is issued by calling mzcompose's `run()` method , which in turn causes `docker up scale=0` on the materialized container (line 491 in __init__.py of mzcompose)
3. This however in turn causes all logs from the container prior to the `rm -rf` to be lost
4. Hence, for any CI jobs that perform restarts, we now only have the logs from environmentd post-restart in the build artifacts

I was hoping I can remove the `rm -rf` workaround altogether as we now have a new implementation of the process orchestrator, but unfortunately for some reason removing the `rm -rf`:

```
diff --git a/misc/python/materialize/mzcompose/__init__.py b/misc/python/materialize/mzcompose/__init__.py
index f55a5c193..fddc72b63 100644
--- a/misc/python/materialize/mzcompose/__init__.py
+++ b/misc/python/materialize/mzcompose/__init__.py
@@ -569,16 +569,6 @@ class Composition:
                 service["command"] = []
             self._write_compose()
 
-        if "materialized" in services:
-            # Work around https://github.com/MaterializeInc/materialize/issues/15725
-            # by cleaning up Process Orchestrator metadata on restart
-            self.run(
-                "materialized",
-                "-c",
-                "rm -rf /mzdata/*.pid /mzdata/*.ports",
-                entrypoint="bash",
-            )
-
         self.invoke("up", *(["--detach"] if detach else []), *services)
 
         if persistent:
```

or removing the `self.invoke("up", "--detach", "--scale", f"{service}=0", service)`  both cause tests to fail as follows:

```
environmentd: 2022-12-20T07:56:26.539049Z  INFO mz_storage_client::controller::rehydration: error connecting to storage host /tmp/environmentd-mzcompose-test-00000000-0000-0000-0000-000000000000-0/storage-u3/controller-0, retrying in 1s: transport error
```
repeated forever. It seems to me that the process orchestrator fails to start any storageds altogether after a restart.

To reproduce:

```
cd test/platform-checks
./mzcompose down -v ; ./mzcompose run default --check=SinkUpsert --scenario=RestartEntireMz 
```

**Comment by benesch** [comment]
Ah! /tmp is not automatically cleared in containers. Put up https://github.com/MaterializeInc/materialize/pull/16767 to fix.
