### ISSUE TITLE
mz cli: error decoding response body: invalid type when attempting to list app passwords

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#16752]
### What version of Materialize are you using?

1636215a8e95d5519052c1b8cd32feefe35706fd

### How did you install Materialize?

Docker image

### What is the issue?

```
philip@materialize:~/materialize$ target/debug/mz --profile staging app-password list
Error: failed to retrieve app passwords

Caused by:
    0: failed to parse results from server
    1: error decoding response body: invalid type: map, expected a sequence at line 1 column 0
    2: invalid type: map, expected a sequence at line 1 column 0
```

**Comment by rjnn** [comment]
cc @sjwiesman who just added this in #16696

**Comment by philip-stoev** [comment]
I am sorry, it is listing the app passwords that is broken, not the secrets. I have fixed the issue title accordingly.

**Comment by philip-stoev** [comment]
I have a fix I think , so assigning to myself
