### ISSUE TITLE
doc/user: wrap section headers in TOC

### ISSUE THREAD

**Issue by morsapaes** [MaterializeInc/materialize#16771]
In the new design template, if a section header doesn't fit the width of the TOC widget, it overflows to infinity instead of wrapping into a new line:

<img width="374" alt="Screenshot 2022-12-21 at 03 25 12" src="https://user-images.githubusercontent.com/23521087/208813951-e78fc4b4-c920-42aa-aa7a-cfa3f39c97f6.png">

As an example, see [this page](https://materialize.com/docs/integrations/dbt/#configuration) + the [expected behaviour](https://materialize.com/docs/lts/integrations/dbt/) in the old template.

**Comment by morsapaes** [comment]
Noticed another unexpected wrapping behaviour: link text seems to be treated as a block, instead of naturally wrapping on a line break.

<img width="838" alt="Screenshot 2022-12-21 at 04 16 29" src="https://user-images.githubusercontent.com/23521087/208820121-158814d8-7c51-4ef3-ba35-5ed88fd1eace.png">

If we _e.g._ remove "connection" from the link text, the wrapping is different:

<img width="840" alt="Screenshot 2022-12-21 at 04 17 45" src="https://user-images.githubusercontent.com/23521087/208820232-b86f9069-7f45-49e4-aa6b-c5e0a324b73a.png">

**Comment by nisarhassan12** [comment]
Fixed in #17143
