### ISSUE TITLE
storage: make persist_source independent of batch sizes

### ISSUE THREAD

**Issue by teskje** [MaterializeInc/materialize#16783]
### Feature request

Currently, the size of chunks emitted by `persist_source` depends on the size of the persist batches being read. Persist batches can grow in size without bounds, so the memory usage of `persist_source` can also grow without bounds.

One scenario where this causes problems is when a compute cluster had a long downtime, so on the inputs of the dataflows it maintains a lot of uncompacted data has been allowed to queue up. Persist has performed physical compaction on that data, resulting in few large batches, but it wasn't allowed to perform logical compaction before the compute cluster had a chance to look at all the times. So when a compute replica comes back up, it starts reading that queued data again. `persist_source` reads one of the large batches at a time, which might lead to the replica getting OOM-killed if the batch is larger than the available memory. Note that `persist_source`'s flow control support doesn't help with this, as it always must emit data until it can advance its frontier, to ensure progress in the downstream operators.

`persist_source` could be changed to stream batch parts (which are limited in size to 128 MB) instead of batches. However, that would only help reduce memory usage in some cases. Many of the interesting dataflow operators (like joins and reduces) require their input frontier to advance before they can make progress, and `persist_source` cannot advance its output frontier before it has read a whole batch. So this is not a satisfying solution.

**Comment by teskje** [comment]
[Relevant discussion in Slack.](https://materializeinc.slack.com/archives/C01CFKM1QRF/p1671540207116969)

**Comment by dseisun-materialize** [comment]
@danhhz is this effectively backpressure for compute? Is this particular ticket still relevant?

**Comment by danhhz** [comment]
@dseisun-materialize This is a necessary precondition for compute turning backpressure on. Very much relevant and I think it should probably get bumped in priority. Things like incident 70 make it a little embarrassing to not have compute backpressure
