### ISSUE TITLE
storage: idling RDS sources are reported as stalled

### ISSUE THREAD

**Issue by petrosagg** [MaterializeInc/materialize#16786]
When a user connects their RDS instance to materialize and that instance doesn't have a steady stream of diffs we eventually incorrectly report the source as stalled with an error even though it's fine.

The error reported is `reached maximum WAL lag`, which is something that happens periodically with RDS sources but doesn't necessarily indicate that something is wrong. There are two separate causes for this:

1. The postgres source reader exposes this error to the rest of the ingestion pipeline in the first place. This is arguably wrong since it's just a normal thing to happen during replication streaming and the pg reader should instead silently handle it without emitting an error. We can consider emitting an error when more complex error conditions are met, for example if we hit the maximum replication lag twice in a row, which should never happen.
2. The ingestion pipeline only learns about progress from the sources when those sources have data to emit. This is problematic for idle postgres sources because while the source is in fact observing its LSN frontier advancing it has no way to report it to the rest of the system unless an actual row comes in. Refactoring of the source traits to allow for pure progress to be communicated is implemented in https://github.com/MaterializeInc/materialize/pull/16214 but further changes need to be done to the individual sources to make use of the newly introduced trait.

**Comment by morsapaes** [comment]
@materializekatrina, this is the situation you ran into in the on-site, when there was no new data being produced after the snapshot.

**Comment by petrosagg** [comment]
This is fixed by https://github.com/MaterializeInc/materialize/pull/19239
