### ISSUE TITLE
Write blog post about robust Reduce

### ISSUE THREAD

**Issue by frankmcsherry** [MaterializeInc/materialize#1680]
Write a blog post about the changes to Reduce from our initial naive version that assembles all records, perhaps with a stop along the way at in-place aggregation, but arriving at the recently PR'd version that disassembles each of the aggregates, applies distinct as an operator, and hierarchically aggregates when appropriate.

Ideally some experimentation with the old versus the new implementation, although most of the difference is going to be in the incremental update time rather than throughput or memory or such. But, great exercise to put together a workload that demonstrates the improvements, even if contrived.

**Comment by rjnn** [comment]
deprecated in favor of the content calendar. please add this to the internal content calendar and then close this issue.
