### ISSUE TITLE
Confusing result when trying to select rows from a non-existent namespace

### ISSUE THREAD

**Issue by umanwizard** [MaterializeInc/materialize#1684]
```
brennan=> select asdf.* from foo;
--
(3 rows)
```

`asdf.*` is indeed the empty set of columns, since there is nothing called `asdf`. But it would be better to throw a warning rather than trying to return something here.

**Comment by ruchirK** [comment]
I think this was actually fixed at some point. When I retry the original query I get
```
materialize=> select asdf.* from foo;
ERROR:  unknown catalog item 'foo'
materialize=>
```

**Comment by benesch** [comment]
I'm afraid it wasn't, actually! You need to have an object called `foo` to see the bug:

```
materialize=> create view foo as select 1;
CREATE VIEW
materialize=> select asdf.* from foo;;
--
(1 row)
```

**Comment by ruchirK** [comment]
Oh whoops! Thanks for catching that Nikhil
