### ISSUE TITLE
persist: only emit entire batches (even during shutdown)

### ISSUE THREAD

**Issue by danhhz** [MaterializeInc/materialize#16860]
Some operators downstream of persist have sanity checks that can trigger if persist_source is shut down via the token at the wrong time. Concretely: if we only emit certain parts of a batch, then downstream operators might see a negative accumulation.

My first instinct for how to fix this is for "shard_source_descs" to be very careful to never have an await point in between emitting parts. Then "shard_source_fetch" would disconnect the shutdown button, so it fetches everything it gets, regardless of whether the dataflow is shutting down.

Note: It's still unclear if this is desirable behavior. Quoting aljoscha:

> Say we get cancelled after reading 1gb of a 10gb batch. We would still read the remaining 9gb, which reduce.rs (and friends) would compute on, and that result would also be ignored.

Note 2: This is in some ways a more limited version of #16858

**Comment by frankmcsherry** [comment]
I don't want to speak to `persist`, but in DD if you read batches from oldest to newest, and each batch is consolidated, you have the ability to avoid records that never existed. The batch total order reveals collections that did actually exist, and you could in principle stop at any key, or any (key, val), or any (key, val, time) within that batch, and not produce records that did not exist. The collection itself might not have existed (if the updates are not time ordered), but it is at least one sanity property that might help.

**Comment by danhhz** [comment]
@pH14 I heard you were interested in picking this one off, so assigning to you. also slotting it in at the top of our priority list in the tracker issue
