### ISSUE TITLE
 mz: various improvements

### ISSUE THREAD

**Issue by rjnn** [MaterializeInc/materialize#16878]
### Feature request

- [x] profiles - right now profiles are a hidden modal thing behind the scenes. if you type ` mz --profile staging login` youre in staging, but now theres no way to find out that you are in staging. Profiles should support `profile list`, `profile set`, etc.
- [x] set region in profile - repeatedly typing `mz shell aws/us-east-1` is annoying, i dont switch regions often (or ever, really)
- ~make region names case insensitive - the cloud ui says "AWS/us-east-1" but the cli says `aws/us-east-1` and does not accept what is displayed in the UI~ Tracked in https://github.com/MaterializeInc/materialize/issues/15371
- [x] Enable `\timing` by default: https://materializeinc.slack.com/archives/CU7ELJ6E9/p1672349454736779

**Comment by joacoc** [comment]
Enabling `\timing` is a bit tricky. Sending the command `\timing` to `psql` makes the stdin/stdout go wild for certain actions, e.g., pressing the arrow keys does nothing. An alternative, with user confirmation, is appending the timing command to ``~/.psqlrc``.

**Comment by benesch** [comment]
> Sending the command `\timing` to `psql` makes the stdin/stdout go wild for certain actions, e.g., pressing the arrow keys does nothing

Yeah, it's documented here in the PostgreSQL manual:

<img width="1585" alt="image" src="https://github.com/MaterializeInc/materialize/assets/882976/5146019b-08e6-48db-9dbb-2bf813a0247d">

—https://www.postgresql.org/docs/current/app-psql.html

Specifying either `-c` or `-f` disables Readline, which means you lose all the fancy terminal line editing features, like arrow keys and such.

> An alternative, with user confirmation, is appending the timing command to `~/.psqlrc`.

I like the direction this is going, but I think editing the user's main `psqlrc` would be rude! But what we can do instead is use a _different_ psqlrc. Here's what I'd recommend. 

  * `mz shell` checks whether `~/.psqlrc-mz` exists. If it doesn't, it writes the following default contents:
    ```
    \timing
    \include ~/.psqlrc
    ```
  * `mz shell` sets `PSQLRC` to `~/.psqlrc-mz` before invoking `psql`.

This means that `\timing` will be enabled by default, the user's default `psqlrc` will be read by default, and they have full ability to change this default behavior by editing `~/.psqlrc-mz`.

**Comment by joacoc** [comment]
@benesch Wow. That solution is amazing. It worked like a charm. I will prepare the PR.

**Comment by benesch** [comment]
Awesome! I guess the one other thing to watch out for: `\include ~/.psqlrc` will fail if `~/.psqlrc` doesn't exist. So `mz shell` probably needs to create `~/.psqlrc` if it doesn't exist.

**Comment by joacoc** [comment]
Already added! I'm cooking the test 🧑‍🍳

**Comment by joacoc** [comment]
Issues resolved.
