### ISSUE TITLE
SQL: Support `USING` join aliases

### ISSUE THREAD

**Issue by jkosh44** [MaterializeInc/materialize#16910]
### What version of Materialize are you using?

v0.38.0-dev (3dc9c0b76)

### How did you install Materialize?

Built from source

### What is the issue?

PostgreSQL allows specifying an alias for the join columns when using the `USING` syntax. More details can be found here: https://www.postgresql.org/docs/current/sql-select.html
> `USING ( join_column [, ...] ) [ AS join_using_alias ]`
>
>    A clause of the form `USING ( a, b, ... )` is shorthand for `ON left_table.a = right_table.a AND left_table.b = right_table.b ...`. Also,  `USING` implies that only one of each pair of equivalent columns will be included in the join output, not both.
>
>    If a `join_using_alias` name is specified, it provides a table alias for the join columns. Only the join columns listed in the `USING` clause are addressable by this name. Unlike a regular `alias`, this does not hide the names of the joined tables from the rest of the query. Also unlike a regular `alias`, you cannot write a column alias list — the output names of the join columns are the same as they appear in the `USING` list.

In Materialize we do not support this syntax.

### Relevant log output

```source
postgres=# CREATE TEMP TABLE tbl1 (a int, b int);
CREATE TABLE
postgres=# CREATE TEMP TABLE tbl1a (a int, c int);
CREATE TABLE
postgres=# SELECT * FROM tbl1 join tbl1a USING (a) as x;
 a | b | c 
---+---+---
(0 rows)


materialize=> CREATE TEMP TABLE tbl1 (a int, b int);
CREATE TABLE
materialize=> CREATE TEMP TABLE tbl1a (a int, c int);
CREATE TABLE
materialize=> SELECT * FROM tbl1 join tbl1a USING (a) as x;
ERROR:  Expected OF, found identifier "x"
LINE 1: SELECT * FROM tbl1 join tbl1a USING (a) as x;
                                                   ^
```

**Comment by benesch** [comment]
@jkosh44 this strikes me more as a feature request than a bug? As in, I don't think we need to rush to fix this.

**Comment by jkosh44** [comment]
Yeah. good point, I'll re-tag it.

**Comment by benesch** [comment]
Fixed by https://github.com/MaterializeInc/materialize/pull/18793.
