### ISSUE TITLE
Audit + Remove Invalid AWS PrivateLink Connection Objects

### ISSUE THREAD

**Issue by chaas** [MaterializeInc/materialize#16942]
With #16804 going out in this release, any environments with AWS PrivateLink connections with invalid availability zone ids will cause the customer's environment to fail to start up.

As such, we must run a manual script to find + delete all of these existing invalid AWS PrivateLink connections. It should be safe to force drop all of those broken PL connections (if any even exist at all), since they can't possibly be working.

Going forward, customers will be prevented from creating this invalid connections.

The script could work like e.g. https://materializeinc.slack.com/archives/C01KV5PEZ9R/p1671472332424089, where we query for all PL connections for all customers on prod + staging, since there shouldn't be many, and print them out, manually inspecting whether the AZ ids are valid.

@alex-hunt-materialize do you have cloud admin access to execute this script? Also do you have the list of AZs we will support?

cc @benesch

**Comment by benesch** [comment]
I think `SHOW CREATE CONNECTION` should do it!

**Comment by chaas** [comment]
🔥 I learn something new every day!
Ok I amend my original comment then. We can use a script that does the following:
1) `SELECT name FROM mz_connections WHERE type = 'aws-privatelink'`
2) `SHOW CREATE CONNECTION <name>` for each result in 1
3) Manually inspect AVAILABILITY ZONES for each result in 2 + delete if invalid

**Comment by chaas** [comment]
@alex-hunt-materialize ran the audit and confirmed there are no privatelink connections in staging and the two environments in production with privatelink connections all look correct, so we're good to go.
