### ISSUE TITLE
mz: error formatting

### ISSUE THREAD

**Issue by ggnall** [MaterializeInc/materialize#16983]
The CLI returns errors in a stack and technical way:

```bash
Error: Retrieving cloud provider region.

Caused by:
    0: Retrieving region data.
    1: Region unavailable
```

It should be able to return errors in a more human-friendly way:
https://developers.google.com/tech-writing/error-messages/identify-the-cause
https://rust-cli.github.io/book/in-depth/human-communication.html

**Comment by joacoc** [comment]
Solved in the new CLI.
