### ISSUE TITLE
regex table function docs

### ISSUE THREAD

**Issue by sploiselle** [MaterializeInc/materialize#1699]
Document selecting from regex, e.g. naming columns, etc.

**Comment by rjnn** [comment]
Ping - do you have a timeline estimate for this?

**Comment by sploiselle** [comment]
@rjnn I left this as a stub for an item that I misunderstood as being-imminently-built (`parse_regex`, which would be a table-valued regex function). However, it seems like it was more animated discussion than an actual work item. Does this ticket name have some other meaning to you that I _should_ document?

**Comment by rjnn** [comment]
No. I have no idea what this is beyond that it was tagged 0.2 and is still open as I was doing some housekeeping! Feel free to close it or update it with more detail and remilestone it :)
