### ISSUE TITLE
[Epic] Idle merge effort skews CPU metrics

### ISSUE THREAD

**Issue by antiguru** [MaterializeInc/materialize#17002]
### What version of Materialize are you using?

main

### How did you install Materialize?

Materialize Cloud

### What is the issue?

The introduction of Differential's `idle_merge_effort` in #16785 causes Timely to do additional work when no other work is pending. This results in observed higher CPU utilization without impeding the general performance of a compute instance.

However, we use the CPU utilization as a metric to determine how healthy a replica is and also expose this information to users. This is now misleading because a high CPU utilization does not indicate an instance being overloaded.

We need to find a different way to report CPU utilization, for example by splitting the time spend handling the idle merges from regular data processing. See [Slack](https://materializeinc.slack.com/archives/C02PPB50ZHS/p1673006283839439) for more details.

### Relevant log output

```source
/
```

**Comment by antiguru** [comment]
Here's a rough breakdown on what happens within compute, which probably helps to put things into perspective:
* There is a driver which does
  * Check incoming messages
  * Report results
  * Perform arrangement maintenance
  * Give Timely time to run
* CPU utilization captures all of the above.
* Ideally, we have
  * CPU utilization as the outside view of how much resources we're using. For compute threads, this is OK to approach 100% after the idle_merge_effort change.
  * Time spend in Timely can be broken into
     * Time spend in operators
     * Time yielding to the OS
     * The rest is overhead, and some part of progress tracking
     * -> effective utilization is all minus time yielding to the OS
  * Arrangement maintenance can be measured, not sure we may not have the right mechanism yet. 
  * We don't measure how much time we spend in check incoming messages/report results.
* This means we have
  * CPU utilization as upper bound,
  * stacked below: timely operators, arrangement maintenance, yielding to the OS
  * Rest, which is unknown Timely overhead and driver maintenance

**Comment by teskje** [comment]
Quick update: The plan is know to configure DD differently, so it only spends idle time on batch merging when that would lead to a significant relative decrease in arrangement size. We've run tests to verify that this will only have a minor effect on CPU usage for common workloads (see [Notion](https://www.notion.so/materialize/Disabling-Idle-Arrangement-Merging-e1d95bc1e8a141d284db2e630967b25b)).
