### ISSUE TITLE
~27% performance regression in multiple scenarios after "persist: refactor batch builder: merge user + compaction write paths"

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#17003]
### What version of Materialize are you using?

455b184d823a716cf91610d62c444fe91b68e8ee

### How did you install Materialize?

Docker image

### What is the issue?

The feature benchmark reports a performance regression that affects multiple distinct scenarios. It is reliably reproducible

https://buildkite.com/materialize/nightlies/builds/1602#0185847e-36e8-4c61-b505-9f51433ef511

```


Benchmark Report for cycle 5: | 0s
-- | --
  | NAME                      \|    THIS     \|    OTHER    \|  Regression?  \| 'THIS' is:
  | ----------------------------------------------------------------------------------------------------
  | Insert                    \|       2.844 \|       2.488 \|    !!YES!!    \| 14.3 pct   slower
  | Update                    \|       5.305 \|       4.528 \|    !!YES!!    \| 17.2 pct   slower
  | UpdateMultiNoIndex        \|       5.454 \|       4.458 \|    !!YES!!    \| 22.4 pct   slower
  | InsertAndSelect           \|       3.459 \|       3.055 \|    !!YES!!    \| 13.2 pct   slower
  | CountDistinct             \|       0.398 \|       0.350 \|    !!YES!!    \| 13.8 pct   slower
  | CreateIndex               \|       1.121 \|       0.881 \|    !!YES!!    \| 27.3 pct   slower
  | DifferentialJoin          \|       0.343 \|       0.287 \|    !!YES!!    \| 19.7 pct   slower
  | FinishOrderByLimit        \|       0.339 \|       0.267 \|    !!YES!!    \| 27.1 pct   slower

```

bisection revealed the following commit:

```
commit 455b184d823a716cf91610d62c444fe91b68e8ee (HEAD, refs/bisect/bad)
Author: Paul Hemberger <paul@materialize.com>
Date:   Thu Jan 5 10:06:05 2023 -0500

    persist: refactor batch builder: merge user + compaction write paths (#16602)
```

Curiously, the scenarios affected perform varied workloads. Initially I thought the speed of DDL statements may have slowed down, but the `FinishOrderByLimit` scenario for example does not perform DDLs.

To reproduce:

```
bin/mzcompose --find feature-benchmark down -v ;
bin/mzcompose --find feature-benchmark run default --scenario=FinishOrderByLimit --other-tag=latest
```

@pH14 FYI

**Comment by pH14** [comment]
I'll take a look! My initial reaction here is: we _thought_ we were consolidating updates when ingesting data prior to that PR, but actually weren't -- there's some chance this is the cost of doing what we meant to be doing all along

**Comment by danhhz** [comment]
Feel free to revert this to unblock the release. We can always unrevert once we've figured it out

**Comment by philip-stoev** [comment]
What is common between those scenarios is that they operate on user tables. I initially though the issue was because the table is populated using a cross join, but the issue is also reproducible with  table populated via generate_series.

The table contains by default 1M rows, but the issue is also reproducible with 100K rows and with 3M rows , so it does not seem to be some sort of a one-time , per-query overhead, which was my other theory.

**Comment by benesch** [comment]
We've been running like this for a while, so either 1) the regression was fixed or 2) we're living with the regression. Either way, calling this complete!
