### ISSUE TITLE
regression: OOM when loading a 2GB Postgres snapshot

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#17044]
### What version of Materialize are you using?

455b184d823a716cf91610d62c444fe91b68e8ee

### How did you install Materialize?

Docker image

### What is the issue?

Prior to this commit

```
commit 455b184d823a716cf91610d62c444fe91b68e8ee
Author: Paul Hemberger <paul@materialize.com>
Date:   Thu Jan 5 10:06:05 2023 -0500

    persist: refactor batch builder: merge user + compaction write paths (#16602)
```

The `test/bounded-memory` test was able to load a 2Gb postgres snapshot without OOM-ing a clusterd that had been given 3Gb of memory.

After this commit, under the same circumstances `clusterd` will be reliably being killed by the OOM killer.

To reproduce, use a `ci` scratch machine and then run `bin/mzcompose --find bounded-memory run default` and wait. The test will hang here:

```
> CREATE SOURCE mz_source FROM POSTGRES CONNECTION pg (PUBLICATION 'mz_source') FOR ALL TABLES WITH ( REMOTE 'clusterd:2100' );
rows match; continuing at ts 1673268653.151359
> CREATE MATERIALIZED VIEW v1 AS SELECT COUNT(*) FROM t1;
rows match; continuing at ts 1673268653.2906787
> SELECT * FROM v1; /* expect 2097152 */
rows didn't match; sleeping to see if dataflow catches up 50ms 75ms 113ms 169ms 253ms 380ms 570ms 854ms
```
at which point dmesg will report the OOM kill.

**Comment by pH14** [comment]
This one was a silly mistake, we weren't clearing a buffer when parts were written to S3, so we accumulated a full batch in memory accidentally. When this PR is reintroduced, there's a very straightforward fix

**Comment by pH14** [comment]
The original PR was reverted and https://github.com/MaterializeInc/materialize/pull/17116 landed with a fix for the memory leak. This one is [all set](https://github.com/MaterializeInc/materialize/pull/17116#pullrequestreview-1249648735)
