### ISSUE TITLE
create `http-client` source type

### ISSUE THREAD

**Issue by quodlibetor** [MaterializeInc/materialize#1704]
Similar to #1701, but sort of the inverse, this will configure materialized to act as a client to some http server. E.g. `CREATE SOURCE wikipedia FROM 'https://stream.wikimedia.org/v2/stream/recentchange' WITH (..)` will create a connection that always reconnects and emits lines to the source `wikipedia`

**Comment by elindsey** [comment]
I'm moving this off the sources and sinks board and onto the product backlog board - it'll need more poking at to determine if we want to do it. I think #2237 may subsume this task, that would cover most of the interesting use cases and in a more standardized way.

**Comment by morsapaes** [comment]
Closing in favor of #2237.
