### ISSUE TITLE
Document datagrip as a SQL Client

### ISSUE THREAD

**Issue by sjwiesman** [MaterializeInc/materialize#17054]
### Documentation request

It turns out DataGrip does work with materialize, you just have to disable introspection[1][2]. 

[1] https://materialize.com/docs/integrations/sql-clients/
[2] https://intellij-support.jetbrains.com/hc/en-us/community/posts/360010694760-How-to-turn-off-automatic-database-introspection-in-Datagrip-

**Comment by morsapaes** [comment]
Using DataGrip with Materialize to an extent where it's working more than as a `psql` shell would require the catalog work mentioned in [#17054](https://github.com/MaterializeInc/materialize/issues/9720) (see [DevEx #204](https://github.com/MaterializeInc/developer-experience/issues/204)). We've documented it with the existing limitations in #17558.

(CC @ggnall)
