### ISSUE TITLE
storage: `create_collections` should parallelize or batch its stash and persist operations

### ISSUE THREAD

**Issue by mjibson** [MaterializeInc/materialize#17057]
### Feature request

We think it already does this for stash. Definitely need to do this for persist. This is needed to speed up envd startup, where currently each call to this function takes 80ms, and is done once per table. (The adapter team is in charge of batching calls to this function.)

**Comment by mjibson** [comment]
(Stash operations should be batched; they can't be parallelized.)

**Comment by aljoscha** [comment]
Registering the shard mapping is causing a persist write, and we're currently doing them one-by-one: https://github.com/MaterializeInc/materialize/blob/8d6cf19f484b7904b92132c17a9b1796b768e443/src/storage-client/src/controller.rs#L951.

We should also batch those up.

**Comment by mjibson** [comment]
Here's a trace with bootstrap making a batched call to create_collections. Definitely blocked on faster persist.

![image](https://user-images.githubusercontent.com/41181/211681723-8e53e55f-9375-483a-994a-bf1aeffdddcb.png)

**Comment by aljoscha** [comment]
What's left to do here?

**Comment by dseisun-materialize** [comment]
@mjibson doing some cleanup and checking in if this ticket is still relevant

**Comment by mjibson** [comment]
Dunno! @guswynn reopened, but I'm not sure why. Surfaces has no outstanding requests here.

**Comment by guswynn** [comment]
This should have been closed with https://github.com/MaterializeInc/materialize/pull/17352
