### ISSUE TITLE
compute: Add replica fully hydrated metric

### ISSUE THREAD

**Issue by lluki** [MaterializeInc/materialize#17064]
### Feature request

When starting a new replica, the initial ingestion may extra load on the replica. We want to know when this phase is over to debug performance problems.

[Slack discussion](https://materializeinc.slack.com/archives/C02PPB50ZHS/p1672914795973389)

## Implementation

It's probably possible to get this metric by adding a query to the promsql exporter. Any dataflow that is initialized will show up in `mz_raw_worker_compute_delays` hence we just need to confirm all dataflows are there (in each replica).

## Blockers

Implementation can start without #14102, but results will be incorrect as we will miss some dataflows.

**Comment by teskje** [comment]
We have `mz_dataflow_initial_output_duration_seconds` now, which kind of gives us this. More hydration metrics are discussed by the observability team, so I don't think we need this issue anymore.
