### ISSUE TITLE
Document default topic configuration when Kafka sink creates a topic

### ISSUE THREAD

**Issue by sjwiesman** [MaterializeInc/materialize#17109]
### Documentation request

The Kafka sink will ensure the target topic exists, and create it if it does not. We should document the configuration used for the topic when created by materialize (number of partitions, retention policy, etc).

**Comment by sjwiesman** [comment]
@bkirwi can you help provide the configuration details? I'm not entirely sure where to look in the codebase.

**Comment by benesch** [comment]
Just stumbled across this issue and funnily enough I just added docs for this.

* Docs: https://materialize.com/docs/sql/create-sink/kafka/#automatic-topic-creation
* PR: https://github.com/MaterializeInc/materialize/pull/23601
