### ISSUE TITLE
Create an mzjdbc

### ISSUE THREAD

**Issue by JLDLaughlin** [MaterializeInc/materialize#1713]
We currently use a [forked version](https://github.com/MaterializeInc/pgjdbc) of [pgjdbc](https://github.com/pgjdbc/pgjdbc) to allow Metabase to connect to Materialize. The forked version has relatively few tweaks (mostly around `pg_catalog`) that differentiates it from the clean version. 

In the future, we should reconcile these differences to use pgjdbc directly.

**Comment by andrioni** [comment]
I'll keep this issue around just in case we ever decide to fork pgjdbc in the future again, but for now Metabase (the main motivation behind the original fork) already works with Materialize out of the box.
