### ISSUE TITLE
Ship metabase-materialize-driver as part of the core Metabase repo

### ISSUE THREAD

**Issue by JLDLaughlin** [MaterializeInc/materialize#1714]
Right now, the [metabase-materialize-driver](https://github.com/MaterializeInc/metabase-materialize-driver) is being shipped as a 3rd party plugin because it was faster and I was skeptical of the Metabase approving a PR with our weird [pgjdbc hack](https://github.com/MaterializeInc/pgjdbc). 

The downside of `metabase-materialize-driver` being a 3rd party plugin is that the user will have to do work (downloading a jar and moving it into a folder) instead of no work (having it ship as part of Metabase). To improve usability, we should eventually move this code to be a packaged plugin shipped with the Metabase repo instead.

Blockers:
https://github.com/materializeinc/materialize/issues/1713

Relevant info:
- [Metabase drivers shipped with core repo](https://github.com/metabase/metabase/wiki/Writing-a-Driver:-Packaging-a-Driver-&-Metabase-Plugin-Basics#drivers-shipped-as-part-of-the-core-metabase-repo-but-packaged-as-plugins)

**Comment by rjnn** [comment]
Now that we're publicly visible, we can do this and PR it to Metabase/metabase

**Comment by benesch** [comment]
I think is is still blocked by #1713.

**Comment by chaas** [comment]
We are being shipped as a partner driver on 47 (Cloud)
https://github.com/metabase/metabase/pull/33409
https://github.com/metabase/metabase/pull/33412

**Comment by chaas** [comment]
We are being shipped as a partner driver on 47 (Cloud)
