### ISSUE TITLE
adapter: Be less cautious about failing RTR queries due to concurrent DDL

### ISSUE THREAD

**Issue by jkosh44** [MaterializeInc/materialize#17148]
### Feature request

As of #17127, any query that requests a real time recency timestamp will wait for that timestamp off of the main Coordinator thread. While waiting for that timestamp, it's possible that the contents of the catalog has changed and the query is no longer valid. If that's the case then we need to return an error back to the user.

The current logic checks if anything has changed in the catalog since the start of the query. If so, we return an error. That logic can be found here:
https://github.com/MaterializeInc/materialize/blob/22950bbc7e588c1a91137b006c6b3dd234644e74/src/adapter/src/coord/message_handler.rs#L707-L712

This is overly cautious because the catalog may have changed objects unrelated to the query and the query is still valid. It would be a much better UX for us to further check which objects in the catalog have changed and if those objects are related to the query.

Although current approach is overly cautious, it is not incorrect. It's always OK to abort a query if there might be an issue.

There is some additional discussion about this in #17127 and #16651

@mjibson Points out that we might be able to preserve the original statement and re-plan from the top. This will be complicated, but hopefully do-able, for read-then-write statements which have a bit of a nested structure in their sequencer code.

Part of #11531

**Comment by sploiselle** [comment]
Is this closed as of #19195?

**Comment by jkosh44** [comment]
Yes, thanks for following up!
