### ISSUE TITLE
Consider providing a Terraform module to automate Kafka PrivateLink NLB setup

### ISSUE THREAD

**Issue by benesch** [MaterializeInc/materialize#17158]
### Feature request

Setting up AWS PrivateLink for use with AWS PrivateLink is challenging. @chuck-alt-delete reports one case that required 9 brokers, 9 target groups, 9 listeners, 3 AZs, and one NLB/endpoint service. That's a lot of copy/pasting that can go wrong.

He suggests creating a Terraform module. Roughly, you'd provide as input the ID of your MSK cluster, and it would spin up a properly configured load balancer for use with Materialize. For bonus points, it could spit out the exact `CREATE CONNECTION` and `CREATE SOURCE` commands to run in Materialize.

cc @morsapaes @bobbyiliev

**Comment by bobbyiliev** [comment]
The module has been pushed here: https://github.com/MaterializeInc/terraform-aws-kafka-privatelink

Currently, the user needs to provide the following:
- The name of their MSK cluster
- The Port that they would be using for the connection, eg 9092 for plaintext, 9094 for TLS and etc. as they might have multiple enabled for the existing cluster 
- The VPC ID where the cluster is deployed at

The module would not work with a self-managed Kafka cluster, as it relies on the `aws_msk_broker_nodes` datasource to get the information for the cluster automatically. Next, we could extend this where the user would need to manually specify a list of their brokers + subnets.

**Comment by benesch** [comment]
Thank you for turning this around so quickly, @bobbyiliev! Calling this closed. Opened some issues against the new repository to track the (optional) follow up work.
