### ISSUE TITLE
Support by OS

### ISSUE THREAD

**Issue by sploiselle** [MaterializeInc/materialize#1717]
Does Materialize work on some specific OS?

https://docs.google.com/spreadsheets/d/13N3ZxNo1ovPU2uQRsBq4mgakgg6mRCOt818EJqQB9S0/edit#gid=0

This information is a best effort and is not guaranteed to be accurate or up to date.

**Comment by morsapaes** [comment]
(Digging through old documentation issues) @sploiselle, is this worth documenting under `doc/developer` somewhere, or can the issue be closed?

**Comment by sploiselle** [comment]
With the advent of platform, this becomes moot
