### ISSUE TITLE
regression: Logs fill up with "error fetching metrics for u3: unknown service u3"

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#17187]
### What version of Materialize are you using?

v0.40.0

### How did you install Materialize?

Docker image

### What is the issue?

The logs are filling up with those messages even for tests that do not drop any sources, such as the Zippy tests (which only create new database objects but never drop existing ones)

To reproduce:

```
cd test/zippy
./mzcompose run default --scenario=KafkaSources
```

and examine the log of the materialized container.

### Relevant log output

```source
zippy-materialized-1     | environmentd: 2023-01-17T01:23:26.641707Z  WARN mz_storage_client::controller::metrics_scraper: error fetching metrics for u8: unknown service u8
zippy-materialized-1     | environmentd: 2023-01-17T01:23:26.641731Z  WARN mz_storage_client::controller::metrics_scraper: error fetching metrics for u42: unknown service u42
zippy-materialized-1     | environmentd: 2023-01-17T01:23:26.641735Z  WARN mz_storage_client::controller::metrics_scraper: error fetching metrics for u60: unknown service u60
zippy-materialized-1     | environmentd: 2023-01-17T01:23:26.641742Z  WARN mz_storage_client::controller::metrics_scraper: error fetching metrics for u68: unknown service u68
zippy-materialized-1     | environmentd: 2023-01-17T01:23:26.641748Z  WARN mz_storage_client::controller::metrics_scraper: error fetching metrics for u21: unknown service u21
zippy-materialized-1     | environmentd: 2023-01-17T01:23:26.641751Z  WARN mz_storage_client::controller::metrics_scraper: error fetching metrics for u50: unknown service u50
zippy-materialized-1     | environmentd: 2023-01-17T01:23:26.641756Z  WARN mz_storage_client::controller::metrics_scraper: error fetching metrics for u55: unknown service u55
zippy-materialized-1     | environmentd: 2023-01-17T01:23:26.641759Z  WARN mz_storage_client::controller::metrics_scraper: error fetching metrics for u15: unknown service u15
zippy-materialized-1     | environmentd: 2023-01-17T01:23:26.641762Z  WARN mz_storage_client::controller::metrics_scraper: error fetching metrics for u26: unknown service u26
zippy-materialized-1     | environmentd: 2023-01-17T01:23:26.641766Z  WARN mz_storage_client::controller::metrics_scraper: error fetching metrics for u33: unknown service u33
```

**Comment by philip-stoev** [comment]
https://buildkite.com/materialize/release-qualification/builds/65#0185babc-b85b-40d3-90b3-dfea68a74e39

is an example of a log infested with those messages. The test does not drop sources nor it does restart any part of Mz . Yet there is one such message per source per 10 seconds.

**Comment by philip-stoev** [comment]
See discussion here https://materializeinc.slack.com/archives/C01CFKM1QRF/p1673473114111099

**Comment by aljoscha** [comment]
Oh boy, the reason is that the storage controller doesn't differentiate between REMOTE and MANAGED storage hosts/clusters. And these tests use REMOTE clusters so the orchestrator doesn't know about them when we try and go fetch metrics. PR incoming. 🙈

**Comment by aljoscha** [comment]
@philip-stoev After https://github.com/MaterializeInc/materialize/pull/17256 this should not be an issue anymore, it's fixed as a side effect, similar to the PR that I had opened. Do you want to verify by yourself that this is actually true?

**Comment by benesch** [comment]
> Do you want to verify by yourself that this is actually true?

I'll take your word for it. Closing, thanks!
