### ISSUE TITLE
adapter: removing of an allowed replica size can break restart

### ISSUE THREAD

**Issue by benesch** [MaterializeInc/materialize#17194]
### What version of Materialize are you using?

v0.41-dev

### How did you install Materialize?

Built from source

### What is the issue?

Removing an allowed replica size from the `allowed_cluster_replica_size` variable will cause Materialize to fail to boot on restart if any replicas of the now-disallowed size exist.

```
$ psql -h localhost -p 6875 -U materialize materialize
materialize=> create cluster foo replicas (r1 (size '2'));
CREATE CLUSTER
```

```
$ psql -h localhost -p 6877 -U mz_system
mz_system=> alter system set allowed_cluster_replica_sizes = '1';
ALTER SYSTEM
mz_system=> 
```

Reboot Materialize and 💥.

**Comment by benesch** [comment]
@chaas @ggnall we should get this one fixed up ASAP (ideally for v0.41) to control free trial spend.

**Comment by aalexandrov** [comment]
What is the desired behavior: we should only validate against the `allowed_cluster_replica_size` when issuing new commands, but accept all replica sizes from objects already persisted in the catalog or the command history?

**Comment by benesch** [comment]
Precisely!

**Comment by benesch** [comment]
I’d be surprised if we do! At least, I remember being careful to design
those other limits to only apply during initial creation, and not during
catalog bootstrap.

**Comment by aalexandrov** [comment]
My mistake, the sources continue to work after restart.

**Comment by benesch** [comment]
Did you mean to close this? When I tested locally, removing a size from `allowed_cluster_replica_size` and then restarting locally caused Materialize to fail to boot.

**Comment by benesch** [comment]
I tried to test this in staging with LaunchDarkly, but updated the `allowed_cluster_replica_size` feature flag in LD had no effect. I'm confused.
