### ISSUE TITLE
Have identifiers for dataflows

### ISSUE THREAD

**Issue by wangandi** [MaterializeInc/materialize#1720]
Currently, we have GlobalIds for database objects such as sources, views, sinks, indexes, and whatnot, but we do not have GlobalIds for individual dataflows. 

It would be useful to have identifiers for dataflows because dataflows can persist even after the original object that resulted in the dataflow being created is dropped. This is due to the fact that we re-use existing dataflows when constructing new ones.

cc: @frankmcsherry

**Comment by rjnn** [comment]
Just a note to add that while this is tagged 'good first issue', it's also scheduled for 0.2, so we plan to have this merged in a matter of weeks.

**Comment by benesch** [comment]
I'm un-nominating this as a good first issue, because I think there's some design work here that needs to be sorted out.
