### ISSUE TITLE
Measure "Get Started" latency against SLO

### ISSUE THREAD

**Issue by chaas** [MaterializeInc/materialize#17215]
This ticket tracks the current state of our "Get Started" guide latency according to https://github.com/MaterializeInc/materialize/issues/15811, until we can get all queries within their targets.

**Comment by mjibson** [comment]
Attached: screenshot for results of these targets from a few months ago, 0.32.3 release. Will update with new ones.

![perf](https://user-images.githubusercontent.com/41181/213512927-edcd57d2-69ab-409f-9767-12aac00c7d4c.png)

**Comment by mjibson** [comment]
We've re-measured and although we haven't reached the documented target SLOs, we are happy with where things are now and are moving on to other priorities.

**Comment by chaas** [comment]
@mjibson do you have the results for the most recent run that you can paste in for posterity?

**Comment by mjibson** [comment]
![image](https://user-images.githubusercontent.com/41181/219116963-2551fa39-65fe-4dec-9786-4096208e3839.png)

**Comment by chaas** [comment]
Thanks @mjibson ! This is helpful. FYI @ggnall
