### ISSUE TITLE
dbt-materialize: support `--persist-docs` config

### ISSUE THREAD

**Issue by morsapaes** [MaterializeInc/materialize#17216]
### Feature request

One of the pros of using dbt is being able to centralize and version control data model documentation. We should support the [`persist-docs`](https://docs.getdbt.com/reference/resource-configs/persist_docs) configuration so users can propagate existing metadata to Materialize (and [beyond](https://materializeinc.slack.com/archives/CURH4E75W/p1674070586817449)) as relation and column comments.

Blocked on adding `COMMENT ON` syntax (#1212).

### Reference

* [PostgreSQL syntax](https://www.postgresql.org/docs/current/sql-comment.html)
* `dbt-postgres` implementation: [`adapters.sql`](https://github.com/dbt-labs/dbt-core/blob/main/plugins/postgres/dbt/include/postgres/macros/adapters.sql) + [`catalog.sql`](https://github.com/dbt-labs/dbt-core/blob/main/plugins/postgres/dbt/include/postgres/macros/catalog.sql)

One caveat to note here is that there are no plans to support decoupling the metadata operation from `dbt run` (see [dbt Labs #4266](https://github.com/dbt-labs/dbt-core/issues/4226) and linked issues), which means that we should come up with a macro that handles refreshing the persisted metadata on-demand as a follow-up.

**Comment by SuperBo** [comment]
I want to upvote for this feature.
