### ISSUE TITLE
Maximum query length

### ISSUE THREAD

**Issue by benesch** [MaterializeInc/materialize#17218]
### Feature request

Materialize has no protection against pathologically large queries. In particular, massive queries can get written down in CockroachDB as part of a view definition. Cockroach disk space is scarce, and also we don't bill customers for their CockroachDB usage.

We should put a reasonable limit on query length ASAP. Snowflake has a 1MB limit, for example: https://docs.snowflake.com/en/user-guide/query-size-limits.html.

cc @chaas and @ggnall for triage

**Comment by chaas** [comment]
Interesting, Snowflake's limit is on the total request size, regardless of the type and number of queries. It's a client request limit vs a query character limit.

Adding the validation to
https://github.com/MaterializeInc/materialize/blob/247bbeb143da4f8e6d13802289243cc4e32c881c/src/sql-parser/src/parser.rs#L55-L58
would achieve the same outcome.
We should consider adding the validation one layer above in pgwire & http endpoint if we only wanted to validate on the initial user request.

1MB seems reasonable to me to start.
[Cockroach accepts 16MB](https://www.cockroachlabs.com/docs/stable/known-limitations.html#size-limits-on-statement-input-from-sql-clients)
I couldn't seem to find AWS's limit, but [this doc](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_PerfInsights.UsingDashboard.SQLTextSize.html) makes me think it's also 1MB for RDS Postgres.

We could use a permanent feature flag for this too if we wanted to selectively increase the limit for certain customers. Not sure if that's overkill @ggnall? Or if it's technically feasible if we put the logic in pgwire.

**Comment by ggnall** [comment]
Def! Another example: [BigQuery](https://cloud.google.com/bigquery/quotas) also uses 1mb.
>1MB seems reasonable to me to start. 

Seems like overkill to make this a environment configuration setting, but would be good to understand this question or leave a TODO/backlog item:
>Or if it's technically feasible if we put the logic in pgwire.

**Comment by benesch** [comment]
> Interesting, Snowflake's limit is on the total request size, regardless of the type and number of queries. It's a client request limit vs a query character limit.

Yeah, Snowflake's only API is HTTP. So they can get away with just having a max request size, and all the other limits are implicit consequences of that limit.

We'll probably want two limits, since we have both a SQL and HTTP API. We'll want a limit on query length, and also a separate limit on maximum request size (pgwire message size or HTTP request size). The maximum request size limit should be more than large enough to allow requests to specify a max length query _and_ some reasonably sized parameters. We want the query length limit to be the user-facing limit, and the max request size to be mostly for preventing DoS attacks.

**Comment by jkosh44** [comment]
> We'll want a limit on query length

How do you feel about this being a limit on the length of a batch of queries? Implementation wise that would be much easier.
