### ISSUE TITLE
storage,persist: consolidate the two separate `persist_sink` implementations

### ISSUE THREAD

**Issue by aljoscha** [MaterializeInc/materialize#17221]
We have both the (compute) `persist_sink` and the (storage) `persist_sink`. Consensus seems to be that it's bad that we have two very similar things.

The two are at somewhat different points of the design space by now:
 - the (compute) sink:
   - is self correcting
   - writes from multiple workers -> more write parallelism
   - it uses potentially a lot of memory because it consolidates updates in memory
   - it only writes out updates once the frontier advances and we know that corrections has "settled down"
   - needs as it's input the _full_ collection of `desired` (what should be in the output shard) and `persist` (what is in the output shard)
 - the (storage) sink:
   - writes from a single worker
   - writes updates out eagerly, no high memory usage
   - is not self correcting, bails when there is a write conflict
   - starts writing at a given frontier, without needing the full desired input, nor the current contents of the output shard

See this internal thread for some more context/colour: https://materializeinc.slack.com/archives/C01CFKM1QRF/p1674057197454209

**Comment by aljoscha** [comment]
I had a branch that attempted this (use the compute `persist_sink` in ingestion). It’s hard, because the compute sink wants to have a `desired` input that contains all updates that should be in the collection while the source will only start reading from a recent offset in Kafka.

I was working around this by feeding in (roughly) the union of `shard contents up to resumption frontier` and `new updates from source beyond resumption frontier` as `desired`. Plus, the source will have to read the current contents of the shard, to feed into the `persist` input that (compute) `persist_sink` has. It seemed like a lot of additional persist reading just to get it work.

And then there are the downsides of the (compute) sink: big memory usage, not writing out updates to the shard eagerly.

A better alternative would seem to add functionality to the (compute) `persist_sink` that allows us to start it and tell it “assume everything that is not beyond an as_of is correct, and only run your consolidation logic from there on”. But then we still have the difference in writing behaviour.

**Comment by guswynn** [comment]
@aljoscha Can I take a look at that branch?

**Comment by aljoscha** [comment]
I don't have it anymore. It was barely more than "replace `persist_sink` in storage with the other one, and hack up a `desired` to make it (apparently) work", but it didn't work.
