### ISSUE TITLE
Automated SQL fuzzing

### ISSUE THREAD

**Issue by cuongdo** [MaterializeInc/materialize#1722]
Fuzzing typically uncovers various crashes and other error conditions. We should run automatic fuzzing for Materialize's SQL dialect.

More context:

Jamie:
> libfuzzer is such a fantastic piece of software

> We have a fuzzer!

> It hasn't been maintained for a while, but it shouldn't be too bitrotted

Nikhil:
> Yeah, it continues to be built (though not run) in CI, so should be mostly working!

**Comment by cuongdo** [comment]
@ruchirK Where do we currently stand with this task?

**Comment by ruchirK** [comment]
Hey @cuongdo the code is all in place it needs some small edits in order to support Smith API changes and it still needs to be set up as a nightly job. Apologies that this has slipped through the cracks the past two weeks -- I can prioritize it this week.

**Comment by benesch** [comment]
@ruchirK have you seen https://github.com/MaterializeInc/materialize/pull/2931? That's 99% of it. Just need to dust it off.

**Comment by ruchirK** [comment]
Looking at this rn
