### ISSUE TITLE
testdrive: support automatic rewriting

### ISSUE THREAD

**Issue by teskje** [MaterializeInc/materialize#17223]
### Feature request

In contrast to other test frameworks we are using (i.e., sqllogictest and datadriven), testdrive does not support automatic rewriting of test results. This makes it particularly painful to use with tests that check `EXPLAIN` output, since every time the query plans change the expected testdrive results must be adjusted manually.

**Comment by def-** [comment]
This should be easier with Petros' https://github.com/MaterializeInc/materialize/pull/21812
