### ISSUE TITLE
doc/user: counter in numbered lists resets

### ISSUE THREAD

**Issue by morsapaes** [MaterializeInc/materialize#17238]
For numbered lists, the counter seems to randomly reset for numbered lists inside a tab group:

<img width="834" alt="Screenshot 2023-01-20 at 11 19 38" src="https://user-images.githubusercontent.com/23521087/213672087-dde703c9-6930-4a7a-a287-14a233a1aac2.png">

See [this page](https://materialize.com/docs/integrations/cdc-postgres/#database-setup) for examples.

**Comment by bobbyiliev** [comment]
I think that this is a standard thing for Markdown. In this case, the list breaks as there is a new paragraph here:
https://github.com/MaterializeInc/materialize/blob/main/doc/user/content/integrations/cdc-postgres.md?plain=1#L118

If we add 4 spaces on that line, the list should work as normal.

**Comment by morsapaes** [comment]
Errr, I totally missed that this tab group in particular had a breaking paragraph. I now realize that this is happening in the following group of tabs because there are numbered instructions common to all tabs that are _outside_ the tabs. I'll fix it! Thanks for sanity checking, @bobbyiliev.
