### ISSUE TITLE
dbt-materialize: upgrade to `dbt-core` v1.4.0

### ISSUE THREAD

**Issue by morsapaes** [MaterializeInc/materialize#17258]
### Feature request

Laundry list to upgrade `dbt-materialize` to `dbt-core` v1.4.0, based on the items from [this discussion](https://github.com/dbt-labs/dbt-core/discussions/6624) that are actionable for the adapter.

- [x] Replace deprecated exception functions (see [dbt-core #6339](https://github.com/dbt-labs/dbt-core/issues/6339), [dbt-snowflake #384](https://github.com/dbt-labs/dbt-snowflake/pull/384/files))

  `RuntimeException -> DbtRuntimeError`
  `DatabaseException -> DbtDatabaseError`
  `raise_compiler_error() -> CompilationError`

- [x] Add `TestCurrentTimestamp` and `TestCurrentTimestamps` to the test suite (see https://github.com/dbt-labs/dbt-core/pull/5838)

- [ ] ~Add `TestChangeRelationTypes` to the [test suite](https://github.com/MaterializeInc/materialize/tree/main/misc/dbt-materialize/tests/adapter) (see [dbt-core #6054](https://github.com/dbt-labs/dbt-core/pull/6054))~ Redundant.

  ~I don't fully understand the difference between the new [`test_change_relation_type.py`](https://github.com/dbt-labs/dbt-core/blob/main/tests/adapter/dbt/tests/adapter/relations/test_changing_relation_type.py) functional test and the relation type check in [`test_base.py`](https://github.com/dbt-labs/dbt-core/blob/93619a9a3761d3606d257c1274828ac4eef4f627/tests/adapter/dbt/tests/adapter/basic/test_base.py). Raised the question in the dbt community ([thread](https://getdbt.slack.com/archives/C030A0UF5LM/p1674349920711339)).~

- [x] Test Python 3.11 support
- [x] Upgrade `dbt-tests-adapter` dependency to v1.4.0

**Comment by dehume** [comment]
| Test Python 3.11 support

Tested on 3.11.0
* Updated the Dockerfile and reran the test suite which was successful
* Created a new virtual env (3.11.0) and installed the adaptor and poked around with the CLI

NOTE: In order to get this to work, I did manually update the `setup.py` to update the `dbt-postgres` version to 1.4.0. Otherwise nothing would work on 3.11

**Comment by morsapaes** [comment]
Thanks, @dehume! The upgrade PR is out in #17505.
