### ISSUE TITLE
Odd kafka issue in testdrive 

### ISSUE THREAD

**Issue by wangandi** [MaterializeInc/materialize#1725]
I can't reproduce the issue locally. It only happens in buildkite.

> CREATE SINK not_mat_sink FROM data_view INTO 'kafka://${testdrive.kafka-addr}/data-view-sink' WITH (schema_registry_url = '${testdrive.schema-registry-url}')

results in this error:

```
db error: ERROR: transport: error sending request for url (http://schema-registry:8081/subjects/data-view-sink/versions): error trying to connect: tcp connect error: Connection refused (os error 111)
```

Under circumstances for the rules for which I have not figured out. My current theory is it has to do with where in the testdrive file it is.

**Comment by sploiselle** [comment]
This flake no longer seems affect us.
