### ISSUE TITLE
Cluster unification validation

### ISSUE THREAD

**Issue by benesch** [MaterializeInc/materialize#17266]
Cluster unification (https://github.com/MaterializeInc/cloud/issues/4929) is landing piecemeal on main as we speak, in order to hit the deadline for this week's canary, but it deserves a bit of extra scrutiny before we ship the release to production.

The last remaining PR is: https://github.com/MaterializeInc/materialize/pull/17256

## Blocking work items

* [x] https://github.com/MaterializeInc/materialize/pull/17269
* [x] https://github.com/MaterializeInc/cloud/pull/5253
* [x] https://github.com/MaterializeInc/materialize/pull/17285
* [x] https://github.com/MaterializeInc/materialize/pull/17286

## Review requests

Commits not listed here are straightforward (often just renamings) that don't require extra scrutiny.

**@jkosh44**

- [x] https://github.com/MaterializeInc/materialize/pull/17265
- [x] https://github.com/MaterializeInc/materialize/pull/17256/commits/18f926e3af622a55405d1047851730fb532ad689

**@aljoscha**

- [x] https://github.com/MaterializeInc/materialize/pull/17256/commits/52d4c4d7697e743a626ec25fa19b08f32d45898f (straightforward; more of an FYI) 
- [x] https://github.com/MaterializeInc/materialize/pull/17256/commits/3c015862ab214ad7442a61f43913b102a069907e

**@teskje**

- [x] https://github.com/MaterializeInc/materialize/pull/17256/commits/e62c2c840064cd795c20942113bb8375b1b09afc

## Testing

Expecting some fallout in this nightly run: https://buildkite.com/materialize/nightlies/builds/1698

@philip-stoev please take a look at [storage-clusters.td](https://github.com/MaterializeInc/materialize/blob/a90be6fa8a567d1b1dc28556d06f8abc2286736a/test/testdrive/storage-clusters.td) and see if there is anything you'd like to add.

**Comment by jkosh44** [comment]
LGTM, but you left a TODO in one of the doc-comments:
https://github.com/MaterializeInc/materialize/commit/18f926e3af622a55405d1047851730fb532ad689#r97765403

**Comment by aljoscha** [comment]
Regarding https://github.com/MaterializeInc/materialize/commit/52d4c4d7697e743a626ec25fa19b08f32d45898f (adapter,storage: remove storage host-related views): We're leaking the shards that were backing the removed collections. We can either accept that or try and work with https://github.com/MaterializeInc/materialize/pull/17105 to get them removed properly. Not sure how feasible that is, though. cc @sploiselle

**Comment by teskje** [comment]
Changes LGTM. I sent a few cleanups in https://github.com/MaterializeInc/materialize/pull/17273, and a fix for a panic these changes caused in https://github.com/MaterializeInc/materialize/pull/17278.

**Comment by aljoscha** [comment]
I looked through all the changes and storage changes LGTM. I'm sure there might be some rough edges, but the overall shape of this looks good. Especially the last commit in step 3.6 (which unifies replica orchestration) is :chefskiss:!

I did put up a small proposal for renaming: https://github.com/MaterializeInc/materialize/pull/17279

**Comment by benesch** [comment]
> Regarding [52d4c4d](https://github.com/MaterializeInc/materialize/commit/52d4c4d7697e743a626ec25fa19b08f32d45898f) (adapter,storage: remove storage host-related views): We're leaking the shards that were backing the removed collections. We can either accept that or try and work with #17105 to get them removed properly. Not sure how feasible that is, though. cc @sploiselle

I think it's ok to just leak them. We've leaked plenty of shards in the past. 😬

**Comment by benesch** [comment]
Calling this closed, as v0.41.1 looks good in the nightlies and release qualification tests, after revert of the `halt!` purge.
