### ISSUE TITLE
Choose and document (kafka) sink guarantees

### ISSUE THREAD

**Issue by JLDLaughlin** [MaterializeInc/materialize#1728]
We don't have any right now! In particular, think about things like ordering (across topics, partitions, etc.) topic names, and duplication

**Comment by benesch** [comment]
Kicking this out of 0.4, so that we can consider 0.4 finished. (It shipped, after all.)

**Comment by ruchirK** [comment]
@umanwizard I think this is something we will have a much better handle on with CDCv2 sinks? at the moment sinks have essentially no guarantees.

I don't feel fully able to _choose_ guarantees at this point because I'm not sure what is / isn't feasible with CDCv2.

**Comment by umanwizard** [comment]
With CDCv2, reordering and duplication can be dealt with, with the caveat that this is only true if the duplicated messages are identical: i.e., if you have two Mz instances writing to the same sink, you need to make sure they are assigning the same timestamps to the same messages.

For just one writer, though, indeed CDCv2 sinks would let us solve the problem of undefined order among different partitions: the reader will be able to figure out how to put things back together in the order defined by the timestamps

**Comment by elindsey** [comment]
Adding this task to 1.0. Specifically we need to decide and document on any guarantees we want to preserve (particularly in Kafka sinks) that would affect backwards compatibility - such as whether or not we guarantee writing data in ts order.
