### ISSUE TITLE
persist: additional introspection into storage usage numbers

### ISSUE THREAD

**Issue by danhhz** [MaterializeInc/materialize#17293]
I'm quite willing to bet that persist is going to be getting a steady stream of questions that look like https://github.com/MaterializeInc/cloud/issues/5131, so I think it's worth building a bit of tooling around it. In particular, there's a "funnel" of sorts between "raw s3 usage of a shard" and "logically live data size if we were to force compaction". The ideal might be to have the steps of that funnel in metrics, but it might be easier to start with a persistcli tool that recalculates them all and dumps them out.

Roughly:
- (1) raw s3 usage
- which can be split into (2a) data not eligible for reclamation by a (future) leaked blob detector and (2b) data that IS eligible
- (2a) can be split into (3a) data that is referenced by some version of state and (3b) data that isn't
- (3a) can be split into (4a) data referenced by the most recent version of state vs (4b) data that isn't
- (4a) can be split into (5a) data in batches/parts and (5b) data in rollups
- (5a) can be split into (6a) "live" data and (6b) data that would be compacted out. (NB: Unlike the others, this one we can't easily compute without modifying the shard.)

In terms of 5131: 
- 10->100 is 6b: a compaction promptness issue tracked by #15093
- 100->300 is 3b: in this case, some still active writer created the blobs but hasn't linked them into state almost certainly due to #17292, if the environment were to restart, these would move to 2b

**Comment by danhhz** [comment]
Now that we have this structure, something we should discuss is exactly what we should be billing for. At the moment, I think we bill for (2a) but there's a good argument to be made that we should be billing for (3a) or even (4a).

**Comment by benesch** [comment]
> Now that we have this structure, something we should discuss is exactly what we should be billing for. At the moment, I think we bill for (2a) but there's a good argument to be made that we should be billing for (3a) or even (4a).

I thought we billed for (1) presently.

**Comment by hlburak** [comment]
@danhhz Thanks so much for typing this up -- the framing is really helpful! In order not to distract from a discussion on any introspection which might be needed, I've referenced this ticket in comments [here](https://github.com/MaterializeInc/cloud/issues/5132). As you can tell there, I lean towards charging at the top of this "funnel", but have a couple of questions: 
- Can you help me understand what might be contained in 2b and 3b?
- For the 10->100 issue how long are the delays in compacting are talking about?

**Comment by danhhz** [comment]
> I thought we billed for (1) presently. Based on a quick read of persist-client/src/usage.rs.

Confirming, I just re-read the code again myself and this is correct.
