### ISSUE TITLE
regression: source stops ingesting in the KafkaSourcesLarge, UserTables Zippy Scenarios after environmentd restart

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#17309]
### What version of Materialize are you using?

v0.41.0

### How did you install Materialize?

Docker image

### What is the issue?

The `KafkaSourcesLarge` release qualification test has been able to previously run for 24+ hours, but now fails in 1 hour as follows:
```
> SELECT count_all FROM sink_7_view /* expecting count_all = 37126 */ ;

^^^ +++
2:1: error: deadline has elapsed
     |
   1 |
   2 | > SELECT count_all FROM sink_7_view /* expecting count_all = 37126 */ ;
```

The reason is that this source is wedged in the past:

```
materialize=> explain timestamp for select * from "materialize"."public".sink_20_source;
                                 Timestamp                                 
---------------------------------------------------------------------------
                 query timestamp: 1674545813125 (2023-01-24 07:36:53.125) +
           oracle read timestamp: 1674545813125 (2023-01-24 07:36:53.125) +
 largest not in advance of upper: 1674501025000 (2023-01-23 19:10:25.000) +
                           upper:[1674501025001 (2023-01-23 19:10:25.001)]+
                           since:[1674501024000 (2023-01-23 19:10:24.000)]+
         can respond immediately: false                                   +
                        timeline: Some(EpochMilliseconds)                 +
                                                                          +
 source materialize.public.sink_20_source (u140, storage):                +
                   read frontier:[1674501024000 (2023-01-23 19:10:24.000)]+
                  write frontier:[1674501025001 (2023-01-23 19:10:25.001)]+
```

If the isolation level is relaxed to serializable, the query above still does not return the expected result.

Creating a fresh source using the same source definition, as taken from `CREATE SOURCE sink_20_source` causes the correct data to show up. 

The test kills and restarts storage clusterd and environmentd separately, and both were restarted just prior to the query that is timing out. There are no panics, no OOMs and no error messages in the logs as far as I could see.

To reproduce:

1. Start a `scratch` machine with the following definition:
```
pstoev@Ubuntu-2004-focal-64-minimal:~/materialize$ cat misc/scratch/ci-large.json
{
    "name": "c6a.12xlarge as used by the CI",
    "launch_script": "true",
    "instance_type": "c6a.12xlarge",
    "ami": "ami-09d56f8956ab235b3",
    "size_gb": 50,
    "tags": {}
}
```
2. Run:
```
cd materilaize/test/zippy
./mzcompose run default --scenario=KafkaSourcesLarge --actions=100000
```

and wait 1 hour or thereabout. The failure happens around action number `#1471`.

A scratch machine is available where the issue has been reproduced already.

**Comment by aljoscha** [comment]
@philip-stoev Are `clusterd` processes allowed to restart by themselves or do we strictly control when they restart?

There is one known race condition that got introduced as part of https://github.com/MaterializeInc/materialize/issues/16773: It can happen that we restart and start the reclock operator at an invalid `as_of`, though we would see a panic for that in the logs. Do you happen to still have the logs for the run?

**Comment by philip-stoev** [comment]
First seen Jan 21st here:

https://buildkite.com/materialize/nightlies/builds/1693#0185d1c1-2315-4b85-950f-e7bad3176eda

**Comment by aljoscha** [comment]
That Jan 21 one doesn't have sources, though.

**Comment by philip-stoev** [comment]
It does have sources -- it creates a sink and then a source over the sink in order to validate that the expected stuff has been emitted to the sink. This is the query that fails:

```
2 \| > SELECT count_all, count_distinct, min_value, max_value FROM sink_4_view /* expecting count_all = 472 count_distinct = 472 min_value = 16565 max_value = 17036 */ ;
```

This is a materialized view over a source from the Kafka topic emitted by a sink from a materialized view from some tables.

**Comment by philip-stoev** [comment]
@aljoscha , no the clusterd process is under the control of the test -- it kills it and then starts it shortly after. There are no panics in any of the CI and self-reproduced logs that I examined .

**Comment by aljoscha** [comment]
sorry, I was confused by the name `UserTables` compared to `KafkaSourcesLarge` ... :see_no_evil:

**Comment by guswynn** [comment]
The revert appears to have fixed the issue, the RQ test is at ~2500

Also checking the `UserTables` nightly test before merging

**Comment by teskje** [comment]
For posterity: We identified https://github.com/MaterializeInc/materialize/pull/16958 as the change that introduced this issue.
