### ISSUE TITLE
persist: update storage usage to reflect (3a)

### ISSUE THREAD

**Issue by danhhz** [MaterializeInc/materialize#17317]
In the jargon of #17293, we're currently calculating usage as (1) but we decided to switch to (3a) for now. So, we need to be able to calculate this in the usage code, which involves looking up the currently live versions of State.

**Comment by necaris** [comment]
Does this imply a change in the schema of the `mz_storage_usage_by_shard` table, or do we expect that to remain the same. Particularly interested as we query it for billing :wink:

**Comment by danhhz** [comment]
@benesch I sat down to think through the details of the implementation here and realized that, because there's no way to read a snapshot that's consistent between both s3 and crdb, there's a tradeoff to be considered. At a high level, the usage code to compute (1) is currently `O(shards)` memory. When we make it compute (3a) we can do something more correct but `O(blobs)` memory or we could do something slightly race-y but `O(shards) + O(writers)` memory.

`O(blobs)` is potentially several orders of magnitude bigger than `O(shards)` and `O(writers)` and this runs in envd, so that seems concerning to me. Plus, this is already only run once an hour, so being slightly race-y seems ~fine. However, one estimate for an upper bound on `O(blobs)` is `data stored / 128MiB` (definitely an undercount but probably the right order of magnitude) and if we make the constant small, the BOE math checks out as doable.

My guess is we'd want the smaller memory footprint, but felt like it was worth checking that conclusion. Happy to give more details if that helps!

**Comment by benesch** [comment]
> My guess is we'd want the smaller memory footprint, but felt like it was worth checking that conclusion.

Works for me, as long as we're wrong in the direction of undercounting and not overcounting!
