### ISSUE TITLE
Add indexes on common internal tables

### ISSUE THREAD

**Issue by RobinClowers** [MaterializeInc/materialize#17328]
### Feature request

In order to make our web UI faster, let's add indexes on some of the queries we are using to power it.

Some queries we are using:

Clusters:
```sql
SELECT r.id,
  r.name as replica_name,
  r.cluster_id,
  r.size,
  c.name as cluster_name,
  u.memory_percent
FROM mz_cluster_replicas r
JOIN mz_clusters c ON c.id = r.cluster_id
JOIN mz_internal.mz_cluster_replica_utilization u ON u.replica_id = r.id
ORDER BY r.id;
```

Sources / sinks (same query except for the table names:
```sql
SELECT s.id, s.oid, s.name, s.type, s.size, st.status, st.error
FROM mz_sources s
LEFT OUTER JOIN mz_internal.mz_source_statuses st
ON st.id = s.id
WHERE s.id LIKE 'u%
```

Source / sink errors (same query except for the table names:
```sql
SELECT MAX(extract(epoch from h.occurred_at) * 1000) as last_occurred, h.error, COUNT(h.occurred_at)
FROM mz_internal.mz_source_status_history h
WHERE source_id = $1
AND error IS NOT NULL
AND h.occurred_at BETWEEN $2 AND $3
GROUP BY h.error
ORDER BY last_occurred DESC
LIMIT ${limit};
```

**Comment by chaas** [comment]
This is merged! I didn't make the Thursday release cutoff, so this won't go out until the week of 10/16.

**Comment by RobinClowers** [comment]
Awesome, thanks for taking care of it! Did you have a chance to upgrade your staging environment and that version to see the memory usage?

**Comment by chaas** [comment]
Oh oops I posted this on the wrong index ticket sorry...let me move my comment to the right one https://github.com/MaterializeInc/materialize/issues/21858
