### ISSUE TITLE
Allow mocking out system timestamp for audit events purposes

### ISSUE THREAD

**Issue by necaris** [MaterializeInc/materialize#17331]
## Motivation
The main consumer of the audit events table is our billing system. Validating our billing ahead of launch has been a multi-week process and while we are confident that our billing is correct right now, we will need ongoing automated regression testing to have that confidence over the long term.

The existing billing tests are both hard to update and not protective enough. The tests run against PostgreSQL, not Materialize and therefore risk missing real bugs in the interaction between the usage exporter and Materialize, or in Materialize itself.

We have a [proposed design for a v2 test harness](https://github.com/MaterializeInc/cloud/issues/5155) that will make it easier to update the test assertions in the case of desirable changes, and also provide nearly end-to-end coverage of the whole pipeline.

A key requirement for this pipeline to work without waiting for real time to elapse is the ability mock out the system timestamp in `mz_audit_events` records. Using this capability, we could create test cases with precise control over the timestamps of records, enabling us to efficiently test numerous aspects of the usage exporter that converts raw `mz_audit_event` rows into metering data.

## Proposal

We should be able to mock out the system timestamp oracle, for the purpose of comprehensively testing audit events. Suggested implementation, after conversing with @benesch:

- Add a system parameter whose value is the overridden timestamp, and which can be set with `ALTER SYSTEM`. For example, `ALTER SYSTEM SET audit_timestamp_override 1699284893`
- In the audit log write path, if this parameter is set, use its value as the timestamp; otherwise use the system timestamp oracle

**Comment by necaris** [comment]
Note we'd be happy to put up a draft PR if that would be helpful here!

**Comment by necaris** [comment]
cc @mjibson @jkosh44

**Comment by necaris** [comment]
cc @benesch

**Comment by benesch** [comment]
Thanks, @necaris! Going to signal boost this request in #team-surfaces.

**Comment by mjibson** [comment]
Would this be enabled only for unsafe mode, or do we need it running in staging/prod for some reason? If only behind unsafe: no concerns.

**Comment by jkosh44** [comment]
> In the audit log write path, if this parameter is set, use its value as the timestamp; otherwise use the system timestamp oracle

Would the audit log continue using the same timestamp every time until it is changed/reset, or will the value be automatically reset after it is used once?

**Comment by necaris** [comment]
> Would the audit log continue using the same timestamp every time until it is changed/reset, or will the value be automatically reset after it is used once?

To minimize complexity in the implementation itself, I think it's reasonable to leave it to the surrounding test code to correctly update the override timestamp, and not build any intelligence into that code path?

**Comment by benesch** [comment]
Agreed—I think it's preferable to have the audit log use the timestamp until it's changed/reset.
