### ISSUE TITLE
Use of `give_vec` does not preserve intended initial capacity of operator buffer

### ISSUE THREAD

**Issue by vmarcos** [MaterializeInc/materialize#17359]
### What version of Materialize are you using?

v0.42.0-dev (9cf94f01c)

### How did you install Materialize?

Built from source

### What is the issue?

In PR #17345, it has been observed that `give_vec` will internally perform a `std::mem::take`, thus resetting the capacity of the provided buffer to zero. This behavior may not be desired in operators that wish to employ a buffer with a given capacity. In the referred PR, `ConsolidateBuffer` was an example of a buffer implementation that performed update consolidation internally and had this problem.

Upon surveying the codebase by [this suggestion](https://github.com/MaterializeInc/materialize/pull/17345#pullrequestreview-1270917375), the following use of the same pattern was found in `persist_source`: https://github.com/MaterializeInc/materialize/blob/34b79afcbb2eab59630b8c37ebb9fa6078dfe110/src/storage-client/src/source/persist_source.rs#L187-L188 followed by https://github.com/MaterializeInc/materialize/blob/34b79afcbb2eab59630b8c37ebb9fa6078dfe110/src/storage-client/src/source/persist_source.rs#L246 and https://github.com/MaterializeInc/materialize/blob/34b79afcbb2eab59630b8c37ebb9fa6078dfe110/src/storage-client/src/source/persist_source.rs#L263
This issue is a request to ensure that the buffer capacity is reinstated after `give_vec` (e.g., by calling `reserve_exact` as in PR #17345 or employing `ConsolidateBuffer` if adequate), assuming that is what was intended by the original code.

**Comment by danhhz** [comment]
Hey @antiguru, in https://github.com/MaterializeInc/materialize/pull/17156 you replace these two give_vec calls with... _drumroll_ ... ColsolidateBuffer! Should we go ahead and get that merged?

**Comment by antiguru** [comment]
I'll spend some time on #17252 today so we can get it over the finish line. It's a different take on #17156.

**Comment by antiguru** [comment]
Fixed by #17252.
