### ISSUE TITLE
One-off SELECTs are almost monotonic

### ISSUE THREAD

**Issue by ggevay** [MaterializeInc/materialize#17358]
For one-off select queries, the inputs are _almost_ monotonic, because no (positive or negative) changes will come later at all. But not quite, because the input data might be non-consolidated. (For which sources can this happen? All of them?) However, adding a `consolidate` call often incurs less cost than the difference between a monotonic and non-monotonic operator (e.g., TopK). Therefore, we should consider adding some `consolidate` calls in one-off selects.

The added `consolidate` call could come right before an operator that can benefit from monotonicity, or in some cases it might be better to put it at the sources (if the sources are smaller and there is no such operator in-between that would destroy the monotonicity). But as long as we don't have cost-based optimization or cardinality estimates, it seems ok to just put it right before the relevant operators.  

Originally suggested here:
https://materializeinc.slack.com/archives/C02PPB50ZHS/p1674496250784249

There is an old draft PR which partially solves this: https://github.com/MaterializeInc/materialize/pull/14607

Keep in mind https://github.com/MaterializeInc/materialize/pull/14607#issuecomment-1236394599, i.e., that in a snapshot setting even a `Reduce` has a monotonic _output_. So a snapshot situation is even better than simply having monotonic inputs. (Btw. window functions could make use of this also: for a one-off SELECT, we could use the naive, non-incremental rendering.)

**Comment by tokenrove** [comment]
Possibly #17437 could make this easier?

**Comment by ggevay** [comment]
Is https://github.com/MaterializeInc/materialize/issues/14351 essentially the same issue?

**Comment by vmarcos** [comment]
I think that a full solution to this issue that inserts the consolidation only when necessary will be achieved when we fix #18732?
