### ISSUE TITLE
Issue a notice, or don't allow, running sources and sinks on a 2xlarge replica or larger

### ISSUE THREAD

**Issue by sjwiesman** [MaterializeInc/materialize#17367]
### Feature request

Post cluster unification, sources and sinks may be executed on replicas of any size. However, they only leverage one process of a multi-process timely cluster. That means running a replica of 2xlarge or above wastes resources and money. We can solve this problem, but it needs to be worked on. 

In the meantime we should help users by either: 

- not allowing 2xlarge replicas or above on clusters containing sources or sinks
- issue a notice

**Comment by guswynn** [comment]
At this point we would need a migration to disallow this now that `IN CLUSTER` is in production, but that might be worth it!

**Comment by sjwiesman** [comment]
I just checked grafana, no one is running sources on a 2xlarge or above replica today, and I'd be shocked if anyone does in the short term without me knowing, so we can probably avoid the migration :) 


But I'm also fine with a notice if we think that's better!

**Comment by benesch** [comment]
> I'd be shocked if anyone does in the short term without me knowing

It's also default disallowed on environments. You've got to override via LaunchDarkly. So no immediate possibility of this happening!

**Comment by benesch** [comment]
I think it would be not that much more work to just support sources/sinks on horizontally scaled replicas (#17419). Unless enabling that feature turns out to be trickier than expected, would love to invest the energy there, instead of in improving the disabled UX.

**Comment by sjwiesman** [comment]
@guswynn can we close this issue as not necessary?

**Comment by guswynn** [comment]
Not necessary! The next release lifts this limitation!
