### ISSUE TITLE
storage: make use of horizontally scaled replicas

### ISSUE THREAD

**Issue by benesch** [MaterializeInc/materialize#17419]
### Feature request

*Part of the multipurpose clusters epic (#17413)*.

Creating a source or sink on a horizontally scaled cluster replica (2xlarge+) is permitted, but the source/sink does not actually make use of the bigger size. The source/sink is scheduled onto only the first process in the cluster replica.

We could fix this quickly by:

  1. Adjusting `clusterd`'s command-line arguments to allow constructing a multi-process timely cluster for storage.
  2. Teaching the storage controller to partition commands across the multiple processes in the replica.

But we might prefer to instead unify the timely clusters first (#17416), in which case we'd get horizontally scaled support "for free", by piggybacking on the compute protocol's support for initializing multi-process compute timely clusters.

See also #17367, which tracks adding a notice or disabling creating sources/sinks on horizontally scaled replicas in the meantime.

**Comment by guswynn** [comment]
Its a bit more complicated than the quick fix; we certainly could hack something together, but ultimately there is a significant amount of accounting required on the server and client side to make multi-machine clusters work as expected.

That said, doing it correctly basically boils down to "make all the `CreateTimely` stuff in compute generic and use it in storage, which *I think* doesn't require too much extraction. Luckily, that kind of change overlaps _perfectly_ with the first steps we want to do in service of https://github.com/MaterializeInc/materialize/issues/17416

**Comment by benesch** [comment]
What makes the quick fix complicated?

**Comment by guswynn** [comment]
@benesch There is no intrinsic complexity, just a lot of code that needs to be made generic (mostly in `mz_compute::server` and moved around! What I meant was there was no way around some amount of that code movement!

**Comment by benesch** [comment]
Hmm, I was envisioning the quick fix as making `clusterd` accept the addresses of the other `clusterd`’a storage timely ports as command line arguments, and using those to initialize a multiprocess storage timely cluster _in addition_ to the multiprocess compute cluster. Initializing the timely cluster via CLI arguments is how `computed` used to work, and it seems like a reasonable quick fix for this, since we don’t expect it to last long.

Maybe I’m not up to speed on your and Moritz’s proposals, but making the `CreateTimely` command generic is surprising to me! I was envisioning the unified command protocol as something like:

```rust
enum Command {
    InitializeTimely { … },
    Storage(StorageCommand),
    Compute(ComputeCommand),
}
```

**Comment by guswynn** [comment]
@benesch What I ended up doing is somewhere in between:
- Add a `CreateTimely` variant to `StorageCommand`
- Merge the way storage and compute servers are setup (this basically amounts to: "get `ClusterClient` to work with storage)
- Drop `connect_partitioned` into `mz_storage::controller::rehydration`

In https://www.notion.so/materialize/ComputeState-StorageState-Unification-f8139794f9e449408ecd5244f4ae814b we decided to wait on merging the command streams, as the compute team (and really, the storage team) is more comfortable with an iterative approach. I also think the path I chose is the path of least resistance, as the maximal amount of code can be used, but it does mess with some tests, for example:

https://github.com/MaterializeInc/materialize/blob/main/test/zippy/mzcompose.py#L39 needs to turn into a `WORKERS = 4` here: https://github.com/MaterializeInc/materialize/blob/main/test/zippy/mzcompose.py#L125
