### ISSUE TITLE
Add option to make `demo/http_logs` more interactive

### ISSUE THREAD

**Issue by sploiselle** [MaterializeInc/materialize#1742]
In creating documentation for `demo/http_logs`, I've found that the "automatically do everything" nature of the demo is very convenient, but makes it hard to provide users an opportunity to interact with Materialize in a hands-on way.

I'd love for an option that:
- Does not run `demo/http_logs/cli/setup.sh`
- Provides a tool that outputs the server logs to the user's terminal

@umanwizard Would an extension to the tool like this be feasible to add?

**Comment by morsapaes** [comment]
Closing as stale.

**Comment by umanwizard** [comment]
> it's unlikely I'll get to it this week

I wasn't wrong here ...
