### ISSUE TITLE
storage: create sources/sinks in active cluster by default

### ISSUE THREAD

**Issue by benesch** [MaterializeInc/materialize#17420]
### Feature request

*Part of the multipurpose clusters epic (https://github.com/MaterializeInc/materialize/issues/17413).*

Right now, creating a source/sink without specifying `IN CLUSTER` or `WITH (SIZE = ...)` is prohibited:

```
CREATE SOURCE src FROM KAFKA ...;
error: SIZE option is required
```

Once #17659 is complete, users will be able to seamlessly mix and match sources, sinks, indexes, and materialized views on clusters of any size and replication factor. At that point, we should default to creating sources/sinks on the active cluster, if no `IN CLUSTER` and no `SIZE` option is explicitly specified.

We could in theory make this change immediately. But the getting started UX will be very confusing before those issues are complete. E.g., running `CREATE SOURCE` would turn the `default` cluster into a sources/sinks cluster, and then users would probably be confused when they later run `CREATE INDEX` and get told they can't create an index on a cluster containing sources/sinks.

**Comment by sploiselle** [comment]
Should this behavior depend on the state of `enable_unified_clusters` or should we remove the flag?

**Comment by benesch** [comment]
Let's remove the flag, since it's enabled across the board!

**Comment by sploiselle** [comment]
@benesch Do you know if there's a strongly principled reason we don't delete user clusters when resetting materialize's state in testdrive? We delete the materialize catalog which approximately drops everything that could be running on the clusters, but we leave the clusters themselves chilling. Implementing the feature described in this ticket means we end up creating a lot more clusters than we did before and managing them is annoying––would be easier to just reset the set of clusters present, as well.

**Comment by benesch** [comment]
No, in fact I think it’s a bug that we leave those clusters around. I think we just never thought to update testdrive to drop clusters when we added clusters to Materialize last year.
