### ISSUE TITLE
LIR planning should return a more descriptive error

### ISSUE THREAD

**Issue by ggevay** [MaterializeInc/materialize#17446]
`Plan::from_mir` returns `Result<(Self, AvailableCollections), ()>`. It should return a more descriptive error than `()`. (Even just a string would already be better.) Btw. it seems that currently the only case when it returns an error is when a join is Unimplemented.

The coordinator currently unwraps this error (in `finalize_dataflow`), but maybe we should cleanly report it to the user instead.

Also, as @tokenrove noted, we currently unconditionally grow the stack there, and maybe it's about time we also replace that with potentially throwing `RecursionLimitError`. 

For more discussion, see
https://materializeinc.slack.com/archives/C02PPB50ZHS/p1675118575725109
- Especially, check https://materializeinc.slack.com/archives/C02PPB50ZHS/p1675180922478749?thread_ts=1675118575.725109&cid=C02PPB50ZHS before starting work on this.

**Comment by teskje** [comment]
This was fixed in #17456. `Plan::from_mir` returns a `String` error now, which seems fine since only a single error is returned.

> Also, as @tokenrove noted, we currently unconditionally grow the stack there, and maybe it's about time we also replace that with potentially throwing RecursionLimitError.

There is a large comment now explaining that we don't want to do this because adapter can't deal with errors at this point anyway.
