### ISSUE TITLE
Infer and Record Debezium Source from Connection 

### ISSUE THREAD

**Issue by heeringa** [MaterializeInc/materialize#17451]
### Feature request

Materialize cannot currently identify any upstream source arriving via Kafka + Debezium.  This feature request asks to infer the upstream source and record it durably in a system table.  Having this information gives us better insight into the customer and their use cases both for support and analytics.

**Comment by benesch** [comment]
Copying over some of my thoughts from Slack:

> To expose [this] in the system catalog we’d need to infer [the upstream source type] at plan time based on the Avro schema in the schema registry. (E.g., if the `source.lsn` field is present, it’s a PostgreSQL upstream.) Doable, but a little gnarly. You’d hope to be able to actually read the value of `source.connector`, but we don’t have access to the actual messages in the topic at the time we populate the system catalog (and in fact there might not be any messages in the topic, for an empty table).

**Comment by benesch** [comment]
We haven't had further requests for this in a while, so going to close as stale!
