### ISSUE TITLE
storage: demux postgres subsource errors

### ISSUE THREAD

**Issue by aljoscha** [MaterializeInc/materialize#17490]
**edit** hijacking this issue to track work on demultiplexing subsource errors, which was first mentioned in this original issue.

Currently, when you drop a table that is being ingested by a source we don't report anything back to the user. The (subsource) table is still queryable in Materialize as of the last time we got updates/the table still existed.

Instead, we should report an error in `mz_source_status_history`/`mz_source_status`, and prevent queries of the table by reporting back an error.

Some nuance: I think it is good if we only "wedge" the individual subsource/Table and not the entire Postgres source. This would make things repairable once we add support for adding/dropping tables to a Postgres source via `ALTER SOURCE ` (#15832).

**Comment by sploiselle** [comment]
To do this, we want to demux/partition the error stream from the reclock operator in the same way that we do the data/OK stream. The output of errors from source will then also need to mirror the way we output data, which includes the output index.

However, we also want to propagate any errors from the primary source into the subsource error streams. This lets subsources error independently of one another, while letting the primary source’s errors propagate to all of the subsources. I believe this should be tractable with a passthrough from the primary source error stream into each subsource error stream.

We then also need to break out subsources into their own rows in mz_source_statuses, which I also think will be a nice ergonomic improvement.

I think once this is in place, we’ll also be much better situated to handle #15832.

As a high-level approach, wdyt @aljoscha @petrosagg ?

**Comment by aljoscha** [comment]
I'm easily convinced to just drop this, yes. Did we talk to product/devex/field eng? (@morsapaes @sjwiesman)

**Comment by sploiselle** [comment]
I believe this is more-or-less akin to #17595 but for letting users drop tables without wedging the entire source--seems like a meaningful improvement to PG source's ergonomics and not that much work.

**Comment by sploiselle** [comment]
Maybe this could be better positioned as simply "demultiplexing subsource errors," e.g. if one of your tables produces an error (e.g. schema change), there's no need to propagate the errors to the other tables. I think that's a meaningful ergonomic improvement, but curious about @MaterializeInc/devex 's opinions here

**Comment by morsapaes** [comment]
Not wedging the whole source if a table is dropped upstream would definitely be a meaningful ergonomic improvement! Having the subsource be queryable instead of throwing an error is a surefire way for users to not realize that the table was dropped upstream and is no longer receiving updates (for larger organizations, the owner of the PostgreSQL database will usually not be the team setting up or using the replicated data).

> We then also need to break out subsources into their own rows in mz_source_statuses, which I also think will be a nice ergonomic improvement.

+1

@aljoscha, related: should we add truncation handling to the epic? This should have a similar behavior to the change proposed here (_i.e._ make an upstream table truncation not wedge the whole source), and is also unsolved for Kafka sources using the Debezium envelope (#6596).

**Comment by heeringa** [comment]
Agree it's an ergonomic improvement -- would love for @chaas or @ggnall or @RobinClowers to weigh in on the downstream effects of subsource error tracking and reporting in the console.

**Comment by aljoscha** [comment]
@sploiselle Which errors do even show up in `mz_source_status_history`? I had imagined that it's mostly (only?) whole-source-level errors, such as connection issues and the like, and errors like truncation or a table being removed don't show up there, so it's easy to route them to the subsource/table, and wedge that one.

**Comment by sploiselle** [comment]
@aljoscha Any subsource error, e.g. if I add a column to a table in PG:

```
select source_id, error from mz_internal.mz_source_status_history;
 source_id |                                                        error                                                         
-----------+----------------------------------------------------------------------------------------------------------------------
 u4        | 
 u4        | 
 u4        | failed during initialization, must be dropped and recreated: source table pk_table with oid 2421290 has been altered
```

In my proposed design, only whole source level errors would show as an error for the source itself, and this kind of error would only show for the subsource (where we would also have a new row here for each of the source's subsources).

**Comment by RobinClowers** [comment]
@heeringa thanks for tagging me. Currently Console doesn't query for subsource errors, so we would need to update our query to include those, but it's a pretty straightforward change. If we decide to move for forward with this I can make that change right away, just let me know.

**Comment by sploiselle** [comment]
Don't have any tests yet, but have a feature branch https://github.com/sploiselle/materialize/tree/pg-subsource-errors
