### ISSUE TITLE
environmentd: slow OOM with debug tracing enabled

### ISSUE THREAD

**Issue by mjibson** [MaterializeInc/materialize#17497]
In staging I have an envd pod with tracing enabled (`--opentelemetry-enabled=true` added to the statefulset cli args). Should be using the default tracing filter which is `tokio_postgres=info,debug`. The envd pod now ooms a few times per day:

![image](https://user-images.githubusercontent.com/41181/216420860-de3f058f-d965-4e28-b476-1f20f46fed6b.png)

The memory profiler flamegraph shows, widest points around 250MB:

![image](https://user-images.githubusercontent.com/41181/216421164-508be027-6987-4fc3-9091-569bb707d11a.png)

This suggests that the tracing infra is causing this. We'd like to [enable infoby default](https://github.com/MaterializeInc/materialize/issues/17392). Although this isn't info, still probably good to understand if/why tracing is leaking memory.

**Comment by mjibson** [comment]
Another:

![screenshot_2023-02-20_at_11 09 34_720](https://user-images.githubusercontent.com/41181/220208167-4eee42d4-7a26-4a16-a5ca-6c2fb004391b.png)

**Comment by parker-timmerman** [comment]
Update, we discovered what was causing the OOM, tl;dr long running Spans don't flush their events, and just continuously eat memory as more gets logged (see [slack](https://materializeinc.slack.com/archives/C032AKCA1RA/p1677879715464429) for more discussion). Thanks for the help on this @guswynn!

The plan right now is to get https://github.com/MaterializeInc/tracing/pull/1 merged, which allows us to set a max for the number of events recorded to a single span.

When testing locally using that PR and setting a max of 512, the memory usage of `environmentd` stabilizes around 97MB for the entire process, and persistent allocations of `otel::Event`s stabilizes around 1MB (as measured by Instruments)
