### ISSUE TITLE
`TopK` query prevents selection pushdown

### ISSUE THREAD

**Issue by sthm** [MaterializeInc/materialize#17515]
### What version of Materialize are you using?

v0.42.2 (705f463eb)

### How did you install Materialize?

Materialize Cloud

### Schema
```
                          Table "public.bids"
   Column   |           Type           | Collation | Nullable | Default 
------------+--------------------------+-----------+----------+---------
 id         | bigint                   |           | not null | 
 buyer      | bigint                   |           | not null | 
 auction_id | bigint                   |           | not null | 
 amount     | integer                  |           | not null | 
 bid_time   | timestamp with time zone |           | not null | 

                       Table "public.auctions"
  Column  |           Type           | Collation | Nullable | Default 
----------+--------------------------+-----------+----------+---------
 id       | bigint                   |           | not null | 
 seller   | bigint                   |           | not null | 
 item     | text                     |           | not null | 
 end_time | timestamp with time zone |           | not null | 
```

### Query

The example query is adapted from here: https://www.notion.so/materialize/Auction-House-a2d43a0ef1104007a9987a4c74d521a0

```
EXPLAIN SELECT * FROM highest_bid_per_auction WHERE end_time < mz_now() AND auction_id < 10;
                                 Optimized Plan                                  
---------------------------------------------------------------------------------
 Explained Query:                                                               +
   Project (#2, #0, #1, #5, #6, #3, #4, #7)                                     +
     Filter (#2 < 10) AND (timestamp_tz_to_mz_timestamp(#7) < mz_now())         +
       TopK group_by=[#2] order_by=[#3 desc nulls_first] limit=1 monotonic=false+
         Project (#0..=#4, #6..=#8)                                             +
           Filter (#4 < #8)                                                     +
             Join on=(#2 = #5) type=differential                                +
               ArrangeBy keys=[[#2]]                                            +
                 Get materialize.public.bids                                    +
               ArrangeBy keys=[[#0]]                                            +
                 Get materialize.public.auctions                                +
 
(1 row)
```

### Problem

It seems like the `TopK` query prevents the pushdown of the `Filter`. I would have expected that the filter conditions `(#2 < 10)` and `(timestamp_tz_to_mz_timestamp(#7) < mz_now())` are applied before the `Join` and `ArrangeBy` to eagerly filter out tuples that cannot contribute to the answer of the query.

Is this intentional or is there room to improve the query optimizer?

**Comment by frankmcsherry** [comment]
Filter pushdown would not generally be correct, as e.g. `timestamp_tz_to_mz_timestamp(#7) < mz_now()` should (according to the query) be applied after the `LIMIT 1` in the view. The greatest amount should be determined, and then filtered if its time has expired. If you push down the filter you expire the data first, and instead pick the largest remaining amount, which is different.

It should be possible, I think, to push down filters on expressions supported by the `TopK` key. I'm not certain why that doesn't happen.

**Comment by sthm** [comment]
That's a good point. You are right, it's not possible to push down the filter on the timestamp. But the mystery why the condition on `auction_id` is not pushed down remains. Removing the temporal filter does not change the behaviour.

```
EXPLAIN SELECT * FROM highest_bid_per_auction WHERE auction_id < 10;
                                 Optimized Plan
---------------------------------------------------------------------------------
 Explained Query:                                                               +
   Project (#2, #0, #1, #5, #6, #3, #4, #7)                                     +
     Filter (#2 < 10)                                                           +
       TopK group_by=[#2] order_by=[#3 desc nulls_first] limit=1 monotonic=false+
         Project (#0..=#4, #6..=#8)                                             +
           Filter (#4 < #8)                                                     +
             Join on=(#2 = #5) type=differential                                +
               ArrangeBy keys=[[#2]]                                            +
                 Get materialize.public.bids                                    +
               ArrangeBy keys=[[#0]]                                            +
                 Get materialize.public.auctions                                +

(1 row)
```

**Comment by ggevay** [comment]
Nice catch @sthm!

We should add a case to this `match`: https://github.com/MaterializeInc/materialize/blob/d41f2be9ac6853ac4281d0176deb6e01e536dd1a/src/transform/src/predicate_pushdown.rs#L161 for `MirRelationExpr::TopK`. (And we should check that the filter expression is supported by the TopK key, as Frank wrote.)

**Comment by aalexandrov** [comment]
We are also not pushing the filter through `Threshold`, which at first glance also seems safe (filtering based on an arbitrary predicate and then filtering based on the `diff` field (`diff > 0`) should be the same than if we do this in the opposite order.

**Comment by aalexandrov** [comment]
Also, I'm not sure why we're not pushing predicates behind `ArrangeBy`...

**Comment by ggevay** [comment]
> Also, I'm not sure why we're not pushing predicates behind ArrangeBy...

I think it's because `ArrangeBy` is sometimes a marker that the stuff directly below it is already arranged, and if a Filter comes below it then it would rearrange after filtering.

**Comment by aalexandrov** [comment]
> > Also, I'm not sure why we're not pushing predicates behind ArrangeBy...
> 
> I think it's because `ArrangeBy` is sometimes a marker that the stuff directly below it is already arranged, and if a Filter is moved below it then it would rearrange after filtering.

Ah, yes. But if we use it exclusively as an a marker for creating an arrangement at rendering time this won't be an issue, right?

**Comment by frankmcsherry** [comment]
I don't think we exclusively use it for this though, at the moment. For example, I think we put an `ArrangeBy` around a `Reduce` if we expect to use its output in arranged form. It is an enforcer, but the expectation is that it is a logical no-op; moving a `Filter` between the `ArrangeBy` and `Reduce` would introduce a new arrangement.

**Comment by aalexandrov** [comment]
> It should be possible, I think, to push down filters on expressions supported by the `TopK` key. I'm not certain why that doesn't happen.

#17521 is adding support for that.

Generalizing this even further, I think it should be possible to push down filters on expressions that are functionally determined by the `TopK` key. This will unblock the example in this issue, where `auction_id → end_time` is a functional dependency because `auction_id` is a key in `auctions`.

```text
explain with(keys) select * from accounts
+--------------------------------------------------------+
| Optimized Plan                                         |
|--------------------------------------------------------|
| Explained Query:                                       |
|   Get materialize.public.accounts // { keys: "([0])" } |
+--------------------------------------------------------+
```

**Comment by frankmcsherry** [comment]
> I think it should be possible to push down filters on expressions that are functionally determined by the `TopK` key.

Another take is that we should be able to push the `TopK` and `Filter` through the `Join`. It seems to fall under reduction pushdown, admittedly not with our `Reduce` operator but instead with other group-wise operators that match the join key.

I don't think this subsumes the functional dependence thing, but if one were to hand-write the query above it would be a `TopK` around the `bids` and filters around the `auctions`.
