### ISSUE TITLE
Debugging tools for SQL

### ISSUE THREAD

**Issue by jamii** [MaterializeInc/materialize#1752]
* [x] new output format
* [x] EXPLAIN TYPED
* [x] EXPLAIN VIEW
* [x] EXPLAIN DECORRELATED/OPTIMIZED
* [x] EXPLAIN RAW
* [ ] EXPLAIN EXECUTE
* [ ] EXPLAIN ANALYZE

---

Debugging planning bugs is currently difficult. My workflow for https://github.com/MaterializeInc/materialize/issues/1708 was:

* insert `println!("{}", expr.pretty())` in various places and recompile
* copy tests into a psql repl
* copy debug output into an editor
* edit out irrelevant noise
* hand execute the plan

The last part is particularly painful, because the non-optimized plans for even mildly complex queries can be several screen widths and require constant scrolling up and down to match identifiers to definitions.

Here are some initial ideas for better tooling.

## better pretty

The current format gets too wide to view and is default to follow by hand because it's printed top-down rather then in the order that data flows through it. Here's a tiny example:

```
Join {
  variables: [[(0, 1), (1, 0)]],
  Get { l11 },
  Union {
    Get { l24 },
    Map {
      scalars: [null],
      Union {
        Negate { Distinct { group_key: [#0], Get { l24 } } },
        Get { l12 }
      }
    }
  }
}
```

Instead, let's print the plan nodes bottom-up and left-to-right - the order that matches the dataflow.

```
<0> = Get l24
<1> = Distinct ^ [#0]
<2> = Negate ^
<3> = Get l12
<4> = Union <2> ^
<5> = Map ^ [null]
<6> = Get l24
<7> = Union ^ <5>
<8> = Get l11
<9> = Join [^ <7>] [[(0, 1), (1, 0)]]
```

Nodes are referred to by number (eg `<4>`), except in the common case of referring to the previous node which is just `^`.

We can maybe even syntax highlight this using terminal codes if psql supports them.

An extra advantage of this is that it's now easy to annotate nodes with extra information eg

```
<0> = Get l24
  names = a, b, _
  type = i32, str?, str
  keys = [0, 1]
<1> = Distinct ^ [#0]
  ...
```

Indenting the annotation means that most editors can easily code-fold them away.

## more explain

I propose extending `explain` syntax to:

`explain analyze? execute? typed? (correlated | decorrelated | optimized)? plan for (select ... | view view-name)`

## typed

This would produce the example types above. It would help track down where types get lost or mangled.

## correlated | decorrelated | optimized

These are the most obvious parts of the pipeline to expose - between planning and decorrelation, between decorrelation and optimization, between optimization and rendering. The default would be `optimized`.

## analyze

`analyze` (named after similar postgres command) would annotate nodes with info about differential arrangements:

```
<9> = Join [^ <7>] [[(0, 1), (1, 0)]]
  arrangement = u53
  live_records = 12
  uncompacted_records = 13000
  memory_usage = 14_000_000 bytes
```

This would be pretty useful to users too, for debugging high memory usage.

This requires being able to track arrangement ids back to plans which we don't currently support.

This would probably only work with `optimized` and `view view-name`.

## execute

`execute` would run the plan through a simple interpreter and annotate the plan nodes with their results.

```
<9> = Join [^ <7>] [[(0, 1), (1, 0)]]
  output = ("a", "b", 0), ("a", "c", 1)
```

I do this by hand a lot for debugging to locate where in the plan mistakes are introduced.

Having interpreters for both plan types also gives us great leverage for fuzzing, since we can compare results before and after each stage.

**Comment by aalexandrov** [comment]
Closing this, this will be revisited as part of #13137.
