### ISSUE TITLE
storage: bound size of `mz_*_status_history`

### ISSUE THREAD

**Issue by aljoscha** [MaterializeInc/materialize#17548]
We currently never remove entries from `mz_*_status_history` (`mz_source_status_history` and `mz_sink_status_history`) which could become problematic with sources/sinks that are stuck in a very fast restart-loop. With non-restarting sources, this would also become a problem sooner or later.

We should add a periodic task to the storage controller that emits retractions for old entries (with configurable retention), such that they can "fall out" of the collection/shard once compaction catches up to the original update and the retraction.

**Comment by aljoscha** [comment]
cc @ggnall because this affects what we present to users.
cc @bkirwi who originally added this. Maybe you have opinions/thoughts?

**Comment by bkirwi** [comment]
Only that this is the same problem as eg. https://github.com/MaterializeInc/cloud/issues/3716 and we should probably share a solution, whatever it is!

**Comment by ggnall** [comment]
Noting that the current UI lets users view a maximum history of 30 days of source/sink errors. That was arbitrary but works from a UX standpoint.

I see a note in [cloud#3716 ](https://github.com/MaterializeInc/cloud/issues/3716):
>We only need x number of days of records (per @hlburak at least 60), and after that we can delete rows outside that threshold.

@hlburak - can you give us some more insight into that minimum requirement?

**Comment by hlburak** [comment]
60 days is the number product and operations agreed represented a minimum time frame to keep around any records we might need in a billing dispute or audit back in September. But it seems like the [new consensus for keeping around usage records is 14 months](https://github.com/MaterializeInc/cloud/issues/5142#issuecomment-1385496948) as a very safe number. 

I think it makes sense to align records of inputs to usage records with the usage record lifecycle policy, but since we don't explicitly bill for sources and sinks and source/sink health does not impact bills, it's not clear to me that alignment is warranted here, especially if there are performance or cost tradeoffs.

**Comment by benesch** [comment]
> I think it makes sense to align records of inputs to usage records with the usage record lifecycle policy, but since we don't explicitly bill for sources and sinks and source/sink health does not impact bills, it's not clear to me that alignment is warranted here, especially if there are performance or cost tradeoffs.

Agreed. And keeping around 14mo of this data would be potentially very expensive. If a source/sink is stuck in a tight resource loop and emitting about one record a second, that's ~100k rows in the table per day, which adds up real fast.

**Comment by aljoscha** [comment]
We should wait for https://github.com/MaterializeInc/materialize/issues/18823 to resolve before tackling this one.

**Comment by benesch** [comment]
Mentioned this to @dseisun-materialize, but I'm worried #18823 will take a very long time to resolve. It might be worth just adding the logic to prune this table on startup, and tackle the question of whether we want to change the representation of this sort of historical data in the future.

**Comment by benesch** [comment]
This in theory got done in https://github.com/MaterializeInc/materialize/pull/19060, but it looks like we don't have a test for the truncation. We should write a test before closing this issue.

Does @MaterializeInc/qa have spare bandwidth to help test this?

**Comment by def-** [comment]
Yes, I'll add a test for this.

**Comment by benesch** [comment]
Beautiful, thank you! It should be safe to mark this issue as fixed by your
PR to add a test.

**Comment by sploiselle** [comment]
I don't believe this is done for sinks.

**Comment by def-** [comment]
Correct, also noticed this in https://github.com/MaterializeInc/materialize/pull/20056

**Comment by benesch** [comment]
Thanks so much for just knocking this one out!
