### ISSUE TITLE
Compute reconciliation is not efficient

### ISSUE THREAD

**Issue by teskje** [MaterializeInc/materialize#17594]
### What version of Materialize are you using?

main

### How did you install Materialize?

Built from source

### What is the issue?

The metrics added in #17576 show that compute reconciliation caused by environmentd restarting fails to fulfill its intended purpose currently: (almost?) all existing dataflows are dropped and re-created during reconciliation, even though it should be possible to reuse them.

### Reproduction

The issue can be reproduced on staging by:

1. Installing some dataflows (indexes, materialized views) in a cluster.
2. Killing the environmentd pod, causing the orchestrator to restart it.
3. Checking the `mz_compute_reconciliation_*` metrics.

The metrics will show that (most?) dataflows are replaced instead of reused.

I think it might be possible for reconciliation to work correctly in rare cases, hence my parenthetical use of modifiers above.

### Diagnosis

I haven't checked this yet, but I strongly suspect that this issue is caused by our selection of dataflow `as_of`s during coordinator bootstrap.

* For indexes, we choose the least valid read time (i.e. the maximum/join of `since`s) of all input collections: https://github.com/MaterializeInc/materialize/blob/4fade0a936c32ca511a3a4d2306b3fc493c1539d/src/adapter/src/coord/dataflows.rs#L238
* For materialized views, we do the same: https://github.com/MaterializeInc/materialize/blob/4fade0a936c32ca511a3a4d2306b3fc493c1539d/src/adapter/src/coord.rs#L831

These least valid read times are ultimately informed by the `since`s of persist shards the dataflows read from, because these are the only `since`s we persist durably. So a dataflow's `as_of` is selected to be the join of the `since`s of all persist shards that feed the dataflow.

Storage delays compaction of persist shards to reduce communication overhead. Which means that when the compute controller tells the storage controller that compacting an input storage collection is allowed, the advancement of the underlying persist shard's `since` can be delayed. On the other hand, the compute replicas are informed about allowed compaction immediately (via the `AllowCompaction` command).

Assume that a replica maintains an index `D` reading from a persist shard `S`. `D` has been compacted to time `t2`, whereas `S` has only been compacted to `t1` (with `t1 < t2`) due to the compaction rate limiting mentioned above. Now environmentd restarts but the replica does not. The coordinator performs bootstrapping, as part of which it instructs the compute controller to create a dataflow `D'` with the same definition as `D` but an `as_of` of `t1`. The compute controller sends that dataflow description to the replica, which performs reconciliation. During reconciliation, the replica checks if its existing dataflow `D` is compatible with `D'` and can therefore be reused. It notices that `D`'s `as_of` (`t2`) is beyond `D'`'s `as_of` (`t1`) and [consequently decides that `D` cannot be used in place of `D'`](https://github.com/MaterializeInc/materialize/blob/4fade0a936c32ca511a3a4d2306b3fc493c1539d/src/compute-client/src/types/dataflows.rs#L294-L295). So it drops `D` and creates a new dataflow instead.

### Fixes

Assuming the above diagnosis is correct, the fundamental issue is that after an environmentd restart the replica is instructed to re-create a dataflow with an `as_of` that is before the frontier the dataflow has already been allowed to compact to. The issue can therefore be solved by ensuring that the compute controller always re-creates dataflows with `as_of`s that are beyond the frontiers these dataflows have been allowed to compact to previously.

One option is having the compute controller durably store information about previous compaction commands it has sent, and use that information on a restart to inform dataflow `as_of`s. This is part of what [compute command durability](#13222) would provide.

It is currently not clear if and how we want to implement durability in the compute controller. In the interest of fixing reconciliation in a timely manner, we could alternatively adjust the coordinators' bootstrapping to use the minimum/meet of `upper`s (rather than the maximum/join of `since`s) of all input collections when selecting `as_of`s for compute dataflows. These frontiers should always be beyond the what we allowed compaction to before the restart, assuming that we allow compaction only up to the current `upper`.

**Comment by aljoscha** [comment]
Hate to be a nitpicker, but: is it not _effective_ or not _efficient_?

**Comment by teskje** [comment]
You are right, "efficient" is better. Reconciliation does still fulfill its purpose of restoring the desired dataflow state, it doesn't violate correctness.

**Comment by frankmcsherry** [comment]
I think before we can do too much on this we need to sort out the "is the `Coordinator` the boss of the `Controller`, or vice versa?" question, no? If on `envd` restart the `Coordinator` picks a `DataflowDescription` with a historical `as_of`, based on persist shards, ... it feels like there isn't much to do other than respect its wishes. Generally, if the `Controller` always respects the wishes of its users, we would need to teach the users to ask for better things rather than change the `Controller`, I think? Happy to be wrong, but that's my sense!

**Comment by teskje** [comment]
Thinking more about it, basing the `as_of` on the `upper`s of dataflow inputs instead of the `since`s is not a good idea. The issue is that the compute controller is responsible for holding back compaction of storage inputs to dataflows for times that replicas are still reading. If we tell the compute controller "please create this dataflow at this `as_of`" it will assume that allowing compaction of the dataflow inputs up to that `as_of` is fine. But if the `as_of` is based on the `upper`s of those inputs that might not be the case! Existing replicas might have compatible dataflows that still read from the inputs at an earlier time, and those replicas might crash if the inputs were compacted up to their `upper`s.

Having replicas crash is not the worst thing, they would recover fine after being restarted. But this would lead to the occasional "cannot serve requested as_of" panic in our logs, without any indication of whether it was caused by a failed reconciliation attempt or an actual bug.

**Comment by teskje** [comment]
Thinking about this even more, this statement needs some elaboration:

> Existing replicas might have compatible dataflows that still read from the inputs at an earlier time, and those replicas might crash if the inputs were compacted up to their uppers.

If a replica reading from a persist collection has successfully instantiated a read handle, that handle will hold back the since even if the compute controller released its read hold for the time the replica is reading at. There are, however, at least two cases where holding back the since like this doesn't work:
* If the read handle has not yet been instantiated, e.g., because the replica is slow to instantiate the persist source.
* If the read handle's lease has expired, e.g., because it's heartbeat didn't make it to persist.

Both scenarios can be triggered by networking issues, or by a pegged replica CPU, I think. So the read handle's read hold makes panics less likely, but not impossible.

**Comment by teskje** [comment]
Here is something else I missed previously: Even writing down the compaction frontier for each collection durably in the compute controller will not be enough to avoid the "cannot serve requested as_of" issue outlined above. That is because the compaction frontier (aka. the "implied capability" of a compute collection) is computed based on the `upper` of the fastest replica, so it is not useful to hold back compaction for slower replicas.

To explain a bit more:
* The compute controller keeps for each compute collection (index, MV, subscribe) an "implied capability". This capability is computed based on the global write frontier of the collection, by applying the collection's read policy to it. Normally it is just "write frontier - 1s". The global write frontier is the `upper` of the fastest replica, or the join of all replica `upper`s.
* The implied capability is used to allow compaction to compute collections. Whenever the implied capability changes, the controller sends an `AllowCompaction` command with that frontier to all replicas.
* Note that the compaction frontier/implied capability can be beyond the `upper` of some of the replicas, since it is based on the join of all replica `upper`s. This is fine, DD is able to handle allowed compaction of an arrangement beyond its `upper`.
* The compute controller keeps a read hold on all dataflow inputs at the implied capability. This is not enough, however, because the implied capability can be beyond the `upper`s of some of the replicas. So some replicas might still be reading from dataflow inputs at times before the implied capability. This is not an issue for compute inputs (i.e. arrangements) because DD takes care of holding back compaction, but it is an issue for storage inputs, as I described in my previous comments.
* So to prevent slow replicas from crashing when reading compacted storage inputs, the compute controller also installs read holds for each replica at the replica's `upper`. So even if a replica is lagging behind with an `upper` before the collection's implied capability, we can ensure that its storage inputs are not compacted beyond what the slow replica has read.

So there are two important frontiers when reconciling a compute collection:
* The compaction frontier/implied capability that was sent to all replicas before the controller restarted. After the the restart, we need to set the dataflow's as_of to a frontier *equal to or beyond* that previous implied capability, otherwise reconciliation will be inefficient (i.e. the replicas will drop the dataflow and re-create it).
* The meet of all replica `upper`s reported to the compute controller before the restart. After the restart, we need to install per-replica read holds at a frontier *equal to or before* that on the storage inputs to our compute collection, otherwise replicas might attempt to read compacted data.

One way to restore these frontiers is by having the controller write them down durably.

But note that we don't need the exact frontiers, we are actually happy with frontiers beyond or before, respectively. And we can get those based on the persist state:
* A surrogate for the compaction frontier can be `meet(uppers of all transitive persist inputs)` for indexes/subscribes and `upper of the output shard` for MVs.
* A surrogate for the meet of replica `uppers` can be `join(sinces of all transitive persist inputs)`.

At least I think that would work out. It's still way more complicated and brittle than having the compute controller remember these things.

**Comment by teskje** [comment]
Reopened because our chosen workaround leads to other bugs (https://github.com/MaterializeInc/cloud/issues/7998) and is therefore not viable.

**Comment by teskje** [comment]
Closing again because we have managed to adapt the chosen workaround to make it viable after all!
