### ISSUE TITLE
adapter: add tracing for all getting started queries

### ISSUE THREAD

**Issue by mjibson** [MaterializeInc/materialize#17611]
Some getting started queries have gaps in their traces. Track these down and add them so we can better understand what's going on. Queries missing:

```
CREATE SOURCE demo FROM LOAD GENERATOR AUCTION FOR ALL TABLES WITH (SIZE = '2xsmall');

CREATE MATERIALIZED VIEW avg_bids AS
  SELECT auction_id, avg(amount) AS amount
  FROM on_time_bids
  GROUP BY auction_id;
```

**Comment by parker-timmerman** [comment]
@mjibson do you have an example of what traces we do expect from these queries?

**Comment by mjibson** [comment]
We expect that there are no visible gaps in the trace waterfall.
