### ISSUE TITLE
sql,storage: support `ALTER CONNECTION`

### ISSUE THREAD

**Issue by benesch** [MaterializeInc/materialize#17620]
## Summary

Support `ALTER CONNECTION` for ~all available options for each connector. For example, we could support updating a Kafka broker's hostname like so:

```
ALTER CONNECTION foo TO KAFKA
    BROKER 'new-hostname:9092';
```

## Details

Today, once you create a connection in Materialize, its definition is fixed. The only way to change any connection options is to drop and recreate the connection. This can be painful if there are downstream sources and sinks (which, of course, is the whole reason you create a connection in the first place—to create sources and sinks!), as all of _those_ sources and sinks need to be recreated as well.

There is one small exception here: connection parameters that are secrets can have their definition changed at any point via `ALTER SECRET`.

I think it should be possible for `ALTER CONNECTION` to support changing approximately any option for any connection type. At least, I can't think of any existing connection option that we couldn't change after creation.

Using `ALTER CONNECTION` to change the _type_ of a connection is strictly not supported, though.

## Use cases

@chuck-alt-delete highlighted that a very common case will be adding a new broker to an MSK Kafka cluster that is behind an AWS PrivateLink tunnel. Because Materialize requires the NLB mapping for each broker to be declared on the PrivateLink connection, each new broker will require running an `ALTER CONNECTION` to add the broker mapping.

## Open questions

* When does the `ALTER CONNECTION` take effect? Do we automatically restart the sources and sinks that are attached to the source/sink? If we don't restart those sources/sinks immediately, what do we tell users about when their `ALTER CONNECTION` will take effect?

* Having to re-specify the connection type in the `ALTER` statement is awkward, and makes it seem like you might be able to change a connection type. Is there a way to avoid this?

cc @uce @aljoscha

**Comment by sjwiesman** [comment]
@dseisun-materialize Just want to make sure this is on your radar. Not urgent by any means, but I feel like it will become important as we have more production workloads where users can't easily drop their sources to update a connection object. 


> When does the ALTER CONNECTION take effect? Do we automatically restart the sources and sinks that are attached to the source/sink? 

I would expect it to restart the sources and sinks automatically and do so right away

**Comment by sploiselle** [comment]
Design proposal in #21109

**Comment by benesch** [comment]
Reopening to track the addition of the docs that @sploiselle has in the works.
