### ISSUE TITLE
Include regex verbatim in `SHOW CREATE SOURCE`

### ISSUE THREAD

**Issue by sploiselle** [MaterializeInc/materialize#1762]
After creating a dynamic file source, and structuring it with regex, `SHOW CREATE SOURCE` does not provide specific enough data to let the user re-create the source.

One of the impossible-to-retrieve components here is the regular expression included in `CREATE SOURCE ... WITH (regex='...', ...)`. We should include at least that detail in `SHOW CREATE SOURCE` so users can recreate their sources if need be.

@umanwizard Are you a good candidate for this work?

**Comment by rjnn** [comment]
@umanwizard was this fixed when the new `CREATE SOURCE` syntax shipped in 0.10?

**Comment by benesch** [comment]
No, if anything the situation is worse, because `SHOW CREATE SOURCE` shows an old-style URL.

**Comment by umanwizard** [comment]
I consider this a bug; changing the labels appropriately.
