### ISSUE TITLE
ALTER SOURCE allowed on non-linked clusters, has no effect

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#17638]
### What version of Materialize are you using?

v0.44.0-dev (c851bd6e5)

### How did you install Materialize?

Docker image

### What is the issue?

It is possible to issue `ALTER SOURCE ... SIZE` on a source that is already assigned to a non-linked cluster. That command seems to have no effect in this case, but I think it should be disallowed altogether to prevent nasty surprises.

```
materialize=> CREATE SOURCE generator1 IN CLUSTER default FROM LOAD GENERATOR COUNTER;
CREATE SOURCE
materialize=> alter source generator1 SET (size '2');
ALTER SOURCE
...
SET cluster=mz_introspection;
materialize=> select * from mz_cluster_replicas;
 id | name | cluster_id | size | availability_zone 
----+------+------------+------+-------------------
 1  | r1   | u1         | 1    | 
 2  | r1   | s1         | 1    | 
 3  | r1   | s2         | 1    | 
``` 

@benesch FYI

### Relevant log output

```source
environmentd: 2023-02-13T10:52:30.309541Z  INFO mz_adapter::catalog: update source materialize.public.generator1 (u3)
```

**Comment by benesch** [comment]
Good spot, thanks! Put up https://github.com/MaterializeInc/materialize/pull/17646 to fix.
