### ISSUE TITLE
Improve redirect after creating an mz app password via the browser

### ISSUE THREAD

**Issue by sjwiesman** [MaterializeInc/materialize#17648]
### Feature request

After successfully creating an app password via the browser, mz redirects you to an unsettled page that says, "You may now close this tab". We should either redirect to an existing page or create something more well-styled. 

<img width="1512" alt="Screen Shot 2023-02-13 at 8 44 10 AM" src="https://user-images.githubusercontent.com/1891970/218489094-78ed4552-2b20-4b7a-8afa-9c27ad261be9.png">

**Comment by ggnall** [comment]
100% cc @parkerhendo

**Comment by joacoc** [comment]
Fixed.
