### ISSUE TITLE
Document `ReducePlan::DistinctNegated` in the code

### ISSUE THREAD

**Issue by vmarcos** [MaterializeInc/materialize#17640]
Presently, our documentation of `ReducePlan::DistinctNegated` is insufficient and needs expansion. The following [Slack thread](https://materializeinc.slack.com/archives/C02PPB50ZHS/p1676288759455119) gives the necessary context.

**Comment by antiguru** [comment]
Related: #17642

**Comment by antiguru** [comment]
Related: #19466 which removes the `ReducePlan::DistinctNegated` implementation.
