### ISSUE TITLE
storage,compute: allow multipurpose clusters

### ISSUE THREAD

**Issue by benesch** [MaterializeInc/materialize#17659]
### Feature request

*Part of the multipurpose clusters epic (#17413).*

Once the following four issues are complete...

- https://github.com/MaterializeInc/materialize/issues/17416
- https://github.com/MaterializeInc/materialize/issues/17418
- https://github.com/MaterializeInc/materialize/issues/17419
- https://github.com/MaterializeInc/materialize/issues/18076

...there will be no remaining _technical_ blockers to allowing users to mix storage and compute objects in the same cluster.

But there is a people and process issue: it will be harder to tell which layer is at fault when there are problems in a cluster. Storage will need to be prepared to identify when a problem that presents as a source or sink issue is actually a compute problem, and vice-versa. This will require substantial knowledge sharing between the teams, and possibly a review of one another's timely operators.

The Compute team needs to gain a good understanding of at least the following components:
* Command distribution. Sending commands to workers must happen such that all workers see commands in the same order. At the moment, all commands originate from the controller, but workers cannot introduce their own commands, which seems to contrast with Storage's approach. We have to keep in mind that commands to construct dataflows need to be applied in the same order on all workers to satisfy Timely's requirements.
* Tearing down dataflows. In Compute, dataflows are only ever dropped because nobody is interested in their output, and the mechanism for this is to allow compaction to the empty frontier. Storage might use a pattern of re-creating dataflows to handle source ingestion problems, which needs careful analysis to determine potential side-effects.
* Debuggability: Compute in the past tried to ensure that there are tools to debug and diagnose dataflow issues. We need to make sure that Storage offers the same level of debuggability. (@antiguru doesn't claim the situation is great, instead, it could benefit from much better tooling and documentation!)
* Code ownership: We need to clarify which set of people is responsible for maintaining the unified components in the future.
* Protocol specification. Compute recently invested some considerable amount of effort in specifying the semantics and invariants of the compute protocol (see the docstrings of `ComputeCommand` and `ComputeResponse`). We want to keep this documentation complete and updated with every protocol evolution, which includes merging the compute and storage protocols.

We must explicitly get sign off from both storage and compute that the teams are comfortable allowing multipurpose clusters. At the time of writing, that means:

  - [ ] @aljoscha 
  - [ ] @antiguru 
  - [ ] @teskje 
  - [ ] @frankmcsherry 

Once everyone is signed off, we can simply remove the conditional in the SQL planner that prevents mixing storage and compute objects in the same cluster.

**Comment by antiguru** [comment]
I added a description of what I think are Compute's concerns or guidelines. cc @teskje, please take a look and feel free to add items!

**Comment by teskje** [comment]
Thanks Moritz! I've added another point about the protocol spec.

**Comment by benesch** [comment]
We ended up allowing users to mix-and-match compute and storage objects on a cluster (#21846) even before addressing the technical issues laid out in the issue description.
