### ISSUE TITLE
cannot migrate from catalog version 0.43.0-dev to version 0.43.0-dev (earlier versions might still work): Expected identifier, found number "1.00"

### ISSUE THREAD

**Issue by def-** [MaterializeInc/materialize#17665]
### What version of Materialize are you using?

v0.43.0-dev (1c9960719)

### How did you install Materialize?

Built from source

### What is the issue?

With the code in https://github.com/MaterializeInc/materialize/pull/17614/commits/b25e08c0d64ccf08252f01b754f1b116fff17955 I introduce a new `Identifiers` check. Restarting Materialize fails with a secret created like this:

```
CREATE SECRET "1.00" as '1.00_value';
```

It seems like we are not serializing/deserializing the `"1.00"` secret name correctly and it gets reinterpreted as a number instead of a string.

Can be reproduced with:
```
$ cd ~/git/materialize
$ git checkout b25e08c0d64ccf08252f01b754f1b116fff17955
$ bin/mzcompose --find platform-checks down -v && bin/mzcompose --find platform-checks run default --scenario=RestartEntireMz --check=Identifiers
```

### Relevant log output

```source
platform-checks-materialized-1 | environmentd: cannot migrate from catalog version 0.43.0-dev to version 0.43.0-dev (earlier versions might still work): Expected identifier, found number "1.00"
```

ci-regexp: Expected identifier, found operator

**Comment by philip-stoev** [comment]
This looks like a genuine catalog migration issue -- if Mz is not restarted, the table definition looks ok:

```
materialize=> show create table t1;
         name          |                              create_sql                               
-----------------------+-----------------------------------------------------------------------
 materialize.public.t1 | CREATE TABLE "materialize"."public"."t1" ("1.00" "pg_catalog"."text")
```
and the `CREATE TABLE` statement recorded is valid and runnable. So some rewrite during a migration is probably the source of the error.

**Comment by def-** [comment]
Similar but slightly different issue with database:
```
CREATE DATABASE "-1";
```
fails after mz restart:
```
platform-checks-materialized-1  | environmentd: cannot migrate from catalog version 0.43.0-dev to version 0.43.0-dev (earlier versions might still work): Expected identifier, found operator "-"
```
Also with secrets:
```
> CREATE SECRET "10" as '11';
```
fails after mz restart:
```
platform-checks-materialized-1  | environmentd: cannot migrate from catalog version 0.43.0-dev to version 0.43.0-dev (earlier versions might still work): Expected AS, found number ".10"
```

**Comment by aalexandrov** [comment]
Added `release-blocker` to this one. I would be quite scared of this appearing in production during an upgrade. @benesch Maybe we should delay the release until this is resolved and a bugfix version of `0.43` is cut?

**Comment by def-** [comment]
This has probably been broken for a long time though, so it's not a regression. I just added new testing. I'm still happy to have this fixed asap though of course.

**Comment by chaas** [comment]
Thanks for catching this and adding testing @def- ! Yeah I can imagine this has been around for a long time. Definitely good to fix asap, and we are looking into it, but I wouldn't release block on it. The release manager can run an `mzadmin` script over `mz_columns` to be sure no live customers have any numeric column names.

**Comment by benesch** [comment]
Agree with @chaas—as long as this existed in v0.42 (can someone check?), I don't think we need to block v0.43 over this.

**Comment by jkosh44** [comment]
> Agree with @chaas—as long as this existed in v0.42 (can someone check?), I don't think we need to block v0.43 over this.

I'll confirm this.

**Comment by def-** [comment]
It's not just numeric column names, but also some other strange unicode, as well as in secrets and database names, see the "TODO: Enable when fixed" in https://github.com/def-/materialize/commit/fedfc2cf209f9d8445f85e0ded551024228549db

**Comment by jkosh44** [comment]
Ok, I figured it out. The issue doesn't actually exist for table columns. It's the secret that causes this.
```
CREATE DATABASE "1.00_db";
SET DATABASE="1.00_db";
CREATE SECRET "1.00_db.public.1.00_secret" AS '********';
```

After that Materialize will fail to start up. The database is probably unnecessary. 

I checked and this issue is present in v0.42.0.

**Comment by def-** [comment]
@jkosh44  My bad, you are right, this only seems to affect secret and database, not table.

**Comment by jkosh44** [comment]
I have a fix for secrets here: https://github.com/MaterializeInc/materialize/pull/17675. 

I was not able to reproduce the database issue on `main` though.

**Comment by jkosh44** [comment]
> I have a fix for secrets here: #17675.
> 
> I was not able to reproduce the database issue on `main` though.

@def- Is it possible that you were creating a secret in the database "-"? In which case the failure would happen when parsing the fully qualified secret and not when parsing the database. If that was the case, then my PR will fix that issue too.

**Comment by def-** [comment]
Yes, that's possible, let's see the run result to know if there is a db identifier issue remaining.

**Comment by def-** [comment]
It was a bit hairy to figure out which queries are actually failing, I'd suggest also printing the full query/context in "cannot migrate" errors.

**Comment by def-** [comment]
Reopen for presentation this evening, and because this is still failing the upgrade tests from old version before fix. (Will automatically get fixed in a few days and I'll close this again, no other action required.)
