### ISSUE TITLE
Unexpected "extra data after last expected column" with a SIZE "4-1" pg-cdc source

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#17664]
### What version of Materialize are you using?

cd4ffc512a5f0875d22ac21704cfcdd38485a9fb

### How did you install Materialize?

Docker image

### What is the issue?

A build that use SIZE "4-1" for storage clusterds failed as follows:

https://buildkite.com/materialize/tests/builds/49870#01864f32-a0c6-46d9-bc17-3f8a8fdbe6c9

The error indicates that the pg-cdc source did not properly detect that the table has been altered. Instead, it received more data in a row than expected, which happily also caused the source to error out, but I would assume other forms of ALTER TABLE on the Postgres side would not have caused the replication to error out and would have produced incorrect data in the source instead.

To reproduce, you can use this patch:

```
diff --git a/misc/python/materialize/mzcompose/services.py b/misc/python/materialize/mzcompose/services.py
index 245dc2772..7e44ce600 100644
--- a/misc/python/materialize/mzcompose/services.py
+++ b/misc/python/materialize/mzcompose/services.py
@@ -103,7 +103,8 @@ class Materialized(Service):
         if propagate_crashes:
             command += ["--orchestrator-process-propagate-crashes"]
 
-        self.default_storage_size = default_size
+        self.default_storage_size = "1" if default_size == 1 else f"{default_size}-1"
+
         self.default_replica_size = (
             "1" if default_size == 1 else f"{default_size}-{default_size}"
         )
```

### Relevant log output

```source
verify-data.td:15:1: error: expected error containing "altered", got "Source error: u24: failed during initialization, must be dropped and recreated: extra data after last expected column"
--
  | \|
  | 14 \|
  | 15 \| ! SELECT * FROM to_be_altered;
  | \| ^
```

@guswynn FYI

**Comment by guswynn** [comment]
@philip-stoev Were you able to reproduce this? Locally I haven't been able to at all

**Comment by benesch** [comment]
I also haven't been able to reproduce this. Going to optimistically assume that various PostgreSQL source improvements have resulted in this being fixed.
