### ISSUE TITLE
multi-process storage: individual computed processes conflict on CRDB 

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#17666]
### What version of Materialize are you using?

cd4ffc512a5f0875d22ac21704cfcdd38485a9fb

### How did you install Materialize?

Docker image

### What is the issue?

If the feature benchmark is run with SIZE "4-1" for storage clusters, it reports the following:

```
NAME                      \|    THIS     \|    OTHER    \|  Regression?  \| 'THIS' is:
--
  | ----------------------------------------------------------------------------------------------------
  | StartupLoaded             \|      15.875 \|       8.016 \|    !!YES!!    \| 98.0 pct   slower
```

Turns out that this is because of exponential back-off in the consensus implementation:

```
consensus::open failed, retrying in 8.192s: determinate: db error: ERROR: restart transaction: TransactionRetryWithProtoRefreshError: TransactionRetryError: retry txn (RETRY_WRITE_TOO_OLD - WriteTooOld flag converted to WriteTooOldError): "sql txn" meta={id=4fbb68ad key=/Table/5/1/117/0 pri=0.04758006 epo=0 ts=1676378175.104633148,1 min=1676378175.104461904,0 seq=2} lock=true stat=PENDING rts=1676378175.104461904,0 wto=false gul=1676378175.604461904,0
```

This does not seem to happen on the latest released Mz container on DockerHub.

To reproduce:

1. Apply diff:
```
diff --git a/misc/python/materialize/mzcompose/services.py b/misc/python/materialize/mzcompose/services.py
index 245dc2772..7e44ce600 100644
--- a/misc/python/materialize/mzcompose/services.py
+++ b/misc/python/materialize/mzcompose/services.py
@@ -103,7 +103,8 @@ class Materialized(Service):
         if propagate_crashes:
             command += ["--orchestrator-process-propagate-crashes"]
 
-        self.default_storage_size = default_size
+        self.default_storage_size = "1" if default_size == 1 else f"{default_size}-1"
+
         self.default_replica_size = (
             "1" if default_size == 1 else f"{default_size}-{default_size}"
         )
```
2. Run:
```
cd test/feature-benchmark
./mzcompose down -v ; ./mzcompose run default --scenario=StartupLoaded --max-measurements=1 --max-retries=1 --other-tag=latest
```
3. When the benchmark gets to here:
```
Running the shared() section for StartupLoaded ...
shared() done
Running the init() section for StartupLoaded ...
init() done
[+] Running 1/1
 ⠿ Container feature-benchmark-materialized-1  Killed                                                         0.4s
[+] Running 1/1
 ⠿ materialized Pulled                                                                                        0.9s
[+] Running 0/1
 ⠿ Container feature-benchmark-materialized-1  Waiting                                                        6.8s
```

hit Ctrl+C to stop the python script and leave the containers intact. You can then use 

```
docker logs feature-benchmark-materialized-1
```
to see the log and the offending retry backoff.

**Comment by philip-stoev** [comment]
I guess the exponential back-off needs to have some random jitter added to it - https://aws.amazon.com/blogs/architecture/exponential-backoff-and-jitter/

**Comment by danhhz** [comment]
> I guess the exponential back-off needs to have some random jitter added to it

It already does have jitter! :D https://github.com/MaterializeInc/materialize/blob/7a797f863b50e662e52715795b65f05d1e027b9a/src/persist/src/retry.rs#L82-L94

**Comment by guswynn** [comment]
@philip-stoev The attached pr should reduce the contention here. In my local testing (admittedly, its local on an m1 mac, so the speed of the check is wildly different), but it appeared to reduce the slowdown from "occasionally 2.4x slower" to "20% slower", but that may be dependent on whatever else was running on my machine at the time I tested.
