### ISSUE TITLE
storage: gracefully restart ingestion on compare_and_append conflict

### ISSUE THREAD

**Issue by aljoscha** [MaterializeInc/materialize#17696]
Currently, when the _storage_ `persist_sink` that sits at the end of the ingestion pipeline encounters a conflict it `panic!`s (via an `expect()` call). This has the effect of not only restarting ingestion for that particular source but for everything running on the same (cluster) replica.

Instead, we should use the internal control flow (introduced in https://github.com/MaterializeInc/materialize/pull/16958) to gracefully restart only that particular ingestion.

**Comment by moulimukherjee** [comment]
Done via https://github.com/MaterializeInc/materialize/pull/17589
