### ISSUE TITLE
Expand allowed origins for environmentd

### ISSUE THREAD

**Issue by RobinClowers** [MaterializeInc/materialize#17701]
### Feature request

In order to support the new web console hosting provider and preview deployments, we will have to allow additional CORS origins. Specifically, the production origin will be `https://console.materialize.com`, and preview deployments will be at `https://*.vercel.com`.

**Comment by benesch** [comment]
The way I’d recommend accomplishing this is to add logic to the existing `allowed-origin` field. We should lightly parse the hostname there and, if it contains a wildcard, create an `Origin::predicate` that applies the wildcard matching logic.
