### ISSUE TITLE
"Checks + restart Redpanda & Debezium" is flaky

### ISSUE THREAD

**Issue by bkirwi** [MaterializeInc/materialize#17747]
### Buildkite link

https://buildkite.com/materialize/tests/builds/50159#01867015-5dae-46ad-9337-d01c05300653

### Relevant log output

```source
platform-checks-materialized-1  | thread 'timely:work-2' panicked at 'u14: see198271-13f1-4e6b-8558-350ecd9ba2e7 cannot serve requested as_of Antichain { elements: [1676916955340] }: Since(Antichain { elements: [1676917373925] })', /var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0ad5cbdc64164b540-1/materialize/tests/src/persist-client/src/operators/shard_source.rs:177:24
[...]
platform-checks-materialized-1  | cluster-u3-replica-5: 2023-02-20T18:24:23.148213Z  INFO mz_storage::sink::kafka: kafka-u17: initial as_of: Antichain { elements: [1676916955340] }, latest progress record: Some(1676917373926)
```

### Additional thoughts

This seems like a recent regression... I don't recall seeing these before the last week, and I've seen a few today already.

I'm a bit nervous this has to do with some recent refactoring of how since holds work in the controller... cc @aljoscha @sploiselle who were around for that PR.

**Comment by philip-stoev** [comment]
Dup of https://github.com/MaterializeInc/materialize/issues/17543
