### ISSUE TITLE
stash error: unexpected peek multiplicity

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#17754]
### What version of Materialize are you using?

v0.44.0-dev (680c26013)

### How did you install Materialize?

Docker image

### What is the issue?

I was testing how we handle CRDB rolling restarts by bringing a Cockroach Cloud cluster from 7 nodes down to 3 while running a `CREATE TABLE` / `DROP TABLE` DDL against Mz. In the process, Mz experienced various errors in the log and ultimately the catalog appears to have been borked:

```
materialize=> create table t1 (f1 integer);
ERROR:  stash error: unexpected peek multiplicity
``` 

ci-regexp: unexpected peek multiplicity

**Comment by philip-stoev** [comment]
[gh17754.log.zip](https://github.com/MaterializeInc/materialize/files/10790940/gh17754.log.zip)
[gh17754-mzdata.zip](https://github.com/MaterializeInc/materialize/files/10790941/gh17754-mzdata.zip)
The CRDB database has been backed up to a bucket in the Scratch account . Search using the issue number in the AWS console to find it.

**Comment by mjibson** [comment]
Was able to repro locally with the bucket data. Looking.

**Comment by philip-stoev** [comment]
Just happened in the CI

```
The Zippy scenario that restarts CRDB caused the following panic:

```
zippy-materialized-1     | thread 'coordinator' panicked at 'sinks should be validated by sequence_create_sink: Catalog(Error { kind: Stash(StashError { inner: Other("unexpected peek multiplicity") }) })', /var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0550088af0be19dcb-1/materialize/tests/src/adapter/src/coord/message_handler.rs:494:22
```

https://buildkite.com/materialize/nightlies/builds/1851#018680d8-9211-4156-a18f-e2f230e629d1
