### ISSUE TITLE
persist: [brainstorm] how to be $ cheaper $

### ISSUE THREAD

**Issue by danhhz** [MaterializeInc/materialize#17777]
Persist's monetary costs come from a few places:
- (1) S3 BytesSeconds prices for the time that data is at rest
- (2) S3 Get/Put prices for when the data is compacted and read
- (3) Less directly, needing to scale up the CRDB cluster
- (4) Also less directly, the cpu/memory/etc of the EC2 nodes running persist code (and the possibility that a smaller node could be used and/or the opportunity cost of whatever else the node would be doing instead)

Concretely, this brainstorming comes from a tension using persist in the most natural way vs the most cost-efficient way. For example, in practice, every shard's upper is advanced once per second, resulting in a constant ~1 qps per shard on CRDB. This includes system tables that are written once at startup and not again until the next envd restart (a user table that's written once is even worse). We've optimized this query heavily to make this query as cheap as possible, but shards have become the natural building block for everything in mz (e.g. we're even keeping perf introspection data in there to serve users) and so this adds up. We've also hesitated to [turn back on durability for compute introspection shards](https://github.com/MaterializeInc/materialize/issues/15470) because of [bugs](https://github.com/MaterializeInc/materialize/issues/15985) but also because of how much they cost. Looking (far) forward to self-service, product-led sales motions work best when trials don't have an end date (citation needed) which effectively means a system at rest needs to cost very very little.

**Comment by danhhz** [comment]
# Idea: Quiesce Shard Usage

One previous idea I've had here was to "quiesce" things like system tables. The idea would be something like, after a configurable time period, the coordinator would stop calling compare and append for any table not actively being used as an input to a materialized view. Then, the next time it's read (e.g. a user SELECTs it or starts a new mz using it as an input), the coordinator could do one big compare_and_append to catch it up. This would introduce a decent amount of complexity on top of persist and a good amount of potential for distributed systems-y bugs and there hasn't been much appetite for it.

**Comment by danhhz** [comment]
### Idea: Multi-shards (enabled by filter pushdown)

Another more recent idea I've had is to heavily lean into #12684 and build some sort of "multi-shard" abstraction (on top of persist or within it, TBD) which is logically a set of shards but physically a single one where all the data is wrapped in an enum/union (with one variant per logical shard). A read of one of these logical shards could then push down a filter to aggressively prune the unrelated data out before even fetching it. There are at least two big gotchas here:

- Adding and removing logical shards from the set is probably hard
- Because of compare_and_append's atomicity of updates+frontier, all logical shards in the set would have to be written together. This is less of an issue for things like compute introspection sources which IIUC don't care about the particular timestamp they're reclocked to (or could be made to not care). In fact, it would potentially allow for a new design for compute introspection, where every replica in a cluster is put in the same shard, which could improve the ergonomics.

There's also an interesting potential upside though! This would be a way to atomically write data to multiple shards, which I hear has come up in the context of the coordinator and table writes.

**Comment by sploiselle** [comment]
Regarding [quiescence](https://github.com/MaterializeInc/materialize/issues/17777#issuecomment-1439217384), there's an issue (#14927), a design doc in [Notion](https://www.notion.so/materialize/Quiesce-timestamp-updates-164ca2342bc14758a31f6cb90323118f), and [a very outdated commit](https://github.com/sploiselle/materialize/tree/quiesce-timestamp-updates) with a sketch of the feature.

**Comment by danhhz** [comment]
Okay, y'all I think @petrosagg figured this out.

###  Idea: Table Remap Shard

Each table keeps a data shard, but each environment gets a (new) singleton "table remap shard". The table remap shard becomes the source of truth for the upper of a table. Anything in the table data shard past the remap upper is considered not yet committed. Any "time" between the table data upper and the remap upper is known to be empty of updates.

When no table writes are happening the remap shard is ticked forward (this could stay one second, but the traffic would be small enough that we could probably make it a hot loop if we wanted).

Whenever a table txn commits, the updates are all written to the corresponding data shards. After that is successful, the remap shard upper is advanced. After that is successful, the write is acknowledged to the user. If this table txn write process is interrupted (envd crashes), then the new envd discovers this on startup (a data upper will be past the remap upper) and is responsible for rolling back the updates before it starts ticking forward the remap shard.

At read time, we render an operator with the data and remap shards as inputs and one output. It passes through any updates from the data shard as soon as it reads them. Whenever the remap shard upper advances, it has to fetch the latest version of state for the data shard (NB that means this has to be done via a linearizable write, new work for persist but tractable), make sure the data shard input has advanced to at least that, and then passes on the frontier update to the output.
