### ISSUE TITLE
[SQLsmith] mz_repr::row::encoding: protobuf decoding found Dummy datum

### ISSUE THREAD

**Issue by def-** [MaterializeInc/materialize#17775]
### What version of Materialize are you using?

v0.45.0-dev (d6371fdc5)

### How did you install Materialize?

Built from source

### What is the issue?

```
materialize=> select from(select case when EXISTS(select indexprs limit 9) then indisreplident end from mz_views join pg_index on true);
--
(3600 rows)
```
The result is empty, even though 3600 rows are supposed to be there. The cluster logging indicates a protobuf decoding error.

### Relevant log output

```source
cluster-u1-replica-1: 2023-02-21T14:58:02.816719Z ERROR mz_repr::row::encoding: protobuf decoding found Dummy datum
```

**Comment by teskje** [comment]
I don't think there is a bug here. The query in question selects zero columns from 3600 rows, and this is just how the values of zero columns are represented. You can confirm that with this minimal query:

```
materialize=> select from pg_views;
--
(50 rows)
```

Postgres behaves the same way:

```
jan=# select from pg_views;
--
(137 rows)
```

The "protobuf decoding found Dummy datum" error is not really an error but a Sentry marker we added in to see if we have `Dummy` datums persisted anywhere. This is in service of our [attempt to remove `Dummy`](https://github.com/MaterializeInc/materialize/pull/17099). It's true that we don't expect to see this error being logged though, so I'll investigate why that happens here.

**Comment by aalexandrov** [comment]
@teskje the code you are referencing is basically the code that we are trying to remove. One of the things that #17099 does is to remove this `for` loop.

**Comment by aalexandrov** [comment]
> This means the error can be logged even if no Dummy is actually made durable, so we might get confused when seeing them in Sentry.

Yeah, I don't think we can modify the behavior depending on the client, can we?

**Comment by teskje** [comment]
> Yeah, I don't think we can modify the behavior depending on the client, can we?

No, we don't have this information locally when we decode a row. We could make persist_source check all the `Datum`s it emits instead of doing the check in row decoding, but that sounds like non-negligible overhead. I think it might be sufficient to be aware of the fact that the "protobuf decoding found Dummy datum" error can have FPs when/if we see it in Sentry.

**Comment by teskje** [comment]
Closing this issue based on the above.
