### ISSUE TITLE
logged-errors: follow-up usability enhancements

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#17798]
### Feature request

Various small things that have been observed while using the feature:
- [x] Add the entire machinery to `ci/release-qualification/pipeline.yml` as well
- [x] Add a documentation in doc/developer/*.md describing the syntax for annotating tickets. Maybe even link to this documentation page for the cases where the error is "unknown".
- [ ] Put the name of the buildkite step in the artifacts. The name of the mzcompose composition is not specific enough, as the same composition `zippy default` is used for several tests with different command-line options
- [x] have run.log for the cloudtest as well and include it in the logs that are being processed
- [x] add regular expressions for the errors that come out of testdrive output:
```
kafka-progress.td:27:1: error: non-matching rows: expected:
```

and
```
testdrive/kafka-exactly-once-sink.td:317:1: error: missing record
```
and

```
foo.td:1:1: error: query succeeded, but expected error
```

There may be more, src/testdrive would be the definitive source.

in test/testdrive/mzcompose.py, testdrive is called with an option where the testdrive binary will generate an XML file containing such errors. However, none of the other frameworks that use .td fragments or files is instrumented to call testdrive like that. So, until that happens, adding a regexp or two to fish for the same errors in the logs would be an easy win.

- [x] Add `halting process` to the regexp. Apparently this is a prefix that is tacked on to various cases of `unwrap` in the Rust code:
```
zippy-materialized-1     | environmentd: 2023-02-28T00:45:06.786732Z  WARN mz_adapter::util: halting process: updating cluster status cannot fail: Catalog(Error { kind: Stash(StashError { inner: Transaction(Commit(StashError { inner: Postgres(Error { kind: Closed, cause: None }) })) }) })
```

- [x] Make sure stderr is also captured in the `run.log` . Right now it seems that `tee` does not cause it to be captured, and testdrive errors in particular are sent to stderr.

**Comment by def-** [comment]
>  add regular expressions for the errors that come out of testdrive output:

I count 90, that seems like a lot of strings to add:
```
$ git grep "bail\!(" src/testdrive|wc -l
90
```
I'll add the reasonable seeming ones from sql.rs

**Comment by def-** [comment]
Another problem with the testdrive lines is that many output the interesting part in the next line, so the current model of just capturing a single line might not be sufficient in the long term.

**Comment by def-** [comment]
>  Put the name of the buildkite step in the artifacts. The name of the mzcompose composition is not specific enough, as the same composition zippy default is used for several tests with different command-line options

Do you mean the junit logged-error artifact name? Otherwise I'm not sure.
Also, you mean `BUILDKITE_STEP_KEY="checks-upgrade-entire-mz-previous-version"` should be used, right?

**Comment by philip-stoev** [comment]
> Do you mean the junit logged-error artifact name? Otherwise I'm not sure.

Yes, but turns out you already have it:
```
log error 1 (new) in checks-upgrade-clusterd-compute-first
```

> Also, you mean BUILDKITE_STEP_KEY="checks-upgrade-entire-mz-previous-version" should be used, right?

Yes.

**Comment by philip-stoev** [comment]
> Another problem with the testdrive lines is that many output the interesting part in the next line, so the current model of just capturing a single line might not be sufficient in the long term.

Yes, this is true. The full information about the error is available in the junit xml file that is generated directly from testdrive. Lets keep the current setup for a while and then we can figure out a better pipeline for error processing that would allow testdrive errors to also be processed for known issues.

Currently, the pipeline it looks something like:

![image](https://user-images.githubusercontent.com/1279722/222069967-f1680d48-3c50-4274-8f6e-76bc0f7c3ecc.png)

but eventually should look something like:

![image](https://user-images.githubusercontent.com/1279722/222070096-f0f311b6-5515-484f-8e1f-6e0db4e5ae6c.png)
