### ISSUE TITLE
read from multiple kafka partitions using multiple timely workers

### ISSUE THREAD

**Issue by rjnn** [MaterializeInc/materialize#1779]
When we read from Kafka, today we assign a single timely worker to read "the topic". The topic, as managed by Kafka could be partitioned, a fact that is known to us when we connect to it.

We could assign multiple timely workers to read from it, one per partition. Since there are no ordering guarantees across partitions anyway, there's limited value to serializing everything through a single timely worker.

**Comment by frankmcsherry** [comment]
I believe this can be closed.
