### ISSUE TITLE
[SQLsmith] ERROR:  Evaluation error: internal error: invalid input type

### ISSUE THREAD

**Issue by def-** [MaterializeInc/materialize#17807]
### What version of Materialize are you using?

v0.45.0-dev (f01773cb1)

### How did you install Materialize?

Built from source

### What is the issue?

```
materialize=> SELECT CAST(ref_0.relpersistence AS char(1)) AS c1 FROM pg_catalog.pg_class AS ref_0;
ERROR:  Evaluation error: internal error: invalid input type
materialize=> SELECT CAST(ref_0.attidentity AS char(1)) AS c1 FROM pg_catalog.pg_attribute AS ref_0;
ERROR:  Evaluation error: internal error: invalid input type
```

ci-regexp: Evaluation error: internal error: invalid input type

**Comment by chaas** [comment]
Took a brief look at this one. This columns are defined as 
```
'p'::pg_catalog.\"char\" AS relpersistence,
...
''::pg_catalog.\"char\" as attidentity,
```
So it looks like a problem where `pg_catalog.char` can't be cast to a regular `char`. I think maybe there's an issue with our implementation of `pg_catalog.char` where it has an extra quote?

I ran
```
materialize=> select pg_typeof('p'::pg_catalog.char);
 pg_typeof 
-----------
 "char"
materialize=> select pg_typeof('abc'::pg_catalog.text);
 pg_typeof 
-----------
 text
```
Maybe there's a reason for this, I'm not really sure, but it seems odd.
