### ISSUE TITLE
stash: Support serialization format migrations

### ISSUE THREAD

**Issue by jkosh44** [MaterializeInc/materialize#17824]
### Feature request

The current process for changing the on disk serialization format for stash collections is to wrap the new fields with an `Option`, and then maybe remove the `Option` after a release. While this works for the majority of use cases, it is a bit limited. 

Ideally we could implement a migration that deserializes a collection using the old structs, runs a closure to convert all the keys and values to the new structs, then serializes and overwrites all the data with the new format.

**Comment by ParkMyCar** [comment]
Fixed by #19373
