### ISSUE TITLE
Protobuf compatibility linting in CI

### ISSUE THREAD

**Issue by teskje** [MaterializeInc/materialize#17882]
Some of our protobuf definitions are used to persistently write down data and thus must be backward-compatible. Currently we rely on human review and the upgrade tests for ensuring this. We can do better by employing a protobuf linter than runs as part of the regular PR checks in CI.

There are several tools that provide this kind of linting, e.g.:
* https://github.com/bufbuild/buf
* https://github.com/nilslice/protolock

There are protobuf definitions that we don't require backward-compatibility for currently, like the compute/storage protocol types. We need to ensure that ignoring compatibility violations for these types is still possible. This can be done by configuring the linter to ignore certain types, or by making the CI job check for an "ignore protobuf compatibility violations" label in commit messages or PR descriptions.

**Comment by philip-stoev** [comment]
@nrainer-materialize is this one done, or you intend to do additional PRs? If done, please close the ticket.

**Comment by nrainer-materialize** [comment]
> @nrainer-materialize is this one done, or you intend to do additional PRs? If done, please close the ticket.

It's done, thanks for reminding. :-) I apparently chose a phrase in the PR description that did not trigger closing this ticket.
