### ISSUE TITLE
[SQLsmith] ERROR:  internal error: unimplemented join

### ISSUE THREAD

**Issue by def-** [MaterializeInc/materialize#17897]
### What version of Materialize are you using?

v0.45.0-dev (486332472)

### How did you install Materialize?

Built from source

### What is the issue?

```
CREATE TABLE IF NOT EXISTS a (a boolean, b boolean);
CREATE VIEW IF NOT EXISTS b AS SELECT 2 + 2;
CREATE TABLE IF NOT EXISTS c (data jsonb);
SELECT (SELECT NULL FROM a) AS c1, ref_0."?column?" AS c4 FROM b AS ref_0 WHERE EXISTS (SELECT FROM c AS ref_7 WHERE EXISTS (SELECT ref_0."?column?" AS c2)) OR ref_0."?column?" IS NOT NULL;
```
Fails with:
```
ERROR:  internal error: unimplemented join
```
Since it's an internal error it sounds like a bug. I guess the jsonb column might have something to do with it. I'll ignore the query error in SQLsmith for now, so this isn't blocking me or anything.

**Comment by philip-stoev** [comment]
@ggevay , @aalexandrov took a look at this and thinks that your changes from yesteday may be related.

**Comment by aalexandrov** [comment]
This is most likely a consequence of moving `JoinImplementation` to its own fixpoint loop in #17708.

**Comment by aalexandrov** [comment]
@ggevay This is most likely a consequence of moving `JoinImplementation` to its own fixpoint loop in #17708. Maybe we can just revert that bit as a quickfix and investigate what needs to be changed in order to make the above modification work separately.

**Comment by ggevay** [comment]
Thanks for finding this bug so quickly @def- ! I indeed introduced it just yesterday with https://github.com/MaterializeInc/materialize/commit/a98618b907df30b853f4817ad96d13092dd8f5b1.

I opened a PR to fix it, where I'm adding your above query into `joins.slt`.

**Comment by ggevay** [comment]
Btw. this query shows another, more subtle and less urgent bug in our optimizer: https://github.com/MaterializeInc/materialize/issues/17909
