### ISSUE TITLE
[SQLsmith] ERROR:  coalesce could not convert type character to "char"

### ISSUE THREAD

**Issue by def-** [MaterializeInc/materialize#17899]
### What version of Materialize are you using?

v0.45.0-dev (486332472)

### How did you install Materialize?

Built from source

### What is the issue?

Only a query error, so I can ignore it:
```
materialize=> SELECT COALESCE((SELECT collprovider FROM pg_catalog.pg_collation), CAST(NULL AS char(1))) AS c3;
ERROR:  coalesce could not convert type character to "char"
```
Also happens in the other direction:
```
materialize=> SELECT COALESCE(CAST(NULL AS char(1)), subq_0.c0) AS c5 FROM (SELECT ref_1.amtype AS c0 FROM pg_catalog.pg_am AS ref_1) AS subq_0;
ERROR:  coalesce could not convert type "char" to character
```

ci-regexp: coalesce could not convert type character
ci-regexp: coalesce could not convert type "char"

**Comment by chaas** [comment]
This looks to have the same cause as https://github.com/MaterializeInc/materialize/issues/17807 with something wonky in the `pg_catalog.char` type

**Comment by def-** [comment]
@sploiselle This appears not to be fully fixed yet:
```
materialize=> SELECT COALESCE((SELECT collprovider FROM pg_catalog.pg_collation), CAST(NULL AS char(1))) AS c3;
ERROR:  coalesce could not convert type character to "char"
materialize=> SELECT COALESCE(CAST(NULL AS char(1)), subq_0.c0) AS c5 FROM (SELECT ref_1.amtype AS c0 FROM pg_catalog.pg_am AS ref_1) AS subq_0;
ERROR:  coalesce could not convert type "char" to character
materialize=> select mz_version();
       mz_version
-------------------------
 v0.47.0-dev (e3b631cb2)
(1 row)
```
Or is this considered expected behavior now?

**Comment by sploiselle** [comment]
@def- This looks right to me––can I get a little more detail as to what the discrepancy is?

**Comment by def-** [comment]
I guess it's fine, and Postgres seems to have similar behavior.
