### ISSUE TITLE
Remove `CREATE VIEW <name> AS` from builtin view definitions.

### ISSUE THREAD

**Issue by jkosh44** [MaterializeInc/materialize#17892]
https://github.com/MaterializeInc/materialize/blob/5f379bde442940336bffe0e83b415a45797c7ffb/src/adapter/src/catalog/builtin.rs#L126-L131
When defining a builtin view, we specify the view name, schema, and sql which takes the form: `CREATE VIEW <schema>.<name> AS ...`. This leaves opportunity to accidentally create an inconsistency with the name and schema field and the name and schema in the sql definition. For example
https://github.com/MaterializeInc/materialize/blob/5f379bde442940336bffe0e83b415a45797c7ffb/src/adapter/src/catalog/builtin.rs#L2663-L2679

Instead, the `sql` field should just be the query that comes after `AS`. Then we can add the following function to `BuiltinView`:
```Rust
fn create_sql(&self) -> String {
  format!("CREATE VIEW {}.{} AS {}", self.schema, self.name, self.sql)
}
```

**Comment by d-sonuga** [comment]
Hi.

I want to work on this issue. Can I have it assigned to me?

**Comment by jkosh44** [comment]
> Hi.
> 
> I want to work on this issue. Can I have it assigned to me?

Yes, I just assigned it to you. Please let me know if you have any questions!

**Comment by d-sonuga** [comment]
Hey, I have a problem.
I can't run the unit/integration tests. The crates compile up to the last 1 to 3, then the OS kills the process.
Is there a minimum amount of RAM my computer must have for this, or is there any way to reduce the amount of
resources needed to run the tests?

**Comment by jkosh44** [comment]
> Hey, I have a problem. I can't run the unit/integration tests. The crates compile up to the last 1 to 3, then the OS kills the process. Is there a minimum amount of RAM my computer must have for this, or is there any way to reduce the amount of resources needed to run the tests?

I'm not sure if there's a specific amount of RAM needed, but compiling Materialize does usually need a large amount and it's not unheard of to OOM during compilation. Have you tried specifying `--jobs 1` in cargo to limit the parallelism in the compiler?

**Comment by friendlymatthew** [comment]
Hi Joe -- I would like to work on this 🤠

**Comment by jkosh44** [comment]
> Hi Joe -- I would like to work on this 🤠

Great! I'll assign the issue to you. Let me know if you have any questions.
