### ISSUE TITLE
Spike more efficient creation of spec-like tests for MIR transforms

### ISSUE THREAD

**Issue by aalexandrov** [MaterializeInc/materialize#17917]
Investigate the possibility of getting rid of `lowertest` in favor of a hand-rolled MIR parser so we can more easily create [spec-style tests](https://martinfowler.com/bliki/GivenWhenThen.html) for each transform.

If this is viable and economical, we can add tests while working on the transforms so we have isolated specification examples that demonstrate our current understanding of what each transform should do.

**Comment by ggevay** [comment]
Btw. I just now accidentally found an `MzReflect` usage that I'm not sure we should eliminate: `unary_func_introduces_nulls` in `scalar/func.rs`.

**Comment by aalexandrov** [comment]
> Btw. I just now accidentally found an `MzReflect` usage that I'm not sure we should eliminate: `unary_func_introduces_nulls` in `scalar/func.rs`.

I think we can just inline all `UnaryFunc` variants here.

**Comment by ggevay** [comment]
> I think we can just inline all UnaryFunc variants here.

Hmm, ok!

**Comment by antiguru** [comment]
Possibly related: #8111

**Comment by aalexandrov** [comment]
The spike was successful so far! I'll start adding tests in the next weeks (all in a private branch), and after that I can share what I have and we can decider whether to merge it and how to structure the PRs.
