### ISSUE TITLE
pg sources: accepts schema change when columns have same name

### ISSUE THREAD

**Issue by sploiselle** [MaterializeInc/materialize#17927]
### What version of Materialize are you using?

6dd84ed229cef7d65d11d605cadebe8bd3cadf8e

### How did you install Materialize?

Built from source

### What is the issue?

the following testdrive test passes on `main`

```
$ postgres-execute connection=postgres://postgres:postgres@postgres
ALTER USER postgres WITH replication;
DROP SCHEMA IF EXISTS public CASCADE;
DROP PUBLICATION IF EXISTS mz_source;

CREATE SCHEMA public;

CREATE TABLE alter_table_change_attnum (f1 VARCHAR(10), f2 VARCHAR(10));
ALTER TABLE alter_table_change_attnum REPLICA IDENTITY FULL;
INSERT INTO alter_table_change_attnum (f1, f2) VALUES ('f1_orig','f2_orig');

CREATE PUBLICATION mz_source FOR ALL TABLES;

> CREATE SOURCE mz_source
  FROM POSTGRES CONNECTION pg (PUBLICATION 'mz_source')
  FOR ALL TABLES;

> SELECT * from alter_table_rename_column;
f1_orig f2_orig

$ postgres-execute connection=postgres://postgres:postgres@postgres
ALTER TABLE alter_table_change_attnum DROP COLUMN f2;
ALTER TABLE alter_table_change_attnum ADD COLUMN f2 VARCHAR(10);
INSERT INTO alter_table_change_attnum (f1, f2) VALUES ('f1_changed', 'f2_changed');

# We have fooled the system into accepting this schema change while doing it online.
# Results should be
# f1_orig <null>
# f1_changed f2_changed
> SELECT * FROM alter_table_change_attnum;
f1_orig f2_orig
f1_changed f2_changed
```

However, this needs to error because the instance of `f2` in the final `SELECT` is not actually the same column.

My current thinking is that we can resolve this ambiguity with `attnum` which identifies the column with a monotonic number.

**Comment by philip-stoev** [comment]
You are evil :-)

This was reported previously as https://github.com/MaterializeInc/materialize/issues/6739. That ticket was used to do a lot of work on erroring out on schema changes, but apparently the original bug was never fixed and the test case provided back then was not added to `test/pg-cdc` .
