### ISSUE TITLE
Experiment with S3 versioning and lifecycle policies

### ISSUE THREAD

**Issue by bkirwi** [MaterializeInc/materialize#17926]
[S3 versioning](https://docs.aws.amazon.com/AmazonS3/latest/userguide/Versioning.html) allows keeping around multiple versions of each object in S3, including deleted versions. It's typically paired with an [expiration policy](https://docs.aws.amazon.com/AmazonS3/latest/userguide/lifecycle-expire-general-considerations.html) to avoid keeping around stale versions or tombstones forever.

Over the past months, we've run into a few cases where S3 versioning would have been useful:
1. When investigating a [persist GC performance bug](https://github.com/MaterializeInc/materialize/issues/17214), the GC eventually succeeded and deleted the bad state. We would have liked to keep that old state around for later analysis. Versioning would have allowed us to recover it.
2. It might help to derisk frightening changes, like [enabling deletes on a rare code path](https://github.com/MaterializeInc/materialize/pull/17292). Versioning would allow us to undelete blobs if we run into production bugs.
3. We've discussed using versioning as an element of a backup/restore in #17605.

Each of these has solutions that don't involve versioning. But in aggregate having versioning seems likely to be valuable.

The scariest thing about enabling versioning is that it's a whole-bucket setting; if a rollout goes badly it affects an entire S3 bucket. We'd probably want to leave versioning on for some extensive period in staging to shake out any issues before going to prod.

Personally I like versioning, because I am constitutionally rather nervous about bugs like 2., and I would be glad to have it enabled. But I think even if we think it's only _plausible_ that we want versioning, it would be worth enabling in staging earlier than later to derisk it as an option, so that we can roll it out to production quickly if we decide that's important.

**Comment by bkirwi** [comment]
I've posted the current state of the design for backup/restore at https://github.com/MaterializeInc/materialize/pull/18157. Still a draft, but I think the likelihood that we end up wanting S3 versioning for backups is now quite high.

**Comment by benesch** [comment]
@bkirwi shipped backup/restore last quarter, so calling this closed!
