### ISSUE TITLE
storage/sources/postgres: `SHOW CREATE SOURCE` contains a big hex encoded protobuf string

### ISSUE THREAD

**Issue by petrosagg** [MaterializeInc/materialize#17957]
During purification postgres sources resolve and store all the necessary information about the upstream schema for the replicated tables. In the past, for any additional information obtained from purification corresponded to some SQL syntax that in theory a user could type themselves, although in practice never did. Nevertheless, having a human readable output of what additional metadata we retrieved during purification is useful to debug issues and understand the state of the system.

For postgres sources we decided (can't remember the reasoning) to simply define a protobuf struct of the purification state and simply hex encode its binary representation in the SQL string. This makes it easy to parse and decode but horrible for users to interpret.

We should find a way to make `SHOW CREATE SOURCE` readable to users by either storing the purification metadata elsewhere or by inventing human readable syntax for them.

**Comment by benesch** [comment]
> This is part of our public API now; see: https://materialize.com/docs/sql/create-source/#protobuf
> 
> I think that means we're committed to it, for better or worse...

I don't think so? This isn't about the user-facing `FORMAT PROTOBUF` feature for Kafka, but the fact that `SHOW CREATE SOURCE` on a PostgreSQL source renders a bunch of unreadable hex-encoded Protobuf garbage.
