### ISSUE TITLE
materialize dataflow not show in ddshow 

### ISSUE THREAD

**Issue by code1704** [MaterializeInc/materialize#17969]
### What version of Materialize are you using?

v0.26.5

### How did you install Materialize?

Docker image

### What is the issue?

The dataflow (created by sql, e.g. select a+b from xx ...) not shown in ddshow. 

<img width="399" alt="image" src="https://user-images.githubusercontent.com/110730540/223228429-83f1f743-e10c-42d8-b4f1-9ec8daf555c8.png">

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/110730540/223228756-b8e1dd9d-3d6b-4aa3-b05b-8bb4445ee2bd.png">

**Comment by antiguru** [comment]
We don't support the `ddshow` tool for Materialize. Instead, it's better to use the built-in visualizer accessible through the HTTP endpoint (only locally), or follow #17563 for updates on what's available in the web console.

The reason why you might not see any dataflow is that `SELECT` only creates a short-lived dataflow, or doesn't create one if only an index lookup is needed to fulfill the request. Creating an index should result in a dataflow.

**Comment by code1704** [comment]
> We don't support the `ddshow` tool for Materialize. Instead, it's better to use the built-in visualizer accessible through the HTTP endpoint (only locally), or follow #17563 for updates on what's available in the web console.

@antiguru thanks. i'm new to materialize. how to open built-in visualizer?
