### ISSUE TITLE
cloudtest is flaky

### ISSUE THREAD

**Issue by jkosh44** [MaterializeInc/materialize#17965]
### Buildkite link

https://buildkite.com/materialize/tests/builds/50910#0186b7dc-2fbc-4540-bedc-bb57bf5accff

### Relevant log output

```source
N/A
```

### Additional thoughts

Cloudtest seems to be timing out regularly.

Two more instances:
- https://buildkite.com/materialize/tests/builds/50875#0186b6e0-ade8-4f7a-b5c7-f7ec8f7b1519
- https://buildkite.com/materialize/tests/builds/50916#0186b81f-6e99-4354-9346-5b243b1d8f7e

**Comment by def-** [comment]
This should be fixed by https://github.com/MaterializeInc/materialize/pull/17976, right @philip-stoev ?

**Comment by philip-stoev** [comment]
Yes, there have been no failures since.
