### ISSUE TITLE
Creating a source via the `IN CLUSTER` syntax results in a stuck source

### ISSUE THREAD

**Issue by parkerhendo** [MaterializeInc/materialize#17972]
### What version of Materialize are you using?

v0.45.0

### How did you install Materialize?

Materialize Cloud

### What is the issue?

When i create a source on an existing cluster via `... IN CLUSTER <cluster_name>`, the source remains stuck the **Created** state for an indefinite period of time.

**Steps to reproduce**
1. create a new cluster `c1`
2. create a new Kafka source (I'm using confluent cloud) using the new `CREATE SOURCE … IN CLUSTER c1` syntax
3. See the source stuck in the "Created" state in `mz_internal.mz_source_statuses`

When I create the exact same source and pass a `SIZE` instead of a cluster (the "old" way), the new source works as expected.

**Comment by benesch** [comment]
Closing as this must be fixed, given that we've had many customers successfully use `CREATE SOURCE ... IN CLUSTER`.
