### ISSUE TITLE
[SQLsmith] ERROR:  internal transform error: scalar types do not match: [ColumnType { scalar_type: String, nullable: false }] v [ColumnType { scalar_type: Bool, nullable: false }]

### ISSUE THREAD

**Issue by def-** [MaterializeInc/materialize#18023]
### What version of Materialize are you using?

v0.46.0-dev (ea8e22a62)

### How did you install Materialize?

Docker image

### What is the issue?

```
materialize=> SELECT mz_internal.mz_any(current_database());
ERROR:  internal transform error: scalar types do not match: [ColumnType { scalar_type: String, nullable: false }] v [ColumnType { scalar_type: Bool, nullable: false }]
```
But the individual parts work fine:
```
materialize=> select current_database();
 current_database
------------------
 materialize
(1 row)

materialize=> SELECT mz_internal.mz_any('materialize');
 ?column?
----------
 f
(1 row)
```
Optimizer problem I guess, also can't explain:
```
materialize=> explain SELECT mz_internal.mz_any(current_database());
ERROR:  internal transform error: scalar types do not match: [ColumnType { scalar_type: String, nullable: false }] v [ColumnType { scalar_type: Bool, nullable: false }]
```

ci-regexp:  internal transform error: scalar types do not match:

### Relevant log output

```source
environmentd: 2023-03-09T15:24:08.339683Z ERROR mz_transform: Optimizer::optimize(): internal transform error: scalar types do not match: [ColumnType { scalar_type: String, nullable: false }] v [ColumnType { scalar_type: Bool, nullable: false }]
```

**Comment by def-** [comment]
@sploiselle similar to https://github.com/MaterializeInc/materialize/issues/17762 ?

**Comment by teskje** [comment]
Related issue: https://github.com/MaterializeInc/materialize/issues/15805

In particular:
> Ah, interesting. I believe these functions are not meant to ever be called by the user directly, and only injected into the query as part of the planning process. We probably want a better way of doing that than mz_internal.

**Comment by sploiselle** [comment]
@def- sadly not that likely to be similar
