### ISSUE TITLE
Improve visibility into stalled sources

### ISSUE THREAD

**Issue by guswynn** [MaterializeInc/materialize#18029]
Incident 42 revealed 2 related issues:

- Certain types of error conditions in kafka sources appear to not cause rows to be written to `mz_source_status_history`
  - These were errors in connecting to the confluent schema registry. My understanding is that this might occur in decoding, which I don't think touches `mz_source_status_history` right now
  - a similar issue is here: https://github.com/MaterializeInc/materialize/issues/17924, where certain kinds of network hangups/long timeouts cause hangs as opposed to marking the sources as stalled
- The status of a source in `mz_source_statuses` should be marked with a prometheus metric. This is a direct parallel to how `mz_source_statistics` have prometheus metrics, which were explicitly useful in debugging the incident.

**Comment by guswynn** [comment]
The first fix might be a good issue for Mouli, ill look into the details!

**Comment by benesch** [comment]
The CSR issues were fixed at some point last year, and #17924 has been closed, so calling this complete!
