### ISSUE TITLE
Add health checks for connections

### ISSUE THREAD

**Issue by sjwiesman** [MaterializeInc/materialize#18035]
### Feature request

We might consider adding health checks for connection objects that test if they are reachable. This can help determine whether something is failing due to a bad private link setup or credentials. For kafka, this might be trying to make a TCP connection every minute. Regardless of whether the credentials are correct, just reaching the brokers provides information about the state of the system.

**Comment by benesch** [comment]
Going to close this in favor of #15082, which has quite a bit of background and philosophy! I'll add a note about PrivateLink specifically to that issue, though.
