### ISSUE TITLE
mz: control characters echoed into prompt

### ISSUE THREAD

**Issue by chuck-alt-delete** [MaterializeInc/materialize#18040]
### What version of Materialize are you using?

dad5ac14570921c92f0001cf49a3b42365e361a4

### How did you install Materialize?

Built from source

### What is the issue?

This is regarding the mz CLI. After pulling from main up to commit `dad5ac`, a couple of things broke in the CLI.

Internal slack thread:
- https://materializeinc.slack.com/archives/C04LQV4KUR4/p1678420588103899?thread_ts=1678391111.835539&cid=C04LQV4KUR4

Much of the behavior was fixed by commenting out this line: 
```
.args(["-c", "\\timing", "-f", "-"])
```
in [shell.rs](http://shell.rs/)

However, I am still prompted (twice) by Mac keyring whenever I use `mz shell`.

**Comment by RobinClowers** [comment]
Fixed by: https://github.com/MaterializeInc/materialize/pull/18058
