### ISSUE TITLE
Simplify/Refactor Catalog transactions

### ISSUE THREAD

**Issue by jkosh44** [MaterializeInc/materialize#18056]
The core of catalog transactions can be found here:

https://github.com/MaterializeInc/materialize/blob/5d94794ccb106e8cfbd37e7ca70316f01dc865e9/src/adapter/src/catalog.rs#L4327-L5754

For any type of catalog transaction this accomplishes three things:
- Updates the on disk catalog representation in the stash via a stash transaction.
- Updates the in memory catalog state.
- Generates updates to system tables.

The current catalog transaction is broken up into two phases `Op`s and `Action`s. It's not clear what the responsibilities of each phase is, what the differences between an `Op` and an `Action` are, or where/when each of the three changes should happen. Much of the current design is due to technical debt and and not a particularly good reason. This makes the methods difficult to read, understand, and reason about.

We should refactor these two methods to reduce the complexity and make it obvious that we are doing the right things in all cases. For example, each note like this seems like a bug waiting to happen: https://github.com/MaterializeInc/materialize/blob/5d94794ccb106e8cfbd37e7ca70316f01dc865e9/src/adapter/src/catalog.rs#L4540-L4541. I would suggest removing `Action`s entirely and co-locating all of the logic for a single `Op`.

Additionally we should double check that we have tests for every different type of `Op`, and in those tests we make sure that the affected system tables are still in a valid state.

**Comment by benesch** [comment]
> Additionally we should double check that we have tests for every different type of `Op`, and in those tests we make sure that the affected system tables are still in a valid state.

Yes, this, please!

**Comment by jkosh44** [comment]
I'm going to re-open this issue. Although #18101 was a huge step in the right direction there's a couple of other things that I think need cleaning up. Maybe these each warrant their own issue.

## Builtin Table Updates

I think that all of the `pack_X_update` functions found in https://github.com/MaterializeInc/materialize/blob/main/src/adapter/src/catalog/builtin_table_updates.rs should be made to have a consistent format. Some of the functions behave differently, and I haven't been able to figure out if there's a specific reason. The formats I've seen are:

  1. Accept unique identifiers for object X as parameters, look up the object in the state, use the found object to generate the row. An example is here: https://github.com/MaterializeInc/materialize/blob/e95f3e5e858b5328d1c4d79e3912ea0fc8f31478/src/adapter/src/catalog/builtin_table_updates.rs#L128-L149
  2. Accept a name for object X as parameters, look up the object in the state, use the found object to generate the row. An example is here: https://github.com/MaterializeInc/materialize/blob/e95f3e5e858b5328d1c4d79e3912ea0fc8f31478/src/adapter/src/catalog/builtin_table_updates.rs#L174-L186
  3. Accept a reference to a catalog object corresponding to X as a parameter, use the parameter to generate information for the row. An example is here: https://github.com/MaterializeInc/materialize/blob/e95f3e5e858b5328d1c4d79e3912ea0fc8f31478/src/adapter/src/catalog/builtin_table_updates.rs#L85-L100
  4. Accept all the relevant row information for object X as parameters, use the parameters to generate the row. An example is here: https://github.com/MaterializeInc/materialize/blob/e95f3e5e858b5328d1c4d79e3912ea0fc8f31478/src/adapter/src/catalog/builtin_table_updates.rs#L517-L532

If possible I think we should pick one of these format, refactor all of the methods to match the chosen format, and add a comment to the top of the file explaining the approach to add a new method.

Personally I find format (1) to be the best. 

Format (3) I find to be especially problematic. Format 3 requires a reference to some catalog object, which usually requires taking a reference on the `CatalogState`. Then to call the `pack_X_update` method requires another reference on `CatalogState`. This causes a lot of headaches to ensure both references are immutable, especially in update/alter `Op`s.

## Validations

For me it's not always clear where to add a certain validation for a specific statement. The three possible locations are:

1. The planner
2. The sequencer
3. The catalog transaction

Looking through the code it seems like for certain validations, we don't have a consistent story. For example, preventing users from interacting with system objects happens in the planner: https://github.com/MaterializeInc/materialize/blob/e95f3e5e858b5328d1c4d79e3912ea0fc8f31478/src/sql/src/plan/statement/ddl.rs#L3511-L3516
and the catalog transaction:
https://github.com/MaterializeInc/materialize/blob/e95f3e5e858b5328d1c4d79e3912ea0fc8f31478/src/adapter/src/catalog.rs#L4408-L4415

I think that we should clarify which types of validations belong where and add a comment to the relevant files/methods to make this obvious. Then we can pull some validations out of catalog transactions and push others into it.

## Structure of All `Op`s

This one is a bit of a nit and a nice to have, but I think that all `Op`s within a catalog transaction should follow the same general structure and order of operations. The only difference in the structure from `Op` to `Op` would be that some `Op`s leave out a step. For example, here's one idea for the structure:
  
1. Generate builtin table retractions.
2. Update in memory catalog.
3. Update stash.
4. Generate builtin table additions.

Add `Op`s would leave out step 1, while Drop `Op`s would leave out step 4. I think we should have this written down in a comment at the top of `transact_inner` and have all `Op`s conform to this structure (or one like it). It's useful because accidentally switching steps (1) and (2) can result in an invalid retraction and corrupt the system catalog. So having a template to follow will help eliminate those types of bugs.

An even smaller nit that's part of this is that some Update `Op`s will remove an item from the in-memory catalog and then insert an updated version, while others will update the in-memory catalog in-place. I think we should pick one and do that for all updates possible, with my preference being to update the catalog in place since it has slightly better performance.
