### ISSUE TITLE
Tighten wildcard CORS matching

### ISSUE THREAD

**Issue by RobinClowers** [MaterializeInc/materialize#18063]
### Feature request

When we originally added support for wildcard CORS in https://github.com/MaterializeInc/materialize/pull/17711, it was implemented as `*.foo.com` would match anything that ended in `foo.com` (including the top level `foo.com`), but in practice I think it would be more useful if it only matched when there is a subdomain. So for example, we could have a rule for `*.console.materialize.com`, which would match any subdomain, but *not* `console.materialize.com`. Currently we don't have a way to express that distinction.

@mjibson @necaris @benesch thoughts on this?

**Comment by benesch** [comment]
I think it already works as you request?

https://github.com/MaterializeInc/materialize/blob/2b86c94f0305825fa20fbbcccaafbd74b0e7cdbb/src/http-util/src/lib.rs#L286-L297

That test verifies that "*.example.org" allows "https://foo.example.org" but _not_ "https://example.org".

**Comment by RobinClowers** [comment]
Looks like you are right, I should have read the tests instead of the code :)
