### ISSUE TITLE
Improve error message when trying to use invalid operator

### ISSUE THREAD

**Issue by sploiselle** [MaterializeInc/materialize#1808]
@ruchirK discovered this, which might be able to be improved with a simple rewrite:

```sql
materialize=> SELECT 'dog'->>'woof';
```
```
ERROR:  No overload for string ->> string
```

The term "no overload for" confused me; I had to have it explained to me that this is, in fact, a type error.

However, the Postgres message is a little more edifying:

```
ERROR:  operator is not unique: unknown ->> unknown
LINE 1: SELECT 'dog'->>'woof';
                    ^
HINT:  Could not choose a best candidate operator. You might need to add explicit type casts.
```

I'd like to see something more akin to the Postgres message, which is a little more helpful in helping you figure out you might try adding a cast to get the operator to work. Maybe

```
ERROR: Unknown operator: string ->> string
HINT: Add casts to left- or right-hand side to match operator signature at mtrlz.io/functions
```

**Comment by benesch** [comment]
This has been improved:

```
ERROR:  no overload for string + i32: arguments cannot be implicitly cast to any implementation's parameters; try providing explicit casts
```
