### ISSUE TITLE
sqllogictest: specify halt behavior for long running tests

### ISSUE THREAD

**Issue by mjibson** [MaterializeInc/materialize#18098]
Some nightly slt tests exceed our 10h timeout. We don't know which tests these are. We'd like to not disable the entire slt nightly run just because of them. In the short term we would like to:

Teach the slt binary to take a timeout duration and action. For tests that exceed the timeout, the test is halted and the action performed. The action can be to error the test or log/print the timedout test. This will allow us to run the nightly tests in a "run everything that executes in under 10h" mode, and have it print the long tests. We can use that for local dev to determine what is causing the slow tests to be slow.

**Comment by philip-stoev** [comment]
Assigning all sqllogictest related tickets to @def- . will discuss during the QA weekly meeting.

**Comment by def-** [comment]
I think this might not be necessary anymore. sqllogictest pipeline is ok again with having split the tests into 10 parts, unfortunately every query seems to have gotten slower, not anything specific.
