### ISSUE TITLE
Add way to identify if cluster load is coming from the console UI or end user queries

### ISSUE THREAD

**Issue by chaas** [MaterializeInc/materialize#18094]
Recently we've seen issues (#18075) where customers' `mz_introspection` clusters are getting overloaded, and right now there's no way to see whether it's because of user actions (e.g. user requests on the cluster) or the console UI making API requests.

We should:
1) Figure out if there is currently any way to distinguish the origin of queries in a) metrics tools like grafana and b) any other debugging that support does
2) If not, add it. This may require propagating some data thru the adapter that's only available now at the request layer.

Pre-work:
Understand the data that support and oncall engineers look at when investigating load on a cluster (e.g. which grafana metrics, which queries do they try and run on the environment)

**Comment by parker-timmerman** [comment]
Fixed with:
- https://github.com/MaterializeInc/materialize/pull/18426
- https://github.com/MaterializeInc/console/pull/78

**Comment by ggnall** [comment]
@parkerhendo can you discuss a follow up on this data with @matthelm ? It would be great to filter analytics events (in amplitude and other tools) by whether the actions are performed through the web console or various other tools.
