### ISSUE TITLE
Unexpected plan success: No division by zero error

### ISSUE THREAD

**Issue by def-** [MaterializeInc/materialize#18153]
### What version of Materialize are you using?

v0.47.0-dev (e019f665e)

### How did you install Materialize?

Built from source

### What is the issue?

```
materialize=> SELECT - - 96 * 11 * + CASE WHEN NOT + 84 NOT BETWEEN 27 / 0 AND COALESCE ( + 61, + AVG ( 81 ) / + 39 + COUNT ( * ) ) THEN - 69 WHEN NULL > ( - 15 ) THEN NULL ELSE NULL END AS col2;
 col2
------

(1 row)
```
On postgres:
```
deen=> SELECT - - 96 * 11 * + CASE WHEN NOT + 84 NOT BETWEEN 27 / 0 AND COALESCE ( + 61, + AVG ( 81 ) / + 39 + COUNT ( * ) ) THEN - 69 WHEN NULL > ( - 15 ) THEN NULL ELSE NULL END AS col2;
ERROR:  division by zero
```
Noticed via the long SLT run which finishes again (barely): https://buildkite.com/materialize/sql-logic-tests/builds/5489

**Comment by def-** [comment]
@petrosagg Git bisect result:
```
45291097dfe28d45b86185aaba35b063908122ed is the first bad commit
commit 45291097dfe28d45b86185aaba35b063908122ed
Author: Petros Angelatos <petrosagg@gmail.com>
Date:   Thu Feb 23 13:05:11 2023 +0100

    expr: deterministic logical operators

    The current implementation of logical operators suffers from
    non-determinism because there are two separate short-circuit execution
    paths and which one comes first is dependent on how the optimizer
    chooses to optimize an expression.

    This PR keeps the short-circuit behavior of logical operators in the
    presence of `false` and `true` items for `AND` and `OR` respectively and
    removes the short-circuit path of errors. This means that in the absence
    of errors the implementation is just as fast and in the presence of
    errors we maintain our correctness properties.

    The new implementation has the property that `A && B == B && A` and `A
    || B == B || A` in all cases. They implement the following truth tables:

    ```
    | A    | B    | A && B      | B && A
    |------|------|-------------|--------
    | T    | T    | T           | T
    | T    | F    | F           | F
    | T    | null | null        | null
    | T    | E    | E           | E
    | F    | T    | F           | F
    | F    | F    | F           | F
    | F    | null | F           | F
    | F    | E    | F           | F
    | null | T    | null        | null
    | null | F    | F           | F
    | null | null | null        | null
    | null | E    | E           | E
    | E    | T    | E           | E
    | E    | F    | F           | F
    | E    | null | E           | E
    | E1   | E2   | max(E1, E2) | max(E1, E2)
    ```

    ```
    | A    | B    | A || B      | B || A
    |------|------|-------------|--------
    | T    | T    | T           | T
    | T    | F    | T           | T
    | T    | null | T           | T
    | T    | E    | T           | T
    | F    | T    | T           | T
    | F    | F    | F           | F
    | F    | null | null        | null
    | F    | E    | E           | E
    | null | T    | T           | T
    | null | F    | null        | null
    | null | null | null        | null
    | null | E    | E           | E
    | E    | T    | T           | T
    | E    | F    | E           | E
    | E    | null | E           | E
    | E1   | E2   | max(E1, E2) | max(E1, E2)
    ```

    Signed-off-by: Petros Angelatos <petrosagg@gmail.com>

 src/expr/src/scalar/func.rs | 38 ++++++++++++++++++++++----------------
 1 file changed, 22 insertions(+), 16 deletions(-)
```

**Comment by petrosagg** [comment]
This is a known difference that we introduced between materialize an postgres in the commit you bisected to. The order of execution of logical operations in SQL is unspecified and we have chosen to always pick the same result no matter what the order of the argument is which is necessary to ensure other correctness properties of our dataflow rendering.

Where is this test defined? Is it autogenerated?

**Comment by def-** [comment]
Alright, good. Yes, the test is auto-generated and I have a change open to change the expected value already for us: https://github.com/MaterializeInc/materialize/pull/18154
