### ISSUE TITLE
Rework `fold_constants` so it is `recursion_safe`

### ISSUE THREAD

**Issue by aalexandrov** [MaterializeInc/materialize#18163]
### Size estimate

S

### Notes

Constant propagation through bindings is done in `NormalizeLets`, but the `LetRec` case currently returns an error.

### `LetRec` implementation (basic)

Just remove the 
```rust
Err(crate::TransformError::LetRecUnsupported)?;
```
clause from the `MirRelationExpr::LetRec` case in `FoldConstants::action`.

### `LetRec` implementation (advanced)

We could to something similar to the "basic" or even of the "advanced" case of `column_knowledge`:

1. Introduce a context with the current bindings.
2. On `LetRec`, extend this context with the `ids` of the enclosing `LetRec` node and update those iteratively, descending sequentially in `FoldConstants::action` to each binding before descending to the body. 
3. Doing the above step once is akin to how we estimate `column_knowledge` now, doing it until the bindings converge before we move to the body is akin to the proposed "advanced" scheme in `column_knowledge`.

### Open questions

1. Can the _inductive case_ from the **Implementation sketch** above diverge? (cc: @mgree I think in our offline discussion earlier today you came up with some good reasons against that concern)

**Comment by aalexandrov** [comment]
@ggevay assigning this to myself as this is one of the three that will also enable `FuseAndCollapse` (the others are `redundant_join` and `projection_lifting`).

**Comment by ggevay** [comment]
> Can the inductive case from the Implementation sketch above diverge?

I think we'll have to limit the maximum number of iterations similarly to https://github.com/MaterializeInc/materialize/issues/16800
