### ISSUE TITLE
Warn or deny on missing doc comments in `mz-timely-util`

### ISSUE THREAD

**Issue by tokenrove** [MaterializeInc/materialize#18192]
Since these are all library functions intended to be consumed repeatedly, it would make sense to enforce documenting them.

Checklist:
 - [ ] `src/timely-util/src/lib.rs:88:1` - `pub mod antichain;`
 - [ ] `src/timely-util/src/antichain.rs:20:1` - `pub trait AntichainExt {`
 - [ ] `src/timely-util/src/antichain.rs:21:5` - `type Pretty<'a>: Display`
 - [ ] `src/timely-util/src/antichain.rs:25:5` - `fn pretty(&self) -> Self::Pretty<'_>;`
 - [ ] `src/timely-util/src/antichain.rs:52:1` - `pub struct FrontierPrinter<F>(F);`
 - [ ] `src/timely-util/src/lib.rs:89:1` - `pub mod buffer;`
 - [ ] `src/timely-util/src/builder_async.rs:223:1` - `pub trait CapabilityTrait<T: Timestamp> {`
 - [ ] `src/timely-util/src/builder_async.rs:224:5` - `/     fn session<'a, D, P>(`
 - [ ] `src/timely-util/src/builder_async.rs:261:1` - `pub struct AsyncOutputHandle<T: Timestamp, D: Container, P: Push<BundleCore<T, D>> + 'static> {`
 - [ ] `src/timely-util/src/builder_async.rs:297:5` - `pub async fn give_container<C: CapabilityTrait<T>>(&mut self, cap: &C, container: &mut D) {`
 - [ ] `src/timely-util/src/builder_async.rs:314:5` - `pub async fn give<C: CapabilityTrait<T>>(&mut self, cap: &C, data: D) {`
 - [ ] `src/timely-util/src/lib.rs:91:1` - `pub mod capture;`
 - [ ] `src/timely-util/src/capture.rs:19:1` - `pub struct UnboundedTokioCapture<T, D>(pub UnboundedSender<EventCore<T, D>>);`
 - [ ] `src/timely-util/src/order.rs:173:1` - `pub struct PartitionedSummary<P: Partition, T: Timestamp>(`
 - [ ] `src/timely-util/src/lib.rs:95:1` - `pub mod panic;`
 - [ ] `src/timely-util/src/lib.rs:96:1` - `pub mod probe;`
 - [ ] `src/timely-util/src/probe.rs:59:1` - `pub struct Handle<T: Timestamp> {`
 - [ ] `src/timely-util/src/lib.rs:98:1` - `pub mod reduce;`

**Comment by benesch** [comment]
Closing as stale.
