### ISSUE TITLE
Numeric precision does not always agree with postgres

### ISSUE THREAD

**Issue by jamii** [MaterializeInc/materialize#1824]
Originally discussed in https://github.com/MaterializeInc/materialize/issues/1653, leaving this open as a tracker. 

Materialize:

```
jamie=> SELECT COALESCE ( - 25, 33 * AVG ( 43 ) );
     coalesce     
------------------
 -25.000000000000
(1 row)

jamie=> SELECT COALESCE ( - 25, AVG ( 43 ) );
  coalesce  
------------
 -25.000000
(1 row)
```

Postgres:

```
jamie=# SELECT COALESCE ( - 25, 33 * AVG ( 43 ) );
 coalesce 
----------
      -25
(1 row)

jamie=# SELECT COALESCE ( - 25, AVG ( 43 ) );
 coalesce 
----------
      -25
(1 row)
```

Because we choose precision at planning time rather then recording it in the value, values that at runtime turn out not to affect the result can still alter it's precision. This may be essential for fast incremental maintenance of aggregates over decimal types, so we're not looking to change it atm.

**Comment by benesch** [comment]
We're swapping out our decimal implementation, and now we have a new issue to track this: #6846.
