### ISSUE TITLE
An `mz_sessions` system table

### ISSUE THREAD

**Issue by teskje** [MaterializeInc/materialize#18289]
### Feature request

Adapter should expose an `mz_sessions` system table that lists active user sessions and maps session IDs to user names (and possibly other relevant information, like when the session was started).

Once we have that table, we should adjust the schema of `mz_subscriptions` by replacing the `user` column with a `session_id`/`connection_id` column that is a foreign key into `mz_sessions`. This would enable users to more accurately map their active subscribes to sessions they have started.

**Comment by teskje** [comment]
Motivated by @benesch's comment [in Notion](https://www.notion.so/Weekly-Product-Updates-46515707eba84deab6d6d3cd4bb2768a?d=c1a2cddbfb6f43c1b0f6efbfa2173e96#16b4bc387f684391b5442609b03dada8).

**Comment by jkosh44** [comment]
Since `mz_sessions` will be a table, I think we should use `role_id` instead of `user`, to conform to our normalization standard in the style guide:
https://github.com/MaterializeInc/materialize/blob/main/doc/developer/style.md#system-catalog-style

**Comment by benesch** [comment]
Yes, 100% agree!
