### ISSUE TITLE
Implement Slow Query Logging

### ISSUE THREAD

**Issue by materializesupport** [MaterializeInc/materialize#18318]
### Feature request

To help identify slow running queries that impact system performance, we should implement a form of slow query logging with a user-definable time limit that captures the query being executed and conditionally, the length of time the query has been executing or the length of time it took to execute the query (this allows us to account for queries currently executing and those that have fully executed).

As an example (in PostgreSQL), an entry would look something like:

```
2023-03-21 12:00:59 LOG: duration: 15000ms statement: SELECT
```

If implemented using JSON, an entry may look like:

```
{"[uuid]": { "timestamp": 1679444386, "query": "SELECT ....", "duration": 15000 }  }
```

**Comment by sjwiesman** [comment]
cc @ggnall

**Comment by benesch** [comment]
Throwing this onto the surfaces team board.

**Comment by chaas** [comment]
@benesch I saw in your thread you mentioned wanting these to be user facing. As far as I know, we don't provide any customer-facing logs. Perhaps I'm wrong?
Were you thinking we'd emit these alongside the response?
Or write these to our internal logs, which we then forward and/or write in parallel to some new customer facing logs?

**Comment by sjwiesman** [comment]
I was thinking this would be an mz_catalog table

**Comment by benesch** [comment]
Yes, what @sjwiesman said! I was envisioning a Materialize equivalent of Snowflake's [`QUERY_HISTORY` table](https://docs.snowflake.com/en/sql-reference/functions/query_history).

**Comment by chaas** [comment]
Is there a concern right now about this table getting arbitrarily big, since we don't support data expiration?
We could do the same "hack" we do for `mz_source_statistics` where they are reset to 0 on restart, but I don't love that either.
Or something similar where on bootstrap we delete data older than some retention period?

**Comment by ggnall** [comment]
User queries will be made available in https://github.com/MaterializeInc/cloud/issues/6428

Users will be able to sort and filter queries in `mz_statement_execution_history` by duration, or create views for queries `where duration > [some threshold]`

We also plan to have some UI for surfacing these and other problematic queries https://github.com/MaterializeInc/console/issues/259

May be worth revisiting after those pieces land.

**Comment by benesch** [comment]
Huge 👍🏽 from me on closing this. The log for _all_ queries, not just slow queries, is strictly better than the slow query log!
