### ISSUE TITLE
Test an upgrade chain X versions back?

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#18326]
Nice. Do we want to do this even further and have an upgrade chain X versions back?

_Originally posted by @def- in https://github.com/MaterializeInc/materialize/issues/18324#issuecomment-1479235544_

**Comment by def-** [comment]
I guess patch versions would end up being pretty slow with many releases.

**Comment by philip-stoev** [comment]
Implemented as https://github.com/MaterializeInc/materialize/pull/18558
