### ISSUE TITLE
Connecting to Kafka via SSH bastion flakey 

### ISSUE THREAD

**Issue by sjwiesman** [MaterializeInc/materialize#18333]
### What version of Materialize are you using?

v0.47.0 (613cca5c0)

### How did you install Materialize?

Materialize Cloud

### What is the issue?

We've witnessed multiple instances where creating a Kafka source that proxies via an ssh bastion fails the first time but succeeds on the second to third attempt. No configurations were changed between source creation attempts. 

It's unclear if the bastion is returning an error that indicates an automatic retry is required, or there is a missing startup step to open the connection, but if the connection can succeed it should on the first attempt. 

cc @sthm @dseisun-materialize

**Comment by sjwiesman** [comment]
@philip-stoev confirmed its' the customer environment I was referencing. And the timestamp aligns with when I witnessed this happen.

**Comment by sthm** [comment]
I've run this from my staging account `aws-us-east-1-a0c3a1e9-854d-4208-bd4e-387c1dad13ad-0`. There is a slight chance that I ran it from eu-west-1 rather than us-east-1. The approximate timestamp is Mar 17 around 12pm UTC. I ran several tests at that time, so you'll find more successful and unsuccessful source creation attempts around that time.

**Comment by sthm** [comment]
Here's some context from the private slack conversation on this. We have already concluded, that the source/destination check is unlikely to be the root cause.

> I don’t know why, but when I enable the source/destination check on my instance, it takes several attempts to create a connection. So Nikhil was once again right and I’m seeing something different.

Source/destination check disabled:
```
materialize=> CREATE SOURCE json_source                                                                                                                                                                                                                                         FROM KAFKA CONNECTION kafka_connection (TOPIC 'test')
FORMAT BYTES
WITH (SIZE = '3xsmall');
CREATE SOURCE
materialize=> drop source json_source;
```

Source/destination check enabled:
```
materialize=> CREATE SOURCE json_source
FROM KAFKA CONNECTION kafka_connection (TOPIC 'test')
FORMAT BYTES 
WITH (SIZE = '3xsmall');
ERROR:  Failed to create and connect Kafka consumer: librdkafka: [thrd:sasl_ssl://bbb.c13.kafka.us-east-1.amazonaws.]: sasl_ssl://bbb.c13.kafka.us-east-1.amazonaws.com:9096/bootstrap: Connect to ipv4#127.0.0.1:55060 failed: Connection refused (after 0ms in state CONNECT)

materialize=> CREATE SOURCE json_source
FROM KAFKA CONNECTION kafka_connection (TOPIC 'test')
FORMAT BYTES
WITH (SIZE = '3xsmall');
ERROR:  Failed to create and connect Kafka consumer: librdkafka: [thrd:sasl_ssl://bbb.c13.kafka.us-east-1.amazonaws.]: sasl_ssl://bbb.c13.kafka.us-east-1.amazonaws.com:9096/bootstrap: Connect to ipv4#127.0.0.1:55663 failed: Connection refused (after 0ms in state CONNECT)

materialize=> CREATE SOURCE json_source
FROM KAFKA CONNECTION kafka_connection (TOPIC 'test')
FORMAT BYTES
WITH (SIZE = '3xsmall');
CREATE SOURCE
```

> But something seems to be going on as this is reproducible. After I enable the check, several attempts fail. But once the source is created successful, recreating the source works on every subsequent attempt. When I disable and enable the check again, the cycle restarts and creating the source fails for several attempts (even when waiting minutes between attempts) before it starts working again. What’s suspicious is that it always seems to work on the 3rd attempt, regardless of how long I wait in between.

**Comment by guswynn** [comment]
> @guswynn — this looks like Kafka is failing to connect to the local SSH tunnel port. Is there a race condition, where we're firing librdkafka at the tunnel before ssh has actually started listening on that port?

Yes I have seen this before, where rdkafka attempts to use the socket too early. A bit of a wait in the async function the starts the tunnel should work

**Comment by benesch** [comment]
Mercifully, I think we can finally call this fixed. There have been many fixes to SSH tunneling in the past few months, but I think the ones that made the largest dent in this particular issue are #18371 and #18547.
