### ISSUE TITLE
Clean up Coordinator

### ISSUE THREAD

**Issue by cuongdo** [MaterializeInc/materialize#1835]
There has been a growing chorus of concerns regarding the Coordinator. We should take a look at the overall structure of Coordinator and make it easier to understand and extend.

cc @frankmcsherry @benesch @wangandi who can fill in more details

**Comment by cuongdo** [comment]
Sadly removing from 0.2. I believe that we should bundle this work with a significant feature that touches Coordinator.

**Comment by sploiselle** [comment]
@jkosh44 Underwent a heroic effort to do this long ago. Not that there isn't more work to do, but the original pain point that caused this issue is done.
