### ISSUE TITLE
Debugging support for WMR dataflows

### ISSUE THREAD

**Issue by aalexandrov** [MaterializeInc/materialize#18362]
Citing @frankmcsherry from #18113 

> An ~different~ additional guard rail we could use, and probably want anyhow, is to allow the user to bound the number of iterations. I'm guessing that debugging recursive queries is annoying, and a reasonable pattern is to look at the results after one iteration, two iterations, etc. You could change the query to time itself out (with some counter), but it's plenty easy for DD to handle this for you if you have an upper bound on number of iterations.
> 
> More generally .. though I'm sure also more frighteningly .. this could just be a temporal filter on round of iteration, which DD supports also (well, manipulation of the timestamp component, which is what temporal filters end up being).

From some [proposed alternatives](https://github.com/MaterializeInc/materialize/issues/16800#issuecomment-1456421313) it seems that the most elegant solution is to extend the WMR syntax with an optional clause, so a user can write:

```sql
WITH MUTUALLY RECURSIVE LIMIT :x
```

to indicate that they want to stop the recursive computation after `x` iterations (where `x > 0`).

See also here: https://materializeinc.slack.com/archives/C02CB7L4TCG/p1678266977745819?thread_ts=1678266846.169599&cid=C02CB7L4TCG

**Comment by aalexandrov** [comment]
Until we have this, here is a relatively straight forward way to emulate this directly in SQL.

Let's say we have the following schema
```sql
CREATE TABLE edges (src INTEGER, dst INTEGER);
INSERT INTO edges values (1, 2), (2, 3), (3, 4), (4, 5);
```
and the following reachability query
```sql
WITH MUTUALLY RECURSIVE
  reach(x integer, y integer) AS (
    SELECT * FROM (
      -- last iteration result
      SELECT * FROM reach
      
      UNION ALL
      
      -- base case
      SELECT * FROM edges
      
      UNION
      
      -- induction step
      SELECT a.x, b.y 
      FROM reach AS a, reach AS b
      WHERE a.y = b.x
    )
  )
SELECT * FROM reach;
```
We can mechanically modify this query to see the results after `n` iterations as follows:
```sql
WITH MUTUALLY RECURSIVE
  it(count integer) AS (
    SELECT GREATEST(1, (SELECT LEAST(count + 1, $m) FROM it))
  ),
  reach(x integer, y integer) AS (
    SELECT * FROM (
      -- last iteration result
      SELECT * FROM reach
      
      UNION ALL
      
      -- base case
      SELECT * FROM edges
      
      UNION
      
      -- induction step
      SELECT a.x, b.y 
      FROM reach AS a, reach AS b, it
      WHERE a.y = b.x AND it.count <= $n
    )
  )
SELECT * FROM reach;
```

The diff consists of two parts:

1. An extra WMR binding `it` that starts from `1` and goes up to `$m >= $n` with an increment of `1` per iteration step. This part will never change.
2. For every induction query: an extra `FROM` clause that selects `it` and an extra `WHERE` clause `it.count <= $n`.

The downside of this approach (besides requiring manual rewrites) is that the extra `it` source in the inductive part of the WMR recursion will lead to a cross join. It would be great if this can run as a cross join, but unfortunately at the moment I don't think this is possible.

**Comment by aalexandrov** [comment]
> You could change the query to time itself out (with some counter), ...

@frankmcsherry I suppose the suggestion :point_up: is an instance of what you meant here.

**Comment by sthm** [comment]
This is pretty cool for debugging purposes! Will this keep working if the fixpoint operation does not terminate? Eg, if `reach` has a bug and keeps growing on every iteration, is the query optimizer smart enough to understand that the where clause will filter any new edges once `it.count > :n` and terminate the computation so that the output of the `SELECT * FROM reach` can be generated?

**Comment by aalexandrov** [comment]
> Will this keep working if the fixpoint operation does not terminate?

I believe so, yes. It's not something that the query optimizer needs to understand. By placing the `it.count > :n` clauses at the right positions in the original query you ensure that `reach` will stops growing after `:n` iterations.

**Comment by sthm** [comment]
Of course. `reach ` will automatically just stop growing. 🤦
