### ISSUE TITLE
Add default SSH TUNNEL option for Kafka connections

### ISSUE THREAD

**Issue by sthm** [MaterializeInc/materialize#18375]
### Feature request

When creating a Kafka connection over SSH, each broker needs to have an option that tells Materialize to connect to that specific broker over the ssh tunnel.

```sql
CREATE CONNECTION kafka_connection TO KAFKA (
    BROKERS (
        'broker1:9092' USING SSH TUNNEL ssh_connection,
        'broker2:9092' USING SSH TUNNEL ssh_connection
         -- Add all Kafka brokers
    ),
    ...
)
```

This seems error prone as users may inadvertently forget to add brokers or just add an bootstrap broker string that is different from the actual brokers. Moreover, if a Kafka cluster is scaled and new brokers are added to the cluster, Materialize will not be able to connect to the new brokers over the existing ssh connection.

We have discussed [in this thread](https://materializeinc.slack.com/archives/CU7ELJ6E9/p1679589514629989) how adding a SSH TUNNEL option to the connection rather then individual brokers can help mitigate these problems. By default, the `ssh_connection_default` connection is used for communication with the cluster with the option to overwrite that setting for individual brokers (`ssh_connection_override`).

```sql
CREATE CONNECTION kafka_connection TO KAFKA (
    BROKERS (
        -- Uses default SSH tunnel.
        'broker1:9092'
        'broker2:9092' USING SSH TUNNEL ssh_connection_override
         -- No need to list all brokers explicitly; any unlisted brokers will use the default SSH tunnel.
    ),
    SSH TUNNEL ssh_connection_default,
    ...
);
```

@josharenberg and @guswynn have furthermore pointed out that it makes sense for improving the availability of the connection to allow a list of ssh connections rather than a single one.

**Comment by benesch** [comment]
cc @dseisun-materialize
