### ISSUE TITLE
Use consistent names in the catalog/parser/planner

### ISSUE THREAD

**Issue by jkosh44** [MaterializeInc/materialize#18463]
In some contexts `Object` refers to anything that a user can create or drop (something that would be assigned an OID in PostgreSQL). 

https://github.com/MaterializeInc/materialize/blob/52261cd8091679b1b86f9c9fc86ae67c1f1ddf61/src/sql-parser/src/ast/defs/statement.rs#L2283-L2298

In other contexts `Object` refers to something that lives in a schema (i.e. something identified by a `GlobalId`).

https://github.com/MaterializeInc/materialize/blob/52261cd8091679b1b86f9c9fc86ae67c1f1ddf61/src/sql/src/names.rs#L370-L386

Additionally we use `Item` to refer to things that live in a schema.

https://github.com/MaterializeInc/materialize/blob/52261cd8091679b1b86f9c9fc86ae67c1f1ddf61/src/sql/src/catalog.rs#L440-L444

I think it would reduce confusion if we used these terms consistently and updated the code to match their meaning. My personal preference would be:
- `Object` should refer to anything that a user can create or delete (something with an OID in PostgreSQL).
- `Item` should refer to anything that lives in a schema.

**Comment by jkosh44** [comment]
@andrewrodriguez-m Can we close this issue?

**Comment by andrewrodriguez-m** [comment]
Yea I think so. I just did another pass, seems like the Object/Item usages are pretty aligned

**Comment by sploiselle** [comment]
propagating this distinction in its current form into doc strings somewhere in the parser would be enormously helpful. Right now `ItemName` is described as:

> /// The type used for table references.

And `ObjectName` has the wonderfully tautological:

> /// They type used for any object names.
