### ISSUE TITLE
docs: Sketch a new docs information architecture

### ISSUE THREAD

**Issue by jseldess** [MaterializeInc/materialize#18508]
### Documentation request

A good docs information architecture anticipates and mirrors the needs of users through different types of documentation: 
- **Guides/how-tos/recipes:** All users need guidance to understand and use the product successfully. Guidance can be _proactive_ (how to do it right from the start) or _reactive_ (how to know what to do differently, e.g., optimizing/troubleshooting), and can range from beginner to advanced.
- **Reference:** Once users have some experience with a product, they expect clear and accurate reference information about its interfaces/etc. Users generally have to know what they're looking for when using reference docs. For example, if a user doesn't know why and how to transform data in Materialize (guidance), they might not know to look at `CREATE INDEX` or `CREATE MATERIALIZE VIEW` for details. 
- **Concepts/explanations:** Basic explanations for successful product usage should complement guides, but power users will always want a deeper, detailed understanding of the system architecture, capabilities, and behavior. Dedicated conceptual docs serve this purpose. 
- **Tutorials:** Similar to guides, tutorials are instructional in nature, but they usually present an end-to-end learning scenario involving multiple actions to achieve a broader goal. For example, instead of a doc that helps you configure Materialize to consume data from Kafka (a how-to), a tutorial might walk users through a broader scenario involving connecting Kafka to Materialize, like [this blog](https://materialize.com/guides/segment-to-materialize/) that helps you "connect a real-time stream of user-centric events from Segment to Materialize, using Kafka as the intermediary." 

Our current docs contain all of these but are particularly heavy on reference, with guidance embedded in or presented as reference in some cases. Instead, I believe we should give clear prominence to guidance, which most users need, while presenting reference material for folks who know what to look for, as well as detailed conceptual explanations for power users. For now, I think tutorials live well on the blog, though we should consider a place for them in docs over time.

**Comment by jseldess** [comment]
Sketch (overly simplistic):

```
Guides
    Get Started
        What is Materialize?
	Quickstart
	Demos
    Plan Your Deployment
        xxx <clusters/replicas/sizing based on goals, dbt/terraform best practices>
    Connect Sources
        Connect Postgres to Materialize
        Connect Kafka to Materialize
	Connect Readpanda to Materialize
    Transform Data
        Create Views and Indexes
	Create Materialized Views
	Optimize Queries
    Stream results
        Stream to a Client
	Stream to a Message Broker	
	One-off Queries
    Manage Your Account
        Monitor Resources
        Prepare for Upgrades
        Resize a Replica
        Increase Fault Tolerance
    Troubleshooting
        xxx	
Reference	
	SQL
	CLI
	APIs
	Third-Party Tools
        Telemetry
Concepts
        Architecture overview
        Storage Layer
        Compute Layer
        Adapter Layer
        Life of a Materialize View
        Life of an Index
	Consistency Guarantees
Releases
	Release Notes
	Release Schedule
	Backwards Compatibility
```

Not sure "Transform data" and "Stream results" are the best expressions.

**Comment by jseldess** [comment]
Thanks for the feedback, @ruf-io! 

1. I like `Serve data` and your related suggestions very much. Updated the sketch accordingly.
2. I'm using "guide", "how-to", and "recipe" interchangeably. Can you share what you think of as a "recipe" and an example of a second-order problem?
3. Yeah, I had the sense nagging feeling about "Manage Your Account". I like "Manage Materialize" and will go with that for now.

I haven't look closely at the integration pages yet. I was assuming they would feed into "Connect Sources", but I may be misunderstanding. I'll take a look.

**Comment by frankmcsherry** [comment]
> I'm 100% behind Docs pushing back on the rest of Product to make MZ more explainable and consistent.

Early days we had one of our Product goals to be "have as few asterisks as possible on the web page". Essentially, we wanted as few moments where the clear and concise description you'd want to read wasn't the whole story. I just remembered that, and want to supply it as ammunition for you against ... the otherwise prevailing entropy.

**Comment by jseldess** [comment]
Thanks, @frankmcsherry! 

Yes, once we're confident in the overall approach, the next step will be to get a sense of what content we have that needs to be refactored vs. what content we need to write from scratch. I'm sure it's a mix and also that it'll be more effective to tackle this incrementally. 

Appreciate the encouragement to push for changes in favor of fewer asterisks!

**Comment by benesch** [comment]
This looks great to me, too.

> Yeah, I had a nagging feeling about "Manage Your Account". I like "Manage Materialize" better and will go with that for now.

I'll throw out "Operate" as an alternative. I'm not sure "Operate Materialize" is necessarily better, but the guides in there are definitely "how to operate Materialize in production".

**Comment by jseldess** [comment]
Thanks, @benesch. I want to be cautious about using the term "operate", as that term is easily understood to mean "run the thing." It has to be clear that we do the primary operations but users still have an active hand in the success of that.

**Comment by benesch** [comment]
Makes sense!

**Comment by sjwiesman** [comment]
First of all, this looks amazing! Only two question/comments. The first is just to understand where tables fit into to the structure.

The second, I’d like to hear your opinion on the railroad diagrams, and how and where those fit into the structure

**Comment by materializesupport** [comment]
Echoing @sjwiesman here, this looks great!

One concern I have is with consistency. It would be great to have parity between docs and other sections of Materialize. A good example is the recent [CDC in Production ](https://materialize.com/guides/cdc-in-production/) guide.

In our guides, we show one diagram view and in docs, we show a diagram view that is completely different (comparisons below). The overall flow and cleanliness of the diagrams in our Guides makes reading through much easier and a more enjoyable experience. For docs, a splash of color may be needed to highlight the core focus, though bringing these over would provide a significant improvement.

**Blog / Guides**
![screenshot-2023-04-05__010816PM@2x](https://user-images.githubusercontent.com/110483338/230153615-b140570b-96f2-498a-a2a6-da2307b43f85.png)

**Docs**
![screenshot-2023-04-05__010911PM@2x](https://user-images.githubusercontent.com/110483338/230153857-cff72696-c89d-43f5-bf23-6c1e136ed98d.png)

**Comment by jseldess** [comment]
Thanks, @sjwiesman and @materializesupport! Glad the structure resonates overall. 

> Only two question/comments. The first is just to understand where tables fit into to the structure.

In general, tables are helpful when there's a list of items that you want to define consistently, like we have on most [SQL reference](https://materialize.com/docs/sql/create-index/#syntax) pages or on the [tools and integrations overview](https://materialize.com/docs/integrations/) page. I think we'll want to keep using tables in such cases, though there's an argument to make for breaking items into their own section for easier linking. That's what I ended up doing in the [ReadySet CLI docs](https://docs.readyset.io/reference/cli/readyset/#options). That's what [Postgres](https://www.postgresql.org/docs/current/sql-createindex.html) does, too, though they don't have anchor links. 

Do you have any specific thoughts about tables, @sjwiesman?

> The second, I’d like to hear your opinion on the railroad diagrams, and how and where those fit into the structure 

We used railroad diagrams in CockroachDB docs, too, and my sense is that they're specifically for summarizing the syntax of SQL commands. With that in mind, I'd expect them only (or mostly) in the SQL command docs here. Does that make sense to you? 

As for my opinion about railroad diagrams, I'm torn, and I remember hearing lots of mixed feelings at Cockroach. Based on [input from Marta](https://www.notion.so/materialize/Documentation-53f21d318c3f4abaa26398a04be67b2e#72a15019b202484c8aa0f5f575b9d2ed), I gather the feelings are mixed here, too. I think in simple cases, a railroad diagram can feel more intuitive for users who might not know how to read the type of [synopsis conventions](https://www.postgresql.org/docs/9.1/notation.html) you find in postgres/mysql reference docs. I think one big downside of railroad diagrams is that they get hard to maintain. Having a textual synopsis may be easier. Very open to input here, and if we've heard from users on this topic, would also be good to know.

@materializesupport, ^ address the docs diagram you mention. For non-SQL syntax-related diagrams, I would love to follow the style of the blog.

**Comment by jseldess** [comment]
We implemented the first instance of this info architecture in https://github.com/MaterializeInc/materialize/pull/19172. Closing this issue, though we'll open follow-ups to evolve the navigation.
