### ISSUE TITLE
[WMR] Improve error message on type mismatch

### ISSUE THREAD

**Issue by teskje** [MaterializeInc/materialize#18501]
WMR queries that have mismatch in the specified recursive column type produce a hard-to-read error that includes Rust debug output:

```
materialize=> with mutually recursive forever (i int) as (select count(*) from mz_views union (select i + 1 from forever)) select * from forever;
ERROR:  declared type of WITH MUTUALLY RECURSIVE query forever did not match inferred type: RelationType { column_types: [ColumnType { scalar_type: Int32, nullable: true }], keys: [] }, RelationType { column_types: [ColumnType { scalar_type: Int64, nullable: true }], keys: [] }
```

**Comment by aalexandrov** [comment]
@MaterializeInc/surfaces can you give me pointer of the correct API to use if I want to render a `RelationType` as a user-facing output. I'm not seeing a `Display` implementation for `RelationType` or `ColumnType`.

**Comment by mjibson** [comment]
https://dev.materialize.com/api/rust-private/mz_repr/explain/trait.ExprHumanizer.html#tymethod.humanize_scalar_type is the way to convert a ScalarType (a pub property on ColumnType) into a human-readable string.

**Comment by aalexandrov** [comment]
Looking at similar error types (`UnknownOperator`, `IndistinctFunction`), it seems that whenever the error message of that type is constructed, we do a pass on some `Vec<ScalarType>` and map it to a `Vec<String>` using an enclosing `ecx: &ExprContext`.

However, the `RecursiveTypeMismatch` is constructed from a function (`plan_ctes`) that only has access to a `qcx: &mut QueryContext`, not the enclosing `ecx: &ExprContext`. How can I make the `ecx: &ExprContext` available in `plan_ctes`?

**Comment by mjibson** [comment]
https://dev.materialize.com/api/rust-private/mz_sql/plan/struct.QueryContext.html#method.humanize_scalar_type exists on QueryContext!

**Comment by aalexandrov** [comment]
Thanks, @mjibson, this was easier than expected!
