### ISSUE TITLE
postgres source is stuck for 30 seconds post-restart

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#18520]
### What version of Materialize are you using?

9c0850faaadcc392f0e1e44f7a48271758d1b294

### How did you install Materialize?

Docker image

### What is the issue?

After Mz is restarted, a SELECT from a postgres source is stuck for 30+ seconds.

To reproduce:

```
cd test/platform-checks
./mzcompose down -v ; ./mzcompose run default --scenario=RestartEntireMz --check=PgCdc
````
and you will see a hang here:

```
> SELECT f1, max(f2), SUM(LENGTH(f3)) FROM postgres_source_tableB GROUP BY f1;
rows match; continuing at ts 1680244550.0512028
> SELECT f1, max(f2), SUM(LENGTH(f3)) FROM postgres_source_tableC GROUP BY f1;
rows didn't match; sleeping to see if dataflow catches up 50ms <- HERE
rows match; continuing at ts 1680244582.0886092
```

The difference between the two timestamps is 32 seconds even though the other two postgres sources were available immediately.

The sources contain less than 1Mb of data each. The issue is not reproducible without a Mz restart.

Here is the `EXPLAIN TIMESTAMP` while the source is hung:

```
materialize=> explain timestamp for SELECT f1, max(f2), SUM(LENGTH(f3)) FROM postgres_source_tableC GROUP BY f1;
                                 Timestamp                                 
---------------------------------------------------------------------------
                 query timestamp: 1680244561813 (2023-03-31 06:36:01.813) +
           oracle read timestamp: 1680244561813 (2023-03-31 06:36:01.813) +
 largest not in advance of upper: 1680244548999 (2023-03-31 06:35:48.999) +
                           upper:[1680244549000 (2023-03-31 06:35:49.000)]+
                           since:[1680244548000 (2023-03-31 06:35:48.000)]+
         can respond immediately: false                                   +
                        timeline: Some(EpochMilliseconds)                 +
                                                                          +
 source materialize.public.postgres_source_tablec (u14, storage):         +
                   read frontier:[1680244548000 (2023-03-31 06:35:48.000)]+
                  write frontier:[1680244549000 (2023-03-31 06:35:49.000)]+
 ```

**Comment by sploiselle** [comment]
This is caused when the WAL has no new entries but we decide to try to produce replication values anyway; it receives a heartbeat every 30 seconds, so we wait 30 second to find out that we can advance to the end of the WAL. Should be straightforward to fix.

**Comment by petrosagg** [comment]
There is something missing from this explanation that I don't understand. During ingestion the upper is advanced as the remap operator continuously mints bindings, and that process happens regardless of what the source frontier is doing. Is that process getting stuck? If yes, why?

**Comment by sploiselle** [comment]
If the restart detects that the replication slot exists, it goes into the "snapshot + rewind" mode. The "rewind" portion often takes 30 seconds because it requires receiving a `PrimaryKeepAlive` message to see an LSN that exceeds the snapshot's/temporary replication slot's consistent point. Said slightly differently, all of the "actual" data is caught by the snapshot, so we spend the time just waiting to ensure we've seen all of the messages between `slot_lsn` and `snapshot_lsn`, but the only way to reach `snapshot_lsn` is with a keep alive message.

**Comment by sploiselle** [comment]
Err, sorry––when I said:

> all of the "actual" data is caught by the snapshot

I meant that all of the "actual" data would have been caught by a snapshot ending at the `slot_lsn`, i.e. all of the data is at LSNs below the `slot_lsn`.
