### ISSUE TITLE
docs: Document "batches" in the context of "arrangements"

### ISSUE THREAD

**Issue by jseldess** [MaterializeInc/materialize#18525]
### Documentation request

A few `mz_arrangement_*` views contain a `batches` field defined as `The number of batches in the arrangement.` However, we don't explain what we mean by "batches" in this context anywhere in our docs. We should consider doing so, likely where we explain [arrangements](https://materialize.com/docs/overview/arrangements/#arrangements). 

### Related work

https://github.com/MaterializeInc/materialize/pull/18512#discussion_r1153790430

**Comment by morsapaes** [comment]
I don't think it's relevant to go into this level of detail outside of maybe enriching the description of the `batches` column itself for `mz_{dataflow_}arrangement_*` views. What stood out to me in #18512 and we don't mention anywhere is what these views are useful for, which is (AFAIU) approximating how much memory is being used at the dataflow- or arrangement-level.
