### ISSUE TITLE
Replace deprecated `pkg_resources` library

### ISSUE THREAD

**Issue by jkosh44** [MaterializeInc/materialize#18527]
### What version of Materialize are you using?

v0.49.0-dev

### How did you install Materialize?

Built from source

### What is the issue?

Our optimizer benchmarking python scripts rely on the `pkg_resources` library which is deprecated.

https://github.com/MaterializeInc/materialize/blob/138bf7fcb694fac900e32219b7024ef5b3cdd96c/misc/python/materialize/optbench/__init__.py#L13

The documentation for `pkg_resources` and the deprecation notice can be found here: https://setuptools.pypa.io/en/latest/pkg_resources.html

You can also see the warning when running one of our python linters:
```bash
$ ./bin/pyactivate -m pytest -qq --doctest-modules misc/python
..                                                                                                                                                                                 [100%]
==================================================================================== warnings summary ====================================================================================
misc/python/venv/lib/python3.10/site-packages/pkg_resources/__init__.py:121
  /home/joe/materialize/misc/python/venv/lib/python3.10/site-packages/pkg_resources/__init__.py:121: DeprecationWarning: pkg_resources is deprecated as an API
    warnings.warn("pkg_resources is deprecated as an API", DeprecationWarning)

misc/python/venv/lib/python3.10/site-packages/pkg_resources/__init__.py:2870
  /home/joe/materialize/misc/python/venv/lib/python3.10/site-packages/pkg_resources/__init__.py:2870: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('google')`.
  Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
    declare_namespace(pkg)

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
```

The suggested alternative is to switch to the `importlib.resources`: https://docs.python.org/3/library/importlib.resources.html

I found a useful migration guide here: https://importlib-resources.readthedocs.io/en/latest/migration.html#pkg-resources-resource-filename

**Comment by jkosh44** [comment]
I don't see a code-owner for our python code, so I thought maybe this was a QA team task. Looking at the file I see that it was written by @aalexandrov, so maybe he has the best context to update it.

**Comment by aalexandrov** [comment]
Thanks, @jkosh44, I'll take a look.
