### ISSUE TITLE
Not a regression: Unexpected keys in indexes with PgCdc

### ISSUE THREAD

**Issue by def-** [MaterializeInc/materialize#18536]
### What version of Materialize are you using?

84b5c727ab0f9c4caa20a9333b8941fa67e30bb6

### How did you install Materialize?

Built from source

### What is the issue?

Reproduced with `bin/mzcompose --find platform-checks down && bin/mzcompose --release --find platform-checks run default --scenario=UpgradeClusterdComputeLast --check=PgCdc`
Fails:
```
> SELECT key FROM (SHOW INDEXES ON postgres_source_tableA);
rows didn't match; sleeping to see if dataflow catches up 50ms 75ms 113ms 169ms 253ms 380ms 570ms 854ms 1s 2s 3s 4s 6s 10s 15s 22s 33s 49s 74s 78s
^^^ +++
32:1: error: non-matching rows: expected:
[["{f1,f2}"]]
got:
[["{f1,f2,f3}"]]
Poor diff:
+ {f1,f2,f3}
- {f1,f2}

     |
  31 |
  32 | > SELECT key FROM (SHOW INDEXES ON postgres_source_tableA);
     | ^
```
@philip-stoev Have you already bisected this? Seems like a regression to me, happens in nightly. I'll check where this came from. Noticed in https://github.com/MaterializeInc/materialize/pull/18477 but unrelated to it.

ci-regexp: 32:1: error: non-matching rows

**Comment by philip-stoev** [comment]
@def- this is not a regression -- after discussion with @sploiselle and #team-compute it turns out that the both values returned are acceptable -- the returned value depends on whether the Pg source was created before or after an upgrade to the latest Mz.

**Comment by philip-stoev** [comment]
The test needs to be fixed to allow either value to be returned. I could not get to do it today, I planned to fix it Monday.

**Comment by def-** [comment]
Ok, thanks!
