### ISSUE TITLE
testing: test against more/newer versions of PG for sources

### ISSUE THREAD

**Issue by sploiselle** [MaterializeInc/materialize#18537]
### Feature request

We currently test PG sources against PG 10 (at least in `pg-cdc`); it would be great if we used a more current version than this (preferably 15). However, I think testing against a suite of versions would also be very useful, albeit more challenging given their different levels of support for different features.

**Comment by benesch** [comment]
Closing as a duplicate of https://github.com/MaterializeInc/materialize/issues/6825.
