### ISSUE TITLE
Improve unique key inference for `LetRec`

### ISSUE THREAD

**Issue by ggevay** [MaterializeInc/materialize#18553]
Unique key inference for `LetRec` currently starts pessimistic (HIR planning creates the type with an empty set of keys [here](https://github.com/MaterializeInc/materialize/blob/12be404482903e0983cff84c4adb3165df5b6004/src/sql/src/plan/query.rs#L1193)) and performs one iteration (in `refresh_types` in `NormalizeLets`). While this is not incorrect (because unique key inference is _monotonic_, [similarly](https://github.com/MaterializeInc/materialize/pull/18323#issuecomment-1484072718) to `MonotonicFlag`), it could be made smarter to be able to infer more keys:
1. A relatively simple change (I think), would be to make it go until fixpoint instead of just 1 iteration.
2. Or maybe it could start optimistic, similarly to `ColumnKnowledge`. However, this runs the risk of too many keys, due to `top` being the keys of an empty collection, which is all possible keys, which is all subsets of the columns, which is exponential in arity. An idea to avoid this risk is to simply give up if more than, say, 7 columns, i.e., start `bottom`. A minor improvement to this could be not totally giving up, but starting from each 1-column key.

One example will be in `reduce_elision.slt` after merging [#18554](https://github.com/MaterializeInc/materialize/pull/18554). Edit: One more example is introduced by https://github.com/MaterializeInc/materialize/pull/19445 in `outer_join_simplification.slt`, where the keys coming from a UNION DISTINCT would be good to propagate through a recursive binding, so that SemijoinIdempotence can simplfy a LEFT JOIN whose right side comes from the recursive Get. Edit 2: Also note that [accurate key inference is important when creating Kafka sinks](https://github.com/MaterializeInc/materialize/issues/19143).

~~Before we go too deep into 2., we should try to understand how much better 2. is than 1. I have a feeling that the difference is not so big as in `MonotonicFlag`, because monotonicity is usually about not messing up the monotonicity of the input, while unique keys are often _introduced_ even from inputs with no keys. A notable example in WMR is that there is often a `UNION DISTINCT` at the root of a recursive binding.~~

There is also the question of where we should put this code. Maybe simply extend `refresh_types` in `NormalizeLets`?

**Edit:**

[I tried 1., and unfortunately it doesn't work](https://github.com/MaterializeInc/materialize/pull/18595), so we have to go with 2. It's an open question how to handle the too-many-keys problem. Maybe it's enough to start dropping them if we get too many, but we should try it how often this happens.

One more surprising thing is that **we absolutely need to normalize the key sets to antichains**. Otherwise, we lose keys when intersecting the key sets (and this does happen in practice, I tried without normalization).

So then the sets of keys that we need to intersect are the spans of the antichains that we get from the normalization: Let's define the span of an antichain to be the set of all such subsets of columns that have a subset that is present in the antichain.

Computing the intersections between these sets that are represented as the spans of the antichains is a bit tricky: Let's say `[x1, x2, ...]` and `[y1, y2, ...]` are the two antichains whose spans' intersection we need to compute.
1. So, we need to compute `(span(x1) u span(x2) u ...) ∩ (span(y1) u span(y2) u ...)`
2. This is equivalent to (by distributing the terms): `U_i,j: span(xi) ∩ span(yj)`
3. Which is equivalent to `U_i,j: span(xi u yj)`

So 3. is a direct way to calculate the intersection of two of these sets. Unfortunately, this shows that the antichains can get quadratically bigger at an intersection. So this is the point where we start dropping keys when the antichains are getting too big? Maybe a good heuristic for what to keep would be to keep / compute only those `i`, `j` pairs in the above  `U_i,j` in 3. where `xi` and `yj` are comparable (i.e., one of `xi` and `yj` is a subset of the other)? (But do this only when the key sets are getting too big.

**Edit 2:**
I think that if an `xi` and an `yj` are incomparable, that means that our key inference is non-monotonic! So this shouldn't happen too often that an `xi` and an `yj` are incomparable, because the key derivation should be monotonic in most cases. I mean, it has to be some really messed up pathological case when it's not monotonic, and maybe then the fix is not that we'll figure out a way to keep track of a gazillion key sets from the quadratic explosions, but that we fix the pathology that causes the key inference to not be monotonic (and just drop keys in the meantime).

I suggest getting back to this when we have
- more WMR users, and/or
- more examples where the weak key inference is actually hurting some optimization.
- keep in mind https://github.com/MaterializeInc/materialize/issues/19143

**Comment by aalexandrov** [comment]
note for reverse indexing purposes: there is a test in `outer_join_simplification.slt` that demonstrates a limitation of the optimizer that prohibits `SemijoinIdempotence` from kicking in some `LetRec` contexts (see the test defined in #19445 that references this issue).

**Comment by ggevay** [comment]
Also note that [accurate key inference is important when creating Kafka sinks.](https://github.com/MaterializeInc/materialize/issues/19143)

**Comment by frankmcsherry** [comment]
This has the potential to be closed, I think? The `analysis::UniqueKeys` transform is lattice-enabled, and will perform an optimistic analysis that .. other things being equal .. should be able to infer keys around a WMR loop rather than tripping over pessimistic assumptions.

**Comment by ggevay** [comment]
Yes, this is done! Thank you @frankmcsherry !
