### ISSUE TITLE
Object ownership: Can't drop object, but cascade can drop it

### ISSUE THREAD

**Issue by def-** [MaterializeInc/materialize#18551]
### What version of Materialize are you using?

v0.50.0-dev (762302a54)

### How did you install Materialize?

Built from source

### What is the issue?

```
# As mz_system
mz_system=> ALTER SYSTEM SET enable_rbac_checks TO true;
ALTER SYSTEM
# As materialize
materialize=> create role r1;
CREATE ROLE
# As r1:
materialize=> create table t (c int);
CREATE TABLE
# As materialize
materialize=> create index i on t (c);
CREATE INDEX
# As r1:
materialize=> drop index i;
ERROR:  must be owner of INDEX materialize.public.i
materialize=> drop table t;
DROP TABLE
materialize=> drop index i;
ERROR:  unknown catalog item 'i'
```

On Postgres I can directly drop the index when I own the table, even though it was created by a different role:
```
postgres=# set role r1;
SET
postgres=> drop index i;
DROP INDEX
```

**Comment by jkosh44** [comment]
@def- Can you show the full PostgreSQL commands for creating the index? My investigation shows that it's impossible to create an index on a table that you don't own:

```
# As postgres

postgres=# CREATE ROLE foo LOGIN;
CREATE ROLE
postgres=# CREATE TABLE t (a INT);
CREATE TABLE

# As foo
postgres=> CREATE INDEX i ON t (a);
ERROR:  must be owner of table t

# As postgres
postgres=# CREATE INDEX i ON t (a);
CREATE INDEX
postgres=# ALTER INDEX i OWNER TO foo;
WARNING:  cannot change owner of index "i"
HINT:  Change the ownership of the index's table, instead.
ALTER INDEX
```

**Comment by jkosh44** [comment]
So here's one thing for sure, 
- The index owner is always set to the table owner (this was a bit hard to track down in the code):

When creating the index `rel` is set to the underlying table:
https://github.com/postgres/postgres/blob/a9781ae11ba2fdb44a3a72c9a7ebb727140b25c5/src/backend/commands/indexcmds.c#L653-L664

`rel` is then passed to `index_create()` as the `heapRelation` param:
https://github.com/postgres/postgres/blob/a9781ae11ba2fdb44a3a72c9a7ebb727140b25c5/src/backend/commands/indexcmds.c#L1163-L1172
https://github.com/postgres/postgres/blob/a9781ae11ba2fdb44a3a72c9a7ebb727140b25c5/src/backend/catalog/index.c#L665-L731

Then the owner of `heapRelation` is used as the owner of the index:
https://github.com/postgres/postgres/blob/a9781ae11ba2fdb44a3a72c9a7ebb727140b25c5/src/backend/catalog/index.c#L994

- When altering the owner of a table/materialized view/view, we should alter the owners of any dependent indexes: https://github.com/postgres/postgres/blob/a9781ae11ba2fdb44a3a72c9a7ebb727140b25c5/src/backend/commands/tablecmds.c#L14010-L14031
- When altering the owner of an index issue a warning and do nothing: https://github.com/postgres/postgres/blob/a9781ae11ba2fdb44a3a72c9a7ebb727140b25c5/src/backend/commands/tablecmds.c#L13848-L13867

**Comment by jkosh44** [comment]
The `DROP OWNED` docs (https://www.postgresql.org/docs/current/sql-drop-owned.html) say this:

> Using the `CASCADE` option might make the command recurse to objects owned by other users.

So I think that implies that it's OK to drop objects now owned by you through `CASCADE`, though clearly from my example above you can't drop those objects directly.

**Comment by def-** [comment]
> @def- Can you show the full PostgreSQL commands for creating the index?

Sure:
```
postgres@dev:~$ psql
psql (15.2 (Ubuntu 15.2-1.pgdg22.10+1), server 14.7 (Ubuntu 14.7-1.pgdg22.10+1))
Type "help" for help.

postgres=# create role r1;
CREATE ROLE
postgres=# set role r1;
SET
postgres=> create table t (c int);
CREATE TABLE
postgres=# set role postgres;
SET
postgres=# create index i on t (c);
CREATE INDEX
postgres=# set role r1;
SET
postgres=> drop index i;
DROP INDEX
```

**Comment by jkosh44** [comment]
> > @def- Can you show the full PostgreSQL commands for creating the index?
> 
> Sure:
> 
> ```
> postgres@dev:~$ psql
> psql (15.2 (Ubuntu 15.2-1.pgdg22.10+1), server 14.7 (Ubuntu 14.7-1.pgdg22.10+1))
> Type "help" for help.
> 
> postgres=# create role r1;
> CREATE ROLE
> postgres=# set role r1;
> SET
> postgres=> create table t (c int);
> CREATE TABLE
> postgres=# set role postgres;
> SET
> postgres=# create index i on t (c);
> CREATE INDEX
> postgres=# set role r1;
> SET
> postgres=> drop index i;
> DROP INDEX
> ```

Ah ok, so what's happening here isn't completely straight forward. Normally to create an index, you must own the table. However, `postgres` is a superuser (you can tell because the prompt is `=#` instead of `=>`. So `postgres` creates the index as a superuser, but the owner is set to the owner of the table, which is `r1`. So when you go to drop the index as `r1`, you actually do own the index.

```
postgres=# CREATE ROLE r1;
CREATE ROLE
postgres=# SET role r1;
SET
postgres=> CREATE TABLE t (c INT);
CREATE TABLE
postgres=> SET ROLE postgres;
SET
postgres=# CREATE INDEX i ON t(c);
CREATE INDEX
postgres=# SET ROLE r1;
SET
postgres=> SELECT relowner FROM pg_class WHERE relname = 'i';
 relowner 
----------
   756229
(1 row)

postgres=> SELECT relowner,rolname FROM pg_class JOIN pg_roles ON pg_class.relowner = pg_roles.oid WHERE relname = 'i';
 relowner | rolname 
----------+---------
   756229 | r1
(1 row)

postgres=> DROP INDEX i;
DROP INDEX
```
