### ISSUE TITLE
Update Metabase docs to include configuration settings to avoid expensive metadata queries

### ISSUE THREAD

**Issue by josharenberg** [MaterializeInc/materialize#18596]
### Documentation request

I've documented the changes that we found necessary to avoid bad performance:
https://www.notion.so/materialize/Metabase-9e7b7de2c8e4465b8ec180930ca26dab

We probably want to add them in some form to the public-facing docs.

**Comment by morsapaes** [comment]
No longer relevant, since in the meantime we shipped automatic routing of introspection queries to `mz_introspection`.
