### ISSUE TITLE
Report OOMs in introspection

### ISSUE THREAD

**Issue by sjwiesman** [MaterializeInc/materialize#18621]
### Feature request

If a `clusterd` process OOMs, there is no way to know that as a user. If you are in an OOM loop, it appears that things are moving slowly. You have to look at memory statistics and infer the process is falling over. 

This should be a first class metric we show to users.

**Comment by aljoscha** [comment]
We already have a pipeline set up for reporting stats from Kubernetes from here: https://github.com/MaterializeInc/materialize/blob/e479bd2102b34b0230148a0db136dab1cc35b150/src/orchestrator-kubernetes/src/lib.rs#L423. If it's not too hard to get OOM metrics from k9s we could plug them in here. Then the only worry is changing the schema of the metrics table, but... 🤷

**Comment by ggnall** [comment]
cc @parkerhendo @umanwizard some validation on this idea. en route to a comprehensive "activity log" we should surface at least OOM events in the console and sql/prometheus for triggering alerts.

**Comment by benesch** [comment]
@aljoscha I think we'd want to plug into the _other_ Kubernetes introspection we do here: 

https://github.com/MaterializeInc/materialize/blob/e479bd2102b34b0230148a0db136dab1cc35b150/src/orchestrator-kubernetes/src/lib.rs#L850-L901

That code is already rigged up to read the pod status. If we could figure out how to tweak the `mz_cluster_replica_statuses` table, it'd be a fairly straightforward change to fix this. Maybe a new status like `oom-killed`, alongside `not-ready` and `ready`?

**Comment by umanwizard** [comment]
That'd be one more table we need to turn on 30-day retention/indexing for, then. Which might be costly if a replica is constantly flapping. We should do some back-of-the-envelope cost analysis.

**Comment by benesch** [comment]
Would we strictly need to? It seems valuable to report even if the status history is only available since the last envd reboot.

**Comment by umanwizard** [comment]
Indeed, that would be better than nothing, but my understanding from @ggnall and @parkerhendo was that a log over time was the ultimate desired state.

**Comment by benesch** [comment]
Hm, the current schema of `mz_cluster_replica_statuses` includes an `updated_at` column. So we're not using the differential time as the time of the observation.

Say—does anything currently clean up that table? Or does it just grow forever? I think your concern about cost is valid, but applies to the current state of the world, not adding an additional `oom-killed` status!

**Comment by umanwizard** [comment]
Good catch -- I hadn't realized that.

IMO, it doesn't fundamentally change the question. Since BC is not guaranteed for these tables, the current state of the world doesn't have much bearing on the question of what the desired end state is.

**Comment by benesch** [comment]
> IMO, it doesn't fundamentally change the question. Since BC is not guaranteed for these tables, the current state of the world doesn't have much bearing on the question of what the desired end state is.

Right, my point is just that the current state of the world is unsustainable, and we need to fix that even if we don't add a new `oom-killed` status.

So proposal:

  * Add `oom-killed` as a status (so `ready`, `not-ready`, and `oom-killed` in total).
  * On `environmentd` restart, remove any entries from this table that are older than {30, 60, 90} days.

**Comment by umanwizard** [comment]
I checked, and it turns out that we were wrong, and we are _not_ retaining everything in the table now, but only the latest version.

So, indeed, making this a new retained metrics relation will increase memory usage (I'll do an analysis to see whether this is acceptable before turning on the retainedness for this one)
