### ISSUE TITLE
Clean up storage networking tuning tech debt

### ISSUE THREAD

**Issue by benesch** [MaterializeInc/materialize#18683]
As part of the latest production incidents, we've been accumulating a lot of good tuning of networking configuration, but it's sprawling out across the codebase. This leads to uneven coverage: not all combinations of tunnels and sources/sinks result in tuned network connections.

* [x] ~~The PostgreSQL replication timeouts are great, but no reason to limit them to the replication connections. IMO, they should be turned on for the snapshot connections and data fetching connections too.~~ (fixed in https://github.com/MaterializeInc/materialize/commit/dfdd27727e3b5de37bb03bcd61719e56a489a162)
* [x] ~~SSH-tunneled PostgreSQL connections create a raw TCP socket and don't configure any of the TCP settings: https://github.com/MaterializeInc/materialize/blob/07a8705801b77bda48cd61ad8190f7f75e66c304/src/postgres-util/src/lib.rs#L528
  This is probably _correct_ because the TCP connection is just to the local `ssh` process on the local machine—but why are we using TCP sockets?! We should switch this to a Unix domain socket ([link](https://docs.rs/openssh/latest/openssh/enum.Socket.html#variant.UnixSocket.field.path)) so that we don't have to do the "find a free TCP port" song and dance.~~ unix sockets dont support tls with pg
* [x] ~~https://github.com/MaterializeInc/materialize/blob/07a8705801b77bda48cd61ad8190f7f75e66c304/src/postgres-util/src/lib.rs#L544
  PrivateLink-tunneled PostgreSQL connections do not apply any of the TCP settings. I think this is a straight up bug that should be fixed.~~ fixed in https://github.com/MaterializeInc/materialize/pull/23589
* [x] ~~https://github.com/MaterializeInc/materialize/blob/3d1c53b18a49c1552cc83fc2dde031d30c6c65b7/src/ssh-util/src/tunnel.rs#L31-L32 
  SSH keepalives are not configurable.~~ closed by https://github.com/MaterializeInc/materialize/pull/23850
* [x] ~~PostgreSQL replication settings are configurable but are not wired up through LaunchDarkly.~~ implemented in https://github.com/MaterializeInc/materialize/pull/21150
* [x] ~~None of the TCP tuning has been applied to Kafka connections. Maybe this is fine, because librdkafka already has sane defaults and timeouts, but we should at least think harder about this~~ closed by https://github.com/MaterializeInc/materialize/issues/18683

cc @guswynn @sploiselle @dseisun-materialize @aljoscha @pH14 

Apologies that this is stream of consciousness; it's late and I wanted to write all this down before I forgot it.

**Comment by benesch** [comment]
We should also fix https://github.com/MaterializeInc/materialize/issues/20299 as part of this work.

**Comment by pH14** [comment]
One thing that occurred to me while chatting with @sploiselle -- should we consolidate our grpc services on `clusterd` to be run out of a single server? Then we could have a single tuned TCP connection between `envd <-> clusterd`, while still keeping the abstraction boundary of separate RPC services for compute and storage (and possibly forwarded webhooks, TBD). This seems like a cleaner story to me, since there's one connection to manage + tune + open ports for.

**Comment by benesch** [comment]
> One thing that occurred to me while chatting with @sploiselle -- should we consolidate our grpc services on `clusterd` to be run out of a single server? Then we could have a single tuned TCP connection between `envd <-> clusterd`, while still keeping the abstraction boundary of separate RPC services for compute and storage (and possibly forwarded webhooks, TBD). This seems like a cleaner story to me, since there's one connection to manage + tune + open ports for.

Does having two physical TCP connections make them harder to tune? Merging the TCP connections (or not) seems like a question to tackle as part of [cluster unification](https://github.com/MaterializeInc/materialize/issues/17416).

The code that establishes the gRPC servers and clients is already factored out into a bunch of helpers (https://github.com/MaterializeInc/materialize/blob/main/src/service/src/grpc.rs), so I'm hopeful that tuning the storage controller–clusterd and compute controller–clusterd protocols would just be a matter of setting the right keep-alive settings in that one place?

**Comment by pH14** [comment]
Ah yeah, I took a look at the code and it's not as straightforward as I thought it might be given how the grpc services are set up. Thought there might be a quick win in mapping 1 physical connection to n logical services, but it's involved enough where cluster unification seems like the answer.

**Comment by guswynn** [comment]
> This is probably correct because the TCP connection is just to the local ssh process on the local machine—but why are we using TCP sockets?! We should switch this to a Unix domain socket ([link](https://docs.rs/openssh/latest/openssh/enum.Socket.html#variant.UnixSocket.field.path)) so that we don't have to do the "find a free TCP port" song and dance.

@benesch kafka ssh connections would still need to do this song and dance right? my understanding is that rdkafka doesnt support unix domain sockets?

**Comment by guswynn** [comment]
> This is probably correct because the TCP connection is just to the local ssh process on the local machine—but why are we using TCP sockets?! 

Are we sure about this? the underlying tcp connection that the ssh tunnel makes to the daemon has the ssh-configured keepalive, but I imagine we still want to configure the _tunneled_ socket the exact same as if we aren't using ssh?

**Comment by guswynn** [comment]
In any case, here is a first step to resolving this issue: https://github.com/MaterializeInc/rust-postgres/pull/18

**Comment by benesch** [comment]
> @benesch kafka ssh connections would still need to do this song and dance right? my understanding is that rdkafka doesnt support unix domain sockets?

Yeah, I think I was just wrong on this. rdkafka doesn't support UDS and rust-postgres doesn't support TLS over UDS. So never mind.

> > This is probably correct because the TCP connection is just to the local ssh process on the local machine—but why are we using TCP sockets?!
> 
> Are we sure about this? the underlying tcp connection that the ssh tunnel makes to the daemon has the ssh-configured keepalive, but I imagine we still want to configure the _tunneled_ socket the exact same as if we aren't using ssh?

Yeah, it'd be great if the socket that `ssh` makes on our behalf enabled TCP keep alives. But that's something we'd have to configure via the SSH library. I'm not sure if its configurable? But tl;dr is I think the `clusterd <-> ssh` TCP socket doesn't need keepalives because that's all within a single container.

**Comment by guswynn** [comment]
> Yeah, it'd be great if the socket that ssh makes on our behalf enabled TCP keep alives. But that's something we'd have to configure via the SSH library. 

It has https://docs.rs/openssh/latest/openssh/struct.SessionBuilder.html#method.server_alive_interval, which we do set to 30 seconds (we can make this LD configurable), but i don't openssh offers anything else we can configure client side

**Comment by guswynn** [comment]
> None of the TCP tuning has been applied to Kafka connections. Maybe this is fine, because librdkafka already has sane defaults and timeouts, but we should at least think harder about this

also, I thought more about this, and I concluded that yes, we would prefer rdkafka managing the sockets, as it ostensibly has the best understanding of the connection to the broker

**Comment by guswynn** [comment]
@benesch ah yes, and ensure its configurable

**Comment by guswynn** [comment]
We can also probably add a flag for `socket.timeout.ms` and `socket.connection.setup.timeout.ms`

**Comment by benesch** [comment]
> We can also probably add a flag for `socket.timeout.ms` and `socket.connection.setup.timeout.ms`

That would be great.

**Comment by guswynn** [comment]
I am breaking "We don't apply keepalives to our own internal connections between services! https://github.com/MaterializeInc/materialize/issues/20299" out into its own issue
