### ISSUE TITLE
Web UI fails to load against latest `main`

### ISSUE THREAD

**Issue by benesch** [MaterializeInc/materialize#18684]
### What version of Materialize are you using?

07a8705801b77bda48cd61ad8190f7f75e66c304

### How did you install Materialize?

Materialize Cloud

### What is the issue?

Reported on Slack by @sploiselle, who was testing a custom build on staging: https://materializeinc.slack.com/archives/CL68GT3AT/p1680967496832069

![image](https://user-images.githubusercontent.com/882976/230820228-ffe5fae9-2b9e-4713-b718-268b9bb1f42e.png)

The problem seems to be that we're double-encoding the `options` parameter.

I believe this is a release blocker for v0.51 (next week) not v0.50 (this week), but someone should double check.

**Comment by parker-timmerman** [comment]
Fixed by: https://github.com/MaterializeInc/console/pull/114

**Comment by benesch** [comment]
Fixed by https://github.com/MaterializeInc/console/pull/114.

**Comment by chaas** [comment]
Thanks for the quick fix @parker-timmerman! Are there any learnings from this bug on a) additional automated testing and/or b) additional documentation on manual testing, that we could add to prevent this kind of issue in the future?
If so, could you file a follow up ticket?
