### ISSUE TITLE
'since' timestamp for indexes with metrics_retention >1 are not being held back

### ISSUE THREAD

**Issue by chaas** [MaterializeInc/materialize#18699]
### What version of Materialize are you using?

d72ac959d8c4eb507fc29f83f218fcba0a171081

### How did you install Materialize?

Materialize Cloud

### What is the issue?

The issue was first observed in the web console, where the cluster resource usage graphs are not showing historical data, only the single current value.

The query to fetch the data for those graphs is a `SUBSCRIBE .. AS OF` query, where the underlying tables and indexes have `is_retained_metrics_relation` set to true, meaning their retention should be 30 days. See https://github.com/MaterializeInc/materialize/pull/18400.

Strangely, the query returns historical data fine on staging. Also, running the same build that's currently on prod locally, the query returns historical data fine too.

**Comment by mjibson** [comment]
Should this be closed now @umanwizard?
