### ISSUE TITLE
Wrong result when using inequation operators on ranges

### ISSUE THREAD

**Issue by nrainer-materialize** [MaterializeInc/materialize#18726]
### What version of Materialize are you using?

v0.50.0-dev (f11e4d67e)

### How did you install Materialize?

Built from source

### What is the issue?

Inequality on range types seems to be broken and behavior is inconsistent with Postgres (https://www.postgresql.org/docs/9.3/functions-range.html).

```
select '[1,1]'::INT8RANGE < '[2,2]'::INT8RANGE;
```
returns `false` but should return `true`. The same applies to other operators, such as  `>`.

CC @sploiselle, @philip-stoev, @def-

**Comment by def-** [comment]
From the Postgres documentation:
> The simple comparison operators <, >, <=, and >= compare the lower bounds first, and only if those are equal, compare the upper bounds. These comparisons are not usually very useful for ranges, but are provided to allow B-tree indexes to be constructed on ranges.

**Comment by sploiselle** [comment]
The equality functions were correctly implemented, just incorrectly planned. ty for catching this.

**Comment by chaas** [comment]
@sploiselle is this fixed by https://github.com/MaterializeInc/materialize/pull/18817?

**Comment by sploiselle** [comment]
Fixed by https://github.com/MaterializeInc/materialize/pull/18817
