### ISSUE TITLE
Enforce testing of both monotonic and non-monotonic plans

### ISSUE THREAD

**Issue by vmarcos** [MaterializeInc/materialize#18734]
It is presently common to structure `sqllogictest` and `testdrive` tests such that functionality is validated by issuing one-shot `SELECT` queries. This strategy is based on the hidden assumption that execution of one-shot `SELECT` queries is representative of dataflow execution in other contexts, e.g., with indexed or materialized views. However, with PR https://github.com/MaterializeInc/materialize/pull/18546 and subsequent work bringing about performance improvements to one-shot `SELECT` queries, this assumption will be broken.

In particular, the plans produced in for one-shot `SELECT` queries will use monotonic operators whenever possible, implying that all tests that now exercise non-monotonic operator logic will stop doing so. The latter is concerning as indexed and materialized views must employ the non-monotonic versions.

To manage this change, PR https://github.com/MaterializeInc/materialize/pull/18546 introduces the feature flag `enable_monotonic_oneshot_selects`, which is turned off by default. Ideally, the feature flag be sunsetted at some point in the future. This issue is a request to devise a strategy to maintain (or even improve) our test coverage before that happens.

One alternative here is to change the execution frameworks for our tests such that one-shot `SELECT` statements start being executed redundantly at least as: (a) a normal one-shot `SELECT`, which will leverage single-time dataflow refinements, and (b) a `SELECT` over a corresponding indexed view, which will use regular non-monotonic operators and dataflow planning for streaming settings.

**Comment by uce** [comment]
The compute team will implement the feature and QA will consult on which tests to actually run given the expected impact on test execution times.
