### ISSUE TITLE
Feedback for Postgres CDC integration guide

### ISSUE THREAD

**Issue by chuck-alt-delete** [MaterializeInc/materialize#18764]
### Documentation request

While working with a customer to set up a postgres source, we ran into some friction points. Here is some feedback:
- Instead of "alter role", we should encourage folks to set up a new user specifically for replication to materialize. Something like
    ```sql
    CREATE USER materialize_replication_user WITH REPLICATION PASSWORD '<materialize_replication_user_password>';
    ```
- Instead of showing how to grant select on all tables, give a specific example for tables t1, t2, t3
- Instead of `IN SCHEMA schema` do something like `IN SCHEMA <your_schema>`
- When setting replica identity to full, we should do so for t1, t2, t3 to be consistent with the aforementioned suggestion

### Affected Pages

- https://materialize.com/docs/integrations/cdc-postgres/#direct-postgres-source

**Comment by chuck-alt-delete** [comment]
I will note that RDS is slightly different in that you cannot create a user with replication privileges. You have to do this instead:
```
CREATE ROLE my_materialize_replication_role;
GRANT rds_replication TO my_materialize_replication_role;
```

**Comment by chuck-alt-delete** [comment]
Also, it looks like we're missing a step for creating a connection before creating the source:
- https://materialize.com/docs/connect-sources/cdc-postgres-direct/

The connection is assumed to exist

**Comment by jseldess** [comment]
Fixed by https://github.com/MaterializeInc/materialize/pull/19453.
