### ISSUE TITLE
Consider adding a WMR hard limit

### ISSUE THREAD

**Issue by ggevay** [MaterializeInc/materialize#18832]
### Feature request

[Users often write divergent WMR queries by mistake while developing a query.](https://github.com/MaterializeInc/materialize/issues/16800) Now we have [proper dataflow cancellation](https://github.com/MaterializeInc/materialize/pull/18718) to stop these dataflows when the user hits Ctrl+C or the corresponding view is dropped. However, we might still want to consider having a default hard limit that errors out the dataflow after, say, 1000 steps. (And make it easily changeable by users.)

I think @frankmcsherry is opposed to this, while @antiguru might be a proponent of this feature, if I remember correctly.

One argument for this feature was that the cluster might OOM before the user realizes the problem and hits Ctrl+C. But unfortunately, this might also happen before hitting the limit, so the limit would prevent OOMing in only a narrow set of situations.

Examples in other systems:
- Postgres doesn't seem to have a default limit (or it's larger than 10000000). Discussion [here](https://www.postgresql.org/message-id/18351.1446039187%40sss.pgh.pa.us).
- MariaDB [used to have a similar default hard limit of 1000, but then it was raised to 4294967295](https://mariadb.com/kb/en/server-system-variables/#max_recursive_iterations), which is essentially no limit.
- MS SQL Server has a default limit of 100.
- [Google BigQuery has a default limit of 500, and it can't even be changed without involving customer support](https://cloud.google.com/bigquery/docs/reference/standard-sql/recursive-ctes#remove-limit).
- [Snowflake has a default limit of 100, changable only by customer support.](https://stackoverflow.com/questions/71347956/snowflake-recursion-exceeded-max-iteration-count-100)

Compared to other systems, our recursive query support is much more general, so we should not blindly follow them!

There is further discussion in the [WMR limits design doc](https://github.com/MaterializeInc/materialize/pull/18538).

**Comment by ggevay** [comment]
More Slack discussion: https://materializeinc.slack.com/archives/C015RHB3LDR/p1684920829567139?thread_ts=1684855280.479629&cid=C015RHB3LDR

**Comment by aalexandrov** [comment]
This should be resolved (along with finalization of the WMR concrete syntax) as a required issue before we can close #17012.

For the concrete syntax discussion, check [this slack thread](https://materializeinc.slack.com/archives/C015RHB3LDR/p1684855280479629).
