### ISSUE TITLE
Add `max_credits_per_hour` system limit

### ISSUE THREAD

**Issue by benesch** [MaterializeInc/materialize#18830]
### Feature request

Add a new `max_credits_per_hour` system limit, which restricts the maximum hourly credit burn of an environment.

Detailed proposal: https://www.notion.so/materialize/Self-guided-trial-viability-47c4b14f19b44c58a630d360a7e615a8?pvs=4#1c493d1fa3a94483a5da54f61f1e4f3c

Timeline: to hit next week's go live date, we need this limit to land in this week's release (i.e., by Friday 4/21 at 2pm ET).

cc @chaas @hlburak

**Comment by jkosh44** [comment]
What do we think the default for this limit should be?

**Comment by jkosh44** [comment]
Also we have a default replica mapping here:

https://github.com/MaterializeInc/materialize/blob/02ac7ebf3011f2bc2cc1503f580da3b1c5d6858c/src/adapter/src/catalog/config.rs#L80-L148

I'm pretty sure this is only used for testing. Is there a default mapping somewhere I should use or can I make something up? I was going to do credits = workers * scale.

**Comment by benesch** [comment]
> What do we think the default for this limit should be?

Maybe 64? I don't think the compiled-in limit matters too much; we'll dial it around in LD pretty immediately.

> Is there a default mapping somewhere I should use or can I make something up? I was going to do credits = workers * scale.

That's perfect.

**Comment by benesch** [comment]
> Is that accurate?

Unfortunately, yes. Do we not currently support `numeric` or `f64` settings? 😬

**Comment by jkosh44** [comment]
> > Is that accurate?
> 
> Unfortunately, yes. Do we not currently support `numeric` or `f64` settings? grimacing

We do not support either type of settings. That's fine, I have `f64` settings working locally. PostgreSQL uses `double` for these types of settings so we had to get around to it eventually.
