### ISSUE TITLE
Investigate regression in Avro decode throughput

### ISSUE THREAD

**Issue by ruchirK** [MaterializeInc/materialize#1883]
We used to go north of 100 mb/s (see #217 ) and today we are back to 40 - 60 mb/s

* why did this change?
* can we make it good again?

**Comment by cuongdo** [comment]
@umanwizard is there further work to be done for this issue?

**Comment by umanwizard** [comment]
Yes, we have it up to 80 MB/s (unscientific benchmark on my machine!) but we can get it up to at least 100 MB/s with some work I plan to get to this week (getting rid of the clone of field names for every record).

**Comment by umanwizard** [comment]
It can probably go above 200 MB/s with some more substantial work, but that should most likely be in a separate issue.

**Comment by rjnn** [comment]
Are these numbers per thread? And if so, can we read from k partitions at k*200 mb/s given enough cores?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by umanwizard** [comment]
@benesch can answer, he wrote the benchmark. (If he doesn’t know I’ll take a look tomorrow)

**Comment by benesch** [comment]
The benchmark is single threaded! Also note that the numbers are highly workload dependent. If your Avro payloads are 1MB each with just a single text field, well, that's going to decode a lot faster than a 1KB record with 256 ints.

**Comment by umanwizard** [comment]
@rjnn Also even if avro decide throughout were infinite, I think we might become bottlenecked on Kafka decode — though that’s not something we’ve measured yet

**Comment by rjnn** [comment]
Thanks!

**Comment by cuongdo** [comment]
This is well understood now and is superseded by #2133
