### ISSUE TITLE
Investigate our choice of allocator(s)

### ISSUE THREAD

**Issue by ruchirK** [MaterializeInc/materialize#1884]
Currently we run with jemalloc on Linux and the system allocator on macOS. While thats certainly workable we need to have robust answers for:

* why are we using jemalloc on Linux (alternatively whats the downside to switching to system allocator on Linux -- note that things like debuggability should factor in here as well as perf)
* Iff jemalloc is deemed worth using on Linux, can we make it work without latency issues on macOS?

**Comment by antiguru** [comment]
We're using jemalloc in production and by default on Linux, but can enable or disable it on MacOS if needed. Closing as we're relying on jemalloc's infrastructure for allocation profiling.
