### ISSUE TITLE
RBAC docs

### ISSUE THREAD

**Issue by chaas** [MaterializeInc/materialize#18849]
@jkosh44  has been adding in reference documentation throughout implementation, but we'll also want
a) conceptual docs introducing RBAC and 
b) guidance on how to set up RBAC

Our implementation mirrors Postgres's, so there's lots of examples.
The main difference between our RBAC and Postgres is the presence of clusters. In addition to the hierarchical database-schema-object model that exists in Postgres, we also have clusters, which are orthogonal. For example, a user needs to have both access to an object and a cluster in order to run a subscribe query for that object on that cluster.

From @jkosh44:

> Here is a list of the existing reference docs related to RBAC:
> https://materialize.com/docs/sql/create-role/
> https://materialize.com/docs/sql/alter-role/
> https://materialize.com/docs/sql/drop-role/
> https://materialize.com/docs/sql/drop-user/
> https://materialize.com/docs/sql/alter-owner/
> https://materialize.com/docs/sql/grant-role/
> https://materialize.com/docs/sql/revoke-role/
> 
> Here are two open PRs that include RBAC docs, these are the last reference docs for RBAC related SQL commands:
> https://github.com/MaterializeInc/materialize/pull/18799
> https://github.com/MaterializeInc/materialize/pull/18811
> 
> Here are the PostgreSQL docs that talk about their RBAC features:
> https://www.postgresql.org/docs/current/user-manag.html
> https://www.postgresql.org/docs/current/ddl-priv.html

There may also be implications for the get started guides.
E.g. the first user is an admin and has superuser privileges. Subsequent users for an org will need to be granted those privileges.

**Comment by tr0njavolta** [comment]
#19222
