### ISSUE TITLE
SINK documentation should say more about available Kafka knobs and common scenarios

### ISSUE THREAD

**Issue by rjnn** [MaterializeInc/materialize#18848]
### Documentation request

In Kafka SINKS, we have the power to create topics on the Kafka broker if one does not already exist.

There are certain assumptions we have made in our product about how you have configured your Kafka broker, as Kafka itself has various configuration knobs. 
For instance, when you create a sink, either you've pre-created the kafka topic, or you are expecting Materialize to create a Kafka topic for you. In the latter instance, there are some configuration knobs you can supply us with, which we will in turn supply kafka with in (e.g. the number of partitions to configure that topic with). If you don't supply those knobs, Kafka has some config parameters for what the default should be (`num.partitions`) for new topics. Today, if you haven't supplied that, and you haven't set that parameter, we error out with:
`ERROR: error registering kafka topic for sink: default was requested for partition_count, but num.partitions was not found in broker config`

While that specific error feels like a bug (which will likely be addressed before this docs request), the _documentation_ request is that we explain this background situation to the user more thoroughly. Right now CMD+F "partition" on the SINKS documentation page returns zero results, and that is the specific docs ask.

### Affected Pages

https://materialize.com/docs/sql/create-sink/kafka/

### Related work

https://materializeinc.slack.com/archives/C01CFKM1QRF/p1681924452485939

**Comment by morsapaes** [comment]
Linking to #18853.

**Comment by benesch** [comment]
Also linking in #14656.

---

FWIW, setting `PARTITION COUNT` is no longer supported! Until we bring back that option, I don't think there is too much to say about partitions in the docs! Maybe something like this:

> If the topic does not yet exist in the Kafka cluster, Materialize will attempt to create it, using the Kafka cluster's default number of partitions and replication factor.

**Comment by bkirwi** [comment]
We currently believe that the underlying cause of #18853 is an ACL issue. (The code requires the DescribeConfigs permission on the cluster resource -- which it probably shouldn't -- and the error message does not implicate ACLs -- which it should.)

But that reminds me that we don't actually document what ACLs are required for our sources and sinks to work successfully! Which seems like a really helpful thing to document as well, even once #18853 had landed.
