### ISSUE TITLE
Document how to compute credit consumption rate

### ISSUE THREAD

**Issue by benesch** [MaterializeInc/materialize#18882]
### Documentation request

In https://github.com/MaterializeInc/materialize/pull/18846, we're adding a `max_credits_per_hour` limit (caveat: name may change), which restricts the maximum number of cluster replicas that can exist at a given instant based on the credit consumption rate.

Users may want to monitor their credit consumption against this limit. We should document the query users can run to determine the number of credits their region is consuming:

```sql
SELECT sum(s.credits_per_hour) AS total_credits_per_hour
FROM mz_cluster_replicas r
JOIN mz_internal.mz_cluster_replica_sizes s ON r.size = s.size;
```

Details: https://www.notion.so/materialize/Self-guided-trial-viability-47c4b14f19b44c58a630d360a7e615a8?d=a72803ebd9cb4ef1bbb4515b0e1f7107#2b9f355a4532417193faf1d69a9d4123

cc @jseldess @jkosh44 @ch

**Comment by morsapaes** [comment]
Making it clearer here that the new `credits_per_hour` column is only shipping with `v0.52.2` later this week.
