### ISSUE TITLE
[coverage] Sporadic failure in test_auth_expiry: panicked at 'called `Result::unwrap()` on an `Err` value: "expected refresh count 2, got 1"', src/environmentd/tests/auth.rs:776:10

### ISSUE THREAD

**Issue by def-** [MaterializeInc/materialize#18904]
### What version of Materialize are you using?

c65dc06c05a5fa438fc68d4daa9d397d603aae38

### How did you install Materialize?

Built from source

### What is the issue?

`cargo llvm-cov nextest --no-clean -j 16 --workspace test_auth_expiry` sometimes fails, might be timing-related since coverage increases running time.

`cargo install cargo-llvm-cov cargo-nextest` to be able to run it locally.

Noticed as part of enabling unit test coverage.

@mjibson I noticed that we had similar issues a few times: https://github.com/MaterializeInc/materialize/issues/12342 and https://github.com/MaterializeInc/materialize/pull/14246

### Relevant log output

```source
thread 'test_auth_expiry' panicked at 'called `Result::unwrap()` on an `Err` value: "expected refresh count 2, got 1"', src/environmentd/tests/auth.rs:776:10
stack backtrace:
   0: rust_begin_unwind
             at /rustc/8bdcc62cb0362869f0e7b43a6ae4f96b953d3cbc/library/std/src/panicking.rs:578:5
   1: core::panicking::panic_fmt
             at /rustc/8bdcc62cb0362869f0e7b43a6ae4f96b953d3cbc/library/core/src/panicking.rs:67:14
   2: core::result::unwrap_failed
             at /rustc/8bdcc62cb0362869f0e7b43a6ae4f96b953d3cbc/library/core/src/result.rs:1651:5
   3: <core::result::Result<(), alloc::string::String>>::unwrap
             at /rustc/8bdcc62cb0362869f0e7b43a6ae4f96b953d3cbc/library/core/src/result.rs:1076:23
   4: auth::wait_for_refresh
             at ./tests/auth.rs:762:5
   5: auth::test_auth_expiry
             at ./tests/auth.rs:854:5
   6: auth::test_auth_expiry::{closure#0}
             at ./tests/auth.rs:781:23
   7: <auth::test_auth_expiry::{closure#0} as core::ops::function::FnOnce<()>>::call_once
             at /rustc/8bdcc62cb0362869f0e7b43a6ae4f96b953d3cbc/library/core/src/ops/function.rs:250:5
   8: core::ops::function::FnOnce::call_once
             at /rustc/8bdcc62cb0362869f0e7b43a6ae4f96b953d3cbc/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by mjibson** [comment]
Yup. Previous fixes have been to keep bumping the timeout. If it's slower in coverage, gotta bump some more?

**Comment by def-** [comment]
I was hoping there would be a more elegant solution. I'll do so in the change introducing unit test coverage: https://github.com/MaterializeInc/materialize/pull/18903
