### ISSUE TITLE
sql: improve ergonomics of setting current schema / `search_path`

### ISSUE THREAD

**Issue by chaas** [MaterializeInc/materialize#18946]
*New proposal.* Expanded from @mjibson in https://github.com/MaterializeInc/materialize/issues/18946#issuecomment-1532155294. 

* Allow `SET schema {= | TO} {ident | string}`. This deviates from PostgreSQL, which allows only `SET SCHEMA {string}`, but is consistent with `SET DATABASE` and `SET CLUSTER`.
* Do *not* allow multiple schemas, as in `SET SCHEMA = s1, s2, public`. Users who want to use multiple schemas need to use the `search_path`.
* Add `SHOW schema`, which functions as `SELECT current_schema()`.
* Teach `SHOW database`, `SHOW cluster`, and `SHOW schema` to report a notice if the shown database, cluster, or schema does not exist.

After much discussion, the above proposal is thought to best thread the needle between "match PostgreSQL" and "match user expectations." The weirdest part of the proposal is the fact that `SHOW schema` must show _one_ schema, even if the search path contains multiple schemas. Fortunately, the "current schema" is already a concept in PostgreSQL: it's the schema in which new objects will be created if a schema is not explicitly specified in the DDL statement.

-----

*Initial proposal; superseded.*

~`SCHEMA` is actually an alias for `search_path`.~
~In PG you omit the TO/= when you're using an alias, and you include it when you specify the configuration parameter directly.~

~So you can run `SET SCHEMA foo` or `SET search_path = foo`.~
~This UX is confusing because users typically run `SET DATABASE = bar` first, then expect `SET SCHEMA = foo` to work too. They don't realize SCHEMA is an alias and we don't tell them to use search_path anywhere.~

~When a user types `SET SCHEMA = foo` we should reject it with a hint to type `SET SCHEMA foo` instead.~

**Comment by morsapaes** [comment]
Since `schema` is an alias for `search_path`, should we also support `SHOW schema`? It's a bit confusing that you can type `SET SCHEMA qck`, but then are forced to type `SHOW search_path`.

**Comment by benesch** [comment]
> Since `schema` is an alias for `search_path`, should we also support `SHOW schema`? It's a bit confusing that you can type `SET schema qck`, but then are forced to type `SHOW search_path`.

`schema` is not quite an alias for `search_path`; rather `SET SCHEMA <string lit>` is an alias for `SET search_path TO <string lit>`, and only single-schema search paths can be specified like this:

<img width="935" alt="image" src="https://user-images.githubusercontent.com/882976/235386675-60883040-caf0-4f02-a2b0-1a002ba59e7e.png">

There's no sane way to implement `SHOW SCHEMA` AFAICT—what would it return if the search path was `foo, bar`? Even if `SHOW SCHEMA` returned `foo, bar` in that case, I think that actually makes the consistency of the system _worse_, because you can't type `SET SCHEMA foo, bar`.

My recommendation is to bury `SET SCHEMA` in our docs as deep as possible. The `SET SCHEMA` abstraction breaks so quickly that I think we want to rip the complexity bandaid off here in the docs: explain what a `search_path` is, and always recommend that users use `SET search_path` and `SHOW search_path`. It's not _that_ complicated, and we can draw analogy to the `$PATH` environment variable.

**Comment by chaas** [comment]
I agree it'll be easier to just work with `search_path` and have our docs tell folks to use `SET/SHOW search_path`.

I'm assuming we'll still need users to run `CREATE SCHEMA <value>` and `SHOW SCHEMAS`. In which case I do think folks will still try to do `SET schema`, but a hint can still work here.

**Comment by morsapaes** [comment]
> because you can't type SET SCHEMA foo, bar

It seems like you can, in Materialize:

```sql
materialize=> set schema public, qck;
SET
materialize=> show search_path;
 search_path
-------------
 public, qck
(1 row)
```

But not in Postgres, as expected (and it turns out you're forced to use single quotes with `SET SCHEMA`):

```sql
postgres=> SET search_path = public, qck;
SET
postgres=> SHOW search_path;
 search_path
-------------
 public, qck
(1 row)

postgres=> SET schema public, qck;
ERROR:  syntax error at or near "public"
LINE 1: SET schema public, qck;

postgres=> set schema public;
ERROR:  syntax error at or near "public"
LINE 1: set schema public;
                   ^
postgres=> set schema 'public';
SET
```

**Comment by mjibson** [comment]
Proposal:

- `SET SCHEMA = <ident>` will set the search_path to ident. It will issue a notice of ident is not a schema.
- `SHOW SCHEMA` is sugar for `SELECT current_schema()` which returns the first resolvable schema in the search path. It will return NULL if there is no resolvable schema. In the NULL case it will also issue a notice saying like "there's no schema in from the search path: <search_path>"

**Comment by benesch** [comment]
`USE SCHEMA` interacts with `ALTER SESSION SET search_path` in Snowflake ([details](https://docs.snowflake.com/en/sql-reference/name-resolution#queries)), so I feel even better about @mjibson's proposal.

**Comment by benesch** [comment]
I've updated the issue description with an expanded version of @mjibson's proposal. Let me know if any questions. 

@morsapaes @rjnn @sjwiesman — I believe you've all had complaints about the existing `SET SCHEMA` experience. Can you take a look at the proposal in the issue description and render an opinion on whether it addresses your concerns?

**Comment by sjwiesman** [comment]
This looks sensible to me

**Comment by morsapaes** [comment]
LGTM. It makes sense to deviate from PostgreSQL when there's clear usability improvements, like in this case.

**Comment by jkosh44** [comment]
> Teach SHOW database, SHOW cluster, and SHOW schema to report a notice if the shown database, cluster, or schema does not exist.

I'm not sure this makes a ton of sense for `SHOW SCHEMA`. It will never show a schema that does not exist, instead it will just return `NULL`. Should we send a notice in the `NULL` case saying something like "no resolvable schemas on the search path"? 

Also, this is probably OK but I wanted to point out that schemas still behave differently than databases and clusters with regards to non-resolvable names. For example (I've removed the notices):
```
materialize=> SET DATABASE TO 'non-resolvable-name';
SET
materialize=> SHOW database;
      database       
---------------------
 non-resolvable-name
(1 row)

materialize=> SET CLUSTER TO 'non-resolvable-name';
SET
materialize=> SHOW cluster;
       cluster       
---------------------
 non-resolvable-name
(1 row)

materialize=> SET SCHEMA TO 'non-resolvable-name';
SET
materialize=> SHOW SCHEMA;
 schema 
--------
 <null>
```

**Comment by mjibson** [comment]
> Should we send a notice in the NULL case saying something like "no resolvable schemas on the search path"

This was in the [original proposal](https://github.com/MaterializeInc/materialize/issues/18946#issuecomment-1532155294), maybe it didn't make it to the edited comment above (or was maybe removed on purpose
?):

> In the NULL case it will also issue a notice saying like "there's no schema in from the search path: <search_path>"

**Comment by benesch** [comment]
Not removed on purpose. Having a slightly different NOTICE for nonexistent
schemas makes sense to me. There’s no getting around a little inconsistency
given that schemas have search paths but nothing else does.
