### ISSUE TITLE
postgres source refuses to ingest after systematic upgrade from v0.39.3 to HEAD

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#18940]
### What version of Materialize are you using?

3e77515eba1c96582deeb1a0267d532f6d29dacc

### How did you install Materialize?

Docker image

### What is the issue?

ci-regexp: 22:1: error: non-matching rows: expected:

We have a new test in Nightly that performs upgrades by the book, version-by-version, starting from older Mz versions. If the upgrade starts from version `v0.39.3`, by the time the Mz binary is upgraded to `HEAD`, one out of 3 postgres sources is showing up empty.

While `v0.39.3` is a release from January, I would caution against calling it very old or trying to figure out if there are postgres sources in production that are that old. Instead, I think `HEAD` should not have gotten into the state described to start with, regardless of what previous versions are involved. It may be that the sheer number of restarts is what causes the issue to trigger, rather than the starting Mz version.

To reproduce, install the specific upgrade scenario that is problematic as follows:

```
diff --git a/misc/python/materialize/checks/scenarios_upgrade.py b/misc/python/materialize/checks/scenarios_upgrade.py
index 94f9e01ec..0632f775c 100644
--- a/misc/python/materialize/checks/scenarios_upgrade.py
+++ b/misc/python/materialize/checks/scenarios_upgrade.py
@@ -215,3 +215,43 @@ class UpgradeClusterdComputeFirst(Scenario):
             StartMz(tag=None),
             Validate(self),
         ]
+
+
+class UpgradeBug(Scenario):
+    def base_version(self) -> MzVersion:
+        return MzVersion.parse("0.39.3")
+
+    def actions(self) -> List[Action]:
+        return [
+            StartMz(bootstrap_system_parameters=[], tag=MzVersion.parse("0.39.3")),
+            Initialize(self),
+            Manipulate(self, phase=1),
+            Manipulate(self, phase=2),
+            KillMz(),
+            StartMz(bootstrap_system_parameters=[], tag=MzVersion.parse("0.40.0")),
+            KillMz(),
+            StartMz(bootstrap_system_parameters=[], tag=MzVersion.parse("0.41.1")),
+            KillMz(),
+            StartMz(bootstrap_system_parameters=[], tag=MzVersion.parse("0.42.4")),
+            KillMz(),
+            StartMz(bootstrap_system_parameters=[], tag=MzVersion.parse("0.43.0")),
+            KillMz(),
+            StartMz(bootstrap_system_parameters=[], tag=MzVersion.parse("0.44.3")),
+            KillMz(),
+            StartMz(bootstrap_system_parameters=[], tag=MzVersion.parse("0.45.0")),
+            KillMz(),
+            StartMz(bootstrap_system_parameters=[], tag=MzVersion.parse("0.46.1")),
+            KillMz(),
+            StartMz(bootstrap_system_parameters=[], tag=MzVersion.parse("0.47.1")),
+            KillMz(),
+            StartMz(bootstrap_system_parameters=[], tag=MzVersion.parse("0.48.4")),
+            KillMz(),
+            StartMz(bootstrap_system_parameters=[], tag=MzVersion.parse("0.49.6")),
+            KillMz(),
+            StartMz(bootstrap_system_parameters=[], tag=MzVersion.parse("0.50.3")),
+            KillMz(),
+            StartMz(bootstrap_system_parameters=[], tag=MzVersion.parse("0.51.0")),
+            KillMz(),
+            StartMz(tag=None),
+            Validate(self),
+        ]
```

and then run it:

```
cd test/platform-checks
./mzcompose down -v ; ./mzcompose run default --scenario=UpgradeBug --check=PgCdc
```

On the first or second try, it will fail like this:

```


[2023-04-25T07:05:10Z] > SELECT f1, max(f2), SUM(LENGTH(f3)) FROM postgres_source_tableC GROUP BY f1;
--
  | [2023-04-25T07:10:10Z] rows didn't match; sleeping to see if dataflow catches up 50ms 75ms 113ms 169ms 253ms 380ms 570ms 854ms 1s 2s 3s 4s 6s 10s 15s 22s 33s 49s 74s 77s
  | [2023-04-25T07:10:10Z] 22:1: error: non-matching rows: expected:
  | [2023-04-25T07:10:10Z] [["A", "800", "97350"], ["B", "800", "97350"], ["C", "700", "97350"], ["D", "600", "97350"], ["E", "500", "97350"], ["F", "400", "97350"], ["G", "300", "97350"], ["H", "200", "97350"]]
  | [2023-04-25T07:10:10Z] got:
  | [2023-04-25T07:10:10Z] []
  | [2023-04-25T07:10:10Z] Poor diff:
  | [2023-04-25T07:10:10Z] - A 800 97350
  | [2023-04-25T07:10:10Z] - B 800 97350
  | [2023-04-25T07:10:10Z] - C 700 97350
  | [2023-04-25T07:10:10Z] - D 600 97350
  | [2023-04-25T07:10:10Z] - E 500 97350
  | [2023-04-25T07:10:10Z] - F 400 97350
  | [2023-04-25T07:10:10Z] - G 300 97350
  | [2023-04-25T07:10:10Z] - H 200 97350
  | [2023-04-25T07:10:10Z]
  | [2023-04-25T07:10:10Z]      \|
  | [2023-04-25T07:10:10Z]   21 \|
  | [2023-04-25T07:10:10Z]   22 \| > SELECT f1, max(f2), SUM(LENGTH(f3)) FROM postgres_source_tableC GROUP BY f1;
  | [2023-04-25T07:10:10Z]      \| ^


```

If you log in the Mz instance, you will see 2 postgres sources / 2 tables properly replicated and 1 that is stuck at tempty. All postgres sources replicate the same upstream table, but under different names. The `_progress` source of the problematic postgres source reports an LSN that is different from the one of the 2 working sources.

**Comment by aljoscha** [comment]
@sploiselle and/or @petrosagg, I have a feeling we did have migrations for in-between versions, but those have been removed because we only care about upgrades from the past version.

**Comment by sploiselle** [comment]
👀

**Comment by sploiselle** [comment]
The shortest path I have been able to find that repros is 0.39.3 to 0.46.1

However, if I add `Validate(self)` after each `StartMz`, it no longer repros (within 4 runs, whereas I'm typically able to repro within 2 runs).

**Comment by sploiselle** [comment]
I've spent the morning running this and have narrowed it down to occurring for sources that are created at `v0.46.1` or older and are not read for the first time until `v0.46.1` or later. However, I was getting very consistent reproductions for a bit this morning and things have stopped failing as often and I've begun to doubt my sanity.

To better understand this, I need access to the logs of both the instance where the source was initially created and the instance that's failing; however, we truncate all of the logs on killing/bringing back up instances.

Right now my hunch is that we are testing a `pg-cdc-resumption`-like scenario that fails, where we fail before the snapshot completes. In v0.46.1 there was some work to handle frontiers differently, and I am wondering if we have a snapshot that failed on one side of v0.46.1 and is allowed to complete on the other side of v0.46.1, it runs into issues where it believes the snapshot completed but never did. Speculation, though.

@philip-stoev Given that I am unable to repro this failure with the addition of `Validate(self)` on the upgrades, would you feel comfortable removing the `release-blocker` tag? In a realistic upgrade scenario, the source would have had enough time to "catch up" between the upgrades. Here is what I propose is more realistic in prod:

```python

class UpgradeBug(Scenario):
    def base_version(self) -> MzVersion:
        return MzVersion.parse("0.39.3")

    def actions(self) -> List[Action]:
        return [
            StartMz(bootstrap_system_parameters=[], tag=MzVersion.parse("0.39.3")),
            Initialize(self),
            Manipulate(self, phase=1),
            Manipulate(self, phase=2),
            Validate(self),
            KillMz(),
            StartMz(bootstrap_system_parameters=[], tag=MzVersion.parse("0.40.0")),
            Validate(self),
            KillMz(),
            StartMz(bootstrap_system_parameters=[], tag=MzVersion.parse("0.41.1")),
            Validate(self),
            KillMz(),
            StartMz(bootstrap_system_parameters=[], tag=MzVersion.parse("0.42.4")),
            Validate(self),
            KillMz(),
            StartMz(bootstrap_system_parameters=[], tag=MzVersion.parse("0.43.0")),
            Validate(self),
            KillMz(),
            StartMz(bootstrap_system_parameters=[], tag=MzVersion.parse("0.44.3")),
            Validate(self),
            KillMz(),
            StartMz(bootstrap_system_parameters=[], tag=MzVersion.parse("0.45.0")),
            Validate(self),
            KillMz(),
            StartMz(bootstrap_system_parameters=[], tag=MzVersion.parse("0.46.1")),
            Validate(self),
            KillMz(),
            StartMz(bootstrap_system_parameters=[], tag=MzVersion.parse("0.47.1")),
            Validate(self),
            KillMz(),
            StartMz(bootstrap_system_parameters=[], tag=MzVersion.parse("0.48.4")),
            Validate(self),
            KillMz(),
            StartMz(bootstrap_system_parameters=[], tag=MzVersion.parse("0.49.6")),
            Validate(self),
            KillMz(),
            StartMz(bootstrap_system_parameters=[], tag=MzVersion.parse("0.50.3")),
            Validate(self),
            KillMz(),
            StartMz(bootstrap_system_parameters=[], tag=MzVersion.parse("0.51.0")),
            Validate(self),
            KillMz(),
            StartMz(tag=None),
            Validate(self),
        ]
```

This ensures that the original snapshot completes; however, if this isn't as stressful as you were hoping, we could rewrite the manipulate functions to delete everything from the tables (phase1) and then restore the state (phase2), expecting all of this to "even out" at each iteration.

Alternatively, we can try to chase down the cause of this issue, though I think the bug might be more something more esoteric than we intend.

**Comment by philip-stoev** [comment]
I am removing the release blocker tag given that v0.46.1 is implicated, so this must predate any recent refactorings. Apologies for the alarm.

**Comment by dseisun-materialize** [comment]
Just checking that we're good to close here given we're well past this version upgrade? (but transparently didn't read the nuances of the ticket closely)

**Comment by sploiselle** [comment]
I defer to Phillip but that this has not impacted anyone running PG sources in production suggests to me that this is an issue only in the abstract at this point.

**Comment by sploiselle** [comment]
This is good to close as it seems to have been an error in a version we will never run again
