### ISSUE TITLE
adapter: `EXPLAIN TIMESTAMP` is not run transactionally

### ISSUE THREAD

**Issue by jkosh44** [MaterializeInc/materialize#18950]
### What version of Materialize are you using?

v.0.53.0-dev

### How did you install Materialize?

Built from source

### What is the issue?

When `EXPLAIN TIMESTAMP` is run as part of a transaction, it should do the following three things:
- Select a transaction timestamp if one hasn't been selected yet.
- Acquire read holds if they haven't been acquired yet.
- Always return the same value for `query timestamp`.

Currently it doesn't do those three things.

### Relevant log output

```source
materialize=> CREATE TABLE t (a INT);
CREATE TABLE
materialize=> BEGIN;
BEGIN
materialize=*> EXPLAIN TIMESTAMP FOR SELECT * FROM t;
                                 Timestamp                                 
---------------------------------------------------------------------------
                 query timestamp: 1682438637118 (2023-04-25 16:03:57.118) +
           oracle read timestamp: 1682438637118 (2023-04-25 16:03:57.118) +
 largest not in advance of upper: 1682438637118 (2023-04-25 16:03:57.118) +
                           upper:[1682438637119 (2023-04-25 16:03:57.119)]+
                           since:[1682438636000 (2023-04-25 16:03:56.000)]+
         can respond immediately: true                                    +
                        timeline: Some(EpochMilliseconds)                 +
                                                                          +
 source materialize.public.t (u1, storage):                               +
                   read frontier:[1682438636000 (2023-04-25 16:03:56.000)]+
                  write frontier:[1682438637119 (2023-04-25 16:03:57.119)]+
 
(1 row)

materialize=*> EXPLAIN TIMESTAMP FOR SELECT * FROM t;
                                 Timestamp                                 
---------------------------------------------------------------------------
                 query timestamp: 1682438638120 (2023-04-25 16:03:58.120) +
           oracle read timestamp: 1682438638120 (2023-04-25 16:03:58.120) +
 largest not in advance of upper: 1682438638120 (2023-04-25 16:03:58.120) +
                           upper:[1682438638121 (2023-04-25 16:03:58.121)]+
                           since:[1682438637000 (2023-04-25 16:03:57.000)]+
         can respond immediately: true                                    +
                        timeline: Some(EpochMilliseconds)                 +
                                                                          +
 source materialize.public.t (u1, storage):                               +
                   read frontier:[1682438637000 (2023-04-25 16:03:57.000)]+
                  write frontier:[1682438638121 (2023-04-25 16:03:58.121)]+
 
(1 row)
```

**Comment by rkrishn7** [comment]
Hey @jkosh44, I can take a stab at this one if that's alright!

Just for my understanding:

- We need to acquire read holds to demonstrate that any dependent sources will not compacted during the transaction. I say "demonstrate" because it seems we only really _need_ to block compaction at the time we start reading, which `EXPLAIN` never actually does.
- The query timestamp should be presented as the same across all reads as these should occur at a single logical timestamp (i.e. the "transaction timestamp").

Definitely could be missing something so would be much appreciated if you could point out any gaps in my thinking.

**Comment by jkosh44** [comment]
Hi @rkrishn7, you can take a stab, but I think there's still a little design work that's needed for this issue. Let me give you some background on how read transactions without `EXPLAIN` currently work, sorry if you know all of this already.

1. A user types `BEGIN`, we update the user's session to indicate that they are in a transaction, but we don't actually do much else.
2. A user executes some `SELECT` query. We do the following:
  a. Collect a set of objects that are in the transaction's time domain. Additional queries in the same transaction can only reference these objects. You can read a little more about that here: https://materialize.com/docs/sql/begin/#same-timedomain-error.
  b. Select a timestamp for the transaction. This timestamp will be used for the current query and all future queries within the transaction. For this issue it's not that important to understand how we do this.
  c. Acquire read holds on all objects within our time domain at the selected timestamp. These read holds will prevent compaction on these objects past the selected timestamp. This guarantees that we can query any object in the same time domain for the duration of our transaction.
3. A user executes another `SELECT` query. We execute this query at the already chosen timestamp.
Committing a transaction isn't important for this issue.

Currently `EXPLAIN TIMESTAMP` has no idea if there is an active transaction. There are a couple of things that potentially need to be done as part of this issue.

1. If we are in an active read transaction AND a timestamp has already been selected from a previous query, then `EXPLAIN TIMESTAMP` should return the transaction timestamp as the `query timestamp`. I'm fairly confident that this is the right thing to do, but open to alternatives. An open question here is, what should we do if `EXPLAIN TIMESTAMP` is executed on objects outside of our time domain? One option is to return an error and abort the transaction. That doesn't feel too good, but may be just as bad as aborting a transaction due to a typo. The other option is to return a response that indicates that there is no valid timestamp without aborting the transaction.
2. If we are in an active read transaction AND a timestamp has NOT already been selected, then should `EXPLAIN TIMESTAMP` pick a time domain, select a timestamp, and acquire read holds? When I wrote this issue I thought the answer was yes, but not I'm not as convinced. Perhaps it should just inform the user of what timestamp would have been selected if it was an actual read, but not have any real side-effects (CC @mjibson who originally made this point).
3. If we run `EXPLAIN TIMESTAMP` in a write only transaction then what should happen?

**Comment by mjibson** [comment]
> EXPLAIN TIMESTAMP should return the transaction timestamp as the query timestamp

Agree.

> what should we do if EXPLAIN TIMESTAMP is executed on objects outside of our time domain

Return an error just like SELECT would.

> a timestamp has NOT already been selected, then should EXPLAIN TIMESTAMP pick a time domain, select a timestamp, and acquire read holds

Yes!

> If we run EXPLAIN TIMESTAMP in a write only transaction then what should happen

Write-only transactions very importantly get their timestamp during COMMIT so don't have a timestamp to display. This should be an error.

I think my summary of all of the above is: EXPLAIN acts *exactly* like SELECT inside of a transaction.

**Comment by rkrishn7** [comment]
Thank you for all that context! Super helpful as I try to get a better understanding of things.

In particular, I didn't realize that holds were acquired for all "queryable" objects. I had assumed they were on newly dependent sources as reads get issued.

**Comment by jkosh44** [comment]
> In particular, I didn't realize that holds were acquired for all "queryable" objects. I had assumed they were on newly dependent sources as reads get issued.

The issue there would be that it might already be too late to acquire a read hold if some object has been compacted past when we want to query.
