### ISSUE TITLE
Add documentation for FORMAT JSON

### ISSUE THREAD

**Issue by sjwiesman** [MaterializeInc/materialize#18979]
### Documentation request

We need docs to follow up https://github.com/MaterializeInc/materialize/pull/18822. 

There are also a number of examples in the Kafka docs we cast bytes to JSON that should be updated to use the new format.

**Comment by morsapaes** [comment]
AFAICT, this is [behind a feature flag](https://github.com/MaterializeInc/materialize/blob/596ce0e484e174bb837a054c0cfc3fe13e2200f3/src/sql/src/session/vars.rs#L708). The motivation behind the initial implementation was internal, to unblock some work related to MFP pushdown. It's unclear (at least to me) what the plans are to roll the format out to sources.

```sql
CREATE SOURCE src 
FROM KAFKA CONNECTION analytics_upstash_kafka (TOPIC = 'pageviews') 
FORMAT JSON WITH (SIZE = '3xsmall');
ERROR:  `FORMAT JSON` is not enabled
DETAIL:  The requested feature is not currently enabled on this account.
```

To avoid confusion, `FORMAT JSON` has always been supported for sinks (see [`CREATE SINK`](https://materialize.com/docs/sql/create-sink/#json)); what Seth is referring to is specific to sources.
