### ISSUE TITLE
Separate docs deploy pipeline

### ISSUE THREAD

**Issue by jseldess** [MaterializeInc/materialize#18991]
### Buildkite link

N/A

### Describe your frustration

Today, if a PR just touches `/doc`, after merging to `main`, CI runs through all tests, and it takes quite a while before the live docs site is updated. 

### Describe the expected ideal experience

It would be great if we could special case docs, and have a separate docs deploy pipeline that deploys docs immediately after the “lint docs” test succeeds.

**Comment by philip-stoev** [comment]
@benesch I have no rights to view or modify the configuration of the current Deploy pipeline. Would it be possible to get access to it? If not, then it would be difficult for the QA team to work on this task.

**Comment by benesch** [comment]
I don’t think we need to change the configuration of the existing deploy pipeline in Buildkite! Rather, we need to create a new “deploy docs” pipeline, add a trigger step to the tests pipeline on main only that triggers the “deploy docs” pipeline, and move the deploy docs job from the deploy/pipeline.yml file in the repo to a new deploy-docs/pipeline.yml file in the repo that defines the pipeline for the new “deploy docs” build.

I’m happy to take care of this if that description doesn’t make sense.

**Comment by benesch** [comment]
Just ran an timing experiment for the new behavior with PR https://github.com/MaterializeInc/materialize/pull/19141. Took just a hair over 5m from the time I pressed merge on the PR to the time I was able to see the live change on the docs website, as measured with a stopwatch. 🎉
