### ISSUE TITLE
Surface privatelink connection status to users

### ISSUE THREAD

**Issue by alex-hunt-materialize** [MaterializeInc/materialize#19022]
### Feature request

We have two levels of privatelink connection status which are not currently exposed to the user:
1. The privatelink connection itself (ie: VPC Endpoint status).
    a. This is not currently exposed to environmentd, that is being worked on in https://github.com/MaterializeInc/cloud/issues/6276 .
    b. After the above issue is done, this needs to be surfaced to users.
2. Connection to individual kafka brokers or postgres databases over the privatelink connection.

The db can surface this information to the user and do its own troubleshooting (either surfaces or storage?)
a. Db knows what port its trying to connect
b. Db knows which AZs it is using
c. Db knows which protocols it’s using
We should attempt to connect on the appropriate port/AZ/protocol combination after PG or Kafka connection creation, and surface the results of these connection attempts to the user.

**Comment by benesch** [comment]
Here is a proto-design document for this feature. The next step is to turn this into a real design document.

----

We add a new system table called `mz_internal.mz_aws_privatelink_connection_status_history` with the following columns:

Name | Type | Description
------|-----|-----
`id`  | `text` |  The ID of the AWS PrivateLink connection.
`status` | `text` | The status of the AWS PrivateLink connection: `pending-service-discovery`, `creating-endpoint`, `recreating-endpoint`, `updating-endpoint`, `available`, `expired`, `failed`, `pending`, `pending-acceptance`, `rejected`, `unknown`
`occurred_at` | `timestamptz` | Wall clock timestamp of the connection status change.

This is modeled after `mz_internal.mz_source_status_history`.

The table will be maintained by the adapter. The `CloudResourceController` will expose a `watch_vpc_endpoints` method, like the `watch_services` endpoint exposed by the `KubernetesOrchestrator`. The `watch_vpc_endpoints` method will establish a Kubernetes watch on all `VpcEndpoint`s in the namespace and translate them into `VpcEndpointEvent`s. The adapter will be responsible for reading these events and turning them into writes to the `mz_internal.mz_aws_privatelink_connection_status_history` table.
