### ISSUE TITLE
Support `SASL_PLAINTEXT` authentication mechanism

### ISSUE THREAD

**Issue by sjwiesman** [MaterializeInc/materialize#19039]
### Feature request

Materialize Kafka only supports SASL_SSL. If a user tries to connect to brokers configured for SASL_PLAINTEXT we log an error and silently fail to ingest data. 

> sasl_ssl://20.100.194.205:9092/bootstrap: SSL handshake failed: Disconnected: connecting to a PLAINTEXT broker listener? (after 39ms in state SSL_HANDSHAKE

~Instead, we should expose an error via the source status table or at least issue a notice and fail to create the source~

*Nikhil edit:* We should just support `SECURITY PROTOCOL = SASL_PLAINTEXT`. We used to support this, pre-platform, but it got lost in the transition to connections.

**Comment by benesch** [comment]
I think we should just support the `SASL_PLAINTEXT` security protocol. Updated the issue description accordingly.

**Comment by benesch** [comment]
We have another request to support this from [WarpStream](https://www.warpstream.com)/ @richardartoul.
