### ISSUE TITLE
regression: The max_connections limit does not seem to work as advertised

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#19109]
### What version of Materialize are you using?

8341b91c43c14033d4b40be940b0b020beb02f9b

### What is the issue?

The test/limits test has started failing in a way that indicates that the max_connections limit kicks in a a value that is 1/2 of the desired one. This brings the entire method of calculating the number of concurrent connections in question, so I fear that even though the default is 1000, in production we may see legitimate clients kicked out much earlier than expected.

To reproduce:

1. In a mz_system connection, set 
```
ALTER SYSTEM SET max_connections=2;
```
2. Open a normal connection No 1
3. Open a normal connection No 2:

and do:

```
materialized=> select 1;
FATAL:  creating a connection would violate max connections limit (desired: 3, limit: 2, current: 1)
HINT:  Drop an existing a connection or contact sales to request a limit increase.
```

The error says `desired: 3`, which is incorrect.

A larger test that attempts to open 1000 concurrent connections dies after 500+/-1 have been opened

**Comment by andrewrodriguez-m** [comment]
Reverted then fixed in #19117
