### ISSUE TITLE
Update MSK guide to cover using PrivateLink or SSH tunnel

### ISSUE THREAD

**Issue by tr0njavolta** [MaterializeInc/materialize#19122]
From Bobby in docs slack channel:
[@Andy Hattemer](https://materializeinc.slack.com/team/U01K9B8LTNG)
 brought up that the MSK guide that we have is a bit outdated, we are focusing on how to make an MSK cluster public:
https://materialize.com/docs/integrations/amazon-msk/
This was necessary in the past before we had PrivateLink and SSH connections and making a cluster public was the only way we could connect.
This still might be a valuable information but we should probably explicitly mention that the users don’t have to do this unless they specifically want to make the cluster public, as instead they could use [SSH or PrivateLink](https://materialize.com/docs/ops/network-security/privatelink/) and keep their clusters private.

**Comment by jseldess** [comment]
[Related thread in community Slack](https://materializecommunity.slack.com/archives/C015KDVS7EV/p1684492911084769)

**Comment by morsapaes** [comment]
Good to see this in the pipeline! Logging a related [thread from our community Slack](https://materializecommunity.slack.com/archives/C015KDVS7EV/p1684492911084769).

**Comment by bobbyiliev** [comment]
Closed via #21504
