### ISSUE TITLE
explain: OneShot plan has temporal constraints

### ISSUE THREAD

**Issue by teskje** [MaterializeInc/materialize#19148]
### What version of Materialize are you using?

main

### What is the issue?

Minimal reproduction:

```sql
materialize=> create table t (a timestamp);
CREATE TABLE
materialize=> create default index on t;
CREATE INDEX
materialize=> explain select * from t where a < mz_now();
ERROR:  OneShot plan has temporal constraints
```

The query itself works as expected, so this is only an issue in our EXPLAIN code.

### Initial Diagnosis

The issue occurs in the explain sequencing code where we check whether the target query uses the fast path: https://github.com/MaterializeInc/materialize/blob/1edab459b447bbd7bdc114e434f3dd58497ded2f/src/adapter/src/coord/sequencer/inner.rs#L2687

`create_fast_path_plan` calls `permute_oneshot_mfp_around_index`:
https://github.com/MaterializeInc/materialize/blob/1edab459b447bbd7bdc114e434f3dd58497ded2f/src/adapter/src/coord/peek.rs#L218

... which in turn expects the passed MFP to not contain any non-temporal expressions:
https://github.com/MaterializeInc/materialize/blob/1edab459b447bbd7bdc114e434f3dd58497ded2f/src/adapter/src/coord/peek.rs#L164-L165

It seems like the explain sequencing code needs to do the work of replacing `mz_now()` expressions before calling `create_fast_path_plan`, as the peek sequencing code does.

**Comment by aalexandrov** [comment]
In `plan_peek` the `self.create_peek_plan` does this with the `visit_children` call that wraps `prep_relation_expr` / `prep_scalar_expr`:

https://github.com/MaterializeInc/materialize/blob/8c6866f54bad8c03a5522636638da28b60a54841/src/adapter/src/coord/sequencer/inner.rs#L2335-L2359
