### ISSUE TITLE
storage: idle postgres sources run postgres server out of disk space

### ISSUE THREAD

**Issue by benesch** [MaterializeInc/materialize#19142]
### What version of Materialize are you using?

v0.52

### What is the issue?

A PostgreSQL source connected to a publication that has no writes will eventually run the PostgreSQL server out of disk space (or hit the maximum replication slot WAL size).

Here's an example, courtesy of @bobbyiliev:

![image](https://user-images.githubusercontent.com/882976/236725772-b8fd7ed3-57c0-4572-863b-36bf323f463d.png)

This is a problem for Debezium too: https://debezium.io/documentation/reference/stable/connectors/postgresql.html#postgresql-wal-disk-space. Debezium has a (gross) workaround, which is to optionally periodically run a query that updates a dummy table in the publication, to keep the LSNs moving in the publication.

Maybe we can be more clever than Debezium; maybe we need to implement exactly the same workaround; at the very least we should document this risk and how to work around it (ensure one table is always experiencing some traffic).

Slack conversation: https://materializeinc.slack.com/archives/C01CFKM1QRF/p1683044622380809

@sploiselle — you mind figuring out how to prioritize this into the PostgreSQL improvements epic? 

cc @petrosagg as well, since I think he's thought about solutions to this problem in the past.

cc @morsapaes @RobinClowers who participated in discussions about this issue

**Comment by petrosagg** [comment]
Fixed by https://github.com/MaterializeInc/materialize/pull/19239
