### ISSUE TITLE
We create a surprising number of file descriptors

### ISSUE THREAD

**Issue by quodlibetor** [MaterializeInc/materialize#1919]
For a few reasons we generate sometimes over a thousand open fds, even with source and thread counts in the 10s. Sometimes this causes `materialized` to become unresponsive when we go over the ulimit. We increase the nofile ulimit in #1918 , but ideally the constant factor for number of open files per actual source would be less than it currently is.

**Comment by frankmcsherry** [comment]
Further discussion / back-of-enveloping with @benesch:

There seem to be roughly 10-20 FDs per instantiated source, 10 per rdkafka consumer (and up to two consumers: one for data, one for timestamp information). Importantly, this is per *instantiated* source, not per created source: across the 22 queries there could easily be 5x as many instantiated sources, leading to 1k+ file descriptors just from rdkafka use.

We could multiplex Kafka use across a smaller number of consumers. I'm not sure what the value of multiple consumers is (should there be one per worker?), but if there is a value we might want to reason out on what basis we should create new consumers.

**Comment by frankmcsherry** [comment]
One consumer limitation is that the "consumer group" is per-consumer, which (I think) means that it cannot read from the same topic multiple times. If a stream needs to be re-read (e.g. to catch up a second use of the stream) a second consumer (with a different consumer group) appears to be required. 

It seems reasonable to arrange for at most one consumer per dataflow, though. Multiplexing across dataflows seems more awkward. But within one dataflow, we build all Kafka sources at once, and can use a single timely operator to demux the received messages based on the topic (and then register each source with the corresponding output stream).

**Comment by benesch** [comment]
One thing to keep in mind: it's quite possible that someone will create two distinct sources that pull from the same underlying Kafka topic:

```sql
CREATE SOURCE src1 FROM KAFKA BROKER 'b' TOPIC 't'
CREATE SOURCE src2 FROM KAFKA BROKER 'b' TOPIC 't'
```

A query that uses both sources (`CREATE MATERIALIZED VIEW v AS SELECT * FROM src1 UNION ALL SELECT * FROM src2`) would require separate handling.

> Multiplexing across dataflows seems more awkward.

That's where the magic would happen, though! If you only share Kafka consumers intra-dataflow, then installing all 22 TPCH queries would still use ~500 FDs. I think we should consider a per-node Kafka consumer pool that lives outside Timely and handles the demuxing.

**Comment by benesch** [comment]
We've got consensus that we ought to consolidate Kafka consumers (#3791, #6450). Short of replacing librdkafka, I don't think there's any other way to solve this issue, so going to close this out.
