### ISSUE TITLE
docs: Monitoring guide using Grafana and Prometheus SQL Exporter

### ISSUE THREAD

**Issue by jseldess** [MaterializeInc/materialize#19230]
### Documentation request

We should build out a guide on monitoring for [product limits](https://github.com/MaterializeInc/materialize/issues/19229) and other important signals (like [OOM](https://github.com/MaterializeInc/materialize/issues/18621)) using [Grafana and the Prometheus SQL Exporter](https://github.com/MaterializeInc/demos/tree/main/integrations/prometheus-sql-exporter). Ideally, we would also use AlertManager to define alerting rules, to make monitoring more proactive. 

### Related work

https://github.com/MaterializeInc/materialize/issues/19229
https://github.com/MaterializeInc/materialize/issues/18621

CockroachDB monitoring docs, as an example:
- [Prometheus tutorial](https://www.cockroachlabs.com/docs/stable/monitor-cockroachdb-with-prometheus.html)
- [Common issues to Monitor (in CRDB Console)](https://www.cockroachlabs.com/docs/stable/common-issues-to-monitor.html)
- [Events to alert on](https://www.cockroachlabs.com/docs/stable/monitoring-and-alerting.html#events-to-alert-on)

**Comment by morsapaes** [comment]
Linking to #17381 and #18803. @joacoc has already done some work to include template monitoring dashboards in the existing demos.

**Comment by morsapaes** [comment]
Closed via #21161.
