### ISSUE TITLE
Expose error details through the http interface

### ISSUE THREAD

**Issue by RobinClowers** [MaterializeInc/materialize#19264]
### Feature request

I noticed that some sql errors returned over pgwire include `ERROR` and `DETAIL`, for example:

```
ERROR:  failed to connect to PostgreSQL database
DETAIL:  publication "mz_source" does not exist
```

When I get that same error over the http interface, it looks like this:
```
{"results":[{"error":"failed to connect to PostgreSQL database","notices":[]}]}
```

It would be very useful to have those details in the console.

**Comment by benesch** [comment]
cc @mjibson 

Should we change the structure of the `error` field to be a complex type? For example: `{"error": {"message": "failed to connect to PostgreSQL database", "detail": "publication 'mz_source' does not exist" }}`

**Comment by mjibson** [comment]
Yup.

**Comment by benesch** [comment]
Probably want to include the code and the hint too. Similarly for notices.
