### ISSUE TITLE
Musing: consider how to enforce fine-grained permissions for console features.

### ISSUE THREAD

**Issue by umanwizard** [MaterializeInc/materialize#19297]
### Feature request

With RBAC we have a way to grant fine-grained permissions to individual users for objects that are visible in SQL.

However, we have some other features that cannot be expressed in terms of permissions to query SQL objects. Typically now we model these as Frontegg permissions. For example, `materialize.environment.write` allows a user to spin up a new environment, and `materialize.invoice.read` allows a user to access billing data.

We may want to allow fine-grained controls over these Frontegg permissions; for example, customers may want to create a user that isn't a full admin (and therefore doesn't have `materialize.environment.write`) but still has access to billing data (and therefore has `materialize.invoice.read`). Today this is impossible as the only knob we have for assigning Frontegg permissions is whether the user is an admin or not.

**Comment by RobinClowers** [comment]
It seems unfortunate that we have RBAC in the database and frontegg separately. I've heard that we planned to do all RBAC in the database, but unless we are going to add SQL objects to represent billing and console features, it seems like we will end up using Frontegg for this, at least for the time being.

I think we can probably kick this can down the road for quite a while, but it's hard to say for sure. Frontegg allows us to create arbitrary roles, but it doesn't seem like they support custom roles per organization, so if any customer wanted a new role, it would be available for all customers.

**Comment by benesch** [comment]
> Today this is impossible as the only knob we have for assigning Frontegg permissions is whether the user is an admin or not.

I'm not sure I follow this. We can add a new "Organization Billing Admin" role that allows access to `materialize.invoice.read` but _not_ `materialize.environment.write`.

@RobinClowers is right that we can't allow users to create custom "Organization ..." roles alongside "Organization Admin" and "Organization Member", but I think that's fine. The set of roles that 99% of users will want is "full admin", "billing admin", "billing read-only" and "member", and we can easily just hardcode that set of roles.

> It seems unfortunate that we have RBAC in the database and frontegg separately. I've heard that we planned to do all RBAC in the database, but unless we are going to add SQL objects to represent billing and console features, it seems like we will end up using Frontegg for this, at least for the time being.

Yeah, a bit ugly, but this was the only way to marry Frontegg with SQL RBAC. Using Frontegg for "global" features (things that span across multiple regions) was always the plan, though!

**Comment by umanwizard** [comment]
OK, if there are no plans to ever merge them, we can close out this issue.
