### ISSUE TITLE
Monotonic one-shot `SELECT` feature fails to get activated in serializable mode with source that emits the empty frontier

### ISSUE THREAD

**Issue by vmarcos** [MaterializeInc/materialize#19290]
### What version of Materialize are you using?

v0.55.0-dev (196fa12a5)

### What is the issue?

We have recently introduced a feature to use monotonic operators in one-shot `SELECT`s, gated behind the feature flag `enable_monotonic_oneshot_selects` (part of epic #14442, PR #18546). When the feature flag is enabled, monotonic operator selection for one-shot `SELECT`s works as expected with `transaction_isolation` equal to `strict serializable`. However, the same is not true when `serializable` is chosen and we use a TPC-H load generator source without updates.

To reproduce this behavior, firstly enable the feature flag with `mz_system`:

```sql
sol:materialize vmarcos$ psql -U mz_system -h 127.0.0.1 -p 6877 materialize
psql (14.7 (Homebrew), server 9.5.0)
Type "help" for help.

materialize=> alter system set enable_monotonic_oneshot_selects = on;
ALTER SYSTEM
materialize=> show enable_monotonic_oneshot_selects;
 enable_monotonic_oneshot_selects 
----------------------------------
 on
(1 row)

```

Subsequently, log in normally, create a TPC-H source without updates, and wait for it to hydrate::

```sql
CREATE SOURCE lgtpch FROM LOAD GENERATOR TPCH (SCALE FACTOR 0.1) FOR ALL TABLES WITH (SIZE = '1');
SELECT count(*) > 0 FROM lineitem; -- repeat this statement until it returns true
```

Now, execute the following statements:
```sql
EXPLAIN PHYSICAL PLAN FOR SELECT DISTINCT ON(l_linenumber) l_linenumber, l_discount FROM lineitem ORDER BY l_linenumber, l_orderkey;
SET transaction_isolation = serializable;
EXPLAIN PHYSICAL PLAN FOR SELECT DISTINCT ON(l_linenumber) l_linenumber, l_discount FROM lineitem ORDER BY l_linenumber, l_orderkey;
```
We would expect the output for the two `EXPLAIN` statements above to be the same. However, the following output was observed instead:

```sql
materialize=> EXPLAIN PHYSICAL PLAN FOR SELECT DISTINCT ON(l_linenumber) l_linenumber, l_discount FROM lineitem ORDER BY l_linenumber, l_orderkey;
SET transaction_isolation = serializable;
EXPLAIN PHYSICAL PLAN FOR SELECT DISTINCT ON(l_linenumber) l_linenumber, l_discount FROM lineitem ORDER BY l_linenumber, l_orderkey;
                                    Physical Plan                                    
-------------------------------------------------------------------------------------
 Explained Query:                                                                   +
   Finish order_by=[#3 asc nulls_last, #0 asc nulls_last] output=[#3, #6]           +
     TopK::MonotonicTop1 group_by=[#3] order_by=[#0 asc nulls_last] must_consolidate+
       Get::PassArrangements materialize.public.lineitem                            +
         raw=true                                                                   +
 
(1 row)

SET
                              Physical Plan                               
--------------------------------------------------------------------------
 Explained Query:                                                        +
   Finish order_by=[#3 asc nulls_last, #0 asc nulls_last] output=[#3, #6]+
     TopK::Basic group_by=[#3] order_by=[#0 asc nulls_last] limit=1      +
       Get::PassArrangements materialize.public.lineitem                 +
         raw=true                                                        +
 
(1 row)
```

Above, we observe the use of `TopK::Basic` when `transaction_isolation` is `serializable`.

I could only reproduce this outcome with the TPC-H load generator source so far, so it may be connected to the source emitting the empty frontier when no updates are generated. Here is the output of `EXPLAIN TIMESTAMP` in `strict serializable` and `serializable` modes:

```sql
materialize=> EXPLAIN TIMESTAMP FOR SELECT DISTINCT ON(l_linenumber) l_linenumber, l_discount FROM lineitem ORDER BY l_linenumber, l_orderkey;
                                 Timestamp                                 
---------------------------------------------------------------------------
                 query timestamp: 18446744073709551615                    +
 largest not in advance of upper: 18446744073709551615                    +
                           upper:[]                                       +
                           since:[1684163317000 (2023-05-15 15:08:37.000)]+
         can respond immediately: true                                    +
                        timeline: Some(EpochMilliseconds)                 +
                                                                          +
 source materialize.public.lineitem (u2, storage):                        +
                   read frontier:[1684163317000 (2023-05-15 15:08:37.000)]+
                  write frontier:[]                                       +
 
(1 row)

materialize=> show transaction_isolation;
 transaction_isolation 
-----------------------
 serializable
(1 row)

materialize=> SET transaction_isolation = 'strict serializable';
SET
materialize=> EXPLAIN TIMESTAMP FOR SELECT DISTINCT ON(l_linenumber) l_linenumber, l_discount FROM lineitem ORDER BY l_linenumber, l_orderkey;
                                 Timestamp                                 
---------------------------------------------------------------------------
                 query timestamp: 1684163491134 (2023-05-15 15:11:31.134) +
           oracle read timestamp: 1684163491134 (2023-05-15 15:11:31.134) +
 largest not in advance of upper: 18446744073709551615                    +
                           upper:[]                                       +
                           since:[1684163317000 (2023-05-15 15:08:37.000)]+
         can respond immediately: true                                    +
                        timeline: Some(EpochMilliseconds)                 +
                                                                          +
 source materialize.public.lineitem (u2, storage):                        +
                   read frontier:[1684163317000 (2023-05-15 15:08:37.000)]+
                  write frontier:[]                                       +
 
(1 row)

```

The issue appears to be that `until` cannot be equal to `as_of + 1` when the `as_of` is chosen as the maximum possible value.

**Comment by teskje** [comment]
Sounds like we maybe want to follow @frankmcsherry's suggestion and make `until` an inclusive frontier? Then we would just set `until = as_of` for one-shot SELECTs and that edge-case is solved.

**Comment by vmarcos** [comment]
> Sounds like we maybe want to follow @frankmcsherry's [suggestion](https://github.com/MaterializeInc/materialize/blob/7f487c861b9a03f3938d031b966c51cb3c02880e/src/compute-client/src/types/dataflows.rs#L76) and make `until` an inclusive frontier? Then we would just set `until = as_of` for one-shot SELECTs and that edge-case is solved.

We use the current semantics of `until` when importing a trace: https://github.com/MaterializeInc/materialize/blob/def17f98217db24f6cffcf429484ff6ff048da7a/src/compute/src/render/mod.rs#L408-L419
Unfortunately, [`import_frontier_core` is in DD](https://github.com/TimelyDataflow/differential-dataflow/blob/14417e66d7365fa3869246d5495a795de9abeee1/src/operators/arrange/agent.rs#L443). There are some spots where DD's code checks for something like `!until.less_equal(&time)`. So changing the semantics implies AFAICT trying to change all of these uses in both DD and Materialize consistently.

As such, I am concerned that this change, while making the code more elegant, is of much higher complexity than maintaining the current semantics. I am therefore inclined to not change the semantics of `until` at this point in time. My suggestion is that we potentially revisit and refactor in the future, but apply a semantics-preserving fix in the meantime so that we can get a resolution to this issue.

**Comment by teskje** [comment]
That reasoning sounds good to me. Changing the semantics of `until` doesn't give us any substantial benefit, so punting on it seems fine.
