### ISSUE TITLE
rbac: ERROR: Expected identifier, found operator "<": ERROR: Expected identifier, found operator "<"

### ISSUE THREAD

**Issue by def-** [MaterializeInc/materialize#19332]
### What version of Materialize are you using?

c8da0567b059c63fd55e102b72f52b996fc587c9

### What is the issue?

While trying to enable RBAC for CI by default I'm getting this error:
```
Connecting to PostgreSQL server at postgres://mz_system:materialize@materialized:6877...
> DROP DATABASE materialize
> DROP ROLE materialize
^^^ +++
error: db error: ERROR: Expected identifier, found operator "<": ERROR: Expected identifier, found operator "<"
```
Repro on the code state (https://github.com/MaterializeInc/materialize/pull/19331): 
```
bin/mzcompose --find limits down && bin/mzcompose --find limits run default --scenario=SelectExpression
```

**Comment by jkosh44** [comment]
It looks like there's some bug in the testdrive reset logic. I dumped all the queries ran and got the following:
```
SELECT current_user
ALTER SYSTEM RESET ALL
SHOW DATABASES
SELECT * FROM (SELECT name FROM mz_catalog.mz_databases) q WHERE true ORDER BY q.*
SELECT * FROM (SELECT name FROM mz_catalog.mz_databases) q WHERE true ORDER BY q.*
DROP DATABASE materialize
CREATE DATABASE materialize
SELECT name FROM mz_roles
DROP ROLE materialize
GRANT USAGE ON DATABASE materialize TO PUBLIC
GRANT CREATE ON DATABASE materialize TO <unknown user>
```

The error is clearly coming from `GRANT CREATE ON DATABASE materialize TO <unknown user>` which comes from here: https://github.com/MaterializeInc/materialize/blob/13f9223e27384caf07d21ef29fd8363854f97cfa/src/testdrive/src/action.rs#L346-L351

So `self.materialize_user` is being set to `<unknown user>`.

That value likely comes from here: https://github.com/MaterializeInc/materialize/blob/13f9223e27384caf07d21ef29fd8363854f97cfa/src/testdrive/src/action.rs#L692-L697

**Comment by jkosh44** [comment]
The reason that `SELECT current_user` fails is due to a permission error: `permission denied for CLUSTER default`.

We have a bit of a catch-22 here. In order to reset the state of materialize we need to get the current user. However, to get the current user we need to reset the state of Materialize so that we have permissions on the current cluster.

Ideally, we wouldn't need cluster permissions to execute `SELECT current_user`.

**Comment by jkosh44** [comment]
@def- I made a PR against your branch: https://github.com/def-/materialize/pull/1
