### ISSUE TITLE
docs: Additional guidance for PrivateLink / SSH Bastion Terraform modules

### ISSUE THREAD

**Issue by chuck-alt-delete** [MaterializeInc/materialize#19336]
### Documentation request

We have awesome terraform modules, but they only manage AWS resources. There is still a manual step to interact with Materialize. We have documentation about how to use the Materialize Terraform Provider in conjunction with the some of the modules for a fully automated solution here:
- https://github.com/MaterializeInc/demos/tree/main/integrations/terraform

I think this sort of guidance should be in the docs as well

**Comment by jseldess** [comment]
Definitely want to factor terraform into the docs. I'm unclear if we should invest in this now or wait for the privatelink/ssh tunnel improvements on the Storage team's Q2 plan. @dseisun-materialize's, do you have thoughts?
