### ISSUE TITLE
Materialize and underlying MySQL instance returning different results (CHBench)

### ISSUE THREAD

**Issue by nacrooks** [MaterializeInc/materialize#1933]
<img width="949" alt="Screen Shot 2020-02-10 at 5 04 39 PM" src="https://user-images.githubusercontent.com/2697885/74194620-9bd3b580-4c27-11ea-868b-67bb29d343d5.png">

1) Materialize returns different results than the underlying SQL database. 
2008 is NULL in Materialize, 0 in MySQL
2017 is NULL in MySQL, 0.26790640 in Materialize

2) 2016 appears out of order in the ORDERBY query.

**Comment by cuongdo** [comment]
@nacrooks if there are no currently known discrepancies, can this now be closed?
