### ISSUE TITLE
billing-demo: make it more like a prod-ready microservice

### ISSUE THREAD

**Issue by ruchirK** [MaterializeInc/materialize#1937]
1. Lets make it actually publish results back to Kafka / a file OR write something that can automatically query Materialize and send out the bills. Right now its not really a "service"
2. the memory usage is really high (30x input volume) + grows indefinitely
3. Maybe we can think about publishing some performance numbers?

see also https://github.com/MaterializeInc/materialize/pull/1861#issuecomment-582565566

**Comment by ruchirK** [comment]
addressed #2 by adding a new low memory mode via https://github.com/MaterializeInc/materialize/pull/2165

**Comment by ruchirK** [comment]
Billing demo now writes output to a kafka sink

**Comment by rjnn** [comment]
I'm going to advocate for this issue to be closed. Memory usage/perf work in general is tracked elsewhere. I think the demo serves its purpose. Other benchmarks (like chBenchmark) also grow indefinitely, and that is by design.
