### ISSUE TITLE
docs: How to ingest data from Kafka MSK

### ISSUE THREAD

**Issue by jseldess** [MaterializeInc/materialize#19374]
### Documentation request

We need to refresh our Kafka MSK page to provide end-to-end and correct guidance. Related to [similar work for Postgres](https://github.com/MaterializeInc/materialize/issues/19038).

Issues to handle as part of this work:
- https://github.com/MaterializeInc/materialize/issues/19122
- https://github.com/MaterializeInc/materialize/issues/17343
- https://github.com/MaterializeInc/materialize/issues/17213

**Comment by bobbyiliev** [comment]
Closed via #21504
