### ISSUE TITLE
rbac: ERROR: no schema has been selected to create in

### ISSUE THREAD

**Issue by def-** [MaterializeInc/materialize#19388]
### What version of Materialize are you using?

a5fa9e6ed2dbc35277d85853862232881c1bfe9a

### What is the issue?

When trying to enable rbac for all our CI tests in https://github.com/MaterializeInc/materialize/pull/19331 I am noticing a failure in catalog.td:
```
> CREATE TYPE type1 AS LIST (ELEMENT TYPE = text)

^^^ +++
catalog.td:654:1: error: executing query failed: db error: ERROR: no schema has been selected to create in: ERROR: no schema has been selected to create in
     |
 653 |
 654 | > CREATE TYPE type1 AS LIST (ELEMENT TYPE = text)
     | ^
```
Adding a `> SET SCHEMA public` before that doesn't help. Is this expected?

**Comment by def-** [comment]
It appears that the public schema somehow disappeared. Maybe I'm misreading the test but I don't see how.

**Comment by jkosh44** [comment]
yes, that error means that no schemas on the `search_path` exist. The `search_path` at the time of `CREATE TYPE` is `public`. You added a line earlier in the file (line 389) to drop the `public` schema which is why this is now failing.
