### ISSUE TITLE
MFP Pushdown: EXPLAIN WITH (mfp_pushodown) indicates pushdown even when feature is disabled

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#19401]
### What version of Materialize are you using?

v0.56.0-dev (e03849c)

### What is the issue?

`EXPLAIN WITH (mfp_pushdown)` indicates that pushdown will take place even if the feature itself is disabled via a feature flag.

This causes issues when testing and will cause issues with support further down the line.

If `WITH (mfp_pushdown)` is specified but `persist_stats_filter_enabled` is false, the `EXPLAIN` should not show any pushdown taking place.

**Comment by bkirwi** [comment]
We went back and forth over this one... I found it useful to help analyze queries even when the optimization was not in force, but I understand how it would be confusing.

Can you say more about the issues it's been causing with testing?

**Comment by bkirwi** [comment]
Resolved by #19508!
