### ISSUE TITLE
MFP Pushdown: Performance degradation with many rows/blobs

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#19400]
### What version of Materialize are you using?

v0.56.0-dev (e03849c)

### What is the issue?

In contrast with #19399 , where the performance suffered with many conditions over multiple columns, the performance of MFP pushdown is also suboptimal in the case of very reasonable queries when executed against a table with many rows (which I assume is equivalent to running a source with many blobs). The queries take multiple seconds to execute.

Consider this script:

```
COUNT = 10
print("\\timing on")
print("DROP TABLE IF EXISTS t1;")

column_list = ", ".join(f"f{i} INTEGER" for i in range(COUNT))
print(f"CREATE TABLE t1 ({column_list});")

print("BEGIN");
for row in range(1000):
   value_list = ", ".join(f"{row}" for i in range(COUNT))
   print(f"INSERT INTO t1 VALUES ({value_list});")
print("COMMIT");

where_list = []

for i in range(COUNT):
     where_list.append(f"f0 = {i}")
     where_condition = " OR ".join(where_list)
     print(f"SELECT f1 FROM t1 WHERE {where_condition};")
```

It creates a table with 10 columns and 1000 rows. It then generates queries such as this one:

```
SELECT f1 FROM t1 WHERE f0 = 0 OR f0 = 1 OR f0 = 2 OR f0 = 3 OR f0 = 4 OR f0 = 5 OR f0 = 6 OR f0 = 7 OR f0 = 8 OR f0 = 9;
 f1 
----
  1
  2
  3
  4
  5
  6
  7
  8
  9
(9 rows)

Time: 3961.629 ms (00:03.962)
```

This query is equivalent to a 10-item `IN` list against a single column, so nothing to write home about, and yet and takes 4 seconds to execute with MFP pushdown

**Comment by bkirwi** [comment]
Resolved by #19448!
