### ISSUE TITLE
doc: Real-time analytics demo/tutorial in Instruqt

### ISSUE THREAD

**Issue by jseldess** [MaterializeInc/materialize#19409]
### Documentation request

Based on https://github.com/MaterializeInc/materialize/blob/main/doc/user/content/quickstarts/streaming-analytics.md.

The exact scope and experience is TBD, but here are some basic intentions:
- Configure Instruqt to start with everything already running
- Focus user on the cool things that Materialize is doing
- Guide users to add additional features 

cc: @morsapaes, @hlburak, @ruf-io

**Comment by ggnall** [comment]
Cancelled due to changes in project ownership and direction needed for demos.
