### ISSUE TITLE
doc: Automation & alerting demo/tutorial in Instruqt

### ISSUE THREAD

**Issue by jseldess** [MaterializeInc/materialize#19410]
### Documentation request

Based on: https://github.com/MaterializeInc/materialize/blob/main/doc/user/content/quickstarts/user-workflows.md.

The exact scope and experience is TBD, but here are some basic intentions:
- Configure Instruqt to start with everything already running
- Focus user on the cool things that Materialize is doing
- Guide users to add additional features 

cc: @morsapaes, @hlburak, @ruf-io

**Comment by morsapaes** [comment]
We've decided to table Instruqt for the time being, so closing this issue.
