### ISSUE TITLE
[SQLancer] ERROR: table "having3.public.t5" already exists

### ISSUE THREAD

**Issue by def-** [MaterializeInc/materialize#19431]
### What version of Materialize are you using?

356343079fa255a7ae06b044c693d6fd4bf404c8

### What is the issue?

SQLancer started having failures complaining about table existing already, even with `bin/environmentd --reset`. The reproduction is easy with:
```bash
cd ~/git/sqlancer
mvn package -DskipTests
cd ~/git/sqlancer/target
java -jar sqlancer-*.jar --num-tries 1000 --num-threads 8 --host localhost --username materialize --qpg-enable true --port 6875 --database-prefix having materialize --oracle HAVING --set-max-tables-mvs true
```
Strangely I can't reproduce this with mzcompose though, maybe it is setting some different flags for Materialized?
```bash
bin/mzcompose --find sqlancer down
bin/mzcompose --find sqlancer run default --runtime=600 --oracle=HAVING --qpg
```
This runs 8 sqlancer threads at once, on 8 different databases (having0-having7). The table names are kept track of in SQLancer and they are only ever created, not dropped. Nevertheless there are now failures about the table already existing. The logs show that a table in another database with the same name was created, which is probably where the problem comes from?
```
environmentd: 2023-05-22T21:57:20.005002Z  INFO mz_adapter::catalog: create table having0.public.t5 (u39)
environmentd: 2023-05-22T21:57:20.721069Z  INFO mz_adapter::catalog: create table having3.public.t5 (u40)
```

A bisect revealed this change CC @parker-timmerman :
```
b0f14e70f38a77d9e62478b2c4a8f837a4f70c73 is the first bad commit
commit b0f14e70f38a77d9e62478b2c4a8f837a4f70c73
Author: Parker Timmerman <126496446+parker-timmerman@users.noreply.github.com>
Date:   Mon Apr 17 10:47:10 2023 -0500

    adapter: Remove the `enable_auto_route_introspection_queries` LD Flag (#18798)

    ### Motivation

    Fixes #18457

    This PR removes the `ENABLE_AUTO_ROUTE_INTROSPECTION_QUERIES`
    LaunchDarkly flag that was introduced to gate #18310. The original
    feature shipped with `v0.49` and this PR should be included in `v0.52`,
    so the feature will have had 3 weeks of bake time.

    In addition to removing the LD flag, we also remove the note from our
    docs that indicates users should set their cluster to
    `mz_introspection`. With this feature the documented queries get
    automatically run on this cluster.

    ### Checklist

    - [ ] This PR has adequate test coverage / QA involvement has been duly
    considered.
    - [ ] This PR has an associated up-to-date [design
    doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md),
    is a design doc
    ([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)),
    or is sufficiently small to not require a design.
      <!-- Reference the design in the description. -->
    - [ ] This PR evolves [an existing `$T ⇔ Proto$T`
    mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md)
    (possibly in a backwards-incompatible way) and therefore is tagged with
    a `T-proto` label.
    - [ ] If this PR will require changes to cloud orchestration, there is a
    companion cloud PR to account for those changes that is tagged with the
    release-blocker label
    ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
    <!-- Ask in #team-cloud on Slack if you need help preparing the cloud
    PR. -->
    - [x] This PR includes the following [user-facing behavior
    changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):
    - Queries that only depend on system tables, e.g. the `SHOW ...`
    commands, will automatically get run on the `mz_introspection` cluster,
    which contain in-memory indexes on these tables to speed up the
    execution.

 doc/user/content/sql/show-cluster-replicas.md      |  2 --
 doc/user/content/sql/show-clusters.md              |  2 --
 doc/user/content/sql/show-columns.md               |  2 --
 doc/user/content/sql/show-connections.md           |  2 --
 doc/user/content/sql/show-databases.md             |  2 --
 doc/user/content/sql/show-indexes.md               |  2 --
 doc/user/content/sql/show-materialized-views.md    |  2 --
 doc/user/content/sql/show-objects.md               |  2 --
 doc/user/content/sql/show-schemas.md               |  2 --
 doc/user/content/sql/show-secrets.md               |  2 --
 doc/user/content/sql/show-sinks.md                 |  2 --
 doc/user/content/sql/show-sources.md               |  2 --
 doc/user/content/sql/show-tables.md                |  2 --
 doc/user/content/sql/show-types.md                 |  2 --
 doc/user/content/sql/show-views.md                 |  2 --
 doc/user/layouts/shortcodes/show-command-note.html |  4 ----
 src/adapter/src/config/params.rs                   |  3 +--
 src/adapter/src/coord/introspection.rs             | 11 ++---------
 src/environmentd/tests/testdata/http/post          |  2 +-
 src/sql/src/session/vars.rs                        | 23 ----------------------
 20 files changed, 4 insertions(+), 69 deletions(-)
 delete mode 100644 doc/user/layouts/shortcodes/show-command-note.html
```

Tell me if you need any help with reproducing this.

**Comment by def-** [comment]
@pH14 Since you worked on PubSub, do you think there is a connection?

**Comment by pH14** [comment]
I'm not very familiar with the adapter code here, but from what I do know, persist pubsub seems unrelated and I'd be surprised if it's directly affecting the behavior. That said, if it's race condition style bug, I could believe that turning pubsub on/off could alter the timings of unrelated code to make certain outcomes more or less likely.

**Comment by ParkMyCar** [comment]
Looked into this further and chatted with @jkosh44, I think the issue has to do with SQLsmith running in serializable mode, and the indexes on `mz_introspection` containing "stale" data.

I believe what's happening is on thread will create table `t5` and the operation will complete, but before the index on the `mz_introspection` cluster can get updated, a second thread queries to see what tables exist, does not yet see `t5` since the index isn't updated, and then tries to create `t5` itself.

I'm guessing we don't see the issue when running with PubSub enabled because the latency to detect the created table is reduced enough to where the `mz_introspection` cluster has enough time to update it's indexes. If we disable the creation (i.e. comment out) [these indexes](https://github.com/MaterializeInc/materialize/blob/366088e019b3d0550b8235af7e496251a4fdff94/src/adapter/src/catalog/builtin.rs#L3828-L3833) I also don't observe the issue.

To fix the tests there are a few things we could do:
1. `SET auto_route_introspection_queries = false`, this will prevent us from auto routing to the introspection cluster and thus using the indexes.
2. Running SQLsmith in Strict Serializable.
3. (Maybe?) Enable PubSub for SQLsmith. Something else might cause latency to increase in the future though, to which we'll be back in this situation.

**Comment by def-** [comment]
I explicitly went away from Strict Serializable in SQLancer, would be quite unfortunate for our testing performance.

> I believe what's happening is on thread will create table t5 and the operation will complete, but before the index on the mz_introspection cluster can get updated, a second thread queries to see what tables exist, does not yet see t5 since the index isn't updated, and then tries to create t5 itself.

There is only ever one thread running on one database. This seems correct though, SQLancer creates the table, then checks the current tables in a new connection, then sees it doesn't exist and creates another one with the same name.

So at least it is not as scary as it initially looked. I'm not sure what the best solution is. I guess I can do `SET auto_route_introspection_queries = false` for now in SQLancer.

**Comment by ParkMyCar** [comment]
Fixed by https://github.com/sqlancer/sqlancer/pull/792
