### ISSUE TITLE
Connection refused in Canary Deploy in Staging Cloud

### ISSUE THREAD

**Issue by def-** [MaterializeInc/materialize#19434]
### What version of Materialize are you using?

8b04c01

### What is the issue?

There is also a failure in cloud-canary, which could be related to https://github.com/MaterializeInc/materialize/pull/19120 CC @sploiselle .  

This started failing in nightly during https://github.com/MaterializeInc/materialize/compare/004de7e...3749d80. There was also a version bump which seems suspicious too CC @umanwizard : 3749d802545715644901cab7293e05765801eb4f

Nightly run: https://buildkite.com/materialize/nightlies/builds/2446#018845cf-6cf2-4666-9bd6-3bb9bd8b2f70

I tried running it locally with `bin/mzcompose --find cloud-canary down && bin/mzcompose --find cloud-canary run default` but apparently you need some secret env variables:
```
KeyError: 'NIGHTLY_CANARY_APP_PASSWORD'
```

The test fails with:
```
--- canary-load-generator.td
^^^ +++
canary-clusters.td:10:1: error: connecting to postgres: error connecting to server: Connection refused (os error 111): Connection refused (os error 111)
     |
   9 | 
  10 | $ postgres-execute connection=postgres://mz_system:materialize@${testdrive.materialize-internal-sql-addr}
     | ^
```
Also sometimes fails with:
```
[2023-05-23T08:59:34Z] mzcompose: test case workflow-default failed: never got correct result for dbname=materialize host=4ubmcadydimtorlqtp9f5pgcq.us-east-1.aws.staging.materialize.cloud port=6875 user=infra+nightly-canary@materialize.com password='m...': Can't create a connection to host 4ubmcadydimtorlqtp9f5pgcq.us-east-1.aws.staging.materialize.cloud and port 6875 (timeout is 1 and source_address is None).
```
Would any of the feature flags block mz_system connections? I'm wondering if this could also have something to do with the recent region lockdown CC @matthewarthur @guswynn

**Comment by def-** [comment]
It is not related to the recent region lockdown, since a rerun on older main state works fine: https://buildkite.com/materialize/nightlies/builds/2454

I have used nightly runs to bisect it (since I can't repro locally) and this comes from the unsafe mode removal as well (https://github.com/MaterializeInc/materialize/pull/19120): https://buildkite.com/materialize/nightlies/builds/2455

**Comment by philip-stoev** [comment]
yes the .td file attempts to use the admin port to issue SQL to Mz, but that port is not available from outside of the cloud.

**Comment by def-** [comment]
Indeed, that's it: https://github.com/MaterializeInc/materialize/pull/19120/files#diff-ca7b487b1ad8ed75ddf904944bf51e31370bab171ada0fccf7c4edf0c88de9deR10

**Comment by def-** [comment]
Even when I remove that call I'm still seeing failures currently:

```
[2023-05-24T09:57:50Z] mzcompose: test case workflow-default failed: never got correct result for dbname=materialize host=ebwphyblf4ts9qhw20yocqak.us-east-1.aws.staging.materialize.cloud port=6875 user=infra+nightly-canary@materialize.com password='m...': Can't create a connection to host ebwphyblf4ts9qhw20yocqak.us-east-1.aws.staging.materialize.cloud and port 6875 (timeout is 1 and source_address is None).
```

So something is still strange.

**Comment by sploiselle** [comment]
Testing a fix [here](https://buildkite.com/materialize/nightlies/builds/2476)
