### ISSUE TITLE
storage: PostgreSQL subsources can subvert `max_sources` limit

### ISSUE THREAD

**Issue by benesch** [MaterializeInc/materialize#19454]
The `max_sources` limit, along with `max_tables` and `max_materialized_views`, is meant to limit the maximum number of persist shards that an environment can create. These controls aren't meant to be _perfect_, but rather good enough protection against a malicious actor attempting a DoS attack against our production CockroachDB instance.

We realized today ([Slack link](https://materializeinc.slack.com/archives/CU7ELJ6E9/p1684849824531749?thread_ts=1684792917.526109&cid=CU7ELJ6E9)) that PostgreSQL subsources subvert this control. You can create a PostgreSQL source with hundreds of subsources, each backed by a persist shard, and those won't count against the limit. 

There are three known paths forward:

  1. Introduce a new `max_postgres_tables_per_source` limit.
  2. Introduce a `max_collections` limit.
  3. Make PostgreSQL subsources count towards the `max_sources` limit.

@petrosagg doesn't like (1) because it's hard to choose the right value for the limit. You need to set it low enough that `max_sources * max_postgres_tables_per_source` isn't stressful for CockroachDB, but setting that low enough fights against legitimate uses of Materialize (one PostgreSQL source with lots of subsources, or lots of Kafak topics).

I don't love (2) because it's a) hard to explain to users and b) makes it difficult to evolve Materialize in ways that increase the number of collections each {source, table, materialized view} uses. What's a "collection"? How many "collections" does a {source, table, materialized view} create? How would we roll out something like the `_progress` collections, where suddenly each source had an additional collection associated with it? We'd have to answer these questions if we introduced these limits. 

Of the above, I think I like (3) the best. It's easy to explain to users and solves the problem. Is there a problem I'm not seeing? I believe the reason they _don't_ count towards the limit is because the exclusion predates cluster unification, and back in those days `max_sources` was primarily about limiting the number of `storaged` pods that were created (which subsources did not create), rather than the number of persist shards that are created.

cc @sploiselle @petrosagg

**Comment by jkosh44** [comment]
For reference this is the original issue that excluded subsources: https://github.com/MaterializeInc/materialize/issues/15514
and this is the PR that resolved that issue: https://github.com/MaterializeInc/materialize/commit/f650ffb5

**Comment by sploiselle** [comment]
Closed by #19460
