### ISSUE TITLE
pg-cdc: data partially ingested after a source disruption

### ISSUE THREAD

**Issue by antiguru** [MaterializeInc/materialize#19485]
### Buildkite link

https://buildkite.com/materialize/tests/builds/56248#0188505c-55bd-49f9-a011-9fc081b44d7d

### Relevant log output

```source
[2023-05-25T01:10:45Z] verify-data.td:10:1: error: non-matching rows: expected:
[2023-05-25T01:10:45Z] [["500000"]]
[2023-05-25T01:10:45Z] got:
[2023-05-25T01:10:45Z] [["739311"]]
[2023-05-25T01:10:45Z] Poor diff:
[2023-05-25T01:10:45Z] - 500000
[2023-05-25T01:10:45Z] + 739311
[2023-05-25T01:10:45Z]
[2023-05-25T01:10:45Z]      |
[2023-05-25T01:10:45Z]    9 |
[2023-05-25T01:10:45Z]   10 | > SELECT COUNT(*) FROM t1;
[2023-05-25T01:10:45Z]      | ^
```

ci-regexp: verify-data.td:10:1: error: non-matching rows

**Comment by def-** [comment]
Seen the same: https://buildkite.com/materialize/tests/builds/56250#018851d4-5fd7-4493-a575-f4d55913d922
I'll check I can repro it locally.

**Comment by philip-stoev** [comment]
@petrosagg recently pushed https://github.com/MaterializeInc/materialize/pull/19239 , so it is most likely a genuine regression. I will tag it accordingly.

**Comment by philip-stoev** [comment]
The range @def- has indicated includes:

```
commit 5d45392590eb1cf345e6e4814bead0224982e8bc
Merge: 366088e019 d6fe7cf092
Author: Petros Angelatos <petrosagg@gmail.com>
Date:   Tue May 23 12:24:43 2023 -0400

    Merge pull request #19239 from petrosagg/multi-worker-pg
    
    storage: multi-worker postgres source refactor
```

**Comment by def-** [comment]
I just checked the same, seems very likely that this is the cause based on when it started appearing on main. Depends on the timing/race it seems, so not easy to reproduce locally.

**Comment by sploiselle** [comment]
Just hit this and got `749912` records, so another point for a race condition.

**Comment by sploiselle** [comment]
This also repros for me reliably with `--dev` builds, which further indicates raciness.

**Comment by def-** [comment]
I couldn't get it to fail totally reliably locally, but had the failure 2 times with main and didn't happen yet with 5d45392590eb1cf345e6e4814bead0224982e8bc reverted.

**Comment by philip-stoev** [comment]
@petrosagg is already on it. To summarize:
- the test already uses 300 second timeout, so the timeout should not be increased further, as 300 seconds for 1.5M replication events is already quite slow of a performance
- the other problem is that the fact that some number of records that is not 500K or 1M is seen, meaning that either the snapshot or the ingestion of the stream did not observe Pg transactional boundaries and the SELECT observed some intermediate state that should not have been possible.

**Comment by guswynn** [comment]
reverted in #19526, but leaving the issue open until we solve this holistically

**Comment by sploiselle** [comment]
This has been reverted again, so am removing the release blocker label.
