### ISSUE TITLE
[SQLsmith] Slow running query using huge amounts of memory with many conditions; with persist_stats_collection_enabled & persist_stats_filter_enabled

### ISSUE THREAD

**Issue by def-** [MaterializeInc/materialize#19496]
### What version of Materialize are you using?

ed7a58fe351818b2a81c73c1130f1479a7c46944

### What is the issue?

```
f5a69461da10ecb0d7ad76e324ee48ec1fc6ce09 is the first bad commit
commit f5a69461da10ecb0d7ad76e324ee48ec1fc6ce09
Merge: ab98bbd2f7 de7b5451b9
Author: Philip Stoev <pstoev@materialize.io>
Date:   Thu May 18 16:09:34 2023 +0300

    Merge pull request #19324 from philip-stoev/feature-flags-enable

    ci: Enable various feature flags in CI

 misc/python/materialize/mzcompose/services.py | 6 ++++++
 1 file changed, 6 insertions(+)
```
Seen OoMs in SQLsmith-explain in nightly sporadically, memory usage of clusterd keeps growing. I checked which setting it was and it's
`persist_stats_collection_enabled=true;persist_stats_filter_enabled=true`. @bkirwi @danhhz 

My reproducer is `bin/mzcompose --find sqlsmith down && bin/mzcompose --find sqlsmith run default --max-joins=15 --explain-only --runtime=6000` and watch the clusterd memory usage, it starts growing after a few minutes and never stops. Without `persist_stats_collection_enabled=true;persist_stats_filter_enabled=true` there is no increased memory usage (tested by commenting it out in `misc/python/materialize/mzcompose/services.py`).

What is special about this workload is that we are running different queries non-stop, and only doing an `EXPLAIN` on them, never actually executing them. So we have a lot of throughput and can notice memory leaks faster.

Is this an expected part of the stats collection? Should there be a limit of the stats size? Is it expected to live in the clusterd process?

**Comment by def-** [comment]
Actually, let me verify again if it's persist_stats_filter_enabled or persist_stats_collection_enabled that causes this, I had them enabled together before.

**Comment by danhhz** [comment]
@bkirwi any chance this is also an artifact of https://github.com/MaterializeInc/materialize/pull/19448?

**Comment by bkirwi** [comment]
Anything's possible! I don't see how - if sqlsmith is running explain, weirdo queries shouldn't even hit clusterd -- but I don't really have any other theories for this one either yet.

**Comment by danhhz** [comment]
> Is this an expected part of the stats collection? Should there be a limit of the stats size? Is it expected to live in the clusterd process?

to answer this explicitly, this is not expected and we do limit the stats size (but there very well may be a bug, of course)

**Comment by def-** [comment]
This is actually weirder than expected. This query fails to ever return and keeps running in clusterd, thus we never start running the actual queries:

```
SELECT
  mz_schemas.name AS nspname,
  mz_functions.oid,
  ret_type.oid AS prorettype,
  mz_functions.name AS proname
FROM mz_catalog.mz_functions
JOIN mz_catalog.mz_schemas
ON mz_functions.schema_id = mz_schemas.id
JOIN mz_catalog.mz_types AS ret_type
ON mz_functions.return_type_id = ret_type.id
WHERE mz_functions.name <> 'pg_event_trigger_table_rewrite_reason'
AND mz_functions.name <> 'pg_event_trigger_table_rewrite_oid'
AND mz_functions.name !~ '^ri_fkey_'
AND mz_functions.name <> 'mz_panic'
AND mz_functions.name <> 'mz_logical_timestamp'
AND mz_functions.name <> 'mz_sleep'
AND mz_functions.name <> 'date_bin'
AND mz_functions.name <> 'list_length_max'
AND mz_functions.name <> 'list_n_layers'
AND mz_functions.name <> 'list_remove'
AND mz_functions.name <> 'concat_agg'
AND mz_functions.name <> 'array_in'
AND mz_functions.name <> 'generate_series'
AND mz_functions.name <> 'jsonb_array_elements'
AND mz_functions.name <> 'jsonb_array_elements_text'
AND mz_functions.name <> 'jsonb_each'
AND mz_functions.name <> 'jsonb_each_text'
AND mz_functions.name <> 'jsonb_object_keys'
AND mz_functions.name <> 'mz_row_size'
AND mz_functions.name <> 'jsonb_build_object'
AND mz_functions.name <> 'mz_error_if_null'
AND mz_functions.name <> 'mz_now'
AND NOT (returns_set or mz_functions.name in ('array_agg', 'avg', 'bit_and', 'bit_or', 'bit_xor', 'bool_and', 'bool_or', 'count', 'every', 'json_agg', 'jsonb_agg', 'json_object_agg', 'jsonb_object_agg', 'list_agg', 'max', 'min', 'range_agg', 'range_intersect_agg', 'string_agg', 'sum', 'xmlagg', 'corr', 'covar_pop', 'covar_samp', 'regr_avgx', 'regr_avgy', 'regr_count', 'regr_intercept', 'regr_r2', 'regr_slope', 'regr_sxx', 'regr_sxy', 'stddev', 'stddev_pop', 'stddev_samp', 'variance', 'var_pop', 'var_samp', 'mode', 'percentile_cont', 'percentile_disc', 'rank', 'dense_rank', 'percent_rank', 'grouping', 'mz_all', 'mz_any') or mz_functions.name in ('row_number', 'rank', 'dense_rank', 'percent_rank', 'cume_dist', 'ntile', 'lag', 'lead', 'first_value', 'last_value', 'nth_value'));
```
Verified with `MZ_SOFT_ASSERTIONS=1 MZ_SYSTEM_PARAMETER_DEFAULT="persist_stats_filter_enabled=true;persist_stats_collection_enabled=true" bin/environmentd --reset --release -- --orchestrator-process-propagate-crashes`

So this is probably a performance problem where this query has become extremely slow because of the large number of conditions.

**Comment by danhhz** [comment]
ah, yeah, that query looks a lot like what got fixed in https://github.com/MaterializeInc/materialize/pull/19448!

**Comment by def-** [comment]
Confirmed, it's fixed! Thanks

**Comment by bkirwi** [comment]
That implies that sqlancer is not running only explains, though, right? (If we're spinning up a dataflow in the cluster?) If so that might be a bug in the test!

**Comment by def-** [comment]
SQLsmith works in this way, it first loads all data from the DBMS, existing tables, procedures, operators, etc, then starts its normal workload. I didn't notice initially that this failed already during the initial phase, and opened a follow-up PR so I could have caught that immediately: https://github.com/MaterializeInc/materialize/pull/19497
