### ISSUE TITLE
Build "Create Source Generator"

### ISSUE THREAD

**Issue by sploiselle** [MaterializeInc/materialize#1951]
The `CREATE SOURCE` docs are too beastly; we can make a little browser tool that lets users tell us what they want to do and we can give them the appropriate `CREATE SOURCE` statement.

**Comment by morsapaes** [comment]
@bobbyiliev worked on a [prototype](https://materializeinc.slack.com/archives/CNVRXGFDJ/p1663838090894639) for this! I'll close the issue since it'll land in the UI rather than the documentation.
