### ISSUE TITLE
[Epic] Managed clusters

### ISSUE THREAD

**Issue by benesch** [MaterializeInc/materialize#19547]
## Product outcome

Make it possible to manage clusters without thinking about individual replicas.

## Discovery

* We have a design doc with a detailed proposal in [#19544](https://github.com/MaterializeInc/materialize/pull/19554).
* There is an additional design document for managed cluster reconfiguration in [#20437](https://github.com/MaterializeInc/materialize/pull/20437) (considered out-of-scope).

### Non-goals

* Zero-downtime resizing, where the new replica must catch up before the old replica is dropped.
* Automatic cluster sizing in response to load.
* Automatic rebalancing of replicas across availability zones.

## Work items

```[tasklist]
### Milestone 1: basic managed cluster support
* [x] #19762
* [ ] #19976 
* [x] #20004  
* [x] #20368 
```

```[tasklist]
### Later
* [ ] #19978 
* [ ] #20000
* [ ] #20010 
```

## Decision log

* **28 May 2023.** Issue created.

**Comment by benesch** [comment]
I'm not sure which team should own this. Storage, compute, and surfaces all have a hand in clusters at the moment. I think the API changes are, strictly speaking, surfaces remit, but it may be compute that has the capacity for this work.

**Comment by antiguru** [comment]
Milestone 1 implemented and in GA. Closing issue.
