### ISSUE TITLE
adapter: differentiate progress subsources from others

### ISSUE THREAD

**Issue by sploiselle** [MaterializeInc/materialize#19542]
### Feature request

Right now, you cannot consult any introspection table to determine which subsource is the progress subsource/remap collection.

I see a few fixes for this:
- Add a `progress_id` column to `mz_sources`

  This would express an optional ID if the source has a progress collection. This has the advantage of total backward compatibility, but the disadvantage of requiring queries that need this information to be more verbose.
- Add a new `type` of source called `progress`

  Subsources that used to be `subsource` might become `progress`, so this is a backward-incompatible change because members of the set `type = 'subsources'` will change. However, it has the advantage of making the data in `mz_sources` more expressive because data-bearing and progress subsources are very different types of collections.

- Add a 'subsource_type' column to `mz_sources`, either 'data' or 'progress'.

  This is a backward compatible version of the above that would also let us extend subsources into other types in the future.

@benesch pinging you because you're often the adjudicator of backward incompatibility

**Comment by benesch** [comment]
> * Add a new `type` of source called `progress`

I like this too. I think the backincompat implications are minimal. Can't imagine anyone has managed to write a useful SQL query using `type = subsource` today.

**Comment by sploiselle** [comment]
closed by #19550
