### ISSUE TITLE
Slow queries in the dataflow can slow down unrelated queries

### ISSUE THREAD

**Issue by quodlibetor** [MaterializeInc/materialize#1956]
If you look at this latency chart:

<img width="1427" alt="image" src="https://user-images.githubusercontent.com/277161/74284916-bd4da380-4cf2-11ea-8ae2-db7f9498a8e5.png">

You can see that the majority of queries at the dataflow layer take less than 8ms, with the median being under 200 _micro_ seconds. Unfortunately that doesn't translate to the wire protocol layer, where we see that the slow queries appear to be interacting with all the other queries, causing the median to be in the 125-250 _milli_ second range.

This chart was generated by running peeker with queries 1,2,3,12 , and it's 2 that is the slow one.

**Comment by cuongdo** [comment]
@frankmcsherry suggests that as a prerequisite for resolving this issue, we need to improve our diagnostic workflow. The next time we run into this, let's investigate and create/tighten our workflow.

**Comment by wangandi** [comment]
Will be fixed to the best of our ability now that we have switched to the platform architecture.
