### ISSUE TITLE
Add a lint to validate that the documentation of introspection sources matches their schema

### ISSUE THREAD

**Issue by antiguru** [MaterializeInc/materialize#19563]
### Feature request

At the moment, the [documentation](https://github.com/MaterializeInc/materialize/blob/ef389ee7ed42be96b177d68a72a1e0c4e50bc547/doc/user/content/sql/system-catalog/mz_internal.md) of introspection sources is separate from their [definition](https://github.com/MaterializeInc/materialize/blob/ef389ee7ed42be96b177d68a72a1e0c4e50bc547/src/adapter/src/catalog/builtin.rs). This causes them to diverge frequently. We should add a lint that compares the schema to the documentation and errors if it doesn't match.

Alternatively, we could consider an approach where both definition and documentation are generated from a common source.

**Comment by jseldess** [comment]
@antiguru, would it be possible to do something similar for `information_schema`, `mz_catalog`, and `pg_catalog`?
