### ISSUE TITLE
Support SET TRANSACTION ISOLATION LEVEL

### ISSUE THREAD

**Issue by def-** [MaterializeInc/materialize#19589]
### Feature request

Instead of just `SET TRANSACTION_ISOLATION`. See https://materialize.com/docs/get-started/isolation-level/ vs https://www.postgresql.org/docs/current/sql-set-transaction.html

Noticed while porting Jepsen, which uses Clojure's jdbc lib, which internally uses `SET TRANSACTION ISOLATION LEVEL`. I assume this is quick to implement.

**Comment by jkosh44** [comment]
Just a note, `SET TRANSACTION ISOLATION LEVEL` and `SET TRANSACTION_ISOLATION` are not equivalent. `SET TRANSACTION ISOLATION LEVEL` is equivalent to `SET LOCAL TRANSACTION_ISOLATION`, if I understand it correctly.

**Comment by def-** [comment]
Right, my bad. It should be only for the current session.
