### ISSUE TITLE
Postgres CDC resumption tests sees partial results

### ISSUE THREAD

**Issue by sploiselle** [MaterializeInc/materialize#19617]
### What version of Materialize are you using?

fd23c0f413b2f88c5722de881a6d784c4c181c41

### What is the issue?

We thought that we had resolved this bug with #19079

However there is another occurrence of it after the fixed have merged:
https://buildkite.com/materialize/tests/builds/56660#01887319-8ed0-421a-b791-6e34797ca177

The plan is to revert the code that we believe introduces this (somewhere in the reversion chain of #19576 which does not include multi-worker PG code) late on Thursday, unless @teskje has insight that lets us fix the bug earlier in the day.

**Comment by teskje** [comment]
The fastest way to reproduce this locally I've found so far is to apply this diff:
```diff
diff --git a/test/pg-cdc-resumption/mzcompose.py b/test/pg-cdc-resumption/mzcompose.py
index 39396d2086..270b85d51f 100644
--- a/test/pg-cdc-resumption/mzcompose.py
+++ b/test/pg-cdc-resumption/mzcompose.py
@@ -25,14 +25,14 @@ def workflow_default(c: Composition) -> None:

     # TODO: most of these should likely be converted to cluster tests
     for scenario in [
-        disconnect_pg_during_snapshot,
-        disconnect_pg_during_replication,
+        # disconnect_pg_during_snapshot,
+        # disconnect_pg_during_replication,
         restart_pg_during_snapshot,
-        restart_mz_during_snapshot,
-        restart_pg_during_replication,
-        restart_mz_during_replication,
-        fix_pg_schema_while_mz_restarts,
-        verify_no_snapshot_reingestion,
+        # restart_mz_during_snapshot,
+        # restart_pg_during_replication,
+        # restart_mz_during_replication,
+        # fix_pg_schema_while_mz_restarts,
+        # verify_no_snapshot_reingestion,
     ]:
         print(f"--- Running scenario {scenario.__name__}")
         initialize(c)
```

... and then run `./mzcompose run default` in an endless loop until it fails.
