### ISSUE TITLE
Convert filters on index fields into joins

### ISSUE THREAD

**Issue by frankmcsherry** [MaterializeInc/materialize#1962]
From #780, filters that test for equality between a constant and fields that are an arrangement key can be converted into Join operators.

@wangandi has some work in progress here, but we should check the interaction with other aspects of join planning (for example, should these become `ScalarExpr::Literal` variants in the join's equivalence classes?).

**Comment by awang** [comment]
@wangandi can i close this one out?

**Comment by awang** [comment]
closing issue, @wangandi please reopen if there's still work to do
