### ISSUE TITLE
Address testing holes from the Jun 1st thing 

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#19658]
### Feature request

- [ ] Run CI pipelines with compaction disabled
- [x] Platform checks: Add upsert sources where the data grows and shrinks - https://github.com/MaterializeInc/materialize/pull/19661
- [x] Zippy: Add pad column to Kafka sources and implement upsert actions by modifying the pad column
- [x] Zippy: Add pad column to Postgres sources and implement Update actions over the pad column (will also cause DEBEZIUM sources to have upsert)
- [x] Brainstorm on a dedicated "exhaust all upsert combinations" test

## Exhaust all upsert combinations

Current tests , including randomized one, are not guaranteed to cause any possible combinations of upsert events to happen. Upsert events being:
- individual upsert events, such as inserts, updates and deletes
- combinations of N of upsert events within the same timestamp, such as two updates , within the same timestamp (if supported by Mz at ll)
- combinations of N upsert events over multiple timestamps
- restarts

So , for example, a combination would be to delete a value from one key, insert it into another and then update it in-place

**Comment by uce** [comment]
We'll break out the 2nd part of this ticket ("Exhaust all upsert combinations") into a separate ticket.

**Comment by philip-stoev** [comment]
The second part has been broken out as #19744
