### ISSUE TITLE
ERROR: Invalid data in source errors, saw retractions (100) for row that does not exist

### ISSUE THREAD

**Issue by def-** [MaterializeInc/materialize#19703]
### What version of Materialize are you using?

5f21d36

### What is the issue?

Happened in v0.57.0 nightly, fails sporadically: https://buildkite.com/materialize/nightlies/builds/2521#01887e6c-09cb-460d-b3c7-a7e5f696111d
```
[2023-06-03T00:54:33Z] > SELECT f1, max(f2), SUM(LENGTH(f3)) FROM postgres_source_tableA GROUP BY f1;
[2023-06-03T00:59:33Z] rows didn't match; sleeping to see if dataflow catches up 50ms 75ms 113ms 169ms 253ms 380ms 570ms 854ms 1s 2s 3s 4s 6s 10s 15s 22s 33s 49s 74s 78s
^^^ +++
[2023-06-03T00:59:34Z] 7:1: error: executing query failed: db error: ERROR: Invalid data in source errors, saw retractions (100) for row that does not exist: Evaluation error: internal error: Invalid data in source, saw non-positive accumulation for key Row{[String("C")]} in hierarchical mins-maxes aggregate: ERROR: Invalid data in source errors, saw retractions (100) for row that does not exist: Evaluation error: internal error: Invalid data in source, saw non-positive accumulation for key Row{[String("C")]} in hierarchical mins-maxes aggregate
[2023-06-03T00:59:34Z]      |
[2023-06-03T00:59:34Z]    6 | 
[2023-06-03T00:59:34Z]    7 | > SELECT f1, max(f2), SUM(LENGTH(f3)) FROM postgres_source_tableA GROUP BY f1;
[2023-06-03T00:59:34Z]      | ^
+++ !!! Error Report
```
Note by @philip-stoev:
> When upgrading from versions that are known pg-problematic, the test waits for the snapshot to complete before proceeding. So this could be very well be an actual product bug

I'll check if I can reproduce it locally and if it was introduced recently or has been failing for longer.

**Comment by def-** [comment]
Unfortunately I couldn't reproduce this. It was first seen in CI on April 28, happened a total of 3 times since then, so hard to pin down where this came from exactly. As Philip said this could be a product bug. @petrosagg Do you have any idea?

**Comment by sploiselle** [comment]
We have seen oddities before if the snapshot is attempted in one release and then allowed to complete in another https://github.com/MaterializeInc/materialize/issues/18940#issuecomment-1522112700--triggered only when upgrading from X to X + (> 1).

@def- Do you know if these tests allow the snapshots to complete within the same version?

**Comment by def-** [comment]
@sploiselle Yes, we wait for snapshot to complete before the next action.

The logs were spammed with a whole lot of this for much of the test run:
```
upgrade-matrix-materialized-1  | cluster-u1-replica-1: 2023-06-03T00:54:33.953221Z  WARN mz_compute::render::errors: [customer-data] Non-positive accumulation in MinsMaxesHierarchical (key=(Row{[String("A")]}, 3650857), value=[Row{[Int32(289)]}], count=-1) dataflow="oneshot-select-t8"
upgrade-matrix-materialized-1  | cluster-u1-replica-1: 2023-06-03T00:54:33.953229Z  WARN mz_compute::render::errors: [customer-data] Non-positive accumulation in MinsMaxesHierarchical (key=(Row{[String("A")]}, 27730428), value=[Row{[Int32(264)]}], count=-1) dataflow="oneshot-select-t8"
upgrade-matrix-materialized-1  | cluster-u1-replica-1: 2023-06-03T00:54:33.953244Z ERROR mz_compute::render::errors: Non-positive accumulation in MinsMaxesHierarchical
upgrade-matrix-materialized-1  | cluster-u1-replica-1: 2023-06-03T00:54:33.953242Z  WARN mz_compute::render::errors: [customer-data] Non-positive accumulation in MinsMaxesHierarchical (key=(Row{[String("A")]}, 56343410), value=[Row{[Int32(237)]}], count=-1) dataflow="oneshot-select-t8"
```

**Comment by sploiselle** [comment]
@def- The `PgCdc` check doesn't ensure the snapshot has completed until the `validate` step. For example in this, it looks like the snapshot begins in v0.52.4 and isn't guaranteed to complete until `None`, which I'm guessing is the HEAD of the branch we're building against.

```
[BeginUpgradeScenario, BeginVersion(v0.52.4), ChecksInitialize, ChecksManipulate(#1), EndVersion(v0.52.4), BeginVersion(v0.53.0), ChecksManipulate(#2), EndVersion(v0.53.0), BeginVersion(v0.54.0), EndVersion(v0.54.0), BeginVersion(v0.55.0), EndVersion(v0.55.0), BeginVersion(v0.56.1), EndVersion(v0.56.1), BeginVersion(None), ChecksValidate, EndUpgradeScenario]
```

Am I misreading this?

**Comment by def-** [comment]
In the `ChecksManipulate(#1)` of PgCdc check it creates the `postgres_source1` based on `postgres_source_tableA` as well as the index, and then waits for the `count(*)` to catch up, which indicates snapshot completion as far as I understand it:

https://github.com/MaterializeInc/materialize/blob/563f7253821e4806803d42bc56512802a0f6117d/misc/python/materialize/checks/pg_cdc.py#L75-L77

This is all done in a single version. The scenario that ran here was:
```
Testing upgrade scenario with id 23: [BeginUpgradeScenario, BeginVersion(v0.54.0), ChecksInitialize, EndVersion(v0.54.0), BeginVersion(v0.55.0), ChecksManipulate(#1), ChecksManipulate(#2), EndVersion(v0.55.0), BeginVersion(v0.56.1), EndVersion(v0.56.1), BeginVersion(None), ChecksValidate, EndUpgradeScenario]
```
So all of this happened at v0.55.0, then after an upgrade to v0.56.1 and current main state the validate is run, which has the invalid data in source errors then.

**Comment by sploiselle** [comment]
Ah, the `[version>=4601]` at the beginning of the select threw me off; I didn't see the `SELECT` statement. My mistake!

The buildkite output makes it look like this is the scenario that ran in closest proximity to the failure at `[2023-06-03T00:51:29Z]`

```
Testing upgrade scenario with id 25: [BeginUpgradeScenario, BeginVersion(v0.39.3), ChecksInitialize,
ChecksManipulate(#1), EndVersion(v0.39.3), BeginVersion(v0.40.0), EndVersion(v0.40.0), BeginVersion(v0.41.1), 
EndVersion(v0.41.1), BeginVersion(v0.42.4), EndVersion(v0.42.4), BeginVersion(v0.43.0), EndVersion(v0.43.0), 
BeginVersion(v0.44.3), EndVersion(v0.44.3), BeginVersion(v0.45.0), EndVersion(v0.45.0), BeginVersion(v0.46.1), 
ChecksManipulate(#2), EndVersion(v0.46.1), BeginVersion(v0.47.1), EndVersion(v0.47.1), BeginVersion(v0.48.4), 
EndVersion(v0.48.4), BeginVersion(v0.49.6), EndVersion(v0.49.6), BeginVersion(v0.50.3), EndVersion(v0.50.3), 
BeginVersion(v0.51.1), EndVersion(v0.51.1), BeginVersion(v0.52.4), EndVersion(v0.52.4), BeginVersion(v0.53.0), 
EndVersion(v0.53.0), BeginVersion(v0.54.0), EndVersion(v0.54.0), BeginVersion(v0.55.0), EndVersion(v0.55.0), 
BeginVersion(v0.56.1), EndVersion(v0.56.1), BeginVersion(None), ChecksValidate, EndUpgradeScenario]
```

But in this, the `ChecksManipulate(#1)` is done in version 0.39.3, which does not wait for the snapshot to complete. This failure is on table A, which checks out, because its snapshot wasn't waited to completion.

I think this is substantiated by:

```
[2023-06-03T00:51:39Z] Starting Mz using image materialize/materialized:v0.39.3
....

without a `Testing upgrade scenario with id...` line between it and the failure.

Am I misreading this, as well? Known to happen 😅
