### ISSUE TITLE
Initial spike in memory usage prevents sizing down

### ISSUE THREAD

**Issue by chuck-alt-delete** [MaterializeInc/materialize#19726]
### What version of Materialize are you using?

v0.56.2 (7275107b5)

### What is the issue?

The steady state for my workload on an xsmall is roughly 25% memory usage. This should be safe to scale down to 2xsmall. However, there is an initial spike in memory usage that prevents sizing down because the smaller replica OOMs.

- [Context (from Slack)](https://materializeinc.slack.com/archives/CU7ELJ6E9/p1685985801183179)
- [Workload (from Notion)](https://www.notion.so/materialize/PDT-802f9460ccf44d22b66130a81feebec8)
  - Running a join with an index on each join column and then an indexe on the result
  - I let it run over the weekend to get up to 18M input records (only about 1GB)

Resource graph:
![image-3](https://github.com/MaterializeInc/materialize/assets/87353672/f5c64902-b319-4627-bc7b-b0d896865287)

**Comment by chuck-alt-delete** [comment]
As of now, the topic is still active in Confluent Cloud, so let me know and I can hook you up with access keys.

**Comment by benesch** [comment]
Thanks, @chuck-alt-delete!  This is super helpful. I'm going to fold this into our existing issue on the subject: #15974.
