### ISSUE TITLE
Document common Debezium pitfall of leaving `decimal.handling.mode` set to `precise`

### ISSUE THREAD

**Issue by chuck-alt-delete** [MaterializeInc/materialize#19756]
### Documentation request

At least twice users have asked how to convert `bytea` to `numerical` because they used the default `decimal.handling.mode=precise` in debezium when they could have set it to `double`.

Adding conversion from `bytea` to `numerical` in Materialize is computationally expensive and not straightforward to implement. We could consider creating special `ENVELOPE DEBEZIUM` schema parsing logic that does this conversion automatically in the source, but it seems like users don't tend to actually want to use `precise` in most cases and it would be better if this pitfall were pointed out in the docs instead.

### Affected Pages

- https://materialize.com/docs/connect-sources/cdc-mysql/
- https://materialize.com/docs/connect-sources/cdc-postgres-kafka-debezium/

**Comment by benesch** [comment]
Wait wait wait! Something is fishy here. Setting `decimal.handling.mode` to `double` is generally not what we should be recommending—that's YOLO mode! Most decimals are not losslessly convertible to doubles, and this will result in subtly incorrect data.

We have a test that we correctly handle `decimal.handling.mode = precise` for Debezium + PostgreSQL:

https://github.com/MaterializeInc/materialize/blob/bab312e0736ad0c31935264e64dbada805f8c281/test/debezium/postgres/90-decimal-handling-mode.td#L10-L32

I suspect something _else_ went wrong in this user's pipeline. @chuck-alt-delete do you have a repro?

**Comment by chuck-alt-delete** [comment]
Found a another issue discussing this
- https://github.com/MaterializeInc/materialize/issues/17155


The case I’ve been looking at seems ok to use double. Should the guidance be to use string instead and then cast to numeric in Materialize?

I don’t have a direct repro, but it’s a very straightforward Postgres -> debezium -> Kafka -> materialize. With precise, it shows up as bytea in Materialize, whereas with double it works as expected.

**Comment by chuck-alt-delete** [comment]
It may be that the column in Postgres wasn’t created with a specific numerical precision

**Comment by benesch** [comment]
Ahh, I see, yes. Closing in favor of #17155.

**Comment by chuck-alt-delete** [comment]
Wait @benesch this issue is specifically to put something in the docs to warn people or give guidance around it. I think the other issue is more about solving the problem in the product. Should we keep this open as a docs issue?

**Comment by benesch** [comment]
I updated the title and description there to try to cover both! Let me know what you think. My fear is that it's not clearly a good use of docs time to document the complexities of this situation. The engineering required to support variable-precision decimals is bounded and straightforward, and so it may be better for docs to agitate for engineering to just fix this, rather than trying to figure out how to explain the current subpar situation. I figure whoever picks this up is more likely to make the right call if we bundle the documentation and feature request together in the same issue.
