### ISSUE TITLE
ws: support query cancellation

### ISSUE THREAD

**Issue by benesch** [MaterializeInc/materialize#19773]
*Part of epic #19771.*

It's not (easily?) possible today to cancel a query running on a WebSocket connection. This is particularly annoying for `SUBSCRIBE` queries, which typically are not expected to terminate until they are explicitly canceled.

From https://github.com/MaterializeInc/materialize/issues/18224#issuecomment-1562286516:

> I actually think you _could_ cancel the subscribe if you could somehow figure out the connection ID for the session and then issue a cancellation request via pgwire. But we should probably support this natively in the WS protocol. Probably the best thing to do is to allow the client to send a `{"cancel": true}` message at any point to cancel the in-flight command on the connection.
> 
> Don't think we want to follow the pgwire approach of having a separate connection send a cancel request. The justification for why it works like this in pgwire seems stuck in 1998.
> 
> > During the processing of a query, the frontend might request cancellation of the query. The cancel request is not sent directly on the open connection to the backend for reasons of implementation efficiency: we don't want to have the backend constantly checking for new input from the frontend during query processing. Cancel requests should be relatively infrequent, so we make them slightly cumbersome in order to avoid a penalty in the normal case.
> 
> We have access to async/await in Rust, so it is perfectly efficient to both stream query results to the client while checking to see if the client has sent a cancel request.

The ask here is roughly to allow the WS client to send a message like

```
{"cancel": true}
```

at any point, and have the server issue a cancellation request for whatever is currently running on the connection.

**Comment by mjibson** [comment]
Trying to figure out how this would actually work. Our WS handler would have to keep listening for input while it was waiting for any coordinator response or row response. But those requests could also be query requests, not just cancels. So we could get:

```
query: "subscribe t"
query: "select 1"
cancel: "true"
```

This would block on the subscribe. Our listener would see the `SELECT` and then do what? Add it to some incoming work queue? Then the cancel would affect the SUBSCRIBE? This ordering doesn't make a lot of sense. A new connection has benefits here. Documenting exactly how inband cancel works would be a bit weird, which makes me suspect it's a bad design.

**Comment by benesch** [comment]
> Our listener would see the `SELECT` and then do what? Add it to some incoming work queue? Then the cancel would affect the SUBSCRIBE? This ordering doesn't make a lot of sense.

That's what I was envisioning. Requests get queued, but cancel requests jump the queue.

> A new connection has benefits here. Documenting exactly how inband cancel works would be a bit weird, which makes me suspect it's a bad design.

Ok. So the alternative would be to introduce a `BackendKeyData` message to the WS protocol, like pgwire has, and then add support for `pg_cancel_backend`. Then the web console can cancel an ongoing WS session by issuing a `POST /api/sql` with `{"query": "SELECT pg_cancel_backend($1)", params: ["<conn id>"]}`.

**Comment by mjibson** [comment]
`pg_cancel_backend` in pg is "allowed if the calling role is a member of the role whose backend is being canceled". We'd need to add that information to the cancel infrastructure, which we could do.

What about a POST with payload

```
{
  "cancel": <conn id>,
  "secret": <secret>,
}
```

And we add the full connid/secret message to the initial ws connection, identical to pgwire?

Other options are adding an optional second argument to pg_cancel_backend that is the secret key in lieu of teaching the cancel infra about role membership.

Ideas thus far are:

1. `pg_cancel_backend(conn_id)` + teach coord's cancel stuff about roles + teach ws to send the conn_id
2. `pg_cancel_backend(conn_id, secret)` + teach ws to send the conn_id and secret
3. New `{cancel, secret}` POST message + teach ws to send conn_id and secret
4. Allow inband WS cancel messages that jump the queue

3 appeals the most to me and I think is the least amount of typing and documentation. 4 would require refactoring how WS connections work quite a bit because of the message queue thing and so we wouldn't be able to send down the `&mut ws` to the various request functions that expect access to it.

**Comment by mjibson** [comment]
Over huddle: going to try 1 to see how hard the impl is. Worth doing for pg compat generally.

**Comment by mjibson** [comment]
`pg_cancel_backend` needs to take an argument and be an unmat fn. We decided this would be the first unmat fn that takes an argument. Due to how this fn works, it'd have to be a const expression (no Get), and that's ok.

**Comment by jkosh44** [comment]
So just to confirm, we've decided to do the following:

1. Update unmaterializable functions to be able to take an argument.
2. Implement pg_cancel_backend(conn_id) that cancels any currently running query initiated by conn_id.
3. Check that the role executing pg_cancel_backedn is a member of the session role of conn_id.

Has there been any discussion on how to accomplish the first two items?

**Comment by jkosh44** [comment]
> So just to confirm, we've decided to do the following:
> 
>   1. Update unmaterializable functions to be able to take an argument.
>   2. Implement `pg_cancel_backend(conn_id)` that cancels any currently running query initiated by conn_id.
>   3. Check that the role executing `pg_cancel_backend` is a member of the session role of conn_id.
> 
> Has there been any discussion on how to accomplish the first two items?

This may have already been discussed but here's some challenges with this approach:
- Currently the execution context for functions only has access to the catalog state, not the coordinator state, so there's no way to look up active sessions. We can probably fix this by threading the coordinator state into this context.
- Similarly to the point above, unmaterializable functions have no way to send messages to the coordinator so we'll to thread in some channel.
- If my understanding is correct, unmaterializable functions are fully evaluated as part of `EXPLAIN`. If we want to match PostgreSQL semantics, then we'd have to find a way to avoid cancelling queries when a query containing `pg_cancel_backend` is explained.

**Comment by benesch** [comment]
> * If my understanding is correct, unmaterializable functions are fully evaluated as part of `EXPLAIN`. If we want to match PostgreSQL semantics, then we'd have to find a way to avoid cancelling queries when a query containing `pg_cancel_backend` is explained.

Erm, is there some reason that `EXPLAIN` must work like this? It seems much nicer if `EXPLAIN` could refrain from doing that. Is it something about needing to optimize the plan, which can only happen if the unmaterialized functions have been eval'd? Sigh.

**Comment by mjibson** [comment]
`eval_unmaterializable_func` might need to return a

```
struct EvaluatedUnmaterializableFunc {
    expr: MirScalarExpr,
    cancel_ids: Vec<ConnectionId>, // or u32?
}
```

that gets passed up and optionally processed by the coordinator. It would be super good if `eval_unmaterializable_func` didn't need to take a `&mut Coordinator` because in its current state it can be executed off thread.

**Comment by mjibson** [comment]
Oh wait that might not work either. `pg_cancel_backend ` returns a boolean of whether it cancelled a query or not (double check this, it might return true if the named connection exists but isn't executing anything atm), so it'd need more information (active queries by connection id, role membership) in order to produce the correct MirScalarExpr when eval'd.

**Comment by jkosh44** [comment]
> double check this, it might return true if the named connection exists but isn't executing anything atm

I'm pretty sure it's just true if the pid exists or not.

![Screenshot from 2023-06-14 17-05-30](https://github.com/MaterializeInc/materialize/assets/10800303/414dcdc8-281e-4e7e-a8b1-34b743353f14)

**Comment by jkosh44** [comment]
> > * If my understanding is correct, unmaterializable functions are fully evaluated as part of `EXPLAIN`. If we want to match PostgreSQL semantics, then we'd have to find a way to avoid cancelling queries when a query containing `pg_cancel_backend` is explained.
> 
> Erm, is there some reason that `EXPLAIN` must work like this? It seems much nicer if `EXPLAIN` could refrain from doing that. Is it something about needing to optimize the plan, which can only happen if the unmaterialized functions have been eval'd? Sigh.

Just to double check that I'm not completely misreading the code:

`sequence_explain_plan` calls `prep_scalar_expr` here:

https://github.com/MaterializeInc/materialize/blob/6c5b2b2cd698440d9e52fbf95f51db070fe503b3/src/adapter/src/coord/sequencer/inner.rs#L2601-L2604

and `prep_scalar_expr` evaluates all unmaterializable functions here: 

https://github.com/MaterializeInc/materialize/blob/6c5b2b2cd698440d9e52fbf95f51db070fe503b3/src/adapter/src/coord/dataflows.rs#L654-L676

I ran a debugger and executed `EXPLAIN SELECT mz_now()`, which seemed to confirm that `mz_now()` was executed as part of sequencing.

**Comment by mjibson** [comment]
I'm not opposed to having a thing (the planner?) recognize queries that are of the exact form `SELECT pg_cancel_backend($1)` and those produce a different plan than Peek. It'd avoid all this mess at the expense of some pg compat. `SELECT pg_cancel_backend(x) FROM generate_series(1, 1000000) t(x)` for example. This is perhaps better than trying to untangle all the above.

**Comment by benesch** [comment]
> `SELECT pg_cancel_backend(x) FROM generate_series(1, 1000000) t(x)` for example.

Well we were never going to be able to support that anyway, because `x` isn't an integer literal!

**Comment by benesch** [comment]
So, how would the alternative work? Something like:

```rust
// Somewhere in the `sql` crate...

/// A side-effecting function is a function whose evaluation triggers side effects,
/// like `pg_cancel_backend`.
///
/// In PostgreSQL, these functions can appear anywhere in a query:
///
///     SELECT 1 WHERE pg_cancel_backend(1234)
///
/// In Materialize, our compute layer cannot execute functions with side effects. So we
/// sniff out the common form of function calls, e.g.
///
///    SELECT side_effecting_function(...)
///
/// where all arguments are literals or bound parameters, and plan them specially as a
/// `Plan::SideEffectingFunction`. This gets us pgcompat for 90% of cases, without causing
/// stress for the compute layer (optimizer, dataflow execution, etc.), as we can handle all
/// the side effects cleanly in the adapter layer.
enum SideEffectingFunction {
    /// The `pg_cancel_backend` function, .
    PgCancelBackend {
        // The ID of the connection to cancel.
        connection_id: ConnectionIdType
    },
}

enum Plan {
    // ...
    SideEffectingFunction(SideEffectingFunction),
}
```

And then we'd adjust `plan_root_query` to sniff out this pattern: a `SELECT` with exactly one expression in the select list containing exactly one side-effecting function call with arguments that are all either literals or parameters.

I think we still have an `EXPLAIN` problem—`EXPLAIN` also needs to be taught about this massive special case—but seems tractable!

**Comment by mjibson** [comment]
SGTM!

**Comment by jkosh44** [comment]
I think it sounds tractable too. The planner will just have to error if it sees one of those functions in a more complex query.

Also not that anyone asked, but `pg_cancel_backend` is not run transactionally in PostgreSQL. It will cancel the query immediately in the middle of the transaction, even if the transaction later aborts. Spooky stuff.

I'm not sure if this has already been discussed, but at this point would it be easier to just add a new command for cancelling queries? We could treat it similarly to `Command::DumpCatalog` and we avoid having to do all of this special casing. I'd be surprised to hear that any of our customers care if we have this PostgreSQL function available.

**Comment by mjibson** [comment]
Have been working on this and there seem to be 2 bad ways to implement.

1. At the top of `plan_select`, sniff the `Statement` for this form. This is just a ton of match statements that nest pretty deep, and at the end we still have an ast Expr that we need to convert into a MirScalarExpr. This is bad because of how SQL syntax aware it needs to be, and also it needs to do some manual ast expr -> mir expr conversion.
2. Add `HirScalarExpr::SideEffectingFunc` and `MirScalarExpr::SideEffectingFunc`, and func.rs produces exactly that. `plan_select` can then sniff the `MirScalarExpr` for something drastically simpler. The downside is we have to plumb these side effecting fns through hir and mir and protobufs, which is a bit strange since they are never executed.

I don't like either of these. Is there a better one?

**Comment by benesch** [comment]
Plan (1) was what I was envisioning, because part of the appeal here is
insulating the MirScalarExpr from this grossness.

The match statement is deep, for sure, but I feel like it is mostly just
typing and not actually that complicated? Gross and annoying, don’t get me
wrong, but not subtle and complicated. Is the manual conversion from AST
expr to MirScalarExpr harder than just going even deeper down the rabbit
hole to peel off an Expr::Value, calling plan_value to get a datum, and
then making sure it’s a Datum::Int32?
