### ISSUE TITLE
Maintaining transactional atomicity in Materialize (when reading from MySQL/Postgres through Debezium)

### ISSUE THREAD

**Issue by nacrooks** [MaterializeInc/materialize#1979]
Materialize processes records obtained through debezeum through separate Kafka Topic per tables. It does not currently preserve transactional guarantees. It is possible to
1) see partial results of a transaction (this is transient)
2) end up in a state that does not correspond to a serializable execution (this is not necessarily transient)

I do not believe that there is any permanent loss of atomicity. Once no more data is ingested, Materialize will eventually settle to a consistent state. 

**1) Transient Partial Results:**
Debezeum writes database changes to Kafka as a stream of invidual row-level changes. Materialize then processes each Kafka record invidually.

If a transaction writes 10 records to the same table, it is possible for a Materialize SELECT query to return a view that contains only the first x records.

**2) Transient Inconsistent Results**

Binary log writes records in the order in which they were executed. Records from multiple concurrent transactions can thus be interleaved.

```
create table foo (a int, b int);
insert into foo values (1,1);
insert into foo values (2,2);

create table  bar (a int, b int);
insert into bar values (1,1);
insert into bar values (2,2);

```
The two transactions are running from two different MySQL/PSQL clients:
```

Client 1 start transaction
Client 2 start transaction
Client 1 update foo set a = 100 where b = 1;
Client 2 update foo set a = 50 where b = 2 ;
Client 2 update bar set a = 50 where b = 2;
Cilent 1 update bar set a = 100 where b = 1;
Client 1 commit 
Client 2 commit 

```
It is possible for Materialize to see the following state, which could not have arisen in any serializable execution.
```
foo
a       b
100   1
50    2
```

```
bar
a    b
1     1  
50  2

```

**Comment by rjnn** [comment]
Just holding to MySQL for now: If we configure Debezium to emit GTIDs, is there sufficient information in the topics to process all messages in order, and atomically across topics?

**Comment by frankmcsherry** [comment]
I don't believe so, but others can leap in. While GTIDs can show up with records, we would also need completeness information: that no further records will show up, in this topic or in others.

**Comment by nacrooks** [comment]
After some more research, it's actually possible to do it for Oracle, MySQL
and Postgres (at least for the case where you have a single master, I'm not
sure about MySQL's multi master setup).

**Comment by nacrooks** [comment]
The "benefit" of this approach is that it is not specific to Materialize and might be something that Debezeum is interested in (there's been a number of comments online about asking Debezeum to support some form of transaction watermarking. They've answered that it is a feature that they want to support but not a priority). It also wouldn't hurt Debezeum's read/write throughput unless it is turned on

**Comment by awang** [comment]
From what I can tell, we prefer correctness over urgency, so moving to 0.6

**Comment by elindsey** [comment]
I'm closing this in favor of https://github.com/MaterializeInc/materialize/issues/7537 - dbz now has txn metadata topics so we don't need to create our own format, but do need to consume this for rt.
