### ISSUE TITLE
Cockroach unhealthy during upgrade tests

### ISSUE THREAD

**Issue by def-** [MaterializeInc/materialize#19810]
### What version of Materialize are you using?

b053fd4

### What is the issue?

All 3 upgrade tests which failed here had Cockroach unhealthy: https://buildkite.com/materialize/nightlies/builds/2555

Nothing suspicious in the logs, so I'm not sure what is going on there and how to continue.

**Comment by def-** [comment]
@philip-stoev Do you have any ideas on how to continue with this? It's sporadic, docker inspect and logs don't seem to reveal much except that CRDB is returning 503s

**Comment by philip-stoev** [comment]
Not seen since https://github.com/umanwizard/materialize-1/commit/8cee44f2dc59fcd7a1d6e83bb3ecc59e7177fa2d was merged
