### ISSUE TITLE
Mysterious triggering of ArrangementFlavor::Trace code path

### ISSUE THREAD

**Issue by wangandi** [MaterializeInc/materialize#1985]
The following line in test/testdrive/dependencies.td goes through the `ArrangementFlavor::Trace(_)` code path during index exporting:
```
> CREATE OR REPLACE MATERIALIZED VIEW v3 AS SELECT 1
```

This is very mysterious because no indexes are supposed to be imported when creating a view on `select <constant>`.

For unknown reasons, I am unable to produce any println output in this code path to print out what index may be being imported, and I cannot step into this code path via lldb.

Right now, this mysterious code path does not have detrimental effects on the product because we just do nothing.

**Comment by wangandi** [comment]
To see this mysterious behavior in action. 

Here is the current (at time of this comment) code for when index being exported is stored in the context as `ArrangementFlavor::Trace`:
```
                    Some(ArrangementFlavor::Trace(_)) => {
                        if let Some(existing_id) = dataflow
                            .index_imports
                            .iter()
                            .filter_map(
                                |(id, (desc, _))| if desc == index_desc { Some(id) } else { None },
                            )
                            .next()
                        {
                            // if the index being exported is a duplicate of an existing
                            // one, just copy the existing one
                            let trace = manager.get(existing_id).unwrap().clone();
                            manager.set(*export_id, trace);
                        }
                        // Do nothing otherwise.
                        // TODO: materialize#1985 Somehow this code branch is triggered
                        // when materializing a view on `SELECT <constant>`
                    }
```

Change the code to something like 

```
                    Some(ArrangementFlavor::Trace(_)) => {
                        let existing_id = dataflow
                            .index_imports
                            .iter()
                            .filter_map(
                                |(id, (desc, _))| if desc == index_desc { Some(id) } else { None },
                            )
                            .next().unwrap();
                         let trace = manager.get(existing_id).unwrap().clone();
                         manager.set(*export_id, trace);
                    }
```

Run test/testdrive/dependencies.td. Materialize will crash at the `let existing_id...` line. 

Note that if you change the changed version one step further by replacing `if desc == index_desc { Some(id) } else { None }` to `Some(id)`, Materialize will not crash, which suggests that `dataflow.index_imports` contains something, but I am unable to print any information out about what `dataflow.index_imports` might contain.

**Comment by benesch** [comment]
This seems related to #2276. The query you highlighted here in the issue description is a red herring. The actual sequence of queries that causes Materialize to crash is this:

```
> CREATE MATERIALIZED VIEW test1 AS SELECT 1;

> CREATE MATERIALIZED VIEW test2 AS SELECT * FROM test1;

> CREATE MATERIALIZED VIEW test3a AS SELECT * FROM test2;

> CREATE MATERIALIZED VIEW test3b AS SELECT * FROM test2;
```

It looks like the fault lies with one of the later queries in the testdrive script because testdrive is able to squeeze in a bunch more `CREATE` and `DROP` queries before materialized crashes, because dataflow creation is asynchronous.

This makes this issue much less mysterious. I'm still not sure on the root cause, but something is fishy in the way that arrangements are stored for test2 vs test3a/test3b.

**Comment by frankmcsherry** [comment]
Should this result in a crash? (typed by hand, so multiple seconds between commands; debug build):
```
materialize=> CREATE MATERIALIZED VIEW test1 AS SELECT 1;
CREATE VIEW
materialize=> CREATE MATERIALIZED VIEW test2 AS SELECT * FROM test1;
CREATE VIEW
materialize=> CREATE MATERIALIZED VIEW test3a AS SELECT * FROM test2;
CREATE VIEW
materialize=> CREATE MATERIALIZED VIEW test3b AS SELECT * FROM test2;
CREATE VIEW
materialize=> show views;
 VIEWS  
--------
 test1
 test2
 test3a
 test3b
(4 rows)

materialize=> 
```

**Comment by benesch** [comment]
Only on restart, but yes.

**Comment by frankmcsherry** [comment]
I have some data. Here is a print out of the first defective `DataflowDesc`, along with the complaint when it doesn't find what it is looking for:

```
BUILDING: DataflowDesc { 
    source_imports: {}, 
    index_imports: {User(4): (IndexDesc { on_id: User(3), keys: [Column(0)] }, RelationType { column_types: [ColumnType { nullable: false, scalar_type: Int32 }], keys: [] })}, 
    objects_to_build: [BuildDesc { id: User(5), relation_expr: OptimizedRelationExpr(Get { id: Global(User(3)), typ: RelationType { column_types: [ColumnType { nullable: false, scalar_type: Int32 }], keys: [] } }), eval_env: EvalEnv { logical_time: None, wall_time: None }, typ: Some(RelationType { column_types: [ColumnType { nullable: false, scalar_type: Int32 }], keys: [] }) }, BuildDesc { id: User(6), relation_expr: OptimizedRelationExpr(ArrangeBy { input: Get { id: Global(User(5)), typ: RelationType { column_types: [ColumnType { nullable: false, scalar_type: Int32 }], keys: [] } }, keys: [[Column(0)]] }), eval_env: EvalEnv { logical_time: None, wall_time: None }, typ: None }], 
    index_exports: [(User(6), IndexDesc { on_id: User(5), keys: [Column(0)] }, RelationType { column_types: [ColumnType { nullable: false, scalar_type: Int32 }], keys: [] })], 
    sink_exports: [], 
    dependent_objects: {User(3): [User(4)], User(5): [User(3)]}, 
    as_of: None, 
    debug_name: "materialize.public.test3a_primary_idx" 
}
DIDN'T FIND: IndexDesc { on_id: User(5), keys: [Column(0)] }
```

It looks like what is happening is that although we find a trace imported, it doesn't have a description that matches what we are looking for. Specifically, we were looking for 
```
IndexDesc { on_id: User(5), keys: [Column(0)] }
```
but the import is actually
```
IndexDesc { on_id: User(3), keys: [Column(0)] }
```
which makes some sense because we returned an alias last time.

**Comment by frankmcsherry** [comment]
Also, it seems the reason this happens first with `test3` and not with `test2` is that the arrangement produced for `test1` has a different key `[]` than what is requested by `test2` which wants `[0]`. So, `test2` makes a new arrangement, and `test3` is the first to fail to find it.
