### ISSUE TITLE
Add `redacted_..._sql` columns to system catalog

### ISSUE THREAD

**Issue by benesch** [MaterializeInc/materialize#19850]
*Part of epic MaterializeInc/cloud#6622.*

## Overview

Per our [Data Management Policy](https://docs.google.com/document/d/1eC-BxjNK52zRkVgvvEjdl-OU-Hyfp1Th/edit), raw SQL queries are considered customer data, not usage data. 

Several of our catalog tables representing the objects that exist in the system (e.g., `mz_views`, `mz_materialized_views`) contain a `definition` statement that contains the raw SQL query submitted by a user. To export the system catalog into our analytics pipeline, which is only permitted to store usage data, we'll need to redact these definitions.

## Design

* Add a `create_sql` statement to the following catalog tables:
  * `mz_connections`
  * `mz_functions`
  * `mz_indexes`
  * `mz_materialized_views`
  * `mz_secrets`
  * `mz_sinks`
  * `mz_tables`
  * `mz_types`
  * `mz_views`
* Add a corresponding `redacted_create_sql` column to each of the above. For an example of how to correctly redact a SQL query, see what @umanwizard did for the statement log: https://github.com/MaterializeInc/materialize/pull/21758
* Ensure `WITH` options are correctly redacted. As described in the management policy, redacting a SQL query consists of removing all string and numeric literals, but not idents. I think we'll need to crisp this up a bit for `WITH` options, which can, somewhat oddly, accept values as _either_ idents or literals—and we'll want to handle both the same way.

## Design considerations

We could alternatively have the catalog exporter perform the redaction, but this would require that the catalog exporter learn to parse Materialize's SQL dialect. This would be a tricky versioning problem, because the Materialize SQL dialect can evolve in every release, so we'd have to be careful to always bump the SQL parser version in the catalog exporter on every release. Having Materialize responsible for its own redaction sidesteps this problem entirely, because the SQL parser is definitionally capable of parsing all SQL in the catalog. 

The downside of this approach is that if there is a bug in the redactor we have to wait an entire release cycle to correct it. But we could always temporarily halt catalog exports in that case, or do a one-off manual fixup of the existing data in the analytics pipeline.

cc @uce @jpepin

**Comment by aalexandrov** [comment]
Some notes that came in a @MaterializeInc/compute discussion:

1. It would be good if we can extend the `EXPLAIN` syntax with an output modifier that also outputs redacted output.
2. Literal redaction when pretty-printing SQL queries and `EXPLAIN AS TEXT WITH(redacted_literals)` should be consistent with each other. For example, if a string literal "foo" should obfuscated as "???" in both the SQL query and the `EXPLAIN` output.

**Comment by benesch** [comment]
Also related is this issue to redact the output of `INSPECT SHARD` so that it can be run by `mz_support`: https://github.com/MaterializeInc/materialize/issues/21355

We should aim to align the syntax for `EXPLAIN ... (redacted)` and `INSPECT SHARD (redacted)`.

**Comment by jpepin** [comment]
Do we consider the `params` column in `mz_statement_execution_history` to be sensitive also?

**Comment by benesch** [comment]
Oh, yes, absolutely. Good call.

**Comment by aalexandrov** [comment]
> We should aim to align the syntax for `EXPLAIN ... (redacted)` and `INSPECT SHARD (redacted)`

@benesch the current plan for `EXPLAIN` is to [extend `ExplainConfig` with a `redacted` flag](https://github.com/MaterializeInc/materialize/blob/7bdcf673c18bfa14ea14120dd76a01e712c74691/src/repr/src/explain/mod.rs#L155-L189).

In `*.slt` tests for this feature you will see `EXPLAIN WITH(redacted)`, but when this is wired in the adapter code for `mz_support` we will have a some logic in the planner / sequencer code that will force-set this value to `true` when:

1. the user running the query is `mz_support` and
2. the user doesn't have `SELECT` some of the `GlobalId`s returned by `CollectionPlan::depends_on`.

In that sense the user-facing `EXPLAIN` syntax won't change -- running `EXPLAIN` as `mz_system` will just start emitting redacted output when needed.

In my current WIP branch the output uses █ as a placeholder for a redacted literal.

```
materialize=> create table t(x int, y int);
CREATE TABLE
materialize=> insert into t values (1, 2), (1, 3), (2, 4);
INSERT 0 3
materialize=> explain with(redacted) select x + 7 from t where y * 3 > 42 order by x * 5;
                  Optimized Plan                   
---------------------------------------------------
 Explained Query:                                 +
   Finish order_by=[#3 asc nulls_last] output=[#2]+
     Filter ((#1 * █) > █)                        +
       Map ((#0 + █), (#0 * █))                   +
         ReadStorage materialize.public.t         +
                                                  +
 Source materialize.public.t                      +
   filter=(((#1 * █) > █))                        +
 
(1 row)

materialize=> explain with(redacted, no_fast_path) select x + 7 from t where y * 3 > 42 order by x * 5;
                  Optimized Plan                   
---------------------------------------------------
 Explained Query:                                 +
   Finish order_by=[#3 asc nulls_last] output=[#2]+
     Filter ((#1 * █) > █)                        +
       Map ((#0 + █), (#0 * █))                   +
         ReadStorage materialize.public.t         +
                                                  +
 Source materialize.public.t                      +
   filter=(((#1 * █) > █))                        +
 
(1 row)
```

**Comment by benesch** [comment]
Thanks, makes sense!
