### ISSUE TITLE
/metrics endpoint should be configurable via --metrics-addr flag

### ISSUE THREAD

**Issue by quodlibetor** [MaterializeInc/materialize#1987]
To make SOC 2 compliance easy, we need to ensure that we don't expose anything other than metrics to materialize engineers.

**Comment by benesch** [comment]
Just a quick note: I would like to advocate for port splitting to be behind flags (`--metrics-addr`) so that the default configuration is still a combined single port on 6875.

**Comment by rjnn** [comment]
Assigned to @umanwizard not for immediate work, but as security owner so that when this is fixed, it is fixed to his satisfaction.

**Comment by quodlibetor** [comment]
I don't know that mTLS is actually required, especially not for v1.

**Comment by rjnn** [comment]
I'd like security issues to have owners, so you get to decide when it needs to be done, but least this way it doesn't slip through the cracks.

**Comment by quodlibetor** [comment]
I've moved mTLS into a dedicated issue #3649 , it's unclear to me if or when we'll need it.

**Comment by andrioni** [comment]
My two cents as a user:
- Having it as a CLI flag works for me.
- mTLS would be interesting to have, but not a blocker.

**Comment by quodlibetor** [comment]
Removing myself as assigned because we don't actually know if we want to do this, so there's no current plan of me working on it.

**Comment by benesch** [comment]
Superseded by #12698.
