### ISSUE TITLE
Support connecting to Kafka brokers with SSL (client) authentication 

### ISSUE THREAD

**Issue by ruchirK** [MaterializeInc/materialize#1989]
Right now we only support SSL encryption (client -- Materialize -- connects to secured Kafka broker, verifies broker with a CA certificate and messages between broker and Materialize are encrypted). That work was done with #1785 

We will likely also need to support SSL client authentication (where the broker authenticates Materialize). Also in scope with this work -- tests for SSL functionality. Not sure of the best way to achieve this probably best to set up a new pipeline / environment specifically for this

**Comment by sploiselle** [comment]
Does this issue contain work that is different than #1785?

**Comment by benesch** [comment]
> Does this issue contain work that is different than #1785?

Yes; #1785 only implemented SSL auth in one direction, namely, Materialize can now authenticate a Kafka server. But Kafka deployments can be configured to also authenticate clients (i.e., the reverse direction), and we don't yet support that.

**Comment by cuongdo** [comment]
Was this resolved by #2744? cc @sploiselle @benesch

**Comment by benesch** [comment]
Afraid not, for the reasons mentioned in my last comment.

**Comment by benesch** [comment]
Oh, no, sorry, I misread! Yes.
