### ISSUE TITLE
pg sources: metrics during snapshotting

### ISSUE THREAD

**Issue by sploiselle** [MaterializeInc/materialize#19909]
### Feature request

As a user setting up a PG source, I should be able to understand how my snapshot is progressing.

We currently show users when their snapshot has completed, but until that point, it is challenging to tell what is happening without e.g. having access to MZ-internal dashboards.

"Progress" in this case could be:

- MB ingested (preferred)
- Records ingested (sufficient)

Add'l thoughts:
- This needs to reset when the source resets, e.g. if a cluster gets resized during snapshotting
- Most importantly we show the number increasing if we ingest more stuff and the number doesn't move if we aren't.

**Comment by benesch** [comment]
Oh, I'm so glad you filed this issue. I'd meant to file a similar issue last night watching the customer issue go past and it slipped my mind.

Quick question: is the existing `mz_source_statistics` table enough? Is it just a matter of updating `updates_staged` as the snapshot is progressing? AFAICT that table goes from "no data" to "snapshot committed, _x_ bytes received" when the snapshot is complete, when it could be updating `updates_staged` the whole time, and `updates_committed` once the snapshot is committed.

**Comment by benesch** [comment]
Superseded by https://github.com/MaterializeInc/materialize/issues/23154.
