### ISSUE TITLE
#19176 increases `environmentd` binary size

### ISSUE THREAD

**Issue by antiguru** [MaterializeInc/materialize#19911]
### What version of Materialize are you using?

v0.55

### What is the issue?

#19176 increases the compressed binary size by around 100Mib

![image](https://github.com/MaterializeInc/materialize/assets/582946/e070cb98-6e4c-4532-adcf-632f4bddc99f)

Large: [unstable-3d9fb192f561dd8d45ebef68770eca67b3f8694a](https://hub.docker.com/layers/materialize/environmentd/unstable-3d9fb192f561dd8d45ebef68770eca67b3f8694a/images/sha256-00c2b7f08767817796a3a072e017616a238828787ab66515734d257e25695b82?context=explore)
environmentd v0.55.0-dev (3d9fb192f)
Small: [unstable-be155d61dadb203a44fe1b0f04ca9aa64ab659e8](https://hub.docker.com/layers/materialize/environmentd/unstable-be155d61dadb203a44fe1b0f04ca9aa64ab659e8/images/sha256-b91d1c25e367099bd51641dcc1dfcdcf9dc9959962b4bea81e21cf01d20141a9?context=explore)
environmentd v0.55.0-dev (ac7723dc4)

**Comment by antiguru** [comment]
I'd argue that it's a significant dependency that's only used to send parameters around, which is why I wanted to flag it.

**Comment by benesch** [comment]
Ohh, I see. The concern is not about `clusterd` (which must link RocksDB) but about `environmentd` (which does not). Thanks for clarifying!
