### ISSUE TITLE
Support all potential AWS credentials for Kinesis

### ISSUE THREAD

**Issue by JLDLaughlin** [MaterializeInc/materialize#1991]
Context: https://github.com/MaterializeInc/materialize/pull/1931

Basically, Kinesis sources assume they will be provided AWS credentials in the form of an `access_key` and `secret_access_key` from an IAM account. @benesch correctly pointed out that there are a variety of other ways to provide AWS credentials, we should support those -- or at least explore them.

**Comment by cuongdo** [comment]
@JLDLaughlin to make this more actionable, let's understand what current partners need and prioritize that first

**Comment by JLDLaughlin** [comment]
As of now, we support reading AWS credentials in two ways for Kinesis sources:
1. By default, we will try to grab credentials via Rusoto's ChainProvider.
2. If provided, we will use static IAM information.

(User docs updated here: https://github.com/MaterializeInc/materialize/pull/3502)

For now, that seems sufficient -- I'm going to close this ticket.
