### ISSUE TITLE
doc/user: Small edit to "Enable Logical Replication" docs on Postgres Source help

### ISSUE THREAD

**Issue by ruf-io** [MaterializeInc/materialize#19933]
Here https://materialize.com/docs/ingest-data/postgres-self-hosted/ we write: 

> Back in your psql shell, verify that replication is now enabled:
```
SHOW wal_level;
```

![image](https://github.com/MaterializeInc/materialize/assets/11527560/ce94c4dc-616a-4048-a3c0-0a4911101229)

**Why it's confusing:**
1. "Replication is enabled" is not the goal, replication is enabled by default when `wal_level = replica` - the goal is to enable **logical** replication
2. As someone who mostly scans, the most important information for me to see in the confirmation step is the **output** of the command: 
```
postgres=# show wal_level;
 wal_level
-----------
 logical
(1 row)
```

## Suggested Change

So ideally, we:
1. change the sentence to something like: `Back in your psql shell, verify that logical replication is now enabled:`
2. add the output that the user needs to see to the code block:
```
postgres=# show wal_level;
 wal_level
-----------
 logical
(1 row)
```

**Comment by morsapaes** [comment]
Fixed in #19453.
