### ISSUE TITLE
storage: backoff restarting SuspendAndRestart's

### ISSUE THREAD

**Issue by guswynn** [MaterializeInc/materialize#19944]
In https://github.com/MaterializeInc/materialize/pull/19890, I discovered we restart sources/sinks VERY Fast. We should have some amount of backoff

**Comment by benesch** [comment]
There's a 30s backoff: https://github.com/MaterializeInc/materialize/blob/38a4b30f9e35f8463421d7e9b4712ef02dbbf970/src/storage/src/healthcheck.rs#L37-L39. Not sure if that was present at the time you filed the issue or not, but either way it seems to work well enough!
