### ISSUE TITLE
miri: the main thread terminated without waiting for all remaining threads in mz-persist-client read::tests::seqno_leases

### ISSUE THREAD

**Issue by def-** [MaterializeInc/materialize#19983]
### What version of Materialize are you using?

b270344c4d4abe3abb3f334a8e9cf91fb66f72cd

### What is the issue?

```
--- STDERR:              mz-persist-client read::tests::seqno_leases ---
error: the main thread terminated without waiting for all remaining threads

note: pass `-Zmiri-ignore-leaks` to disable this check
```
I'm not sure if this is expected, will ignore it for now. Found as part of https://github.com/MaterializeInc/materialize/pull/19956

**Comment by sploiselle** [comment]
This issue is somewhat antique at this point; closing and and can reopen if this is something we come across again.
