### ISSUE TITLE
doc: Guide user to validate SSH tunnel and PrivateLink connections with VALIDATE CONNECTION

### ISSUE THREAD

**Issue by jseldess** [MaterializeInc/materialize#20007]
### Documentation request

When creating a connection with an SSH tunnel or PrivateLink, users can now run `VALIDATE CONNECTION` after `CREATE CONNECTION` to discover upstream networking issues before moving further down the flow. 

We need to update all SSH and PrivateLink guidance to encourage users to use `VALIDATE CONNECTION`. This will be in the source integration guides, the network security pages, and probably other create connection examples using SSH and PrivateLink.

For sources without an SSH tunnel or PrivateLink, we validate the connection automatically and return errors if something's off. 

### Related work

@benesch, @uce, can either of you please add links to the relevant epic and design doc, if any?

**Comment by benesch** [comment]
Tagging in @dseisun-materialize as this is storage team work!

I don't think there was a design doc written though, I'm afraid. Here's what I've got:

  * [Petros's implementation PR covering everything but SSH tunnel connections and AWS PrivateLink connection](https://github.com/MaterializeInc/materialize/pull/19487). The PR description is hopefully useful to docs.
  * [Slack conversation about the design](https://materializeinc.slack.com/archives/C02FWJ94HME/p1686657822658549). Possibly too in the weeds for your purposes.

**Comment by morsapaes** [comment]
Done in #20996.
