### ISSUE TITLE
[Inc 67] sinks: bootstrapping catalog does not wait for sink creation

### ISSUE THREAD

**Issue by sploiselle** [MaterializeInc/materialize#20019]
### What version of Materialize are you using?

main

### What is the issue?

Part of #17210

Bootstrapping the coordinator does not wait for sinks to be created, which leads to inconsistent state. While this is a problem generally, it specifically leads to a pathological panic if the storage controller attempts to reconnect to a running worker (known as reconciliation).

1. During bootstrapping, we [defer the work of building the connection](https://github.com/MaterializeInc/materialize/blob/52c1cac3cd37640e0a73cb7468b39111c50b9a6a/src/adapter/src/coord.rs#L1107-L1128), which has is an asynchronous process that we ostensibly do not want to hold up starting Materialize.
2. The coordinator notifies the storage controller that [initialization completed](https://github.com/MaterializeInc/materialize/blob/52c1cac3cd37640e0a73cb7468b39111c50b9a6a/src/adapter/src/coord.rs#LL1213C14-L1213C14), which [kicks off the process](https://github.com/MaterializeInc/materialize/blob/52c1cac3cd37640e0a73cb7468b39111c50b9a6a/src/storage-client/src/controller.rs#LL1217C20-L1217C20) of [reconciliation](https://github.com/MaterializeInc/materialize/blob/52c1cac3cd37640e0a73cb7468b39111c50b9a6a/src/storage/src/storage_state.rs#L972-L977) in the the individual worker's storage state.
	Important to note that from the perspective of the storage controller, we have only generated a source export token and the lower-level clients (e.g. the rehydrating storage client for the cluster where the sink runs) have absolutely no record of the sink's pending creation.
3. During reconciliation, the storage state assumes [all running exports are stale](https://github.com/MaterializeInc/materialize/blob/52c1cac3cd37640e0a73cb7468b39111c50b9a6a/src/storage/src/storage_state.rs#L986) and removes them from being marked as stale if it [sees a `CreateSinks` command with the ID](https://github.com/MaterializeInc/materialize/blob/52c1cac3cd37640e0a73cb7468b39111c50b9a6a/src/storage/src/storage_state.rs#L1072). In this case, reconciliation occurs while the sink's connection is still getting created, so we don't know that it shouldn't be reconciled away––and then reconcile it away.

This means we are almost certain to drop sinks running on existing workers.

## Misc. thoughts

I was very surprised to see that the sink code path does not rely on purification like sources do. My first inclination is that this code should pattern itself after sources and push down the problem of maintaining connection health into storage.

**Comment by sploiselle** [comment]
Yeah, I think we need to handle side-effects in purification more robustly. I have a bit of code here that sketches an approach but needs more deliberation.

https://github.com/MaterializeInc/materialize/pull/18601/files

Some of the other concerns here are things we handle in source creation with PG. For example, we check that we have permissions on the tables we want in purification––if it turns inti a toctou error, we just surface it in storage. All toctou errors are problems that could arise later on (at least in PG), so we already have code paths to handle them. Even if handling them is just wedging the source––but the status will report as such.

**Comment by benesch** [comment]
> FWIW, my understanding of the reasoning here is that creating the sink connection creates a topic, and it would be bad for purification to have side effects. (Imagine the command fails after purification; you'd have a new topic in your cluster, but nothing in your materialize instance that corresponded to it.)

That's exactly right. I dug up the Slack conversation where we discussed this a while back: https://materializeinc.slack.com/archives/C01CFKM1QRF/p1665168505993079!

The outcome of that conversation made it into my [Connection and source validation braindump](https://www.notion.so/materialize/Connection-and-source-validation-477045065ef1481d90d25e06dbeca4b6) but unfortunately never made it into a GitHub issue. So thank you very much for finally filing one, Sean!

Here are the two relevant bits of that doc:

<img width="744" alt="image" src="https://github.com/MaterializeInc/materialize/assets/882976/1c7d8e50-7571-420c-acc8-aa33ce125d4f">

<img width="774" alt="image" src="https://github.com/MaterializeInc/materialize/assets/882976/6b2679bf-fa9d-4374-8ae0-fa296cef1569">

The doc never actually got ratified, so not gospel, but I would be very, very nervous about a design that leaks external state during purification. Leaking a PostgreSQL replication slot is just such a disaster for the upstream database.

> Defer topic creation to after the whole sink-creation process; `clusterd` could be responsible for creating it somehow. The downside here is that it'd be pretty easy to create a sink that could never work... if eg. we didn't have permissions to create the topic.
> * We might be able to mitigate this somewhat by checking permissions via the admin API, but I don't know if that could be made perfectly reliable.

Exactly, and I think it's 100% fine if this is not perfectly reliable. I think we can easily get to 95%+ reliability over time. If the trade is between occasionally creating a sink that immediately wedges on topic creation or occasionally silently leaking a Kafka topic/PostgreSQL replication slot, I'd take the former every day of the week.

**Comment by benesch** [comment]
I should note that we do something similarly sketchy in the `drop_source` code path, where we try to drop the PostgreSQL replication slot for "a while" (30s) and then give up:

https://github.com/MaterializeInc/materialize/blob/30606f9e32d333b7007fc8892252fe3f74f41868/src/adapter/src/coord/ddl.rs#L419

Fixing this one's even harder, because we need the source to transition into a "dropping" state and then a "failed-to-drop" state. Both of these states should be loudly surfaced in the UI, so that users know when a source has leaked external state. At least we've got an issue for that one! https://github.com/MaterializeInc/materialize/issues/14551

The meta point here is that we've played it fast and loose in the past with external state, but no better time than the present to clean that up. I really want us to think of all external state operations as things that require a durable WAL (for creates, the existence of the catalog entry serves as the WAL entry to ensure the topic/replication slot exists). Processing a WAL entry is then something that can survive a Materialize crash, an external system crash, or a network misconfiguration. Failure to process a WAL entry is something that should be loudly surfaced to the user, as they'll likely need to perform manual remediation.

**Comment by aljoscha** [comment]
A naive thought: can't we fix this by making sure that we only tell the controller _initialization complete_ once all the connections/sinks have been re-built? (sorry if this has been mentioned elsewhere already) And then reconciliation will work correctly.

**Comment by benesch** [comment]
There's no guarantee that we'll _ever_ manage to rebuild a sink at the moment, though. For example if a Kafka cluster for a Kafka sink is no longer reachable. The only solution that really seems viable to me is to push topic/replication slot creation down into `clusterd`.

**Comment by aljoscha** [comment]
makes sense, yes!

**Comment by sploiselle** [comment]
@moulimukherjee and I will take this on. [I have some inline comments in a branch](https://github.com/sploiselle/materialize/tree/incident-50-waypoints) suggesting ways to fix this that I plan to aggregate into a design doc.

**Comment by benesch** [comment]
Those comments look spot on. Really excited for this!
