### ISSUE TITLE
storage: reconciliation on running workers leads to panics

### ISSUE THREAD

**Issue by sploiselle** [MaterializeInc/materialize#20020]
### What version of Materialize are you using?

main

### What is the issue?

Part of #17210

1. During reconciliation, we might decide to reconcile away (i.e. [drop](https://github.com/MaterializeInc/materialize/blob/52c1cac3cd37640e0a73cb7468b39111c50b9a6a/src/storage/src/storage_state.rs#L1108-L1115) some running dataflows that are no longer in the controller we're agreeing to work with.
2. We process these synthesized drop commands [just as we would any other command](https://github.com/MaterializeInc/materialize/blob/52c1cac3cd37640e0a73cb7468b39111c50b9a6a/src/storage/src/storage_state.rs#L1122-L1130), i.e. there is no special flag that these IDs are being dropped by reconciliation.
3. Whenever we receive an [`AllowCompaction` to the empty frontier](https://github.com/MaterializeInc/materialize/blob/52c1cac3cd37640e0a73cb7468b39111c50b9a6a/src/storage/src/storage_state.rs#L1268-L1287) (a drop), we [track it as a dropped ID](https://github.com/MaterializeInc/materialize/blob/52c1cac3cd37640e0a73cb7468b39111c50b9a6a/src/storage/src/storage_state.rs#L856).
4. We periodically [report our dropped IDs](https://github.com/MaterializeInc/materialize/blob/52c1cac3cd37640e0a73cb7468b39111c50b9a6a/src/storage/src/storage_state.rs#L521C22-L525) to the PartitionedState to which we're connected, at which time we've forgotten the provenance of the drop.
5. In the case of reconciliation, we explicitly and only drop IDs which the client driving us doesn't have. If we do see a command, the partitioned client [tracks the uppers](https://github.com/MaterializeInc/materialize/blob/52c1cac3cd37640e0a73cb7468b39111c50b9a6a/src/storage-client/src/client.rs#L541-L546).
6. When the worker sends back a response that it has dropped the IDs it reconciled away, [the PartitionedState has no record of the collection](https://github.com/MaterializeInc/materialize/blob/52c1cac3cd37640e0a73cb7468b39111c50b9a6a/src/storage-client/src/client.rs#L649-L656), leading to the panic.

## Why don't we hit this more often

It is a long-known issue that we do not properly emit `DroppedId` responses (#8185), so triggering this requires reconciliation on an active worker with an apparent catalog change in the move between epochs. I don't think that scenario is well tested, but the repeated occurrence of #17210 suggests it's not so rare.

## Misc.
- Fix seems easy but testing seems hard.
- This bug alerted us to the existence of #20019

**Comment by aljoscha** [comment]
It's good that `PartitionedState` has those checks, otherwise I'd have a feeling the bug can be slightly more insidious than that:
 - the workers return spurious `DroppedIds` messages on reconciliation
 - the controller goes ahead and drops state/finalizes things, thinking that these `DroppedIds` messages were originally caused by it (the controller) trying to drop things
