### ISSUE TITLE
Test out support for `target_feature=aes`

### ISSUE THREAD

**Issue by vmarcos** [MaterializeInc/materialize#20028]
We noticed in https://github.com/MaterializeInc/materialize/pull/19848#issuecomment-1593254846 that currently there are libraries, namely `AHash`,  which could make use of AES instructions, but do not. Since these instructions are widely supported in cloud ([Slack ref](https://materializeinc.slack.com/archives/CL68GT3AT/p1686933180465529)), this issue is a request to test enabling this target feature.

**Comment by tokenrove** [comment]
I can't imagine any cloud instance that wouldn't have AES-NI or its ARM equivalent.  All the Graviton processors are ARMv8 so they should have ARM's AES instructions, and AES-NI was introduced in Westmere (and has generally been omitted only in mobile processors), while every known instance type I could find (exporting data from https://instances.vantage.sh) is at least Sandy Bridge.

I think we should consider actually setting our target-cpu to the baseline for AWS cloud instances, being either `sandybridge` for x86-64, or `cortex-a72` for aarch64; we could just add `target-feature`s individually, but I suspect we'd want to add not just `aes` but also at least `popcnt`, `avx`, `sse4.2`, which setting the target-cpu appropriately would do for us.  (Aside from within our own code, we have at least one dependency, crc32c, that would be accelerated significantly by turning on SSE4.2, as well as the crc32c code within rocksdb, which is reason to cover both Rust and C compiler flags.)

I'm happy to work on this by the way.

**Comment by teskje** [comment]
AES support was enabled as part of #22187.
