### ISSUE TITLE
Adding `NULL` to a timestamp results in an `internal error`

### ISSUE THREAD

**Issue by sthm** [MaterializeInc/materialize#20077]
### What version of Materialize are you using?

v0.57.8 (1f8d4427a)

### What is the issue?

Doing timestamp arithmetic with `NULL` values results in an internal error.

```
staging > SELECT now() + null;
ERROR:  internal error: column 0 is not of expected type ColumnType { scalar_type: TimestampTz, nullable: false }: Null
```

I would have expected that the expression evaluates to `NULL`. According to Nikhil, this seems like a bug in the optimizer/our type determination code.

ci-regexp: is not of expected type ColumnType

**Comment by ggevay** [comment]
Fixed by https://github.com/MaterializeInc/materialize/pull/20081
