### ISSUE TITLE
storage: StorageState's ingestions + exports retained, exports partially freed possibly multiple times

### ISSUE THREAD

**Issue by sploiselle** [MaterializeInc/materialize#20084]
### What version of Materialize are you using?

v0.57.8

## Storage State ingestions + exports always retained

Neither I nor Rust Analyzer can find anywhere in `storage_state.rs` that calls `storage_state.exports.remove(id)` or `storage_state.ingestions.remove(id)`. I believe these structs are retained for the lifetime of the worker.

## Exports' state partially freed

When a storage worker receives an `AllowCompaction` command for a sink, if the compacted-to frontier is `[]`, it [removes the sink handle from its memory](https://github.com/MaterializeInc/materialize/blob/ab8ec8fd4ef869d394a14d2a1dead6303c425366/src/storage/src/storage_state.rs#L1272-L1285) and panicking if it doesn't exist.

When a running storage worker reconciles itself with a new storage controller (i.e. reconciliation), it looks at all of its running exports and marks them all as stale. If it doesn't see a corresponding `CREATE` command, it synthesizes an `AllowCompaction` command to `[]`. Following from the fact above, that will result in removing the sink handle from memory (or panicking if it doesn't exist).

So this series of events means that workers that have dropped sinks will _always_ panic during reconciliation.

1. Controller_0 tells Worker to drop sink.
2. Worker executes command, removing sink handle but retaining export state.
3. Controller_1 replaces Controller_0 at some point in the future.
4. Worker reconciles itself with Controller_1.
    1. Worker has the state of all sinks it's ever maintained, marking them all as stale.
    2. Controller_1 has no record of the sink, which was dropped from its predecessor's catalog.
    3. Worker synthesizes an `AllowCompaction` command to `[]` for the sink.
    4. When executing the `AllowCompaction` command, Worker panics because it cannot find the sink handle it dropped in the previous epoch.

**Comment by aljoscha** [comment]
I don't remember a reason for keeping those around. Might just be an oversight or it got lost in refactorings.
