### ISSUE TITLE
Can we get rid of the simple-demo / other really old READMEs or demos

### ISSUE THREAD

**Issue by ruchirK** [MaterializeInc/materialize#2008]
A lot of developers will go to the github home page and directly navigate to demo/simple because it seems like the fastest path to see it in action -- once there they will find something both out of date and not terribly compelling like

```
197 - Materialize cannot currently order the results of the materialized view. This
198   is a known limitation and will be fixed in a future build.
199 - Materialize requires that the load generator perform some updates on the
200   `region` and `user` table after the source has been created so that it picks
201   up that all of these records exist. This is a known limitation and will be
202   fixed in a future build.
```

i think we have plenty of other demos and can scrap this one?

**Comment by benesch** [comment]
I like the simple demo, personally! It's much less code than any of the other demos. Seems like it could just use an update to remove the out of date limitations?

**Comment by rjnn** [comment]
I'd rather take it down and then reinstate it when it's good to go, instead of leaving in something obsolete and straight up wrong as a bad first impression.

**Comment by benesch** [comment]
It didn't take long to fix. See #2012.

**Comment by rjnn** [comment]
Wow, ok! Thank you!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
