### ISSUE TITLE
storage/connections/aws-privatelink: duplicate AZs erroneously allowed

### ISSUE THREAD

**Issue by jubrad** [MaterializeInc/materialize#20128]
### What version of Materialize are you using?

v0.56.0

### What is the issue?

Sentry reports issues reconciling vpc endpoints. This seems to occur every reconciliation of a particular private link connection. On inspection of that k8s resources it appears that it has duplicate AZs. The VpcEndpointController will be fixed to ignore duplicate AZs, but we should also be validating the SQL command to ensure AZ uniqueness. 

This is a snippet of the spec for the resource. It's also notable that this resource is on generation 1, implying that this was likely not caused by an update of the resource. It's probably worth fishing for some logs, if they exist, to validate this was actually entered erroneously and not a bug in our system that duplicated on create or a modification. 

```
Spec:
  Availability Zone Ids:
    use-az2
    use-az6
    use-az6
    use-az2
```

https://materializeinc.sentry.io/issues/3687813529/events/db7ba88cb1a94b7591d92cc9c9bab1ba/?project=5697415

**Comment by jubrad** [comment]
@chaas tagging you here for tracking.

**Comment by benesch** [comment]
Thanks @jubrad!

Linking in Slack conversation about how to fix/test this: https://materializeinc.slack.com/archives/CL68GT3AT/p1687553057499989?thread_ts=1687552924.672459&cid=CL68GT3AT

**Comment by morsapaes** [comment]
@jubrad @benesch: is this still relevant?

**Comment by morsapaes** [comment]
Done.

**Comment by jubrad** [comment]
Yeah, that PR is still open, but on the cloud side we've resolve this by de-duping the az list. In practice this isn't going to cause any failures now, but we really should return an error rather when duplicate AZs are used.

**Comment by benesch** [comment]
Fixed by https://github.com/MaterializeInc/materialize/pull/20134#pullrequestreview-2059442716.
