### ISSUE TITLE
Slim down runtimes for CI

### ISSUE THREAD

**Issue by def-** [MaterializeInc/materialize#20132]
### Feature request

Especially for releases.

We could do:

1. push the docker images in parallel
2. Build all binaries in one cargo run command
3. Increase max. number of agents, sometimes spends a few minutes waiting
4. Checks + restart of the entire Mz is pretty slow in normal CI, maybe move to nightly
5. Split up miri test into two parts (or move slow part to nightly)

**Comment by benesch** [comment]
Thanks for cataloguing all of these, @def-!

Just want to call out that (1) and (2) will be somewhat tricky to accomplish given how mzbuild.py is currently structured. Certainly they are doable changes, but I'm not seeing a path that's not a fair bit of refactor. Please CC me on that review—also happy to try to find some time to brainstorm about approaches.

**Comment by def-** [comment]
Some more ideas for build times: https://endler.dev/2020/rust-compile-times/
https://github.com/Swatinem/rust-cache/
https://www.lpalmieri.com/posts/fast-rust-docker-builds/

**Comment by def-** [comment]
I'm not sure how to do (2), the rest are done, some still unmerged.

**Comment by guswynn** [comment]
We can probably still move miri tests to nightly, we very rarely write unsafe code that needs to be checked by miri!

**Comment by benesch** [comment]
> We can probably still move miri tests to nightly, we very rarely write unsafe code that needs to be checked by miri!

But when we do, it is absolutely essential to run that code through miri. Would strongly prefer that buggy unsafe code never make it main.
