### ISSUE TITLE
Warn on unfixable errors in `--auto-index-selects` option of `sqllogictest`

### ISSUE THREAD

**Issue by vmarcos** [MaterializeInc/materialize#20146]
### Feature request

As observed in https://github.com/MaterializeInc/materialize/pull/19780#issuecomment-1601039619, there are some cases where employing `--auto-index-selects` in `sqllogictest` leads to an inconsistent view outcome, but where the reason is fundamentally unfixable due to semantic differences in the ways one-shot `SELECT`s and indexed views are processed in Materialize. For example:

1. A one-shot `SELECT` may include an unmaterializable function, but these functions are forbidden in indexed views.
2. Wildcard expansions or NATURAL JOINs are not allowed in a view that depends on system objects.
3. There are limitations regarding the use of `AS OF`.
4. A one-shot `SELECT` can be issued inside of a transaction, but performing the corresponding DDL for creating the indexed view will make the transaction abort.

We could extend the `--auto-index-selects` option in `sqllogictest` to account for these unfixable errors and remain silent when they occur. There is a trade-off, however, since then these classes of differences between indexed views and one-off `SELECT`s would become invisible in runs with the `--auto-index-selects` option, which can be error prone. The most concerning case is with the use of transactions, since silently ignoring `SELECT`s that would otherwise be valid for indexed views because they are in a transactional context could be confusing.

To increase observability of the runs with the `--auto-index-selects` option but still avoid unwanted errors, we could potentially introduce a warning outcome in `sqllogictest`. That outcome would be part of the final report, but not fail the run of the SLT.

**Comment by nrainer-materialize** [comment]
Is the number of cases manageable? Would it be an option to annotate statements that cannot be processed with a certain evaluation strategy?
For example, our platform checks allow running statements conditionally based on the version: `>[version>=5500] SELECT 1;` (https://github.com/MaterializeInc/materialize/pull/19217/files#diff-0e75185705f0683fc07a43771efee7c26becb34e9b7d5e82db62e29619f9d284)

**Comment by vmarcos** [comment]
> Is the number of cases manageable? Would it be an option to annotate statements that cannot be processed with a certain evaluation strategy? For example, our platform checks allow running statements conditionally based on the version:
> 
> ```
> >[version>=5500] SELECT 1;
> ```
> 
> (https://github.com/MaterializeInc/materialize/pull/19217/files#diff-0e75185705f0683fc07a43771efee7c26becb34e9b7d5e82db62e29619f9d284)

This is an interesting idea once we get the number of statement failures down by an initial filtering of the most common classes of errors. From a [recent output of the slow SLTs](https://buildkite.com/materialize/sql-logic-tests/builds/5599#01893f92-845a-4684-935a-61dfe89cef7a), I would estimate several hundreds of statements could be affected, and we are not even running all SLTs yet with `--auto-index-selects`. If we can transform a large number of these errors into warnings, then we can think of introducing an annotation like `[no-indexed-view]` to catch the remaining trickier cases.
