### ISSUE TITLE
Measure memory regressions in feature benchmark

### ISSUE THREAD

**Issue by vmarcos** [MaterializeInc/materialize#20151]
### Feature request

As observed recently in https://github.com/MaterializeInc/materialize/issues/20125, significant memory regressions can go undetected by our testing / validation infrastructure. While in the medium term investments such as the ones advocated for in #9157 and #16112 would be ideal, a short-term measure could be to investigate if we can extend the feature benchmark to meaningfully detect a class of memory regressions in nightly and PRs, just as it is used to detect query processing time regressions.

A possibility here is to follow a similar strategy as for the `--auto-index-selects` feature of `sqllogictest` (https://github.com/MaterializeInc/materialize/pull/19780): For a subset of the scenarios evaluated by the feature benchmark, we could not only execute a `SELECT` statement, but also make the relevant statement into an indexed view and then observe if there are differences in memory usage between the two compared alternatives.

The memory usage could be estimated by querying `mz_internal.mz_arrangement_sizes` as well as by directly looking at the reported usage by allocator metrics in the `metrics` endpoint of `clusterd`. Note that it is important to observe the memory usage only after the dataflow stabilizes. For example, if the source data comes from a table and transits through a materialized view, as is often the case in the feature benchmark, we'd like, e.g., to see `EXPLAIN TIMESTAMP` for the `SELECT` on the indexed view return `can respond immediately: true` in `strict serializable` mode _before_ looking at the memory usage.

**Comment by philip-stoev** [comment]
@vmarcos this has now been pushed. Some distinctions from your specification:
- the memory consumption as observed by docker for the entire Mz container (exclusing CRDB and Minio) is being measured. I believe this is the best metric as it is the one that is closest to what is will be used to actviate the OOM killer in K8s production. This will allow memory leaks in non-dataflow and non-clusterd parts of the code to be detected as well. For example, https://materializeinc.slack.com/archives/C01CFKM1QRF/p1688132019011439
- the memory measurement is taken after the dataflow is completely hydrated , but before jemalloc has had the chance to return any unused memory to the system. So we are essentially measuring something between truly-peak memory usage (which may happen in the middle of some dataflow hydration) and the consumption of a steady-state, idle workflow.
- the feature benchmark has been extended with more permanent dataflows, even though it seems that even one-off dataflows can be used to detect memory consumption regressions.

**Comment by vmarcos** [comment]
Thanks, @philip-stoev! I think that since we run several repetitions in the feature benchmark, measuring container-level memory should be reliable enough. Regarding the more permanent dataflows, with the work on monotonic one-shot `SELECT`s, we should keep in mind to add over time dataflows that use min/max/top-k patterns. Once we use the monotonic variants for one-shot `SELECT`s, memory requirements will be pretty different between the one-shot and incrementally maintained versions.
