### ISSUE TITLE
A few of the top level links in the API documentation 404

### ISSUE THREAD

**Issue by ruchirK** [MaterializeInc/materialize#2015]
e.g. https://mtrlz.dev/api/dataflow-bin/index.html

billing-demo is especially bad because the textual description for it is "null" I'll throw up a pr to fix billing-demo asap

**Comment by ruchirK** [comment]
@sploiselle this issue was about API docs over at mtrlz.dev/api -- I think you meant to close https://github.com/MaterializeInc/materialize/issues/1635 instead (for broken links in the user docs). I'm going to reopen this for now because it looks like the fuzz and dataflow-bin crates still cause a 404 on the api doc toplevel

**Comment by sploiselle** [comment]
Derp! Mixed up the two issues related to broken links.
