### ISSUE TITLE
Increased memory usage test with repro

### ISSUE THREAD

**Issue by def-** [MaterializeInc/materialize#20154]
### Feature request

Add a release qualification test with Brennan's repro for incident 55 that looks for increased memory usage

**Comment by benesch** [comment]
Related: https://github.com/MaterializeInc/materialize/issues/20151.

**Comment by philip-stoev** [comment]
Implemented as part of https://github.com/philip-stoev/materialize/commit/fe42d742bec3cc9697c7783f750b27840618bec4  . The customer's workload is in the CI and the feature benchmark framework has been extended to detect memory usage regressions.
