### ISSUE TITLE
doc: Quickstart doesn't spell out the value prop

### ISSUE THREAD

**Issue by jseldess** [MaterializeInc/materialize#20161]
### Documentation request

Feedback from @frankmcsherry:

> We just had a call with an onboardee who bailed without having created any indexes, materialized views, etc., seemingly on account of they did not know what the value proposition of MZ was meant to be (or that these were the intended moments). Checking the doc, it seems like it could plausibly spell out the why of the quickstart a bit more. Right now it says e.g. "connect a streaming source" and "compute real-time results with indexes and materialized views", which aren't wrong but don't (to me) speak to why you'd to do this.

### Affected Pages

https://materialize.com/docs/get-started/quickstart/

**Comment by morsapaes** [comment]
No longer relevant, since we completely rehauled the quickstart.
