### ISSUE TITLE
On DROP ... CASCADE, add notice with list of all deleted objects

### ISSUE THREAD

**Issue by chaas** [MaterializeInc/materialize#20166]
### Feature request

Mirror this behavior by postgres, which print out the list of objects that a cascade is deleting as a notice.
```
postgres=> drop table t cascade;
NOTICE:  drop cascades to function f(t)
DROP TABLE
```

From @jkosh44 

> I don't think it would be very hard. We track all the objects we are going to drop and we know which ones were referenced directly and which ones are are being dropped due to a CASCADE.
> https://github.com/MaterializeInc/materialize/blob/0b6c779e81cc3a7fe6268cee6ad16fbb611e5fe8/src/sql/src/plan.rs#L629-L634

**Comment by friendlymatthew** [comment]
Hi @chaas, I have a draft PR up for this issue. I'm currently working on a different issue at the moment, so I'll focus on that first. But once that gets resolved, I'd love to work on this issue 🤠
