### ISSUE TITLE
doc: Quickstart could elide CLUSTER configuration

### ISSUE THREAD

**Issue by frankmcsherry** [MaterializeInc/materialize#20164]
### Documentation request

The quickstart documentation works through cluster creation, creating both a storage and compute cluster. This isn't strictly necessary, as creating a load generator source creates its own cluster (`materialize_public_auction_house` for me) when not specified; dropping the load generator source drops the cluster.

Cluster configuration may be a valuable topic to work through, but I could also imagine a "quicker" quick start that gets to "live updated views" faster / with fewer steps that may distract. In particular, we've had a few moments where we would like the fastest possible path to revealing the value proposition of MZ.

### Affected Pages

https://materialize.com/docs/get-started/quickstart/

**Comment by chuck-alt-delete** [comment]
This will be a good way to go after we’re able to run sources and sinks alongside compute dataflows. We’ve seen confusion in the field with users creating sources with linked clusters when they should be grouping sources into a single source cluster. The current flow more accurately resembles how field engineering guides users to onboard their own use cases.

**Comment by chuck-alt-delete** [comment]
This is shipped!
