### ISSUE TITLE
Re-enable memory tracking per arrangement

### ISSUE THREAD

**Issue by umanwizard** [MaterializeInc/materialize#20185]
### Feature request

The memory tracking per arrangement was reverted due to https://github.com/MaterializeInc/materialize/issues/20125 (further explained in [this gist](https://gist.github.com/umanwizard/ee692e7e9e27e9e53ba1e781b20a952b)).

We would like to re-add this feature after we fix the issues with it, since it is very useful for customers and FE.

**Comment by ggnall** [comment]
When this is fixed, we should also update the Console display to add raw sizes (e.g. GB, in addition to %s), since that's a convention users expect. cc @RobinClowers

**Comment by antiguru** [comment]
Arrangement size logging is enabled in production. See https://app.launchdarkly.com/default/production/features/enable_arrangement_size_logging/history/64dceb1243bb6d13d88f57bc/details/diff.
