### ISSUE TITLE
testing: test reconciliation of running workers, esp. sinks

### ISSUE THREAD

**Issue by sploiselle** [MaterializeInc/materialize#20181]
### Feature request

We recently hit a spate of issues around reconciliation involving sinks:

https://github.com/MaterializeInc/materialize/issues/20084
https://github.com/MaterializeInc/materialize/issues/20020
https://github.com/MaterializeInc/materialize/issues/20019

The QA team did a coverage check and discovered some crucial lines of code are not being exercised.

![Screenshot 2023-06-22 at 15 59 05](https://github.com/MaterializeInc/materialize/assets/19260003/cba82e24-de4e-4123-bee9-80e5f3d2f421)

`test/cluster`, specifically `test_remote_storage` is a place that we can flesh out more of these tests.

Adding @philip-stoev in case his team has bandwidth to write these tests before I get to it.

**Comment by sploiselle** [comment]
@def- Could you run a coverage test on `main` now and ensure this was fixed? I believe it needs to run some portion of `zippy` up to 400 some-odd actions to hit the code path for certain.

**Comment by def-** [comment]
<img width="805" alt="Screenshot 2023-10-25 at 15 05 34" src="https://github.com/MaterializeInc/materialize/assets/2335377/be802704-b650-41f4-b1fd-afbc8d0cccc7">
Sure, looks good now: https://buildkite.com/materialize/coverage/builds/287#018b6649-962a-4706-96e5-716d3735ae9f

**Comment by sploiselle** [comment]
ty @def-
