### ISSUE TITLE
Improve documentation for expected group size hint

### ISSUE THREAD

**Issue by uce** [MaterializeInc/materialize#20184]
### Documentation request

Our documentation on the expected group size query hint is pretty sparse currently. We should provide more context on when this is a useful hint, what trade-offs are involved, and how to pick a number for the hint.

This request is best handled by the compute team directly rather than the docs team.

#### Query

(From https://github.com/MaterializeInc/materialize/issues/20457)

In an [internal exchange](https://materializeinc.slack.com/archives/C02PPB50ZHS/p1689018644351249), it was observed that we can often provide some degree of guidance on how to set the `EXPECTED GROUP SIZE` hint controlling the height of the stacks of arrangements created for incremental maintenance of min/max/top-k patterns.

This issue is a request to prototype an introspection query that will provide such guidance for the presently installed indexed and materialized views. One strategy is for each stack of arrangements, look for the "funneling" stage, i.e., a stage above which data are either not reduced at all or not significantly reduced. This strategy has the caveat that it looks at aggregate values and not the maximum group size, as would be ideal. However, it can be the basis for some automatic advice that would then be verified by human intervention.

Note that a given indexed/materialized view may contain multiple stacks of arrangements for different patterns in the query. Each such stack needs to be evaluated independently, so the advice output should for each dataflow, report a set of `EXPECTED GROUP SIZE` recommendations, one for each min/max/top-k region in the dataflow.

For testing, a set of indexed or materialized views can be created, e.g., by utilizing the TPC-H load generator. This suffers from the issue of employing uniform data distributions, but it should be sufficient to validate the basic strategy outlined above. The views should vary `GROUP BY` attributes so that many different values of the tuning parameter would be ideal for the variations.

### Affected Pages

https://materialize.com/docs/sql/select/#query-hints

### Related work

* [Slack](https://materializeinc.slack.com/archives/C02PPB50ZHS/p1687862343342089)

**Comment by ggevay** [comment]
Some things that should be mentioned/explained off the top of my head:
- The effect of giving the hint: reduced memory usage.
- What happens if the given hint is wrong:
  - If it's too small, then extra CPU usage / latency.
  - If it's too big, then more memory than ideal (but probably still less than without the hint).
- The word "expected" doesn't mean avg here! We want the size of the largest group.
- (We can consider talking about looking at the introspection to inspect the sequence of arrangement sizes in each stage, but this might require explaining way too many things, and would make this more scary than it has to be.)

**Comment by vmarcos** [comment]
In conversation with @uce: The documentation page on [Optimization](https://materialize.com/docs/transform-data/optimization/) could be a good candidate place for writing about how to improve queries with min/max/top-k patterns by setting the `EXPECTED GROUP SIZE` hint. It could explain things from first principles, and then have a link to an extended page with the query for automatic detection of tuning opportunities for this query hint.
