### ISSUE TITLE
Managed cluster with a huge replication factor not rejected immediately, causes 100% CRDB CPU usage  

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#20195]
### What version of Materialize are you using?

5a96695985ec0613459321fa24d57c61e9b1f206

### What is the issue?

@jkosh44 This is a follow-up from one of the issues raised in the "Managed Clusters" PR. 

This statement:

```
CREATE CLUSTER foo SIZE '1', replication factor 99999;
```

Should fail immediately with a `ERROR:  creating cluster replica would violate max_replicas_per_cluster limit` error. Instead, it causes a prolonged 100% CRDB usage until it fails eventually with the expected message.

I suspect the `max_replicas_per_cluster` check is misplaced in the code as it should trigger and fail immediately without a delay. Maybe the check is performed for every replica, rather than just once for the entire `CREATE CLUSTER` statement?  

This has the potential to (D)DoS our CRDB instance as any trial user could run the statement in question.

**Comment by philip-stoev** [comment]
@antiguru FYI.

**Comment by benesch** [comment]
Filing as a release blocker just to ensure we don't forget to merge the fix (#20236) before the release.
