### ISSUE TITLE
Document bootstrap views

### ISSUE THREAD

**Issue by sploiselle** [MaterializeInc/materialize#2020]
Need to document the default views that we create that provide stats about your Materialize cluster.

**Comment by rjnn** [comment]
Ping - do you have a timeline estimate for this?

**Comment by sploiselle** [comment]
Didn't realize this was put on the 0.2 milestone; can get it finished by next week.

**Comment by rjnn** [comment]
I'm fine with bumping the milestone to 0.3 and taking it at a more leisurely pace - there isn't anything pressing driving the milestone here.

**Comment by morsapaes** [comment]
Fixed in #4497 (let me know if I'm reading wrong into it, @sploiselle)!
