### ISSUE TITLE
AssertionError: more dataflows than expected in replica history

### ISSUE THREAD

**Issue by def-** [MaterializeInc/materialize#20242]
### What version of Materialize are you using?

a4710805d5

### What is the issue?

Seen in https://buildkite.com/materialize/tests/builds/58589#018906a3-10fc-4f8f-8bee-540cdb88a1dc
```
mzcompose: test case test-github-15531 failed:
Traceback (most recent call last):
  File "/var/lib/buildkite-agent/builds/buildkite-15f2293-i-0c926df81a9c49462-1/materialize/tests/misc/python/materialize/mzcompose/__init__.py", line 416, in test_case
    yield
  File "/var/lib/buildkite-agent/builds/buildkite-15f2293-i-0c926df81a9c49462-1/materialize/tests/test/cluster/mzcompose.py", line 82, in workflow_default
    c.workflow(name)
  File "/var/lib/buildkite-agent/builds/buildkite-15f2293-i-0c926df81a9c49462-1/materialize/tests/misc/python/materialize/mzcompose/__init__.py", line 332, in workflow
    func(self)
  File "/var/lib/buildkite-agent/builds/buildkite-15f2293-i-0c926df81a9c49462-1/materialize/tests/test/cluster/mzcompose.py", line 384, in workflow_test_github_15531
    assert (
AssertionError: more dataflows than expected in replica history
```
I can reproduce it locally via `while true; do bin/mzcompose --find cluster down && bin/mzcompose --find cluster run test-github-15531 || break; done`, took ~40 minutes. It's probably too difficult to bisect this since it's pretty flaky, but I'll try.

**Comment by def-** [comment]
The bisect led me to this, which seems plausible and makes this a regression:
```
aa454e828a3e967b4bfb1e44bf12fe4d825fe800 is the first bad commit
commit aa454e828a3e967b4bfb1e44bf12fe4d825fe800
Merge: 52c1cac3cd df487a1131
Author: Jan Teske <jteske@posteo.net>
Date:   Sat Jun 17 09:09:17 2023 +0200

    Merge pull request #19964 from teskje/compute-history-metrics

 doc/developer/design/20230531_compute_metrics.md |  34 +++----
 src/compute-client/src/controller/instance.rs    |   6 +-
 src/compute-client/src/lib.rs                    |   3 +-
 src/compute-client/src/metrics.rs                | 104 ++++++++++++++++++++--
 src/compute-client/src/protocol/history.rs       | 104 +++++++++++++---------
 src/compute/src/compute_state.rs                 |  15 +---
 src/compute/src/metrics.rs                       |  34 +++++--
 src/compute/src/server.rs                        |  18 ++--
 test/cluster/mzcompose.py                        | 107 +++++++++++++++--------
 9 files changed, 291 insertions(+), 134 deletions(-)
```

**Comment by vmarcos** [comment]
It makes sense that this PR is responsible for making the test flake. It changes the code that updates the dataflow count metric in a way that exposes intermediate states while running a `push` operation on the history visible. The previous code would only update the metric after the `push` was entirely completed. It is not wrong to expose this more fine-grained data as the command history is mutating, but it does make it reasoning about the visible states from the test a bit trickier.

**Comment by teskje** [comment]
While https://github.com/MaterializeInc/materialize/pull/20251 fixes the flaky test (thanks @vmarcos!), I think there is another issue with the new way of counting commands that we need to fix. Namely, `ComputeCommandHistory::reduce` works by first resetting the command count metrics and then counting them up as new commands are pushed. This creates a period of time where the metrics make it look like the history contains zero command (or less than the final reduced count), which is definitely wrong. We should change this so that the metrics don't expose transient counts and are only updated at the end of each `pub` method invocation.
