### ISSUE TITLE
Autoroute queries that don't reference any relation to mz_introspection

### ISSUE THREAD

**Issue by sjwiesman** [MaterializeInc/materialize#20247]
### Feature request

Materialize already supports auto routing queries that only reference system catalog relations to the mz_introspection cluster. This issue asks to expand that to also include queries that don't include any relation such as `SELECT 0` or `SELECT now()`. 

Today these queries require an active compute cluster to execute. These queries are prevalent in the `dbt-core` codebase as health checks. The trouble is they are not set in places that are overridable by out dbt adapter and it means the adapter breaks if a user drops the default cluster or set the cluster in their profiles.yml to a source cluster.

**Comment by morsapaes** [comment]
This would fix #19318.

**Comment by jkosh44** [comment]
One potential issue with this is that an expensive function can bring down `mz_introspection`. For example if someone runs something like `SELECT * FROM generate_series(0, 100000000000000000000000)`, that would put a lot of strain on `mz_introspection`.

This issue actually already exists (https://github.com/MaterializeInc/materialize/issues/19413), for example on a query like `SELECT * FROM mz_views, generate_series(0, 100000000000000000000000)`. However, It's probably still worth thinking about here.

**Comment by sjwiesman** [comment]
@jkosh44 would it be feasible to limit it to queries without functions. I believe dbt only actually issues `SELECT 0` and `SELECT 1 as id`. I may have been over zealous with writing `SELECT now()`.

**Comment by jkosh44** [comment]
> @jkosh44 would it be feasible to limit it to queries without functions.

Yeah that would be feasible.

> Though I do wonder how often something like `SELECT * FROM generate_series(0, 100000000000000000000000)` actually happens outside a malicious actor.

I'm using `generate_series(0, 100000000000000000000000)` as a placeholder here, but really the issue exists with any sufficiently expensive function/query. It's probably not that likely, but I'm worried about scenarios like the following:
- Someone wants to do some experimenting so they switch to a dev cluster assuming that it will isolate them from negatively affecting any other cluster.
- The run some query that references no relation but ends up being expensive. Maybe they had a copy-paste/fat-finger error and ran `generate_series` with an extremely large number. Maybe they were playing around with WMR queries. etc.
- Their query silently is auto-routed to `mz_introspection` and causes excessive load on that cluster.


It's also probably worth noting that small constant queries like `SELECT 0` and `SELECT now()` do not require a cluster to evaluate. They are fully evaluated in `environmentd` without any communication with a cluster. We just require a valid active cluster for all queries without actually checking if a cluster is used. So even if these queries start auto-routing to `mz_introspection`, nothing will actually change about their evaluation. Perhaps a different approach is that we should not requires a valid active cluster for queries that will not need a cluster. Some drawbacks with this approach are:
- It's opaque to the client which queries will need a cluster and which will not.
- If the logic for when a query is evaluated on a cluster changes, then it will potentially break some user flows.

**Comment by benesch** [comment]
> > @jkosh44 would it be feasible to limit it to queries without functions.
> 
> Yeah that would be feasible.

This sounds like the way to go for now. A query that references no functions or relations is certain to be basically free to execute. If we "auto route" that to the `mz_introspection` cluster (really it will just get executed in `environmentd`, as previously mentioned), that will unblock the dbt adapter without being unnecessarily constraining.

As @jkosh44 mentions it's somewhat scary to use the optimizer or the "cost" of a particular function to determine whether to route a query to `mz_introspection` or not, as the optimizer/our notion of cost will evolve frequently. Whereas a query that references neither a function nor a relation is guaranteed to be cheap forever.

**Comment by mjibson** [comment]
From a meeting: we can do this for queries with no functions, references, or operators. We can probably also do it for unmaterializable functions because those already only get executed in envd (this might need a small bit more thought to make sure it's right).
