### ISSUE TITLE
Materialize does not notice if a `clusterd` process dies without TCP reset

### ISSUE THREAD

**Issue by benesch** [MaterializeInc/materialize#20299]
### What version of Materialize are you using?

v0.58

### What is the issue?

Observed in [incident 58](https://github.com/MaterializeInc/cloud/issues/6817). A node failed and stopped responding to all network requests. An `environmentd` pod connected to a storage `clusterd` on the failed node did not notice that the storage cluster had gone away. When the storage cluster was rescheduled on a healthy node, `environmentd` did not attempt to reconnect, because it did not realize the original `clusterd` had failed. I believe this is because in regular operation `environmentd` does not send any commands to a storage `clusterd` (possibly also a compute `clusterd`), so it can go arbitrarily long without realizing that a `clusterd` has gone away.

We should write a test that demonstrates that this is a problem. Will probably require some complicated toxiproxy shenanigans to simulate a the kind of failure that doesn't involve sending an RST back to `environmentd`.

I think the fix for the issue is simple: having `environmentd` configure a relatively short TCP keepalive on the connection.

**Comment by uce** [comment]
On the QA side, @def- will look into writing a test that  surfaces the problematic behavior.

**Comment by benesch** [comment]
I think this is both a compute issue and a storage issue! At least, those are the two teams that actually own the TCP connection(s) between `environmentd` and `clusterd`.

**Comment by philip-stoev** [comment]
@pH14 the test was pushed already prematurely as part of https://github.com/def-/materialize/commit/fc2fefdb013e522d826566389d4138c722c69b49

as `test-clusterd-death-detection` in `test/cloud/mzcompose.py`. Please enable it once you have a fix.

**Comment by pH14** [comment]
@philip-stoev observed some concerning behavior in the release that rolled out this change. @teskje and I have been looking, but so far it's inconclusive what's happening, or if it's even keep-alive related. But, it is concerning enough where we've lifted the keep-alive knobs so high as to be effectively off.

What we saw: the sandbox env kept on cycling its connection between `envd`<->`clusterd` for one replica. The h2 and tonic trace logs showed that `clusterd` was dropping its stream and sending a `Reset, Err=Cancel` message to `envd`: https://gist.github.com/pH14/953d6e302473bdff199d2642c5938ce0

In particular:

```
{"timestamp":"2023-08-09T16:46:21.880781Z","level":"TRACE","fields":{"message":"pop_frame; frame=Reset { stream_id: StreamId(1), error_code: CANCEL }"},"target":"h2::proto::streams::prioritize","span":{"stream.id":"StreamId(1)","stream.state":"State { inner: Closed(ScheduledLibraryReset(CANCEL)) }","name":"popped"},"spans":[{"name":"server_handshake"},{"peer":"Server","name":"Connection"},{"name":"poll"},{"name":"pop_frame"},{"stream.id":"StreamId(1)","stream.state":"State { inner: Closed(ScheduledLibraryReset(CANCEL)) }","name":"popped"}]}
```

It's not clear what was causing this. `envd` would observe this, hit the error `error reading a body from connection: stream error received: stream no longer needed` and then reconnect, only to hit this again after ~70-90s had passed.

We tried restarting `clusterd` but this had no effect. We restarted `environmentd` and this fixed the issue, even though the keep-alive flags were kept the same. We also did not see any issues with the storage connection between the two processes.

**Comment by pH14** [comment]
TODO:
- [ ] It would have been wiser to make the GRPC system var knows `Option<Duration>` so we can fully disable the feature. This should be backwards compatible, but it'd be good to double check everything
- [ ] Lower the keep-alive values on prod back to being something useful. We can continue to monitor staging to build confidence here

**Comment by guswynn** [comment]
@teskje yes! https://github.com/MaterializeInc/materialize/issues/23869 tracks the final persist grpc connections that need to configurablr
