### ISSUE TITLE
pg sources: source restarts PG process when inert

### ISSUE THREAD

**Issue by sploiselle** [MaterializeInc/materialize#20295]
### What version of Materialize are you using?

8e1d5a825149ee1837b7aef77355f870a0bc9904

### What is the issue?

Materialize relies on the PG function `pg_logical_slot_peek_binary_changes` to inspect the state of its replication slot, primarily to assess if there is replication lag and if the slot's `write`/`flush`/`apply_lsn`s can/should be forwarded.

Calling this function ~10 times causes the PG process to restart. Unfortunately, this is not "10 successive times," or "10 times in an hour," but just 10 times since the last time the server cleared an internal cache (which I am only sure happens on connection). After some number of calls, the PG server encounters a fatal error:

> `“out of relcache_callback_list slots`

The issue is discussed [here](https://www.postgresql.org/message-id/OSZPR01MB631004A78D743D68921FFAD3FDA79%40OSZPR01MB6310.jpnprd01.prod.outlook.com) and has been resolved in PG [15.3](https://www.postgresql.org/docs/current/release-15-3.html):

 > Avoid leaking cache callback slots in the pgoutput logical decoding plugin (Shi Yu)
> 
> Multiple cycles of starting up and shutting down the plugin within a single session would eventually lead to an “out of relcache_callback_list slots” error.

I haven't verified that this works yet, but irrespective of it being fixed or not, I have reproed the issue on 15.2. It is easiest to trigger with this diff:

```diff
diff --git a/src/storage/src/source/postgres/replication.rs b/src/storage/src/source/postgres/replication.rs
index e39d2b2b45..fef59b4118 100644
--- a/src/storage/src/source/postgres/replication.rs
+++ b/src/storage/src/source/postgres/replication.rs
@@ -89,7 +89,7 @@ const FEEDBACK_INTERVAL: Duration = Duration::from_secs(30);
 
 /// The maximum amount of waiting for a transaction to appear in the replication stream before
 /// checking for replication lag.
-const TX_TIMEOUT: Duration = Duration::from_secs(30);
+const TX_TIMEOUT: Duration = Duration::from_secs(1);
 
 // A request to rewind a snapshot taken at `snapshot_lsn` to the initial LSN of the replication
 // slot. This is accomplished by emitting `(data, 0, -diff)` for all updates `(data, lsn, diff)`
@@ -215,8 +215,10 @@ pub(crate) fn render<G: Scope<Timestamp = MzOffset>>(
                 let mut container = Vec::new();
                 let max_capacity = timely::container::buffer::default_capacity::<((u32, Result<Vec<Option<Bytes>>, DefiniteError>), MzOffset, Diff)>();
 
+                tracing::info!("outer stream");
                 while let Ok(_) = tokio::time::timeout(TX_TIMEOUT, stream.as_mut().peek()).await {
                     let mut new_upper = *data_cap.time();
+                    tracing::info!("inner stream");
                     while let Some(event) = stream.as_mut().peek().now_or_never() {
                         match event {
                             Some(Ok(LogicalReplicationMessage::Begin(begin))) => {
@@ -258,11 +260,13 @@ pub(crate) fn render<G: Scope<Timestamp = MzOffset>>(
                             None => break,
                         }
                     }
+                    tracing::info!("exit inner stream");
                     data_output.give_container(data_cap, &mut container).await;
                     upper_cap.downgrade(&new_upper);
                     data_cap.downgrade(&new_upper);
                     rewinds.retain(|_, (_, req)| data_cap.time() <= &req.snapshot_lsn);
                 }
+                tracing::info!("exit outer stream");
             }
         })
     });
```

Whoever is interested in trying this out can set the timeout that matches their patience.

## Proposal

To fix this issue, we need to remove the calls to `pg_logical_slot_peek_binary_changes`. Those calls are used to handle replication lag in the face of an inert publication while the reset of the system made progress, so we have to find an alternative methodology.

 I recommend we do what a number of other developers do and perform trivial modifications to the upstream PG database co force its WAL to advance.

One of the warts in this is that we need to see not only that the WAL advanced, but that it inserts a `BEGIN` statement in the replication slot's publication (this is the only way that we can be sure that we meaningfully encounter the value).

Without the ability to repeatedly inspect the state of the replication slot, I don't know of any other way we can possibly ensure that the stream is active.

We could also require all users of PG sources upgrade to version 15.3. That seems like a challenging requirement to enforce on all users forevermore.

**Comment by benesch** [comment]
Oy! Good find! What a mess!

> Calling this function ~10 times causes the PG server to restart.

Does the whole server restart ... or just the one backend (i.e., the process handling your connection)? If it's just the one backend.... I mean maybe we just roll with it? Is that crazy? Hopefully we just reconnect and all is well.

> In addition, this issue coincides with [], which demonstrates some issues with the way we currently handle progress––and particularly progress at the end of the stream. That issue has more detail about how this affects its solution.

Is https://github.com/MaterializeInc/materialize/issues/20296 the issue that's meant to be referenced here?

**Comment by benesch** [comment]
> > Calling this function ~10 times causes the PG server to restart.
> 
> Does the whole server restart ... or just the one backend (i.e., the process handling your connection)? If it's just the one backend.... I mean maybe we just roll with it? Is that crazy? Hopefully we just reconnect and all is well.

Maybe slightly less crazy: what if we kept track of the number of calls to `pg_logical_slot_peek_binary_changes` and gracefully terminated and restarted the connection after, say, five calls to that function?

**Comment by petrosagg** [comment]
Wow, this is a great find! I had seen these errors in CI logs but never occurred to me that this is something we're causing. There is an alternative trick to peeking the slot which is described here https://fivetran.com/docs/databases/postgresql#heartbeat

Annoyingly this trick only generates a continuous stream of empty transactions on the logical replication stream for postgres < 15. In version 15 they "fixed" this problem and logical replication doesn't bother to send over the wire empty transactions which means we can't observe the frontier advancing. I have a lead to a possible way out but some investigation is needed

**Comment by sploiselle** [comment]
@benesch Sorry––this issue originally said server, but I meant process. Though I guess processes don't "restart," so I had muddied some terms.
