### ISSUE TITLE
pg sources: eagerly downgrading cap can panic + ignore data

### ISSUE THREAD

**Issue by sploiselle** [MaterializeInc/materialize#20296]
### What version of Materialize are you using?

8e1d5a825149ee1837b7aef77355f870a0bc9904

### What is the issue?

When ingesting from PG, there are a few conditions where we eagerly downgrade our capabilities, essentially committing an LSN's data. However, the current approaches have shortcomings that can lead to panics if we encounter another transaction at the same LSN (which this code does not preclude).

### Container capacity

We downgrade [[1](https://github.com/MaterializeInc/materialize/blob/93651373fc36af27d88cef29abb9cd7600c0ad92/src/storage/src/source/postgres/replication.rs#L247-L252)] our capabilities when we have exceeded our desired capacity [[2](https://github.com/MaterializeInc/materialize/blob/93651373fc36af27d88cef29abb9cd7600c0ad92/src/storage/src/source/postgres/replication.rs#L216)].

However, an LSN can span multiple transactions and this approach does not guarantee that we will never produce data at this LSN before downgrading the capability.

### Stream interruption

We  downgrade our capabilities [[3](https://github.com/MaterializeInc/materialize/blob/93651373fc36af27d88cef29abb9cd7600c0ad92/src/storage/src/source/postgres/replication.rs#L261-L263)] whenever the stream terminates [[4](https://github.com/MaterializeInc/materialize/blob/93651373fc36af27d88cef29abb9cd7600c0ad92/src/storage/src/source/postgres/replication.rs#L220)]. I speculate that the semantics here are assuming Materialize consumed the entire stream, meaning that once it resumed its next LSN would be greater than the last we saw.

However, the implementation relies on a `now_or_never()` call, which only means that the next value was not immediately available, not that this LSN has no more values. For example, there could have been interruption in the connection between Materialize and the server.

## Impact

If we encounter either of these issues, the PG ingestion will panic on the call to downgrade the capability. It is possible that this will happen after we have appended to the persist shard and downgraded the write frontier. In this case, on resumption, we would advance past the data transactions we missed, believing that we had already committed them [[5](https://github.com/MaterializeInc/materialize/blob/93651373fc36af27d88cef29abb9cd7600c0ad92/src/storage/src/source/postgres/replication.rs#L517-L519)].

## Proposal

The most desirable solution to this problem is to only downgrade our capabilities when we know that we have seen all of the data at a given LSN––through our observations of the data we receive, as well as by using admin-type functions like `pg_logical_slot_peek_binary_changes` .

However, as outlined in #20295 we cannot rely on `pg_logical_slot_peek_binary_changes` without requiring all clients use only a _very_ recent version of PG.

This leaves us with the ability to inspect data that comes across the replication stream. The proposal in #20295 also solves this issue; if we continually adjust a table in the publication, it will continually produce data and we will be able to close out the stream regular intervals. 

In terms of the current architecture of the ingestion, these inserts only need to occur if we believe we have encountered the end of the replication stream.

With this change in place, though we do also have to make a potentially controversial or annoying change, and add a `halt` outside the outer loop that awaits the replication stream with a timeout (removing the outermost `loop`). In the case that we have exited the timeout loop, we have given data away but never committed it. If we re-enter the PG replication stream and eventually commit data, there is no guarantee what the multiplicity of the data we will commit if we do eventually downgrade the data capability.

**Comment by petrosagg** [comment]
I don't see any issue with how the code handles downgrades at the moment.

> We downgrade [[1](https://github.com/MaterializeInc/materialize/blob/93651373fc36af27d88cef29abb9cd7600c0ad92/src/storage/src/source/postgres/replication.rs#L247-L252)] our capabilities when we have exceeded our desired capacity [[2](https://github.com/MaterializeInc/materialize/blob/93651373fc36af27d88cef29abb9cd7600c0ad92/src/storage/src/source/postgres/replication.rs#L216)].
>
> However, an LSN can span multiple transactions and this approach does not guarantee that we will never produce data at this LSN before downgrading the capability.

We only check if the capacity is exceeded at transaction boundaries (the while loop above runs until the `tx` stream is exhausted), so it's not possible to downgrade mid-transaction.

Also, what does "an LSN can span multiple transactions" mean? That doesn't sound right and I have never observed such a thing. That would require two separate transaction to have their commit record happen at the same LSN. Have you seen this happening?


> We downgrade our capabilities [[3](https://github.com/MaterializeInc/materialize/blob/93651373fc36af27d88cef29abb9cd7600c0ad92/src/storage/src/source/postgres/replication.rs#L261-L263)] whenever the stream terminates [[4](https://github.com/MaterializeInc/materialize/blob/93651373fc36af27d88cef29abb9cd7600c0ad92/src/storage/src/source/postgres/replication.rs#L220)]. I speculate that the semantics here are assuming Materialize consumed the entire stream, meaning that once it resumed its next LSN would be greater than the last we saw.
>
> However, the implementation relies on a now_or_never() call, which only means that the next value was not immediately available, not that this LSN has no more values. For example, there could have been interruption in the connection between Materialize and the server.

This downgrade also seems correct to me. We are calling `downgrade` at transaction boundaries because only the first `Begin` message is received with `now_or_never`. The entirety of the transaction is consumed by the inner loop which produces an error if the stream is interrupted. If no transaction are consumed then the downgrade is a no-op because `new_upper` gets initialized to whatever timestamp the capability already had.

**Comment by sploiselle** [comment]
I believe Petros is right and these downgrades are correct. I spent a while yesterday looking for any documentation that provided a guarantee of the relationship between WAL entries and transactions and found nothing, so concluded that we were holding an undocumented invariant true.

However, I now believe this was "too obvious to state," which is why the PG docs (or no one else) mentions it. WAL entries represent a byte offset in a log, and each `BEGIN` message is greater than a byte, so it is impossible to have two begin messages with the same LSN offset.

I had incorrectly assumed that the WAL positions offered a greater degree of indirection than 8, but that is totally unnecessary as this addressing scheme can address 18 exabytes of data.
