### ISSUE TITLE
[Epic] Support adding unbilled replicas to user clusters

### ISSUE THREAD

**Issue by benesch** [MaterializeInc/materialize#20317]
## Background

Incident 55 demonstrated that new versions of Materialize can increase the memory usage of existing workloads to a degree that they no longer fit in the currently allocated cluster replica size. 

As a temporary mitigation, the on call/release engineer can create new, larger replicas of the affected clusters. Unfortunately, the only way to do this at the moment results in replicas that the user gets billed for. While we can and have sorted this out in post by refunding the cost of the extra replicas, this creates an accounting headache. It'd be much cleaner if the on call/release engineer could add an "unbilled" replica that never hits the billing system at all.

## Description

Support adding unbilled replicas to a user cluster.

Open design question:

  * What should the syntax be? `CREATE CLUSTER REPLICA ... (UNBILLED = TRUE)`? 
  * How do unbilled replicas interact with managed clusters?
  * What users are allowed to create unbilled replicas? `mz_introspection`? `mz_system`? Both?
  * What users are allowed to drop unbilled replicas?
  * Do unbilled replicas have a different ID format? (https://github.com/MaterializeInc/materialize/pull/18636) E.g. "p1", "p2", where "p" stands for provider, as in replicas created by the service provider, i.e., us. Not clear this is worth it.

Note: I'd originally been thinking about this work item as adding _system_ replicas to a user cluster. But I don't think that's right. We should reserve "system" replicas for replicas that are literally baked into the binary, like `mz_introspection` and `mz_system`. Unbilled clusters should still present as "user" clusters.

## Work items

* [x] Implement support for adding unbilled replicas to user clusters
* [x] Add analytics that surface any user clusters with unbilled replicas, so that we remember to drop them when they are no longer required.

**Comment by teskje** [comment]
Depending on how we want to detect these replicas in billing, this PR that introduces tagged replica IDs might be a precondition for this feature: https://github.com/MaterializeInc/materialize/pull/18636. If we don't want to use system IDs for these replicas, we could introduce a new prefix to separate them from regular user replicas in `mz_audit_events`. Alternatively, adding a "billed" field to `mz_audit_events` should do the trick too.

**Comment by teskje** [comment]
@benesch Do you think Compute is involved here in any way? This looks to be a surfaces-only feature, but maybe I'm missing something.

**Comment by benesch** [comment]
Agree that it's all surfaces code. I CC'd compute on the issue since @antiguru did the most recent UX improvements for clusters (managed clusters).

**Comment by teskje** [comment]
> What's the status on #18636? Is something blocking that?

I wasn't able to quickly fix the cloudtests (specifically the upgrade tests stumble over the pod name change) and then didn't have time to work more on this. If we determine that it blocks this feature, I can pick it up again. I think this depends on how billing should recognize unbilled replicas.

**Comment by antiguru** [comment]
Closing this issue as completed. We support unbilled/billed-as replicas in production and surface metrics internally.

**Comment by jkosh44** [comment]
> What users are allowed to create unbilled replicas? mz_introspection? mz_system? Both?

Did this question ever get answered? Currently only `mz_system` can create unbilled replicas.

> Do unbilled replicas have a different ID format? (https://github.com/MaterializeInc/materialize/pull/18636) E.g. "p1", "p2", where "p" stands for provider, as in replicas created by the service provider, i.e., us. Not clear this is worth it.
>
> Note: I'd originally been thinking about this work item as adding system replicas to a user cluster. But I don't think that's right. We should reserve "system" replicas for replicas that are literally baked into the binary, like mz_introspection and mz_system. Unbilled clusters should still present as "user" clusters.

We ended up adding the concept of `INTERNAL` replicas. Does this logic still apply to those replicas? It feels a bit odd that internal replicas have user IDs

> What users are allowed to drop unbilled replicas?

Did this get answered either? As far as I can tell all users can drop an unbilled and internal replica. This also seems a bit strange that any user can drop internal replicas.

**Comment by benesch** [comment]
> We ended up adding the concept of `INTERNAL` replicas. Does this logic still apply to those replicas? It feels a bit odd that internal replicas have user IDs

I think the problem may be the name `INTERNAL` more than the fact that they have user IDs. I like the idea of using user IDs for everything that' snot literally baked into the binary.

> Did this get answered either? As far as I can tell all users can drop an unbilled and internal replica. This also seems a bit strange that any user can drop internal replicas.

Agreed it's somewhat weird, but it's like this to avoid breaking user workflows. E.g., a GitHub action that scales the cluster to zero at night, or drops and recreates the cluster. Wouldn't want that kind of stuff to get wedged because we'd created a temporary unbilled replica on a cluster.
