### ISSUE TITLE
Publish the lexer as an npm package

### ISSUE THREAD

**Issue by arusahni** [MaterializeInc/materialize#20313]
### Feature request

The Websocket and HTTP APIs provide two distinct modes with differing transactional semantics: simple and extended. The former uses an implicit transaction, and allows multiple statements per query string. The latter eagerly commits, but only permits a single statement per query string. Some Materialize clients may receive free input from end-users and not be able to preportion their statements into discrete query strings. These clients may then attempt to do some parsing or lexing on their end, but it can be complicated (and potentially inconsistent with how Materialize does things).

Instead of leaving this as an exercise to the reader, we should expose some of these internals to end-users via an installable library. As frontend applications are the most likely to use the HTTP and Websocket APIs, let's meet them where they are and publish a JavaScript library that allows applications to lex a query string using our lexer.

## Requirements

- An npm package is published with each database release. The version should match the Mz version.
- This package exports a single function as WebAssembly `mz_sql_parser::lexer::lex`
- A series of WASM build jobs are integrated into CI for both PR validation and release jobs
- This package is published under the materialize npm org: `@materialize/sql-lexer`
- A TypeScript type declaration file should be included in the package
- The published package should be reasonably-sized so as to be feasible for inclusion in web projects

**Comment by benesch** [comment]
As part of this work, I'd like to move the lexer into its own crate called `mz-sql-lexer`. That will help keep boundaries clear. Eyeballing the current `lexer` module, I think the crate will have four exports:

  1. `fn lex(query: &str) -> Result<Vec<(Token, usize)>, ParserError>`
  2. `Token`
  3. `Keyword`
  4. `LexerError`

(1) - (3) should be a simple cut/paste of the existing code. (4) will require a bit of refactoring. We'll need to copy the existing `ParserError` struct into the new crate and rename it `LexerError`, and then add an `impl From<LexerError> for ParserError` to the `mz-sql-parser` crate.

Propose using @materializeinc/sql-lexer for the NPM package name. The @materializeinc org means we can drop the `mz-` prefix.

**Comment by arusahni** [comment]
1-4 make sense. I'll start with that refactor as PR, and then follow-up with WASM-ification.
