### ISSUE TITLE
Try moka cache v0.9.8 (new version) as the in-memory blob cache?

### ISSUE THREAD

**Issue by tatsuya6502** [MaterializeInc/materialize#20322]
### Feature request

Hi. I am the author of moka cache library. I published [moka v0.9.8](https://crates.io/crates/moka/0.9.8) to crates.io few hours ago. It has a potential fix for the segfault found in #19746. Can you please try moka again as the blob cache? No need to rush though. (moka was removed by #19945)

I ran Materialize's "Long Zippy w/ user tables" test with moka v0.9.8 on an Amazon EC2 `c6a.12xlarge` instance. I ran it for 14 hours and could not reproduce the problem. I am hoping v0.9.8 fixed the problem.

- Used Materialize at commit https://github.com/MaterializeInc/materialize/commit/9ab5f833b919f8a5200b3918eca0847f40cc3337
    - This is the first commit mentioned in #19746.
    - but, with moka v0.9.8, instead of v0.9.6. (`cargo update -p moka`)
- Amazon EC2 `c6a.12xlarge` instance (48 vCPUs)
    - Ubuntu 22.04 x86_64
- Ran "Long Zippy w/ user tables" for 14 hours.
    - There were 63,237 actions executed.
    - It ran slower on EC2 than my local PC. Maybe it was hitting the IOps limit of gp2 EBS volume.

### About the root cause and the fix

I analyzed a core dump of `clusterd` generated by a crashed Zippy test with moka v0.9.6. I found the problem may have been already fixed in moka v0.11.0 (which was released on May 1, 2023). So I backported the fix to moka v0.9.8.

The following GH issue has the stack trace in the `clusterd` core dump, and potential steps to reproduce:

- https://github.com/moka-rs/moka/issues/281#issuecomment-1616445598

Some details about the root cause and the fix:

- Pull request for v0.11.0: https://github.com/moka-rs/moka/pull/259
- Because the bug made a (mutable) raw pointer from a shared (immutable) reference, rustc/LLVM assume the pointee will not change in the memory and can remove redundant load (from memory to register) operations as optimization. However, in some corner cases, the data in the memory will change after first load, so a copy of the data in a register becomes outdated. Using such an outdated data will cause the segmentation fault.
- The bug was found by myself when reviewing unsafe code. I added a test case for Miri, and Miri reported a stacked borrow violation as expected. (See [moka #259](https://github.com/moka-rs/moka/pull/259) for more details)
- I fixed the code (for v0.11.0) and verified that Miri no longer reported any issues on the test.
- I ported the fix to v0.9.8: https://github.com/moka-rs/moka/pull/283

**Comment by benesch** [comment]
@tatsuya6502 thanks again for digging so deep on this. We ultimately decided to introduce the blob cache using our own in-house LRU cache implementation that doesn't use `unsafe`, to further minimize the risk of memory unsafety: https://github.com/MaterializeInc/materialize/pull/24208.

**Comment by tatsuya6502** [comment]
@benesch Thanks for the update. I am glad you guys found a solution!
