### ISSUE TITLE
thread 'timely:work-0' panicked at 'invalid as_of: upper(Antichain { elements: [0] }) <= as_of(Antichain { elements: [] })'

### ISSUE THREAD

**Issue by nrainer-materialize** [MaterializeInc/materialize#20320]
### What version of Materialize are you using?

9787faf

### What is the issue?

```
Unknown error in [services.log](https://buildkite.com/organizations/materialize/pipelines/nightlies/builds/2714/jobs/01891e19-99e7-497b-b6cd-6e7b6bc9f45a/artifacts/01891e47-b883-4725-ad3b-567897d1ac5d):247889:
    testdrive-materialized-1     | thread 'timely:work-0' panicked at 'invalid as_of: upper(Antichain { elements: [0] }) <= as_of(Antichain { elements: [] })', /var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0c093f8302ef2062a-1/materialize/tests/src/storage/src/source/reclock/compat.rs:117:9
```

occurred in https://buildkite.com/materialize/nightlies/builds/2714

ci-regexp: panicked at 'invalid as_of: upper

**Comment by philip-stoev** [comment]
Happened again https://buildkite.com/materialize/nightlies/builds/2931#_

**Comment by philip-stoev** [comment]
And again https://buildkite.com/materialize/nightlies/builds/2957#_

**Comment by philip-stoev** [comment]
and again https://buildkite.com/materialize/tests/builds/65493

**Comment by def-** [comment]
Now also seen in production ^ Still happens often in nightly and tests pipelines, this seems important to look at.
