### ISSUE TITLE
Multiple hierarchical reductions in one query could be in a `Row` instead of a `Vec<Row>`

### ISSUE THREAD

**Issue by ggevay** [MaterializeInc/materialize#20332]
When there are multiple hierarchical reductions in one query, `build_bucketed` starts with collecting the relevant input values into a `Vec<Row>`, where each `Row` has exactly one `Datum`. However, it could instead collect into a single `Row` with multiple `Datum`s. This would save a lot of memory, since a `Row` is always at least 24 bytes (`Smallvec`), while an aggregate is usually just 4 or 8 bytes.

There is a minor downside though: The `reduce_abelian` at the end (and in `build_bucketed_negated_output`) will have a slightly more complicated logic, which will probably be more costly CPU-wise. However, currently most clusters are memory-bound rather than CPU-bound, so we should probably go ahead with the optimization. Note that we could make the logic have a special code path for the case when there is only 1 aggregate to not have the CPU overhead in that case when there is no memory saving.

For example, this would help with the memory usage of the query that was in the center of incident-55, because it has two `max` aggregations.

cc @vmarcos

**Comment by vmarcos** [comment]
When we get to this issue, it would be great if we could co-solve it together with #19358. Also in the case of a bucketed hierarchical aggregation, if we keep to `Row` values in the first `map`, then this operation becomes an identity mapping when there are only hierarchical aggregates in the query. In this case, the entirety of the first `map` in `build_bucketed` can be omitted.
