### ISSUE TITLE
parallel-workload: unknown catalog item 'u4736'

### ISSUE THREAD

**Issue by def-** [MaterializeInc/materialize#20381]
### What version of Materialize are you using?

f5e1857956d968a759c879a4b207a5ebf7da70c4

### What is the issue?

With the new parallel-workload in https://github.com/MaterializeInc/materialize/pull/20354:
```
$ bin/parallel-workload-test --threads=500 --complexity=ddl --seed=1688671291
[...]
pg8000.exceptions.DatabaseError: {'S': 'ERROR', 'C': 'XX000', 'M': "unknown catalog item 'u4736'"}
Exception: Thread worker_139 failed, exiting
```
This is an excessive 500 connections running queries in parallel. With fewer threads I haven't seen this error, is it expected?

All queries that ran: https://gist.github.com/def-/ed2e36642abce3d90da975fdd58fe327

**Comment by def-** [comment]
I'm now ignoring this error, it's happening all the time with parallel-workload, example:
```
git checkout 98795b94bd9c1bec476b0e0dfe15d15974d1fd68
bin/parallel-workload-test --threads=100 --runtime=10 --seed=1688741552 --complexity=dd
[...]
Dropping database db_pw_1688741552
Queries executed: 1532 (26% failed)
Error statistics:
  in the same timedomain: SelectAction: 208
  unknown catalog item: SelectAction: 132, InsertAction: 7, DeleteAction: 2, UpdateAction: 10, DropIndexAction: 4
  query could not complete: SelectAction: 9
  already exists: CreateViewAction: 21, CreateTableAction: 9
  still depended upon by: DropTableAction: 3
```
So "unknown catalog item" occured > 100 times, I'm ignoring it for now, so it's not really blocking. Maybe this should just be expected when you drop tables/views/indexes while other transactions are running?

**Comment by mjibson** [comment]
This seems like it's expected if things are being dropped while also being queried. Sometimes the drop executes first and the query then has to error.
