### ISSUE TITLE
'main' panicked at 'process orchestrator requires scratch directory' in Canary Deploy in Staging Cloud

### ISSUE THREAD

**Issue by nrainer-materialize** [MaterializeInc/materialize#20401]
### What version of Materialize are you using?

v0.60.0-dev

### What is the issue?

"Canary Deploy in Staging Cloud" fails due to this panic.

```
cloud-canary-materialized-1  | thread 'main' panicked at 'process orchestrator requires scratch directory', src/environmentd/src/bin/environmentd/main.rs:769:30
cloud-canary-materialized-1  | stack backtrace:
cloud-canary-materialized-1  |    0: rust_begin_unwind
cloud-canary-materialized-1  |    1: core::panicking::panic_fmt
cloud-canary-materialized-1  |    2: core::panicking::panic_display
cloud-canary-materialized-1  |    3: core::panicking::panic_str
cloud-canary-materialized-1  |    4: core::option::expect_failed
cloud-canary-materialized-1  |    5: environmentd::run
cloud-canary-materialized-1  |    6: environmentd::main
cloud-canary-materialized-1  | note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

(https://buildkite.com/materialize/nightlies/builds/2747)

Possibly related:
* https://github.com/MaterializeInc/materialize/pull/20106
* https://github.com/MaterializeInc/materialize/pull/20379

**Comment by guswynn** [comment]
this was just testing!

**Comment by def-** [comment]
@guswynn What do you mean by just testing? It still fails in the latest nightly: https://buildkite.com/materialize/nightlies/builds/2760#018932b2-9fb9-4895-8ef2-f34957ab4030
The test/cloud-canary/mzcompose.py brings up a Materialized instance with `--orchestrator-process-secrets-directory=/mzdata/secrets` which panics:

https://github.com/MaterializeInc/materialize/blob/main/test/cloud-canary/mzcompose.py#L37-L44

I'll provide a fix.

**Comment by nrainer-materialize** [comment]
Thanks, Dennis!
