### ISSUE TITLE
Support single DDL in explicit transactions

### ISSUE THREAD

**Issue by benesch** [MaterializeInc/materialize#20426]
## Summary

Allow explicit transactions that contain a single DDL statement, like:

```sql
BEGIN;
CREATE TABLE t1 (a int);
COMMIT;
```

This will unblock running DDL in at least:

  * Deepnote
  * DBeaver

## Details

Materialize today does not support executing DDL transactionally. E.g., you can't create two tables in a single transaction and have Materialize atomically create both tables or neither:

```sql
BEGIN;
CREATE TABLE t1 (a int);
CREATE TABLE t2 (a int);
COMMIT;
```

However, Materialize's mechanism of enforcement is quite restrictive. Materialize rejects any explicit transaction that contains even a single DDL statement:

```sql
=> BEGIN;
=> CREATE TABLE test (a int);
ERROR:  CREATE TABLE test (a int4) cannot be run inside a transaction block
```

I don't _think_ there is any technical reason that we couldn't allow exactly one DDL statement in an explicit transaction block.

DBeaver always executes DDL statements in an explicit transaction block, and so currently always fails like so when attempting to create or alter the definition of any SQL objects:

![](https://user-images.githubusercontent.com/882976/252060790-8cb792fa-bd74-4064-b8cb-53e2fa958a51.png)

Deepnote similarly has the same issue:

<img width="955" alt="image" src="https://github.com/MaterializeInc/materialize/assets/882976/37ba43c0-81fe-432a-920c-7c01752718b6">

I imagine there are other SQL tools that suffer from the same problem.

## Implementation notes

  * Keep #9999 in mind. We want to be sure we don't accidentally allow DDL in transactions that do anything besides DDL.

cc @mjibson

**Comment by morsapaes** [comment]
> I imagine there are other SQL GUIs that suffer from the same problem.

Pretty much all GUIs I've tried so far have at least one feature that requires transactional DDL (though mostly single-statement transactions, as mentioned in this issue). Off the top of my head, I can think of Hex as a tool where this is most prominently annoying (see [this thread](https://materializeinc.slack.com/archives/C0521SK0YJ0/p1680786033800699?thread_ts=1680785406.376039&cid=C0521SK0YJ0)).

**Comment by morsapaes** [comment]
Linking to #5874, which is partially blocked on this issue.

**Comment by benesch** [comment]
> Linking to #5874, which is partially blocked on this issue.

Is that the right issue? The pgAdmin issue is unrelated to this, no? Did you mean to link a Deepnote issue?

**Comment by benesch** [comment]
Updated the issue description to mention Deepnote too.

**Comment by mjibson** [comment]
Worked a bit on this at https://github.com/mjibson/materialize/tree/ddl-txn. That method is going to require more invasive changes to make it work at the protocol layer. Doing this in the coord layer is probably a better choice.

**Comment by mjibson** [comment]
PR and design document out for this if anyone would like a read!
