### ISSUE TITLE
"Canary Deploy in Staging Cloud" contains empty services.log

### ISSUE THREAD

**Issue by nrainer-materialize** [MaterializeInc/materialize#20463]
`services.log` is often 0 bytes if "Canary Deploy in Staging Cloud" fails

### Buildkite link

https://buildkite.com/materialize/nightlies/builds/2771#01894464-7ab9-4eb0-8cbd-a32b0ce147d3

### Additional thoughts

@def- suspects that the whole Docker composition gets destroyed due to errors such that `bin/mzcompose --find ...` can no longer find the file.

**Comment by nrainer-materialize** [comment]
FYI @philip-stoev

**Comment by philip-stoev** [comment]
I am no longer able to reproduce this. The file is no longer empty for me. Furthermore, services.txt for this CI job only contains the output of a short-lived Materialize instance that is just used to perform the version check -- that is, make sure that the correct thing is being deployed on the cloud.

The actual logs from the cloud deployment should be found in Grafana.
