### ISSUE TITLE
parallel-workload: FETCH doesn't work in a read-transaction

### ISSUE THREAD

**Issue by def-** [MaterializeInc/materialize#20474]
### What version of Materialize are you using?

main

### What is the issue?

Using the WIP parallel-workload (https://github.com/MaterializeInc/materialize/pull/20354) I have run into a problem with `FETCH` not running inside of a read-only transaction:

```
materialize=> create table t(c int);
CREATE TABLE
materialize=> begin;
BEGIN
materialize=*> select * from t;
 c
---
(0 rows)

materialize=*> declare c cursor for subscribe t;
DECLARE CURSOR
materialize=*> fetch all c;
ERROR:  transaction in read-only mode
```
I think this should work as `FETCH` is read-only too.

**Comment by def-** [comment]
Maybe FETCH is not supposed to work together in the same transaction with SELECT, in that case this is just a wrong error message.

**Comment by mjibson** [comment]
This is working as intended, although the error message isn't helpful. The problem is you can't run both SELECT and SUBSCRIBE in a transaction. It's got nothing to do with the FETCH.
