### ISSUE TITLE
linux apt install documentation is incorrect

### ISSUE THREAD

**Issue by mjibson** [MaterializeInc/materialize#2050]
At: https://materialize.io/docs/install/#linux-installation

A `t` is missing from the apt sources.list.d line, and a call to `apt update` needs to happen. Full should be:

```
echo "deb [trusted=yes] https://packages.materialize.io/apt/ /" > /etc/apt/sources.list.d/fury.list
apt update
apt install materialized
```

**Comment by benesch** [comment]
Thanks, @mjibson. On it!
