### ISSUE TITLE
expr: regexp_extract is broken in some cases

### ISSUE THREAD

**Issue by maddyblue** [MaterializeInc/materialize#20533]
We have some tests that use regexp_extract and work, however:

```
materialize=> select regexp_extract('aaa', 'a');
ERROR:  XX000: column "table_func_b8f64986-14da-4915-8b12-6737ba7d12de" does not exist
```

so something's broken with its scoping or column refs.

ci-regexp: column ".*" does not exist

**Comment by mjibson** [comment]
This function isn't in postgres, but kinda lifted from cockroach. But we differ from cockroach too, who only returns the first match and we say we return all matches. Unclear if we should change that behavior, probably not.

**Comment by mjibson** [comment]
See https://github.com/MaterializeInc/materialize/issues/23630#issue-2022016412 for another repro.
