### ISSUE TITLE
Detect disabled tests and task tags that reference a closed issue

### ISSUE THREAD

**Issue by def-** [MaterializeInc/materialize#20549]
### Feature request

And warn in the PR that fixes the issue as well as in nightly about closed issues which still have associated TODOs in the code, so that we don't forget to re-enable the relevant tests. This happened in a few instances already, see https://github.com/MaterializeInc/materialize/pull/20518 and https://github.com/MaterializeInc/materialize/pull/20505 and https://github.com/def-/sqlsmith/commit/062006aa6c0c7b46f2e50db83c0c06dd4b28122e (outside of Materialize repo)

Based on a discussion with @nrainer-materialize

**Comment by nrainer-materialize** [comment]
Besides `TODO` comments, this should also apply to the annotation `@unittest.skip(message)`

**Comment by nrainer-materialize** [comment]
Also include `@disabled` annotation on `Check`s (https://github.com/MaterializeInc/materialize/pull/22682).
