### ISSUE TITLE
Failed to create source.

### ISSUE THREAD

**Issue by mdevan** [MaterializeInc/materialize#2057]
Just downloaded and ran materialized v0.1.0, on a Debian 10. Connected with psql and tried to create a source:

```
materialize=> create source requests from 'file:///var/log/nginx/access.log' with ( regex='foo', tail=true );
ERROR:  Parse error:
create source requests from 'file:///var/log/nginx/access.log' with ( regex='foo', tail=true );
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Expected one of FILE or KAFKA or KINESIS, found: 'file:///var/log/nginx/access.log'
```

What am I doing wrong? The file location/existence does not seem to matter, neither does the case of "file".

(Also: is there a better place to ask such questions?)

**Comment by mdevan** [comment]
OK, looks like the query at https://materialize.io/docs/demos/log-parsing/#create-sources-from-logs has not been updated to match the latest syntax.

So here's an updated query which should work as per https://materialize.io/docs/sql/create-source/#connector-specifications

```
materialize=> create source requests from file '/var/log/nginx/access.log' format regex '(?P<full>.*)';
CREATE SOURCE
```

It fails if I add the `tail = true` option though:

```
materialize=> create source requests2 from file '/var/log/nginx/access.log' format regex '(?P<full>.*)' with ( tail = true );
ERROR:  Parse error:
create source requests2 from file '/var/log/nginx/access.log' format regex '(?P<full>.*)' with ( tail = true );
                                                                                          ^^^^
Expected end of statement, found: with
```

The syntax appears to be correct as per: https://materialize.io/docs/sql/create-source/#creating-a-source-from-a-dynamic-unstructured-file

**Comment by ruchirK** [comment]
Hi @mdevan! Thanks for raising this.

The correct syntax for what you want is
```
create source requests2 from file '/var/log/nginx/access.log' with (tail = true) format regex '(?P<full>.*)';
```

Let me know if that works for you. The rationale is that the with args are part of the connector specifications and so must follow at the end of that part of the query (before the format specifications).

The other example in the docs is out of date and I've filed an issue to fix https://github.com/MaterializeInc/materialize/issues/2060

**Comment by mdevan** [comment]
That works, thanks.
