### ISSUE TITLE
`RETURNING` is not a reserved keyword

### ISSUE THREAD

**Issue by benesch** [MaterializeInc/materialize#20584]
### What version of Materialize are you using?

v0.60.1

### What is the issue?

The following SQL query is valid in PostgreSQL but fails to parse in Materialize:

```
insert into t select * from generate_series(1,10) returning *;
ERROR:  Expected end of statement, found star
```

The problem is that we don't consider `RETURNING` a reserved keyword:

https://github.com/MaterializeInc/materialize/blob/9864a3a41825a627bd1fab49e267de65b81cbe82/src/sql-lexer/src/keywords.rs#L59-L72

Fixing this in the straightforward way (i.e., adding it to the list of reserved keywords) would be a breaking change, unfortunately, as `CREATE VIEW v AS SELECT returning FROM (VALUES (...)) _ (returning)` is currently a valid SQL query in Materialize, but would cease to be valid after `RETURNING` is marked as reserved. This would cause the view definition to become unparseable in a new version of Materialize.

The sooner we fix this the better. We may be lucky right now and have no view definitions in production that contain the word `returning`.

cc @jkosh44 

Originally reported on Slack by @umanwizard: https://materializeinc.slack.com/archives/C02FWJ94HME/p1688056945378559

**Comment by jkosh44** [comment]
This might not be a breaking change because it looks like we actually do properly quote "returning" before saving it in the catalog.

```
materialize=> CREATE VIEW v AS SELECT returning FROM (VALUES (1)) _ (returning);
CREATE VIEW
materialize=> SELECT name, definition FROM (SELECT name, definition FROM mz_views UNION ALL SELECT name, definition FROM mz_materialized_views) WHERE definition LIKE '%returning%';
 name |                         definition                         
------+------------------------------------------------------------
 v    | SELECT "returning" FROM (VALUES (1)) AS "_" ("returning");
(1 row)


```
