### ISSUE TITLE
docs: Wikievent examples in getting started docs fail after mistyping filename

### ISSUE THREAD

**Issue by seletz** [MaterializeInc/materialize#2058]
## Problem

The "wiki event" examples form getting started did not work for me after mistyping the filename while creating the file source **even after dropping and recreating the source**.

Additionally, a -- to me at last -- confusing error message is shown.

```
materialize=> select count(*) from wikievent;
ERROR:  catalog item 'wikievent' does not exist
materialize=> drop index wikievent;
ERROR:  catalog item 'wikievent' does not exist
materialize=> CREATE SOURCE wikirecent
FROM FILE 'wikirecent'
WITH ( tail=true )
FORMAT REGEX '^data: (?P<data>.*)';
ERROR:  catalog item 'wikirecent' already exists
```

## Recreate

- Wikievent example in getting started
- Mistype filename while creating the source
- Try to recover

## Version and Platform

materialized v0.1.0 (e1d970912) 
macOS Catalina

**Comment by ruchirK** [comment]
Hi @seletz ! I have two clarifying questions:

1. When you originally created the source did you name it `wikievent` or `wikirecent`?
2. Is there any way you can show me either the output of `SHOW SOURCES`,  and/or the history of commands you inputted into the postgres cli.

Basically I'm having a hard time understanding how to reproduce this state -- it looks like you may have had a correctly named source called `wikirecent` from the beginning which would explain the output we see here?

**Comment by seletz** [comment]
I"ll try to check this.

**Comment by seletz** [comment]
Oh dang -- it sure looks like I fat-fingered the name of the source.  I've just tried again and got It working.

Sorry for wasting your time.
