### ISSUE TITLE
Modularize the implementations for sources, formats, and envelopes

### ISSUE THREAD

**Issue by theikkila** [MaterializeInc/materialize#2059]
I'm looking for implementing new sources for Materialized and went through code.

Currently it seems that the implementation details of data sources are all over the codebase and even in syntax description.

What I would like to see is well decoupled implementations of data sources that would make it easily approachable to create a new source.
I think that creating new sources with current architecture causes technical debt so faster we refactor, less technical debt we will have.

If this sounds good idea I might try to seek some time to implement refactoring for this.

**Comment by JLDLaughlin** [comment]
First of all, thank you for your interest in using (and extending) Materialize!

In terms of the source implementation, I agree that it's spread across our codebase right now. We've actually been working on adding new sources recently (like Kinesis), as well as refactoring our `CREATE SOURCE` syntax to be more flexible. We are still internally debating how to improve sources to make it plug and play in the future, but realistically this won't happen anytime soon. The challenge is that source implementations need to interact with the underlying infrastructure (Differential and Timely) in non-trivial ways.

That being said, I'd be interested to hear about the use-cases you have in mind. Were you considering adding a particular type of source?

In the meantime, here are two potential "workarounds" for source types that are not currently implemented: 

1. Output your streaming data to a file and use a [File source](https://materialize.io/docs/sql/create-source/#file-source-details).
1. Push your streaming data to a Kafka topic and use a [Kafka source](https://materialize.io/docs/sql/create-source/#kafka-source-details).

**Comment by rjnn** [comment]
I'm coming around to the point of view that @theikkila is correct here. In 0.4, we should seek to do some amount of modularization of the various sources and formats and envelopes, and have a really clear product _and_ engineering story by 0.5. This is going to take us some time to understand, hence the long timelines here - but tagging as 0.4 to ensure we make some progress on diagnosing what the biggest bottlenecks to modularizing these are.

**Comment by wangandi** [comment]
As part of the upsert work, I started modularizing formats by creating a trait DecoderState whose methods a common caller would call, which I would consider to be a start towards this work. One limitation of DecoderState at the moment is that envelopes and formats have not been decoupled, so instead of `decode_value`, there is `give_value` and `give_key_value`, to account for behaviors of different envelopes.

**Comment by benesch** [comment]
Closing, as we've made a lot of progress on source orthogonality internally. I don't currently think it would be beneficial to modularize further (e.g., by modularizing the SQL parsing of connection/source options), as 1) adjusting parsing/planning for new source types typically only takes a day or two, and 2) modularization would substantially complicate the parsing/planning of `ALTER CONNECTION`, as it needs to understand all connection options at once.
