### ISSUE TITLE
Fix create source command in simple file demo

### ISSUE THREAD

**Issue by ruchirK** [MaterializeInc/materialize#2060]
see https://materialize.io/docs/sql/create-source/#creating-a-source-from-a-dynamic-unstructured-file

**Comment by mdevan** [comment]
Also this: https://materialize.io/docs/demos/log-parsing/#create-sources-from-logs

**Comment by ruchirK** [comment]
> Also this: https://materialize.io/docs/demos/log-parsing/#create-sources-from-logs

Thank you! I'll search the docs for CREATE SOURCE and check all hits
