### ISSUE TITLE
Add storage controller frontiers

### ISSUE THREAD

**Issue by benesch** [MaterializeInc/materialize#20626]
## Summary

The compute controller exposes the frontiers of each export that are known to the controller: https://materialize.com/docs/sql/system-catalog/mz_internal/#mz_cluster_replica_frontiers. We should do the same for the storage controller. This would allow users to compute the lag between their sources and their downstream materialized views/indexes.

## Details

Today, the only way to get this information out of the system is to parse it out of the human-readable `EXPLAIN TIMESTAMP` command. This is painful.

See this Slack conversation for details: https://materializeinc.slack.com/archives/C056M3001Q9/p1689618367915189

cc @dseisun-materialize

**Comment by danhhz** [comment]
The compute ones are served out of memory, not a persist shard, and these ones would be as well, correct?

**Comment by teskje** [comment]
It would be very cool if the storage frontiers could also end up in `mz_cluster_replica_frontiers`, where the compute frontiers already are. This would fit the spirit of cluster unification and make it easier for users to find the frontiers they are looking for. It's probably harder to implement though, as compute and storage have to agree on a mechanism to write controller metadata.

**Comment by teskje** [comment]
Something that might be an issue with the `mz_cluster_replica_frontiers` approach: The controller only reports per-replica frontiers. This has two consequences which might be dealbreakers for the planned observability work:

1. If a cluster has no replicas, no frontier information is available for it.
2. No frontier information is available for collections that are not maintained by replicas (like the storage-managed collections produced by the storage controller).

We could resolve both issues by instead/in addition having a table `mz_collection_frontiers` that lists for each compute/storage collection its current global frontier as known to the controller. The approach could be the same as what #20696 does, just the stored data would be different.

**Comment by teskje** [comment]
Closed by https://github.com/MaterializeInc/materialize/pull/20696
