### ISSUE TITLE
Managed clusters can be created with a REPLICATION FACTOR higher than the size of the AVAILABILITY ZONES list

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#20646]
### What version of Materialize are you using?

v0.61

### What is the issue?

This definition is accepted:

```
CREATE CLUSTER c_compute SIZE = '1', REPLICATION FACTOR 2, AVAILABILITY ZONES ['just_one_zone_here'];
```

Which causes both replicas to be placed in the same availability zone. This statement should have failed instead.

@antiguru FYI

**Comment by antiguru** [comment]
I'm inclined to say this works as expected, at least it works the same as unmanaged clusters used to work. The replicas round-robin through the availability zones, and for one .. it results in all replicas in the same zone. We should definitely document this to avoid confusion!

**Comment by nrainer-materialize** [comment]
Does the statement _and_ spinning up the replicas succeed? Or does just the statement succeed but placing the replicas afterwards fails because the `anti_affinity` applies (`cluster.rs`, L550)?

**Comment by antiguru** [comment]
We concluded that it's working as designed. It's not particularly useful to have all replicas in the same availability zone, but if that's what the user wants, we're not going to prevent it.

**Comment by benesch** [comment]
It still can be useful, if you want to ensure that you can tolerate the failure of a single EC2 instance but don't care about tolerating the failure of a single AZ.
