### ISSUE TITLE
feature benchmark: Regressions in Join-related scenarios

### ISSUE THREAD

**Issue by nrainer-materialize** [MaterializeInc/materialize#20658]
### What version of Materialize are you using?

65a0a57596205254472306cee50930fa7ad8d04e

### What is the issue?

[Nightly#2881](https://buildkite.com/materialize/nightlies/builds/2881#01896b5b-1c45-483e-b4ca-160fbbe473a7) and further builds:

```
The following scenarios have regressions: DeltaJoinMaintained, DifferentialJoin, FullOuterJoin
```

Bisecting to identify the cause is in progress.

**Comment by teskje** [comment]
Here is a simple repro for the speed regression with `mz_join_core`. This can be run on staging by switching `enable_mz_join_core` on/off via LD:

```sql
CREATE TABLE ten (f1 INTEGER);
INSERT INTO ten SELECT generate_series(1, 10);
CREATE VIEW v1 AS SELECT a1.f1 AS f1, a2.f1 AS f2, a3.f1 AS f3, a4.f1 AS f4, a5.f1 AS f5, a6.f1 AS f6 FROM ten AS a1, ten AS a2, ten AS a3, ten AS a4, ten AS a5, ten AS a6;
CREATE VIEW v2 AS SELECT COUNT(a1.f1) AS c1, COUNT(a2.f1) AS c2 FROM v1 AS a1 FULL OUTER JOIN v1 AS a2 USING (f1, f2, f3, f4, f5, f6);

\timing
SELECT * FROM v2;
```

The final SELECT takes ~8s with the DD join, but ~12 seconds with `mz_join_core`.

**Comment by nrainer-materialize** [comment]
Based on the bisecting results, I can confirm that failing `DifferentialJoin` and `FullOuterJoin` first occurred after [#20597 (Enable mz_join_core by default)](https://github.com/MaterializeInc/materialize/pull/20597) as @teskje suggested.
Failing `DeltaJoinMaintained`, which was observed in [Nightly#2881](https://buildkite.com/materialize/nightlies/builds/2881#01896b5b-1c45-483e-b4ca-160fbbe473a7), has had no further occurrences. Neither a retry in [Nightly#2904](https://buildkite.com/materialize/nightlies/builds/2904#0189704b-583e-48b1-96b2-48752f32e698) nor one of the following scheduled nightlies [#2888](https://buildkite.com/materialize/nightlies/builds/2888#01896deb-d77c-4e04-94a7-9d16ac9310bc) and [#2906](https://buildkite.com/materialize/nightlies/builds/2906#01897081-9172-4301-88d6-cd1113abcbdf) failed due to `DeltaJoinMaintained`. Therefore, I consider it an outlier.
I will remove the release blocker marker from this issue as suggested.

Slack discussion: https://materializeinc.slack.com/archives/CTESPM7FU/p1689774337880389
