### ISSUE TITLE
Support ingesting JSON in Kafka

### ISSUE THREAD

**Issue by benesch** [MaterializeInc/materialize#207]
Right now we can ingest Kafka topics where records are encoded using Avro, but not when the records are encoded in JSON.

**Comment by ruchirK** [comment]
This might be a dumb question but given that we have jsonb support why do we still need schemas for json objects / why not just chuck the whole thing into a jsonb column?

**Comment by rjnn** [comment]
@benesch, I think Ruchir is right here?

**Comment by benesch** [comment]
Agreed. Probably nothing to do here but document what you need to do.

**Comment by benesch** [comment]
Oh, here's another issue that explains why we might yet want JSON schema: https://github.com/MaterializeInc/materialize/issues/1494

Definitely don't need both of these issues though. Leaving this open because I think there's a bit of docs work to do, plus deciding whether it makes sense to have a `FORMAT JSON` format that just yields one JSON column.

**Comment by rjnn** [comment]
I'm closing #1494. There's a different way to articulate the-thing-we-might-yet-want, and I've filed #2679 instead.

**Comment by awang** [comment]
created a separate issue (#3176) for followup documentation, closing this issue as completed.
