### ISSUE TITLE
Window funcs don't work in `CASE WHEN`

### ISSUE THREAD

**Issue by ggevay** [MaterializeInc/materialize#20746]
### What version of Materialize are you using?

4f4a2370536cb096f7092d3fbfabe5b06b5a0946

### What is the issue?

Window functions give wrong results when they are inside a `CASE WHEN` ([this was noticed by a customer](https://materializeinc.slack.com/archives/C05J136GN6M/p1689955089758899)):
```
CREATE TABLE t(cond bool, x int);

INSERT INTO t VALUES (true, 0), (false, 1), (false, 2);

SELECT
  cond,
  x,
  CASE
    WHEN cond THEN
      first_value(x) OVER (ORDER BY x DESC)
    ELSE
      42
    END
FROM t;
```

Background: `CASE WHEN` is compiled to an `If`. [If there is a subquery in `If` (a window func is considered kind of like a subquery here), then it is decorrelated and lowered as follows:](https://github.com/MaterializeInc/materialize/blob/fa1a8893b3ce27a29cd648e3dd84e92f366c1829/src/sql/src/plan/lowering.rs#L870-L916) We split the scalar `If` into a `Union` of relation exprs, where we have one Union input for each branch. Each of these branches start with a `Filter` for only those rows for which `cond` has a specific value.

The problem is that the lowering logic for `If` assumes that the `HirScalarExpr` in the branches of the `If` will access only the current row. This is true for everything except window functions:
- If there are normal column references, then they obviously refer to the current row.
- If there is a subquery, then that can refer to the outer context only through the `^` column references, which always refer to the current row.
- However, window functions can refer to all the rows from the outer context.

So what goes wrong is that the `If` lowering logic will modify the outer context (confusingly referred to as `inner` in the decorrelation code) that is passed to any subquery in the branches in a way that guarantees the availability only of the current row: Specifically, it lowers the branches but gives each branch only those rows for which `cond` has the appropriate value. This means that when the lowering of a window function inside a branch accesses `inner`, it will see not the full input, but only those rows for which the `cond` had a specific value.

Another way to think about all this is that one can imagine the same `If` lowering code to be written in two steps: an HIR transform to an HIR `Union` with the two `Filter`s, and then the lowering. In this case, one can see that the HIR transform would be already wrong in itself, without any lowering, just by the semantics of HIR itself.

It's worth pondering over what exactly are the semantics of `HirScalarExpr::Windowing`. Window functions can refer to _other rows_ besides the current row (e.g., the previous row in a LAG), as opposed to any other `HirScalarExpr`. It's always perfectly clear what the _current row_ is, since `HirScalarExpr`s refer to it all the time. But where are the _other rows_ coming from? Arguably, we need a `HirRelationExpr` to which we can point to and say that the _current row_ is there inside that relation, and the _other rows_ are this and this rows somewhere around that _current row_. But a `HirScalarExpr` can be in many places, so do we need to specify the `HirRelationExpr` that the _other rows_ are pointing into when the `HirScalarExpr` is in each of these places? Fortunately, I think that a `HirScalarExpr::Windowing` can only occur in such a `HirScalarExpr` that is one of the expressions of a `HirRelationExpr::Map`, because they can be planned only in Step 7 and 8 of `plan_view_select`. If this is true (still need to verify this), then we can say that the _other rows_ point into the `input` `HirRelationExpr` of that `Map`.

I can imagine several approaches to fix this:
1. Make the `If` lowering more careful: it would specifically detect the situation when there is a window func call in one of the `HirScalarExpr`s of the branches, and pull out the window func evaluation into a `Map` before the `Filter`s that it is inserting. 
  - Advantages: 
    - Relatively small, localized change.
    - We don't have to be sure that a window function can occur only inside a `HirRelationExpr::Map`.
  - Disadvantages:
    - I'm not 100% sure whether some other part of the lowering is not also making the same problematic assumption about the `HirScalarExpr` accessing only the current row.
2. Do the lifting of window functions into a separate `Map` already as the first thing we do when seeing a `Map` during the lowering. The `HirScalarExpr`s in the new `Map` would contain window function calls only at their top.
  - Advantages:
    - We solve the bug even if other scalar expr lowerings are making the same problematic assumption.
  - Disadvantages:
    - We need to be sure that a window function can occur only inside a `HirRelationExpr::Map`.
3. Perform a full traversal of the entire HIR plan before lowering and pull out window funcs to separate `Map`s.
  - Advantages: If we see a window func that is not where we expect it to be (i.e., not in `Map`), we can `soft_panic_or_log`.
4. Add two new steps before each of steps 7 and 8 in `plan_view_select`, where we plan only window functions, and rely on `resolve_expr` (at the beginning of `plan_expr_inner`) in the current steps 7 and 8 to make references to the already planned window function calls. (This would be somewhat similar to how we handle aggregates, see Step 5 in `plan_view_select`.).
  - Advantages:
    - There wouldn't be a time even temporarily when HIR plans might have window functions not at the top level of a map scalar expr, because the HIR planning would already ensure this invariant.
    - Later, we can control the relative order of evaluation of window functions vs. table functions, and thus we can fix https://github.com/MaterializeInc/materialize/issues/20979
  - Disadvantages: HIR planning is already quite hairy. And argument could be made to separate concerns, and ensure the above invariant by a separate HIR transform.
5. We can conceivably take the above 4. approach further and create a dedicated `HirRelationExpr` node for window functions, so that we don't have to have the invariant that a window function call can only be at the top scalar expr of a Map.
  - Advantages: No surprising invariants for where window functions can be in an HIR plan, but we would have a dedicated place for it.
  - Disadvantages: A lot more code in the lowering and possibly elsewhere.

I think either 3. or 4. would be the best. We might discuss with @aalexandrov and @mjibson before going into the implementation.

(Note that if we pull out a window function call that can error from a CASE WHEN, then we might get spurious errors, in the sense that the CASE WHEN's condition won't be guarding the error. But I would solve this corner case later, together with [other](https://github.com/MaterializeInc/materialize/issues/17189) problems with spurious errors, e.g., MFP CSE might also lift it out from behind the CASE WHEN (as it does in the other variation of the customer query, see below))

It also requires an explanation how the customer's workaround sidesteps the problem. The customer's workaround is to have a copy of the same window function call also outside the CASE WHEN:
```
SELECT
  cond,
  x,
  first_value(x) OVER (ORDER BY x DESC),
  CASE
    WHEN cond THEN
      first_value(x) OVER (ORDER BY x DESC)
    ELSE
      42
    END
FROM t;
```
This surprisingly works correctly, and the reason is that MFP CSE then pulls out the window function call that is inside the CASE WHEN to a separate Map expression, and then the `If` lowering logic is no longer surrounding the window function call.

**Comment by mjibson** [comment]
I don't know a lot about HIR planning or lowering. But from reading this approach 5 appeals. If that means we have to add more code in lowering, that is probably good because there may be other places where this is going on but we weren't aware of. Making it a compile error seems hugely beneficial. In order to cut scope a bit could some of those branches return some unsupported error? Big downside is that could prevent some customer views from starting up that previously worked. But maybe they were previously working incorrectly?

**Comment by ggevay** [comment]
Ok, so my plan is to do 4. this week, and later do 5. in a separate PR. The main reason I would like to delay 5. is because it would create a big merge conflict with my WIP branch for aggregate window functions. So I would like to merge aggregate window functions between tackling 4. and 5.
