### ISSUE TITLE
regression: Mz hangs after a CRDB node is taken offline 

### ISSUE THREAD

**Issue by nrainer-materialize** [MaterializeInc/materialize#20753]
### Buildkite link

https://buildkite.com/materialize/nightlies/builds/2929#01898867-c233-4750-b3b5-c9629e9741dc (of `v0.62.2`)

### Relevant log output

```source
[2023-07-24T14:59:30Z] > CREATE SOURCE s_new FROM LOAD GENERATOR COUNTER (TICK INTERVAL '0.1s') WITH (SIZE ='4-4');
[2023-07-24T15:00:50Z]
[2023-07-24T15:00:50Z] 10:1: error: deadline has elapsed
[2023-07-24T15:00:50Z]      |
[2023-07-24T15:00:50Z]    9 | > DROP SOURCE IF EXISTS s_new CASCADE;
[2023-07-24T15:00:50Z]   10 | > CREATE SOURCE s_new FROM LOAD GENERATOR COUNTER (TICK INTERVAL '0.1s') WITH (SIZE ='4-4');
[2023-07-24T15:00:50Z]      | ^
!!! Error Report
[2023-07-24T15:00:50Z] 1 errors were encountered during execution
```

### Additional thoughts

Probably just a timeout. Let's see if further instances occur.

**Comment by philip-stoev** [comment]
This is a genuine regression. Bisected to the following commit:

```
commit f6e44c5811e74fb4ff2f2989e0698e60292fea42 (HEAD)
Merge: 1c6d48b225 0aa9988c4e
Author: Daniel Harrison <52528+danhhz@users.noreply.github.com>
Date:   Mon Jul 24 16:25:39 2023 -0400

    Merge pull request #20709 from danhhz/persist_crdb_nostats
    
    persist: disable crdb automatic stats on consensus table
```
Reverting the patch causes the test to succeed. 

To reproduce:

```
cd test/crdb-restarts
./mzcompose down -v ; ./mzcompose run default
```

and the first query against Mz after CRDB has been disrupted will hang.

**Comment by philip-stoev** [comment]
To clarify:

1. The failure happened once in v0.62.2, and went away on retry. The hang was later in the test.
2. The failure happened repeatedly on "main", and was bisectable to the commit above that is not present in 0.62.2 . The hang was immediate on the first disruption to CRDB.

I will try to reproduce it against v0.62.2 just in case.

**Comment by danhhz** [comment]
Wild. I can't begin to imagine how this PR would cause it, but I'll take a look

**Comment by danhhz** [comment]
it does seems to eventually start working again... ```environmentd: 2023-07-25T15:36:06.367633Z  INFO environmentd::run:environmentd::serve: mz_persist::postgres: WIP about to create consensus table
environmentd: 2023-07-25T15:36:06.389698Z  INFO environmentd::run:environmentd::serve: mz_persist::postgres: WIP finished creating consensus table
cluster-s2-replica-3: 2023-07-25T15:36:08.153779Z  INFO mz_persist::postgres: WIP about to create consensus table
cluster-s2-replica-3: 2023-07-25T15:36:08.289067Z  INFO mz_persist::postgres: WIP finished creating consensus table
cluster-u1-replica-1: 2023-07-25T15:36:15.997850Z  INFO mz_persist::postgres: WIP about to create consensus table
cluster-u1-replica-1: 2023-07-25T15:36:15.997942Z  INFO mz_persist::postgres: WIP about to create consensus table
cluster-u1-replica-1: 2023-07-25T15:36:15.997963Z  INFO mz_persist::postgres: WIP about to create consensus table
cluster-u1-replica-1: 2023-07-25T15:36:15.998006Z  INFO mz_persist::postgres: WIP about to create consensus table
cluster-u2-replica-4: 2023-07-25T15:36:16.815518Z  INFO mz_persist::postgres: WIP about to create consensus table
cluster-u2-replica-4: 2023-07-25T15:40:54.387746Z  INFO mz_persist::postgres: WIP finished creating consensus table
cluster-u2-replica-4: 2023-07-25T15:40:54.427526Z  INFO mz_persist::postgres: WIP about to create consensus table
cluster-u2-replica-4: 2023-07-25T15:40:54.427544Z  INFO mz_persist::postgres: WIP about to create consensus table
cluster-u2-replica-4: 2023-07-25T15:40:54.431533Z  INFO mz_persist::postgres: WIP about to create consensus table
cluster-u2-replica-4: 2023-07-25T15:40:54.613207Z  INFO mz_persist::postgres: WIP finished creating consensus table
cluster-u2-replica-4: 2023-07-25T15:40:54.676800Z  INFO mz_persist::postgres: WIP finished creating consensus table
cluster-u2-replica-4: 2023-07-25T15:40:54.714725Z  INFO mz_persist::postgres: WIP finished creating consensus table```
