### ISSUE TITLE
Map out Kafka "exactly once" support

### ISSUE THREAD

**Issue by frankmcsherry** [MaterializeInc/materialize#2078]
Kafka has a mechanism for "exactly once" processing, in which they commit corresponding offsets in input topics and output topics, so that on recover one can more clearly see where work got to and what output needs to be reproduced. This information could be valuable for recovery (though, strictly speaking isn't necessary on the data plane if we are acting as a deterministic transducer).

There are some contact points with @nacrooks's work on timestamping, in that this correlates input topic offsets with logical timestamps, which are likely to be the units observed at Kafka sinks and which would connect input and output offsets.

The short-term goal would be to map out the requirements and do some feasibility (who needs to know what; is this in the coordinator, is this in the workers?). From that, we might make some decisions about what actually needs to get done.

**Comment by rjnn** [comment]
I've added a 0.2 label - not that this needs to be done in 0.2, but that it needs to be mapped out before we start 0.3.

**Comment by ruchirK** [comment]
I think this https://github.com/MaterializeInc/materialize/issues/1442 is related

**Comment by cuongdo** [comment]
@benesch and @ruchirK: assigning to you, because this is likely related to source persistence

**Comment by wangandi** [comment]
The confluent blog post describing how transactions work.
https://www.confluent.io/blog/transactions-apache-kafka/

It looks like we need to interpret "transaction commit markers" that get written to partitions. Kafka expects transactional consumers to "filter out messages from aborted transactions and to not return messages which are part of open transactions."

**Comment by ruchirK** [comment]
Is this still something that needs to be done? to be honest reading the initial issue I'm not sure what the ask is other than "see if Kafka exactly-once could be useful for us" and I think someone working on CDCv2 might be in a better position to do that now?

**Comment by awang** [comment]
Yup, it's still an issue.  

There's nothing immediately actionable -- I'll take this one for now, as it's more of an issue of 
1. publishing docs & recommendations on how best to accomplish this, as well as 
2. making exactly-once support a bit more user-friendly

**Comment by awang** [comment]
marking as complete, now that we have https://github.com/MaterializeInc/materialize/issues/2915 in-progress
