### ISSUE TITLE
adapter: Cluster and cluster replica owners should be kept in sync

### ISSUE THREAD

**Issue by jkosh44** [MaterializeInc/materialize#20792]
### What version of Materialize are you using?

v0.63.0-dev

### What is the issue?

The owner of a ~~managed~~ cluster  and the owner of all the replicas in a ~~managed~~ cluster should always be the same. Currently, there's no check that does this.

~~When converting a non-managed cluster to a managed cluster we should either:~~
~~- Require that the cluster and replicas already have the same owners.~~
~~- Convert the owner of the replicas to the owner of the cluster.~~

When altering the owner of a ~~managed~~ cluster, the owner of the replicas should automatically be updated.

**Comment by jkosh44** [comment]
@antiguru Do you have any opinions on the two options listed?

**Comment by jkosh44** [comment]
Personally I lean towards forcibly altering the replica owners.

**Comment by antiguru** [comment]
I don't have a strong opinion. For the names, we require the user to supply us with the correct names, so the logical extension here would be that the user needs to own all replicas.

If we forcibly change the owner, could this have any negative implications?

**Comment by jkosh44** [comment]
> If we forcibly change the owner, could this have any negative implications?

The only negative implication I can think of is that the original owner can no longer make changes or drop the replica.

> For the names, we require the user to supply us with the correct names, so the logical extension here would be that the user needs to own all replicas.

One negative implication of this approach is that if I own a cluster, and some other user creates a replica in my cluster, then I can't alter the cluster to be managed without that other user altering their replica. This same issue applies to the names of replicas too.

If you consider `ALTER CLUSTER _ (MANAGED)` to be equivalent to `DROP CLUSTER _; CREATE CLUSTER _ (MANAGED);` Then I think it makes sense to forcibly alter the replicas because you can drop replicas without owning them and even without specifying `CASCADE`.

I think we should keep the name and owner requirements consistent for now and require a user to own all of the replicas. Do you have any thoughts on keeping the name requirements as is vs updating the code to automatically re-name replicas?

**Comment by antiguru** [comment]
> One negative implication of this approach is that if I own a cluster, and some other user creates a replica in my cluster, then I can't alter the cluster to be managed without that other user altering their replica. This same issue applies to the names of replicas too.

I think that's a great point, and a solution would be that the owner of the cluster should be automatically privileged to operate on replicas in the cluster, implying that they could change a cluster to and from managed.

> Do you have any thoughts on keeping the name requirements as is vs updating the code to automatically re-name replicas?

Automatically re-naming seems fine. I didn't implement it because it needs to be well communicated to users to avoid surprises, and the burden to match the naming pattern seems small. I imagined the main use-case for this to be something like this:

```sql
CREATE CLUSTER mycluster SIZE 'small';
ALTER CLUSTER mycluster SET (MANAGED = false);
-- Temporarily add more resources
CREATE CLUSTER REPLICA mycluster.large SIZE 'large';
-- wait until it's not needed anymore
DROP CLUSTER REPLICA mycluster.large;
ALTER CLUSTER mycluster SET (MANAGED);
```

**Comment by jkosh44** [comment]
> I think that's a great point, and a solution would be that the owner of the cluster should be automatically privileged to operate on replicas in the cluster, implying that they could change a cluster to and from managed.

Good point. I originally modeled the privileges for replicas in clusters after the privileges for views on a relation. Specifically the owner of the relation/cluster can drop the view/replica, but they cannot alter the view/replica. Additionally, with the right `CREATE` privileges, anyone can create a view/replica, even if they don't own the underlying relation/cluster.

Perhaps instead it would be better to model the privileges for replicas in clusters after the privileges for indexes on a relation. Specifically, only the owner of the relation/cluster can create an index/replica and the owner of the index/replica is always kept in sync with the relation/cluster.  That way the owner of the cluster will always be able to operate on all replicas.

**Comment by jkosh44** [comment]
> Perhaps instead it would be better to model the privileges for replicas in clusters after the privileges for indexes on a relation. Specifically, only the owner of the relation/cluster can create an index/replica and the owner of the index/replica is always kept in sync with the relation/cluster. That way the owner of the cluster will always be able to operate on all replicas.

The one downside here is that users won't be able to add replicas to the `default` cluster.

**Comment by jkosh44** [comment]
> Perhaps instead it would be better to model the privileges for replicas in clusters after the privileges for indexes on a relation. Specifically, only the owner of the relation/cluster can create an index/replica and the owner of the index/replica is always kept in sync with the relation/cluster. That way the owner of the cluster will always be able to operate on all replicas.

I've thought about this more and am convinced that it's the right thing to do. This way adding/removing a replica is treated more like altering the cluster than creating/deleting brand new objects.
