### ISSUE TITLE
testdrive: improve catalog comparison

### ISSUE THREAD

**Issue by mjibson** [MaterializeInc/materialize#20811]
testdrive includes a feature that compares some data of an in memory catalog to an on disk catalog. However it's currently a pretty small set of the data (it was probably more when that feature was written years ago). We should improve the `dump()` method of CatalogState to include nearly all of its state. There are some fields that are designed to change on startup and can't be directly compared. Perhaps dump should be a raw JSON dump of the object derived from serde. Then we implement a new function by hand that compares two catalog state objects but knows which fields to ignore.

The fix in https://github.com/MaterializeInc/materialize/issues/20796 does add GRANT and other things to the testdrive catalog checker, but because there's so little data there, that change would not have caught #20795.

This would have caught https://github.com/MaterializeInc/materialize/issues/20795.

**Comment by benesch** [comment]
Hugely in support of this. I have a long abandoned PR that once worked towards this: https://github.com/MaterializeInc/materialize/pull/5758. Almost surely no longer relevant—just wanted to flag we've been meaning to do this for 2.5 years and it'd be great to finally deliver.
