### ISSUE TITLE
Add testing for resilience against network issues

### ISSUE THREAD

**Issue by wangandi** [MaterializeInc/materialize#2089]
Determined to be a separate topic from Chaos Testing (#1130).

In addition to testing our product's resilience against failures of dependent software, it would be nice to test what happens if our product faces network issues. For example, what if one (or more) message(s) of an early timestamp is very laggy?

**Comment by wangandi** [comment]
Putting this down as a note, but it seems that https://github.com/alexei-led/pumba (Apache 2 license) might be useful for generating network issues between docker containers.

**Comment by cuongdo** [comment]
@JLDLaughlin were you planning on addressing part of this as part of your current chaos work?

**Comment by JLDLaughlin** [comment]
I am touching on this! https://github.com/MaterializeInc/materialize/pull/3303

**Comment by JLDLaughlin** [comment]
We now have tests that simulate the following network issues for the `debezium` and `kafka` Docker containers: delays, rate limits, packet loss, packet duplication, and packet corruption.

**Comment by cuongdo** [comment]
Basic network resilience testing now exists, so closing this issue. Filed #3611 as a followup
