### ISSUE TITLE
sql: secure comparison for hmac digests

### ISSUE THREAD

**Issue by benesch** [MaterializeInc/materialize#20929]
*Part of the webhooks epic (#19951).*

When users create a webhook source, they'll need to provide a `CHECK` expression that validates the incoming HTTP request. The most common validation involves applying an `hmac` digest to the request body and comparing it to a digest provided as a header.

But comparing `hmac` digests is delicate business:

  * https://materializeinc.slack.com/archives/C036E6WT6KE/p1689962970358839?thread_ts=1689706365.418549&cid=C036E6WT6KE
  * https://web.archive.org/web/20160203044316/https://www.nccgroup.trust/us/about-us/newsroom-and-events/blog/2011/february/double-hmac-verification/

We should consider adding either or both:

 * An `hmac_eq(data1 text, data2 text, key text, type text) -> bool` function that implements the double-HMAC approach described in the above article. (And analogously for `bytea`.)
 * A `constant_time_eq(data1 any, data2 any) -> bool` function that uses [`subtle`](https://docs.rs/subtle/latest/subtle/trait.ConstantTimeEq.html) to implement constant-time equality. Latacora has signed off on `subtle` correctly implementing constant-time equality.

cc @ParkMyCar

**Comment by benesch** [comment]
> * A `constant_time_equals(data1 any, data2 any) -> bool` function that uses [`subtle`](https://docs.rs/subtle/latest/subtle/trait.ConstantTimeEq.html) to implement constant-time equality. Latacora has signed off on `subtle` correctly implementing constant-time equality.

I think this is my preference given that Latacora is signed off on it, as it's more general purpose than `hmac_equals`.

**Comment by matthewarthur** [comment]
#22832
