### ISSUE TITLE
sql: support `max_identifier_length` session variable

### ISSUE THREAD

**Issue by benesch** [MaterializeInc/materialize#20931]
### Feature request

PostgreSQL has a compile-time constant that sets the maximum identifier length. Its default value is 63, which is the value that nearly every PostgreSQL server uses.

Materialize has no such limit, and we leverage this to good effect. For example, our dbt adapter disables the temporary name truncation that is required by dbt-postgres: https://github.com/MaterializeInc/materialize/pull/16243

Unfortunately, in other situations, tools run `SHOW max_identifier_length`, which today is not a session variable that Materialize supports. We have two ways of implementing this:

  1. Return `63` to match PostgreSQL, but continue to have no actual limit on identifier length.
  2. Pick a number that is large enough to be effectively unlimited (e.g., 16384), report that in `SHOW max_identifier_length`, _and_ enforce that limit on identifier length

(2) is my preference, but we may need to thread the needle a bit. Reporting an identifier length of 16384 might cause psqlODBC to allocate buffers for each identifier of size 16384, which is going to use 256 times more memory than it would have if the maximum identifier length was 63. Snowflake has a maximum identifier length of 255, so maybe we should aim for the same. 

(2) is a backwards incompatible change, and we'd need to be careful not to break any existing SQL queries that users are running.

Note that we already _do_ have a limit on the maximum SQL query size (1MB), which means in practice large identifiers are not that useful as you can't have that many of them in a single SQL query, and any single identifier is limited to ~1MB in size.

cc @sthm

**Comment by sthm** [comment]
Given that there is a precedent for 255, I think it is most reasonable to aim for that. It's not backward compatible, but I plan to run the following query against all existing environments to verify that there isn't currently any identifier exceeding that limit.

```
WITH identifier_length AS (
    SELECT length(name) FROM mz_catalog.mz_cluster_replicas
    UNION ALL
    SELECT length(name) FROM mz_catalog.mz_clusters
    UNION ALL
    SELECT length(name) FROM mz_catalog.mz_columns
    UNION ALL
    SELECT length(name) FROM mz_catalog.mz_connections
    UNION ALL
    SELECT length(name) FROM mz_catalog.mz_databases
    UNION ALL
    SELECT length(name) FROM mz_catalog.mz_functions
    UNION ALL
    SELECT length(name) FROM mz_catalog.mz_indexes
    UNION ALL
    SELECT length(name) FROM mz_catalog.mz_materialized_views
    UNION ALL
    -- this includes the most of the others, but better save than sorry
    SELECT length(name) FROM mz_catalog.mz_objects
    UNION ALL
    SELECT length(name) FROM mz_catalog.mz_relations
    UNION ALL
    SELECT length(name) FROM mz_catalog.mz_roles
    UNION ALL
    SELECT length(name) FROM mz_catalog.mz_schemas
    UNION ALL
    SELECT length(name) FROM mz_catalog.mz_secrets
    UNION ALL
    SELECT length(name) FROM mz_catalog.mz_sinks
    UNION ALL
    SELECT length(name) FROM mz_catalog.mz_sources
    UNION ALL
    SELECT length(name) FROM mz_catalog.mz_tables
    UNION ALL
    SELECT length(name) FROM mz_catalog.mz_types
    UNION ALL
    SELECT length(name) FROM mz_catalog.mz_views
)

SELECT max(length) FROM identifier_length;
```

**Comment by sthm** [comment]
Confirmed for staging that the max identifier length is 82.

```
for env in `tsh db ls -f json | jq -r '.[].metadata.name' | grep staging`; do 
tsh db connect --db-user=mz_introspection --db-name=materialize $env <<EOF
...

SELECT max(length) FROM identifier_length;
EOF
done
```
