### ISSUE TITLE
storage/envelopes: consider new Striim envelope

### ISSUE THREAD

**Issue by benesch** [MaterializeInc/materialize#20957]
## Background

[Striim](https://www.striim.com) is a real-time CDC tool. Think of it like Fivetran but real-time.

We're exploring an integration between Striim and Materialize. The usual caveats of source integrations apply. Materialize is not a good native target for Striim because its tables are too limited: no primary keys and no schema changes. But what's interesting about Striim is that it natively supports writing to Kafka. What's doubly interesting is that we believe it to be more pedantic than Debezium about ensuring exactly once delivery, which means that we could avoid the memory overhead of the upsert envelope that we use to filter out duplicates due to Debezium's at-least once delivery.

## Proposal

Prototype support for `ENVELOPE STRIIM`, which decodes Striim's [`WAEvent`](https://www.striim.com/docs/en/parsing-the-data-field-of-waevent.html) envelope. This envelope is similar to Debezium's envelope, but it uses the field name `data` in place of `after`.

Unlike `ENVELOPE DEBEZIUM`, `ENVELOPE STRIIM` would not create an upsert operator, because we believe Striim provides exactly-once delivery. (See open questions below, though.) When processing an update, the Striim envelope would produce a -1 diff for the `before` row and a +1 diff for the `data` row. On restart, the source would simply resume reading from where it left off. 

## Scope and priority

I think a prototype of this could be built with just a few days of work.

Priority TBD. cc @dseisun-materialize @morsapaes 

## Open questions

* Does Striim truly provide exactly-once delivery? [This blog post](https://www.striim.com/blog/kafka-stream-processing-with-striim/#:~:text=%E2%80%8B%E2%80%8BStriim%20delivers%20built,with%20no%20duplicates%20(E1P).) looks promising.
* Does Striim handle TOASTed data with PostgreSQL?

## Activity log

* **21 February 2024.** Split out work item to document MVP integration that requires no changes to Materialize or Striim: https://github.com/MaterializeInc/materialize/issues/25447. Kicking this issue back to "Later" in the storage team's roadmap.

**Comment by guswynn** [comment]
The exactly-once docs seems pretty convincing

I imagine this can be based on the still-existing non-upsert-debezium operator, probably sharing code

**Comment by benesch** [comment]
> The exactly-once docs seems pretty convincing

Indeed! We talked live to the Striim team, too, and I after the conversation I was fully convinced of the correctness of their approach.

**Comment by benesch** [comment]
For anyone following along internally, here's the Slack channel to join: https://materializeinc.slack.com/archives/C05PT7214AD

**Comment by uce** [comment]
Moving this to Icebox, because we don't have capacity to look into this right now. Please complain if that's a problem.

**Comment by benesch** [comment]
Quick status update. @bobbyiliev, @sploiselle, and I were able to get data flowing from MySQL -> Striim -> Kafka -> Materialize using JSON and a simulation of `ENVELOPE STRIIM FORMAT JSON`:

```
CREATE SOURCE users;
FROM KAFKA CONNECTION k (TOPIC 'users')
FORMAT JSON
ENVELOPE NONE;

ALTER SYSTEM SET enable_repeat_row = false;
SELECT
    (r->'data'->>'id')::int4 AS id, 
    (r->'data'->>'email')::text AS email, 
    (r->'data'->>'is_vip')::boolean AS is_vip,
    (r->'data'->>'created_at')::timestamp AS created_at,
    (r->'data'->>'updated_at')::timestamp AS updated_at
FROM s, jsonb_array_elements(data) r;
UNION ALL
SELECT
    (r->'before'->>'id')::int4 AS id, 
    (r->'before'->>'email')::text AS email, 
    (r->'before'->>'is_vip')::boolean AS is_vip,
    (r->'before'->>'created_at')::timestamp AS created_at,
    (r->'before'->>'updated_at')::timestamp AS updated_at
FROM s, jsonb_array_elements(data) r, repeat_row(-1)
WHERE r->'before' <> 'null';
```

We'd like this to instead work via Avro, but we're blocked on Striim helping us figure out how to get their Avro formatter to publish schemas to a schema registry.

Details here: https://www.notion.so/materialize/Striim-MySQL-Kafka-CSR-addb53b6271e4ace96abf30b8a142144

**Comment by benesch** [comment]
We're finally unblocked here, thanks to Striim support.  Details in the aforementioned Notion document: https://www.notion.so/materialize/Striim-MySQL-Kafka-CSR-addb53b6271e4ace96abf30b8a142144

Here's the tl;dr demonstrating that we can load Avro-formatted data from Striim in with `ENVELOPE NONE`:

```sql
CREATE SOURCE src
FROM KAFKA CONNECTION kafka_conn (TOPIC 'striim_topic')
FORMAT AVRO
USING CONFLUENT SCHEMA REGISTRY CONNECTION csr_conn
-- Because Striim uses nonstandard subject names in the 
-- schema registry, Materialize can't find the schema by
-- default. Instead we have to manually supply the schema
-- ID to use.
--
-- Replace `schema-registry` and `shop.users` below with the 
-- appropriate values in your environment:
--     curl schema-registry:8081/subjects/shop.users/versions/latest | jq .id
VALUE STRATEGY ID 1;

-- TODO: support ENVELOPE STRIIM
-- https://github.com/MaterializeInc/materialize/issues/20957
```

Here's an example of the Avro schema generated by Striim:

```json
{
  "type": "record",
  "name": "users",
  "namespace": "shop",
  "fields": [
    {
      "name": "data",
      "type": [
        "null",
        {
          "type": "record",
          "name": "data_record",
          "namespace": "data_record_namespace",
          "fields": [
            {
              "name": "ID",
              "type": [
                "null",
                "int"
              ],
              "aliases": [
                "id"
              ]
            },
            {
              "name": "EMAIL",
              "type": [
                "null",
                "string"
              ],
              "aliases": [
                "email"
              ]
            },
            {
              "name": "IS_VIP",
              "type": [
                "null",
                "int"
              ],
              "aliases": [
                "is_vip"
              ]
            },
            {
              "name": "CREATED_AT",
              "type": [
                "null",
                "string"
              ],
              "aliases": [
                "created_at"
              ]
            },
            {
              "name": "UPDATED_AT",
              "type": [
                "null",
                "string"
              ],
              "aliases": [
                "updated_at"
              ]
            }
          ]
        }
      ]
    },
    {
      "name": "before",
      "type": [
        "null",
        {
          "type": "record",
          "name": "before_record",
          "namespace": "before_record_namespace",
          "fields": [
            {
              "name": "ID",
              "type": [
                "null",
                "int"
              ],
              "aliases": [
                "id"
              ]
            },
            {
              "name": "EMAIL",
              "type": [
                "null",
                "string"
              ],
              "aliases": [
                "email"
              ]
            },
            {
              "name": "IS_VIP",
              "type": [
                "null",
                "int"
              ],
              "aliases": [
                "is_vip"
              ]
            },
            {
              "name": "CREATED_AT",
              "type": [
                "null",
                "string"
              ],
              "aliases": [
                "created_at"
              ]
            },
            {
              "name": "UPDATED_AT",
              "type": [
                "null",
                "string"
              ],
              "aliases": [
                "updated_at"
              ]
            }
          ]
        }
      ]
    },
    {
      "name": "metadata",
      "type": [
        "null",
        {
          "type": "map",
          "values": [
            "null",
            "string"
          ]
        }
      ]
    },
    {
      "name": "userdata",
      "type": [
        "null",
        {
          "type": "map",
          "values": [
            "null",
            "string"
          ]
        }
      ]
    },
    {
      "name": "datapresenceinfo",
      "type": [
        "null",
        {
          "type": "record",
          "name": "datapresenceinfo_record",
          "namespace": "datapresenceinfo_record",
          "fields": [
            {
              "name": "ID",
              "type": "boolean"
            },
            {
              "name": "EMAIL",
              "type": "boolean"
            },
            {
              "name": "IS_VIP",
              "type": "boolean"
            },
            {
              "name": "CREATED_AT",
              "type": "boolean"
            },
            {
              "name": "UPDATED_AT",
              "type": "boolean"
            }
          ]
        }
      ]
    },
    {
      "name": "beforepresenceinfo",
      "type": [
        "null",
        {
          "type": "record",
          "name": "beforepresenceinfo_record",
          "namespace": "beforepresenceinfo_record",
          "fields": [
            {
              "name": "ID",
              "type": "boolean"
            },
            {
              "name": "EMAIL",
              "type": "boolean"
            },
            {
              "name": "IS_VIP",
              "type": "boolean"
            },
            {
              "name": "CREATED_AT",
              "type": "boolean"
            },
            {
              "name": "UPDATED_AT",
              "type": "boolean"
            }
          ]
        }
      ]
    },
    {
      "name": "__striimmetadata",
      "type": {
        "type": "record",
        "name": "StriimMeta_Record",
        "fields": [
          {
            "name": "position",
            "type": [
              "null",
              "string"
            ]
          }
        ]
      }
    }
  ]
}
```

So `ENVELOPE STRIIM` would want to sniff out the `before` and `data` fields, turn the `before` field into a -1, and the `data` field into a +1. Seems relatively tractable. We would be relying on Striim to get the before image exactly right all the time, or invalid retractions will appear in the source.

The alternative to consider: tell users to install the table's primary key as the Kafka message key, and use "Format As: Table". Then create the source with `ENVELOPE UPSERT` in Materialize. This works today!

@morsapaes @bobbyiliev I propose that we leave this integration here for now. I.e., we write up some docs describing how to set this up with `ENVELOPE UPSERT`, but punt on building out `ENVELOPE STRIIM` for now. The downside is that upsert sources are more expensive than `ENVELOPE STRIIM` sources would be, because we have to store the upsert state in memory. But the upside is that we don't need to invest eng time to build out `ENVELOPE STRIIM` until someone's actively asking for it, and we don't need to stress about Striim sending us bad `before` data that causes invalid retractions in the source.

**Comment by morsapaes** [comment]
Closing as not planned. We've added an integration guide to the documentation that uses the Kafka source + `ENVELOPE UPSERT` (#25711), and are in touch with the Striim team about building a direct integration.
