### ISSUE TITLE
[Epic] Implement a persist backed catalog

### ISSUE THREAD

**Issue by jkosh44** [MaterializeInc/materialize#20953]
## Motivation

One of the goals of Platform v2 is use case isolation. The serving layer currently does not provide use case isolation. All queries are served through a single `environmentd` process that uses a single `Coordinator` thread to linearize all operations. We'd like to be able to create a serving layer that can provide some form of isolation to users, i.e. serving user A does not negatively impact serving user B.

In order to achieve this isolated serving layer, we need one process in the serving layer to be able to respond to catalog/state changes made by another process in the serving layer.

## Context

The [stash](https://github.com/MaterializeInc/materialize/tree/main/src/stash) is a durable key value store that has some properties of a TVC. It is implemented using CockroachDB. Currently all of its users treat it as a key value store and do not use the timestamp or diff information.

A stash collection is the stash's abstraction that is roughly equivalent to a table. All key value pairs in a stash collection have the same binary format.

At a high level the stash has the following users:

- The Coordinator uses it to store durable catalog information. This user is the motivator of this change.
- The Controller uses it to store durable metadata.
- The stash-debug tool uses it to read and modify the current contents.

At a slightly lower level, the stash has the users listed below. Along with each user, I've included a list of operations that each user currently use the stash for. Each of these operations need to fail if the stash has lost leadership. 

### Controller:

- Upsert multiple keys into a single collection.
- Insert without overwrite for multiple keys into a single collection.
- Delete multiple keys from a single collection.
- Read multiple keys from multiple collections.

### Stash debug tool

- Read all collection names.
- Delete a single key from a single collection.
- Upsert a single key into a single collection.
- Read multiple keys from multiple collections.

### Catalog Storage Connection

This is the Coordinator's abstraction that wraps the stash and provides single statement operations. The name is a bit confusing but it's unrelated to storage.

- Upsert multiple keys to a single collection.
- Read multiple keys from a single collection.
- Confirm stash leadership (Note: in the final platform v2 vision this will be unnecessary, but while transitioning it is still required).
- Delete multiple keys from a single collection, based on a predicate of the values (i.e. read then write).

### Catalog Storage Transaction

This is the Coordinator's abstraction that wraps the stash and provides transactions against the stash. The name is a bit confusing but it's unrelated to storage.

- Read multiple keys from multiple collections.
- Append multiple keys to multiple collections (i.e. insert, update, or delete depending on the specific key).

### Catalog Storage Init/Migrate

This is the process at startup that initializes the catalog's stash and potentially migrates the contents of the stash.

- Arbitrary read/write transactions.

This usage will likely be the most difficult to port over to persist. Fundamentally it should be possible to convert the catalog initialization/Migrate to do the following:
  
  1. Read the current contents of the stash into memory (if any exists).
  2. Perform migrations in memory or prepare initial data in memory.
  3. Write out everything to the stash.

This would be much easier to implement using persist.

Also note, that the current migration code is a bit tangled within the stash implementation and the adapter crate. See https://github.com/MaterializeInc/materialize/issues/20922

## Approach

At a high level the approach I plan on taking is as follows: 

1. Create a stash trait based on the operations listed above and implement it using the current CockroachDB stash. 
2. Port over all of the stash users to only interact with the stash through the trait.
3. Implement the trait using persist.

This will let us compare the performance and correctness of the persist stash on a one-to-one basis with the CockroachDB stash. We could even have a shadow implementation of the trait that wraps both the CockroachDB and persist implementations and compare the results while running.

**Comment by mjibson** [comment]
Persist does not provide multi-shard transactions. Does this mean that the persist impl would put a single stash into one shard?

Overall this sounds like a safe approach. I expect the transaction parts to take a fair amount of effort. Removal of our previous stash trait was done when we added the transaction APIs because they are not pleasant to maintain, and we were able to shunt the work off into cockroach's transaction layer.

**Comment by jkosh44** [comment]
> Persist does not provide multi-shard transactions. Does this mean that the persist impl would put a single stash into one shard?

That's the idea for now, we'd store everything as raw bytes and use the existing protobuf mechanics to serialize/deserialize. Persist is working on multi-shard transactions, so if that might change in the future.

**Comment by jkosh44** [comment]
One question that I've been grappling with for the past couple of days/weeks is where should the trait live. The two options that I see are

## `mz_stash`

The trait would present a generic key-value store with TVC properties, like the current stash implementation and the old stash trait.

### Pros

- We can re-use existing stash migration implementation.
- We can re-use existing stash-debug tool.
- We can migration the controller to the persist backed stash for free.

### Cons

- Adds a lot of complexity to the persist implementation.
- As @mjibson points out 
> I expect the transaction parts to take a fair amount of effort. Removal of our previous stash trait was done when we added the transaction APIs because they are not pleasant to maintain, and we were able to shunt the work off into cockroach's transaction layer.

## `mz_adapter::catalog::storage`

The trait would be very specific to the durable coordinator state and have methods like `get_item(&self, gid: &GlobalId)` and `set_item(&mut self, gid: GlobalId, item: Item)`. One implementation would use the existing stash and the other would use persist without a generic stash API.

### Pros

- Much simpler to implement and maintain than a generic trait.

### Cons

- We'd have to re-implement the stash-debug tool.
- We'd have to re-implement or port over stash migrations.
- The controller would have to either stay on the old stash implementation or have it's own custom persist implementation. 

----

I originally thought that the trade-offs made `mz_stash` the better approach, but as I look into it more I'm starting to think that `mz_adapter::catalog::storage` is the better approach.

Let me know if anyone has thoughts on this.

**Comment by jkosh44** [comment]
Here's another pro for `mz_adapter::catalog::storage`. The Coordinator maintains the entire catalog state in memory via the `CatalogState` struct. Then for each catalog transaction it starts a catalog storage transaction, which reads the entire stash state into memory. Effectively we end up with two copies of the same thing in memory, and we wast cycles reading the stash into memory when the `CatalogState` is effectively equivalent.

Doing the durability work directly in `mz_adapter::catalog::storage`, may make it easier to merge these two concepts into a single struct.

**Comment by jkosh44** [comment]
Here is a very rough prototype of the `mz_adapter::catalog::storage` approach: https://github.com/MaterializeInc/materialize/pull/21071
