### ISSUE TITLE
Create a builtin view for object creation time

### ISSUE THREAD

**Issue by RobinClowers** [MaterializeInc/materialize#20983]
### Feature request

The console shows the created date for objects, which we have to get from `mz_audit_events`, which is fairly slow.

Something like this would solve it:

```
CREATE VIEW mz_internal.mz_object_creation_time AS 
    SELECT 
        a.details ->> id,
        a.occurred_at AS created_at
    FROM mz_catalog.mz_audit_events a
    WHERE z.event_time = 'create';
```

Though I wonder if we can come up with something a bit more generic that includes other object metadata we might need access to.

**Comment by benesch** [comment]
This makes a lot of sense to me!

**Comment by benesch** [comment]
Yes!
