### ISSUE TITLE
adapter: Clean up SUBSCRIBE lifecycle

### ISSUE THREAD

**Issue by jkosh44** [MaterializeInc/materialize#21081]
The lifecycle of a `SUBSCRIBE` in the ADAPTER is confusing to readers and the code itself seems to be confused about what's going on.

This issue came from discussion in: https://github.com/MaterializeInc/materialize/pull/17475

## State

The Coordinator stores metadata about all active connections in `active_conns`

https://github.com/MaterializeInc/materialize/blob/4c8430f978d46bfa5d94af65bb9583abe4495ce0/src/adapter/src/coord.rs#L779-L781

`ConnMeta` stores all subscribe backing compute sinks in `drop_sinks`. These sinks eventually need to be dropped in compute to clean up the subscribe state.

https://github.com/MaterializeInc/materialize/blob/4c8430f978d46bfa5d94af65bb9583abe4495ce0/src/adapter/src/coord.rs#L506-L508

The Coordinator additionally stores all active subscriptions in `active_subscribes`

https://github.com/MaterializeInc/materialize/blob/4c8430f978d46bfa5d94af65bb9583abe4495ce0/src/adapter/src/coord.rs#L819-L820

The controller/compute additionally maintains some state for subscribes.

## Creation

Subscribes get initialized in the sequencer which sets the Coordinator state as well as creates the subscribe in compute.

https://github.com/MaterializeInc/materialize/blob/4c8430f978d46bfa5d94af65bb9583abe4495ce0/src/adapter/src/coord/sequencer/inner.rs#L2640-L2677

https://github.com/MaterializeInc/materialize/blob/4c8430f978d46bfa5d94af65bb9583abe4495ce0/src/adapter/src/coord/sql.rs#L196-L215

This all seems sane and works well (in my opinion).

## Deletion

The Coordinator state gets cleaned up in `remove_active_subscribe`:

https://github.com/MaterializeInc/materialize/blob/4c8430f978d46bfa5d94af65bb9583abe4495ce0/src/adapter/src/coord/sql.rs#L217-L233

Note the comment about how drop sinks are removed at commit time. 

The controller/compute state gets cleaned up in `drop_compute_sinks`:

https://github.com/MaterializeInc/materialize/blob/4c8430f978d46bfa5d94af65bb9583abe4495ce0/src/adapter/src/coord/ddl.rs#L534-L575

Note that the sink isn't dropped unless it is found in `self.active_subscribes`, and the sink was removed from `self.active_subscribes` in `remove_active_subscribe`. So the comment in `remove_active_subscribe` about drop sinks getting dropped during commit time is inaccurate, because it prevents the sinks from being dropped by removing them from `self.active_subscribes`. This is what caused the issue in https://github.com/MaterializeInc/materialize/pull/17475.

`remove_active_subscribe` get's called when the controller tells us it's OK to remove the subscribe.

https://github.com/MaterializeInc/materialize/blob/4c8430f978d46bfa5d94af65bb9583abe4495ce0/src/adapter/src/coord/message_handler.rs#L256-L270

`drop_compute_sinks` get's called also when the controller tells us it's OK to remove the subscribe: 

https://github.com/MaterializeInc/materialize/blob/4c8430f978d46bfa5d94af65bb9583abe4495ce0/src/adapter/src/coord/message_handler.rs#L256-L270

or when a subscribe dependency is dropped 

https://github.com/MaterializeInc/materialize/blob/4c8430f978d46bfa5d94af65bb9583abe4495ce0/src/adapter/src/coord/ddl.rs#L370-L385

or when someone calls `DISCARD ALL`

https://github.com/MaterializeInc/materialize/blob/4c8430f978d46bfa5d94af65bb9583abe4495ce0/src/adapter/src/coord/sequencer.rs#L388-L405

or when clearing out transaction state

https://github.com/MaterializeInc/materialize/blob/4c8430f978d46bfa5d94af65bb9583abe4495ce0/src/adapter/src/coord/sql.rs#L175-L194

We clear transaction state when terminating a connection

https://github.com/MaterializeInc/materialize/blob/4c8430f978d46bfa5d94af65bb9583abe4495ce0/src/adapter/src/coord/command_handler.rs#L805-L832

or when we commit a transaction

https://github.com/MaterializeInc/materialize/blob/4c8430f978d46bfa5d94af65bb9583abe4495ce0/src/adapter/src/coord/sequencer/inner.rs#L1837-L1848

Calling `drop_compute_sinks` will cause the controller to send us a message saying that it's OK to remove the subscribe, which will cause us to call `drop_compute_sinks` again and clean up the Coordinator state via `remove_active_subscribe`. That how the Coordinator state is cleaned up during query cancellation, session termination, dependency dropping, and `DISCARD ALL`.

The logic here is rather confusing and circular, and there are parts of the code (at least the comments) that seem to be written with a misunderstanding about how other parts of the code work.

**Comment by teskje** [comment]
Some more relevant discussion in https://github.com/MaterializeInc/materialize/issues/16121#issuecomment-1902838309.

I think we should refactor this logic:
* In adapter, remove subscribe state immediately when the subscribe is dropped. If it was not cancelled by the user (but by, e.g. a dependent relation getting dropped), terminate the subscribe query with an error too.
* In the compute controller, stop sending responses for subscribes that have been dropped.

**Comment by benesch** [comment]
The way subscribes are _canceled_ on current main is particularly twisty. Sending on the cancellation tx...

https://github.com/MaterializeInc/materialize/blob/b73cf12afac9a1b577e5a4be87f572b4e5a51080/src/adapter/src/coord/command_handler.rs#L926-L927

...is observed by the pgwire protocol handler, which cancels the subscribe, which then commits the transaction, which then drops all outstanding subscribes for the transaction, which then tells the controller to actually drop the subscribe, which eventually sends a response back up to the adapter which causes it to abort the subscribe.

**Comment by benesch** [comment]
I put up https://github.com/MaterializeInc/materialize/pull/25179, which straightens out the lifecycle enough that I think we could call this issue closed.
