### ISSUE TITLE
`DEBUG` vs. `NOTICE` in `SHOW SOURCES`

### ISSUE THREAD

**Issue by vmarcos** [MaterializeInc/materialize#21112]
### Feature request

This issue was first observed in the SQL Shell as MaterializeInc/console#590.

When typing `SHOW SOURCES`, the SQL Shell returns the result plus a message `DEBUG: query was automatically run on the "mz_introspection" cluster`. Totally subjective, but as a user, I'd be a bit confused about the use of `DEBUG`, since we are not "debugging" anything at this point. Perhaps just call it a `NOTICE`?

@RobinClowers

**Comment by chaas** [comment]
We suppress these notices in the shell now, so closing as stale.
