### ISSUE TITLE
doc/user: add integration guides for notebooks

### ISSUE THREAD

**Issue by morsapaes** [MaterializeInc/materialize#21195]
[Deepnote](https://deepnote.com/) and [Hex](https://hex.tech/) have shipped Materialize branded connectors, which are extensions of their existing PostgreSQL connector.

Let's add integration guides to the documentation!

- [x] Deepnote (see [their documentation](https://deepnote.com/docs/materialize))
- [x] Hex (see [their documentation](https://hex.tech/product/integrations/materialize/))

## Guidance
As you pick up this issue, make sure to:

* Follow a structure similar to [this guide](https://materialize.com/docs/manage/monitor/datadog/).
* Double-check the documentation on their end, and reach out in the shared Slack channels if you find bits and pieces that need patching.

**Comment by joacoc** [comment]
Both have been merged!
