### ISSUE TITLE
Dependencies not recorded correctly

### ISSUE THREAD

**Issue by RobinClowers** [MaterializeInc/materialize#21207]
### What version of Materialize are you using?

v0.65.0 (977b26f5e)

### What is the issue?

Newly created objects (materialized views specifically, though I think other objects as well) don't seem to be written to the `mz_object_dependencies` table:

```sql
CREATE CLUSTER test SIZE = '3xsmall';
SET CLUSTER TO test;
CREATE MATERIALIZED VIEW mv AS
SELECT 1;
SELECT * FROM mz_internal.mz_object_dependencies WHERE referenced_object_id = 'u11';
 object_id | referenced_object_id
-----------+----------------------
(0 rows)
```

Existing objects still show up as expected:

```sql
SELECT * FROM mz_internal.mz_object_dependencies WHERE referenced_object_id = 'u4';
 object_id | referenced_object_id
-----------+----------------------
 u5        | u4
 u9        | u4
```

**Comment by jkosh44** [comment]
Can you include a dump of the `mz_objects` view? Otherwise it's hard to tell what the expected output of the queries with hard-coded IDs are.

Is `u11` the ID of the cluster? If so, this might be an instance of https://github.com/MaterializeInc/materialize/issues/21041. `mz_object_dependencies` only includes objects found in `mz_objects`, which does not include clusters (https://materialize.com/docs/sql/system-catalog/mz_internal/#mz_object_dependencies)

**Comment by jkosh44** [comment]
Also I think the docs,

> The mz_object_dependencies table describes the dependency structure between all database objects in the system.

is a bit misleading since it does not include:
- roles
- databases
- schemas
- clusters
- cluster replicas.

**Comment by jkosh44** [comment]
If you want all the objects in a cluster, you'll have to do something like this (I just made this up and didn't check for syntax errors so you might need to tweak it a bit):

```SQL
SELECT id FROM (
  SELECT id, cluster_id FROM mz_sinks
  UNION ALL
  SELECT id, cluster_id FROM mz_sources
  UNION ALL
  SELECT id, cluster_id FROM mz_materialized_views
  UNION ALL
  SELECT id, cluster_id FROM mz_indexes
)
WHERE cluster_id = 'u11';
```

**Comment by RobinClowers** [comment]
Apologies for the lack of clarity. `u11` is the ID of the cluster, I was indeed under the impression that `mz_object_dependencies` included clusters. It looks like my other test case (`u4`) appeared to work, because there is a different object with that ID, which does appear in `mz_object_dependencies`.
