### ISSUE TITLE
"CRDB rolling restarts" is flaky

### ISSUE THREAD

**Issue by nrainer-materialize** [MaterializeInc/materialize#21235]
### Buildkite link

https://buildkite.com/materialize/nightlies/builds/3353#018a04a2-c158-4de3-8614-088ab79acbd1

### Relevant log output

```source
> CREATE SOURCE s_new FROM LOAD GENERATOR COUNTER (TICK INTERVAL '0.1s') WITH (SIZE ='4-4');
10:1: error: deadline has elapsed
     |
   9 | > DROP SOURCE IF EXISTS s_new CASCADE;
  10 | > CREATE SOURCE s_new FROM LOAD GENERATOR COUNTER (TICK INTERVAL '0.1s') WITH (SIZE ='4-4');
     | ^
!!! Error Report
```

### Additional thoughts

Should we increase the timeout?
Required two retries to get it green.

**Comment by nrainer-materialize** [comment]
Further occurrences:
* https://buildkite.com/materialize/nightlies/builds/3406#018a1718-56b0-4b5f-867e-acdc777151d2

**Comment by philip-stoev** [comment]
Fixed by https://github.com/MaterializeInc/materialize/pull/21365
