### ISSUE TITLE
support all casts, and until then, warn in docs that this is a work in progress

### ISSUE THREAD

**Issue by rjnn** [MaterializeInc/materialize#2127]
Currently, the 'casts' page lists a set of valid casts. The remaining casts are unsupported because we haven't gotten around to it yet, not because of any inherent technical limitation. I just ran into an unsupported cast. As a temporary workaround, the docs page should call out that the limitations are just because we're at 0.1, and not that there's anything inherently impossible in Materialize.

One example is that we cannot currently cast from anything to date or time types, which is frustrating.

**Comment by benesch** [comment]
Are you using the latest master? Pretty sure this is fixed.

**Comment by rjnn** [comment]
Nope, I tested brew installation instructions, I'm still on 0.1.0. Thanks for the note!

**Comment by benesch** [comment]
Hmm, brew should be shipping 0.1.1 these days. Can you try `brew upgrade materialized`? Not that 0.1.1 has the feature you want; but worried that something is broken with tap updating. 

Are there other casts you think are important? I don’t think “all casts” is particular actionable, now that we support the text -> everything casts.

**Comment by rjnn** [comment]
nope, this is all my fault, I haven't run `brew upgrade` since 0.1.1 shipped.

I don't think this issue is actionable. Closed. Thanks!
