### ISSUE TITLE
sqlsmith does not consider the `avg_internal_v1` function to be an aggregate

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#21295]
### What version of Materialize are you using?

HEAD

### What is the issue?

SQLsmith does not consider the `avg_internal_v1` function to be an aggregate, and therefore tries to put it in places where aggregate functions are not allowed.

```
--- [SQLsmith] Error XX000: ERROR:  WHERE clause error: aggregate functions are not allowed in WHERE clause (function [s249 AS pg_catalog.sum])
 (1486 occurences)
From 11:42:02 until 12:31:24
Query: select  
  subq_0."c0" as c0, 
  pg_catalog.session_user() as c1, 
  subq_0."c0" as c2
from 
  (select  
        ref_0."schema_id" as c0
      from 
        mz_catalog.mz_tables as ref_0
      where (mz_catalog.avg_internal_v1(
          CAST(INTERVAL '1' MINUTE as interval))) < (case when ((select pg_catalog.min("d") from public.t)
              ) > ((select "d" from public.t limit 1 offset 1)
              ) then mz_catalog.mz_uptime() else mz_catalog.mz_uptime() end
          )
      limit 164) as subq_0
where (true) 
```

This needs to be fixed on the sqlsmith side, but we will silence it in test/sqlsmith/mzcompose.py in the meantime.

**Comment by ParkMyCar** [comment]
For reference I added `avg_internal_v1` in https://github.com/MaterializeInc/materialize/pull/21219. Is someone from the QA side already fixing sqlsmith, or would y'all like me to pick this up?

**Comment by philip-stoev** [comment]
@ParkMyCar we will fix it on our side. We first need to move SQLSmith into the MaterializeInc organization .

**Comment by def-** [comment]
I have moved SQLsmith to MaterializeInc org, will now fix this.

**Comment by def-** [comment]
@ParkMyCar Do we have an internal view/table that contains whether a function is an aggregate? Currently I'm hard-coding the list, fix is here: https://github.com/MaterializeInc/sqlsmith/commit/2e12dd959940112a59fc89c9ccd5a404568cddb9
