### ISSUE TITLE
Improve the speed of Avro parsing

### ISSUE THREAD

**Issue by umanwizard** [MaterializeInc/materialize#2133]
>placeholder text

**Comment by cuongdo** [comment]
Is it time to dust off #587 ?

**Comment by rjnn** [comment]
Now that we've cleared some air and are reconsidering performance works, should this be something that is re-triaged? cc @frankmcsherry @awang @benesch

**Comment by benesch** [comment]
I think Brennan has been trying to get to this for multiple weeks now, but higher priority items keeping popping up. But it seems like it's in the cards for the near future?

**Comment by umanwizard** [comment]
Yep, this is in progress! Should have something out soon.
