### ISSUE TITLE
[webhook] Expose URLs for webhook sources

### ISSUE THREAD

**Issue by ParkMyCar** [MaterializeInc/materialize#21343]
### Feature request

We should expose the URLs for webhook sources in some way, e.g. maybe a table called `mz_webhook_sources`.

**Comment by benesch** [comment]
100%! But please start the table in `mz_internal` so we can iterate on its exact schema.

**Comment by chaas** [comment]
Also +1 this! We have similar catalog table for the privatelink principal called `mz_aws_privatelink_connections` that users have found very useful.
Agree to keeping this in `mz_internal` since we're sticking to public preview for webhooks for now.
