### ISSUE TITLE
sql: block tutorials from executing non-load generator `CREATE SOURCE` statements

### ISSUE THREAD

**Issue by JLDLaughlin** [MaterializeInc/materialize#21435]
### Feature request

When a prospect is in a tutorial, don't allow them to create non-load generator sources.

When a user tries to create a different class of source, we should return an error that tells them to reach out. Copy idea (we can work on it):

> CREATE SOURCE disabled in tutorials, please reach out to the Materialize team for access.

**Comment by SangJunBak** [comment]
Dependent on https://github.com/MaterializeInc/product/issues/223

We also want to hide the source creation UI for sandboxed environments.
