### ISSUE TITLE
code coverage: non-coverable comment lines marked as uncovered

### ISSUE THREAD

**Issue by nrainer-materialize** [MaterializeInc/materialize#21486]
### What version of Materialize are you using?

main

### What is the issue?

[This build](https://buildkite.com/materialize/coverage/builds/198) reports the following uncovered lines:
```
--- a/src/expr/src/scalar/func/impls/datum.rs
+++ b/src/expr/src/scalar/func/impls/datum.rs
@@ -38,10 +38,6 @@ sqlfunc!(
         match a {
             Datum::Null => Ok(None),
             datum => {
!                // This will undercount sizes for installations that aren't in the
!                // `variable_length_row_encoding` treatment, but
!                // functions need to be determinstic, so there's no better we can do.
!                let sz = mz_repr::datum_size_deterministic::<true>(&datum);
                 i32::try_from(sz)
                     .map(Some)
                     .or(Err(EvalError::Int32OutOfRange(sz.to_string())))
```

Do the line numbers not match or are these lines not detected as uncoverable?

**Comment by def-** [comment]
This is https://github.com/rust-lang/rust/issues/110487, which happens here because `sqlfunc!` is a macro: https://github.com/MaterializeInc/materialize/blob/36a9c73d94cf6bcaaff6fd90eab99af16f58a5ac/src/expr/src/scalar/func/macros.rs#L17

I don't have a fix unfortunately, and while this is open coverage for macro-heavy files is mostly useless.

**Comment by nrainer-materialize** [comment]
Wondering if we should still throw some heuristics on it (throw out all uncovered lines starting with `\s+// `) or if this will be even more confusing when some following code lines are first uncovered and then covered.
