### ISSUE TITLE
Dropped MV + index with pending peek never gets cleaned up

### ISSUE THREAD

**Issue by teskje** [MaterializeInc/materialize#21497]
### What version of Materialize are you using?

main

### What is the issue?

We observed a case of an index dataflow that has stopped advancing its frontier but doesn't get cleaned up, seemingly because a pending peek is still waiting on it.

This is the (redacted) state of the replica:

* There is one dataflow that doesn't appear in the catalog and has stopped advancing its frontier.
  ```sql
  materialize=> select export_id, time from mz_internal.mz_compute_frontiers f where export_id like 'u%' and not exists (select * from mz_objects o where o.id = f.export_id);
   export_id |     time
  -----------+---------------
   u12472    | 1692980032000
  (1 row)
  ```

* It is kept alive by a pending peek:
  ```sql
  materialize=> select * from mz_internal.mz_compute_dependencies where import_id = 'u12472';
   export_id | import_id
  -----------+-----------
   t389414   | u12472
  (1 row)
  
  materialize=> select * from mz_internal.mz_compute_exports where export_id = 't389414';
   export_id | dataflow_id
  -----------+-------------
   t389414   | 8726
  (1 row)
  
  materialize=> select * from mz_internal.mz_dataflows where id = 8726;
    id  |               name
  ------+----------------------------------
   8726 | Dataflow: oneshot-select-t389413
  (1 row)
  
  materialize=> select * from mz_internal.mz_active_peeks;
                    id                  | index_id |     time
  --------------------------------------+----------+---------------
   a2eec950-4619-494d-8b09-d86a904221d3 | t389414  | 1692980108781
  (1 row)
  ```

* The peek time is after the index' frontier, so that explains why the peek is not served.

* The index is reading from an MV that has been dropped:
  ```sql
  materialize=> select * from mz_internal.mz_compute_dependencies where export_id = 'u12472';
   export_id | import_id
  -----------+-----------
   u12472    | u12470
  (1 row)
  
  materialize=> select * from mz_objects where id = 'u12470';
   id | oid | schema_id | name | type | owner_id | privileges
  ----+-----+-----------+------+------+----------+------------
  (0 rows)
  
  materialize=> select event_type, object_type, occurred_at from mz_audit_events where details->>'id' = 'u12470';
   event_type |    object_type    |        occurred_at
  ------------+-------------------+----------------------------
   create     | materialized-view | 2023-08-24 22:41:08.821+00
   drop       | materialized-view | 2023-08-25 16:18:32.278+00
  (2 rows)
  ```

## Possible explanation

Maybe this happens:
* User sends a peek, but the peek can’t be fulfilled immediately because the MV (or its dependencies) is still hydrating. The peek becomes pending.
* User drops the MV.
* Adapter tells the compute controller to drop both the MV and the index, but not to cancel the peek.
* Compute drops the MV (nothing depends directly on that, things depend on the storage collection instead) so that stops advancing its frontier.
* Compute refuses to drop the index because there is still a peek depending on it.
* The peek never gets served because the index frontier has stopped advancing, so the index also never gets dropped.

**Comment by jkosh44** [comment]
This is probably related to https://github.com/MaterializeInc/materialize/issues/16121.

I had a feeling that the issue was something simple. This PR fixes the issue for me locally: https://github.com/MaterializeInc/materialize/pull/21635.

I don't have the bandwidth to add testing right now, but if someone wants to take over and push it over the finish line, then feel free.
