### ISSUE TITLE
`CREATE SOURCE ... IN CLUSTER` should not need `SYSTEM` privileges

### ISSUE THREAD

**Issue by chuck-alt-delete** [MaterializeInc/materialize#21543]
### What version of Materialize are you using?

v0.67.3 (6510d54bc)

### What is the issue?

With `RBAC`, creating a source in a specific cluster appears to require `SYSTEM` privileges. I don't feel I need any of the `SYSTEM` privileges -- `CREATEROLE` , `CREATEDB` , or `CREATECLUSTER` . If I were creating a linked cluster, that would make sense to require `CREATECLUSTER`.

Example:
```sql
CREATE SOURCE IF NOT EXISTS sales IN CLUSTER demo_sources
FROM KAFKA CONNECTION demo.public.kafka_connection 
(TOPIC 'datagen_demo_snowflakeschema_sales', START TIMESTAMP -90000000) 
KEY FORMAT BYTES 
VALUE FORMAT AVRO USING CONFLUENT SCHEMA REGISTRY CONNECTION demo.public.csr_connection
INCLUDE TIMESTAMP as kafka_timestamp 
ENVELOPE NONE ;
```
```
Error: permission denied for SYSTEM
```

But then:
```sql
select has_cluster_privilege('chuck@materialize.com', 'demo_sources', 'CREATE');
```

```
has_cluster_privilege
true
```

**Comment by jkosh44** [comment]
Here's an easy repro:

1. Start up Materialize.
2. Execute the following as the `mz_system` role:

```
materialize=> CREATE ROLE r1;
CREATE ROLE
materialize=> GRANT CREATE ON CLUSTER default TO r1;
GRANT
materialize=> GRANT CREATE ON SCHEMA materialize.public TO r1;
GRANT
```
3. Execute the following as the `r1` role:
```
materialize=> CREATE SOURCE s IN CLUSTER default FROM LOAD GENERATOR COUNTER;
ERROR:  permission denied for SYSTEM

```

**Comment by jkosh44** [comment]
This is due to the progress source. The progress source reports a cluster config of undefined, which RBAC mistakenly thinks means it's going to create a new cluster and require the `CREATECLUSTER` privilege.
