### ISSUE TITLE
Move `subexpression-replacement.td` and `primary-key-optimizations.td` to slt

### ISSUE THREAD

**Issue by ggevay** [MaterializeInc/materialize#21577]
These two Testdrive tests have a lot of EXPLAIN outputs, which are tedious to rewrite when changing the EXPLAIN output. I'm not completely sure why they were originally implemented in td rather than slt, but I think nowadays slt should mostly have the required functionality:
- In `subexpression-replacement.td` I don't see anything scary at all.
- In `primary-key-optimizations.td`, there is a Kafka source, and some amount of testing that primary key information from sources is properly propagated. However, I think propagating primary key info from sources could be tested with just a few EXPLAINs, and then all the rest of the EXPLAINs could be moved to slt.

Alternatively, we could add support for bulk rewriting to td: https://github.com/MaterializeInc/materialize/issues/17223

**Comment by nrainer-materialize** [comment]
@ggevay: This is probably no longer relevant with https://github.com/MaterializeInc/materialize/pull/26528, is it?
CC @def-

**Comment by ggevay** [comment]
Indeed, https://github.com/MaterializeInc/materialize/pull/26528 would make this not important.
