### ISSUE TITLE
min function does not support time type

### ISSUE THREAD

**Issue by nrainer-materialize** [MaterializeInc/materialize#21584]
### What version of Materialize are you using?

v0.67.3 (6510d54bc)

### What is the issue?

```
CREATE TABLE t (time_val TIME);
INSERT INTO t VALUES ('00:00:00'::TIME);
SELECT min(time_val) FROM t;
```

produces

```
ERROR:  function min(time) does not exist
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
```

**Comment by jkosh44** [comment]
I'm going to switch this to a feature. Generally, 100% PostgreSQL compatibility is not considered a bug.

**Comment by nrainer-materialize** [comment]
I was considering it rather an incompleteness of the `min` function and less a Postgres inconsistency. I had assumed that `min`/`max` are supposed to work on all data types but this assumption may be invalid.

Still, absolutely fine with me to change it to a feature. (And, "100% compatibility" is never a bug 😀.)

**Comment by nrainer-materialize** [comment]
Closing as duplicate of https://github.com/MaterializeInc/materialize/issues/22024.
