### ISSUE TITLE
Performance harness

### ISSUE THREAD

**Issue by benesch** [MaterializeInc/materialize#216]
We want the equivalent of the sqllogictest tracker (mtrlz.dev/civiz) for performance tracking. It should automatically run a set of designated queries on dedicated(ish) hardware to get reproducible numbers, and put the results on a chart somewhere.

**Comment by quodlibetor** [comment]
At this point what we want for this is to make the nightly load tests digestible over time, yeah?

**Comment by benesch** [comment]
@philip-stoev's feature benchmark (#10156) is now running in CI and checking for exactly these sorts of regressions!
