### ISSUE TITLE
Flaky support for back-references in Avro schemas

### ISSUE THREAD

**Issue by umanwizard** [MaterializeInc/materialize#2166]
In Avro, it should be possible to specify the name of a previous chunk of the schema when defining a sub-schema; for example:

```
{
     "name": "outer",
     "type": "record",
     "fields": [
       {"name": "inner1", "type": {
           "name": "inner2", "type": "record", "fields": [
               {"name": "foo", "type": "long"},
               {"name": "bar", "type": "long"}
       ]}},
       {"name": "inner3", "type": {
           "type": "array",
           "items": "inner2"
       }}
     ]
   }
```

Note that `inner2` refers to a previous chunk of the schema.

There was some effort to support this in materialize: see `fn munge`, but it does not work completely.

**Comment by benesch** [comment]
Fixed in #2375. (@umanwizard FYI the "fixes #xxx" magic only works in PR descriptions and commit messages, not comments.)
