### ISSUE TITLE
Make it easier to see the Avro schema that would be created for an Avro sink

### ISSUE THREAD

**Issue by benesch** [MaterializeInc/materialize#21661]
## Problem

Today in Materialize, users cannot easily inspect the Avro schema that will be created for an Avro-formatted Kafka sink. Our best workaround is to create the sink to a dummy Kafka topic, and then pull the schema out of the Confluent Schema Registry:

```
curl http://my-schema-registry:8081/subjects/my-test-topic-value/versions/latest
```

This is a fairly painful workaround.

## Possible solutions

@sjwiesman proposes:

```
SHOW AVRO SCHEMA FOR <materialized-view>;
```

@benesch has some design questions to ponder:

* Should this be a SQL function? E.g., `SELECT mz_sink_avro_schema(<materialized_view_oid>)`
* On the other hand, we’re adding a bunch of `DOC ON` and maybe `DEFAULT ON` options to Avro-formatted sinks (https://github.com/MaterializeInc/materialize/issues/21557). Should we include support for those options in the command? I think the answer here ought to be yes: `SHOW SINK AVRO SCHEMA FOR <mv> (DOC ON …, DEFAULT ON …)`
* Can you embed this command/function in a view? (I think the right answer is no, at least to start.)
* Should the command only work on materialized views and sources? Or can it name unmat views too? 
* Should the command be `SHOW SINK AVRO SCHEMA` or `SHOW SINK SCHEMA` rather than `SHOW AVRO SCHEMA`?
* What is the return type of this command? A single `jsonb` column?

**Comment by sjwiesman** [comment]
I think the first question to answer is "should checking the schema require a running sink". My ideal is no, I want to validate the schema is what I want before starting a sink. 

Depending on where we land, I think that answers several of your design questions. I.e. `SELECT mz_sink_avro_schema(<sink_oid>)` seems to imply a running sink.

**Comment by benesch** [comment]
> Depending on where we land, I think that answers several of your design questions. I.e. `SELECT mz_sink_avro_schema(<sink_oid>)` seems to imply a running sink.

Oh whoops, sorry, that should have said `<materialized_view_oid>`. I updated the original description.

> I think the first question to answer is "should checking the schema require a running sink". My ideal is no, I want to validate the schema is what I want before starting a sink.

Yeah, hard agree. Whatever we do should absolutely allow you to see the schema that _would be_ created for a sink, without actually having to create that running sink.

**Comment by umanwizard** [comment]
Another syntactic option would be `EXPLAIN SCHEMA FOR CREATE SINK ...`

**Comment by benesch** [comment]
> Another syntactic option would be `EXPLAIN SCHEMA FOR CREATE SINK ...`

I like where this is headed! One thing that occurs to me: we probably want `EXPLAIN KEY SCHEMA` and `EXPLAIN VALUE SCHEMA`, yeah?

One thing that's _really_ nice about your proposal, @umanwizard, is that it captures all sink options, regardless of where in the `CREATE SINK` command they end up. The key schema and value schema depend on the envelope, not just the format. Support for that just falls out naturally in your proposal.

The only minor wrinkle is that it's a tiny bit annoying that you have to specify a name and a Kafka connection. Would be nice if you could run `EXPLAIN SCHEMA FOR CREATE SINK` without actually naming the sink or having a Kafka connection. But that's a minor wrinkle. I doubt many folks need to run `EXPLAIN SCHEMA FOR CREATE SINK` without having at least one Kafka connection lying around. We could always engineer omprovements in the future—e.g., have the `EXPLAIN` command accept a slightly modified version of `CREATE SINK` that doesn't require that you specify a name or Kafka connection, as in:

```
EXPLAIN SCHEMA FOR SINK FROM mv INTO KAFKA FORMAT AVRO
```

**Comment by umanwizard** [comment]
+1 to making `CREATE SINK` parsable without a name or connection in that context. We can make them optional in the parser and then check later on (during planning) that they're present when `CREATE SINK` appears in a non-`EXPLAIN` context.

**Comment by umanwizard** [comment]
Or you could just have two different variants of `CREATE SINK` in the parser, but then you have to remember to keep them in sync.

**Comment by moulimukherjee** [comment]
I created a PR https://github.com/MaterializeInc/materialize/pull/22626 to allow `EXPLAIN KEY SCHEMA` or `EXPLAIN VALUE SCHEMA` for a `CREATE SINK` statement. Currently it does check for the create sink statement to be completely valid (i.e. it requires name, connection etc.). Happy to change it based on feedback, but I thought it was the simplest to do without diverging the code here.
