### ISSUE TITLE
Support array types in Avro

### ISSUE THREAD

**Issue by umanwizard** [MaterializeInc/materialize#2167]

**Comment by rjnn** [comment]
Can you add some more detail as to how much work this is?

**Comment by umanwizard** [comment]
@rjnn We already support arrays in Protobuf, so unless there's some hidden gotchas I'm missing about Avro, I expect <1 day of work.

**Comment by rjnn** [comment]
Pinging this issue - is this prioritized for the near future?

**Comment by umanwizard** [comment]
Yes, I am planning on adding this in the next week -- got bogged down with
some other stuff I was working on being more difficult than I expected,
sorry!

**Comment by umanwizard** [comment]
We already support arrays in avro decoding, we just don't support them in Materialize.

If someone needs arbitrarily structured types, the best workaround currently is to use Json, as explained here:

https://github.com/MaterializeInc/materialize/pull/2456#issuecomment-609960660

For array support in Materialize in full generality, see https://github.com/MaterializeInc/materialize/issues/1514 and https://github.com/MaterializeInc/materialize/issues/1248 .
