### ISSUE TITLE
Add `RESTRICT` to `DROP DATABASE`

### ISSUE THREAD

**Issue by sploiselle** [MaterializeInc/materialize#2168]
`DROP DATABASE` does not support `RESTRICT` either implicitly or explicitly; maybe it should.

**Comment by benesch** [comment]
PostgreSQL doesn't support `DROP DATABASE ... RESTRICT` (https://www.postgresql.org/docs/current/sql-dropdatabase.html), so neither do we. 🤷‍♂

**Comment by sploiselle** [comment]
I like to think we can be the change we want to see in the world 🌟

**Comment by benesch** [comment]
There may be a legitimate reason not to support `DROP DATABASE ... RESTRICT`. I can't think of one, but sometimes the PostgreSQL folks have their reasons—reasons we might have to discover the hard way. Before implementing this, someone should try very hard to figure out why neither MySQL or PostgreSQL supports this.

**Comment by rjnn** [comment]
I support the Nikhil's chesterton's fence approach to changing behavior from Postgres. If we do something differently from how postgres does it, we should first be able to succinctly describe why they chose their path, and why they are wrong.

**Comment by benesch** [comment]
In this particular case, I do think there's a decent chance that the
Postgres folks just never got around to implementing it. I
asked @umanwizard to forward our query on to the Postgres mailing list.
I'll post a link here to the discussion if/when the email makes it through
the moderation queue.

**Comment by benesch** [comment]
Whoops, forgot to follow up here, but we did get an answer from the PostgreSQL folks: https://www.postgresql.org/message-id/CAKFQuwYzpDpkLdhC28FUbt1K4MPF=qr+CQs4EUPbZNA=TTb72w@mail.gmail.com

Looks like it's specific to Postgres's database setup, which we have explicitly chosen not to follow. In this case I think it's safe and probably desirable to support `DROP DATABASE {CASCADE|RESTRICT}`, though I think the default might need to stay `CASCADE` for ORM compatibility.
