### ISSUE TITLE
Inconsistent schema privileges

### ISSUE THREAD

**Issue by RobinClowers** [MaterializeInc/materialize#21680]
### What version of Materialize are you using?

v0.68.3 (27bfc107a)

### What is the issue?

When I check the for create privileges on a specific schema, it returns true:

```sql
SELECT
    s.id,
    s.name,
    d.id AS "databaseId",
    d.name AS "databaseName",
    has_schema_privilege(current_user, s.oid, 'CREATE')
        AS "hasCreatePrivilege"
FROM
    mz_catalog.mz_schemas AS s
        JOIN mz_catalog.mz_databases AS d ON d.id = s.database_id
ORDER BY s.name;

 id |  name  | databaseId | databaseName | hasCreatePrivilege
----+--------+------------+--------------+--------------------
 u3 | public | u1         | materialize  | t
```
But when I query for all schema privileges, I don't get any results:
```sql
SELECT *
FROM mz_internal.mz_show_my_schema_privileges
WHERE privilege_type = 'CREATE';

 grantor | grantee | database | name | privilege_type
---------+---------+----------+------+----------------
(0 rows)
```

**Comment by RobinClowers** [comment]
Additional details, I only have the default database and roles:

```sql
 materialize=> select * from mz_databases;
 id |  oid  |    name     | owner_id |        privileges
----+-------+-------------+----------+--------------------------
 u1 | 20001 | materialize | s1       | {s1=UC/s1,s2=U/s1,=U/s1}
(1 row)

Time: 21.918 ms
materialize=> select * from mz_roles;
 id |  oid  |         name          | inherit
----+-------+-----------------------+---------
 s1 | 20007 | mz_system             | t
 s2 | 20008 | mz_support            | t
 u1 | 20009 | robin@materialize.com | t
(3 rows)
```

**Comment by jkosh44** [comment]
Just to confirm, `current_user` was `robin@materialize.com`?

**Comment by RobinClowers** [comment]
Yes, that's right.

**Comment by jkosh44** [comment]
Oh sorry, can you actually dump `select * from mz_schemas;` too?

**Comment by RobinClowers** [comment]
```sql
select * from mz_schemas;
 id |  oid  | database_id |        name        | owner_id |        privileges
----+-------+-------------+--------------------+----------+--------------------------
 u3 | 20006 | u1          | public             | s1       | {s1=UC/s1,s2=U/s1,=U/s1}
 s1 | 20002 |             | mz_catalog         | s1       | {s1=UC/s1,s2=U/s1,=U/s1}
 s2 | 20003 |             | pg_catalog         | s1       | {s1=UC/s1,s2=U/s1,=U/s1}
 s4 | 20004 |             | mz_internal        | s1       | {s1=UC/s1,s2=U/s1,=U/s1}
 s5 | 20005 |             | information_schema | s1       | {s1=UC/s1,s2=U/s1,=U/s1}
(5 rows)
```

**Comment by jkosh44** [comment]
The problem is that `mz_acl_item_contains_privilege` is broken and `has_schema_privilege` relies on that in it's implementation. I have a fix here: https://github.com/MaterializeInc/materialize/pull/21682

The weird thing is that there's 50 tests that use `has_schema_privilege`, yet none of them fail. My understanding is that `has_schema_privilege` will always return true due to the current bug, but there are plenty of tests that expect false. I do some more digging next week.

**Comment by jkosh44** [comment]
> The weird thing is that there's 50 tests that use has_schema_privilege, yet none of them fail. My understanding is that has_schema_privilege will always return true due to the current bug, but there are plenty of tests that expect false. I'll do some more digging next week.

Ah, I got it. If the role has any privileges then it will return true. If it has no privileges then it will return false. All the existing tests just happen to fall into this pattern.
