### ISSUE TITLE
Support reading from multiple Kafka partitions

### ISSUE THREAD

**Issue by nacrooks** [MaterializeInc/materialize#2169]
Materialize currently returns incorrect/ambiguous error messages when reading from multiple Kafka partitions. 

It explicitly breaks the assumption that a consumer will receive offsets in increasing (monotonic) order. 

We should add explicit support for 
1) a single worker reading from multiple Kafka partitions (for correctness)
2) multiple workers reading from multiple Kafka partitions (for scalability)

**Comment by frankmcsherry** [comment]
Related: #1779

**Comment by rjnn** [comment]
This is closed by #2214, right @nacrooks?

**Comment by bhoomit** [comment]
Update known limitation docs :)

https://materialize.io/docs/known-limitations/#kafka

**Comment by JLDLaughlin** [comment]
Thanks @bhoomit ! This change isn't currently merged into the next release, but we will update the docs as soon as it is available: https://github.com/MaterializeInc/materialize/issues/2344
