### ISSUE TITLE
Avro sink schema testing

### ISSUE THREAD

**Issue by def-** [MaterializeInc/materialize#21738]
### Feature request

I'll follow along on https://github.com/MaterializeInc/materialize/issues/17209

Planned:
- Should test avro sinks in general too (explicit + randomized)
- timestamp-millis should work explicitly with a sink, already added some testing in 21570
- doc on feature
- default feature

**Comment by morsapaes** [comment]
@def-, are you comfortable with the current level of testing for this feature? We'd like to move it out of Private Preview, since it's being used in production for a while now.

**Comment by def-** [comment]
Yes, at least we have no further testing planned. Sorry that I forgot to close this issue.

**Comment by morsapaes** [comment]
No worries, @def-! Thanks for confirming.
