### ISSUE TITLE
sql: acquire read holds for catalogs during txns

### ISSUE THREAD

**Issue by mjibson** [MaterializeInc/materialize#21815]
The commit https://github.com/MaterializeInc/materialize/pull/9366/commits/cf1271c1c0bddeee4890744faa1e0646257b8030 purported to include system indexes in read txns, but I incorrectly committed some tiny rename refactor instead. We should do what that commit said because it regularly breaks drivers.

**Comment by mjibson** [comment]
The specific problem that happens is in an explicit transaction if a query returns a weird type (list, map, uint8) many drivers will issue followup queries asking about those types (without the user knowing). Our timedomain code will complain that system indexes aren't in the timedomain and the user gets very confused. If we always add the pg_catalog dependencies to all read sets, this should be ok.

**Comment by chaas** [comment]
I found Matt's commit with that description "coord: always include system indexes in read transactions" that actually does that and was overwritten.
https://github.com/mjibson/materialize/commit/39e7a0a8f4fbe53e186fb0c512a0fe480a246ab3

**Comment by jkosh44** [comment]
> The specific problem that happens is in an explicit transaction if a query returns a weird type (list, map, uint8) many drivers will issue followup queries asking about those types (without the user knowing).

Unfortunately this only solves half the problem. Depending on the query the driver may issue the type lookup query BEFORE the actual user query. If this is the first query of the transaction then the timedomain will only contains system objects and the user will still get a timedomain error because their user object is outside of the timedomain. I think in this scenario there's nothing we can do.

**Comment by mjibson** [comment]
> I think in this scenario there's nothing we can do.

Idea: for first queries in a txn where the query only references catalog objects, add all objects in the current cluster to the timedomain (and, as a logical result described below, disable auto routing for multi stmt txns).

Problems with that idea: if/when we implement "txns always execute on only one cluster", the above will effectively mean we will never auto route any statement of any multi stmt txn to the introspection cluster. Maybe that's good? That is: auto routing should only apply to single statement txns? Ugh so many competing goals here.

**Comment by jkosh44** [comment]
Here is example of a transaction that still fails:

https://github.com/MaterializeInc/materialize/blob/a0a163214afb86c5a25a13b6054095c4bd04a150/test/sqllogictest/transactions.slt#L948-L976
