### ISSUE TITLE
Fast SQL logic tests 1 is flaky

### ISSUE THREAD

**Issue by jkosh44** [MaterializeInc/materialize#21851]
### Buildkite link

https://buildkite.com/materialize/tests/builds/64125#018ab457-c73e-49a6-8034-f5e252be6290

### Relevant log output

```source
Attached in first comment.
```

**Comment by jkosh44** [comment]
[tests_build_64125_fast-sql-logic-tests-1.log](https://github.com/MaterializeInc/materialize/files/12677706/tests_build_64125_fast-sql-logic-tests-1.log)

**Comment by danhhz** [comment]
That panic looks like https://github.com/MaterializeInc/materialize/issues/21744

**Comment by jkosh44** [comment]
Close as dup.
