### ISSUE TITLE
storage/sources/kafka: regression: KafkaEnvelopeNone feature benchmark is slower and uses more memory

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#21862]
### What version of Materialize are you using?

4460d47da

### What is the issue?

comparing `environmentd v0.70.0-dev (4460d47da)` and `environmentd v0.69.2 (c11c3b597)`

```
+++ Benchmark Report for cycle 3:
NAME                                | TYPE      |      THIS       |      OTHER      |  Regression?  | 'THIS' is:
----------------------------------------------------------------------------------------------------
KafkaEnvelopeNoneBytes              | wallclock |          11.984 |          11.486 |      no       | 4.3 pct   more/slower
KafkaEnvelopeNoneBytes              | messages  |            None |            None |      no       | N/A
KafkaEnvelopeNoneBytes              | memory    |        1658.440 |        1312.256 |    !!YES!!    | 26.4 pct   more/slower
```

Similar situation happens with `--scale=+1`

**Comment by benesch** [comment]
We're unfortunately just going to declare bankruptcy on this regression ([Slack conversation](https://materializeinc.slack.com/archives/C01CFKM1QRF/p1707721150932749?thread_ts=1707718024.747309&cid=C01CFKM1QRF)). It's been running in production for several months now without issue. To my knowledge users are quite happy with the performance of `ENVELOPE NONE` Kafka sources, but if we start getting reports of performance problems in production we can look into scheduling some performance improvement work.
