### ISSUE TITLE
Support ingesting json-valued fields inside of avro

### ISSUE THREAD

**Issue by quodlibetor** [MaterializeInc/materialize#2188]
Debezium encodes json and jsonb-valued fields as:

```javascript
{
    "name": "COLUMN_NAME",
    "type": {
        "type": "string",
        "connect.version": 1,
        "connect.name": "io.debezium.data.Json"
    }
}
```

we should convert these into JSON Datums.

**Comment by umanwizard** [comment]
Will do this right after I finish fixing the bugs in schema parsing

**Comment by rjnn** [comment]
@umanwizard do you have an estimate here?

**Comment by cuongdo** [comment]
@umanwizard Let's merge this ASAP, to collect feedback and allow for time for this to bake a bit before the 0.2 release. Reviews should still happen post-merge.

**Comment by umanwizard** [comment]
@rjnn taking a look today, I expect it to be simple enough to finish today, will update on this thread if that turns out not to be the case.
