### ISSUE TITLE
tests: Shuffle flags

### ISSUE THREAD

**Issue by def-** [MaterializeInc/materialize#21893]
### Feature request

Our tests should work with different combinations of system parameters, they should just change performance or enable functionality, not break anything.

This should run periodically on main with tests/nightlies.

**Comment by nrainer-materialize** [comment]
@def-, do we consider this addressed with https://github.com/MaterializeInc/materialize/pull/26837 and https://github.com/MaterializeInc/materialize/pull/26867?
