### ISSUE TITLE
parallel-workload: Many concurrent connections causes network errors

### ISSUE THREAD

**Issue by def-** [MaterializeInc/materialize#21954]
### What version of Materialize are you using?

e9806bd0f6

### What is the issue?

Seen in https://buildkite.com/materialize/nightlies/builds/4304#018acd10-d852-427b-95df-037d419ea977 with 100 threads. Easier to repro locally with 1000 threads (using https://github.com/MaterializeInc/materialize/pull/21883):
```
bin/mzcompose --find parallel-workload down && bin/mzcompose --find parallel-workload run default --complexity=ddl --threads=980 --seed=1695663786 --runtime=3000
```
Starts failing after a few minutes with many occurrences of:
```
worker_385 Query failed: SET CLUSTER = cluster_compute_2; network error
struct.error: unpack_from requires a buffer of at least 5 bytes for unpacking 5 bytes at offset 0 (actual buffer size is 0)
pg8000.exceptions.InterfaceError: network error
```
They all seem to fail in trivial `SET CLUSTER = ...` calls.

@ParkMyCar I'm not sure if you want to look into this since you already investigated some issues with many concurrent connections.

ci-regexp: network error
ci-apply-to: data-ingest
ci-apply-to: parallel-workload

**Comment by ParkMyCar** [comment]
@def- thanks for the ping! I don't have the bandwidth to look into this right now, but next time I (or someone else on Surfaces) looks into connection concurrency issues, I'll bundle this investigation into it.

**Comment by def-** [comment]
This can be triggered with a single thread, seen in https://github.com/MaterializeInc/materialize/pull/22053
https://buildkite.com/materialize/nightlies/builds/4552#018af015-9691-4278-9f18-a1632a5c69a3
Local reproducer:
```
git checkout a4154a6200f637e7ce1a42a9bc96790c10acdbf8
bin/mzcompose --find data-ingest down && bin/mzcompose --find data-ingest run default
```
What it does is run many UPDATE queries on the same key against Mz.
I'm trying to get this into an even simpler reproducer.

**Comment by def-** [comment]
When I have 4 databases this happens all the time, even with just 16 threads. Seen in my WIP change https://github.com/MaterializeInc/materialize/pull/22542

**Comment by def-** [comment]
Also happens in data-ingest now, which only uses one thread against Mz. This seems related to Mz being under high load and somehow dropping connections due to that: https://buildkite.com/materialize/nightlies/builds/4994#018b9a19-9338-43c9-929b-3b8081dd39eb I consider this impotant enough to be looked at, it's also causing lots of CI flakiness.

**Comment by ParkMyCar** [comment]
@def- I looked into the `data-ingest` failure today, and I think it might be a testing issue.

I added some additional logging on the database side to announce when a connection closes, and kept running it locally until I hit a failure. Generally when it would fail, it would be almost immediately, e.g. < 10 seconds, is this what you saw? With this new logging I found a connection closing:

```
2023-11-22 13:12:08 environmentd: 2023-11-22T18:12:08.542182Z  INFO mz_pgwire::codec: cid=1 recv=Terminate
2023-11-22 13:12:08 environmentd: 2023-11-22T18:12:08.542213Z  WARN mz_pgwire::server: Connection closing
```

Which indicates that the connection closed because we received a request from the client. I'm wondering if it's possible that some part of the [run loop](https://github.com/MaterializeInc/materialize/blob/main/misc/python/materialize/data_ingest/executor.py#L455-L528) is failing, which is causing the `pg8000` client to close and send a terminate? 

Let me know what you think!

**Comment by ParkMyCar** [comment]
Unassigning myself at the moment since I don't have any bandwidth to pick this up in the near future

**Comment by def-** [comment]
> Which indicates that the connection closed because we received a request from the client. I'm wondering if it's possible that some part of the [run loop](https://github.com/MaterializeInc/materialize/blob/main/misc/python/materialize/data_ingest/executor.py#L455-L528) is failing, which is causing the pg8000 client to close and send a terminate?

Sorry, just saw this now. I don't think the run loop can fail silently, at least in our code. Maybe pg8000 does something weird internally. Unfortunately this is still occurring occasionally: https://buildkite.com/materialize/nightlies/builds/7266#018eb856-10a3-4105-833c-20f82b8e56f3
