### ISSUE TITLE
Improve Kinesis source activation

### ISSUE THREAD

**Issue by JLDLaughlin** [MaterializeInc/materialize#2195]
In Timely, activating an Operator's address means that the Timely scheduler should execute that Operator at least once. In the first version of Kinesis sources, we are doing the simplest version of activation: reactivate the Kinesis source Operator every 60 seconds.

In reality, we should be doing something more akin to the Kafka source: put a wrapper around the consumer that reactivates when it sees new data.

**Comment by morsapaes** [comment]
Closing as stale.
