### ISSUE TITLE
Add Kinesis source testing to CI

### ISSUE THREAD

**Issue by JLDLaughlin** [MaterializeInc/materialize#2197]
As a first effort to test/maintain stability of our Kinesis source, we should add Kinesis source testing to CI. This will require leaving a Kinesis Data Stream running in our AWS account and hiding AWS credentials in CI environment variables. 

Note: This might be a bummer if we have CI failures that we can't reproduce locally! Should implement https://github.com/MaterializeInc/materialize/issues/2196 to ease that pain.

(If I'm not the one who does this, @benesch offered to help set up the CI environment variables).

**Comment by benesch** [comment]
Fixed in #2507.
