### ISSUE TITLE
Dataflow visualizer needs RBAC checks

### ISSUE THREAD

**Issue by nrainer-materialize** [MaterializeInc/materialize#21978]
### What version of Materialize are you using?

-

### What is the issue?

I get an "There was an error visualizing your dataflow" error on all materialized views and indices (e.g., https://console.materialize.com/regions/aws-us-east-1/clusters/u145/qa_canary_environment_compute/indexes/u2282/qa_canary_environment/public_loadgen/product_category_primary_idx/dependencies).

<img width="1246" alt="Bildschirmfoto 2023-09-26 um 16 07 44" src="https://github.com/MaterializeInc/materialize/assets/129728240/129324d7-318b-42f7-acac-ce3f2f98cf63">

Could it be a CORS issue?

```
Quellübergreifende (Cross-Origin) Anfrage blockiert: Die Gleiche-Quelle-Regel verbietet das Lesen der externen Ressource auf https://o561021.ingest.sentry.io/api/5699757/envelope/?sentry_key=13c8b3a8d1e547c9b9493de997b04337&sentry_version=7&sentry_client=sentry.javascript.react%2F7.70.0. (Grund: CORS-Anfrage schlug fehl). Statuscode: (null).
```
saying that a cross-origin request was blocked from reading due a same-source rule.

If relevant, the used browser is Firefox 117.0.1.

Furthermore, the link behind "visit our help center", which is https://support.materialize.com/hc/en-us/restricted?return_to=https%3A%2F%2Fsupport.materialize.com%2Fhc&locale=en-us, does not work for me and results in an empty page.

**Comment by RobinClowers** [comment]
This is due to an RBAC error, you don't have permission to something. This is the underlying error:
> permission denied for CLUSTER "qa_canary_environment_compute"

That said, we should show an more friendly error message in this case.

**Comment by RobinClowers** [comment]
I've got a PR out to fix the support link: https://github.com/MaterializeInc/console/pull/872

**Comment by RobinClowers** [comment]
I noticed the largest maintained query table also needs an RBAC check:

![Image](https://github.com/MaterializeInc/materialize/assets/91281/73ca6557-0498-41b9-a0f4-e7c1eb041f9f)
