### ISSUE TITLE
Postgres sources always stay in "starting" state after restarting Mz

### ISSUE THREAD

**Issue by def-** [MaterializeInc/materialize#21980]
### What version of Materialize are you using?
e0f3dadd78b4c5b4ac6150509676a6bfeb137887

### What is the issue?

Tried with up to 10 minutes of waiting, happened in multiple tests in https://buildkite.com/materialize/tests/builds/64509 and https://buildkite.com/materialize/nightlies/builds/4348 . Both are for my PR https://github.com/MaterializeInc/materialize/pull/20505 which introduces this as a new check which restarts Mz after a test is finished and verifies that all sources are in a good state. Not all, but some pg sources stay in starting state forever.
```
mzcompose: test case workflow-default failed: <class 'ValueError'>: Source pg_source is expected to be running/created, but is starting, error: None, details: None
Traceback (most recent call last):
  File "/var/lib/buildkite-agent/builds/buildkite-15f2293-i-09c83ad1b18e14065-1/materialize/tests/misc/python/materialize/mzcompose/composition.py", line 437, in test_case
    yield
  File "/var/lib/buildkite-agent/builds/buildkite-15f2293-i-09c83ad1b18e14065-1/materialize/tests/misc/python/materialize/cli/mzcompose.py", line 591, in handle_composition
    composition.workflow(args.workflow, *args.unknown_subargs[1:])
  File "/var/lib/buildkite-agent/builds/buildkite-15f2293-i-09c83ad1b18e14065-1/materialize/tests/misc/python/materialize/mzcompose/composition.py", line 353, in workflow
    self.sanity_restart_mz()
  File "/var/lib/buildkite-agent/builds/buildkite-15f2293-i-09c83ad1b18e14065-1/materialize/tests/misc/python/materialize/mzcompose/composition.py", line 716, in sanity_restart_mz
    raise ValueError(error)
ValueError: Source pg_source is expected to be running/created, but is starting, error: None, details: None
```
Example reproducer: `git checkout e0f3dadd78b4c5b4ac6150509676a6bfeb137887 && bin/mzcompose --find storage-usage down && bin/mzcompose --find storage-usage run default`.

It seems pretty serious to me that Postgres sources don't work reliably after a restart.

I will now disable this check to continue with getting my PR (https://github.com/MaterializeInc/materialize/pull/20505) in.

**Comment by sploiselle** [comment]
@def- The source needs to produce a record to move the subsource's status from `starting` to `running` in the current implementation

**Comment by def-** [comment]
@sploiselle My query is:
```sql
SELECT name, status, error, details
FROM mz_internal.mz_source_statuses
WHERE NOT(
  status = 'running' OR
  (type = 'progress' AND status = 'created') OR
  (type = 'subsource' AND status = 'starting')
)
```
I assumed this would handle subsources being stuck on starting. Or does the subsource being in starting keep the source in starting state too?

**Comment by sploiselle** [comment]
Did you produce more data after restarting MZ? That is what moves from `starting` to `running`. Sorry if my previous mention of "subsources" was unclear.
