### ISSUE TITLE
Canary Deploy in Staging Cloud is stuck

### ISSUE THREAD

**Issue by def-** [MaterializeInc/materialize#21998]
### What version of Materialize are you using?

c1959830e0

### What is the issue?

Noticed in https://buildkite.com/materialize/nightlies/builds/4387#018ad3d6-3eee-48d9-8053-c9acdac0bb5f

Was fine in the previous run: [22087f7026](https://github.com/MaterializeInc/materialize/commit/22087f70264aa6e74ff2486c7064973ccac36142)

**Comment by def-** [comment]
@joacoc Could this be your retry method retrying too often? https://github.com/MaterializeInc/materialize/pull/21975

It was part of the changes that made it into this nightly run: https://github.com/MaterializeInc/materialize/compare/22087f7026...c195983

**Comment by joacoc** [comment]
I think that if the new enable retry was getting stuck we would never see the region details (the following step after enabling the region):

```
  | $ docker compose run mz region enable --version devel-c1959830e04b57fa031e2c20219655a7d2100e9b
  | $ docker compose up --detach --scale mz=0 mz
  | Obtaining hostname of cloud instance ...
  | $ docker compose run mz region show
  | $ docker compose up --detach --scale mz=0 mz
  | Waiting for cloud cluster to come up with username infra+nightly-canary@materialize.com ...
  | Obtaining hostname of cloud instance ...
  | $ docker compose run mz region show
  | C> waiting for dbname=materialize host=1yvq0qtkcoct95p4voy00i5kd.us-east-1.aws.staging.materialize.cloud port=6875 user=infra+nightly-canary@materialize.com password='m...' to handle 'SELECT 1' success!
  | $ docker compose up --detach --wait materialized
```

If I compare one healthy test with this I see that failing logs are new in `canary-tables.md` after `mz region disable`:

```
$ docker compose run mz region disable
--
  | $ docker compose kill -sSIGKILL materialized
  | Container cloud-canary-materialized-1  Killing
  | Container cloud-canary-materialized-1  Killed
  | $ docker compose up --detach --wait materialized
  | Container cloud-canary-cockroach-1  Running
  | Container cloud-canary-materialized-1  Created
  | Container cloud-canary-cockroach-1  Waiting
  | Container cloud-canary-cockroach-1  Healthy
  | Container cloud-canary-materialized-1  Starting
  | Container cloud-canary-materialized-1  Started
  | Container cloud-canary-cockroach-1  Waiting
  | Container cloud-canary-materialized-1  Waiting
  | Container cloud-canary-cockroach-1  Healthy
  | Container cloud-canary-materialized-1  Healthy
  | $ docker compose port materialized 6875
  | > SELECT 1
  | $ docker compose port materialized 6875
```

Could it mean something I'm missing?

**Comment by joacoc** [comment]
I've tried locally and got a success when I remove the Testdrive.

**Comment by def-** [comment]
Oooh, this is happening because of my own change: https://github.com/MaterializeInc/materialize/pull/20505
