### ISSUE TITLE
Postgres inconsistency: timezone function produces different value

### ISSUE THREAD

**Issue by nrainer-materialize** [MaterializeInc/materialize#21999]
### Postgres

```
-- Setup for evaluation strategy 'Postgres evaluation':
DROP TABLE IF EXISTS postgres_evaluation;
CREATE TABLE postgres_evaluation (row_index INT, timestamptz_val TIMESTAMPTZ);
INSERT INTO postgres_evaluation VALUES (0, '0001-01-01 12:00:00 +6'::TIMESTAMPTZ);
-- Query using evaluation strategy 'Postgres evaluation':
SELECT
  (timezone('+5', timestamptz_val))::TEXT
FROM
  postgres_evaluation;
```

produces

```
      timezone       
---------------------
 0001-01-01 01:00:00
```

### mz

```
-- Setup for evaluation strategy 'Dataflow rendering':
DROP TABLE IF EXISTS dataflow_rendering;
CREATE TABLE dataflow_rendering (row_index INT, timestamptz_val TIMESTAMPTZ);
INSERT INTO dataflow_rendering VALUES (0, '0001-01-01 12:00:00 +6'::TIMESTAMPTZ);
-- Query using evaluation strategy 'Dataflow rendering':
SELECT
  (timezone('+5', timestamptz_val))::TEXT
FROM
  dataflow_rendering;
```

produces

```
      timezone       
---------------------
 0001-01-01 11:00:00
```

## Notes
This could also be related to https://github.com/MaterializeInc/materialize/issues/22016.

**Comment by benesch** [comment]
In PostgreSQL, `AT TIME ZONE` uses POSIX time zone names, in which positive offsets are used for locations west of Greenwich:

> Another issue to keep in mind is that in POSIX time zone names, positive offsets are used for locations west of Greenwich. Everywhere else, PostgreSQL follows the ISO-8601 convention that positive timezone offsets are east of Greenwich.

Demonstration:

```
benesch=# set timezone = utc;
SET
benesch=# select '2023-01-02 00:00:00'::timestamptz at time zone 'EST';
      timezone       
---------------------
 2023-01-01 19:00:00
(1 row)

benesch=# select '2023-01-02 00:00:00'::timestamptz at time zone 'UTC-5';
      timezone       
---------------------
 2023-01-02 05:00:00
(1 row)
```

This is massively confusing, because in `timestamptz` input (e.g., `'0001-01-01 12:00:00 -5'::timestamptz`), "-5" means EST, like you would expect.

I ... guess we should adjust Materialize to do the same. But, WTF PostgreSQL.

**Comment by jkosh44** [comment]
> In PostgreSQL, `AT TIME ZONE` uses POSIX time zone names, in which positive offsets are used for locations west of Greenwich:
> 
> > Another issue to keep in mind is that in POSIX time zone names, positive offsets are used for locations west of Greenwich. Everywhere else, PostgreSQL follows the ISO-8601 convention that positive timezone offsets are east of Greenwich.

Where does this quote come from? I was only able to find it in a StackOverflow post but not the actual PostgreSQL docs.

**Comment by jkosh44** [comment]
I'm very confused as to what the semantics are supposed to be according to the PostgreSQL docs. The docs for `AT TIME ZONE` (https://www.postgresql.org/docs/16/functions-datetime.html#FUNCTIONS-DATETIME-ZONECONVERT) says

> In these expressions, the desired time zone `zone` can be specified either as a text value (e.g., `'America/Los_Angeles'`) or as an interval (e.g., `INTERVAL '-08:00'`). In the text case, a time zone name can be specified in any of the ways described in [Section 8.5.3](https://www.postgresql.org/docs/16/datatype-datetime.html#DATATYPE-TIMEZONES). The interval case is only useful for zones that have fixed offsets from UTC, so it is not very common in practice.

[Section 8.5.3](https://www.postgresql.org/docs/16/datatype-datetime.html#DATATYPE-TIMEZONES) is on the page that describes input/output formats for date/time related times and therefore lead me to believe that is described the input format of time zones for `TIMESTAMPTZ` types. Therefore I would think that `TIMESTAMPTZ` interpretation of time zone strings should be equivalent to `AT TIME ZONE` interpretation of time zone strings. Therefore the following two queries should be equivalent:

```
postgres=# select '2023-01-02 00:00:00-5'::timestamptz;
      timestamptz       
------------------------
 2023-01-02 05:00:00+00
(1 row)

postgres=# select '2023-01-02 00:00:00'::timestamp at time zone '-5';
        timezone        
------------------------
 2023-01-01 19:00:00+00
(1 row)

```

However, they're clearly not. If instead I use the `UTC-5` syntax, then they are equivalent.


```
postgres=# select '2023-01-02 00:00:00UTC-5'::timestamptz;
      timestamptz       
------------------------
 2023-01-01 19:00:00+00
(1 row)

postgres=# select '2023-01-02 00:00:00'::timestamp at time zone 'UTC-5';
        timezone        
------------------------
 2023-01-01 19:00:00+00
(1 row)

```

**Comment by benesch** [comment]
> Where does this quote come from? I was only able to find it in a StackOverflow post but not the actual PostgreSQL docs.

Ah, sorry, an old version (8.x) of the docs. 

In the new version, the text has been moved to [section B.5.](https://www.postgresql.org/docs/current/datetime-posix-timezone-specs.html) and reads:

> The positive sign is used for zones west of Greenwich. (Note that this is the opposite of the ISO-8601 sign convention used elsewhere in PostgreSQL.)

----

> However, they're clearly not.

Yeah, the docs are super unclear on this. The only indication of the deviation seems to be table 8.12. Notice how this table says 

![image](https://github.com/MaterializeInc/materialize/assets/882976/e2394eea-2c6c-4ed8-adf8-0a2f10405679)

**Comment by nrainer-materialize** [comment]
@benesch, @jkosh44: I fear that the fix does not fully mitigate the inconsistency with Postgres:

```
--   Value 1 (Materialize evaluation): '15:59:59.999999' (type: <class 'str'>)
--   Value 2 (Postgres evaluation): '15:59:59.999999-08' (type: <class 'str'>)
--   Query 1: SELECT (timezone('+8', time_max_val))::TEXT, double_tiny4 * int4_one, btrim(text_val_1) FROM t_dfr_horiz;
--   Query 2: SELECT (timezone('+8', time_max_val))::TEXT, double_tiny4 * int4_one, btrim(text_val_1) FROM t_pg_horiz;
```

Code to reproduce:
```
-- Setup for evaluation strategy 'Materialize evaluation':
DROP TABLE IF EXISTS mz_evaluation;
CREATE TABLE mz_evaluation (row_index INT, time_max_val TIME);
INSERT INTO mz_evaluation VALUES (0, '23:59:59.999999'::TIME);
-- ------------------------------
-- Setup for evaluation strategy 'Postgres evaluation':
DROP TABLE IF EXISTS postgres_evaluation;
CREATE TABLE postgres_evaluation (row_index INT, time_max_val TIME);
INSERT INTO postgres_evaluation VALUES (0, '23:59:59.999999'::TIME);
-- ------------------------------
-- Query using evaluation strategy 'Materialize evaluation':
SELECT
  (timezone('+8', time_max_val))::TEXT
FROM
  mz_evaluation;
-- ------------------------------
-- Query using evaluation strategy 'Postgres evaluation':
SELECT
  (timezone('+8', time_max_val))::TEXT
FROM
  postgres_evaluation;
```

See also:
* https://github.com/MaterializeInc/materialize/pull/22946
* https://buildkite.com/materialize/nightlies/builds/5005#018ba38c-59e2-4afc-b9e5-fc5451311ad0

**Comment by nrainer-materialize** [comment]
I can still detect inconsistencies on `e5da59fb68`.

```
DROP TABLE IF EXISTS evaluation;
CREATE TABLE evaluation (row_index INT, date_val_1 DATE);
INSERT INTO evaluation VALUES (0, '2023-06-01'::DATE);

SELECT
  (timezone('CET', date_val_1))::TEXT
FROM
  evaluation;
```

produces

```
      timezone       
---------------------
 2023-06-01 02:00:00
(1 row)
```

on mz and

```
      timezone       
---------------------
 2023-06-01 01:00:00
(1 row)
```

in pg.

To the best of my knowledge, the relevant DB configuration matches:

```
materialize=> select now();
            now             
----------------------------
 2023-11-07 09:06:25.099+00
(1 row)

materialize=> show timezone;
 timezone 
----------
 UTC
(1 row)
```

and

```
postgres=# select now();
              now              
-------------------------------
 2023-11-07 09:06:14.768925+00
(1 row)

postgres=# show timezone;
 TimeZone 
----------
 Etc/UTC
(1 row)
```

Is one of the databases assuming another timezone for the insert value `'2023-06-01'::DATE`, which does not explicitly specify one?

**Comment by nrainer-materialize** [comment]
Added a small request regarding the timezone with time type handling in the (already closed) PR: https://github.com/MaterializeInc/materialize/pull/22960#issuecomment-1798096918

**Comment by jkosh44** [comment]
Actually it looks like the `CET` timezone in general is just broken:

```
postgres=# SELECT '2000-06-01 00:00:00 CET'::TIMESTAMPTZ;
      timestamptz       
------------------------
 2000-05-31 23:00:00+00
(1 row)

materialize=> SELECT '2000-06-01 00:00:00 CET'::TIMESTAMPTZ;
      timestamptz       
------------------------
 2000-05-31 22:00:00+00
(1 row)

```

**Comment by jkosh44** [comment]
The discrepancy seems to come from Chrono. PostgreSQL says that `CET` is +1:00:00

```
postgres=# SELECT * FROM pg_timezone_abbrevs WHERE abbrev = 'CET';
 abbrev | utc_offset | is_dst 
--------+------------+--------
 CET    | 01:00:00   | f
(1 row)

```

While Chrono says that `CET` is +2:00:00

```Rust
        let cet = chrono_tz::Tz::from_str_insensitive("CET").unwrap();
        let dt = NaiveDate::from_ymd_opt(2000, 6, 1)
            .unwrap()
            .and_hms_opt(0, 0, 0)
            .unwrap();
        let utc = cet.offset_from_utc_datetime(&dt).fix();
        let local = cet.offset_from_local_datetime(&dt).latest().unwrap().fix();
        println!("utc {utc:?}");
        println!("local {local:?}");
        // Prints: 
        // utc +02:00
        // local +02:00
```

Note: I don't really know the difference between `offset_from_utc_datetime` and `offset_from_local_datetime`, but they produce the same result here. In the code we use `offset_from_local_datetime` which is a little suspect since I would assume that we would want to look at the `TIMEZONE` session variable at some point.

Wikipedia seems to agree with PostgreSQL: https://en.wikipedia.org/wiki/Central_European_Time

> Central European Time (CET) is a [standard time](https://en.wikipedia.org/wiki/Standard_time) of Central, and parts of Western Europe, which is one hour ahead of [Coordinated Universal Time](https://en.wikipedia.org/wiki/Coordinated_Universal_Time) (UTC)

**Comment by nrainer-materialize** [comment]
> The discrepancy seems to come from Chrono. PostgreSQL says that `CET` is +1:00:00

Well, I think this depends on the date. I had a similar discussion with @benesch recently (see: https://github.com/MaterializeInc/materialize/pull/22944#discussion_r1383460977). You chose `(2000, 6, 1)` as a date, which is in summer so that `CET` is used as `CEST`, which is `CET` + DST.

**Comment by jkosh44** [comment]
Ah, it looks like this is related to daylight savings time. Chrono converts `CET` to `CEST` because June 6th is during the summer daylight savings time (at least according to Chrono). The following code:

```Rust
        let cet = chrono_tz::Tz::from_str_insensitive("CET").unwrap();
        let dt = NaiveDate::from_ymd_opt(2000, 6, 1)
            .unwrap()
            .and_hms_opt(0, 0, 0)
            .unwrap();
        let utc = cet.offset_from_utc_datetime(&dt);
        let local = cet.offset_from_local_datetime(&dt);
        println!("utc {utc:?}");
        println!("local {local:?}");
        let utc = utc.fix();
        let local = local.latest().unwrap().fix();
        println!("cet {cet:?}");
        println!("utc {utc:?}");
        println!("local {local:?}");
```
Prints the following:
```
cet CET
utc CEST
local Single(CEST)
utc +02:00
local +02:00
```

Note `CEST` which is Central European Summer Time and indeed +2:00:00.

If we change the date to Novemeber:
```Rust
        let cet = chrono_tz::Tz::from_str_insensitive("CET").unwrap();
        println!("cet {cet:?}");
        let dt = NaiveDate::from_ymd_opt(2000, 11, 1)
            .unwrap()
            .and_hms_opt(0, 0, 0)
            .unwrap();
        let utc = cet.offset_from_utc_datetime(&dt);
        let local = cet.offset_from_local_datetime(&dt);
        println!("utc {utc:?}");
        println!("local {local:?}");
        let utc = utc.fix();
        let local = local.latest().unwrap().fix();
        println!("utc {utc:?}");
        println!("local {local:?}");
```
It prints:
```
cet CET
utc CET
local Single(CET)
utc +01:00
local +01:00
```

We can see the same behavior via SQL:


```
postgres=# SELECT '2000-06-01 00:00:00 CET'::TIMESTAMPTZ;
      timestamptz       
------------------------
 2000-05-31 23:00:00+00
(1 row)

postgres=# SELECT '2000-11-01 00:00:00 CET'::TIMESTAMPTZ;
      timestamptz       
------------------------
 2000-10-31 23:00:00+00
(1 row)

materialize=> SELECT '2000-06-01 00:00:00 CET'::TIMESTAMPTZ;
      timestamptz       
------------------------
 2000-05-31 22:00:00+00
(1 row)

materialize=> SELECT '2000-11-01 00:00:00 CET'::TIMESTAMPTZ;
      timestamptz       
------------------------
 2000-10-31 23:00:00+00
(1 row)

```

PostgreSQL and Chrono use the same databases for timezone information so it's likely that one of them has a bug. Or maybe they have different rules about when they'll infer a different timezone based on daylight savings time.

https://www.postgresql.org/docs/current/datatype-datetime.html#DATATYPE-TIMEZONES
> PostgreSQL uses the widely-used IANA (Olson) time zone database for information about historical time zone rules. 

https://crates.io/crates/chrono-tz
> The impls are generated by a build script using the [IANA database](http://www.iana.org/time-zones) and [parse-zoneinfo](https://github.com/djzin/parse-zoneinfo).

**Comment by jkosh44** [comment]
> > The discrepancy seems to come from Chrono. PostgreSQL says that `CET` is +1:00:00
> 
> Well, I think this depends on the date. I had a similar discussion with @benesch recently (see: [#22944 (comment)](https://github.com/MaterializeInc/materialize/pull/22944#discussion_r1383460977)). You chose `(2000, 6, 1)` as a date, which is in summer so that `CET` is used as `CEST`, which is `CET` + DST.

Yeah exactly. However the PostgreSQL docs are a little unclear about whether `CET` should take into account daylight savings time or not. In the docs (https://www.postgresql.org/docs/current/datatype-datetime.html#DATATYPE-TIMEZONES) it says:

> PostgreSQL allows you to specify time zones in three different forms:
>
>   - A full time zone name, for example America/New_York. The recognized time zone names are listed in the pg_timezone_names view (see [Section 54.32](https://www.postgresql.org/docs/current/view-pg-timezone-names.html)). PostgreSQL uses the widely-used IANA time zone data for this purpose, so the same time zone names are also recognized by other software.
>
>   - A time zone abbreviation, for example PST. Such a specification merely defines a particular offset from UTC, in contrast to full time zone names which can imply a set of daylight savings transition rules as well. The recognized abbreviations are listed in the pg_timezone_abbrevs view (see [Section 54.31](https://www.postgresql.org/docs/current/view-pg-timezone-abbrevs.html)). You cannot set the configuration parameters [TimeZone](https://www.postgresql.org/docs/current/runtime-config-client.html#GUC-TIMEZONE) or [log_timezone](https://www.postgresql.org/docs/current/runtime-config-logging.html#GUC-LOG-TIMEZONE) to a time zone abbreviation, but you can use abbreviations in date/time input values and with the AT TIME ZONE operator.
>
>   - In addition to the timezone names and abbreviations, PostgreSQL will accept POSIX-style time zone specifications, as described in [Section B.5](https://www.postgresql.org/docs/current/datetime-posix-timezone-specs.html). This option is not normally preferable to using a named time zone, but it may be necessary if no suitable IANA time zone entry is available.
>
> In short, this is the difference between abbreviations and full names: abbreviations represent a specific offset from UTC, whereas many of the full names imply a local daylight-savings time rule, and so have two possible UTC offsets. As an example, 2014-06-04 12:00 America/New_York represents noon local time in New York, which for this particular date was Eastern Daylight Time (UTC-4). So 2014-06-04 12:00 EDT specifies that same time instant. But 2014-06-04 12:00 EST specifies noon Eastern Standard Time (UTC-5), regardless of whether daylight savings was nominally in effect on that date.

My interpretation is that abbreviations do not take into account daylight savings time, while full names do take into account daylight savings time. However, `CET` is both an abbreviation and a full name. So which one is it?

```
postgres=# SELECT name FROM pg_timezone_names WHERE name IN (SELECT abbrev FROM pg_timezone_abbrevs);
 name 
------
 EST
 CET
 GMT
 MST
 HST
 MET
 WET
 UCT
 EET
 UTC
(10 rows)

```

**Comment by benesch** [comment]
Recording an in-person conversation with @jkosh44: we expect this to be fixed by #22944. Just to confirm: @nrainer-materialize, you've been observing this inconsistency on the latest `main`, right? I.e., _without_ #22016.

**Comment by nrainer-materialize** [comment]
> Recording an in-person conversation with @jkosh44: we expect this to be fixed by #22944. Just to confirm: @nrainer-materialize, you've been observing this inconsistency on the latest `main`, right? I.e., _without_ #22016.

Great! Not sure what you mean with "without #22016" since that is an issue and not a pull request. Anyway, I last tested this on https://github.com/MaterializeInc/materialize/commit/e5da59fb685604016aa792426586114d6a37139b, which is from yesterday morning. Happy to retest it if needed.

**Comment by nrainer-materialize** [comment]
> > Recording an in-person conversation with @jkosh44: we expect this to be fixed by #22944. Just to confirm: @nrainer-materialize, you've been observing this inconsistency on the latest `main`, right? I.e., _without_ #22016.
> 
> Great! Not sure what you mean with "without #22016" since that is an issue and not a pull request. Anyway, I last tested this on [e5da59f](https://github.com/MaterializeInc/materialize/commit/e5da59fb685604016aa792426586114d6a37139b), which is from yesterday morning. Happy to retest it if needed.

Yes, I can confirm that https://github.com/MaterializeInc/materialize/issues/21999#issuecomment-1798088478 is reproducible with on today's commit 1b25fe090f on `main`.

**Comment by benesch** [comment]
Ugh, I meant to say without https://github.com/MaterializeInc/materialize/pull/22944. I expect the inconsistencies to be fixed by https://github.com/MaterializeInc/materialize/pull/22944.

**Comment by jkosh44** [comment]
I just checked, this is from https://github.com/MaterializeInc/materialize/pull/22944:

```
materialize=> SELECT timezone('CET', '2023-06-01 00:00:00+00'::TIMESTAMPTZ);
      timezone       
---------------------
 2023-06-01 01:00:00
(1 row)

```

So it's been fixed.

**Comment by jkosh44** [comment]
https://github.com/MaterializeInc/materialize/pull/22944 is merged so I'm closing this.

**Comment by nrainer-materialize** [comment]
Thank you!
