### ISSUE TITLE
[Inc 72] Fix shards with incorrectly serialized error types

### ISSUE THREAD

**Issue by dseisun-materialize** [MaterializeInc/materialize#22041]
## Problem
During an upgrade we made a backwards incompatible change to our DataflowError protos which meant any existing errors on a user cluster would panic on reboot as it was unable to decode them. While we've done the short term remediation we now need to "heal" the shards to ensure that they have consistently encoded error protos

**Comment by petrosagg** [comment]
This has been fixed
