### ISSUE TITLE
Nightly feature benchmark on a branch should compare against the common ancestor with `main`

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#22058]
### Feature request

Currently, the feature-benchmark always compares with `latest`. So if there is an ongoing feature-benchmark regression, all feature-benchmarks that run on a branch will report it even if the branch itself is not to blame.

To fix this, when running on a branch, the feature-benchmark should compare against the commit that is the ancestor of the PR being tested.

1. The environment variables that Buildkite sets can provide an indication of this is a build against main or against a branch
2. The code coverage code I believe already contains a logic to determine the common ancestor
3. Once the SHA is known, the feature benchmark should compare against the `unstable-SHA_GOES_HERE` tag.

**Comment by nrainer-materialize** [comment]
@philip-stoev: Some questions:
* What shall we do if `unstable-SHA_GOES_HERE` does not exist or cannot be resolved?
* Against what do we want to compare if we are not in a pull request but on `main`? Compare against `latest`?
