### ISSUE TITLE
Document (or require) correct Postgres replica identity setting

### ISSUE THREAD

**Issue by umanwizard** [MaterializeInc/materialize#2205]
See #2203 for context.

The `"before"` records are not emitted for updates unless the parameter `REPLICA IDENTITY FULL` is set on the corresponding table, causing Materialize to give incorrect results.

Ideally we would be able to detect from some Debezium metadata that this setting is not enabled, and report an error in Materialize when creating sources from such tables.

I'm not sure whether that's possible. If it's not, we should at least document the requirement. (Cc @sploiselle )

**Comment by quodlibetor** [comment]
We could add a `WITH` option saying something like `postgres_verify_db='postgres_uri'` and do verification ourselves.

**Comment by umanwizard** [comment]
No idea

**Comment by benesch** [comment]
Yes, this is explicitly described in the docs for REPLICA IDENTITY: 

https://www.postgresql.org/docs/12/sql-altertable.html#SQL-CREATETABLE-REPLICA-IDENTITY

> This form changes the information which is written to the write-ahead log to identify rows which are updated or deleted. This option has no effect except when logical replication is in use. 

You both need to be using the logical `wal_level` and `REPLICA IDENTITY FULL`.
