### ISSUE TITLE
Unable to connect from Microsoft Power BI

### ISSUE THREAD

**Issue by mathieuisabel** [MaterializeInc/materialize#2206]
When connecting to Materialize using the PostgreSQL implementation in Microsoft Power BI, the following error is generated:

PostgreSQL: 99999: unknown catalog item 'pg_type'

![materialize_power_bi](https://user-images.githubusercontent.com/15805484/75896258-d1258a80-5e04-11ea-865f-a22e874b2409.png)
![materialize_power_bi_error](https://user-images.githubusercontent.com/15805484/75896260-d1258a80-5e04-11ea-9dc4-21f6c2c58a05.png)

**Comment by cuongdo** [comment]
@mathieuisabel Thank you for filing this issue. We haven't yet tested with Microsoft Power BI, and it's attempting to access the `pg_type` view, which we don't support. This is part of #2157, which is a longer-term effort for us.

**Comment by morsapaes** [comment]
Power BI is working as of [Materialize v0.68](https://materialize.com/docs/releases/v0.68/).
