### ISSUE TITLE
OoM in Checks + DROP/CREATE replica

### ISSUE THREAD

**Issue by def-** [MaterializeInc/materialize#22080]
### What version of Materialize are you using?

f99d05e6ec5d

### What is the issue?

Seen in https://buildkite.com/materialize/tests/builds/64790#018ae100-71b6-4540-9433-c748899c4b58, https://buildkite.com/materialize/tests/builds/64701, 
https://buildkite.com/materialize/tests/builds/64832, https://buildkite.com/materialize/tests/builds/64749

Sometimes it happens during `> SELECT * FROM sink_large_transaction_view2`, sometimes during the new [sanity check](https://github.com/MaterializeInc/materialize/pull/20505). Based on this and the timing I'm not sure if we should consider this a regression. Maybe restarting Mz a few times is already increasing the memory consumption.

**Comment by philip-stoev** [comment]
Fixed by https://github.com/MaterializeInc/materialize/pull/22095
