### ISSUE TITLE
Release / nightly test for billing demo

### ISSUE THREAD

**Issue by cuongdo** [MaterializeInc/materialize#2211]
As part of the release process, we do a soak test for the billing demo that involves inserting 10 million records and performing some number of queries to verify that data is being inserted. We should automate this and possibly test for correctness. The latter may be possible given the work @ruchirK has already done to make the billing demo CI test.

**Comment by ruchirK** [comment]
I think we can close this?

**Comment by quodlibetor** [comment]
Oh yeah this is done. The test definitely needs to be improved, but it does exist and catches issues.
