### ISSUE TITLE
[Incident 75] Reclocking can starve CPU

### ISSUE THREAD

**Issue by benesch** [MaterializeInc/materialize#22128]
### What version of Materialize are you using?

v0.70.2

### What is the issue?

We observed in incident 75 that an `ENVELOPE UPSERT` source's reclocking operator was taking 100% of a `2xsmall` cluster's CPU and seemingly not making any progress in rehydrating the source.

Notably, the cluster had disk enabled. We were able to unwedge the source by enabling the `storage_dataflow_delay_sources_past_rehydration` LD flag (which is now enabled for all environments in production), which delayed the ingestion of _new_ records until after the initial records were rehydrated.

Unfortunately, this doesn't feel like a fix for the root cause of the problem. We've seen reclocking eat up an entire CPU in the distant past—e.g., [Dec 15, 2022](https://materializeinc.slack.com/archives/C010UVBK145/p1671147916463519)—and our fix there was just to allocate more CPUs to the affected cluster.

It feels like there is a lurking CPU starvation issue with the reclocking operator, where a steady trickle of new records can cause the reclocking operator to produce more work than it can retire (possibly due to a lack of compaction?), and thus wind up stuck forever.

Some Slack discussions:

  * @frankmcsherry and @petrosagg on the compaction of the reclocking shard: https://materializeinc.slack.com/archives/C01CFKM1QRF/p1695961499809889
  * @petrosagg @frankmcsherry @guswynn on the compaction of the reclocking shard: https://materializeinc.slack.com/archives/C01CFKM1QRF/p1696249652143109?thread_ts=1696248527.092849&cid=C01CFKM1QRF

**Comment by dseisun-materialize** [comment]
@petrosagg did an initial investigation here and wasn't able to find a clear source of the issue. We're going to add some logging so if this issue crops up again we'll have an easier time understanding the source of the issue. Otherwise we're pausing active work on this issue

**Comment by petrosagg** [comment]
I have opened a PR that adds the aforementioned log (I turned it into a metric so that we can track it over time) https://github.com/MaterializeInc/materialize/pull/23036

**Comment by benesch** [comment]
Quick status update: @petrosagg finally identified the cause of this bug ([Slack link](https://materializeinc.slack.com/archives/C01CFKM1QRF/p1709148677064979?thread_ts=1709076044.311069&cid=C01CFKM1QRF)). He's working on the permanent fix. We have a hotfix in v0.89.5 that has mitigated the issue in the affected customer's environment.

**Comment by benesch** [comment]
The long term fix is in #25720, but the review there will require a while to address. @petrosagg kindly put up a middle ground fix (https://github.com/MaterializeInc/materialize/pull/25842) that landed in time for next week's release. Calling this escalation complete.
