### ISSUE TITLE
alerting: Add alerts around Coordinator delays

### ISSUE THREAD

**Issue by ParkMyCar** [MaterializeInc/materialize#22134]
### Feature request

Follow up to https://github.com/MaterializeInc/incidents-and-escalations/issues/20

The amount of [coordinator delays above 1 second](https://grafana.dev.materialize.com/d/mR1Kg1d4z/environmentd-health?orgId=1&from=now-24h&to=now&viewPanel=8) we see at any given time is in the single digits. If we see this metric jump to the high 10s, low 100s, that's a good indicator that something is going wrong and Materialize is being negatively impacted. We should add alerting around this metric to more easily detect these scenarios.

**Comment by pH14** [comment]
@ParkMyCar I believe we have coverage here with https://grafana.dev.materialize.com/alerting/list?search=coordinator, is that right?
