### ISSUE TITLE
Subscribes should be closed when underlying view is dropped

### ISSUE THREAD

**Issue by jubrad** [MaterializeInc/materialize#22136]
### What version of Materialize are you using?

v0.70.2

### What is the issue?

Currently, if you are subscribing to a view which is dropped, the subscribe will stay open and the dataflow/arrangements for the view will continue as long as the subscribe is alive. This differs from the behavior of materialized views and tables which will drop the subscribe.

**Comment by teskje** [comment]
> This differs from the behavior of materialized views and tables which will drop the subscribe.

This is only true for materialized views and tables that are not indexed. If the subscribe is reading from an index, it will not be dropped, because of https://github.com/MaterializeInc/materialize/issues/20334.

**Comment by jkosh44** [comment]
Is my understanding correct that the following scenario is what this issue describes?

Session 1 executes the following:
```
materialize=> CREATE TABLE t (a INT);
CREATE TABLE
materialize=> CREATE VIEW v AS SELECT a + 1 FROM t;
CREATE VIEW
materialize=> COPY (SUBSCRIBE v) TO STDOUT;

```

Session 2 executes the following: 
```
materialize=> DROP VIEW v;
DROP VIEW

```

Then the subscribe from session 1 is never dropped?

If so, https://github.com/MaterializeInc/materialize/pull/21635 resolves this issue.

Feel free to re-open if I've misunderstood.
