### ISSUE TITLE
test: Speed up `mz-adapter catalog::tests::test_builtin_migration`

### ISSUE THREAD

**Issue by jkosh44** [MaterializeInc/materialize#22146]
Follow-up from: https://github.com/MaterializeInc/materialize/issues/21891

The `mz-adapter catalog::tests::test_builtin_migration` test is very slow. the last measured run was 114.583s. Much of this slowness is due to slow startup time since each test case needs to open a fresh catalog.

We should speed this test up.

**Comment by chaas** [comment]
Duplicate of #28722
