### ISSUE TITLE
Fast-forwarding timestamps of empty topics

### ISSUE THREAD

**Issue by nacrooks** [MaterializeInc/materialize#2215]
There is currently no way to fast-forward the timestamp of an empty topic. This will result in queries returning "No complete timestamp" instead of the empty set.

**Comment by frankmcsherry** [comment]
Is this a tricky design question, or just a bug at the moment? It seems like the timestamping machinery could in principle produce a stream of `offset=0, timestamp=ts` statements, or is that wrong?

**Comment by ruchirK** [comment]
I think the only non trivial detail is that the first valid kafka offset is 0 so you can't use 0 for this purpose (but you could use -1 or None)

**Comment by nacrooks** [comment]
It's not possible to use -1 as offsets are u64s, but it's definitely possible to offset our own "offsets" to be "+1" so that we start at 1 and offset 0 means fast forward the empty topic.  It should not be complicated.

**Comment by frankmcsherry** [comment]
I'm not entirely sure I grok what the challenge is. I could imagine (wrongly, maybe) that we associate timestamps to offset intervals, and `[0, 0)` is a totally legit offset interval describing no data. At least, in differential it corresponds to an empty interval (things greater or equal to the first thing, but not the second thing).

It might be worth shaking out what exactly we need to say about bundles of data (something I think @ruchirK is typing up) which might clarify what information needs to make it to the workers. Or it might not. But we might learn about what we need to say for Kinesis and other sources at the same time.

**Comment by nacrooks** [comment]
I agree with you. There's no real complexity in supporting that, just an oversight.

**Comment by frankmcsherry** [comment]
For example, I think the thing analogous to "batches" in differential would be a sequence of lower and upper timestamp bounds, and a description of the data they contain:
```
[lower, upper): <description of kafka offsets, partitions>
```
This might be more natural than a map from Kafka offsets to times, as we can have times evolve without changing the offset at all.

Not trying to rathole, but rather tease out the right "type" for the messages from the inputs to the workers, because we'll probably want the same class of information for the sinks, and for other interop.

**Comment by nacrooks** [comment]
Right now the "information" is: topic/timestamp/offset, which is short hand for saying, for a particular source, messages 0,1,2,3..offset (included) will be timestamped with t and we promise never to send a message with timestamp <= t. 

I *think* this is what you're saying?

**Comment by nacrooks** [comment]
#2214 PR adds support for empty streams. Closing.
