### ISSUE TITLE
pg-snapshot-partial-failure cluster test sporadic failure

### ISSUE THREAD

**Issue by def-** [MaterializeInc/materialize#22161]
### What version of Materialize are you using?

9d05f75baf6a

### What is the issue?

Test comes from https://github.com/MaterializeInc/materialize/pull/17699

Seen in https://buildkite.com/materialize/tests/builds/65124#018af9b2-9aeb-4fad-a354-f54335a84aef

The difference is the `can respond immediately: false` is actually `can respond immediately: true`. The comment tells me that this is actually an important difference and what we want to test here:
> Note that the above regex does NOT match timestamps that are `0`, and also that we check `can respond immediately` == `false`.
We are explicitly checking that the _upper_ of `two` has moved, but we see that we can't actually query any
data out of it yet.

See test/cluster/pg-snapshot-partial-failure/03-verify-good-sub-source.td

**Comment by guswynn** [comment]
Hmm, i am not sure what is going on here, ill bring it to the storage team

**Comment by guswynn** [comment]
Fixed by https://github.com/MaterializeInc/materialize/pull/22163
