### ISSUE TITLE
Expose a "dataflow hydrated" flag in SQL

### ISSUE THREAD

**Issue by teskje** [MaterializeInc/materialize#22166]
### Feature request

To let users (and the console) answer the question of whether a dataflow has finished hydrating, we need to expose a "dataflow hydrated" flag in SQL.

* The flag should be per dataflow (index, MV, source, sink) and per replica.
* It should be initialized as `false` when a dataflow or a replica is created and flip to `true` when the replica has first advanced the write frontier of the dataflow beyond the `as_of`.
* The flag should be exposed in an `mz_hydration_status` table with columns `(object_id, replica_id, hydrated)`.

**Comment by umanwizard** [comment]
@teskje is this not the same information as whether read frontier is less than write frontier?

**Comment by teskje** [comment]
Yep! See [this thread](https://materializeinc.slack.com/archives/C0637RN7PKQ/p1698946082495659).
