### ISSUE TITLE
Implement better offset tracking for Kinesis sources

### ISSUE THREAD

**Issue by JLDLaughlin** [MaterializeInc/materialize#2219]
In the V0 of Kinesis sources, we are simply going to enumerate the records we read from a Kinesis data stream and use that integer to downgrade capabilities. We're doing this because Kinesis record metadata is insufficient: 

1. Sequence numbers are a good candidate, but they are larger than what we can store in an i128.
2. Approximate arrival timestamp is not strictly increasing.

While this sort of works, it has a few problems:
- It doesn't work well with our timestamping code! For our real-time sources to update their offsets, we need to be able to query for the most recent offset. Since the enumeration is local to the `source` closure, we can't do that. I put in a hacky solution that is not ideal.
- **We can't do joins!** @frankmcsherry pointed out that for other sources, the first timestamp is the Unix Epoch and is updated from there. That means a Kinesis source starting at timestamp 1 would have a long way until it could be successfully joined.

cc: @nacrooks, @cuongdo

**Comment by JLDLaughlin** [comment]
@quodlibetor just sent me [this link](https://stackoverflow.com/questions/56352012/kinesis-creates-multiple-records-with-the-same-sequence-number), which also tells us that sequence numbers might not actually be unique!

**Comment by ruchirK** [comment]
I'm sorry I'm sure you've considered this a bunch already but I'm very
curious -- why don't the sequence numbers fit in a i128?

**Comment by JLDLaughlin** [comment]
An example sequence number was 57 digits long! So maybe sometimes they fit, but they certainly don't always work.

**Comment by ruchirK** [comment]
Can we define string timestamps?

**Comment by JLDLaughlin** [comment]
This issue has been moderately improved! Instead of using arbitrary enumeration values, we're just going to use the current system timestamp. This has its drawbacks, but should minimize issues with joins. 

That being said, this ticket should probably still be worked on! But is likely less urgent.
