### ISSUE TITLE
"Source/Sink Error Reporting" is flaky

### ISSUE THREAD

**Issue by nrainer-materialize** [MaterializeInc/materialize#22219]
### Buildkite link

https://buildkite.com/materialize/tests/builds/65324#018b01bf-f7f6-47e9-b5f9-a5a21934583a

### Relevant log output

```source
> SELECT bool_or(error ~* 'UnknownTopicOrPartition|topic')
FROM mz_internal.mz_sink_status_history
JOIN mz_sinks ON mz_sinks.id = sink_id
WHERE name = 'sink1' and status = 'stalled'
rows didn't match; sleeping to see if dataflow catches up 1s
10:1: error: non-matching rows: expected:
[["true"]]
got:
[["<null>"]]
Poor diff:
+ <null>
- true
     |
   9 | # check that there is a stalled status with the expected error.
  10 | > SELECT bool_or(error ~* 'UnknownTopicOrPartition|topic')
     | ^
```

### Additional thoughts

https://materializeinc.slack.com/archives/C01CFKM1QRF/p1696547503020739

**Comment by nrainer-materialize** [comment]
Marked as release blocker: https://materializeinc.slack.com/archives/CTESPM7FU/p1696591804752709?thread_ts=1696591686.227539&cid=CTESPM7FU

**Comment by guswynn** [comment]
I can't repro this locally;

i'm gonna add some logs/etc and try to debug it from ci
