### ISSUE TITLE
Dropping and re-adding subsource wipes it from mz_source_statistics

### ISSUE THREAD

**Issue by chuck-alt-delete** [MaterializeInc/materialize#22235]
### What version of Materialize are you using?

v0.71.0 (4c037eca0)

### What is the issue?

Here are the steps:

1. create postgres source with a publication that uses FOR ALL TABLES
2. drop subsource
3. drop original table in postgres and make a new table with the same name.
4. Add the subsource back with the same name
5. now that subsource shows up in `mz_sources` but not `mz_internal.mz_source_statistics`

**Comment by morsapaes** [comment]
@guswynn @petrosagg, will this be patched with the ongoing refactor in #25218?

**Comment by guswynn** [comment]
@morsapaes The new subsource will have a different id, but it should show up (but I haven't tested this)
