### ISSUE TITLE
::regclass can't handle schemas

### ISSUE THREAD

**Issue by def-** [MaterializeInc/materialize#22239]
### What version of Materialize are you using?

main

### What is the issue?

```
materialize=> set schema public;
SET
materialize=> create table t1 (c int);
CREATE TABLE
materialize=> select 'public.t1'::regclass;
ERROR:  object "public.t1" does not exist
```

Meanwhile on Pg this works fine:
```
deen=> select 'public.t1'::regclass;
 regclass
----------
 t1
(1 row)
```

**Comment by jkosh44** [comment]
This is related to https://github.com/MaterializeInc/materialize/issues/9484

I think there was a skunkworks PR to fix this, not sure what happened with it: https://github.com/MaterializeInc/materialize/pull/20407

**Comment by sploiselle** [comment]
Closed by https://github.com/MaterializeInc/materialize/pull/20407
