### ISSUE TITLE
Bump ulimit in systemd script

### ISSUE THREAD

**Issue by umanwizard** [MaterializeInc/materialize#2224]
We have reports of people using the systemd script in the Ubuntu package hitting file handle exhaustion.

**Comment by benesch** [comment]
Mentioned in Slack, but what version are they using? The auto ulimit bump only just landed in v0.1.2. Also don't think you'd need to bump it in the systemd script, given that we'll bump our own soft limit up to whatever the hard limit is? Assuming that logic is working correctly on Linux. I only tested it on macOS.

**Comment by umanwizard** [comment]
You're right -- if we are automatically bumping the ulimit in-process, there's no need to do it in the systemd script.
