### ISSUE TITLE
sql: litigate `ALTER ... SWAP` syntax

### ISSUE THREAD

**Issue by benesch** [MaterializeInc/materialize#22250]
In #12972, we proposed a new `ALTER ... SWAP` command that lets users ergonomically swap the names of two objects.

The syntax proposed in that issue was invented on the spot, though. We should survey other tools with a similar command and ensure our syntax is aligned with theirs.

Snowflake, for example, puts a `WITH` between the objects to be swapped, as in `ALTER ... SWAP old WITH new`.

cc @ParkMyCar

**Comment by ParkMyCar** [comment]
AFAICT Snowflake is the only product that offers this, and they use a syntax of:

```sql
ALTER SCHEMA blue SWAP WITH green;
```

So using this syntax sounds good to me!

Other products I checked that do not support a SWAP like feature: [Databricks](https://docs.databricks.com/en/sql/language-manual/sql-ref-syntax-ddl-alter-table.html), [RedShift](https://docs.aws.amazon.com/redshift/latest/dg/r_ALTER_TABLE.html), [DuckDB](https://duckdb.org/docs/sql/statements/alter_table),
