### ISSUE TITLE
doc: Explicit statement of client support

### ISSUE THREAD

**Issue by sploiselle** [MaterializeInc/materialize#2228]
Tracker:

* [ ] - #5874
* [x] - #9694 
* [ ] - #9720

**Comment by rjnn** [comment]
@sploiselle can you please add more detail? This issue is sparse.

**Comment by sploiselle** [comment]
We should add more explicit detail about which clients we support connecting to Materialize, as well as express known limitations around features that don't work with specific clients. An example here is `psql`, which works or is "fully supported," in contrast with any PostgreSQL GUI tool, which is likely to not behave well with Materialize at all.

This would also likely encompass things like driver support.

**Comment by morsapaes** [comment]
This is now being tracked and documented in [Tools and Integrations](https://materialize.com/docs/integrations/).
