### ISSUE TITLE
Add websocket endpoint to internal HTTP API

### ISSUE THREAD

**Issue by benesch** [MaterializeInc/materialize#22303]
### Feature request

*Part of epic https://github.com/MaterializeInc/console/issues/370.*

To fully support impersonation, we need the impersonated console to be able to make WS requests as `mz_introspection` via the internal HTTP port, just like it can make HTTP requests as `mz_introspection`.

The work here looks quite similar to https://github.com/MaterializeInc/console/issues/846. Considerations:

  * We'll need to add a /api/experimental/ws handler to the internal HTTP port, as it does not already exist.

  * We'll need to sort out authentication. The client-side WS API doesn't support attaching headers, but I think Teleport might be able to inject a `x-materialize-user` header into the WS Upgrade request anyway—and in fact it may already be doing so due to the [`rewrite`](https://github.com/MaterializeInc/cloud/pull/7653/files#diff-2a1479dea90617859c100a10411c70859a7883d93f90d38d67722a6ffffcca02R291-R295) configuration. If so, we can have the internal WS API not expect any authentication tokens from the client when the connection is established and instead use the user specified in the `x-materialize-user` header, defaulting to `mz_introspection` if no such header exists.

**Comment by rjobanp** [comment]
> We'll need to sort out authentication.

The Internal HTTP doesn't support authentication besides checking the `x-materialize-user` header anyways, right? I agree that if teleport attaches that header to the WS requests then this is super easy, since we already have that auth-check here: https://github.com/MaterializeInc/materialize/blob/main/src/environmentd/src/http.rs#L460

**Comment by rjobanp** [comment]
Oh actually I see what you mean, we likely have to work around the expected auth initialization routine currently expected by the websocket handler : https://github.com/MaterializeInc/materialize/blob/master/src/environmentd/src/http/sql.rs#L93

**Comment by benesch** [comment]
Yeah exactly! Will need to factor that out so that the auth check only happens for the external HTTP port but not the internal HTTP port. 

Btw, would recommend finding some low-risk way to test whether Teleport sends `x-materialize-user` on the initial WS request. Is it easy to point Teleport at a locally-running `environmentd` via ngrok, where you can `println!` the request that's coming through?

**Comment by rjobanp** [comment]
I've been implementing something that bypasses the initial websocket auth message entirely, but I now realize that the `options` that are included in that first message may be somewhat important (they are set here on the client side: https://github.com/MaterializeInc/console/blob/ead575d7991425ba38401795917cad0d0c2e4d58/src/api/materialize/websocket.ts#L151)

@RobinClowers do you think it's worth preserving that initial message to set the options for the websocket connection? I could make the `token` field optional when it's handled by the Internal HTTP API and make sure that teleport sets the `x-materialize-user` header

**Comment by RobinClowers** [comment]
@rjobanp good catch, I wasn't even thinking about that. Making the token optional seems better, since we need to be able to set options, and it keeps the interface the same between the two endpoints.

**Comment by benesch** [comment]
> @rjobanp good catch, I wasn't even thinking about that.

Agreed.

> Making the token optional seems better, since we need to be able to set options, and it keeps the interface the same between the two endpoints.

Agreed again! We definitely want to preserve the ability to send startup options even though we're not sending the token. Sorry for not catching this in my initial musing!

**Comment by rjobanp** [comment]
Cool sounds good, will refactor!

**Comment by rjobanp** [comment]
Confirming teleport does attach the `x-materialize-user` on websocket requests 😄

**Comment by benesch** [comment]
Finally, a stroke of luck!
