### ISSUE TITLE
sql: negative tests for casts

### ISSUE THREAD

**Issue by benesch** [MaterializeInc/materialize#2232]
@sploiselle pointed out in #2230 that we don't have any negative tests for either implicit or explicit casts. We should add some SLT logic tests for such.

Things to test:
  * Error messages when calling functions with invalidly-typed arguments.
  * Calling `CAST` where source and dest are not convertible.
  * Using the `::` operator where source and dest are not convertible.

**Comment by rjnn** [comment]
Tagging as 0.4 due to lack of testing smelling like technical debt (feel free to push back).
