### ISSUE TITLE
Support deleting and updating records from a dataflow without having to resend the entire record

### ISSUE THREAD

**Issue by wangandi** [MaterializeInc/materialize#2236]
~~Probably low priority project most suited for Skunkworks.~~ Is higher priority than previously thought due to upserts being dependent on this.

Differential deletes a row from a dataflow by adding an entry (row, time, -1). To construct this entry, you will need to pass to Differential the entire original row. 

In discussion with @frankmcsherry today, it should be possible to delete records by, say, the primary id only, from a dataflow using a custom iterative operator as described in this illustration: 
![IMG_2873](https://user-images.githubusercontent.com/5522362/76124228-39709980-5fc8-11ea-92b2-35b42246efd7.jpg)

Explanation of illustration:
1. Insert/delete/update message come in from a stream. Arrangement 1 (a.k.a. the left-hand one) is just the collecting of these messages. To save memory, we drop the trace handle and keep the collection.
2. Arrangement 2 (a.k.a. the right hand one) contains the dataset after the insert/update/delete messages were processed. 
3. There is a loop from Arrangement 2 back to a to-be-described operator that will collect batches of updates. When a batch is ready to run, it looks through everything that is currently in Arrangement 2, and appends to Arrangement 2 a (row, diff, -1) entry for every row that matched the deletion criterion.

**Comment by frankmcsherry** [comment]
To add some detail: the backward edge isn't meant to be an "iterative" edge, so much as a shared arrangement handle which gets pushed into the operator in the middle. The idea is that the operator can view the state of the downstream operator, to re-assembled the state of the arrangement just before it needs to process the updates. This should let it figure out what to retract when it needs to do so.

More generally, you could have this be an arbitrary state machine, which is an interesting idea. Or an alternate to `reduce` which uses the reduction function to update its maintained state.

**Comment by wangandi** [comment]
Hmm would this be useful for #1575?

**Comment by rjnn** [comment]
Yes, I think so

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by wangandi** [comment]
Closing because arrange_from_upsert exists in differential-dataflow since TimelyDataflow/differential-dataflow#263
