### ISSUE TITLE
mz_statement_execution_history sometimes gets lost on upgrade

### ISSUE THREAD

**Issue by def-** [MaterializeInc/materialize#22448]
### What version of Materialize are you using?

f45bf4c6cf

### What is the issue?

Failure seen in nightly: https://buildkite.com/materialize/nightlies/builds/4738#018b3d68-71d8-4623-9dd7-633ca50e289b
```
> SELECT sql, finished_status FROM mz_internal.mz_statement_execution_history mseh, mz_internal.mz_prepared_statement_history mpsh WHERE mseh.prepared_statement_id = mpsh.id AND sql LIKE '%/* Btv was here */' ORDER BY mseh.began_at;
rows didn't match; sleeping to see if dataflow catches up 50ms 75ms 113ms 169ms 253ms 380ms 570ms 854ms 1s 2s 3s 4s 6s 10s 15s 22s 33s 49s 74s 78s
^^^ +++
2:1: error: non-matching rows: expected:
[["SELECT 'goodbye' /* Btv was here */", "success"], ["SELECT 'hello' /* Btv was here */", "success"]]
got:
[["SELECT 'goodbye' /* Btv was here */", "success"]]
Poor diff:
- "SELECT 'hello' /* Btv was here */" success

     |
   1 | 
   2 | > SELECT sql, finished_status FROM mz_internal.mz_statement_execution_history mseh, mz_internal.mz_prepared_statement_history mpsh WHERE mseh.prepared_statement_id = mpsh.id AND sql LIKE '%/* Btv was here */' ORDER BY mseh.began_at;
     | ^
```
This check was just enabled in https://github.com/MaterializeInc/materialize/pull/22420
Local repro: `bin/mzcompose --find platform-checks down && bin/mzcompose --find platform-checks run default --scenario=UpgradeEntireMzPreviousVersion --check=StatementLogging`

**Comment by umanwizard** [comment]
Reposting what I sent to Dennis in a DM:

It is expected that the first row will disappear if there is an upgrade in between, because the tables get cleared if their schema changes. That is a known limitation currently. Is there a way to prevent the test from running in scenarios where the version of Mz changes between the two calls to manipulate? Or detect that in Validate so we can check for the proper responses?

**Comment by def-** [comment]
Good to know that this is expected. You can use `if self.current_version == self.base_version:` inside of the check to have code which should only be run when no upgrade happened.

**Comment by umanwizard** [comment]
In general, will upgrades always happen in between the two manipulates,
or can they happen at arbitrary times? (e.g. after both manipulates,
or before both)

**Comment by def-** [comment]
There are many different scenarios we run, so version can change inbetween any two checks and the verify check can be run any number of times in different versions.

**Comment by def-** [comment]
@umanwizard Tell me if I should take this over and fix up the test.

**Comment by nrainer-materialize** [comment]
This is still failing, causing all nightly builds to be red. Let me disable this check for now.

@umanwizard: Please fix and reenable it as soon as possible. Thank you!
If you don't have time, I can also look into it. Just let me know.
