### ISSUE TITLE
user/docs: Show example of request batching for webhook source

### ISSUE THREAD

**Issue by chuck-alt-delete** [MaterializeInc/materialize#22444]
### Documentation request

With the webhook source, the user can send a list of records in one request and then create a materialized view that uses `unnest` to unbatch them

**Comment by benesch** [comment]
Worked through this today with a customer. Since the webhooks are JSON you've got to use `jsonb_array_each` not `unnest`:

```
create materialized view webhook_unnested as select jsonb_array_elements(body) from webhook;
```

**Comment by chuck-alt-delete** [comment]
Looks like we have the doc now:
- https://materialize.com/docs/sql/create-source/webhook/#handling-batch-events

And we have the CREATE SOURCE batching option coming up soon, which will have its own documentation. Closing this.
