### ISSUE TITLE
Flaky failure in Maelstrom persist-txn coverage

### ISSUE THREAD

**Issue by def-** [MaterializeInc/materialize#22465]
### What version of Materialize are you using?

58c5323cfd

### What is the issue?

Seen in https://buildkite.com/materialize/nightlies/builds/4745#018b3ffa-3dc6-4166-ae75-fe218ca985b4
```
INFO [2023-10-17 23:37:58,956] jepsen test runner - jepsen.core {:perf {:latency-graph {:valid? true},
        :rate-graph {:valid? true},
        :valid? true},
 :timeline {:valid? true},
 :exceptions {:valid? true},
 :stats {:valid? false,
         :count 24,
         :ok-count 0,
         :fail-count 0,
         :info-count 24,
         :by-f {:txn {:valid? false,
                      :count 24,
                      :ok-count 0,
                      :fail-count 0,
                      :info-count 24}}},
 :net {:all {:send-count 28,
             :recv-count 28,
             :msg-count 28,
             :msgs-per-op 1.1666666},
       :clients {:send-count 26, :recv-count 26, :msg-count 26},
       :servers {:send-count 2,
                 :recv-count 2,
                 :msg-count 2,
                 :msgs-per-op 0.083333336},
       :valid? true},
 :workload {:valid? :unknown,
            :anomaly-types (:empty-transaction-graph),
            :anomalies {:empty-transaction-graph true},
            :not #{},
            :also-not #{}},
 :valid? false}


Analysis invalid! (?????? ???
```
Rerun succeeded. Since nothing was changed from testing-side and this happened 3 times in 2 days (https://buildkite.com/materialize/nightlies/builds/4738#018b3d68-7201-4f2a-872f-055775917419 and https://buildkite.com/materialize/nightlies/builds/4751#018b428d-5bc7-451e-9cae-292f4882f3bd), I'm assuming this might be a regression in product, thus marking as potential release blocker.
Similar failure ~1 year ago: https://github.com/MaterializeInc/materialize/issues/14575

**Comment by def-** [comment]
I believe this came from https://github.com/MaterializeInc/materialize/pull/22424 which fits the suspicious range of changes: https://github.com/MaterializeInc/materialize/compare/fda6738ac8...f45bf4c6cf and touched persist-txn

**Comment by danhhz** [comment]
This isn't used yet, so pulling off the release blocker flag. Will fix the flake soon!

**Comment by def-** [comment]
@danhhz Still seeing the same failures on main: https://buildkite.com/materialize/nightlies/builds/4810#018b59ba-7472-4fa7-8709-d9606d3ae81a

**Comment by danhhz** [comment]
Ah bummer! Well then I think it's time for me to toss up a PR to disable the test for now. I don't think I'm going to have time to look at this immediately. Will make sure to turn it back on before using this in prod
