### ISSUE TITLE
No stack trace is printed to materialized.log after a crash

### ISSUE THREAD

**Issue by wangandi** [MaterializeInc/materialize#2251]
Feel free to correct the area label if I have gotten it wrong.

It was reported that Materialize crashed and for reasons the output in the terminal/command prompt was not saved/could not be accessed. Unfortunately, there was no stack trace in `materialized.log`, so we do not know what happened.

**Comment by ruchirK** [comment]
we should double check that we didn't get OOM killed / some other external kill? not sure if rust would put down a stack trace in that case

**Comment by wangandi** [comment]
Indeed, rust might not print any stack trace in the case OOM or some external kill.

But I did a basic check where I added in a panic in a `create view` command. Then I ran a `create view` command, and materialized crashed, printing a stack trace in the terminal but not in the log file. The stack trace not being printed out in the log file is not good since we want people to be able to send us bug reports.
