### ISSUE TITLE
Duplicate offsets in Kafka

### ISSUE THREAD

**Issue by frankmcsherry** [MaterializeInc/materialize#2254]
We are seeing duplicate offsets in Kafka quite a fair bit. More specifically, the warning of duplicate messages, which is triggered by any out-of-order offset receipt. There are a few possible reasons this might happen, but we should enumerate them to ensure that we aren't accidentally suppressing valid data, nor repeating duplicate data (the latter does not happen in the error case).

@ruchirK has seen this locally, and might be a good place to start with local reproduction.

**Comment by ruchirK** [comment]
Regardless of whether or not we downgrade the log level i think that changing the error message to print the received offset and the current last processed offset would help

**Comment by frankmcsherry** [comment]
Per a slack discussion, if it turns out that this is due to spurious disconnect/reconnects, we should have all of the relevant information locally to fast-forward to the last received offset, rather than re-pulling all of the data.

**Comment by ruchirK** [comment]
is anyone taking a stab at this? if not I think I know how to whip this up for a single Materialize session pretty quickly

**Comment by cuongdo** [comment]
@nacrooks confirmed that the fix is part of the multi-partition PR

**Comment by nacrooks** [comment]
To be clear: I am unclear whether what you were seeing Ruchir was caused by a *single reset* (and us reprocessing all the data which would generate a large number of those in a short sequence of time) or multiple "transient" duplicates.

**Comment by nacrooks** [comment]
PR #2214 addresses the issue of resets causing many continuous resets, but does not address the underlying cause of the reset.
