### ISSUE TITLE
dataflow,sql: `RowSetFinishing::is_trivial` seems wrong

### ISSUE THREAD

**Issue by benesch** [MaterializeInc/materialize#2260]
Just eyeballing, but `RowSetFinishing::is_trivial` doesn't seem to take into account the projection like it probably should?

https://github.com/MaterializeInc/materialize/blob/4363d1992d59c2013ff3924b233fcc0611991df5/src/dataflow-types/types.rs#L123

/cc @frankmcsherry @umanwizard

**Comment by frankmcsherry** [comment]
Could be! Though, the place that function is used is to install a `TopK` so also maybe this is right (a projection shouldn't force us to insert a TopK). It's all a big tangle, tbh. It would be nice if the coordinator refactor addressed some of these things; it seems to be the place that much of the tangle centralizes.

If there is a bug, my best reading of it is potentially in subqueries or created views that have projections as part of their finishing actions, but do not have ordering. It would be weird that we haven't seen anything like this in tests.
