### ISSUE TITLE
Kinesis sources feel slow

### ISSUE THREAD

**Issue by JLDLaughlin** [MaterializeInc/materialize#2266]
I haven't measured this, but anecdotally I've been surprised by the latency between seeing a record flow through my Kinesis source code (via a dbg!() statement) and having it available to query (as part of a materialized view). I feel particularly surprised since the current implementation of Kinesis sources just constantly downgrades its capabilities using the current system time.

This ticket is a pending to do to measure Kinesis source performance and identify potential bottlenecks.

**Comment by rjnn** [comment]
I'd be interested in getting a bit of a rundown in terms of what improvements you made that (you suspect) make Kinesis not feel slow. Anecdotally, this sort of postmortem is likely to rapidly fade from your memory, but it will be very useful onboarding context to future programmers who add in new sources.

**Comment by JLDLaughlin** [comment]
I actually didn't make active improvements here! 

I think what happened is I almost always run materialized in debug mode locally and forget about the performance hit. Anecdotally, it felt like it took a while (multiple seconds) for newly created Kinesis sources over relatively empty streams to catch up to the tip of the stream.

After I started pushing Kinesis metrics to Prometheus/Grafana (https://github.com/MaterializeInc/materialize/pull/2688), I was able to see in preliminary load testing that we aren't lagging behind the tip of the stream at all.

**Comment by JLDLaughlin** [comment]
These are things that might be useful for future programmers:
- Having a Materialized best practices/deployment guide. It would spell out things like: don't run with --dev, how many threads to use, etc.. This would at least set some sort of consistent baseline.
- Pushing useful metrics to Prometheus/Grafana early.
