### ISSUE TITLE
Preserve connector metadata columns in Avro and Protobuf decoding

### ISSUE THREAD

**Issue by benesch** [MaterializeInc/materialize#2268]
External connectors currently expose metadata in an i64 column that represents, for files, the line number that produced the record, and for Kafka sources, the offset that produced the record. Regex and CSV decoding preserve this metadata column, while Avro and Protobuf decoding unintentionally drop this metadata column on the floor. We should teach Avro and Protobuf to preserve this record as well.

See https://github.com/MaterializeInc/materialize/pull/2261/files for more context.

**Comment by rjnn** [comment]
This is valuable to do eagerly, as a protobuf using prospect has mentioned repeatedly that they want that metadata.

**Comment by benesch** [comment]
Have we sorted out the issue with metadata columns making retractions impossible?

**Comment by morsapaes** [comment]
Can this be closed, now that #7004 landed?

**Comment by benesch** [comment]
Looks like it! We've still got #1577 for the rest.
