### ISSUE TITLE
ASSERT NOT NULL stops working after Mz upgrade

### ISSUE THREAD

**Issue by def-** [MaterializeInc/materialize#22715]
### What version of Materialize are you using?

bb9c8a6171

### What is the issue?

Failed in https://buildkite.com/materialize/nightlies/builds/4906#_, still working in the previous nightly:
```
> SELECT * FROM not_null_view1
query error didn't match; sleeping to see if dataflow produces error shortly 50ms 75ms 113ms 169ms 253ms 380ms 570ms 854ms 1s 2s 3s 4s 6s 10s 15s 22s 33s 49s 74s 78s^^^ +++
2:1: error: query succeeded, but expected error containing "column 1 must not be null"
     |
   1 | 
   2 | ! SELECT * FROM not_null_view1
     | ^
+++ !!! Error Report
```
Reproducer: `bin/mzcompose --find platform-checks down && bin/mzcompose --find platform-checks run default --check=MaterializedViewsAssertNotNull --scenario=UpgradeEntireMz`
I'm trying to bisect. Changes in this range is my current guess, but platform-check was broken before by other tests so might not be accurate: https://github.com/MaterializeInc/materialize/compare/5148c9642432b44756dd04c94fcefb5d1b5c8b17...bb9c8a6171fc51f707bd2e0ab87e9a91bb653c54

**Comment by def-** [comment]
```
10429a1b638ce0dc1c543515a4c8afc802e6f2bd is the first bad commit
commit 10429a1b638ce0dc1c543515a4c8afc802e6f2bd
Author: Marta Paes <marta.paes.moreira@gmail.com>
Date:   Wed Oct 25 09:14:48 2023 -0700

    doc/user: polish v0.73 release notes (#22458)

 doc/user/content/releases/v0.73.md | 97 ++++++++++++++++++++++++++++++++++++--
 doc/user/content/releases/v0.74.md | 11 +++++
 2 files changed, 104 insertions(+), 4 deletions(-)
 create mode 100644 doc/user/content/releases/v0.74.md
```
It was the version change causing this to get tested. So before we were on a too old version to have an actual upgrade and were only testing restarts.

So I think the actual issue is still valid, it works as expected without the upgrade inbetween:
```
materialize=> CREATE TABLE not_null_table (x INT, y INT, z INT);
CREATE TABLE
materialize=> INSERT INTO not_null_table VALUES (NULL, 2, 3), (4, NULL, 6), (7, 8, NULL);
INSERT 0 3
materialize=> CREATE MATERIALIZED VIEW not_null_view1 WITH (ASSERT NOT NULL x) AS SELECT * FROM not_null_table;
CREATE MATERIALIZED VIEW
materialize=> SELECT * FROM not_null_view1;
ERROR:  Evaluation error: column 1 must not be null
```

**Comment by umanwizard** [comment]
If the issue is only triggered by a version upgrade, I think we can consider this not to be a release blocker, as long as we fix it by the next version, since nobody is using it in prod yet anyway, and it's in private preview.

**Comment by umanwizard** [comment]
Actually, I suspect this isn't a real issue. `ASSERT NOT NULL` was broken in v0.73 (it disappeared after restart). In v0.74, it was fixed: see https://github.com/MaterializeInc/materialize/pull/22364 .

Thus, if you start on v0.73 and then upgrade to v0.74, the test will fail, due to the bug in v0.73. So I think we can just fix this by restricting the test to only run starting in v0.74.

**Comment by def-** [comment]
Glad to hear this is the same issue we had before. Easy fix then, I'll push a change to bump the version.

**Comment by umanwizard** [comment]
I already put up a PR, [see above](https://github.com/MaterializeInc/materialize/pull/22719)

**Comment by def-** [comment]
Confirmed manually that from v0.74.2 the upgrade/test works fine.
