### ISSUE TITLE
adapter: finishing over counts result sizes with limit present

### ISSUE THREAD

**Issue by mjibson** [MaterializeInc/materialize#22724]
The query `SELECT x FROM (VALUES ('{"row": 1}')) AS a (x), generate_series(1, 50000) LIMIT 1;` has its byte accounting at 50,000 x (byte size of `{"row": 1}`. The console sets a 1MB max_query_result_size, which exceeds this limit and returns an error. This is wrong because the limit means that we will never actually exceed this. Oddly, the max query result calculation is done twice in the finishing logic. I think the first one is wrong (this bug) and the second one is not needed.

The first one should be changed to never add more rows than are left in the limit.

**Comment by jkosh44** [comment]
If my memory is correct, the `max_query_result_size` also applies to data sent from compute to environmentd. So if all 50000 rows are being sent over the wire before we apply the limit, then it will trigger this error.

**Comment by mjibson** [comment]
Compute accrues rows into `row, diff` format, so duplicate rows would only get byte counted once there.

**Comment by jkosh44** [comment]
> Compute accrues rows into `row, diff` format, so duplicate rows would only get byte counted once there.

Doesn't the above query generate 50,000 unique rows though?

```
postgres=# SELECT * FROM generate_series(1, 50000) LIMIT 10;
 generate_series 
-----------------
               1
               2
               3
               4
               5
               6
               7
               8
               9
              10
(10 rows)

```

**Comment by mjibson** [comment]
https://github.com/MaterializeInc/materialize/blob/4a4aa0f2863f947a311ece5105fdd44db5f82663/src/expr/src/relation/mod.rs#L3072 is where that occurs, yes. Compute -> coord is with diff counts, coord does some safety checking then explodes out the each row into its count. See the linked PR here for more.
