### ISSUE TITLE
Adapter: returning max size limit error on some limit 1 queries

### ISSUE THREAD

**Issue by chaas** [MaterializeInc/materialize#22722]
### What version of Materialize are you using?

v0.72.0-dev (217bce545)

### What is the issue?

In some cases, `limit 1` queries are returning result exceeds max size errors erroneously. It appears the size limit is being applied to the entire underlying query before the limit 1 is getting applied.

Repro:
```
CREATE SOURCE counter
  FROM LOAD GENERATOR COUNTER
  (TICK INTERVAL '500ms')
  WITH (SIZE = '3xsmall');

CREATE INDEX counter_idx ON counter (counter);

CREATE MATERIALIZED VIEW slow_counter AS
WITH MUTUALLY RECURSIVE
  i (x bigint) AS (
    SELECT * FROM counter
  ),
  j (x bigint) AS (
    SELECT x from i
		CROSS JOIN LATERAL generate_series(1, (SELECT * from i order by x desc limit 1) * 1000)
  )
SELECT * FROM j;
```

Then wait a few seconds and
```
> select * from slow_counter limit 1;
Error: result exceeds max size of 1000.0 KB

> create view scv as select * from slow_counter limit 1;
> select * from scv;
x
1
```

Note, this isn't happening on tables as far as I can tell. I made a too-large table using `generate_series` and `limit 1` worked as expected:
```
> CREATE TABLE t2 (a int4);
> INSERT INTO t2 SELECT generate_series::int4 FROM generate_series(1, 30001);
> INSERT INTO t2 SELECT generate_series::int4 FROM generate_series(1, 30001);
> select * from t2;
Error: result exceeds max size of 1000.0 KB
> select * from t2 limit 1;
a
1
```

**Comment by teskje** [comment]
This is likely related to https://github.com/MaterializeInc/materialize/issues/21105

**Comment by chaas** [comment]
Duplicate of https://github.com/MaterializeInc/materialize/issues/22724
