### ISSUE TITLE
Wrong order with uppercase/lowercase letters

### ISSUE THREAD

**Issue by def-** [MaterializeInc/materialize#22805]
### What version of Materialize are you using?

f13fadbc03954ccb3ec0a00e84f4f35ce15177de

### What is the issue?

```
materialize=> create table t (c text);
CREATE TABLE
materialize=> insert into t values ('a'), ('A');
INSERT 0 2
materialize=> select * from t order by c;
 c
---
 A
 a
(2 rows)
```
Meanwhile in Postgres:
```
deen=> select * from t order by c;
 c
---
 a
 A
(2 rows)
```
So this is inconsistent with Postgres, we should at least document that if it's intentional.

**Comment by benesch** [comment]
I think this is a duplicate of https://github.com/MaterializeInc/materialize/issues/5579. In particular see this comment: https://github.com/MaterializeInc/materialize/issues/5579. 

> we should at least document that if it's intentional.

Agreed.

**Comment by nrainer-materialize** [comment]
Likely related: https://github.com/MaterializeInc/materialize/issues/22002

**Comment by def-** [comment]
Duplicate of #5579
