### ISSUE TITLE
sql: return column name instead of position in `ASSERT NOT NULL` violation errors

### ISSUE THREAD

**Issue by morsapaes** [MaterializeInc/materialize#22840]
### Feature request

With the first implementation of `ASSERT NOT NULL` (#22248), we return the column position whenever there's an assertion violation:

```sql
materialize=> SELECT * FROM users_and_orders_constraint;
ERROR:  Evaluation error: column 1 must not be null
```

It'd be more user-friendly to return the column name instead, as well as more consistent with other assertion errors (_e.g._ [column duplication](https://github.com/MaterializeInc/materialize/blob/05d78119d1af9cb665e7942329ebbe32a304c372/src/sql/src/plan/statement/ddl.rs#L2085)). cc @umanwizard

**Comment by umanwizard** [comment]
Definitely agree we should do this. It's a bit of work to pipe the column names through to where the error is generated, which is why I didn't do it for the v0, but I'll take care of this when I get some free time.
