### ISSUE TITLE
Document `to_timestamp` function

### ISSUE THREAD

**Issue by bhoomit** [MaterializeInc/materialize#2285]
Is it possible to convert integer epoch time to timestamp using SQL? 

Something like 

```
SELECT TIMESTAMP 1583982471;
```

**Comment by benesch** [comment]
I believe you're looking for the `to_timestamp` function:

```sql
materialize=> select to_timestamp(1583982471);
      to_timestamp      
------------------------
 2020-03-12 03:07:51+00
(1 row)
```

We should get that added to the docs. /cc @sploiselle
