### ISSUE TITLE
Increased hydration spike starting with version 0.74

### ISSUE THREAD

**Issue by teskje** [MaterializeInc/materialize#22885]
### What version of Materialize are you using?

v0.74

### What is the issue?

Starting with version 0.74 we observed higher-than-usual hydration spikes in at least one customer's environment, to the point where previously healthy replicas started OOMing and failed to come up successfully.

There is some evidence that this might be caused by https://github.com/MaterializeInc/materialize/pull/21968 but that might be a red herring.

[Discussion in Slack.](https://materializeinc.slack.com/archives/C02PPB50ZHS/p1698924563010499)

**Comment by benesch** [comment]
Linking in Slack conversation: https://materializeinc.slack.com/archives/C02PPB50ZHS/p1698924563010499

**Comment by vmarcos** [comment]
#22887 fixed this issue.
