### ISSUE TITLE
environmentd::run:environmentd::serve:storage::open:storage::open_inner: mz_stash::postgres: tokio-postgres stash error, retry attempt 1: stash error: incompatible Stash version 41, minimum: 25, current: 40, code: None

### ISSUE THREAD

**Issue by def-** [MaterializeInc/materialize#22941]
### What version of Materialize are you using?

5ac00836ed

### What is the issue?

Seen in https://github.com/MaterializeInc/materialize/pull/22937, Materialize fails to start after an upgrade when used with SSH tunnels:
```
platform-checks-materialized-1      | environmentd: 2023-11-05T11:56:21.736482Z  INFO environmentd::run:environmentd::serve:storage::open:storage::open_inner: mz_stash::postgres: tokio-postgres stash error, retry attempt 1: stash error: incompatible Stash version 41, minimum: 25, current: 40, code: None
platform-checks-materialized-1      | environmentd: fatal: stash error: incompatible Stash version 41, minimum: 25, current: 40
```
https://buildkite.com/materialize/nightlies/builds/5002
Since there was recent changes in the ssh tunnel code, I'm assuming this might be a release blocker.

ci-regexp: environmentd: fatal: stash error: incompatible Stash version 41, minimum: 25, current: 40

**Comment by ParkMyCar** [comment]
This bug confuses me, the [Stash version hasn't changed in ~3 weeks](https://github.com/MaterializeInc/materialize/tree/main/src/stash-types/protos), did the testing in #22937 do a downgrade while re-using the same Stash/CRDB instance?

**Comment by guswynn** [comment]
@def- I don't think this is possible with my ssh changes; that error only happens during the stash upgrade path, which was not touched, as @ParkMyCar mentioned (my pr's changed some sql, which does not change any stash definitions:

Is it https://github.com/MaterializeInc/materialize/pull/22937/files#r1383735001?

**Comment by def-** [comment]
I think I see why this happens and it's probably a test-only issue. I'll work to fix up my PR, sorry about the noise.

**Comment by guswynn** [comment]
@def- no worries, thank you!

**Comment by def-** [comment]
Fixed inline in https://github.com/MaterializeInc/materialize/pull/22937

**Comment by ParkMyCar** [comment]
No problem, thanks for fixing @def-!
