### ISSUE TITLE
Allow users to gain an idea of progress on processing a stream

### ISSUE THREAD

**Issue by wangandi** [MaterializeInc/materialize#2296]
This is a common thread in prospect feedback. A user would connect Materialize to a several GB stream. It would take a long time for Materialize to go through the whole stream. The user would not know how far Materialize has gotten in processing the stream.

**Comment by wangandi** [comment]
My thoughts on this:
With BYO consistency, it would be trivial to create a function that selects the `since` or `upper` of the primary index of a materialized view. 

With real-time, it would be harder since the timestamps we assign would not correspond to a user's understanding as to how much the kafka stream has advanced. But we could consider creating a `MAX_EVER` function that would output the max value of a column for any record that ever existed in the dataflow, which would be much faster than `MAX` at returning an output, and then the user could do `select MAX_EVER(record_date) from foo` to get an idea of how far Materialize has gotten in processing their stream. A `MAX_EVER` function would also be faster and less memory intensive in the case of an append-only stream, or the user expects the particular column to be monotonically increasing over time, like record date.

cc: @frankmcsherry

**Comment by nacrooks** [comment]
We could have an "intermediate" option where we periodically output how many records have been ingested per source (out of the total available), along with the timestamp of the latest record that has been ingested. This wouldn't represent the view itself, but it would at least be some information (which might anyways be useful)

**Comment by frankmcsherry** [comment]
I think this is literally what logical timestamps are meant to do. 

If there is a correspondence between logical times and their input offsets, we could certainly present that back at them (a logged collection that presents Kafka offsets for each part at each logical time). This could then be queried as they like, or joined with results if they want to extract results with consistent offset statements.

It might be that `COUNT(*)` works as well as `MAX_EVER` except in situations where the user doesn't know how many records are in their topics. I'm not especially sympathetic in that case (most apps I use report records loaded, when available, rather than bytes processed).

I'd be super hesitant to introduce something new and parallel to timestamps.

**Comment by frankmcsherry** [comment]
> a logged collection that presents Kafka offsets for each part at each logical time

This collection probably makes a lot of sense to build, imo, as it probably mirrors what are essentially the low watermark statements about the input. Wherever we get those from (BYO, or created ourselves) it seems reasonable to think about them as a collection that we can move through in time and ideally persist.

**Comment by frankmcsherry** [comment]
While this isn't helpful for all users, the Confluent Dashboard is one place that users should be able to see this information. In principle, it collects information about each of the consumer groups for each topic, and how far behind the head of each topic they are. This is probably not useful for the AWS managed Kafka offering, but I thought I'd drop it in here in case any users are using the value-added flavor of Kafka.

**Comment by quodlibetor** [comment]
One thing that can show "a measure of progress" is our `mz_dataflow_events_read_total` prometheus metric, it is currently faceted on `type` (e.g. avro, protobuf) not source kind (e.g kafka) or name (i.e. the source name) but if you're getting all your metrics by way of avro then it will give a rough heuristic pretty quickly.

That metric is exposed on our default grafana dashboard, or you can do e.g. `curl http://MATERAILIZED/metrics | grep 'mz_dataflow_events_read_total.*avro'`

**Comment by cuongdo** [comment]
Is this resolved by #2745? @quodlibetor, if so, could you please close?

**Comment by cuongdo** [comment]
We have this in the form of a Prometheus metric, so closing. Let's open a new issue if we need this in a different form.
