### ISSUE TITLE
backup+restore: parallel-workload: Negative count for thing in snapshot

### ISSUE THREAD

**Issue by def-** [MaterializeInc/materialize#22982]
### What version of Materialize are you using?

https://github.com/MaterializeInc/materialize/pull/22829

### What is the issue?

Happened in my WIP change https://github.com/MaterializeInc/materialize/pull/22829: https://buildkite.com/materialize/nightlies/builds/5032#018ba6d2-ca23-480f-af15-87353d98fa90
```
[worker_7] Query failed: SELECT * FROM "db-pw-1699311033-0_""`'><script>\xE2"."s-0_ðŸ‘¨â€ðŸ¦° ðŸ‘¨".table0  LIMIT 1; {'S': 'ERROR', 'C': 'XX000', 'M': 'Negative count for thing in snapshot'}
```
after a successful backup&restore cycle.

The code with the assertion comes from https://github.com/MaterializeInc/materialize/pull/21615 @bkirwi 

ci-regexp: Negative count for thing in snapshot

**Comment by bkirwi** [comment]
If this is a postgres source and a backup/restore workload - which looks possible, given my skim of the test output? - this is almost certainly a duplicate of https://github.com/MaterializeInc/materialize/issues/22770.

**Comment by def-** [comment]
That's right, duplicate of #22770.
