### ISSUE TITLE
Multi-partition Kafka buffering

### ISSUE THREAD

**Issue by nacrooks** [MaterializeInc/materialize#2300]
The Kafka streams currently buffers messages that do not yet have a timestamp assigned to them. The current design (a single "buffer slot") could cause a message from one partition (that has yet to be assigned a timestamp) to block messages from other partitions.

An alternative design would be to "locally" buffer messages that have not yet been assigned timestamps.
_Pros_: would not slow down data ingestion
_Con_: would increase memory pressure/cause many records to be stored in memory if the timestamping logic is trailing behind the data stream.

**Comment by sploiselle** [comment]
Some version of this has largely been done with reclocking
