### ISSUE TITLE
POST to webhook source failed: 500, internal storage failure! ShuttingDown("collection manager")

### ISSUE THREAD

**Issue by def-** [MaterializeInc/materialize#23028]
### What version of Materialize are you using?

b2941b3

### What is the issue?

Seen in https://buildkite.com/materialize/nightlies/builds/5065#018bae7f-6fea-48d9-85c9-782301f3ec03
```
ValueError: POST failed: 500, internal storage failure! ShuttingDown("collection manager")
```
There were no restarts or panics, so I'm not sure what happened here.

**Comment by def-** [comment]
Also reproduced locally:
```
materialize.data_ingest.query_error.QueryError: ('POST failed: 500, internal storage failure! ShuttingDown("collection manager")', 'POST http://localhost:6976/api/webhook/db-pw-1698426099-0/s-0/wh-2 Headers: ih0: b\'"woJILJvCDe7s03BPINbjpOhUs47bpG4BhGoyrqSZCrOYqjyWAvwiHuzU7AROfjmul644uUBmLkQcd1ji4r3sFMc1ZNNpi17X4m0G"\', ih1: b\'"XFMYmpjVLIenYnooy1AxPEzIpr8kXy7L5u51IlJ8NP9AFAeoAWjAg4BPEiCjQkCTMuosbjTyX03MFZsLUcwxbQ58CQebyN72KsXc"\', ih2: b\'"MbFIDQ8PFCMDSvnaqgZJq2szK8ddnhfrtpBa0MqlP10aURjFE523OmT1jfxTN11AnfBkbcK0rtSZ11DFQErG0gILGXCfkedQ5anX"\', ih3: b\'"acQPAs8OKKwUT9KfZZRoBf0Im60stqm0k4mZq6BsetX1GuO7I1jS4AHbEfAgFnPk6jtZvCUIOCWf2rIv1OgdR3YelN0XUS0V2KLA"\' Body: b\'DBoqTqAZ8z0nvLkCYa21euMjsNvrWDxP7oiKTKwWgUjYfgppiOS3yL9352tAUURPQFjqq9aaVHSKWDyrzcadTCYgr59iHscHArvV\'')
```
It seems like the source was just dropped: `DROP SOURCE "db-pw-1698426099-0"."s-0"."wh-2";`
Just to confirm, this seems expected to me, right?

**Comment by ParkMyCar** [comment]
Yeah this error is expected if the source got dropped. Maybe we should change the external HTTP error to something like 410 Gone?

**Comment by def-** [comment]
`internal storage failure!` sounds scary to me, maybe also adapt the error message to something that explains what happened.
