### ISSUE TITLE
[Epic] Use-case isolation M0: Isolated Number of Tables

### ISSUE THREAD

**Issue by aljoscha** [MaterializeInc/materialize#23034]
## Background

Use-case isolation is meant to provide customers with the tools for managing incidental unavailability. This seems cryptic, but what it roughly means is that we want a scale-able serving layer and/or a serving layer where use-cases/query workloads can be isolated from each other.

This is the tracking issue for **Milestone 0**, see (internal) doc with more context and description of the milestones: https://www.notion.so/materialize/Use-case-Isolation-Milestones-f1a37b024ea74b7c9d870778c4349fe3

```[tasklist]
### Subtasks
- [ ] https://github.com/MaterializeInc/materialize/pull/20954
- [ ] https://github.com/MaterializeInc/materialize/issues/22173
```

**Comment by danhhz** [comment]
@aljoscha This pretty duplicative of #22173 to me. How would you feel about closing this and renaming that one?

**Comment by aljoscha** [comment]
closing in favour of https://github.com/MaterializeInc/materialize/issues/22173
