### ISSUE TITLE
PersistLocation consensus_uri changes in tests

### ISSUE THREAD

**Issue by sploiselle** [MaterializeInc/materialize#23088]
### What version of Materialize are you using?

v0.77.0

### What is the issue?

Visible [in this nightly](https://buildkite.com/materialize/nightlies/builds/5102#018bb60d-ad85-49ea-9d0c-1e3af8aff190), the `PersistLocation`'s `consensus_uri` changes while the test is running. This looks like it might be occurring during reconciliation, which might make sense––a new environmentd might have a new consensus_uri.

Is the consensus URI changing OK? If so, we can ignore the field in the `alter_compatible` checks.

cc @MaterializeInc/testing

**Comment by def-** [comment]
Where do you see the issue?
Is it in the bounded-memory failure you linked to or [Full Testdrive in Cloudtest (K8s)](https://buildkite.com/materialize/nightlies/builds/5102#_)? For the latter I also just opened an issue: https://github.com/MaterializeInc/materialize/issues/23087

**Comment by sploiselle** [comment]
@def- yes, it's the bounded memory test that I linked. You can see the failure I'm referring to in the logs

**Comment by sploiselle** [comment]
Derp--I had thought we closed that ticket. Marking it as the release blocker

duplicate of #23088
