### ISSUE TITLE
Track memory usage in `MergeSorter`

### ISSUE THREAD

**Issue by umanwizard** [MaterializeInc/materialize#23081]
### Feature request

If lots of data is emitted at a particular timestamp without that timestamp being closed (and therefore an arrangement batch being minted), said data will accumulate in the buffers maintained by the [`MergeSorter`](https://github.com/timelydataflow/differential-dataflow/blob/438804d9/src/trace/implementations/merge_batcher.rs#L134-L135). This is a possible source of missing memory attribution.

Today, it might be expensive to track memory usage here, as we would have to look at every row. However, after https://github.com/TimelyDataflow/differential-dataflow/pull/348 lands, it should be much cheaper to attribute memory, and we should do so.

**Comment by vmarcos** [comment]
Relevant PR that would, if merged, add accounting of size events for the arrangement holding pen: https://github.com/TimelyDataflow/differential-dataflow/pull/434
