### ISSUE TITLE
storage/sources: expose progress information

### ISSUE THREAD

**Issue by dseisun-materialize** [MaterializeInc/materialize#23154]
## Product outcome
As a user of materialize sources I want to:
* Be able to see how my initial source snapshot (aka source "hydration") is progressing and when it's complete
* Be able to see what the lag is between my upstream system and materialize
* [Stretch] Be able to know that I'm "completely caught up" if materialize ever is able to validate that there's no additional upstream data to consume

### Initial hydration
As a user, I largely want to know:
* Is my snapshot progressing
* How long until my snapshot is complete

#### Snapshot progressing
* As a user I want to think of "snapshot progress" as row counts or secondarily bytes transferred. While row sizes can understandably vary, the simplicity of the mental model and ability to easily compare it to my source system (e.g. with a select count(*) ) make it what I will generally reach for initially
* I also want to know the change in snapshot progress to infer when my snapshot will be done and to have confidence that it's not stuck. As a V0 it's likely sufficient to just query a static table several times to start to understand the rate of progress, but later versions should more directly express how quickly the snapshot is progressing

#### Viewing lag
* As a user I want to understand roughly how many seconds behind my source is from my upstream system. I will not have thought deeply about what this means initially so I'll be looking for materialize to explicitly set my expectations
* I likely want to know how long it takes between a given max LSN existing on my upstream datasource and it being reflected and available in my materialize source
* There's a delta in my mental model vs how materialize works: I think in terms of "when I insert a record, when will it be reflected in materialize", but because we only reach out to upstream systems 'x' times every second, it will depend when the record was inserted relative to this polling interval. I should be informed that there will be some inherent (low) variability in my lag based on this
* I also want to be able to see the lag over time to understand "is my source keeping up". 
* [Stretch] If materialize is ever certain that they've processed _all_ new data (e.g. they reached out to my upstream system and found nothing new) I want to know that I'm "fully caught up"

### Work items

* [x] Don't reset `mz_source_statistics` on restart
* [x] Update documentation for `mz_source_statistics` to indicate which fields are approximations

**Comment by dseisun-materialize** [comment]
@benesch after some playing with that table I think it's got most of it! We do need some information from the source system to know the size of the snapshot (rows or bytes). Otherwise it feels like we have enough at least for a V0 in console

**Comment by benesch** [comment]
> @benesch after some playing with that table I think it's got most of it! We do need some information from the source system to know the size of the snapshot (rows or bytes). Otherwise it feels like we have enough at least for a V0 in console

Yep, exactly! I'm not sure there's a good way to get that snapshot from the source system in all cases (maybe you can do rows for PostgreSQL? and maybe Kafka has some stats API?) but even just showing the raw number of "bytes processed" or "rows processed" in console IMO is a good v0, because then you can go open your monitoring console for your upstream system to get the "total bytes" or "total rows" (if available).

**Comment by ggnall** [comment]
Added a v0 Console list for already available statistics. Worth noting that webhook sources don't have any sense of progress today (neither `_progress` subsources nor `mz_source_statistics` entries).

**Comment by dseisun-materialize** [comment]
[Linking a brainstorming doc with some customer discovery etc...](https://docs.google.com/document/d/16EBcAWG47dCKEZYlypGC85h4b98mdnisOiwq7U1QLrY/edit#heading=h.j8bb59nqxzyo)

**Comment by parkerhendo** [comment]
@ggnall @dseisun-materialize Looking at the v0 items above. Are we able to get any notion of ingest rate (e.g. rows or bytes per second)?

Ideally in this context we can show _"300 bytes ingested at 1.5 bytes/second"_ or something along those lines.

**Comment by benesch** [comment]
> @ggnall @dseisun-materialize Looking at the v0 items above. Are we able to get any notion of ingest rate (e.g. rows or bytes per second)?
> 
> Ideally in this context we can show _"300 bytes ingested at 1.5 bytes/second"_ or something along those lines.

Yes, for any column in [`mz_internal.mz_source_statistics`](https://materialize.com/docs/sql/system-catalog/mz_internal/#mz_source_statistics), you can `SUBSCRIBE` to the table (using `AS OF` and `UP TO` if you like) to see how the values change over time. In this case, `bytes_received` should be exactly what you're looking for.

For anyone who's thinking about this issue: I _highly_ recommend creating a PostgreSQL or Kafka source and `SUBSCRIBE`ing to the `mz_source_statistics` table while it's ingesting to get a feel for how these metrics work.

**Comment by ggnall** [comment]
Pardon noise! 😅 
Peeling out the Console work to "reveal what we've got" here: https://github.com/MaterializeInc/materialize/issues/23154
We'll continue to share forward looking designs and pull more requests out of this storage side work.

**Comment by benesch** [comment]
@ggnall did you mean to link to https://github.com/MaterializeInc/console/issues/1197?

**Comment by guswynn** [comment]
@ggnall @RobinClowers @parkerhendo 

I discussed some of this with Robin at the onsite, as well as a long discussion on storage metrics among the team, and I think what we want to offer the user is:

- A semi-granular understanding of the _current size_ of their source. This is just https://materialize.com/docs/sql/system-catalog/mz_catalog/#mz_storage_usage but collected more than once and hour
- The _current number of updates_ in their source.
  - Its also possible that persist could tell us the number of values, basically by summing the the positive and negative diffs
- For `USPERT/DEBEZIUM` sources:
  - The size and number of values in the source (this is `envelope_state_bytes/count` in `mz_source_statistics`)
  - Some notion of progress for _rehydration_ (at the very least the number of keys we have processed vs the total, even better is number of updates). This requires we _remember_ the previous values in `mz_source_statistics` when replicas are restarted
- Clear and documented semantics for `mz_source_statistics`
  - The ephemerality of the data is documented but may not be clear.
  - We don't reset them on replica-reconnection, which we should
  - It should be made clear when they are reset (maybe with a new column that tells you)
- Better information about _hydration_ ("snapshotting") progress
  - Postgres and kafka operate differently but what we came up with is:
    - When starting a source, we can record the snapshot lsn (for pg) and offsets (for kafka), and then report the rate at which we are reading lsns/offsets. This should give the user a good rough estimate on how much of the snapshot we have processed.
    - **Technically we often read faster than we commit data, but once we have hydration backpressure, this number becomes extremely accurate**
    - We can enrich this information by exposing how much buffered data we have in each stage of storage (read-from-upstream, decode, envelope, commit-to-persist)
    
    
Does that cover what you all want? (PLEASE tell me to clarify any sections that don't make sense)

**Comment by RobinClowers** [comment]
@guswynn this is great, thanks for writing it up. The only thing you didn't mention is turning on retention for `mz_source_statistics`, which we need for the graphs we want to show.

**Comment by guswynn** [comment]
@RobinClowers ah yes, let me check my back of the envelope math for that

**Comment by guswynn** [comment]
We also may want to consider some synchronization so the staged/read/committed values are more directly comparable; currently workers operate independently so their can be skew

**Comment by RobinClowers** [comment]
@guswynn for non-upsert sources, is `rehydration_latency` always null? That seems a bit confusing, what do you think about setting to 0 for non-upsert sources?

**Comment by guswynn** [comment]
@RobinClowers we don't actually do rehydration of any form for non-upsert sources so I landed on `NULL`, but if thats confusing we can change it!

**Comment by RobinClowers** [comment]
I see what you mean, 0 is maybe odd. What we really want is a way to tell if a given source is expected to populate that value, right now you have to know which types of sources populate this column. To restate the problem, I want to write a query that tells me if a source is ready to go, and currently there is no way to tell if `null` means the source is not yet hydrated, or if it doesn't have hydration time (and thus is ready ~immediately).

**Comment by guswynn** [comment]
@RobinClowers you can join with `mz_sources` to determine the `envelope_type`, does that work? it shouldn't make the query meaningfully more expensive

**Comment by RobinClowers** [comment]
I guess so? Is it guaranteed to always tell us which sources will have a `rehydration_latency`?

**Comment by guswynn** [comment]
@RobinClowers, yeah only for `envelope_type = ('debezium', 'upsert') is it meaningful

**Comment by RobinClowers** [comment]
That feels like a lot to put on users, and what if we support some other different type of upsert in the future? I'd prefer a some column that explicitly tells us: this source will require rehydration.

**Comment by benesch** [comment]
I'm personally a proponent of using zero for non-upsert sources. It feels natural to me. If we describe ENVELOPE NONE sources as "rehydrating instantly" rather than "not rehydrating", does that make zero make more sense to folks?

**Comment by benesch** [comment]
@petrosagg on Slack says: "We do rehydrate the reclock state for any type of source so this number [the rehydration latency] could even become meaningful"

**Comment by morsapaes** [comment]
The last chunks of work have been shipped with Materialize v0.89. For an implementation overview, see [this `#shipped-it` post](https://materializeinc.slack.com/archives/C04PB3GAQCF/p1708628503163209) (internal Slack).

Related work that remains open:

- [ ] https://github.com/MaterializeInc/materialize/issues/24868
- [ ] https://github.com/MaterializeInc/materialize/issues/24942
- [ ] https://github.com/MaterializeInc/materialize/issues/25501 (mitigated in #25501)
