### ISSUE TITLE
A better explain plan for materialized views

### ISSUE THREAD

**Issue by ruchirK** [MaterializeInc/materialize#2315]
Right now -- in order to view the plan for a view (no pun intended) you have to do:

`explain plan for <query text of view>`

IMO this is pretty unintuitive for me / users of Materialize and we should be able to throw some some syntactic sugar on this

**Comment by jamii** [comment]
This is in my queue, part of https://github.com/MaterializeInc/materialize/issues/1752

**Comment by jamii** [comment]
This was fixed by https://github.com/MaterializeInc/materialize/pull/2394
