### ISSUE TITLE
Remove `CREATE INDEX <name>` from builtin index definitions.

### ISSUE THREAD

**Issue by jkosh44** [MaterializeInc/materialize#23200]
### Feature request

Similar to #17892 but for indexes. 

https://github.com/MaterializeInc/materialize/blob/5f379bde442940336bffe0e83b415a45797c7ffb/src/adapter/src/catalog/builtin.rs#L148-L153
When defining a builtin index we specify the view name, schema, and sql which takes the form: `CREATE INDEX <schema>.<name> IN ...`. This leaves opportunity to accidentally create an inconsistency with the name and schema field and the name and schema in the sql definition. For example

Instead, the `sql` field should just be the part of the SQL that comes after the name. Then we can add the following function to `BuiltinView`:
```Rust
fn create_sql(&self) -> String {
  format!("CREATE INDEX {}.{} {}", self.schema, self.name, self.sql)
}
```

**Comment by friendlymatthew** [comment]
Hey Joe, happy to take on this issue. 🦅
