### ISSUE TITLE
Fix discrepancy in BuiltinView names

### ISSUE THREAD

**Issue by jkosh44** [MaterializeInc/materialize#23201]
### What version of Materialize are you using?

v0.78.0-dev

### What is the issue?

As discovered in https://github.com/MaterializeInc/materialize/pull/23125 there's a discrepancy between the name/schema in the `name`/`schema` field and the `sql` field of the following builtin views:

- `MZ_OBJECT_FULLY_QUALIFIED_NAMES`
- `MZ_DATAFLOW_OPERATOR_PARENTS_PER_WORKER`
- `MZ_DATAFLOW_OPERATOR_PARENTS`

We need to update these builtin views to fix the discrepancies. See https://github.com/MaterializeInc/materialize/pull/23125#issuecomment-1807238403 for more details.

**Comment by friendlymatthew** [comment]
Hi Joe -- have a quick fix for this: https://github.com/MaterializeInc/materialize/pull/23206
