### ISSUE TITLE
materialized container keeps crashing without relevant logs

### ISSUE THREAD

**Issue by bhoomit** [MaterializeInc/materialize#2322]
docker-compose.yml

2 CPUs, 15 GB RAM

```
version: '3.7'
services:
  materialized:
    image: materialize/materialized:latest
    ports:
      - 6875:6875
    volumes:
      - ./materialized/mzdata:/mzdata
      - ./materialized/logs:/logs/
    entrypoint:
      - materialized
      - --log-file=/logs/materialize.log
  mzcli:
    image: materialize/mzcli
    links:
      - materialized
```

```
Mar 16 03:32:21.432 ERROR dataflow::decode::avro: avro deserialization error: Decoding error: Union index out of bounds
Mar 16 03:32:45.305 ERROR dataflow::decode::avro: avro deserialization error: Decoding error: Union index out of bounds
Mar 16 03:33:00.409 ERROR dataflow::decode::avro: avro deserialization error: Decoding error: Union index out of bounds
Mar 16 03:33:13.421 ERROR dataflow::decode::avro: avro deserialization error: Decoding error: Union index out of bounds
Mar 16 03:33:18.553  WARN dataflow::source::kafka: duplicate Kakfa message: souce kafka-u37-0 (reading topic gia_avro_uncategorized_4, partition 6) received offset 1 max processed offset 113114
Mar 16 03:33:18.553  WARN dataflow::source::kafka: Fast-forwarding consumer on partition 6 to offset 113114
Mar 16 03:33:37.724 ERROR dataflow::decode::avro: avro deserialization error: Decoding error: Union index out of bounds
Mar 16 03:33:44.222  WARN dataflow::source::kafka: duplicate Kakfa message: souce kafka-u37-0 (reading topic gia_avro_uncategorized_4, partition 7) received offset 1 max processed offset 605946
Mar 16 03:33:44.229  WARN dataflow::source::kafka: Fast-forwarding consumer on partition 7 to offset 605946
Mar 16 03:33:46.863 ERROR dataflow::decode::avro: avro deserialization error: Decoding error: Union index out of bounds
```

**Comment by wangandi** [comment]
Hi @bhoomit! Note that if you are using the image tagged `latest`, you are running our master branch as of the last merge in github, which may be unstable. We recommend using a version tagged something beginning with a `v`, which should 1) be more stable 2) make it easier for us identify which version of the materialize you are running. For more information see: https://materialize.io/docs/versions/

If you absolutely want to use an unstable version, maybe to immediately try out a bug fix, and you create a bug report, can you run `docker images|grep materialized |grep latest` so we can see the exact image id of materialize? 

That said, we should have fixed the lack of stack trace being printed out as of #2252, and it should be imminently being released in `v0.1.3`, but you can try it out in `v0.1.3-rc3`.

**Comment by bhoomit** [comment]
> Hi @bhoomit! Note that if you are using the image tagged `latest`, you are running our master branch as of the last merge in github, which may be unstable. We recommend using a version tagged something beginning with a `v`, which should 1) be more stable 2) make it easier for us identify which version of the materialize you are running. For more information see: https://materialize.io/docs/versions/
> 
> If you absolutely want to use an unstable version, maybe to immediately try out a bug fix, and you create a bug report, can you run `docker images|grep materialized |grep latest` so we can see the exact image id of materialize?
> 
> That said, we should have fixed the lack of stack trace being printed out as of #2252, and it should be imminently being released in `v0.1.3`, but you can try it out in `v0.1.3-rc3`.

Hi @wangandi  Sorry about that. 

The version is materialized v0.1.3-dev (f08197e0317f7159a1dce0bbce0fbd01c45dded5)

```
materialize/materialized   latest              53356ce3e5c4        12 hours ago        849MB
```

Still, it doesn't print a stack trace. 

My guess is, its happening due to memory. I'm running EC2 R5 xlarge - 32 GB RAM, 4 vcores, 4 GB SWAP. 

I will downgrade the image and let you know. But meanwhile, can you tell me the desired configuration if I want to ingest around 1 Billion events and ~20 materialized views. My container is crashing around 40 Million.

**Comment by frankmcsherry** [comment]
> can you tell me the desired configuration if I want to ingest around 1 Billion events and ~20 materialized views.

Unfortunately, this is going to depend on a lot of things, including how complicated your events are, and what the views require. 

As a totally not made up example, I have a 102M row taxi data set, and one view asking about fare statistics for each passenger count. The memory footprint is a few megabytes. This is almost certainly not representative, but it does highlight how much things could vary.

I'd start with limited prefixes of your data, and try and see how far you get cleanly and what the load appears to be. You could also throw up your queries (here, or perhaps on the gitter channel) and it might be that they have some nice structure that can reduce the memory footprint.

**Comment by benesch** [comment]
Assuming no news is good news. Closing, but feel free to follow up if you're still having trouble.
