### ISSUE TITLE
webhooks: Validate behavior with special characters

### ISSUE THREAD

**Issue by ParkMyCar** [MaterializeInc/materialize#23247]
### What version of Materialize are you using?

v0.78.0-dev

### What is the issue?

The web application validates that names of databases, schemas, and webhooks do not contain special characters. This validation is not performed when using a pgsql client.

It is possible to create databases, schemas, and webhooks that include any characters. As such, a webhook called `../` is possible and will lead to some bugs where this source is not available from the UI as the browser will parse `../` and try to read `/sources/u58/materialize/errors` instead of `/sources/u58/materialize/public/%2e%2e/errors`. The same bug happens with a source containing CRLF characters.

More context, [Slack](https://materializeinc.slack.com/archives/C03QLQK1Q3A/p1700143869320149).

It's not entirely clear if we want to add the same validation at the pgwire layer that the web console makes. But we should at least make sure special characters don't break other behavior

**Comment by benesch** [comment]
I don't totally follow where the bug is, @ParkMyCar! The console seems to correctly URL encode source names, so that e.g. a source named `../` is linked to via: https://console.materialize.com/regions/aws-us-east-1/sources/u3687/materialize/public/..%2F/errors. 

It seems like everything works out exactly as it should as long as the end user uses the appropriate URL-encoded value. We even remember to URL encode in the notice we send back!

<img width="695" alt="image" src="https://github.com/MaterializeInc/materialize/assets/882976/d7297efb-3234-4b3a-bf6d-726b61691607">

> It's not entirely clear if we want to add the same validation at the pgwire layer that the web console makes. But we should at least make sure special characters don't break other behavior

I'm not totally sure I follow! It seems like everything is already working as well as it possibly can in the face of special characters.

**Comment by benesch** [comment]
Ah, I see. There is one bug here, which is when a webhook name, schema name, or database name is `.` or `..`. It is unfortunately not possible for a path segment to be `.` or `..`. Even if you escape it as `%2e%2e`, URL libraries will normalize it away. Hmm. I think there are two options, neither great:

1. When creating a webhook source, error if the database name, schema name, or item name is `.` or `..`.
2. Don't use the URL library to construct the webhook URL. Instead, use `format!` plus a direct call to `urlencode` from the https://docs.rs/urlencoding/latest/urlencoding/ crate. This will result in a URL like `https://da8gqtiy8g8jx8ni5c5g9gri0.us-east-1.aws.materialize.cloud/api/webhook/materialize/../.` for a webhook named `"materialize".".."."."`. That's ... not a totally valid URL, as it'll get normalized to `https://da8gqtiy8g8jx8ni5c5g9gri0.us-east-1.aws.materialize.cloud/api/webhook/materialize` by some HTTP libraries, but it's not entirely useless either—curl handles it just fine, for example. 

I think my preference is (1), but it is technically a backwards incompatible change so we'd need to be careful when rolling it out. @ParkMyCar, WDYT?

**Comment by benesch** [comment]
I'm going to see if @matthewarthur wants to pick this one up!

**Comment by ParkMyCar** [comment]
Thanks for including all of this detail @benesch!

My preference is also (1). IMO it's quite reasonable to reject creating an HTTP related object if the path of that object contains characters that do not interact well with URLs. We can make sure to include this special case in our docs and point users to it if they want to create a webhook source where the path contains `.` or `..`.

**Comment by matthewarthur** [comment]
Seems reasonable, I'll start thinking about how to do this.
