### ISSUE TITLE
cannot fail to create dataflows: SinceViolation(User(397)) 

### ISSUE THREAD

**Issue by nrainer-materialize** [MaterializeInc/materialize#23246]
### What version of Materialize are you using?

4f8597c1e98d8150cd10e007c07179ea53ec3ede

### What is the issue?

This log entry was observed in Nightly https://buildkite.com/materialize/nightlies/builds/5241#018bd81d-cf32-4978-9ce5-4cc59ca85535 in check "Checks upgrade across four versions":

```
 platform-checks-materialized-1      | environmentd: 2023-11-16T13:06:25.260212Z  WARN environmentd::run:environmentd::serve:bootstrap: mz_adapter::util: halting process: cannot fail to create dataflows: SinceViolation(User(397)) 
```

ci-regexp: cannot fail to create dataflows: SinceViolation

**Comment by nrainer-materialize** [comment]
@jkosh44: Is this something to worry about?

I still need to analyze what changed.

**Comment by antiguru** [comment]
Potentially related: #22940

**Comment by jkosh44** [comment]
It's not great. It happens when trying to re-create an index during bootstrapping. @teskje has been looking into this exact thing pretty extensively recently, any thoughts?

**Comment by aalexandrov** [comment]
I think that the query logs should have some extra tracing events that should illumniate about the exact steps taken by `bootstrap_index_as_of` for `u397`.

**Comment by def-** [comment]
Also seen in parallel-workload: https://buildkite.com/materialize/nightlies/builds/5248#018bd966-8023-4744-9170-ee6f67cbc666
Since it happened multiple times in CI, most likely an actual regression.

**Comment by teskje** [comment]
I have a fix for an obvious (in hindsight) issue that was introduced in #22940 and produces the above error message: https://github.com/MaterializeInc/materialize/pull/23260. What's the best way to become confident that this actually fixes the panics seen in CI?

**Comment by teskje** [comment]
> I think that the query logs should have some extra tracing events that should illumniate about the exact steps taken by bootstrap_index_as_of for u397.

These are `info!` log events that are logged during envd bootstrap. I had a hard time finding them in the nightly logs though, can someone point me to them?

**Comment by def-** [comment]
> What's the best way to become confident that this actually fixes the panics seen in CI?

Running nightly should work.

The info log events should be in services.log: https://buildkite.com/organizations/materialize/pipelines/nightlies/builds/5241/jobs/018bd81d-cf32-4978-9ce5-4cc59ca85535/artifacts/018bd83d-b51a-4bdf-a7cf-7d54221aea76 I don't know of any other location.

**Comment by teskje** [comment]
Thanks! The logs also indicate that the thing I fixed caused the CI panics:

```
INFO environmentd::run:environmentd::serve:bootstrap: mz_adapter::coord: bootstrapping index `as_of` export_ids=[u398] cluster_id=u73 as_of=[0] min_as_of=[1700139970239] max_as_of=[0] write_frontier=[1700139971905] lag=1000 max_compaction_frontier=[1700139970905]
```

Note how we select an `as_of` of `[0]` because that's the value of `max_as_of`, which is way before `min_as_of`.
