### ISSUE TITLE
feature benchmark: regression due to variable-length encoding

### ISSUE THREAD

**Issue by nrainer-materialize** [MaterializeInc/materialize#23269]
### What version of Materialize are you using?

4597b2ecb245642234ec4369d2c4e90d006a97fa

### What is the issue?

The feature benchmark failed in the last two nightly builds:
* https://buildkite.com/materialize/nightlies/builds/5248#018bd966-7f36-404d-a4df-7fc77dcc29e0
* https://buildkite.com/materialize/nightlies/builds/5262#018bdab0-7275-42fe-ab83-73026533b77a

Important to know for the analysis: The target resolution was fixed and has therefore changed (with https://github.com/MaterializeInc/materialize/pull/23235).

Both above builds had `v0.77.1` as comparison target, previous builds chose a commit (like https://buildkite.com/materialize/nightlies/builds/5241#018bd81d-cec8-4684-8fd2-bdd28639fd3c).

**Comment by philip-stoev** [comment]
```
6075ad714a6ae27d8a27cc525c5612b601b00eb4 is the first bad commit
commit 6075ad714a6ae27d8a27cc525c5612b601b00eb4
Author: umanwizard <brennan@materialize.com>
Date:   Mon Nov 13 13:53:05 2023 -0500

    Turn on variable-length row encoding unconditionally (#23155)
    
    This has been on in prod for everyone for a while, and we're happy with
    the results. Get rid of the flag.
```

To reproduce:

```
bin/ci-builder run stable bash -c "bin/mzcompose --find feature-benchmark down -v ; bin/mzcompose --find feature-benchmark run default --scenario=DifferentialJoin --other-tag=v0.77.1"
```

and you will get an output like this:

```
+++ Benchmark Report for cycle 1:
NAME                                | TYPE      |      THIS       |      OTHER      |  Regression?  | 'THIS' is:
----------------------------------------------------------------------------------------------------
DifferentialJoin                    | wallclock |           0.533 |           0.416 |    !!YES!!    | 28.1 pct   more/slower
```

**Comment by philip-stoev** [comment]
Other affected scenarios:

```
2023-11-17 00:25:40 UTC	DifferentialJoin                    | wallclock |           0.392 |           0.268 |    !!YES!!    | 46.2 pct   
2023-11-17 00:25:40 UTC	FinishOrderByLimit                  | wallclock |           0.376 |           0.263 |    !!YES!!    | 43.0 pct   
2023-11-17 00:25:40 UTC	CountDistinct                       | wallclock |           0.509 |           0.378 |    !!YES!!    | 34.8 pct 
```

maybe more.

**Comment by umanwizard** [comment]
I have verified by looking at logs that there is a bug in previous versions where we were not setting the flag properly, despite its presence in `DEFAULT_SYSTEM_PARAMETER_VALUES`. On the "other" instance when reproing this, I see log lines like:

```
cluster-s2-replica-s2: 2023-11-21T02:16:29.061971Z  INFO mz_cluster::server: Building timely container with config TimelyConfig { workers: 1, process: 0, addresses: ["/tmp/environmentd-local-az1-7ef2862e-08f9-4ecc-b0ac-222ff375a8a7-0/cluster-s2-replica-s2/compute-0"], idle_arrangement_merge_effort: 1000, variable_length_row_encoding: false }
```

I haven't been able to figure out what was causing this bug, but I think we can consider this "not a release blocker" given that it's just highlighting the difference we already knew existed between the feature being off and being on.

**Comment by teskje** [comment]
I don't think there is a bug here! The feature benchmarks are testing "this" (main) against "other" (the last release). main defaults to VLE being switched on, whereas the last release defaults to VLE being switched off. Crucially, both are using the feature flags in `DEFAULT_SYSTEM_PARAMETERS` as set on main. And since the the `enable_variable_length_row_encoding` has been removed from `DEFAULT_SYSTEM_PARAMETERS`, both versions run with their default configs. Since we expect VLE to have a performance overhead, the feature benchmark results are indeed expected and not a regression.

We should have also been seeing a feature benchmark regression when VLE was first introduced. I can't remember if that was the case. If it wasn't, that would be surprising.

**Comment by umanwizard** [comment]
> both are using the feature flags in DEFAULT_SYSTEM_PARAMETERS as set on main

Aha! This explains the issue, thanks @teskje !

**Comment by umanwizard** [comment]
I didn't realize that we were using the flags from main for both revisions, but it makes sense, and is a bit obvious in hindsight.
