### ISSUE TITLE
[Epic] Hydration Progress & Readiness

### ISSUE THREAD

**Issue by ggnall** [MaterializeInc/materialize#23288]
## Product outcome
[Spec](https://www.notion.so/materialize/Compute-Hydration-Progress-b84d6e2720aa425b94ff70eed772d0cc)

## Work items

```[tasklist]
- [ ] https://github.com/MaterializeInc/materialize/issues/22166
- [ ] https://github.com/MaterializeInc/materialize/issues/23859
```

## Decision log

* **17 November 2023.** Issue created.

**Comment by ggnall** [comment]
@RobinClowers noticed some issues in mz_hydration_statuses, see: https://github.com/MaterializeInc/console/issues/95#issuecomment-1875652755

@parkerhendo is going to think about some designs for exposing compute hydration in the Console. 

@teskje will provide an update when he is back from PTO.

**Comment by teskje** [comment]
I'm still in the process of writing a design doc. That design will specifically be about LIR operator-level frontier logging, as a means of exposing hydration progress in SQL. It will propose:

* During LIR optimization, tag each LIR node (the things reported in `EXPLAIN PHYSICAL PLAN`) with an ID.
* During dataflow rendering, render a separate region for each LIR node and associate that with the respective ID.
* During dataflow computation, track the frontiers of these regions as the frontiers of LIR nodes.
* Communicate these frontier updates using compute protocol responses to the compute controller.
* The compute controller writes these frontiers into a storage-managed collection that can be queried from SQL.

This will immediately give us a way to say "x out of N LIR nodes have been hydrated", as a rough metric of hydration progress. It also allows users to see "the LIR node with this ID seems to be a bottleneck" and then check `EXPLAIN PHYSICAL PLAN` to see what construct this node computes.

**Comment by teskje** [comment]
The design doc is live now: https://github.com/MaterializeInc/materialize/pull/24265

**Comment by ggnall** [comment]
Database side work is done 🚀 . Console implementation tracked in https://github.com/MaterializeInc/console/issues/1574
