### ISSUE TITLE
Notice when creating an index that is identical to an already existing one

### ISSUE THREAD

**Issue by ggevay** [MaterializeInc/materialize#23299]
It might happen that a user creates an index that is identical to an already existing one, i.e., on the same object and same key. This is most probably a user mistake, so let's show a notice.

When printing this on the EXPLAIN of an existing catalog object, we might want to make this dynamic, i.e., rethink whether the notice is still valid the moment when the EXPLAIN is issued. It might loose its validity after creating the object if the other, identical index is later dropped.

**Comment by aalexandrov** [comment]
What is a good reason to have two indexes on the same object that use the same keys in the same cluster (cc @benesch)?

**Comment by aalexandrov** [comment]
> But it wouldn't achieve this goal currently, because an ad hoc query might choose the new index already before it fully rehydrated, and then just block waiting on the rehydration.

Note that currently the plan of a new index most probably is going to be based on the old one:

```sql
CREATE TABLE t (
  a int,
  b int
);

-- Create an index on t(a + 7).
CREATE INDEX t_idx1 ON t(a + 7);

-- CREATE INDEX for an identical index that emits the optimizer notice.
CREATE INDEX t_idx2 ON t(a + 7);

-- Show the plan of the new index.
EXPLAIN WITH(humanized_exprs) INDEX t_idx2;
```

produces 

```text
materialize.public.t_idx2:
  ArrangeBy keys=[[(#0{a} + 7)]]
    ReadIndex on=t t_idx1=[plan root (no new arrangement)]

Used Indexes:
  - materialize.public.t_idx1 (plan root (no new arrangement), index export)
```
