### ISSUE TITLE
SQL: Fix notice error codes

### ISSUE THREAD

**Issue by jkosh44** [MaterializeInc/materialize#23313]
### What version of Materialize are you using?

v0.78.0-dev

### What is the issue?

The majority of our error codes for notices are set to `SqlState::WARNING`.

https://github.com/MaterializeInc/materialize/blob/c244ed46a11b91953523343bbdd81d31358d904e/src/adapter/src/notice.rs#L223-L264

In PostgreSQL, if an error code isn't explicitly set in an error, then the default error code depends on the error severity level:

https://github.com/postgres/postgres/blob/3650e7a3933166b40f7f9043bd91f45d3467c74d/src/backend/utils/error/elog.c#L452-L458

https://github.com/postgres/postgres/blob/3650e7a3933166b40f7f9043bd91f45d3467c74d/src/include/utils/elog.h#L25-L56

Based on that, any message with a severity of `NOTICE`, which most of our notices have, and no explicit error code, should have a default error code of `SqlState::SUCCESSFUL_COMPLETION`.

https://github.com/MaterializeInc/materialize/blob/c244ed46a11b91953523343bbdd81d31358d904e/src/adapter/src/notice.rs#L138-L183

For all of our notices that indicate the successful completion of a statement, and that there isn't an explicit error code from PostgreSQL, we should update the error code to `SqlState::SUCCESSFUL_COMPLETION`.

NOTE: To find if an error has an explicit error code in PostgreSQL, it's usually helpful to search for the error message in the PostgreSQL repository. For example:

https://github.com/postgres/postgres/blob/3650e7a3933166b40f7f9043bd91f45d3467c74d/src/backend/catalog/aclchk.c#L380-L384

**Comment by jkosh44** [comment]
Another note, some of these notices that we're setting to `SqlState::WARNING` actually do have explicit error codes in PostgreSQL that we should mimic.

**Comment by sdht0** [comment]
Hi @jkosh44!

We're scheduled to have a chat tomorrow. @rjnn additionally mentioned that I should try implementing some of the open issues.

I've opened PR #27174 that attempts to fix this one.

**Comment by jkosh44** [comment]
> Hi @jkosh44!
> 
> We're scheduled to have a chat tomorrow. @rjnn additionally mentioned that I should try implementing some of the open issues.
> 
> I've opened PR #27174 that attempts to fix this one.

Thanks so much for your contribution @sdht0, I look forward to chatting tomorrow! @maddyblue will review your PR.
