### ISSUE TITLE
CREATE MATERIALIZED SOURCE docs missing

### ISSUE THREAD

**Issue by frankmcsherry** [MaterializeInc/materialize#2335]
The `CREATE MATERIALIZED SOURCE` command creates a source that is then immediately materialized. It is missing from the docs! I think it is essentially identical to `CREATE SOURCE` but with the materialization property (much like the difference between `CREATE MATERIALIZED VIEW` and `CREATE VIEW`).

**Comment by sploiselle** [comment]
@wangandi Is the index that is created essentially the same as if you had created a materialized view using `SELECCT * FROM some_source`?

**Comment by wangandi** [comment]
Correct, the index that is created is essentially the same as if you had created a materialized view using `SELECT * FROM some_source`.

Also, just like for views, you can materialize un-materialized sources after the fact by calling `CREATE INDEX foo on some_source(<column>)

`SHOW FULL SOURCES` has a column indicating whether it has been materialized.
