### ISSUE TITLE
#23121 memory regression

### ISSUE THREAD

**Issue by antiguru** [MaterializeInc/materialize#23389]
### What version of Materialize are you using?

c44fb2f74717b0c593f723fdf5baa00b83ca5fff

### What is the issue?

The columnated merge batcher has a bug that causes it to retain memory for longer than necessary. As #23121 is already in the latest cut, we should prepare a new version with #23121 reverted.

Context: https://materializeinc.slack.com/archives/C04UK7BNVL7/p1700675989107949

**Comment by antiguru** [comment]
Fix in Differential: https://github.com/TimelyDataflow/differential-dataflow/pull/425

It's hard to do a forward-fix because the issue is in our dependency, which has evolved considerably since our cut.

**Comment by benesch** [comment]
> It's hard to do a forward-fix because the issue is in our dependency, which has evolved considerably since our cut.

We could plausibly backport https://github.com/TimelyDataflow/differential-dataflow/pull/425 to whatever version of differential we're depending on in the last release?

**Comment by antiguru** [comment]
Yes, if we're ok with branching our internal fork of differential!

**Comment by benesch** [comment]
It's fine with me, if you're up for handling the mechanics of it.
