### ISSUE TITLE
storage: subsources can be created in a different namespace than the source

### ISSUE THREAD

**Issue by morsapaes** [MaterializeInc/materialize#23557]
### What version of Materialize are you using?

v0.77

### What is the issue?

Depending on the options used when creating a PostgreSQL source, subsources might get created in a different namespace than that of the source when no other namespace is explicitly specified. AFAICT, the expected behavior only breaks when `FOR SCHEMAS` is used in combination with prefixing the source with a namespace:

```sql
CREATE SOURCE marta_test.public.mz_source
  FROM POSTGRES CONNECTION pg_connection (PUBLICATION 'mz_source')
  FOR SCHEMAS (public, not_public)
  WITH (SIZE = '3xsmall');
```

<img width="1059" alt="Screenshot 2023-11-30 at 02 37 24" src="https://github.com/MaterializeInc/materialize/assets/23521087/2bd59ac0-8cd0-4ed2-baba-a39aed801bd4">

The source gets created in `marta_test.public`, the subsources in `materialize.public` (or in whatever the active namespace is).

Related to [Terraform #389](https://github.com/MaterializeInc/terraform-provider-materialize/issues/389). cc @dehume @rjobanp

**Comment by morsapaes** [comment]
There are scenarios where it is expected that subsources are created in a different schema than the source. For example:

```sql
CREATE SOURCE marta_test.public.mz_source
  FROM POSTGRES CONNECTION materialize.public.pg_connection (PUBLICATION 'mz_source')
  FOR TABLES (public.cdc_test_2 AS materialize.public.cdc_test_2, marta.cdc_test_1)
  WITH (SIZE = '3xsmall');
```

**Comment by benesch** [comment]
cc @sploiselle @moulimukherjee @petrosagg
