### ISSUE TITLE
parallel-workload: SELECTs still gets stuck with few indexes and without peek fast path

### ISSUE THREAD

**Issue by def-** [MaterializeInc/materialize#23582]
### What version of Materialize are you using?

403bca38a7

### What is the issue?

Seen in https://buildkite.com/materialize/nightlies/builds/5426#018c2037-7a33-4a9e-83c4-784d778aa6b8 and https://buildkite.com/materialize/nightlies/builds/5426#018c2094-c6aa-4d92-9ed0-36015f3aa9f0. Still happens in about 1/4 of nightly runs. The queries end up deadlocked after running for 30 minutes. I haven't tried yet to reproduce it locally to see if this ever resolves itself, will check now: `bin/mzcompose --find parallel-workload down && bin/mzcompose --find parallel-workload run default --seed=12345 --runtime=1800 --complexity=ddl --scenario=regression`

Note that only some queries get deadlocked, others keep running fine.

**Comment by def-** [comment]
```patch
diff --git a/misc/python/materialize/parallel_workload/parallel_workload.py b/misc/python/materialize/parallel_workload/parallel_workload.py
index 71f2087030..93697f21e2 100644
--- a/misc/python/materialize/parallel_workload/parallel_workload.py
+++ b/misc/python/materialize/parallel_workload/parallel_workload.py
@@ -146,7 +146,7 @@ def run(
     for i in range(num_threads):
         weights: list[float]
         if complexity == Complexity.DDL:
-            weights = [60, 30, 30, 30, 10]
+            weights = [60, 30, 30, 30, 100]
         elif complexity == Complexity.DML:
             weights = [60, 30, 30, 30, 0]
         elif complexity == Complexity.Read:
```
This causes higher chance of parallel DDLs.
`bin/mzcompose --find parallel-workload down && bin/mzcompose --find parallel-workload run default --seed=12345 --runtime=320 --complexity=ddl --scenario=regression` seems to reproduce it well in ~6 minutes with this setting.
[parallel-workload-queries.log](https://github.com/MaterializeInc/materialize/files/13515235/parallel-workload-queries.log)
[services.log](https://github.com/MaterializeInc/materialize/files/13515237/services.log)
The services.log contains
```
parallel-workload-materialized-1     | environmentd: 2023-11-30T16:19:06.434362Z ERROR mz_adapter::coord: Coordinator is stuck on purified_statement_ready, did not respond after 60s
parallel-workload-materialized-1     | environmentd: 2023-11-30T16:19:54.287310Z  INFO mz_adapter::coord: Coordinator became unstuck
```
But even after becoming unstuck the queries never continue. Load of the system is low, nothing at 100% CPU (~15% for CRDB, ~10% for clusterd processes, 0% environmentd), so it doesn't seem to be overloaded.

**Comment by def-** [comment]
This is still commonly occurring in CI, for example in https://buildkite.com/materialize/nightlies/builds/6684#018df604-bf85-41d5-bfcb-d9011fd1d035 (`bin/mzcompose --find parallel-workload run default --runtime=1500 --seed=1709230900 --threads=4 --complexity=ddl`)
```
2024-02-29 18:54:02 UTC	worker_0 still running: SELECT *, mz_unsafe.mz_sleep(3) FROM "db-pw-1709230900-1"."s-1".table5 JOIN "db-pw-1709230900-0"."s-0".kafka_table3 ON "db-pw-1709230900-1"."s-1".table5.key4 = "db-pw-1709230900-0"."s-0".kafka_table3.value4 LIMIT 1;
2024-02-29 18:54:02 UTC	worker_2 still running: SELECT "db-pw-1709230900-1"."s-1".table5.value9, mz_unsafe.mz_sleep(2) FROM "db-pw-1709230900-1"."s-1".table5  LIMIT 1;
```
Even after 5 minutes these simple queries from table5 never finish. Source definition:
```
[worker_3] CREATE SOURCE "db-pw-1709230900-1"."s-1".postgres_source5
                    IN CLUSTER "cluster-3"
                    FROM POSTGRES CONNECTION pg5 (PUBLICATION 'postgres_source')
                    FOR TABLES (table5 AS table5)
```
All queries ran: https://gist.github.com/def-/fe0d935caac694e2298c7596a82899dc

**Comment by benesch** [comment]
For posterity: we [discussed a bit on Slack](https://materializeinc.slack.com/archives/C01CFKM1QRF/p1709245529268309) and I mentioned I think the `mz_unsafe.mz_sleep` calls might be the problem.

**Comment by def-** [comment]
This is now split into #28108, #28182, #28166 and I hope that I have all root causes with that.
