### ISSUE TITLE
Order of results depends on SELECT expressions

### ISSUE THREAD

**Issue by nrainer-materialize** [MaterializeInc/materialize#23602]
### What version of Materialize are you using?

v0.78.14 (3e192bac8)

### What is the issue?

I know that there is no guarantee regarding the order of results without `ORDER BY` clause. Therefore, I am not sure if this is considered a bug but it is still surprising and slightly confusing.

```
INSERT INTO t VALUES ('1abc2'), ('pqr3stu8vwx'), ('a1b2c3d4e5f'), ('treb7uchet');
```

`SELECT * FROM t;` produces
```
      x      
-------------
 1abc2
 treb7uchet
 a1b2c3d4e5f
 pqr3stu8vwx
```

and `SELECT regexp_match(x, '[0-9]'), * FROM t;` still produces

```
 regexp_match |      x      
--------------+-------------
 {1}          | 1abc2
 {7}          | treb7uchet
 {1}          | a1b2c3d4e5f
 {3}          | pqr3stu8vwx
```

but `SELECT regexp_match(x, '[0-9]') FROM t;` produces

```
 regexp_match 
--------------
 {1}
 {1}
 {3}
 {7}
```

and not

```
 regexp_match 
--------------
 {1}
 {7}
 {1}
 {3}
```

**Comment by teskje** [comment]
> I know that there is no guarantee regarding the order of results without ORDER BY clause. Therefore, I am not sure if this is considered a bug but it is still surprising and slightly confusing.

Yes, this works as intended. I agree it's confusing, but that's just SQL :)
