### ISSUE TITLE
dbt-materialize: force contract pre-flight check to run on valid cluster

### ISSUE THREAD

**Issue by morsapaes** [MaterializeInc/materialize#23600]
### What version of Materialize are you using?

dbt v1.7.0

### What is the issue?

From dbt v1.5.0, users can define [model contracts](https://docs.getdbt.com/docs/collaborate/govern/model-contracts) to ensure their models won't break as a result of changes upstream (_e.g._ type change, column deletion). To implement this feature, dbt dry runs the statement defined in the model ahead of object creation ([source](https://github.com/dbt-labs/dbt-core/blob/main/core/dbt/include/global_project/macros/adapters/columns.sql#L24)):

```sql
{% macro default__get_empty_subquery_sql(select_sql, select_sql_header=none) %}
    {%- if select_sql_header is not none -%}
    {{ select_sql_header }}
    {%- endif -%}
    select * from (
        {{ select_sql }}
    ) as __dbt_sbq
    where false
    limit 0
{% endmacro %}
```

Because we don't force a valid cluster on connection, these queries will run against `default`. If the `default` cluster does not exist in the environment, this will cause the adapter to fail:

```bash
 [0m21:39:29  Postgres adapter: Postgres error: unknown cluster 'default'
```

We need to route these queries to a valid cluster. For `materialized_view` and `table` models, we likely want to run them in the same cluster used for the model. `view` models are trickier, because views aren't tied to a cluster. If the view has indexes defined, we could fall back to that same cluster, but this still leaves us with the scenario where a model just creates a plain, vanilla view.

**Comment by benesch** [comment]
After our conversation today, @morsapaes, I tried a handful of things around preparing statements, all which didn't work. I think I got something workable with temporary views: https://github.com/MaterializeInc/materialize/pull/23712. Still needs tests though.
