### ISSUE TITLE
Checks + backup + rollback to previous fails

### ISSUE THREAD

**Issue by nrainer-materialize** [MaterializeInc/materialize#23608]
### Buildkite link

https://buildkite.com/materialize/nightlies/builds/5451

### Relevant log output

```source
i-0c560a9cce9d00530-1/materialize/nightlies/misc/python/materialize/checks/all_checks/upsert_wide.py:48
error: error connecting to server: failed to lookup address information: Name or service not known: failed to lookup address information: Name or service not known
```

### Additional thoughts

The reason in previous failed builds is: `4:1: error: executing query failed: connection closed` (in different checks)

This is the case in:
* https://buildkite.com/materialize/nightlies/builds/5437#018c217f-8c4b-4645-a966-7ec62c671b03
* https://buildkite.com/materialize/nightlies/builds/5426#018c2095-2d22-45b0-8aee-1913ed327a26
* https://buildkite.com/materialize/nightlies/builds/5423#018c1da2-88b7-44a6-9936-94f30c8b91fb
* https://buildkite.com/materialize/nightlies/builds/5420#018c1c58-e558-4535-9c54-18723a0e5dce

I will disable the job for now.

**Comment by philip-stoev** [comment]
@nrainer-materialize this is https://github.com/MaterializeInc/materialize/issues/18628, see services.log :

```
platform-checks-materialized-1      | kafka-u408: some element of the Sink as_of frontier is too far advanced for our output-gating timestamp: as_of Antichain { elements: [1>
```

For some reason, this was not reflected in the Buildkite annotations. I will open a separate issue about the missing annotation.
