### ISSUE TITLE
testdrive: Improve wrong result output

### ISSUE THREAD

**Issue by def-** [MaterializeInc/materialize#23660]
### Feature request

Use nice +/- diffing instead of printing out Rust vectors. As suggested by @mjibson

**Comment by mjibson** [comment]
I think I was wrong in my request, having only remembered the first half of the output:

```
avro-decode-bad-json.td:33:1: error: non-matching rows: expected:
[["4"], ["a"], ["b"], ["c"]]
got:
[["1"], ["2"], ["3"], ["4"], ["5"]]
Poor diff:
+ 1
+ 2
+ 3
+ 5
- a
- b
- c
```

So I think this can close.
