### ISSUE TITLE
Skew-resistant Reduce

### ISSUE THREAD

**Issue by ggevay** [MaterializeInc/materialize#23688]
To fight skewed shuffles, we should make the reductions that rely on consolidation do some reduction already before the shuffle. Frank's [idea](https://materializeinc.slack.com/archives/C02PPB50ZHS/p1701778148715599?thread_ts=1701774353.225669&cid=C02PPB50ZHS) is to have a bounded consolidation buffer before the shuffle, which will continually consolidate and flush when full-ish. This bounded buffer would result in less consolidation than an unbounded buffer would, but also less memory usage. And the bounded buffer seems like it will hit a nice spot in this trade-off, because
- if there is bad skew in the data, then even a bounded buffer will help a lot to deal with the skew;
- if there is no skew then it won't consolidate much, but that's ok because it also won't waste a lot of memory.

**Comment by ggevay** [comment]
@vmarcos told me that `explode_one` already does this.

**Comment by vmarcos** [comment]
A few (some experimental, some merged) PRs related to early aggregation and hashing issues vs. worker skew in consolidation for monotonic SELECTs: https://github.com/MaterializeInc/materialize/pull/19294, https://github.com/MaterializeInc/materialize/pull/19337, https://github.com/MaterializeInc/materialize/pull/19372 + https://github.com/MaterializeInc/materialize/pull/19848.
