### ISSUE TITLE
sql: Rename `mz_internal` schema to `mz_unstable`

### ISSUE THREAD

**Issue by ParkMyCar** [MaterializeInc/materialize#23693]
### Feature request

After https://github.com/MaterializeInc/materialize/pull/22889 we have two schemas which are "non-stable", `mz_unsafe` and `mz_internal`.

* `mz_unsafe` - objects which cannot be called or referenced by users
* `mz_internal` - objects or functions which can be called and referenced by users, but can possibly change, so we don't allow them in `VIEWS` or `MATERIALIZED VIEWS`.

This issue is to track the work in renaming `mz_internal` to `mz_unstable`. Nothing about the objects in `mz_internal` are actually "internal" to Materialize, they're just unstable, as such we impose limitations to how they can be used. This was discussed in [Slack](https://materializeinc.slack.com/archives/C063H5S7NKE/p1701791151710269)

**Comment by jkosh44** [comment]
Closing as a duplicate of https://github.com/MaterializeInc/materialize/issues/23692
