### ISSUE TITLE
Add statement type to the activity log.

### ISSUE THREAD

**Issue by joacoc** [MaterializeInc/materialize#23735]
### Feature request

Adding a column to the [activity log](https://materialize.com/docs/sql/system-catalog/mz_internal/#mz_activity_log) that specifies the query type/kind (`SELECT`, `CREATE`, `INSERT`, etc.) This would avoid the need to filter by the statement content.

**Comment by ggnall** [comment]
Fixed in:
https://github.com/MaterializeInc/materialize/pull/23846
https://github.com/MaterializeInc/materialize/pull/23846
