### ISSUE TITLE
Confusing error message when referencing column that would need to be in group-by

### ISSUE THREAD

**Issue by nrainer-materialize** [MaterializeInc/materialize#23748]
### What version of Materialize are you using?

v0.78.14 (3e192bac8)

### What is the issue?

```
CREATE TABLE t (x INT, y INT);

SELECT
  (SELECT t2.x FROM t t2 WHERE t1.y = t2.y)
FROM t t1
GROUP BY t1.x;
```

fails with `ERROR:  WHERE clause error: column "t1.y" does not exist`.

In contrast,

```
SELECT t1.y
FROM t t1
GROUP BY t1.x;
```

fails with the more expressive error message `ERROR:  column "t1.y" must appear in the GROUP BY clause or be used in an aggregate function`

**Comment by benesch** [comment]
Turns out this was a correctness issue! See #24328. PR incoming shortly.
