### ISSUE TITLE
Postgres consistency framework: char_length can not be reliably applied to json data

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#23796]
### What version of Materialize are you using?

 v0.80.0-dev (2a355b6a8)

### Build
https://buildkite.com/materialize/nightlies/builds/5556#018c4e8e-d601-4b9d-9d39-9f67ab7506ff

### What is the issue?

Mz will not add spaces between elements when returning a json field:

```
materialize=> select jsonb_val_4 ->> 'b' FROM  t_dfr_horiz;
 ?column?  
-----------
 ["1","2"]
```

But Postgres will:

```
postgres=# select jsonb_val_4 ->> 'b' FROM  t_pg_horiz;
  ?column?  
------------
 ["1", "2"]
```

Hence, the `char_length()` function will return a different result when applied to both values.

Original problematic query:

```
_bk;t=1702125728338+++ Test query #1338.1.2.2.2 (FAILURE)

_bk;t=1702125728338SELECT

_bk;t=1702125728338  char_length((jsonb_val_4 ->> 'b'))

_bk;t=1702125728338FROM

_bk;t=1702125728338  <source>_horiz;
```

**Comment by philip-stoev** [comment]
@nrainer-materialize maybe it makes sense to do one 12-hour run of the output consistency + postgres test in order to surface all such issues once and for all. Otherwise they show up one by one in sucessive runs of Nightly.

**Comment by nrainer-materialize** [comment]
> @nrainer-materialize maybe it makes sense to do one 12-hour run of the output consistency + postgres test in order to surface all such issues once and for all. Otherwise they show up one by one in sucessive runs of Nightly.

This should already be ignored and have an issue, let me check why it isn't caught.
