### ISSUE TITLE
storage: allow configuring automatically created topic for Kafka sinks

### ISSUE THREAD

**Issue by benesch** [MaterializeInc/materialize#23794]
## Summary

Allow users to configure the partition count, replication factor, and retention policy of the topic that Materialize automatically creates for Kafka sinks.

Today, if users wish to use something other than the broker default partition count, replication factor, or retention policy, they need to either pre-create the topic in the Kafka cluster with the desired configuration, or alter the topic after Materialize creates it to have the desired configuration.

### Design

We propose to introduce new options in the `KAFKA CONNECTION` block:

```sql
CREATE SINK ... INTO KAFKA CONNECTION k (
    TOPIC PARTITION COUNT ...,
    <other options>
)
```

The proposed options are:

* `TOPIC PARTITION COUNT`, which indicates the partition count of the created topic. Its value must be a number between 1 and `i64::MAX`. `NULL` indicates "broker default".
* `TOPIC REPLICATION FACTOR`, which indicates the replication factor of the created topic. Its value must be a number between 1 and `i64::MAX`. `NULL` indicates "broker default".
* `TOPIC RETENTION BYTES`, which indicates the size-based retention policy for the created topic. `NULL` indicates the broker default. How to represent "no size-based retention" is an open question.
* `TOPIC RETENTION INTERVAL`, which indicates the time-based retention policy for the created topic. `NULL` indicates the broker default. How to represent "no time-based retention" is an open question.

Other open questions:

  * What happens if the topic already exists when the sink is created with a configuration in Kafka that differs from the configuration specified in Materialize? Should Materialize check the current topic's configuration during purification an error?
  * As an extension to the above, what happens if the topic is altered in Kafka while the sink is running? Should Materialize periodically attempt to bring the Kafka topic's configuration in line with what's declared on the sink? Is that too weird?
  * Should it be possible to change these parameters with `ALTER SINK`?
  * How do users indicate they want to use compaction instead of time or size-based retention?
  * Should users be allowed to configure both compaction and retention? (Kafka supports this, but it rarely makes sense as a policy.)

### History

Most of these options existed in pre-platform Materialize without the `TOPIC` prefix (`PARTITION COUNT`, `REPLICATION FACTOR`, etc.). They were moved to unsafe mode in the shift to platform to minimize scope during the transition. They were then fully removed in #23792 due to the outstanding design questions.

### Prioritization

It is presently unclear how valuable these options are. On the one hand, there was enough demand in the pre-platform days of Materialize that these options were added in the first place. On the other hand, post platform, no one has been clamoring to have them reinstated.

Perhaps the workaround of creating the Kafka topic ahead of time is sufficient? There is a Kafka Terraform provider with a [`kafka_topic` resource](https://registry.terraform.io/providers/Mongey/kafka/latest/docs/resources/topic) that looks like it would pair quite well with the Materialize Kafka sink. Perhaps serious Kafka production deployments are using this approach?

## See also

* https://github.com/MaterializeInc/materialize/issues/14656
* A Slack discussion around how PARTITION COUNT ought to work: https://materializeinc.slack.com/archives/C01CFKM1QRF/p1681924452485939

cc @bkirwi @sploiselle @petrosagg

**Comment by benesch** [comment]
Some notes from a customer call today:

 * Request for configuring the compatibility policy on the schema registry subject too.
 * Only allowing the topic options to be configured at creation time is fine. They'd be fine without support for altering the options, and forcing users to create a fresh topic if they needed the topic options twiddled differently.

**Comment by rjobanp** [comment]
How do folks feel about this proposal as a next step:


CREATE SINK syntax reference (https://materialize.com/docs/sql/create-sink/kafka/):
```
CREATE SINK ... INTO KAFKA CONNECTION k (
    <option 1>,
    <option 2>
)
..
FORMAT AVRO USING CONFLUENT SCHEMA REGISTRY CONNECTION csr_connection (
    <csr option 1>,
    <csr option 2>
)
```

Newly proposed `CONNECTION` options:
```
NULL values always imply 'broker default'

TOPIC PARTITION COUNT <NULL | NonZeroPositive<i32>> 
TOPIC REPLICATION FACTOR <NULL | NonZeroPositive<i32>>
TOPIC RETENTION BYTES <NULL | i64> (negative values imply indefinite retention)
TOPIC RETENTION INTERVAL <NULL | i64> (negative values imply indefinite retention)
TOPIC RETENTION COMPACTION <ON>
PROGRESS TOPIC REPLICATION FACTOR <NULL | int>

TOPIC RETENTION COMPACTION is not allowed when either TOPIC RETENTION BYTES or TOPIC RETENTION INTERVAL are used
```


Newly proposed `CSR CONNECTION OPTIONS`:
```
SUBJECT COMPATIBILITY REQUIREMENT <BACKWARD | BACKWARD_TRANSITIVE | FORWARD | FORWARD_TRANSITIVE | FULL | FULL_TRANSITIVE | NONE>
```
option values taken from https://docs.confluent.io/platform/current/schema-registry/fundamentals/schema-evolution.html


And the open questions:


> What happens if the topic already exists when the sink is created with a configuration in Kafka that differs from the configuration specified in Materialize? Should Materialize check the current topic's configuration during purification an error?

No - since the topic can be externally managed, if it already exists we should leave it alone. It's possible that it's intended to use a different set of options than Materialize supports configuration for and was intentionally created ahead of the sink.

> As an extension to the above, what happens if the topic is altered in Kafka while the sink is running? Should Materialize periodically attempt to bring the Kafka topic's configuration in line with what's declared on the sink? Is that too weird?

No, see above.

> Should it be possible to change these parameters with ALTER SINK?

Not at this time.

> How do users indicate they want to use compaction instead of time or size-based retention?

Listed above, we would fence the TOPIC RETENTION options and throw an error if compaction was used with either of the time/size options.

> Should users be allowed to configure both compaction and retention? (Kafka supports this, but it rarely makes sense as a policy.)

Not at this time.

**Comment by benesch** [comment]
```
TOPIC PARTITION COUNT <NULL | NonZeroPositive<i32>> 
TOPIC REPLICATION FACTOR <NULL | NonZeroPositive<i32>>
```

These look good.

```
TOPIC RETENTION BYTES <NULL | i64> (negative values imply indefinite retention)
TOPIC RETENTION INTERVAL <NULL | i64> (negative values imply indefinite retention)
```

I'd like to avoid the special-ness of negative numbers if we can. IMO that's an ugliness of Java/C APIs that need to pack as much as possible into a single integer that we should strive to avoid. Can we introduce a dedicated tristate for this? `<NULL | i64 | INFINITE>`

```
TOPIC RETENTION COMPACTION <ON>
```

Kafka draws a distinction between "retention" and "compaction". (The term they use to unify both is "cleanup policy.") So I think this option should just be `TOPIC COMPACTION`:

```
TOPIC COMPACTION = {TRUE | FALSE}
```

An alternative design would be to follow the Kafka topic options more closely:

```
TOPIC CLEANUP POLICY = {OFF, COMPACT, DELETE}
```

And then it would be an error to specify `TOPIC RETENTION {BYTES|INTERVAL}` unless `TOPIC CLEANUP POLICY = DELETE`.

```
PROGRESS TOPIC REPLICATION FACTOR <NULL | int>
```

LGTM except `<NULL | NonZeroPositive<i32>>`, right?

----

```
SUBJECT COMPATIBILITY REQUIREMENT <BACKWARD | BACKWARD_TRANSITIVE | FORWARD | FORWARD_TRANSITIVE | FULL | FULL_TRANSITIVE | NONE>
```

They call this the "compatibility" or "compatibility level" in their API—should we use the same rather than "requirement"? E.g. either `COMPATIBILITY` or `COMPATIBILITY LEVEL`.

Also, I'm not sure about the use of "subject" here. It is the technically correct term for the objects stored in the CSR, but I find most people aren't aware of it.

We should also consider whether we want to make this differently configurable for the key and value subjects. I think we probably do.

Here's a bunch of alternative names for the option(s) spelled out for discussion:

```
KEY SUBJECT COMPATIBILITY REQUIREMENT
VALUE SUBJECT COMPATIBILITY REQUIREMENT

KEY SUBJECT COMPATIBILITY LEVEL
VALUE SUBJECT COMPATIBILITY LEVEL

KEY COMPATIBILITY
VALUE COMPATIBILITY

KEY COMPATIBILITY LEVEL
VALUE COMPATIBILITY LEVEL
```

I think I like the last pair best myself, but that's a weak opinion.

Re the compatibility levels with underscores (`BACKWARD_TRANSITIVE`, `FORWARD_TRANSITIVE`, `FULL_TRANSITIVE`), I'm a little torn. In some places we might go more SQL-y and split out the keywords (`BACKWARD TRANSITIVE`, `FORWARD TRANSITIVE`, and `FULL TRANSITIVE`). But also it can be nice to treat this as an opaque string so we don't have to adjust our SQL parser if a new compatibility level gets introduced in the future.

I think it's okay to keep the underscores as long as the documentation always uses quotes, to emphasize that it's an opaque string:

```
KEY COMPATIBILITY LEVEL = 'FULL_TRANSITIVE'
```

(Even though in option values, we intentionally conflate strings/idents, so if someone really wants to say `KEY COMPATIBILITY LEVEL = 'FULL_TRANSITIVE'` or `KEY COMPATIBILITY LEVEL = "FULL_TRANSITIVE"` they can.)

We should be sure to force-uppercase the compatibility level when we send it to the CSR, since otherwise if a user specifies a value as a bare ident (`FULL_TRANSITIVE`) it'll be case folded to lowercase and (probably) rejected by the CSR API.

**Comment by bkirwi** [comment]
One option we've discussed, but I don't think has made it onto this ticket, is allow users to specify the [Kafka topic config options directly](https://kafka.apache.org/documentation/#topicconfigs), a la:

```sql
CREATE SINK ... INTO KAFKA CONNECTION k (
  CREATE TOPIC CONFIGS = MAP['compression.type' => 'zstd'],
)
```

Reasons we might prefer this:
- There are a lot of topic configs! It would be nice not to have to keep coming back to this issue over time. (Like, it seems annoying to have to come up with purpose-built SQL syntax to support `segment.jitter.ms`, even though it's reasonable enough for a user to want to configure that.)
- Since MZ does not read from the topic, it doesn't especially care what the configs are. (Unlike the progress topic, where we care a lot what the configs are!)
- We can point users at the Kafka docs instead of duplicating the docs on our end.

Reasons we might not prefer it:
- Kafka's special-casing around -1 etc... kind of nice to hide this from the user.

**Comment by benesch** [comment]
It's a good alternative to consider! 

Agreed on your list of pros and cons. The thing that pushes me towards the dedicated options is that we reallllly want to ban configuration partition count and cleanup policy options for the progress topic, which would requires that we have a semantic understanding of Kafka topic options, at which point I feel like we might as well go all in on the dedicated option syntax so that end users get the ergonomic benefit.

**Comment by bkirwi** [comment]
It doesn't strike me as a pure ergonomic benefit. If I'm already familiar with Kafka options, specifying a config is more convenient than trying to reverse-engineer the config I want from the options MZ provides, or figuring out if it's even possible. (In a past life as a data engineer, I would have found this mildly annoying, expecially if MZ hadn't gotten around to adding syntax for an option I needed.) Custom syntax does seem like it'd make it easier to come up with a correct config if you're not familiar with Kafka, though!

What are you thinking re: semantic understanding? (Can we get away with denylisting the configs we want to configure ourselves, or is there something more fundamental?)

**Comment by rjobanp** [comment]
I'm actually in favor of @bkirwi 's suggestion over explicitly defined topic config parameters with our own syntax. Since replication-factor and partition-count aren't part of the topic config anyway, those would still likely need to be explicit options themselves and could be restricted for the progress topic.

**Comment by benesch** [comment]
> Since replication-factor and partition-count aren't part of the topic config anyway

Oh, right! Good point. Ok, I think I'm sold. It'd be something like this?

```
TOPIC PARTITION COUNT <NULL | NonZeroPositive<i32>> 
TOPIC REPLICATION FACTOR <NULL | NonZeroPositive<i32>>
TOPIC CONFIG <map[text => text]>
PROGRESS TOPIC REPLICATION FACTOR <NULL | NonZeroPositive<i32>>
```

**Comment by rjobanp** [comment]
Yep that proposal sounds good to me!

**Comment by benesch** [comment]
Still have to sort out what to do for the schema registry compatibility polices!

**Comment by rjobanp** [comment]
> Still have to sort out what to do for the schema registry compatibility policies!

I'm good with your suggestion to use:
```
KEY COMPATIBILITY LEVEL
VALUE COMPATIBILITY LEVEL
```
and to suggest the values should be quoted and treated as opaque-strings (`BACKWARD | BACKWARD_TRANSITIVE | FORWARD | FORWARD_TRANSITIVE | FULL | FULL_TRANSITIVE | NONE`)


What I am a little curious on is what the purpose is from the customer perspective of setting this value? If Materialize is the one publishing the schemas, what purpose does allowing the user to control this compatibility level have? We'd only change the schema on an `ALTER SINK` statement, right? And if so wouldn't we potentially break whatever compatibility contract was previously set, unless we validate the semantics at that time?

**Comment by benesch** [comment]
> I'm good with your suggestion ...

👍🏽 

> What I am a little curious on is what the purpose is from the customer perspective of setting this value? If Materialize is the one publishing the schemas, what purpose does allowing the user to control this compatibility level have? We'd only change the schema on an `ALTER SINK` statement, right? And if so wouldn't we potentially break whatever compatibility contract was previously set, unless we validate the semantics at that time?

@rjobanp and I synced on this one live. What this gives you is the guarantee that if someone runs an `ALTER SINK` command that changes the schema of the sink in a way that violates the schema registry's compatibility rules for the Kafka topic, then no data will be published using that new sink. 

In an ideal world, we'd perform a compatibility check _before_ accepting the `ALTER SINK` command: https://docs.confluent.io/platform/current/schema-registry/develop/api.html#sr-api-compatibility. In the current implementation the check happens too late: after we've committed to the `ALTER SINK` command and when we go to publish the first message using the new sink. The optimistic check won't be 100%, as a different schema might get published in the interim, but it'll catch the vast majority of cases.

Adding that optimistic concurrency check to purification of `ALTER SINK` is probably quite straightforward, @rjobanp, if you wanted to take a stab at doing that as part of this work.

**Comment by rjobanp** [comment]
Opened a PR for the schema registry compatibility options: https://github.com/MaterializeInc/materialize/pull/27641

> Adding that optimistic concurrency check to purification of ALTER SINK is probably quite straightforward, @rjobanp, if you wanted to take a stab at doing that as part of this work.

I briefly looked into adding this, but it would be a decent amount of refactoring so opted not to do it. There is no current purification step for ALTER SINK, and we generate the schemas in a fairly nested part of planning so would need to rework the create sink statement to be able to store the schemas between purification & planning (as far as I understand).
