### ISSUE TITLE
Improve handling of batched webhook events

### ISSUE THREAD

**Issue by sjwiesman** [MaterializeInc/materialize#23809]
### Feature request

Webhook providers may batch records to reduce the number of requests sent to destination systems. Batching is achieved by sending a single request with an array of records. 

When working on a batched dataset, the first step in Materialize is to unpack the array into individual records. 

```sql
SELECT 
  pg_catalog.jsonb_array_elements(body) AS data 
FROM batched_webhook_source
```

However, persist statistics collection does not understand `jsonb_array_elements` and in general we don't collect very interesting statistics on arrays. That means these persist collections are unable to leverage MFP, which is key for webhook sources which are always appended only and typically rely on temporal filters to bound the working set. 

Materialize should improve its handling of batched webhook sources to allow for proper filter pushdown. 

## Discussed solutions. 

1. Improve array statistics collection and handling of `jsonb_array_elements` so the following query is handled gracefully. 

```sql
SELECT 
  pg_catalog.jsonb_array_elements(body) AS data 
FROM batched_webhook_source
WHERE mz_now() <= try_parse_monotonic_iso8601_timestamp(data -> 'data' ->> 'timestamp') + '1 day'::timestamp
```

2. Support batching directly in the webhook source and unroll top-level arrays before writing into persist. 

Internal slack thread https://materializeinc.slack.com/archives/C068PP4FA15/p1702304101726829

**Comment by benesch** [comment]
My two cents: I vote that we do both! Supporting an `ENVELOPE BATCH` for webhook sources is a minor ergonomic win—don't need to create a view downstream to do the unnesting—irrespective of the persist stats pushdown benefit. And teaching persist stats to handle JSON arrays seems useful in more situations than just batched webhooks.

**Comment by ParkMyCar** [comment]
+1 to supporting both! FWIW supporting `ENVELOPE BATCH` should be relatively easy. In the HTTP handler the [API already takes a](https://github.com/ParkMyCar/materialize/blob/main/src/environmentd/src/http/webhook.rs#L76-L77) `Vec<Row>`, today we just pass a Vec of a single item. Most of the changes would be syntax and plumbing the option through.

One thing I'd want to double check is how providers handle validation for batch requests. I imagine it's the same as non-batch, an HMAC of the body, but it would be nice to verify.

**Comment by bkirwi** [comment]
Thinking about this more, I no longer think option 1 is even viable. Looking at the query we'd like to handle -

```sql
SELECT 
  pg_catalog.jsonb_array_elements(body) AS data 
FROM batched_webhook_source
WHERE mz_now() <= try_parse_monotonic_iso8601_timestamp(data -> 'data' ->> 'timestamp') + '1 day'::timestamp
``` 

This query is not quite valid... since the where clause can't mention the output of the `jsonb_array_elements` fn, among other things. I think the intent here is roughly:

```sql
WITH elements as (
SELECT 
  pg_catalog.jsonb_array_elements(body) AS data 
FROM batched_webhook_source
)
SELECT data from elements WHERE mz_now() <= try_parse_monotonic_iso8601_timestamp(data -> 'data' ->> 'timestamp') + '1 day'
```

Which has the explain plan:

```
Explained Query:
  Project (#1)
    Filter (mz_now() <= timestamp_to_mz_timestamp((try_parse_monotonic_iso8601_timestamp(((#1 -> "data") ->> "timestamp")) + 1 day)))
      FlatMap jsonb_array_elements(#0)
        ReadStorage materialize.public.batched_webhook_source
```

Note that the filter is not pushed all the way down to the source: there's a flatmap in the way. If the filter doesn't even make it to the source, there's no way persist can possibly push it down further!

**Comment by bkirwi** [comment]
Or put another way: I think if the Persist source was being passed an MFP for this query, the work we'd need to do to support it is pretty modest. But our compute layer is not actually pushing down the filter that far, and the changes that would be needed to push it down any further seem pretty nontrivial. (To me, based on my limited knowledge of the optimizer, anyways.)

**Comment by ParkMyCar** [comment]
Update: we chatted in [Slack](https://materializeinc.slack.com/archives/C063H5S7NKE/p1702351438262799) about the syntax for option 2, and the consensus is to use `BODY FORMAT JSON ARRAY`.

Ahhh @bkirwi good point for option 1, the second example of the CTE is what I was thinking would be possible. Yeah it definitely seems like the bulk of the work would be in compute, which (to my also limited knowledge of the optimizer) is a lot more work than option 2. Thanks for investigating though!
