### ISSUE TITLE
We can resolve `mz_timestamp` from `pg_catalog`, but it should be `mz_catalog`

### ISSUE THREAD

**Issue by ggevay** [MaterializeInc/materialize#23833]
### What version of Materialize are you using?

62203e2d597983a404c958c8beae9fdaafbd74b6

### What is the issue?

```
        catalog
            .resolve_type(&PartialItemName {
                database: None,
                schema: Some("pg_catalog".to_string()), // todo: Why is this not `mz_catalog`?
                item: "mz_timestamp".to_string(),
            })
            .expect("mz_timestamp should exist");
```
see [here](https://materializeinc.slack.com/archives/C02FWJ94HME/p1702375729277789?thread_ts=1702328168.538389&cid=C02FWJ94HME).

[Here it is in context.](https://github.com/ggevay/materialize/blob/32289ce455864008d1ae1e8db28fc1cc05e60572/src/sql/src/pure.rs#L1503-L1509) Runnable with, e.g.,
```
bin/sqllogictest -- -v test/sqllogictest/materialized_views.slt
```

**Comment by jkosh44** [comment]
This issue exists for all non-PG types. We have been mistakenly hard-coding `pg_catalog` as their schema.

https://github.com/MaterializeInc/materialize/blob/a86b5041c1d075e21bffe1119f06b6cd0d02a05e/src/adapter/src/catalog/open.rs#L1193-L1215
