### ISSUE TITLE
Don't write to mz_activity_log for certain applications

### ISSUE THREAD

**Issue by SangJunBak** [MaterializeInc/materialize#23847]
### Feature request

The Console would like the functionality to not record any queries on certain application names. This is because some queries in the Console (such as `SELECT mz_version();` for health checks) happen frequently thus degrading performance while not serving much value. The number of these health checks actually grows with the number of tabs open and the number of users in a region.

A rough analysis I did shows the number of queries in my staging environment over a month. 

<img width="500" alt="Screenshot 2023-12-12 at 3 43 04 PM" src="https://github.com/MaterializeInc/materialize/assets/29664023/62d88435-e351-4760-acee-5bfa2897f16e">

10,715/ 31,288 queries have been `select mz_version();`.

**Comment by SangJunBak** [comment]
@ggnall for visibility

**Comment by umanwizard** [comment]
I prefer not to do this (not because it's hard, but just because it makes the product more complex) unless we can show that it actually helps performance. Have we verified that filtering these out on the query side isn't sufficient

**Comment by ggnall** [comment]
We are applying filtering on the Console side for the time being: https://github.com/MaterializeInc/console/issues/842
