### ISSUE TITLE
environmentd: HTTP_HOST_NAME needs to be balancer-aware

### ISSUE THREAD

**Issue by mjibson** [MaterializeInc/materialize#23851]
When webhooks return their external address they use the `HTTP_HOST_NAME` cli flag. When the balancer is enabled though, an envd will have 2 valid public addresses. We might need a way to change between those without restarting envd. Possibly a LD variable.

**Comment by alex-hunt-materialize** [comment]
Closing as "won't do" in light of discussion at https://materializeinc.slack.com/archives/C058H9MH8P3/p1702420717446359
