### ISSUE TITLE
clusters: grpc connections between envd and cluster do not have keepalives configured

### ISSUE THREAD

**Issue by guswynn** [MaterializeInc/materialize#23869]
## Problem

Broken out from https://github.com/MaterializeInc/materialize/issues/18683

Closes https://github.com/MaterializeInc/materialize/issues/20299

pubsub connections should have keepalives (and perhaps other timeouts) configurable in launch darkly

## Solution

Add configuration to launch darkly. thread it through to the grpc client creation. pubsub is setup before regular communication happens; we either need to move that, or configure these with cli flags derived in the orchestrator from LD flags

**Comment by guswynn** [comment]
@pH14 do you know if the persist pub-sub connections configure keepalives or anything about the tcp connections?

**Comment by pH14** [comment]
Good point! I don't think we set http2 timeouts for `GrpcPubSubClient` client connections

Note that HTTP2 timeouts were wired up and rolled out for controller RPCs some months ago, but we disabled them in prod due to a bug that seemed network related after that release. We never returned to reenable the flags in  even though I'm 99% sure the bug was unrelated, and they've been running in staging for months now (https://app.launchdarkly.com/default/production/features?q=grpc&state=live)

**Comment by guswynn** [comment]
@pH14 interesting!

So it sounds like to close this issue we want:
- apply these flags (or similar ones) to persist pub sub connections
- turn them on in prod

does that sound right?

**Comment by pH14** [comment]
I think that's it! I feel pretty good about the knobs too, they just got lost in the shuffle and I haven't had the chance to fully revisit

**Comment by guswynn** [comment]
This is resolved except for persist pubsub

**Comment by benesch** [comment]
Sweet! Now that this is enabled in production, can we adjust the default that's baked into the binary to 5s and then get (finally!) get https://github.com/MaterializeInc/materialize/pull/20491 merged?

**Comment by guswynn** [comment]
@benesch will https://github.com/MaterializeInc/materialize/pull/20491 require that persist pubsub also reconnect quickly?

**Comment by guswynn** [comment]
@benesch these ARE the defaults in the binary already!

**Comment by benesch** [comment]
> @benesch these ARE the defaults in the binary already!

Oh, fantastic.

**Comment by benesch** [comment]
> @benesch will #20491 require that persist pubsub also reconnect quickly?

I'm not sure. It's not required for correctness, but not having pubsub makes a meaningful difference to performance (and also to CockroachDB load), so it'd be good to fix this too. 

> pubsub is setup before regular communication happens; we either need to move that

Moving it would be my preference!

**Comment by benesch** [comment]
@guswynn I'm going to add this one to the storage board, with me as the assignee. Seems like a good important but not at all urgent task that I could try to pick off. As will all things, feel free to beat me to this one, if you're feeling inspired.

**Comment by guswynn** [comment]
@benesch sounds good! Feel free to pick it up

**Comment by guswynn** [comment]
Oh I also want to note that in the platform v2 world, we may have additional pubsub channels between the compute controllers in envd
