### ISSUE TITLE
Legacy upgrade test "compile-proto-sources" broken

### ISSUE THREAD

**Issue by nrainer-materialize** [MaterializeInc/materialize#23863]
### What version of Materialize are you using?

1c7e0196365f24b077c8404d8cc316cd61202afd

### What is the issue?

The "Legacy upgrade test" has two "configurations":
* config1 verifies upgrades from older versions to the latest two minor versions based on tags (these were `0.79.0` and `0.78.15` on Dec 9th and today). config1 was run in nightly because it is not deterministic.
* config2 verifies upgrades from older versions to the latest two minor versions based on the release docs (the are currently `0.76.0` and `0.77.1`). config 2 is supposed to run in the tests pipeline.

`compile-proto-sources` in "Legacy upgrade test", which was running in nightly with config1 at that time, breaks with https://github.com/MaterializeInc/materialize/pull/23442 (merge commit: 1c7e0196365f24b077c8404d8cc316cd61202afd) with config2. This blocks the re-introduction of config2 in the tests pipeline, which is desired.

This can be reproduced with
```
git reset --hard 1c7e0196365f24b077c8404d8cc316cd61202afd
# from https://github.com/nrainer-materialize/materialize (see https://github.com/MaterializeInc/materialize/pull/23830/commits)
git cherry-pick e56cadf111a84d4664565e99468725810471a25c bccfdab44683cda38ea093740bdc9ea35129096e
```

(or using branch `temp/repro-upgrade-failure` in my repo)

and command
```
bin/mzcompose --find legacy-upgrade down -v && bin/mzcompose --find legacy-upgrade run default compile-proto-sources
```

**Comment by nrainer-materialize** [comment]
Assigning this to you, @jkosh44, but before you start a question to @philip-stoev: Do we have somewhere a list of all versions that are running somewhere? If so, would we be okay not fixing this if no version older than `0.77.1` is running anywhere?

**Comment by nrainer-materialize** [comment]
I think I might have misunderstood how the test works. I believe the test tries to upgrade from these two versions to the version in the source. That would mean `0.76.0` or `0.77.1` cannot be migrated to latest.

**Comment by jkosh44** [comment]
> I think I might have misunderstood how the test works. I believe the test tries to upgrade from these two versions to the version in the source. That would mean `0.76.0` or `0.77.1` cannot be migrated to latest.

Do we go one version at a time or do we just try to upgrade from 0.76.0 directly to the most recent version?

**Comment by nrainer-materialize** [comment]
> > I think I might have misunderstood how the test works. I believe the test tries to upgrade from these two versions to the version in the source. That would mean `0.76.0` or `0.77.1` cannot be migrated to latest.
> 
> Do we go one version at a time or do we just try to upgrade from 0.76.0 directly to the most recent version?

To my understanding, we upgrade directly.

**Comment by jkosh44** [comment]
> > > I think I might have misunderstood how the test works. I believe the test tries to upgrade from these two versions to the version in the source. That would mean `0.76.0` or `0.77.1` cannot be migrated to latest.
> > 
> > 
> > Do we go one version at a time or do we just try to upgrade from 0.76.0 directly to the most recent version?
> 
> To my understanding, we upgrade directly.

Ok, that will definitely fail as the current version is unable to upgrade directly from v0.76.0. Is this something that will fix itself if we wait long enough?

**Comment by nrainer-materialize** [comment]
> Ok, that will definitely fail as the current version is unable to upgrade directly from v0.76.0. Is this something that will fix itself if we wait long enough?

Yes, since we go `n` versions back from the latest version.

@philip-stoev: Ok, if we do not fix this?

**Comment by danhhz** [comment]
Fwiw, my understanding is that in production, we always require the deploy eng to upgrade through every minor version. https://materializeinc.slack.com/archives/CTESPM7FU/p1697833629126569

**Comment by nrainer-materialize** [comment]
I think we can close this one.
