### ISSUE TITLE
catalog: Update persist shard schema for catalog

### ISSUE THREAD

**Issue by jkosh44** [MaterializeInc/materialize#23871]
### Feature request

Currently, the persist schema that the persist catalog uses is that keys are binary and values are the unit struct. The implementation of this can be found here: 

https://github.com/MaterializeInc/materialize/blob/main/src/catalog/src/durable/impls/persist/state_update.rs#L545-L609

In the future we would like to be able to define views or materialized views over the catalog persist shard as a way to implement system tables. For example `mz_databases` could look something like the following psuedo-SQL:
```SQL
CREATE MATERIALIZED VIEW mz_databases AS
SELECT obj.id, obj.name, ... FROM catalog WHERE obj.type = "database"
```
The current binary schema does not allow us to do that easily. In order to better support this feature we can make the following changes to the persist schema:
- Store the key-values in a `Row`. This is required for views/materialized views to be defined over the shard.
- Update the schema to store JSON objects in the row. Materialize already supports many operations over JSON in SQL which makes defining the views much easier.
- Add a tag to each row to indicate what type of catalog data is stored in that row. This is a performance optimization to make filtering easier.

We can use the existing proto definitions, which already implement `::serde::Serialize` and `::serde::Deserialize`, to define the JSON serialization and deserialization. That approach allows us to keep most of our catalog migration snapshot infrastructure.

https://github.com/MaterializeInc/materialize/tree/main/src/catalog/protos
https://github.com/MaterializeInc/materialize/blob/cc79078379263aab92db78ec06bb95282532c8eb/src/catalog/build.rs#L186-L236

Proto3 supports JSON mapping, which we can also look into: https://protobuf.dev/programming-guides/proto3/#json.

**Drawbacks**
@ParkMyCar points out that JSON has a much less strict format to store data on the wire. For example, the fields in a JSON object are technically unordered. Also a Rust field of `field: None` can either be serialized as `field: NULL` or by omitting the field entirely. We have been bitten in the past with bugs where a retraction of a JSON value does not exactly match the addition of that same JSON value.

**Alternatives**
There probably exists multiple alternative approaches where the catalog data is stored as binary protobuf, and the translation from binary to something else is done in SQL or as a dataflow operator. One example is that we invent a SQL function that knows how to translate the binary catalog data into JSON. Then we could use that function to define materialized views over the catalog.

**Comment by danhhz** [comment]
> @ParkMyCar points out that JSON has a much less strict format to store data on the wire. For example, the fields in a JSON object are technically unordered. Also a Rust field of field: None can either be serialized as field: NULL or by omitting the field entirely. We have been bitten in the past with bugs where a retraction of a JSON value does not exactly match the addition of that same JSON value.

Ooo great point! One way to address this is to make the field a `ScalarType::String` instead of `ScalarType::Jsonb` and then store the JSON as a string (I know, I know). The system table views would then parse this json string into jsonb before extracting various things on it. We could then issue retractions based on the string, instead of the parsed json value.

**Comment by danhhz** [comment]
Nevermind the above, I'm being silly. We'd just keep track of the raw Datum and retract that

**Comment by jkosh44** [comment]
In terms of concrete steps on how to implement this, whatever type `T` we choose to represent the catalog data, I think we need to do the following:
1. Update the persist `Codec` and `Schema` implementations to use `T`. https://github.com/MaterializeInc/materialize/blob/cc79078379263aab92db78ec06bb95282532c8eb/src/catalog/src/durable/impls/persist/state_update.rs#L545-L609
2. Update the `IntoStateUpdateKindBinary` trait to something like `IntoStateUpdateKindT`. https://github.com/MaterializeInc/materialize/blob/cc79078379263aab92db78ec06bb95282532c8eb/src/catalog/src/durable/impls/persist/state_update.rs#L25-L51
3. Update the `From` and `TryFrom` implementations to serialize snapshot data as `T`. https://github.com/MaterializeInc/materialize/blob/cc79078379263aab92db78ec06bb95282532c8eb/src/catalog/src/durable/upgrade.rs#L50-L67
