### ISSUE TITLE
Type errors in joins with `using`.

### ISSUE THREAD

**Issue by frankmcsherry** [MaterializeInc/materialize#2388]
Due to recent verification of type information, `test/slt/cockroach/join.slt` has a test that panics, which is reduced down to
```
    CREATE TABLE onecolumn (x INT)
    CREATE TABLE othertype (x TEXT)
    SELECT * FROM (onecolumn AS a JOIN othertype AS b USING(x))
```
The two column types are not the same. Perhaps they could be, and I'm not myself certain what they should be converted to (or errored about). Per @benesch the only reason this hasn't been a problem before is that in the test there is no data.

cc @jamii

**Comment by benesch** [comment]
Oops, accidental close.

The SLT test expects that query to error with a message like text/int columns cannot be matched. We are discovering that fact, but via a panic, and we should instead surface it as a proper plan time error.
