### ISSUE TITLE
Upgrade checks are broken

### ISSUE THREAD

**Issue by nrainer-materialize** [MaterializeInc/materialize#23890]
### What version of Materialize are you using?

6fe8f8429a590f4b1b759c6457c5cc3b8da82a50

### What is the issue?

```
27:1: error: preparing query failed: db error: ERROR: Expected MS, found string literal "500ms": ERROR: Expected MS, found string literal "500ms"
     |
  18 | $[version>=5500] pos ... [rest of line truncated for security]
  26 |
  27 | > CREATE SOURCE multiple_partitions_source
     | 
```

https://buildkite.com/materialize/nightlies/builds/5592

I am bisecting the commit that introduced the problems.

**Comment by sploiselle** [comment]
@nrainer-materialize [This](https://buildkite.com/materialize/nightlies/builds/5592#018c684f-1348-4c0c-9793-5be22ff45977/2647-2658) looks like https://github.com/MaterializeInc/materialize/pull/23792

**Comment by nrainer-materialize** [comment]
Removing label `release-blocker`, seems to be a test issue.

**Comment by ParkMyCar** [comment]
Re-adding the `release-blocker` tag, without a fix for this we'll have a bunch of nightly issues

**Comment by nrainer-materialize** [comment]
Fixed by https://github.com/MaterializeInc/materialize/pull/23906.
