### ISSUE TITLE
Resolve open TODO of "EXPLAIN WITH (redacted)"

### ISSUE THREAD

**Issue by nrainer-materialize** [MaterializeInc/materialize#23922]
Tracking issue for TODOs that should be resolved before we close https://github.com/MaterializeInc/cloud/issues/8196.

### What version of Materialize are you using?

a78079509533382811bb9453da3f634e87d9fa19

### What is the issue?

These two TODOs in the code reference issue https://github.com/MaterializeInc/cloud/issues/8196, which was addressed and closed with https://github.com/MaterializeInc/materialize/pull/23861.

```
Issue is referenced in comment but already closed: [#8196](https://github.com/MaterializeInc/materialize/issues/8196)
src/expr/src/explain/text.rs:200: // TODO(cloud#8196): delete this

Issue is referenced in comment but already closed: [#8196](https://github.com/MaterializeInc/materialize/issues/8196)
src/repr/src/explain/mod.rs:622: pub struct CompactScalarSeq<'a, T: ScalarOps>(pub &'a [T]); // TODO(cloud#8196) remove this
```

Note that the issue reference is changed to this issue (`TODO(#23922)`) with https://github.com/MaterializeInc/materialize/pull/23919.

**Comment by aalexandrov** [comment]
This was closed by accident,the TODOs are still valid.

**Comment by aalexandrov** [comment]
@nrainer-materialize Note that I added `cloud\#` in `ci_closed_issues_detect.py` because I wasn't sure whether the `https://api.github.com/repos/{repository}/issues/{issue_id}` rest call in CI will work against MaterializeInc/cloud since it is a private repo. If you think this will be fine feel free to merge this pattern to `ISSUE_RE` so we get proper lint warning if we close the cloud issue without resolving the TODOs.

**Comment by nrainer-materialize** [comment]
I think it should be working to reference cloud issues. Alright, I will close this issue and change references back. 👍

**Comment by nrainer-materialize** [comment]
> I think it should be working to reference cloud issues. Alright, I will close this issue and change references back. 👍

No, I am apparently wrong. I will revert https://github.com/MaterializeInc/materialize/pull/23919 and file an issue to extend our issue detector.
