### ISSUE TITLE
Add option to Kafka upsert sinks to omit keys from the value

### ISSUE THREAD

**Issue by sthm** [MaterializeInc/materialize#23925]
### Feature request

I'm regularly using Materialize to think through problems and try different solutions. For convenience, I'm using Materialize to produce sample data into Kafka and then read it back into Materialize. This works well, except for one annoying technical detail.

```
CREATE SOURCE tpch FROM LOAD GENERATOR TPCH (SCALE FACTOR = 1);

CREATE SINK sink_lineitem FROM lineitem
INTO KAFKA ...
KEY ("l_orderkey", "l_linenumber")
FORMAT AVRO 
ENVELOPE UPSERT;
```

By default, the key is included in the Kafka partition key _and_ the value of the message. Therefore, creating a source based on the generated Avro schema fails:

```
CREATE SOURCE source_lineitem
FROM KAFKA ...
ENVELOPE UPSERT;
ERROR:  column "l_orderkey" specified more than once
```
It's not the end of the world to fix the schema manually, but it's annoying for my purposes and it makes using terraform to set up the infrastructure more cumbersome. After a discussion with @petrosagg, I'd like to propose adding a new configuration option to the sink that effectively omits the keys from the value of a message. Maybe something like
```
KEY ("l_orderkey", "l_linenumber") OMIT FROM VALUE
```

And apparently I'm not the only one hitting this problem: https://github.com/MaterializeInc/materialize/issues/22815.

**Comment by petrosagg** [comment]
Writing down some of the other ideas we talked about: 

1. The syntax for sinks could be something even less configurable (i.e `OMIT KEY FROM VALUE`)
2. The upsert sources could be taught about a new option (strawman syntax `EXTRACT KEY FROM VALUE`) that will make the ingestion assert that the key we see in each kafka record exists as-is in the decoded value and then we can skip prepending the key to the value.

**Comment by benesch** [comment]
The `OMIT COLUMNS` option proposed in https://github.com/MaterializeInc/materialize/issues/27758 would also be a solve here, AFAICT.

**Comment by sthm** [comment]
Yeah, should we close this issue in favor of https://github.com/MaterializeInc/materialize/issues/27758?

**Comment by benesch** [comment]
> Yeah, should we close this issue in favor of #27758?

Certainly works for me!
