### ISSUE TITLE
storage: sources + sinks lose definite error status on restart

### ISSUE THREAD

**Issue by sploiselle** [MaterializeInc/materialize#23950]
### What version of Materialize are you using?

main

### What is the issue?

If a source or a sink encounters a definite error, that error will be overwritten in `mz_internal.mz_{source,sink}_statuses` on reboot.

**Comment by philip-stoev** [comment]
@sploiselle how is this not being caught by existing tests? We have a platform check that introduces a bunch of errors and then restarts, maybe more error situations are needed there?
