### ISSUE TITLE
Adding ChBench support for multiple partitions

### ISSUE THREAD

**Issue by nacrooks** [MaterializeInc/materialize#2398]
Debezium supports writing to topics with multiple partitions, but by "default" creates topics with a single partition, and with replication factor 1. For stress testing, it would be useful to have the ability to configure Chbench to run with more than one partition/replica

**Comment by nacrooks** [comment]
The option in Debezium is num_partitions. I tried setting it in various places in the docker-compose file but it seemed to have no effect.

**Comment by sploiselle** [comment]
efforts to improve chbench are not on the roadmap in the foreseeable future; closing isues around it
