### ISSUE TITLE
persist-txn testing

### ISSUE THREAD

**Issue by def-** [MaterializeInc/materialize#24027]
### Feature request

- [x] platform-checks: Start with persist-txn turned off, switch to eager mode (@philip-stoev)
- [x] zippy: Switch between persist-txn turned off and eager mode (@philip-stoev)
- [x] parallel-workload: Switch between persist-txn turned off and eager mode (@def-)
- [x] Add network jitter to zippy using toxiproxy for S3/CRDB connections (@def-)
- [x] Add network jitter to parallel-workload using toxiproxy for S3/CRDB connections (@def-)
- [x] Two Mzs in parallel: Start with old version with persist-txn off, start up new one with eager, have them work in parallel for a short while, then the old one should shut down. The old version shouldn't overwrite anything for the new one, this could potentially be implemented using a platform-check ZeroDowntimeUpgradeScenario instead of a new test. See "How to test it?" in https://www.notion.so/materialize/persist-txn-46c2be29d28e40289803691e8f66d2f3 (@philip-stoev )
- [x] Run all the workloads above with both "lazy" and "eager" @philip-stoev 
  - https://github.com/MaterializeInc/materialize/pull/24158

@philip-stoev Did I get the items and assignments right? If so, I'd share this with the persist-txn devs as our plan.

**Comment by philip-stoev** [comment]
@def- yes the assignments are correct .

**Comment by philip-stoev** [comment]
@def- I think I have an idea on how to implement the " Two Mzs in parallel: ". I did it in Platform Checks already, but it would not have the required concurrency to hit any tiny race condition holes there may be. So I will try to implement a dedicated mzcompose workflow for this if you do not mind.

**Comment by def-** [comment]
Sure, go ahead!
