### ISSUE TITLE
CREATE SINK fails to create schema on time (again)?

### ISSUE THREAD

**Issue by def-** [MaterializeInc/materialize#24043]
### What version of Materialize are you using?

1b5e55b762

### What is the issue?

In Zippy w/ alter connection: https://buildkite.com/materialize/nightlies/builds/5665#018c8358-874a-4fc8-903a-3b959e176b7d
```
--- #591: CreateSink
> CREATE CONNECTION IF NOT EXISTS sink_6_kafka_conn TO KAFKA (BROKER 'kafka:9092', PROGRESS TOPIC 'zippy-sink_6-1', SECURITY PROTOCOL PLAINTEXT);
rows match; continuing at ts 1703011856.6272757
> CREATE CONNECTION IF NOT EXISTS sink_6_csr_conn TO CONFLUENT SCHEMA REGISTRY (URL 'http://schema-registry:8081/');
rows match; continuing at ts 1703011856.8306386
> CREATE SINK sink_6
IN CLUSTER default
FROM view_1
INTO KAFKA CONNECTION sink_6_kafka_conn (TOPIC 'sink-sink_6')
FORMAT AVRO USING CONFLUENT SCHEMA REGISTRY CONNECTION sink_6_csr_conn
ENVELOPE DEBEZIUM;
rows match; continuing at ts 1703011857.1769085
Verifying Kafka topic sink-sink_6
waiting to create Kafka topic...
^^^ +++
12:1: error: topic not found
     |
   3 | > CREATE CONNECTION  ... [rest of line truncated for security]
  11 | 
  12 | $ kafka-verify-topic sink=materialize.public.sink_6 await-value-schema=true
     | ^
```
We previously had similar flakes in https://github.com/MaterializeInc/materialize/issues/23359 which turned out to be a pretty bad regression. Thus I'm considering this important to be looked at, so marking as release blocker. Unfortunately it seems quite flaky, as usual, so can't be sure if this is a recent regression.

There is a panic which could have caused this problem:
```
zippy-materialized-1      | thread 'timely:work-0' panicked at /var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-098f4a0cb6da89b87-1/materialize/tests/src/persist-client/src/operators/shard_source.rs:316:21:
zippy-materialized-1      | u89: s276fce31-2ee9-463d-af10-69b028259f0a cannot serve requested as_of Antichain { elements: [1703011845000] }: Since(Antichain { elements: [1703011853000] })
```
This seems related to https://github.com/MaterializeInc/materialize/issues/19097 CC @aljoscha But I'm not sure if the panic ever caused the missing sink before.

ci-regexp: (topic|subject) not found

**Comment by sploiselle** [comment]
I will not be able to dedicate time to unblock this v0.81.0

**Comment by sploiselle** [comment]
Oh, I misunderstood the schedule––I will not have time to fix this issue this week, but can handle it next week. I don't know if that impacts the release schedule or not.

**Comment by def-** [comment]
Seen again: https://buildkite.com/materialize/nightlies/builds/5711#018c9415-0dc2-45ff-b8be-d6b9cf4a58ce
```
Verifying Kafka topic sink-sink_6
waiting to create Kafka topic...
^^^ +++
12:1: error: topic not found
     |
   3 | > CREATE CONNECTION  ... [rest of line truncated for security]
  11 | 
  12 | $ kafka-verify-topic sink=materialize.public.sink_6 await-value-schema=true
     | ^
+++ !!! Error Report
```
@petrosagg Could this be fallout from https://github.com/MaterializeInc/materialize/pull/23790 ?

**Comment by petrosagg** [comment]
It's not, no. What I see in the logs is this panic which means that we attempted to read `u89` at a time that was not available:

```
zippy-materialized-1      | thread 'timely:work-0' panicked at /var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-016abefee7eb08643-1/materialize/tests/src/persist-client/src/operators/shard_source.rs:316:21:
zippy-materialized-1      | u89: sde214a6b-81fc-4068-9ee8-746011c530d3 cannot serve requested as_of Antichain { elements: [1703292278000] }: Since(Antichain { elements: [1703292287000] })
zippy-materialized-1      | stack backtrace:
```

The item `u89` corresponds to `source_9` which according to the logs is created once and then left alone (i.e no views or sinks are built onto it). The only thing that happens 3 times in the test is an `ALTER CONNECTION source_9_kafka_conn ..` which triggers a re-execution of the ingestion dataflow with the updated connection details. The ingestion dataflow normally writes to`u89` (since it's ingesting the source) but because this is an upsert source we need to rehydrate the upsert state and the dataflow is set up to read a snapshot on initialization.

This similar to the issue that was uncovered here https://github.com/MaterializeInc/materialize/pull/23790#issuecomment-1856164785 where we're sloppy with dataflow executions and things only work out if the timings are right.

Fixing this is part of the storage stability effort and is at the top of my list to work on next. This is the corresponding issue https://github.com/MaterializeInc/materialize/issues/23508

**Comment by petrosagg** [comment]
Separately from that, @def- do you know why buildkite didn't detect the panic in the logs?

**Comment by def-** [comment]
![Screenshot 2023-12-24 at 11 37 30](https://github.com/MaterializeInc/materialize/assets/2335377/3b9c65c6-0b61-4c5d-9c64-3bea1e6c3f6d)
It did, but we are hiding it because it's a known issue (https://github.com/MaterializeInc/materialize/issues/19097). But so far for 19097 we didn't see the schema missing previously I believe.

**Comment by petrosagg** [comment]
> But so far for 19097 we didn't see the schema missing previously I believe.

In this case the panic from the source panicked the whole cluster and so the sink dataflow didn't run at all which is why the topic wasn't created. It was an unlucky timing

**Comment by moulimukherjee** [comment]
Removing `release-blocker` tag, from the comments this will be fixed in https://github.com/MaterializeInc/materialize/issues/23508

**Comment by philip-stoev** [comment]
And again https://buildkite.com/materialize/tests/builds/72165#018cce83-9e92-4a93-8772-d75a868edbf5

**Comment by petrosagg** [comment]
in build 72165 it looks like the k8s controller was not able to create the requested pods for clusterd? The logs are filled with:

```
[pod/environmentd-0/environmentd] 2024-01-03T09:02:15.997620Z  INFO mz_storage_controller::rehydration: error connecting to ClusterReplicaLocation { ctl_addrs: ["cluster-u6-replica-u6-0.cluster-u6-replica-u6.default.svc.cluster.local:2100"], dataflow_addrs: ["cluster-u6-replica-u6-0.cluster-u6-replica-u6.default.svc.cluster.local:2103"], workers: 1 } for storage, retrying in 1s: transport error
```

And there is never a healthy cluster on which the sink is scheduled, which is why the topic does not get created.

**Comment by philip-stoev** [comment]
And again https://buildkite.com/materialize/nightlies/builds/6061#018d1f20-eff9-4acc-b1d2-1a8957cb7906 . The Kubectl get all log artifact indicates that all K8s pods are healthy. No scheduling errors could be found anywhere.

**Comment by petrosagg** [comment]
The recorded logs seem to be truncated or at least missing things. Whenever an object (e.g sink) is created environmentd will print this log:
```
[pod/environmentd-0/environmentd] 2024-01-19T01:53:23.901661Z  INFO mz_adapter::catalog::state: create sink materialize.public.mz_sinks_debezium (u1315)
```
The failing test executes `> CREATE SINK upsert_input_sink2 ...` successfully but if you search for `upsert_input_sink2` in `kubectl-get-logs.log` there is no hit.

**Comment by ggevay** [comment]
Seems to be still happening [here](https://buildkite.com/materialize/nightlies/builds/6560#018dcd7a-dfe0-4cfb-9f90-93728976815e). Failed in the same way throughout 3 tries.

**Comment by def-** [comment]
That is a different issue: https://github.com/MaterializeInc/materialize/issues/19999

**Comment by sploiselle** [comment]
Sinks have had a number of refactors and misc. bug fixes land in recent months. @MaterializeInc/testing do you all know if this is still a regular occurrence?

**Comment by nrainer-materialize** [comment]
I haven't found any recent builds failing due to `error: topic not found` and we also don't have any recent failing instances of "Zippy w/ alter connection".

However, the log entry "cannot serve requested as_of Antichain" still occurs frequently (for example, in https://buildkite.com/materialize/nightlies/builds/7144#annotation-018e89fa-adde-47cd-add5-077cd11d9e93-info).
