### ISSUE TITLE
ci flake: 	kafka-exactly-once-sink.td:304:1: error: record 0 did not match

### ISSUE THREAD

**Issue by def-** [MaterializeInc/materialize#24063]
### What version of Materialize are you using?

7998a64496ad

### What is the issue?

Happened in my PR, but seems totally unrelated: https://buildkite.com/materialize/tests/builds/71705#018c8b6d-6960-4e5b-bdce-566c1f4fb175

```
kafka-exactly-once-sink.td:304:1: error: record 0 did not match
expected:
Record {
    headers: [],
    key: None,
    value: Some(
        Object {
            "frontier": Array [
                Number(2),
            ],
        },
    ),
}

actual:
Record {
    headers: [],
    key: None,
    value: Some(
        Object {
            "frontier": Array [
                Number(1),
            ],
        },
    ),
}
     |
  11 | $ postgres-execute c ... [rest of line truncated for security]
 166 |     URL '${testdrive ... [rest of line truncated for security]
 303 | 
 304 | $ kafka-verify-data format=json key=false topic=testdrive-progress-fixed-${testdrive.seed}
     | ^
```

**Comment by def-** [comment]
Also just seen on main: https://buildkite.com/materialize/nightlies/builds/5682#018c89c8-07a8-4ba0-bcd6-1a6f24ef3214
Since this started happening twice today, I'm assuming this is a regression. Marking as release blocker, will try to figure out what change it came from.

**Comment by benesch** [comment]
Almost surely this is https://github.com/MaterializeInc/materialize/pull/23790. cc @petrosagg

**Comment by def-** [comment]
I just came to the same conclusion, based on the changes between the last good nightly run and the first bad: https://github.com/MaterializeInc/materialize/compare/0a2678e8bb...02f6a7e4d8

**Comment by petrosagg** [comment]
This is a broken test that assumes that frontier will jump directly to `{2}` but it's ok for the frontier to go through `{1}` first. The next message in the kafka progress topic would have been the frontier the test is looking for. I'll try to modify the test to be robust to this

**Comment by petrosagg** [comment]
I'll read it back with a sink and verify its contents in SQL so that I select the latest progress message, PR incoming
