### ISSUE TITLE
rename `statement_kind` column in `mz_internal.mz_activity_log` to `statement_type`

### ISSUE THREAD

**Issue by morsapaes** [MaterializeInc/materialize#24100]
### Feature request

For consistency with other column names in the system catalog, we should consider renaming `statement_kind` to `statement_type` in `mz_internal.mz_activity_log` (#23846). There was a similar discussion in [#23360](https://github.com/MaterializeInc/materialize/pull/23360#discussion_r1407292583), where `kind` was also initially used for consistency with the name of the Rust type; we should strive to be consistent with the user-facing naming conventions, instead.

**cc @umanwizard**

**Comment by umanwizard** [comment]
I used `kind` intentionally, not just because of the Rust type. The reason I didn't want to use "type" is because it can get confused with the "type system" sense of the word. E.g. someone could think "statement type" means the result type of the statement (`text`, `bigint`, etc.)

**Comment by umanwizard** [comment]
I did an informal poll and absolutely everyone disagreed with me and thought it should be `type` (though nobody cared very strongly, including me). I guess I'll take the L on this bikeshed and rename it to `type` 😅

**Comment by benesch** [comment]
Also "kind" has its own type theory problems! https://en.wikipedia.org/wiki/Kind_(type_theory)
