### ISSUE TITLE
Replace `with c.override` with `c.override`

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#24116]
### Feature request

Otherwise any framework that restarts Mz outside/after the `with` block will get Mz with default settings post-restart.

**Comment by def-** [comment]
This might be annoying to fix, has to touch many places. I've already cleaned up some code paths around this.

Larger change would be: https://github.com/MaterializeInc/materialize/pull/24319

We can revisit if we have problems with this again.
