### ISSUE TITLE
Earlier error if argument for schema registry in CREATE {SOURCE, SINK} is not a valid url

### ISSUE THREAD

**Issue by ruchirK** [MaterializeInc/materialize#2412]
If I pass in `localhost:8081` as the schema registry "url" -- the source or sink gets created, but it fails to read / write in any data and the dataflow itself errors out with something like

```
Mar 24 21:35:26.954 ERROR dataflow::sink::kafka: unable to publish schema to registry in kafka sink: transport: builder error for url (localhost:%2Fsubjects/monthly1585100126-value/versions): URL scheme is not allowed
```

I think we should throw an error earlier given that having a valid schema registry url is (currently) a strict requirement, and the only way to revert from this state at the moment is to drop the source / sink and try again? 

Edit: "valid url" can be a lot of things for a lot of people -- strawman proposal -- assert that the scheme is http / https using https://docs.rs/reqwest/0.8.6/reqwest/struct.Url.html#method.scheme and error otherwise?

**Comment by ruchirK** [comment]
Also worth thinking about: should the docs make a louder distinction between the argument for broker (host name) vs schema registry (url)?

**Comment by rjnn** [comment]
@benesch do you have a diagnosis on whether this is doable once runtime errors merges? I believe we need some kind of runtime error support to do this, correct? Or am I mistaken?

**Comment by benesch** [comment]
This is actually a plan-time error, not a runtime error. Just needs someone to work on it.
