### ISSUE TITLE
ERROR: unknown catalog item 'sink_4_view'

### ISSUE THREAD

**Issue by def-** [MaterializeInc/materialize#24133]
### What version of Materialize are you using?

2831ad5e72

### What is the issue?

Seen in my PR https://github.com/MaterializeInc/materialize/pull/24111 and probably related to it: https://buildkite.com/materialize/nightlies/builds/5737#018cb02e-a116-4c46-a2f0-5a846ece239c
```
--- #10022: ValidateView
> SELECT count_all, count_distinct, min_value, max_value FROM sink_4_view  /* expecting count_all = 1017 count_distinct = 1017 min_value = 60760 max_value = 61776 */ ;
rows didn't match; sleeping to see if dataflow catches up 50ms 75ms 113ms 169ms 253ms 380ms 570ms 854ms 1s 2s 3s 4s 6s 10s 15s 22s 33s 49s 74s 111s 166s 101s
^^^ +++
2:1: error: preparing query failed: db error: ERROR: unknown catalog item 'sink_4_view': ERROR: unknown catalog item 'sink_4_view'
     |
   1 | 
   2 | > SELECT count_all, count_distinct, min_value, max_value FROM sink_4_view  /* expecting count_all = 1017 count_distinct = 1017 min_value = 60760 max_value = 61776 */ ;
     | ^
```
What the PR does is introduce network jitter for the CRDB and S3 connections. The sink seems to never get created in that case.

sink_4_view never seems to have gotten created, its `CREATE MATERIALIZED VIEW` doesn't exist in run.log. So I'm confused why zippy thinks it should exist at all. @philip-stoev Maybe you have an idea? Have you seen something like this before?

**Comment by philip-stoev** [comment]
Thanks, will look at this as soon as I can.

**Comment by def-** [comment]
Not seen recently, closing.
