### ISSUE TITLE
Support to_jsonb(sql record)

### ISSUE THREAD

**Issue by JLDLaughlin** [MaterializeInc/materialize#2414]
Right now, this extension of `json_agg` is blocked until this ticket is completed: https://github.com/MaterializeInc/materialize/issues/1514.

(Previous json_agg ticket here: https://github.com/MaterializeInc/materialize/issues/2400)

**Comment by jamii** [comment]
I don't think json_agg needs to do anything special here - it's the implicit to_jsonb that needs to convert things.

**Comment by JLDLaughlin** [comment]
Agreed!

**Comment by rjnn** [comment]
Tagging this as 0.3 so that it is done as a followup once #1514 is done without being dropped.
