### ISSUE TITLE
Allow specifying order of aggregates

### ISSUE THREAD

**Issue by jamii** [MaterializeInc/materialize#2415]
In postgres:

```
jamie=# select jsonb_agg(x) from foo;
 jsonb_agg 
-----------
 [1, 2, 3]
(1 row)

jamie=# select jsonb_agg(x order by x desc) from foo;
 jsonb_agg 
-----------
 [3, 2, 1]
(1 row)
```

I'm not actually clear what determines our current default ordering - it doesn't seem to be Row order:

```
jamie=> create table foo(x int);
CREATE TABLE
jamie=> insert into foo values (1), (2), (3);
INSERT 0 3
jamie=> select jsonb_agg(x) from foo;
   jsonb_agg   
---------------
 [2.0,3.0,1.0]
(1 row)
```

**Comment by frankmcsherry** [comment]
I think it should be `Row` order. I'm sure it isn't, for some reason, but in `Reduce` we put together each `(key, val): (Row, Row)` pair which are grouped by the former and within each group ordered by the latter.

It should be some deterministic order, in any case, as otherwise we might expect a lot of result thrashing.

**Comment by rjnn** [comment]
This seems like it should actually be higher priority than we currently are taking it - as Frank mentioned, `jsonb` values are an antipattern for incremental view maintenance - and nondeterministic ordering is particularly dangerous. I think we should enforce Row ordering here. Thoughts @frankmcsherry ?

**Comment by frankmcsherry** [comment]
Probably good to look in to. My guess is that we are doing something sane, and it is the explanation that is missing. The code in `reduce.rs` should just be following this case:
```rust
        partial.reduce_abelian::<_, OrdValSpine<_, _, _, _>>("ReduceInaccumulable", {
            move |key, source, target| {
                // We respect the multiplicity here (unlike in hierarchical aggregation)
                // because we don't know that the aggregation method is not sensitive
                // to the number of records.
                let iter = source.iter().flat_map(|(v, w)| {
                    std::iter::repeat(v.iter().next().unwrap()).take(*w as usize)
                });
                let mut packer = RowPacker::new();
                if prepend_key {
                    packer.extend(key.iter());
                }
                packer.push(func.eval(iter, &RowArena::new()));
                target.push((packer.finish(), 1));
            }
        })
```

**Comment by frankmcsherry** [comment]
I'm playing around in this code at the moment, so I'll try it out and see if I can present a better explanation.

**Comment by rjnn** [comment]
> My guess is that we are doing something sane, and it is the explanation that is missing.
Smells like tech debt to me, tagging as 0.4 as a result to ensure it gets done at least by then.

**Comment by frankmcsherry** [comment]
The results are in row order, which is first by length of the data and then by the binary representation.
```
SOURCE: [(Row{[Float64(OrderedFloat(2.0))]}, 1), (Row{[Float64(OrderedFloat(3.0))]}, 1), (Row{[Float64(OrderedFloat(1.0))]}, 1)]
bytes: [6, 0, 0, 0, 0, 0, 0, 0, 64]
bytes: [6, 0, 0, 0, 0, 0, 0, 8, 64]
bytes: [6, 0, 0, 0, 0, 0, 0, 240, 63]
```
I have no specific information about why these are the binary representations of 2.0, 3.0, and 1.0.

**Comment by frankmcsherry** [comment]
Though, here is a different worry (totally off topic for the issue)
```
materialize=> select jsonb_agg(x) from foo;
   jsonb_agg   
---------------
 [2.0,3.0,1.0]
(1 row)

Time: 1604.917 ms (00:01.605)
materialize=> 
```
That is a debug build. The release build is faster, but still not impressive
```
materialize=> select jsonb_agg(x) from foo;
   jsonb_agg   
---------------
 [2.0,3.0,1.0]
(1 row)

Time: 145.586 ms
materialize=> 
```

**Comment by jamii** [comment]
> I have no specific information about why these are the binary representations of 2.0, 3.0, and 1.0.

Oh, duh, because 1.0 has a different mantissa. When I wrote the original comment I actually had a sudden worry that I was being dumb about float representations, then thought about it and decided I wasn't. 

I was :D

**Comment by jamii** [comment]
(I was thinking in base 10)

**Comment by frankmcsherry** [comment]
Sanity check then, the issue still stands as we have order-sensitive aggregations and no support for 
```
materialize=> select jsonb_agg(x order by x desc) from foo;
ERROR:  Parse error:
select jsonb_agg(x order by x desc) from foo;
                   ^^^^^
Expected ), found: order
Time: 0.220 ms
materialize=> 
```

**Comment by sploiselle** [comment]
From a Slack convo with Frank:

> 1. it shouldn't be `ORDER BY` at the `SELECT` level, 2. it could be order by within the aggregation (what postgres does), and 3. it might not be that hard if we can jam the ordering requirement into the aggregate definition.
