### ISSUE TITLE
thread 'coordinator' panicked at src/adapter/src/coord.rs:2123:13: error bootstrapping index `as_of`: `min_as_of` [1704028491000] greater than `max_as_of` [0] (import_ids=[u23], export_ids=[u210], dependent_matviews={User(870)})

### ISSUE THREAD

**Issue by def-** [MaterializeInc/materialize#24168]
### What version of Materialize are you using?

e7b53c104b

### What is the issue?

Seen in parallel workload with Mz kills: https://buildkite.com/materialize/nightlies/builds/5781#018cbfda-f013-453f-8bdb-90774db9a0e9
```
thread 'coordinator' panicked at src/adapter/src/coord.rs:2123:13:
error bootstrapping index `as_of`: `min_as_of` [1704028491000] greater than `max_as_of` [0] (import_ids=[u23], export_ids=[u210], dependent_matviews={User(870)})
stack backtrace:
   0: rust_begin_unwind
             at ./rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:597:5
   1: core::panicking::panic_fmt
             at ./rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/panicking.rs:72:14
   2: <mz_adapter::coord::Coordinator>::bootstrap_index_as_of
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-07c7d627b4e3399ae-1/materialize/tests/src/adapter/src/coord.rs:2123:13
   3: <mz_adapter::coord::Coordinator>::bootstrap::{closure#0}::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-07c7d627b4e3399ae-1/materialize/tests/src/adapter/src/coord.rs:1510:37
   4: <tracing::instrument::Instrumented<<mz_adapter::coord::Coordinator>::bootstrap::{closure#0}::{closure#0}> as core::future::future::Future>::poll
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.37/src/instrument.rs:272:9
   5: <mz_adapter::coord::Coordinator>::bootstrap::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-07c7d627b4e3399ae-1/materialize/tests/src/adapter/src/coord.rs:1275:5
   6: <tracing::instrument::Instrumented<<mz_adapter::coord::Coordinator>::bootstrap::{closure#0}> as core::future::future::Future>::poll
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.37/src/instrument.rs:272:9
   7: mz_adapter::coord::serve::{closure#0}::{closure#2}::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-07c7d627b4e3399ae-1/materialize/tests/src/adapter/src/coord.rs:2752:26
   8: <tracing::instrument::Instrumented<mz_adapter::coord::serve::{closure#0}::{closure#2}::{closure#0}> as core::future::future::Future>::poll
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.37/src/instrument.rs:272:9
   9: <tokio::runtime::park::CachedParkThread>::block_on::<tracing::instrument::Instrumented<mz_adapter::coord::serve::{closure#0}::{closure#2}::{closure#0}>>::{closure#0}
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/park.rs:282:63
  10: tokio::runtime::coop::with_budget::<core::task::poll::Poll<core::result::Result<(), mz_adapter::error::AdapterError>>, <tokio::runtime::park::CachedParkThread>::block_on<tracing::instrument::Instrumented<mz_adapter::coord::serve::{closure#0}::{closure#2}::{closure#0}>>::{closure#0}>
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/coop.rs:107:5
  11: tokio::runtime::coop::budget::<core::task::poll::Poll<core::result::Result<(), mz_adapter::error::AdapterError>>, <tokio::runtime::park::CachedParkThread>::block_on<tracing::instrument::Instrumented<mz_adapter::coord::serve::{closure#0}::{closure#2}::{closure#0}>>::{closure#0}>
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/coop.rs:73:5
  12: <tokio::runtime::park::CachedParkThread>::block_on::<tracing::instrument::Instrumented<mz_adapter::coord::serve::{closure#0}::{closure#2}::{closure#0}>>
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/park.rs:282:31
  13: <tokio::runtime::context::blocking::BlockingRegionGuard>::block_on::<tracing::instrument::Instrumented<mz_adapter::coord::serve::{closure#0}::{closure#2}::{closure#0}>>
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/context/blocking.rs:66:9
  14: <tokio::runtime::handle::Handle>::block_on::<mz_adapter::coord::serve::{closure#0}::{closure#2}::{closure#0}>::{closure#0}
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/handle.rs:310:13
  15: tokio::runtime::context::runtime::enter_runtime::<<tokio::runtime::handle::Handle>::block_on<mz_adapter::coord::serve::{closure#0}::{closure#2}::{closure#0}>::{closure#0}, core::result::Result<(), mz_adapter::error::AdapterError>>
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/context/runtime.rs:65:16
  16: <tokio::runtime::handle::Handle>::block_on::<mz_adapter::coord::serve::{closure#0}::{closure#2}::{closure#0}>
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/handle.rs:309:9
  17: mz_adapter::coord::serve::{closure#0}::{closure#2}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-07c7d627b4e3399ae-1/materialize/tests/src/adapter/src/coord.rs:2748:33
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
The assertion seems to come from https://github.com/MaterializeInc/materialize/blame/45f2af9e90fdd941e3174357f54054466e4102da/src/adapter/src/coord.rs#L2123 and according to the comment this is a correctness issue.

This was previously touched in https://github.com/MaterializeInc/materialize/pull/23606 and https://github.com/MaterializeInc/materialize/pull/23564

I haven't seen this before, so probably not easy to reproduce. Command should be `while true; do bin/mzcompose --find parallel-workload down && bin/mzcompose --find parallel-workload run default --seed=1704028085 --threads=32 --runtime=1500 --complexity=ddl --scenario=kill || break; done`

ci-regexp: error bootstrapping index `as_of`

**Comment by def-** [comment]
Took a few hours but I was able to reproduce it during the night with the above command.

**Comment by teskje** [comment]
Can you provide envd logs up until the crash? Particularly, there should be a bunch of "bootstrapping ..." logs that might be interesting.

**Comment by teskje** [comment]
> greater than `max_as_of` [0]

This is mighty suspicious though... `max_as_of` is calculated like this:
```rust
        let mut max_as_of = Antichain::new();
        for mv_id in &dependent_matviews {
            let since = self.storage_implied_capability(*mv_id);
            let upper = self.storage_write_frontier(*mv_id);
            max_as_of.meet_assign(&since.join(upper));
        }
```

So for it to be `[0]` the dependent MV would need to have both its `since` and its `upper` set to `[0]` too. The `upper` will be `[0]` if the MV has never been written, so that's fine. But I'm not sure in which cases we'd expect the `since` to be `[0]` too.

**Comment by def-** [comment]
[services.log](https://github.com/MaterializeInc/materialize/files/13833327/services.log)
[parallel-workload-queries.log](https://github.com/MaterializeInc/materialize/files/13833331/parallel-workload-queries.log)
u870 is:
```
parallel-workload-materialized-1     | environmentd: 2023-12-31T13:14:55.718198Z  INFO mz_adapter::catalog::state: create materialized view db-pw-1704028085-0.s-2.v-259 (u870)
```
which got created via:
```

[worker_29] CREATE MATERIALIZED VIEW "db-pw-1704028085-0"."s-2"."v-259" WITH (ASSERT NOT NULL "value0-kafka_table1", ASSERT NOT NULL "key4-kafka_table1", ASSERT NOT NULL "key2-kafka_table1") AS SELECT "db-pw-1704028085-0"."s-0".kafka_table1.key4 AS "key4-kafka_table1", "db-pw-1704028085-0"."s-0".kafka_table1.key2 AS "key2-kafka_table1", "db-pw-1704028085-0"."s-0".kafka_table1.value0 AS "value0-kafka_table1" FROM "db-pw-1704028085-0"."s-0".kafka_table1;
```
The kafka source definitions are not printed out (yet, but they should be), those are kafka sources from data-ingest:

https://github.com/MaterializeInc/materialize/blob/3a23184d43a15b91e6df666e657e608c45aa6c96/misc/python/materialize/data_ingest/executor.py#L221-L226

**Comment by teskje** [comment]
Thanks! I think that explains the `since = [0]`. Source `since`s are initialized to `[0]`, so any object created on top of a source immediately after its creation gets the same `since`.

**Comment by teskje** [comment]
One plausible case in which this could happen is if `environmentd` crashes after having committed a `CREATE MATERIALIZED VIEW` to the catalog, but before having created the storage collection. In this case, the storage collection will be created on the next bootstrap, but we will have forgotten about the `as_of`, so we use `[0]` instead.

### Repro

* Apply this diff:
```diff
diff --git a/src/adapter/src/coord/sequencer/inner/create_materialized_view.rs b/src/adapter/src/coord/sequencer/inner/create_materialized_view.rs
index 581a486819..815af62636 100644
--- a/src/adapter/src/coord/sequencer/inner/create_materialized_view.rs
+++ b/src/adapter/src/coord/sequencer/inner/create_materialized_view.rs
@@ -484,6 +484,8 @@ impl Coordinator {
                     .catalog_mut()
                     .set_dataflow_metainfo(exported_sink_id, df_meta.clone());

+                panic!();
+
                 // Announce the creation of the materialized view source.
                 coord
                     .controller
```

* Run `bin/environmentd --reset`
* Execute this SQL:

```sql
CREATE TABLE t (a int);
CREATE DEFAULT INDEX ON t;
CREATE MATERIALIZED VIEW mv AS SELECT * FROM t;
```

* Watch envd crash
* Unapply the above diff
* Run `bin/environmentd` (without reset!)
* Watch envd panic with message like the one reported above

**Comment by teskje** [comment]
Here is an explainer of what's happening:

The current as-of bootstrapping logic assumes that the frontiers of storage collections are always available from persist, so it just calls the storage controller’s `create_collections` with `since = None` and expects the actual `since` to be filled in from persist. This almost works, except in one case: It is possible that during handling a `CREATE MATERIALIZED VIEW` command, envd crashes after having committed the materialized view to the catalog but before having created the storage collection. In this case we end up with a materialized view that is listed in the catalog but doesn’t have a storage collection. So when we call `create_collections` for that MV during bootstrap, storage will create a new collection and initialize its `since` to 0. This is obviously bad because it makes the MV readable at times where it doesn’t contain valid data.

I think this is only an issue for materialized views. At least storage collections for sources and tables are initialized to `since = 0` anyway, so things come out the same.

Our best idea to fix this currently is to store the initial as-of of a materialized view durably in the catalog too. This way, we can pass the right as-of to the storage controller during bootstrapping and avoid the issue described above.

Alternatively, we could re-derive a valid as-of based on the frontiers of the dependencies of the MV. But this becomes annoying because to select as-ofs for indexes we need to look at the frontiers of dependent MVs, but to calculate the as-ofs of MVs we'd need to look at the frontiers of the indexes they depend on, which introduces some circular reasoning.
