### ISSUE TITLE
blue/green deployment: cached plan must not change result type

### ISSUE THREAD

**Issue by def-** [MaterializeInc/materialize#24196]
### What version of Materialize are you using?

643dfeec87e1

### What is the issue?

Seen in https://buildkite.com/materialize/tests/builds/72170#018ccea5-4be7-4e81-82f9-631ec27fa562
```
--- mzcompose: test case blue-green-deployment failed: <class 'pg8000.dbapi.ProgrammingError'>: {'S': 'ERROR', 'C': '0A000', 'M': 'cached plan must not change result type'}
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/pg8000/legacy.py", line 251, in execute
    self._context = self._c.execute_simple(operation)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/pg8000/core.py", line 678, in execute_simple
    self.handle_messages(context)
  File "/usr/local/lib/python3.11/dist-packages/pg8000/core.py", line 827, in handle_messages
    raise context.error
pg8000.exceptions.DatabaseError: {'S': 'ERROR', 'C': '0A000', 'M': 'cached plan must not change result type'}
```
Can be reproduced locally with
`while true; do bin/mzcompose --find cluster down && bin/mzcompose --find cluster run blue-green-deployment || break; done`
I'm guessing this comes from the cluster swap and is triggered here:

https://github.com/MaterializeInc/materialize/blob/178f8b550e6d121884a274bc1b6aeecf7c66be23/src/adapter/src/coord.rs#L673-L685

via https://github.com/MaterializeInc/materialize/pull/19195 CC @mjibson 

If this is an expected error during blue/green deployments, then we should at least document it in https://materialize.com/docs/manage/blue-green/ (and I would ignore it in this test

**Comment by ParkMyCar** [comment]
This is an expected error! If the catalog changes at all while a transaction with DDL is open (e.g. blue/green deployments) then we have to abort the transaction. I updated the docs to mention this (https://github.com/MaterializeInc/materialize/pull/24200).

More than happy to update the test as well if you can point me in the right direction, I couldn't find any similar examples.

**Comment by def-** [comment]
The error actually happens in the queries running SELECT/FETCH against the prod mvs, not in the swap itself. Still expected?

**Comment by ParkMyCar** [comment]
That is still expected, because we execute SELECTs in multiple stages and [before each stage](https://github.com/MaterializeInc/materialize/blob/main/src/adapter/src/coord/sequencer/inner.rs#L1833-L1838) we validate the current plan, which would be invalid after the swap
