### ISSUE TITLE
TPCH SLT tests could evaluate queries

### ISSUE THREAD

**Issue by frankmcsherry** [MaterializeInc/materialize#2422]
Our TPCH and CHBENCH SLT tests currently just evaluate the plans of queries, and do not evaluate them. This is probably because it is annoying to move around the associated data, which is usually more than just a few records. However, this means that we rely on visual inspection of query plans to catch potential correctness issues that would be surfaced by them, and not other queries. 

For example, a recent bug in `redundant_join.rs` seemed to manifest in TPCH Q2, and pass the rest of SLT. @wangandi observed some weird changes in the explain plan (from one join to another type) and only on further inspection was it determined to be very wrong.

**Comment by wangandi** [comment]
Given the fact that we can now test many rows of testdrive output by hashing the results, as an alternative to evaluating queries in TPCH SLT, we can have an automated chbench/tpch demo-based test where the demo loads a particular copy of the data in materialize, and we can run a set of  tpch/chbench testdrive tests against it.

**Comment by ggevay** [comment]
This should get easier once https://github.com/MaterializeInc/materialize/pull/14994 is merged.
