### ISSUE TITLE
REFRESH AT with timestamp in the future can't be explained

### ISSUE THREAD

**Issue by def-** [MaterializeInc/materialize#24244]
### What version of Materialize are you using?

main

### What is the issue?

```
materialize=> CREATE TABLE refresh_table (x INT);
CREATE TABLE
materialize=> CREATE MATERIALIZED VIEW refresh_view_late_1 WITH (REFRESH AT mz_now()::string::int8 + 86400000) AS SELECT DISTINCT(x) FROM refresh_table;
CREATE MATERIALIZED VIEW
materialize=> explain select * from refresh_view_late_1;
```
Hangs, even ctrl-c can never cancel it for 1 year. Discovered as part of https://github.com/MaterializeInc/materialize/pull/24219 thanks to Philip's great intuition on what to test!

**Comment by ggevay** [comment]
There is a Slack thread where this was being discussed:
https://materializeinc.slack.com/archives/C02FWJ94HME/p1699014313297729
@jkosh44 figured out the reason there, but there was no consensus on what exactly we could/should do about this:

Joe Koshakow
We may be accidentally linearizing the call to explain timestamp.

Gábor Gévay
Yess, it's not blocking in serializable mode. (Neither EXPLAIN TIMESTAMP, nor the query itself. It selects that as_of as the query timestamp.)

Joe Koshakow
Yeah, I think we must accidently see that the EXPLAIN TIMESTAMP is in the future and then wait for that timestamp to avoid violating linearizability.

Matt Jibson
Not sure that's an accident! We chose to make EXPLAIN TIMESTAMP be transaction aware, and this seems like a reasonable outcome for that choice.

Matt Jibson
(I'm not opposed to doing something different, but it should still be transaction aware which means it is able to set and retrieve the transaction timestamp.)

Joe Koshakow
I think it makes sense for EXPLAIN TIMESTAMP to choose a timestamp in the future, but it's not very useful for it to block and wait for that timestamp to actually happen.

**Comment by ggevay** [comment]
Fixed by https://github.com/MaterializeInc/materialize/pull/24828 and https://github.com/MaterializeInc/materialize/pull/24840
