### ISSUE TITLE
Bad CREATE MATERIALIZED VIEW, with bad SQL query, results in bad error message.

### ISSUE THREAD

**Issue by apghero** [MaterializeInc/materialize#2425]
I'm playing around with CSV files in materialized and created the following source:

```
=> CREATE SOURCE events FROM FILE '/tmp/foobar.csv' WITH (tail = true) FORMAT CSV WITH 8 COLUMNS;
CREATE SOURCE
```

This created the appropriate source, with the appropriate columns `column1`...`column8`. All good so far.

I then went to create a `MATERIALIZED VIEW` over the source:

```
=> CREATE MATERIALIZED VIEW event_count AS select column7, count(*) from events;
ERROR:  column "column7" does not exist
```

The intention was to create a summary of the number of events based on `column7`. But, as you can see, I forgot a `GROUP BY` and got a really terrible error message. `column7` does exist.

When created with the proper `GROUP BY` this works as normal:

```
=> CREATE MATERIALIZED VIEW event_count AS select column7, count(*) from events group by column7;
CREATE VIEW
```

**Comment by rjnn** [comment]
assigned to @jamii as he's the czar with the broad aegis of getting materialize better error messages, jamii feel free to reassign after you diagnose what would be needed to be done to get a fix.

**Comment by benesch** [comment]
Hey, thanks for the report @apghero, and sorry about this bad error message. It's been on our radar for a while, but is unfortunately challenging to fix at the moment. I'm going to close this out in favor of the existing issue, https://github.com/MaterializeInc/materialize/issues/443, but definitely let us know if you run into anything else.
