### ISSUE TITLE
Refactor controller read hold API

### ISSUE THREAD

**Issue by teskje** [MaterializeInc/materialize#24266]
The current API provided by the controller around read holds is confusing. These are some of the issues:

* There is an `implied_capability` and a set of `read_capabilities`. It is not obvious which one to use when querying the read frontier of a collection.
* Read holds can be taken using `update_read_capabilities` (modifying `read_capabilities` directly) but also by setting a read policy (modifying `implied_capability`).
* When setting a read policy to attempt to take a read hold before `implied_capability`, nothing happens because the capability is not allowed to regress. The caller is not informed about this fact. So if you set a read policy to install a read hold, it might be that this fails without you noticing.

We should come up with a better API that's less confusing and not as much of a footgun. I suspect that some of the current timestamp selection bugs in Compute could be avoided that way.

[In Slack](https://materializeinc.slack.com/archives/C01CFKM1QRF/p1700550352787449) @aljoscha and @petrosagg proposed this:

* The read policy should be either `NoPolicy` or `LagWriteFrontier`. It should not be possible to install read holds by changing the policy. (Perhaps it shouldn't even be possible to change the policy at all.)
* The controller should not expose `implied_capability` or `read_capabilities`.
* Instead it should expose an `acquire_read_hold` method that returns a `ReadHold` object that behaves like a Timely `Capability`. You can:
    * Clone it.
    * Downgrade it to allow compaction to some new read frontier.
    * Drop it to uninstall the read hold.
    * Query it for its time to get a valid read frontier of the collection.

**Comment by ggevay** [comment]
> Perhaps it shouldn't even be possible to change the policy at all

I think changing it [would be needed](https://www.notion.so/materialize/Spec-Retain-history-4ee425fb03a942fc8ec310f682f0a65f?pvs=4#0f869c83290f49b38834a2c7fb828a0e) for `ALTER … SET RETAIN HISTORY`.
