### ISSUE TITLE
storage/sources/postgres: correctness-property-2.td: ERROR: Timestamp (0) is not valid for all inputs

### ISSUE THREAD

**Issue by def-** [MaterializeInc/materialize#24324]
### What version of Materialize are you using?

1db872d9d00b

### What is the issue?

This is with running the Postgres CDC test on a smaller agent: https://github.com/MaterializeInc/materialize/pull/24303#pullrequestreview-1812744440
https://buildkite.com/materialize/tests/builds/72707#018cf2a7-093d-4531-9ea2-a5d802f9ef6e
```
^^^ +++
correctness-property-2.td:56:1: error: executing query failed: db error: ERROR: Timestamp (0) is not valid for all inputs: [Antichain { elements: [1704879260000] }]: ERROR: Timestamp (0) is not valid for all inputs: [Antichain { elements: [1704879260000] }]
     |
  10 | $ postgres-execute c ... [rest of line truncated for security]
  15 | $ postgres-execute c ... [rest of line truncated for security]
  32 | > CREATE SECRET pgpa ... [rest of line truncated for security]
  38 |     PASSWORD SECRET  ... [rest of line truncated for security]
  52 | $ postgres-execute c ... [rest of line truncated for security]
  55 | # Verify that at timestamp 0 there is only one record whose value is the final value
  56 | > FETCH 1 c WITH (timeout = '1d');
     | ^
```
@petrosagg This test was added in https://github.com/MaterializeInc/materialize/pull/22163, do you have any idea?

**Comment by petrosagg** [comment]
I have seen this test fail if the queries in testdrive are not ran fast enough for them to be scheduled at timestamp `0`. Is there a way to disable compaction in a materialize test? I think that would fix it

**Comment by def-** [comment]
If we have a flag we cold set it during materialized startup, if it's an ALTER SYSTEM, we could set it too. I only know about `enable_logical_compaction_window` and `upsert_rocksdb_universal_compaction_ratio`, but not sure if any of them help here.

**Comment by benesch** [comment]
I think the new `RETAIN HISTORY` option should let us set an infinite history retention window, which will guarantee that testdrive can see the initial snapshot at 0.

Also related is this issue about setting a non-0 since frontier when a source is created: https://github.com/MaterializeInc/materialize/issues/24955

**Comment by nrainer-materialize** [comment]
Further occurrence (with MySQL source): https://buildkite.com/materialize/tests/builds/76420#018dcffd-0cbe-4b09-bc0d-6a1dda9ca801
