### ISSUE TITLE
`IN` does not support same operators as `= ANY`

### ISSUE THREAD

**Issue by sploiselle** [MaterializeInc/materialize#2440]
`IN` and `= ANY` are equivalent w/r/t subqueries, [according to the PG docs](https://www.postgresql.org/docs/9.0/functions-subquery.html), however in Materialize, `IN` does not support the `VALUES` function, as `= ANY` does.

In PG, both of these...

```sql
SELECT col FROM (SELECT 1 AS col) t WHERE col IN(VALUES(1));
SELECT col FROM (SELECT 1 AS col) t WHERE col = ANY(VALUES(1));
```
evaluate to....
```
 col
-----
   1
```

In Materialize:

```sql
SELECT col FROM (SELECT 1 AS col) t WHERE col IN(VALUES(1));
```
generates an error:
```
ERROR:  unsupported function: values
```

However, these evaluate to the same thing:

```sql
SELECT col FROM (SELECT 1 AS col) t WHERE col = ANY(VALUES(1));
SELECT col FROM (SELECT 1 AS col) t WHERE col IN(1);
```
```
 col
-----
   1
```

**Comment by benesch** [comment]
Looks like a parsing error to me.

**Comment by benesch** [comment]
Yep, this is missing a test for the `VALUES` keyword: https://github.com/MaterializeInc/materialize/blob/7243a8e2bce18e835c0659bba1bfe0c94e837551/src/sql-parser/src/parser.rs#L757. Should be an easy fix!
