### ISSUE TITLE
STDDEV_SAMP returns "Evaluation error: cannot take square root of a negative number" for valid inputs

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#24433]
### What version of Materialize are you using?

 v0.84.0-dev (cc64d57df)

### What is the issue?

```
CREATE TABLE t2 (f1 DOUBLE PRECISION);
INSERT INTO t2 VALUES (0.2);
INSERT INTO t2 VALUES (0.2);
SELECT STDDEV_SAMP ( t2 . f1 ) FROM t2;
ERROR:  Evaluation error: cannot take square root of a negative number
```

The special about those inputs is that A) they are identical and B) they are < than 1.

I suspect that `-0` may be the intermediate value that is causing the errror?

Postgres is able to compute this just fine.

This one is also weird, postgres returns a straight-up zero regardless of the precision/scale of the inputs, as long as they are identical:
```
materialize=> CREATE TABLE t2 (f1 DOUBLE PRECISION);
CREATE TABLE
materialize=> INSERT INTO t2 VALUES (1.3);
INSERT 0 1
materialize=> INSERT INTO t2 VALUES (1.3);
INSERT 0 1
materialize=> SELECT STDDEV_SAMP ( t2 . f1 ) FROM t2;
     stddev_samp      
----------------------
 0.000493139884957727
(1 row)
```

Edit: Possibly related to https://github.com/MaterializeInc/materialize/issues/15186

**Comment by umanwizard** [comment]
```
materialize=> insert into t values (0.6), (0.6);
INSERT 0 2
materialize=> select variance(x) from t;
       variance        
-----------------------
 -4.768374139985099e-9
(1 row)
```

I suggest we just clamp `variance` to zero.
