### ISSUE TITLE
`REFRESH AT` MVs make their inputs' read frontiers stuck

### ISSUE THREAD

**Issue by ggevay** [MaterializeInc/materialize#24469]
### What version of Materialize are you using?

bf1d9b656f11f17c95015fdc99a9d15c54b713b0

### What is the issue?

repro:
```
create table t (x int);

create materialized view mv1 with (refresh at creation) as
select * from t;
```

and then observe the read frontiers of the table not moving with
```
select * from mz_internal.mz_frontiers where object_id like 'u%';
```

The problem is that the global (i.e., not per-replica) read capabilities that we are holding for the inputs of a compute dataflow are based on the read frontier, and a `REFRESH AT` MV's read frontier is expected to be stuck at the last refresh. The fix is to special-case MVs (or more generally, dataflows whose outputs are persisted, which currently are only MVs) to hold read capabilities on their input's at the MV's write frontier instead of the read frontier. This is ok for MVs because their outputs are persisted, so if a new replica comes up, it can just start from the write frontier. (Wouldn't be ok for indexes, because if a new replica is started up suddenly, then it has to be able to reconstruct the arrangement from the inputs.)

@teskje figured out a fix in two long meetings today, and says he will open a PR tomorrow.

**Comment by nrainer-materialize** [comment]
Is https://github.com/MaterializeInc/materialize/issues/24462 related?
