### ISSUE TITLE
retain history: inconsistent behavior with timestamps before MV / source creation

### ISSUE THREAD

**Issue by nrainer-materialize** [MaterializeInc/materialize#24478]
### What version of Materialize are you using?

3f8d05dbe23b7682a0c5a1ffafbc21da72f714b8

### What is the issue?

The behavior of materialized views and sources with retain history is not consistent. In particular, the behavior of the following scenarios should be specified, implemented and verified. The behavior should not differ between materialized views and sources.
* read from materialized view on table with timestamp before the underlying table (and materialized view) existed
* read from materialized view on table with timestamp when the underlying table existed but the materialized view did not
* read from Kafka source with timestamp before the Kafka topic (and source) existed
* read from Kafka source with timestamp when the topic existed but the source did not

Currently, the behavior differs between materialized views and sources **and does not seem to be stable** (empty result vs. `is not valid for all inputs`). Sleep statements can change the observed output.

See also: https://github.com/MaterializeInc/materialize/pull/24344#issuecomment-1894342314

**Comment by nrainer-materialize** [comment]
Please reach out to team-testing for adjusting and re-enabling `misc/python/materialize/checks/all_checks/retain_history.py` once the failure is fixed. Thanks!

**Comment by umanwizard** [comment]
I am not convinced it should be the same for sources as for MVs. As far as I know, Storage does not commit to timestamps having any particular connection to when things existed in the upstream object (this will change as part of RTR, presumably).

So, today when you create a source with `RETAIN HISTORY` far in the past, we will claim that the source had data before the upstream object (Kafka etc.) actually existed, but is that actually a bug, or Storage working as designed? @petrosagg , @benesch any thoughts?

**Comment by benesch** [comment]
It strikes me as a bug that `CREATE SOURCE ... (RETAIN HISTORY '30 days')` will allow you to  `SELECT ... AS OF now() - '1 day'` and see the empty set. At least, I think it is plausibly a violation of correctness property #2? We don't know what happened before the source was created, and I think we shouldn't invent the fact that the source was empty. 

> there was at least one usecase that benefits from sources claiming that they've existed since the beginning of time and that is that you can load up a snapshot from your kafka topic (which will appear at timestamp 0) and then apply a temporal filter that fills in the historical detail on the correct timestamps

Yup, agreed, but I think that's probably behavior that we want users to opt-in to? Total strawman naming, but imagine `CREATE SOURCE ... WITH (SNAPSHOT TIMESTAMP = 0)`.

**Comment by umanwizard** [comment]
I tried to comment again last night, but somehow it got lost ...

Anyway, Storage should tell us what the minimum valid timestamp for new sources is. Is this "the wall-clock timestamp at which the source was created" ? If so, then I agree we have a bug.

**Comment by umanwizard** [comment]
For MVs, the behavior is as I expected: I was not able to query data from before the validity of the dependent objects. @nrainer-materialize if you are observing different behavior, can you provide a test or example?

**Comment by petrosagg** [comment]
Storage today says "the source existed since the unix epoch" and the snapshot happened at timestamp 0, so things behave according to this specification

**Comment by umanwizard** [comment]
Doesn't that contradict what you said earlier (in [this message](https://github.com/MaterializeInc/materialize/issues/24478#issuecomment-1916344102)) ?


It seems you agree with Nikhil's assessment that being able to query a source from before it was created is a bug.

**Comment by umanwizard** [comment]
Ok, I am dumb. I realize now that you were talking about observing an empty set at timestamp 0, not about being able to query timestamp 0 at all.

Reassigning this to @nrainer-materialize . My understanding of the desired behavior is as follows:

1. Sources can be valid from timestamp 0, so setting any `RETAIN HISTORY` less than about 54 years should allow you to query from the beginning of that retain history.
2. MVs can be valid from the intersection of valid times of their dependent objects, so setting `RETAIN HISTORY` to a large value will initially only allow you to query times close to the present (with the queryable range increasing over time from then).

Rainier, please let me know if you can observe any other behavior.

**Comment by nrainer-materialize** [comment]
Thank you, @umanwizard, I will double-check the implementation with this information.

**Comment by benesch** [comment]
> Storage today says "the source existed since the unix epoch" and the snapshot happened at timestamp 0, so things behave according to this specification

Ah, right. I keep forgetting that we satisfied correctness property #2 by always reclocking the snapshot to time 0, rather than performing the snapshot at `now()` and then setting the source's since frontier to `now()`.

**Comment by frankmcsherry** [comment]
Fwiw, I don't 100% agree that this case needs to be handled identically, which if nothing else means there is stuff to unpack. 

> read from materialized view on table with timestamp when the underlying table existed but the materialized view did not

There is a legit take that if the materialized view is fully declarative, it can be mapped across historical data that precedes it. Views certainly can, and materialized views .. maybe aren't that different from views? There are some ways in which they are different, and we don't want to assume that a MV has content identical to the view (because refreshes, version updates), but it seems not unreasonable to allow them to accurately manipulate the past.

**Comment by petrosagg** [comment]
> Ah, right. I keep forgetting that we satisfied correctness property https://github.com/MaterializeInc/materialize/issues/2 by always reclocking the snapshot to time 0, rather than performing the snapshot at now() and then setting the source's since frontier to now().

@benesch The mechanism for the correctness property is not related to the strategy of picking the since frontier. We can pick any since frontier we want without changing how the correctness property is satisfied. This is because even if you initialize the since to `now` the upper frontier still starts at [0] and that is where the snapshot will be emitted. It's just that everything from [0] to [now] will not be available for reading

**Comment by umanwizard** [comment]
> read from materialized view on table with timestamp when the underlying table existed but the materialized view did not

@frankmcsherry , this works for MVs already now. I agree that we should not change that.

**Comment by benesch** [comment]
> > Ah, right. I keep forgetting that we satisfied correctness property #2 by always reclocking the snapshot to time 0, rather than performing the snapshot at now() and then setting the source's since frontier to now().
> 
> @benesch The mechanism for the correctness property is not related to the strategy of picking the since frontier. We can pick any since frontier we want without changing how the correctness property is satisfied. This is because even if you initialize the since to `now` the upper frontier still starts at [0] and that is where the snapshot will be emitted. It's just that everything from [0] to [now] will not be available for reading

Makes sense. I think we may, as a matter of policy unrelated to correctness property #2, want to default to setting the since frontier to `now()`. Don't have bandwidth to push on this much more at the moment, but I'll probably rope you and @frankmcsherry into a conversation about this at some point in the next month or so.

**Comment by benesch** [comment]
I filed https://github.com/MaterializeInc/materialize/issues/24955 to propose that we change the default initial since frontier for sources from 0 to `mz_now()`. @petrosagg @frankmcsherry let's move discussion about whether we like that plan or not to that issue? I'll also raise in the storage hangout and/or weekly this week.

**Comment by nrainer-materialize** [comment]
Sorry for the delay, I had some issues with platform checks and the test itself that had blocked me.

Here are the results:

### Summary
* The MV produces an error for a timestamp at a time before the table exists. Once a timestamp is reached at which the table exists, it returns the data of the table regardless whether the MV already exists at that time or not.
* The source provides the data at the state of the time at which the source was created for timestamps before the source creation.
* Both MV and source return an error once the retain-history window is left. This does not seem in line with the other two observations.

### Materialized Views

| Logical Time  | Used `now()` | Event             | Outcome        |
| ------------- | -------------- | ------------- | ------------- |
| 0 | `2024-02-05 17:59:21.425`  | nothing exists | `Timestamp (1707155961425) is not valid for all inputs`
| 1 | `2024-02-05 17:59:21.548`  | table created | empty data set delivered (= data of time 1)
| 2 | `2024-02-05 17:59:21.576`  | table populated | data of time 2 delivered
| 3 | `2024-02-05 17:59:22.087`  | mv created, table updated | data of time 3 delivered
| 4 | `2024-02-05 17:59:22.114`  | table updated | data of time 4 delivered
| 5 | `2024-02-05 17:59:22.236`  | table updated | data of time 5 delivered


<details>
  <summary>Raw data</summary>

```
materialize=> select * from time;
 time_index |            t            
------------+-------------------------
          0 | 2024-02-05 17:59:21.425
          1 | 2024-02-05 17:59:21.548
          2 | 2024-02-05 17:59:21.576
          3 | 2024-02-05 17:59:22.087
          4 | 2024-02-05 17:59:22.114
          5 | 2024-02-05 17:59:22.236
(6 rows)

When submitting the query after the retain-history time window, `Timestamp (***) is not valid for all inputs` will be returned. Given the outcome from above, this is a bit unexpected for me.

materialize=> SELECT * FROM retain_history_mv1 AS OF '2024-02-05 17:59:21.425'::TIMESTAMP;
ERROR:  Timestamp (1707155961425) is not valid for all inputs: [Antichain { elements: [1707155961495] }]

materialize=> SELECT * FROM retain_history_mv1 AS OF '2024-02-05 17:59:21.548'::TIMESTAMP;
 key | value 
-----+-------
(0 rows)

materialize=> SELECT * FROM retain_history_mv1 AS OF '2024-02-05 17:59:21.576'::TIMESTAMP;
 key | value 
-----+-------
   1 |   100
   2 |   200
   3 |   300
(3 rows)

materialize=> SELECT * FROM retain_history_mv1 AS OF '2024-02-05 17:59:22.087'::TIMESTAMP;
 key | value 
-----+-------
   1 |   110
   2 |   200
   3 |   300
(3 rows)

materialize=> SELECT * FROM retain_history_mv1 AS OF '2024-02-05 17:59:22.114'::TIMESTAMP;
 key | value 
-----+-------
   1 |   110
   2 |   200
   3 |   300
   4 |   400
(4 rows)

materialize=> SELECT * FROM retain_history_mv1 AS OF '2024-02-05 17:59:22.236'::TIMESTAMP;
 key | value 
-----+-------
   1 |   110
   2 |   200
   4 |   400
(3 rows)

-- wait some time

materialize=> select now();
            now             
----------------------------
 2024-02-05 18:12:20.272+00
(1 row)

materialize=> SELECT * FROM retain_history_mv1 AS OF '2024-02-05 17:59:24.93'::TIMESTAMP;
ERROR:  Timestamp (1707155964930) is not valid for all inputs: [Antichain { elements: [1707156141000] }]
```

</details>


### Kafka Sources

| Logical Time  | Used `now()` | Event             | Outcome        |
| ------------- | -------------- | ------------- | ------------- |
| 0 | `2024-02-05 18:19:15.360`  | nothing exists | data of time 3 delivered
| 1 | `2024-02-05 18:19:19.406`  | topic created | data of time 3 delivered
| 2 | `2024-02-05 18:19:22.293`  | added data to topic | data of time 3 delivered
| 3 | `2024-02-05 18:19:24.358`  | updated data in topic | data of time 3 delivered
| 4 | `2024-02-05 18:19:26.534`  | source created in mz | data of time 3 delivered
| 5 | `2024-02-05 18:19:29.872`  | updated data #1 | data of time 5 delivered
| 6 | `2024-02-05 18:19:33.172`  | updated data #2 | data of time 6 delivered
| 7 | `2024-02-05 18:19:35.202`  | updated data #3 | data of time 7 delivered

When submitting the query after the retain-history time window, `Timestamp (***) is not valid for all inputs` will be returned. Given the outcome from above, this is a bit unexpected for me.

<details>
  <summary>Raw data</summary>

```
materialize=> select * from time;
 time_index |            t            
------------+-------------------------
          0 | 2024-02-05 18:19:15.36
          1 | 2024-02-05 18:19:19.406
          2 | 2024-02-05 18:19:22.293
          3 | 2024-02-05 18:19:24.358
          4 | 2024-02-05 18:19:26.534
          5 | 2024-02-05 18:19:29.872
          6 | 2024-02-05 18:19:33.172
          7 | 2024-02-05 18:19:35.202
(8 rows)

materialize=> select * from retain_history_source;
 key1 | f1 
------+----
 K0   | D0
 K1   | C1
 K2   | C2
 K3   | C3
 K4   | C4
 K5   | C5
(6 rows)

materialize=> SELECT * FROM retain_history_source AS OF '2024-02-05 18:19:15.360'::TIMESTAMP;
 key1 | f1 
------+----
 K0   | A0
 K1   | A1
 K2   | A2
 K3   | A3
 K4   | A4
(5 rows)

materialize=> SELECT * FROM retain_history_source AS OF '2024-02-05 18:19:19.406'::TIMESTAMP;
 key1 | f1 
------+----
 K0   | A0
 K1   | A1
 K2   | A2
 K3   | A3
 K4   | A4
(5 rows)

materialize=> SELECT * FROM retain_history_source AS OF '2024-02-05 18:19:22.293'::TIMESTAMP;
 key1 | f1 
------+----
 K0   | A0
 K1   | A1
 K2   | A2
 K3   | A3
 K4   | A4
(5 rows)

materialize=> SELECT * FROM retain_history_source AS OF '2024-02-05 18:19:24.358'::TIMESTAMP;
 key1 | f1 
------+----
 K0   | A0
 K1   | A1
 K2   | A2
 K3   | A3
 K4   | A4
(5 rows)

materialize=> SELECT * FROM retain_history_source AS OF '2024-02-05 18:19:26.534'::TIMESTAMP;
 key1 | f1 
------+----
 K0   | A0
 K1   | A1
 K2   | A2
 K3   | A3
 K4   | A4
(5 rows)

materialize=> SELECT * FROM retain_history_source AS OF '2024-02-05 18:19:29.872'::TIMESTAMP;
 key1 | f1 
------+----
 K0   | B0
 K1   | B1
 K2   | A2
 K3   | A3
 K4   | A4
(5 rows)

materialize=> SELECT * FROM retain_history_source AS OF '2024-02-05 18:19:33.172'::TIMESTAMP;
 key1 | f1 
------+----
 K0   | C0
 K1   | C1
 K2   | C2
 K3   | C3
 K4   | C4
 K5   | C5
(6 rows)

materialize=> SELECT * FROM retain_history_source AS OF '2024-02-05 18:19:35.202'::TIMESTAMP;
 key1 | f1 
------+----
 K0   | D0
 K1   | C1
 K2   | C2
 K3   | C3
 K4   | C4
 K5   | C5
(6 rows)

-- wait for some time

materialize=> select now();
            now             
----------------------------
 2024-02-05 18:32:52.185+00
(1 row)

materialize=> SELECT * FROM retain_history_source AS OF '2024-02-05 18:19:35.202'::TIMESTAMP;
ERROR:  Timestamp (1707157175202) is not valid for all inputs: [Antichain { elements: [1707157380000] }]

```

</details>

### Other
* See also: https://github.com/MaterializeInc/materialize/blob/e63d3a4ca62e5e9bc2d06ea6d5f82662315ccd51/misc/python/materialize/checks/all_checks/retain_history.py
* `now()` has limitations, see https://github.com/MaterializeInc/materialize/issues/24479#issuecomment-1916271626

**Comment by nrainer-materialize** [comment]
@benesch: How should we proceed here?

**Comment by nrainer-materialize** [comment]
Yes, makes sense!

Closing this issue in favor of #24955.
