### ISSUE TITLE
[Epic] Better visibility into pushdown behavior on an actual query execution

### ISSUE THREAD

**Issue by bkirwi** [MaterializeInc/materialize#24498]
## Product outcome

Materialize's "filter pushdown" feature allows the database to skip fetching batch parts from S3 when it can prove that the data in those parts will not impact the result of the query. For example, if we know that column `c` has numbers between 1 and 10 in a particular part, and the user filters `WHERE c > 100`, nothing in that part will affect the result of the query and we don’t need to fetch it. (I’ll refer to parts that get discarded this way as “pruned”.) For users with large or append-only datasets, this optimization is often critical for having queries run in a reasonable time.

This feature shipped along with an extension to our `EXPLAIN` plans: if a user runs `EXPLAIN ... WITH (filter_pushdown)`, the output includes a `pushdown=` sections that lists all the filters that may help prune the source. Limitations of this approach include:

- *May* is a load-bearing word: since the actual effectiveness of pushdown depends on the stats of individual parts, we can't actually know for sure whether a query will prune any of them in practice.
- It can't tell us *how much* data is getting pruned for a query. To the existing explain machinery, `WHERE ts + '1 year' > mz_now()` looks the same as `WHERE ts + '1 minute' > mz_now()`... but the latter will prune much more effectively.

Along with this sort of static query analysis, **we’d like to add a way for users to look at the *actual* amount of pushdown that a specific execution of a query sees, letting them confirm that they’re seeing meaningful speedups on actual data**.

## Discovery

Two approaches here…

### EXPLAIN PUSHDOWN

One challenge with using real shard statistics in our explain plans: it requires us to fetch shard statistics from Persist, but EXPLAIN isn’t allowed to make async calls.

EXPLAIN TIMESTAMP solves a similar problem by splitting up the logic into two parts. The first does some preparatory work and kicks off an async task in the background; the second runs when that task completes and returns the response to the user. We could add a new `EXPLAIN PUSHDOWN` command that uses a similar pattern, fetching shard statistics instead of timestamp info, with output something like:

```sql
> EXPLAIN PUSHDOWN FOR SELECT * FROM my_table where my_col + '1 minute' > mz_now();
Total Bytes | Total Parts | Pruned Bytes | Pruned Parts
------------+-------------+--------------+--------------------
12343       | 16          | 456          | 7
```

Adding a new explain variant seems tedious but straightforward. The design has some open questions, though:

- What kind of information do we want to expose, and how should we format it? (We could include per-part statistics, or info on whether a part was kept because a filter returned true or raised an exception.)
- This is *less* useful than the existing explain plan when the user doesn’t have much existing data. (Perhaps they’ve created a source but haven’t started loading their dataset yet.)
- It’s not obvious how to adapt this for long-running dataflows like materialized or indexed views. These dataflows are planned differently, for example, and are likely to have very different pushdown rates during the initial snapshot than they do afterwards.

### Some catalog table

Maybe `persist_source` should emit a log whenever it makes a decision for a part, then roll those up into some introspection source / catalog table? Compute does this sort of thing all the time, though I don’t think Storage ever has.

This is likely a smaller project. It may give more useful statistics for long-running dataflows, but less useful feedback when iterating on queries.

## Work items

```[tasklist]
### Tasks
- [ ] Add some tasks
```

**Comment by bkirwi** [comment]
cc @sjwiesman, since I know you have experience with (and hit the limitations of) the current EXPLAIN output!

A few options here; any feedback is extremely useful.

**Comment by danhhz** [comment]
> but less useful feedback when iterating on queries

I think that we probably have some options here, if we're able to correlate the dataflow logging with the peek itself, for grabbing the logs after the query executes and presenting them back. I don't have enough context to know if we have the id plumbing to line that up though.

**Comment by sjwiesman** [comment]
Thank you for writing this up!


. Is the intent to only provide statistics for peeks? Or also long running dataflows. If it’s the later I think we’re locked into a catalog table. If it’s the former, I think I still prefer a catalog table. But only if it can be joined against mz_activity_log. But the explain is certainly useful.

**Comment by bkirwi** [comment]
> Is the intent to only provide statistics for peeks? Or also long running dataflows.

The intent is definitely "whatever seems useful"! In practice everyone seems to care mostly about the initial snapshot of even long-running dataflows, so you could in theory do a `EXPLAIN PUSHDOWN FOR MATERIALIZED VIEW x` and get the stats as though the dataflow was re-bootstrapping. But of course if you're interested in historical performance that's less useful.

Illustrative case: let's say I create a source and a downstream MV with a tight temporal filter. My source starts out empty, but fills up over the course of the week. Doing an `EXPLAIN` of the MV query would show very good pushdown, since if the MV was re-bootstrapping that temporal filter would do a lot of pruning. But a stats table would show that the MV was fetching almost every part -- since at the time every row was ingested, it was brand new and so would survive the temporal filter. (Of course, eventually we'll do a release and the MV will re-bootstrap and the stats will look much better.) Which of those is more useful in practice?

**Comment by sjwiesman** [comment]
I think you've convinced me on `EXPLAIN` as being a better tool for troubleshooting.

**Comment by bkirwi** [comment]
Nikhil suggests another option: keeping stats for individual peeks, and sending them back with the results as a notice.

This is exciting for prototyping, since it involves much less new interface than a new `EXPLAIN` variant. May not be the right interface for production, though:

**Comment by benesch** [comment]
That all makes sense, Seth! Thanks for thinking about this with us. Quick point of clarification: are you using `EXPLAIN STRAWMAN SYNTAX FOR ...` in your example instead of `EXPLAIN PUSHDOWN FOR ...` because you don't like the `EXPLAIN PUSHDOWN` syntax?

**Comment by aalexandrov** [comment]
> I think what we do depends on which question we're looking to answer. IMO, the first is more pressing as we want to keep people from running bad queries in production. The second, while interesting is ultimately useless. If you find out your view can't restart, you don't have any many options today.

I agree that `EXPLAIN PUSHDOWN` is going to produce better results if we can teach people how to use it correctly. Some assorted random remarks below (I'll think about this more over the weekend and might have more consolidated thoughts next week).

---

It would be great if we also report the `Served Bytes` and `Served Parts` in the output so people don't have to do the `total - pruned` math themselves.

---

It would be nice if the result of `EXPLAIN PUSHDOWN` can be a relation (as opposed to a singleton set) where the individual rows are against the `pushdown=` entries in `Source materialize.public.t`. That way users should be able to identify the pushdown effects for each input. If we also want to have the aggregated stats we should consider a text output that has both the breakdown and the totals (similar to `EXPLAIN TIMESTAMP`).

--- 

Regular `EXPLAIN` now reports both `filter` and `pushdown` to the sources 

```
materialize=> create table t(x int, y int);
CREATE TABLE
materialize=> explain select 2 * x from t where (x + 1)*(x + 1) > 0;
                      Optimized Plan                      
----------------------------------------------------------
 Explained Query:                                        +
   Project (#3) // { arity: 1 }                          +
     Filter ((#2 * #2) > 0) // { arity: 4 }              +
       Map ((#0{x} + 1), (2 * #0{x})) // { arity: 4 }    +
         ReadStorage materialize.public.t // { arity: 2 }+
                                                         +
 Source materialize.public.t                             +
   filter=(((#2 * #2) > 0))                              +
   map=((#0{x} + 1))                                     +
   pushdown=(((#2 * #2) > 0))                            +
```

but AFAICT at the moment the `map` and `filter` bits are not substantial in any way to the runtime behavior of the installed dataflow (all sources are `persist` sources and the `filter` expressions that they get are applied locally in the same process). I wonder if this might be confusing for people.

We can change this to only print `pushdown` under each source and have an `source_mfps` flag that is used for testing purposes in order to compare the `pushdown` expression against the MFP attached to the `Sources`.

**Comment by bkirwi** [comment]
Thank you for the comments!

> It would be great if we also report [...]

Fair! Do you think it's better to just report the served bytes instead of the pruned bytes? (Reporting both seems a bit redundant / denormalized, though I don't know if we care here.)

> It would be nice if the result of EXPLAIN PUSHDOWN can be a relation [...]

Agree - will do this for the prototype. (I think it's probably fine not to serve the aggregates, so I'll hold the text output for now, but agree that it may be the right call as this evolves.)

> Regular EXPLAIN now reports both filter and pushdown to the sources [...]

Possible. We've gone back and forth on how best to present the `pushdown=` information in the past, and I wasn't around when the `map=`/`filter=` info was added. I'm tempted to leave the "vanilla" explain output alone for now, though that may be a wise followup depending on where we land here...

**Comment by bkirwi** [comment]
I've got a draft of the syntax up here: https://github.com/MaterializeInc/materialize/pull/25053

Right now this supports queries of the form `EXPLAIN PUSHDOWN FOR <explainee>`. I expect to start by supporting just `SELECT` statements as the explainee, though In the Fulness of Time it could in theory support all the types that `EXPLAIN <explainee>` supports.

@sjwiesman - did you have thoughts on Nikhil's https://github.com/MaterializeInc/materialize/issues/24498#issuecomment-1922857481? This syntax is likely to stay behind a flag for a while, so it's not urgent to get it exactly right, but might as well start with something that feels good to folks here...

**Comment by sjwiesman** [comment]
Current syntax is great! I was just trying to be unopinionated. I didn’t mean to imply I don’t like what you’ve proposed!

**Comment by bkirwi** [comment]
Figured, but safer to check - thanks!

**Comment by danhhz** [comment]
Given that the MV part of this has a PR up that I can link to, gonna call this one shipped!
