### ISSUE TITLE
Link source reference documentation to the top level buttons under "Ingest"

### ISSUE THREAD

**Issue by chuck-alt-delete** [MaterializeInc/materialize#24494]
### Documentation request

Currently clicking on any of the sections under "Ingest" opens a drop-down to guides. Then further down in the menu under "Reference" we have "Sources" which give reference documentation for various sources. I think these reference pages should be accessible when clicking the top level for sources under "Ingest" in addition to opening the drop-downs.

**Comment by morsapaes** [comment]
I've been thinking about navigation and what I'd like to do is add an `Overview` section to each top-level nav with, well, an overview of the topic and top-level best practices. We rely too much on linking the reference pages directly, which are cumbersome to parse. We can then link the reference from there.

I'll hopefully have a little more room to work on docs now, and have already started reorganizing things also so we can improve troubleshooting docs in the short-term (which similarly will exist as a `Troubleshooting` section under each top-level).
