### ISSUE TITLE
Dynamically scale the number of workers in Materialize

### ISSUE THREAD

**Issue by rjnn** [MaterializeInc/materialize#2449]
This is a tracking issue for making Materialize appear dynamically scalable. Currently, `--workers` can only be set at startup; scaling up Materialize requires shutting down Materialize and restarting it with a new `--workers` number. While all source and view definitions will be reinstalled, data will be reingested and computation replayed, which results in downtime.

"Dynamically scaling Materialize" is the meta-issue to reduce this downtime, to the point where *Materialize* can dynamically start and shut down timely dataflow clusters of varying sizes at will, while the user gets a seamless experience of no downtime; similar to how a regular database might start and stop queries and index builds over the course of operation.

Dynamically rescaling worker counts has some substantial prerequisites:
 - [ ] Data Persistence (#1182)
 - [ ] Exactly once support (#2078)
 - [ ] Active/active replication (#5)

In theory dynamically scaling Materialize doesn't strictly require active/active clusters in distributed settings (one could imagine wanting to dynamically scale on a single machine), but we should cut scope to only support it on multi-node clusters. The target deployment we are solving for is cloud deployments, where requisitioning more cores is just as easily done by requisitioning a larger VM as scaling up a running VM. Given that rescaling from `m` to `n` workers *temporarily* requires `m+n` cores, its easier to switch over entirely from an `m` core VM to an `n` core VM with an overlap than scaling up to `m+n` and then scaling down to `n`.

Data persistence is a requirement because without it, Materialize would cause havoc on upstream stream processors by replaying datasets. Replay should be minimal. Since data persistence will be achieved using object storage, this is not a major confounding factor - object stores can be accessed by multiple VMs.

Exactly once support is required as the new cluster should pick up *exactly* where the old cluster left off. This is a prerequisite for active/active replication for failover reasons in any case, but it probably is worth restating here.

**Comment by benesch** [comment]
This is finally happening! Tracked in #11240.
