### ISSUE TITLE
SLT rewrite doesn't properly handle multiline queries.

### ISSUE THREAD

**Issue by umanwizard** [MaterializeInc/materialize#24533]
### What version of Materialize are you using?

latest

### What is the issue?

see title.

If a query changes to have a multi-line output, we need to add "multiline" to the query descriptor (e.g. change `query T` to `query T multiline`).

**Comment by mjibson** [comment]
Although multilines are not specifically mentioned in #23294, I think this is a essentially a dup of that.

**Comment by umanwizard** [comment]
I agree, closing this
