### ISSUE TITLE
Connector, format matrix

### ISSUE THREAD

**Issue by sploiselle** [MaterializeInc/materialize#2458]
Which connectors support which formats?

Right now the docs express a limited set of these combinations, but could be more robust, e.g. CSV over Kafka.

**Comment by msudberg** [comment]
The matrix should link out to pages with more details on the support (even if that detail is: "We're thinking about it, let us know if you're interested"). For more discussion, see:

https://materializeinc.slack.com/archives/CPNFV9CVB/p1611928541011300

(Short version: We want search engines to pick up our page on the connectors, not outdated random user pages which may be complaining about a lack of support long after we've implemented something.)

**Comment by sploiselle** [comment]
Ah, I had meant to close this issue when I refactored the `CREATE SOURCE` page, which now contains this matrix:
https://materialize.com/docs/sql/create-source/

If there's some other detail you think we should add, feel free to re-title the issue.
