### ISSUE TITLE
Storage Stability - Improving controller/cluster protocol

### ISSUE THREAD

**Issue by sploiselle** [MaterializeInc/materialize#24585]
Linking to this doc in GitHub just so we have a place to refer to this work in GitHub.

https://docs.google.com/document/d/19i1lBaTKY4-G9Vi2_2-FpRzA1RecYuOCcOk0KMnDacI/edit

**Comment by petrosagg** [comment]
Closing as duplicate of https://github.com/MaterializeInc/materialize/issues/23513
