### ISSUE TITLE
persist: add a "no fencing" mode for catalog debug tool

### ISSUE THREAD

**Issue by danhhz** [MaterializeInc/materialize#24695]
The catalog has a debug cli tool, one of it's functions is to verify that the actual contents of the catalog in some environment are understood by some particular build of the catalog code. This is used in the release process, in addition to the usual testing, as a final check that we're not going to brick any envs in staging or prod.

Now that we have the persist catalog impl, there is an unexpected interaction. Reading a persist shard requires registering a reader (a crdb write, counter-intuitively), which tags persist state with the version of the code doing the reading. We're adding one minor version of forward compatibility to persist, but if someone e.g. runs the catalog debug tool's upgrade checker using a build two minor versions in the future, it would immediately fence out the running environment.

So, to prevent this from accidentally happening, we'd like to add the ability for the catalog debug tool to request that it not fence out the currently operating version.

One thing to note here is that it's a bit tricky to define what the currently operating version is. E.g. what if you're running envd at `v0.X.*` and then run the upgrade checker at `v0.X+1.*`, and then immediately run the upgrade checker again at `v0.X+2.*`. The first should be allowed but the second shouldn't be, even though what it would see as the latest version of state written is `v0.X+1.*`.

**Comment by jkosh44** [comment]
I updated the issue description to be more generic over the entire catalog debug tool. One of the catalog debug tool's features is the upgrade checker, but this same "no fencing" mode will need to apply to all features.
