### ISSUE TITLE
Kafka sinks crash when run with more than 1 thread

### ISSUE THREAD

**Issue by ruchirK** [MaterializeInc/materialize#2469]
Each differential worker runs through the sink code (which explicitly throws a "topic already exists"

Also: why didn't the billing demo fail on this?

**Comment by ruchirK** [comment]
In kafka sources it looks like we designate one worker to be the kafka reader, and all others don't do anything. I guess this means we should do something similar on kafka sinks?

**Comment by benesch** [comment]
Yep, definitely.

**Comment by ruchirK** [comment]
I'm not totally sure how to implement this - my current understanding is that I need to add a Exchange channel before the sink where everything maps to the same u64, but its not clear how to make everything map to the right worker (unclear if thats as simple as mapping every value to one worker id), and we can select the appropriate worker by hashing the sink id and taking the value modulo the number of workers?

Does that sound roughly right? I can whip it up and test it rn

**Comment by frankmcsherry** [comment]
That sounds right. You don't need to do the modulo though (timely will map any `u64` to a consistent worker, and it happens to be mod #workers at the moment). You can either do this with an exchange channel for the sink operator, or with an `exchange` operator before the sink channel (and then a pipeline channel coming in). The former is a bit better than the latter.

**Comment by frankmcsherry** [comment]
E.g, where the code in master currently does
```rust
            stream.sink(Pipeline, &format!("kafka-{}", id), move |input| {
```
you might instead do
```
            stream.sink(Exchange::new(|_| id.convert_to_u64_somehow()), &format!("kafka-{}", id), move |input| {
```
