### ISSUE TITLE
blue-green: Fail swapping schema or clusters if they contain a source

### ISSUE THREAD

**Issue by ParkMyCar** [MaterializeInc/materialize#24690]
### Feature request

If a user tries to run `ALTER [ SCHEMA | CLUSTER ] SWAP ...` and one of the specified objects contain a source, we should fail the command.

**Comment by benesch** [comment]
Wait, why? What goes wrong if you swap a schema containing a source or a sink?

**Comment by benesch** [comment]
Mentioned this in a live meeting or two and on Slack, but I'll mention it here for posterity to: I don't think we should do this! Brief excerpt of the rationale from [this Slack conversation](https://materializeinc.slack.com/archives/C05SLRXKNGN/p1706757140792239?thread_ts=1706729350.801729&cid=C05SLRXKNGN):

> * `ALTER SCHEMA … SWAP` is a thing that’s super easy to explain right now—it unconditionally swaps the names of two schemas. If it starts having opinions about what kinds of schemas it can swap, that makes it harder to explain. Principle of least surprise ’n all—it just _feels right_ to me that a command called “schema swap” wouldn’t care about the contents of those schemas.
> * I think it’s totally legit to swap schemas with sources using blue/green in two different ways:
>   *  Sources bundled with compute objects in the same schema. Should work fine if you’re comfortable rebuilding all your sources on each blue/green. One of our customers does this, and it works well. The only tricky bit is that using dbt to manage sources is fraught. So you need a deploy script that rebuilds sources using some non-dbt tool and then runs dbt. Harder than just running dbt, but not that much harder.
>  * Sources in their own schema (`s_schema`), depended on by views in another schema (`v_schema`). You can blue/green `s_schema`, resulting in `v_schema` pointing at `s_schema_old`. Then you can blue/green `v_schema` to point it at the new `s_schema`.
> (I realize that’s terse; happy to explain with more words and diagrams if it’s confusing.)

**Comment by morsapaes** [comment]
Porting this discussion to #25174. It's easier to be opinionated about what should and shouldn't be brought to the attention of users during a B/G deployment in dbt.

**Comment by benesch** [comment]
That sounds good to me. I'm going to close this as a wontfix and we can discuss the restrictions on sources as part of #25174. If someone feels strongly otherwise we can reopen!
