### ISSUE TITLE
storage/connections/kafka: add default `AWS PRIVATELINK` option

### ISSUE THREAD

**Issue by benesch** [MaterializeInc/materialize#24712]
### Feature request

When using AWS PrivateLink with Kafka today, you need to enumerate each broker in the cluster in the `BROKERS` list and attach an `AWS PRIVATELINK` clause to each:

```
CREATE CONNECTION kafka_connection TO KAFKA (
    BROKERS (
        'broker1:9092' USING AWS PRIVATELINK privatelink_svc,
        'broker2:9092' USING AWS PRIVATELINK privatelink_svc (PORT 9093)
    )
);
```

While verbose, this level of explicit configuration is required to support MSK via PrivateLink, where multiple brokers, each listening on port 9092 in the target VPC, are multiplexed via a single NLB via different ports (e.g., 9093, 9094, 9095...).

Redpanda Cloud has forthcoming native support for AWS PrivateLink. An exciting part of their implementation is that they handle the NLB multiplexing and advertised host rewriting on their side. The broker addresses that are advertised have a host/port that already points to the NLB. No rewriting required! (See caveat below though.)

We'll need syntax to indicate that communication with all brokers should be routed over AWS PrivateLink. I propose the introduction of a new top-level `AWS PRIVATELINK` option:

```
CREATE CONNECTION kafka_connection TO KAFKA (
    AWS PRIVATELINK privatelink_svc (PORT 30292)
);
```

This is analogous to the top-level `SSH TUNNEL` option we introduced in #18375. Note however that a top-level `AWS PRIVATELINK` option is mutually exclusive with specifying `BROKERS`. In top-level `AWS PRIVATELINK` mode, the DNS name of the VPC endpoint itself is used as the bootstrap server (possibly with an overridden port, as shown above).

There's a caveat, though. The addresses advertised by the Redpanda cluster will only resolve to the NLB in the Materialize VPC _if_ we enable private DNS for the VPC endpoint. This is dangerous for us, though, because we have multiple different customers all in the same VPC! It's possible for two VPC endpoint services to declare the same private DNS name... and then it's not possible to create endpoints for those services in the same VPC, as they'll stomp all over each others DNS names. We really want to scope the PrivateLink DNS for a given Kafka connection to only the sources and sinks that use that connection.

I think the solution is straightforward. When a top-level `AWS PRIVATELINK` connection is in use, Materialize will:

  * Set `bootstrap.servers` to `connection-<ID>:<PORT:9092>` —i.e., the address of the NLB, using the port indicated in `CREATE SOURCE`, or `9092` if unspecified.
  * Rewrite the hostnames of _all_ advertised brokers to `connection-<ID>`, but leave their ports untouched.

**Comment by benesch** [comment]
Had a really good conversation with @jubrad just now about the finer points of how this works. I've updated the issue description with our new understanding. The plan seems quite straightforward.

**Comment by benesch** [comment]
Pointers for whoever implements this:

  * Kafka util
    * Adjust [`TunnelingClientContext::default_tunnel`](https://github.com/MaterializeInc/materialize/blob/9ffc531acfdd9bbd1a4b83db0ec88b0cae4447de/src/kafka-util/src/client.rs#L281) to be an enum of `None`, `Ssh(SshTunnelConfig)`, `StaticHost(String)`.
    * Adjust [`TunnelingClientContext::rewrite_broker_addr`](https://github.com/MaterializeInc/materialize/blob/9ffc531acfdd9bbd1a4b83db0ec88b0cae4447de/src/kafka-util/src/client.rs#L428) to handle `StaticHost` tunnels by rewriting the host to the static string, leaving the port untouched.
    * Adjust the rest of the `TunnelingClientContext` as necessary to support the above changes. E.g., `set_default_ssh_tunnel` should become `set_default_tunnel`.
  * Storage
    * Fill in the implementation of default AWS Privatelink tunnels [here](https://github.com/MaterializeInc/materialize/blob/9ffc531acfdd9bbd1a4b83db0ec88b0cae4447de/src/storage-types/src/connections.rs#L536-L538).
  * SQL parsing
    * Add a new `ConnectionAwsPrivateLink` variant to [`WithOptionValue`](https://github.com/MaterializeInc/materialize/blob/9ffc531acfdd9bbd1a4b83db0ec88b0cae4447de/src/sql-parser/src/ast/defs/statement.rs#L3137) that allows setting the `PORT`
    * Adjust parsing of the `AWS PRIVATELINK` option accordingly ([link](https://github.com/MaterializeInc/materialize/blob/9ffc531acfdd9bbd1a4b83db0ec88b0cae4447de/src/sql-parser/src/parser.rs#L2487-L2492))
  * SQL planning
    * Add a feature flag for default AWS PrivateLink tunnels.
    * Adjust [`ConnectionOptionExtracted::try_into_connection`](https://github.com/MaterializeInc/materialize/blob/9ffc531acfdd9bbd1a4b83db0ec88b0cae4447de/src/sql/src/plan/statement/ddl/connection.rs#L264) to create connections with `default_tunnel: Tunnel::AwsPrivatelink(...)` if `AWS PRIVATELINK` is specified at the top level
    * Check that `BROKER`/`BROKERS` and `AWS PRIVATELINK` are not both specified
  * Testing
    * Do some very basic testing of invalid configurations in [test_privatelink_connection.py](https://github.com/MaterializeInc/materialize/blob/main/test/cloudtest/test_privatelink_connection.py).
    * I don't think it's worth the trouble to do a proper end-to-end test in the database repo. Ideally we'd be able to do one in the cloud repository, but that might be hard to rig up (can we do it with MSK or do we need to use a Redpanda dedicated cluster?), so I'd be comfortable shipping this to private preview without having an automatic end-to-end test.

**Comment by jubrad** [comment]
@benesch this may be more consistent with postgres if we do the following syntax

```
CREATE CONNECTION kafka_connection TO KAFKA (
    AWS PRIVATELINK privatelink_svc, 
    PORT 30292,
    ...
);
```
It does untether it from the privatelink connection so I see some bennefits for the suggested implementation `AWS PRIVATELINK privatelink_svc (PORT <port>)`

It would simply the parsing quite a bit to have them be the same though.

**Comment by benesch** [comment]
Ah yeah, I'm totally comfortable with the complexity that the proposed syntax adds to the parser, since the end user syntax should be the overriding concern.

Philosophically (one such past discussion here: https://materializeinc.slack.com/archives/C063H5S7NKE/p1703010057276949?thread_ts=1703005698.609599&cid=C063H5S7NKE), the `CREATE CONNECTION` options should directly correspond to options in the official client library. The `PORT` in PostgreSQL refers to libpq's `port` option, for example. Similarly for `SSL MODE`. Since librdkafka doesn't have a `PORT` option, I'd like to avoid introducing one if possible. (We already messed up a little bit with `BROKERS` rather than `BOOTSTRAP SERVERS`, but we can at least avoid introducing further inconsistencies.)

`SSH TUNNEL` and `AWS PRIVATELINK` are, of course, deviations from the upstream libraries, which never support SSH tunnels or AWS PrivateLink directly—but hopefully understandable deviations! And once we're in the "context" of an `AWS PRIVATELINK` clause (i.e., `AWS PRIVATELINK (<custom options here>)`), we can invent whatever options we like.

I think there's an argument to be made in the _other_ direction, actually, which is that

```sql
CREATE CONNECTION ... TO POSTGRES (
    AWS PRIVATELINK plink,
    PORT 1234
);
```

should never have been allowed—we don't let you specify `HOST` if you specify `AWS PRIVATELINK`, after all!—and instead users should have to write:

```sql
CREATE CONNECTION ... TO POSTGRES (
    AWS PRIVATELINK plink (PORT 1234)
);
```

Like, conceptually, you should _either_ specify `HOST` and `PORT` for a direct PostgreSQL connection, _or_ `AWS PRIVATELINK` for a connection that's tunneled via `AWS PRIVATELINK`.

**Comment by jubrad** [comment]
Yeah that all seem pretty in line with how I've been writing/thinking about it, but wasn't sure if we'd want to avoid inconsistent syntax.  



> Like, conceptually, you should either specify HOST and PORT for a direct PostgreSQL connection, or AWS PRIVATELINK for a connection that's tunneled via AWS PrivateLink.

has the boat sailed here, or would we want to consider a follow up enforcing this?

**Comment by benesch** [comment]
> > Like, conceptually, you should either specify HOST and PORT for a direct PostgreSQL connection, or AWS PRIVATELINK for a connection that's tunneled via AWS PrivateLink.
> 
> has the boat sailed here, or would we want to consider a follow up enforcing this?

I definitely think we should consider it! #epd-sql-council is a good place to discuss.

**Comment by benesch** [comment]
One thing that I just realized is weird no matter what: CSR connections!

```sql
CREATE CONNECTION TO CONFLUENT SCHEMA REGISTRY (
    AWS PRIVATELINK CONNECTION plink,
    -- Should we reject these because the URL contains a port?
    URL 'https://foo-bar:1234',
)
```

**Comment by jubrad** [comment]
should we just prohibit specifying host/port in that case?

**Comment by benesch** [comment]
Calling this closed, as its shipped in PrPr! https://github.com/MaterializeInc/materialize/issues/25468 tracks promoting to PuPr!
