### ISSUE TITLE
mysql: unsupported type: enum

### ISSUE THREAD

**Issue by nrainer-materialize** [MaterializeInc/materialize#24732]
### What version of Materialize are you using?

9c3a455aa9

### What is the issue?

```
CREATE TABLE enum_type (f1 ENUM ('val1', 'val2'));
INSERT INTO enum_type VALUES ('val1'), ('val2');

CREATE SOURCE mz_source
  FROM MYSQL CONNECTION mysql_conn
  FOR ALL TABLES;
```
throws 
```
ERROR: MYSQL source validation: referenced tables use unsupported types
```

**Comment by rjobanp** [comment]
@morsapaes since Materialize itself does not have an `enum` type, I'm not sure if we should leave this as an open issue (it will never be possible to support natively). We now have support for handling these types via `TEXT COLUMNS` instead.
