### ISSUE TITLE
rustc on aarch64 segfaults sporadically

### ISSUE THREAD

**Issue by def-** [MaterializeInc/materialize#24818]
### What version of Materialize are you using?

main

### What is the issue?

For example in https://buildkite.com/materialize/tests/builds/74326#018d5a18-6082-43ce-88a2-d7a70b919a87

See discussion in https://materializeinc.slack.com/archives/C01LKF361MZ/p1706285774937819

Issue in rust: https://github.com/rust-lang/rust/issues/120511

**Comment by nrainer-materialize** [comment]
Further occurrence: https://buildkite.com/materialize/tests/builds/75970#018db23a-3ec1-48ba-89fb-b8adc0af64a2****
