### ISSUE TITLE
persist: FY25 Q1 planning

### ISSUE THREAD

**Issue by bkirwi** [MaterializeInc/materialize#24829]
Previously #22470

* [prod] => stability/introspection
* [req] => requests from other teams/product for new behavior
* [bug] => incorrect behavior

# Bugs
```[tasklist]
### Bugs
- [ ] https://github.com/MaterializeInc/materialize/issues/25533
- [ ] https://github.com/MaterializeInc/cloud/issues/8791
- [ ] https://github.com/MaterializeInc/cloud/issues/6705
- [ ] consensus_scan traffic when an MV input is stuck [context](https://materializeinc.slack.com/archives/C01CFKM1QRF/p1703156679083869)
- [x] └ https://github.com/MaterializeInc/materialize/pull/24985
- [ ] └ Turn on new LD config tuning in staging
- [ ] └ Turn on new LD config tuning in prod
- [ ] webhook source at 10QPS uses a surprising amount of CPU in persist [context](https://materializeinc.slack.com/archives/C04DJT084KA/p1706672394431319)
- [ ] https://github.com/MaterializeInc/materialize/issues/24994
- [ ] https://github.com/MaterializeInc/materialize/issues/26145
- [ ] https://github.com/MaterializeInc/materialize/issues/25015
- [ ] https://github.com/MaterializeInc/materialize/pull/25016
- [ ] https://github.com/MaterializeInc/materialize/issues/25460
- [ ] https://github.com/MaterializeInc/materialize/issues/25776
- [x] second dyncfg for persist_source backpressure in cc replicas so we can migrate customers off of it
- [ ] https://github.com/MaterializeInc/materialize/issues/26384
```

# Now: FY25 Q1

```[tasklist]
### Now: FY25 Q1
- [ ] #24498
- [ ] #16625
- [ ] https://github.com/MaterializeInc/materialize/issues/24830
- [ ] https://github.com/MaterializeInc/materialize/issues/24831
- [ ] https://github.com/MaterializeInc/materialize/issues/24832
- [ ] https://github.com/MaterializeInc/materialize/issues/16607
- [ ] https://github.com/MaterializeInc/materialize/issues/25448
```

# Next: FY25 Q2 (unordered)

- [prod] Turn on CRDB changefeeds -> s3 for all prod environments
- [epic] Actually delete and cleanup data
    - Turn #17292 on in prod
    - https://github.com/MaterializeInc/materialize/issues/17322
- [epic] Refactoring to support transferring ownership of `persist_source`'s `decode_and_mfp` operator and `persist_sink`'s correction buffer operator to compute
- https://github.com/MaterializeInc/materialize/issues/23942
- https://github.com/MaterializeInc/materialize/issues/16858
- [epic] Bounding state size (two-level lookup)
- [epic] #25901
- https://github.com/MaterializeInc/materialize/issues/15209
    - Readers could either use ben's 🤯 idea or frank's "extreme" version
- [req] #20618
    - This does seem to be coming up again recently, maybe projection pushdown related
- [req] Make tombstones cheap enough to support 1MM+ temporary shards in an environment
- [req] Compute storage usage incrementally and store diffs inline in `StateDiff`, enabling "free" continuous tracking
- https://github.com/MaterializeInc/materialize/issues/26545

# Later: FY25 Q3+ (epics first, otherwise not ordered)

- [epic] #25891
- [epic] https://github.com/MaterializeInc/materialize/issues/19322
- [epic] Throughput tuning
    - #15518
    - Update open_loop benchmark to stress sharded reads and writes
    - #18066
- [epic] Indexed lookup
- [epic] #17492
- [epic] #13918
- [req] #24342
- [req] #17206
    - Might be related to PARTITION BY
- [req] #26313
- [pushdown] Wire up stats to a system var (and add extra budget for large parts)
    - Feels bad to keep 1kb of stats for a 5kb part, also feels back to use the same stats cutoff for 128MiB part
    - Existing tuning is already butting up against state sizes before we have two level state
- [prod] on-disk blob cache
- [prod] #19608
- [prod] #13961
    - We have a limit in the call. Maybe some codepaths are still setting a usize::MAX limit
    - Haven’t seen this be an issue in practice recently, but still a footgun
- [prod] Petros's idea to have a sharded exchangeable description of assigned compaction work
- [prod] Take advantage of S3 Express One Zone
- Split mz_persist_client::internal into mz_persist

**Comment by danhhz** [comment]
Closing in favor of #24829
