### ISSUE TITLE
Efficiently rewrite timestamps of data staged in s3

### ISSUE THREAD

**Issue by bkirwi** [MaterializeInc/materialize#24831]
When writing to shards from multiple processes - as we expect to do more with the Persist-backed catalog and transaction system - it will be more common for compare-and-append requests to fail. We'll need a cheap way to re-issue those requests with the same data... but with timestamps advanced so they're past the previous upper.

## Action log

* *7 March 2024.* Slip expected release date to Mar 29 with medium confidence, due to prioritizing persist-txn=lazy release ahead of this work.
* *15 February 2024.* Slip expected release date to Mar 15 with medium confidence, due to prioritizing https://github.com/MaterializeInc/materialize/issues/23332 ahead of this work.
* *30 January 2024.* File issue with an expected release date of Mar 1 with medium confidence.

**Comment by danhhz** [comment]
Okay this will go out in the v0.94.x release cut on Thursday. Because of persist forward compatibility, we can't use it until after that branch splits off from main: i.e we can start merging PRs to use this Thursday afternoon. I'll track that work as part of Pv2.
