### ISSUE TITLE
SSH Postgres connections fail

### ISSUE THREAD

**Issue by def-** [MaterializeInc/materialize#24864]
### What version of Materialize are you using?

832c0c97a497

### What is the issue?

* https://buildkite.com/materialize/tests/builds/74494#018d60c1-c33f-4c9b-9846-284bd0c2b6c3
* https://buildkite.com/materialize/tests/builds/74501#018d60ec-9ddf-447d-9f2e-9f904054f607

```
39:1: error: executing query failed: db error: ERROR: failed to connect to PostgreSQL database
DETAIL: connection closed: ERROR: failed to connect to PostgreSQL database
DETAIL: connection closed
     |
  18 | > CREATE SECRET pgpa ... [rest of line truncated for security]
  24 |   PASSWORD SECRET pg ... [rest of line truncated for security]
  28 | $ postgres-execute c ... [rest of line truncated for security]
  38 | 
  39 | > CREATE SOURCE mz_source_ssh1
     | ^
```

This started immediately after https://github.com/MaterializeInc/materialize/pull/24784 was merged

**Comment by petrosagg** [comment]
Removing the release blocker tag since the offending PR was reverted here https://github.com/MaterializeInc/materialize/pull/24865

**Comment by benesch** [comment]
Should be fixed by https://github.com/MaterializeInc/materialize/pull/24919.
