### ISSUE TITLE
Support parameters in LIMIT clause

### ISSUE THREAD

**Issue by chuck-alt-delete** [MaterializeInc/materialize#24893]
### Feature request

Example:
```sql
PREPARE foo AS SELECT generate_series(1, 10) LIMIT $1;
EXECUTE foo (7);
```
```
Error: Top-level LIMIT must be a constant expression
```
I ran this in the production demos account where `enable_expressions_in_limit_syntax` is true.

A user also hit this when running a parameterized query from a dotnet library for postgres:
```
LIMIT @__p_1
```

Related:
- #7071 
- https://github.com/MaterializeInc/materialize/pull/23276

**Comment by benesch** [comment]
Looping in @chaas. I think we'll be able to find a workaround for the user who ran into this today, but I nonetheless wanted to throw it on your radar, @chaas! I think it would be a pretty straightforward fix. Just missing a call to `bind_parameters` somewhere.

**Comment by benesch** [comment]
Yeah, `bigint` is the right type. The problem you're running into is that we don't apply the same implicit casts that PostgreSQL does when the value of the parameter supplied in `EXECUTE` does not exactly match the type parameter. https://github.com/MaterializeInc/materialize/issues/21072 is the tracking issue for fixing that. It affects all parameters, not just those in `LIMIT` expressions.
