### ISSUE TITLE
webhooks: Support JSON line batching

### ISSUE THREAD

**Issue by ParkMyCar** [MaterializeInc/materialize#24913]
### Feature request

At least one user has asked to support batching JSON requests by [JSON lines](https://jsonlines.org/). What this probably looks like is `BODY FORMAT TEXT` (since JSON is valid UTF-8) and then support for `TRANSFORM USING` so we can expand the lines into rows before passing them onto Persist.

If this is popular enough, an alternative approach is `BODY FORMAT JSON LINES`

**Comment by benesch** [comment]
> an alternative approach is `BODY FORMAT JSON LINES`

Possibly spelled `BODY FORMAT NDJSON`: https://ndjson.org/home/
