### ISSUE TITLE
storage/sources/mysql: report statistics

### ISSUE THREAD

**Issue by morsapaes** [MaterializeInc/materialize#24942]
### Feature request

Related to #23154, [Console #1533](https://github.com/MaterializeInc/console/issues/1533).

The MySQL source should report statistics in [`mz_source_statistics`](https://materialize.com/docs/sql/system-catalog/mz_internal/#mz_source_statistics). Implementation details are laid out in the [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/20240108_source_metrics_2.md#mysql-frontier-aggregation) for source progress metrics, and stubbed in #24889.

cc @rjobanp @guswynn

**Comment by benesch** [comment]
@morsapaes I kicked this one out of the storage team board since AIUI it's linked into the MySQL source epic in the right place, but it's not actively being worked on.

**Comment by morsapaes** [comment]
From [this thread](https://materializeinc.slack.com/archives/C069K7ZUKS9/p1706886558152249?thread_ts=1706884975.143029&cid=C069K7ZUKS9), it was unclear to me if Gus was going to work on it soon, or if this would be kicked down the road. Added to the project for discussion, but sounds like I'm holding the process wrong!

**Comment by benesch** [comment]
Ah! My hope was that the "triage" queue would be something very transient—mostly there for folks outside the storage team who wanted us to look at an issue they filed, or a place for someone on the storage team to toss an issue if they were in a rush. Should we add a "needs discussion" queue for stuff that can't be insta-triaged?

(In this case, though, it seems like you and @rjobanp should just decide whether this is a private preview or public preview blocker for MySQL, and sort it into the MySQL epic appropriately?)

**Comment by morsapaes** [comment]
It's been sorted into the epic already! No need to overcomplicate the process, otherwise.

**Comment by guswynn** [comment]
I will be working on this soon, but I don't think it should be a blocker for private or public preview, depending on timing. I don't think it will come to that though!

**Comment by guswynn** [comment]
Oh @morsapaes this was done during the rest of the statistics work!
