### ISSUE TITLE
github-21031.td: Missing row in subscribe

### ISSUE THREAD

**Issue by def-** [MaterializeInc/materialize#24981]
### What version of Materialize are you using?

3eda008d0a

### What is the issue?

Seen in https://buildkite.com/materialize/nightlies/builds/6316#018d7940-6a1d-4c70-aaae-4448c86ea803:
```
2024-02-05 14:14:01 UTC	github-21031.td:29:1: error: non-matching rows: expected:
2024-02-05 14:14:01 UTC	[["<TIMESTAMP>", "1", "1"]]
2024-02-05 14:14:01 UTC	got:
2024-02-05 14:14:01 UTC	[]
2024-02-05 14:14:01 UTC	Poor diff:
2024-02-05 14:14:01 UTC	- <TIMESTAMP> 1 1
2024-02-05 14:14:01 UTC	
2024-02-05 14:14:01 UTC	     |
2024-02-05 14:14:01 UTC	  28 | > DECLARE c CURSOR FOR SUBSCRIBE mv
2024-02-05 14:14:01 UTC	  29 | > FETCH c
2024-02-05 14:14:01 UTC	     | ^
```
I'm not sure if this is a test issue, but since the MV is a simple `select 1`, I'm wondering how the row can be missing? It happened with 4 replicas (running on the same system), so maybe the system is overloaded? But should it fail in this way then?

Second occurrence in https://buildkite.com/materialize/nightlies/builds/6299#018d6c62-3773-42a6-92db-0b806330e6d2

ci-regexp: github-21031.td:29:1: error: non-matching rows: expected:

**Comment by def-** [comment]
@teskje Can you please check if this is just a test issue? It also failed in a test run for 0.86.1: https://buildkite.com/materialize/nightlies/builds/6326#018d7b71-c080-47ec-afe4-db4e1c9b340f

**Comment by teskje** [comment]
This appears to be an issue with replica-targeted queries. It can be somewhat reliably reproduced with this testdrive, when run with `--replicas=4`.

```
> SET cluster_replica = r1

$ set-regex match=\d{13,20} replacement=<TIMESTAMP>

> CREATE MATERIALIZED VIEW mv AS SELECT 1 AS a

> BEGIN
> DECLARE c CURSOR FOR SUBSCRIBE mv
> FETCH c
<TIMESTAMP> 1 1
> COMMIT

> BEGIN
> DECLARE c CURSOR FOR SUBSCRIBE mv
> FETCH c
<TIMESTAMP> 1 1
> COMMIT

> BEGIN
> DECLARE c CURSOR FOR SUBSCRIBE mv
> FETCH c
<TIMESTAMP> 1 1
> COMMIT

> BEGIN
> DECLARE c CURSOR FOR SUBSCRIBE mv
> FETCH c
<TIMESTAMP> 1 1
> COMMIT

> BEGIN
> DECLARE c CURSOR FOR SUBSCRIBE mv
> FETCH c
<TIMESTAMP> 1 1
> COMMIT

> BEGIN
> DECLARE c CURSOR FOR SUBSCRIBE mv
> FETCH c
<TIMESTAMP> 1 1
> COMMIT
```

**Comment by teskje** [comment]
Bisection says that the issue was introduced in #24487. It does not occur when disabling aggressive read hold downgrades through the feature flag (`enable_compute_aggressive_readhold_downgrades`).
