### ISSUE TITLE
surfaces/integrations: test MySQL source with managed services

### ISSUE THREAD

**Issue by morsapaes** [MaterializeInc/materialize#24999]
Before we release the new MySQL source into Private Preview, we'd like to ensure that users are able to connect via common MySQL managed services. We should test the source against:

- [x] [AWS RDS for MySQL](https://aws.amazon.com/rds/mysql/)
- [x] [AWS Aurora for MySQL](https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/Aurora.AuroraMySQL.html)
- [x] [CloudSQL for MySQL](https://cloud.google.com/sql/docs/mysql)
- [x] [Azure DB for MySQL](https://azure.microsoft.com/en-us/products/mysql)

Let's assume we're connecting to these over the public internet, or using static IP addresses (later on, we'll be able to test connecting over SSH and PrivateLink). Needless to ask because @bobbyiliev, but: if we could keep detailed notes that can serve as a base to integrations guides, it'd be 👨‍🍳 💋 .

cc @chaas for awareness and prioritization.

**Comment by morsapaes** [comment]
@bobbyiliev, in addition to basic replication tests, you can use [this doc](https://docs.google.com/spreadsheets/d/1BgEY_ZXIU14aMCC35hTdzQwRp1ETGViZE1B1uKyGIQE/edit?usp=sharing) as guidance to try out a couple of different topologies. It'd be neat to test this out with both MySQL 5.7 and 8+, since we expect some users to still be on the older version.

**Comment by bobbyiliev** [comment]
Just finished testing Aurora MySQL and it also works as expected. Still need to test out Aurora Serverless, but pretty sure that it will not work.

I’ve updated the notion doc to include that guide as well right below the RDS one.

**Comment by bobbyiliev** [comment]
CloudSQL works as expected! Documented [here](https://www.notion.so/materialize/CloudSQL-for-MySQL-e379e71a2385469c87cdcf4e8ab700df)

Azure DB for MySQL also works well! I've documented it [here](https://www.notion.so/materialize/Azure-DB-for-MySQL-d63fcd1c065341dbafa5b4fac922036b) and also prepared a [terraform module](https://github.com/MaterializeInc/terraform-azurerm-mysql-server) for creating a basic dev instance.

**Comment by morsapaes** [comment]
Thanks, @bobbyiliev! Closing. The next step is to add documentation guides (#24915).
