### ISSUE TITLE
mz_line_no is confusing for csv with headers

### ISSUE THREAD

**Issue by benesch** [MaterializeInc/materialize#2502]
Tracking the line number for CSVs with headers is pretty confusing, because the first record is on line 2. Feels like `mz_record_no` might be a better fit.

/cc @sploiselle @umanwizard

**Comment by wangandi** [comment]
Ignore the mention. Entered the wrong issue number.

**Comment by umanwizard** [comment]
@sploiselle what do you think?

**Comment by sploiselle** [comment]
I like there being some kind of expression that we did in fact process the first line and acknowledge that we're not treating it as data. This is also a "canary" in the sense that if someone creates a source with a header by mistake, the missing first line gives them a chance to understand what happened.

I think that `csv_line_no` might more clearly explain what happened while preserving whatever kind of semantic handle this provides (`SELECT * FROM csv ORDER BY csv_line_no DESC`), but realize this breaks the apparent naming convention of "things we create for you begin with `mz`.

That all being said, if it were `mz_record_no`, I don't think most people would be upset, concerned, or confused.

**Comment by morsapaes** [comment]
Closing as stale, since we no longer support file sources.
