### ISSUE TITLE
surfaces/integrations/cube: add `cluster` as a connection configuration parameter

### ISSUE THREAD

**Issue by morsapaes** [MaterializeInc/materialize#25060]
### Feature request

Our [Cube driver](https://github.com/cube-js/cube/tree/master/packages/cubejs-materialize-driver) doesn't allow specifying `cluster` as a connection configuration parameter. This can have surprising consequences to users, since the driver will just silently use whatever the default cluster is for the role used to connect.

Looking through the code, the driver seems pretty outdated. In addition to adding the new config, we should:

* Set SSL to `true` by default.
* Remove dead code used to connect to Materialize <`v0.27`

We'll need to patch both the [integration guide](https://materialize.com/docs/integrations/cube/) and the [Cube docs](https://cube.dev/docs/product/configuration/data-sources/materialize) once a new version is rolled out.

**Comment by morsapaes** [comment]
[A user](https://materializeinc.slack.com/archives/C06CVUS95SL/p1707863269906489?thread_ts=1707858149.880559&cid=C06CVUS95SL) also noted that the connector isn't sending the `application_name`, which makes it hard to identify queries that are emitted by Cube in the statement log.

**Comment by bobbyiliev** [comment]
The Cube.js PR has been merged and the docs have been updated https://github.com/MaterializeInc/materialize/pull/25590
