### ISSUE TITLE
Error message for trying to use `float` in `round` is confusing.

### ISSUE THREAD

**Issue by umanwizard** [MaterializeInc/materialize#2508]
`round(MAX(avg_call_duration),2)` produces error message `first round argument has non-integer type Float64` -- in reality, the input can be a decimal, not only an integer.

**Comment by benesch** [comment]
This got fixed with Sean's function generalization work. The error message isn't as helpful as it could possibly be, but it's no longer wrong, at least:

```
materialize=> select round(1.03::float, 2);
ERROR:  Cannot call function round(f64, i32): arguments cannot be implicitly cast to any implementation's parameters; try providing explicit casts
````
