### ISSUE TITLE
`has_table_privilege` on internal system tables fails when schema/database is not set

### ISSUE THREAD

**Issue by SangJunBak** [MaterializeInc/materialize#25080]
### What version of Materialize are you using?

v0.86.1

### What you expect to happen

`select has_table_privilege('mz_internal.mz_activity_log', 'select');` returns a result:
<img width="1180" alt="Screenshot 2024-02-08 at 11 47 47 AM" src="https://github.com/MaterializeInc/materialize/assets/29664023/41dfa912-a61a-4391-a2dd-429af51a56c8">

### What actually happens
<img width="1228" alt="Screenshot 2024-02-08 at 11 48 17 AM" src="https://github.com/MaterializeInc/materialize/assets/29664023/217c287c-9f7b-4a94-8600-7b4db3d4343a">

### Steps to reproduce:
1. Set your schema and database to falsy values like `null` 
2. Run `select has_table_privilege('mz_internal.mz_activity_log', 'select');`

**Comment by jkosh44** [comment]
The error here isn't in `has_table_privilege` directly, it's in the cast from `text` to `regclass` which `has_table_privilege` uses in it's implementation.

A more targeted reproduction is as follows:

1. `SET database TO '';`
2. `SELECT 'mz_internal.mz_activity_log'::regclass;`

![Screenshot from 2024-02-08 11-53-38](https://github.com/MaterializeInc/materialize/assets/10800303/8c369874-ab60-4745-a236-ce7be6383f80)

**Comment by jkosh44** [comment]
The `search_path` (A.K.A. active schema) is not related to this issue.

 
![Screenshot from 2024-02-14 16-07-26](https://github.com/MaterializeInc/materialize/assets/10800303/eda21c24-f666-4f08-bfad-aee577fe2a8c)
