### ISSUE TITLE
Feature benchmark on main compares against itself

### ISSUE THREAD

**Issue by def-** [MaterializeInc/materialize#25099]
### What version of Materialize are you using?

main

### What is the issue?

Number of messages regressed in https://buildkite.com/materialize/nightlies/builds/6348#018d84d6-d8b4-4b9e-97f7-05d77681835f vs https://buildkite.com/materialize/nightlies/builds/6344#018d838f-95d2-4d22-aaa7-7d2993b7cc23, but feature benchmark on main found nothing.

It seems to be using the exact same tag for materialized container for this and other. There should be an assertion in feature benchmark to prevent that and we have to change the logic to choose the last released version to compare against.

**Comment by nrainer-materialize** [comment]
Failure on release branch: https://buildkite.com/materialize/nightlies/builds/6363

**Comment by nrainer-materialize** [comment]
From https://buildkite.com/materialize/nightlies/builds/6344#018d838f-95d2-4d22-aaa7-7d2993b7cc23:

The context is clearly not correct:
```
_bk;t=1707310722672Using devel-e462fbf55c0e7a5ee8ebbd13715f3ec4f3765382 as image tag for ancestor (context: merge base of local non-main branch)
```
