### ISSUE TITLE
Use Postgres type names instead of Rust ones whenever externally visible

### ISSUE THREAD

**Issue by umanwizard** [MaterializeInc/materialize#2509]
E.g.: https://kotiri.com/2018/01/31/postgresql-diesel-rust-types.html

**Comment by benesch** [comment]
For whoever implements this: we already maintain this mapping in Materialize: https://github.com/MaterializeInc/materialize/blob/master/src/pgrepr/src/types.rs

**Comment by benesch** [comment]
One specific example from #2823:

```
materialize=> create materialized view test2 as select 1.23::real;
CREATE VIEW
materialize=> show columns from test2;
 Field | Nullable |  Type  
-------+----------+--------
 ?     | YES      | float8
(1 row)
```
