### ISSUE TITLE
Redesign col_names option for CSV sources 

### ISSUE THREAD

**Issue by benesch** [MaterializeInc/materialize#2510]
CSV sources permit a `col_names` option that I think needs to be redesigned.

There are a few issues I spotted:
  * `WITH` options logically apply to the connector (in this case the file connector), not the format. We shouldn't have `WITH` options that apply to only one format.
  * Identifiers should never appear within strings, per SQL syntax conventions.

There is prior art for this, in that view definitions can also rename columns:

```sql
CREATE VIEW v (renamed) AS SELECT 1 AS ignored;
```

We should adopt the same convention for sources:

```sql
CREATE SOURCE s (renamed)
FROM FILE 'blah.csv'
FORMAT CSV WITH HEADER
```

/cc @sploiselle

**Comment by sploiselle** [comment]
@benesch Yeah, it felt odd that the `WITH` options applied to the connector and not the format and I broke that boundary. Do we envision ever adding extensibility for formats, though?

The matter at hand, though: the idea was to allow users to rename columns within the source for CSVs, not to rename the source itself. What do you think of something like

```
CREATE SOURCE s
FROM FILE 'blah.csv'
FORMAT CSV WITH 3 COLUMNS (foo, bar, baz)
```

There doesn't seem like an attractive way to express naming columns with a header, so maybe that just dies on the cutting room floor?

**Comment by benesch** [comment]
> There doesn't seem like an attractive way to express naming columns with a header, so maybe that just dies on the cutting room floor?

It actually seems pretty useful to be able to say "yes, there's a header that should not be included in the data, but I want to use these columns instead."

> The matter at hand, though: the idea was to allow users to rename columns within the source for CSVs, not to rename the source itself.

That is what that syntax does? Arguably a bit confusing, but it's consistent with SQL. So for example to ignore the header column names and use "foo", "bar", "baz" instead:

```sql
CREATE SOURCE s (foo, bar, baz)
FROM FILE 'blah.csv'
FORMAT CSV WITH HEADER
```

**Comment by sploiselle** [comment]
Sorry--my misread of that syntax. Will get that patch up in a bit.

**Comment by benesch** [comment]
Sweet, no rush! Also heads up I'm moving the CSV tests over to testdrive, so that might interfere with your work. That patch should be out shortly though.
