### ISSUE TITLE
doc/user: Fivetran integration guides

### ISSUE THREAD

**Issue by morsapaes** [MaterializeInc/materialize#25143]
### Documentation request

Add new integration guide for Fivetran under `Ingest data`. This section is getting unwieldy, so keeping a note to self to think about how we can improve it.

Once we have a guide shaped up, we'll need to rehash it also for the Fivetran documentation (see [pointers from their team](https://materializeinc.slack.com/archives/C060KAR4802/p1705996849833019)).

**Comment by ParkMyCar** [comment]
Note: Fivetran also requested some docs for their end, [Slack](https://materializeinc.slack.com/archives/C060KAR4802/p1705996849833019). Do you think we should spin out a separate issue for this? Seems like the content would be pretty similar

**Comment by morsapaes** [comment]
We should be able to spin one out of the other easily, so no need for a separate issue!
