### ISSUE TITLE
OoM in clusterd with many indexes (in "product limits")

### ISSUE THREAD

**Issue by def-** [MaterializeInc/materialize#25153]
### What version of Materialize are you using?

main

### What is the issue?

```
bin/mzcompose --find limits down && bin/mzcompose --find limits run default --scenario=Indexes
```
Seen in https://buildkite.com/materialize/nightlies/builds/6396#018d938b-d51d-4649-9dbf-552543afc093 with heap profiles. I used https://github.com/MaterializeInc/materialize/pull/24731 to looked into what clusterds were allocating just before the OoM and 4 of them (clusterd_1_1, clusterd_1_2, clusterd_2_1, clusterd_2_2) have > 2 GB each allocated in TraceWriter::exert.
![profile001](https://github.com/MaterializeInc/materialize/assets/2335377/cee2b281-07b5-4787-81e1-29bb0b93d86e)
Is this expected? (All 4 doing the same is expected since they are replicas for the quickstart cluster I guess). We are seeing OoMs in this test regularly now.
What the test does is create lots of indexes:

https://github.com/MaterializeInc/materialize/blob/1b1f5c59dadc5a560b451a1d4c0c4c984de136d6/test/limits/mzcompose.py#L142-L156

**Comment by teskje** [comment]
What the test is doing is:

* Create a single table `t` with 1000 `INTEGER` columns.
* Insert a single row into `t`.
* Create 1000 indexes on `t`, one for each column.

According to `mz_dataflow_arrangement_sizes`, each index ends up with the following sizes:

```
 id  |               name                | records | batches | size | capacity | allocations
-----+-----------------------------------+---------+---------+------+----------+-------------
 6   | Dataflow: materialize.public.i1   |       1 |       8 | 2977 |  4195240 |          13
```

* The `size` sums up to `2977 * 1000 ~ 2.8MiB`
* The `capacity` sums up to `4195240 * 1000 ~ 3.9GiB`

On my machine, `docker container stats` says that the `clusterd`s use ~2.6GiB of memory, which is something between the two but way larger than the `size`.

I don't know enough about arrangements to say what's expected and what isn't, but the discrepancy between `size` and `capacity` seems notable. @antiguru is it something to worry about?

**Comment by antiguru** [comment]
We should look into https://github.com/MaterializeInc/materialize/pull/24330 whether it causes this, or some of the preceding PRs.

**Comment by def-** [comment]
I tried reverting #24330 in https://github.com/MaterializeInc/materialize/pull/25201 and it seems to use about half the memory: 
[clusterd_1_1-2024-02-13_19 16 58.pb.gz](https://github.com/MaterializeInc/materialize/files/14273024/clusterd_1_1-2024-02-13_19.16.58.pb.gz)
![profile001](https://github.com/MaterializeInc/materialize/assets/2335377/5aef10f6-a385-4c51-a84c-9770751ab8b8)

**Comment by teskje** [comment]
I assume the heap profiles only report virtual memory, so they are not entirely reliable. Increased usage of virtual memory is expected with #24330, but that won't lead to OOMs if it doesn't also cause increased physical memory usage.

To find out the effects on physical memory usage I ran the limits test locally again, this time with #24330 reverted (using https://github.com/MaterializeInc/materialize/pull/25226). Note that this is all in debug mode, so we can expect to be wasting a lot of memory. Looking at diffs should still be meaningful.

Arrangement sizes:
```
 id  |               name                | records | batches | size | capacity | allocations
-----+-----------------------------------+---------+---------+------+----------+-------------
 6   | Dataflow: materialize.public.i1   |       1 |       8 | 3537 |     5040 |          29
```

Final memory usage according to `docker container stats`:

```
CONTAINER ID   NAME                       CPU %     MEM USAGE / LIMIT     MEM %     NET I/O           BLOCK I/O     PIDS
940adae71576   limits-clusterd_1_1-1      0.06%     1007MiB / 31.29GiB    3.14%     1.67GB / 1.92GB   0B / 0B          40
274e3a160ee5   limits-clusterd_1_2-1      0.05%     1.207GiB / 31.29GiB   3.86%     1.9GB / 1.59GB    0B / 0B          40
989ac3eb975e   limits-clusterd_2_1-1      0.07%     1008MiB / 31.29GiB    3.15%     1.67GB / 1.92GB   0B / 0B          44
d0e146610d2a   limits-clusterd_2_2-1      0.02%     1.205GiB / 31.29GiB   3.85%     1.9GB / 1.59GB    0B / 0B          44
```

And this is the final memory usage on main, without the revert applied:

```
1157432e751f   limits-clusterd_1_1-1      0.04%     2.245GiB / 31.29GiB   7.18%     2.06GB / 2.28GB   0B / 0B       40
f752f9d6d66f   limits-clusterd_1_2-1      0.06%     2.419GiB / 31.29GiB   7.73%     2.24GB / 1.99GB   0B / 0B       40
3601c83add29   limits-clusterd_2_1-1      0.04%     2.279GiB / 31.29GiB   7.28%     2.08GB / 2.29GB   0B / 0B       44
1eada9c3c2f2   limits-clusterd_2_2-1      0.03%     2.452GiB / 31.29GiB   7.84%     2.25GB / 2.01GB   0B / 0B       44
```
