### ISSUE TITLE
TAIL ad hoc SELECT queries

### ISSUE THREAD

**Issue by rjnn** [MaterializeInc/materialize#2519]
TAIL currently is only possible on materialized views. A prospect asks if we could add support for TAILing ad hoc SELECT queries.

**Comment by frankmcsherry** [comment]
Operationally not hard.

The question that will arise is "from what timestamp should we tail"? It's totally sane to do the same thing as a SINK, which will be to start from time zero, but probably we should collect a lot of these constraints together and figure out what would unify up a bunch of the desires.

**Comment by benesch** [comment]
Can you say more about the use case? The obvious workaround is:

```sql
CREATE MATERIALIZED VIEW temp_13241351325 AS SELECT ...;
TAIL temp_13241351325;
```

There's the obvious ergonomic pain, but the more pressing issue is that you might forget to `DROP VIEW temp_13241351325`.

We could solve that with session-temporary materialized views, though:

```
CREATE TEMPORARY MATERIALIZED VIEW temp_13241351325 AS SELECT ...;
TAIL temp_13241351325;
```

I think we've had another request for temporary views, so could potentially knock out two birds with one stone here.

**Comment by frankmcsherry** [comment]
I should have a PR for this coming up in just a second. `cargo check` is taking forever downloading new crates.

**Comment by frankmcsherry** [comment]
So, "not hard" but at the moment it is not possible to tail out updates at time zero, because TAIL uses strict inequality against a non-optional timestamp. Probably best to put all the constraints in a pile and figure out what we really need (strict inequality probably isn't a hard constraint).
