### ISSUE TITLE
Confusing info log output when creating a sink

### ISSUE THREAD

**Issue by ruchirK** [MaterializeInc/materialize#2522]
When a user creates a sink they see a sequence of create / drop / create in the info log such as:

```
Apr 01 22:39:57.392  INFO catalog: create sink materialize.public.billing_sink (u21)
Apr 01 22:39:57.862  INFO catalog: drop sink materialize.public.billing_sink (u21)
Apr 01 22:39:57.862  INFO catalog: create sink materialize.public.billing_sink (u21)
```

and it's possible that this may confuse anyone who plays around with sinks and happens to look at the logs. The create / drop / create behaviour is intentional -- we are "reserving" an entry in the catalog for a sink, doing some asynchronous work to set up external state, and then atomically updating the state in the catalog with a drop + create.

The issue here is to hide this implementation detail from the user facing logs, which we could accomplish (if I am understanding the code correctly) by including a boolean in catalog::Op{CreateItem, DropItem} that controls whether or not we emit logs in those operations.

**Comment by benesch** [comment]
Good catch, thanks! Assigning to myself.

**Comment by ruchirK** [comment]
@benesch if you're not actively working on this I can take it on today w/ the strategy described above? no worries if you'd rather do something else

**Comment by benesch** [comment]
Yeah I'd rather not plumb the boolean into the catalog—that's just a sign we're logging in the wrong place. What this has exposed is that there is a distinction between the SQL-level op, which we want to log, and the catalog-level op, which we don't want to log unless it corresponds to a SQL-level op. I think probably we should hoist those logs into the coordinator.

**Comment by ruchirK** [comment]
Got it 👍

**Comment by ruchirK** [comment]
If you want and if its not too much trouble -- we could chat and make sure I'm on the same page re:approach and I could still try to knock it out? It's not a huge deal either way just trying to be helpful

**Comment by benesch** [comment]
Oh, sorry I missed this! We didn't ever sync up on this, did we? I forget.

**Comment by ruchirK** [comment]
We didn't but it's all good

**Comment by benesch** [comment]
My bad! Actually, now that I look at it, I think we can just suppress the `info!` log in `insert_item` (and the drop log line in `Catalog::transact`) whenever the catalog item in question is a pending sink? On the theory that pending sinks aren't "real" catalog items, but placeholders. Maybe even stick a `is_placeholder` method on `CatalogItem`, and use that check in the guard around the log line. That saves plumbing the bool without requiring a dozen log lines.

**Comment by ruchirK** [comment]
I realized I never responded to this either :| will throw up a PR with this approach by eod
