### ISSUE TITLE
"AWS (Real)" is flaky

### ISSUE THREAD

**Issue by nrainer-materialize** [MaterializeInc/materialize#25265]
### Buildkite link

https://buildkite.com/materialize/nightlies/builds/6448#018daa2c-f08f-405c-95d0-1fc0a0f6d7bc

### Relevant log output

```source
: {'S': 'ERROR', 'C': '58000', 'M': 'role trust policy does not require an external ID', 'D': "The trust policy for the connection's role (arn:aws:iam::400121260767:role/testdrive-3254404661-Customer) is insecure and allows any Materialize customer to assume the role.", 'H': 'See: https://materialize.com/s/aws-connection-role-trust-policy'}
```

### Additional thoughts

For tracking if more occurrences happen.

**Comment by benesch** [comment]
Thanks! I'll keep this in my background queue. Please ping if you see this happen again. One easy fix here is to bump the IAM sleep from 10s to 30s. That will slow the test down quite a bit though. The slightly less easy fix is to add retry loops, so that we wait as long as necessary to see what we expect, rather than blanket waiting 10 or 30s.

**Comment by benesch** [comment]
Another simple option: maybe just tell Buildkite to retry this one up to three times when it fails?

**Comment by nrainer-materialize** [comment]
Seen again in https://buildkite.com/materialize/nightlies/builds/6603#018de042-0791-4d1e-8b29-e7a3a942d71d.

**Comment by benesch** [comment]
Have we had trouble with this since #25553 landed?

**Comment by nrainer-materialize** [comment]
> Have we had trouble with this since #25553 landed?

That change landed on Feb 26. Since then, it has failed three times (twice due to this error in [builds/6761](https://buildkite.com/materialize/nightlies/builds/6761#018e0d94-0a88-42b1-a1ac-da70f1444f84) and [builds/7159](https://buildkite.com/materialize/nightlies/builds/7159#018e9c03-48c1-4e5e-b848-76b7006d639b), and once in builds/6755 were most jobs failed) but it recovered each time.

We can consider this resolved.

**Comment by benesch** [comment]
Great!
