### ISSUE TITLE
A view made of constants still generates NULLABLE columns

### ISSUE THREAD

**Issue by ruchirK** [MaterializeInc/materialize#2529]
for example -- something like 

```
> CREATE VIEW decimal_data (a, b) AS VALUES
  ('0.1'::decimal(15, 2), '-0.1'::decimal(15, 1)),
  ('0.1'::decimal(15, 2), '-0.1'::decimal(15, 1))
```

still generates a RelationDesc where a and b are nullable. If there's a workaround to coerce these rows to be non-NULLABLE that would work for me as well

**Comment by frankmcsherry** [comment]
Should be an easy fix! `RelationExpr::typ(&self)` is the function that produces relation type information, and nullability of columns lives there. Right now, the `RelationExpr::Constant` variant doesn't do anything other than assert that each element has the right type, and if there is a single element, produces the empty tuple as a key. It could easily mark the columns as non-nullable for each column for which all values are non-null.
