### ISSUE TITLE
Schema registry elides logical type info (makes it so materialize parses timestamps as int8s)

### ISSUE THREAD

**Issue by ruchirK** [MaterializeInc/materialize#2532]
Not sure what the best thing to do here is as it doesn't actually look like a Materialize issue filing here so its captured as a current known limitation

To reproduce -- first create a view that has a timestamp field and create a kafka sink based off of that view:

e.g.

```
materialize=> create view foo (ts) as values (TIMESTAMP '2000-01-01 10:10:10');
CREATE VIEW
materialize=> select * from foo;
         ts
---------------------
 2000-01-01 10:10:10
(1 row)

materialize=> create sink foo_sink from foo into kafka broker 'localhost:9092' topic 'foo-sink' format avro using confluent schema registry 'http://localhost:8081';
CREATE SINK
```

Next, find the real topic name Materialize is using to output the data:

```
materialize=> select * from mz_kafka_sinks;
 global_id |                    topic
-----------+----------------------------------------------
 u199      | foo-sink-u199-1585851326-2887751389022349577
(1 row)
```

it will be prefixed with `foo-sink` (the topic name argument passed to Materialize but your version of this string will be different)

And now, make a new source based on that <actual topic name>

```
materialize=> create materialized source foo_reingest from kafka broker 'localhost:9092' topic 'foo-sink-u199-1585851326-2887751389022349577' format avro using confluent schema registry 'http://localhost:8081' envelope debezium;
CREATE SOURCE
materialize=> show columns in foo_reingest;
 Field | Nullable | Type
-------+----------+------
 ts    | NO       | int8
(1 row)

materialize=> select * from foo_reingest;
       ts
-----------------
 946721410000000
(1 row)
```

The ingested data comes in as int8s and not as timestamps (though it is the correct int8)

Finally you can hit `curl -sX GET http://localhost:8081/subjects/{actual-topic-name}-value/versions/1 to see what schema registry thinks the schema is:

```
altaria-2:materialize Test$ curl -sX GET http://localhost:8081/subjects/foo-sink-u199-1585851326-2887751389022349577-value/versions/1 | jq .
{
  "subject": "foo-sink-u199-1585851326-2887751389022349577-value",
  "version": 1,
  "id": 10,
  "schema": "{\"type\":\"record\",\"name\":\"envelope\",\"fields\":[{\"name\":\"before\",\"type\":[\"null\",{\"type\":\"record\",\"name\":\"row\",\"fields\":[{\"name\":\"ts\",\"type\":\"long\"}]}]},{\"name\":\"after\",\"type\":[\"null\",\"row\"]}]}"
}
altaria-2:materialize Test$
```
and here astute readers will see that the schema is missing the required logicalType info so Materialize has no choice but to parse the data in as a long. I've validated that the schema we send to the registry has the right logicaltype info. This issue may be related https://github.com/confluentinc/schema-registry/issues/1199

**Comment by benesch** [comment]
Closing as stale. Not sure what the issue was, but this definitely isn't the behavior in current versions of Materialize.
