### ISSUE TITLE
[Epic] Implement Platform V2 Logical Design for Compute Controller

### ISSUE THREAD

**Issue by lfest** [MaterializeInc/materialize#25342]
### Feature request

Modify the compute controller according to the [Pv2 logical architecture](https://github.com/MaterializeInc/materialize/pull/23543).

The details need more design/discussion, but the rough idea is to replace the current synchronous compute controller API with an asynchronous one that uses commands sent over a channel. The controller becomes a free-standing task that continually pulls commands from the channel, performs the requested work, and sends responses back through another channel. Doing this lets us remove the controller's processing from the coordinator's sequencer hot path.

In a second step we can introduce the ability to send ephemeral (i.e. peek) commands from multiple clients concurrently and use that ability to further decouple fast-path peek processing from the coordinator.

* **Blocked by:** @aljoscha's in-progress work of migrating the compute controller to `StorageCollections`

**Comment by benesch** [comment]
Closing this; we'll handle as part of pv2.

**Comment by benesch** [comment]
Leaving a breadcrumb to the pv2 issue tracking this: https://github.com/MaterializeInc/materialize/issues/24845
