### ISSUE TITLE
kubectl-get-logs-previous.log is often empty

### ISSUE THREAD

**Issue by def-** [MaterializeInc/materialize#25369]
### What version of Materialize are you using?

main

### What is the issue?

See for example https://buildkite.com/materialize/nightlies/builds/6517#018dbc32-c4de-40c6-afdb-24d8e1d16fa4 (compared to https://buildkite.com/materialize/nightlies/builds/6522#018dc06f-df63-4a5f-a54b-95d18c1268ba, which contains a panic)

**Comment by nrainer-materialize** [comment]
A possible solution could be to start streaming the logs (once the pods are up (if we have a possiblity to hook in)): https://stackoverflow.com/a/57007668/584532

**Comment by def-** [comment]
I'll add an assertion
