### ISSUE TITLE
persist: mitigate rehydration spikes in `persist_source` (Q1FY2025)

### ISSUE THREAD

**Issue by benesch** [MaterializeInc/materialize#25448]
Placeholder issue for the roadmap to reflect persist's work in Q1FY2025 to mitigate rehydration spikes in compute (https://github.com/MaterializeInc/materialize/issues/23332).

Desired outcome: the rehydration spike caused by `persist_source` is no longer the bottleneck to scaling down a cluster.

Work items:

  * [x] https://github.com/MaterializeInc/materialize/pull/25097
  * [x] https://github.com/MaterializeInc/materialize/pull/25170
  * [x] Ensure feature flags are enabled for `cc` sizes in production
  * [x] #shipped-it post

## Action log

* **21 February 2024.** Create this issue.

**Comment by danhhz** [comment]
There aren't a ton of cc sized replicas in prod, so this is getting limited volume right now, but optimistically calling this done until/if we hear otherwise.
