### ISSUE TITLE
mysql: dropping / changing a column from a table returns stale results instead of erroring with incompatible schema change

### ISSUE THREAD

**Issue by nrainer-materialize** [MaterializeInc/materialize#25451]
### What version of Materialize are you using?

2c23008aa1

#### Dropping a column

```
$ mysql-execute name=mysql
CREATE TABLE remove_column (f1 INTEGER, f2 VARCHAR(2));
INSERT INTO remove_column VALUES (2, 'ab');

> SELECT * FROM remove_column;
2 ab

$ mysql-execute name=mysql
ALTER TABLE remove_column DROP COLUMN f2;
INSERT INTO remove_column VALUES (3);

! select * from remove_column;
```

Expected: `contains:incompatible schema change`
Got: an outdated result

Adding something like `$ sleep-is-probably-flaky-i-have-justified-my-need-with-a-comment duration=3s` doesn't help either.

#### Changing a column

The same happens with:
```
CREATE TABLE alter_column (f1 INTEGER, f2 VARCHAR(2));
[...]
ALTER TABLE alter_column MODIFY f2 int;
```

#### Drop nullability
```
CREATE TABLE alter_drop_nullability (f1 INTEGER NOT NULL);
ALTER TABLE alter_drop_nullability MODIFY f1 INTEGER;
```

also with consequence
```
# We have guaranteed that this column is not null so the optimizer eagerly
# returns the empty set.
> SELECT * FROM alter_drop_nullability WHERE f1 IS NULL;
```

See also: #25040

#### drop PK
```
CREATE TABLE alter_drop_pk (f1 INTEGER PRIMARY KEY);
ALTER TABLE alter_drop_pk DROP PRIMARY KEY;
```

#### and others

See `TODO: #25451` in https://github.com/MaterializeInc/materialize/pull/24733

**Comment by nrainer-materialize** [comment]
This possibly partially overlaps with https://github.com/MaterializeInc/materialize/issues/25040.

**Comment by nrainer-materialize** [comment]
This might have already worked in an earlier version and be a regression.

**Comment by nrainer-materialize** [comment]
Furthermore, the whole MySQL source is now in state `stalled` at the end of the test.

**Comment by rjobanp** [comment]
Fixed by https://github.com/MaterializeInc/materialize/pull/25626
