### ISSUE TITLE
surfaces/adapter: allow querying progress subsources from `mz_introspection`

### ISSUE THREAD

**Issue by morsapaes** [MaterializeInc/materialize#25464]
### Feature request

In the scope of [Console #1574](https://github.com/MaterializeInc/console/issues/1574), it'd be helpful to allow querying progress subsources from `mz_introspection`, to avoid having to rely on user-created clusters.

See [Slack](https://materializeinc.slack.com/archives/C02FWJ94HME/p1708560138903649) for more context.

**Comment by RobinClowers** [comment]
I stumbled across this issue and realized it's not really relevant anymore, since I realized the information we wanted from the progress source is also available in `mz_source_statistics`, which doesn't have this limitation.
