### ISSUE TITLE
surfaces/integrations: test Striim with Oracle and SQL Server

### ISSUE THREAD

**Issue by morsapaes** [MaterializeInc/materialize#25462]
### Feature request

As a follow-up to #20957, and before we document the integration (#25447), we should test using Striim with Oracle and SQL Server, which will be the most valuable data sources for users needing a CDC provider (rather than our native CDC sources).

**Comment by bobbyiliev** [comment]
Testing for both Oracle and SQL server has been completed. They would work the same way as MySQL as we would be using the same configuration for the Striim KafkaWriter.

The only thing that is different is the CDDL feature does not work with newer Oracle DB versions:

```
Start failed! Exception(s) leading to TERMINATED State: { “componentName” : “bobby_iliev_301_5449.oracle” , “componentType” : “SOURCE” , “exception” : “com.striim.exception.checked.AdapterInternalException” , “message” : “Message: Using OracleReader, CDDL Feature is not available for Oracle database version >= 19c. If your requirement is capture DDL changes from Oracle database version >= 19c in Striim, please reach out to our customer support. \nComponent Name: oracle. \nComponent Type: SOURCE. \nCause: Using OracleReader, CDDL Feature is not available for Oracle database version >= 19c. If your requirement is capture DDL changes from Oracle database version >= 19c in Striim, please reach out to our customer support\n” , “relatedEvents” : “[]” , “relatedEntity” : null , “exceptionCode” : null }
```

**Comment by morsapaes** [comment]
CDDL will be relevant once we explore a direct integration with Striim, but it doesn't seem relevant right now since the `KafkaWriter` doesn't seem to support this ([docs](https://www.striim.com/docs/en/handling-schema-evolution.html)).
