### ISSUE TITLE
storage/connections: promote default PrivateLink connections to Public Preview

### ISSUE THREAD

**Issue by morsapaes** [MaterializeInc/materialize#25468]
### Feature request

Since default PrivateLink connections are being successfully used in production with a Redpanda Cloud deployment, it's safe to promote the feature to Public Preview.

- [ ] Remove the `enable_default_kafka_aws_private_link` flag. https://github.com/MaterializeInc/materialize/pull/25527
- [ ] Update the documentation.

@jubrad, I'll take the opportunity to push the docs improvements we talked about.

**Comment by benesch** [comment]
Added this to the storage roadmap for tracking.
