### ISSUE TITLE
adapter: enforce `max_connections` for superusers

### ISSUE THREAD

**Issue by benesch** [MaterializeInc/materialize#25474]
Today, superusers (i.e., those with the Organization Admin role) are not subject to the `max_connections` limit:

https://github.com/MaterializeInc/materialize/blob/adef84e348f34da44a207c4e2d64cb1acbf81f9c/src/sql/src/session/user.rs#L92-L94

This is scary, because we introduced the `max_connections` flag to protect _our_ infrastructure (https://github.com/MaterializeInc/materialize/issues/18341#issuecomment-1529238072). Allowing end users to dodge the limit by connecting with an Organization Admin user means that we're not protected from our users running `environmentd` out of resources.

We discussed a bit recently in https://github.com/MaterializeInc/materialize/pull/25450#discussion_r1498628026. It sounds like the original rationale was that we didn't want a non-admin user to be able to hog all 500 connections and box out the admins. I think the idea was that you could log in and inspect `mz_sessions` to figure out which application was using too many connections. (Without support for `pg_terminate_backend` (https://github.com/MaterializeInc/materialize/issues/13130), there's nothing an admin can _do_ on the Materialize side to disconnect the problematic connections. They need to disconnect them from the other end, by terminating the problematic applications.)

PostgreSQL has a nice solution to this. In addition to a `max_connections` limit, they have a `superuser_reserved_connections` parameter. The `max_connections` limit is a strict limit that can never be exceeded, but there are `superuser_reserved_connections` slots that are set aside for superusers only. For example, if `max_connections` is 500 and `superuser_reserved_connections` is 3, then normal users will only be able to create 497 connections, and the last 3 slots will be reserved for superusers.

I propose that we follow PostgreSQL here—i.e., introduce the `superuser_reserved_connections` parameter, and then enforce the `max_connections` limit for all users.

One wrinkle to be aware of: several of our customers in production routinely exceed the 500 connection limit, presumably because their production apps are connecting as superusers. When we roll this change out, we'll want to be sure to bump the connection limit for these customers so that we don't break their production apps. I filed https://github.com/MaterializeInc/materialize/issues/25476 to track that request.

cc @chaas @ParkMyCar @mjibson

**Comment by mjibson** [comment]
SGTM

**Comment by ParkMyCar** [comment]
This also looks good to me!
