### ISSUE TITLE
adapter: increase default `max_connections`

### ISSUE THREAD

**Issue by benesch** [MaterializeInc/materialize#25476]
Our current default for `max_connections` is 500. But we have a few customers that routinely bust through this limit, in the range of 2000-5000 connections, presumably because we have a loophole that allows superusers to dodge the connection limit (https://github.com/MaterializeInc/materialize/issues/25474).

One common way that users get to thousands of connections is with AWS Lambda. If each Lambda establishes a connection pool with a dozen connections, and you scale to dozens or hundreds of Lambdas, you can pretty easily wind up with a few thousand connections to Materialize.

The traditional answer to this problem is a dedicated connection pooler, like [pgbouncer](https://www.pgbouncer.org) or [AWS RDS Proxy](https://aws.amazon.com/rds/proxy/). But I think this is fundamentally a workaround for the fact that connections in traditional databases like MySQL and PostgreSQL are expensive, because each connection requires a separate _process_ on the server. By contract, connections to Materialize are cheap—just a lightweight Tokio task.

So, I propose that we bless using Materialize with thousands of connections. Supporting this deployment pattern meaningfully decreases the operational overhead of Materialize for folks using serverless technologies like AWS Lambda, because they don't need to run a separate connection pool service.

Concretely, I propose that we bump the default `max_connections` limit to 5k, with an eye towards bumping it to 10k in the future if necessary.

cc @chaas @ParkMyCar @mjibson

**Comment by mjibson** [comment]
SGTM
