### ISSUE TITLE
Relate mz_sessions to mz_activity_log

### ISSUE THREAD

**Issue by chuck-alt-delete** [MaterializeInc/materialize#25665]
### Feature request

I was expecting `mz_internal.mz_recent_activity_log.session_id`  , which is a uuid, to correspond to `mz_internal.mz_sessions.id`, an integer. Would it be possible to relate the former to the latter?

This would be useful, for example, when finding rogue queries that need to be canceled with `pg_cancel_backend()`. Right now, the best I can do is find sessions with a timestamp close to the query.

**Comment by chaas** [comment]
Adding Brennan's description of the work item: 

We have both a UUID in mz_session_history (which gets exposed in mz_recent_activity_log and a non-unique ID (i.e., it gets recycled) in mz_sessions. There is currently no way to correlate these, and the fact that they are both called session_id is very confusing.

We should hide the UUID from the user as it's only useful as a join key between mz_prepared_statement_history and mz_session_history. We should also give ourselves a way to connect a UUID to an ID.
