### ISSUE TITLE
mysql: unexpected ssl connection validation results

### ISSUE THREAD

**Issue by nrainer-materialize** [MaterializeInc/materialize#25679]
### What version of Materialize are you using?

122073a7c6

### What is the issue?

A similar (inactive) test in Postgres is supposed to result in an error but it succeeds with MySQL:

```
> CREATE CONNECTION mysql_conn TO MYSQL (
  HOST mysql,
  USER certuser,
  SSL MODE verify_ca,
  SSL CERTIFICATE AUTHORITY SECRET ssl_ca
  );
! CREATE SOURCE "mz_source"
  FROM MYSQL CONNECTION mysql_conn
  FOR TABLES (public.numbers);
```

Expected: `contains:db error: FATAL: connection requires a valid client certificate`
Actual: no failure

**Comment by rjobanp** [comment]
@nrainer-materialize the options are different in MySQL. `verify-identity` enforces that a client-cert is provided, but `verify-ca` just validates that the server-cert matches the CA provided. See here for the options: https://dev.mysql.com/doc/refman/8.0/en/connection-options.html#option_general_ssl-mode

**Comment by nrainer-materialize** [comment]
Ok, thanks! I will update the tests accordingly.
