### ISSUE TITLE
Investigate huge rehydration spike for `mz_introspection`

### ISSUE THREAD

**Issue by umanwizard** [MaterializeInc/materialize#25699]
### What version of Materialize are you using?

v0.89.x

### What is the issue?

The user with the largest activity log has anywhere from 9 to 16 GB in max RSS, but only ~1GB steady state. This is preventing us from decreasing the size of their cluster, so we should figure out what's wrong.

**Comment by benesch** [comment]
Closing in favor of https://github.com/MaterializeInc/accounts/issues/49. This is expected until https://github.com/MaterializeInc/materialize/issues/25448 and https://github.com/MaterializeInc/materialize/issues/24983 are completed.
