### ISSUE TITLE
[Epic] Automatic cluster scheduling for `REFRESH EVERY` matviews

### ISSUE THREAD

**Issue by benesch** [MaterializeInc/materialize#25712]
*Split out from fully general automated cluster scheduling (https://github.com/MaterializeInc/materialize/issues/23132).*

## Product outcome

Users can create clusters that automatically pause and resume based on the `REFRESH` schedules of the materialized views maintained by the cluster.

## Design

We'll introduce a new `SCHEDULE` cluster option to `CREATE CLUSTER`. It will have two modes: `MANUAL` and `REFRESH`. The `MANUAL` mode indicates the current behavior: users are entirely responsible for pausing and resuming the cluster. The `REFRESH` mode is the new behavior, and indicates that the cluster should automatically pause and resume based on the `REFRESH` schedules of the materialized views maintained by the cluster.

Here is the syntax written out:

```sql
CREATE CLUSTER ... (SCHEDULE = {MANUAL | REFRESH});
```

For further details, see:

  * [Discussion on more general ticket on scoping down this MVP](https://github.com/MaterializeInc/materialize/issues/23132#issuecomment-1929693147)
  * [Braindump from meeting with @benesch / @frankmcsherry / @ggevay on 2/13](https://www.notion.so/materialize/Compute-meeting-on-automatic-cluster-scheduling-ce353b8af52e449d8784241c4a1c0585)

In particular, we'll be building a general purpose mechanism as part of this MVP, but building a very simple policy (Policy v1 in the notion doc).

## Future work

When this work is complete, we should strongly consider picking up https://github.com/MaterializeInc/materialize/issues/20010 (graceful reconfiguration of managed clusters). The mechanism we're building here should make it straightforward to add a policy like the one described in #20010.

## See also

* https://github.com/MaterializeInc/materialize/issues/13870

**Comment by ggevay** [comment]
Implemented in
- https://github.com/MaterializeInc/materialize/pull/25998
- https://github.com/MaterializeInc/materialize/pull/26242
- https://github.com/MaterializeInc/materialize/pull/26401
- https://github.com/MaterializeInc/materialize/pull/26535
