### ISSUE TITLE
Postgres: Fail to replicate with max_replication_slots=2 

### ISSUE THREAD

**Issue by def-** [MaterializeInc/materialize#25809]
### What version of Materialize are you using?

7b219f8f56de (Pull Request #25808)

### What is the issue?

Seen in https://buildkite.com/materialize/tests/builds/77720#018e1363-944b-43af-b3d3-2346162968e8
```
builtins.ValueError: Source pk is expected to be running/created, but is stalled, error: postgres: db error: ERROR: all replication slots are in use HINT: Free one or increase max_replication_slots.: ERROR: all replication slots are in use HINT: Free one or increase max_replication_slots., details: {'namespaced': {'postgres': 'db error: ERROR: all replication slots are in use\nHINT: Free one or increase max_replication_slots.: ERROR: all replication slots are in use\nHINT: Free one or increase max_replication_slots.'}}
```
The workflow_replication_slots explicitly allows only 2 replications slots, but this sometimes doesn't seem to work?

ci-regexp: Source pk is expected to be running/created, but is stalled, error: postgres: db error: ERROR: all replication slots are in use

**Comment by sploiselle** [comment]
This failure is annoyingly expected with only 2 replication slots. If you try to add a subsource while another snapshot is occurring, we will think we need 3 replication slots (we need 2 for the initial create, which we use, and then we think we need 1 additional for the add'l subsource). We'll drop the snapshot replication slot when performing the new source's snapshot, but in planning where this error occurs, there's not a reasonable way for us to determine this.

The simplest means of making this test reliable is to bump the max replication slots to 3.

**Comment by def-** [comment]
Perfect, then I'll just do that. I assumed this could've been something wrose.
