### ISSUE TITLE
thread 'timely:work-2' panicked at src/dataflow/operators/partition.rs:52:33: index out of bounds: the len is 5 but the index is 6

### ISSUE THREAD

**Issue by def-** [MaterializeInc/materialize#25826]
### What version of Materialize are you using?

465c3f1e86f3

### What is the issue?

Seen in https://buildkite.com/materialize/tests/builds/77783#018e1537-d1e7-46bf-8c81-6abf76b6934e
This might be related to testdrive becoming faster recently.
```
mysql-cdc-resumption-materialized-1  | thread 'timely:work-2' panicked at /cargo/git/checkouts/timely-dataflow-70b80d81d6cabd62/9208396/timely/src/dataflow/operators/partition.rs:52:33:
mysql-cdc-resumption-materialized-1  | index out of bounds: the len is 5 but the index is 6
mysql-cdc-resumption-materialized-1  | stack backtrace:
```
(There seems to be no backtrace)

ci-regxp: panicked at .*src/dataflow/operators/partition.rs:52

**Comment by benesch** [comment]
Thanks, @def-! I think it's safe to go to PrPr without this fixed, but we should definitely hop on fixing it ASAP. @morsapaes @rjobanp, what do you think?

**Comment by morsapaes** [comment]
+1, also because [it seems flaky](https://materializeinc.slack.com/archives/C069K7ZUKS9/p1709762792658789?thread_ts=1709762097.367179&cid=C069K7ZUKS9).

**Comment by def-** [comment]
Same, this unfortunately hasn't happened again in CI either.

**Comment by nrainer-materialize** [comment]
Further occurrence in https://buildkite.com/materialize/tests/builds/78031.
