### ISSUE TITLE
mysql: source does not detect when switching to a replica with a lower GTID

### ISSUE THREAD

**Issue by nrainer-materialize** [MaterializeInc/materialize#25836]
### What version of Materialize are you using?

a85fcf1abc

### What is the issue?

Workflow: `workflow_switch_to_lagging_replica` in https://github.com/MaterializeInc/materialize/pull/25773

> mysql-replica-1 replicates mysql. The source is attached to mysql. mysql-replica-1 is configured to have a replication delay and lags behind. mz switches the connection to mysql-replica-1, which exhibits a lower GTID.

`mysql`:
```
mysql> select @@gtid_executed;
+-------------------------------------------+
| @@gtid_executed                           |
+-------------------------------------------+
| 51667cc2-dc64-11ee-9975-0242c0a83004:1-28 |
+-------------------------------------------+
1 row in set (0.00 sec)
```

`mysql-replica-1`:
```
mysql> select @@gtid_executed;
+-------------------------------------------------------------------------------------+
| @@gtid_executed                                                                     |
+-------------------------------------------------------------------------------------+
| 51667cc2-dc64-11ee-9975-0242c0a83004:1-21,
5bb1ffbf-dc64-11ee-898d-0242c0a83005:1-5 |
+-------------------------------------------------------------------------------------+
1 row in set (0.00 sec)
```

The mz source remains in status "running".

**Comment by rjobanp** [comment]
@nrainer-materialize I'm not sure that this one should actually put the source into a bad state. If we switch over to a lagging replica, we don't necessarily lose correctness guarantees, we'll just ignore any transactions that we've already seen as we receive them from this replica.

**Comment by nrainer-materialize** [comment]
Yes, that makes sense to me. We can close this issue then.
