### ISSUE TITLE
storage/sinks/kafka: failing kafka/ssh sink can crashloop replica [incident 100]

### ISSUE THREAD

**Issue by benesch** [MaterializeInc/materialize#25833]
In incident 100, we saw a cluster with a Kafka-over-SSH sink that was failing to publish its schema to the schema registry cause the cluster to enter a very slow OOM loop—about once every two hours. There were actually three sinks on the cluster, and I _think_ they were all in the same schema registry fail loop

Our investigation indicated that librdkafka threads and sockets were piling up. See the Slack conversation for details: https://materializeinc.slack.com/archives/C06NCJ8B23W/p1709763502099829

My hunch is that we're leaking rdkafka handles during suspend and restart events. Not sure whether the SSH tunnels are relevant.

**Comment by def-** [comment]
For completeness I believe this to be the issue: https://github.com/MaterializeInc/materialize/pull/25849#issuecomment-1985470258
