### ISSUE TITLE
sqllogictests bypass pgwire checks

### ISSUE THREAD

**Issue by justinj** [MaterializeInc/materialize#2583]
Unsure if this is an actual problem, but certain checks that are expected to be done by pgwire get bypassed by the sqllogictests, for instance, this query crashes a server:

```sql
select $1
```

**Comment by wangandi** [comment]
I think this is expected behavior.

From section "testdrive" in https://github.com/MaterializeInc/materialize/blob/master/doc/developer/testing.md 
> Note that testdrive actually interacts with Materialize over the network, via the PostgreSQL wire protocol, so it tests more of Materialize than our sqllogictest driver does. (It would be possible to run sqllogictest over the network too, but this is just not how things are configured at the moment.) Therefore it's often useful to write some additional testdrive tests to make sure things get serialized on the wire properly. For example, when adding a new data type, like, say, DATE, the upstream CockroachDB sqllogictests will provide most of the coverage, but it's worth adding some (very) basic testdrive tests (e.g., > SELECT DATE '1999-01-01') to ensure that our pgwire implementation is properly serializing dates.

**Comment by justinj** [comment]
It's expected, but I'm not sure it's desirable (it confused me at first, at least)?

**Comment by wangandi** [comment]
From an architectural standpoint, it would be kind of strange to add pgwire validation to the sqllogictest because sqllogictest is not transmitting anything over a wire.

That said, it would be desirable for `select $1` to raise a less confusing error. For me, the real question would be, does the sql validation code that `pgwire` is running really belong in the `pgwire` module, or should it be moved to `sql::session`?

**Comment by benesch** [comment]
> From an architectural standpoint, it would be kind of strange to add pgwire validation to the sqllogictest because sqllogictest is not transmitting anything over a wire.

The question is more—why is the SLT runner doing that in the first place? Why can't it just use pgwire like testdrive and other clients? Limiting the number of interfaces to Materialize to 1 is desirable, IMO. I think there were sensible reasons at the time, but those reasons might be moot now. @jamii do you remember the history here?

**Comment by benesch** [comment]
But yes it is also possible that those checks should live in coord, rather than pgwire, but we don't presently have the ability to set pgwire error codes from coord. (We should!)

**Comment by jamii** [comment]
Testdrive's polling had to timeout before giving up for each failed test. At 5s per failed test, we would have taken >50 years to run slt. So we needed the ability to query at a particular timestamp. 

It looks like the docs in runner still say that, but the code has been changed and no longer uses timestamps. So maybe we can do it in sql?

**Comment by jamii** [comment]
Oh, and the runner also needs access to the parse tree to decide what to do with statements, but we could always parse it twice.
