### ISSUE TITLE
Introduce an `mz_probe` cluster for internal uptime monitoring

### ISSUE THREAD

**Issue by benesch** [MaterializeInc/materialize#25834]
## Summary

Introduce a new system cluster called `mz_probe` with minimal resources, whose sole purpose is to handle our uptime monitoring probes.

## Details

Currently the `mz_system` cluster serves three purposes:

  1. The billing usage exporter runs an hourly export query in this cluster.
  2. The Prometheus SQL exporter runs a `SHOW VIEWS` probe against the cluster every minute, as a check that the environment is end to end healthy and can handle a basic query that reads out of S3.
  3. We occasionally run critical debugging commands manually against this cluster by logging in as the `mz_system` user.

On Tuesday, @bkirwi ran a manual debugging query against an `mz_system` cluster that used 100% CPU usage for multiple minutes. This caused the `SHOW VIEWS` probe to fail repeatedly, which in turn caused our on call engineer (@teskje) to be woken up. @teskje is in CEST and @bkirwi is in ET, so it was the end of Ben's workday but the middle of Jan's night. Details in this Slack conversation: https://materializeinc.slack.com/archives/C04DJT084KA/p1709595815043619

The problem here is that we are colocating tasks (2) and (3) on the same cluster. The load bearing probes for our uptime monitoring should not be located on the same cluster where we run system debugging commands, as those debugging commands can cause the probes to fail.

We can solve this by introducing a new system cluster called `mz_probe` to handle the uptime probes (2). This cluster will need minimal resources. @alex-hunt-materialize has proposed using a 1cc size, for example. We'll need to do some testing in a staging environment to determine just how small we can really go with `mz_probe`, but 1cc sounds like a reasonable place to start, and is cheap enough that we won't need to worry about it. (We won't want to introduce the 1cc size for customers though, as it'll be useless for anything besides these uptime probes.)

We can offset the cost of `mz_probe` by sizing down the `mz_system` cluster. I'll follow up about that in https://github.com/MaterializeInc/materialize/issues/24983. 

cc @chaas @jubrad @jpepin

**Comment by aalexandrov** [comment]
In which category does serving the queries for console fall into?

**Comment by chaas** [comment]
> In which category does serving the queries for console fall into? Which of the two clusters do this job?

There's a third system cluster `mz_introspection` that already exists and is not mentioned in this issue that serves console queries. It's where the indexes on the system catalog are loaded, and where system catalog queries & show commands are auto-routed.

**Comment by chaas** [comment]
A thought from an offline discussion: we should consider making the official guidance that the on-call/Materialize employees spin up an unbilled cluster temporarily to run critical debugging commands manually. This ensures isolation from the other things being run on `mz_system`.
It still might be a good idea to create `mz_probe` to split out (1) and (2).

**Comment by aalexandrov** [comment]
> A thought from an offline discussion: we should consider making the official guidance that the on-call/Materialize employees spin up an unbilled cluster temporarily to run critical debugging commands manually. This ensures isolation from the other things being run on `mz_system`. It still might be a good idea to create `mz_probe` to split out (1) and (2).

This means that every time when we want to run a non-trivial query on all environments we will need to request `mz_system` access for every environment. It is highly likely that @MaterializeInc/compute will want to run one of these checks almost every week. If possible, I would appreciate if we can allow spinning up an unbilled `mz_system` cluster under `mz_support`.

**Comment by benesch** [comment]
I wonder if we want to introduce a new cluster called `mz_support` that has zero replicas, as a home for adding one-off debug replicas under `mz_support`. So, all together:

  * `mz_system`: size down to a 25cc cluster, with one replica, to run the regular usage export
  * `mz_probe`: a new 1-5cc cluster, single replica, for running Prometheus SQL exporter uptime probes
  * `mz_support`: a new cluster with no replicas that `mz_support` can add unbilled replicas to as necessary

**Comment by jubrad** [comment]
@benesch how do we want to do (1-5)cc? 
Do we want to provide this as a general cluster size that anything can use or somehow make this internally usable only? 
Based on our cluster-size scripts this is what I 1cc would look like:
```yaml
    1cc:
      cpu_limit: 0.02
      memory_limit: 155MiB
      disk_limit: 310MiB
      scale: 1
      workers: 1
      credits_per_hour: "0.01"
      cpu_exclusive: false
      selectors:
        "kubernetes.io/arch": arm64
```

**Comment by pH14** [comment]
If we have `mz_support` do we still need `mz_probe`? It'd be nice to avoid introducing a new built-in / cluster size if we can avoid it. If we have `mz_support` then ideally `mz_system` is purely responsible for just the usage export + `SHOW VIEWS` queries and nothing ad-hoc

**Comment by aalexandrov** [comment]
> If we have `mz_support` do we still need `mz_probe`?

I think the concern is that ad-hoc queries executed by some automation scripts might interfere / bring down the Prometheus metrics if they happen on the same cluster. The suggestion was to have `mz_support` with 0 replicas by default, and only bring replicas (as `mz_system`) from scripts that need to run more expensive queries.

**Comment by jubrad** [comment]
If we combined mz_support and mz_probe I'd assume we'd still do so on a small cluster size (5cc?) with a single replica and we'd potentially have some metric misses on resize, or oom due to a bad query.

**Comment by pH14** [comment]
> I think the concern is that queries executed by some automation scripts might interfere / bring down the Prometheus metrics if they are executed on the same cluster. The suggestion was to have mz_support with 0 replicas by default for the former, and expect that the scripts will bring up replicas when needed.

Right so if we have `mz_support`, it seems like we've offloaded `mz_system` from needing to run any expensive debugging queries. The only workloads on `mz_system` will be well-defined ones that we've code reviewed, like billing usage + `SHOW VIEWS` uptime.

> If we combined mz_support and mz_probe I'd assume we'd still do so on a small cluster size (5cc?) with a single replica and we'd potentially have some metric misses on resize, or oom due to a bad query.

I was thinking the combination would be `mz_system` and `mz_probe` (also known as keeping things as they are 🙃), as a result of introducing `mz_support`. `mz_system` gets to size down to 25cc, and `mz_support` is given whatever size is needed for the adhoc queries required in the moment.

I think I also like this more from a permissions perspective -- in general we should be trying to solve as many problems as possible using only the `mz_support` role and cluster.

**Comment by jubrad** [comment]
Using mz_system as the probe cluster makes sense to me, unless we want something like additional access restrictions tied to an `mz_probe` user. We would be saying mz_system unavailability is an acceptable reason for a show views failure, which to me, sounds fine.

**Comment by benesch** [comment]
I think it is still worthwhile to introduce the `mz_probe` cluster, because the usage export workload is quite different from the uptime probe workload. The former runs a semi-expensive query every hour, while the latter runs a cheap query every 10s. By splitting the two workloads out, we can bring the costs way down as soon as we have autosuspending clusters. `mz_probe` needs to be on 100% of the time, but `mz_system` only needs to be on for ~1m every hour.

> @benesch how do we want to do (1-5)cc?
> Do we want to provide this as a general cluster size that anything can use or somehow make this internally usable only?

Here's a proposal: introduce a new size calle `mz_probe`. Then we can evolve the definition of that size as necessary based to support the prom SQL exporter's needs. The `allowed_cluster_replica_sizes` LD flag in its present configuration will prevent users from creating their own clusters of this size. And I do think we want to prevent users from using this size; clusters this tiny are generally too resource constrained to be useful, and we don't want to be in the business of trying to debug workloads that users are cramming into a 1 or 5cc cluster.
