### ISSUE TITLE
mysql: types: support TIME type

### ISSUE THREAD

**Issue by nrainer-materialize** [MaterializeInc/materialize#25847]
### What version of Materialize are you using?

a85fcf1

### What is the issue?

Support for type `TIME`:
```
# CREATE TABLE t2 (time_col TIME);
# INSERT INTO t2 VALUES ('-838:59:59');
# INSERT INTO t2 VALUES ('838:59:59');

# > SELECT * FROM t2;
# "-838:59:59"
# "838:59:59"
```

```
types-temporal-2.td:57:1: error: executing query failed: db error: ERROR: Source error: u5: unable to decode: error decoding value for 'public.t1' column 'time_col': Couldn't convert the value `Time("'-838:59:59'")` to a desired type: ERROR: Source error: u5: unable to decode: error decoding value for 'public.t1' column 'time_col': Couldn't convert the value `Time("'-838:59:59'")` to a desired type
```

**Comment by rjobanp** [comment]
@nrainer-materialize this error is expected -- that time value is too large for the postgres/materialize time value which only supports up to 24:00:00

**Comment by nrainer-materialize** [comment]
> @nrainer-materialize this error is expected -- that time value is too large for the postgres/materialize time value which only supports up to 24:00:00

Ok. I think I also saw it with`-04:00:00`. Should that fails as well?

**Comment by rjobanp** [comment]
Yes the supported ranges are available here: https://www.postgresql.org/docs/current/datatype-datetime.html

**Comment by nrainer-materialize** [comment]
> > @nrainer-materialize this error is expected -- that time value is too large for the postgres/materialize time value which only supports up to 24:00:00
> 
> Ok. I think I also saw it with`-04:00:00`. Should that fails as well?

Yeah, looks like:
```
materialize=> select '-04:00:00'::TIME;
ERROR:  invalid input syntax for type time: Invalid syntax at offset 0: provided Dash but expected Colon: "-04:00:00"
materialize=> select '04:00:00'::TIME;
   time   
----------
 04:00:00
(1 row)
```
