### ISSUE TITLE
mysql: types: support YEAR type

### ISSUE THREAD

**Issue by nrainer-materialize** [MaterializeInc/materialize#25846]
### What version of Materialize are you using?

a85fcf1abc

### What is the issue?

Support for type `YEAR`:

```
CREATE TABLE t3 (year_col YEAR);
INSERT INTO t3 VALUES ('1901');
INSERT INTO t3 VALUES ('2155');

# > SELECT * FROM t3;
# "1901"
# "2155"
```

**Comment by nrainer-materialize** [comment]
Though, it is not listed in https://github.com/MaterializeInc/materialize/issues/24956 as supported type.

**Comment by rjobanp** [comment]
Discussed in slack -- this will be implemented by supporting it as a `TEXT COLUMNS` option since there is no direct equivalent type in materialize/postgres
