### ISSUE TITLE
mysql: types: support TINYTEXT

### ISSUE THREAD

**Issue by nrainer-materialize** [MaterializeInc/materialize#25851]
### What version of Materialize are you using?

a85fcf1abc

### What is the issue?

```
CREATE TABLE t3 (f1 TINYTEXT, f2 MEDIUMTEXT, f3 LONGTEXT) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;
INSERT INTO t3 VALUES ('abc ', 'abc ', 'abc ');
```

`TINYTEXT` is listed in https://github.com/MaterializeInc/materialize/issues/24956 but not supported. Probably, just the type mapping is missing.

**Comment by rjobanp** [comment]
fixed in https://github.com/MaterializeInc/materialize/pull/25854
