### ISSUE TITLE
sqlsmith: internal error: column 3 is not of expected type ColumnType { scalar_type: Jsonb, nullable: true }: Map({"89": Null})

### ISSUE THREAD

**Issue by def-** [MaterializeInc/materialize#25899]
### What version of Materialize are you using?

f9ea5c54061d38e9fccb700773742641ab454a05

### What is the issue?

```
materialize=> SELECT NULL AS c2, pg_catalog.jsonb_object_agg(subq_2.c2, mz_internal.mz_normalize_schema_name(NULL)) AS c3 FROM (SELECT subq_1.c9 AS c2 FROM (SELECT subq_0.c0 AS c9 FROM LATERAL (SELECT 89 AS c0) AS subq_0) AS subq_1) AS subq_2;
ERROR:  internal error: column 1 is not of expected type ColumnType { scalar_type: Jsonb, nullable: true }: Map({"89": Null})
```

Logs:
```
environmentd: 2024-03-08T22:49:15.428893Z  WARN mz_transform::typecheck: TYPE ERROR IN TRANSIENT QUERY:
In the MIR term:
Constant
  - (█, █)


bad constant row
      got (null, {89: null})
expected row of type (String?, Jsonb)

Constant
  - (█, █)

environmentd: 2024-03-08T22:49:15.428896Z ERROR mz_transform::typecheck: type error in MIR optimization (details in warning; see 'Type error omnibus' issue #19101 <https://github.com/MaterializeInc/materialize/issues/19101>)
```

I'm scared that this might be a correctness issue. We had a similar issue in https://github.com/MaterializeInc/materialize/issues/23015 @aalexandrov are you the right assignee?

ci-regexp: is not of expected type ColumnType { scalar_type: Jsonb,

**Comment by def-** [comment]
Running the same query on the prod sandbox panics: `internal error: entered unreachable code: not a json-compatible datum: Null`

**Comment by ggevay** [comment]
Might have found the issue: https://materializeinc.slack.com/archives/CTESPM7FU/p1710170083303989?thread_ts=1710169018.775959&cid=CTESPM7FU

**Comment by def-** [comment]
@ggevay That sounds correct to me, reassigned the issue.

**Comment by benesch** [comment]
Here's a fix PR: https://github.com/MaterializeInc/materialize/pull/25941.

**Comment by ggevay** [comment]
(Not a release blocker as discussed here: https://materializeinc.slack.com/archives/CTESPM7FU/p1710180239096799?thread_ts=1710169018.775959&cid=CTESPM7FU)
