### ISSUE TITLE
persist: fast count(*) with projection pushdown

### ISSUE THREAD

**Issue by danhhz** [MaterializeInc/materialize#25891]
Once we have #24830, it should be possible to push projections all the way down to s3 fetching[^1]. This would be particularly impactful for `count(*)` queries, which are reasonably common[^2]. We already plumb the MapFilterProject information to persist, so this hopefully doesn't require much, if any, compute work to support. We'd still need to fetch the timestamp and diff columns, which unfortunately does give a reasonably high floor to how low we can get the latencies here.

Note that once we have 24830, we'll be storing each column's data together, but persist doesn't yet have a way to fetch partial parts, which would be necessary. This is likely to be the bulk of the work for this issue. Feels like the approaches to this fall into one of two buckets:

- Allow fetching byte ranges of a Blob OR
- Write data such that columns are aligned to Blob boundaries

My initial guess is that the cost implications (and tail latencies) of the latter make it less desirable.

Related: [a different (complementary?) approach to speeding up count queries](https://github.com/MaterializeInc/materialize/issues/20618)

[^1]: Once we have 24830, there's an intermediate milestone available that is _much_ easier, which is to avoid parquet decoding of the unnecessary columns in the fetched full part. This would reduce memory usage and wasted cpu, but unclear how much impact this would have on the latencies, so dunno if it's particularly interesting. Otoh, rehydration shows us that we can fetch data faster than we can decode it (this might change after 24830), so it _might_ have an interesting reduction of latencies.

[^2]: Moreso, `count(*)` queries happen disproportionally often during the first uses of materialize, informing whether a potential new users thinks of us as fast or slow.

**Comment by danhhz** [comment]
Recent convo where this came up https://materializeinc.slack.com/archives/CU7ELJ6E9/p1709914504815139

**Comment by JLDLaughlin** [comment]
we just got a customer ask for this, details here: https://materializeinc.slack.com/archives/C04SN4BEQ0N/p1710419191083269

**Comment by danhhz** [comment]
We ended up going with the approach described in #20618, but it amounts to the same thing as the user sees it: `count(*)` queries now receive what is essentially a special case of projection pushdown and are (usually) fast. This is rolled out to all of prod, so I'll go ahead and close this issue.
