### ISSUE TITLE
mysql: source stalled in canary environment

### ISSUE THREAD

**Issue by nrainer-materialize** [MaterializeInc/materialize#25928]
### What version of Materialize are you using?

2b0a0793a6b06715dafc44cc10c1c06a80e3cfda

### What is the issue?

mysql source is stalled, subsources are ceased.

```
select *
from mz_internal.mz_source_statuses
join mz_sources using (id)
join mz_schemas on (schema_id = mz_schemas.id)
join mz_databases on (database_id = mz_databases.id)
where mz_databases.name = 'qa_canary_environment'
and not (
  status = 'running' or
  (mz_sources.type = 'progress' and status = 'created') or
  (mz_sources.type = 'subsource' and status = 'starting')
);
```

in `qa_canary_environment`

```
mysql: mysql server binlog frontier at Antichain { elements: [Partitioned((Interval { lower: 00000000-0000-0000-0000-000000000000, upper: 064dbcaf-d274-11ee-a4e0-021eee57f78c }, Absent)), Partitioned((Interval { lower: 064dbcaf-d274-11ee-a4e0-021eee57f78d, upper: 064dbcaf-d274-11ee-a4e0-021eee57f78d }, Active(2358150))), Partitioned((Interval { lower: 064dbcaf-d274-11ee-a4e0-021eee57f78e, upper: ffffffff-ffff-ffff-ffff-ffffffffffff }, Absent))] }
is beyond required frontier Antichain { elements: [Partitioned((Interval { lower: 00000000-0000-0000-0000-000000000000, upper: 064dbcaf-d274-11ee-a4e0-021eee57f78c }, Absent)), Partitioned((Interval { lower: 064dbcaf-d274-11ee-a4e0-021eee57f78d, upper: 064dbcaf-d274-11ee-a4e0-021eee57f78d }, Active(1823879))), Partitioned((Interval { lower: 064dbcaf-d274-11ee-a4e0-021eee57f78e, upper: ffffffff-ffff-ffff-ffff-ffffffffffff }, Absent))] }
```

**Comment by rjobanp** [comment]
What mysql upstream is this canary environment connected to? this is the error that occurs when the binlog has removed events that we need to resume replication. Is this upstream mysql set to rotate binlogs very frequently, and was the canary environment down for some time?

**Comment by def-** [comment]
It's a MySQL RDS source: https://eu-west-1.console.aws.amazon.com/rds/home?region=eu-west-1#database:id=qa-canary-environment-mysql;is-cluster=false
I set it up exactly as described in https://www.notion.so/materialize/RDS-MySQL-Materialize-b3eca1b1fd924353a962961a4d9b2860#ed22d9837ae7480c96b7c604ec280785

**Comment by nrainer-materialize** [comment]
I would say the canary environment is down during upgrades.
Regarding the access to MySQL, I will send you the 1password link on Slack.

**Comment by rjobanp** [comment]
Awesome thanks!!

**Comment by rjobanp** [comment]
It turns out that is because RDS apparently has its own parameter for configuring the binlog retention time and ignores the mysql `binlog_expire_logs_seconds` system parameter: [https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/mysql-stored-proc-configuring.html#mysql_rds_set_configuration[…]notes.binlog-retention-hours](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/mysql-stored-proc-configuring.html#mysql_rds_set_configuration-usage-notes.binlog-retention-hours)
you apparently have to call a stored procedure to set the retention hours to something greater than the default of NULL/0

This is the current config on the RDS instance:
```
mysql> CALL mysql.rds_show_configuration;
+------------------------+-------+-----------------------------------------------------------------------------------------------------------+
| name                   | value | description                                                                                               |
+------------------------+-------+-----------------------------------------------------------------------------------------------------------+
| binlog retention hours | NULL  | binlog retention hours specifies the duration in hours before binary logs are automatically deleted.      |
| source delay           | 0     | source delay specifies replication delay in seconds between current instance and its master.              |
| target delay           | 0     | target delay specifies replication delay in seconds between current instance and its future read-replica. |
+------------------------+-------+-----------------------------------------------------------------------------------------------------------+
3 rows in set (0.12 sec)

Query OK, 0 rows affected (0.12 sec)
```

**Comment by nrainer-materialize** [comment]
To my understanding, this occurred due to a misconfiguration of the MySQL source, which resulted in bin log entries being stored only for a very short time so that a gap occurred when restarting mz. I think we can close this issue. @rjobanp, do you agree?
