### ISSUE TITLE
surfaces/adapter: remove `size` column from `SHOW { SOURCES | SINKS }` commands

### ISSUE THREAD

**Issue by morsapaes** [MaterializeInc/materialize#25953]
### Feature request

Since we deprecated and removed the concept of linked clusters (#24161, #24850), sources and sinks can no longer have a size associated. To avoid confusion, we should remove the `size` column from the `SHOW SOURCES` and `SHOW SINKS` commands.

This also allows us to remove the join with `mz_clusters` for both `mz_sources` and `mz_sinks`. Because these tables are in the stable `mz_catalog`, I assume we can't entirely remove the column, but we should at least mark it as `(Deprecated)` in the reference documentation.

**Comment by chaas** [comment]
This is technically a breaking change too. Per our backwards compatibility policy, only adding columns to `SHOW` commands is not a breaking change.
https://www.notion.so/materialize/Backwards-compatibility-policy-434ecf894656435795ef3f61b3a54976

@morsapaes  I'm still fine doing it tho if you think it's the right thing to do. Users can't make views etc. on top of SHOW commands, so it would only be breaking their experience outside of Materialize (e.g. a dbt script). Let me know what you think

**Comment by morsapaes** [comment]
> it would only be breaking their experience outside of Materialize

Not sure I follow! But I'm +1 doing it, since we shouldn't have references to invalid concepts in user-facing helper commands.

**Comment by chaas** [comment]
> Not sure I follow! 
If anyone's application executes `SHOW SOURCES`, and depends on the result, it may break. That's why we have a backwards compatibility policy. So are you comfortable risking that happening? We could potentially write a script that queries across all environments to see if `SHOW SOURCES` is in their query history, and if so from what application_name. But if you think it's not worth it we can just take the risk.

**Comment by morsapaes** [comment]
> Users can't make views etc. on top of SHOW commands, so it would only be breaking their experience outside of Materialize (_e.g._ a dbt script).

Because we don't allow this, I'm comfortable making this change.
