### ISSUE TITLE
min(time) returns timedelta instead of time

### ISSUE THREAD

**Issue by nrainer-materialize** [MaterializeInc/materialize#25959]
### What version of Materialize are you using?

762e5fb20bda4f8ba104270599b518d393b76a2a

### What is the issue?

```
CREATE TABLE t (x TIME);
materialize=> INSERT INTO t VALUES ('14:00:00'::TIME);
```

`SELECT x FROM t` returns Python type `class 'datetime.time'` but `SELECT min(x) FROM t` returns `class 'datetime.timedelta'`. Both SELECT statements should return `class 'datetime.time'` as it is the case in Postgres.

**Comment by guswynn** [comment]
This seems like an optimizer/planning issue:
```
materialize=> explain raw plan for select x, pg_typeof(x), pg_typeof(min(x)) from t group by x;
                            Raw Plan
-----------------------------------------------------------------
 Project (#0, #2, #3)                                           +
   Map ("time", "interval")                                     +
     Reduce group_by=[#1] aggregates=[min(time_to_interval(#0))]+
       Map (#0)                                                 +
         Get materialize.public.t                               +

(1 row)
```

where a `time_to_interval` cast is being inserted; nothing seems wrong with how we manage the types in the aggregate function definition itself

`CastTimeToInterval` seems to be an implicit cast but idk how its being selected here

**Comment by sploiselle** [comment]
We don't support `min(time)` and we just choose the best option available. We can fix this by just adding the implementation. I can do this tomorrow.

**Comment by guswynn** [comment]
ohhhh @sploiselle I was confusing the `Timestamp` and `Timestampz` impls for `Time`!
