### ISSUE TITLE
High load on Kafka cluster

### ISSUE THREAD

**Issue by frankmcsherry** [MaterializeInc/materialize#2597]
At least one user has reported high load on their Kafka cluster, enough that it is causing problems with other Kafka-ecosystem things. We don't have specifics on what causes this, other than it is probably us, and it seems to be high CPU load (the network is apparently well provisioned).

There are at least two things to do: 

1. Introduce some safety mechanisms to prevent harm to clusters (e.g. a rate limit on data read),
2. Attempt to reproduce and diagnose load on Kafka clusters; it is possible we are spamming them with control messages or something like that.

cc @umanwizard

**Comment by ruchirK** [comment]
we should validate basic things like does the kafka wire protocol version our consumer is asking for match the wire protocol version their producer gives / their broker store internally

theres other footguns that I can't think of offhand. would be good to know:

what kind of hardware does their broker run on?
how much load is "high load" -- how much data are we reading?
whats the distribution of cpu and network load across cores / broker nodes
