### ISSUE TITLE
Avoid Copy unless we're sure

### ISSUE THREAD

**Issue by jamii** [MaterializeInc/materialize#2599]
Making a type impl Copy saves a bit of typing. But some changes (eg adding ScalarType::Array) prevent a type from being Copy, which requires editing tons of code and causing horrific merge conflicts. We shouldn't impl Copy on any type that we expect to become more complicated.

**Comment by benesch** [comment]
How big is the variant getting? u128's are `Copy`, and they're 16 bytes wide.

**Comment by benesch** [comment]
Oh, I see, a `Box<ScalarType>`. Yeah, ok, that ain't gonna be `Copy`.

**Comment by jamii** [comment]
Yep. Records and other composite types will be similar too.

**Comment by benesch** [comment]
This hasn't been an issue lately, I don't think.
