### ISSUE TITLE
storage/sources: improve rehydration time for upsert sources

### ISSUE THREAD

**Issue by morsapaes** [MaterializeInc/materialize#26003]
@guswynn had penciled down [potential optimizations](https://www.notion.so/materialize/Further-Optimizations-for-Spill2Disk-a16ab75f807b47e494180b16b99246d2) to our spill-to-disk implementation. Now that we have additional disk space on replicas, a quick win to improve rehydration times of upsert sources would be to use RocksDB's native `merge` operator. This would make rehydration a pure write workload, rather than a read-then-write, and allow us to trade-off CPU for speed.

In the future, we might reconsider using RocksDB. See [this Slack thread](https://materializeinc.slack.com/archives/C01CFKM1QRF/p1710191616476659) for initial benchmarks of rehydration performance for upsert sources using different state backends.

## Action log

* **15 March 2024.** Set release date as April 19 with medium confidence.

**Comment by bosconi** [comment]
@rjobanp as discussed in Notion, this will go to Closed+Done (in Cluster Status) after this Friday's rollout?

Related PRs:
https://github.com/MaterializeInc/materialize/pull/27450
https://github.com/MaterializeInc/materialize/pull/27064

**Comment by benesch** [comment]
How much did the merge operator wind up improving rehydration time?

**Comment by rjobanp** [comment]
@benesch the initial PR didn't provide a meaningful speed up during my tests on staging, but with the merge of https://github.com/MaterializeInc/materialize/pull/27450 we do see about 10% improvement in the load-test cases (see that PR description)

I attempted another speed up by replacing `bincode` with `bitcode` but ran into some roadblocks - details here https://github.com/MaterializeInc/materialize/pull/27450#discussion_r1631661750

**Comment by benesch** [comment]
Got it! Bummer there wasn't more of a speedup. 

I still have a suspicion that something is afoot with our RocksDB configuration or implementation. I would expect rehydration to proceed about twice as fast as it does.

I think it's right to set this work down where we did, as we made the optimization we set out to make. But I think it's worth keeping an issue around to track the fact that upsert rehydration is still much slower than we'd like.

**Comment by bosconi** [comment]
@rjobanp can you set to this state after the rollout this Friday?

Cluster Team project: 
- Status:Done  
- Status Note: empty

Product Roadmap project:
- Status: GA
- Status Note: empty
- Completed: FY2025Q2 (May-July)

**Comment by rjobanp** [comment]
This will be closed after the release rolls out this week! should be done thursday

**Comment by benesch** [comment]
> But I think it's worth keeping an issue around to track the fact that upsert rehydration is still much slower than we'd like. (May be preferable to close this issue out and file a new one, but worth keeping a durable record around somewhere.)

Hey @bosconi @rjobanp — I think this note may have gotten lost! Upsert source rehydration time is still much slower than I'd expect it to be, so it'd be great to get an issue tracking the opportunity for further performance enhancements here.

**Comment by bosconi** [comment]
@benesch good catch! https://github.com/MaterializeInc/materialize/issues/28005 created to track further work.
@morsapaes FYI.

**Comment by benesch** [comment]
Wonderful, thank you!
