### ISSUE TITLE
storage/connections: remove flag for default SSH connections

### ISSUE THREAD

**Issue by morsapaes** [MaterializeInc/materialize#26011]
@guswynn: with #22871 merged, is there any remaining work to remove the `enable_default_kafka_ssh_tunnel` LD flag? This came up while discussing #25527. cc @jubrad

**Comment by guswynn** [comment]
Yes we can remove this! @jubrad you can fold this into your pr, or we can do it separately

**Comment by jubrad** [comment]
@guswynn good point, easy enough for me to do it in that pr
https://github.com/MaterializeInc/materialize/pull/25527
