### ISSUE TITLE
Datum::eq and Row::eq disagree

### ISSUE THREAD

**Issue by jamii** [MaterializeInc/materialize#2608]
```
jamie=> insert into foo values ('0');
INSERT 0 1
jamie=> insert into bar values ('-0');
INSERT 0 1

jamie=> (select * from foo) union (select * from bar);
 x 
---
 0
 0
(2 rows)

jamie=> select *, foo.x = bar.x from foo, bar;
 x | x | ?column? 
---+---+----------
 0 | 0 | t
(1 row)
```

**Comment by frankmcsherry** [comment]
This particular defect has been cleaned up (+0 and -0 being distinct). Do we know of other cases, and should we document these two methods as being the same (modulo Null and maybe NaN who knows)? 

cc: @sploiselle @benesch

**Comment by uce** [comment]
We might want to create a follow-up issue to document internally as a case to handle when adding new types (e.g. in architecture.md).

**Comment by frankmcsherry** [comment]
Closing this in favor of a more detailed discussion in https://github.com/MaterializeInc/materialize/issues/10566.
