### ISSUE TITLE
Support col_description()

### ISSUE THREAD

**Issue by RobinClowers** [MaterializeInc/materialize#26108]
### Feature request

Console uses Kysely to build type safe queries against materialize, and they recently started calling [col_description](https://github.com/kysely-org/kysely/pull/842), which means we can't upgrade to the latest version until Materialize supports this feature.

I also noticed [Table Plus uses this function](https://github.com/MaterializeInc/materialize/issues/19891).

**Comment by chaas** [comment]
Looks like it's a comment feature https://www.postgresql.org/docs/current/functions-info.html#FUNCTIONS-INFO-COMMENT

> col_description ( table oid, column integer ) → text
> Returns the comment for a table column, which is specified by the OID of its table and its column number. (obj_description cannot be used for table columns, since columns do not have OIDs of their own.)

We now support comments so it makes sense to add.

Postgres's sql defn
https://github.com/postgres/postgres/blob/5162f663fcbe837648ae28f00e18ed972f5e360b/src/backend/catalog/system_functions.sql#L322-L329
