### ISSUE TITLE
Support ALTER VIEW RENAME

### ISSUE THREAD

**Issue by rjnn** [MaterializeInc/materialize#2613]
This is a catalog only alteration, follow Postgres in supporting

`ALTER VIEW foo RENAME TO bar`

https://www.postgresql.org/docs/8.3/sql-alterview.html

**Comment by benesch** [comment]
Just a note that this is hard, because all downstream dependencies of the view need to be rewritten with the new name of the view. 

This is a downside of using SQL as the catalog serialization format.

**Comment by rjnn** [comment]
Yup, that makes sense. Could we add support for doing this only in cases where there are no downstream dependencies?

**Comment by benesch** [comment]
I actually don't think that's terribly easier than just rewriting all
downstream views. It's more that this is a day or two long project, not the
hour long project that it might initially appear.

**Comment by rjnn** [comment]
I think this should get done in 0.4. It's a nice QOL feature but one that interplays with refactors to pay down technical debt, which is a good fit for 0.4

**Comment by benesch** [comment]
@sploiselle implemented an 80% solution in #3469, so closing this out!
