### ISSUE TITLE
Support Common Table Expressions (CTE)

### ISSUE THREAD

**Issue by rjnn** [MaterializeInc/materialize#2617]
CTEs are primarily used in defining recursive queries, but non-recursive CTEs are simpler and also useful. They are often used by query builders that do inline-view definition style things without explicitly constructing hierarchies of views.

We should support CTEs, since we'd need them before we can support WITH RECURSIVE (#2516).

**Comment by jamii** [comment]
Seems easy to implement if we only allow WITH at the top level (ie not inside subqueries).

**Comment by rjnn** [comment]
Then let's do it soon! @cuongdo do you think we have space in 0.3?

**Comment by cuongdo** [comment]
@rjnn This seems to be 1-2 weeks of work, so it may fit. The unknown at this point is the other competing demands.

**Comment by rjnn** [comment]
I think I've changed my mind in light of the amount of refactoring we have since decided to do in the 0.3 timeframe. This can wait a release.
