### ISSUE TITLE
Regular expression whitespace inconsistencies

### ISSUE THREAD

**Issue by def-** [MaterializeInc/materialize#26204]
### What version of Materialize are you using?

v0.93.0

### What is the issue?

Seen in https://buildkite.com/materialize/nightlies/builds/7002#018e62f3-5dd2-4ebf-ae8a-91b7745b2c8b
```
Value type differs
ValidationErrorType.CONTENT_TYPE_MISMATCH: Value type differs at row index 0, column index 0 ('regexp_match(text_val_w_spaces, '.*')').
  Value 1 (Constant folding 1): '[' mAA m\n\t ']' (type: <class 'list'>)
  Value 2 (Constant folding 2): '[' mAA m']' (type: <class 'list'>)
  Query 1: SELECT regexp_match(text_val_w_spaces, '.*') FROM v_ctf_1_horiz WHERE ((text_empty NOT ILIKE 'a%b'));
  Query 2: SELECT regexp_match(text_val_w_spaces, '.*') FROM v_ctf_2_horiz WHERE ((text_empty NOT ILIKE 'a%b'));
```
v0.93.0 contains #26191, which I strongly suspect is causing the difference in whitespaces.

**Comment by def-** [comment]
Minimal reproducer:
```sql
CREATE OR REPLACE VIEW v_ctf_1_horiz (text_val_w_spaces) AS SELECT ' mAA m
	 '::TEXT;
SELECT regexp_match(text_val_w_spaces, '.*') FROM v_ctf_1_horiz;
```
The output in v0.92.1 was:
```
 regexp_match
--------------
 {" mAA m"}
(1 row)
```
While in v0.93.0 it is:
```
 regexp_match
--------------
 {" mAA m    +
          "}
(1 row)
```
This is actually the same result as in Postgres, so it seems like we fixed an issue, which is what dot_matches_new_line in the PR does. So this is by design and not an issue. I'll add an ignore in our output consistency test for this.

**Comment by def-** [comment]
@nrainer-materialize Why didn't the consistency check find this before when comparing against Postgres btw?

**Comment by nrainer-materialize** [comment]
> @nrainer-materialize Why didn't the consistency check find this before when comparing against Postgres btw?

It was a known inconsistency that was tracked with https://github.com/MaterializeInc/materialize/issues/22000. I will check if that one is completely fixed now.
