### ISSUE TITLE
parallel-workload: Sessions stay open even after everything is finished

### ISSUE THREAD

**Issue by def-** [MaterializeInc/materialize#26206]
### What version of Materialize are you using?

main

### What is the issue?

Noticed in https://github.com/MaterializeInc/materialize/pull/26165#issuecomment-2014063060
https://buildkite.com/materialize/nightlies/builds/7008
```
builtins.ValueError: Sessions are still running even though all threads are done: (['25182', 'u1', datetime.datetime(2024, 3, 21, 23, 38, 28, 774000, tzinfo=datetime.timezone.utc)], ['228656', 'u1', datetime.datetime(2024, 3, 21, 23, 38, 35, 808000, tzinfo=datetime.timezone.utc)], ['410162', 'u1', datetime.datetime(2024, 3, 21, 23, 38, 35, 668000, tzinfo=datetime.timezone.utc)], ['355316', 'u1', datetime.datetime(2024, 3, 21, 23, 38, 12, 739000, tzinfo=datetime.timezone.utc)])
```
Happens in every test, even without HTTP selects. We should debug this some more and fix it (or hopefully it's a test problem?)

ci-regexp: Sessions are still running even though all threads are done

**Comment by def-** [comment]
CC @ParkMyCar in case you have some insights

**Comment by ParkMyCar** [comment]
I think this might be a test issue. Specifically the `mz_sessions`s table gets updated asynchronously when a session is dropped, if I run the following scenario:
```
bin/mzcompose --find parallel-workload down && bin/mzcompose --find parallel-workload run default --threads=8 --runtime=500 --complexity=dml
```
The test fails because of outstanding sessions, but if I connect to the MZ instance running in Docker after the test completes, and `SELECT * FROM mz_internal.mz_sessions`, I see all of the sessions get cleaned up.

**Comment by benesch** [comment]
Agreed this looks like a test issue. I believe I tracked it down in https://github.com/MaterializeInc/materialize/pull/26165/commits/2a9150a0970cef3431a01a00b12b0aed4b087755.

**Comment by def-** [comment]
Perfect, I was hoping it was something simple like that, thanks.

**Comment by def-** [comment]
I'm still seeing this error even when closing all sessions, for example in https://buildkite.com/materialize/nightlies/builds/7048#018e7689-e18b-48d8-aabe-9fc6ab9820ba (seems unrelated to the PR):
```
Sessions are still running even though all threads are done: (['114195', 'u1', datetime.datetime(2024, 3, 25, 17, 4, 17, 163000, tzinfo=datetime.timezone.utc)], ['96035', 'u1', datetime.datetime(2024, 3, 25, 17, 6, 18, 88000, tzinfo=datetime.timezone.utc)], ['352853', 'u1', datetime.datetime(2024, 3, 25, 17, 5, 32, 392000, tzinfo=datetime.timezone.utc)], ['359256', 'u1', datetime.datetime(2024, 3, 25, 17, 11, 37, 844000, tzinfo=datetime.timezone.utc)], ['204893', 'u1', datetime.datetime(2024, 3, 25, 17, 4, 13, 686000, tzinfo=datetime.timezone.utc)], ['131434', 'u1', datetime.datetime(2024, 3, 25, 17, 7, 8, 707000, tzinfo=datetime.timezone.utc)], ['147315', 'u1', datetime.datetime(2024, 3, 25, 17, 14, 52, 190000, tzinfo=datetime.timezone.utc)], ['76919', 'u1', datetime.datetime(2024, 3, 25, 17, 16, 16, 142000, tzinfo=datetime.timezone.utc)], ['474233', 'u1', datetime.datetime(2024, 3, 25, 17, 10, 29, 107000, tzinfo=datetime.timezone.utc)], ['278905', 'u1', datetime.datetime(2024, 3, 25, 17, 5, 24, 52000, tzinfo=datetime.timezone.utc)], ['513437', 'u1', datetime.datetime(2024, 3, 25, 17, 2, 21, 649000, tzinfo=datetime.timezone.utc)], ['325561', 'u1', datetime.datetime(2024, 3, 25, 17, 6, 26, tzinfo=datetime.timezone.utc)], ['296159', 'u1', datetime.datetime(2024, 3, 25, 17, 5, 36, 11000, tzinfo=datetime.timezone.utc)], ['462069', 'u1', datetime.datetime(2024, 3, 25, 17, 19, 14, 786000, tzinfo=datetime.timezone.utc)])
```
Is there a way to map where that session came from? I tried searching for the ids in logs, but to no avail.

**Comment by def-** [comment]
Perfect, I'll look into adding something like that into parallel-workload to make it easier to debug this issue.

**Comment by def-** [comment]
I tried printing the pg_backend_pid in https://github.com/MaterializeInc/materialize/pull/26280 for all pg8000 connections that get started during the runs, and also for the HTTP API selects, but there is still a bunch of sessions staying open without a connection to any of them: https://buildkite.com/materialize/nightlies/builds/7081#018e7d13-4f8a-4c9f-862a-b76c0a736dd8
@ParkMyCar Is it possible that the webhook posts are also opening a session? I'll try commenting them out from the test and see if it still happens.

**Comment by benesch** [comment]
@def- I recommend monkey patching `pg8000.connect` to be sure that you've really captured all the connections. Something like this should work:

```
import pg8000

def connect(self, *args, **kwargs):
    conn = pg8000_connect(*args, **kwargs)
    print(...)
    return conn

pg8000_connect = pg8000.connect
pg8000.connect = connect
```

For example, there are some sneaky connections in data_ingest/executor.py that I think your current logging would not surface.

**Comment by def-** [comment]
Timing-wise it 's not these connections. I'll add the monkey-patch and try removing actions until I find what is causing the sessions. They don't seem to persist forever, so maybe just some long-running things in the background (maybe cancelled)

**Comment by ParkMyCar** [comment]
@def- it looks like you already tested but just to confirm webhooks do not open new sessions
