### ISSUE TITLE
Casting Error with `NULL`s and Lists

### ISSUE THREAD

**Issue by Ludwig-Uni** [MaterializeInc/materialize#26256]
### What version of Materialize are you using?

v0.92.1

### What is the issue?

Hi everyone, I believe to have found a bug in Materialize regarding casts:

When `NULL` is casted to a list type, and another `NULL` column without an explicit cast is in the same select list, the operation fails.
Reproduce:
```sql
SELECT NULL                   AS "a",
       CAST(NULL AS int list) AS "b";
-- ERROR:  internal error: column 1 is not of expected type ColumnType { scalar_type: List { element_type: Int32, custom_id: None }, nullable: false }: Null

-- Or, with a custom list type:
DROP TYPE IF EXISTS t;
CREATE TYPE t AS (x float, y text);  -- Just any example of a non-builtin type

SELECT NULL                 AS "a",
       CAST(NULL AS t list) AS "b";
-- ERROR:  CAST does not support casting from text to t list
```

The same query works as expected if:
- The explicit cast is to a scalar type (like `int`), instead of a list OR
- The explicit cast is from a non-`NULL` value (like `LIST[1, 2, 3]`), instead of `NULL` OR
- The first `NULL` is also explicitly casted to something OR
- The first value is not `NULL`

Examples:
```sql
SELECT NULL              AS "a",
       CAST(NULL AS int) AS "b";
-- Works as expected: The explicit NULL cast is not to a list.


SELECT NULL                      AS "a",
       CAST(LIST[2] AS int list) AS "b";
-- Works as expected: Something is explicitly casted to a list, but it's not NULL.


SELECT CAST(NULL AS text)     AS "a",
       CAST(NULL AS int list) AS "b";
-- Works as expected: NULL is explicitly casted to a list, but there are no other NULL columns without explicit casts.


SELECT 'test'                 AS "a",
       CAST(NULL AS int list) AS "b";
-- Works as expected: NULL is explicitly casted to a list, but there are no other NULL columns without explicit casts.
```

**Comment by ParkMyCar** [comment]
Hey @Ludwig-Uni, thank you for the thorough bug report! @sploiselle and I looked into this issue this morning and should have a fix out for it soon.
