### ISSUE TITLE
Docs: Add Eventbridge Pipes example

### ISSUE THREAD

**Issue by chuck-alt-delete** [MaterializeInc/materialize#26263]
### Documentation request

Eventbridge Pipes is a service that allows request batching in Eventbridge. This can be used in conjunction with the webhook source’s `BODY FORMAT JSON ARRAY` to vastly increase the throughput of records into Materialize.

We should either rewrite the eventbridge guide to have this be the standard procedure, or we should at least add it as a note near the top of the existing guide.

### Affected Pages

- https://materialize.com/docs/ingest-data/amazon-eventbridge/

**Comment by morsapaes** [comment]
Added a note to the guide [here](https://materialize.com/docs/ingest-data/amazon-eventbridge/#throughput), which then links to the reference documentation on [handling batched events](https://materialize.com/docs/sql/create-source/webhook/#handling-batch-events). I don't love the flow of the current guide, but something to revise when we have a better UX in the console to support webhook source configuration.
