### ISSUE TITLE
Metabase docs recommend duplicating view definitions?

### ISSUE THREAD

**Issue by benesch** [MaterializeInc/materialize#2627]
Just stumbled across this paragraph in the Metabase docs:

> Metabase will store comments alongside queries, and it’s a good practice to keep a verbatim copy of the view’s definition alongside places that use it. However, this same information is also retrievable with `SHOW CREATE VIEW <name>`. If you follow that practice, the text entry box would look like:

```
-- CREATE MATERIALIZED VIEW query01 as SELECT
--     ol_number,
--     sum(ol_quantity) as sum_qty,
--     sum(ol_amount) as sum_amount,
--     avg(ol_quantity) as avg_qty,
--     avg(ol_amount) as avg_amount,
--     count(*) as count_order
-- FROM
--     mysql_tpcch_orderline
-- WHERE
--     ol_delivery_d > date '1998-12-01'
-- GROUP BY
--     ol_number;
SELECT * FROM query01;
```

I don't think we should be calling this good practice. If someone adopted this practice in a real project, it would almost certainly lead to skew between the query in Metabase and the view definition in Materialize and confusion for end users. We seem to be working around some limitation of Metabase, that makes it hard to see through views? At the very least I think we should call out that this is a workaround for something, rather than claiming that copying view definitions around is unqualified best practice. Thoughts?

/cc @quodlibetor @sploiselle

**Comment by sploiselle** [comment]
Yeah, this was not sufficiently careful in its wording. Will fix.
