### ISSUE TITLE
frontegg: SCIM roles not consistently returned by API

### ISSUE THREAD

**Issue by maddyblue** [MaterializeInc/materialize#26355]
The `roles` returned by the `v1/api-token` and `v1/user/token/refresh` endpoints differ. The latter returns SCIM roles while the former does not. This causes `is_superuser()` to vary based on how users have logged in (generally via the console or not).

**Comment by mjibson** [comment]
I've confirmed that the `v2/api-token` endpoint also has this behavior.

**Comment by benesch** [comment]
Happily, this has been fixed by Frontegg! https://materializeinc.slack.com/archives/C02940WNMRQ/p1720445042351329?thread_ts=1711595875.336879&channel=C02940WNMRQ&message_ts=1720445042.351329
