### ISSUE TITLE
sql: DROP ... CASCADE can be slow

### ISSUE THREAD

**Issue by ParkMyCar** [MaterializeInc/materialize#26373]
### What version of Materialize are you using?

v0.94.2

### What is the issue?

Running a `DROP ... CASCADE` can be relatively slow because we collect all of the items to drop at the [planning stage](https://github.com/MaterializeInc/materialize/blob/main/src/sql/src/plan/statement/ddl.rs#L4077) and then is subject to a similar issue as seen in https://github.com/MaterializeInc/materialize/pull/26361

**Comment by chaas** [comment]
Looked at stats for current blue/green use cases and the drop can be as slow as 7s, which should be improved, but is not as severe as https://github.com/MaterializeInc/materialize/pull/26361.
@ParkMyCar ran some tests that are consistent with this number.
See https://materializeinc.slack.com/archives/C02FWJ94HME/p1712178602536649 for more details.
Moving this to the backlog for now.
