### ISSUE TITLE
Consistency formats/envelopes

### ISSUE THREAD

**Issue by nacrooks** [MaterializeInc/materialize#2638]
As the consistency information is getting more flexible (and specifically has been engineered to speak to Debezium more directly), I find myself having to deal with format/envelopes combinations for consistency as well as for sources. Current formats/envelopes that are supported are "Avro/Debezium, AvroOCF/Debezium, Bytes/Byo, Avro/Byo". Here Byo stands for the consistency topic format that y'all saw me demo.  Debezium stands for the format the the CDC outputs.

There are two options:

 **1) add new options to create source for consistency**. Specifically, we currently have with` (consistency=topicname)`. We could support, much like create source, both a format option and an envelope option, though I'm happy to merge them for now to avoid making it more complicated. Something like this: `(consistency=topicname, consistency_format=ByoAvro/DebeziumOcf)`This is obviously cluttering the create source command further. And as a second step it will be nice to create a separate create consistency source (or something like that) command. But for now, I'm wondering if people are ok with adding these additional options to the source.

**2) (my preferred solution) tie the format/envelope of the consistency topic to that of the source.** I'll note that it is not possible (currently) to assume that our sources with envelope debezium are actually generated by debezium (and thus use the debezium consistency format). As we seem to use debezium as a shortcut for before/after. If that were true, we could simply reuse the format/encoding of the actual source. To realise option 2), we should separate the current Debezium envelope option into two. One that is Before/After (but not necessarily generated by Debezium), and one that is actually a "true" Debezium envelope.  That second option is my preferred option as it doesn't add yet another parameter to create source.

Thoughts?

**Comment by nacrooks** [comment]
@quodlibetor @umanwizard @benesch @JLDLaughlin I recall you had the most involvement in the current formatting decisions of Create Source?

**Comment by frankmcsherry** [comment]
This might be massively oversimplifying, but what if the consistency topic was a sequence of instructions about where to find and what to do with the data? So, rather than binding all of this in CREATE SOURCE, much of it gets determined dynamically as part of reading the consistency topic. I'm imagining (note: not advocating for) something where records in the consistency topic/stream could look like
```
ConsistencyRecord {
    source: kafka://topicname/part/offset1-offset2
    timestamp: <time>
    encoding: text/avro/wtf
    envelope: ???
}
```
Some information like schema would need to be known at CREATE SOURCE time, but .. it seems like to curtail the complexity explosion something like this might be helpful? Or just complicating...

**Comment by nacrooks** [comment]
This isn't possible if you're reading from a Debezium consistency topic, for instance.  The Debezium consistency topic has a pre-determined format that we cannot touch. It also requires the Consistency Record to be in a fixed format itself. It seems suboptimal to force someone to write out a (for instance) Avro or Json consistency record if they are only dealing with CSV formats in their own sources.

**Comment by frankmcsherry** [comment]
Right. I'm definitely proposing trading away optimality for flexibility.

**Comment by nacrooks** [comment]
In this instance, we'd be back to problem 2) which is: we would initially
need to know whether the consistency topic follows the ConsistencyRecord
envelope you're suggesting, vs the Debezium envelope that Debezium outputs
(which would force us to distinguish between the BeforeAfter format vs
records actually generated by Debezium). There's also the "problem" that we
would need to detect in what format this ConsistencyRecord is written in
(Json,Avro, etc.). This seems to create a chicken and egg problem. I'm not
entirely sure what your proposed solution would bring us in terms of
flexibility?

>

**Comment by ruchirK** [comment]
I'm just recording something from a conversation with @nacrooks 

Do we use the Debezium format currently to ingest data from sources that were not populated by Debezium / do users actually want to use this format or do they want something more like kafka key val upsert semantics?

I don't think the debezium "format" makes a ton of sense outside of things that debezium exports. We're essentially giving fields in a schema the power to insert and retract things - which seems odd?

**Comment by benesch** [comment]
> do users actually want to use this format

Cockroach also exports records in this Debezium before/after format, FWIW. I'm not aware of any other uses of it.

My gut feeling is that we should just do (1) for now, to keep things simple. I think the design of `CREATE SOURCE` needs a complete rethink, now that we have support for `UPSERT` too, and I'm leery of changing its syntax in isolation. Put another way: it would definitely be nice not to clutter up `CREATE SOURCE` with more `WITH` options, and I would love to do that eventually, but I think we should batch all these `CREATE SOURCE` rough edges up and solve them in a single redesign, so that we make sure the design handles all the edge cases!

**Comment by nacrooks** [comment]
By (1) do you mean (2)? The one that fixes the expected consistency format to that specified by CREATE_SOURCE?

**Comment by benesch** [comment]
No I was thinking the one that adds a WITH option! The only constraint is that I don’t think we should change the `ENVELOPE DEBEZIUM` atm. But if you wanted to do (2) by adding a `is_fake_debezium` WITH option, or something like that, maybe that could work? I.e., tie the consistency format to the source format, and then add a WITH option for the one case where we need an additional knob?

**Comment by nacrooks** [comment]
Oh sorry, I thought you mean the one that did not change CREATE SOURCE.

If I understand correctly, you'd prefer to add a WITH option to Create Source than to tie the consistency format to the source format?

**Comment by benesch** [comment]
I'm fine with any solution that does not involve changing the syntax to `CREATE SOURCE`, is I think the shortest way of summarizing my position! If that's a `consistency_format` option, or a `envelope_is_really_in_debezium_format` option—either is fine with me!

**Comment by nacrooks** [comment]
Thanks!

**Comment by elindsey** [comment]
A bit less applicable without BYO now. We can revisit if we end up with demand for different consistency formats.
