### ISSUE TITLE
storage: remove progress subsources

### ISSUE THREAD

**Issue by benesch** [MaterializeInc/materialize#26389]
## Summary

Remove progress subsources from Materialize.

## Details

Over the past year, progress subsources have been shown to be confusing. They're not a subsource like other subsources, because they don't contain data. @morsapaes is fond of claiming that no users have ever once queried a progress subsource. They've caused friction in the following interfaces:

  * The console's workflow graph
  * The console's subsource list
  * The output of `SHOW SOURCES`
  * The output of `SHOW SUBSOURCES`
  * The documentation for the last two commands

In all the above cases, the progress subsource has been seen as clutter that's not worth explaining. That's a fairly clear indication that we should consider their removal.

Also, as `mz_source_statistics` has improved, it's satisfied many of the use cases that were initially envisioned for the progress subsource. In particular, the console's new source progress page is entirely based on the source statistics table, and not at all based on the progress subsource.

I still think the information in the progress source is valuable, but we've not yet found a user who has a sophisticated enough understanding of consistency to want the progress subsource. Specifically, a progress subsource can tell you the upstream LSN or offset that a query in Materialize was up to date with:

```
BEGIN;

SELECT * FROM my_source_progress;
-- Returns some LSN.

SELECT * FROM my_computed_value;
-- Returns the results I care about.

COMMIT;
```

There is no way to accomplish the above without a progress subsource.

In #20208, we have an idea for de-emphasizing the progress subsource: having the source return its progress information when queried directly. Then the progress subsource can go away. It won't clutter the output of `SHOW SOURCES` or the console's interfaces. But power users in the know can query the source directly to get at progress information.

Unfortunately, that's a large migration that will take quite a bit of time. And so that led us to the idea in this issue: what if we preemptively removed user access to the progress subsources? We don't think anyone is presently depending on them, but every day that passes is a day that someone might introduce a dependency on the progress subsource, which makes the migration harder. 

I don't feel great about taking this away from users, but since 1) we haven't seen anyone make use of them yet, 2) we _have_ seen many users get confused about them, and 3) we have a path for bringing the progress information back, and 4) the path towards our ideal design is plausibly _easier_ if we preemptively remove them, I feel like removing them is likely the right thing to do.

Still TODO is the exact design of the migration. Can we just rip progress subsources out? Are there actually no prod dependencies on progress subsources? Do we need to leave something around so `mz_support` can still access progress subsources, or some alternative syntax like `SELECT * FROM PROGRESS <source>`, for debugging reclocking?

**Comment by benesch** [comment]
Removing progress sources from `SHOW SOURCES` works for me, as long as we're all certain that we have a path to removing them entirely as a concept in the not too distant future.

**Comment by sploiselle** [comment]
@RobinClowers where do we pull the objects from for the dependency graph in the UI? want to make sure progress subsources don't show up there.

**Comment by RobinClowers** [comment]
@sploiselle We explicitly filter them out here: https://github.com/MaterializeInc/console/blob/7ccdd68e6dce814d5842ab8853da172dec793652/src/api/materialize/useWorkflowGraph.ts#L65

**Comment by morsapaes** [comment]
Closing as this work will be folded into #20208. Opened #26814 for the specific task of filtering progress subsources from the output of `SHOW` commands.
