### ISSUE TITLE
Bug in before/after envelope avro decoding

### ISSUE THREAD

**Issue by nacrooks** [MaterializeInc/materialize#2639]
This might be my lack of understanding of the code, but shouldn't the before image of debezium generate a `(before, time, -1)` tuple in decode/avro.rs

```
    /// give a session a plain value
    fn give_value<'a>(
        &mut self,
        bytes: &[u8],
        _: Option<i64>,
        session: &mut PushSession<'a, (Row, Timestamp, Diff)>,
        time: Timestamp,
    ) {
        match self.decoder.decode(bytes) {
            Ok(diff_pair) => {
                self.events_success += 1;
                if let Some(before) = diff_pair.before {
                    session.give((before, time, 1));
                }
                if let Some(after) = diff_pair.after {
                    session.give((after, time, 1));
                }
            }
            Err(err) => {
                self.events_error += 1;
                error!("avro deserialization error: {}", err)
            }
        }
    }
```

**Comment by nacrooks** [comment]
@frankmcsherry, can you confirm?

**Comment by frankmcsherry** [comment]
It looks 100% wrong to me!

**Comment by frankmcsherry** [comment]
@umanwizard indicated that it might be correct, because of how it is used elsewhere. But in any case, this stays open until someone writes some docs for this method (and ideally others like it).

**Comment by umanwizard** [comment]
See https://github.com/MaterializeInc/materialize/pull/2641

**Comment by umanwizard** [comment]
@frankmcsherry If we think the `DecoderState` API should have better documentation, can we make that a separate issue? I don't think it is related to this specific code, which existed before `DecoderState` landed.

**Comment by frankmcsherry** [comment]
Sounds good. I'll file an issue about docs.

**Comment by ruchirK** [comment]
I think we can close this issue now?
