### ISSUE TITLE
"Parallel Workload (100 threads)" fails with "Failed to receive start signal from leader"

### ISSUE THREAD

**Issue by nrainer-materialize** [MaterializeInc/materialize#26422]
### What version of Materialize are you using?

25ae696b1f7bd24ff0c971093a283871e03201b5

### What is the issue?

https://buildkite.com/materialize/nightlies/builds/7222

```
materialize.parallel_workload.worker_exception.WorkerFailedException: ^^^ +++ Thread worker_37 failed, exiting
("{'S': 'ERROR', 'C': 'XX000', 'M': 'Failed to receive start signal from leader'}", 'COPY (SELECT * FROM "db-pw-1712189137-0"."s-0"."t-2") TO \'s3://copytos3/86\' WITH (AWS CONNECTION = aws_conn, FORMAT = \'csv\');')
```

This occurred in several retries.

**Comment by nrainer-materialize** [comment]
I will try to bisect.

**Comment by nrainer-materialize** [comment]
Not a release-blocker because copy-to-s3 is not released yet.

**Comment by nrainer-materialize** [comment]
> @def- @nrainer-materialize the issue seems to be that the path being copied to is being used more than once during this parallel workload test (the `randrange(100)` isn't providing enough variance to ensure each run will use a different path):
> 
> https://github.com/MaterializeInc/materialize/blob/172211192976a041bf7e261319f6f3360634613e/misc/python/materialize/parallel_workload/action.py#L405
> 
> and in this recent PR #25857 we now error if there are any existing objects in the specified S3 path on a copy.
> 
> The first error visible in the log is
> 
> ```
> 'S3 bucket path is not empty, contains: ["46/batch-t3616-0000-0001.csv", "46/batch-t3616-0001-0001.csv", "46/batch-t3616-0002-0001.csv", "46/batch-t3616-0003-0001.csv", "46/batch-t3616-0004-0001.csv", "46/batch-t3616-0005-0001.csv", "46/batch-t3616-0006-0001.csv", "46/batch-t3616-0007-0001.csv", "46/batch-t3616-0008-0001.csv", "46/batch-t3616-0009-0001.csv", "46/batch-t3616-0010-0001.csv", "46/batch-t3616-0011-0001.csv", "46/batch-t3616-0012-0001.csv", "46/batch-t3616-0013-0001.csv", "46/batch-t3616-0014-0001.csv", "46/batch-t3616-0015-0001.csv"]\'
> ```
> 
> and then the `Failed to receive start signal from leader` happens subsequently

Ok! So, we should be good if we increase this value?

**Comment by rjobanp** [comment]
> Ok! So, we should be good if we increase this value?

Ideally we'd be able to enforce the variant that a path is never re-used across the parallel workload tests, but if that's difficult to do, we want to make the random range large enough that it's very unlikely the same value would be re-used

**Comment by def-** [comment]
Why is it not allowed to reuse a path? I did it like this by design.
