### ISSUE TITLE
sql/sources/pg: allow uncastable types in publication if they are not referenced

### ISSUE THREAD

**Issue by sploiselle** [MaterializeInc/materialize#26465]
### What version of Materialize are you using?

v0.95.0

### What is the issue?

If a user has a table in their publication that contains `regclass`, we error suggesting that they should use `TEXT COLUMNS` to allow its ingestion irrespective of its inclusion as a subsource.

**Comment by sploiselle** [comment]
The new subsource dependency structure makes a fix for this issue non-trivial.

In the future version of PG sources and subsources, the table casts are determined for the entire publication, i.e. if you are applying `TEXT COLUMNS`, it must be done at the publication level. However, we also have a stipulation that `TEXT COLUMNS` only reference columns that are included in a subsource (this is only a sanity check; maybe it's overkill). i.e. if you have a `regclass` column in a table in the publication you must ingest it and must specify it as `TEXT COLUMNS`.

In the future, though, the source itself will have no notion of what subsources exist for it and which tables it should store casts for.

The most natural solution here is that adding a subsource to a source should determine which casts to use, as well as "bring them" to the source itself.

**Comment by benesch** [comment]
Thanks for filing! Labeled as a storage bug and [added to the mega tracker](https://github.com/MaterializeInc/materialize/issues/24755).
