### ISSUE TITLE
30% performance regression in FastPathFilterNoIndex

### ISSUE THREAD

**Issue by def-** [MaterializeInc/materialize#26481]
### What version of Materialize are you using?

2abcd90ac3

### What is the issue?

Seen in https://buildkite.com/materialize/nightlies/builds/7263#018eb32d-5f3c-4995-b907-ee8b2a7f0782
There was only one PR merged for this nightly run, so this is a regression caused by https://github.com/MaterializeInc/materialize/pull/26084
@frankmcsherry @antiguru  Do we want to accept this in light of the memory improvements or can something be done about the regression?
```
NAME                                | TYPE      |      THIS       |      OTHER      |  Regression?  | 'THIS' is:
----------------------------------------------------------------------------------------------------
FastPathFilterNoIndex               | wallclock |           0.131 |           0.103 |    !!YES!!    | 28.3 pct   more/slower
```
If something can be done about it, we should probably consider this a release blocker for v0.96

**Comment by antiguru** [comment]
I've tried to reproduce this issue on staging, comparing v0.95.0 with v.94.2. Looking at the CPU profile, we're spending the same amount of time in the same places (delta stack differences), so I think this is noise caused by another part of the system.

**Comment by antiguru** [comment]
Trace v0.95: https://grafana.dev.materialize.com/explore?schemaVersion=1&panes=%7B%229nm%22%3A%7B%22datasource%22%3A%22e47e25f5-623b-4790-b2eb-a11c3137d7b4%22%2C%22queries%22%3A%5B%7B%22refId%22%3A%22traceId%22%2C%22datasource%22%3A%7B%22type%22%3A%22tempo%22%2C%22uid%22%3A%22e47e25f5-623b-4790-b2eb-a11c3137d7b4%22%7D%2C%22queryType%22%3A%22traceql%22%2C%22limit%22%3A1%2C%22tableType%22%3A%22traces%22%2C%22query%22%3A%22de89006489f64b455321de1514869f89%22%7D%5D%2C%22range%22%3A%7B%22from%22%3A%22now-15m%22%2C%22to%22%3A%22now%22%7D%7D%7D&orgId=1

Trace v0.94.2: https://grafana.dev.materialize.com/explore?schemaVersion=1&panes=%7B%22hla%22:%7B%22datasource%22:%22e493dba3-b407-4300-8211-7ab8d29671a2%22,%22queries%22:%5B%7B%22refId%22:%22traceId%22,%22datasource%22:%7B%22type%22:%22tempo%22,%22uid%22:%22e493dba3-b407-4300-8211-7ab8d29671a2%22%7D,%22queryType%22:%22traceql%22,%22limit%22:1,%22tableType%22:%22traces%22,%22query%22:%221bb2dc88c882c67a930ec1e7f6e5f7d3%22%7D%5D,%22range%22:%7B%22from%22:%22now-15m%22,%22to%22:%22now%22%7D%7D%7D&orgId=1
