### ISSUE TITLE
copy-to-s3-minio.td:88:1: error: executing query failed: db error: ERROR: Failed to receive start signal from leader

### ISSUE THREAD

**Issue by def-** [MaterializeInc/materialize#26509]
### What version of Materialize are you using?

38a9b7f57a46 (Pull Request #26502)

### What is the issue?

Seen in https://buildkite.com/materialize/tests/builds/80162#018ec08e-b1ab-4fd7-92a4-635fe030fbb1

Seems to happen without writing to the same location twice:
```
copy-to-s3-minio.td:88:1: error: executing query failed: db error: ERROR: Failed to receive start signal from leader: ERROR: Failed to receive start signal from leader
     |
  12 | $ postgres-execute c ... [rest of line truncated for security]
  21 | > CREATE SECRET aws_ ... [rest of line truncated for security]
  26 |     SECRET ACCESS KE ... [rest of line truncated for security]
  52 | contains:only 's3:// ... [rest of line truncated for security]
  87 | # functions like now() should work in the s3 path
  88 | > COPY t TO 's3://copytos3/test/1' || TO_CHAR(now(), 'YYYY-MM-DD')
     | ^
+++ !!! Error Report
1 errors were encountered during execution
files involved: copy-to-s3-minio.td
```
Looks unrelated to the PR to me.

Edit: Same in AWS Localstack test: https://buildkite.com/materialize/nightlies/builds/7281#018ebec3-9fac-4be4-8f2a-8a92b88b7b57

ci-regexp: ERROR: Failed to receive start signal from leader

**Comment by rjobanp** [comment]
Hasn't happened anytime recently - closing this since I think it's been resolved https://buildkite.com/organizations/materialize/analytics/suites/testdrive/tests/018e5ca2-472d-7fa9-b818-07db3d6856dd?branch=main
