### ISSUE TITLE
Large Pg transactions require huge amounts of clusterd memory (for Pg source)

### ISSUE THREAD

**Issue by def-** [MaterializeInc/materialize#26514]
### What version of Materialize are you using?

e5bb28937e

### What is the issue?

![profile004](https://github.com/MaterializeInc/materialize/assets/2335377/9e529bc3-08e7-46cb-b357-32aef68ad164)
[prof-materialized-cluster-u3-replica-u3-2024-04-09_04:57:35.pb.gz](https://github.com/MaterializeInc/materialize/files/14913866/prof-materialized-cluster-u3-replica-u3-2024-04-09_04.57.35.pb.gz)
Failing in bounded memory test: https://buildkite.com/materialize/nightlies/builds/7285#018ec00f-ac81-4ca5-a2ed-482ac5e69cb4
As a workaround I'll bump the available memory even further.

**Comment by def-** [comment]
Since this test scenario was just added in #26287 I assume this is no regression

**Comment by benesch** [comment]
@def- @nrainer-materialize @petrosagg is this perhaps fixed now that https://github.com/MaterializeInc/materialize/pull/26267 is merged?

**Comment by def-** [comment]
I'll check now.
