### ISSUE TITLE
Figure out why `OptimizerTrace(true, ...)` leaks memory

### ISSUE THREAD

**Issue by aalexandrov** [MaterializeInc/materialize#26569]
### What version of Materialize are you using?

v0.96.0-dev (6a58ef6e9)

### What is the issue?

Taken from #26504, which introduces a feature flag `enable_broken_optimzier_trace` which forces `OptimizerTrace(true, ...)` everywhere. For prior discussion see [here](https://github.com/MaterializeInc/materialize/pull/26504#discussion_r1559071250) and [here](https://github.com/MaterializeInc/materialize/pull/26504#issuecomment-2047757752).

This loop is not causing a leak:

```bash
while true; do 
  psql --set verbosity=verbose \
    -c 'set emit_plan_insights_notice = true' \
    -c 'select count(*) from bids b left join users u on (b.buyer = u.id)' > /dev/null
done
```

However, this loop

```bash
while true; do
  psql \
    -c 'explain plan insights as json for select count(*) from bids b left join users u on (b.buyer = u.id)' > /dev/null
done
```

is not causing a leak only when `enable_broken_optimzier_trace = false` (which is consistent with the current behavior in `main`), but is causing a leak when `enable_broken_optimzier_trace = true`. I'll open a separate issue to investigate.

I'm attaching [a series of heap profiles](https://github.com/MaterializeInc/materialize/files/14935386/memory_leak.zip) taken while running the leaking version of the loop. If you open them side by side you can see that the right-most part of the flame graph is growing. I suspect that somebody is holding on to `Span` data longer than expected.

**Comment by def-** [comment]
[prof-mz_1-2024-04-10_14 30 36.pb.gz](https://github.com/MaterializeInc/materialize/files/14935452/prof-mz_1-2024-04-10_14.30.36.pb.gz)
[prof-mz_2-2024-04-10_14 30 36.pb.gz](https://github.com/MaterializeInc/materialize/files/14935454/prof-mz_2-2024-04-10_14.30.36.pb.gz)
![profile001](https://github.com/MaterializeInc/materialize/assets/2335377/d7e1a0b6-11e5-43b2-b801-2ae652538066)

**Comment by aalexandrov** [comment]
The weirdest part for me is that I see the leak when

```
let _dispatch_guard = explain_ctx.dispatch_guard();
```

comes from the `ExplainContext::Plan` path, but not when it comes from the `ExplainContext::PlanInsightsNotice` path. The former happens when you run

```bash
psql -c 'explain plan insights as json for select count(*) from bids b left join users u on (b.buyer = u.id)' > /dev/null
```

in a loop. The latter happens when you run

```bash
  psql --set verbosity=verbose \
    -c 'set emit_plan_insights_notice = true' \
    -c 'select count(*) from bids b left join users u on (b.buyer = u.id)' > /dev/null
```

in a loop.

**Comment by guswynn** [comment]
@aalexandrov is it possible we are spawning a task from one of the functions that is called with an active dispatch guard?

Also, do you think its worth it now for me to rebase https://github.com/MaterializeInc/materialize/pull/23124 and get it working on main?

**Comment by aalexandrov** [comment]
> @aalexandrov is it possible we are spawning a task from one of the functions that is called with an active dispatch guard?

All 

```rust
let _dispatch_guard = explain_ctx.dispatch_guard();
```

are scoped to a `pipeline` function defined and executed in `mz_ore::task::spawn_blocking(...)` that represents the optimizer pipeline that needs to be executed off-thread.

> Also, do you think its worth it now for me to rebase #23124 and get it working on main?

Ah, either I forgot about this or I think we landed it. I'll take a look and see if this fixes the issue.
