### ISSUE TITLE
Support reading from Kafka stream as of a specific offset

### ISSUE THREAD

**Issue by rjnn** [MaterializeInc/materialize#2656]
Kafka equivalent to #2294.

Just a heads up that one prospect gave me the valuable feedback that this feature is super important because oftentimes the start of the stream is full of bad dev data and things only iron out (in terms of schema being ironed out, all columns being present, NULL treatment, etc.) after some point in time. They know the offset at which they want to read, but they do need the knob to keep Materialize from throwing parsing errors or other such things before that point. (e.g. if they switched out Avro schemas in a backward-incompatible way)

Forked from #1210, which is a different topic (but not entirely unrelated?).

**Comment by frankmcsherry** [comment]
It would be good to check which of these frameworks allow subsetting streams as a metadata action on their side. It seems like the sort of thing they should support (for this sort of reason) and if they do we can save adding the complexity ourselves.

**Comment by rjnn** [comment]
So on this particular issue, Kafka just expects the consumer to set the `seek(offset)` parameter on the client-side, before you start reading. So we do have to implement it as a "WITH" option.

But in general, that is a good point and a helpfu; reminder! We should ensure we don't duplicate effort if things are a trivial operation on the broker side.

**Comment by frankmcsherry** [comment]
I think this is plausibly fixed in #2726, is that right @umanwizard ?

**Comment by umanwizard** [comment]
I think we need to (1) land per-partition offsets, and (2) document it, before we can call this done. Assigning myself.

**Comment by awang** [comment]
@umanwizard @JLDLaughlin i think this is now done?  Can we close this issue?
