### ISSUE TITLE
Allow BYO Consistency in the form of a function

### ISSUE THREAD

**Issue by wangandi** [MaterializeInc/materialize#2659]
Suggested by a prospect.

Currently, in order for BYO consistency to work, you need an extra kafka topic which stores all the timestamps that records at particular offsets are supposed to have.

In practicality, a user using BYO consistency in production would most likely be using a piece of software that is running some function to auto-generate the timestamps that will then be fed into the kafka topic. Given this, it would be more convenient for the user to just pass the function directly to materialize instead of having to write their own consistency kafka topic generator.

cc: @nacrooks

**Comment by wangandi** [comment]
Concerns I personally have that we probably want to think through:
* Security: We definitely don't want materialize to run arbitrary lambdas.
   * What would the API for defining the timestamp function look like?
* Performance impact of running dynamic code

**Comment by nacrooks** [comment]
I agree with the above concerns.  It also seems like generating the consistency metadata is most readily done when you actually generate/write the data as opposed to post-hoc.

**Comment by benesch** [comment]
Closing as (very) stale. BYO has morphed into CDCv2, and even that isn't enabled at the moment.
