### ISSUE TITLE
DROP CLUSTER REPLICA on HTTP SQL API returns success, but replica still exists

### ISSUE THREAD

**Issue by def-** [MaterializeInc/materialize#26612]
### What version of Materialize are you using?

d940c979ef (Pull Request #26550)

### What is the issue?

This happened in https://buildkite.com/materialize/nightly/builds/7371#018ecd5d-8b13-4702-96e9-dca439954274 (on PR https://github.com/MaterializeInc/materialize/pull/26550)
```
[worker_90] CREATE CLUSTER "cluster-23" REPLICAS("r-1" (SIZE = '1'), "r-2" (SIZE = '1'));
[worker_9] DROP CLUSTER REPLICA "cluster-23"."r-1"; [HTTP]
[worker_12] Query failed: CREATE SOURCE "db-pw-1712842662-5"."s-12"."wh-43" IN CLUSTER "cluster-23" FROM WEBHOOK BODY FORMAT JSON INCLUDE HEADERS INCLUDE HEADER 'ih0' as ih0 INCLUDE HEADER 'ih1' as ih1 INCLUDE HEADER 'ih2' as ih2 INCLUDE HEADER 'ih3' as ih3 CHECK (WITH (BODY, HEADERS) map_length(HEADERS) = map_length(HEADERS) AND BODY = BODY); {'S': 'ERROR', 'C': 'XX000', 'M': 'cannot create source in cluster with more than one replica'}
```
The HTTP query was sent over the stable SQL API, it returned a 200 return code and had no `"error"` field. So I assumed this to have worked,but the following `CREATE SOURCE` failing indicates that the replica was not successfully dropped (yet). According to the services.log the `DROP CLUSTER REPLICA` was never executed, it's simply missing.

I haven't investigated further.

**Comment by chaas** [comment]
@def- Do you know if this is a regression, or something that's probably been around for a while and only just discovered?

**Comment by chaas** [comment]
I tried reproing this manually on staging + locally and can't seem to repro. I ran the `DROP CLUSTER REPLICA` command via curl and confirmed the replica is dropped. Locally I tried it with both the http address and the new balancer http address and it worked for both. So it looks like not a widespread bug, but perhaps a race condition or something - very strange it would return a 200 but never execute the drop. We'll have to do some more investigation

**Comment by def-** [comment]
It is probably not a regression, I just extended parallel-workload with this functionality. It happens in about one in 5 runs with this diff on main:
```
diff --git a/misc/python/materialize/parallel_workload/action.py b/misc/python/materialize/parallel_workload/action.py
index e5e81724bc..b5f7e4eb58 100644
--- a/misc/python/materialize/parallel_workload/action.py
+++ b/misc/python/materialize/parallel_workload/action.py
@@ -1154,7 +1154,7 @@ class DropClusterReplicaAction(Action):
             query = f"DROP CLUSTER REPLICA {cluster}.{replica}"
             try:
                 # TODO(def-) Reenable http when #26612 is fixed
-                exe.execute(query, http=Http.NO)
+                exe.execute(query, http=Http.YES)
             except QueryError as e:
                 # expected, see #20465
                 if (
```
with `bin/mzcompose --find parallel-workload down && bin/mzcompose --find parallel-workload run default --runtime=1500 --threads=100`

**Comment by def-** [comment]
This actually seems to be a problem of my test implementation! I'll debug it, sorry for the noise.

**Comment by chaas** [comment]
Thanks for figuring it out!
