### ISSUE TITLE
Implement temporary views

### ISSUE THREAD

**Issue by rjnn** [MaterializeInc/materialize#2661]
One solution is to add support for session temporary view names, e.g.

`CREATE TEMPORARY VIEW foo AS ...`. When that PG session ends, those views are dropped.

This is helpful independently as a SQL feature with multiple requests, but I do want to call out one ergonomic reason why this is immediately useful: `TAIL` currently requires that you name a view. A prospect wants to TAIL queries for a rich variety of queries that are issued ad-hoc. Creating a view and tailing each one of them would clog up the namespace quite a bit. They want to avoid that, so this feature would alleviate that. An alternative is to support `TAIL <statement>` but there was some pushback that this would introduce further technical debt in the coordinator.

**Comment by JLDLaughlin** [comment]
Closed with #3038, materialized temporary views still not implemented: https://github.com/MaterializeInc/materialize/issues/3105
