### ISSUE TITLE
adapter: decoding large peek responses can maybe slowdown the Coordinator?

### ISSUE THREAD

**Issue by ParkMyCar** [MaterializeInc/materialize#26712]
### What version of Materialize are you using?

v0.96.2

### What is the issue?

Currently `clusterd` will respond to a peek with `ProtoPeekResponse` which contains a list of `ProtoRow`s. `environmentd` then spends a ton of CPU time and memory decoding these `ProtoRow`s into `Row`s ([PolarSignals](https://pprof.me/e4ad962dc507515275db00625449843c)). I'm not totally positive, but it seems like this decoding _might_ be happening on the Coordinator's main thread? At the very least at the same time we were decoding this data, in the same environment we saw a "controller_ready" Coordinator message that took ~38 seconds.

Encoding from `Row` to `ProtoRow` and then later decoding `ProtoRow` back to `Row` seems unnecessary in this case since, AFAIU, the compute protocol requires that `environmentd` and `clusterd` are the same version, and `Row` already has it's own serialization format. What would be great is if `ProtoPeekResponse` could be something like:
```
message ProtoPeekResponse {
  repeated uint64 offsets = 1;
  bytes rows = 2;
}
```
Using `bytes::Bytes` the `rows` blob would be deserialized with zero copies, and then `environmentd` could stream out a peek response over pgwire by iterating over `offsets`.

Or possibly:
```
message ProtoPeekResponse {
  repeated bytes rows = 1;
}
```
Assuming `prost` is smart enough to create a `Vec<bytes::Bytes>` here that borrows from the underlying buffer read off the network.

**Comment by maddyblue** [comment]
The above sounds fine to me. If there are other objections to it, we should at the least have coord do a blind handover to the adapter session task which can do any needed decoding tasks instead.
