### ISSUE TITLE
Rename the `mz_introspection` cluster

### ISSUE THREAD

**Issue by teskje** [MaterializeInc/materialize#26731]
### Feature request

The term "introspection" for this cluster is confusing since we use the term normally to refer to per-replica dataflow introspection, which is not what this cluster is about. The cluster exists to speed up the serving of queries against catalog relations, and its name should reflect that. Plus, freeing the `mz_introspection` name will allow us to introduce a schema by the same name to hold the per-replica introspection relations without causing utter confusion.

Proposed alternative names (by @benesch):
* `mz_catalog`
* `mz_catalog_serve`

[Slack thread.](https://materializeinc.slack.com/archives/C063H5S7NKE/p1713368560676129)

**Comment by benesch** [comment]
Thanks for filing this, @teskje! The issue description said `mz_cluster` and `mz_cluster_serve` rather than `mz_catalog` and `mz_catalog_serve`—I'm assuming that was a typo and took the liberty of updating the issue description.
