### ISSUE TITLE
adapter: expose freshness of `mz_frontiers`

### ISSUE THREAD

**Issue by benesch** [MaterializeInc/materialize#26748]
The read and write frontiers of each source, table, index, and materialized view is periodically written to the [`mz_frontiers`](https://materialize.com/docs/sql/system-catalog/mz_internal/#mz_frontiers) table. The documentation notes this caveat:

> At this time, we do not make any guarantees about the freshness of these numbers.

Today, the implementation emits updated frontiers for all objects, in a single write, about once per second but, as the documentation warns, users should not rely on this. A hiccup in the coordinator might cause frontiers to be late. Or we might change the implementation to emit frontiers less frequently, or update different objects' frontiers at different frequencies.

Some consumers of this data, like the workflow graph in the console, want to determine how fresh the frontiers in the table are. This shouldn't be unduly constraining for us, as we still wouldn't provide _guarantees_ about freshness.

The current proposal on the table is to include the timestamp oracle's current time (roughly `SELECT mz_now()` under `strict serializable` isolation) at the time the frontiers are written to the table. There are at least two ways to do this:

  1. Include a `timestamp_oracle_time mz_timestamp` column in `mz_frontiers`. This would allow us flexibility in the future to update just _part_ of the table, reflecting that some rows were fresher than others.
  2. Add a new table `mz_timestamp_oracles (name text, time mz_timestamp)` that's updated transactionally with `mz_frontiers`. This would require that we continue to always update the table in its entirely, but reflects the fact that we technically have multiple timestamp oracles under the hood, and allows us flexibility to lean further into that world in the future.

The workflow graph in the console would then be able to assess whether source ingestion was falling behind the timestamp oracle by comparing the source's recorded write frontier to the timestamp oracle's recorded current time—that comparison might itself be on data some number of seconds in the past, but _both_ data points will be from the same moment in the past, and so the comparison will not be subject to skew.

To work around the lack of this feature for the workflow graph in the console, @SangJunBak is currently planning to compare the source's write frontier in `mz_frontiers` against the timestamp oracle's time fetched via `SELECT mz_now()`. This has the defect that we're relying on the data in `mz_frontiers` to be somewhat fresh—exactly what the documentation tells us not to do! We're planning to use larger tolerance (say, 10s) than ideal to account for this. We all feel reasonably good relying on the data in `mz_frontiers` to be no more than 10s stale, despite the warning in the documentation.

Slack conversation: https://materializeinc.slack.com/archives/C06GZ7GBKB5/p1713542474137569?thread_ts=1713425816.754639&cid=C06GZ7GBKB5

cc @chaas @teskje @SangJunBak

**Comment by chaas** [comment]
I'm reviving this issue in case it's relevant to current freshness work @teskje @SangJunBak . If not, feel free to move it back to the backlog

**Comment by benesch** [comment]
Ah indeed, it's tightly related! I think we've gotten comfortable with the idea of using the current wallclock time rather than the timestamp oracle time. And with that lens, the proposal in (1) is the spiritual predecessor of the `mz_wallclock_lag_history` table that @teskje is presently designing. So I think we can call this closed in favor of the MVP freshness metric epic (https://github.com/MaterializeInc/materialize/issues/28097).
