### ISSUE TITLE
postgres inconsistency: ERROR:  Evaluation error: null character not permitted

### ISSUE THREAD

**Issue by def-** [MaterializeInc/materialize#26754]
### What version of Materialize are you using?

main

### What is the issue?

```sql
DROP TABLE IF EXISTS mz_evaluation;
CREATE TABLE mz_evaluation (row_index INT, int2_val INT2);
INSERT INTO mz_evaluation VALUES (5, 0::INT2);
INSERT INTO mz_evaluation VALUES (7, 32767::INT2);
SELECT
  upper(chr(int2_val))
FROM
  mz_evaluation
WHERE (row_index IN (5, 7))
ORDER BY row_index ASC
LIMIT 0;
```
On Postgres:
```
 upper
-------
(0 rows)
```
On Materialize:
```
psql:x.sql:13: ERROR:  Evaluation error: null character not permitted
```

ci-regexp: Error 1: 'Evaluation error: null character not permitted'

**Comment by def-** [comment]
I think this is actually just Materialize choosing a different evaluation order. @nrainer-materialize Do we have a good way to fix this in the postgres consistency check?

**Comment by nrainer-materialize** [comment]
This is an interesting find! It is about the limit clause.

**Comment by nrainer-materialize** [comment]
Some more insights.

* `SELECT chr(0::INT2);` causes `ERROR:  Evaluation error: null character not permitted` in both mz and Postgres.
* `SELECT chr(32767::INT2);` succeeds in both.
* Doing a `SELECT` with `LIMIT 1` will fail regardless of whether `chr(0::INT2)` is within the rows to be fetched. In other words, fetching from the table above with these two values will fail with `LIMIT 1` for both `ORDER BY row_index ASC` and `ORDER BY row_index DESC`.
* The difference only occurs for `LIMIT 0`.

CC @ggevay
