### ISSUE TITLE
System catalog object names should be unique

### ISSUE THREAD

**Issue by RobinClowers** [MaterializeInc/materialize#26849]
### What version of Materialize are you using?

v0.97.3 (9e7948e5b)

### What is the issue?

I recently [added an index](https://github.com/MaterializeInc/materialize/pull/26795) on `mz_kafka_sources`, and I was able to create a index with the exactly same name, in the same schema, which seems incorrect.

**Comment by maddyblue** [comment]
This is working as intended. The problem here is that index was never actually used! Need to add it to BUILTINS_STATIC, then we fail as expected.

**Comment by RobinClowers** [comment]
🤦 Good catch, thank you!
