### ISSUE TITLE
Add Protobuf formatting to Consistency Source

### ISSUE THREAD

**Issue by nacrooks** [MaterializeInc/materialize#2684]
The consistency topic currently supports: 

- AvroOCF ` {source: "SourceName", "partition_count": partition_count, "partition_id": pid, "timestamp", 4, "offset": 5}`
- Avro` {source: "SourceName", "partition_count": partition_count, "partition_id": pid, "timestamp", 4, "offset": 5}`
-  a comma separated byte format: `(SourceName,PartitionCount,PartitionId,Timestamp,Offset)`

It should additionally support a Protobuf format. This would allow consistency metadata to always be expressed using the same format as the associated source.

**Comment by elindsey** [comment]
We've reduced formats supported for consistency topics and I don't expect we'll expand it anytime soon - closing this as won't fix. We can revisit if it comes up in byo discussions
