### ISSUE TITLE
[Epic] dbt-materialize: testing & productionizing blue/green workflow

### ISSUE THREAD

**Issue by chaas** [MaterializeInc/materialize#26933]
Follow up to https://github.com/MaterializeInc/materialize/issues/24186: add testingf or dbt-materialize blue/green workflow so that we feel comfortable releasing to PuPr/GA

Product outcome: users can easily manage blue/green deployments with dbt and trust that it "just works".

**Comment by morsapaes** [comment]
Closing as done after #27557, where we added end-to-end tests for the blue/green deployment workflow.
