### ISSUE TITLE
Kinesis sources hit rate limit on ListShards operation

### ISSUE THREAD

**Issue by benesch** [MaterializeInc/materialize#2694]
Since the addition of the new multi-shard support for Kinesis, we're pretty consistently hitting an AWS rate limit while running the ci-only/kinesis.td script. Try as I might I cannot reproduce this locally (and I'm running against real AWS, not localstack), which makes it really challenging to debug. 

As best as I can tell, we're no longer throttling our API requests in the Kinesis source. I think maybe this is supposed to be an `activate_after` call? https://github.com/MaterializeInc/materialize/blob/a24737518f928fb91c702c87bdc4204002cda80c/src/dataflow/source/kinesis.rs#L190-L192

But I'm not sure.

I think I've managed to hack around the issue for now in #2693, but would be great to get someone more familiar with Kinesis on the case! /cc @JLDLaughlin

**Comment by benesch** [comment]
Oh, FWIW, ListShards is supposed to rate limit at ~100 requests per second. I added logging and it seems like we're hitting it ~20x/s. Definitely not ideal from a performance perspective, but also not super close to the rate limit. Not sure what's up with that.

**Comment by JLDLaughlin** [comment]
That can definitely be an `activate_after`! But I'm surprised we'd hit the limit at 20x/s, will look into this.
