### ISSUE TITLE
`CREATE MATERIALIZED VIEW mv AS SELECT` breaks catalog migration

### ISSUE THREAD

**Issue by aalexandrov** [MaterializeInc/materialize#27167]
### What version of Materialize are you using?

v0.101.0-dev (21a97db52)

### What is the issue?

After running 

```sql
CREATE MATERIALIZED VIEW mv AS SELECT
```

on the latest development build I can no longer restart the process with

```
CREATE MATERIALIZED VIEW mv AS SELECT
```

because I get the following error

```
environmentd: fatal: cannot migrate from catalog version 0.101.0-dev to version 0.101.0-dev (earlier versions might still work): corrupt catalog: failed to deserialize item u1 (materialize.public.mv): column "as" does not exist

CREATE MATERIALIZED VIEW "materialize"."public"."mv" IN CLUSTER [u1] WITH (REFRESH = ON COMMIT) AS SELECT "as" AS OF 0
```

I think that the purified SQL saved in the catalog when creating the materialized view item is not correct.

**Comment by benesch** [comment]
This has been broken for a very long time, so I think we can lift the release blocker tag here. Regardless, #27181 is the fix.
