### ISSUE TITLE
storage: ensure tokio-postgres doesn't buffer replication data

### ISSUE THREAD

**Issue by guswynn** [MaterializeInc/materialize#27213]
`tokio-postgres` does io on a separate tokio task, communicating with the client using a channel. During replication, its unclear if the task buffers new values from upstream to be processed from the client.

If it DOES do this (this must be checked), then it must be altered so the client can backpressure this process (with the strictest definition of the word backpressure) when it is not polling the channel.

**Comment by petrosagg** [comment]
> If it DOES do this (this must be checked)

I checked this (and in the process tidied up our rust-postgres fork) and it does NOT do this so there is nothing to be done on the Materialize side. The connection task spawned in a separate tokio task communicates with the timely operators via bounded queues so backpressure is applied correctly
