### ISSUE TITLE
storage/persist: support multiple configurations of `BatchBuilder`

### ISSUE THREAD

**Issue by guswynn** [MaterializeInc/materialize#27214]
We probably want to be able to at least control the number of outstanding parts-per-worker in storage, separate from compute. Possibly more configs.

**Comment by guswynn** [comment]
@danhhz @bkirwi is there a way to write (or is there a way to adjust some code to support) to a `BatchBuilder` and have it start a multipart upload for a part before it gets to 128MiB? As in, can we have a persist writer use a more granular amount of memory than `128MiB`?

Currently we see that if you set the outstanding parts config in a `BatchBuilder`, the memory used is proportional to 1 part (128MiB) + some overhead for maintenance (which appears to be 2-3 parts worth of memory?)? Does that match your understanding?

**Comment by danhhz** [comment]
Nope! Persist is pretty hardcoded to buffer up some amount of data and then flush it out in one `Blob::set` call (which internally does the s3 multipart).

> Currently we see that if you set the outstanding parts config in a BatchBuilder, the memory used is proportional to 1 part (128MiB) + some overhead for maintenance (which appears to be 2-3 parts worth of memory?)? Does that match your understanding?

Yeah, you can probably have in memory simultaneously of a part you're about to write out: the ColumnarRecords representation (going away with Parker's structured blob work), the structured representation for stats, and the parquet encoded bytes

**Comment by guswynn** [comment]
@danhhz I see! This issue then captures that we should be able to configure the `BatchBuilder` to use 1 part-per-worker-per-shard + overhead in storage, without changing the configuration for the compute `persist_sink`.

If we need to be even more constrained than that (I doubt it), then we can round-robin access to a singular outstanding part between the various shards (if someone wants to ingest like 100 mysql tables on a single 25cc replica oh god)

> Yeah, you can probably have in memory simultaneously of a part you're about to write out: the ColumnarRecords representation (going away with Parker's structured blob work), the structured representation for stats, and the parquet encoded bytes

In our testing @petrosagg and I saw periodic spikes, is that from compaction (or is that on read only)? Or is just because we are doubling up the ColumnarRecords and the encoded bytes?

**Comment by danhhz** [comment]
Uhhh not sure that's enough info for me to be able to tell you what the spikes are, but PolarSignals should be able to tell you immediately!

Is there some more context to motivate this? I'd love for us to first convince ourselves that there isn't some better resolution to the problem you're having than just adding more configs to the mix :)

**Comment by guswynn** [comment]
@danhhz it was just local testing; if we see the problem in staging/testing we will attempt to get some traces

> Is there some more context to motivate this? I'd love for us to first convince ourselves that there isn't some better resolution to the problem you're having than just adding more configs to the mix :)

The only motivation here is that 3 128MiB chunks being buffered + overhead per source is a huge chunk of the smaller replica sizes' memory footprint. I am just trying to get ahead of things here trying to ensure flow control has reasonable behavior across the spectrum of replica sizes. In our testing in the future we will have more info. I'm gonna leave this issue up connected to the epic (feel free to remove the persist label if its bugging you) to make sure I don't forget about it

**Comment by danhhz** [comment]
Sounds good, happy to revisit when y'all are ready!

One thing I'll probably push on is the idea of wrapping these in some sort of semaphore first/also. Changing the tunings might get us a multiplicative improvement, but it doesn't fundamentally solve the problem. Would be nice to also discuss how to avoid the game of whack-a-mole entirely

**Comment by guswynn** [comment]
> 
Sounds good, happy to revisit when y'all are ready!

One thing I'll probably push on is the idea of wrapping these in some sort of semaphore first/also. Changing the tunings might get us a multiplicative improvement, but it doesn't fundamentally solve the problem. Would be nice to also discuss how to avoid the game of whack-a-mole entirely


Yeah, I think a (fair) semaphore shared between the workers might be a big win

**Comment by bosconi** [comment]
Closing after this [Slack discussion](https://materializeinc.slack.com/archives/C075QPD99PV/p1718620225961869?thread_ts=1718600280.613069&cid=C075QPD99PV). This parameter affects the maximum transient memory required for persist sink. Having a memory ceiling is what's important, what the ceiling actually is is secondary. We may revisit this after https://github.com/MaterializeInc/materialize/issues/27630.
