### ISSUE TITLE
compute: cardinality computations in the new analysis.rs can panic

### ISSUE THREAD

**Issue by mgree** [MaterializeInc/materialize#27348]
### What version of Materialize are you using?

v0.101.1

### What is the issue?

The following query:

```sql
explain with(cardinality)
with mutually recursive
  t(x int) as (select 1 union all select * from u),
  u(x int) as (select t.x+1 from t where x < 7)
(select * from t);
```

Will cause environmentd to panic. @frankmcsherry and I (with help from @SangJunBak  and @arusahni) have traced the issue to the port of cardinality to the analysis framework.

**Comment by frankmcsherry** [comment]
Fixed in #27353
