### ISSUE TITLE
Clean up Kafka `start_offset` support.

### ISSUE THREAD

**Issue by umanwizard** [MaterializeInc/materialize#2736]
Most importantly, it should be extended to work with a separate offset per partition (it is almost useless in the multi-partition case currently).

We should also consider if there are ways to make it fail more gracefully when updates/deletes are detected.

**Comment by ruchirK** [comment]
I'll need this for the source persistence prototype so I'm happy to push a commit that adds multipartition support separately?

**Comment by umanwizard** [comment]
@ruchirK what would be the expected semantics for non-append-only sources?

**Comment by ruchirK** [comment]
in source persistence? we persist a local copy of your data we read previously and concat that with the new data thats read in from kafka

**Comment by umanwizard** [comment]
I mean, without source persistence though, if you let someone type `CREATE SOURCE foo ... WITH (start_offsets = [1234, 5678])`, what happens if their source has unbalanced deletes after those start indices?

I think this problem is why we haven't really implemented this: there's no obvious way to make it safe. `start_offset` even without multi-partition support isn't safe either, for the same reason, which is why we haven't documented it.

If you're just talking about allowing us to do it internally, and not about exposing the API to SQL, I'm all for it!

**Comment by ruchirK** [comment]
right. my understanding was that adding multipartition support doesnt make it more or less safe and therefore exposing it in sql would not be a big deal.

that being said the minimum I need is to have internal support so if you don't want me to expose the api to sql I am happy to do that?

I definitely agree we should not document this rn

**Comment by umanwizard** [comment]
Sure - nothing is made _less_ safe by adding multi-partition support. Nothing bad will happen if you do it. I was just trying to understand whether it's actually useful.

If you know for sure that it's useful, definitely go ahead!

**Comment by rjnn** [comment]
Bumping this - do we support specifying the starting offset yet, and is it documented, etc.?

**Comment by umanwizard** [comment]
no, we might tentatively be planning on that for 0.8 though.

Keep in mind that it will be of limited use because it will never be possible for debezium/cdc sources.

**Comment by rjnn** [comment]
for non-debezium users this is of great use, and we have clear user interest in this being solved. throw up a doc warning that they shouldnt use this with debezium data, and we should be good.

**Comment by krishmanoh2** [comment]
Would it not work for debezium users if 5709 lands?

**Comment by umanwizard** [comment]
@krishmanoh2 yes, it could - if those users are willing to accept the additional memory and compute costs that #5709 entails.

**Comment by JLDLaughlin** [comment]
@umanwizard @elindsey - it seems like most of the necessary plumbing for this work is already in place, trying to wrap my head around why this is hard.

To state my assumptions: Kafka topic partitions are named like `topic-name-{partitionid}`. We want to support creating Kafka sources with a `WITH` clause like: `WITH (start_offset=[0, 1, 2, ...])`. I'm assuming that `start_offset` should be a list of offsets in `partitionid` order. We'll add those offsets to `ConsistencyInfo`'s `start_offset`, and I think everything should more or less work (with `UPSERT` data)?

A corner case is that if a new partition comes online, the current code defaults the previously unknown partition's offset to 0. It seems possible that we'd want to start reading from the most recent message instead. 

Wanted to check before I write code, is there anything else I'm missing?

**Comment by umanwizard** [comment]
That field in `ConsistencyInfo` is somehow relevant to BYO timestamping I think; it should indeed be populated with the correct answers, but it isn't what actually controls the offset we read Kafka from.

The relevant field is `start_offsets` in `KafkaSourceConnector`, which is set in `plan_create_source` . 

Another thing I should mention: please make sure the current undocumented flag that works for Debezium doesn't go away, because Datalot is relying on that. (They have a bunch of topics in Debezium format, but they happen to know that they are actually logially append-only, so everything works). But the actual robust/documented version should indeed not work for Debezium data, as it's an almost guaranteed way to make Materialize crash.

>  corner case is that if a new partition comes online, the current code defaults the previously unknown partition's offset to 0

This should be fine. If a new partition is created, there won't be and data in it, so reading from 0 is essentially the same as reading from the latest offset.

**Comment by JLDLaughlin** [comment]
We support multiple Kafka `start_offset`s as of https://github.com/MaterializeInc/materialize/pull/5960. There are still caveats! Behavior is a bit quirky (documented in the PR) and limited to non-Debezium sources. 

I'm not sure if this "cleans up" Kafka `start_offset` support enough to close this issue, I'll leave that to @umanwizard to decide if there's work left here.

**Comment by umanwizard** [comment]
It seems like we're doing everything we can, so this issue can be closed out. We should now document this, along with the caveats.
