### ISSUE TITLE
Kafka RTR test is flaky: simple/verify-rtr.td:98:1: error: non-matching rows:

### ISSUE THREAD

**Issue by def-** [MaterializeInc/materialize#27393]
### What version of Materialize are you using?

9b63ce388759

### What is the issue?

Failed in https://buildkite.com/materialize/test/builds/83023 and https://buildkite.com/materialize/test/builds/83016
```
^^^ +++
simple/verify-rtr.td:98:1: error: non-matching rows: expected:
[["DEF"]]
got:
[]
Poor diff:
- DEF

     |
  10 | $ postgres-execute c ... [rest of line truncated for security]
  97 | 
  98 | > FETCH ALL c2
     | ^
testdrive: maximum number of errors reached; giving up
+++ !!! Error Report
1 errors were encountered during execution
files involved: simple/verify-rtr.td
```

The tests were added as part of the RTR MVP: https://github.com/MaterializeInc/materialize/pull/25195
@sploiselle Could this be an actual product issue?

ci-regexp: simple/verify-rtr.td:98:1: error: non-matching rows

**Comment by def-** [comment]
The test is pretty simple, so I'm not seeing that anything is wrong with the test case. But maybe there is something subtle about the RTR semantics.

**Comment by bosconi** [comment]
@nrainer-materialize this is a flake, that only occurs intermittently? If so, do you have any data on how frequently it occurred?

**Comment by def-** [comment]
It was failing a lot in CI, so I disabled it, meaning we don't have any data about how frequently it fails. I'll try to reproduce it locally with `while true; bin/mzcompose --find kafka-rtr down && bin/mzcompose --find kafka-rtr run default || break; done` and this diff reenabling the check:
```diff
diff --git a/test/kafka-rtr/simple/verify-rtr.td b/test/kafka-rtr/simple/verify-rtr.td
index c1a44eb525..af1c5c2e86 100644
--- a/test/kafka-rtr/simple/verify-rtr.td
+++ b/test/kafka-rtr/simple/verify-rtr.td
@@ -95,12 +95,11 @@ DEF,B,0
 > FETCH ALL c1
 ABC

-# TODO(def-) Reenable rest of the test when #27393 is fixed
-# > FETCH ALL c2
-# DEF
-#
-# > DECLARE c3 CURSOR FOR SELECT sum FROM sum;
-# > FETCH ALL c3
-# 5000209
-#
-# > COMMIT
+> FETCH ALL c2
+DEF
+
+> DECLARE c3 CURSOR FOR SELECT sum FROM sum;
+> FETCH ALL c3
+5000209
+
+> COMMIT
```

**Comment by def-** [comment]
Reproduced, but took about an hour:
```
> FETCH ALL c2

^^^ +++
simple/verify-rtr.td:98:1: error: non-matching rows: expected:
[["DEF"]]
got:
[]
Poor diff:
- DEF

     |
  10 | $ postgres-execute c ... [rest of line truncated for security]
  97 |
  98 | > FETCH ALL c2
     | ^
testdrive: maximum number of errors reached; giving up
+++ !!! Error Report
1 errors were encountered during execution
files involved: simple/verify-rtr.td
```

**Comment by nrainer-materialize** [comment]
> @nrainer-materialize this is a flake, that only occurs intermittently? If so, do you have any data on how frequently it occurred?

This exact flake with `[["DEF"]]` vs. `[]` as difference occurred 9 times in CI. The first occurrence was in https://buildkite.com/materialize/test/builds/82695 from Monday, 27th May and this part of the check was disabled in CI this Monday (3rd June).

**Comment by ggevay** [comment]
I don't see any code for `FETCH` that would try to honor real-time recency, so maybe it's just that RTR is not implemented at all for `FETCH`? But I don't know this code well, so I might be missing something obvious.

In particular, I don't see any timestamp selection going on in the fetch handling code. It seems we just return whatever results the cursor currently has. I also tried looking from the other direction: Searching for calls to `determine_real_time_recent_timestamp`, but I only see calls from `explain...` and `peek...`.

**Comment by ggevay** [comment]
Could @MaterializeInc/adapter confirm the above?

**Comment by ggevay** [comment]
Also note that the test's comment says `# Try subscribing`, but then it actually does a one-off SELECT instead of a `SUBSCRIBE`.

**Comment by ggevay** [comment]
But even if it's not a SUBSCRIBE, but a one-off SELECT, it's still a valid question why RTR is not honored.

I have a guess at what is happening: The whole thing is inside a transaction (because of the `BEGIN`), and what transactions roughly do is that they determine the timestamp for the whole transaction when the first thing that needs a timestamp happens, right? So, then maybe the
```
> FETCH ALL c1
```
determines an RTR timestamp for the topic `input-1`, and then the `> FETCH ALL c2` doesn't request a new timestamp, because it's still the same transaction, and it's not guaranteed that the RTR timestamp for `input-1` is good for `input-2`'s recent insertion.

**Comment by ggevay** [comment]
So, to sum it up, my understanding is that there are two problems with the test, and one problem with the system:
1. The test does a one-off SELECT, when it wants to do a SUBSCRIBE.
2. The test expects a valid RTR timestamp for a second select statement in a transaction, but the timestamp is already locked in at the first select statement of the transaction.
3. It seems that RTR is not implemented for `FETCH`ing from a `SUBSCRIBE`.

(The above is with the caveat that I'm completely new to RTR, CURSORs, and not an expert at transactions.)

**Comment by maddyblue** [comment]
`DECLARE` doesn't start running anything. The first time `FETCH` is issued on a portal is when execution starts. So the `FETCH c2` doesn't start until after the `kafka-ingest`s. Presumably there could be a race between the `kafka-ingest` getting fully through kafka and the `FETCH` choosing a timestamp. Does that explain what could be happening here?

This has been known for a long time but hasn't ever been a priority to fix. https://github.com/MaterializeInc/materialize/issues/6770#issuecomment-842646766

**Comment by maddyblue** [comment]
Also yes, the first `FETCH` determines the timestamp for the whole transaction, so the second `FETCH` gets the same timestamp. Looking at this test, I don't see why `DECLARE` and `FETCH` are used at all. `FETCH ALL` on a `SELECT` is identical to using just `SELECT`. `FETCH` is (mostly) only useful for `SUBSCRIBE`.

**Comment by bosconi** [comment]
@petrosagg what's your take here? Is it well-formed to be using `FETCH` with RTR? The corresponding [PG](https://github.com/MaterializeInc/materialize/blob/main/test/pg-rtr/rtr/verify-rtr.td) and [MySQL](https://github.com/MaterializeInc/materialize/blob/main/test/mysql-rtr/rtr/verify-rtr.td) tests are working fine but are restricted to `SELECT`. We could drop Kafka back to SELECT only too (and potentially add a check that disables RTR for everything but SELECTs?)

**Comment by maddyblue** [comment]
Using `SELECT` instead of `FETCH` almost certainly has nothing to do with this. If we removed the `DECLARE`s and replaced all `FETCH` with `SELECT` the same problem would occur.

**Comment by bosconi** [comment]
Ah, OK. Thanks @maddyblue. Maybe we should make that change anyway, for parity between then Kafka, PG and MySQL tests?

**Comment by maddyblue** [comment]
Yes, that change should be made. `FETCH` is misleading here. It should only be used with `SUBSCRIBE`.

**Comment by nrainer-materialize** [comment]
> This was observed again on `main` after reenabling the adjusted test: https://buildkite.com/materialize/test/builds/83291#018fed1f-2a23-4103-9d3e-3807fc9e0bc4

We already have a further one reported by @ggevay: https://buildkite.com/materialize/test/builds/83292
