### ISSUE TITLE
INSERTs and UPDATEs exceed max result size even though they have no result

### ISSUE THREAD

**Issue by def-** [MaterializeInc/materialize#27428]
### What version of Materialize are you using?

main

### What is the issue?

Maybe slightly related to https://github.com/MaterializeInc/materialize/issues/22724
Minimized from https://github.com/MaterializeInc/materialize/pull/27424
```
materialize=> set max_query_result_size = '1MB';
SET
materialize=> show max_query_result_size;
 max_query_result_size
-----------------------
 1MB
(1 row)
materialize=> create table t2 (c1 map[text=>text], c2 bytea);
CREATE TABLE
materialize=> insert into t2 select '{a=>b}'::map[text=>text], generate_series::text::bytea from generate_series(1, 100000);
ERROR:  result exceeds max size of 1048.6 KB
```
Same for updates:
```
materialize=> insert into t2 select '{a=>b}'::map[text=>text], generate_series::text::bytea from generate_series(1, 10000);
INSERT 0 10000
materialize=> insert into t2 select '{a=>b}'::map[text=>text], generate_series::text::bytea from generate_series(1, 10000);
INSERT 0 10000
materialize=> insert into t2 select '{a=>b}'::map[text=>text], generate_series::text::bytea from generate_series(1, 10000);
INSERT 0 10000
materialize=> update t2 set c2 = 'nn3DRUlJQ3eAcPQhggRgIYapX54TpY8gaXv9KtSNvfueHznjUa5dfrqVl4Ixlsm7EKL1gMlGsS8AAD0Cr1OMv2OWohBeDTRAAqIs' where map_length(c1) = map_length('{a=>b}'::map[text=>text]);
ERROR:  result exceeds max size of 1048.6 KB
```
Is this expected? Do we have some internal data structures that grow too large? Maybe we just shouldn't word this as "result size".

**Comment by nrainer-materialize** [comment]
Note that this does also effect `DELETE` statements (https://materializeinc.slack.com/archives/CU7ELJ6E9/p1718349601451369).

**Comment by maddyblue** [comment]
We should: change the inner `SELECT` of RTR plans to ignore this limit since we already have `max_result_size` that is protecting against what we want here. `max_query_result_size` is specifically for protecting against serializing bytes over the network to a user, not internal anything.
