### ISSUE TITLE
RTR causes coordinator deadlock, last_message_kind=linearize_reads, doesn't recover

### ISSUE THREAD

**Issue by def-** [MaterializeInc/materialize#27542]
### What version of Materialize are you using?

326fdeb (https://github.com/MaterializeInc/materialize/pull/27541)

### What is the issue?

Seen in my new test https://github.com/MaterializeInc/materialize/pull/27541
When I run it locally with `bin/mzcompose --find rtr-combined down && bin/mzcompose --find rtr-combined run default` Materialize becomes stuck after a few seconds. Happens reliably.

The logs indicate a problem in the coordinator:
```
rtr-combined-materialized-1     | environmentd: 2024-06-10T04:41:40.752618Z  WARN mz_adapter::coord: coordinator stuck for 30s last_message_kind=linearize_reads last_message_sql=<none>
```
[services.log](https://github.com/user-attachments/files/15756580/services.log)
Let's see if this reproduces in CI: https://buildkite.com/materialize/test/builds/83475 (Edit: it does)

psql connections to Materialize stop working entirely, there seems to be no amount of waiting that makes Mz go back into a healthy state, so I'd consider this a showstopper for the RTR feature.

Environmentd stays at ~25% CPU usage, no logging, Cockroach at 100%, also no logging. I assume we might just not be able to keep up with the load, but 1000 ints via kafka, pg, mysql each and 10 parallel selects doesn't sound like that much. Edit: Also seems to hang for a while with 10 rows being ingested each, but recovers for a bit.

**Comment by bosconi** [comment]
Thanks for this @def- . Since @petrosagg will pick up RTR next, I will assign to him and put in ToDo state/P2.

**Comment by petrosagg** [comment]
Fixed by https://github.com/MaterializeInc/materialize/pull/29239
