### ISSUE TITLE
`mz_cluster_replica_statuses` sometimes shows wrong termination reason

### ISSUE THREAD

**Issue by teskje** [MaterializeInc/materialize#27602]
### What version of Materialize are you using?

main

### What is the issue?

We observed that `mz_cluster_replica_statuses` can sometimes contain the wrong not-ready `reason`. Specifically, it may contain the reason "oom-killed" when in reality the replica crashed because of a panic.

[Slack thread](https://materializeinc.slack.com/archives/C053EPHMU05/p1718181829912609) for context.

**Comment by teskje** [comment]
I suspect the issue might be with this logic: https://github.com/MaterializeInc/materialize/blob/196c6ca90f5202d7f7d5b701b605fe768055194c/src/orchestrator-kubernetes/src/lib.rs#L1412-L1423

My theory is that we pick up the OOM from the previous replica termination. That's consistent with what we observed in that the replica pod had an OOM, then restarted, and then crashed with the misdiagnosed `reason`.

**Comment by benesch** [comment]
Seems like a good bet! The current logic just looks bad. I think we probably only want to consider `last_state` if the current state is `running` or `waiting`. If the current state is `terminated`, the current state is probably the only state we should consider.

Container state docs: https://docs.rs/k8s-openapi/latest/k8s_openapi/api/core/v1/struct.ContainerState.html
