### ISSUE TITLE
kafka-matrix has OoM and scalability benchmark shows a regression with heap profiling

### ISSUE THREAD

**Issue by def-** [MaterializeInc/materialize#27639]
### What version of Materialize are you using?

db88613212

### What is the issue?

Seen in https://buildkite.com/materialize/nightly/builds/8081#_

Heap profiling was enabled by default in https://github.com/MaterializeInc/materialize/pull/27614

I'll investigate.

**Comment by nrainer-materialize** [comment]
I assume that this is fixed by https://github.com/MaterializeInc/materialize/pull/27640.

**Comment by def-** [comment]
"fixed" in the sense that it doesn't happen in CI anymore, but I was hoping that we can figure out why there is such an impact from the heap profiling.

**Comment by def-** [comment]
Closing following discussion: https://materializeinc.slack.com/archives/CM7ATT65S/p1718347003548669 This is probably expected.
