### ISSUE TITLE
pgcli doesn't work OOB

### ISSUE THREAD

**Issue by z3n-badam** [MaterializeInc/materialize#2763]
Following the Getting Started documentation on Mac OS X Catalina.

installed materialize 0.2.0 via homebrew
installed pgcli version 2.0.0 via homebrew

started materialize using `materialized --w=1 &`

`pgcli -h localhost -p 6875 materialize` fails with
`unsupported function: pg_backend_pid`

Using psql connects quite happily

**Comment by benesch** [comment]
Ah, sorry about that! That's a docs bug. We're not compatible with pgcli—that's why we've got the mzcli fork: https://github.com/materializeInc/mzcli

I've opened #2768 to make this clearer in the docs.

**Comment by z3n-badam** [comment]
Well that explains it. 
[The docs currently recommend pgcli. ](https://materialize.io/docs/connect/cli/)

**Comment by rjnn** [comment]
Thanks for catching this, @z3n-badam! That's just a straight up oops on our side, and should fix as soon as #2768 merges. Sorry that you had to endure that frustration.
