### ISSUE TITLE
Testdrive with redpanda: Cluster keeps segfaulting, sink topic config doesn't show stalled but dropped state

### ISSUE THREAD

**Issue by def-** [MaterializeInc/materialize#27648]
### What version of Materialize are you using?

a9ec602ddf

### What is the issue?

Seen in https://buildkite.com/materialize/nightly/builds/8096#019013f1-2d6e-42a1-952c-cf54b18aa791
There seem to have been multiple segfaults of clusterd, but coredump text is empty:
```
testdrive-materialized-1          | environmentd: 2024-06-13T23:54:11.222347Z ERROR mz_orchestrator_process: cluster-u152-replica-u164-3 exited: ExitStatus(unix_wait_status(512)); relaunching in 5s
testdrive-materialized-1          | environmentd: 2024-06-13T23:54:11.350577Z ERROR mz_orchestrator_process: cluster-u154-replica-u166-2 exited: ExitStatus(unix_wait_status(512)); relaunching in 5s
testdrive-materialized-1          | environmentd: 2024-06-13T23:54:11.350633Z ERROR mz_orchestrator_process: cluster-u154-replica-u166-1 exited: ExitStatus(unix_wait_status(512)); relaunching in 5s
testdrive-materialized-1          | environmentd: 2024-06-13T23:54:11.350697Z ERROR mz_orchestrator_process: cluster-u154-replica-u166-3 exited: ExitStatus(unix_wait_status(512)); relaunching in 5s
testdrive-materialized-1          | environmentd: 2024-06-13T23:55:58.255874Z ERROR mz_orchestrator_process: cluster-u184-replica-u196-2 exited: ExitStatus(unix_wait_status(512)); relaunching in 5s
testdrive-materialized-1          | environmentd: 2024-06-13T23:55:58.257872Z ERROR mz_orchestrator_process: cluster-u184-replica-u196-1 exited: ExitStatus(unix_wait_status(512)); relaunching in 5s
testdrive-materialized-1          | environmentd: 2024-06-13T23:55:58.258396Z ERROR mz_orchestrator_process: cluster-u184-replica-u196-3 exited: ExitStatus(unix_wait_status(512)); relaunching in 5s
testdrive-materialized-1          | environmentd: 2024-06-14T00:04:44.701234Z ERROR mz_orchestrator_process: cluster-u196-replica-u209-2 exited: ExitStatus(unix_wait_status(512)); relaunching in 5s
testdrive-materialized-1          | environmentd: 2024-06-14T00:04:44.705620Z ERROR mz_orchestrator_process: cluster-u196-replica-u209-3 exited: ExitStatus(unix_wait_status(512)); relaunching in 5s
testdrive-materialized-1          | environmentd: 2024-06-14T00:04:44.846792Z ERROR mz_orchestrator_process: cluster-u197-replica-u210-3 exited: ExitStatus(unix_wait_status(512)); relaunching in 5s
testdrive-materialized-1          | environmentd: 2024-06-14T00:05:55.666003Z ERROR mz_orchestrator_process: cluster-u215-replica-u228-2 exited: ExitStatus(unix_wait_status(512)); relaunching in 5s
testdrive-materialized-1          | environmentd: 2024-06-14T00:07:48.762440Z ERROR mz_orchestrator_process: cluster-u232-replica-u245-1 exited: ExitStatus(unix_wait_status(512)); relaunching in 5s
testdrive-materialized-1          | environmentd: 2024-06-14T00:07:48.762749Z ERROR mz_orchestrator_process: cluster-u232-replica-u245-2 exited: ExitStatus(unix_wait_status(512)); relaunching in 5s
testdrive-materialized-1          | environmentd: 2024-06-14T00:07:49.481745Z ERROR mz_orchestrator_process: cluster-u231-replica-u244-3 exited: ExitStatus(unix_wait_status(512)); relaunching in 5s
testdrive-materialized-1          | environmentd: 2024-06-14T00:07:49.487348Z ERROR mz_orchestrator_process: cluster-u231-replica-u244-2 exited: ExitStatus(unix_wait_status(512)); relaunching in 5s
```
Then the kafka sink topic config test fails because the source got dropped, probably a symptom of the segfaults:
```
kafka-sink-topic-config.td:77:1: error: non-matching rows: expected:
[["stalled", "kafka: Error creating topic testdrive-kafka-config-unknown-135627053 for sink: Admin operation error: InvalidConfig (Broker: Configuration is invalid)"]]
got:
[["dropped", "<null>"]]
Poor diff:
+ dropped <null>
- stalled "kafka: Error creating topic testdrive-kafka-config-unknown-135627053 for sink: Admin operation error: InvalidConfig (Broker: Configuration is invalid)"

     |
  22 |     URL '${testdrive ... [rest of line truncated for security]
  76 | 
  77 | > SELECT status, error FROM mz_internal.mz_sink_statuses WHERE name = 'topic_config_unknown';
     | ^
```
The logs are full of this warning, but I'm not sure if it's related:
```
testdrive-materialized-1          | environmentd: 2024-06-14T00:28:16.571366Z  WARN mz_storage_client::storage_collections: error during background finalization of shard s7df12173-be22-4484-8b40-5d0a8bfaa84a: FinalizationError { since: Antichain { elements: [0] }, upper: Antichain { elements: [] } }
```
This is immediately after landing https://github.com/MaterializeInc/materialize/pull/27553, so I think it should be fixed or atl east understood before releasing the feature.

ci-regexp: kafka-sink-topic-config.td:77:1: error: non-matching rows

**Comment by teskje** [comment]
Where do you see that there were segfaults? Exit status 512 seems more like an error parsing command line arguments, no?

**Comment by def-** [comment]
I only see in Buildkite that there is a core file, but it's empty, so the segfault was my guess:
<img width="1469" alt="Screenshot 2024-06-14 at 17 01 32" src="https://github.com/MaterializeInc/materialize/assets/2335377/e0f9f458-dd11-4d2d-9b25-b32bbd80faaf">

**Comment by rjobanp** [comment]
From what I can tell this is just a difference between kafka and redpanda. It appears that redpanda is ignoring the bad config keys whereas kafka returns the error we look for in the test.

When running locally I can reproduce the error with 
```
bin/mzcompose --find testdrive down && bin/mzcompose --find testdrive run default --redpanda kafka-sink-topic-config.td
```

but without the `--redpanda` flag it works fine.

The other confusing thing is the `dropped` status. But curiously, when looking at all the sinks created in this test they all immediately enter 'dropped' status
```
materialize=> SELECT name, status, error FROM mz_internal.mz_sink_statuses;
         name         | status  | error 
----------------------+---------+-------
 topic_config         | dropped | 
 topic_partition      | dropped | 
 topic_replication    | dropped | 
 topic_config_unknown | dropped | 
```

whereas in the materialized logs I only see them enter the `running` state. So I think there might be a separate issue with sink status reporting

**Comment by rjobanp** [comment]
Ahh the sinks implicitly enter a dropped state because the upper frontier is downgraded to the empty frontier since the materialized view they depend on has no other values to produce (it's a static view). I tested this by comparing the status of various kafka sinks created in `kafka-sinks.td` - those with an upstream source stayed running, but those with a static materialized view got dropped after writing out the data.

So I think overall we can consider this a test issue when using redpanda -- @def- is there a way to selectively run this `SELECT status, error FROM mz_internal.mz_sink_statuses WHERE name = 'topic_config_unknown';` check if we're using `kafka` and not `redpanda`? If not we will likely need to remove it

**Comment by benesch** [comment]
> is there a way to selectively run this `SELECT status, error FROM mz_internal.mz_sink_statuses WHERE name = 'topic_config_unknown';` check if we're using `kafka` and not `redpanda`

Something sort of gross you could do is use `set-from-sql` and inspect whether `${kafka-addr}` contains the string "redpanda". Relies on container naming conventions but might be good enough.

**Comment by rjobanp** [comment]
> Something sort of gross you could do is use set-from-sql and inspect whether ${kafka-addr} contains the string "redpanda". Relies on container naming conventions but might be good enough.

Tried doing this but we alias the redpanda container to kafka and use `kafka` as `${kafka-addr}` in all cases...

**Comment by benesch** [comment]
Oh, bummer!
