### ISSUE TITLE
MySQL CDC test fails flakily with 2 panics: invalid as_of: as_of(Antichain { elements: [0] }) < since(Antichain { elements: [1718358237000] }) & always valid to read at since: Since(Antichain { elements: [1718358237000] })

### ISSUE THREAD

**Issue by def-** [MaterializeInc/materialize#27665]
### What version of Materialize are you using?

f3276e8c2962

### What is the issue?

Seen in https://buildkite.com/materialize/test/builds/83862#_
```
mysql-cdc-materialized-1  | thread 'timely:work-1' panicked at /var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-092d06436de6c590d-1/materialize/test/src/storage/src/source/reclock/compat.rs:137:13: invalid as_of: as_of(Antichain { elements: [0] }) < since(Antichain { elements: [1718358237000] }), source u125, remap_shard: Some(ShardId(09a3bf7f-8963-4db8-bf3b-57030218c1ab))
mysql-cdc-materialized-1  | thread 'tokio-runtime-worker' panicked at /var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-092d06436de6c590d-1/materialize/test/src/storage/src/storage_state/async_storage_worker.rs:150:26: always valid to read at since: Since(Antichain { elements: [1718358237000] })
```
Full [services.log](https://github.com/user-attachments/files/15836863/services.log)

The first location was last touched in https://github.com/MaterializeInc/materialize/pull/27314 which is part of v0.103.0 @bkirwi 

ci-regexp: invalid as_of: as_of(Antichain
ci-regexp: always valid to read at since: Since(Antichain

**Comment by bkirwi** [comment]
Yeah, I think this is pretty likely to be my PR.

I have a potential fix for this in https://github.com/MaterializeInc/materialize/pull/27633. It may make sense to revert my PR in the meantime however, in case it takes a while for me to land that change.
