### ISSUE TITLE
additional logging to verify async timeouts around `librdkafka` calls in the Kafka sink

### ISSUE THREAD

**Issue by bosconi** [MaterializeInc/materialize#27933]
## Problem

During investigation of https://github.com/MaterializeInc/incidents-and-escalations/issues/33 one instance was observed where the sink seemingly got permanently stuck and needed a manual restart. This suggests an async call did not time out, but there is insufficient logging to be sure.

## Solution

Add additional logging to confirm if an async call in this area fails to time out.

## See also

* https://github.com/MaterializeInc/incidents-and-escalations/issues/33
* https://app.slack.com/client/TL68GSMGF/C04DJT084KA
* https://app.slack.com/client/TL68GSMGF/C06CQC8LW4V

**Comment by benesch** [comment]
Interesting! Is there a rough description of the logs we're hoping to add that will shed light on this? I read through KIP-890 and didn't immediately see how we'd detect that on our side as the Kafka producer.

**Comment by bosconi** [comment]
@benesch, the second time the behavior was observed, the sink seemingly got permanently stuck and needed a manual restart. This means an async call did not time out. The additional logging will help narrow this issue if it occurs again.

**Comment by benesch** [comment]
Oh, I see — we want to add some logging around those async calls to understand if they got stuck? That makes sense to me. (Based on the initial description, I thought we wanted to add some logging to more directly check if we were experiencing the transaction issue described in KIP-890.)

**Comment by benesch** [comment]
No problem at all—thanks for filing! The reason I was digging is that this may be something I can knock out next time I'm in the area, to spare Petros the trouble.
