### ISSUE TITLE
Switch from Row `to_datum_iter`/`packer` to copying

### ISSUE THREAD

**Issue by antiguru** [MaterializeInc/materialize#27976]
At the moment, there are many places where we do the following:
```rust
let row: &Row = ...;
let mut packer = other_row.packer();
packer.extend(row.to_datum_iter());
```

This takes all datums from `row` and pushes them into `other_row` by means of decoding and encoding each individual item. There is an obvious way to make this faster based on the observation that the decoding/encoding is idempotent: We can instead just copy the bytes backing the datums. This probably means to skip some `ToDatumIter::to_datum_iter` calls since we're lacking specialization.

**Comment by antiguru** [comment]
It might be worth going though all uses of `RowPacker::extend`, because there are several that append a whole row (or chaining a row with another iterator.)

**Comment by sdht0** [comment]
Thanks @antiguru. I opened #28139.
