### ISSUE TITLE
Interval's zero is signed, and not equal to opposite sign

### ISSUE THREAD

**Issue by frankmcsherry** [MaterializeInc/materialize#2812]
The sign of a zero depends on the sign of the first argument, so we can write things like
```
materialize=> select (interval '-1' day + interval '1' day) = (interval '1' day + interval '-1' day);
 ?column? 
----------
 f
(1 row)
```
whereas is postgres these two should be equal
```
mcsherry=# select (interval '-1' day + interval '1' day) = (interval '1' day + interval '-1' day);
 ?column? 
----------
 t
(1 row)

mcsherry=# 
```

This probably comes from the `is_positive` bool in the `Interval` struct and us deriving `Eq`. However, even if we change the derivation of `Eq` we still need to worry that the `Row` representation will be distinct for positive and negative intervals. 

We should probably either double check all uses to make sure that the case of zero and the bools are handled, or maybe consider an `i128` in place of the `Duration` (maybe that is a rat hole though).

**Comment by benesch** [comment]
Fixed by #3151. Not sure why this issue didn't auto-close.
