### ISSUE TITLE
persist: Re-enable assert that checks we only push empty Rows into `SourceDataRowColumnarEncoder::EmptyRow`

### ISSUE THREAD

**Issue by ParkMyCar** [MaterializeInc/materialize#28146]
### What version of Materialize are you using?

v0.108.0-dev

### What is the issue?

Currently for the new columnar encoder implemented with `Schema2` we disable the check that the row we're pushing into `SourceDataRowColumnarEncoder::EmptyRow` is empty. This is because there is a known race with `txn-wal` having the correct schema.

**Comment by nrainer-materialize** [comment]
@danhhz, could you address https://github.com/MaterializeInc/materialize/blob/1be805f0301b53653727b8444b136bf5cbdfe705/src/repr/src/row.rs#L140-L150 please? Thanks!

**Comment by danhhz** [comment]
Sorry for the delay, I looked at this, but realized I didn't quite have the context to know what's going on with this second piece. Seems fine to wait until Parker gets back and let him handle it.
