### ISSUE TITLE
`WARN  mz_storage_client::storage_collections: Reference to absent collection` occurring frequently

### ISSUE THREAD

**Issue by bosconi** [MaterializeInc/materialize#28151]
Per [this Slack discussion](https://materializeinc.slack.com/archives/C0761MZ3QD9/p1720617409046719), this log message is now being observed frequently in certain environments, including CI:

```
2024-07-10 13:12:05.290	: environmentd-55-0: WARN  mz_storage_client::storage_collections: Reference to absent collection u210638
```

Can this be addressed in the context of `pv2`? Speculatively added to https://github.com/MaterializeInc/materialize/issues/27406.

**Comment by benesch** [comment]
@aljoscha if you could take a look at this when you're back, that'd be 👌🏽.
