### ISSUE TITLE
SELECT ... AS OF

### ISSUE THREAD

**Issue by justinj** [MaterializeInc/materialize#2824]
I couldn't find an existing issue for this, might have missed something though.

Creating this issue to get @rjnn's official position on this feature, my expectation is that it works basically the same as `TAIL WITH SNAPSHOT AS OF t`, but without any actual tailing. That is, we compact all the diffs before `t` to `t` and then read them at that timestamp.

@frankmcsherry mentioned offline that the primary difference between this and `TAIL` is that it might want to do something slightly smarter in the presence of unmaterialized sources: while it's not morally incorrect to allow `SELECT AS OF` from an unmaterialized source (just as it's not incorrect to `SELECT AS OF` a time in the future), it's sort of a footgun, since we do not a priori have timestamp information about an unmaterialized source and thus cannot guarantee that such a query will terminate in a timely fashion (or ever).

**Comment by frankmcsherry** [comment]
Oh and just to add color: I may have misled by distinguishing TAIL and SELECT. That particular distinction about timestamps is why SELECT and TAIL *currently* have different code paths, but the AS OF modifier for each should make them more similar. Probably different code paths still, but the AS OF behavior might be roughly identical logic.

**Comment by frankmcsherry** [comment]
One design question for `AS OF` is whether we want to support it in any `SELECT` query, or only modifying top-level queries. We talked this out a bit before, and it is not unreasonable to think about allowing it on any `SELECT` query (perhaps with some restrictions on timestamp selection)  as we "know" how to slide around and filter updates to capture collections at certain times and move them to other times. At least, if 

Perhaps it is easiest to start at the top-level and make more general temporal operators an add-on feature we can workshop later.

**Comment by rjnn** [comment]
Let's simply disallow `SELECT AS OF` from unmaterialized sources for now? To my brain, the reason to not allow it is the same as the reason to not allow bare `SELECT` queries from unmaterialized sources: my expectation is the same as @justinj's expectation: it's the same as `TAIL` without the diffs.

**Comment by benesch** [comment]
This has existed for a while now!
