### ISSUE TITLE
Inconsistent terminology is used when talking about numeric/decimal

### ISSUE THREAD

**Issue by wangandi** [MaterializeInc/materialize#2825]
It seems like in some places in the docs, we use `numeric`, and in some places we use `decimal`.

For example:
On the [numeric page](https://materialize.io/docs/sql/types/numeric/#details), it says "Materialize assumes untyped numeric literals containing decimal points or e-notation are decimal." and `decimal` links right back to the same page.

Below that, it lists casts to and from `numeric`, and when you click on the word `cast`, you get a page where the word `decimal` is used in place of `numeric`.

**Comment by benesch** [comment]
We're trying to switch everything over to Postgres's terminology, so
"numeric" is what we should prefer!

**Comment by morsapaes** [comment]
These inconsistencies seem patched now (with #6345 removing the last bits of it), so closing the issue.
