### ISSUE TITLE
60% performance regression in ManyKafkaSourcesOnSameCluster

### ISSUE THREAD

**Issue by def-** [MaterializeInc/materialize#28270]
### What version of Materialize are you using?

256e1f839b

### What is the issue?

Seen in https://buildkite.com/materialize/nightly/builds/8567#_
```
New regression against v0.108.3
NAME                                | TYPE            |      THIS       |      OTHER      |  Regression?  | 'THIS' is:
----------------------------------------------------------------------------------------------------
ManyKafkaSourcesOnSameCluster       | wallclock       |          43.716 |          27.338 |    !!YES!!    | 59.9 pct   more/slower
ManyKafkaSourcesOnSameCluster       | messages        |            None |            None |      no       | N/A
ManyKafkaSourcesOnSameCluster       | memory_mz       |        4533.768 |        4448.891 |      no       | 1.9 pct   more/slower
ManyKafkaSourcesOnSameCluster       | memory_clusterd |          64.392 |          68.302 |      no       | 5.7 pct   less/faster
```
The range of commits that landed: https://github.com/MaterializeInc/materialize/compare/5f3620a8b7...256e1f839b @petrosagg All commits are by you. I guess it is caused by https://github.com/MaterializeInc/materialize/pull/28228

Is this expected? If not, I'd consider it a release blocker.

**Comment by petrosagg** [comment]
This is the distribution of sources to workers which looks very suspiciously symmetric

```
sources=64 worker_id=0 num_workers=4
sources=94 worker_id=1 num_workers=4
sources=64 worker_id=2 num_workers=4
sources=94 worker_id=3 num_workers=4
```

**Comment by petrosagg** [comment]
Interestingly all source ids are even.. which is because for each source we also create a progress collection

**Comment by petrosagg** [comment]
I think this is a potential fix https://github.com/MaterializeInc/materialize/pull/28277
