### ISSUE TITLE
CREATE SOURCE ... WITH option naming inconsistencies

### ISSUE THREAD

**Issue by benesch** [MaterializeInc/materialize#2837]
There are a few `CREATE SOURCE ... WITH` option names that are a bit inconsistent, that I'd like to correct if possible.

  * `kafka_source_id` is prefixed with the word "kafka", but other Kafka configuration parameters (e.g. `sasl_kerberos_keytab`).
  * Kinesis sources have an `access_key` parameter, but the AWS APIs/docs are very consistent about calling this the "access key ID", weird and wordy as that phrasing may be. (The reason is that the "secret access key" is the actual access key; the access key ID is more like a username.)

**Comment by benesch** [comment]
I don't think that these are documented, either!

**Comment by sploiselle** [comment]
Think this is referring to `kafka_client_id`, and FWIW the Kinesis options are documented.

@umanwizard Is anyone using `kafka_client_id`? i.e. could we change it to `client_id` and just notify them?

**Comment by umanwizard** [comment]
One user that we know of relies on `kafka_client_id` being set, but I don't think they're overriding the default, so this should be fine to change. Let me know if/when you change it and I'll notify them just in case.
