### ISSUE TITLE
Create cleanup job for Kinesis streams

### ISSUE THREAD

**Issue by JLDLaughlin** [MaterializeInc/materialize#2845]
When testdrive finishes running in CI, it should clean up any Kinesis streams created for that particular run. However, for any testdrive run that is not completed, its streams will not be removed.

We should add removing stale Kinesis streams to the `cleanup` pipeline to remove these additional streams.

More details here: https://github.com/MaterializeInc/materialize/pull/2832

**Comment by benesch** [comment]
Fixed in #2908.
