### ISSUE TITLE
Materialized exits with internal error: assertion failed `(left == right)` 

### ISSUE THREAD

**Issue by awang** [MaterializeInc/materialize#2846]
Note that I'm using Ubuntu on Windows 10 Pro:
```
awang@DESKTOP-6A3ICBQ:~/dev/materialize$ uname -a
Linux DESKTOP-6A3ICBQ 4.4.0-18362-Microsoft #476-Microsoft Fri Nov 01 16:53:00 PST 2019 x86_64 x86_64 x86_64 GNU/Linux


awang@DESKTOP-6A3ICBQ:~/dev/materialize$ materialized --w=1
...
materialized v0.2.0-dev (54f9318de) listening on 0.0.0.0:6875...
materialized encountered an internal error and crashed.
...
```

 thread: <unnamed>
message: assertion failed: `(left == right)`
  left: `22`,
 right: `4`
   0: materialized::handle_panic
             at src/materialized/bin/materialized.rs:296
   1: core::ops::function::Fn::call
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libcore/ops/function.rs:72
   2: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:476
   3: rust_begin_unwind
             at src/libstd/panicking.rs:380
   4: std::panicking::begin_panic_fmt
             at src/libstd/panicking.rs:334
   5: std::sys::unix::thread::Thread::sleep
             at src/libstd/sys/unix/thread.rs:172
      std::thread::sleep
             at src/libstd/thread/mod.rs:789
   6: coord::timestamp::Timestamper::update
             at src/coord/timestamp.rs:469
   7: coord::coord::Coordinator<C>::serve_core::{{closure}}::{{closure}}
             at /workdir/src/coord/coord.rs:295
      tokio::runtime::context::enter
             at /cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.16/src/runtime/context.rs:72
      tokio::runtime::handle::Handle::enter
             at /cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.16/src/runtime/handle.rs:39
   8: coord::coord::Coordinator<C>::serve_core::{{closure}}
             at /workdir/src/coord/coord.rs:295
      std::sys_common::backtrace::__rust_begin_short_backtrace
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libstd/sys_common/backtrace.rs:129
   9: std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}}
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libstd/thread/mod.rs:475
      <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libstd/panic.rs:318
      std::panicking::try::do_call
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libstd/panicking.rs:305
  10: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:86
  11: std::panicking::try
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libstd/panicking.rs:281
      std::panic::catch_unwind
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libstd/panic.rs:394
      std::thread::Builder::spawn_unchecked::{{closure}}
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libstd/thread/mod.rs:474
      core::ops::function::FnOnce::call_once{{vtable.shim}}
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libcore/ops/function.rs:232
  12: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/liballoc/boxed.rs:1015
  13: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/liballoc/boxed.rs:1015
      std::sys_common::thread::start_thread
             at src/libstd/sys_common/thread.rs:13
      std::sys::unix::thread::Thread::new::thread_start
             at src/libstd/sys/unix/thread.rs:80
  14: start_thread
             at /build/glibc-YYA7BZ/glibc-2.31/nptl/pthread_create.c:477
  15: __clone

**Comment by ruchirK** [comment]
Thanks for reporting this @awang ! Did it crash immediately on startup? And also, does it crash like that repeatedly?

**Comment by awang** [comment]
Yup! it crashes immediately and consistently for me, unfortunately

**Comment by benesch** [comment]
`EINVAL`, apparently. That doesn't really seem like our fault.

@awang the answer in the short term may just be that we are not compatible with WSL.

**Comment by benesch** [comment]
Ah, yep, here we go: https://github.com/rust-lang/rustup/issues/2293

More details: https://github.com/microsoft/WSL/issues/4898

Are you compiling *in* WSL, @awang? Are you able to upgrade to WSL2? AIUI that's a total rework of the WSL and it seems that it doesn't have this bug. (Probably has others, of course...)

**Comment by benesch** [comment]
Looks like you could also downgrade to Ubuntu 18.04, which uses an older version of glibc that doesn't tickle this unsupported code path in WSL1.

**Comment by awang** [comment]
I'm not compiling in WSL, just using the compiled binary.  I think this is all I need -- thanks!

**Comment by awang** [comment]
Just updating the thread -- downgrading to Ubuntu 18.04 fixed it!
