### ISSUE TITLE
Support Azure Event Hub sources

### ISSUE THREAD

**Issue by sd2k** [MaterializeInc/materialize#2851]
I noticed this is mentioned in the README but couldn't find an issue for it, so this could be considered 'interest expressed' :smile:

I've used rust-rdkafka to connect to Event Hubs using the Kafka interface before and had to twiddle a few knobs to get it working, as documented [in this Azure repo](https://github.com/Azure/azure-event-hubs-for-kafka/blob/master/CONFIGURATION.md):

```
let consumer: rdkafka::consumer::StreamConsumer = rdkafka::config::ClientConfig::new()
    .set("bootstrap.servers", &config.host)
    .set("group.id", &config.consumer_group)
    .set("socket.keepalive.enable", "true")
    .set("metadata.max.age.ms", "180000")
    .set("heartbeat.interval.ms", "3000")
    .set("session.timeout.ms", "30000")
    .set("enable.partition.eof", "false")
    .set("enable.auto.commit", "true")
    .set("security.protocol", "SASL_SSL")
    .set("sasl.mechanism", "PLAIN")
    .set("sasl.username", "$ConnectionString")
    .set("sasl.password", &config.connection_string)
    .create();
```

(note that rust-rdkafka needs building with the `sasl` feature).

**Comment by rjnn** [comment]
Hi @sd2k, thanks for the feature suggestion, as well as the helpful links! 

We just added in SASL support, and are finishing up support for Kinesis, which frees up some engineering resources that we can look at supporting Azure Event Hub. It should "just work", but those are words I hesitate to utter!

I think that we'll likely just need to play with the configurations to test things out - it should be a fairly light ask, the biggest burden being in the testing (there doesn't seem to be an Azure equivalent of localstack for AWS), and subsequent documentation of the correct flags.

**Comment by guswynn** [comment]
Its unlikely this will be implemented soon, but the storage team will reconsider it in the future!
