### ISSUE TITLE
VALUES clause type problem

### ISSUE THREAD

**Issue by justinj** [MaterializeInc/materialize#2852]
```
materialize=> select * from (values (1), (10000000000));
ERROR:  Can't union types: Int32 and Decimal(38, 0)
```
The error message here suggests we can fix this by adding functionality to promote an Int32 to a Decimal.

**Comment by benesch** [comment]
Just to clarify: that logic does exist in scalar contexts, I think, but the
logic for unifying types in row contexts (rows of a values clause, or
unioning two SELECT statements together) is a different code path that
seems not to know how to do this.
