### ISSUE TITLE
a real full-refresh in dbt-materialize

### ISSUE THREAD

**Issue by hui-zheng** [MaterializeInc/materialize#28571]
### use case
the dbt run only replace/recreate models currently defined in dbt.  when dbt models are deleted or renamed, the dbt run will not remove the old/legacy m-views in materializeDB.
Those ghost models in production env as well as various dev envs, would become a drag to the cluster and performance. 

I would like to add a feature into dbt-materialize so that when we run dbt run --full-refresh , it would do either (1) or (2)
1. drop cascade the target schema and create it again
2. clean up all assets in the target schema

### Implementation Attempt
I tried to implement that as a macro to be executed on on-run-start in dbt_project

```
on-run-start: |
  {%- if flags.FULL_REFRESH -%}
    {{ prep_full_refresh_run(target.dbname, target.schema) }}
  {%- endif -%}
```
the macro 
```
{% macro prep_full_refresh_run(dbname, schema_name) %}

{# for a full_refresh, we clean up all m-views/tables in the given db.schema #}

    {% do log("INFO: this is a full refresh run, drop schema {}.{} and everything inside it".format(dbname, schema_name), info=True)%}

    {% set sql_stmt = [
        "drop schema if exists {}.{} CASCADE;".format(dbname, schema_name),
        "create schema {}.{};".format(dbname, schema_name)
    ] %}
    
    {% do return(sql_stmt | join(' ')) %} 
    

{% endmacro %}
```
However, it won't work, because those DROP statements could not be run inside a transaction block
```
error:  DROP SCHEMA IF EXISTS dbname.schema CASCADE cannot be run inside a transaction block
```

**Comment by benesch** [comment]
I believe you just need to let dbt run those statements separately, rather than joining them into a single string. I'd recommend trying something like this:

```yml
on-run-start:
  - |
     {%- if flags.FULL_REFRESH -%}
       drop schema if exists {{ target.dbname}}.{{ target.schema }}
     {%- endif -%}
  - |
     {%- if flags.FULL_REFRESH -%}
       create schema {{ target.dbname }}.{{ target.schema }}
     {%- endif -%}
```

**Comment by hui-zheng** [comment]
It works!! Thank you!

**Comment by benesch** [comment]
You bet! Thanks for reaching out. Let us know if you run into further trouble.
