### ISSUE TITLE
Introduce a new way to drop sinks that doesn't flush pending writes

### ISSUE THREAD

**Issue by ruchirK** [MaterializeInc/materialize#2860]
We will have a nice setup after #2855 gets merged where we are careful to write down all pending kafka messages in a kafka sink when we drop it. that's great -- except if someone has downstream issues and wants to shut things down without flushing

let's introduce a new command -- something like `DROP SINK foo ASAP` (joke proposal I don't have a good idea for a name) so that we have the capability to drop a producer without flushing if / when we need to

**Comment by benesch** [comment]
Proposal: this should be the default behavior of `DROP`. The fact that's it's not is a bug, IMO. It's just hard to fix. If you want to wait to drop a sink until some data arrives... you can just wait to drop the sink until that data arrives.
