### ISSUE TITLE
[Epic] Sources & sinks: source versioning

### ISSUE THREAD

**Issue by JLDLaughlin** [MaterializeInc/materialize#28653]
## Notion epic

**Link:** https://www.notion.so/Handle-structured-columnar-data-8ddbf2568db6492fb0e224399e211955
**Product brief:** 
**Status:** In progress
**Prioritization:** Now
**Estimated delivery date:** 2024-08-31

Lmizcx re uh ybmoaq kigu av czi Nuvorobiv luxve

**Comment by morsapaes** [comment]
Closing in favor of #28430.
