### ISSUE TITLE
parallel-workload: ALTER SINK causes stuck queries

### ISSUE THREAD

**Issue by def-** [MaterializeInc/materialize#28726]
### What version of Materialize are you using?

8d0aabadc8 (Pull Request #28708)

### What is the issue?

Noticed in https://buildkite.com/materialize/nightly/builds/8927

**Comment by def-** [comment]
I think this is actually caused by us picking an incompatible schema. Is this supposed to succeed in Materialize? I would have expected an error during the `ALTER SINK`, not for the query to just hang and the schema-registry to tell me that I picked an incompatible schema:
```
parallel-workload-schema-registry-1  | io.confluent.kafka.schemaregistry.rest.exceptions.RestIncompatibleSchemaException: Schema being registered is incompatible with an earlier schema for subject "sink_topic6-value", details: [{errorType:'MISSING_UNION_BRANCH', description:'The new schema is missing a type inside a union field at path '/fields/0/type/1' in the old schema', additionalInfo:'reader union lacking writer type: RECORD'}, {errorType:'MISSING_UNION_BRANCH', description:'The new schema is missing a type inside a union field at path '/fields/1/type/1' in the old schema', additionalInfo:'reader union lacking writer type: RECORD'}, {oldSchemaVersion: 1}, {oldSchema: '{"type":"record","name":"envelope","fields":[{"name":"before","type":["null",{"type":"record","name":"row","fields":[{"name":"c_2_jsonb_t_0","type":["null",{"type":"string","connect.name":"io.debezium.data.Json"}]},{"name":"c_0_int___t_0","type":["null",{"type":"array","items":["null","int"]}]}]}]},{"name":"after","type":["null","row"]}]}'}, {validateFields: 'false', compatibility: 'BACKWARD'}]
```
Definitions:
```sql
CREATE TABLE "db-pw-1722618900-0"."s-0"."t-0"("c-0-int[]" int[],
    "c-1-float8" float8 DEFAULT 52008245645.87885,
    "c-2-jsonb" jsonb);
CREATE MATERIALIZED VIEW "db-pw-1722618900-0"."s-0"."v-1" WITH (REFRESH EVERY '2 seconds 1 minutes' ALIGNED TO (mz_now())) AS SELECT "db-pw-1722618900-0"."s-0"."t-0"."c-2-jsonb" AS "c-2-jsonb-t-0", "db-pw-1722618900-0"."s-0"."t-0"."c-0-int[]" AS "c-0-int[]-t-0" FROM "db-pw-1722618900-0"."s-0"."t-0";
data-ingest-4-value: {"type": "record", "name": "value", "fields": [{"name": "value0", "type": "float"}, {"name": "value1", "type": "double"}, {"name": "value2", "type": "string"}, {"name": "value3", "type": "long"}, {"name": "value4", "type": "int"}, {"name": "value5", "type": "long"}, {"name": "value6", "type": "float"}, {"name": "value7", "type": "float"}, {"name": "value8", "type": "string"}, {"name": "value9", "type": "int"}, {"name": "value10", "type": "int"}]}
data-ingest-4-key: {"type": "record", "name": "key", "fields": [{"name": "key0", "type": "double"}, {"name": "key1", "type": "int"}, {"name": "key2", "type": "int"}, {"name": "key3", "type": "int"}, {"name": "key4", "type": "float"}, {"name": "key5", "type": "long"}, {"name": "key6", "type": "string"}, {"name": "key7", "type": "int"}, {"name": "key8", "type": "long"}, {"name": "key9", "type": "double"}]}
CREATE SOURCE "db-pw-1722618900-0"."s-2".kafka_table4
                    IN CLUSTER "cluster-0"
                    FROM KAFKA CONNECTION materialize.public.kafka_conn (TOPIC 'data-ingest-4')
                    FORMAT AVRO
                    USING CONFLUENT SCHEMA REGISTRY CONNECTION materialize.public.csr_conn
                    ENVELOPE UPSERT
data-ingest-7-value: {"type": "record", "name": "value", "fields": [{"name": "value0", "type": "int"}, {"name": "value1", "type": "int"}, {"name": "value2", "type": "int"}, {"name": "value3", "type": "int"}, {"name": "value4", "type": "float"}, {"name": "value5", "type": "float"}, {"name": "value6", "type": "long"}, {"name": "value7", "type": "int"}, {"name": "value8", "type": "long"}, {"name": "value9", "type": "float"}, {"name": "value10", "type": "int"}, {"name": "value11", "type": "string"}, {"name": "value12", "type": "int"}, {"name": "value13", "type": "float"}, {"name": "value14", "type": "float"}, {"name": "value15", "type": "float"}, {"name": "value16", "type": "string"}, {"name": "value17", "type": "long"}]}
data-ingest-7-key: {"type": "record", "name": "key", "fields": [{"name": "key0", "type": "int"}, {"name": "key1", "type": "int"}, {"name": "key2", "type": "float"}, {"name": "key3", "type": "string"}, {"name": "key4", "type": "int"}]}
CREATE SOURCE "db-pw-1722618900-0"."s-1".kafka_table7
                    IN CLUSTER "cluster-0"
                    FROM KAFKA CONNECTION materialize.public.kafka_conn (TOPIC 'data-ingest-7')
                    FORMAT AVRO
                    USING CONFLUENT SCHEMA REGISTRY CONNECTION materialize.public.csr_conn
                    ENVELOPE UPSERT
CREATE SINK "db-pw-1722618900-0"."s-1"."sink-6" IN CLUSTER "cluster-0" FROM "db-pw-1722618900-0"."s-0"."v-1" INTO KAFKA CONNECTION kafka_conn (TOPIC sink_topic6)  FORMAT AVRO USING CONFLUENT SCHEMA REGISTRY CONNECTION csr_conn ENVELOPE DEBEZIUM;
ALTER SINK "db-pw-1722618900-0"."s-1"."sink-6" SET FROM "db-pw-1722618900-0"."s-2".kafka_table4;
ALTER SINK "db-pw-1722618900-0"."s-1"."sink-6" SET FROM "db-pw-1722618900-0"."s-1".kafka_table7;
```
If this is expected (I don't think it's good ergonomics) I can make parallel-workload pick better fitting sources for the sinks of course.

**Comment by benesch** [comment]
> I think this is actually caused by us picking an incompatible schema. Is this supposed to succeed in Materialize? I would have expected an error during the `ALTER SINK`, not for the query to just hang and the schema-registry to tell me that I picked an incompatible schema:
> ...
> If this is expected (I don't think it's good ergonomics) I can make parallel-workload pick better fitting sources for the sinks of course.

Aha! Yes, this is expected right now. Agreed it's poor ergonomics; we have a tracking issue for improving the ergonomics here: https://github.com/MaterializeInc/materialize/issues/27613

(The current behavior was much easier to implement than #27613.)

> Since my query doesn't refer to this column, I think the user should never get this error! What we typically do in such cases where the catalog changed making the query impossible is return something like `query could not complete` instead.

Took a quick look through the code. I don't think this is about concurrent changes to the catalog, but rather `ALTER`ing a sink with a `KEY` that refers to a column that doesn't exist in the new `FROM` relation.

**Comment by benesch** [comment]
> Took a quick look through the code. I don't think this is about concurrent changes to the catalog, but rather `ALTER`ing a sink with a `KEY` that refers to a column that doesn't exist in the new `FROM` relation.

https://github.com/MaterializeInc/materialize/pull/28817 should make this error much clearer.

**Comment by benesch** [comment]
Ok, @def-, can I toss this one back to you?

  * #28817 has merged and should make it much clearer when you're running an `ALTER SINK ... FROM <new from>` command where `<new from>` is missing columns that are required by the sink's `KEY` clause. Hopefully it's easy to adapt the tests to only try to alter sinks to relations where all key columns still exist?
  * As mentioned in https://github.com/MaterializeInc/materialize/issues/28726#issuecomment-2269345279, it's expected that `ALTER SINK` will only lazily produce an error to `sink_status_history` when the new schema is incompatible with the old schema.

**Comment by def-** [comment]
Yep, will fix parallel-workload for that.
