### ISSUE TITLE
storage/sinks: report `key_format` and `value_format` in `mz_sinks`

### ISSUE THREAD

**Issue by morsapaes** [MaterializeInc/materialize#28789]
### Feature request

We recently added support for specifying different formats for the key and value of sinked Kafka records (#26787), but missed adding the additional format to `mz_sinks` (see [`mz_sources`](https://materialize.com/docs/sql/system-catalog/mz_catalog/#mz_sources)).

Since changing the name of the existing `format` column would be a breaking change, we can either add new `key_format` and `value_format` columns to the table and deprecate `format`, or add a `key_format` column that complements the existing `format` one. I'm actually not sure what the guidelines are for this sort of change to the system catalog, so will drop this in the internal SQL council channel ([Slack](https://materializeinc.slack.com/archives/C063H5S7NKE/p1722818395647549))!

**Comment by benesch** [comment]
One of the reasons we've gotten wedged here in the past is that there are additional details about certain formats that would be nice to reflect in the catalog. E.g., for Avro formats, which CSR connection you're using. That would maybe require a separate `mz_sink_avro_formats` table or something though, which we never got around to sorting out.

Doesn't need to necessarily block this work, but it's worth thinking through this as we think about the design of `key_format` and `value_format`. 

Put more simply: a single `text` column does not capture the full richness of a sink (or source's) format specification.

**Comment by morsapaes** [comment]
Agreed! I've thought about this as well as I typed out the issue. There's source- (and, in the future, possibly sink-)type specific configurations that shouldn't live in the top-level system catalog object, and it'd be interesting for us to derive type-specific configurations that go a level deeper to use in analytics, to avoid having to parse the raw (redacted) SQL statements. It's beyond the scope of this issue, though, but I'll create a dedicated one.

**Comment by rjobanp** [comment]
Can you specify what the exact scope of this issue should be?

I just verified that we already report the `format` in the existing `mz_sinks` table as `key-{}-value-{}` when using a key-value format sink. Do we just want to switch this to separate `key_format` and `value_format` columns like `mz_sources`, and set them both to the same value if there is only one format specifier?

**Comment by benesch** [comment]
> Do we just want to switch this to separate `key_format` and `value_format` columns like `mz_sources`, and set them both to the same value if there is only one format specifier?

That sounds like the way to go to me.

**Comment by morsapaes** [comment]
> I just verified that we already report the format in the existing mz_sinks table as key-{}-value-{} when using a key-value format sink.

I wasn't aware of that implementation detail — thanks for double-checking!

> Do we just want to switch this to separate key_format and value_format columns like mz_sources, and set them both to the same value if there is only one format specifier?

Yes. This will guarantee consistency across system catalog tables, and help avoid that users (_e.g._ Console) have to maintain custom parsing logic.
