### ISSUE TITLE
cannot create column with type uint

### ISSUE THREAD

**Issue by rjnn** [MaterializeInc/materialize#28854]
### What version of Materialize are you using?

v0.111.3 (18f229d9c)

### What is the issue?

```
create table foo (a uint);
Error: type "uint" does not exist
Returned in 24.0ms
create table foo (a uint4);
CREATE TABLE
Returned in 186.0ms
```
But the [docs](https://materialize.com/docs/sql/types/) lists `uint` as a valid alias of `uint4`.

Either the alias should be removed from the docs, or we should support it as documented.

**Comment by benesch** [comment]
https://github.com/MaterializeInc/materialize/pull/28855
