### ISSUE TITLE
0dt/m1: fix txn-wal handover of migrated builtin shards

### ISSUE THREAD

**Issue by benesch** [MaterializeInc/materialize#28919]
While rolling out v0.112 via 0dt deployments, we wedged the `mz_catalog_server` in all deployments. 

Here's my assessment of the issue:

  * https://github.com/MaterializeInc/materialize/pull/28833 changed the schema of `mz_sinks`, resulting in a builtin migration
  * The new 0dt builtin code correctly created a new shard for `mz_sinks` outside of txn-wal
  * The new `mz_catalog_server` cluster started maintaining some indexes and reading from that shard outside of txn-wal
  * The new envd got promoted and registered the new shard with txn-wal
  * The new `mz_catalog_server` cluster continued to read from the `mz_sinks` shard without txn-wal, and only received writes every 5m or so when they were flushed from the WAL to the data shard
  * Various things in the console reported as hung, and the Prometheus SQL exporter got repeatedly wedged while trying to export metrics based on `mz_sinks`

This seems rather hard to fix, unfortunately. It seems quick tricky to flip a `persist_source` operator that was *not* using txn-wal to suddenly start using txn-wal.

cc @danhhz @jkosh44 @aljoscha

**Comment by benesch** [comment]
> This seems rather hard to fix, unfortunately. It seems quick tricky to flip a `persist_source` operator that was _not_ using txn-wal to suddenly start using txn-wal.

Actually, I think txn-wal already has the right behavior around register/forget, and the problem is that we're intentionally not setting `metadata.txns_shard` when we create the `persist_source`. But if we _did_ set that, I think it would all just fall out properly.

**Comment by benesch** [comment]
I nerdsniped myself into putting up https://github.com/MaterializeInc/materialize/pull/28920.

**Comment by jkosh44** [comment]
> > This seems rather hard to fix, unfortunately. It seems quick tricky to flip a `persist_source` operator that was _not_ using txn-wal to suddenly start using txn-wal.
> 
> Actually, I think txn-wal already has the right behavior around register/forget, and the problem is that we're intentionally not setting `metadata.txns_shard` when we create the `persist_source`. But if we _did_ set that, I think it would all just fall out properly.

I think you mentioned this somewhere else, but it was intentional to not set `metadata.txns_shard`. When that's set we end up calling `unblock_reads` which commits an empty writes to the table, preventing us from back-filling the table with data.

**Comment by aljoscha** [comment]
> > > This seems rather hard to fix, unfortunately. It seems quick tricky to flip a `persist_source` operator that was _not_ using txn-wal to suddenly start using txn-wal.
> > 
> > 
> > Actually, I think txn-wal already has the right behavior around register/forget, and the problem is that we're intentionally not setting `metadata.txns_shard` when we create the `persist_source`. But if we _did_ set that, I think it would all just fall out properly.
> 
> I think you mentioned this somewhere else, but it was intentional to not set `metadata.txns_shard`. When that's set we end up calling `unblock_reads` which commits an empty writes to the table, preventing us from back-filling the table with data.

Yeah, I think we _do_ need to set `metadata.txns_shard`, so that the source can switch over when we actually register the shard in txn. But we need to _not_ do an unconditional `unblock_reads` call. I don't yet know how hard it is to know that you're not supposed to do that `unlock_read`.

**Comment by jkosh44** [comment]
> > > > This seems rather hard to fix, unfortunately. It seems quick tricky to flip a `persist_source` operator that was _not_ using txn-wal to suddenly start using txn-wal.
> > > 
> > > 
> > > Actually, I think txn-wal already has the right behavior around register/forget, and the problem is that we're intentionally not setting `metadata.txns_shard` when we create the `persist_source`. But if we _did_ set that, I think it would all just fall out properly.
> > 
> > 
> > I think you mentioned this somewhere else, but it was intentional to not set `metadata.txns_shard`. When that's set we end up calling `unblock_reads` which commits an empty writes to the table, preventing us from back-filling the table with data.
> 
> Yeah, I think we _do_ need to set `metadata.txns_shard`, so that the source can switch over when we actually register the shard in txn. But we need to _not_ do an unconditional `unblock_reads` call. I don't yet know how hard it is to know that you're not supposed to do that `unlock_read`.

I'll look into this today, but I'm hoping that it's relatively easy. I think we are calling `unblock_reads` when getting a snapshot of all tables so that we know what needs to be retracted from all tables. We should be able to exclude migrated tables because we know they're empty. Of course then we need to be really careful not to get a snapshot of migrated tables elsewhere and the whole thing is a bit hacky.

**Comment by aljoscha** [comment]
Can't we know from the stream of update we get from the txns shard that our table is not registered (yet), and not do an unblock_reads?

**Comment by jkosh44** [comment]
> Can't we know from the stream of update we get from the txns shard that our table is not registered (yet), and not do an unblock_reads?

I think you're maybe suggesting that we should fix this issue: https://github.com/MaterializeInc/materialize/issues/27088?
