### ISSUE TITLE
`dbt seed` only succeeds on the first run

### ISSUE THREAD

**Issue by jnoynaert** [MaterializeInc/materialize#28927]
### What version of Materialize are you using?

v0.111.3 (18f229d9c)

## Environment
Using dbt-materialize 1.8.2 and dbt 1.8.3:

## Bug
- `dbt seed` succeeds
- `dbt seed --full-refresh` returns an error on subsequent runs:
```
Database Error in seed seeds_utility__valid_timezones (seeds/utility/seeds_utility__valid_timezones.csv)
  can't execute an empty query
```
- `dbt seed` returns a different error on subsequent runs:
```
Database Error in seed seeds_utility__valid_timezones (seeds/utility/seeds_utility__valid_timezones.csv)
  querying the following items "dev_dbt.utility.valid_timezones" is not allowed from the "mz_catalog_server" cluster
  DETAIL:  The transaction is executing on the mz_catalog_server cluster, maybe having been routed there by the first statement in the transaction
```

## Workaround
In both cases dropping the seed table manually and re-running `dbt seed` works fine, but this requires a manual workaround when deploying updates.

## Desired behavior
- Seeds should work on subsequent runs
- If the seed file schema changes, the subsequent run should fail, requiring a `--full-refresh`. This is consistent with other adapters
- If the schema does not change, the seed should update inside a single transaction, yielding incremental updates only downstream

**Comment by morsapaes** [comment]
Thanks for reporting this bug, @jnoynaert! Reproducing it was straightforward, and so is the fix. I'll put up a PR soon, though I might take some extra time to enforce the generic behavior of the `--full-refresh` flag — in `dbt-materialize`, this only makes sense for seeds.
