### ISSUE TITLE
0dt/m1: review emergency patch for schema mismatch

### ISSUE THREAD

**Issue by benesch** [MaterializeInc/materialize#28924]
I merged #28923 without review from @aljoscha or @jkosh44 to fix test breakage on `main`. This issue tracks getting a review from one of them, which needs to happen before we cut the next release of Materialize.

**Comment by jkosh44** [comment]
I reviewed the PR and it LGTM. You can't stamp an already merged PR with a check mark, otherwise I would.

**Comment by benesch** [comment]
Sweet, thank you!
