### ISSUE TITLE
Nightly load test

### ISSUE THREAD

**Issue by cuongdo** [MaterializeInc/materialize#290]
We need some basic infrastructure to test `materialized`'s stability under load. Most likely, this will use the performance harness with a different configuration.

**Comment by cuongdo** [comment]
Renamed to make the intent clearer -- we should be running a load test nightly, based on the latest build off of master.

**Comment by rjnn** [comment]
This is the last non-doc issue for 0.2. Given that 0.2 shipped, I'm flagging this one for re-triage.

**Comment by cuongdo** [comment]
@quodlibetor reports that this is done!
