### ISSUE TITLE
0dt: Cluster with sink never hydrates

### ISSUE THREAD

**Issue by def-** [MaterializeInc/materialize#29015]
### What version of Materialize are you using?

bac3b513d8

### What is the issue?

Seen in [Checks 0dt upgrade across two versions](https://buildkite.com/materialize/nightly/builds/9101#019154ac-1f50-4058-aff1-dbb3c32c4321):
```
materialize.ui.UIError: Timed out waiting for mz_2 to reach Mz deployment status ReadyToPromote, still in status Initializing
```
From the logs:
```
environmentd: 2024-08-15T06:22:17.261329Z  INFO mz_orchestrator_process: launching cluster-u4-replica-u4-gen-0-0 via /usr/local/bin/clusterd --storage-controller-listen-addr=/tmp/71946df063c611a7398684a2c7fbfd7148481829 --compute-controller-listen-addr=/tmp/c501eb96dd09373e29790822859c6d858fa57247 --internal-http-listen-addr=/tmp/e498dcbd9490ba68d7219bab65faa789709c451f --opentelemetry-resource=cluster_id=u4 --opentelemetry-resource=replica_id=u4 --persist-pubsub-url=http://localhost:6879 --environment-id=mzcompose-us-east-1-00000000-0000-0000-0000-000000000000-0 --aws-external-id-prefix=eb5cb59b-e2fe-41f3-87ca-d2176a495345 --aws-connection-role-arn=arn:aws:iam::123456789000:role/MaterializeConnection --secrets-reader=local-file --secrets-reader-local-file-dir=/mzdata/secrets --startup-log-filter=info --log-format=text --log-prefix=cluster-u4-replica-u4-gen-0 --scratch-directory=/scratch/cluster-u4-replica-u4-gen-0...
```
This is the cluster, it contains sinks like this:
```sql
> CREATE CLUSTER sink_format_sink1_cluster SIZE '1';
rows match; continuing at ts 1723702937.2869983
> CREATE SINK sink_format_sink1
IN CLUSTER sink_format_sink1_cluster
FROM sink_format_table
INTO KAFKA CONNECTION kafka_conn (TOPIC 'testdrive-sink-format-sink-1')
KEY (f1)
KEY FORMAT TEXT
VALUE FORMAT JSON
ENVELOPE UPSERT;
```
Even waiting 15 minutes it never hydrates:
```
platform-checks-mz_2-1              | environmentd: 2024-08-15T06:25:26.672607Z  INFO mz_compute_client::controller: cluster u4 is not hydrated
[...]
platform-checks-mz_2-1              | environmentd: 2024-08-15T06:45:47.599666Z  INFO mz_compute_client::controller: cluster u4 is not hydrated
```
Is there some reason why a cluster with only sinks would take that long to hydrate? It has very little data.
It seems very reproducible, happened on the last 3 nightly runs: `bin/mzcompose --find platform-checks down && bin/mzcompose --find platform-checks run default --scenario=ZeroDowntimeUpgradeEntireMzTwoVersions`
Note that the hydration fails while bringing up `v0.112.2`, so maybe this is something that's already fixed on main?

ci-regexp: Timed out waiting for mz_.* to reach Mz deployment status ReadyToPromote, still in status Initializing

**Comment by def-** [comment]
This might be related to there being a migration in the upgrade from v0.111.3 to v0.112.2?

**Comment by aljoscha** [comment]
Is there more logs that say which collections are not hydrated? Normally we should have those right above the lines you posted:
```
platform-checks-mz_2-1              | environmentd: 2024-08-15T06:25:26.672607Z  INFO mz_compute_client::controller: cluster u4 is not hydrated
```

**Comment by def-** [comment]
```
environmentd: 2024-08-15T06:45:47.599665Z  INFO mz_compute_client::controller::instance: collection t72 not in live frontiers write_frontier=AntichainRef { frontier: [1723704347000] }
```
This seems to be:
```
environmentd: 2024-08-15T06:25:17.880781Z  INFO environmentd::run:environmentd::serve:adapter::serve:coord::coordinator:coord::bootstrap: mz_adapter::coord::introspection: installing introspection subscribe id=t72 replica_id=u4 type_=ComputeHydrationTimes
```

**Comment by aljoscha** [comment]
> ```
> environmentd: 2024-08-15T06:45:47.599665Z  INFO mz_compute_client::controller::instance: collection t72 not in live frontiers write_frontier=AntichainRef { frontier: [1723704347000] }
> ```
> 
> This seems to be:
> 
> ```
> environmentd: 2024-08-15T06:25:17.880781Z  INFO environmentd::run:environmentd::serve:adapter::serve:coord::coordinator:coord::bootstrap: mz_adapter::coord::introspection: installing introspection subscribe id=t72 replica_id=u4 type_=ComputeHydrationTimes
> ```

This one is fine, that's just informing us that we're not seeing a frontier for that collection in the frontiers of the previous deployment. And then the check should be continuing.

**Comment by aljoscha** [comment]
If, on the other hand, the write frontier is `[0]`, like in 
```
platform-checks-mz_2-1              | environmentd: 2024-08-15T06:25:17.934222Z  INFO mz_compute_client::controller::instance: collection t52 not in live frontiers write_frontier=AntichainRef { frontier: [0] }
```

That means we consider it as NOT hydrated and would fail the check.

**Comment by def-** [comment]
My bad, new try:
```
environmentd: 2024-08-15T06:45:47.599658Z  INFO mz_compute_client::controller::instance: collection t70 is not caught up write_frontier=AntichainRef { frontier: [1723704347000] } live_write_frontier=Antichain { elements: [18446744073709551615] } allowed_lag=60000
```
It's one of the sinks:
```
cluster-u1-replica-u1-gen-0: 2024-08-15T06:21:57.123476Z  INFO mz_storage_operators::s3_oneshot_sink: s3 leader worker initialization sink_id=t70 worker_id=14
cluster-u1-replica-u1-gen-0: 2024-08-15T06:21:57.141350Z  INFO mz_storage_operators::s3_oneshot_sink::pgcopy: starting upload: bucket copytos3, key key1/mz-t70-batch-0009-0001.csv
cluster-u1-replica-u1-gen-0: 2024-08-15T06:21:57.151845Z  INFO mz_storage_operators::s3_oneshot_sink::pgcopy: finished upload: bucket copytos3, key key1/mz-t70-batch-0009-0001.csv, bytes_uploaded 6, parts_uploaded 1
environmentd: 2024-08-15T06:25:17.880668Z  INFO environmentd::run:environmentd::serve:adapter::serve:coord::coordinator:coord::bootstrap: mz_adapter::coord::introspection: installing introspection subscribe id=t70 replica_id=u4 type_=ComputeErrorCounts
environmentd: 2024-08-15T06:25:17.935533Z  INFO mz_compute_client::controller::instance: collection t70 is not hydrated on any replica
```

**Comment by aljoscha** [comment]
Also, though, on `main` we're now excluding `t%` (transient) collections from the checks, so those should not hold up promotion anymore.

And now that I saw https://github.com/MaterializeInc/materialize/issues/29015#issuecomment-2291036541. Yes! This should be fixed on at least `main`. The frontiers of transient collections don't correlate, because we mint new transient IDs (afaik). In the log output we can see that the previous live frontier is `u64::MAX` (if I'm not mistaken), so we can never reach that.

It was this PR that fixed it: https://github.com/MaterializeInc/materialize/pull/28965

**Comment by teskje** [comment]
Because I was confused by this for a bit: `s3_oneshot_sink` is not a sink, at least not a SQL sink. It's the dataflow sink part of a `COPY TO S3` command. That's why it gets a transient ID, objects that are written to the catalog never get these.

**Comment by def-** [comment]
Perfect, that explains it.
