### ISSUE TITLE
Materialize spams logs when a sink is misconfigured

### ISSUE THREAD

**Issue by alex-hunt-materialize** [MaterializeInc/materialize#29042]
### What version of Materialize are you using?

v0.112.2

### What is the issue?

We seem to be doing something in an extremely tight loop, which spams logs to the point of breaking our log infrastructure and potentially filling disks on the node.

```
{"timestamp":"2024-08-15T19:06:10.141681Z","level":"WARN","fields":{"message":"primary key error: expected at most one update per key and timestamp This can happen when the configured sink key is not a primary key of the sinked relation.","sink_id":"User(355)","from_id":"User(345)"},"target":"mz_storage::render::sinks"}
```

See https://materializeinc.slack.com/archives/C04LKPKJDSM/p1723741768249579 and https://materializeinc.slack.com/archives/CL68GT3AT/p1723748537163919 for context and the downstream impact.

We will also fix our log infrastructure now that we know of this problem, but we should at least add some kind of backoff to whatever is spamming.

CC @arusahni for a reproduction.

**Comment by benesch** [comment]
Related:

  * https://github.com/MaterializeInc/materialize/issues/17549
  * https://github.com/MaterializeInc/materialize/pull/16487

Prescient: https://github.com/MaterializeInc/materialize/pull/16487/files#r1041108099

**Comment by benesch** [comment]
@morsapaes I'm going to pull this into the "productionize sinks" ticket under "now", since it would be good to get this fixed ASAP.

**Comment by arusahni** [comment]
The offending sink has the following characteristics:

- Sourced from an auction house loadgen source that was created Jun. 13, 2024. Using the quickstart tutorial's `fraud_activity` view, the following MV is generated:
	```sql
	CREATE MATERIALIZED VIEW materialize.public.fraud_activity_real
	    IN CLUSTER foo
	    WITH (REFRESH = ON COMMIT)
	    AS SELECT * FROM materialize.public.fraud_activity;
	```
- The sink DDL is as follows:
	```sql
	CREATE SINK materialize.public.sunk IN CLUSTER quickstart
		FROM materialize.public.fraud_activity_real
		INTO KAFKA CONNECTION materialize.public.kafka_conn2 (TOPIC = 'sink_topic')
		FORMAT JSON ENVELOPE DEBEZIUM WITH (PARTITION STRATEGY = 'v0');
	```

The sink is regularly experiencing two classes of errors:

```
kafka: Transaction error: ProduceRequest for sink_topic [0] with 5460 message(s) failed: Broker: Producer attempted an operation with an old epoch (broker 7 PID{Id:11399559,Epoch:34}, base seq 2002834): transactional producer fenced by newer producer instance: ProduceRequest for sink_topic [0] with 5460 message(s) failed: Broker: Producer attempted an operation with an old epoch (broker 7 PID{Id:11399559,Epoch:34}, base seq 2002834): transactional producer fenced by newer producer instance
```

and

```
kafka: Transaction error: 389904 message(s) timed out on sink_topic [0]: 389904 message(s) timed out on sink_topic [0]
```

**Comment by rjobanp** [comment]
I'm fairly new to this sink code, but from what I can tell this might be an unnecessary warning when we handle the debezium envelope in cases where there is no user-specified `key` specified on the sink and there is no primary key on the sinked relation:

https://github.com/MaterializeInc/materialize/blob/bdaca973f1ae0263ca75175775b4425f0541d28e/src/storage/src/render/sinks.rs#L121-L154

This logic will use the hash of the value as the key, instead, which is used to group all 'values' for a given key by timestamp:
https://github.com/MaterializeInc/materialize/blob/bdaca973f1ae0263ca75175775b4425f0541d28e/src/storage/src/render/sinks.rs#L172-L192

And then the warning `primary key error: expected at most...` is emitted by the `warn_on_dups` line here if there is more than 1 value for a given key at each timestamp:
https://github.com/MaterializeInc/materialize/blob/bdaca973f1ae0263ca75175775b4425f0541d28e/src/storage/src/render/sinks.rs#L198-L199

So this will warning will be emitted any time there is a Debezium envelope sink emitting records for a relation without a primary key, if there are any rows in that relation that hash to the same value at a given timestamp (which I'm guessing is what's happening in the load-generator output)

**Comment by rjobanp** [comment]
For context I checked the offending materialized view and it has no keys:
<img width="751" alt="image" src="https://github.com/user-attachments/assets/74e84bdb-3c76-4095-9b3c-65a80ff30c3f">

**Comment by rjobanp** [comment]
Fix PR https://github.com/MaterializeInc/materialize/pull/29089
