### ISSUE TITLE
Selectability decreases drastically when there are many records across many partitions

### ISSUE THREAD

**Issue by wangandi** [MaterializeInc/materialize#2913]
I see this at ~3mil records distributed across 30 kafka partitions. Trying to select from a kafka source made on it returns `ERROR:  At least one input has no complete timestamps yet.` This continues for minutes on end after the source was made.

Yet I was able to select almost immediately after a materialize source
* on ~200k records distributed across 30 kafka partitions
* or ~3mil records in one partition

Adjusting `--batch-size` down to 1000 or 100 does not appear to solve this issue. 

EDIT: behavior observed with 4 threads in `--dev` mode

**Comment by frankmcsherry** [comment]
I don't have a great read on our + Kafka's load balancing, but this could plausibly be a result of not reading the multiple partitions in an appropriately round-robin manner. It looks like we get whatever data we get from the producer.

If this is the issue, it might be good to either 1. establish a deeper pipeline (I think we maintain one "next" unprocessable message, and if the Kafka source has handed us one from a part that we can't process yet we'll stall the reading until we can, or 2. set up a consumer for each part.

But, probably good to diagnose the balance in reading from parts, if we don't have that built in yet (I don't see it myself, but .. who knows).

**Comment by nacrooks** [comment]
Currently investigating. The issue that you're mentioning Frank (re having a "single" message buffered) shouldn't cause an issue in Real-Time consistency because that message will get timestamped almost immediately by the timestamping thread (given the timestamping thread will immediately assign timestamps to all messages that exist on the topic). If we are not reading fairly across partitions, then I can see issues arising though. Currently investigating.

**Comment by frankmcsherry** [comment]
Thanks! These are definitely just things I was throwing out. The "boundedness" of the read buffer is one potential blocker (even if it should be soon unblocked, if not draining the inbound messages causes Kafka to start over at part 0 next time we read from it, .. potential horror).

This is probably obvious, but if we can repro the slowness, the next question is probably "what prevents the downgrading of capabilities?" which it seems like we should be able to answer with some diagnostics (on each scheduling of the source operator, what is the state of the read input vs the timestamp statements). It sounds like you may be on that, though!

**Comment by nacrooks** [comment]
PR #2936  addresses this.

**Comment by frankmcsherry** [comment]
Should this be closed @nacrooks?
