### ISSUE TITLE
perf-kinesis improvement ideas

### ISSUE THREAD

**Issue by JLDLaughlin** [MaterializeInc/materialize#2921]
`perf-kinesis` contains code to load test Kinesis sources. At the moment, it is a pretty simple test that ensures Materialize can handle reading X records/second from a Kinesis stream for some amount of time. A simple count on top of the ingested records is materialized and queried once per second.

There are lots of things that we can improve about this test!
- Put more meaningful data to the Kinesis stream (right now it's just random strings converted to bytes)
- Make queries per second configurable
- Use more complicated/realistic queries -- assume that most people won't be running with a single count
- Start reading from a stream that already contains records to see how we perform with a backlog

**Comment by morsapaes** [comment]
Closing as stale, since we no longer support Kinesis as a source, and any future implementation will be rewritten from scratch. This issue is listed in the source tracker for historical context.
