### ISSUE TITLE
Avro: support ingesting ENUM types

### ISSUE THREAD

**Issue by rjnn** [MaterializeInc/materialize#2924]
context: @umanwizard determined in an offline conversation that this would be an easy fix, so this is skipping the usual scoping channels. @umanwizard feel free to unassign if there's a determination that this needs to go through that process. cc @cuongdo

**Comment by umanwizard** [comment]
The PR predates the issue! https://github.com/MaterializeInc/materialize/pull/2923

**Comment by rjnn** [comment]
I knew stepping out for lunch was a mistake!
