### ISSUE TITLE
Consistency guarantees on processing CDC data from an at-least-once delivery source

### ISSUE THREAD

**Issue by rjnn** [MaterializeInc/materialize#2932]
Consider Azure Event Hub (e.g. #2851). They have a Kafka compatible API, but they do not support Kafka's "exactly-once" transaction commit protocol. We have a user interested in using Azure Event Hub as input.

The user's question is: given that the data in the data plane itself - Debezium style CDC records with `{before: {}, after: {}, timestamp: {}}` information, could we do the required deduplication - in order to achieve idempotent results when two change messages are processed (but with identical application timestamps) - across failures/connection restarts - in materialize? 

I do not know the answer to this question, but would appreciate thoughts.

**Comment by frankmcsherry** [comment]
We can certainly do the deduplication on our *output* side (logical timestamps and deterministic processing can replace exactly only). If the *input* data are coming in with potential duplication, ... ideally they wrote some sequence numbers down, or have primary keys or some other way to tell what is actually true and what are errors.

**Comment by rjnn** [comment]
They do have gtid or other unique (possibly monotonically increasing) commit timestamps.

**Comment by rjnn** [comment]
The answer is now yes, with upsert sources.
