### ISSUE TITLE
hydration-status.td is flaky

### ISSUE THREAD

**Issue by nrainer-materialize** [MaterializeInc/materialize#29465]
### Buildkite link

https://buildkite.com/materialize/nightly/builds/9471#0191d68e-0782-4dff-b9ae-7ec7b695ed16

### Relevant log output

```source
testdrive/hydration-status.td:80:1: error: non-matching rows: expected:
[["idx", "hydrated_test_1", "true"], ["mv", "hydrated_test_1", "true"], ["mv_const", "hydrated_test_1", "true"]]
got:
[["idx", "hydrated_test_1", "true"], ["mv", "hydrated_test_1", "true"]]
Poor diff:
- mv_const hydrated_test_1 true
```

### Additional thoughts

The first failure was observed on Sept 9th 13:33 CEST on main in [nightly/builds/9471](https://buildkite.com/materialize/nightly/builds/9471), which is commit [388649cb](https://github.com/MaterializeInc/materialize/commits/388649cb02cc12daab81437a8011e36a9d5597a3/).
Based on the previous commits, I assume that this is caused by https://github.com/MaterializeInc/materialize/pull/29148.

### Occurrences in nightly

> Match in build #9479 (pipeline nightly on ParkMyCar:bazel/ci):
URL: https://buildkite.com/materialize/nightly/builds/9479
Annotation: Full Testdrive in Cloudtest (K8s) 1

> Match in build #9478 (pipeline nightly on danhhz:persist_schema_plumbing):
URL: https://buildkite.com/materialize/nightly/builds/9478
Annotation: Full Testdrive in Cloudtest (K8s) 1

> Match in build #9478 (pipeline nightly on danhhz:persist_schema_plumbing):
URL: https://buildkite.com/materialize/nightly/builds/9478
Annotation: <span class="ui-emoji">🏎️</span> testdrive with SIZE 8 (#2)

> Match in build #9477 (pipeline nightly on main):
URL: https://buildkite.com/materialize/nightly/builds/9477
Annotation: Full Testdrive in Cloudtest (K8s) 1

> Match in build #9475 (pipeline nightly on ParkMyCar:bazel/ci):
URL: https://buildkite.com/materialize/nightly/builds/9475
Annotation: Full Testdrive in Cloudtest (K8s) 1

> Match in build #9471 (pipeline nightly on main):
URL: https://buildkite.com/materialize/nightly/builds/9471
Annotation: <span class="ui-emoji">🏎️</span> testdrive with SIZE 8

### Occurences in test

> Match in build #90116 (pipeline test on main):
URL: https://buildkite.com/materialize/test/builds/90116
Annotation: Testdrive 6

> Match in build #90068 (pipeline test on main):
URL: https://buildkite.com/materialize/test/builds/90068
Annotation: Testdrive 6

**Comment by nrainer-materialize** [comment]
@antiguru, do you think that https://github.com/MaterializeInc/materialize/pull/29148 can be the cause? Could you please take a look? Thank you!

**Comment by antiguru** [comment]
Indeed surprising; it shouldn't have any effect here. Checking!

**Comment by nrainer-materialize** [comment]
Thank you for your analysis!

I will disable this part of the test for now.
