### ISSUE TITLE
Have the billing demo (optionally) validate its own sink output

### ISSUE THREAD

**Issue by ruchirK** [MaterializeInc/materialize#2947]
The billing demo writes to a sink. I'm pretty sure we can
- reingest that sink
- generates a view that joins old and new data and looks for any inconsistencies
- yells at us if it finds any

**Comment by quodlibetor** [comment]
I believe that @nacrooks is working on a `checker` script (analogous to `peeker`) that we might be able to leverage for this.

**Comment by ruchirK** [comment]
I was thinking that for this the validation is simple enough that we could do it purely within Materialize (would also be a good test of "can we reingest what we write out to sinks?")

**Comment by quodlibetor** [comment]
Purely within materialize meaning via testdrive? I assumed this was about testing in CI, but maybe you meant this more as a musing that we can just check that it works?

**Comment by ruchirK** [comment]
No I mean we can have Materialize reingest sink output, and then write a materialize view to validate that the original view and its generated sink give equivalent results

**Comment by ruchirK** [comment]
basically like https://github.com/MaterializeInc/materialize/issues/2803#issuecomment-620689597 but written up as a part of the billing demo

**Comment by ruchirK** [comment]
Closed by #3194
