### ISSUE TITLE
Query latency spikes 1 minute into running Materialize (during compaction)

### ISSUE THREAD

**Issue by def-** [MaterializeInc/materialize#29653]
### What version of Materialize are you using?

fecdfc9377

### What is the issue?

![PoolRead_other_timeline](https://github.com/user-attachments/assets/58e5de63-51e6-4e18-b76b-8306ba982d10)
![PoolRead_this_timeline_2](https://github.com/user-attachments/assets/8af268c1-e37e-4ff5-9bc1-0bd2d03c547e)
![PoolRead_this_timeline](https://github.com/user-attachments/assets/a03e0707-e8e7-4e4d-879a-884c0db269a9)
Seen in at least three runs in CI:
https://buildkite.com/materialize/nightly/builds/9619
https://buildkite.com/materialize/nightly/builds/9602
I have not been able to reproduce it locally.
Based on the logs there seems to be a compaction happening at this exact time:
```
parallel-benchmark-materialized-1  | environmentd: 2024-09-18T17:49:21.876146Z  INFO mz_persist_client::cli::admin: dangerous_force_compaction_and_break_pushdown catalog s86892608-7ff3-82f8-1090-7584b4945aaa compacting 2 batches in 2 parts totaling 16927 bytes: lower=[4] upper=[6] since=[0]
parallel-benchmark-materialized-1  | environmentd: 2024-09-18T17:49:21.887672Z  INFO mz_persist_client::cli::admin: dangerous_force_compaction_and_break_pushdown catalog s86892608-7ff3-82f8-1090-7584b4945aaa compacted in 11.497201ms: AppliedExact
```
Do we expect compactions to somehow be blocking or should they not affect query latency? Is there a way to disable compactions for the duration of the benchmark or to ensure that they happen at exactly the same time? This is making the benchmark flaky and my goal is not to add retries but to get it reliable with other measures.

**Comment by danhhz** [comment]
Ah, yeah that's a new thing we added for pv2 to fully compact down the catalog shards, that'll really only run the once in prod, but we have it running continually in CI to exercise the correctness as much as possible. Absolutely do feel free to set `persist_catalog_force_compaction_fuel` to 0 for benchmark-y type things
