### ISSUE TITLE
I'm unable to create an OCF source via psql.  Should I switch to another CLI ?

### ISSUE THREAD

**Issue by aart** [MaterializeInc/materialize#2969]
config:
materialize/materialized:mzbuild-ZNLYGJRMJGZ7I45BY5SEZVIYK4WV3PGT
psql (9.6.17, server 9.5.0)

materialize=> CREATE SOURCE events FROM FILE '/sources/fx_freight_offer.ocf' WITH (tail = true)FORMAT AVRO OCF ENVELOPE NONE;
ERROR:  Parse error:
CREATE SOURCE events FROM FILE '/sources/fx_freight_offer.ocf' WITH (tail = true)FORMAT AVRO OCF ENVELOPE NONE;
                                                                                             ^^^
Expected USING, found: OCF

**Comment by benesch** [comment]
Hi @aart, thanks for trying out Materialize! Sorry about this; our documentation was wrong. Your CLI is working fine. 

The correct syntax to use is

```sql
CREATE MATERIALIZED SOURCE basic FROM AVRO OCF '${testdrive.temp-dir}/data.ocf'
```

There is a preliminary version of the corrected documentation available here: https://5eb6f28ce8dff70006f9f858--materializeinc.netlify.app/docs/sql/create-source/avro-file/.
