### ISSUE TITLE
sql: document + productionalize LIST type

### ISSUE THREAD

**Issue by benesch** [MaterializeInc/materialize#2997]
The type exists (#2644), but it is not particularly usable yet. We don't construct it for any Avro arrays, nor is there any way to manipulate a list (extract elements, etc) from within SQL. I'm going to hold off adding it to the release notes in v0.2.2, so it should get mentioned in the release notes of whatever release we do think it's ready for.

Remaining tasks to consider this finished:

* [x] `unnest` #3800

* [x] concatenation #3799

* [x] text casts #4677

* [ ] binary encoding #4628

* [x] basic documentation (PR #4739)

**Comment by benesch** [comment]
This is super close now! I added a checklist with the remaining tasks to the issue description.

**Comment by andrioni** [comment]
Are you planning on supporting list constructors as well, similarly to `array` in Postgres? E.g.
```sql
select e, array(select * from unnest(arr) val where val is not null) vals
from (select 1 e, array[1,2,3, null] arr) t
```

**Comment by sploiselle** [comment]
@andrioni Added an issue to track that work #3878 . Not sure of its size/complexity, but will assign it once we start development, and can provide an estimate at that point.

**Comment by sploiselle** [comment]
@benesch You feel like #4627 should be included in this?

**Comment by benesch** [comment]
Ah yeah, definitely. Also we need to sort out the list binary encoding.
