### ISSUE TITLE
release: automation

### ISSUE THREAD

**Issue by benesch** [MaterializeInc/materialize#3018]
@quodlibetor and I were discussing that when the release checklist has been stable for a release or two, we should automate most of the steps, since most of them are pure busywork.

The release checklist lives here: https://github.com/MaterializeInc/materialize/blob/master/.github/ISSUE_TEMPLATE/release.md

I propose the addition of two scripts:

  * bin/mkrelease, to manage creating the Git tags associated with a release and the necessary Cargo.toml/LICENSE changes.
  * bin/releaseck, to verify that all release assets have been published.

Here's a rough sketch of the interface.

  * `bin/mkrelease v0.2.3-rc1 <COMMIT-REF>` will start the release process for v0.2.3 based on the provided SHA. It will validate that v0.2.3 is the next release in a contiguous sequence; i.e., it should validate that the prior GitHub tag is v0.2.2. If we were instead releasing v1.0.0 or v0.3.0, it should prompt for additional confirmation that the minor version bump is desired. A bump to v0.2.4 that would skip v0.2.3 should be outright rejected.

  At the time of writing, these are the steps the command needs to take. It needs to open a PR against the master branch that bumps the version in materialized's Cargo.toml and LICENSE to `v0.2.4-dev`, including the changes to Cargo.lock. It also needs to update the same files on a `v0.2.3-rc1` tag and push up that tag to GitHub.

  In an ideal world, we'd choose the commit immediately before the `v0.2.4-dev` bump merged to master to use as the basis for `v0.2.3`, but that would be tricky to automate.

  * `bin/mkrelease v0.2.3-rcN <COMMIT-REF>` will validate that `v0.2.3-rc1` exists and that it is a parent of the specified SHA. Then it will update the Cargo.toml/LICENSE/Cargo.lock files appropriately and push up the RC tag with the changes.

* `bin/mkrelease v0.2.3 <RC-TAG>` will validate that the specified RC tag is the latest RC for v0.2.3, update the usual files, and push up the final release tag.

* `bin/releaseck v0.2.3` will validate that all assets for the release are present:
  * Validate that the macOS tarball exists.
  * Validate that the Linux tarball exists, installs in a container, and reports the correct version.
  * Validate that the Debian package installs in a container, reports the correct version, and that `systemctl start materialized` boots correctly. 
  * Validate that the Homebrew formula mentions the correct version. (The Homebrew tap has its own CI, so no need to do more validation on this. It's hard to write a script that tests macOS binaries that will work for folks who run Linux.)
  * Validate that the Docker image has been published and reports the correct version.
  * Validate that https://materialize.io/docs/versions/ mentions the version.
  * Validate that https://materialize.io/docs/release-notes/ does not claim the version is unreleased.

    releaseck should be structured as a series of checks that can fail independently, so that you can see what you've forgotten to do, if anything. That will also make it possible to run a new version of releaseck against an old release and get useful output, where some checks will be irrelevant (e.g., the Homebrew tap check will be wrong).

I _think_ that will automate away 80% of the drudgery with only about 20% of the effort of automating everything. The release checklist would simplify to:

  * Choose a SHA and run `bin/mkrelease v0.2.3-rc1 SHA`.
  * Launch load tests from infra repo.
  * Backport fixes and run `bin/mkrelease v0.2.3-rc2`... as necessary.
  * Run `bin/mkrelease v0.2.3 v0.2.3-rcN`.
  * Wait for binaries to build and publish.
  * Update Homebrew bottle.
  * Update release notes and website.
  * Run `bin/releaseck v0.2.3`.

Whoever works on this, a gentle plea to write the scripts in Python, not Bash!

**Comment by morsapaes** [comment]
Closing as stale. This is no longer relevant in light of the new cloud architecture.
