### ISSUE TITLE
Materialize does not properly handle duplicated messages from Debezium

### ISSUE THREAD

**Issue by umanwizard** [MaterializeInc/materialize#3026]
Debezium guarantees at-least-once semantics for the messages it generates. We were wrongly assuming it to be exactly-once.

This can cause Materialize to produce incorrect results, or even crash. For example: if an update message is produced twice, Materialize will interpret it as two retractions and two inserts, leaving the original tuple with a count of -1. (and tuples with negative multiplicities can cause crashes in any number of places, including but not limited to during reduces).

One possible solution is to assume that in the absence of duplicates, the Debezium MySQL connector produces rows in increasing order of binlog position. If that assumption is true (we need to validate it), we can have Materialize simply ignore any messages with a binlog position earlier than the latest one it has seen before.

A few caveats to this approach:

* it means we will have to decode the entire Avro message, including source metadata, possibly slowing down ingest considerably. This increases the urgency of doing a deep-dive into the decode performance of our `mod avro`.
* we also need to figure out if there is a corresponding concept for other connectors (PostgreSQL, etc.)
* on initial load, when Debezium is not reading from the binlog but instead scanning tables directly, this approach will not work. We need to understand whether duplicates are possible in that case, and if so, how to handle them.

**Comment by frankmcsherry** [comment]
Can this be closed @umanwizard ? I think we cleaned out the known deduplication issues, including some of the weirder corner cases.
