### ISSUE TITLE
More aggressive port state handling in CI

### ISSUE THREAD

**Issue by ruchirK** [MaterializeInc/materialize#3029]
See discussion in https://github.com/MaterializeInc/materialize/pull/3020

Basically, we are not able to externally bind (not sure what the right jargon is here) to specific ports (e.g. 6875 for materialize / 9092 for kafka) in CI because we can't be sure that some other container might have used it and not cleaned up. However, not binding to a specific port has usability problems as now if someone runs a demo they need to figure out what port Materialize is mapped to.

Lets "get something sorted out with either mzconduct or more aggressive CI cleanup steps (docker ps | xargs docker kill, roughly)."

**Comment by benesch** [comment]
Thanks very much for filing this!

**Comment by quodlibetor** [comment]
adding a `step: down` to the end of mzconduct workflows should guarantee that things go down at the end of a test, if the the test doesn't fail.

We can also add cleanup steps there, but I think a better option would be to just futz with mzcompose (under a philosophy that mzcompose is currently responsible for all docker-compose.yml rewriting) to add an `--expose-service-ports` option.

**Comment by quodlibetor** [comment]
from https://github.com/MaterializeInc/materialize/pull/3020#pullrequestreview-411008708

> Ideally IMO we would use the existing setup of allowing compose to find a free port

I totally missed that this is possible if you just specify a port. Yeah we can work this into mzconduct easily, and I support putting it there, and making that nice to work with.
