### ISSUE TITLE
materialized should commit consumed kafka offsets

### ISSUE THREAD

**Issue by quodlibetor** [MaterializeInc/materialize#3060]
Since every time we come up (with no persistence) we connect to kafka with a new group ID, we should be able to commit all ingested Kafka offsets. 

This will help folks who already have monitoring of Kafka clients understand how materialize is doing, and should be a no-op for us. Once we have persistence we'll probably want to only commit offsets that have been persisted.

**Comment by quodlibetor** [comment]
This also supports #2296 and is related to #2225

**Comment by elindsey** [comment]
Offset autocommit is now enabled in tip - materialize consumers will show up like `<optional prefix>-materialize-<uuid>-<source id>`. The optional prefix is user customizable via the kafka source `group_id_prefix` option.

**Comment by elindsey** [comment]
We did this quite awhile ago, then changed it to be opt in. Stale task; closing
