### ISSUE TITLE
Compaction documentation

### ISSUE THREAD

**Issue by sploiselle** [MaterializeInc/materialize#3071]
From a conversation with @frankmcsherry, slightly edited:

```
CREATE SOURCE foo_src;
CREATE MATERIALIZED VIEW foo AS SELECT * FROM foo_src
```
> ...uses the standard compaction tech, which maintains everything rolled up, except for the most recent `--logical-compaction-window time` units which are kept broken out.
> So as time advances, historical updates outside that interval get merged together, and .. if you are lucky, cancellation may occur.

Note that this behavior applies to materialized sources, as well.

**Comment by morsapaes** [comment]
Fixed in #4232.
