### ISSUE TITLE
Support string_agg

### ISSUE THREAD

**Issue by justinj** [MaterializeInc/materialize#3110]
The `string_agg` aggregate function concatenates its inputs with a separator: https://www.postgresql.org/docs/9.0/functions-aggregate.html.

**Comment by andrioni** [comment]
👍 for this, as it can help with pivoting data, as right now the alternatives aren't great:
- using `jsonb_agg`: it doesn't ignore nulls, so it is not that helpful for pivoting (at least without #3873 )
- using `max`/`min`: in my tests, it can keep more than one order of magnitude more data around than `jsonb_agg`
