### ISSUE TITLE
Improving "No complete timestamp" message

### ISSUE THREAD

**Issue by nacrooks** [MaterializeInc/materialize#3122]
Following discussion with Arjun:

Error: No complete timestamp is potentially misleading and may not reflect the fact that the system is making progress/this is an "expected" state for loading. 

A better solution would be to convey some progress metrics

**Comment by rjnn** [comment]
Ping @awang

**Comment by awang** [comment]
related: https://github.com/MaterializeInc/materialize/issues/2917

**Comment by benesch** [comment]
From discussion with @awang this morning, I think we can get a lot of mileage out of including more details in the error message. We should list all the inputs that have incomplete timestamps, and also check whether they're unmaterialized sources. If they are, we should very explicitly tell the user to materialize them. If they are already materialized, we should tell the user that maybe we are having trouble connecting to their (Kafka, Kinesis, file), and that they should check the logs for details.

**Comment by frankmcsherry** [comment]
I don't think this has very much to do with optimization and/or dataflow. It seems right in @mjibson's wheelhouse though.

**Comment by mjibson** [comment]
Yes, this is a coordinator thing and it has annoyed me for the above reasons also. Since
