### ISSUE TITLE
[Question] how does a non-rust Postgres Backed web app make use of this?

### ISSUE THREAD

**Issue by simkimsia** [MaterializeInc/materialize#3123]
I’m using django which is a python web app framework running on Postgres 10.3 and using celery and web sockets for doing some long running jobs

This is an interesting project

But can non-rust web Apps use this somehow to update real time dashboard? I don’t mind some time latency. User requests almost never exceed 100 per second on my app

**Comment by simkimsia** [comment]
Thanks for the quick response

What abt having Postgres as the Connector? I tried reading your docs and it doesn’t seem to say

Meaning python <==> materialize <==> postgres for the real-time effects

**Comment by quodlibetor** [comment]
Materialize is not a connector in the sense of [mysql-connector](https://pypi.org/project/mysql-connector-python/) -- which is I think what you're thinking of? It does not get deployed as part of your app, it is it's own service, like a database.

Currently our production-ready workflow requires debezium to act as a postgres read-replica if you want to mirror a postgres database. There are other ways that it can be deployed, though, which may be more appropriate for you. See our [archicecture](https://materialize.io/docs/overview/architecture/), or [our](https://materialize.io/docs/demos/log-parsing/) [various](https://materialize.io/docs/demos/microservice/) [demos](https://materialize.io/docs/demos/business-intelligence/) for an idea of how it could fit in with your other services.

**Comment by simkimsia** [comment]
By connector I mean the term your own docs use ![image](https://user-images.githubusercontent.com/245021/82693407-120a9e00-9c94-11ea-87d5-e19916318c52.jpeg)


And no I don’t mean in the mysql connector way 

I read it as the raw data source from which materialize listen to for changes

Thanks for pointing me towards debenizum I’ll take a look

**Comment by simkimsia** [comment]
By the way I’m most interested in this demo

Can fix the diagram?


https://materialize.io/docs/demos/business-intelligence/#diagram

It looks like this in my mobile Safari 

![image](https://user-images.githubusercontent.com/245021/82693967-0c618800-9c95-11ea-926c-217e87089906.jpeg)

**Comment by simkimsia** [comment]
Ok thanks I found this diagram which answers my question

I’ll fork the earlier comment abt the missing BI demo diagram to a new issue

![image](https://user-images.githubusercontent.com/245021/82694127-4a5eac00-9c95-11ea-9fa1-4d72916e28b7.jpeg)

**Comment by rjnn** [comment]
@simkimsia take a look at [MaterializeInc/tb](https://github.com/MaterializeInc/tb), which is a lighter weight version of standing up Debezium. It is very much a work in progress, but based on community needs (which means you!) we could be inclined to put more work into it.

It's also not wasted work - getting `tb` up and running will get you in a place where you can (if its not working for you) swap in "proper" debezium + kafka + materialize setup, if `tb` is not production for you.

**Comment by simkimsia** [comment]
Thx!
