### ISSUE TITLE
[bug in docs] missing diagram for BI demo

### ISSUE THREAD

**Issue by simkimsia** [MaterializeInc/materialize#3127]
Transferred from https://github.com/MaterializeInc/materialize/issues/3123#issuecomment-632820413

![image](https://user-images.githubusercontent.com/245021/82694237-7e39d180-9c95-11ea-9b37-90724fb8b439.jpeg)

Missing diagram for the BI demo on the documentation page viewed on mobile safari

**Comment by benesch** [comment]
Thanks very much for the report. Fixed in #3135!
