### ISSUE TITLE
Unbounded input streams should have footprint proportional to active data

### ISSUE THREAD

**Issue by frankmcsherry** [MaterializeInc/materialize#3134]
Input data we stream in has the ability to cancel itself, for example + and - canceling out, or a `None` update for a key in upsert streams. We currently do not always zero out this data, primarily in upsert mode. The `arrange` operator does this, maintaining only the distinct `(data, time)` pairs accumulating `diff` in place and removing zeros. The upsert path does not do this, for a few reasons but mainly that 1. we don't know which entries correspond to `None`, and 2. we need more assumptions about the order of events to delete a cancelled entry (i.e. that offsets increase, so that we don't then see an insert for a prior offset, and erroneously introduce it).

**Comment by frankmcsherry** [comment]
cc @wangandi

**Comment by frankmcsherry** [comment]
I think this may be fixed in the current upsert code. What do you think?

**Comment by wangandi** [comment]
Yeah I think it's fixed as of #5608.
