### ISSUE TITLE
Support additional aggregate functions

### ISSUE THREAD

**Issue by justinj** [MaterializeInc/materialize#3154]
* [ ] `bool_or`
* [ ] `bool_and`
* [x] `array_agg`

Probably more! Please comment on this issue if you encounter others we're missing.

See [here](https://www.postgresql.org/docs/9.5/functions-aggregate.html). These are aggregates that return the OR/AND of their inputs. Note that their behaviour is actually distinct from the dataflow `Any` and `All` aggregates in the presence of `NULL`.

**Comment by justinj** [comment]
Going to generalize this to missing aggregates more broadly.

**Comment by frankmcsherry** [comment]
> Note that their behaviour is actually distinct from the dataflow Any and All aggregates in the presence of NULL.

But they can be determined from dataflow `Any` and `All`, right, by mapping `NULL` to true and false, respectively?

**Comment by frankmcsherry** [comment]
We should probably just delete `Any` and `All` and require everyone to rewrite aggregates in to `Sum` and finish with the domain-specific logic they require.

**Comment by wangandi** [comment]
Related: #2813

**Comment by andrioni** [comment]
It would be nice to have `list_agg` here, as it could provide (I imagine) a more efficient alternative to `jsonb_agg` in several cases.
