### ISSUE TITLE
Friendlier error when misusing GROUP BY

### ISSUE THREAD

**Issue by justinj** [MaterializeInc/materialize#3165]
This is a common misuse of `GROUP BY`:
```
materialize=> select a from x group by b;
ERROR:  column "a" does not exist
```

Enough so that I think it's worth going the extra mile like Postgres explaining what's wrong:
```
postgres=# select a from x group by b;
ERROR:  column "x.a" must appear in the GROUP BY clause or be used in an aggregate function
LINE 1: select a from x group by b;
```

**Comment by benesch** [comment]
Duplicate of #443. But yes, this is a huge pain point. I think the fix gets easier with a separate name resolution fix, but if you see an easy way to fix it at the moment, don't let me stop you, @justinj.
