### ISSUE TITLE
Document how to ingest JSON in Kafka

### ISSUE THREAD

**Issue by awang** [MaterializeInc/materialize#3176]
Continuation of https://github.com/MaterializeInc/materialize/issues/207#issuecomment-612556519:  Document how to use a jsonb column

Also might want to consider whether it makes sense to have a FORMAT JSON format that just yields one JSON column.

**Comment by sploiselle** [comment]
Is this sufficient, @awang? https://materialize.io/docs/sql/create-source/json-kafka/

**Comment by awang** [comment]
sorry for missing this!  lgtm, closing
