### ISSUE TITLE
Timestamp in sink target table version data

### ISSUE THREAD

**Issue by awang** [MaterializeInc/materialize#3216]
Add timestamp in target table data (valid from+to).

currently, we have the image before and after of the state of data, however, there is no timestamp that gives information about when this change has happened. Having these timestamps will enable tracking when exactly changes happen in the materialized view (update, insert, delete), so that we enable time travel in the target table

**Comment by frankmcsherry** [comment]
It would be great to have an output format that is
```
(data, time, diff)
```
This is the native differential format, and .. at least if we add the convention that a zero diff indicates timestamp progress .. it presents a pretty self-contained representation of (a part of) the output collection. We can produce output to other formats too, but there sure is a lot of friction around how they aren't what we actually want.

**Comment by ruchirK** [comment]
I think we can encode this in the Avro/Debezium diff envelope world as a separate struct that contains timestamp metadata. Then the diff envelope encodes data and +/- 1 (we are careful to only ever write out a before OR an after never both, and a empty diff is just no before or after

**Comment by ruchirK** [comment]
We now emit transaction ids and a separate transaction topic in sinks if the user asks us to. Our outputs follow the debezium transaction metadata format. I'm not entirely sure if thats sufficient to close this issue and open a new one to have our sink output be reingestable by Materialize (it currently is not) and to emit the new (v2) materialize consistency format

@awang @cuongdo thoughts?

**Comment by cuongdo** [comment]
I defer to @awang on this.

**Comment by cuongdo** [comment]
@awang Should we resolve this issue, move to another milestone, or delay 0.4 for additional required changes?

**Comment by ruchirK** [comment]
Note that we already have #3618 to track reingesting sinks. Since we have not fully decided on the v2 consistency format I would suggest that we close this issue, as the key deliverable of "express timestamps in Materialize sink outputs" has been achieved

**Comment by awang** [comment]
Closing issue, will reopen if the customer encounters challenges or create a new issue if we need to make changes to the payload format
