### ISSUE TITLE
Runtime control of logging

### ISSUE THREAD

**Issue by benesch** [MaterializeInc/materialize#3228]
We need to introduce some knobs that allow us to control log levels at runtime. The current approach requires setting an environment variable at boot, which works nicely when a problem quickly reproduces, but is disastrous if a problem occurs infrequently or only after several minutes/hours of load.

Something that worked really well at Cockroach was a tool called logspy (https://github.com/cockroachdb/cockroach/blob/master/pkg/server/debug/logspy.go), which was just an HTTP page you could hit that would surface log messages as long as the HTTP connection was alive for whatever module and at whatever verbosity you requested in the URL.

@ruchirK has some thoughts on this front from a prior job, too.

**Comment by morsapaes** [comment]
Closing as stale.

**Comment by benesch** [comment]
Indeed! We got this wired up with LaunchDarkly!
