### ISSUE TITLE
chbench demo not working

### ISSUE THREAD

**Issue by mcrapts** [MaterializeInc/materialize#3238]
I am trying to run the demo in https://materialize.io/docs/demos/business-intelligence. The instructions are to run `bin/mzconduct run chbench --workflow demo-load`. This result in the following error:

```
$ ./mzcompose --mz-quiet -f ./mzcompose.yml run peeker --only-initialize -c /etc/peeker/materialized-sources.toml -q loadtest
unable to read config file "/etc/peeker/materialized-sources.toml": No such file or directory (os error 2)
C> Failed! giving up: peeker --only-initialize -c /etc/peeker/materialized-sources.toml -q loadtest
```

In `chbench/mzcompose.yml` the directory `chbench/peeker-config` is mounted as a volume. However, this directory in the repository is empty, which explains the error: indeed the file `materialized-sources.toml` does not exist. It appears the peeker configuration is missing in this demo, which causes it not to run.

**Comment by benesch** [comment]
Sorry about that, @mcrapts, and thanks for the diagnosis! I've pinged the appropriate folks.

**Comment by quodlibetor** [comment]
Sorry about that, should be fixed now @mcrapts ! Feel free to re-open this issue if it there continue to be problems.

**Comment by mcrapts** [comment]
Thanks, working perfectly now! These demos are very powerful.
