### ISSUE TITLE
failure to create Avro OCF source

### ISSUE THREAD

**Issue by rjnn** [MaterializeInc/materialize#3274]
# What version of Materialize are you using?

```
$ materialized -v
materialized v0.3.0 (c9408416ed580b6faf12c605c4f230e3deafa407)
```

### How did you install Materialize?
* [X] Homebrew tap

### What was the issue?
I am running postgres, TB, and Materialize. I could not create a source for a simple testing table.

In Postgres I ran:
`create table testing (foo varchar, bar varchar);`

I ran `tb` successfully, creating an Avro OCF source from this table.

Manually inspecting the Avro OCF file shows:
```
arjun@altaria  ~/checkouts/tb/tbshare/data   master  cat tb.public.testing 
Objavro.schema?{"type":"record","name":"Envelope","namespace":"tb.public.testing","fields":[{"name":"before","type":["null",{"type":"record","name":"Value","fields":[{"name":"foo","type":["null","string"],"default":null},{"name":"bar","type":["null","string"],"default":null}],"connect.name":"tb.public.testing.Value"}],"default":null},{"name":"after","type":["null","Value"],"default":null},{"name":"source","type":{"type":"record","name":"Source","namespace":"io.debezium.connector.postgresql","fields":[{"name":"version","type":"string"},{"name":"connector","type":"string"},{"name":"name","type":"string"},{"name":"ts_ms","type":"long"},{"name":"snapshot","type":[{"type":"string","connect.version":1,"connect.parameters":{"allowed":"true,last,false"},"connect.default":"false","connect.name":"io.debezium.data.Enum"},"null"],"default":"false"},{"name":"db","type":"string"},{"name":"schema","type":"string"},{"name":"table","type":"string"},{"name":"txId","type":["null","long"],"default":null},{"name":"lsn","type":["null","long"],"default":null},{"name":"xmin","type":["null","long"],"default":null}],"connect.name":"io.debezium.connector.postgresql.Source"}},{"name":"op","type":"string"},{"name":"ts_ms","type":["null","long"],"default":null},{"name":"transaction","type":["null",{"type":"record","name":"ConnectDefault","namespace":"io.confluent.connect.avro","fields":[{"name":"id","type":"string"},{"name":"total_order","type":"long"},{"name":"data_collection_order","type":"long"}]}],"default":null}],"connect.name":"tb.public.testing.Envelope"}Ѭ????.?+???蜊?%    
```

But creating the source failed:

```
materialize=> create source v from avro ocf '/Users/arjun/checkouts/tb/tbshare/data/tb.public.testing' with (tail = true);
ERROR:  validating avro ocf reader schema: Unsupported type in schema: Record { doc: None, fields: [RecordField { name: "foo", doc: None, default: Some(Null), schema: Piece(Union(UnionSchema { schemas: [Piece(Null), Piece(String)], anon_variant_index: {Null: 0, String: 1}, named_variant_index: {} })), order: Ascending, position: 0 }, RecordField { name: "bar", doc: None, default: Some(Null), schema: Piece(Union(UnionSchema { schemas: [Piece(Null), Piece(String)], anon_variant_index: {String: 1, Null: 0}, named_variant_index: {} })), order: Ascending, position: 1 }], lookup: {"bar": 1, "foo": 0} }
materialize=> \q
```

### Please attach any applicable log files.
The last line of `mzdata/materialized.log` shows
`Jun 05 11:04:35.912 ERROR coord::catalog: items leftover in temporary schema for conn_id: 1   `

I am not sure if it is relevant.

**Comment by awang** [comment]
not helpful, but i'm also using Homebrew materialize 0.3.0 (c9408416e).  I get the same error message in `materialized.log`

**Comment by umanwizard** [comment]
@awang can you send me the ocf file on slack?

**Comment by benesch** [comment]
Oh, I don't think this is actually a bug. You didn't specify `ENVELOPE DEBEZIUM`, and we don't support nested Avro types with the specific exception of the Debezium envelope.

This should work:

```sql
CREATE SOURCE v FROM AVRO OCF '/Users/arjun/checkouts/tb/tbshare/data/tb.public.testing' WITH (tail = true) ENVELOPE DEBEZIUM;
```

**Comment by benesch** [comment]
Is there a documentation bug somewhere?

**Comment by awang** [comment]
that helps!  i've updated the tb documentation.

I'm now able to create the source+view in Materialize with a proper schema, but no data is appearing:

```
materialize=> create source my_foo from avro ocf 'tbshare/data/tb.public.foo' WITH (tail = true) envelope debezium;
CREATE SOURCE
materialize=> show columns from my_foo;
 Field | Nullable | Type 
-------+----------+------
 bar   | YES      | int4
(1 row)

materialize=> create materialized view foo as select bar from my_foo;
CREATE VIEW
materialize=> select * from foo;
 bar 
-----
(0 rows)
```

```
postgres=# insert into foo values (1), (2), (3);
INSERT 0 3
postgres=# select * from foo;
 bar 
-----
   1
   2
   3
   1
   2
   3
(6 rows)
```

materialized.log shows that it's creating a source, view, and index for my_foo and foo, but no other error messages.

**Comment by awang** [comment]
Update: I'm able to get data "correctly" from most of my PG-->Debezium tables!  (i'm missing a few rows, but I'll make a separate issue for that once I dig into what's missing).  

However, I'm strangely still not getting data from the `foo` table.  I'm attaching the ocf file here as well

[tb.public.foo.zip](https://github.com/MaterializeInc/materialize/files/4741275/tb.public.foo.zip)

**Comment by benesch** [comment]
Weird! There is no data in that OCF file beyond the initial schema. So definitely a problem somewhere, but it doesn't seem to be in Materialize. Possibly `tb` emitted some warnings or errors somewhere?

**Comment by awang** [comment]
Thanks! Closing issue for now (as it now works for me), I'll look into the dbz/tb OCF issue separately.  @rjnn let us know if adding `ENVELOPE DEBEZIUM` doesn't solve it for you
