### ISSUE TITLE
Materialize hangs on connecting to client after restart when we create a specific large view

### ISSUE THREAD

**Issue by ruchirK** [MaterializeInc/materialize#3280]
If I create a view using generate series, e.g.

```
materialize=> create materialized view foo as select * from generate_series(1, 32000);
CREATE VIEW
```

and then query it a few times to make sure its reasonable
```
materialize=> select * from foo limit 10;
 generate_series
-----------------
             256
             512
             768
            1024
            1280
            1536
            1792
            2048
            2304
            2560
(10 rows)

materialize=> select count(*) from foo;
 count
-------
 32000
(1 row)
```

and then shut down the psql client, shut down Materialize, restart Materialize, and then try to restart psql -- psql hangs indefinitely and is unable to connect to Materialize.

This seems to happen when we make larger views with `generate_series` but not smaller ones.

In running experiments locally, views created this way with less than 30k rows didn't exhibit this problem, and views with more than 35k rows always exhibited this behaviour, there was an intermediate range between 30 - 35k that sometimes did and sometimes didn't (its possible that I had an error in manually running the experiment)

No other views, sinks, or sources were installed. I'm running master on `3dc70fc7f45e429aadb72da81761e74f3285a4d6`

**Comment by ruchirK** [comment]
Oh also: I ran materialize with
```
cargo run --release -- -w 1 --log-file=stderr
```

**Comment by benesch** [comment]
Oh, I think I see the issue. When the coordinator boots it loads all the existing view definitions from disks, parses them, and sends a bunch of `CreateDataflow` commands to the workers. Normally these commands are small, but I'm willing to bet that

    create materialized view foo as select * from generate_series(1, 32000);

gets const-evaled into `create materialized view foo as values (1, 2, 3, 4, ...)`.

**Comment by benesch** [comment]
Anyway, we don't create the dataflow threads until _after_ the coordinator boots. This is probably just wrong. The commands the coordinator sends to the dataflow workers get shoved into some kernel buffer until the dataflow workers boot and drain the queue. This works fine... until it doesn't.

FWIW I wasn't able to reproduce this issue on Linux, presumably because the Linux kernel has a bigger buffer in the relevant place.
