### ISSUE TITLE
Catalog gets corrupted by view with query that converts jsonb to timestamp

### ISSUE THREAD

**Issue by wangandi** [MaterializeInc/materialize#3281]
A testdrive test to reproduce the problem is here. Change `.txt` file suffix to `.td`.
[jsonbcatalogtimestamptz.txt](https://github.com/MaterializeInc/materialize/files/4738469/jsonbcatalogtimestamptz.txt)

A description of how to reproduce for those who don't want to run the testdrive test:

1) Have some text source that contains a json that has a field that can be converted into a timestamp, like:
`{"arrival_time":"2020-05-04T13:07:41-04:00"}`

2) Create a view that casts that view into a timestamptz:
```
CREATE VIEW some_view as 
SELECT CAST(text::jsonb->>'arrival_time' AS timestamptz) arrival_time
from source_name;
```

3) If you turn off materialize and try to turn it back on, you will get 
`corrupt catalog: failed to deserialize item u29 (materialize.public.some_view): No overload for jsonb? ->> timestamptz?`

`SHOW CREATE VIEW some_view` shows that `some_view` has been rewritten to
```
CREATE VIEW "materialize"."public"."some_view" AS 
SELECT "text"::jsonb -> 'arrival_time'::timestamp with time zone AS "arrival_time" FROM "materialize"."public"."some_view";
```
If you try to run the rewritten version, you will also get `query failed: db error: ERROR: No overload for jsonb? ->> timestamptz?`

**Comment by benesch** [comment]
Thanks for the great report. I have a fix in the works.
