### ISSUE TITLE
Control plane consistency

### ISSUE THREAD

**Issue by benesch** [MaterializeInc/materialize#33]
Metastore currently stores its data in ZooKeeper, which is... not great. The psuedo-filesystem that ZooKeeper chooses to expose makes life difficult when you want a strictly ordered stream of events across the whole filesystem, not just across one file or one directory. We're suffering at the moment because `PEEK` is not properly sequenced with `CREATE DATAFLOW`*, and therefore differential often sees a `PEEK foo` command come through before it sees the corresponding `CREATE DATAFLOW foo ...` command. Not to mention that we globally sequence things _twice_! ZooKeeper does one round of consensus, and then we do another round of exchanging with differential's sequencer.

The question, then, is what would be a suitable replacement for ZooKeeper? @frankmcsherry and @jamii have both proposed using a single-partition Kafka topic. For reasons I'll describe below, I'm not sold on that particular solution. Let me start by listing out what I think we need out of our metadata storage layer.

  * **Consistency**. We need to make sure that a dataflow D cannot be deleted while there exists another dataflow that depends on D. This effectively means that the metadata layer needs to support transactions, or that there is some means of electing a leader who is the sole arbiter of metadata updates.

  * **Sequencing**. The metadata storage should be able to produce an ordered log of all operations, *including* read commands, like `PEEK`, and write commands, like `CREATE DATAFLOW`.

  * **Durability**. If the server goes down, rebooting materialized should, at the very least, reinstall all dataflows that were previously installed. This is a prerequisite for durably storing computation state. Ideally, the metadata layer would be *selectively* durable. It doesn't need to store old versions of dataflows, for example, nor does it need to remember read-only commands.

A single-partition Kafka topic gives us sequencing and durability. @jamii mentioned that clever use of keys might even allow Kafka to garbage-collect old versions of dataflows and all but the last PEEK command, allowing Kafka to meet the stricter goal of selective durability.

The problem with a single-partition Kafka topic, AFAICT, is maintaining consistency. You can either validate consistency on the way in, or the way out. I think performing validation on the way in is totally doomed, because Kafka has no write-only-if-nothing-changed primitive. Put another way, let's say that two users simultaneously execute `CREATE DATAFLOW bar SELECT * FROM foo;` and `DROP DATAFLOW bar;`. Only one of these commands can succeed. Either the `CREATE` wins and the `DROP` fails, because `bar` is now depended upon by `foo`, or the `DROP` wins and the `CREATE` fails because `bar` no longer exists. But if you have two clients performing validation simultaneously, they won't know about the other command yet, and so they'll both decide that the command is valid and push the computed action into Kafka, where the computed action is either "definitely build this dataflow" or "definitely drop this dataflow", corresponding to today's [`dataflow::Command`] struct. And now whatever's reading from Kafka on the other end will explode.

So what about performing validation on the way out? In this world I think you push raw SQL into the Kafka topic. Then whatever reads from Kafka parses and validates the SQL, potentially rejecting the command with an error. This seems fundamentally viable, except that the durability is in the wrong place. When materialized crashes and you turn it back on, you'll have all these busted queries sitting in the Kafka topic that you have to run through. It's also not clear how you would use Kafka's automatic garbage collection in this model; you wouldn't want `CREATE DATAFLOW foo AS <valid>; CREATE DATAFLOW foo AS <invalid>` to only remember the invalid command (because it's later)!

There's also the problem that Kafka's strength is not minimizing latency, it's maximizing throughput, so pushing commands through Kafka in the first place might add unacceptable latency to the interactive experience.

FWIW, I fully accept that I may be suffering from insufficient imagination here, and I would love for someone to point out flaws in my reasoning! :)

So what does satisfy all three properties? As far as I can tell, both etcd3 and CockroachDB do, and not much else. CockroachDB isn't a great fit, given how resource hungry it is. etcd3 is actually intended for exactly our desired use case, but there aren't Rust bindings for its v3 API (and the v2 API doesn't actually meet our needs) and it's yet another service that would need to be deployed alongside materialized.

I'm pretty unsure of what the upshot is. One nuclear option is that we could punt on this problem until later, when we tackle active–active replication. That would allow us to rip out the ZooKeeper goop, and get a super-fast in-memory metadata store for tests. If we needed durability in the short term, we could just have one of the workers be responsible for saving metadata updates to disk.

Other, less nuclear options involve:

  * Continuing to hack our way around ZooKeeper. I think this is workable, but
    painful.

  * Switching to etcd3, with the intention of one day bundling it with
    materialized itself.

<small>*I am apparently using `CREATE DATAFLOW` to mean either `CREATE MATERIALIZED VIEW` or `CREATE DATA SOURCE`.</small>

[`dataflow::Command`]: https://github.com/MaterializeInc/materialize/blob/643874305291417cb98c1070131e820b37bb7019/src/materialize/dataflow/server.rs#L35-L36

**Comment by ruchirK** [comment]
I stumbled onto this issue but I think this has actually been solved quite nicely? If theres a problematic view one can use the sqlite3 interface to delete it from the catalog (we probably need to document that more) without involving mz at all

**Comment by benesch** [comment]
Agreed.

> one can use the sqlite3 interface to delete it from the catalog

100%.

> we probably need to document that more

The fact that the catalog is a SQLite database should remain an open secret, IMO. It's a nice escape hatch for us to walk customers through, but I don't want us publicly documenting/committing to the fact that you can use the sqlite3 CLI to perform surgery on Materialize's internal state.
