### ISSUE TITLE
Rewrite results for sqllogictest

### ISSUE THREAD

**Issue by sploiselle** [MaterializeInc/materialize#3323]
I was thinking that @justinj's `datadriven` rewrite feature would be really sick for `sqllogictest`.

I've had to update some of the output for tests that rely on plans, and it sucks; if I could just have the test runner rewrite, those, I'd be really stoked.

**Comment by frankmcsherry** [comment]
`sqllogictest --rewrite-results` should do it for the moment, I think.

**Comment by sploiselle** [comment]
@frankmcsherry Thank you! I tried `rewrite` but obviously not `help` :D
