### ISSUE TITLE
Support string split functions

### ISSUE THREAD

**Issue by rjnn** [MaterializeInc/materialize#3339]
`Split` is a useful string function. It was asked for by a user - for whom `CSV_extract` will do the job, but I wanted to track the work item!

There's a few varieties (`split_part`, `regexp_split_to_array`, `regexp_split_to_table`) and it's unclear which ones are the most important, but that's for someone else to have a stronger point of view on!

cc @sploiselle who might have some thoughts on scoping and work estimates here

**Comment by benesch** [comment]
`split_part` is pretty trivial, probably <1 day of work. `regexp_split_to_array` is blocked on support for proper arrays. `regexp_split_to_table` is probably supportable today with table functions, but I don't know how useful it is in practice.

**Comment by andrioni** [comment]
+1 from me, `split_part` would already be pretty handy.

**Comment by JLDLaughlin** [comment]
@andrioni - `split_part` is now supported!

**Comment by benesch** [comment]
Closing, as `split_part` is implemented and we have `regexp_split_to_table` and `regexp_split_to_array` tracked separately:

 * https://github.com/MaterializeInc/materialize/issues/7153
 * https://github.com/MaterializeInc/materialize/issues/4714
