### ISSUE TITLE
Change default DEBEZIUM envelope behavior from "ORDERED" to "FULL"

### ISSUE THREAD

**Issue by rjnn** [MaterializeInc/materialize#3342]
Since the merging of #3332, which added two ways in which we ingest debezium records, we now have:

@frankmcsherry said
> Seems good to me. I'd be more tempted to have the default be full, in the interest of minimizing surprising crashes and forcing people to opt in to better performance. I'm not strongly opinionated here, though.
which I agree with!

@umanwizard said:
> I don't feel strongly about what the default should be -- I just didn't want to change it in this PR, so we can have a wider discussion about it.
This is the place for that discussion!

(This should also be documented!)

**Comment by morsapaes** [comment]
We no longer support this configuration in `ENVELOPE DEBEZIUM` (see #13309 for context).
