### ISSUE TITLE
Data plane consistency

### ISSUE THREAD

**Issue by jamii** [MaterializeInc/materialize#34]
## Problem

https://github.com/MaterializeInc/materialize/issues/33 deals with control plan consistency. Regardless of which solution we adopt, we still have a related issue on the data plane - we don't have a notion of data plane time and so we don't have any kind of consistency for PEEK. Consequences:

* tests have no way to know if PEEK results are wrong or just not caught up yet, so they have to set a long timeout before failing
* in a replicated setting, PEEK might go back in time if executed against different servers 
* multiple timely workers might resolve PEEK at different timestamps? (I'm not sure of this, but I think @benesch mentioned it)

---

## Solution A

@frankmcsherry suggested rather than allowing workers to read freely from Kafka, add an Advance command which contains a Kafka timestamp and allows workers to read up to the timestamp. This ties data plane times to control plane times, so we can now define PEEK consistency by saying that it must return results that are correct as of the last Advance before the PEEK.

Initial questions:

* Who sends the Advance?
* How much will this impact latency?
* Can our control plane take the throughput?

**Comment by cuongdo** [comment]
This is marked as a 0.4 feature, but I'm not clear on what action is desired here. @frankmcsherry do you have thoughts regarding what might make sense for 0.4?

**Comment by frankmcsherry** [comment]
I think that assignment might be vestigial from an earlier time. I think this is in the "production ready" blockers pile, but it might also be a good idea to file some more specific issues instead of this one (which is maybe over-broad). We do have a fair pile of TODOs on data-plane consistency, which I think mostly fall under "fleshing out BYO consistency" (from my pov).

**Comment by benesch** [comment]
Calling this one superseded by the recently defined correctness properties: https://github.com/MaterializeInc/materialize/blob/main/doc/developer/platform/ux.md#correctness. There are various epics that track the implementation of those properties (e.g., #11631).
