### ISSUE TITLE
Basic test for multi-process

### ISSUE THREAD

**Issue by cuongdo** [MaterializeInc/materialize#3457]
#3448 identified a gap in our testing: we don't have any tests that use multiple processes (`--processes`). We should have at least a basic test to ensure that using multiple processes works at a basic level (stays up with some basic views, etc.).

**Comment by philip-stoev** [comment]
Such a test is included in https://github.com/MaterializeInc/materialize/pull/8947 .

Further testing will be done as the project progresses.
