### ISSUE TITLE
Fix ANY/ALL planning regression

### ISSUE THREAD

**Issue by benesch** [MaterializeInc/materialize#3488]
I'm intentionally introducing a planning regression for ANY/ALL queries in #3399. I'm quite confident that we can fix this—the code is all written—but it is blocked on #3449, and that's not going to land until @frankmcsherry gets back to vacation, and I need #3399 to land in order to make progress on record types.

**Comment by rjnn** [comment]
> until @frankmcsherry gets back to vacation
Interesting Freudian slip 😁

**Comment by cuongdo** [comment]
Is this fully fixed by #3632?

**Comment by benesch** [comment]
Yep. GitHub auto closing fail, thanks.
