### ISSUE TITLE
Hasura support or compatibility

### ISSUE THREAD

**Issue by rrjanbiah** [MaterializeInc/materialize#3496]
Already posted to Hasura https://github.com/hasura/graphql-engine/issues/4307

Not sure who has to implement. But, seems to have great potential as Hasura on plain PostgreSQL is not suitable for all cases.

**Comment by quodlibetor** [comment]
Thanks for your interest in this! We are very interested in hasura compatibility overall, related issues for hasura support are #2772 (which has a great comment explaining our current compat) and we need to support some large subset of pg_catalog #2157 , which we still have lots of work to do to support.

**Comment by cuongdo** [comment]
#4150 provides more detail regarding what's needed for Hasura support

**Comment by awang** [comment]
Closing this issue in favor of #4150, as it has more details
