### ISSUE TITLE
CREATE SINK AS OF documentation example

### ISSUE THREAD

**Issue by rjnn** [MaterializeInc/materialize#3543]
It would be good to get an example of the `AS OF` behavior. Currently, https://materialize.io/docs/sql/create-sink/#as-of contains only a single sentence.

What are the acceptable timestamps? How does one figure out the minimum timestamp one could use? Are these integerers? TIMESTAMP/DATE types? 

Also, now that we have optional timestamps as part of `CREATE SOURCE`, and `CREATE SINK`, We might also want to augment `SHOW FULL VIEWS`, `SHOW FULL SOURCES`, and `SHOW FULL SINKS` to display the timestamp that it is valid from.

For instance, just now I have a source and a view:
```
materialize=> SHOW FULL SOURCES;
  SOURCES   | TYPE | MATERIALIZED 
------------+------+--------------
 wikirecent | USER | f
(1 row)

materialize=> show full views;
     VIEWS     | TYPE | QUERYABLE | MATERIALIZED 
---------------+------+-----------+--------------
 recentchanges | USER | t         | t
 top10         | USER | t         | t
 useredits     | USER | t         | t
(4 rows)
```
Now I want to create a sink that emits diffs from the very start of the source. (I.e. I don't want a snapshot + changes after the snapshot where the system picks the time. I want an empty snapshot followed by all the changes _as they happened_). 

I.E. I want to do:
```
CREATE SINK top10sinkasof FROM top10 INTO AVRO OCF '/Users/arjun/tmp/top10.ocf' AS OF <DAWN OF TIME>
```

It seems that what I want is to do calculate when the upstream sources were created, and use that timestamp. Right now I have no way to understand what that timestamp might be.

cc @ruchirK, @JLDLaughlin, @awang, @frankmcsherry.

**Comment by frankmcsherry** [comment]
> Now I want to create a sink that emits diffs from the very start of the source.

A thing we haven't discussed is that sources do have implicit `AS OF` constraints. We might have lots of history, or we might not. If we are making up the times ourselves, we could pretend that is all the history. If we got this source from someone else who wants to be clear about from when it is valid (any BYO source should have this opportunity) then we want to be careful about how we present output changes for the SINK.

**Comment by rjnn** [comment]
> A thing we haven't discussed is that sources do have implicit AS OF constraints. We might have lots of history, or we might not. If

Right. As I mentioned, I want the `SHOW FULL SOURCES` to display some of this `valid_from` information.

**Comment by frankmcsherry** [comment]
Sorry, I misunderstood the issue as proposing a thing, and then asking for a second thing (the "Now I want..." onwards). Is it ok to mentally replace "`DAWN OF TIME`" with "from the beginning of its validity"?

One thing that is a bit sketchy is that unless we change some things, the `since` lower bounds are going to race with user query submission. We can report what they look like now, but that could change by the time you finish your query. I'm not 100% clear on the likely interactive use case (i.e., where the user wants a specific time, but has to discover that specific time).

**Comment by rjnn** [comment]
Yes, beginning of its validity would do well. Is there a way to tell Materialize that we would like the validity to be something for a view and have that not change?

That could be solved with a subquery? Does not work right now unfortunately:

```
materialize=> create sink tesing from top10 into avro ocf '/Users/arjun/tmp/testing.ocf' as of (select sum(count), sum(count) FILTER (where count < 100000) AS filtered FROM top10);
ERROR:  AS OF does not allow subqueries
```
😢

**Comment by benesch** [comment]
I don't understand the intention of that `AS OF` subquery at all! Can you
say more about the intent?

**Comment by rjnn** [comment]
Oh sorry, that inner subquery is 100% bogus - it was literally just a query I had in my paste buffer to see if subqueries were even allowed. The actual intent would be to execute something like this:

```
create sink tesing from top10 into avro ocf '/Users/arjun/tmp/testing.ocf' as of (select valid_from from show full views where views = top10);
```

**Comment by awang** [comment]
related issues: #2438 and #3617

**Comment by msudberg** [comment]
Closing for now because we temporarily removed the `AS OF` option in #5866.
