### ISSUE TITLE
Document, surface `filter`

### ISSUE THREAD

**Issue by frankmcsherry** [MaterializeInc/materialize#3545]
The `filter` modifier for aggregations appears to be undocumented. At least, one user reported they thought it was not implemented, and I couldn't find it in the docs with some casual searching.

**Comment by rjnn** [comment]
This is a docs item linked to a long-ago engineering item, but there isn't a clear designated engineer who implemented this recently, so we should pool this across the engineering team. Volunteers would be appreciated!

**Comment by benesch** [comment]
I implemented it, but I don't have the slightest clue where it should go in the docs. We don't have anything like the section in which `FILTER` is described in the PostgreSQL docs: https://www.postgresql.org/docs/current/sql-expressions.html#SYNTAX-AGGREGATES

@sploiselle do you have a suggestion?

**Comment by sploiselle** [comment]
Seems like this could be a note in close proximity to the aggregate function list. I can mock something up and see how messy it is.
