### ISSUE TITLE
dataflow: a failure in schema resolution results in runaway schema registry requests

### ISSUE THREAD

**Issue by benesch** [MaterializeInc/materialize#3576]
The schema cache has a defect in that if schema resolution fails, it does not cache the result. See https://github.com/MaterializeInc/materialize/blob/6c2d3e82488ba871f04d62762c612522c968f62e/src/interchange/src/avro.rs#L1229-L1240

This can result in runaway requests, since we'll try again to update the cache for the next record and the next record and the next record...

This doesn't usually come up in practice because _most_ invalid schemas are detected and rejected by the SQL layer during `CREATE SOURCE`. The way we observed this was via a bug in schema resolution that triggered once we got to the `dataflow` layer, but it should be possible to tickle/test this condition by creating a topic with two records with incompatible schemas.

**Comment by umanwizard** [comment]
i will take this on soon
