### ISSUE TITLE
add version check on startup

### ISSUE THREAD

**Issue by rjnn** [MaterializeInc/materialize#3580]
It would be useful for Materialize to perform a version check on startup - by making a simple HTTP GET of the latest version, and report to the user if they're running an old version, and should be nudged to upgrade.

Assigned to @awang to flesh out.

**Comment by umanwizard** [comment]
Sounds like a super useful feature! I do suggest though that we make it easy to turn off, because some users might be averse to any "phoning home", even if telemetry / data collection is not at all our intention.

**Comment by awang** [comment]
Product spec attached to https://github.com/MaterializeInc/product/issues/10
