### ISSUE TITLE
Materialize does not support "SHOW TRANSACTION ISOLATION LEVEL"

### ISSUE THREAD

**Issue by damienhollis** [MaterializeInc/materialize#3593]
### What version of Materialize are you using?

```
$ materialized -v
materialized v0.4.0-dev (a3ef3577d083071d1ece7edd9710ba19063bdfeb)
```                                                                                                     

### How did you install Materialize?

* [ ] Docker image
* [ ] Linux release tarball
* [ ] APT package
* [x] macOS release tarball
* [ ] Homebrew tap
* [ ] Built from source

### What was the issue?
We are trying to use materialize with https://github.com/pgjdbc/r2dbc-postgresql and when creating the initial connection the connection factory calls: `SHOW TRANSACTION ISOLATION LEVEL`

The line reference is:

`r2dbc-postgresql-0.8.3.RELEASE-sources.jar!/io/r2dbc/postgresql/PostgresqlConnectionFactory.java:254`

### Is the issue reproducible? If so, please provide reproduction instructions.
Yes

**Comment by rjnn** [comment]
We should probably support this as a quick win.
