### ISSUE TITLE
CREATE SINK AS OF documentation clarification

### ISSUE THREAD

**Issue by rjnn** [MaterializeInc/materialize#3617]
Now that we have `CREATE SINK AS OF` implemented, we need a clear documentation walkthrough on creating a sink that is valid from a specific point in time.

Since materialized views may have automatically vacuumed up to a time `t1` such that creating sinks at time `t0` where `t0 < t1` may no longer be possible, we need guidelines for users if they need `t0`. This guideline is best added to the `CREATE SINK` docs.

My understanding is if a user wants to guarantee that a sink can be created at a historical `t0`, then they should create the sink off of an _unmaterialized_ view, as that will create a new dataflow which can in fact be spun up.

If this understanding is incorrect, please let me know, (cc @frankmcsherry, @ruchirK )

**Comment by frankmcsherry** [comment]
More than an *unmaterialized* view, the sink would need to be created off of raw sources, and in particular raw sources that are themselves valid for all times. Sources may not be valid for all times for various reasons (e.g. we pull down a copy of the DB when debezium is started and have no prior history, or our own sinks which may only be valid from some time).

At present, if a user requests a thing AS OF a time, and that thing depends on a materialized view, we may tell them "no". We could try and be more energetic and bypass the materialization and return to raw sources, but we have to weight "saying no" against "transparently performing potentially expensive work". Even in this case, the source may not have access to all times.

There may be a UX issue if users expect to be able to announce arbitrary times and receive valid results. We should be able to tell them what times are appropriate, but we may also need to disable compaction (temporarily, or allow manual manipulation of it).

**Comment by ruchirK** [comment]
we got rid of `create sink as of` in #5866 so I think we can close this for now?
