### ISSUE TITLE
consistent terminology: vacuuming vs compaction

### ISSUE THREAD

**Issue by rjnn** [MaterializeInc/materialize#3623]
There are a few concepts which often get confused due to inconsistent terminology. At least, each time we talk about these things, I have to mentally first sort out overlapping concepts and isolate which ones we're talking about. I propose we internally decide on a single consistent set of vocabulary to discuss these concepts, and stick to it (and possibly rename things). I'm indifferent as to where we land, just desire that we do (somewhere).

There are a few things that can happen when we "compact" logical batches and physical batches of data in Materialize:

1. The data is physically rearranged to make it more efficient to look up keys.
1. The data is logically modified so that it is no longer possible to distinguish the value of data at times previous to some watermark.

In database land, the former (physical changes) is often not named, because B-trees do this sort of physical data shuffling relatively eagerly, without large chunks of compaction work done at a time. The latter (logical changes) is sometimes always called "vacuuming". 

In particular, in _Postgres-land_, logically getting rid of the ability to perform reads in the past is called vacuuming, and since we align closely with Postgres on the user level, if we want to choose terminology to expose this to the user to manually drive around, it is useful to use the same name.

In LSM trees (which are relatively new in databases), the former physical rearranging is called "compaction". In particular, in RocksDB (the most popular LSM implementation), LSM pages are immutable, so necessarily, any other thing that happens happens "during compaction.

I believe we also share that second property since batches in differential dataflow are immutable. So it's a convenient shorthand to say that happen "during compaction" (they do!). But morally speaking, we should use separate terminology to drive them around, and I tentatively propose that the terminology we should use is "vacuuming"

**Comment by rjnn** [comment]
cc @frankmcsherry

**Comment by frankmcsherry** [comment]
I think it may be worth sorting out the goal. If it is "to communicate with postgres users" then feel free to use "vacuuming" for logical compaction. If the goal is technical clarity, I personally use (and recommend) "logical compaction" and "physical compaction" and will almost certainly will continue to use them myself (don't let that stop the company from using other terms). The logical-physical distinction comes up in a few other places in differential dataflow (I thinking at least of input batching) and I have found to be helpful generally to explain the distinction between ways a system might behave.

**Comment by benesch** [comment]
By my read of the PostgreSQL docs on [`VACUUM`](https://www.postgresql.org/docs/current/sql-vacuum.html), the term is actually closer to physical compaction than logical compaction.
