### ISSUE TITLE
Support Avro Duration logical type

### ISSUE THREAD

**Issue by JLDLaughlin** [MaterializeInc/materialize#3630]
Logical types described [here](https://avro.apache.org/docs/current/spec.html#Logical+Types)

**Comment by quodlibetor** [comment]
> The duration logical type represents an amount of time defined by a number of months, days and milliseconds. This is not equivalent to a number of milliseconds, because, depending on the moment in time from which the duration is measured...

> A duration logical type annotates Avro fixed type of size 12, which stores three little-endian unsigned integers that represent durations at different granularities of time. The first stores a number in months, the second stores a number in days, and the third stores a number in milliseconds.

3 i32s packed into a 12-byte string. Amazing.

**Comment by morsapaes** [comment]
Consolidated into #3629.
