### ISSUE TITLE
sql: support tables

### ISSUE THREAD

**Issue by benesch** [MaterializeInc/materialize#3638]
We should support basic tables and insert statements. This is an alternative to #1701 that allows us to re-use the existing SQL interface rather than introducing a new HTTP interface. If we _do_ want to support the HTTP interface someday, we'll be able to easily build it on top of this interface; plus it'll be easy to write a separate HTTP -> SQL microservice externally if someone needs it urgently.

Here's the rough scope of the feature:

```sql
CREATE TABLE t (
    a int,
    b text NOT NULL,
)
```

```sql
INSERT INTO t VALUES (1, 'a')
```

```sql
DROP TABLE t
```

Things that are explicitly out of scope:

* Primary keys. Tables always have no primary key, in the SQL sense of the word. In the differential sense, that means that a table is stored in an arrangement that stores all columns.
* Unique constraints. Tables do not support checking uniqueness.
* Check constraints. Tables do not validate input data beyond types and `NOT NULL` constraints.
* Default column values. Tables do not allow specifying column defaults, and `INSERT` statements therefore must always specify all columns.
* `INSERT INTO ... SELECT`. Insert statements that use anything but a `VALUES` clause to specify their data are out of scope.
* `UPDATE ...` and `DELETE`. Update and delete statements are harder because they require read/write transactions, whereas insert statements require just write-only transactions.
* Persistence. `INSERT` statements will not persist data until we have source persistence. Restarting materialized will result in a bunch of empty tables.

I believe the parser already has support for parsing `CREATE TABLE` and `INSERT` to the extent that we need it to, so the work here will happen almost entirely in the `sql`/`coord` crates.

There may be some timestamp shenanigans required, but the gist is that `INSERT`s should occur at the wall-clock time that they are processed by the coordinator. They'll look very similar to the stuff that @justinj is doing in #3535.

Symbiosis mode's support for `CREATE TABLE` and `INSERT` should override our support for `CREATE TABLE` and `INSERT`, since Cockroach's SLTs use all sorts of crazy `CREATE TABLE` and `INSERT` statements. This'll require a bit of refactoring of the logic that decides whether to run a given query against materialized or PostgreSQL, but it shouldn't be too bad.

**Comment by cuongdo** [comment]
If table definitions are written to the catalog, should we also support `DROP TABLE`? If we don't it seems that tables will remain in the catalog forever.

Also, are `UPDATE` and `DELETE` explicitly out of scope?

**Comment by benesch** [comment]
Good catches, @cuongdo! I've reflected the issue description to reflect that `DROP TABLE` is in scope but `UPDATE` and `DELETE` are out of scope.

If we need to support `UPDATE` and `DELETE`, we definitely can, but it will be a lot more work.

**Comment by cuongdo** [comment]
@JLDLaughlin @benesch Are we done with this for 0.5? If so, please close the issue.

**Comment by JLDLaughlin** [comment]
We are done with the scoped version of table support described in this issue!
