### ISSUE TITLE
Document swap space soft requirements, and how to configure it on Mac, Linux, and Docker

### ISSUE THREAD

**Issue by rjnn** [MaterializeInc/materialize#3669]
Right now, users aren't aware that they should give Materialize ample swap space. When setting up standard Linux VMs, this is important to know ahead of time.

This is also important to get right in Docker.

AFAIK OS X just does the right thing out of the box and lets you swap out to the whole disk, which is great.

We should add this to the docs site, as this comes up repeatedly.

**Comment by awang** [comment]
reopening -- add more instructions on how to setup swap
