### ISSUE TITLE
Optimize LIMIT 0, and LIMIT without ORDER BY

### ISSUE THREAD

**Issue by rjnn** [MaterializeInc/materialize#3670]
Selecting a single column with limit 0 is pretty fast, no worries there:

```
mz> select v.transaction_timestamp from fake_tx_view v limit 0;
+-------------------------+
| transaction_timestamp   |
|-------------------------|
+-------------------------+
SELECT 0
Time: 0.014s
```

Adding a date_trunc  to this column, the query gets noticeable slower (around 0.7~0.8 seconds):

```
mz> select date_trunc('minute', v.transaction_timestamp) from fake_tx_view v limit 0;
+--------------+
| date_trunc   |
|--------------|
+--------------+
SELECT 0
Time: 0.730s
```

We should special case out and push `LIMIT`s that don't `ORDER BY`s.

Thanks @andrioni for the report. Cc @frankmcsherry if there are any subtleties or if this is just a quick win. Even if its a longer refactor, I thought we could benefit from tracking an issue for it. cc @awang.

**Comment by benesch** [comment]
Can you say more about the use case? (In general it would be very helpful if these sorts of issues included the why in addition to the what.) `LIMIT 0` doesn't seem like it would ever be a useful query—so while we can optimize it, it's not clear to me (yet?) why we should spend time on it. Happy to be convinced!

**Comment by benesch** [comment]
Oh, is the `LIMIT 0` just to demonstrate that we don't currently optimize `LIMIT` without `ORDER BY` at all?

**Comment by frankmcsherry** [comment]
A user was trying it out as a way to prototype queries, but with an attempt to minimize the cost of running (e.g. post-pend with a limit statement). They had not particular interest in `limit 0`, and just tried it because `limit k` was also slower than they expected (both could be pushed up in their query, but `limit 0` was the "surprisingly slow" one).

**Comment by wangandi** [comment]
We also need to optimize limit 0 and limit without order by in the materialized view case. Currently, it is very memory expensive because the limit/offset is rendered as a `TopK`. We should maintain the view without the limit/offset and apply the limit/offset at select time. (Related: #724)

**Comment by frankmcsherry** [comment]
The `LIMIT 0` case should now be handled by #5768 (tyvm @andrioni for observing). No changes to limit without order by, but also no information about how that implementation would be specialized correctly.

**Comment by frankmcsherry** [comment]
This should be complete now. As mentioned above `limit 0` is optimized out of dataflow plans (not `RowSetFinishing`), and `limit k` without an `order by` is plenty fast in tests I just did (6ms to pull out `select * from lineitem limit 1`).
