### ISSUE TITLE
Avro keys are erroneously assumed to be a subset of the value schema

### ISSUE THREAD

**Issue by umanwizard** [MaterializeInc/materialize#3677]
We should gracefully handle the case when this isn't true; for example, by just ignoring key info (which can block some optimizations, but will generally be correct). In the future, we might also think about letting the user specify which columns are keys.

**Comment by wangandi** [comment]
This problem applies to ENVELOPE NONE and to ENVELOPE DEBEZIUM.

ENVELOPE UPSERT has the opposite problem (#3370).
