### ISSUE TITLE
Support UUID types inside Materialize

### ISSUE THREAD

**Issue by andrioni** [MaterializeInc/materialize#3687]
It would be nice to have UUIDs as a possible data type, mainly for memory efficiency. UUIDs are also supported in Postgres. Related somewhat to #3577.

**Comment by awang** [comment]
Great idea! @benesch and @umanwizard, do you think this would make more sense as an extension (which I believe we currently don't support)

**Comment by benesch** [comment]
> Great idea! @benesch and @umanwizard, do you think this would make more sense as an extension (which I believe we currently don't support)

It'll be years before we support any sort of extension framework, unless you know something I don't, @awang. It's gonna have to be part of the core product. But that's fine! It's important enough to be part of the core product in CockroachDB (and mostly in PostgreSQL, too).

The change is straightforward—just apply some elbow grease—but I'm not sure who's going to do it, or when.

**Comment by umanwizard** [comment]
Related to https://github.com/MaterializeInc/materialize/issues/3577 , which is the task to support decoding them as a separate type in Avro.
