### ISSUE TITLE
implement enough of pg_catalog to unfork pgjdbc for metabase

### ISSUE THREAD

**Issue by rjnn** [MaterializeInc/materialize#3727]
Context: https://github.com/MaterializeInc/materialize/issues/1713#issuecomment-579315231

This is a useful first test of `pg_catalog` compatibility.

**Comment by rjnn** [comment]
cc #2157.

**Comment by JLDLaughlin** [comment]
Required work:
- [ ] Support [`SHOW TRANSACTION ISOLATION LEVEL`](https://github.com/MaterializeInc/pgjdbc/commit/b3050c5e0eb58fd3000b91e223165fca599feea6)
- [ ] Support [`getTables` query](https://github.com/MaterializeInc/pgjdbc/commit/014fa5a7df56cf80185e8802f14dec2621f64278)
- [ ] Support or handle [unsupported Postgres types](https://github.com/MaterializeInc/pgjdbc/commit/05d75f3b24833363a67e8e92bab25a906f3fcc4c)
- [ ] Support [`getPrimaryKeys` query](https://github.com/MaterializeInc/pgjdbc/commit/fef07ebb20e97c648f35aacf52b07b9b4c996975). **Note: This is currently blocked on https://github.com/MaterializeInc/materialize/issues/883**
- [ ] Support [`getColumns` query](https://github.com/MaterializeInc/pgjdbc/commit/ebc320937219cd206230bc193d5337a7bc2eca5d)
- [ ] Support [`getSchemas` query](https://github.com/MaterializeInc/pgjdbc/commit/d249591ba562684a5755028f105368ba53acd8fc)
- [ ] Support [`getSqlType`](https://github.com/MaterializeInc/pgjdbc/commit/7a10425ae095f8d93cb1cd0b6800d02031249631#diff-49fcaf90c4908b482951125628e65c3bL184)
- [ ] Support [`getPGType `](https://github.com/MaterializeInc/pgjdbc/commit/7a10425ae095f8d93cb1cd0b6800d02031249631#diff-49fcaf90c4908b482951125628e65c3bL361)
- [ ] Support [`getImportedKeys`](https://github.com/MaterializeInc/pgjdbc/commit/147b51e4f57e64c71c187f62e11441b17b46c4ac#diff-51599ad44370100577a1a80caa64ee2bL2079)
- [ ] Support [`getExportedKeys`](https://github.com/MaterializeInc/pgjdbc/commit/147b51e4f57e64c71c187f62e11441b17b46c4ac#diff-51599ad44370100577a1a80caa64ee2bL2084)

**Comment by cuongdo** [comment]
Setting milestone to 0.6, because this has already started.

**Comment by andrioni** [comment]
Metabase currently works out of the box with vanilla pgjdbc 🎉 , so I'm closing this issue. Support for Looker is tracked now in #9531, while support for Tableau will be tracked later on.
