### ISSUE TITLE
SELECT queries could close inputs immediately

### ISSUE THREAD

**Issue by frankmcsherry** [MaterializeInc/materialize#3740]
SELECT queries are issued at times whose data are immediately available. However, we install the dataflows to accept ongoing streams of changes. While the SELECT queries will quickly be cleaned up, there is a non-trivial efficiency overhead executing the queries without closing the inputs: as soon as we can determine that an operator will receive no more messages it can be shut down, reclaiming memory and ceasing further work. At the moment, we hold on to the memory and continue to process updates until the output has been received and the dataflow as a whole can be terminated.

Most likely this looks like an additional `DataflowDesc` parameter which indicates at which time the dataflow can be terminated, which can be used for the source and arrangement import operators to allow them to wind down eagerly. Not clear exactly how this happens (we control sources; perhaps not arrangement imports).

**Comment by antiguru** [comment]
Dataflows come with an `until` parameter, which allows sources to cease producing data at a specific point in time.
