### ISSUE TITLE
Correlate capability downgrade events

### ISSUE THREAD

**Issue by frankmcsherry** [MaterializeInc/materialize#3777]
Our input sources downgrade their capabilities at a frequency that the user can specify (using the `timestamp_frequency_ms` argument). However, at the moment our sources do this in an uncorrelated manner, which results in an increase in the number of distinct timestamps by a factor proportional to the number of workers. Differential dataflow operators perform incremental work for each distinct timestamp, and so uncorrelated rounding can result in a factor of `#workers` more total work to do than if the rounding were correlated.

cc: @nacrooks

**Comment by benesch** [comment]
Was this fixed by #3782?

**Comment by nacrooks** [comment]
Yes!
