### ISSUE TITLE
It should be possible to share non-materialized sources across dataflows

### ISSUE THREAD

**Issue by quodlibetor** [MaterializeInc/materialize#3794]
Currently if you have a non-materialized source all materialized views that depend on it will incur an extra read of every item in the stream. It should be possible to express multiple materialized views that all want to read from the same source, but only once.

For example, this will read the same data from kafka at least two times:

```sql
CREATE SOURCE foo FROM kafka;
CREATE MATERIALIZED VIEW bar AS SELECT .. FROM foo;
CREATE MATERIALIZED VIEW quux AS SELECT .. FROM foo;
```

While in the long term we'd like to support arbitrary merging of dataflows, doing that is hard. Edit: the part of merging dataflows that directly impacts this is #3791 .

In the past, the way that we've discussed supporting this is by requiring that views be created as part of a transaction if you want them to use the same data:

```sql
BEGIN;
CREATE SOURCE foo FROM kafka;
CREATE MATERIALIZED VIEW bar AS SELECT .. FROM foo;
CREATE MATERIALIZED VIEW quux AS SELECT .. FROM foo;
COMMIT;
```

This is related to #3793 , but is not as far-reaching.

**Comment by frankmcsherry** [comment]
Related to #3791.

**Comment by benesch** [comment]
Prior art: #33 #318 #399 #1919. None of these are exact duplicates, but probably only one needs to exist.

**Comment by benesch** [comment]
Now that we've agreed that #3791 is worth doing, the remainder of this issue (atomically creating multiple dataflows) is covered by #318, so let's centralize discussion there!
