### ISSUE TITLE
Support for Snappy-compressed Avro files

### ISSUE THREAD

**Issue by andrioni** [MaterializeInc/materialize#3811]
Right now the mz-avro crate is being built without support for snappy, so any attempts to read an Avro file compressed with snappy just return the following error:
```
Decoding error: unrecognized codec 'snappy'
```

The code in mz-avro also doesn't work anymore out of the box with `snap` 1.0, as there were some minor breaking changes in the API. It does build fine with 0.2.5, though.

**Comment by umanwizard** [comment]
@andrioni , what build errors were you getting when trying with snap 1.0 ? It seems to be working for me.
