### ISSUE TITLE
dataflow,transform: unimplemented join panic

### ISSUE THREAD

**Issue by benesch** [MaterializeInc/materialize#3817]
```sql
    SELECT CASE a+1 WHEN b THEN 111 WHEN c THEN 222
            WHEN d THEN 333  WHEN e THEN 444 ELSE 555 END,
           CASE WHEN a<b-3 THEN 111 WHEN a<=b THEN 222
            WHEN a<b+3 THEN 333 ELSE 444 END,
           a+b*2+c*3+d*4,
           a+b*2+c*3,
           c,
           CASE WHEN c>(SELECT avg(c) FROM t1) THEN a*2 ELSE b*10 END,
           abs(b-c)
      FROM t1
     WHERE EXISTS(SELECT 1 FROM t1 AS x WHERE x.b<t1.b)
        OR b>c
        OR d NOT BETWEEN 110 AND 150
     ORDER BY 4,1,5,2,6,3,7
```
```
thread 'timely:work-2' panicked at 'Attempt to render unimplemented join', src/dataflow/src/render/mod.rs:964:29
```
https://buildkite.com/materialize/sql-logic-tests/builds/4854#93c27415-9cd5-48a4-b209-d787ac0e7e87

**Comment by wangandi** [comment]
I have copied the test in question and the t1 table creation into a file attached so that we can reproduce the issue without having to run the entire select1.test.

Attached file also contains a copy of the plan containing the unimplemented join.

[issue-3817.txt](https://github.com/MaterializeInc/materialize/files/5008832/issue-3817.txt)

**Comment by frankmcsherry** [comment]
It looks like it is just an optimization order issue. LiteralLifting can unimplement a join, and is part of physical planning for unclear reasons!

**Comment by wangandi** [comment]
It's not LiteralLifting unimplementing the join. If LiteralLifting unimplemented the join, it being in the same fixpoint as JoinImplementation would mean that the join implementation would be restored.

It's the final ProjectionLifting that is causing the join to become unimplemented.

**Comment by benesch** [comment]
Ooh, ok. If it's that simple, I've maybe got a fix out in https://github.com/MaterializeInc/materialize/pull/3826. Thanks for tracking down the issue!
