### ISSUE TITLE
Support Parquet as a source format

### ISSUE THREAD

**Issue by rjnn** [MaterializeInc/materialize#386]
Not every input to Materialize will be a Kafka topic. In particular, database backups are a format worth supporting as-is to create a source. In making some simplifying assumptions, we can assume the dumpfile is a set of DDL and INSERT statements in the standard mysqldump format, and is stored in a single file on S3/Google Cloud Storage/Azure Blob Storage, and was backed up with `--gtid` enabled.

cc @benesch for triage - perhaps this issue seems familiar to you? :)

**Comment by dazzag24** [comment]
+1 for Parquet support.  I can see definite use cases for using Materialize to process our parquet datasets stored on Azure blob.

**Comment by rjnn** [comment]
@dazzag24 thanks for the input! I'd love to grab a longer conversation with you if possible - we have a few different paths to supporting Parquet, and understanding your use cases would be very valuable inputs to those design decisions.

**Comment by quodlibetor** [comment]
A related (but row- instead of column-oriented) file format that we _do_ support right now is Avro ObjectContainerFiles. Pointing it out because it comes up in similar spaces that folks want to use parquet in but wasn't mentioned in an earlier list of filetypes that we support OOTB.

**Comment by rjnn** [comment]
I wonder how much work it is to add support for Parquet...

**Comment by quodlibetor** [comment]
Unfortunately the main rust crate for parquet uses the rust nightly "specialization" feature, and it seems like [they think] that will be hard to remove.

[they think]: https://issues.apache.org/jira/browse/ARROW-4678

**Comment by rjnn** [comment]
the linked issue is Arrow, not Parquet?

**Comment by rjnn** [comment]
(redacting my previous comment, i understand now).

**Comment by alippai** [comment]
I assume @andygrove can help with an authoritative answer

**Comment by jdotjdot** [comment]
Another big +1 here for Parquet support.  I've done a lot of migrations between warehouses, regular dumping of OLTP data to OLAP warehouses, and I also regularly keep flat copies of the OLTP data in S3 for arbitrary queries with Presto or Athena as needed. In all cases, Parquet is the main storage format I use in-between.  Parquet would be very useful.

**Comment by andrioni** [comment]
Good news: with apache/arrow#8698, Arrow (and Parquet) doesn't require nightly anymore. I believe they are planning to cut Arrow 3.0 in early January.

**Comment by awang** [comment]
Looks like arrow 3.0 just dropped, we should consider leveraging it for Parquet support.

**Comment by benesch** [comment]
Yep, this would definitely be a nice to have, but our bandwidth for maintaining yet another source format is a bit thin at the moment. The data types are here: https://docs.rs/arrow/3.0.0/arrow/datatypes/enum.DataType.html. Per usual they don't map perfectly to ours—notably the existence of unsigned types, which has been a persistent irritation. (Protobuf also has unsigned types.)

On the bright side, the `arrow` crate looks to be in much better shape than the `avro` crate was. That's promising. The `parquet` crate sadly looks a bit spottier, based on the number of missing docs, but still hopefully serviceable.

**Comment by morsapaes** [comment]
**Update:** we're working on bulk imports and exports to blob storage, starting with s3. Parquet support will be considered in the scope of that work. Closing this issue in favor of #21902 and #7256. It's been a mighty long time, but if anyone is still interested in taking this for a spin when it's released into Private Preview, let us know!

@rjnn, we'll be tracking support for one-click catalog metadata exports in [Console #1671](https://github.com/MaterializeInc/console/issues/1671) as a first stab at supporting `pg_dump`-like functionality.
