### ISSUE TITLE
Embed assets (d3/bootstrap) in Materialize instead of using a CDN, or remove the dependency

### ISSUE THREAD

**Issue by umanwizard** [MaterializeInc/materialize#3860]
_Originally posted by @benesch in https://github.com/MaterializeInc/materialize/pull/3859#issuecomment-669208425_

**Comment by benesch** [comment]
Upon reflection, Brennan is starting to convince me that perhaps this isn't so bad, but marking as an 0.5 release blocker so we remember to revisit before this ships.
