### ISSUE TITLE
docs: versioning

### ISSUE THREAD

**Issue by benesch** [MaterializeInc/materialize#3868]
We run into weird issues when we add documentation for a new feature before that feature makes it into a stable release of Materialize. See #3867, for example.

The way this is usually handled is by building different versions of the docs for each release. See the PostgreSQL or CockroachDB docs, for example. Unfortunately there are all sorts of hidden complexities here. Netlify can't build/publish a site from multiple branches at once (not easily, at least).  Version selectors that work correctly across versions are hard when pages move around.

**Comment by benesch** [comment]
I think a good middle ground could be something similar to Sphinx's `versionadded` directive: https://www.sphinx-doc.org/en/1.7/markup/para.html#directive-versionadded

The gist is that you drop these annotations around when you add a new feature, and a line like *New in version x.y* gets rendered in the docs. For extra smarts, we can compare the "added in" version to the most recent version, and if it's not yet in a release, render it with a big warning label. Basically what #3867 is doing, but in a way that won't require us to remember to remove the warnings when the release ships.

**Comment by sploiselle** [comment]
Yeah, I think your idea for something akin to `versionadded` is ideal to allow us "soft" versioning.
