### ISSUE TITLE
sql: INSERT does not reject column specifications

### ISSUE THREAD

**Issue by benesch** [MaterializeInc/materialize#3903]
The following query succeeds, but it shouldn't, because the user has specified they only want to provide a value for column `a`, but then include values for both `a` and `b`:

```
create table t (a int, b int);
insert into t (a) values (1, 2);
```

Relatedly,

```sql
insert into t (b, a) values (1, 2);
```

will insert `1` for `a` and `2` for `b`, when the semantics of the query actually require the reverse.

We definitely shouldn't support the first example. Probably we should support the second example, but not urgent as long as we at least return an error message instead of silently doing the wrong thing!

**Comment by JLDLaughlin** [comment]
Why would we not want to support the first use case eventually?

**Comment by benesch** [comment]
Hah, so I thought we needed to support defaults (e.g. `create table t (a int, b int default 7)`) before the first example was useful, but it turns out the default default is null so it's actually reasonable to support in the meantime. We must've had the same thought at the same time, because I just posted exactly this on #3911 :D.
