### ISSUE TITLE
Should `render.rs` perform any optimizations?

### ISSUE THREAD

**Issue by frankmcsherry** [MaterializeInc/materialize#391]
Presently `render.rs` takes the opportunity to identify re-use of collections and arrangements, which is fairly easy for it to do by maintaining a map from `RelationExpr` to assembled dataflow elements. At the same time, perhaps this is a poor design, where something like the coordinator should be making decisions of this sort. None of the `render.rs` decisions seem bad (they are all "no brainers") but at the moment it may render graphs that have different structure than what it was asked to render.

The AST has `let` and `get` nodes, and we can *describe* opportunities for re-use in the `RelationExpr`. It isn't clear that we can capture 100% of the detail yet (e.g., noticing which relations are arranged by which keys), but it seems plausible that this level of decision making can be promoted upwards. 

A first step could be a query transformation that introduces let bindings on behalf of render.rs, which then just finds it has relatively fewer opportunities for cleverness. @apparebit may have an appetite for that, as it touches on some recent work. But, everyone might have an opinion on where the cleverness and surprises should live.

**Comment by ruchirK** [comment]
I think we can close this issue too - given that render.rs now has a dedicated lower level IR and performs optimizations?
