### ISSUE TITLE
mz_catalog sources, tables, and views are undocumented

### ISSUE THREAD

**Issue by JLDLaughlin** [MaterializeInc/materialize#3984]
Sources, tables, and views in the `mz_catalog` schema contain important metadata information about the performance of a given `materialized` instance. To allow users (and myself!) to make use of this information, we need to provide documentation about the purpose of each of these objects and the data found within them.

**Comment by sploiselle** [comment]
Is this closable with https://materialize.com/docs/sql/system-catalog/?

**Comment by benesch** [comment]
Many of the interesting views are still undocumented, sadly. We should get them documented!
