### ISSUE TITLE
Dataflow description revamp

### ISSUE THREAD

**Issue by frankmcsherry** [MaterializeInc/materialize#399]
I'd like to think through a revamp of the `Dataflow` type, which is currently:
```rust
pub enum Dataflow {
    Source(Source),
    Sink(Sink),
    View(View),
}
```
Each of these are interesting dataflow elements, but there is a bit of a .. trichotomy here that isn't strictly necessary. For example, it is totally reasonable to want to import a verbose source and apply some filtering and projection to it before publishing it. It is also reasonable to assemble a few views at the same time (using the same dataflow) and publish some of the results and feed others to sinks, without publishing the results for others to see.

My thinking is that we can re-arrange `Dataflow` to look a bit more like what differential dataflow is able to do, at which point `Source`, `Sink`, and `View` each become idioms in a larger vocabulary. We need to retain the detail that `Source` and `Sink` do other things (e.g. provide capabilities, so that we can squash inputs when appropriate). Perhaps this planning would clarify what exactly we need them to do or not do?

Each dataflow (without the `Dataflow` to mean a timely/differential dataflow) is able to register any number of sources, create multiply headed dataflows, each of which could be published and or fed to any number of sinks. 

The main restriction of a dataflow is that the execution of elements in the dataflow are coupled: it is difficult to terminate part of a dataflow without affecting other parts of the dataflow; if one published arrangement is still in common use, the whole dataflow should be retained even if parts of it are not especially interesting. Parts of a dataflow can be shutdown by pressing shutdown buttons for some of their inputs, but some analysis would be needed to determine the inputs that will not affect still-important arrangements.

**Comment by benesch** [comment]
This did in fact get done! The resulting type was called `DataflowDesc`: https://github.com/MaterializeInc/materialize/blob/17a67b4f6bd0daa18014c147100ec8022c2c3d69/src/dataflow-types/src/types.rs#L77-L101

It's probably evolved substantially since this issue was filed, but morally I think we can consider this complete!
