### ISSUE TITLE
Source persistence doesn't work correctly with materialized sources

### ISSUE THREAD

**Issue by ruchirK** [MaterializeInc/materialize#4023]
On restart, persisted sources need to check if there are any previously persisted files available and if so, the coordinator needs to augment the source connector with the required list of files + starting offsets so that persisted sources read from the files for data that we've already seen, and start reading from the upstream broker at the new starting offsets.

We use the strategy for augmenting sink connectors where we update a connector by dropping the catalog entry and then reinserting an updated one with the all the same data except a modified connector. This works fine for sources that are unmaterialized, but does not work correctly for sources that are materialized and have a associated index.

**Comment by justinj** [comment]
Fixed by #4038.
