### ISSUE TITLE
Add metrics / more intelligent introspection around persistence

### ISSUE THREAD

**Issue by ruchirK** [MaterializeInc/materialize#4025]
I'm not 100% sure what metrics and introspection would be nice to have but imo

on a per topic / per partition basis
- records persisted
- bytes persisted
- records / bytes waiting to be persisted
- number of files we wrote to / number of times we wrote

I think we could potentially also explore a system table / log like `mz_persistence_frontiers` for some of this data but having metrics is nice because you can observe that postmortem

**Comment by cuongdo** [comment]
cc @danhhz

**Comment by elindsey** [comment]
I'm not sure if this was about the old source caching system or the newer persistence work, but I'm moving it to the Persistence project board for triage

**Comment by ruchirK** [comment]
> having metrics is nice because you can observe that postmortem

clearly didn't anticipate persistent tables :D
