### ISSUE TITLE
Harden source persistence against file modifications / incorrect deletions

### ISSUE THREAD

**Issue by ruchirK** [MaterializeInc/materialize#4030]
Right now the source persistence code fails if a user either deletes a subset of persisted files, or if a user modifies any of the persisted files. We need to harden against both cases by:

-- checking that the set of persisted files actually contains the prefix that we think they do (for example if we think we have the prefix from [0, 300) but we only have files for [0, 50) and [200, 300) we are missing something)
-- introducing a header to persistence files that includes

- catalog id (pending #4029)
- source id
- partition id
- start offset
- end offset
- checksum

and teaching the coordinator to respect this header.

**Comment by awang** [comment]
@ruchirK is this one finished?

**Comment by ruchirK** [comment]
Hey Albert this isn't finished. I'll put up a PR for it this week

**Comment by ruchirK** [comment]
closing this because source caching (fka source persistence) was removed in #7328 (we're going to go a different direction with the persist crate)
