### ISSUE TITLE
Chaos tests for persistence

### ISSUE THREAD

**Issue by ruchirK** [MaterializeInc/materialize#4031]
There's a few different flavors of chaos that I think we should care about:

- repeatedly creating and destroying sources
- repeatedly killing and restarting materialize
- incorrectly deleting the catalog
- incorrectly deleting / renaming / modifying persistence files
- plugging persistence into other chaos tests?

This depends on #4029 and #4030

**Comment by cuongdo** [comment]
cc @danhhz

**Comment by elindsey** [comment]
Moving to the Persistence project board for triage - pretty sure this is a stale task related to source caching, but not positive.

**Comment by danhhz** [comment]
This is obsoleted by various testing efforts from philip
