### ISSUE TITLE
Clearer delineation between in-memory and persisted state for catalog objects

### ISSUE THREAD

**Issue by justinj** [MaterializeInc/materialize#4040]
As referenced in [this comment](https://github.com/MaterializeInc/materialize/pull/4038#issuecomment-679534845), these currently overlap and it would be good to have the distinction be clearer.

**Comment by jkosh44** [comment]
This should be resolved by the separation of https://github.com/MaterializeInc/materialize/blob/adc2a0e02eb01523710a3c223128ec6ff112b992/src/catalog/src/durable/objects.rs#L10-L26 and https://github.com/MaterializeInc/materialize/blob/adc2a0e02eb01523710a3c223128ec6ff112b992/src/catalog/src/memory/objects.rs#L10-L12.
