### ISSUE TITLE
Implement CDC v2 Format

### ISSUE THREAD

**Issue by awang** [MaterializeInc/materialize#4041]
(This might be an epic ticket, so we should break this down further)

As described in https://github.com/frankmcsherry/blog/blob/master/posts/2020-08-01.md

We've started a PR that adds CDCv2: TimelyDataflow/differential-dataflow#279
There are some changes to make (un-fix bincode as the only serialization strategy) and probably a great deal more testing to do.

**Comment by cuongdo** [comment]
@benesch Could you break this down into discrete tasks?

**Comment by frankmcsherry** [comment]
> There are some changes to make (un-fix bincode as the only serialization strategy) and probably a great deal more testing to do.

The PR has landed several days ago and the bincode change has been made.

**Comment by cuongdo** [comment]
Reassigned to @umanwizard, who will be taking this on.

**Comment by awang** [comment]
only support sources for now, not yet sinks

**Comment by umanwizard** [comment]
Closed as we have another issue for sinks.
