### ISSUE TITLE
materialize.io: remove kafka.materialize.io

### ISSUE THREAD

**Issue by benesch** [MaterializeInc/materialize#4051]
I'm not sure what this is pointing to, and I don't think it belongs on a channel as official as a subdomain of materialize.io. (See #4050 for more of this rationale.)

Let's either remove it if it's not important, or move it to `kafka.mtrlz.dev`.

**Comment by awang** [comment]
As discussed, we'll change it to `analytics.materialize.io` (or something like that) instead.

Internal docs on the setup:
https://github.com/MaterializeInc/infra/blob/main/handbook/handbook/infrastructure/snowplow.md
https://docs.google.com/document/d/1NstLcahwZSfW2060w7pNP5PWpH9EKv1LePlEZN63gII/edit?usp=sharing

Related issue:
https://github.com/MaterializeInc/infra/issues/303

**Comment by benesch** [comment]
Tracked in an internal repository now. (There's a link to the issue in the event stream above, for folks at the company.)
