### ISSUE TITLE
sql: map type

### ISSUE THREAD

**Issue by benesch** [MaterializeInc/materialize#4052]
Avro supports a map type which takes strings to arbitrary values. This is a bit annoying to use in SQL. We can't use records, since the map keys are not fixed by the schema. We could use the `json` type (this is actually what's done for protobuf today), but this has the significant downside of dynamic typing of the value, whereas the Avro schema contains the type of the value. The closest analog in PostgreSQL is the [`hstore` extension](https://www.postgresql.org/docs/current/hstore.html), but hstore uses freeform keys _and_ values.

The best approach is probably to build a new map type that is modeled off of the hstore type, except that the value type can be any arbitrary SQL type.

**Comment by andrioni** [comment]
For reference, the way we at Nubank currently work around it on BigQuery is by processing maps as lists of key-value pairs (since Avro maps have fixed types for keys and values). It's definitely not the most efficient or pleasant to query approach, but it gets the job done.

**Comment by JLDLaughlin** [comment]
Implemented here: https://github.com/MaterializeInc/materialize/pull/4801
