### ISSUE TITLE
Determine chbench queries to run in benchmarks

### ISSUE THREAD

**Issue by cirego** [MaterializeInc/materialize#4056]
We need to figure out which chbench queries to run in our benchmarks because we don't support all of the queries. Determine which set of queries we want to support.

**Comment by sploiselle** [comment]
We should run all queries to determine performance and bottle necks.

**Comment by sploiselle** [comment]
Seems like there is some complexity to investigate here because some queries might regularly OOM, which might prevent us from really benchmarking anything; details in #521
