### ISSUE TITLE
SHOW COLUMNS output not ordered in source order

### ISSUE THREAD

**Issue by mjibson** [MaterializeInc/materialize#4084]
On master:

```
materialize=> create table t (b date, a text);
CREATE TABLE
materialize=> show create table t;
        Table         |                         Create Table                         
----------------------+--------------------------------------------------------------
 materialize.public.t | CREATE TABLE "materialize"."public"."t" ("b" date, "a" text)
(1 row)

materialize=> show columns from t;
 Field | Nullable | Type 
-------+----------+------
 a     | YES      | text
 b     | YES      | date
(2 rows)
```

While the column order in the table is `b, a`, `SHOW COLUMNS` reports the alphabetically sorted `a, b`. Printing some debugs in statement.rs:handle_show_columns I see that the columns are being iterated over in the defined order, so something downstream must be sorting them. This matters for the new CREATE TABLE/INSERT stuff. INSERT doesn't support specifying columns yet, so trying to programatically insert random data into one of these tables needs SHOW COLUMNS to use the same order as INSERT expects.

While SELECT doesn't need to guarantee order without an ORDER BY, SHOW statements perhaps could have a guaranteed order. Or else maybe some additional column that is the source order or something.

**Comment by JLDLaughlin** [comment]
Good spot! I actually just found this too working on https://github.com/MaterializeInc/materialize/issues/913. Should be fixed shortly!

**Comment by JLDLaughlin** [comment]
WIP PR: https://github.com/MaterializeInc/materialize/pull/4085

**Comment by JLDLaughlin** [comment]
#4085 didn't fix this, #4101 should!

**Comment by mjibson** [comment]
Nice! I have a question though: what is the thing that was changing the order?

**Comment by benesch** [comment]
> what is the thing that was changing the order?

That's a good question. Maybe the optimizer mucks around with the order of constant relations.

**Comment by JLDLaughlin** [comment]
I also don't know the answer to this! (But could figure it out!)
