### ISSUE TITLE
coord: mz_catalog.{schema,database}_id should be ints?

### ISSUE THREAD

**Issue by benesch** [MaterializeInc/materialize#4086]
@JLDLaughlin just eyeballing, but I think we want `mz_catalog.schema_id` and `mz_catalog.database_id` to be of type Int64, not String? https://github.com/MaterializeInc/materialize/blob/5d360e87e97d624ac3c1468b19a9a3d3067d412a/src/coord/src/catalog/builtin.rs#L249-L250

**Comment by JLDLaughlin** [comment]
I'm on board with making `mz_catalog.schema_id` an Int64! But for the `mz_catalog.database_id`, just having the int value loses the system/user information.

**Comment by JLDLaughlin** [comment]
This clicked today!

**Comment by benesch** [comment]
Oh good! Sorry, missed your earlier comment because of vacation!
