### ISSUE TITLE
Nicer way to introspect what has already been persisted

### ISSUE THREAD

**Issue by ruchirK** [MaterializeInc/materialize#4123]
Ideally we would have some SQL-layer idiom for "show me what data has been persisted" that we could use when testing source persistence.

There's a range of ideas from:

- system table that stores previously written out filenames
- new source type that only ingests persisted data and nothing else
- table-valued function that returns the set of persisted records
- ??

cc: @justinj

**Comment by justinj** [comment]
Having sat on it a bit more I think I still quite like "table function that returns persisted data," it strikes me as both the most general and possibly the least invasive to implement?

**Comment by ruchirK** [comment]
I don't have a very strong preference because none of the options jump out as much easier than any of the other ones. That being said, I'm definitely the least familiar with table functions :)

**Comment by ruchirK** [comment]
@justinj I think this can be closed now?

**Comment by justinj** [comment]
Agreed
