### ISSUE TITLE
JoinImplementation does not know how to plan joins with expression keys

### ISSUE THREAD

**Issue by wangandi** [MaterializeInc/materialize#4170]
Create:
* source foo(a int, b int, c int)
* source bar(a int, b int, c int)

Optionally create:
* index foo(mod(a, 5))
* index bar(mod(a, 5))

Either way, the following is the result of `explain plan for select foo.a, b, c, d, e from foo, bar where mod(foo.a, 5) = mod(bar.a, 5)`:
```
%0 =
| Get materialize.public.foo (u1)
| ArrangeBy ()

%1 =
| Get materialize.public.bar (u3)

%2 =
| Join %0 %1 (= (#0 % 5) (#3 % 5))
| | implementation = Differential %1 %0.()
| | demand = (#0..#2, #4, #5)
| Project (#0..#2, #4, #5)
```

The reason the plan looks like this is that instead of keeping track of all join keys that need to be bound, the field `bound` belonging to the struct `Orderer` in `JoinImplementation` only keeps track of columnar join keys. Since there are no columnar join keys above, JoinImplementation plans the join as a cross join and ignores the presence of all indexes on expressions.

**Comment by wangandi** [comment]
A comment on how this bug manifests in practicality:

If only one of the join keys in a join is an expression, the resulting join is less bad because the input corresponding to the expression join key always become the first input in a differential join:
```
explain plan for select foo.a, b, c, d, e from foo, bar where foo.a = mod(bar.a, 5)
----
%0 =
| Get materialize.public.foo (u1)
| ArrangeBy (#0)

%1 =
| Get materialize.public.bar (u3)

%2 =
| Join %0 %1 (= #0 (#3 % 5))
| | implementation = Differential %1 %0.(#0)
| | demand = (#0..#2, #4, #5)
| Project (#0..#2, #4, #5)
```

If there are three or more inputs, with at least two inputs with expression join keys, the resulting join can become quite bad, such as the below plan where `foo` and `baz` are cross-joined together first:
```
explain plan for select foo.a, b, c, d, e from foo, bar, baz where mod(baz.a, 5) = mod(bar.a, 5) and mod(foo.a, 5) = mod(bar.e, 5)
----
%0 =
| Get materialize.public.foo (u1)
| Filter !(isnull((#0 % 5)))
| ArrangeBy ()

%1 =
| Get materialize.public.bar (u3)
| Filter !(isnull(#2))
| ArrangeBy ()

%2 =
| Get materialize.public.baz (u5)

%3 =
| Join %0 %1 %2 (= (#0 % 5) (#5 % 5)) (= (#3 % 5) (#6 % 5))
| | implementation = Differential %2 %0.() %1.()
| | demand = (#0..#2, #4, #5)
| Project (#0..#2, #4, #5)

EOF
```

**Comment by frankmcsherry** [comment]
Super interesting; thanks for spotting!
