### ISSUE TITLE
Add more information to "kafka error"

### ISSUE THREAD

**Issue by wangandi** [MaterializeInc/materialize#4174]
A prospect has gotten a message that looks like this:
```
ERROR dataflow::source::kafka: kafka error: Message consumption error: InvalidMessage (Broker: Invalid message)
```
[This error comes from Kafka and is unlikely to be something we need to deal with on our end.](https://cwiki.apache.org/confluence/display/KAFKA/A+Guide+To+The+Kafka+Protocol#AGuideToTheKafkaProtocol-ErrorCodes)

However, the prospect would like `kafka error:` to be replaced with something like `kafka error for topic <topic> at partition <partition #>, offset <offset #>` to make it easier to determine where the kafka error is coming from.

**Comment by wangandi** [comment]
If offset number were not possible, last processed offset would be great too.

**Comment by ruchirK** [comment]
Let me see if I can quickly knock this one out
