### ISSUE TITLE
Support different ports for SQL connections and HTTP/Prometheus metrics

### ISSUE THREAD

**Issue by andrioni** [MaterializeInc/materialize#4186]
It would be good to be able to control access to each functionality on a network level: I want to let Prometheus scrape Materialize, but without giving it access to open SQL connections.

**Comment by benesch** [comment]
Yep, this is definitely on our radar! Going to close this in favor of the existing issue though: #1987. Definitely follow up there if the proposed design (a `--metrics-addr` CLI flag that controls the port on which the `/metrics` endpoint is available) is unsuitable for your needs.

**Comment by andrioni** [comment]
Oops, sorry, I missed that one, thanks!
