### ISSUE TITLE
SHOW DATABASES bug

### ISSUE THREAD

**Issue by JLDLaughlin** [MaterializeInc/materialize#4187]
### What version of Materialize are you using?

```
materialized v0.4.3-dev
```

### How did you install Materialize?

* [ ] Docker image
* [ ] Linux release tarball
* [ ] APT package
* [ ] macOS release tarball
* [ ] Homebrew tap
* [X] Built from source

### What was the issue?

`SHOW DATABASES` returns an error if run from a deleted database.

### Is the issue reproducible? If so, please provide reproduction instructions.

Yes!

```
materialize=> create database j;
CREATE DATABASE
materialize=> set database = j;
SET
materialize=> drop database j;
DROP DATABASE
materialize=> show databases;
ERROR:  unknown database 'j'
```

**Comment by JLDLaughlin** [comment]
From prior conversations with @benesch, this isn't necessarily a bug -- but it's not super user-friendly? Meaning, it's not obvious that a user would have to switch databases to get `SHOW DATABASES` to work correctly.

**Comment by benesch** [comment]
Yeah definitely would be good to make this work (I think it used to)
because otherwise you have no way to figure out what databases are valid to
connect to. I think it should be easy to fix though! I have a hypothesis on
what’s going wrong; can look in a sec.

**Comment by JLDLaughlin** [comment]
I think I have a fix! Will send shortly.

**Comment by benesch** [comment]
Yeah, so if you fully qualify this as `mz_catalog.mz_databases`, I think it
should work:
https://github.com/MaterializeInc/materialize/blob/main/src/sql/src/plan/statement.rs#L542

Probably should do this for everything now that I think about it. As
written I think if a user creates a table called mz_databases in the
connection’s current database, which is a totally valid thing to do, then
`SHOW DATABASES` will query the wrong table!
