### ISSUE TITLE
Delay of ~2 minutes in scheduling some kafka source operators

### ISSUE THREAD

**Issue by ruchirK** [MaterializeInc/materialize#4197]
When you create a kafka source reading a multipartition (tested with 4) topic with a lot of records, one of the kafka source operators is not scheduled as often as the rest, for the first roughly two - four minutes of the source's existence. This happens deterministically (when run on a 4 partition topic with 4 workers, worker 2 is always delayed in being scheduled). This happens regardless of the number of workers (I tested it with 2, 3, 4, 6, 11 workers). When run with 11 workers, worker 9 is the one delayed. In this case, worker 9 is not reading any data, but it is still not being scheduled as frequently as the other non-reading operators.

Notably, it does not seem to manifest when Materialize is run with exactly one worker, nor does it seem to manifest when the source has exactly one partition (I tested this with kafka sources with 1 and 4 partitions).

It reproduces if you create the source right after restart, and also if you a while after Materialize has started before you create your source.

To reproduce this yourself -- head over to the upsert demo 

```
cd test/performance/perf-upsert
``` 

I changed the demo to not do upsert using this diff

```
diff --git a/test/performance/perf-upsert/src/main.rs b/test/performance/perf-upsert/src/main.rs
index 1ccd5e6a..3e16a4ae 100644
--- a/test/performance/perf-upsert/src/main.rs
+++ b/test/performance/perf-upsert/src/main.rs
@@ -142,12 +142,9 @@ async fn create_upsert_text_source(
     );

     let query = if enable_persistence {
-        format!(
-            "{} WITH (persistence = true) FORMAT TEXT ENVELOPE UPSERT",
-            query_prefix
-        )
+        format!("{} WITH (persistence = true) FORMAT TEXT", query_prefix)
     } else {
-        format!("{} FORMAT TEXT ENVELOPE UPSERT", query_prefix)
+        format!("{} FORMAT TEXT", query_prefix)
     };
     log::debug!("creating source=> {}", query);

altaria-2:perf-upsert Test$
```

but I don't think its relevant to the bug (famous last words)

Now, create a 4 partition topic with the following invocation

```
cargo run --release -- --message-count 25000000 --messages-per-second 50000 --create-topic --kafka-topic perf-upsert-4-part --partitions 4 --replication-factor 1
```

this creates a 4 partition topic named `perf-upsert-4-part` with 25MM messages and will take approximately 500 seconds to fill it with 25 MM messages.

verify that each of the partitions have roughly equivalent amounts of data in them by running
```
kafkacat -b localhost:9092 -C -o -1 -f "[partition: %p] offset: %o\n" -t perf-upsert-4-part
```

each topic should end at an offset ~= 6.25 MM

now, start up Materialize in release mode (I used main at `e9683151e`), and make it ingest the source by either typing in:

```
CREATE SOURCE "materialize"."public"."perf_upsert_source" FROM KAFKA BROKER 'localhost:9092' TOPIC 'perf-upsert-4-part' FORMAT TEXT
```

to psql, or running the demo again with message-count=0

At this point, if you look at the `mz_operator_scheduled_total` metric, you should see one of the worker's scheduled count is suspiciously low.

<img width="1672" alt="Screen Shot 2020-09-12 at 3 20 17 PM" src="https://user-images.githubusercontent.com/4015012/93003589-fc083e00-f50d-11ea-95f5-fb65b5be5711.png">
<img width="1675" alt="Screen Shot 2020-09-12 at 3 09 30 PM" src="https://user-images.githubusercontent.com/4015012/93003590-fc083e00-f50d-11ea-9e5f-b37e0b080c42.png">

With grafana it should look something like the screenshots attached.

As it stands currently, this quirk has the potential to blow up memory usage for BYO sources, because if we are ingesting from all partitions but 1, we may not be able to downgrade capabilities for a while. This is also problematic for persistent sources.

cc: @justinj

**Comment by ruchirK** [comment]
Note that in all the graphs attached theres always one operator whose scheduled counts stay flat for the first 2 - 4 minutes and then spike up (admittedly hard to see in a few cases)

**Comment by ruchirK** [comment]
<img width="1914" alt="Screen Shot 2020-09-21 at 9 42 41 AM" src="https://user-images.githubusercontent.com/4015012/93774216-018d1480-fbef-11ea-8c5d-6492a7298fcb.png">

**Comment by ruchirK** [comment]
I figured out what was happening here. We send records to different workers based on the hash of the record itself which is a recent change afaict. In the past, I thought we used the record's position (e.g. kafka offset). In this particular case, all of the records are the same which leads to all of them getting sent to the same worker.

It wasn't an entire waste of time -- managed to use the macos cpu profiler to finally figure this out!

I'll throw up a pr that changes the parallelization to prefer using position if its available, and otherwise fall back to hashing the value. IMO thats more reliable?

cc: @frankmcsherry since you were interested in this and will no doubt be glad to know there's no timely bug

**Comment by frankmcsherry** [comment]
I was interested in this!

There is a caveat we should check out with @umanwizard : the distribution may want / need to be by Kafka key at some point, because Debezium deduplication only ends up being correct if data are distributed that way. I'm not certain if this connects with this defective performance, and whether changing the behavior might get in the way of that bit of correctness, but I am optimistic that the two of you together can shake it out (I'll watch / help if I can!).
