### ISSUE TITLE
Allow for CREATE SOURCE ... LIMIT <x>

### ISSUE THREAD

**Issue by ruchirK** [MaterializeInc/materialize#4216]
A lot of our users have a exploratory period where they want to inspect some data, try some queries and figure out what computations they want to perform, before they turn those computations into materialized views and install them on their Materialize instance.

Currently, this is a slow and memory intensive process partially because each ad-hoc query potentially rereads the whole source and computes stuff for it from scratch. Instead, if we allowed for some way for users to grab only a subset of their input data, they could then explore that subset fairly easily, determine what computations they want to perform, and then do it on the full data set.

Note that defining a view like

```
CREATE MATERIALIZED VIEW <view_name> AS
SELECT * FROM <src_name>
LIMIT <x>;
```

is not sufficient for this use case because at least for debezium sources, the view above will use memory proportional to the number of undeleted records in the source, which can be much greater than `x`

cc: @cuongdo

**Comment by benesch** [comment]
This smells like a bit of a bandaid to me. I like the look of the materialized view in the description quite a bit more. We could invest in making that use bounded memory instead.

**Comment by justinj** [comment]
How would that work? Don't you need to keep around all the other stuff in case the bounded elements get deleted?

**Comment by benesch** [comment]
Oh good point, but that means the semantics of `CREATE SOURCE ... LIMIT <x>` have the same weird issue, where you need to figure out how to "replenish" the source if one of your initial records that initially satisfied the limit gets deleted, don't they?

**Comment by ruchirK** [comment]
imo the limit in create source ... with limit is a limit on the number of messages ingested from the source and not a limit on how many net inserts that generates? (i totally get that this might be ultra confusing to users and seem band-aid-y to us)

I'm not attached to any particular route as long as we can have some way to do a bounded memory thing for external sources

**Comment by ruchirK** [comment]
would it feel less bad if instead of `LIMIT` we used a `WITH` option to express the bounded read?

**Comment by justinj** [comment]
I think that would be preferable for me—to me `LIMIT` is a relational concept that operates on "rows" rather than "messages."

**Comment by benesch** [comment]
That sounds a bit better to me, but I'm still not sure that we've fully explored the design space here. Roughly speaking: maybe the more general feature is to be able to pause/resume ingesting messages from a source? Like, will it be frustrating if you create a source limited to 1000 messages from Kafka, build a whole stack of views, and then want to unleash the firehose? With the design as proposed you might need to throw away the whole source/view stack.

But, hmm, maybe we could allow you to `ALTER` the `max_messages` parameter. That sounds pretty nice.

**Comment by frankmcsherry** [comment]
What we used to do with DryadLINQ was a filter clause with something like `record.key % 100 == 0` in order to slim down the data. I could imagine something similar might be an easy idiom to explain to people, if we are worried about the semantics of a source operator that exists only to help people try things out.

**Comment by cuongdo** [comment]
Frank's suggestion has promise. Users could do `record.key % 100 = 0` for primary keys. Some care would be needed to make sure foreign keys used so that joins return rows. For example, `other_table.foreign_key_for_record % 100 = 0`. @ruchirK how does that sound to you?

**Comment by ruchirK** [comment]
Yeah I think Frank's suggestion might be a better way to go for now? I investigated this a little bit and the original proposal is not as straightforward for multipartition topics because we have separate readers for each partition

Also I'm not sure why tables that join with "thinned out" collections would need to be aware of the thinning? e.g. if we only took in employee ids that were multiples of 100 and materialized that as a view -- users could still join the employee view with other stuff they would just get 1/100th of the results back? Am I missing something?

**Comment by ruchirK** [comment]
I'm not sure we still need this given Frank's suggestion above - should I close this issue?

**Comment by benesch** [comment]
Yes do it!

**Comment by ruchirK** [comment]
I think the product goal of this are better served with a one shot source / `IMPORT`
