### ISSUE TITLE
Visualize dataflow graph

### ISSUE THREAD

**Issue by apparebit** [MaterializeInc/materialize#422]
Now that `EXPLAIN` surfaces the dataflow graph in a nice textual representation (see #379), it's worth considering how we can further help people understand what's going on inside Materialize. The textual representation returned by `EXPLAIN` is nicely regular and thus eminently parseable. That enables further tools that consume the output, notably, a graphical visualization of the dataflow graph.

As an added bonus, implementing this visualization is nicely self-contained project. It does *not* require directly interfacing with the Rust codebase, let alone modifying it.

Instead, I recommend building a Node.js tool that leverages an existing library implementing the PostgreSQL wire protocol—the [pgwire](https://www.npmjs.com/package/pgwire) package hosted in the [kagis/pgwire](https://github.com/kagis/pgwire) repository appears to be the best option—to access the output of `EXPLAIN`. The tool then parses the text and creates the corresponding SVG graph with embedded styles to make it look appealing. This being JavaScript, there are many good options for processing SVG available.

**Comment by frankmcsherry** [comment]
It is possible that we can close this, what with the dataflow rendering work of @mjibson.

**Comment by benesch** [comment]
I agree!
