### ISSUE TITLE
Graphical UX for dataflows

### ISSUE THREAD

**Issue by frankmcsherry** [MaterializeInc/materialize#4226]
Materialize produces raw tabular data about the dataflow graphs that it manages, their structure, and resources associated with each of the operators. These data are valuable, but hard to consume in their raw form. 

Materialize would likely benefit from a more graphical navigable interface to this information. For example, we could present the list of running dataflows with their accumulated resource uses, with the ability to expand out dataflow to their constituent operators and nested regions. We could also present dataflow graphs for each of the dataflows, perhaps annotated with resource usage, or progress frontiers, or other useful information.

There is some design work to do to determine what facets are useful, but it feels like several of these options would be excellent starting points even if we quickly conclude they should be improved.

---

Information about dataflow structure can be found in the `mz_catalog` sources:
```
mz_dataflow_channels
mz_dataflow_operator_addresses
mz_dataflow_operators
```
The `_operators` and `_channels` collections name operators and the edges between them. The `_addresses` relation describes the hierarchical relationship these share. There are some idiosyncrasies, mainly that dataflow edges that cross levels of the hierarchy go through a phantom "operator zero" in each scope, whose inputs and outputs correspond to the outputs and inputs (respectively) of the containing scope.

---

For prior work on graph drawing timely dataflow graphs, consider https://github.com/TimelyDataflow/diagnostics

**Comment by cuongdo** [comment]
@benesch wants to make this a first-class feature in Materialize, as opposed to an external script. He believes it'll take on the order of days to create the basic infrastructure to make this happen. I know @frankmcsherry wanted fast progress on this, so you two should discuss timing of this issue.

**Comment by justinj** [comment]
I also think this should be first-class! Something we did at Cockroach that worked really well IMO, was an `EXPLAIN` variant that packed the data for a plan into a base64-encoded string and handed you a URL to that. I think something like that would be really great here, since it would also allow for more interactivity than just an image.
