### ISSUE TITLE
CREATE INDEX ... WITH

### ISSUE THREAD

**Issue by benesch** [MaterializeInc/materialize#4231]
Via #3636 we got the awesome ability to set the compaction window per index. Unfortunately this is only available via `ALTER INDEX ... SET` after creating the index—it should be possible to say `CREATE INDEX ... WITH (logical_compaction_window = ...)` to do it all one shot.

/cc @ruchirK

**Comment by frankmcsherry** [comment]
As observed in #5335 being able to set the compaction at creation is important to avoid a race where the data are loaded and compacted before one can express that they should not be. This fouls up some tests, but also for folks who want historical access they would have to roll the dice on a race between the ALTER statement and the coordinator first determining it can compact a thing.
