### ISSUE TITLE
Apply backpressure to source operators

### ISSUE THREAD

**Issue by cuongdo** [MaterializeInc/materialize#4237]
When dataflow processing substantially lags incoming data from sources, this can cause memory use to quickly grow as unprocessed data accumulates. This can trigger unnecessary OOMs and swapping. One approach to reducing memory use is applying backpressure to source operators to slow down reading of data from sources.

We should consider this for 0.6.

cc @umanwizard @frankmcsherry @awang

**Comment by benesch** [comment]
@frankmcsherry do you have a rough sketch of how something like this would be designed? There isn't anything in Timely's standard APIs that obviously provides this functionality, but you always have tricks!

**Comment by frankmcsherry** [comment]
The timely back-pressure philosophy is end-to-end, so it would be the sources that should slow down ingestion. If the set of dataflow were static, we could just look at the available frontiers as currently maintained, and slow down ingestion for any source that has fallen more than `slack` behind `now()`.

I think we should have a more serious discussion at some point about what guarantees we want RT sources to have, especially if something like backpressure is going to play with timestamping decisions. Ideally, in my world, we would assign timestamps to inbound data independent from the current behavior of the system. At that point, one can make decisions about how much data to release in to the system without that behavior affecting the results themselves. I'm very uncomfortable with the idea that backpressure might cause MZ to report answers as "up to date" where in fact it just hasn't gotten around to reading the input yet.

Back-pressure introduces coupling between slow and fast parts of the dataflow, which will be a new surprise that we'll have to deal with. If something is having a hard time keeping up (e.g., a Kafka sink is slow to write) that might cause all folks with a shared input to slow down, which could then cause all of their inputs to back up as well. It's an exciting and interesting space, and we should be careful before just shipping it.

**Comment by frankmcsherry** [comment]
Notes from #eng-integrations convo: back-pressure may not be ideal when the system is up and running (holding back ingestion makes us fall behind the tip of the streaming source, and is another issue) but on start-up, we do want to make sure that we don't have to fall down if the workload is skewed (if some readers naturally read faster than the dataflow can retire work).

**Comment by elindsey** [comment]
I'm going to close this one out - the assumptions here are all around storage and compute competing for resources on the same nodes, which aren't applicable in the platform design.
