### ISSUE TITLE
Bulk uploading historical data for new database source

### ISSUE THREAD

**Issue by jdotjdot** [MaterializeInc/materialize#4242]
I'm really excited by Materialize and just getting started with it.  In particular, I'm very excited for use cases that would let me have always-up-to-date views on data coming from OLTP sources, like Postgres.  I know you can use Debezium to stream Postgres events to Materialize.  However, I don't see anywhere in "Getting Started" or the docs in general how to _start_ with a Postgres source.

Are you supposed to use Debezium's "snapshot" feature, or something else? If that's what you're supposed to use, that's fine, but I'd recommend adding some notes in the documentation for the brand-new Debezium user on how to get started with Materialize, given it's a very common use case, and `pg_dump` isn't currently supported.

**Comment by rjnn** [comment]
thanks @jdotjdot , this is an excellent documentation request. You are right that a comprehensive walkthrough/howto is missing. Assigned to @awang to re-assign and schedule in the 0.6(?) timeframe.

**Comment by benesch** [comment]
Funnily we do have these docs, but they're in the internal developer documentation rather than the user facing docs. https://github.com/MaterializeInc/materialize/blob/main/doc/developer/setup-postgres-debezium.md

**Comment by awang** [comment]
Thanks for the request @jdotjdot ! As we get you better docs, there's also some stuff we wrote up that should get you started at https://github.com/MaterializeInc/tb

**Comment by jdotjdot** [comment]
Thanks! This is helpful.  Some of this seems a bit at odds though with this part of the documentation:
![image](https://user-images.githubusercontent.com/1328961/93543642-12f1ca80-f92a-11ea-8a46-875b1708bca6.png)

[link](https://materialize.io/docs/overview/architecture/#sources-ingesting-data)

It seems you _can_ seed the data, it just has to be seeded "through" the streaming source.

Additionally, if everything is in-memory--for a case like this, what happens if Materialize shuts down or restarts? Will the data re-seed automatically from Debezium?  If it's been so long that data was purged from Kafka, do you have to run all of these commands again?

**Comment by jdotjdot** [comment]
FWIW, I actually read through the full mdbooks of both timely dataflow and differential dataflow.  Very excited by this approach!

**Comment by morsapaes** [comment]
**Update:** Materialize has come a long way since this issue was created! We support direct PostgreSQL CDC via the [PostgreSQL source](https://materialize.com/docs/sql/create-source/postgres/), will soon support direct MySQL CDC and support other RDBMS via Kafka+Debezium. There's guides for all of these integrations in our [documentation](https://materialize.com/docs/), too, which include details about how we do snapshotting!
