### ISSUE TITLE
Crash in coordinator on start-up.

### ISSUE THREAD

**Issue by frankmcsherry** [MaterializeInc/materialize#4248]
### What version of Materialize are you using?

```
$ materialized -v
materialized v0.4.4-dev (be335c7cdcc62014f138d801ff857d5372927d0f)
```

### How did you install Materialize?

* [ ] Docker image
* [ ] Linux release tarball
* [ ] APT package
* [ ] macOS release tarball
* [ ] Homebrew tap
* [x] Built from source

### What was the issue?

Materialize crashes on start-up.

### Is the issue reproducible? If so, please provide reproduction instructions.

```
shell1% rm -r mzdata
shell1% cargo run -- --dev -w1
shell2% cargo run --bin testdrive -- test/testdrive/materializations.td
```
wait for tests to complete (successfully, at least for me).
```
shell1% ^C
shell1% cargo run -- --dev -w1
```
This reproducibly (100% of the time) in a panic:
```
Sep 18 12:53:37.628 ERROR panic: main: name missing at coordinator
```

**Comment by JLDLaughlin** [comment]
I can reproduce this! Taking a look now

**Comment by JLDLaughlin** [comment]
The issue is this unmaterialized sink: https://github.com/MaterializeInc/materialize/blob/main/test/testdrive/materializations.td#L137. Still looking.

**Comment by JLDLaughlin** [comment]
The problem is we're calling `default_index_for` on a sink with no indexes. I have a proposed fix that I'll get out in a minute.

**Comment by JLDLaughlin** [comment]
Spoke too soon! The problem is actually that the unmaterialized sink _does_ have an index that isn't tracked in the Coordinator's indexes.

**Comment by frankmcsherry** [comment]
What does a sink having an index mean?
