### ISSUE TITLE
Miri flag passing changed

### ISSUE THREAD

**Issue by RalfJung** [MaterializeInc/materialize#4256]
`cargo miri test` changed to be more compatible with `cargo test`, but this means we had to find a different way to pass flags to the interpreter, so there now is a `MIRIFLAGS` environment variable for that. The old way still works for now, but is deprecated.

This affects the following line:
https://github.com/MaterializeInc/materialize/blob/f3338f577b104d5b6804d8a4ae272c5d184217a6/ci/test/cargo-test-miri.sh#L27
This should now be `cargo miri test miri`, running the same tests as `cargo test miri`.

**Comment by benesch** [comment]
Wow, thanks very much for the heads up, @RalfJung! We'll make that update next time we update our pinned version of our nightly Rust toolchain.

Out of curiosity, how did you find our usage of Miri? It's always fun to know that folks like you are following along!

**Comment by RalfJung** [comment]
I used GitHub global search for "cargo miri" and reported issues for everything that would be affected by the change. About half the results were vendored copies of old versions of smallvec.^^
