### ISSUE TITLE
Cloud persistence of sources

### ISSUE THREAD

**Issue by umanwizard** [MaterializeInc/materialize#4270]
Marking this as "musing" since it probably needs significant design/product work to figure out what we actually want and how it should work.

It would be excellent to be able to persist ingested data to S3 or similar - then users would not need to rely on Kafka for long-term storage of Materialize data, nor would they need to keep all the data on a local hard disk. I know @rjnn in particular has a lot of thoughts about this

**Comment by elindsey** [comment]
The persistence group is actively working on this, so I'm closing out this sources/sinks tracking task.
