### ISSUE TITLE
Support pg_catalog.pg_class

### ISSUE THREAD

**Issue by JLDLaughlin** [MaterializeInc/materialize#4280]
Required for `\d`: https://github.com/MaterializeInc/materialize/issues/4279

**Comment by JLDLaughlin** [comment]
Required for `\dv`: https://github.com/MaterializeInc/materialize/issues/4283

**Comment by JLDLaughlin** [comment]
Required for `\dt`: https://github.com/MaterializeInc/materialize/issues/4284

**Comment by JLDLaughlin** [comment]
Required for `\di`: https://github.com/MaterializeInc/materialize/issues/4285

**Comment by JLDLaughlin** [comment]
Required for `\di`: https://github.com/MaterializeInc/materialize/issues/4285

**Comment by benesch** [comment]
Enough of this was implemented in #4332 and #4424 to call this complete, I think!
