### ISSUE TITLE
Support pg_catalog.pg_namespace

### ISSUE THREAD

**Issue by JLDLaughlin** [MaterializeInc/materialize#4281]
Required for `\d`: https://github.com/MaterializeInc/materialize/issues/4279

**Comment by JLDLaughlin** [comment]
Required for `\dv`: https://github.com/MaterializeInc/materialize/issues/4283

**Comment by JLDLaughlin** [comment]
Required for `\dt`: https://github.com/MaterializeInc/materialize/issues/4284

**Comment by JLDLaughlin** [comment]
Required for `\di`: https://github.com/MaterializeInc/materialize/issues/4285

**Comment by benesch** [comment]
Fixed via #4296 and #4322!
