### ISSUE TITLE
OIDs should wrap around u32::max

### ISSUE THREAD

**Issue by JLDLaughlin** [MaterializeInc/materialize#4319]
[Postgres `OID`s](https://www.postgresql.org/docs/13/datatype-oid.html) are object identifiers implemented as unsigned four-byte integers. `OID`s are used as primary keys for system tables, and as input for or output from specialized routines. 

In an effort to support `pg_catalog`, Materialize (mostly) [supports OIDs](https://github.com/MaterializeInc/materialize/pull/4316). However, our implementation diverges from Postgres'. Upon reaching the `u32` limit (4 billion ids), Postgres wraps around and begins assigning previously assigned ids again - meaning that `OID`s are not unique! In Materialize, the user will encounter an `OidExhaustion` error instead. 

Currently, users can work around the `OidExhaustion` issue by restarting their Materialize instance. `OID`s are not persisted and are dynamically assigned - restarting an instance should ensure that fewer than 4 billion items will be created. In the future, we should consider allowing this value to wrap around the `u32::max` boundary to match Postgres.

**Comment by benesch** [comment]
Thanks for writing this up! Just to make the description of Postgres's behavior a bit more precise: OIDs within a particular _index_ in PostgreSQL are always unique. So all of the OIDs in e.g. `pg_namespace` are guaranteed to be unique, even in the face of wraparound. But OID 7 might refer to both a namespace and a type, for example, if wraparound occurs.

If we get to the point where we need to handle OID wraparound, then we'll need to implement the same semi-uniqueness properties!

**Comment by jkosh44** [comment]
As of https://github.com/MaterializeInc/materialize/pull/25700 OIDs are durable and wrap around. Though they are globally unique unlike PostreSQL.
