### ISSUE TITLE
Pipe error streams through the entire system.

### ISSUE THREAD

**Issue by umanwizard** [MaterializeInc/materialize#4327]
We do this correctly for errors that happen on ingest: see https://github.com/MaterializeInc/materialize/blob/8cf6d28d081d5515a9b1f0230cd3fe3a7b07b95d/src/dataflow/src/render/mod.rs#L416-L421 where the error stream from the `create_source` function is properly concatenated onto the error stream.

For errors that happen on _decode_, however, (e.g. Avro schema mismatch), we just print something to the logs. We should pipe the error stream stuff through to there also.

**Comment by benesch** [comment]
This got fixed.

**Comment by umanwizard** [comment]
Hard to believe we ever just printed these to stderr. Different world…
