### ISSUE TITLE
Fuse Map/Filter/Project operations to Get

### ISSUE THREAD

**Issue by justinj** [MaterializeInc/materialize#4346]
There are several things that could be considered part of this project:
1. Adding a logical MapFilterProject operator that supplants the existing Map/Filter/Project operators,
2. fusing Map/Filter/Project operators to Gets at render time,
3. getting Map/Filter/Project operators logically close to Gets during planning.
4. fusing Map/Filter/Projects to other operators (say, Join),
5. pushing Map/Filter/Projects more deeply into sources.

I think there is not consensus on whether or not we should do (1). (3) is fairly important for (2) to be beneficial, but I think (2) can be done+tested in isolation from (3) if we want to keep work smaller. (4) and (5) out of scope for now.

So I would describe the initial work item as:

1. During render time, detect chains of `Map/Filter/Project` above a Get, and collapse them into a rendered single operation on top of that Get.

and then as a followup task:

2. Add a stage during physical planning, where, by looking at the demand analysis (and perhaps other things), we push down maps, filters, and projections to get them close enough to the Gets that the above rule can fire.

cc @frankmcsherry for your thoughts on whether this characterizes what should be done, cc @cuongdo

**Comment by frankmcsherry** [comment]
I think this looks good. Somewhere in the list we probably want "optimize `MapFilterProject`", but as we discussed it should be as optional as all the other optional stuff.

**Comment by frankmcsherry** [comment]
If it helps for re-using existing idioms: the way we've been effecting the analogue of projection pushdown is with demand analysis, that at any point in the dataflow can replace un-demanded columns with a projection that deletes them, and then a map that adds a dummy value in their place (it does not do this, but it should be safe to). At this point, the map with a literal can be lifted upwards until it is eventually absorbed in to some operator (wherever our disinterest in it originates from).

**Comment by frankmcsherry** [comment]
I'm using this issue for some note-taking on related TODO items. 

Bonus: #4463 fuses linear operators into a `Get` in a way that minimizes the cloning of `Row` instances, but it still calls `row.unpack()` which allocates a `Vec<Datum<'row>>` for each row. If we opened up the `flat_map_ref` function a bit more, it would be able to re-use one vector across multiple rows, further reducing the allocations.

**Comment by justinj** [comment]
Thoughts after a discussion with @frankmcsherry, there are two concurrent mostly-orthogonal paths to continue down here:

1. leverage demand analysis to get Projects down closer to Gets. Add a step that uses demand analysis to replace a Get with a Get -> Project -> Map -> Permute combination which will then get fused by the PR that just merged.
2. work more on pushing MFP into sources themselves. Right now some sources are able to leverage demand information to produce fewer columns, but we could also allow them to make use of MFP to do more work closer to the source.

Along with that there's another work item to change the implementation that we did in the previous PR to affix an MFP to `Get` and allow `Get` to absorb any such operators on top of it, which might make things easier in the sense that we could be less afraid of other transformations hoisting them up after. This could also include merging them into things like `FlatMap`.

I think at the moment I'm most interested in looking into (1), but let me know if this is an accurate assessment of what we discussed @frankmcsherry?

**Comment by frankmcsherry** [comment]
I think this accurately reflects what we discussed!

Two additional thoughts:

1. One "meta"-task is to learn a bit more about how we would like to go forward with physical planning as distinct from logical planning. Should we move away from "demand" analysis, which is a bit bespoke, towards projection and predicate pushdown? Will we want the same information in more places, like `Join` and `FlatMap`?

2. Fusing filtering in to `Get` will likely abut / interact with @wangandi's work on using indexes for certain types of filtering. At least, one instance of that work is "we have a key, and want to use it to look directly at an arrangement by key". We probably want these two things to play nice, but also eventually to work together (e.g. look something up by key, and immediately apply additional maps, predicates, and projections. 

    I think we should probably double check the specific interaction to make sure that we don't accidentally do conflicting work. I think option (1.) above is the most likely to do that, but "moving information around the plan" is not fundamentally in conflict. Though perhaps we want to partition the work so that one person owns "`Get` rendering" which could be distinct from who owns "moving the AST around". Thoughts?

**Comment by frankmcsherry** [comment]
Several operators have MFPs fused into their implementations (`Get`, `FlatMap`, `Join`) and other operators (`Reduce`) have open issues explaining the challenges. We have an open issue for pushing projections toward sources (#6449) and an open issue for converting source `LinearOperator`s into `MapFilterProject`s (#6657). There is also the issue of moving MFPs closer to sources, and I just filed #7486 about that issue.

We can leave this issue open as a tracking issue for these multiple tasks, but we could also close it down and create a new one if we want to track the specific progress towards moving linear operators to sources.

**Comment by wangandi** [comment]
Since this seems to still be the overarching MFP tracking ticket, I'm linking this comment as something to be aware of but we don't have enough details to act on yet: https://github.com/MaterializeInc/materialize/issues/7437#issuecomment-884276772
