### ISSUE TITLE
Support ANY array comparison

### ISSUE THREAD

**Issue by JLDLaughlin** [MaterializeInc/materialize#4353]
Needed to support `pg_catalog.pg_table_is_visible`: https://github.com/cockroachdb/cockroach/blob/f2056ba8cde1d969b3170b513c974a74b5a2ddbd/pkg/sql/sem/builtins/pg_builtins.go#L1067-L1068

**Comment by JLDLaughlin** [comment]
We do support this! In Postgres:
```
select 1 = any(array[1]);
```

In Materialize:
```
select 1 = any(values (1));
```

**Comment by benesch** [comment]
Are you sure? I actually assumed we would need to add support for this! No easy way to get the output of `current_schemas` into a `VALUES` clause.

**Comment by JLDLaughlin** [comment]
You're right! There is no easy way to get that into a `VALUES` clause.

**Comment by benesch** [comment]
Fixed in #4410.
