### ISSUE TITLE
Chbench run container exited with 0 exit code and no logs

### ISSUE THREAD

**Issue by cirego** [MaterializeInc/materialize#4465]
Even after running `nuke` and starting from scratch, I'm unable to get the `chbench_chbench` container to startup correctly. It's exiting with no logs on stdout, no logs in `/var/log` and no exit code.

**Comment by cirego** [comment]
Cleaning up old issues. This is because the container is being run as a script and not a daemon.

**Comment by cirego** [comment]
On second thought, I should open a PR to have the container emit a single message when finished.

**Comment by benesch** [comment]
Stale.
