### ISSUE TITLE
Memory diagnostic queries 

### ISSUE THREAD

**Issue by awang** [MaterializeInc/materialize#4490]
The goal of this feature is to allow users to understand what's costing memory in the system. It was suggested we should build diagnostic queries to identify whether memory consumption is growing because a view is falling behind, or because of other causes.

Related issues: 
1. [improved memory accounting](https://github.com/MaterializeInc/materialize/issues/815)
1. [Graphical UX for dataflows](https://github.com/MaterializeInc/materialize/issues/4226)

Followon Tasks -- Desired functionality that I'm hoping to unlock with this issue:
1. [Active dataflow cancellation](https://github.com/materializeinc/materialize/issues/2392) 
1. [Controlled demolition of dataflows](https://github.com/materializeinc/materialize/issues/400) - in general, dropping an view should restore the memory state to it's previous state
1. [Reduce risk of errant view/query consuming all memory](https://github.com/MaterializeInc/materialize/issues/672)

@frankmcsherry and @cuongdo does this look reasonable to you?

**Comment by awang** [comment]
The immediate outcome for our end-users would be a new tool we can ask them to run, and send us the results of.

The desired outcome for us would be to identify how best to proceed with the Followon Tasks.  In other words, this would be most useful if we're able to make forward progress towards those.

If users could use this to self-diagnose, that would be great, but I'm expecting them to have to send the results to us. I imagine  this to be similar to a memory profile: there are some interesting takeaways for the average user, but you're likely going to have to be familiar with the codebase for it to be immediately actionable.

**Comment by benesch** [comment]
We have `mz_dataflow_arrangement_sizes` now, which reports the size of each arrangement in the system. I believe that accomplishes enough of the original spirit of the issue.
