### ISSUE TITLE
Dataflow visualizations are inconvenient to share

### ISSUE THREAD

**Issue by cuongdo** [MaterializeInc/materialize#4495]
Due to their length and possibly some of the characters they contain, dataflow visualization URLs can be hard to share.

To successfully share the visualization for chbench q05, I had to put it into the following GItHub gist:

https://gist.github.com/cuongdo/cbbad4f964b61066cf164de0bfef540c

I could not share the URL using the following:
* Slack refuses to post the URL due to message length limits, even if you hide the URL behind a titled link
* Bit.ly complains that the URL isn't valid

cc @mjibson

**Comment by benesch** [comment]
Should we gzip the data first?

**Comment by mjibson** [comment]
The URL size in that gist is 28k. gzipped version is 4075 bytes. Sounds good.

**Comment by justinj** [comment]
Another option, if they are still yet too big, is to have a service (the telemetry server maybe?) that an MZ instance can send the full contents to and get a url-shortener version back
