### ISSUE TITLE
sql: array_lower doesn't descend dimensions

### ISSUE THREAD

**Issue by sploiselle** [MaterializeInc/materialize#4517]
In Postgres, the second argument to `array_lower` indicates which dimension of the array you want the lower bound of, e.g.

```
SELECT array_lower(ARRAY[[[9]]], 2);
 array_lower
-------------
           1

SELECT array_lower(ARRAY[[[9]]], 3);
 array_lower
-------------
           1
```

However, the implementation in MZ basically just does a check that the array has that many elements and doesn't perform any kind of dimensional descent:

```
materialized=> SELECT array_lower(ARRAY[[[9]]], 2);
 array_lower
-------------

(1 row)

SELECT array_lower(ARRAY[[[9, 10]]], 2);
 array_lower
-------------
           1
(1 row)

materialized=> SELECT array_lower(ARRAY[[[9, 10]]], 3);
 array_lower
-------------

(1 row)
```

For an example of a function with a similar API that descends into a list (not an array, but close!), checkout [`list_length_max`](https://github.com/MaterializeInc/materialize/blob/main/src/expr/src/scalar/func.rs#L3363).

**Comment by benesch** [comment]
Oops, great catch, Sean! This is actually quite a bit simpler with arrays than with lists. Just need to iterate over dims rather than elements: 

https://github.com/MaterializeInc/materialize/blob/13217abc049201d1e5e9ab75f6de25bc9382162b/src/repr/src/adt/array.rs#L34-L37
