### ISSUE TITLE
materialized: mz_catalog queries should be fast and not block

### ISSUE THREAD

**Issue by mjibson** [MaterializeInc/materialize#4537]
A user reported the /memory page was stuck on the `Loading...` message. We need to do more analysis of how mz_catalog debug queries work under load. Users may use the memory page or run other debug queries when their mz instance is having trouble, and those are the worst times for mz_catalog to block or be unusably slow.

I think our goal should be that mz_catalog never errors, blocks, or is any kind of slow.

**Comment by benesch** [comment]
I very much agree the sentiment, but I'm not sure the framing here will inform the solution. There is nothing particularly special about the tables and views in  `mz_catalog` implementation-wise. (Usage-wise, yes, you're more likely to want these tables when something is wrong with your cluster.)

Making mz_catalog more responsive is the same as the general "loss of interactivity" (#1537) that plagues Materialize clusters under load. Basically we need Materialize to be more responsive to all "cheap" queries even when it is under heavy load. That'll make mz_catalog queries fast as well as queries against user-created sources/views provided those views have data ready to go.

**Comment by benesch** [comment]
I've reopened #1537. I'm going to use that as a general tracking issue. As mentioned above there isn't anything particularly special about losing interactivity on the catalog views.
