### ISSUE TITLE
Progress messages in `TAIL` output.

### ISSUE THREAD

**Issue by umanwizard** [MaterializeInc/materialize#4539]
`TAIL` should have a way to communicate that a timestamp is closed, so that users can know when diffs have stopped changing.

**Comment by benesch** [comment]
From a discussion I just had with Brennan in person: possibly "easy mode TAIL" should not involve progress messages at all, and instead guarantee that you'll only ever see non-decreasing message timestamps.

There are several defects with this approach:

  * The client won't know when they've seen all messages. (This is the inverse of the flush-tables problem we used to have.)
  * We're forced to do a single-threaded sort.

That said, I believe this will cover 80% of use cases, and cover those use cases more ergonomically than if progress messages were present. Progress-less streaming is what most folks are used to with Kafka.

This doesn't preclude adding a `TAIL WITH PROGRESS` variant down the road for more sophisticated users.
