### ISSUE TITLE
Extend popular client libraries to make their COPY implementation usable for Materialize tail.

### ISSUE THREAD

**Issue by umanwizard** [MaterializeInc/materialize#4540]
Most client libraries support Postgres's COPY protocol, but in a way that is not useful to Materialize. Common issues include:

(1) The copy from server to client is not cancelable - it relies on the server to tell the client when it's done. This doesn't make sense for Materialize, where `TAIL`s never end until the client wants them to.
(2) The library doesn't expose a stream of rows to the caller, but rather just writes them all into a database file

We should upstream some work on a few of the most popular client libraries (pgjdbc, psycopg2, pg8000) in order to address these issues. In order to maximize the probability of our upstream changes being accepted, we should strive to frame them in a way that is potentially useful to users of Postgres, not just Materialize.

**Comment by mjibson** [comment]
Regarding 1. The [postgres docs](https://www.postgresql.org/docs/10/protocol-flow.html#PROTOCOL-COPY) say:

> The frontend cannot abort the [COPY TO] transfer (except by closing the connection or issuing a Cancel request)

and as a maintainer of a [Go postgres driver](https://github.com/lib/pq) there's no way I would accept changes to a driver that were against the spec.

At this point I'm questioning the motivations to use the copy protocol for this. We want it to have many properties regular SQL rows already have. Extending drivers to do this is going to be a no-go from many or all of them. We may need to reconsider this feature and figure out how we can get what users need in to a thing supported by the postgres protocol.

**Comment by umanwizard** [comment]
Perhaps what we could do (if we want to continue using the copy protocol) is tell people to issue cancel requests, then. Is that something typically supported by driver APIs ?

**Comment by mjibson** [comment]
AFAIK yes those are generally supported. There are also other options like adding a parameter to TAIL that specifies a timestamp to return at, which can then be used in the `AS OF` for next query or something. I think my argument is that if we are willing to work on the drivers, then we should re-asses if COPY is the best protocol.

**Comment by mjibson** [comment]
https://github.com/MaterializeInc/materialize/issues/2821!

**Comment by umanwizard** [comment]
> There are also other options like adding a parameter to TAIL that specifies a timestamp to return at, which can then be used in the AS OF for next query or something.

This has the defect that on slow-moving streams, you might never return. On the other hand... it might be fine to just tell anyone using non-real-time sources "sorry, you are on the hook for tuning your UNTIL params properly".

> I think my argument is that if we are willing to work on the drivers, then we should re-asses if COPY is the best protocol.

I talked about this in more detail in #engineering on Slack. The tl;dr is that I'm all for it, if there's something else that lets us meet all the constraints.

**Comment by benesch** [comment]
We actually already support the use of the cancel protocol to abort `TAIL`s, and I think that's a reasonable solution for now. Alternatively, just axe the connection and open a new one, since the cancel protocol opens a new connection anyway.

I don't think we actually need to extend any client libraries in the near future to make this worthwhile.

**Comment by umanwizard** [comment]
@benesch We would still need to work on client libraries in order to make copy give you a stream of rows, because some of them (at least including psycopg2) just take a file object and dump the rows there.

**Comment by benesch** [comment]
Right, but I think it's fine to say "you're on your own" if you're using psycopg2 with Materialize in the short term, because there are clients (Npgsql + rust-postgres) that do expose the necessary interfaces out of the box.

**Comment by umanwizard** [comment]
@awang have we verified that the people who are asking for this in the short term are using npgsql?

**Comment by awang** [comment]
@umanwizard I'll DM you with details, but the answer is yes
