### ISSUE TITLE
Toggle whether logging logs the logging.

### ISSUE THREAD

**Issue by frankmcsherry** [MaterializeInc/materialize#4542]
The logging dataflows by default do not log their own behavior, as this leads to substantial CPU churn as we continually update stats about our own logging. However, this can be helpful to diagnose potential defects in the logging dataflows themselves. The change is about ten lines of code copy/pasted twenty lines away, and seems like it could reasonable just be a command line toggle.

cc: @elindsey @ruchirK

**Comment by ruchirK** [comment]
I'm happy to do this real quick if you want frank?
