### ISSUE TITLE
Don't cast Nulls to Array(String) during function selection

### ISSUE THREAD

**Issue by JLDLaughlin** [MaterializeInc/materialize#4549]
In implementing `array_upper` (https://github.com/MaterializeInc/materialize/pull/4515), I found that the following test case returns different results when run against Materialize and Postgres because we will currently cast anything to an array of strings:
```
materialize=> SELECT array_upper(NULL, 1);
 array_upper
-------------

(postgres)
jessicalaughlin=# SELECT array_upper(NULL, 1);
ERROR:  could not determine polymorphic type because input has type unknown
```

We are currently okay with this divergence, particularly since @sploiselle's work later this week might clean it up, but creating this issue to track this difference.

**Comment by sploiselle** [comment]
Fixed in #4582
