### ISSUE TITLE
Clearly demarcate source-type specific panels on the dashboard

### ISSUE THREAD

**Issue by benesch** [MaterializeInc/materialize#4552]
See, for example, this graph on Grafana: https://grafana.i.mtrlz.dev/d/materialize-overview/materialize-overview-load-tests?orgId=1&from=1603080000000&to=1603252799000

**Comment by quodlibetor** [comment]
It actually only works for kinesis events, where it [does show up](https://grafana.i.mtrlz.dev/d/materialize-overview/materialize-overview-load-tests?orgId=1&from=1603080000000&to=1603252799000&var-env=dev&var-purpose=load_test&var-test=perf-kinesis&var-workflow=cloud-load-test&var-commit_time=All&var-git_ref=All&var-id=.*&var-command=execute&var-command=query&var-timely_workers=All&var-built_at=2020-10-19T14:39:38Z&var-build_version=0.5.0-rc3&var-build_sha=f24437d965984b80bc48bb45ef861c73036a41db&var-instances=All&var-id_explicit=All&var-ec2_instance_type=All&var-num_warehouses=All&var-oltp_threads=All&var-olap_threads=All&var-queries=):

<img width="780" alt="image" src="https://user-images.githubusercontent.com/277161/96613065-83468f80-12cc-11eb-9e15-bd8664b09bd5.png">

We should more clearly demarcate source-type only panels though.

**Comment by benesch** [comment]
Maybe just the release checklist is wrong then? 
![image](https://user-images.githubusercontent.com/882976/96616086-2220bb00-12d0-11eb-8f14-36ba78b700c7.png)

**Comment by quodlibetor** [comment]
ohh, each of those checkboxes is for a different test, which should be made more clear, yes.

**Comment by quodlibetor** [comment]
#4839 improved this a bit for the specific issue of the kinesis "time behind external source" metric.

**Comment by quodlibetor** [comment]
This is done.
