### ISSUE TITLE
Extend source caching to speed up restarts

### ISSUE THREAD

**Issue by cuongdo** [MaterializeInc/materialize#4566]
0.5 added an experimental version of source caching (f.k.a. source persistence) that writes data from Kafka sources to disk. This was a good first step, reducing the impact of Materialize restarts on upstream Kafka brokers.

One of the main benefits users want from source caching is to speed up restarts. We've considered the following approaches:

1. Cache data in a format that's native to Materialize to reduce the work required to re-read cached source data on restart
2. Cache data for materialized views

Item 2 is a long-term effort that needs significant design and engineering work. 

Item 1 *should* improve restart times, but we may want to verify that's the case with a prototype. To prevent adding significant tech debt, item 1 requires some form of #2537 (source orthogonality).

cc @umanwizard @ruchirK

**Comment by ruchirK** [comment]
closing this because source caching was removed in #7328 (we're going to go a different direction with the persist crate)
