### ISSUE TITLE
Tailed file sources occasionally fail to be initialized with cryptic error messages

### ISSUE THREAD

**Issue by ruchirK** [MaterializeInc/materialize#4567]
Some users are seeing log lines like the following

```
Oct 20 23:34:47.104 ERROR dataflow::source::file: file source: failed to create notify watcher: other os error (path: /tbshare/data/tb.UMAU_STAGING_1.PRODUCT)
```

which indicates a failure to create a directory notifier (not sure of the correct noun) used for TAIL-ed file sources on Linux machines. The string `other os error` comes from Rust's internal io error type and corresponds to some flavor of io error not covered by everything else in `std::io::ErrorKind` ( https://doc.rust-lang.org/std/io/enum.ErrorKind.html )

Also worth noting, this error doesn't always happen and it only seems to happen when creating dataflows that read from a large number (10+) of file sources at the same time

**Comment by umanwizard** [comment]
If you have more details about the dataflow/use-case, can you share it? (On slack, if it's confidential)

**Comment by damienhollis** [comment]
The use case is very simple, I was trying to get a count of the number of records in all the sources (unmaterialized) and I thought an easy way to do that would be to create a single materialized views like:

`create materialized view source_count as 
select 'source_a', count(*) from source_a
union all
select 'source_b', count(*) from source_b
union all
select 'source_c', count(*) from source_c;`

The actual view has 17 sources.

The server is n2-standard-4 on GCP. It is running centos 7.  The sources are from `tb` and reside on persistent SSD. We are not running materialize in docker. The server also has a local SSD disk but that is just used for swap.

**Comment by damienhollis** [comment]
We rebuilt our materialize server using ubuntu and recreated the view and it worked fine this time. So it would appear that the problem is caused by centos, although this is just one data point, so it might be something else completely.

**Comment by umanwizard** [comment]
My guess is that `sysctl fs.inotify.max_user_watches` was too low. If so, we should check for this and report a friendlier error message.

**Comment by benesch** [comment]
Is it really so low that you’d run into it with just a dozen files though?
That seems unlikely to me. Certainly possible, but just seems unlikely that
the default is 10, or that another process used LIMIT - 2.

I wonder if we should just give up on this notify library. It’s been a
constant source of bugs. Polling once a second isn’t so bad and it’s a lot
more reliable.

**Comment by benesch** [comment]
Obsoleted by platform.
