### ISSUE TITLE
Unify "Avro OCF" and "Avro Kafka" decoding code

### ISSUE THREAD

**Issue by umanwizard** [MaterializeInc/materialize#4575]
part of #2537 .

Right now, Avro decoding goes through two completely separate code paths depending on whether it came from an OCF file (delimited by the bounds of the message itself; i.e., you need to decode the message to find out where it ends) or a Kafka stream (delimited by Kafka messages).

This is bad and we should unify the code as much as possible.

**Comment by guswynn** [comment]
We don't support OCF files anymore!
