### ISSUE TITLE
Surface logged timely dataflow message counts

### ISSUE THREAD

**Issue by frankmcsherry** [MaterializeInc/materialize#4584]
Timely dataflow logs numbers of messages that move along each of the channels. This is information, not unlike memory and CPU used, that can help folks diagnose performance issues.

One particular thing I would like to see are the numbers of data vs progress messages. The latter has the potential to be quadratic in the worker count, and while there are interventions we can do we would want to see the measurements first.

**Comment by ruchirK** [comment]
Do you have a sense for how difficult this might be? I wonder if it is appropriate for a third or fourth issue

**Comment by frankmcsherry** [comment]
I think it looks a lot like the `mz_scheduling_*` views, in that there are some things to add up, and then to toss away once we don't track the dataflow any more. I suspect almost all the code can be copy/pasted, and the sport would be figuring out where all that code needs to be (e.g. schema definitions, etc).

**Comment by antifuchs** [comment]
@frankmcsherry Ruchir just pointed me at this issue & it's interesting! Did you start on this yet, or am I good to pick it up?
