### ISSUE TITLE
docs: Implement breadcrumbs to improve usability of docs

### ISSUE THREAD

**Issue by krishmanoh2** [MaterializeInc/materialize#4591]
We could implement breadcrumbs in docs. This allows for several benefits such as easy back/forth, educating the customer on a workflow (simple to complex) - especially on how-to type articles.

Examples are here - https://docs.yugabyte.com/latest/quick-start/build-apps/python/ysql-psycopg2/
https://docs.aws.amazon.com/redshift/latest/dg/welcome.html

@rjnn

**Comment by sploiselle** [comment]
This is relatively straightforward to implement in Hugo, see: [1](http://hugocodex.org/add-ons/breadcrumbs/), [2](https://discourse.gohugo.io/t/solved-how-to-implement-breadcrumbs-with-categories/14041)

**Comment by rjnn** [comment]
cc @msudberg as well

**Comment by msudberg** [comment]
We can enable this as part of implementing a new theme for #4551, but we might also want to just go forward and start it off on our current setup without waiting, if it's simple. I'll take a look.

**Comment by benesch** [comment]
> implementing a new theme

Wait, are we planning to rebuild the docs theme?

**Comment by msudberg** [comment]
I would like to, yes. There's one that would make it a lot easier to implement and maintain some of the features I want. But I need to be sure a) it won't break anything b) can match or approximate the current appearance first.

**Comment by benesch** [comment]
Ok, then we should definitely sync up! The current docs theme has built up a fair few customizations over time, and I'm worried we're pretty far past the point where it is straightforward to swap out the current theme for another. But I am hopeful there might be a quick path to adding the missing features to the current theme!
