### ISSUE TITLE
docs: Implement copy button for commands to improve docs usability and reduce copy/paste errors

### ISSUE THREAD

**Issue by krishmanoh2** [MaterializeInc/materialize#4592]
We can implement copy button for commands. This makes it simpler to follow instructions - especially tutorials.

Examples here - https://docs.aws.amazon.com/redshift/latest/dg/t_loading-tables-from-s3.html

@rjnn

**Comment by benesch** [comment]
This is a great idea, and something we've been meaning to do for a while.
