### ISSUE TITLE
docs: show command prompt in shell commands

### ISSUE THREAD

**Issue by krishmanoh2** [MaterializeInc/materialize#4593]
Currently, we do not show the shell prompt when a user requires to run an OS command. As a result, some of the steps fail when run as a non-privileged user - example below  from https://materialize.io/docs/install/

The part where we need to run curl and other commands as well - missing the user prompt as $ or #

`[mz@compute1vm2 ~]$ curl -L https://downloads.mtrlz.dev/materialized-v0.4.3-x86_64-unknown-linux-gnu.tar.gz \
>     | tar -xzC /usr/local --strip-components=1
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 63.0M  100 63.0M    0     0  6720k      0  0:00:09  0:00:09 --:--:-- 6928k
tar: bin/materialized: Cannot open: Permission denied
tar: bin: Cannot utime: Operation not permitted
tar: etc/materialized: Cannot mkdir: Permission denied
tar: Exiting with failure status due to previous errors
`
General industry practice is to show the user running the commands as below - https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-install.html

![Screenshot from 2020-10-23 11-02-25](https://user-images.githubusercontent.com/72518904/97026647-4a522900-151f-11eb-9660-1655a35ed322.png)

The command here is run by a normal user. 

In order to run as root, either we use sudo or show the root prompt. The example below - AWS is showing sudo.

![Screenshot from 2020-10-23 11-03-39](https://user-images.githubusercontent.com/72518904/97026818-81c0d580-151f-11eb-998c-39fd00455702.png)

The docs can use sudo wherever root privileges are needed and follow the convention for showing users are non-privileged. This would make it obvious and also standardize the process.

**Comment by krishmanoh2** [comment]
@rjnn

**Comment by morsapaes** [comment]
Fixed in #7815.
