### ISSUE TITLE
docs: document minimum requirements to run materialize

### ISSUE THREAD

**Issue by krishmanoh2** [MaterializeInc/materialize#4594]
Document minimum requirements to run materialize - this will ensure basic standards for running materialize

For example - Linux Kernel release, Linux vendor (redhat, centos, ubuntu etc), Linux Vendor release, Minimum number of CPU, Minimum memory, minimum swap, disk for persistence (and disk specs - SSD, NVME etc) and any other linux sysctl params

TCP Port 6875 is the default and needs to be open.

Example here - https://docs.memsql.com/v7.1/reference/configuration-reference/cluster-configuration-reference/system-requirements/

@rjnn

**Comment by benesch** [comment]
The start of this documentation is here: https://materialize.io/docs/ops/deployment/. It's not yet very specific about hardware requirements because we don't have the necessary experience to state any rules of thumb. But we are certainly interested in coming up with those rules of thumb over time.

**Comment by awang** [comment]
can we start by documenting what OSes we officially test/support?

re: cpu/memory/disk -- not a priority, as this collides with cloud product.
if we feel comfortable supporting a t3.nano instance class, i think that's sufficient

**Comment by benesch** [comment]
Presently we only test on Ubuntu 18.04, though any similarly recent Linux
should work.

**Comment by morsapaes** [comment]
Linking to #742.

**Comment by morsapaes** [comment]
Closing, now that we're running on cloud! Related: we'll include a sizing guide in the documentation to support users with provisioning for sources and sinks.
