### ISSUE TITLE
cli: mimic --data-directory for log directory as well

### ISSUE THREAD

**Issue by krishmanoh2** [MaterializeInc/materialize#4598]
Current materialize option to separate log file and data directories are confusing UX.

We have -- data-directory (expecting a directory) and --log-file (expecting a file name and pre-created directories)

It is better to not have to specify the file-name, but rather to only point to a directory. Keeping the name as materialized.log will make it consistent and easy for customers/support.

Maybe change  --log-file PATH where materialized will write logs (default <data
                        directory>/materialized.log)

to 

--log-directory PATH where materialized will write logs 

This is more in sync with industry standards as well. 

Both data-directory and log-directory would create the directory structure if missing and if unable to do so, report the error with a code that is easy to understand.

**Comment by krishmanoh2** [comment]
@rjnn

**Comment by benesch** [comment]
Hmm, I'm not sure I understand what the problem with the current design is. Is it just that we don't ensure that the parent directories of the specified log file exist? Your proposal would make things a bit less flexible by requiring that the file be named materialized.log, and I'm not sure why that restriction would be good? Plus most users are not presently expected to configure the log file, and simply leave it in its default location.

I can definitely imagine that we will need to support "Enterprise Grade Logging" at some point, where we rotate log files (#4599) and can target a variety of logging sinks, like syslog, have slow query logs, etc. But I'm not sure we understand the common deployment strategies enough to be able to nail the design of that feature right now.

**Comment by krishmanoh2** [comment]
In my experience with other products (oracle, memsql),  the log file name is fixed however the location can be changed. This allows for easy finding/correlation with what the file represents.  If there is a problem, it is easier for the end user to search for the file materialized.log as well. This is for standardization as well. 

logfiles and data files are kept separate or have the ability to keep them separate. logfiles tend to grow and sometimes fill up the filesystem. Certain organizations also restrict access to the logfiles depending on the content - if auditing is turned on or not. 

Example from oracle - https://docs.oracle.com/cd/B19306_01/server.102/b14237/initparams018.htm#REFRN10008

From crdb - https://www.cockroachlabs.com/docs/stable/debug-and-error-logs.html

**Comment by rjnn** [comment]
> Hmm, I'm not sure I understand what the problem with the current design is
I believe the problem here is that the two things we specify (data directory and log directory) have opposing behaviors (one creates a directory and puts its files there, one expects a directory to exist and targets a specific file) and that's counterintuitive for a new user.

**Comment by benesch** [comment]
> > Hmm, I'm not sure I understand what the problem with the current design is
> 
> I believe the problem here is that the two things we specify (data directory and log directory) have opposing behaviors (one creates a directory and puts its files there, one expects a directory to exist and targets a specific file) and that's counterintuitive for a new user.

Then I just disagree that this is confusing. The first option configures the *directory* in which data will be stored and is therefore called `--data-directory`. The other option configures the *file* in which logs will be written and is therefore called `--log-file`. That seems very clear to me. In fact, having a `--log-directory` option seems more confusing to me, because it implies that we might automatically rotate log files when we do not (#4599). I think we should support log rotation eventually, but until we do, I don't see why we should change the existing options.

It does seem wrong that `--data-directory` creates the parent hierarchy but `--log-file` does not. I think it makes sense to make both create their parent hierarchy.

**Comment by rjnn** [comment]
> It does seem wrong that --data-directory creates the parent hierarchy but --log-file does not. I think it makes sense to make both create their parent hierarchy.

I would be happy with that solution.
