### ISSUE TITLE
docs: document log rotation best practices

### ISSUE THREAD

**Issue by krishmanoh2** [MaterializeInc/materialize#4599]
log rotation of materialized.log automatically is a customer loved feature. Pretty much most products do not do this today and having this as an option makes a difference in managing the environment.

@rjnn

**Comment by benesch** [comment]
I agree this is a nice to have, but I'd like to propose that this be considered low priority, because a sufficiently dedicated user can wire this up themselves with standard programs like `logrotate`.

**Comment by rjnn** [comment]
probably easy enough to document the standard tool to use, under a 'recommended production settings' section

**Comment by awang** [comment]
`logrotate` works great, but I don't think it should be our responsibility to document this, as it will then need to be kept up to date.  Bringing this inhouse goes against our path towards being cloud-first.
