### ISSUE TITLE
UX - materialized -h help syntax not in sync with documentation

### ISSUE THREAD

**Issue by krishmanoh2** [MaterializeInc/materialize#4600]
materialized - h Help syntax not in sync with documentation

    -p, --process INDEX identity of this process (default 0)
    -n, --processes N   total number of processes (default 1)

Docs has it correct - 

![Screenshot from 2020-10-21 09-44-40](https://user-images.githubusercontent.com/72518904/97032176-0105d780-1527-11eb-887f-35eb7dcaebd7.png)

@rjnn

**Comment by benesch** [comment]
What is out of sync here? They both look correct to me.

**Comment by krishmanoh2** [comment]
Could we make them the same? The -h syntax is not intuitive that these are options for running a distributed cluster. The docs has it better.

**Comment by benesch** [comment]
Oh, I see. Sure!
