### ISSUE TITLE
cli: remove the word DANGEROUS and change "enable experimental features" to "enable beta features"

### ISSUE THREAD

**Issue by krishmanoh2** [MaterializeInc/materialize#4601]
Could be “enable beta features” and remove the word DANGEROUS

beta features are always unsupported but valuable in terms of gathering feedback from end-users.

@rjnn

**Comment by benesch** [comment]
Experimental features _are_ dangerous. They might corrupt your data or brick your cluster. They are not to be used in production. The current wording is correct, in my opinion.

**Comment by sploiselle** [comment]
We do also have the notion of alpha/beta features, e.g. [Kinesis](https://materialize.io/docs/sql/create-source/text-kinesis/). The experimental features are a different and distinct class of feature.

**Comment by rjnn** [comment]
@awang we should have a product discussion to standardize on which words we use (beta vs experimental vs dangerous) and when

**Comment by benesch** [comment]
This got done in https://github.com/MaterializeInc/materialize/pull/7270!
