### ISSUE TITLE
docs: migrate and maintain the architecture blog post to a more permanent home

### ISSUE THREAD

**Issue by krishmanoh2** [MaterializeInc/materialize#4605]
Logs are a great way to educate end-users. By exposing more information in logs and documenting it, we help customers teach themselves.

The various sub-systems in the logs could be documented - dataflow, coord, pgwire, sql_parser (maybe more)

@rjnn

**Comment by benesch** [comment]
> Logs are a great way to educate end-users. By exposing more information in logs and documenting it, we help customers teach themselves.

I'd like to gently push back on this claim. In my opinion, logs, especially info/debug logs, are the last resort for educating end users. They are primarily intended to help developers diagnose problems, with the secondary goal of being useful to the most sophisticated of users. I do not think it should be a goal for most users to be able to understand most log messages, with the exception of errors/warnings.

In general error log messages indicate a deficiency in proper error reporting channels, like the issue with CSV sources that you pointed out. Practically every error log should be converted to a runtime error that is surfaced through SQL, where is it much more accessible to users. To a first approximation, whenever we currently might expect a user to understand a log message, I'd prefer to try to surface that information outside of the logs instead.

**Comment by rjnn** [comment]
I think there's an impedance mismatch between developers (who dont use logs for education) versus DBA/operators (who do). In any case, let's split the asks into two:

1) document the subsystems for user/operator education - this is done in the blog post: https://materialize.io/blog-architecture

One thing that @msudberg pointed out is that the blog is more "ephemeral" (and hence @krishmanoh2 might have missed it)  - so there's a need to transfer the knowledge that is in the blog into a more "permanent" home on the docs site. 

2) adding some of this information to the logging systems for DBAs/operators to help diagnose errors. I think here I'm with @benesch - we should surface this in SQL errors. So we'll table this part for now (although I suspect that in the long run we'll increasingly sprinkle in things for operators over time, so I'm not against revisiting this once we're at a later stage of development).

Renaming the issue to reflect the task listed in (1) above.

**Comment by morsapaes** [comment]
Closing this issue since it's covered (and linked) in #8655.
