### ISSUE TITLE
dataflow: invalid kafka sources should error out at creation time

### ISSUE THREAD

**Issue by krishmanoh2** [MaterializeInc/materialize#4607]
Currently, it looks like materialize allows you to create a source without validating the source ( as in IP address, file location etc). 

If we are able to validate the source at create time, it would be helpful in preventing other problems down the line. This would be helpful for developers to catch problems at the onset.

For example - Kafka source with a broken IP address - selecting from source returns no errors. Here the IP address is not valid. There is no such host.

materialize=> CREATE SOURCE "materialize"."public"."jtest2" FROM KAFKA BROKER '192.168.1.252:9092' TOPIC 'user_behavior' FORMAT BYTES;
CREATE SOURCE

materialize=> select * from jtest2 limit 10 as of now();
 data | mz_offset 
------+-----------
(0 rows)

It was surprising that it did not error out. In my experience with other similar products, the engine rejects a source if not accessible. This helps correct the problem during create time.

With a csv source, the error was different -

Broken source does not  report where/what/why it is broken

materialize=> select * from category as of now();
ERROR:  Source error: File IO: Is a directory (os error 21)

Both the cases, I was able to create the source without any issues. 

@rjnn

**Comment by rjnn** [comment]
this has tripped me up as well, although I believe the issues I filed were mostly to do with local sources (e.g. file sources where the file doesn't exist). @krishmanoh2 brings up issues where there are kafka sources, which seem similar. 

@krishmanoh2 your second point seems like the error message is clear to me: when I tried to create a source, I got a clear error message:

```
materialize=> create source name_raw2 from file '/Users/arjun' format csv with header;
ERROR:  Is a directory (os error 21)
```
And the source wasn't created. So that seems fine, unless you uncovered a different error?

**Comment by krishmanoh2** [comment]
I still see the problem with creating csv sources that are pointing to invalid locations -

materialize=> CREATE SOURCE "materialize"."public"."category12" ("category", "description") FROM FILE '/home/mz/src/flink-sql-demo' FORMAT CSV WITH 3 columns DELIMITED BY ','
;
CREATE SOURCE
materialize=> select * from category12 as of now();
ERROR:  Source error: File IO: Is a directory (os error 21)

**Comment by rjnn** [comment]
Interesting, this might be a linux versus mac problem. This problem does not occur on OS X! Please file a separate issue (leaving this one kafka focused)

**Comment by awang** [comment]
some internal discussion on potential behavior:  https://materializeinc.slack.com/archives/C01CFKM1QRF/p1608134924483700
