### ISSUE TITLE
Reduce duplication between keys and rows of an arrangement.

### ISSUE THREAD

**Issue by frankmcsherry** [MaterializeInc/materialize#4629]
Our arrangements arrange data by a key, maintaining the whole row because that is the plan. However, in cases where we don't have good information about key structure, we use the entire row as the key. This results in entire duplication between the key and row.

The key information is statically available, and we should be able to for example remove the key columns from the row itself. This requires a plan for which way to remove the redundant information, perhaps by eliding any row columns where `Column(foo)` exists in the key, and then some not unpleasant tooling for going from a key and row pair to a `[Datum]` containing what used to be there (most likely by pointing somewhat at the key and somewhat at the row).

**Comment by benesch** [comment]
Is this #220? #778 was tracking exactly what you've written here, but it was closed in favor of #220. Possibly #778 should not have been closed, because #220 seems slightly different.

**Comment by frankmcsherry** [comment]
That's why I could find it! Yes, it is a dup of #778, which was partially addressed in the context of joins, but not other arrangements. For example, 
```
create default index for source
```
still does the bad thing if `source` doesn't have any keys. I think pointing at #220 in closing #778 might have been a bug, as secondary indexes are def a bigger thing.

**Comment by frankmcsherry** [comment]
dup of #778, which I've re-opened.
