### ISSUE TITLE
source-caching: enforce minimum for persistence-max-pending-records

### ISSUE THREAD

**Issue by krishmanoh2** [MaterializeInc/materialize#4642]
We are able to set persistence-max-pending-records to as low as 1 which can result in 

1. Significant number of files created causing filesystem issues

2. Persistence failing with errors as below -

`

Oct 22 10:50:03.895 DEBUG dataflow::source::kafka: reading persisted data from /data/mz/data/persistence/u58/materialize-cf1abdd286ad4d13b6eb664a34b8777c-u58-0-12856-12857    Oct 22 10:50:03.896  WARN dataflow::source::kafka: Kafka message before expected offset: source kafka-u58/25 (reading topic user_behavior, partition 0) received Mz offset 1 expected Mz offset 12858
--
Oct 22 11:06:37.357 ERROR coord::persistence: Persistence thread encountered error: failed to flush enough for source u58. Currently 101 pending but max allowed is 100    Oct 22 11:06:37.357 ERROR coord::persistence: All persisted sources on this process will not continue to be persisted.
`

It maybe better to enforce a minimum for this flag.

**Comment by ruchirK** [comment]
closing this because source caching was removed in #7328 (we're going to go a different direction with the persist crate)
