### ISSUE TITLE
Surface more information in EXPLAIN

### ISSUE THREAD

**Issue by justinj** [MaterializeInc/materialize#4657]
As of changes like #4649 we detect certain patterns in the coordinator and perform them more efficiently. Whether or not this will happen is not currently surfaced from the `EXPLAIN` for the query, which is not ideal. We could fix this by making these decisions in the optimizer and encoding them in the plan returned (say, by absorbing MFPs into `Get`).

**Comment by wangandi** [comment]
Superseded by #13138 and #13137
