### ISSUE TITLE
dataflow: on Linux hosts - able to create csv sources pointing to invalid locations

### ISSUE THREAD

**Issue by krishmanoh2** [MaterializeInc/materialize#4674]
[mz@compute2 bin]$ uname -a
Linux compute2 4.18.0-193.el8.x86_64 #1 SMP Fri May 8 10:59:10 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

mz version - 0.5.0

materialize=> CREATE SOURCE "materialize"."public"."category12" ("category", "description") FROM FILE '/home/mz/src/flink-sql-demo' FORMAT CSV WITH 3 columns DELIMITED BY ','
;
CREATE SOURCE
materialize=> select * from category12 as of now();
ERROR: Source error: File IO: Is a directory (os error 21)

**Comment by umanwizard** [comment]
thanks for the report. All we do on source create time is check that the file can be readably opened - we should also make a stat call to check that it is not a directory.

It still won't be possible to robustly detect all possible fs read errors ahead of time (the file might go away between source creation and ingest, or read might fail for any number of reasons...) but we can indeed handle this particular case.
