### ISSUE TITLE
Peek already/not yet registered error messages

### ISSUE THREAD

**Issue by wangandi** [MaterializeInc/materialize#4697]
From logs of a prospect. First, you see messages like this, one for each available worker:
```
[2mNov 03 20:47:00.218[0m [31mERROR[0m dataflow::logging::materialized: peek already registered: worker=3, connection_id: 0 
```
Then a second later there are messages like this, one for each available worker:
```
[2mNov 03 20:47:01.315[0m [31mERROR[0m dataflow::logging::materialized: peek not yet registered: worker=3, connection_id: 0
```

`connection_id: 0` corresponds to sql-over-http, which is used by our memory visualization tool. Indeed there was a memory visualization query then, but because we weren't staring at the logs while querying for memory visualization, it is unknown what the specific sequence of memory visualization http queries caused this.

It is unknown whether anything bad happens elsewhere due to this error. It's possible that we just want to use a more distinct id for peeks than the connection id for logging purposes.

**Comment by mjibson** [comment]
pgwire uses the connection id for specific stuff (connection cancellation) and currently doesn't have any hooks outside of it for other stuff to get and recycle connection ids. If peeks need some kind of unique identifier number for the thing doing the peeking, we could consider using something else that's not the connection id, since not all peek requests are attached to a real connection.

**Comment by frankmcsherry** [comment]
> If peeks need some kind of unique identifier number for the thing doing the peeking, [...]

They probably do. In addition to the error guff in the output, peek cancellation happens by `conn_id`. If these get confounded, we end up cancelling other peeks with the same connection id.

**Comment by chaas** [comment]
Closing this, since it appears to have been resolved in https://github.com/MaterializeInc/materialize/issues/17568.
