### ISSUE TITLE
sql: support `regexp_split_to_array` function

### ISSUE THREAD

**Issue by rjnn** [MaterializeInc/materialize#4714]
~Postgres has an optional flag `g` - which we do not currently support, which returns all matches. We should add support for this, requested by a user.~

We should support `regexp_split_to_array` function. See: https://www.postgresql.org/docs/current/functions-matching.html#FUNCTIONS-POSIX-REGEXP

**Comment by rjnn** [comment]
cc @benesch who i believe implemented `regexp_match` to give a quick work estimate here

**Comment by benesch** [comment]
`regexp_match` does not support the 'g' flag even in Postgres, actually:

https://github.com/postgres/postgres/blob/24b83a5082541bdb1b333b7fcbe92f194128595c/src/test/regress/expected/regex.out#L118-L120

**Comment by benesch** [comment]
Not sure the `regexp_matches` function is actually the right choice for the problem that inspired this issue. Following up on the community Slack now.

**Comment by benesch** [comment]
Redirecting this to be about adding support for `regexp_split_to_array`.

**Comment by mjibson** [comment]
Closed by https://github.com/MaterializeInc/materialize/pull/20585
