### ISSUE TITLE
Support the UPSERT envelope for sinks

### ISSUE THREAD

**Issue by rjnn** [MaterializeInc/materialize#4716]
Sinks currently only support the Debezium envelope. Now that there is the ability to specify keys for sinks, we could support UPSERT semantics for sinks, where deletes follow the convention of empty values.

This is a prospect request.

**Comment by ruchirK** [comment]
This also requires setting `log.cleanup.policy = compact` in the sink topic btw, and we may want to expose some configurable options for compaction delay at sink creation time? or maybe not idk

**Comment by rjnn** [comment]
@ruchirK do you have an eyeball work estimate for this? Won't hold you to it.

**Comment by ruchirK** [comment]
I dont think this is super hard - should be a few days worth of work?

**Comment by awang** [comment]
@umanwizard is this one done?

**Comment by umanwizard** [comment]
no, there is a PR out that needs a few changes which I will clean up as soon as I'm back from vacation

**Comment by awang** [comment]
update: upsert sinks have landed, now we just need to document it

**Comment by umanwizard** [comment]
Yes! I will add documentation this week. Thanks for the reminder!

**Comment by awang** [comment]
@umanwizard where are we with this?  okay to close?

**Comment by rjnn** [comment]
Looks documented to me in our live docs
