### ISSUE TITLE
Allow remapping rows as deletes

### ISSUE THREAD

**Issue by wangandi** [MaterializeInc/materialize#4735]
A concrete example of what I'm looking for.
The MBTA V3 API is a server-sent events source (#2237) and data comes in like this:
```
event: update
data: {"attributes":{"arrival_time":"2020-11-04T18:52:42-05:00","departure_time":"2020-11-04T18:52:42-05:00","direction_id":1,"schedule_relationship":null,"status":null,"stop_sequence":5},"id":"prediction-45683936-69-5","relationships":{"route":{"data":{"id":"1","type":"route"}},"stop":{"data":{"id":"69","type":"stop"}},"trip":{"data":{"id":"45683936","type":"trip"}},"vehicle":{"data":{"id":"y1823","type":"vehicle"}}},"type":"prediction"}

event: remove
data: {"id":"prediction-45683928-57-6","type":"prediction"}
```

If we implement upsert-style sinks (#4716), I would like some way of specifying that the remove event goes into the kafka topic as a delete:
```
key                                                   | value
-------------------------------------------------------------------------------------------------
{"id":"prediction-45683928-57-6","type":"prediction"} |
```
as opposed to an upsert row:
```
key                                                   | value
-------------------------------------------------------------------------------------------------
{"id":"prediction-45683928-57-6","type":"prediction"} | {"data": null}
```

I can think of two potential ways of specifying a row should be treated as a delete:
1) Allow treating rows where all columns are null except the key column as deletes.
2) Allow specifying a boolean column within the view as the "deletion column", and rows get treated as deletes if that the entry in that column is "true".

I would like this to be implemented as a dataflow operator that takes a predicate and maps a row to `None` if the predicate is false or `Some(row)` if it is true that way the same operator could be reused for [creating an upsert view on top of a non-upsert source or view](https://github.com/MaterializeInc/materialize/issues/1576#issuecomment-621961931) and generalized upserts (#2814).

**Comment by wangandi** [comment]
The workaround for converting this server-sent event source to an upsert sink given the lack of this feature:
1) Sink the server-sent event source into a key-value topic t1.
2) Load t1 into Materialize as an upsert source and filter for the rows that don't match the "treat as delete criterion".
3) Sink the upsert source into key-value topic `t2`.

**Comment by wangandi** [comment]
Note that we already have a very similar dataflow operator [here] (https://github.com/MaterializeInc/materialize/blob/0f88a31c93bede73ae1424725b39e5fe22fd1f2a/src/dataflow/src/render/upsert.rs#L185), and the code inside this operator can probably be reused by the row remapping operator.

**Comment by uce** [comment]
@wangandi We were wondering yesterday whether this should be moved to sources/sinks. What do you think?

**Comment by wangandi** [comment]
Since upsert is out of my hands now, yes.

**Comment by benesch** [comment]
Subsumed by the more general feature of `TRANSFORM USING` (#16547).
