### ISSUE TITLE
Billing demo load test OOMs materialized

### ISSUE THREAD

**Issue by quodlibetor** [MaterializeInc/materialize#4753]
Some change to the queries that we materialize caused the billing demo to crash materialized when run for 24 hours. It should not.

**Comment by ruchirK** [comment]
Could you give a little bit more color on what happened here? Specifically

- did the memory usage jump by a lot or was it already close to the threshold and something tipped it over
- what was the last version that successfully ran the load test without OOM-ing

Also sort of meta-note- would it be useful if the billing demo binary itself stayed alive and periodically queried mz to make sure it was up? that way there wouldn't be a manual burden on the release engineer to make sure that the mz binary closed successfully

**Comment by benesch** [comment]
We no longer use the billing load test post platform.
