### ISSUE TITLE
Billing demo generates no events

### ISSUE THREAD

**Issue by dorzey** [MaterializeInc/materialize#4765]
### What version of Materialize are you using?

tags/v0.5.1

### How did you install Materialize?

* [ ] Docker image
* [ ] Linux release tarball
* [ ] APT package
* [ ] macOS release tarball
* [ ] Homebrew tap
* [X] Built from source

### What was the issue?

I am following the steps to [run the demo](https://materialize.com/docs/demos/microservice/#run-the-demo), but I never get events in the database.

### Is the issue reproducible? If so, please provide reproduction instructions.

```
git clone https://github.com/MaterializeInc/materialize.git
git checkout v0.5.1
cd ./materialize/demo/billing
./mzcompose up
```
All the services startup then I keep seeing the error message in the logs show in the section below. I have sources in my database, but no events.

```
materialize=> SHOW SOURCES;
      name
----------------
 billing_source
 price_source
(2 rows)

materialize=> SELECT jsonb_pretty(records::jsonb) AS records FROM billing_raw_data LIMIT 1;
 records
---------
(0 rows)
```

I am running
* Docker version 20.10.0-beta1, build ac365d7
* docker-compose version 1.27.4, build 40524192
* macOS Catalina 10.15.7.

### Please attach any applicable log files.

`materialized_1                | Nov 11 22:41:45.086 ERROR rdkafka::client: librdkafka: Global error: UnknownTopicOrPartition (Broker: Unknown topic or partition): billing [0]: topic does not exist (Broker: Unknown topic or partition)`

**Comment by ruchirK** [comment]
Hi @dorzey thanks for the report! I'm looking at this now

**Comment by ruchirK** [comment]
Looks like our docs are a bit out of date. You should get the behavior you want if you destroy any containers created by mzcompose (with `./mzcompose down` ) and then from the repository top level run:

```
$ bin/mzconduct up billing
```
I'll open a pr to update the docs tomorrow morning. Let me know if that doesn't work for you

**Comment by dorzey** [comment]
The error I saw has disappeared from the logs, but I still get no data into `billing_raw_data`.

The Grafana dashboard shows that nothing has been ingested. Am I missing a step to trigger the events?

<img width="1362" alt="tmp" src="https://user-images.githubusercontent.com/61307/98932166-e34ce200-24d6-11eb-9385-6aba21b808d1.png">

**Comment by ruchirK** [comment]
Apologies Paul I had also modified the `mzcompose.yml` file last night and forgot to mention that
```
diff --git a/demo/billing/mzcompose.yml b/demo/billing/mzcompose.yml
index 80754bc69..5950b16d0 100644
--- a/demo/billing/mzcompose.yml
+++ b/demo/billing/mzcompose.yml
@@ -62,6 +62,9 @@ services:
       --kafka-host kafka
       --schema-registry-url http://schema-registry:8081
       --csv-file-name /share/billing-demo/data/prices.csv
+      --create-topic
+      --replication-factor 1
+      --partitions 1
     depends_on: [kafka, schema-registry, materialized]
   dashboard:
     mzbuild: dashboard
```

this should work and I'll have a pr for this in a few hours (have had a bit of a late start today)

**Comment by ruchirK** [comment]
@dorzey I merged a PR that updates the demo mzcompose.yml and the instructions in the user doc. If you pull materialize again (to get the new mzcompose) and follow the new instructions in the doc it should work. Let me know if that doesn't work

**Comment by dorzey** [comment]
All works now. Thanks!
