### ISSUE TITLE
Create an alert against chbench for negative counts

### ISSUE THREAD

**Issue by cirego** [MaterializeInc/materialize#4767]
I'm having a hard time getting my ingest benchmark to work correctly, in part because Materialize is complaining about negative counts. Let's surface the number of "Negative count" events by dataflow / materialized view, plot the number in Grafana and alert when the number is above zero.

**Comment by cuongdo** [comment]
What's the exact error that's happening?

**Comment by cirego** [comment]
The error message is the same as seen in #4440 and I haven't figured out yet how to make it go away.

**Comment by cirego** [comment]
This was related to our handling of Postgres data. Going to mark as closed for now.

Additionally, we have #5402 open to verify Materialize view counts against the source data, which will also resolve this issue.

**Comment by cirego** [comment]
This was related to our handling of Postgres data. Going to mark as closed for now.

Additionally, we have #5402 open to verify Materialize view counts against the source data, which will also resolve this issue.
