### ISSUE TITLE
Unify mzconduct and mzcompose

### ISSUE THREAD

**Issue by quodlibetor** [MaterializeInc/materialize#4769]
`mzconduct` and `mzcompose` are both wrappers around docker-compose, with *slightly* different purposes:

* `mzcompose` adds just the `mzbuild:` key, which integrates with `bin/mzimage` to try to
  guarantee (it doesn't work with `bin/mzcompose run`, because of a docker-compose bug) that the
  current code is executed in docker images.
* `mzconduct` is higher level and allows listing and identifying any mzcompose file in the repo by
  name, and also the execution of `workflows`, which are strictly ordered steps within an
  mzcompose file.

We should be able to unify them by deleting `mzconduct` and adding `--find=NAME` and
`--workflow=WORKFLOW` flags to mzcompose that just use the existing code in mzconduct.

The way the code is currently written, `--find` won't work correctly in a subdirectory (since it
just searches through subdirectories of the current dir) but that's fine.

**Comment by benesch** [comment]
Fixed in #5072.
