### ISSUE TITLE
UX: Dropping a kafka sink does not drop the corresponding kafka topic

### ISSUE THREAD

**Issue by krishmanoh2** [MaterializeInc/materialize#4772]
As of now, dropping a sink does not drop the corresponding kafka topic. And recreating the same sink results in a new kafka topic.

We can either warn that existing topic will not be dropped or have a cascade option to drop the topic associated with the sink.

**Comment by benesch** [comment]
I'd like to stay out of the Kafka topic deletion game if possible. There are a number of wrinkles, all Kafka's fault, that make it really hard to reliably delete a Kafka topic: https://github.com/MaterializeInc/materialize/blob/7bfdf290f90e242ef62d65d87b00d0b1d872d352/src/testdrive/src/action/kafka/create_topic.rs#L95-L143

We should definitely get this documented if it isn't already.

**Comment by rjnn** [comment]
Yup, I'm with @benesch here. we should however explicitly mention this at drop time if possible.
