### ISSUE TITLE
UX: report the consistency topic name in mz_kafka_sinks

### ISSUE THREAD

**Issue by krishmanoh2** [MaterializeInc/materialize#4774]
If consistency is enabled, mz creates a new topic in kafka. This topic name is not visible in mz_kafka_sinks. We could add a new column that shows this information (if a topic was created for consistency).

**Comment by ruchirK** [comment]
The consistency topic name is always going to be `{the data topic name}-consistency` which is the behavior documented here https://materialize.com/docs/sql/create-sink/#consistency-metadata

It's not hard to add a new column for the consistency topic, but do you still feel that showing the topic name is necessary vs for example indicating `Consistency-enabled` : true / false?

**Comment by krishmanoh2** [comment]
I feel it would be useful to show the consistency topic name to make it consistent with what mz creates on the kafka side.
