### ISSUE TITLE
UX: creating a sink using with options - creates the sink but consistency clause is not applied 

### ISSUE THREAD

**Issue by krishmanoh2** [MaterializeInc/materialize#4775]
UX: creating a sink using with options - if the with clause was located not after the keyword topic - creates the sink but consistency clause is not applied

### What version of Materialize are you using?

```
$ materialized -v

materialized v0.5.2-dev (84a9121a0)

```

### How did you install Materialize?

* [ ] Docker image
* [ ] Linux release tarball
* [ ] APT package
* [ ] macOS release tarball
* [ ] Homebrew tap
* [X ] Built from source

### What was the issue?

The keyword WITH needs to be after  TOPIC to work as expected. Placing the WITH clause elsewhere does not error out, but does not work as expected (consistency topic is not created). 

The below executes successfully but does not create a consistency topic in kafka and also no transaction id in the avro messages.
materialize=> CREATE SINK "materialize"."public"."sink_top_buy_categories" FROM "materialize"."public"."mv_top_buy_categories" INTO KAFKA BROKER '192.168.1.254' TOPIC 'sink_top_buy_categories' FORMAT AVRO USING CONFLUENT SCHEMA REGISTRY 'http://192.168.1.254:8081' **WITH ("consistency" = true)** WITH SNAPSHOT AS OF "now"()

The below creates a kafka consistency topic.
materialize=>    CREATE SINK "materialize"."public"."sink_top_buy_categories" FROM "materialize"."public"."mv_top_buy_categories" INTO KAFKA BROKER '192.168.1.254' TOPIC 'sink_top_buy_categories' **WITH (consistency = true)** FORMAT AVRO USING CONFLUENT SCHEMA REGISTRY 'http://192.168.1.254:8081'  WITH SNAPSHOT AS OF "now"()
materialize-> ;
CREATE SINK

**Comment by nmeagan11** [comment]
We are refactoring the sinks syntax as part of the re-design, so closing.
