### ISSUE TITLE
UX: display parameters, versions from psql client

### ISSUE THREAD

**Issue by krishmanoh2** [MaterializeInc/materialize#4776]
Could we have some equivalent to select version() or store information in a mz view to report running version of mz?

Same for parameters - Right now, option is to see logfile or check running process.

**Comment by rjnn** [comment]
I have also tried to run `select version()` from the SQL client, this is a useful thing to have.

**Comment by benesch** [comment]
Just as a heads up `SELECT version()` has to lie and say we're PostgreSQL. But we can put the real version information in `mz_version()`.
