### ISSUE TITLE
Alert on decoding errors

### ISSUE THREAD

**Issue by cirego** [MaterializeInc/materialize#4813]
We have Grafana metrics that show how many external events we have read or attempted to read. We need to add this to our Grafana dashboard and alert on this.

```
# HELP mz_dataflow_events_read_total Count of events we have read from the wire
# TYPE mz_dataflow_events_read_total counter
mz_dataflow_events_read_total{format="avro",status="error"} 520141
mz_dataflow_events_read_total{format="avro",status="success"} 0
mz_dataflow_events_read_total{format="csv",status="error"} 0
mz_dataflow_events_read_total{format="csv",status="success"} 0
mz_dataflow_events_read_total{format="protobuf",status="error"} 0
mz_dataflow_events_read_total{format="protobuf",status="success"} 0
mz_dataflow_events_read_total{format="raw",status="error"} 0
mz_dataflow_events_read_total{format="raw",status="success"} 0
```

**Comment by cirego** [comment]
This little [Grafana explore query](https://grafana.i.mtrlz.dev/explore?orgId=1&left=%5B%22now-1h%22,%22now%22,%22Prometheus%22,%7B%22expr%22:%22sum%20by%20(status,%20format)%20(rate(mz_dataflow_events_read_total%5B5m%5D))%22,%22hide%22:false%7D,%7B%22mode%22:%22Metrics%22%7D,%7B%22ui%22:%5Btrue,true,true,%22none%22%5D%7D%5D) shows the rate of logging messages by Format and Status.

For easy reading, this is the raw Grafana query: `sum by (status, format) (rate(mz_dataflow_events_read_total[5m]))`

**Comment by benesch** [comment]
Closing as stale. We no longer have a user-facing Grafana dashboard.
