### ISSUE TITLE
Developer docs refer to inaccessible mtrlz-setup repo

### ISSUE THREAD

**Issue by petrosagg** [MaterializeInc/materialize#4815]
### What version of Materialize are you using?

```
$ materialized -v
materialized v0.5.2-dev (9a66d82a2c85246af2d04465cac03770f73593c4)
```

### How did you install Materialize?

* [ ] Docker image
* [ ] Linux release tarball
* [ ] APT package
* [ ] macOS release tarball
* [ ] Homebrew tap
* [x] Built from source

### What was the issue?
The [developer documentation](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide.md#linux) mentions running `nix-shell` to ease installation of dependencies on Linux. However, according to https://github.com/MaterializeInc/materialize/commit/15a6c46cbda221de7fa9cec8469205be315146fd, `shell.nix` was moved to the [mtrlz-setup](https://github.com/MaterializeInc/mtrlz-setup) repo which is private. The repo is also mentioned at the bottom of the developer docs.

I was able to use the old `shell.nix` to build materialize on NixOS but ideally I'd like to use the up to date development environment. If that repo  doesn't contain private information, could you make it public? I'm more than happy to fix the documentation once I get some guidance on the desired action.

**Comment by benesch** [comment]
Sorry about that, @petrosagg! We no longer support the Nix configuration file and the mtrlz-setup repository is also I believe unmaintained at this point—and it never quite worked on Linux, either. Your best bet is to just manually install Rust and optionally the Confluent Platform. I've updated the docs accordingly.

**Comment by petrosagg** [comment]
Thank you for the quick fix @benesch!
