### ISSUE TITLE
UX: Resource management controls at query level

### ISSUE THREAD

**Issue by krishmanoh2** [MaterializeInc/materialize#4819]
Basic resource management to ensure predictability in behavior and prevent run-away queries.

Query run-time - kill query if it does not complete in x seconds

Query memory usage - kill query and/or stop running dataflow if it exceed x MB in memory

Here Query can be new view creation, adhoc query or an existing dataflow that is falling behind.

**Comment by benesch** [comment]
Yep! FYI, the way you are using the term "query" is exactly the way in which we use the term "dataflow" here. Let's centralize discussion on the existing issue, #4257. I've updated the issue description there to indicate that we may want both memory limits and runtime limits.
