### ISSUE TITLE
Build step fails when rerun under CI

### ISSUE THREAD

**Issue by cirego** [MaterializeInc/materialize#4850]
Running the [Materialize / Tests / main](https://buildkite.com/materialize/tests/builds?branch=main) job fails if run more than once. It appears that the build / upload to bintray operation is not idempotent.

```
Creating Bintray version...
--
  | Uploading Debian package (65.4 MB)...
  | Traceback (most recent call last):
  | File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
  | "__main__", mod_spec)
  | File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
  | exec(code, run_globals)
  | File "/var/lib/buildkite-agent/builds/buildkite-builders-i-0ccddf105e1557b0f-1/materialize/tests/ci/test/build.py", line 116, in <module>
  | main()
  | File "/var/lib/buildkite-agent/builds/buildkite-builders-i-0ccddf105e1557b0f-1/materialize/tests/ci/test/build.py", line 43, in main
  | stage_deb(repo, "materialized-unstable", deb.unstable_version(workspace))
  | File "/var/lib/buildkite-agent/builds/buildkite-builders-i-0ccddf105e1557b0f-1/materialize/tests/ci/test/build.py", line 111, in stage_deb
  | architectures=["amd64"],
  | File "/var/lib/buildkite-agent/builds/buildkite-builders-i-0ccddf105e1557b0f-1/materialize/tests/misc/python/materialize/bintray.py", line 98, in debian_upload
  | res.raise_for_status()
  | File "/usr/local/lib/python3.6/dist-packages/requests/models.py", line 941, in raise_for_status
  | raise HTTPError(http_error_msg, response=self)
  | requests.exceptions.HTTPError: 409 Client Error: Conflict for url: https://api.bintray.com/content/materialize/apt/materialized-unstable/0.5.3-dev-8193-aebcb900340e12f735b410d63fe5e2ce777e88c5//0.5.3-dev-8193-aebcb900340e12f735b410d63fe5e2ce777e88c5/materialized-aebcb900340e12f735b410d63fe5e2ce777e88c5.deb
```

**Comment by cirego** [comment]
Looking at the code, it appears that we already try ignoring the error:

```
    try:
        print("Creating Bintray version...")
        commit_hash = git.rev_parse("HEAD")
        package.create_version(version, desc="git main", vcs_tag=commit_hash)
    except bintray.VersionAlreadyExistsError:
        # Ignore for idempotency. Bintray won't allow us to overwite an existing
        # .deb below with a file whose checksum doesn't match, so this is safe.
        pass
```

However, looking at the stacktrace, the error being raised is a `requests.exception.HTTPError`, not a `bintray.VersionAlreadyExistsError`.

**Comment by cirego** [comment]
@quodlibetor, @benesch or @umanwizard, can one of you comment on the desired behavior here? What should we do when someone reruns the Tests pipeline and the output of the binary has changed. I'm assuming we don't have reproducible builds, so my thinking is that we have a couple of options:

1. Ignore the upload failure and simply rerun the rest of the pipeline, using the previously built binary. This would work if the failed part of the pipeline was a flaky test but not if the failure was due to a bad build.
2. Delete the old binary and upload the new one. This seems unsafe.
3. Fail the pipeline, since we cannot use the binary built from this run.

**Comment by benesch** [comment]
Yeah, I think the desired behavior would be that `cargo deb` produces the same `.deb` file for the same input. The binary that's getting passed to `cargo deb`  is actually bit-for-bit identical, thanks to the way we cache things on Docker Hub, but it looks like `cargo deb` introduces all sorts of entropy into the build process.

I suppose we could just ignore the conflict—i.e., option (1) above—and skip the upload. Nothing in the rest of the pipeline depends on the `.deb`. If the build was bad the rest of the pipeline will be bricked by the Docker Hub cache anyway.
