### ISSUE TITLE
correctness testing using TPC-C checks

### ISSUE THREAD

**Issue by rjnn** [MaterializeInc/materialize#486]
TPC-C has a set of 'checks' that can be run[1], essentially invariants that must be maintained at all times. We can leverage this to check the correctness of Materialize's SQL engine, by essentially materializing views for each of the check queries, and monitoring the answers of those queries for violations when running ch-benchmark.

cc @cuongdo who I had an offline discussion about this.

[1] see https://github.com/cockroachdb/cockroach/blob/eed4a08f69b1b5860330ad471d202cc163147f1b/pkg/workload/tpcc/checks.go

**Comment by cuongdo** [comment]
Blocked by #1979, because we can't run these TPC-C checks without preserving atomicity of upstream transactions. Moving to 0.3, because #1979 is tentatively slated for 0.3.

**Comment by cuongdo** [comment]
@nacrooks Is this resolved by #3089? What is the easiest way to run the consistency checker against chbench load?

**Comment by nacrooks** [comment]
`./mzcompose run test-correctness` is how to run the checker (once chbench is running).

This will currently report inconsistent results (as in, the checker will report that some of the integrity constraints fail) while we are still loading data as ChBench runs on MySQL and Debezium does not have the transaction consistency topic. Once you shutdown the loading, the number of consistency violations should stop increasing.

**Comment by awang** [comment]
@cuongdo do you happen to remember what the final state of this was?

**Comment by nacrooks** [comment]
You can run it for both Postgres and MySQL and it'll correctly show that 1) without the consistency topic, we generate periodic inconsistencies 2) with the consistency topic we only return consistent results. Unless the mzcompose approach has changed, then the above should still work.  The demo slides I had show how to run it too.

**Comment by nacrooks** [comment]
(I realised I never replied to Cuong's message, but I do think that this was resolved by #3089.)

**Comment by awang** [comment]
👍 thanks again Natacha!!
