### ISSUE TITLE
Debian builds should be reproducible

### ISSUE THREAD

**Issue by cirego** [MaterializeInc/materialize#4862]
Our CI build takes the materialized binary out of a Docker image and creates a debian using that binary. This removes on of the potential sources of non-reproducibility from our build process. However, as #4850 shows, we do not produce the same debian if the builds are run again.

[Debian Wiki - ReproducibleBuilds](https://wiki.debian.org/ReproducibleBuilds) is a great resource for creating reproducible debians. If we can fix this, then we can also fixup #4860 to fail if the second upload fails.

**Comment by benesch** [comment]
Solved by switching to a tool that allows us to re-upload .deb files if we need to.
