### ISSUE TITLE
Large amount of memory allocated in std::panic::catch_unwind

### ISSUE THREAD

**Issue by cirego** [MaterializeInc/materialize#4864]
After running the "bad topic" test to try and reproduce #4814, I ran into another interesting heap profile. This time, nothing is going on, we've finished reading all topic data, but the heap profile shows a large amount of memory allocated to unwinding panics:

![Screenshot from 2020-11-23 11-09-20](https://user-images.githubusercontent.com/551285/100004835-ec626c80-2d7c-11eb-9e66-5e2f87237c85.png)
![Screenshot from 2020-11-23 11-08-58](https://user-images.githubusercontent.com/551285/100004837-eec4c680-2d7c-11eb-88ee-8edd45bafa12.png)

I have a heap profile as well: [jeprof.heap.txt](https://github.com/MaterializeInc/materialize/files/5585257/jeprof.heap.txt)

**Comment by umanwizard** [comment]
This is cached debug symbol data used for rendering the flamegraph. In general it will not increase (the size of the cache is limited), but will use a few hundred megs, forever, after the first time you run the flamegraph tool.

**Comment by umanwizard** [comment]
Notice that it doesn't show up the first time you generate a flamegraph, but only the second and subsequent. That's because it is used during the flamegraph processing, so in the first time, it hasn't been created yet :)

**Comment by cirego** [comment]
I see -- the `backtrace::gimli` lines at the top are the relevant parts?

**Comment by umanwizard** [comment]
Yep - that `catch_unwind` stuff is a red herring - it's just some Rust runtime thing so it will probably appear in most/all of our stack traces.

Anyway, we could do something smart, like dropping this data automatically after a few minutes of non-use. But that'd require us to fork on modify the `backtrace` library, which doesn't seem worth it to save a one-time cost of a few hundred MB.

**Comment by benesch** [comment]
Looks like there's nothing to do here!
