### ISSUE TITLE
Cannot create custom types with non-zero numeric scale

### ISSUE THREAD

**Issue by sploiselle** [MaterializeInc/materialize#4884]
In Postgres:
```
CREATE TYPE numeric_range AS RANGE (subtype = numeric(38,5));
```

In MZ:
note that the cast shown below is taken from a [branch on my fork](https://github.com/sploiselle/materialize/tree/custom-type-casts) that implements this feature)

```
materialize=> CREATE TYPE numeric_map AS MAP (key_type=text, value_type=numeric(38,2));

ERROR:  Expected right parenthesis, found left parenthesis
LINE 1: ...umeric_map AS MAP (key_type=text, value_type=numeric(38,2));

materialize=> CREATE TYPE numeric_map AS MAP (key_type=text, value_type=numeric);

CREATE TYPE

materialize=> SELECT '{a=>1.23}'::numeric_map;
 ?column?
----------
 {a=>1}
(1 row)
```

The underlying issue is that the `value_type`'s `GlobalId` refers to the generic `numeric` type, which defaults to 0 scale. And is non-configurable, anyhow.

**Comment by pH14** [comment]
I saw that `CatalogItem` very specifically aims to remove modifiers, but could it make sense for List/Map/Record to additionally store modifiers for their field types? 

https://github.com/MaterializeInc/materialize/blob/941bf2aa62198eb187d5ead66745160362ffc746/src/sql/src/catalog.rs#L336-L343

Since custom types are re-planned after reading from the catalog, it seems like we could reconstruct the modifiers needed fairly easily.

For context: as we get closer to using record types to map JSON sources, I think supporting type modifiers will become increasingly important

(cc @sploiselle @benesch)

**Comment by sploiselle** [comment]
Yeah, there's some typmod arithmetic that would let us store the typmod value of custom types, and resaturate it:
https://github.com/MaterializeInc/materialize/blob/main/src/pgrepr/src/types.rs#L446

I think the issue is a matter that no one has plumbed everything through, moreso than a technical intractability. Haven't seen folks complain about the limitation, so didn't have much impetus to improve it, but if you need it for something, I believe it can be done. Though @benesch's recall for why things haven't been done yet exceeds mine and might be good to get his nod before taking on the task.

**Comment by benesch** [comment]
So, along the lines of that ID braindump (https://www.notion.so/materialize/ID-braindump-bb2df6f1ae604998ba39507cc681652e)... `typmod`s are sort of like OIDs in that they are a PostgreSQL concept that a large part of our system tries to be oblivious to. I'm not _entirely_ sure that our catalog wants to store modifiers for a type in the same way that PostgreSQL does. Certainly we need to be able to convert our modifier representation to/from a packed `typmod` for the types that are compatible with PostgreSQL, but ... potentially want more flexibility for types under our control, too. Not sure!

**Comment by benesch** [comment]
So yeah, comes out a little cleaner to store modifiers as a `Vec<i64>` rather than a packed typmod, AFAICT! Sorry, had to actually type some code to figure it out. I put up #11164. Not planning on working on it any further, but should be a good base for someone else to run with.
