### ISSUE TITLE
Allow setting read_uncommitted for kafka sources

### ISSUE THREAD

**Issue by elindsey** [MaterializeInc/materialize#4915]
Kafka sources always `read_committed` today. For some use cases it's fine to `read_uncommitted`, but we don't currently expose that as a configuration option.

As part of this work, we should also unify how the kafka client is configured for sources and for our polling timestamp thread so they don't drift apart (related to https://github.com/MaterializeInc/materialize/pull/4912).

**Comment by awang** [comment]
@elindsey i'm moving this to a candidate for 0.7:

> that would be great, because we have a few transactional topics, which have commit markers every 1-2 minutes, but it's fine to consume uncommitted messages

**Comment by awang** [comment]
@elindsey this is the task that would help our prospect we discussed this morning

**Comment by elindsey** [comment]
One note - it is still important for the isolation level config to propagate to the timestamper for rt because it'll be used for logging the max offset to prometheus (we don't want eg. the source to be reading uncommitted but metrics to only show the max committed offset). After Ruchir's refactoring this may just work (the config is passed through `create_rt_kafka_connector`), but it's good to verify.
