### ISSUE TITLE
Memory usage profiling

### ISSUE THREAD

**Issue by umanwizard** [MaterializeInc/materialize#493]
We need, at the bare minimum, a mechanism for telling how much memory is consumed by a dataflow (source or view).

Given a particular arrangement, this is relatively simple (with some minor changes to differential). Simply walk all the batches in the trace, find all the `Vec`s (or other heap-allocated types) under them, get the raw pointer out, and ask jemalloc for the size of the allocation. There is pre-existing code by Mozilla which does a similar thing for Servo; I hacked it into differential and it seems to work.

This gets us sources out of the box. For views (which may spawn many arrangements) we would need to have each arrangement logging this information, which is a bit complicated for differential because it can't actually assume that the downstream user is using jemalloc like Materialize is. @frankmcsherry  and I have been discussing what a reasonable API is...

**Comment by ruchirK** [comment]
Is the intent of this issue covered by the memory usage visualization that @mjibson built (I know that didn't use the exact solution described in the issue)

**Comment by umanwizard** [comment]
I don't think so, as that only counts number of rows, without taking into account the size of each row.

**Comment by antiguru** [comment]
Not completely implemented, but we know for each arrangement how much memory it consumes.
