### ISSUE TITLE
copy binary with npgsql not working

### ISSUE THREAD

**Issue by mjibson** [MaterializeInc/materialize#4932]
A user reported errors `Already in the middle of a row` while using COPY BINARY. This appears to be a bug either in our production of copy binary messages or npgsql's parsing of those. Need to research.

**Comment by mjibson** [comment]
(That error message is from npgsql.)

**Comment by benesch** [comment]
I think this can also happen if you read the wrong number of columns from a row. Npgsql is pretty unhelpful there.
