### ISSUE TITLE
mz crash - Internal error: A non-Avro Debezium-envelope source should not have been created.

### ISSUE THREAD

**Issue by krishmanoh2** [MaterializeInc/materialize#4941]
mz version - 0.5.2

Installed from tar ball.

Creating a kafka source with envelope debezium but with json instead of avro causes a crash.

mz> create source testdb_public_test from kafka broker 'kafka:8092' topic 'testdb.public.test' format BYTES envelope debezium;
CREATE SOURCE
Time: 0.003s
mz> create materialized view testdb_public_test_json as select cast (data as jsonb) as data from (select convert_from(data, 'utf8') as data from testdb_public_test);
CREATE VIEW
Time: 0.005s
mz> Exception in thread completion_refresh:
Traceback (most recent call last):
<snip python stack trace>
psycopg2.OperationalError: server closed the connection unexpectedly
    This probably means the server terminated abnormally
    before or while processing the request.
Server side:
materialized v0.5.2 (58333a7e8) listening on 0.0.0.0:6875...
Dec 02 17:12:35.294 ERROR panic: timely:work-0: internal error: entered unreachable code: Internal error: A non-Avro Debezium-envelope source should not have been created.
   0: materialized::handle_panic
             at /var/lib/buildkite-agent/builds/buildkite-builders-i-0c0231b1f2bdc4566-1/materialize/tests/src/materialized/src/bin/materialized/main.rs:545:65
   1: core::ops::function::Fn::call
             at /usr/local/lib/rustlib/src/rust/library/core/src/ops/function.rs:70:5
   2: std::panicking::rust_panic_with_hook
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:573:17
   3: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:476:9
   4: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/sys_common/backtrace.rs:153:18
   5: rust_begin_unwind
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:475:5
   6: std::panicking::begin_panic_fmt
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:429:5
   7: dataflow::decode::decode_values
             at /var/lib/buildkite-agent/builds/buildkite-builders-i-0c0231b1f2bdc4566-1/materialize/tests/src/dataflow/src/decode/mod.rs:564:39
   8: dataflow::render::<impl dataflow::render::context::Context<timely::dataflow::scopes::child::Child<G,<G as timely::dataflow::scopes::ScopeParent>::Timestamp>,expr::relation::RelationExpr,repr::row::Row,u64>>::import_source
             at /var/lib/buildkite-agent/builds/buildkite-builders-i-0c0231b1f2bdc4566-1/materialize/tests/src/dataflow/src/render/mod.rs:433:53
   9: dataflow::render::build_dataflow::{{closure}}::{{closure}}
             at /var/lib/buildkite-agent/builds/buildkite-builders-i-0c0231b1f2bdc4566-1/materialize/tests/src/dataflow/src/render/mod.rs:202:17
      <timely::dataflow::scopes::child::Child<G,T> as timely::dataflow::scopes::Scope>::scoped
             at /cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/a025087/timely/src/dataflow/scopes/child.rs:124:13
      timely::dataflow::scopes::Scope::region_named
             at /cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/a025087/timely/src/dataflow/scopes/mod.rs:187:9
      timely::dataflow::scopes::Scope::region
             at /cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/a025087/timely/src/dataflow/scopes/mod.rs:155:9
  10: dataflow::render::build_dataflow::{{closure}}
             at /var/lib/buildkite-agent/builds/buildkite-builders-i-0c0231b1f2bdc4566-1/materialize/tests/src/dataflow/src/render/mod.rs:188:9
      timely::worker::Worker<A>::dataflow_core
             at /cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/a025087/timely/src/worker.rs:442:13
  11: dataflow::render::build_dataflow
             at /var/lib/buildkite-agent/builds/buildkite-builders-i-0c0231b1f2bdc4566-1/materialize/tests/src/dataflow/src/render/mod.rs:183:5
  12: dataflow::server::Worker<A>::handle_command
             at /var/lib/buildkite-agent/builds/buildkite-builders-i-0c0231b1f2bdc4566-1/materialize/tests/src/dataflow/src/server.rs:591:21
  13: dataflow::server::Worker<A>::run
             at /var/lib/buildkite-agent/builds/buildkite-builders-i-0c0231b1f2bdc4566-1/materialize/tests/src/dataflow/src/server.rs:488:17
  14: dataflow::server::serve::{{closure}}::{{closure}}
             at /var/lib/buildkite-agent/builds/buildkite-builders-i-0c0231b1f2bdc4566-1/materialize/tests/src/dataflow/src/server.rs:231:13
      tokio::runtime::context::enter
             at /cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/runtime/context.rs:72:5
  15: tokio::runtime::handle::Handle::enter
             at /cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/runtime/handle.rs:76:9
      dataflow::server::serve::{{closure}}
             at /var/lib/buildkite-agent/builds/buildkite-builders-i-0c0231b1f2bdc4566-1/materialize/tests/src/dataflow/src/server.rs:225:9
      timely::execute::execute_from::{{closure}}
             at /cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/a025087/timely/src/execute.rs:299:22
      timely_communication::initialize::initialize_from::{{closure}}
             at /cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/a025087/communication/src/initialize.rs:269:33
      std::sys_common::backtrace::__rust_begin_short_backtrace
             at /usr/local/lib/rustlib/src/rust/library/std/src/sys_common/backtrace.rs:137:18
  16: std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}}
             at /usr/local/lib/rustlib/src/rust/library/std/src/thread/mod.rs:458:17
      <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /usr/local/lib/rustlib/src/rust/library/std/src/panic.rs:308:9
      std::panicking::try::do_call
             at /usr/local/lib/rustlib/src/rust/library/std/src/panicking.rs:373:40
      std::panicking::try
             at /usr/local/lib/rustlib/src/rust/library/std/src/panicking.rs:337:19
      std::panic::catch_unwind
             at /usr/local/lib/rustlib/src/rust/library/std/src/panic.rs:379:14
      std::thread::Builder::spawn_unchecked::{{closure}}
             at /usr/local/lib/rustlib/src/rust/library/std/src/thread/mod.rs:457:30
      core::ops::function::FnOnce::call_once{{vtable.shim}}
             at /usr/local/lib/rustlib/src/rust/library/core/src/ops/function.rs:227:5
  17: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/alloc/src/boxed.rs:1042:9
      <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/alloc/src/boxed.rs:1042:9
      std::sys::unix::thread::Thread::new::thread_start
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/sys/unix/thread.rs:87:17
  18: start_thread
  19: __clone
    
materialized encountered an internal error and crashed.

**Comment by krishmanoh2** [comment]
@umanwizard

**Comment by umanwizard** [comment]
Indeed, we don't support debezium over JSON yet. We should do something better than crash, though.
