### ISSUE TITLE
Support setting custom offsets for Kafka based sources

### ISSUE THREAD

**Issue by andrioni** [MaterializeInc/materialize#4948]
It would be nice to be able to set custom starting offsets when creating new Kafka-based sources for cases when the topic has too much history that might not be completely relevant.

Ideally these offsets should be defined similarly to the [Kafka application reset tool](https://kafka.apache.org/documentation/streams/developer-guide/app-reset-tool.html): by either absolute or relative offset or (more importantly) absolute or relative timestamps.

One example of why this is useful: I have a very large Kafka topic with about 10TB of data for 30 days of retention, and even on an `r5.16xlarge` with 31 workers it still takes over one hour to go through the entire topic, but I could use only the last one or two days of data for most views without causing any impact on my service.

Some overlap with #1577, which talks about exposing message-based timestamps.

**Comment by rjnn** [comment]
thanks @andrioni. 

@umanwizard can we get an effort size estimate here? This isn't the first time this request has come up.

**Comment by maqroll** [comment]
Also would be nice to be able to start processing on a specific timestamp. In my use case we provide certain metrics over last-N minutes window. Being able to start processing from N minutes ago is better than earliest or latest strategy.

**Comment by umanwizard** [comment]
This is working now for envelopes other than debezium (for which it is impossible; and `DEBEZIUM UPSERT` should be used instead, if the memory overhead for that is acceptable)

**Comment by umanwizard** [comment]
https://materialize.com/docs/sql/create-source/text-kafka/#partition-offsets
