### ISSUE TITLE
Persist history for a materialized view so that a program can retrieve information asynchronously

### ISSUE THREAD

**Issue by krishmanoh2** [MaterializeInc/materialize#4981]
When building an app, I had a view that returns a single row without any time-component. If I need to track the changes to this value over-time, it is difficult to do as out of the box. 

KSQL offers this ability today with RETENTION clause.

https://docs.ksqldb.io/en/latest/concepts/time-and-windows-in-ksqldb-queries/

This is extremely useful when you want to display such data in a dashboard.  This will allow for tracking trends (timeseries data).

This will also allow for a program to be able to retrieve these changes without needing a persistent sync connection to mz.

**Comment by rjnn** [comment]
this is basically the option to preserve the ability to query a view `AS OF` a time in the past. So locking in the ability to make historical reads on that view.

**Comment by rjnn** [comment]
It's not related to tail.

**Comment by krishmanoh2** [comment]
to give an example - 

create materialized view test1 as select <> -- returns 1 column.

The ask is the below behavior - 

select * from test1;
<last_updated_timestamp> <value>

sleep 10 and assuming that test1 has been updated x times in past 10 seconds

select * from test1;
<last_updated_timestamp1> <value>
<last_updated_timestamp2> <value2>
<last_updated_timestampx> <valuex>

We have the ability to see all updated timestamps upto RETENTION period.

**Comment by benesch** [comment]
Pretty sure it is related to `TAIL`. At the very least, it doesn’t make sense for `SELECT` to return rows reflecting results at multiple times as described above.

In fact I believe this is just `TAIL ... AS OF` coupled with a suitably large logical compaction window.

**Comment by benesch** [comment]
Once we support `TAIL ... UNTIL` (https://github.com/MaterializeInc/materialize/issues/2821) then I don’t believe there is anything else to do.

**Comment by elindsey** [comment]
Letting 2821 track this
