### ISSUE TITLE
COPY - CSV output as option

### ISSUE THREAD

**Issue by krishmanoh2** [MaterializeInc/materialize#4982]
Copy command in mz allows you to write to stdout only. CSV looks to be not enabled currently.

krmanoha=> copy (select * from mv_src_sub_category_dim a join mv_src_item_dim b on a.sub_category_id = b.sub_category_id) to '/data/sample_data/item_dim_n.out';
ERROR:  Expected STDOUT, found string literal
LINE 1: ...im b on a.sub_category_id = b.sub_category_id) to '/data/sam...

Having CSV option allows for several possibilities.

It is an easy way to do QA on data. I ran into this problem when building an application. I could not easily extract the data out from mz to validate it. It also allows you to port data to other environments.

CSV is an option that is available with other data management products.

**Comment by rjnn** [comment]
Seems easy enough but low priority. At some point we'll want to broaden the COPY formats/envelopes just as we are currently pushing to broaden the SOURCe formats/envelopes, at which point we can triage this.

**Comment by andrioni** [comment]
Related to #3692
