### ISSUE TITLE
DOCS: Explain clearly the difference between now() and mz_logical_timestamp

### ISSUE THREAD

**Issue by krishmanoh2** [MaterializeInc/materialize#4983]
The current documentation does not state why I would need to use mz_logical_timestamp.

From docs - 

mz_logical_timestamp() -> numeric
The logical time at which a query executes.

now() -> timestamptz
The timestamptz representing when the query was executed.

It may be better to also consider renaming mz_logical_timestamp to mz_query_timestamp. This would make it more intuitive.

**Comment by morsapaes** [comment]
Addressed in [this](https://materialize.com/docs/sql/functions/now_and_mz_logical_timestamp/#main) docs page, @krishmanoh2 . Closing the issue!
