### ISSUE TITLE
UX: Allow specifying latest or earliest offset for a kafka source

### ISSUE THREAD

**Issue by krishmanoh2** [MaterializeInc/materialize#4986]
Right now, mz will grab the data from the earliest available offset. It would be preferable to have the ability to specify the latest or earliest offset or even a specific offset. A simple application of this capability - This allows a customer to test data in kafka easily. 

In my experience, most products in the streaming space offer this capability - druid, memsql etc.

**Comment by rjnn** [comment]
Dup #4948. Agreed that this is very useful.
