### ISSUE TITLE
UX - When creating an MV, provide the ability to wait for mv to complete  before returning to user

### ISSUE THREAD

**Issue by krishmanoh2** [MaterializeInc/materialize#4987]
Currently, when an MV is created, the prompt is returned back to the user immediately. This gives the impression that the MV is ready to go. In reality, it would be processing the data and it may take time to catch up.

Having the ability to specify wait and display a progress bar to complete would allow a developer to know as below 

1. The MV is up-to-date and ready to go as of that point in time when it was created. 

2. Set expectations as regards the cost of the MV and also how long it may take to be populated on a restart (some time indication).

3. If the MV is taking a long time, allow the user to abort the MV and figure out the problem.

**Comment by rjnn** [comment]
This is a great point. Might be useful for SELECTS as well.

**Comment by rjnn** [comment]
That said, I think it can be tricky to create blocking DDL commands, as I'm not sure whether cancellation is cleanly possible to tear down the dataflow mid-construction. This would require some delicate dataflow work, so while I agree with the UX issue, it may not be immediately actionable.

**Comment by benesch** [comment]
I 100% agree we have an observability problem at the moment. It's not easy to determine whether your view is up-to-date—and if it's not, _why_ it's not.

The challenge here is not in making `CREATE MATERIALIZED VIEW` block. There is actually prior art for that. `CREATE SINK` blocks, for example, until it can create the topic in Kafka. 

The challenge is that we don't know what to block _for_. With our current "realtime" timestamping approach, the view is in fact perfectly up to date at the moment it is created. It's just that at timestamp `now()`, the view is defined to have zero data. At some point in the future it will have more data, but there is no way to pick a good timestamp to wait for. 

I'm also not convinced that `CREATE MATERIALIZED VIEW` should block. That seems like it would be annoying if you wanted to create a bunch of views in one shot at startup.

I'd advocate instead for additional progress visualizations in the web interface, or some sort of `SHOW PROGRESS` command that is accessible from the CLI.

**Comment by frankmcsherry** [comment]
Almost certainly related: https://github.com/MaterializeInc/materialize/issues/2310

**Comment by antiguru** [comment]
I implemented a variant that allows users to observe the progress of the initial data loading using the system catalog: #7265. I'll go ahead an unassign myself.

**Comment by benesch** [comment]
We have a better understanding of this now; closing in favor of real-time recency: #11531.
