### ISSUE TITLE
mzconduct generating "WARNING: unknown env var" messages

### ISSUE THREAD

**Issue by cirego** [MaterializeInc/materialize#5022]
When running mzcompose, I get the following error messages:

```
C> WARNING: unknown env var 'DEFAULT_PROGRESS_MODE'
C> WARNING: unknown env var 'API_KEY'
C> WARNING: unknown env var 'ARCHIVE_PATH'
```

Looking at `ARCHIVE_PATH` for example, it's only present in the `play/mbta` demo:

```
play/mbta/doc/mbta-setup.md
88:`ARCHIVE_PATH=<insert_path_archive> ../../bin/mzconduct run mbta -w replay`. Do not uncompress
the archive.

play/mbta/mzcompose.yml
72:          ${ARCHIVE_PATH}
```

However, this message prints even when running `mzconduct` for other workflows:

```
[chris-work:~/materialize/materialize:(wikirecent-demo[|])] ./bin/mzconduct web wikirecent app
C> WARNING: unknown env var 'DEFAULT_PROGRESS_MODE'
C> WARNING: unknown env var 'API_KEY'
C> WARNING: unknown env var 'ARCHIVE_PATH'
```

Should we make this an error message? Should I be getting this warning message even when running other
workflows or should we only print this message if it's the current workflow?

@quodlibetor, thoughts?

**Comment by benesch** [comment]
For posterity, the plan here is to eventually reject environment variables in mzcompose.yml and force everything to go through the new CLI flag-based infrastructure.
