### ISSUE TITLE
Materialize failing to read all messages from a Kafka topic

### ISSUE THREAD

**Issue by cirego** [MaterializeInc/materialize#5024]
Our `chbench` snapshot demo waits for `mz_source_info` to show that Materialized has reached a
specific offset before then verifying that the view matches the snapshot view. However, it appears
that Materialize is never reaching the specified offset:

For example, I have the following topic with 100,000 messages:

```
[chris-work] kafkacat -C -b 127.0.0.1:9092 -t
"debezium.tpcch.item" -f 'Topic %t [%p] at offset %o\n' -e | tail -n 1
% Reached end of topic debezium.tpcch.item [0] at offset 100000: exiting
Topic debezium.tpcch.item [0] at offset 99999
```

However, reading source info, we see that Materialize has only read 99,564 messages:

```
materialize=> select * from mz_source_info;
     source_name     | source_id | dataflow_id | partition_id | offset |   timestamp   
---------------------+-----------+-------------+--------------+--------+---------------
 debezium.tpcch.item | u2        |          22 | 0            |  99564 | 1607840663001
(1 row)
```

This prevents our benchmark from completing, as Materialize never reaches the end of the topic.

**Comment by cirego** [comment]
I have  a branch where I can run this against a released version of Materialized and I appear to be running into the same issue. The problem now appears to be that the counts are not matching. I'm going to try an experiment where I modify the logic to measure time to catch up to the offset and then fail the overall benchmark if the counts do not match.

**Comment by cuongdo** [comment]
@umanwizard please triage

**Comment by umanwizard** [comment]
@elindsey is it possible mz_source_info is wrong here?

**Comment by elindsey** [comment]
Looking into this. I see a way for mz_source_info to be incorrect under some conditions. Rather than try to patch it I'm just going to refactor some of this sources logic, it's super messy.

**Comment by elindsey** [comment]
The refactor/bugfix was merged. I'm not sure if the bug I fixed was the bug you were hitting or a different one, and I noticed you have PR 5064 up - let me know if after yours and my PR you're still seeing this. 🙂

**Comment by cirego** [comment]
> The refactor/bugfix was merged. I'm not sure if the bug I fixed was the bug you were hitting or a different one, and I noticed you have PR 5064 up - let me know if after yours and my PR you're still seeing this.

@elindsey Thanks for the quick response. I am no longer seeing this issue after fixing #5064.
