### ISSUE TITLE
Create benchmark to test ingest performance using FORMAT BYTES

### ISSUE THREAD

**Issue by cirego** [MaterializeInc/materialize#5052]
After talking with @umanwizard , if we believe that Avro decoding is slow, then we should try creating
a source that uses the `FORMAT BYTES` option instead of `FORMAT AVRO ...`. We can measure the
performance of just reading from a source and see how it compares with the results where we are
decoding Avro.

**Comment by benesch** [comment]
Covered by Philip's feature benchmark framework.
