### ISSUE TITLE
complete the Materialize dbt adapter

### ISSUE THREAD

**Issue by JLDLaughlin** [MaterializeInc/materialize#5086]
[dbt (data build tool)](https://docs.getdbt.com/docs/introduction) is a tool for analytics engineers to easily create, update, and test views on top of their data living in some arbitrary data warehouse. dbt connects to those data warehouses via adapters, some of which are builtin and others of which are created and maintained by the community.

@jwills created the [Materialize dbt adapter](https://github.com/MaterializeInc/dbt-materialize) last February (thank you @jwills!). The goal of this issue is to complete that adapter. The adapter will be considered complete when it passes all of the [dbt adapter test suite tests](https://github.com/fishtown-analytics/dbt-adapter-tests). 

Issues listed in comments here come from failed test suite runs.

**Comment by JLDLaughlin** [comment]
support CTEs in `CREATE VIEW` statements, like:
```
materialize=> create view my_view as (with my_cte as (select 1) select * from my_cte);
ERROR:  unknown catalog item 'my_cte'
```

@sploiselle, @benesch: is this something we'd want to support?

**Comment by benesch** [comment]
100%! I'm surprised it doesn't already work, to be honest.

**Comment by JLDLaughlin** [comment]
another blocker! https://github.com/MaterializeInc/materialize/issues/5096

**Comment by JLDLaughlin** [comment]
support [`upper` string function](https://www.postgresql.org/docs/8.1/functions-string.html)

**Comment by JLDLaughlin** [comment]
I accidentally duplicated this! Moving to the new issue that has a more up-to-date description: https://github.com/MaterializeInc/materialize/issues/5462
