### ISSUE TITLE
Kafka sources overload low id workers

### ISSUE THREAD

**Issue by frankmcsherry** [MaterializeInc/materialize#5088]
Kafka sources currently assign responsibility for topic parts round robin, according to `part_id % workers == worker_id`. This results in consistently skewed assignment, where small id workers can be overwhelmed. In particular, if all sources are single-part topics, worker zero will perform all of the work. This has been observed in practice.

We should better distribute responsibility for parts across workers, perhaps with a random offset to the round-robin scheme.

**Comment by cirego** [comment]
How do you want to balance load when topics have multiple partitions? Adding a random offset is a good start and should reduce the likelihood that a single worker is overwhelmed with too many topics.

It seems to me that we want something conceptually similar to cuckoo hashing for all topics and all partitions to ensure that every worker is reading at least one partition before any worker is asked to read two partitions.
