### ISSUE TITLE
grafana - show OS specs - OS version, CPU count, Physical Memory, Swap configured on system in mz details panel 

### ISSUE THREAD

**Issue by krishmanoh2** [MaterializeInc/materialize#5093]
Adding this information along with the mz build details will help understand the environment better.

**Comment by awang** [comment]
@quodlibetor is this something we can easily do?  i'm loathe to put much work into grafana, as we should do it in our own systems instead (both "flare" as well as the cloud product UI)

**Comment by quodlibetor** [comment]
Yeah we can get this. Everything that goes into grafana is actually just prometheus, and so will be forward compatible any any other metrics collection service we use.
