### ISSUE TITLE
source caching - stops writing to disk with error on pending records

### ISSUE THREAD

**Issue by krishmanoh2** [MaterializeInc/materialize#5095]
> !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
                                WARNING!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Starting Materialize in experimental mode means:
- This node's catalog of views and sources are unstable.
If you use any version of Materialize besides this one, you might
not be able to start the Materialize node. To fix this, you'll have
to remove all of Materialize's data (e.g. rm -rf mzdata) and start
the node anew.
- You must always start this node in experimental mode; it can no
longer be started in non-experimental/regular mode.
For more details, see https://materialize.com/docs/cli#experimental-mode
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
materialized v0.5.2-dev (0cbb6c85b) listening on 0.0.0.0:6875...
Nov 13 07:26:40.626  WARN dataflow::source::kafka: Kafka message before expected offset: source kafka-u2/20 (reading topic user_behavior, partition 0) received Mz offset 1 expected Mz offset 19945    
Nov 13 07:26:40.675  WARN dataflow::source::kafka: We did not seek to the expected Kafka offset. Current Kafka offset: 1 Expected Kafka offset: 19944    
Nov 13 07:26:40.675  WARN dataflow::source::kafka: Kafka message before expected offset: source kafka-u2/22 (reading topic user_behavior, partition 0) received Mz offset 1 expected Mz offset 19945    
Nov 13 07:26:40.740  WARN dataflow::source::kafka: We did not seek to the expected Kafka offset. Current Kafka offset: 1 Expected Kafka offset: 19944    
Nov 13 07:26:40.740  WARN dataflow::source::kafka: Kafka message before expected offset: source kafka-u2/24 (reading topic user_behavior, partition 0) received Mz offset 1 expected Mz offset 19945    
Nov 13 07:26:40.788  WARN dataflow::source::kafka: We did not seek to the expected Kafka offset. Current Kafka offset: 1 Expected Kafka offset: 19944    
Nov 13 07:26:40.788  WARN dataflow::source::kafka: Kafka message before expected offset: source kafka-u2/26 (reading topic user_behavior, partition 0) received Mz offset 1 expected Mz offset 19945    
Nov 13 07:26:40.854  WARN dataflow::source::kafka: We did not seek to the expected Kafka offset. Current Kafka offset: 1 Expected Kafka offset: 19944    
Nov 13 07:26:41.789  WARN dataflow::source::kafka: Kafka message before expected offset: source kafka-u2/20 (reading topic user_behavior, partition 1) received Mz offset 1 expected Mz offset 14302    
Nov 13 07:26:41.789  WARN dataflow::source::kafka: We did not seek to the expected Kafka offset. Current Kafka offset: 1 Expected Kafka offset: 14301    
Nov 13 07:26:41.839  WARN dataflow::source::kafka: Kafka message before expected offset: source kafka-u2/22 (reading topic user_behavior, partition 1) received Mz offset 1 expected Mz offset 14302    
Nov 13 07:26:41.890  WARN dataflow::source::kafka: We did not seek to the expected Kafka offset. Current Kafka offset: 1 Expected Kafka offset: 14301    
Nov 13 07:26:41.891  WARN dataflow::source::kafka: Kafka message before expected offset: source kafka-u2/24 (reading topic user_behavior, partition 1) received Mz offset 1 expected Mz offset 14302    
Nov 13 07:26:41.953  WARN dataflow::source::kafka: We did not seek to the expected Kafka offset. Current Kafka offset: 1 Expected Kafka offset: 14301    
Nov 13 07:26:41.954  WARN dataflow::source::kafka: Kafka message before expected offset: source kafka-u2/26 (reading topic user_behavior, partition 1) received Mz offset 1 expected Mz offset 14302    
Nov 13 07:26:42.003  WARN dataflow::source::kafka: We did not seek to the expected Kafka offset. Current Kafka offset: 1 Expected Kafka offset: 14301    
Nov 13 07:26:47.895 ERROR coord::persistence: Caching thread encountered error: failed to flush enough for source u2. Currently 102401 pending but max allowed is 102400    
Nov 13 07:26:47.895 ERROR coord::persistence: All cached sources on this process will not continue to be cached.

Offsets as in Kafka 

[mz@compute2 confluent-6.0.0]$ ./list_offset.sh user_behavior
user_behavior:0:4182286
user_behavior:1:4182287
user_behavior:2:4182287
user_behavior:3:4182287
user_behavior:0:0
user_behavior:1:0
user_behavior:2:0
user_behavior:3:0

**Comment by krishmanoh2** [comment]
@ruchirK  - as we discussed

**Comment by ruchirK** [comment]
closing this because source caching was removed in #7328 (we're going to go a different direction with the persist crate)
