### ISSUE TITLE
UX: show source caching if enabled in mz_sources

### ISSUE THREAD

**Issue by krishmanoh2** [MaterializeInc/materialize#5127]
mz_sources does not show you if source caching is enabled/disabled today. It looks like the only way to determine is to check the DDL. 

Can we show if enabled/disabled and other related information pertaining to caching (number of records to cache, if caching has failed and why) in mz_sources?

**Comment by ruchirK** [comment]
closing this because source caching was removed in #7328 (we're going to go a different direction with the persist crate)
