### ISSUE TITLE
Avoid using reserved keywords as column names in internal relations

### ISSUE THREAD

**Issue by cirego** [MaterializeInc/materialize#5129]
As an example, `mz_source_info` uses `offset` as a column name. This means that queries to select `offset` must use double-quotes or the `mz_source_fino.offset` to parse correctly.

Let's try to avoid using reserved keywords as column names in our internal relations.

**Comment by chaas** [comment]
The reported column no longer exists.
According to our keywords file, these are the truly reserved keywords
https://github.com/MaterializeInc/materialize/blob/main/src/sql-parser/src/keywords.rs#L74-L76
I'm not seeing any of these being used as system table column names currently.

Do we want to use the full list of recommended keywords to avoid? @benesch 
https://github.com/MaterializeInc/materialize/blob/main/src/sql-parser/src/keywords.txt
This would involve changing all columns named `id`, `type`, and `size` among others.

**Comment by benesch** [comment]
> I'm not seeing any of these being used as system table column names currently.

Me neither!

> Do we want to use the full list of recommended keywords to avoid? @benesch

Oh, definitely not! "Reserved keywords" are the ones that matter, because those are the ones that you can't use in names. As long as we're not using those anywhere (and we're not, AFAICT), we're good here!

Calling this one done.
