### ISSUE TITLE
Wrong result: scalar subqueries are allowed to return more than 1 row

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#5219]
### What version of Materialize are you using?

```
$ materialized -v
v0.6.0 (9ed7c170f)
```

### How did you install Materialize?

* [ ] Docker image

### What was the issue?

Scalar subqueries are allowed to return more than one row, which makes the result of the entire query incorrect. An error should have been returned instead.

### Is the issue reproducible? If so, please provide reproduction instructions.

````
philips=> create table t1 (f1 integer);
CREATE TABLE
philips=> insert into t1  values (1),(2);
INSERT 0 2
philips=> select 1, (select * from t1) from t1;
 ?column? | f1 
----------+----
        1 |  1
        1 |  1
        1 |  2
        1 |  2
(4 rows)
{code}

**Comment by rjnn** [comment]
Thanks for the bug report! Not sure how this slipped up unreplied for a couple weeks, perhaps we should have some kind of triage-bot (@awang)? Assigned to @benesch for the time being only because I'm not sure what the semantics should be.

**Comment by benesch** [comment]
Ah, yeah, I can't find the source for this, but this is presently intentional. It wasn't clear at the time decorrelation was implemented how to error if the subquery returned more than one row. I think it's more clear now, though perhaps still an irritating dataflow operator to have to write/install into query plans.

**Comment by frankmcsherry** [comment]
I may be oversimplifying, but it seems like it is a `Reduce` with the subquery keys and a count aggregation, then a `Filter` looking for counts greater than one, then a `Map` with an `Err(whatever)`?

Like, in SQL it would be 
```sql
SELECT key1, key2, .. , Err("whatever")
FROM subquery
GROUP BY key1, key2, ...
HAVING count(*) > 1
```
Most of the decorrelated subqueries conclude with a grouping operator, so grafting this on seems probably not too hard?

**Comment by benesch** [comment]
So, yeah, rewriting that slightly to

```sql
SELECT mkerr("subquery more than one row")
FROM <subquery>
GROUP BY key1, key2, ...
HAVING count(*) > 1
```

gets you a relation that will either have no rows or one row containing an error. What's not so clear to me is how to actually graft that onto the query so that you get _either_ the row with the data you want _or_ the error. I guess something like this?

```
SELECT mkerr("subquery more than one row")
FROM <subquery>
GROUP BY key1, key2, ...
HAVING count(*) > 1
UNION
<subquery>
```

That... would probably just work? Unclear to me what the performance cost of that would be though.

I think the way it works in Cockroach (cc @justinj) is that they have a `Max1Row` node that they can drop into their `RelationExpr` equivalent around every subquery.

**Comment by frankmcsherry** [comment]
UNION ALL would be zero overhead. I think the plan ends up being
```
outer.join(inner).union_all(inner.flat_map())
```
Adding a new operator to do the same thing that an existing operator does seems not great.

**Comment by frankmcsherry** [comment]
Or even, if the count is part of the aggregate, then just doing the join as normal, and erroring afterwards:
```
outer.join(inner_with_count).map(|...| error_if_count_big)
```

**Comment by frankmcsherry** [comment]
Ah, wait, the problem is that no one is actually doing the group by in the first place. Yeah, it's probably expensive and stuff. SQL should be better.

**Comment by frankmcsherry** [comment]
I have a WIP fix for this that I'll PR, but it is a bit hard to test because
```
thread 'main' panicked at 'internal error: failed to load bootstrap view:
pg_type
error:
more than one record produced in subquery', src/coord/src/catalog.rs:633:29
```

**Comment by benesch** [comment]
Hah! I can fix that up if you like.

**Comment by frankmcsherry** [comment]
It's over in https://github.com/MaterializeInc/materialize/pull/5651

**Comment by benesch** [comment]
Yeah I'm lookin!

**Comment by frankmcsherry** [comment]
This reminds me: I think the branch_key optimization has a bug, in that it eagerly computes some subquery results that it may not return, and then uses a semijoin to select them out. If any of those results would error and then not be returned, we will still error whereas strict subquery evaluation would not.

**Comment by benesch** [comment]
Yeah, so I'm not actually seeing that subquery generate more than one row. On main the following query returns counts of only one or zero:

```
SELECT *, (SELECT
count(t.oid)
FROM
mz_catalog.mz_array_types AS a
JOIN mz_catalog.mz_types AS t ON a.type_id = t.id
WHERE
a.element_id = mz_types.id) FROM mz_types
```

**Comment by benesch** [comment]
Reassigning this to Frank to capture that he put up the draft implementation for this: #5651.

**Comment by frankmcsherry** [comment]
The work in https://github.com/MaterializeInc/materialize/pull/5651 has stalled due (imo) to a lack of specification around what should happen with errors. I'm happy to consult should someone want to pick this up in the future, but I'm unassigning myself.

**Comment by philip-stoev** [comment]
Yes, this is now fixed and tests to that effect have been pushed. Closing.
