### ISSUE TITLE
SQL semantics of trailing spaces not observed during comparison operations

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#5258]
### What version of Materialize are you using?

```
$ materialized -v
materialized v0.6.0 (9ed7c170f) 
```

### How did you install Materialize?

* [ ] Built from source

### What was the issue?

Trailing spaces have unique semantics in SQL -- during comparisons, they should basically be disregarded (the SQL standard I believe has a more verbose description as to how exactly the arguments to a comparison operation need to be padded)

### Is the issue reproducible? If so, please provide reproduction instructions.

In Materialize:

```
CREATE TABLE t1 (f1 CHAR(5));
insert into t1 values ('a'),('a '),('a  ');
select f1 from t1 where f1 = 'a ';

 f1 
----
 a 
(1 row)
```

Only the row with "a" and 1 trailing space is matched. Contrast with Postgresql:

```
postgres=# select * from t1 where f1 = 'a ';
     f1     
------------
 a         
 a         
 a         
(3 rows)

````
All 3 rows are returned, with 0 to 2 trailing spaces, as demanded by the standard.

**Comment by benesch** [comment]
Thanks for another great report, @philip-stoev! It looks like the `CREATE TABLE` got cut off, though. Is `f1` a column of type `char`? If so, yeah, we're unfortunately known not to support the `char` type. We've got an open issue for removing it, actually: #5169.

**Comment by philip-stoev** [comment]
I fixed the CREATE TABLE statement. The issue is also reproducible with TEXT.

**Comment by benesch** [comment]
> The issue is also reproducible with TEXT.

Hmm, are you sure on this point? PostgreSQL does not apply the strange trailing space comparison semantics to its `text` type, as far as I can tell:

```
benesch=> create table t1 (f1 text);
CREATE TABLE
benesch=> insert into t1 values ('a'),('a '),('a  ');
INSERT 0 3
benesch=> select f1 from t1 where f1 = 'a ';
 f1 
----
 a 
(1 row)

benesch=> 
```

**Comment by philip-stoev** [comment]
Sorry, I meant that the issue is reproducible with TEXT in Materialize, so silently converting CHAR to TEXT or forcing the users to use TEXT is going to change the semantics for previously-CHAR data.

This one is an actual real-life problem that has been hit by production customers of other database products. Mainframe-age data has such trailing spaces all over the place and many legacy queries have been written out there that expect that the database will do the right thing.

**Comment by benesch** [comment]
Ah, yep, then we're totally on the same page! The current plan is to delete the `char` type until we're ready to support it, but as you say folks who have already used the `char` type will be stuck with the wrong behavior. :/

**Comment by justinj** [comment]
Is "trailing spaces" the right classification of this issue? I think it's more about the `CHAR` type overall, right? Postgres has this behaviour, for instance:
```
postgres=# select 'ab'::char = 'a'::char;
 ?column?
----------
 t
(1 row)
```

**Comment by philip-stoev** [comment]
@justinj I think your example is a different thing. CAST-ing to CHAR without a length specified seems to default to ```CHAR(1)``` so both sides of your comparison are ```'a'``` so they are indeed equal to one another.

```
pstoev=# select 'ab'::char;
 bpchar 
--------
 a
(1 row)

pstoev=# select 'ab'::char(2);
 bpchar 
--------
 ab
(1 row)
```

(This is not the case in Materialize, which is I guess a different issue)

**Comment by justinj** [comment]
This still strikes me as not about the comparison semantics, but about the datatype itself, `CHAR(n)` in postgres is a fixed-length string, so `'a'` when cast to a CHAR(5) is stored as `'a    '`, but maybe that's splitting hairs?

**Comment by benesch** [comment]
On the bright side, I think the fix here is "implement the `char` type" no matter which way you slice the description of this issue.
