### ISSUE TITLE
mzbuild rebuild logic doesn't work for new directories

### ISSUE THREAD

**Issue by cirego** [MaterializeInc/materialize#5271]
If a user is modifying an existing service by adding new files, it's possible for the `mzbuild`
rebuild logic to appear flaky. This is because we use the following command to list files that
should be included in the image fingerprint: `git diff --name-only -z
4b825dc642cb6eb9a060e54bf8d69288fbee4904 -- <mzbuild_dir>`.

Unfortunately, this function ignores directories that are unknown to git. Even more unfortunately?
It's unlikely that users will notice this right away. This is because, when adding new files, the
user most likely modified existing files that referenced those files. This means that the first
build will pick up those files, as `mzbuild` doesn't create a sandbox, and the first build will
appear to be correct. However, subsequent builds may not pick up changes to the new files.

Here's the scenario I have in mind. Let's image that we have a service with the following
directory layout:

```
mzbuild.yml
Dockerfile
```

Now, we go ahead and add a new script to this image by creating a new directory and modifying
the Dockerfile:

```
bin/script
Dockerfile
mzbuild.yml
```

Because we modified the Dockerfile, a rebuild will be triggered if we start the service. However,
because `git diff` won't return information about `bin/script`, unless the user runs `git add`,
any further changes to `bin/script` will be ignored and the image will not be rebuilt.

**Comment by benesch** [comment]
I think this may also be fixed by #5270?
