### ISSUE TITLE
1.0 blockers

### ISSUE THREAD

**Issue by benesch** [MaterializeInc/materialize#5273]
At some point—not imminently!—we'll ship v1.0. I'd like this issue to become an exhaustive list of the *engineering*-driven blockers to releasing 1.0. There may be additional product/marketing-driven blockers, and I don't intend to capture all of those here.

I'm not sure exactly what our backwards compatibility policy will be post-1.0, but it is likely to be quite strict. So any breaking change that we can predict should be considered a 1.0 blocker.

### coord

* [x] #3793

### expr

* [ ] #5275

### sql

* [x] #5258
* [x] #5169
* [x] #4400, #5274
* [ ] #5579
* [ ] #4969, #5670
* [x] #3562
* [ ] #7174
* [ ] #8086
* Subqueries don't require an alias (at odds with PostgreSQL)

### interchange

* [x] #7907

### sql-parser

* [x] Are we prepared to never make breaking SQL parser changes? (sort of #1643; TODO a more general issue) (answer: yes)

### dataflow

* [x] #8162

### Global

All panics and wrong results in https://github.com/orgs/MaterializeInc/projects/13.

**Comment by frankmcsherry** [comment]
I'd like to add https://github.com/MaterializeInc/materialize/issues/3793 which is that sources should be consistent by default. More generally, we need to improve the level of sanity surrounding the assignment of timestamps, as a foundation for features like source compaction, fast restart, and active-active replication.

**Comment by mjibson** [comment]
Is source persistence going to be part of this list? If it is, we should also add #5073.

**Comment by frankmcsherry** [comment]
I know we have "productionalize Decimal type" but looking at the issue I think we should go further and put https://github.com/MaterializeInc/materialize/discussions/5274 on the list, i.e. "have decimals that work". The productionalization seems to be more than just a few dark corners and some documentation.

**Comment by benesch** [comment]
Updated with all these suggestions!

**Comment by benesch** [comment]
Added collations #5579 to the list.

**Comment by benesch** [comment]
Adding sorting out our error philosophy to the list (#5670).

**Comment by frankmcsherry** [comment]
I'd like to add https://github.com/MaterializeInc/materialize/issues/7153 or one of the closely related issues to introduce a table-valued function from e.g. text to multiple rows. Without this, I think we are missing the ability to do e.g. "wordcount" which would be silly. Also, at least in the linked issue the implementation seems pretty easy.

**Comment by benesch** [comment]
Added #7174 to the list.

**Comment by benesch** [comment]
We should definitely figure out which of these are platform blockers. I'll add that to my queue.

**Comment by benesch** [comment]
Going to call this one closed. #7174 is the only one that we've committed to doing before EA, and that's already tracked by the surfaces team. We'll just have to live without #5275, #5579, #4969, #5760, and #8086.
