### ISSUE TITLE
Unify logs and metrics

### ISSUE THREAD

**Issue by quodlibetor** [MaterializeInc/materialize#5277]
Ideally all prometheus metrics and materialized catalog metrics are mirrors of each other -- every prometheus metric should be in an `mz_catalog` table, and every table in `mz_catalog` can be materialized in our `/metrics` endpoint.

There are a couple of issues preventing that though:

* Duplicating the logic is annoying
* More importantly, Prometheus metrics are designed to be extremely low-cost to update, but dataflow tables have less-negligible overhead -- inserting possibly hundreds-of-thousands of changes per second takes away from valuable compute that can be dedicated to user work, especially for items that only ever need to be approximate.

We can choose to solve this by prioritizing either the "metrics" interface or the "logs" interface:

* Prioritizing the metrics interface means creating new APIs that wrap both a prometheus metric and a timely logger, and writing to that.

  This introduces a new API everywhere that we want to record a new metric of any sort.
* Prioritizing the logging interface means writing a new Prometheus collector that scans the log views to update its internal metrics

  This requires all metrics to go through dataflow.

I believe creating the new API that wraps both metrics/logs is better for performance and flexibility: that would allow us to write to metrics at very high speed and introduce a polling function that only updates dataflows with on occasion, potentially dramatically reducing logical compaction work for univariate values.

**Comment by benesch** [comment]
Love the idea of unifying these. Still a bit unclear on the implementation, though! I don't think it's possible to plumb the timely logger through the whole system? AIUI It's basically only available in `dataflow` and the things `dataflow` calls. Anything "above" `dataflow` (`coord`, `pgwire`, etc.) is not going to have access to a timely logger. (I guess you could probably hack something up now that we don't support distributed mode, but, that'd set us back for re-enabling distributed mode in the future.)

**Comment by benesch** [comment]
No longer relevant with platform.
