### ISSUE TITLE
 UX - report options used to create a source in relevant mz catalog view

### ISSUE THREAD

**Issue by krishmanoh2** [MaterializeInc/materialize#5288]
When creating a source, there are several configuration choices available. The current method to retrieve these are to do a show create view. It is easy to use a specific option and forget about it. 

Reporting these options that were used to create the source in a mz catalog view  would make it easier to identify them and also audit them as needed.

**Comment by ruchirK** [comment]
when you say options do you mean only `WITH` options or would `FORMAT AVRO` also be considered an "option"?

**Comment by krishmanoh2** [comment]
When I opened this, I was thinking of options such as these - timestamp_frequency_ms, ignore_source_keys etc.

**Comment by ruchirK** [comment]
Gotcha. I think its pretty doable to present the set of `with` options (which I think everything you've listed is).

**Comment by benesch** [comment]
The distinction between what is a `WITH` option and what is syntax is pretty arbitrary. Just outputting the `WITH` options won't be super useful IMO. Also there are three possible places `WITH` options can occur: in the connector, in the format, and in the envelope. Those all need to be properly separated.

I'm up for exposing this information in the catalog in a structured fashion, but it's not quite as simple as a table with `source_id`, `key`, `value` fields.

**Comment by benesch** [comment]
We've started to expose these options in the catalog (e.g., `envelope_type`). Going to close this out. We'll need to handle each desired option on a case-by-case basis, as each option can have custom syntax and allowed values. If anyone has specific options they'd like to see in the system catalog, please open an issue for that specific option!
