### ISSUE TITLE
UX: report kafka consumer group in mz_source_info

### ISSUE THREAD

**Issue by krishmanoh2** [MaterializeInc/materialize#5289]
mz allows you to specify a consumer group for a kafka source. This information is available only via show create view. 

Reporting this information in mz_source_info would make it easy to determine the consumer group that is used and help troubleshoot issues as needed - especially on the kafka cluster.

**Comment by benesch** [comment]
This is now reported in the `mz_kafka_sources` table: https://materialize.com/docs/sql/system-catalog/mz_internal/#mz_kafka_sources.
