### ISSUE TITLE
UX: logical_compaction_window defaults  - make it 1ms from 60000ms

### ISSUE THREAD

**Issue by krishmanoh2** [MaterializeInc/materialize#5291]
The current defaults for logical_compaction_window is 60 seconds. This results in higher resource usage which can be avoided.

Keeping a default of 1ms would meet most requirements and help improve first experience. If a customer requires time-travel, then it can increased as needed.

**Comment by rjnn** [comment]
This isn't a free win - the larger logical compaction window is required to allow for some room so that overlapping timestamps are available when joining across multiple sources.

**Comment by benesch** [comment]
Is that still true? @frankmcsherry made some improvements on that front in
the not so distant past.

**Comment by frankmcsherry** [comment]
Right, so this should be less of a problem now. We should never (modulo bugs) report "timestamp not available" unless you request a specific time (or perhaps other corner cases). Instead, we will pick the earliest valid time and block until we get a response for that time.

I believe the current state of affairs is that `--logical-compaction-window` mainly reduces the possibility you may need to block (in addition to making explicit `AS OF` queries possible). I think changing the default to `1ms` (or maybe `0s`, though this introduces a "guaranteed wait") makes a lot of sense.

This was discussed in https://github.com/MaterializeInc/materialize/pull/4516#event-4199266929 but peripherally and that just got closed. We could bring it and this choice back to life, which I think would be an improvement.

**Comment by benesch** [comment]
Seems like we should just decrease it to 1ms and see what happens?

**Comment by frankmcsherry** [comment]
Fwiw, https://github.com/MaterializeInc/materialize/pull/4467 is the PR where the behavior was changed to pick an advanced time rather than error.
