### ISSUE TITLE
Queries on mz_catalog views/tables - improve response time especially during heavy system load

### ISSUE THREAD

**Issue by krishmanoh2** [MaterializeInc/materialize#5292]
When the system is under heavy load,  queries on mz_catalog views/tables to extract diagnostic data becomes quite slow. 

This makes it difficult to debug the problem. It would be helpful to be able to run diagnostics even if the system is running a heavy load.

**Comment by benesch** [comment]
Agreed that this is a problem, but it's covered in detail by #1537. Let me know if you disagree.
