### ISSUE TITLE
Start/Stop individual components of a workflow (source -> dataflow -> sink)

### ISSUE THREAD

**Issue by krishmanoh2** [MaterializeInc/materialize#5295]
Today, mz is an on/off system in the sense that you create a source, create a view, create a sink and it will run immediately. To stop it, have to drop the source and related objects.

Having the ability to start/stop individual components of a workflow/job (source -> view -> sink) allows for several nice benefits.

1. Understand the impact of each part of the workflow
2. Do maintenance as needed - if a view has fallen behind ,pause the source so the view can catch up to latest. This sometimes is a business requirement.
3. Stop a workflow to free up resources so that another high priority job can run

Flink has similar capabilities - you can save state and stop a job. Resume and it will continue from prior state.

**Comment by ruchirK** [comment]
This seems challenging because we currently rely entirely on the timely scheduler to execute dataflow operators and the full generality of starting / stopping any component of a workflow would be a pretty invasive change to the scheduler.

The more limited version of this request that may be feasible is (just as an example), we could have `PAUSE <source or sink name>` / `RESUME <source or sink name>` commands for sources and sinks that would stop or restart reading / writing from a given source or sink.

To be clear, I do not know whether adding commands like that is a good idea from a product or engineering point of view. I think that merits more discussion. But, this jumps out as maybe the most feasible thing we could do in the general thrust of this issue.

**Comment by benesch** [comment]
Agreed that the general case of pausing a view seems ... extremely difficult. But yeah, severing a source or sink at the moment it interfaces with the external world definitely seems doable! I'm on board with `PAUSE SOURCE`/`RESUME SOURCE` commands, though I haven't thought in detail about what the implementations would look like.

**Comment by ruchirK** [comment]
there's like a externally visible "token" that currently is a bool behind an arc that we use for shutdown in a complicated dance, im pretty sure we could change that to a 3 state enum (running, paused, shutdown) that we write to to pause. but this is mostly a spitball

**Comment by ruchirK** [comment]
I also suspect that `PAUSE`-ing a sink might one day become important for blue / green cc @elindsey

**Comment by krishmanoh2** [comment]
A request from customer along similar lines   - "is it possible to make materialize prioritize catching up on consumer lag vs. hydrating the materialized views on startup?"

**Comment by cirego** [comment]
> A request from customer along similar lines - "is it possible to make materialize prioritize catching up on consumer lag vs. hydrating the materialized views on startup?"

I'm not clear on how we can make a tradeoff between those two? Is this about two different sources? If it's the same source, then catching up on consumer lag and hydrating materialized views are two halves of the same process. Are they worried that view maintenance will cause us to read too slowly and therefore messages will be compacted away from the underlying topics?

**Comment by de1ux** [comment]
The problem we're running into: throwing everything at mz (source + views creation) causes memory to balloon. It appears that waiting for sources to catch-up (near zero consumer lag) before building any views on top of the sources solves the memory issue. 

Ideally, we would ask materialize for source + views, and it would be intelligently prioritize catch-up with the sources before hydrating the views.

**Comment by cirego** [comment]
> The problem we're running into: throwing everything at mz (source + views creation) causes memory to balloon. It appears that waiting for sources to catch-up (near zero consumer lag) before building any views on top of the sources solves the memory issue.
> 
> Ideally, we would ask materialize for source + views, and it would intelligently prioritize catch-up with the sources before hydrating the views.

Thank you for the explanation!
