### ISSUE TITLE
DOCS: Tail behavior specifics

### ISSUE THREAD

**Issue by krishmanoh2** [MaterializeInc/materialize#5307]
Can we move this below content to the conceptual framework of TAIL? 

It looks like this behavior of clients not returning data back can be interpreted as TAIL not functioning.

> TAIL produces rows similar to a SELECT statement, except that TAIL may never complete. Many drivers buffer all results until a query is complete, and so will never return. Below are the recommended ways to work around this.

**Comment by benesch** [comment]
Is this for people typing `TAIL` in `psql`? I have a different solution in mind for that, where we produce a notice response to let them know that they probably wanted to type something else.

**Comment by krishmanoh2** [comment]
Yes to psql (testing first ) and then see same issue with npgsql driver as well.

**Comment by awang** [comment]
I think Nikhil's proposal sounds good to me, but I don't entirely follow what the proposed solution should be, so I quickly built this PR (which I don't intend to merge unless told otherwise):  https://github.com/MaterializeInc/materialize/pull/5318
