### ISSUE TITLE
JSONB aggregation with the wrong order

### ISSUE THREAD

**Issue by petrosagg** [MaterializeInc/materialize#5311]
### What version of Materialize are you using?
main branch 

### What was the issue?

When using an aggregation on a subquery with an `ORDER BY` in an unrelated column causes the data in the aggregation to be reordered.

### Is the issue reproducible? If so, please provide reproduction instructions.

SQL to reproduce:

```sql
CREATE TABLE t (a int, b text);
INSERT INTO t VALUES (1, 'b');
INSERT INTO t VALUES (2, 'a');
SELECT jsonb_agg(b) FROM (SELECT b FROM t ORDER BY a);
```

Expected result:

```
 jsonb_agg
------------
 ["b", "a"]
(1 row)
```

Actual result:

```
 jsonb_agg
-----------
 ["a","b"]
(1 row)
```

**Comment by ruchirK** [comment]
This seems at least related to: https://github.com/MaterializeInc/materialize/issues/2415

**Comment by benesch** [comment]
Yeah, pretty sure our reliable current ordering is just ... totally random luck? I have no idea what would enforce it, if nothing else.

**Comment by ruchirK** [comment]
I'm not surprised by this because the current `jsonb_agg` implementation in the dataflow crate orders them in `Row` order - which is essentially memcpy order on the bytes in these two rows, and doesn't respect any other ordering on its inputs.

It's not clear to me whether this is something we have to support

**Comment by ruchirK** [comment]
in `build_basic_aggregate` the `reduce_abelian` operator enforces that all values for a key are ordered with respect to their ord implementation and then we read through them in order to make a datumlist in the `jsonb_agg` function

**Comment by ruchirK** [comment]
I'm going to close this in favor of #2415 unless Petros or Nikhil you guys think it should stay open?

**Comment by petrosagg** [comment]
the only question I have is if the order (however arbitrary) has to be consistent between two aggregates in the same query. i.e is it technically valid for this query to return two different values?

```sql
SELECT jsonb_agg(b), jsonb_agg(b) FROM (SELECT b FROM t ORDER BY a);
```

**Comment by petrosagg** [comment]
I found my answer [here](https://stackoverflow.com/questions/7317475/postgresql-array-agg-order). I'll close this issue in favour of #2415

**Comment by ruchirK** [comment]
I didnt test the query you posted but I think the returned order will always be consistent btw

**Comment by frankmcsherry** [comment]
Doesn't JSONB specify an order for the fields, or is it just the tie-breaking it specifies an order for? Should we be sorting and deduplicating the entries, for example?

**Comment by benesch** [comment]
`jsonb_agg` aggregates into a jsonb array which has no constraints on order or duplicates. I think you're thinking of jsonb objects.
