### ISSUE TITLE
Multi-table DROP TABLE CASCADE fails with "unknown catalog item" if view with a join is present

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#5316]
### What version of Materialize are you using?

```
$ materialized -v
materialized v0.6.0 (9ed7c170f)
```

### How did you install Materialize?

* [ ] Docker image

### What was the issue?

I was experimenting with automatic generation of view definitions and turns out that if the view definition contains a join, multi-table DROP TABLE CASCADE fails

### Is the issue reproducible? If so, please provide reproduction instructions.

```
DROP VIEW IF EXISTS v1 CASCADE;
CREATE TABLE t1 (f1 INTEGER);
CREATE TABLE t2 (f2 INTEGER);
CREATE MATERIALIZED VIEW v1 AS SELECT * FROM t1, t2;
DROP TABLE t1, t2 CASCADE;
ERROR:  unknown catalog item 'u454': unknown catalog item 'u454'
```

DROP CASCADE works if the view references just a single table.

Dropping the view directly works. Dropping tables individually works. So plenty of workarounds are available. No permanent corruption.

**Comment by rjnn** [comment]
Assigned to @JLDLaughlin for triage, as I believe you worked on tables.
