### ISSUE TITLE
sql: support power

### ISSUE THREAD

**Issue by JLDLaughlin** [MaterializeInc/materialize#5329]
Add support for the [math function `power`](https://www.postgresql.org/docs/13/functions-math.html):

```
power ( a numeric, b numeric ) → numeric
power ( a double precision, b double precision ) → double precision
    a raised to the power of b
    power(9, 3) → 729
```

Unblocks a [dbt macro](https://github.com/MaterializeInc/materialize-dbt-utils/blob/main/integration_tests/dbt_utils/dbt_project.yml#L69).

**Comment by aljoscha** [comment]
@antifuchs Should this have been closed?

**Comment by antifuchs** [comment]
Oops, yes it should have been, guess I got the github syntax wrong. Thanks!
