### ISSUE TITLE
docs: create a list of tools that connect to Materialize

### ISSUE THREAD

**Issue by JLDLaughlin** [MaterializeInc/materialize#5333]
As we work on building out the ecosystem of software that can connect to and work with Materialize, we should publicly document which tools work and to what extent. To start, Materialize currently works with:
- psql
- DBeaver (if errors are ignored)
- Metabase (with a hack)
- dbt (with a custom adapter)

**Comment by benesch** [comment]
See also #2228, which is specifically focused on PostgreSQL drivers.

**Comment by JLDLaughlin** [comment]
Partially implemented here: https://github.com/MaterializeInc/materialize/pull/5467

**Comment by morsapaes** [comment]
This has now materialized (ah) as ✨[Tools and Integrations](https://materialize.com/docs/integrations/)✨, and we're actively working on ensuring that each supported tool has a clear step-by-step integration guide. 

Closing the issue!
