### ISSUE TITLE
Can't connect to SASL over SSL source

### ISSUE THREAD

**Issue by escobera** [MaterializeInc/materialize#5366]
### What version of Materialize are you using?

```
$ ./materialized -vv                
materialized v0.6.1-dev (600f364c7)
OpenSSL 1.1.1g  21 Apr 2020
librdkafka v1.5.3

```

### How did you install Materialize?

 Built from source

### What was the issue?

I'm trying to create a KAFA source poiting to a local strimzi.io cluster. I'm using SASL over SSL without kerberos. But when I try to create the source as such: 

```sql
CREATE SOURCE processos_kafka FROM KAFKA BROKER 'kafka-stage.apps.tjdft.jus.br:443'
    TOPIC 'processos.public.processos'
    WITH (
        security_protocol = 'sasl_ssl',
        sasl_mechanism = 'scram-sha-512',
        sasl_username = 'prospeccao',
        sasl_password = '----',
        ssl_certificate_location = '/home/rafa/ca.crt'        
    )
    FORMAT BYTES;
```

I get `SQL Error [XX000]: ERROR: Can't seem to find local keytab cache. You must provide explicit sasl_kerberos_keytab or sasl_kerberos_kinit_cmd option.`

I'm using options found here: https://github.com/MaterializeInc/materialize/pull/5133

**Comment by sploiselle** [comment]
This was caused by using `sasl_mechanism = 'scram-sha-512'` instead of `sasl_mechanisms = 'scram-sha-512'`, as mentioned in #5133
