### ISSUE TITLE
Create a tornado-materialize library once psycopg3 is widely available

### ISSUE THREAD

**Issue by cirego** [MaterializeInc/materialize#5385]
Our play/wikirecent python application has code to run TAIL and convert rows into JSON objects
that are broadcast over websockets. This code can easily be packaged up into something reusable by
in other Tornado applications (and we should look at web frameworks too, like Django and FastAPI).
We should consider packaging it up and publishing it on PyPI to help people get started building
apps with Materialize!

**Comment by benesch** [comment]
I'm all for dropping the barrier to entry to the bare minimum, but I think we can reduce the maintenance burden of supporting WebSockets by building support for publishing `TAIL` over WebSockets into Materialize itself! @mjibson has a WIP branch here: https://github.com/mjibson/materialize/commit/d6a04702df662b8ee29dc1eac1f02dfbfe778371. See also https://github.com/MaterializeInc/materialize/issues/3423#issuecomment-756939474 for additional discussion.

**Comment by cirego** [comment]
That's great! That will simplify the implementation of `tornado-materialize`, as it wouldn't require a dependency on `psycopg3`. I do believe there is still value in providing this as a library, even with websockets.

**Comment by benesch** [comment]
Forgive me if I'm being dense, but what would tornado-materialize do in a world where Materialize natively supports `TAIL over WebSockets?

**Comment by cirego** [comment]
I think there are a few things this library would still do:

1. Enable some amount of connection pooling for shared views, if we want to reduce the number of connections to Materialize.
2. Provide a way to deserialize the data from Materialize and present them as Python objects -- something that psycopg does for us today.

It's also possible that this library should not be tornado specific, but rather just a library to produce an async stream of batches (or rows) from tail.

**Comment by benesch** [comment]
Closing as this is not in line with our vision. The plan is to make `TAIL` so scalable that you don't need to run a proxy (Python or otherwise) in front of materialized. And the reason it is currently designed to use pgwire is precisely so we're not in the business of writing client libraries in every language we want to support.
