### ISSUE TITLE
SHOW VIEWS broken when queried from either psycopg2 or pg8000

### ISSUE THREAD

**Issue by cirego** [MaterializeInc/materialize#5399]
Not sure what the proper fix is but our chbench ingest benchmarks are currently broken with the
following error:

```
Creating chbench_mzutil_run ... done
Traceback (most recent call last):
  File "/usr/local/bin/wait_for_view_states.py", line 229, in <module>
    main()
  File "/usr/local/bin/wait_for_view_states.py", line 225, in main
    wait_for_materialize_views(args)
  File "/usr/local/bin/wait_for_view_states.py", line 152, in wait_for_materialize_views
    installed_views = set(view_names(conn))
  File "/usr/local/bin/wait_for_view_states.py", line 40, in view_names
    cursor.execute("SHOW VIEWS")
psycopg2.errors.ActiveSqlTransaction: SHOW VIEWS cannot be run inside a transaction block

Failed! giving up: mzutil wait_for_view_states.py
```

I'm not sure if this is the behavior that @mjibson intended, but we can
probably also work around this within the Python code.

**Comment by cirego** [comment]
It looks like this issue is more general than just the benchmarks.

I'm unable to run `SHOW VIEWS` using either `psycopg2` or `pg8000`:

```
>>> conn = pg8000.connect(user="materialize", port=6875, database="materialize")
>>> cur = conn.cursor()
>>> cur.execute("SHOW VIEWS")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/pg8000/core.py", line 341, in execute
    self._c.execute_unnamed(
  File "/usr/local/lib/python3.8/dist-packages/pg8000/core.py", line 1214, in execute_unnamed
    self.handle_messages(cursor)
  File "/usr/local/lib/python3.8/dist-packages/pg8000/core.py", line 1381, in handle_messages
    raise self.error
pg8000.exceptions.ProgrammingError: {'S': 'ERROR', 'C': '25001', 'M': 'SHOW VIEWS cannot be run inside a transaction block'}
```

```
>>> import psycopg2
>>> with psycopg2.connect(f"postgresql://localhost:6875/materialize") as conn:
...     with conn.cursor() as cur:
...             cur.execute("SHOW VIEWS")
... 
Traceback (most recent call last):
  File "<stdin>", line 3, in <module>
psycopg2.errors.ActiveSqlTransaction: SHOW VIEWS cannot be run inside a transaction block
```

**Comment by benesch** [comment]
You can probably turn on autocommit like Matt did here to work around this
for now:
https://github.com/MaterializeInc/materialize/pull/5297/files#diff-5b4afdac9c0422adf4baaf2db3b3198979470c4b027ed0c4721cbcc19579120b

Separately, @mjibson, SHOW commands (except for SHOW <var>) are simple read
only queries and can probably be allowed everywhere normal SELECTs are?

**Comment by cirego** [comment]
I will try running with that workaround, thanks @benesch!

**Comment by mjibson** [comment]
`SHOW` commands consult the catalog. Unless we can serialize catalog access it's not correct to return results from `SHOW` in a txn. I agree that `SHOW` is maybe one of the easier things, and maybe it's actually ok to do and I just haven't thought about it enough.

**Comment by benesch** [comment]
But so do normal `SELECT` queries? I don't understand how `SHOW` and `SELECT` are any different.

**Comment by mjibson** [comment]
Oh right :(. Ok seems like we can allow SHOW in txns and then figure out how to fix them. I guess the risk is that someone could drop something during another txn and then the txn starts failing even though it should have been isolated from that drop? Probably not an actual problem.

**Comment by benesch** [comment]
Going to reopen this because it's also blocking dbt-materialize!
