### ISSUE TITLE
docs: s3 sources

### ISSUE THREAD

**Issue by benesch** [MaterializeInc/materialize#5414]
S3 sources are in v0.6.1, but behind an experimental flag. I'm going to leave them unmentioned in the release notes until we have documentation about them. (Per policy we don't mention changes to experimental features in the release notes.) This issue serves a reminder to add a release note for them when we unexperimentalize them and have docs.

/cc @quodlibetor

**Comment by awang** [comment]
this is a really good one, @msudberg i would put this at the top of your list as it's already well-documented in @quodlibetor 's initial writeup:  https://github.com/MaterializeInc/materialize/issues/4914 and it's going to be broadly interesting to many folks
