### ISSUE TITLE
Tail returning rows with negative diff in initial result set

### ISSUE THREAD

**Issue by cirego** [MaterializeInc/materialize#5421]
When running the "TAIL (WITH PROGRESS)", I expect that the first set of rows (up until progressed
= true) to be inserts only. Alternately, I expected a compacted representation of the initial view
state.

Here is the output I currently get but I do no expect to see:

```
materialize=> DECLARE cur CURSOR FOR TAIL top10 WITH (SNAPSHOT);
DECLARE CURSOR
materialize=> FETCH 26 cur;
   timestamp   | diff | user | count 
---------------+------+------+-------
 1611360541000 |    1 | Fæ   |    48
 1611360541000 |    1 | Fæ   |    49
 1611360541000 |    1 | Fæ   |    54
 1611360541000 |    1 | Fæ   |    55
 1611360541000 |    1 | Fæ   |    56
 1611360541000 |    1 | Fæ   |    62
 1611360541000 |    1 | Fæ   |    66
 1611360541000 |    1 | Fæ   |    68
 1611360541000 |    1 | Fæ   |    74
 1611360541000 |    1 | Fæ   |    75
 1611360541000 |    1 | Fæ   |    79
 1611360541000 |    1 | Fæ   |    80
 1611360541000 |    1 | Fæ   |   126
 1611360541000 |   -1 | Fæ   |    48
 1611360541000 |   -1 | Fæ   |    49
 1611360541000 |   -1 | Fæ   |    54
 1611360541000 |   -1 | Fæ   |    55
 1611360541000 |   -1 | Fæ   |    56
 1611360541000 |   -1 | Fæ   |    62
 1611360541000 |   -1 | Fæ   |    66
 1611360541000 |   -1 | Fæ   |    68
 1611360541000 |   -1 | Fæ   |    74
 1611360541000 |   -1 | Fæ   |    75
 1611360541000 |   -1 | Fæ   |    79
 1611360541000 |   -1 | Fæ   |    80
 1611360541000 |   -1 | Fæ   |   126
```

Inspecting the above manually, I would have expected that all of the above rows would have been
compacted away and we would not have returned any of those rows to the client.

**Comment by benesch** [comment]
@umanwizard I'm 99% certain that behavior regressed in c333420f0, since that removed the call to `consolidate` in the tail code path. Debezium and upsert sinks now call `combine_at_timestamp`, but I'm not sure whether that is the correct method to call for tail sinks.

**Comment by umanwizard** [comment]
Yes, it sounds almost certainly related. Should be fine to just go ahead and add the consolidate back for `tail`; I'll do so tomorrow.

No, `combine_at_timestamp` is _not_ correct for tail; we should just use consolidate.

**Comment by benesch** [comment]
I tried to write a test that avoided this last night but couldn’t reproduce. Not sure exactly what it takes to get two unconsolidated batches emitted in a snapshot.

**Comment by benesch** [comment]
Never mind. I figured it out. PR incoming.
