### ISSUE TITLE
Sink creation uses an `as_of` time that is no longer valid.

### ISSUE THREAD

**Issue by frankmcsherry** [MaterializeInc/materialize#5423]
Per a conversation on Slack, sink creation needs to pick an `as_of` time for its dataflow, but it appears that having done so it yields control and by the time it sends the creation dataflow the bound time is no longer valid.

> benesch  20 hours ago
> Oof, ok. So we pick a good AS OF time for the sink; then we off and create a Kafka topic; when we come back the AS OF time is no longer valid. That sucks.
> benesch  20 hours ago
> The coordinator will need to avoid advancing the since frontier while it creates the Kafka topic.

I have no information about the necessary remedy, but if the `as_of` time needs to be picked well in advance of deploying the dataflow, there exists an `ALTER INDEX` command that can pause compaction. I'm not clear on why the time is picked before the Kafka topic is constructed though (is it part of the name?). 

cc @benesch

**Comment by benesch** [comment]
Are sinks with `AS OF` just totally broken on restart? What happens when you come back online? Won't that `AS OF` time be total crap? Hmmm...

**Comment by frankmcsherry** [comment]
They don't need to be, but they might be. I think a thing we should do but do not do is track `as_of` for sources: how far back in time are we sure they are providing accurate timestamp information. If on restart we get the same `as_of` for the source, the sink is fine too. However, I believe at the moment `as_of` for a source is not a concept (some comments in the code to this effect, where we would want it, that it doesn't exist).

I can believe that on recovery we don't *want* to use the same `as_of`, unless very specifically instructed, because if we've already committed through `time` in the output, we'd really love to fast-forward up to `time` and go from there.

I don't know much about recovery and whether we try and reproduce the same `AS OF` in the statement that created the thing. I could imagine that was easiest, though. But we should probably have a think about what the system should recover to on failure (should it recover to the whatever state it has recently been in, or should it take the user through all prior states it has been in?).

**Comment by frankmcsherry** [comment]
Perhaps relevant: https://github.com/MaterializeInc/materialize/issues/2862

**Comment by frankmcsherry** [comment]
One quirk that has come up and may want to be resolved independently is that the catalog stores the sink with its `AS OF` creation timestamp. However, there is no guarantee on recovery that it will be able to recreate the sink with the same timestamp. It seems like certain things (sinks, dataflows, sources even) should be potentially unparameterized, and you get what you get. Perhaps you can express requests, and maybe you should get an error if you can't get your request, but generally time may have moved on in the intervening moments.

Longer term, this is probably fine: if MZ runs for a week and then reboots, when it comes back up again the sink probably has been shown all of that weekly data, and we just need to reload the sink AS OF whatever was last ack'd by the sink.
