### ISSUE TITLE
Problems around creating Source with Protobuf Schema

### ISSUE THREAD

**Issue by macthestack** [MaterializeInc/materialize#5427]
### What version of Materialize are you using?

```
materialized v0.6.1 (3247686f8)
```

### How did you install Materialize?

Tried with both installed and docker on PopOS

### What was the issue?

Can't create source

```
CREATE SOURCE tracks FROM
  KAFKA BROKER 'localhost:9092' TOPIC 'incoming'
  WITH ( cache = true )
  FORMAT PROTOBUF MESSAGE '.test.Test' USING SCHEMA '0A320A0A746573742E70726F746F12047465737422160
 A0454657374120E0A02696418012001280952026964620670726F746F33';
```
This give me `parsing encoded protobuf descriptors failed: unexpected wire type`

If I try to instead point it to my schema file I get `o such file or directory (os error 2)`. Both in mzcli and psql

This is my .proto:

```
syntax = "proto3";
package test;

message Test {
    string id = 1;
}
```

**Comment by benesch** [comment]
Ah, yeah, `USING SCHEMA` takes a byte string literal in the PostgreSQL format, which is not quite a hex string literal. The format is fully specified here: https://www.postgresql.org/docs/current/datatype-binary.html

The tl;dr is that you can either provide a series of escaped octets, like `'\000\001\001'` or `\x` followed by a series of hex-encoded bytes:  '\xABCDEF`. In your case I think the following would work:

```sql
CREATE SOURCE tracks FROM
  KAFKA BROKER 'localhost:9092' TOPIC 'incoming'
  WITH ( cache = true )
  FORMAT PROTOBUF MESSAGE '.test.Test' USING SCHEMA '\x0A320A0A746573742E70726F746F12047465737422160A0454657374120E0A02696418012001280952026964620670726F746F33';
```

Sounds like there's a separate issue with the `SCHEMA FILE` alternative that you tried. If you're running via Docker, remember that you'll have to mount the schema file into the `materialized` container. Also the path is relative to the `materialized` process's CWD; sometimes it helps to debug these things by using an absolute path instead.

**Comment by benesch** [comment]
We ought to get this documented, though! Thanks for the report.

**Comment by macthestack** [comment]
Thanks a bunch! @benesch
