### ISSUE TITLE
KAFKA+AVRO - Don't know how to serialize key / message

### ISSUE THREAD

**Issue by macthestack** [MaterializeInc/materialize#5443]
I'm using `materialized v0.6.1 (3247686f8)` and I'm getting this error:

```
ERROR dataflow::decode: avro deserialization error: wrong Confluent-style avro serialization magic: expected 0, got 121
```
This doesn't seem to come from the message but the key. If I add 5 zeroes before the key I get:

```
dataflow::decode: avro deserialization error: IO error: UnexpectedEof
```

I have tried to encode as utf8 as well as avro record with single string. I'm not sure what the correct way is. Please help.

This is what I'm doing to create the source:

```
CREATE SOURCE test
 FROM KAFKA BROKER  'localhost:9092' TOPIC 'test'
 FORMAT AVRO USING SCHEMA '{
     "type": "record",
     "name": "Test",
     "namespace": "test",
     "fields": [
         {
             "name": "test",
             "type": "float"
         }
     ]
 }'
 ENVELOPE UPSERT;
```

P.S. It seems wasteful to prepend every event with 5+5 bytes even if you are defining the schema at CREATE STREAM

**Comment by benesch** [comment]
Yeah, this is kind of a rough spot at the moment. Small discussion on this point here: https://github.com/MaterializeInc/materialize/issues/2125#issuecomment-591638003

@umanwizard, what's the latest on this?

**Comment by umanwizard** [comment]
Prepending five zeroes should work, if the schema is correct. Can you share the actual raw bytes you are trying to decode with that schema?

**Comment by wangandi** [comment]
If your key has a different schema/type from your value, then you need to add the format specification after `ENVELOPE UPSERT`. 

If your key is straight-up utf8 that is not avro encoded, the correct source creation command is
```
CREATE SOURCE test
 FROM KAFKA BROKER  'localhost:9092' TOPIC 'test'
 FORMAT AVRO USING SCHEMA '{
     "type": "record",
     "name": "Test",
     "namespace": "test",
     "fields": [
         {
             "name": "test",
             "type": "float"
         }
     ]
 }'
 ENVELOPE UPSERT FORMAT TEXT;
```

If your key is an avro record with a single string, your source creation command should look like
```
CREATE SOURCE test
 FROM KAFKA BROKER  'localhost:9092' TOPIC 'test'
 FORMAT AVRO USING SCHEMA '{
     "type": "record",
     "name": "Test",
     "namespace": "test",
     "fields": [
         {
             "name": "test",
             "type": "float"
         }
     ]
 }'
 ENVELOPE UPSERT FORMAT AVRO USING SCHEMA '{
      "type": "record",
     "name": "KeyTest",
     "namespace": "test",
     "fields": [
         {
             "name": "testkey",
             "type": "string"
         }
     ]
}';
```

**Comment by macthestack** [comment]
I've got it working now with `ENVELOPE UPSERT FORMAT TEXT;`

Thanks!
