### ISSUE TITLE
clear dbt-materialize adapter for production use-cases

### ISSUE THREAD

**Issue by JLDLaughlin** [MaterializeInc/materialize#5462]
The `dbt-materialize` adapter is currently an active work in progress. In order to sign off on the adapter being used for production use-cases, we should:
- [x] Test its limits (and likely add more functionality): https://github.com/MaterializeInc/materialize/issues/5448
- [x] Implement all possible dbt-utils macros: https://github.com/MaterializeInc/materialize/issues/5446
- [x] Get feedback on the adapter

**Comment by morsapaes** [comment]
Closing this issue, since there are now a couple of users successfully deploying Materialize+dbt in production and no major issues have been reported.
