### ISSUE TITLE
coord,sql: support temporary tables and indexes

### ISSUE THREAD

**Issue by benesch** [MaterializeInc/materialize#5470]
We currently support `CREATE TEMP VIEW`, but not `CREATE TEMP INDEX`, which in turn means we can't support `CREATE TEMP TABLE` or `CREATE TEMP MATERIALIZED VIEW`. This issue tracks adding these three new SQL commands.

- [x] `CREATE TEMP INDEX`
- [ ] `CREATE TEMP TABLE`
- [x] `CREATE TEMP MATERIALIZED VIEW`

This is an important part of Fivetran support (#5188).

**Comment by cuongdo** [comment]
What is the current motivating use for this feature?

**Comment by benesch** [comment]
Oops, I forgot to mention that this is also an important part of Fivetran support.
