### ISSUE TITLE
DROP TYPE allowed even if objects still reference said type -> Materialize fails to load catalog on startup

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#5577]
```
pstoev=> CREATE TYPE int4_list AS LIST (element_type = int4);
CREATE TYPE

pstoev=> create view v1 as select cast('{2}' as int4_list);
CREATE VIEW

pstoev=> drop type int4_list;
DROP TYPE
```

Restart than fails:

```
materialized: corrupt catalog: failed to deserialize item u2153 (pstoev.public.v1): unknown catalog item 'pstoev.public.int4_list'
```

Rather than tracking dependencies exhaustively, this can be resolved by in-lining the complete type definition inside every view that references it. This will however prevent a proper future implementation of e.g. ```ALTER TYPE```

**Comment by JLDLaughlin** [comment]
Fixed by https://github.com/MaterializeInc/materialize/pull/5810
