### ISSUE TITLE
sql: add SHOW EXTENDED TABLES

### ISSUE THREAD

**Issue by JLDLaughlin** [MaterializeInc/materialize#5593]
Like other `SHOW EXTENDED` commands, `SHOW EXTENDED TABLES` should return all of the tables in the current or provided schema as well as all `system` tables and `temp` tables for the connection.

For reference, it should look something like [`SHOW EXTENDED TYPES`](https://github.com/MaterializeInc/materialize/blob/main/src/sql/src/plan/statement/show.rs#L409).

**Comment by OscarTHZhang** [comment]
I can take this ticket

**Comment by JLDLaughlin** [comment]
That'd be great, @OscarTHZhang! Please reach out if you need any help, some information on contributing to Materialize can be [found here](https://github.com/MaterializeInc/materialize/blob/main/CONTRIBUTING.md).

**Comment by OscarTHZhang** [comment]
What's the best way to reach out?

**Comment by JLDLaughlin** [comment]
The best way to reach out is probably on here! Our team is pretty active responding on Github issues, and that way I'm not a blocker. For background, Oscar reached out to ask about the goal of `SHOW EXTENDED TABLES`. Here's my long-ish response:

In general, Materialize aims to be compatible with Postgres, not with other databases. This means that we’re okay with implementing features, like `SHOW EXTENDED …`, differently than non-Postgres databases. So while you’re totally right that adding `OR s.database_id IS NULL` to the `SHOW` query would not implement Databrick’s `SHOW EXTENDED` spec, we’re okay with that!

For background, there are two types of objects in Materialize’s catalog: system-created objects and user-created objects. By default, `SHOW ..` will only return user-created objects. By contrast, `SHOW EXTENDED ..` will return Materialize’s system objects as well. 

`SHOW TYPES` and `SHOW EXTENDED TYPES` illustrates this:
```
materialize=> create type custom_type as list (element_type = int4);
CREATE TYPE

# Show types created by a user
materialize=> show types;
    name
-------------
 custom_type
(1 row)

# Show types created by the system or a user
materialize=> show extended types;
     name
--------------
 _bool
 _bytea
 _date
 _float4
 _float8
...
custom_type
```
Objects that are created by a user will be qualified by a database and schema, like `database.schema.object`. Objects that are created by the system, on the other hand, do not belong to a particular database--they are created directly in the [`MZ_CATALOG` schema](https://github.com/MaterializeInc/materialize/blob/main/src/coord/src/catalog/builtin.rs#L35) instead. That's why adding `OR s.database_id IS NULL` to a `SHOW` query will include system objects as well as user objects.

**Comment by OscarTHZhang** [comment]
@JLDLaughlin Thanks for your detailed explanation. I have a PR [here](https://github.com/MaterializeInc/materialize/pull/6159). Updated both code and doc. Is there a way that I could test this without building it to a binary?

**Comment by JLDLaughlin** [comment]
Amazing! You will have to build the binary with your changes locally in order to test them. You can do this interactively by spinning up a Materialize instance, entering a `psql` shell, and checking that outputs to your queries match what you'd expect. For this type of change, it would also make sense to add a [`testdrive`](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-testing.md#testdrive) test--I'll put more info on your PR!

**Comment by JLDLaughlin** [comment]
Closed by https://github.com/MaterializeInc/materialize/pull/6159, thanks @OscarTHZhang !
