### ISSUE TITLE
s3 sources: Support avro-encoded records

### ISSUE THREAD

**Issue by quodlibetor** [MaterializeInc/materialize#5596]
Currently S3 sources only support text-like encodings. There are a few reasons for this:

* We need a way to specify arbitrary record delimiters (#2461)
* Avro needs a schema to be parseable, the OCF format includes a schema in each file, but that means that each object has the chance to break its schema so we need to add some more error handling. We also need to do a bit more work to split out headers from the records that are sent through
* S3 sources need to be able to stream byte chunks through to decoders, but byte chunks might not be complete if you're not using a length-prefixed record delimiter, and decoder's currently expect each message to be an entire record.

**Comment by paul-snively** [comment]
:100: 

I'm not sure what to add to this, but if Materialize wishes to compete with tools like Presto or Dremio, it's going to be necessary to solve this, and related, problems.

> S3 sources need to be able to stream byte chunks through to decoders, but byte chunks might not be complete if you're not using a length-prefixed record delimiter, and decoder's currently expect each message to be an entire record.

I'm frankly not sure what this means. Naïvely, perhaps, it sounds like "decoder" here refers to something in Materialize, and that something is making the assumption that the encoding is "length-prefixed record delimited."

Don't do that! :-)

More seriously, I imagine this is part and parcel of the work to orthogonalize "source" and "encoding," and look forward to the results.

**Comment by benesch** [comment]
Closing as stale. We no longer support S3 sources.
