### ISSUE TITLE
Support `WHERE now() BETWEEN` in maintained dataflows

### ISSUE THREAD

**Issue by frankmcsherry** [MaterializeInc/materialize#5624]
Folks write queries that are continually re-evaluated, and often want to use `now()`, the current system time. We currently permit this in one-off `SELECT` queries (using the value of `now()` when the query will be executed), but not in maintained dataflows (as the value of `now()` continually changes). This document moves forward under the assumption that what they want is `mz_logical_timestamp()`, which is to say the "current time" as seen within the dataflow. This is naively very painful, because this value changes for all records, at every timestamp.

This doc propose an approach that probably handles ~95% of the use cases, just a guess, by restricting uses to WHERE clauses with simple inequalities. In particular, it proposes *not* doing https://github.com/MaterializeInc/materialize/issues/2439 and instead solving a more restricted problem in a way that is more likely to yield appealing behavior.

# The problem

Folks want to be able to write
```sql
SELECT record
FROM records
WHERE now() BETWEEN record.valid_from AND record.valid_until;
```
and variants of it (operations on both fields, perhaps optionally dropping the lower or upper bounds).

Recast with `mz_logical_timestamp()` instead of `now()`, this is still a perfectly deterministic computation. To the reader it isn't even all that complicated: the record shows up at a time, and then vanishes at a time.

The issue is that predicates can be complicated, and the following query makes much less sense
```sql
SELECT record
FROM records
WHERE hash(now() + record.valid_from + record.valid_until) == 0;
```

This is also a perfectly valid deterministic computation. However, we likely have no choice but to reconsider each record at each logical time, just to see what the hash equals.

The problem then is that folks want the first thing, but we would need to avoid the complexity of building the second thing.

# Approach 1: Time sources

This approach is presented in https://github.com/MaterializeInc/materialize/issues/2439.

Imagine a source of data that contains the current time, and ticks forward. This tick can be manual, but it can also be automatically generated, as the updates are exactly the timestamp:

```text
    (time0, time0, +1)
...
    (time1, time1, +1)
    (time0, time1, -1)
..
    (time2, time2, +1)
    (time1, time2, -1)
..
    (time3, time3, +1)
    (time2, time3, -1)
..
```

The `now()` call can desugar to cross-joining in this source, roughly the same as
```sql
SELECT record
FROM records, time_source
WHERE now BETWEEN record.valid_from AND record.valid_until;
```

Implementing this query as a cross join is very computationally expensive, because `now` changes very often. Each time `now` changes we will reconsider each record, because the predicate is an opaque expression that can only be evaluated.

This approach will perform linear per-time work, and will retain all of `records` forever. This was explored in https://github.com/MaterializeInc/materialize/issues/3880 and determined that Materialize eventually falls irrecoverably behind.

# Approach 2: Inequality joins

Still considering time sources, the `WHERE` clause in the desugared query just above a special structure
```sql
WHERE now BETWEEN record.valid_from AND record.valid_until;
```

This is an "inequality join" where instead of equality constraints there are inequality constraints. Such queries can be efficiently implemented on databases that used ordered data stores. Differential dataflow does not have such an operator natively, though one could scope out how to build one.

This approach reduces the work from linear per time, to logarithmic per time.
This approach will still retain all of `records` forever.

# Approach 3: Update narrowing

Stepping back from the use of time sources, the `WHERE` clause has a specific function here. It narrows the time interval in which a `record` can appear to a specific interval: `[valid_from, valid_until]`.

This operator is not difficult to implement in differential dataflow: each update of the form `(data, time, diff)` corresponds to a change whose effective interval is `[time, infinity)`. We need to restrict that interval based on bounds we extract from `data`.

The following code sketches the per-update logic to narrow its effective interval to `[from, until]`:
```rust
    for (data, time, diff) in updates {
        // extract `Option<Time>` bounds from `data`.
        let (from, until) = extract_from_data(data);

        // only continue if `time` does not exceed `until`.
        if until.as_ref().map(|t| time.le(t)).unwrap_or(true) {
            // if there is a lower bound, advance `time` to it.
            if let Some(from) = from {
                time = std::cmp::max(time, from);
                output.push((data, time, diff));
            }
            // if there is an upper bound, retract `data` then.
            if let Some(until) = until {
                output.push((data, until, -diff));
            }
        }
    }
```

I assert that this has the behavior of intersecting the `[time, infinity)` interval to `[from, until]`. It is also super easy to implement on a per-update basis (in the sense of no state required).

This approach performs no per-time computation, constant per-update computation, and maintains records only for their validity interval (rather than forever).

We could permit the use of `now()` in `now() BETWEEN` statements, extract the bounds, and then implement such an operator. There are lots of unknown issues.  One example is that creating updates at future times gums up the works until they are able to be processed. If you ship a bunch of updates all at the same time, but with different and far-future `valid_until` fields, differential dataflow will start to trip over these.

**Comment by ruchirK** [comment]
So just thinking about this a bit more -- if a customer had a table of `(transaction, cost, timestamp)` and wanted to answer a query like "whats the largest cost transaction from the past 7 days", they would preprocess this data to look like
`(transaction, cost, round_down_to_the_nearest_day(timestamp - interval 7 days), round_up_to_day(timestap)` and then use the last two columns as valid from / until bounds for their `select max(cost)` query? is that right?

**Comment by frankmcsherry** [comment]
I think one important part of using this is that you can't roll time backwards. So, everything ends up being from the moment you introduce the record, forward (we may end up advancing `time`, but never going backwards).

You could certainly do some flavor of window by writing
```sql
SELECT dataz.key, sum(dataz.whatever)
FROM dataz
WHERE now() BETWEEN dataz.event_time AND dataz.event_time + 7 days
```
which I think is what you are proposing (and rounding to days would mean a more compact representation, which is especially important for the future times).

**Comment by frankmcsherry** [comment]
If you wrote a different query that was
```sql
SELECT dataz.key, sum(dataz.whatever)
FROM dataz
WHERE now() BETWEEN dataz.event_time - 7 days AND dataz.event_time
```
then .. if you introduced a record at or around its `event_time`, it probably wouldn't be reflected in the output for very long. To get that to happen would required (as far as I can tell) multi-temporal timestamps.

**Comment by ruchirK** [comment]
> I think one important part of using this is that you can't roll time backwards. So, everything ends up being from the moment you introduce the record, forward (we may end up advancing time, but never going backwards).

This makes sense! I think the key ingredient that lets this all work in a intuitive way for the end user is that `mz_logical_timestamp()` is approximately equal to the wall clock `now()` (and I suppose the query intervals are much larger than the `timestamp_frequency_ms`) -- like in a BYO setup this would all make less sense

**Comment by frankmcsherry** [comment]
Random noodling, but you also get a decent way to express "impulse" events:
```sql
SELECT data
FROM dataz
WHERE data.event_time = now()
```
I didn't describe how to handle equality (and it needs timestamps to e.g. now how to increment by one), but this would presumably transform append-only events into impulse events, without having to worry about issuing retractions.

**Comment by frankmcsherry** [comment]
> This makes sense! I think the key ingredient that lets this all work in a intuitive way for the end user is that mz_logical_timestamp() is approximately equal to the wall clock now() (and I suppose the query intervals are much larger than the timestamp_frequency_ms) -- like in a BYO setup this would all make less sense

TBH I think we should probably strike out `now()` as way too ambiguous, except as sugar in some hand-held situtations. `mz_logical_timestamp()` is the much more precise thing to use, and it continues to make sense in a BYO/CDC setting.

**Comment by frankmcsherry** [comment]
One immediate issue here is that `mz_logical_timestamp()` has type decimal, but our timestamps are `u64`.

**Comment by ruchirK** [comment]
I could imagine someone coming in and saying "I don't have an event time column in my data, but can I do something so that it just gets removed 6 hours after its ingested" and I think something like the operator you've sketched out would maybe work for that but I don't know if thats something we would want to support or what the right syntax would be.

My understanding is that the nice thing about having it be a predicate on the data is that we can filter out historical data, and we can reject late arriving events in a way thats probably more intuitive for a user but I'm not sure if the predicate bit is fundamentally important?

**Comment by frankmcsherry** [comment]
It seems to be important that the new time interval is a function of the data only (not the time) which is part of what makes retractions work out (imagine retracting a thing you've scheduled for deletion in six hours based on timestamp, and trying to figure out at what point in the future you should retract that deletion).

**Comment by ruchirK** [comment]
Naively, I was thinking that we could emit
```
(Row, time, +1)
```
and 
```
(Row, time + 6hrs, -1)
```
and then if we got a retraction at some later time `time + k`
then we would do the same as above and emit

```
(Row, time + k, -1),
(Row, time + k + 6hrs, +1)
```
which I guess has the unfortunate consequence that now `time + 6 hours` has a record with negative multiplicity, but then at `time + k + 6hours` things are back to normal? I'm not sure how bad that is and I'm also sure there's more to this that I'm missing rn. Another thought is: maybe intervals as a function of the time make sense for append-only sources?

**Comment by frankmcsherry** [comment]
> Another thought is: maybe intervals as a function of the time make sense for append-only sources?

I think this works badly with things like compaction. If we compact up an append-only source, then the retraction happens at a future time that depends on the compaction, which screws up determinism. There is probably a property that we can state about operators that implies determinism under compaction (e.g. that the logic applied to any compacted source emits the compaction of the output on the uncompacted source).

**Comment by frankmcsherry** [comment]
> like in a BYO setup this would all make less sense

I might be misinterpreting, but I think this makes *more* sense in a BYO setting. Here, you have to roll the dice and see if the RT timestamp we assign has any relation to the timestamps in your data. Maybe you put `+100` in your query, but we assigned a RT timestamp well past that so you just never get to see the data. This would have clearer semantics for BYO/CDC with explicit timestamps, where you could know whether the timestamp and the `valid_from` will line up or fight, rather than just crossing your fingers.

**Comment by ruchirK** [comment]
> I might be misinterpreting, but I think this makes more sense in a BYO setting. Here, you have to roll the dice and see if the RT timestamp we assign has any relation to the timestamps in your data. 

I totally agree with that. I was thinking about the very first framing of "people often want to use clock time `now()` in queries" -- and in cases like that it seemed like the important property that RT timestamps need to have is "be approximately equal to wall clock time". I agree that everything would be a lot clearer / saner in BYO-land but those folks wouldn't be part of the group that cared about clock time in their views (at least not in a way that makes sense to me)
