### ISSUE TITLE
Add note to CREATE TABLE to suggest using CREATE SOURCE if handling large amounts of streaming data

### ISSUE THREAD

**Issue by msudberg** [MaterializeInc/materialize#5626]
See [5611](https://github.com/MaterializeInc/materialize/issues/5611#issuecomment-774130902) -- a user ran into problems with the time it took to (re-)create materialized views on streaming data because they were using CREATE TABLE and running the queries on in-memory data, instead of using CREATE SOURCE. The CREATE TABLE documentation should advise using CREATE SOURCE instead for large quantities of streaming data.

**Comment by cirego** [comment]
We should be careful with this guidance. Using a source isn't necessarily a panacea.

The root cause of the issue was that they want to ingest more data than Materialize can fit into memory. This advice won't solve that problem if they're only inserting data.

**Comment by msudberg** [comment]
Superceded by 5634.
