### ISSUE TITLE
Materialize docs example fails to connect (auth undocumented?)

### ISSUE THREAD

**Issue by frankmcsherry** [MaterializeInc/materialize#5631]
It seems like we have authentication now, but our docs do not.
```
mcsherry@gallustrate materialize % psql -h localhost -p 6875 -d materialize          
psql: error: could not connect to server: Connection refused
        Is the server running on host "localhost" (::1) and accepting
        TCP/IP connections on port 6875?
FATAL:  role "mcsherry" does not exist
HINT:  Try connecting as the "materialize" user.
mcsherry@gallustrate materialize %                                         
```
The docs (https://materialize.com/docs/get-started/) have 
<img width="724" alt="Screen Shot 2021-02-05 at 4 11 45 PM" src="https://user-images.githubusercontent.com/5741500/107089595-e18c7500-67cc-11eb-88f6-386eaac35b4f.png">

**Comment by benesch** [comment]
We're in a bit of a bind here. This role stuff is new in v0.7.0, but v0.7.0 is not yet shipped. So the docs are correct for the last version, but not for the new version.

**Comment by cirego** [comment]
Why not update the docs now? The username would still be supported on older versions, correct?

**Comment by benesch** [comment]
Idk. Fridays, man. 🤦🏽‍♂️
