### ISSUE TITLE
sql: mz_logical_timestamp() returns a bogus value if used without a table context

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#5661]
### What version of Materialize are you using?

```
materialized v0.7.1-dev (dd01d9f90)
```

### What was the issue?

```mz_logical_timestamp()``` returns a bogus  value if used in a context where there is no underlying table:

### Is the issue reproducible? If so, please provide reproduction instructions.

```
materialize=> select mz_logical_timestamp() ;
 mz_logical_timestamp 
----------------------
 18446744073709551615
```

Contrast with use of same function with an actual table:

```
materialize=> select (select mz_logical_timestamp()) from v ;
 mz_logical_timestamp 
----------------------
        1612788696975
        1612788696975
```

**Comment by frankmcsherry** [comment]
I think this is technically "as intended" but I can understand not being impressed with that. :)

We fill in `mz_logical_timestamp()` with the timestamp we will use for the query, so it reports back "at what time am I answering this query". It also indirectly informs us at which time we are *able* to answer the query. In the first case we can produce an answer out at the end of time, whereas in the second cas we can't go any further than `v`.

I'm happy to leave this open until we think up a better way of explaining what `mz_logical_timestamp()` does that is less confusing! :D

**Comment by frankmcsherry** [comment]
For another example, I think you would see the same thing if you used a file source without the `WITH (TAIL = true)` option, which will read in a file as a static collection, valid for all time. Timestamps against that will also (I believe) shoot up to `u64::MAX`.

**Comment by philip-stoev** [comment]
Ok so this is to be expected then. Closing the ticket as I do not think this particular corner case deserves even a mention in the documentation.
