### ISSUE TITLE
mz_logical_timestamp() not properly printed in EXPLAIN

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#5662]
```
$ materialized -v
materialized v0.7.1-dev (dd01d9f90)
```

### What was the issue?

```mz_logical_timestamp``` is shown as ```0dec``` in the EXPLAIN. If anything, it should be in uppercase, preferably in blinking red on supported terminals.

### Is the issue reproducible? If so, please provide reproduction instructions.

```
materialize=> explain select mz_logical_timestamp();
  Optimized Plan   
-------------------
 %0 =             +
 | Constant (0dec)+
 
```

Same happens when ```mz_logical_timestamp``` is used in views ( in #5625) , in which context it is most definitely not a constant:

```materialize=> explain select * from temporal where  mz_logical_timestamp() < start_time ;
              Optimized Plan              
------------------------------------------
 %0 =                                    +
 | Get materialize.public.temporal (u305)+
 | Filter (0dec < i64todec(#1))          +
```

**Comment by frankmcsherry** [comment]
This is fixed as part of #5635 changing how `MzLogicalTimestamp` is substituted.
