### ISSUE TITLE
Expose kafka stats via system table

### ISSUE THREAD

**Issue by elindsey** [MaterializeInc/materialize#5666]
Currently mz can output detailed kafka stats when sources are created with `statistics_interval_ms`. This isn't very useful because it spews a pile of json into the log.

We've had requests to expose the kafka topic's high watermark via a system table (currently it's only in prometheus) - this is one way to address that.

Rough work is to modify the `ClientContext::stats` callback of `source/kafka.rs` to log to a new mz_kafka_stats table via the timely logger. The minimum data we need is topic, partition ID, current offset, and high watermark offset, but there may be other useful stats we're getting from rdkafka that can be plugged in as well (Krishna's a good person to ask about what are/aren't useful stats to record).

I'm slightly concerned about the overhead of running with these stats enabled. We may need to run it at a fairly high granularity (30s or so) or modify rdkafka to eg. not track latency histograms. Running a before/after benchmark via Chris' framework once we have a working impl may be the best way to determine that.

[This](https://github.com/MaterializeInc/materialize/pull/4572) PR may be a useful reference, it added some other logging from the sinks.

**Comment by cirego** [comment]
The statistics output is quite verbose, here is an example output, for a single consumer, from running the `avro-upsert` benchmark:

[sample.txt](https://github.com/MaterializeInc/materialize/files/6145238/sample.txt)

As Eli mentioned, we'll want to cut this down and likely start with the data he mentioned:

- topic
- partition id
- current offset
- high watermark offset

At the moment, the other metric that seems to make sense is `tx / rx bytes / messages`.

**Comment by cirego** [comment]
Quick update: `rdkafka` expects that `ClientContext` to satisfy the `Send + Sync` traits, as the context may be accessed from multiple threads. However, our `logger` as implemented, cannot be shared between threads. This will be slightly more complex than simply plumbing the logger into `GlueConsumerContext` and calling `log` in the callback.

**Comment by cirego** [comment]
Update: the PR is working and we have the ability to log metrics via `Logger`.

Before I finish the PR, I want to verify the metrics that we are collecting (and I'm also running a benchmark comparison). Topic and partition are properties of the Source and are not included in the statistics object. Additionally, those metrics are already captured in other tables. I'm tempted to leave them out of `mz_kafka_consumer_statistics`, since this table also has a foreign relation to `mz_source_info`.

The following information is available for the partition:

```
                4: Partition {
                    partition: 4,
                    broker: 1,
                    leader: 1,
                    desired: true,
                    unknown: false,
                    msgq_cnt: 0,
                    msgq_bytes: 0,
                    xmit_msgq_cnt: 0,
                    xmit_msgq_bytes: 0,
                    fetchq_cnt: 370038,
                    fetchq_size: 10588581,
                    fetch_state: "active",
                    query_offset: -2,
                    next_offset: 469264,
                    app_offset: 99226,
                    stored_offset: 99226,
                    committed_offset: 53388,
                    eof_offset: -1001,
                    lo_offset: 0,
                    hi_offset: 666464,
                    ls_offset: 666464,
                    consumer_lag: 567238,
                    txmsgs: 0,
                    txbytes: 0,
                    rxmsgs: 469264,
                    rxbytes: 17669085,
                    msgs: 469264,
                    rx_ver_drops: 0,
                    msgs_inflight: 0,
                    next_ack_seq: 0,
                    next_err_seq: 0,
                    acked_msgid: 0,
                },
```

It appears that we should be using per-partition metrics, since we assign a reader per partition. In this case, we should log:

- rxmsgs
- rxbytes
- txmsgs
- txbytes
- app_offset
- consumer_lag

**Comment by cirego** [comment]
I ran the avro-upsert benchmark with the existing PR to compare enabling metrics at 1-second intervals (`None`), compared with `main` and our previous releases. I stopped the run after a couple of rounds, so the data is a bit noisy and I'm running a smaller dataset. It appears to me that enabling kafka stats doesn't introduce much of a performance regression and I'll run the bigger benchmark overnight to verify.

![visualization](https://user-images.githubusercontent.com/551285/112058708-27e92980-8b18-11eb-87c6-f6e79de5c830.png)

**Comment by cirego** [comment]
I'm running a big benchmark now. Should have decent results in the morning!

**Comment by elindsey** [comment]
This is awesome! Could we add ls_offset to the table as well?

I wonder if having 0 for all the tx columns will be confusing for users. Those have meaning and will be non-zero for sinks, but don't mean much for sources. Perhaps we should drop them from this view?

cc @krishmanoh2 if you have thoughts on the above table or any other stats that would be immediately useful for Kafka sources (list of those available is here https://github.com/MaterializeInc/materialize/issues/5666#issuecomment-804342688)

**Comment by krishmanoh2** [comment]
This looks great! Could we add the below to the table?


rtt | object |   | Broker latency / round-trip time in microseconds. See Window stats below
lo_offset | int gauge |   | Partition's low watermark offset on broker
hi_offset | int gauge |   | Partition's high watermark offset on broker
ls_offset | int gauge |   | Partition's last stable offset on broker, or same as hi_offset is broker version is less than 0.11.0.0.

**Comment by cirego** [comment]
> This looks great! Could we add the below to the table?
> 
> rtt | object |   | Broker latency / round-trip time in microseconds. See Window stats below
> lo_offset | int gauge |   | Partition's low watermark offset on broker
> hi_offset | int gauge |   | Partition's high watermark offset on broker
> ls_offset | int gauge |   | Partition's last stable offset on broker, or same as hi_offset is broker version is less than 0.11.0.0.

Will do!

**Comment by cirego** [comment]
> > This looks great! Could we add the below to the table?
> > rtt | object |   | Broker latency / round-trip time in microseconds. See Window stats below
> > lo_offset | int gauge |   | Partition's low watermark offset on broker
> > hi_offset | int gauge |   | Partition's high watermark offset on broker
> > ls_offset | int gauge |   | Partition's last stable offset on broker, or same as hi_offset is broker version is less than 0.11.0.0.
> 
> Will do!
> 
> Clarification question on `rtt` -- that's a gauge, not a counter. The rest of these metrics are all counters. We can collect this but it'll be much more difficult for the user to consume. Are we still certain that we wish to collect this?

Oh, to complicate matters more -- `rtt` is actually a histogram and is a broker property, not a PartitionConsumer property:

```
            rtt: Some(
                Window {
                    min: 376,
                    max: 50037,
                    avg: 11974,
                    sum: 143689,
                    cnt: 12,
                    stddev: 19560,
                    hdrsize: 13424,
                    p50: 811,
                    p75: 1455,
                    p90: 48639,
                    p95: 48639,
                    p99: 50175,
                    p99_99: 50175,
                    outofrange: 0,
                },
            ),
```

I think `rtt` should be it's own PR if we want it.

**Comment by cirego** [comment]
And reading this more closely:

```
lo_offset | int gauge |   | Partition's low watermark offset on broker
hi_offset | int gauge |   | Partition's high watermark offset on broker
ls_offset | int gauge |   | Partition's last stable offset on broker, or same as hi_offset is broker version is less than 0.11.0.0.
```

Can these values actually go down as well as up?

**Comment by krishmanoh2** [comment]
rtt is valuable since it can help a customer figure out if mz or kafka is slowing down the ingest.

**Comment by cirego** [comment]
> rtt is valuable since it can help a customer figure out if mz or kafka is slowing down the ingest.

Hi Krishna, I agree that `rtt` is valuable. My comment is because `rtt` metrics are gathered on the `broker` object and not on per-partition. The table above is showing per-partition metrics. It seems to me that we'd need a new table to display `rtt` and that's why I think it should be its own PR.

**Comment by elindsey** [comment]
> Can these values actually go down as well as up?

These should only go up, even across broker failure/election
