### ISSUE TITLE
Eager subquery evaluation leads to unnecessary errors

### ISSUE THREAD

**Issue by frankmcsherry** [MaterializeInc/materialize#5670]
### What version of Materialize are you using?

```
$ materialized -v
materialized v0.7.1-dev
```

### How did you install Materialize?

* [ ] Docker image
* [ ] Linux release tarball
* [ ] APT package
* [ ] macOS release tarball
* [ ] Homebrew tap
* [x] Built from source

### What was the issue?

A subquery that shouldn't produce an error leads to an error. 

I believe the error is due to the "branch key" optimization, as discussion here (https://github.com/MaterializeInc/materialize/pull/2944/files). It removes some of the strictness of subquery evaluation, and replaces much of the work with a semijoin. However, this means that if results that would be discarded error along the way, we retain the errors even though we should never have evaluated them.

### Is the issue reproducible? If so, please provide reproduction instructions.

```materialize=> create table keys (key int8);
create table values (key int8, value int8);

insert into keys values (2);
insert into values values (1, 0);
insert into values values (2, 1);

select key, recip
from 
    keys,
    lateral (
        select 1/value as recip
        from values
        where values.key = keys.key
    );
CREATE TABLE
CREATE TABLE
INSERT 0 1
INSERT 0 1
INSERT 0 1
ERROR:  Evaluation error: division by zero
materialize=> 
```

**Comment by benesch** [comment]
I'm actually not convinced that our behavior here is incorrect. I mean, I agree it sucks as a user, but I don't think we have a proper specification for whether we will or will not evaluate a given expression. If I understand the PostgreSQL position correctly, they will happily rearrange `RelationExpr` nodes as long as they are algebraically equivalent, even if it changes whether or not a given error occurs.

Can we write down the property that we want to uphold? Is it something like "we will never defer a filter"?

cc @justinj

**Comment by frankmcsherry** [comment]
I don't mind either way, tbh. But I think the intent with subqueries is that they should be quite close to a for loop over the outer relation. If it is within spec to execute arbitrary other code, it seems like it would be within spec to always error on subqueries (we just eval'd 1/0 for no reason).

I'd feel bad publicly stating that we are ok with this erroring out:
```sql
create table values (key int8, value int8); 
insert into values values (1, 0);
insert into values values (2, 1);

select key, recip
from 
    (select key from values where value > 0) as keys,
    lateral (
        select 1/value as recip
        from values
        where values.key = keys.key
    );
```

**Comment by benesch** [comment]
> If it is within spec to execute arbitrary other code, it seems like it would be within spec to always error on subqueries (we just eval'd 1/0 for no reason).

Well, it's not _arbitrary_ other code. It's just that we can rewrite your expression into any algebraically equivalent form that we want, paying no mind to side effects. So if you didn't put an `x / y` in your query then we can't give you a division by zero error. If your underlying relation never contained `y = 0` then we also can't give you a division by zero error. But we _can_ push the filter around, i.e., there is no promise that we won't rewrite

```
SELECT x / y FROM foo WHERE y != 0
```

to:


```
SELECT * FROM (SELECT x / y FROM foo) WHERE y != 0
```

I'd be fine _making_ such a promise... I'm just not sure on how to state it? It does seem like a hard thing to prove that your optimizer upholds, but I'd feel better just being able to write down what it is that we are trying to uphold.

**Comment by benesch** [comment]
> I'd be fine _making_ such a promise... I'm just not sure on how to state it? It does seem like a hard thing to prove that we uphold, but I'd feel better just being able to write down what it is that we are trying to uphold.

@frankmcsherry @justinj any thoughts on this?

**Comment by frankmcsherry** [comment]
In this specific case, I think we could make the promise that the subquery is evaluated only for the keys present in the outer relation. We don't live up to that at the moment, but it's a clear enough thing to state. Informally, it would be nice to state that for a naive evaluation of your query: across each row in each relation, applying each filter, evaluating each subquery, we provoke no errors that would not be provoked in this naive execution.

**Comment by benesch** [comment]
I'm kicking this out of "Critical" because, while the current behavior is arguably undesirable, I believe it is defensible. There is also a workaround: wrap the division in a `CASE`. (And even if you think the current behavior is not "defensible", @frankmcsherry, I think we both agree that it's not important enough that it needs to jump the regular scheduling queue?)

I've instead dropped the issue into the 1.0 blockers list.

**Comment by ggevay** [comment]
https://github.com/MaterializeInc/materialize/issues/20769 might be one more case of this.

**Comment by ggevay** [comment]
Wait, this is not happening anymore on the current main. Note that the issue description is missing the definition of `keys`, but assuming it's `create table keys (key int8);`, the query runs through fine for me currently on 9e480a9d104d6a734937758062a787f4f217a20c.

But I'm not sure whether this is a happy thing, because I was hoping that this is the same issue as in https://github.com/MaterializeInc/materialize/issues/20769, and then we could have used the relatively simple repro from here to debug that other issue rather than that monster query there...
