### ISSUE TITLE
Enable dependabot for Docker Images

### ISSUE THREAD

**Issue by cirego** [MaterializeInc/materialize#5678]
We currently have Dependabot enabled for Cargo. @benesch and I were talking the other day and we
thought it would be a good idea to enable [Dependabot for Docker](https://dependabot.com/docker/).

This is related to another issue with our dockerfiles. Many of our images are based on older,
non-LTS Ubuntu releases and can no longer be rebuilt. Our CI only works due to build caching from
`mzbuild`. I'm not sure if Dependabot can help with this, but it's a datapoint to consider.

`MZFROM` presents a double-edged sword. We can have a small number of well-supported Dockerfiles
that get updated when there are security updates and the downstream projects can inherit these
updates via the `MZFROM` directive. However, I'm not sure how Dependabot would handle this MZFROM
keyword.

**Comment by alex-hunt-materialize** [comment]
It seems that Dependabot does not support multiple directories for a single action, so we'd have to specify the config separately for each directory (see https://github.com/dependabot/dependabot-core/issues/2824 and https://github.com/dependabot/dependabot-core/issues/2178 for more details). This will likely cause dozens of PRs every time the base image updates.

Given the above, we probably want to write our own scheduled Github Action to handle this for our common Ubuntu images (and maybe others).

We'd need to:
1. Query the docker API for a list of available tags.
2. Find the latest one matching a pattern.
3. Replace the strings in the Dockerfiles and/or mzbuild config files.
4. Open the PR.

That's obviously not as nice as having Dependabot manage it for us, but should work for our purposes.

**Comment by benesch** [comment]
Ooh, actually, I think a combination of Dependabot and mzcompose could do it, as Chris was alluding to above. The tl;dr is:

  1. Make a base image with the version of Ubuntu that we want to use. This will _look_ like a totally normal Dockerfile, even though it could use special mzcompose features.
  2. Change all the existing Dockerfiles to use `MZFROM base`.
  3. Configure Dependabot to update the base image periodically.

Do you have interest in tackling that, @alex-hunt-materialize? I think it's quite tractable, actually!

**Comment by alex-hunt-materialize** [comment]
Ah, that's a good idea. Do all our images use mzbuild? If so, that's pretty easy.

**Comment by benesch** [comment]
> Ah, that's a good idea. Do all our images use mzbuild? If so, that's pretty easy.

I believe so, yep.
