### ISSUE TITLE
transform: improve testing framework

### ISSUE THREAD

**Issue by benesch** [MaterializeInc/materialize#5684]
In https://github.com/MaterializeInc/materialize/pull/5565#issuecomment-772588754 we got a great new test of `transform` that couldn't use @justinj transform testing framework for the reasons @wangandi detailed here:

> > re the unit test: seems like it could be a good time to use @justinj's transform testing framework? https://github.com/MaterializeInc/materialize/blob/main/src/transform/tests/testdata/join-implementation
> 
> That was my first approach, but a couple of hours later, I figured that it is better to fix this earlier with a regression test in the file than to hold up the merge due to adding design discussions and a new round of reviews for changes to the testing framework.
> 
> The problem is that if you look at https://github.com/MaterializeInc/materialize/blob/main/src/transform/tests/test_runner.rs there are several components missing:
> 
> * `build_rel` does not support `FlatMap` or `Reduce`. In both of these, you specify a function name, and Materialize picks a more relevant function based on what the type of the column is.
> * `build_scalar` does not support parsing the `null` literal.
> * `build_scalar` does not support parsing anything other than `MirScalarExpr::Column` and `MirScalarExpr::Literal`, whereas I need `MirScalarExpr::CallBinary(BinaryFunc::Eq, ...)` for the test.
> 
> There's a TODO in the file that reads:
> 
> > // TODO(justin): is there some way to re-use the sql parser/builder for this?
> 
> I consider this the ideal solution, and I looked into this.
> 
> * The text -> sql tokens part is easy: `sql-parser::parse_expr`
> * The `HirScalarExpr` -> `MirScalarExpr` part is also easy: one calls `HirScalarExpr::lower_uncorrelated`.
> * The sql token -> `HirScalarExpr` part is non-trivial: the translation function is `plan_expr`, and I'd need to construct `ExprContext`, `QueryContext`, and `StatementContext`. I figured this part requires a longer discussion with you to discuss how to do it right, and whether or not I need to make `Dummy<thing>Context`s given the fact that `MirScalarExpr` are way simpler than `HirScalarExpr`. (If I have to make `Dummy<thing>Context`s, that's likely to require disruptive changes in the SQL layer. I think `DummyStatementContext` can be avoided if I just pass `StatementContext` something that implements the `Catalog` trait)
> 
> If the ideal solution is not feasible, then I figured it would still trigger a new round of reviews/design discussions as to what the new syntax should be which is better fixed in another PR.

This issue is to track these improvements.

**Comment by wangandi** [comment]
Oops forgot to think about this when the slack channel was filled with questions on how query plans worked.
We should add the additional progress on this from the slack discussion:
* My impression of the consensus is that we should construct `MirScalarExpr`s using a more direct route than text -> sql-token ->`HirScalarExpr`-> `MirScalarExpr`.
* My impression of the consensus is that at least in the initial version, the syntax should require the test-writer to manually specify the type of null or the type of `Table/AggregateFunc`, e.g. it is up to the test-writer to select between `SumInt32` and `SumInt64`
* We should be able to generate string/sexpr to enum constructors. We shouldn't use `strum`.
* Can we reduce the verbosity of the sexpr translation code?

**Comment by benesch** [comment]
Awesome, thanks Andi! Hopefully this jumpstarts discussion whenever someone
gets the chance to work on this.

**Comment by wangandi** [comment]
Done in #7118 and #7126. Design doc is at #6922.
