### ISSUE TITLE
Bintray being deprecated

### ISSUE THREAD

**Issue by awang** [MaterializeInc/materialize#5689]
We need to migrate to an alternative solution by July 4:   

https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

**Comment by cirego** [comment]
I was looking into this for a bit today and it appears that we can host debian packages in an S3 bucket.

The best option that I found was https://github.com/aptly-dev/aptly, which appears to be actively maintained and has documentation on [how to publish to S3](https://www.aptly.info/doc/feature/s3/). One can also run the `aptly` CLI from within a Docker container, meaning that we should be able to publish directly from buildkite without too much effort (we can give buildkite agents permissions to write to the S3 bucket).

Two other alternatives that exist but are no longer maintained, are https://github.com/brianm/apt-s3/ and https://github.com/krobertson/deb-s3.

**Comment by mattfox** [comment]
If you prefer a hosted solution rather than figuring out the bits and pieces yourself, I'd invite you to try my service [Balto Repo](https://www.getbalto.com/debian.html). Compared to the S3 bucket you'd also get a web site for the repo and analytics about usage.

**Comment by awang** [comment]
i think this is done, @umanwizard feel free to reopen if i'm wrong

**Comment by benesch** [comment]
Yes, it's done, thanks!
