### ISSUE TITLE
timestamps: increase batch size when source falls behind

### ISSUE THREAD

**Issue by benesch** [MaterializeInc/materialize#5690]
See #3822, which went stale and got closed. The intent is still sound: to increase timestamp batch sizes if we detect that we're not keeping up with a source, since Timely can be more efficient when updates are larger.

/cc @ruchirK @frankmcsherry

**Comment by frankmcsherry** [comment]
I think #3822 was meant as a solution to https://github.com/MaterializeInc/materialize/issues/2310, which is still open. We might want refine this a bit, or just re-up that issue.

**Comment by benesch** [comment]
Oh, thanks, that never got linked up properly to #3822. Closing this in favor of #2310.
