### ISSUE TITLE
Sources with custom delimiters.

### ISSUE THREAD

**Issue by umanwizard** [MaterializeInc/materialize#5711]
Problem: For sources that produce a stream of bytes (like S3/files), we can't in general assume that records will be delimited by newlines. They may require decoding of the underlying format in order to understand where one record ends and the next begins (e.g.: a file might consist of a series of Json records with no delimiter between them).

One possible API design is to split these into two parts:

```
trait ByteStreamSource {
    fn read_next_chunk(&mut self, out: &mut Vec<u8>);
}

trait ByteStreamDelimiter {
    // Read a chunk of bytes, and consume it if possible, producing a `Row`.
    fn process(&mut self, in: &mut Vec<u8>) -> Option<Row>;
}
```

`ByteStreamSource` would be inhabited by `S3Source`, `FileSource`, etc., and `ByteStreamDelimiter` by `NewlineDelimiter`, JsonRecordBoundaryDelimiter`, `AvroRecordBoundaryDelimiter`, etc.

**Comment by benesch** [comment]
Closing as stale. We no longer support byte-oriented sources.
