### ISSUE TITLE
Avro OCF sources seem to use a lot more memory than the corresponding kafka source

### ISSUE THREAD

**Issue by ruchirK** [MaterializeInc/materialize#5713]
A user found this after running avro ocf debezium formatted source and seeing a pretty large memory overhead - when I tried to duplicate their workload on Kafka I saw ~1 / 3 as much memory usage (running both workloads on my laptop with 16 workers). They also saw a pretty significant memory reduction by using Kafka.

This bug report needs more specific repro instructions, but putting this so other users who've run into this can chime in.

**Comment by morsapaes** [comment]
We no longer support Avro OCF as a source.
