### ISSUE TITLE
Allow non-append-only tables via `INSERT [WITH DIFF]` or similar syntax.

### ISSUE THREAD

**Issue by umanwizard** [MaterializeInc/materialize#5718]
Discussion in Slack: https://materializeinc.slack.com/archives/CMHDK0DK8/p1612984044452900

The proposal is to allow syntax like 
```
-- delete the "foo" row
INSERT WITH DIFF INTO table
VALUES
    ('foo', -1);
```
 to create not-necessarily-append-only collections without requiring a dependency on Kafka or anything else.

**Comment by philip-stoev** [comment]
This feature will be very much welcome. Would it be possible to put the -1 as an argument after DIFF so that it is not a part of the value list and the value list remains conforming to PostgreSQL. This will make generating such INSERT statements easier for the various fuzz frameworks.

**Comment by umanwizard** [comment]
@philip-stoev what if you want to insert some values with different diffs ? E.g.

```
-- update (1, 'foo') to (1, 'bar')

INSERT WITH DIFF INTO table
VALUES
    (1, 'foo', -1),  (1, 'bar', 1);
```

**Comment by philip-stoev** [comment]
@umanwizard . Good point. how about ```INSERT INTO table VALUES (1, 'foo') WITH DIFF -1 , (1, 'bar') WITH DIFF 1;```?

Anyway, whatever you come up with will be useful, I will figure the generation of compatible statements on my side.

**Comment by benesch** [comment]
This got done. We support tables and you can use the (private) `repeat_row` function to insert negative data into them. Alternatively you can use the SQL standard `UPDATE` and `DELETE` commands.
