### ISSUE TITLE
[orthogonality] Make avro/protobuf/etc. decoding a stage in the ingest pipeline rather than doing it with custom code

### ISSUE THREAD

**Issue by umanwizard** [MaterializeInc/materialize#5720]
Decoding is just a function from a row to a (set of) rows, so it should be expressible as `HirRelationExpr::FlatMap` .

This won't apply cleanly to Avro OCF files, since decoding the avro needs to be done as part of parsing out the records anyway. That situation might get better after https://github.com/MaterializeInc/materialize/issues/5711 lands.

**Comment by quodlibetor** [comment]
This also affects s3 sources, which also need to parse objects to know how to send rows into dataflow, and also eventually we probably eventually want e.g. multi-row kafka messages.

**Comment by benesch** [comment]
Closing as stale. The orthogonality work is largely completed.
