### ISSUE TITLE
[orthogonality] Move source caching and timestamping to run at the end of the source transform.

### ISSUE THREAD

**Issue by umanwizard** [MaterializeInc/materialize#5722]
I.e., these operations should happen at the barrier between the ingest pipeline and the rest of the system.

We would still need some kind of custom logic per source to tell the source caching layer how to re-hydrate the stateful bits (e.g. upsert, dbz dedupe, ...) which are now expressed relationally, as views. I'm not too sure of the best way to do this. One mostly half-baked idea: maybe expose a function on RelationExpr that computes what data is necessary for source caching, for each node in the IR?

This is closely related to https://github.com/MaterializeInc/materialize/issues/4566 and probably a prerequisite for it.

**Comment by umanwizard** [comment]
Cc @ruchirK

**Comment by ruchirK** [comment]
source caching was removed in #7328 - not sure if that means we should close this issue. We are figuring out the product definition and engineering work for "source persistence" and "view persistence" and how it might interact with ingest dataflows, but all of that code is going to be built on the new persist core and have nothing to do with source caching.
