### ISSUE TITLE
Push `Reduce` through `Join`

### ISSUE THREAD

**Issue by frankmcsherry** [MaterializeInc/materialize#573]
We should be able to push reduce operators through joins, in certain circumstances.

In particular, if any aggregation has support that is restricted to one of the input relations, we can push the reduce into the input where we reduce by the restriction of the reduce keys to those in the input. We then join things back up, and *probably* this all works out.

Probably.

**Comment by frankmcsherry** [comment]
This is not especially well detailed, but there is some supporting work in papers. Roughly, for a Reduce around a multi-way Join, each of the inputs can be pre-reduced using a reduction that contains the reduce keys, any columns used by predicates in between, and potentially some further detail to be able to recombine the reduced information. 

For example, to push a `Sum` down through a join to one of the inputs, we could perform the sum on that input, as long as the grouping contains enough keys to perform the join, but also we would need to preserve the counts for the corresponding keys in the other inputs, in order to multiply by the sum to get the correct answer. Generally, it seems we can integrate out irrelevant columns (we do this a bit already with the `Demand` analysis) and ideally collapse down aggregates that would otherwise have their contributing values maintained in the join state.

**Comment by cuongdo** [comment]
Moving this to 0.6, because we believe this to be a generally useful optimization that would have reduced Materialize's memory use for recent deployments.
