### ISSUE TITLE
Types for `AS OF` and `mz_logical_timestamp()` are different

### ISSUE THREAD

**Issue by frankmcsherry** [MaterializeInc/materialize#5730]
Our timestamp types are `u64` and `mz_logical_timestamp()` is `numeric`. This results in some weird situations where you can compare negative or large numbers to `mz_logical_timestamp()` but if you try and use them in `AS OF` you get an error instead.

Reported by @ruchirK

**Comment by benesch** [comment]
So the problem here is that PostgreSQL (and therefore Materialize) does not support unsigned integer types. So we have no way of representing the full range of a `u64` without resorting to `numeric`.

**Comment by benesch** [comment]
Er, not saying there aren't specific things we can do to make this better! But it's kind of thorny.

**Comment by frankmcsherry** [comment]
Yup, just recording the issue as reported by Ruchir, so that it doesn't block my PR. :)

**Comment by philip-stoev** [comment]
There is another type incompatibility:

If we have a column that is reasonably defined as:

```
DATE_PART('epoch', ("data"::"pg_catalog"."jsonb" ->> 'ts')::"pg_catalog"."timestamp") * 1000 AS "ts"
```

This column's type is ```double precision``` and thus it can not be compared directly to ```mz_logical_timestamp()``` and the error message is not helpful:

```
materialize=>  create materialized view v3 as select * from v2 where mz_logical_timestamp() > ts + 3600000;
ERROR:  "Unsupported temporal predicate: `mz_logical_timestamp()` must be directly compared to a non-temporal expression"
```

**Comment by frankmcsherry** [comment]
@mjibson is this in any way improved with the new `mz_timestamp` type?

**Comment by mjibson** [comment]
Much of this is improved: there's no more reason to use `extract(epoch ...)`, and `AS OF` now requires a thing that can be losslessly converted to the same type that `mz_now()` produces, removing the possibility of users writing fractions or negatives (although I wonder if it actually just moves the error around somehow?). It's at least much less ambiguous, and we could make some ergonomic changes if needed. I think we could reasonably close this issue and open new ones as we discover usage difficulties of the new `mz_timestamp` type.

**Comment by frankmcsherry** [comment]
That sounds great! I'll close for now, and we can open new issues as you say!
