### ISSUE TITLE
Discussion: adding new source metadata tables for different source types

### ISSUE THREAD

**Issue by quodlibetor** [MaterializeInc/materialize#5733]
Currently sources don't have access to their own tables, but different sources _do_ have metadata that is uniform to a source type. Brought in https://github.com/MaterializeInc/materialize/issues/5502#issuecomment-770948130, I'm copy/pasting the comment here:

I was imagining a larger refactor (or really creation) of metadata tables for sources. Right now for each of our input sources we insert one column of metadata, that is differently named for each source type.

I am thinking that we should instead insert two columns -- both of which are always the same name -- something like `mz_record_no` and `mz_metadata_id` and then create a metadata table per source-type (as well as a mapping table), so that we end up with, for S3:

```
 +---------------|--------------|-----------------+
 | <source_cols> | mz_record_no | mz_metadata_id  |
 |               | 1            | 1               |
 |               | 2            | 1               +-
 |               | 3            | 1               | \--
 |               | 4            | 2               |    \--
 +---------------|--------------|-----------------+       \--
                                                              \--
                                                                 \--
                                                      +-------------\+----------------+
                                                      | source_table | metadata_table |
                                                      | public.ex    | materialize.ex |
 +----+--------+--------+-----------------+           +--------------+----------------+
 | id | bucket | object | object_complete |                ------/
 | 1  | ex     | a.csv  | true            |          -----/
 | 2  | ex     | b.csv  | false           |    -----/
 |    |        |        |                 |<--/
 |    |        |        |                 |
 +----+--------+--------+-----------------+
```

Once we have access to the catalog from sources, similar tables could and should be created to track metadata about sources -- e.g. partition count, topic name for kafka, buckets, objects, sqs queues connected for s3, etc.

**Comment by guswynn** [comment]
This metadata has ended up in different tables (various `mz_internal` ones, and `_progress` subsources, so this can be closed!
