### ISSUE TITLE
dataflow: improve tail sending

### ISSUE THREAD

**Issue by mjibson** [MaterializeInc/materialize#5737]
#5660 happened (we believe) because a tail send happened after a portal had been destroyed (and thus the receiver went away) before the drop sink propagated down. The new unbounded comm code makes that not a problem because if the unbounded receiver is dropped, the sender will return an error which is handled by the current tail.rs, and a drop sink should be coming imminently to clean it up even though it also entered some error state (which we're not convinced is good).

We should improve tail send so we can always use .unwrap such that things always flow in one direction. That is, there's no information flowing into sender from the receiver. This will probably involve actively draining destroyed portals.

**Comment by benesch** [comment]
Seems to me like this got done in https://github.com/MaterializeInc/materialize/pull/7628/files.
