### ISSUE TITLE
Temporal Filters - Not working in material views together with kafka

### ISSUE THREAD

**Issue by macthestack** [MaterializeInc/materialize#5745]
I'm not expecting these two queries to behave differently.

```
CREATE MATERIALIZED VIEW test1 AS SELECT * FROM s_test WHERE mz_logical_timestamp() >= 0
---
SELECT COUNT(*) FROM test1
+---------+
| count   |
|---------|
| 0       |
+---------+
```
```
CREATE MATERIALIZED VIEW test2 AS SELECT * FROM s_test
---
SELECT COUNT(*) FROM test2
+---------+
| count   |
|---------|
| 3035    |
+---------+
```

I spoke with @frankmcsherry on slack and he gave me a few queries that ran well - using a table as source - which is why "kafka" is in the title.

I'm only seeing this in views. Queries like this work:

```
SELECT COUNT(*) FROM s_test WHERE mz_logical_timestamp() > 0 AS OF now() + '5s'
+---------+
| count   |
|---------|
| 4203    |
+---------+
```

My actual use case looks something like this:

```
CREATE MATERIALIZED VIEW test AS SELECT * FROM s_test WHERE mz_logical_timestamp() < ts + 5000
```

**Comment by macthestack** [comment]
The source is created in this fashion:

```
CREATE SOURCE s_test FROM KAFKA BROKER ''
       TOPIC 'test'
       WITH (
           timestamp_frequency_ms = 100,
           security_protocol = 'sasl_ssl',
           sasl_mechanisms = 'plain',
           sasl_username = '',
           sasl_password = ''
       )
 FORMAT AVRO USING SCHEMA '{
     "type": "record",
     "name": "Test",
     "namespace": "test",
     "fields": [
         {
             "name": "ts",
             "type": "long"
         },
     ]
 }'
 ENVELOPE UPSERT FORMAT TEXT;
```

**Comment by frankmcsherry** [comment]
Well, that *should* work. :)  I'm not sure the right next debugging step; by the time they hit this operator there isn't a difference I know between Kafka and table sources. It would be great to see something like
```sql
SELECT ts, mz_logical_timestamp()
FROM s_test
LIMIT 5
```
just to take a peek at what sort of values we are looking at, if you don't mind.

**Comment by frankmcsherry** [comment]
Ah, another distinction is that you are using an `UPSERT` source, and we have some logic for pushing down predicates that I may have broken. Lemme look into that.

**Comment by macthestack** [comment]
Running your query gives me 

```
Unable to automatically determine a timestamp for your query; this can happen if your query depends on non-materialized sources.
For more details, see https://materialize.com/s/non-materialized-error
```

I can run this though:

```
SELECT ts, mz_logical_timestamp()
 FROM s_test
 LIMIT 5 AS OF now() + '5s'
+---------------+------------------------+
| ts            | mz_logical_timestamp   |
|---------------+------------------------|
| 1613136068608 | 1613139272803          |
| 1613136598016 | 1613139272803          |
| 1613136862208 | 1613139272803          |
| 1613136732416 | 1613139272803          |
| 1613136732416 | 1613139272803          |
+---------------+------------------------+
```

**Comment by frankmcsherry** [comment]
Sorry, if you could remove the `UPSERT` and either make it a `CREATE MATERIALiZED SOURCE` or use `CREATE INDEX` to materialize it. The upsert sources automatically materialize themselves, which (should) allow them to answer queries without an `AS OF`. If not then something is broken (on our end).

**Comment by frankmcsherry** [comment]
I think we've shaken out some of the bugs in https://github.com/MaterializeInc/materialize/pull/5748 and https://github.com/MaterializeInc/materialize/pull/5750, when they land. These were moments where temporal predicates slipped through and got evaluated by code that didn't understand what was supposed to happen.

**Comment by frankmcsherry** [comment]
They are all merged into `main` now (as are temporal filters themselves). Feel free to check it out when you get a chance; I'm writing kafka upsert tests right now.

**Comment by macthestack** [comment]
Thanks Frank, I was haven't yet had the time to take out the upserts but will jump straight to the new main to check it out.

**Comment by macthestack** [comment]
It works! Brilliant!
