### ISSUE TITLE
catalog corruption: migration fails to normalize functions inside derived tables

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#5802]
### What version of Materialize are you using?

```
materialized v0.7.1-dev (473f7c3c0)
materialized v0.3.1-dev (86637771e)
```

### What was the issue?

Upgrading from an older Materialize version to the latest one fails because a function reference inside a derived table is not normalized.

### Is the issue reproducible? If so, please provide reproduction instructions.

In the old version, create a view that references functions in various places in the view definition:

```
 create materialized view v1 as select  convert_from(cast(null as bytea),'utf-8') FROM (select convert_from(cast(null as bytea),'utf-8')) where convert_from(cast(null as bytea),'utf-8') is not null; 
```

Upgrade to new version:

```
materialized: corrupt catalog: failed to deserialize item u3 (materialize.public.v1): unknown catalog item 'convert_from'
```

The view definition in sqlite is:

```
CREATE VIEW \"materialize\".\"public\".\"v1\" AS SELECT \"pg_catalog\".\"convert_from\"(NULL::\"pg_catalog\".\"bytea\", 'utf-8') FROM (SELECT \"convert_from\"(NULL::\"pg_catalog\".\"bytea\", 'utf-8')) WHERE \"pg_catalog\".\"convert_from\"(NULL::\"pg_catalog\".\"bytea\", 'utf-8') IS NOT NULL
```
All the references to ```convert_from``` have been normalized escept the one in the SELECT list of the derived table.

**Comment by benesch** [comment]
Oh _brilliant_ Philip! Thanks for tracking this down.

**Comment by benesch** [comment]
@sploiselle this should drop into the `catcompatck` script pretty neatly, I think?

**Comment by sploiselle** [comment]
@benesch Yep––almost done
