### ISSUE TITLE
catalog corruption: Functions inside CREATE SINK AS OF are not normalized

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#5808]
### What version of Materialize are you using?

```
materialized v0.7.1-dev (60b75bb28)
```

### What was the issue?

Even after  closing #5802 via #5804, the catalog file attached fails to load:

```
materialized: corrupt catalog: failed to deserialize item u269 (materialize.public.sink_mv_buy_activity_time): function now() does not exist
``` 

The definition is as follows:

```
{"User":269}|3|sink_mv_buy_activity_time|{"V1":{"create_sql":"CREATE SINK \"materialize\".\"public\".\"sink_mv_buy_activity_time\" FROM \"materialize\".\"public\".\"mv_buy_activity_time\" INTO AVRO OCF '/data/mz/sinks/sink_mv_buy_activity_time.ocf' WITH SNAPSHOT AS OF \"now\"()","eval_env":{"logical_time":null,"wall_time":"2020-12-04T18:24:55.430979578Z"}}}
```
So ```NOW()``` is being used inside a ```CREATE SINK``` definition.

There may be other non-select-query where a function could end up, e.g. in the DEFAULT clause of CREATE TABLE, in an expression inside a CREATE INDEX, etc., like the ones identified in the comments of #5679

### Is the issue reproducible? If so, please provide reproduction instructions.

Load the attached catalog file. 
[catalog.zip](https://github.com/MaterializeInc/materialize/files/6004938/catalog.zip)

**Comment by benesch** [comment]
Eep! @sploiselle we should be able to stuff this into the migration you just wrote before v0.7.1 ships.
