### ISSUE TITLE
sql: support log/exp

### ISSUE THREAD

**Issue by elindsey** [MaterializeInc/materialize#5812]
Add support for the log/exp operators https://www.postgresql.org/docs/13/functions-math.html

These are likely needed for histogram support, though that hasn't been specced out yet. Good to support either way!

**Comment by frankmcsherry** [comment]
Probably related to: https://github.com/MaterializeInc/materialize/issues/5329

**Comment by andrioni** [comment]
This also helps with the pattern of using `exp(sum(ln(column)))` as an aggregation function for multiplication.
