### ISSUE TITLE
Avoid usage of static Prometheus metrics

### ISSUE THREAD

**Issue by benesch** [MaterializeInc/materialize#5825]
Static prometheus metrics are global mutable state, which should be avoided whenever possible. We talked about this a while back in Slack, though I can't find the conversation now. The alternative is to plumb a bunch of metrics structs around that all ultimately hang of `materialized::Server`. In particular, this makes metrics meaningful when running multiple servers within one process, like we do for unit tests.

I have a branch somewhere that I can dust off, though it's probably rotted quite a bit at this point.

cc @quodlibetor

**Comment by quodlibetor** [comment]
I would support doing this in the abstract, the fact that they need to be plumbed through the entire system makes it plausible that adding new metrics can become meaningfully-enough worse that the tradeoffs here might be different.

In general I think the difference between metrics and general global mutable state is that nothing should ever make a decision based on the existence of metrics -- they're not configuration, they're essentially an append-only hashmap. That difference is big enough to make the global state antipattern more bearable here.

**Comment by quodlibetor** [comment]
Again, though, I support at least exploring it.

**Comment by benesch** [comment]
Just to make my position clearer: I don't think this is something that needs to be explored. Rather I think it is imperative! I would like to solve this sooner rather than later, so that that task of destatic-izing these metrics does not get dauntingly large.
