### ISSUE TITLE
Crash on creating upsert sink

### ISSUE THREAD

**Issue by krishmanoh2** [MaterializeInc/materialize#5826]
### What version of Materialize are you using?

0.7.1 dev

### How did you install Materialize?

Compiled from source

### What was the issue?

Mz crash on creating an upsert sink

### Is the issue reproducible? If so, please provide reproduction instructions.

Unsure

### Please attach any applicable log files.

materialize=> select count(1) from repl_test_v;
  count   
----------
 16777216
(1 row)

-- Looks like the error message below could be better. I missed http for the schema registry. 

materialize=> create sink sink_repl_test from repl_test_v into kafka broker 'compute2:9092' topic 'sink_repl_test_topic' with("partition_count"=1) format avro using confluent schema registry 'compute2:8081' envelope upsert with snapshot;
ERROR:  error registering kafka topic for sink: unable to publish value schema to registry in kafka sink: transport: builder error for url (compute2:%2Fsubjects/sink_repl_test_topic-u74-1613582123-10664451505501098025-value/versions): URL scheme is not allowed: builder error for url (compute2:%2Fsubjects/sink_repl_test_topic-u74-1613582123-10664451505501098025-value/versions): URL scheme is not allowed: URL scheme is not allowed

materialize=> create sink sink_repl_test from repl_test_v into kafka broker 'compute2:9092' topic 'sink_repl_test_topic' with("partition_count"=1) format avro using confluent schema registry 'http://compute2:8081' envelope upsert with snapshot;
CREATE SINK

On the kafka side, I see 2 topics for the sink. Not sure why.

2021-02-19T23:18:35.887312Z ERROR panic: primary key error: expected at most one DiffPair per timestamp
thread: timely:work-1
location: /home/mz/mz_binaries/materialize/src/ore/src/collections.rs:58:18
version: 0.7.1-dev (473f7c3c0bb5a65a3e86bbb26263a146379a1445)
backtrace:
   0: materialized::handle_panic
             at /home/mz/mz_binaries/materialize/src/materialized/src/bin/materialized/main.rs:612:21
   1: core::ops::function::Fn::call
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/core/src/ops/function.rs:70:5
   2: std::panicking::rust_panic_with_hook
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panicking.rs:597:17
   3: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panicking.rs:499:13
   4: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/sys_common/backtrace.rs:141:18
   5: rust_begin_unwind
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panicking.rs:495:5
   6: std::panicking::begin_panic_fmt
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panicking.rs:437:5
   7: <T as ore::collections::CollectionExt<T>>::expect_element
             at /home/mz/mz_binaries/materialize/src/ore/src/collections.rs:58:18
   8: interchange::envelopes::upsert_format
             at /home/mz/mz_binaries/materialize/src/interchange/src/envelopes.rs:145:14
   9: dataflow::render::<impl dataflow::render::context::Context<timely::dataflow::scopes::child::Child<G,<G as timely::dataflow::scopes::ScopeParent>::Timestamp>,expr::relation::MirRelationExpr,repr::row::Row,u64>>::export_sink::{{closure}}
             at /home/mz/mz_binaries/materialize/src/dataflow/src/render/mod.rs:760:29
      differential_dataflow::collection::Collection<G,D,R>::map::{{closure}}
             at /home/mz/.cargo/git/checkouts/differential-dataflow-d065d23d797aa027/2b12f29/src/collection.rs:83:46
      <timely::dataflow::stream::Stream<S,D> as timely::dataflow::operators::map::Map<S,D>>::map::{{closure}}::{{closure}}::{{closure}}::{{closure}}
             at /home/mz/.cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/1cbfc99/timely/src/dataflow/operators/map.rs:57:78
      core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &mut F>::call_once
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/core/src/ops/function.rs:280:13
      core::option::Option<T>::map
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/core/src/option.rs:453:29
      <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::next
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/core/src/iter/adapters/mod.rs:924:9
      timely::dataflow::channels::pushers::buffer::Session<T,D,P>::give_iterator
             at /home/mz/.cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/1cbfc99/timely/src/dataflow/channels/pushers/buffer.rs:105:21
      <timely::dataflow::stream::Stream<S,D> as timely::dataflow::operators::map::Map<S,D>>::map::{{closure}}::{{closure}}::{{closure}}
             at /home/mz/.cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/1cbfc99/timely/src/dataflow/operators/map.rs:57:17
      timely::dataflow::operators::generic::handles::InputHandle<T,D,P>::for_each
             at /home/mz/.cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/1cbfc99/timely/src/dataflow/operators/generic/handles.rs:92:13
      <timely::dataflow::stream::Stream<S,D> as timely::dataflow::operators::map::Map<S,D>>::map::{{closure}}::{{closure}}
             at /home/mz/.cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/1cbfc99/timely/src/dataflow/operators/map.rs:55:13
      <timely::dataflow::stream::Stream<G,D1> as timely::dataflow::operators::generic::operator::Operator<G,D1>>::unary::{{closure}}::{{closure}}
             at /home/mz/.cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/1cbfc99/timely/src/dataflow/operators/generic/operator.rs:402:17
      timely::dataflow::operators::generic::builder_rc::OperatorBuilder<G>::build::{{closure}}::{{closure}}
             at /home/mz/.cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/1cbfc99/timely/src/dataflow/operators/generic/builder_rc.rs:123:31
      timely::dataflow::operators::generic::builder_rc::OperatorBuilder<G>::build_reschedule::{{closure}}
             at /home/mz/.cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/1cbfc99/timely/src/dataflow/operators/generic/builder_rc.rs:163:26
      <timely::dataflow::operators::generic::builder_raw::OperatorCore<T,L> as timely::scheduling::Schedule>::schedule
             at /home/mz/.cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/1cbfc99/timely/src/dataflow/operators/generic/builder_raw.rs:203:9
  10: timely::progress::subgraph::PerOperatorState<T>::schedule
             at /home/mz/.cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/1cbfc99/timely/src/progress/subgraph.rs:655:30
  11: timely::progress::subgraph::Subgraph<TOuter,TInner>::activate_child
             at /home/mz/.cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/1cbfc99/timely/src/progress/subgraph.rs:338:26
      <timely::progress::subgraph::Subgraph<TOuter,TInner> as timely::scheduling::Schedule>::schedule
             at /home/mz/.cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/1cbfc99/timely/src/progress/subgraph.rs:304:17
  12: timely::progress::subgraph::PerOperatorState<T>::schedule
             at /home/mz/.cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/1cbfc99/timely/src/progress/subgraph.rs:655:30
  13: timely::progress::subgraph::Subgraph<TOuter,TInner>::activate_child
             at /home/mz/.cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/1cbfc99/timely/src/progress/subgraph.rs:338:26
      <timely::progress::subgraph::Subgraph<TOuter,TInner> as timely::scheduling::Schedule>::schedule
             at /home/mz/.cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/1cbfc99/timely/src/progress/subgraph.rs:304:17
  14: timely::worker::Wrapper::step::{{closure}}
             at /home/mz/.cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/1cbfc99/timely/src/worker.rs:693:57
      core::option::Option<T>::map
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/core/src/option.rs:453:29
      timely::worker::Wrapper::step
             at /home/mz/.cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/1cbfc99/timely/src/worker.rs:693:26
  15: timely::worker::Worker<A>::step_or_park
             at /home/mz/.cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/1cbfc99/timely/src/worker.rs:375:38
  16: dataflow::server::Worker<A>::run
             at /home/mz/mz_binaries/materialize/src/dataflow/src/server.rs:436:13
  17: dataflow::server::serve::{{closure}}
             at /home/mz/mz_binaries/materialize/src/dataflow/src/server.rs:197:13
      timely::execute::execute::{{closure}}
             at /home/mz/.cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/1cbfc99/timely/src/execute.rs:284:22
      timely_communication::initialize::initialize_from::{{closure}}
             at /home/mz/.cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/1cbfc99/communication/src/initialize.rs:285:33
      std::sys_common::backtrace::__rust_begin_short_backtrace
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/sys_common/backtrace.rs:125:18
  18: std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}}
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/thread/mod.rs:474:17
      <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panic.rs:322:9
      std::panicking::try::do_call
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panicking.rs:381:40
      std::panicking::try
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panicking.rs:345:19
      std::panic::catch_unwind
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panic.rs:396:14
      std::thread::Builder::spawn_unchecked::{{closure}}
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/thread/mod.rs:473:30
      core::ops::function::FnOnce::call_once{{vtable.shim}}
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/core/src/ops/function.rs:227:5
  19: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/alloc/src/boxed.rs:1307:9
      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/alloc/src/boxed.rs:1307:9
      std::sys::unix::thread::Thread::new::thread_start
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/sys/unix/thread.rs:71:17
  20: start_thread
  21: __clone
    
[mz@compute1vm2 logs]$

**Comment by umanwizard** [comment]
16777216 is a very interesting number. It's the first 32-bit float with the property that incrementing it by 1 is a no-op.

How are you generating the data?

**Comment by krishmanoh2** [comment]
I loaded 16M rows using insert as select on Postgres.  Replication from postgres using debezium envelope. It is a 3 column table. 

materialize=# select count(1) from repl_test;
  count   
----------
 16777216
(1 row)

materialize=# \d+ repl_test;
                                        Table "public.repl_test"
 Column |         Type          | Collation | Nullable | Default | Storage  | Stats target | Description 
--------+-----------------------+-----------+----------+---------+----------+--------------+-------------
 id     | integer               |           | not null |         | plain    |              | 
 id2    | integer               |           |          |         | plain    |              | 
 id3    | character varying(10) |           |          |         | extended |              | 
Indexes:
    "repl_test_pkey" PRIMARY KEY, btree (id)
Replica Identity: FULL
Access method: heap

I materialize the source on mz.

**Comment by krishmanoh2** [comment]
I did not see an option to specify the key in the syntax. As customer, I would assume that I have the ability to pick a key.

How is the key picked today?

**Comment by umanwizard** [comment]
@wangandi how do we specify the key when creating an upsert source? Indeed, I can't find this easily in the docs.

**Comment by wangandi** [comment]
https://materialize.com/docs/sql/create-source/avro-kafka/#key-columns

Does this help?

Since the upsert source is always a kafka source, the key is always the set of columns that are contained in the key of the kafka record.

**Comment by umanwizard** [comment]
@krishmanoh2 I don't think this is actionable without saying more about how you were generating the data.

**Comment by krishmanoh2** [comment]
I think this was due to not specifying a key for the upsert. Was this not restricted - meaning now it is mandatory to specify a key for avro upsert?

**Comment by cuongdo** [comment]
@aljoscha could you please have a look?

**Comment by aljoscha** [comment]
Ha! thanks for the heads up. I actually added a check for this in https://github.com/MaterializeInc/materialize/pull/6709. Now it will fail with something like `Invalid key: (), valid keys are: (a, b)`. The previous error talking about the `DiffPair` was not very helpful.

@krishmanoh2 Do you think the new error message when creating the sink is more helpful?

**Comment by krishmanoh2** [comment]
Yes, this looks good.

**Comment by aljoscha** [comment]
Sorry for not closing this earlier. I have a "This closes #5826" in #6709 that would have closed this but I can see that more eagerly closing issues improves clarity.
