### ISSUE TITLE
Avro: Don't require a schema-registry version byte for inline schemas.

### ISSUE THREAD

**Issue by quodlibetor** [MaterializeInc/materialize#5859]
Currently we always expect Avro messages in kafka to start with a magic byte generated by confluent encoders, but it is possible for users to not use confluent to encode avro. The code that checks this is [in interchange/../avro.rs](https://github.com/MaterializeInc/materialize/blob/594c35fa469f96ba717d0f63731fe35af69a90d4/src/interchange/src/avro.rs#L2079-L2099).

The fix is not hard, but we need to decide if we should autodetect this, or require some `WITH` parameter, or if there are other options.

**Comment by umanwizard** [comment]
That's true; raw Avro (without the Confluent wrapper) in Kafka will not work.

Are people actually using Avro in Kafka without using Schema-Registry ?

**Comment by quodlibetor** [comment]
Yup we just got some folks mentioning it in the community slack.

**Comment by cirego** [comment]
> That's true; raw Avro (without the Confluent wrapper) in Kafka will not work.
> 
> Are people actually using Avro in Kafka without using Schema-Registry ?

I ran into this last week while using popular Python libraries  write Avro encoded messages to Kafka and store their schemas in Schema Registry.

I solved this by moving to the `confluent-kafka` Python library, as it includes an AvroProducer that will both add the magic badding bytes and write the schemas to the registry. However, none of the other Python Kafka libraries worked out of the box to write Avro to Kafka and have Materialize decode that Avro from the schema registry.

**Comment by quodlibetor** [comment]
> I solved this by moving to the confluent-kafka Python library, as it includes an AvroProducer that will both add the magic badding bytes and write the schemas to the registry.

Interesting, do you know if that's required for that library? Or can it be configured to not write those bytes?

**Comment by cirego** [comment]
> > I solved this by moving to the confluent-kafka Python library, as it includes an AvroProducer that will both add the magic badding bytes and write the schemas to the registry.
> 
> Interesting, do you know if that's required for that library? Or can it be configured to not write those bytes?

There is no option, from what I can see, to disable writing the magic bytes, but it could also be their version of `librdkafka` that does this (getting their custom `librdkafka` installed is part of why it's non-trivial to install under Docker).

**Comment by quodlibetor** [comment]
Okay, that's kind of unfortunate but is a strong existence proof for the solution we need here.

**Comment by jstuyts** [comment]
It's my lack of knowledge of the Kafka and Confluent ecosystem, I guess. Do people always send the header even if they do not use a schema registry?

But if I read the documentation for `CREATE SOURCE`, there is no information at all about the expected message structure. As it is missing I would expect that:

* Using an inline schema implies messages do not have to contain a reference to a schema.
* Using the Confluent schema registry implies that the messages cannot be bare Avro messages, but contain the header with the schema reference.

I do not expect a huge amount of messages, so a few additional bytes per message will not matter for me. But I can imagine situations where adding a few bytes is quite a bit of overhead.

Switching to bare Avro messages now is backward compatible, but a `WITH` option to indicate the messages will not have a schema reference header would be nice.

**Comment by benesch** [comment]
I agree that the default should be to assume the Confluent header when
using the schema registry, and not otherwise. We could write a migration to
retroactively install this default in existing clusters, so that backwards
compatibility isn’t a concern.
