### ISSUE TITLE
`SourceConnector::Local` does not respect `Context::as_of_frontier`

### ISSUE THREAD

**Issue by frankmcsherry** [MaterializeInc/materialize#5865]
The local source connector is constructed without ensuring that times are advanced at least to the `as_of` frontier of the dataflow that is being built. This can lead to the presentation of incorrect results at times not beyond that frontier.

**Comment by philip-stoev** [comment]
I have a vague gut feeling that https://github.com/MaterializeInc/materialize/issues/6295 is related.
