### ISSUE TITLE
[docs] Update TAIL doc

### ISSUE THREAD

**Issue by awang** [MaterializeInc/materialize#5876]
I think this issue can suffice as a FAQ for now:

1. can it also happen that the -1 and +1 parts of an update are in different timestamps?
2. are updates "compacted" within a timestamp? (that is there are maximum two updates for each PK or it can send us a series of changes of a PK in undefined order)
3. if I simply sequentially count the tuples as they come from a TAIL, is it ever possible that the count temporarily becomes negative? (i.e. a -1 tuple removal is before the actual +1 tuple addition that logically must have happened before)
4. if 3) is possible, can it also happen across different timestamps? (i.e. the -1 tuple removal at t0 and then +1 tuple addition at t1)

The answers are:
1. No.
2. Yes (there are a maximum of two updates per PK per time).  "Within each timestamp, each row occurs at most once." If it happens they have primary keys, then there will be at most two updates (because of additional reasoning about primary keys), but more generally we won't have the same row twice within the same timestamp.
3. No.
4. No.

**Comment by cirego** [comment]
Please forgive my ignorance, but what is a PK?

Regarding 1: if results are compacted, then the +1 and -1 updates must be in different timestamps. Each row in the output of TAIL is a tuple and Materialize does not understand the relation between ((foo, bar, 1), -1) and ((foo, bar, 2), +1).

**Comment by benesch** [comment]
> Please forgive my ignorance, but what is a PK?

"primary key:

**Comment by ruchirK** [comment]
> if results are compacted, then the +1 and -1 updates must be in different timestamps

I might be misreading but I think the intent of question 1 is -- if I update a row from

(foo, bar)
to
(foo, baz)

then is it possible to see ((foo, bar) -1) and ((foo, baz) +1) at different times and I believe the answer is no - those two tuples have to be in the same timestamp (if not then I don't know what the verb "update" means)

**Comment by cirego** [comment]
> > if results are compacted, then the +1 and -1 updates must be in different timestamps
> 
> I might be misreading but I think the intent of question 1 is -- if I update a row from
> 
> (foo, bar)
> to
> (foo, baz)
> 
> then is it possible to see ((foo, bar) -1) and ((foo, baz) +1) at different times and I believe the answer is no - those two tuples have to be in the same timestamp (if not then I don't know what the verb "update" means)

I think part of my confusion stems from the fact that, without primary key information, there's no way to know if `(foo, baz)` is a new tuple that was added or if it's an update to the row identified by primary key `foo`. As such, it seems strange to talk about `updates` to a row within the context of how TAIL currently works.

**Comment by msudberg** [comment]
Based on discussion with @ruchirK: The questions here depend on the idea of `TAIL` output having a primary key, which is not something Materialize requires or enforces. I noticed a formatting problem while review and am fixing that, but not adding any new text.
