### ISSUE TITLE
coord: make catalog changes auditable

### ISSUE THREAD

**Issue by JLDLaughlin** [MaterializeInc/materialize#5884]
At some point in the future, when multiple users are creating/dropping objects in the same Materialize instance, we will probably get a bug report that looks something like: my table disappeared! (Hopefully) this issue just means that another user dropped the table. However, right now, we wouldn't have a satisfying way to resolve these types of issues for the user.

I think that we should consider creating a new `mz_catalog_updates` table that's updated with every catalog update (sorry, @benesch). I think this table should include: the SQL statement that was run, the time it was run, and which user ran it. I'm very aware that `time it was run` will be contentious, but I think that's worth figuring out. I'm hoping this will preempt some user headaches, and avoid some Materialize blame!

(In general, this is in the theme of "data governance," which I don't think we've explored much yet.)

**Comment by JLDLaughlin** [comment]
If we don't think this is worth the cycles/memory required for a new system table, maybe we just write the information to its own log? Or include the metadata in however we're planning to persist objects?

**Comment by benesch** [comment]
Thanks for writing this up @JLDLaughlin! So we do already record the creation and deletion of every catalog object in `materialized.log` and the time at which it occurred. Adding the user to that message sounds like a good idea, and it should be a pretty straightforward thing to do! Would you find that to be a satisfying short-term solution?

I can definitely imagine someone wanting `mz_catalog_updates` but having a system table that grows without bound makes me nervous. We'd probably need to expose some knobs to control the retention period on that table and that gets complicated. Tractable, but a good bit more work than just stuffing a bit more information into the log file. The nice thing about log files is that folks are already used to having to toss/rotate them when they get too large.

**Comment by JLDLaughlin** [comment]
Ah, right! Definitely happy to add user to `materialized.log`, and maybe role, too? Agreed about the retention period being complicated.

**Comment by benesch** [comment]
Fixed by #12731!
