### ISSUE TITLE
Imlement mz_internal.mz_sleep(seconds) SQL function

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#5894]
Implement the ```mz_internal.mz_sleep(seconds)``` function with a parameter as to how many seconds to sleep with fractions allowed. This is needed for stress-testing purposes where random sleeps will be used to simulate transactions of various running times.

**Comment by ruchirK** [comment]
oooh this could be a good one for @antifuchs assuming you don't need it immediately?

**Comment by benesch** [comment]
@philip-stoev do you _need_ the function to be called `pg_sleep`, or would `mz_internal.mz_sleep` be ok? The design of PostgreSQL means that they have a more sensible way to describe the semantics of `pg_sleep`. I worry that if we expose something called `pg_sleep` users will assume it works like it does in Postgres, when in fact it does not and cannot!

**Comment by philip-stoev** [comment]
mz_internal.mz_sleep is just fine, let me fix the title. There is no immediate need as crude workarounds are available.
