### ISSUE TITLE
BEGIN on an already running transaction should produce a warning

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#5902]
### What version of Materialize are you using?

```
materialized v0.7.1-dev (d6525bd2a) 
```

### What was the issue?

```BEGIN``` is allowed in a transaction context and seems to be a no-op, but Postgresql produces a warning in the same context. I think this is a good idea as it will warn users if their transactions are not properly formed and bleed into one another.

### Is the issue reproducible? If so, please provide reproduction instructions.

```
materialize=> begin;
BEGIN
materialize=> begin;
BEGIN
```

Contrast with postgresql:

```
pstoev=# begin;
BEGIN
pstoev=# begin;
WARNING:  there is already a transaction in progress
BEGIN
```

Note that this is a warning, not an error, so the transaction continues unaffected.

**Comment by OscarTHZhang** [comment]
I can take this ticket.

**Comment by OscarTHZhang** [comment]
This issue can be closed now

**Comment by antiguru** [comment]
The corresponding PR has been merged. Closing this issue.
