### ISSUE TITLE
Brew package fails to work on Apple Silicon

### ISSUE THREAD

**Issue by JakeMakesStuff** [MaterializeInc/materialize#5915]
### What version of Materialize are you using?

```
$ materialized -v

```
N/A

### How did you install Materialize?

* [ ] Docker image
* [ ] Linux release tarball
* [ ] APT package
* [ ] macOS release tarball
* [X] Homebrew tap
* [ ] Built from source

### What was the issue?

As of right now, if you use Apple Silicon and get arm64 brew to install, it will throw the following error:
```
==> Installing materializeinc/materialize/materialized
==> cargo install src/materialized

Last 15 lines from /Users/jake/Library/Logs/Homebrew/materialized/01.cargo:

warning: build failed, waiting for other jobs to finish...
The following warnings were emitted during compilation:

warning: error: unknown target triple 'unknown-apple-macosx11.0.0', please use -triple or -arch

The following warnings were emitted during compilation:

warning: error: unknown target triple 'unknown-apple-macosx11.0.0', please use -triple or -arch
warning: error: unknown target triple 'unknown-apple-macosx11.0.0', please use -triple or -arch

error: failed to compile `materialized v0.7.0 (/private/tmp/materialized-20210227-5619-v9lpq7/materialize-0.7.0/src/materialized)`, intermediate artifacts can be found at `/private/tmp/materialized-20210227-5619-v9lpq7/materialize-0.7.0/target`

Caused by:
  build failed

Do not report this issue to Homebrew/brew or Homebrew/core!
```
As an additional note, pre-built binaries would probably also be quite nice here for arm64 since otherwise it hangs whilst it builds for quite a while.

### Is the issue reproducible? If so, please provide reproduction instructions.
Install the Brew tap on Apple Silicon.

### Please attach any applicable log files.

[01-cargo.txt](https://github.com/MaterializeInc/materialize/files/6054526/01-cargo.txt)
(is 01.cargo but GH doesn't allow me to attach a .cargo file)

**Comment by benesch** [comment]
Thanks for the report, @JakeMakesStuff! It looks like this is failing while building libz-sys:

```
  --- stderr


  error occurred: Command "clang" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-fno-omit-frame-pointer" "--target=aarch64-apple-darwin" "-I" "src/zlib" "-fvisibility=hidden" "-DSTDC" "-D_LARGEFILE64_SOURCE" "-D_POSIX_SOURCE" "-D_C99_SOURCE" "-o" "/private/tmp/materialized-20210227-5619-v9lpq7/materialize-0.7.0/target/release/build/libz-sys-4c16d1178bbca78a/out/build/src/zlib/adler32.o" "-c" "src/zlib/adler32.c" with args "clang" did not execute successfully (status code exit code: 1).
```

Looking into this now.

**Comment by JakeMakesStuff** [comment]
Alright, thanks @benesch! Let me know if you need someone if you need any help testing it. 👍

**Comment by benesch** [comment]
I do! I don't have easy access to Apple silicon right now. Happy to walk you through things here, or you can hop on our [community Slack](https://materialize.com/s/chat) and we can chat there.

**Comment by JakeMakesStuff** [comment]
@benesch I joined the Slack last night, I am `Jake Gealer` over there. 😄
