### ISSUE TITLE
JSON with a field having 19 digits long is not parsed

### ISSUE THREAD

**Issue by btheu** [MaterializeInc/materialize#5919]
### What version of Materialize are you using?

```
materialized 0.7.0
```

### How did you install Materialize?

* [X] Docker image
* [ ] APT package
* [ ] Linux release tarball
* [ ] macOS release tarball
* [ ] Homebrew tap
* [ ] Built from source

### What was the issue?

When a JSON file contains a field with 19 digit long, all fields of the same record are valuated as null. This is a usecase when a field is a nano timestamp serialized as a long.

Issues are:
* 19 digits long are not parsed, result being null for that field
* when this happen, others fields are also set as null

This was tested with file and s3 JSON sources.

### Is the issue reproducible? If so, please provide reproduction instructions.

Create a json file with content (/work/file.json)
```
{"time":1614259308542846100, "value":"value A"}
{"time":1614259308542846, "value":"value B"}
```

```
CREATE SOURCE json_file 
FROM FILE '/work/file.json'
FORMAT BYTES;

CREATE MATERIALIZED VIEW jsonified_bytes AS
SELECT CAST(data AS JSONB) AS data
FROM (
    SELECT CONVERT_FROM(data, 'utf8') AS data
    FROM json_file
);

SELECT data->'time', data->'value' FROM jsonified_bytes;
```
|?colunm?                  | ?colunm?
|-----------------------|-------------
|null                            | null
|1614259308542846  | value B

**Comment by ruf-io** [comment]
@btheu Thank you for the very clear issue report.

This does look like an internal issue and/or missing error propagation. We've made it a priority!

**Comment by benesch** [comment]
Thanks for the report, @btheu!

**Comment by benesch** [comment]
@sploiselle I'm actually going to reopen this. I think it would be substantially nicer to use the `Numeric` type for storing _all_ numbers in JSON, rather than our current approach of accepting either an i64 or f64.
