### ISSUE TITLE
dbt-materialize: dbt generate docs throws a non-fatal error

### ISSUE THREAD

**Issue by rjnn** [MaterializeInc/materialize#5944]
A user reports that while doing `dbt generate docs` that they got a
```
Encountered an error while generating catalog: Database Error
  WHERE clause error: function "upper" does not exist
dbt encountered 1 failure while writing the catalog
```
They were still able to generate and browser the docs, but we should fix this.

cc @JLDLaughlin

**Comment by jtcohen6** [comment]
This is the line:

https://github.com/MaterializeInc/materialize/blob/3dda2520e2897f4136d07dc1af87dded068dcb84/misc/dbt-materialize/dbt/include/materialize/macros/catalog.sql#L52

My guess is that the user has an older version of Materialize installed, prior to the addition of the `upper` string function last month (https://github.com/MaterializeInc/materialize/pull/5192).

**Comment by JLDLaughlin** [comment]
I agree with @jtcohen6 !

**Comment by rjnn** [comment]
Sounds very likely! Closing!
