### ISSUE TITLE
TAIL documentation doesn't reference COPY TO

### ISSUE THREAD

**Issue by frankmcsherry** [MaterializeInc/materialize#5946]
It seems hard to correctly use TAIL from a SQL session without using COPY TO, but there is no reference to this on the TAIL documentation. Several Materialize employees have stumbled over this, which makes it seem likely that others will too.

**Comment by benesch** [comment]
I would also really like to be able to generate a pgwire notice that tells you about your mistake.

**Comment by mjibson** [comment]
We knowingfully and purposefully removed the mention of COPY TO so that users would not use it because we have better solutions now. If this is added back, it needs to be very clear it should probably be used only during interactive sessions, not from an application.

**Comment by cirego** [comment]
To follow up on Matt's comment, my understanding is that we recommend doing DECLARE / FETCH? Something like:

```
DECLARE cur CURSOR FOR TAIL <view> WITH (PROGRESS)
FETCH ALL cur
```

My understanding is that downside to this approach is that it will not stream the results endlessly. You'll need to rerun FETCH each time you want to see more results.

**Comment by benesch** [comment]
Right. `COPY TO` is still recommended for interactive use in `psql`, because you get that sweet streaming experience.

**Comment by frankmcsherry** [comment]
> If this is added back, it needs to be very clear it should probably be used only during interactive sessions, not from an application.

This seems fine. Perhaps the ask isn't to reference COPY TO so much as make sure there are document TAIL for interactive use, for which the right answer might be COPY TO.
