### ISSUE TITLE
Write helper mzcompose to standup Confluent services using Docker

### ISSUE THREAD

**Issue by cirego** [MaterializeInc/materialize#5964]
In our developer docs, we have guidance that developers should install the Confluent platform. For
those that don't wish to install this locally, but are willing to run Docker, we should provide a
simple mzcompose workflow to start these services on the expected ports.

Also, the [Developer
Guide](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/develop.md) link is
broken.

**Comment by benesch** [comment]
The tests that require the Confluent Platform offer mzcompose workflows to spin up the appropriate tools from the Confluent platform, so I don't think there's anything else we need to do here!
