### ISSUE TITLE
`MZ_VERBOSE_KAFKA` environment variable for easier Kafka debugging

### ISSUE THREAD

**Issue by umanwizard** [MaterializeInc/materialize#5986]
The variable should do the following:

(1) The same thing as `MZ_LOG=librdkafka=debug,info` does now
(2) Add `WITH (statistics_interval_ms=1000)` for all Kafka sources

**Comment by benesch** [comment]
Can we push a little harder on the design here? An env var that controls another env var and also adds WITH options seems subpar! I think we’d be well served by enabling statistics logging to a system table by default, and then the MZ_LOG env var to control the rest is probs ok?

**Comment by benesch** [comment]
Closing as long stale.
