### ISSUE TITLE
Optimize `LIMIT 1` for append-only collections

### ISSUE THREAD

**Issue by frankmcsherry** [MaterializeInc/materialize#5996]
When we apply `TopK` with a limit of one, we can at least use the semigroup rendering tricks we use for `min` and `max` to avoid constructing feedback loops for garbage collection. Top1 is a not-uncommon idiom for programming "upsert"-like fragments, and shaving off the factor of 8x the hierarchical reduction imposes is worth doing.

cc: @ruchirK

**Comment by ruchirK** [comment]
this could be a good intro task for a new hire right?

**Comment by frankmcsherry** [comment]
I believe this this is at best a good second issue! Teaching them about monoids and stuff like that seems pretty exciting to do all at once!

**Comment by danhhz** [comment]
Monoid you say...

![ByouVy9CAAE8bdY](https://user-images.githubusercontent.com/52528/114067742-01362d00-9852-11eb-918c-15532fdc6624.jpg)
