### ISSUE TITLE
High memory footprint for TopK queries

### ISSUE THREAD

**Issue by macthestack** [MaterializeInc/materialize#5997]
It seems to be an unreasonably high amount of records being maintained for the view below.

```
CREATE SOURCE source1 FROM KAFKA BROKER ''
      TOPIC 'topic'
      WITH (
          security_protocol = 'sasl_ssl',
          sasl_mechanisms = 'plain',
          sasl_username = '',
          sasl_password = ''
      )
  FORMAT AVRO USING SCHEMA '';

create materialized view view1 as (select * from
       (select distinct id as key from source1) grp,
       lateral (
           select * from source1
           where id = grp.key
           order by ts desc limit 1
       ));
```

* Records in "source1": ~1600
* Records returned from querying "view1": 7
* Records maintained in data flow: ~50,000

I get the same result in 0.7.0 and unstable (from a couple of days ago) docker images.

**Comment by ruf-io** [comment]
Thanks for surfacing this @macthestack - For my own clarification, when you say `records maintained in data flow` what metric are you referring to?

I _think_ it's possible to try and replicate using the `simple` demo https://github.com/MaterializeInc/materialize/tree/main/demo/simple and creating the following view once in the CLI:
```sql
CREATE SOURCE purchase                            
FROM KAFKA BROKER 'kafka:9092' TOPIC 'mysql.simple.purchase'
FORMAT AVRO USING CONFLUENT SCHEMA REGISTRY 'http://schema-registry:8081'
ENVELOPE DEBEZIUM;

create materialized view view1 as (select * from
   (select distinct user_id as key from purchase) grp,
   lateral (
       select * from purchase
       where user_id = grp.key
       order by amount desc limit 1
   ));
```
When running that I see multiple indexes are created with the total number of purchases, but not sure where to look for the 30x increase in records maintained in dataflow.

**Comment by macthestack** [comment]
> For my own clarification, when you say `records maintained in data flow` what metric are you referring to?

I'm referring to records being stored in arrangements (materialize:6875/memory)

I will take a look at your example and see if I run into the same thing.

**Comment by frankmcsherry** [comment]
If you have a chance to check, can you try running `materialized` with `--differential-idle-merge-effort 1000`? This is what gives `materialized` permission to compact its in-memory representation even when not receiving additional data. I'll try and repro on my end and see if I see the same thing, but wanted to give you something that might help.

**Comment by frankmcsherry** [comment]
Also, just to caveat @ruf-io's example: it uses `ENVELOPE DEBEZIUM` which will have an unavoidably high memory cost because it supports arbitrary retractions; we'll need to keep at least data proportional to the input around. @macthestack I *think* your example should be able to end up with a footprint that looks proportional to the output size, as it seems to be an append-only source of data, and we are able to optimize those down (barring bugs along the way, ofc)>

**Comment by frankmcsherry** [comment]
I just confirmed that with the query up above, attached directly to a source that is ~ the same as your (no authentication, using `FORMAT TEXT` rather than `FORMAT AVRO`) the monotonic (append-only) `TopK` rendering is occurring. I think the `--differential-idle-merge-effort` setting above should probably clear things up a bit for you.

**Comment by macthestack** [comment]
Sorry for the late reply!

I just tried to recreate the query I used earlier but with `--differential-idle-merge-effort 1000`. Unfortunately, it doesn't get any better. I'll try different data sources/formats as soon as I get a chance.

**Comment by frankmcsherry** [comment]
Just a heads up: until recently (https://github.com/MaterializeInc/materialize/pull/6091, merged just now) Materialize wasn't picking up the arguments. It had previously, but a refactor happened and the argument was ignored. If you get a chance to double check it now, that would be great. If the situation isn't improved 1. we have more bugs to find and 2. we should improve our introspection.

**Comment by macthestack** [comment]
Hooray! I tried your update and it's down from 90'000 records to 119.

Thanks for all the help!
