### ISSUE TITLE
Cannot create a kafka sink under a specific auth combination

### ISSUE THREAD

**Issue by elindsey** [MaterializeInc/materialize#6006]
Creating a Kafka sink that uses SSL certs for topic auth and http basic for schema registry auth causes materialize to panic. The bad sql text is persisted to the catalog, so crash will keep happening on restart until you wipe mz's data directory. This is the default auth configuration when using Kafka + Schema Registry on aiven.

Example that causes failure:
```
create sink s from columns into kafka broker 'blah.aivencloud.com:16715' topic 'test-sink' with (security_protocol='SSL',ssl_ca_location='/Users/eli/Downloads/aiven/ca.pem',ssl_certificate_location='/Users/eli/Downloads/aiven/service.cert',ssl_key_location='/Users/eli/Downloads/aiven/service.key',ssl_key_password='password') format avro using confluent schema registry 'https://blah.aivencloud.com:16718' with (username='avnadmin',password='password');
```

Resulting panic:
```
2021-03-05T16:14:09.533391Z ERROR panic: known to be a valid identity: reqwest::Error { kind: Builder, source: Error { code: -25264, message: "MAC verification failed during PKCS12 import (wrong password?)" } }
thread: tokio:work-1
location: src/ccsr/src/tls.rs:64:14
version: 0.7.2-dev (c72343f6ecc384f2255b16b1dbe4d9a42280f230)
```

The problem is that our schema registry client incorrectly tries to use the SSL client certs for auth instead of the provided http basic auth parameters. Manually commenting out [this line](https://github.com/MaterializeInc/materialize/blob/main/src/ccsr/src/config.rs#L73) fixes the query - the permanent solution is to rearrange how the ccsr config is pieced together such that SSL client cert auth is only added if the ccsr clause itself has no explicit auth options specified.

**Comment by elindsey** [comment]
This also means we need at least some additional test coverage of auth combinations in the kafka-ssl testrig.

**Comment by benesch** [comment]
Oof. Part of me thinks we should stop defaulting the CSR SSL params to the broker SSL params and require you to specify them separately.

**Comment by benesch** [comment]
I forget when exactly this got done, but somewhere during the `CREATE CONNECTION` work we stopped conflating Kafka and CSR auth parameters. 😮‍💨
