### ISSUE TITLE
Support single-string http basic auth URLs for schema registry

### ISSUE THREAD

**Issue by elindsey** [MaterializeInc/materialize#6008]
Small quality of life improvement. Today we support http basic auth to the schema registry by explicitly specifying username/password as WITH options, like so:

```
format avro using confluent schema registry 'https://example.com:16718' with (username='user',password='password')
```

It's far more common to specify those in the URL string. It's also more convenient for users, because they're usually copy/pasting this URL into the statement:

```
format avro using confluent schema registry 'https://user:password@example.com:16718'
```

Today we _do_ actually support this - but it appears to be accidental (reqwest just so happens to do The Right Thing). We should document it as supported and add a test case to make sure it stays supported.

**Comment by benesch** [comment]
Fixed (or, rather, completely changed in a way that makes this irrelevant) by `CREATE CONNECTION`.
