### ISSUE TITLE
Expose credentials errors in AWS sources as sql errors

### ISSUE THREAD

**Issue by quodlibetor** [MaterializeInc/materialize#6010]
Currently both the kinesis and s3 sources try to get AWS credentials but, on failure, just log error messages and eventually give up.

Instead, they should:

* immediately push an error to the dataflow error stream
* retry forever, continuing to log messages
* retract the error if credentials are corrected and AWS calls start succeeding

**Comment by quodlibetor** [comment]
Related to this, I think that every time we stick an error into a stream we should ensure that some prometheus metric exists signalling the error state. Adding a metric here should probably be added to this work, but might deserve a separate issue.

**Comment by cuongdo** [comment]
I agree with @quodlibetor's point that a metric should exist -- should we also mirror that metric in a logging table? (or do we already do that automatically @antifuchs ?)

**Comment by antifuchs** [comment]
Yep, that's all wired up: Once it's a prometheus metric, it'll go into the metrics table!

**Comment by umanwizard** [comment]
@philip-stoev  - are you working on coming up with a test for this ?
