### ISSUE TITLE
Docker documentation is unclear

### ISSUE THREAD

**Issue by JakeMakesStuff** [MaterializeInc/materialize#6018]
On the [install page](https://materialize.com/docs/install/), the Docker command is incomplete and does not seem to contain the data mount required for persistent storage.

**Comment by ruf-io** [comment]
@JakeMakesStuff thanks for reporting - I am thinking we should either add a note about using a volume or link to a more thorough documentation about using Materialize in Docker. (for example, here: https://materialize.com/docs/ops/deployment/#docker)

**Comment by morsapaes** [comment]
Fixed in #11733.
