### ISSUE TITLE
UX: Kafka Auto Commit as user defined option 

### ISSUE THREAD

**Issue by krishmanoh2** [MaterializeInc/materialize#6022]
With https://github.com/MaterializeInc/materialize/issues/5324 - materialize automatically updates the last consumed offset in kafka. 

While this allows for monitoring the lag at the Kafka side, this can also result in spamming kafka with too many consumer groups' offsets that become inactive after a restart.

Can we make this as an option that the user can define during the create source time?

**Comment by awang** [comment]
how is this different from https://github.com/MaterializeInc/materialize/issues/3060#issuecomment-763736001 ?
