### ISSUE TITLE
Create end-to-end test for byo eos kafka sinks

### ISSUE THREAD

**Issue by elindsey** [MaterializeInc/materialize#6027]
This task is for creating the bare minimum exactly-once integration test. It can use byo to avoid the dependency on idempotent realtime timestamping.

It should:
1. Start up mz, configuring a source and create a Kafka eos sink directly from the materialized source
2. Write data t1 into the source
3. Verify that t1 shows up in the sink
4. Restart mz
5. Write data t2 into the source
6. Verify that _both_ t1 and t2 are in the sink

A draft branch exists, modeled on the existing catcompat integration test. A series of changes need to be made for this new test to be expressible, specifically:
1. The `exactly_once` WITH option needs to be exposed externally behind an experimental feature flag
2. testdrive needs to take an externally generated rng seed since we are invoking testdrive multiple times as part of the integration test.
3. testdrive's kafka-verify needs to be in read_committed for this test
4. testdrive's kafka-verify needs to support or specifically exclude the committed tx id when validating results

You can find the work-in-progress draft of the integration test plus related changes here https://github.com/elindsey/materialize/commit/bb0298176a833f0cc3b04f282021005d29315395

**Comment by elindsey** [comment]
Ideally we'd also like to have tests that exercised specific states of failed kafka transactions, but we don't have a way of expressing that today. That's being tracked in https://github.com/MaterializeInc/materialize/issues/5968

**Comment by elindsey** [comment]
What about something like 2 + 3 - if we include transaction info in the kafka-verify arguments, then we validate it, otherwise we exclude transaction id from the comparison? Do you think that would be useful or too confusing?

It would keep us backwards compatible with the existing tests (the vast majority of our tests will never care about txid), but still give us a way to express txid for eos tests.

I do think checking for txid will be important, not necessarily for this specific happy case test but for when we start exercising different scenarios like aborted transactions.

**Comment by aljoscha** [comment]
I could do that, yes.

One observation with this: right now, `kafka-verify` doesn't "know" about the transaction info, it just blindly compares the structure. If I want to change behavior based on whether the transaction info is there in the expected values, I need to reach into those Avro objects and decide based on just the name (in this case `transaction`) of the record. Similarly, I will probably have to manually excise the `transaction` record from the actual data when we don't have transaction info in the expected data. Will that be a problem?

They way we encode the transaction info could also change, thought I'm not familiar enough with this yet to guess anything, really. 😅

**Comment by elindsey** [comment]
> They way we encode the transaction info could also change

I just realized that I'm way off target in how I was thinking about this. For some reason when I was working on this unit test I thought the tx ID I was seeing was coming from Kafka as part of its commit protocol, but that's actually our tx ID that we introduce when we create sinks with consistency topics.

Today we do support kafka-verify with explicit transaction ids, so you probably don't need any testdrive kafka-verify changes here at all - I think I just wrote those kafka-verify lines wrong in my branch and they should look more like this https://github.com/MaterializeInc/materialize/blob/main/test/testdrive/avro-sinks.td#L173

**Comment by aljoscha** [comment]
That looks exactly like what I wrote above, doesn't it? 😅

**Comment by elindsey** [comment]
Indeed - I _think_ it will all just work, and this was my fault for writing a bad kafka-verify. Sorry for leading you down the wrong path!

**Comment by aljoscha** [comment]
No worries! I did work with option three because it seemed very straightforward but I also thought about the other options, just to be thorough.

I created #6055, it doesn't work yet, though. Will post some questions there.
