### ISSUE TITLE
Remove blocking Kafka txn calls from dataflow workers

### ISSUE THREAD

**Issue by elindsey** [MaterializeInc/materialize#6035]
In our current Kafka eos sink implementation, these calls to rdkafka will block:
* init_transactions
* begin_transaction
* commit_transaction
* abort_transaction

These calls are executed from the dataflow worker threads. Those dataflow threads are cooperatively scheduled, so doing blocking IO wastes time that could be spent executing other operators.

https://github.com/MaterializeInc/materialize/issues/5267 tracks trying to make these calls async in upstream, but we'll need to do something in the immediate term to work around it. 

There are a number of options, from spinning up a small pool of threads per worker to service blocking calls, to integrating with existing tokio threadpools/`spawn_blocking`, to hiding all of this crud behind our own internal mz kafka client shim (which we may need to do on the source side eventually anyways to allow for combining consumers of the same upstream topic). There will need to be some upfront work to decide direction.

**Comment by aljoscha** [comment]
@benesch Do you think we should go forward with this or put all efforts into async-ifying rust-rdkafka (and librdkafka). My main questions with solving it upstream would be a) how much work would this be, and b) how likely is upstream to accept the contribution.

If we want to prioritise a stopgap solution on Materialize itself I'd get started on figuring out the options.

**Comment by benesch** [comment]
> @benesch Do you think we should go forward with this or put all efforts into async-ifying rust-rdkafka (and librdkafka). My main questions with solving it upstream would be a) how much work would this be, and b) how likely is upstream to accept the contribution.
> 
> If we want to prioritise a stopgap solution on Materialize itself I'd get started on figuring out the options.

Sorry for missing this question originally. Recording some thoughts that I conveyed to @cjubb39 just now on Slack.

I don't think trying to upstream this to librdkafka is likely to be successful. It's a contribution I think they'd likely accept long term, but I imagine that it would be a several month process. Getting familiar with the C codebase is no small task; then the PR would languish in several review cycle for a long while; and after all that we'd still have to update rust-rdkafka for the new interfaces. 

I'm honestly much more enthusiastic about ditching rdkafka entirely and writing our own Kafka client. I don't think it would be terribly hard, as the protocol is rather simple without consumer groups. I'm not actually advocating for this, but it gets more attractive every day.

I think the best bet if we want to solve this in the immediate term is to smash some calls to `spawn_blocking` in the right places (or some channels and threads, whatever). 

It's also worth noting that if the platform work gets sources and sinks off the dataflow threads, it doesn't matter if they block.
