### ISSUE TITLE
Wrong "column does not exist" error with GROUP BY over expressions, ON condition

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#6050]
### What version of Materialize are you using?

```
v0.7.2-dev (4f934b163)

```

### What was the issue?

A query that performs GROUP BY over two expressions in the presence of an ON clause wrong returns a "column does not exist" query. The query is valid and not entirely unrealistic and works as expected in Postgres.

### Is the issue reproducible? If so, please provide reproduction instructions.

```
materialize=> CREATE TABLE t1 (f1 INTEGER, f2 INTEGER);
CREATE TABLE
materialize=> SELECT a2.f1 + a1.f2, a1.f1 + a1.f2 FROM t1 AS a1 JOIN t1 AS a2 ON (a1.f1 = a2.f1) GROUP BY 1, 2;
ERROR:  column "a1.f1" does not exist
```

Both the expressions, ```GROUP BY``` and the ```ON``` clause are required to reproduce. So it seems to me that the condition in the ON clause causes equality propagation to happen in a way that breaks name resolution.

**Comment by benesch** [comment]
I'm not sure when exactly this got fixed, but the query in the issue description works correctly with the latest main.
