### ISSUE TITLE
[dbt-materialize] Mismatch between mz_columns.type + mz_types.name

### ISSUE THREAD

**Issue by jtcohen6** [MaterializeInc/materialize#6063]
### What version of Materialize are you using?

```
$ materialized -v
materialized v0.7.0 (953d2279d)
```

### How did you install Materialize?

* [ ] Docker image
* [ ] Linux release tarball
* [ ] APT package
* [ ] macOS release tarball
* [x] Homebrew tap
* [ ] Built from source

### What was the issue?

This issue arose while using `dbt-materialize`, though I don't think it's specific to the dbt adapter.

The SQL in the `materialize__get_catalog` macro—which grabs information about relations, columns, and column types—performs an inner join between `mz_columns.type` and `mz_types.name`:

https://github.com/MaterializeInc/materialize/blob/578d6e6bc7d7b24c7790d3669773952b6c027861/misc/dbt-materialize/dbt/include/materialize/macros/catalog.sql#L45

This has the effect of excluding columns whose value in `mz_columns.type` is the data type name instead of the catalog alias (e.g. `bigint` instead of `int8`, per [docs](https://materialize.com/docs/sql/types/integer/#main)).

### Is the issue reproducible? If so, please provide reproduction instructions.

I saw this come up in the `wikirecent-dbt` demo project, where the aggregate column `changes` in the **useredits** and **top10** models is implicitly of type `bigint`:

https://github.com/MaterializeInc/materialize/blob/578d6e6bc7d7b24c7790d3669773952b6c027861/play/wikirecent-dbt/models/useredits.sql#L18

In the context of dbt, this has the ultimate effect of rendering column types (or entire columns) missing from the auto-generated documentation site:

<img width="1006" alt="Screen Shot 2021-03-11 at 3 39 28 PM" src="https://user-images.githubusercontent.com/13897643/110804077-20a45f00-8280-11eb-88b1-efb41e0ac496.png">

I ran an altered subset of the catalog query:

```sql
select

	mz_columns.name as attname,
	position as attnum,
	mz_relations.oid as attrelid,
	FALSE as attisdropped,
	mz_columns.type as column_type,
	mz_relations.name as relation_name

from mz_columns          
join mz_relations on mz_columns.id = mz_relations.id
where mz_columns.name = 'changes'
--join mz_types on mz_columns.type = mz_types.name
```

attname | attnum | attrelid | attisdropped | column_type | relation_name
-- | -- | -- | -- | -- | --
changes | 2 | 20212 | false | bigint | top10
changes | 2 | 20210 | false | bigint | useredits

When I un-comment the last line to re-add the inner join to `mz_types`, it returns no rows, because `bigint` does not exist in `mz_types`:
```sql
select * from mz_types
where name like '%int%'
```

id | oid | schema_id | name
-- | -- | -- | --
s1002 | 20 | 2 | int8
s1003 | 23 | 2 | int4
s1010 | 1007 | 2 | _int4
s1012 | 1016 | 2 | _int8
s1024 | 1186 | 2 | interval
s1025 | 1187 | 2 | _interval

### Possible resolutions
- It's not clear to me whether the inner join to `mz_types` is even needed in `materialize__get_catalog`. We could just remove that from the query.
- The [`mz_types`](https://materialize.com/docs/sql/system-catalog/#mz_types) system table could include each type alias as an additional rows. Alternatively, another system catalog item could provide a many-to-one mapping from type aliases to `mz_types.id` or `mz_types.name`.

**Comment by JLDLaughlin** [comment]
@jtcohen6 thank you for this incredibly thorough bug report -- you've done my work for me! I'm going to remove the join to `mz_types`, as you suggested.

**Comment by JLDLaughlin** [comment]
Fixed, thank you @jtcohen6 !
