### ISSUE TITLE
"Ignoring decrease in partitions" error is malformed, new and old partition counts are swapped

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#6088]
### What version of Materialize are you using?

```
v0.7.2-dev (5c05c16fa)
```

### What was the issue?

In ```timestamp.rs```:

```
                    cmp::Ordering::Less => {
                        error!(
                            "Ignoring decrease in partitions (from {} to {}) for topic {} (source {})",
                             new_partition_count, current_partition_count, c.topic, c.id,
                        );
                    }
```

```new_partition_count``` and ```current_partition_count``` are misplaced.

Also, how can something be both an ```ERROR``` and be "ignored".

### Is the issue reproducible? If so, please provide reproduction instructions.

Run testdrive against materialize and in the log you will see errors like:

```
2021-03-16T09:12:05.607685Z ERROR coord::timestamp: Ignoring decrease in partitions (from 0 to 3) for topic testdrive-non-dbz-data-varying-partition-3567593364 (source u71)    
```

it should be "from 3 to 0".

**Comment by ruchirK** [comment]
I'm taking this one for a new hire!
