### ISSUE TITLE
AWS Clients don't respect http(s) proxy settings

### ISSUE THREAD

**Issue by quodlibetor** [MaterializeInc/materialize#6096]
Currently the Rusoto connectors don't do anything special when the `HTTP_PROXY`/`HTTPS_PROXY` is set. There is a concise example of responding to it using `hyper`'s ProxyConnector [here](https://github.com/lucdew/rusoto-example/blob/cdaa8645774eaac430a83746b5c6f8882a5e84f0/src/client.rs).

The main work to do here is to ensure that all our AWS clients use the same function to generate their http connector.

**Comment by benesch** [comment]
Hrm. Marking as needs-discussion. How common are these variables in customer deployments? If we respect them for AWS API calls, we probably ought to respect them for all HTTP traffic we send out, yeah? Only supporting them for the AWS API calls seems bound to be confusing!

**Comment by benesch** [comment]
Also unmarking as a bug for now, as I think this is really a feature that needs to be added, and removing the good first issue label since I think there is design work that needs to happen first.

**Comment by quodlibetor** [comment]
> How common are these variables in customer deployments?

I've worked places that mandated them for all http traffic inside of the infrastructure. I don't know how common they are, but my guess is that it will be a hard blocker for anyone that requires it -- as indeed it is for the customer who reported it.

> we probably ought to respect them for all HTTP traffic we send out, yeah?

Yes, absolutely, if the HTTP(S)_PROXY env vars are set then essentially all programs are supposed to respect them for all HTTP traffic. We should probably stick something near the root of the crate graph that gets us a "standard" http client, but I'm not sure how much other will be necessary.

**Comment by umanwizard** [comment]
> Yes, absolutely, if the HTTP(S)_PROXY env vars are set then essentially all programs are supposed to respect them for all HTTP traffic

This is true irrespective of what port the traffic is on, right?

**Comment by quodlibetor** [comment]
Correct, the port shouldn't matter.

**Comment by quodlibetor** [comment]
@benesch What discussion would you like to see around this? I believe that your questions have had discussion. I'm not sure how detailed of a design you would like to see.

**Comment by benesch** [comment]
As long as we're in agreement that `HTTP_PROXY` controls _all_ outgoing HTTP traffic then I'm good! Just wanted to flag that this wasn't a quick win. So that means:

  * rusoto
  * ccsr
  * PubNub?
  * SSE (if it lands)

Are there other places we make HTTP requests? I can't think of any, but could be wrong!

**Comment by umanwizard** [comment]
is `HTTP_PROXY` supposed to have any effect on the HTTP _server_ ? (I doubt it, since it wouldn't make sense to expect it to ... magically set up a reverse proxy, or anything like that, but I wanted to check)

**Comment by quodlibetor** [comment]
> is HTTP_PROXY supposed to have any effect on the HTTP server?

I don't know what that would mean, so I don't think so.

> Are there other places we make HTTP requests? I can't think of any, but could be wrong!

Telemetry/version check.
