### ISSUE TITLE
JSONB number out of range in Materialize, but supported in Postgres

### ISSUE THREAD

**Issue by andrioni** [MaterializeInc/materialize#6107]
### What version of Materialize are you using?

`v0.7.2-dev (69cf42555)`

### How did you install Materialize?

* [x] Docker image

### What was the issue?

A JSONB message failed to parse because it had a number that it was too large: 655907283880600004.

### Is the issue reproducible? If so, please provide reproduction instructions.

```
mz> SELECT '655907283880600004'::jsonb
invalid input syntax for type jsonb: 655907283880600004 is out of range for a jsonb number at line 1 column 18: "655907283880600004"
```

On Postgres 13.1:

```
# select '655907283880600004'::jsonb;
       jsonb
--------------------
 655907283880600004
(1 row)
```

**Comment by benesch** [comment]
Closing this in favor of #5919. Not a strict duplicate, but the same underlying issue!
