### ISSUE TITLE
"failed to initialize inotify" and related errors not propagated to SQL client

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#6114]
### What version of Materialize are you using?

```
v0.7.2-dev (c14eabd85)
```
### What was the issue?

If ```inotify``` can not be initialized, the following error is printed in the log:

```
materialized_1     | 2021-03-17T12:13:12.645063Z ERROR dataflow::source::file: file source: failed to initialize inotify: Bad file descriptor (os error 9)    
```

However, the error is not propagated to the affected materialized views, so selecting against them returns no rows.

### Is the issue reproducible? If so, please provide reproduction instructions.

Yes, see test case in #6115

**Comment by philip-stoev** [comment]
Frank said:
>  let's ping @Brennan Vincent as I think this is an example of "sources should propagate more errors" which I think is within our power (maybe @Chris too, as he did a sweep of some sources and their errors).

 @umanwizard @cirego

**Comment by umanwizard** [comment]
Yep, @cirego any interest in taking this?
