### ISSUE TITLE
DROP of file source with TAIL does not release inotify resources

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#6115]
### What version of Materialize are you using?

```
materialized v0.7.2-dev (c14eabd85)

```

### What was the issue?

Neither ```rm_watch``` nor ```close``` appear to be called on the ```inotify``` object , so ```inotify``` stuff accumulates until the ```/proc/sys/fs/inotify/max_user_watches``` is exceeded at which point further ```inotify``` handlers can not be registered and watching further files stops.

### Is the issue reproducible? If so, please provide reproduction instructions.

Yes, set ```sudo sysctl fs.inotify.max_user_watches=32``` and then run this ```.td``` test in a loop:

```
$ file-append path=dynamic.csv
city,state,zip

> CREATE MATERIALIZED SOURCE dynamic_csv
  FROM FILE '${testdrive.temp-dir}/dynamic.csv' WITH (tail = true)
  FORMAT CSV WITH HEADER

> SELECT * FROM dynamic_csv
```
like this:

```
while ../../target/release/testdrive inotify.td ; do :; done
```

and very soon the server will start reporting:

```
2021-03-17T12:49:41.030036Z ERROR dataflow::source::file: file source: failed to add watch for file: No space left on device (os error 28) (path: /tmp/.tmpsuQH38/dynamic.csv)    
```

If the test was actually checking that the data is properly processed, it would have started failing at that point.

**Comment by benesch** [comment]
We've removed file sources, so this is now obsolete.
