### ISSUE TITLE
Logfile showing color escape sequences - option to disable

### ISSUE THREAD

**Issue by krishmanoh2** [MaterializeInc/materialize#6117]
The latest release of mz - the logfile shows color escape sequences. Can this be disabled?

materialized v0.7.2-dev (8ef46c13b)
OpenSSL 1.1.1j  16 Feb 2021
librdkafka v1.6.0
os: Ubuntu 20.4.0 [64-bit]
cpus: 96 logical, 48 physical
cpu0: Intel(R) Xeon(R) Platinum 8168 CPU @ 2.70GHz 3399MHz
memory: 1621945180KB total, 299673057KB used
swap: 0KB total, 0KB used
^[[2m2021-03-10T15:28:03.097624Z^[[0m ^[[32m INFO^[[0m coord::catalog: create type pg_catalog.bool (s1000)
^[[2m2021-03-10T15:28:03.097687Z^[[0m ^[[32m INFO^[[0m coord::catalog: create type pg_catalog.bytea (s1001)
^[[2m2021-03-10T15:28:03.097695Z^[[0m ^[[32m INFO^[[0m coord::catalog: create type pg_catalog.int8 (s1002)
^[[2m2021-03-10T15:28:03.097701Z^[[0m ^[[32m INFO^[[0m coord::catalog: create type pg_catalog.int4 (s1003)
^[[2m2021-03-10T15:28:03.097707Z^[[0m ^[[32m INFO^[[0m coord::catalog: create type pg_catalog.text (s1004)
^[[2m2021-03-10T15:28:03.097713Z^[[0m ^[[32m INFO^[[0m coord::catalog: create type pg_catalog.oid (s1005)
^[[2m2021-03-10T15:28:03.097723Z^[[0m ^[[32m INFO^[[0m coord::catalog: create type pg_catalog.float4 (s1006)
^[[2m2021-03-10T15:28:03.097728Z^[[0m ^[[32m INFO^[[0m coord::catalog: create type pg_catalog.float8 (s1007)
^[[2m2021-03-10T15:28:03.097735Z^[[0m ^[[32m INFO^[[0m coord::catalog: create type pg_catalog._bool (s1008)
^[[2m2021-03-10T15:28:03.097739Z^[[0m ^[[32m INFO^[[0m coord::catalog: create type pg_catalog._bytea (s1009)
^[[2m2021-03-10T15:28:03.097753Z^[[0m ^[[32m INFO^[[0m coord::catalog: create type pg_catalog._int4 (s1010)
^[[2m2021-03-10T15:28:03.097758Z^[[0m ^[[32m INFO^[[0m coord::catalog: create type pg_catalog._text (s1011)
^[[2m2021-03-10T15:28:03.097772Z^[[0m ^[[32m INFO^[[0m coord::catalog: create type pg_catalog._int8 (s1012)
^[[2m2021-03-10T15:28:03.097782Z^[[0m ^[[32m INFO^[[0m coord::catalog: create type pg_catalog._float4 (s1013)
^[[2m2021-03-10T15:28:03.097787Z^[[0m ^[[32m INFO^[[0m coord::catalog: create type pg_catalog._float8 (s1014)
^[[2m2021-03-10T15:28:03.097793Z^[[0m ^[[32m INFO^[[0m coord::catalog: create type pg_catalog._oid (s1015)

**Comment by benesch** [comment]
Oh, I see the issue. https://github.com/tokio-rs/tracing/issues/1160
