### ISSUE TITLE
wrong-result: Extra columns in Avro writer schema not handled correctly

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#6135]
### What version of Materialize are you using?

```
v0.7.2-dev (46234d1f7)
```

### What was the issue?

The Avro spec has the following to say about writer schemas and extra columns:

> if the reader's record schema has a field that contains a default value, and writer's schema does not have a field with the same name, then the reader should use the default value from its field.
> if the reader's record schema has a field with no default value, and writer's schema does not have a field with the same name, an error is signalled.

However this is currently not the case. In either case Materialize attempts to read further into the Avro stream, which results in a ```UnexpectedEof```` error, or , potentially, in wrong results.

### Is the issue reproducible? If so, please provide reproduction instructions.

```
$ set 1column={"type": "record", "name": "schema_1column", "fields": [ {"name": "f1", "type": "int"} ] }
$ set 2columns-nodefault={"type": "record", "name": "schema_2columns_nodefault", "fields": [ {"name": "f1", "type": "int"} , {"name": "f2", "type": "int"} ] }
$ set 2columns-default={"type": "record", "name": "schema_2columns_default", "fields": [ {"name": "f1", "type": "int"} , {"name": "f2", "type": "int", "default": "345"} ] }

#
# 1 column -> 2 columns with no default
#

$ kafka-create-topic topic=resolution-1to2-nodefault

$ kafka-ingest format=avro topic=resolution-1to2-nodefault schema=${1column} timestamp=1
{"f1": 123}

> CREATE MATERIALIZED SOURCE resolution_1to2_nodefault
  FROM KAFKA BROKER '${testdrive.kafka-addr}' TOPIC 'testdrive-resolution-1to2-nodefault-${testdrive.seed}'
  FORMAT AVRO USING SCHEMA '${2columns-nodefault}'
  ENVELOPE NONE

! SELECT * FROM resolution_1to2_nodefault
avro deserialization error: IO error: UnexpectedEof
```

This should have thrown an error along the lines of "f2 does not have a default value"

and this:

```
$ kafka-create-topic topic=1to2

$ kafka-ingest format=avro topic=resolution-1to2-default schema=${1column} timestamp=1
{"f1": 123}

> CREATE MATERIALIZED SOURCE resolution_1to2_default
  FROM KAFKA BROKER '${testdrive.kafka-addr}' TOPIC 'testdrive-resolution-1to2-default-${testdrive.seed}'
  FORMAT AVRO USING SCHEMA '${2columns-default}'
  ENVELOPE NONE

! SELECT * FROM resolution_1to2_default
avro deserialization error: IO error: UnexpectedEof
```

Should have suceeded instead , returning ```[123,345]```

**Comment by umanwizard** [comment]
Closing - see https://github.com/MaterializeInc/materialize/issues/6134#issuecomment-802307240
