### ISSUE TITLE
Avro: Integer types can not be promoted to floating-point

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#6137]
### What version of Materialize are you using?

```
0.7.2-dev (46234d1f7) 
```

### What was the issue?

The Avro spec says that:

> the writer's schema may be promoted to the reader's as follows:
> - int is promotable to long, float, or double
> - long is promotable to float or double

But this does not work in Materialize

### Is the issue reproducible? If so, please provide reproduction instructions.
```
$ set null={"type": "record", "name": "field_null", "fields": [ {"name": "f1", "type": "null"} ] }
$ set int={"type": "record", "name": "field_int", "fields": [ {"name": "f1", "type": "int"} ] }
$ set float={"type": "record", "name": "field_float", "fields": [ {"name": "f1", "type": "float"} ] }

$ kafka-create-topic topic=promo-int2float

$ kafka-ingest format=avro topic=promo-int2float schema=${int} timestamp=1
{"f1": 123}

> CREATE MATERIALIZED SOURCE promo_int2float
  FROM KAFKA BROKER '${testdrive.kafka-addr}' TOPIC 'testdrive-promo-int2float-${testdrive.seed}'
  FORMAT AVRO USING SCHEMA '${float}'
  ENVELOPE NONE

! SELECT * FROM promo_int2float
avro deserialization error: IO error: UnexpectedEof
```
This should have returned ```123``` instead.

**Comment by umanwizard** [comment]
Closing - see https://github.com/MaterializeInc/materialize/issues/6134#issuecomment-802307240
