### ISSUE TITLE
Avro: reading data with wrong schema results in an attempt to allocate excessive memory

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#6138]
### What version of Materialize are you using?

```
materialized v0.7.2-dev (46234d1f7)
```

### What was the issue?

Reading a nested map with a wrong schema results in:

```
avro deserialization error: Allocation error: attempt to allocate 18446744073709551562 bytes (maximum allowed: 536870912)
```

My guess is that by some lucky coincidence the attempted memory allocation was too large to be realistic. It is possible that a particular Avro schema will result in a realistic allocation that will OOM the materialize server.

### Is the issue reproducible? If so, please provide reproduction instructions.

```
$ set map-int={"type": "record", "name": "map1", "fields": [ {"name": "f1", "type": { "type": "map", "values": "int" } } ] }
$ set map-map={"type": "record", "name": "map1", "fields": [ {"name": "f1", "type": { "type": "map", "values": { "type": "map", "values": "int" } } } ] }

$ kafka-create-topic topic=resolution-map-map-int

$ kafka-ingest format=avro topic=resolution-map-map-int schema=${map-map} timestamp=1
{"f1": {"key1": {"key2": 123}}}

> CREATE MATERIALIZED SOURCE resolution_map_map_int
  FROM KAFKA BROKER '${testdrive.kafka-addr}' TOPIC 'testdrive-resolution-map-map-int-${testdrive.seed}'
  FORMAT AVRO USING SCHEMA '${map-int}'
  ENVELOPE NONE

! SELECT f1 -> 'key1' FROM resolution_map_map_int
avro deserialization error: Allocation error: attempt to allocate 18446744073709551562 bytes (maximum allowed: 536870912)
```

This should have thrown an error prior to attempting that memory allocation.

**Comment by umanwizard** [comment]
Closing - see https://github.com/MaterializeInc/materialize/issues/6134#issuecomment-802307240

**Comment by philip-stoev** [comment]
@umanwizard I think this needs to be fixed so that we do not make an attempt to allocate excessive memory even if the schema is not set up right.

**Comment by umanwizard** [comment]
@philip-stoev We already do that - we don't try to allocate the memory if it exceeds 512 MiB . In this case we did not allocate anything because 18446744073709551562 bytes is greater than 512 MiB. That's the error message you're seeing.

**Comment by philip-stoev** [comment]
Understood, I just thought that 512Mb qualifies as an excessive allocation. Is it possible to add any extra checks prior to the allocation? If not  , then please feel free to close the ticket.

**Comment by umanwizard** [comment]
Perhaps the real resolution is not to allow people to create Avro sources with fixed schemas (without schema registry)
