### ISSUE TITLE
Table Persistence

### ISSUE THREAD

**Issue by elindsey** [MaterializeInc/materialize#6155]
Tracking task for table persistence

Currently tables are ephemeral - data inserted into tables is lost across restart. Ideally that would not be the case and customers could rely on INSERTs persisting data with guarantees similar to other databases.

I'm cutting this tracking task primarily to consolidate some resources/context for when we start working on this at some point in the future.

Internal docs:
Philip's proposed acceptance criteria - https://docs.google.com/document/d/1xG8ZfOq88bkpdMIN7DosXdzIMSKvqUhmS5grA_qBp8g/edit?usp=sharing
Ruchir's persistent tables doc - https://docs.google.com/document/d/1ogoOXwxItpnBaSPCrkNTcFwWMT9Y-LeN-6CjpLpqGus/edit?usp=sharing
And related PR with commentary - https://github.com/MaterializeInc/materialize/pull/5762

When we restart work on this we'll need to spend more time upfront figuring out what exact behaviors/guarantees we want to offer and writing a design doc that covers the work - it feels like there are a lot of unknown unknowns in this area, and anything we can do to address those earlier in the process is beneficial, otherwise we will likely end up continually expanding/mutating the implementation as we learn about and try to encompass new requirements.
That doc may also need to cover some aspects of table semantics, because that area is a bit underspecified/implementation defined.

**Comment by nmeagan11** [comment]
Closing in favor of https://github.com/MaterializeInc/materialize/issues/11774
