### ISSUE TITLE
Support file rotation for file sinks

### ISSUE THREAD

**Issue by quodlibetor** [MaterializeInc/materialize#6156]
File sinks do not support rotating the files (either via a file rotation config, or via the standard "`kill -HUP materialized` to re-open files" protocol, as commonly used by logrotate).

Well-behaved long-lived systems _do_ support this, as a way of preventing disks from becoming entirely filled by perpetually-appended-to files.

My intuition is that we'll need to support this as part of sink definition, since otherwise we will need to close and re-open _every_ sink (and log file) and check whether it has changed on receiving a HUP signal.

Please comment or react to this issue if it is a feature that would help you in your work, to help us decide how to prioritize the work!

**Comment by elindsey** [comment]
File sinks are deprecated
