### ISSUE TITLE
Avro UUID data mapped to TEXT, not checked for correctness

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#6163]
### What version of Materialize are you using?

```
v0.7.2-dev (46234d1f7)
```

### What was the issue?

If Avro data that arrives with ```"logicalType": "UUID"``` , the column type that is created in the source is ```Text```, and no checking is performed on whether the incoming string is indeed a valid UUID. This should not be the case as Materialize supports a native ```UUID``` data type that has proper checking.

### Is the issue reproducible? If so, please provide reproduction instructions.

This test succeeds even though the last query should have failed with some error:

```
$ set uuid={"type": "record", "name": "field_null", "fields": [ { "name": "f1", "type": { "logicalType": "UUID", "type": "string" } } ] }

$ kafka-create-topic topic=avro-types-uuid

$ kafka-ingest format=avro topic=avro-types-uuid schema=${uuid} timestamp=1
{"f1": "abc"}

> CREATE MATERIALIZED SOURCE avro_types_uuid
  FROM KAFKA BROKER '${testdrive.kafka-addr}' TOPIC 'testdrive-avro-types-uuid-${testdrive.seed}'
  FORMAT AVRO USING SCHEMA '${uuid}'
  ENVELOPE NONE

> SELECT * FROM avro_types_uuid
abc
```

Contrast insertion via Avro with the same operation performed with ```INSERT``` :+1: 
```
materialize=> create table t1 (f1 UUID);
CREATE TABLE
materialize=> insert into t1 values('abc');
ERROR:  invalid input syntax for type uuid: invalid length: expected one of [36, 32], found 1: "abc"
```

**Comment by biryukovmaxim** [comment]
I tryed to fix issue, but pipe is broken with:

Checking whether GitHub user biryukovmaxim is a member of the build-authorized team
--
&nbsp; | curl: (22) The requested URL returned error: 404
&nbsp; | 🚨 Error: Error setting up bootstrap: The global environment hook exited with status 22

Could some1 explain what should i do with it?

**Comment by philip-stoev** [comment]
The original test had an error, UUID should have been lowercase. Once it was changed to lowercase, the test was passing.
