### ISSUE TITLE
Transient issues with the schema registry can cause permanent errors in the source stream

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#6185]
### What version of Materialize are you using?

```
v0.7.2-dev (f63a8eb91)
```

### What was the issue?

The REST API calls that are made to the schema registry when ingesting Avro data are not protected against transient issues. They are not retried so any sort of tranisent error would cause the stream to error out permanently.

### Is the issue reproducible? If so, please provide reproduction instructions.

1. In one terminal, mess with the schema registry:
```
while true ; do pkill -f schema-registry ; sleep 1 ;  confluent local services schema-registry start ; sleep 1; done
```
2. In another terminal, run testdrive:
```
../../target/release/testdrive  avro-resolution*
```

Sometimes this will error out in ```kafka-ingest```, which is OK, but sometimes it willl error out on a ```SELECT```:

```
> SELECT f1 FROM resolution_enums
rows didn't match; sleeping to see if dataflow catches up 125ms 250ms 500ms 1s 2s 4s 2.112008138s
avro-resolution-enums.td:37:1: error: executing query failed: db error: ERROR: Decode error: Text: avro deserialization error: transport: error sending request for url (http://localhost:8081/schemas/ids/41): error trying to connect: tcp connect error: Connection refused (os error 111)
     |
  36 | 
  37 | > SELECT f1 FROM resolution_enums
     | ^
```

Note that the error message here is the more verbose one suggested in #6153 . Without that patch, it will simply say ```Failed to fetch schema with ID 18```

**Comment by philip-stoev** [comment]
HTTP error codes that indicate transient issues should also be retired, e.g. "Internal Server Error" and whatnot.

**Comment by philip-stoev** [comment]
The schema registry's kafkastore.timeout.ms is 500ms , that is, 1/2 of a second. This means that if Kafka is not around for 1/2 of a second, the schema registry starts returning "500 Internal Error" s

**Comment by benesch** [comment]
Reopening as we had a customer hit this, presumably because #6724 added only a 30s retry loop and there was a more-than-30s blip in network connectivity.
