### ISSUE TITLE
Invalid WITH options to CREATE SOURCE are not detected

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#6186]
### What version of Materialize are you using?

```
v0.7.2-dev (f63a8eb91)
```

### What was the issue?

The following ```CREATE SOURCE``` command is accepted even though the ```WITH``` section contains an invalid option:

```
CREATE MATERIALIZED SOURCE resolution_enums
FROM KAFKA BROKER 'localhost' TOPIC 'abc'
WITH (missspelled_timestamp_frequency_ms = 100)
ENVELOPE NONE;
```

The following arrives at the ```extract_timestamp_frequency_option```:

```
    "missspelled_timestamp_frequency_ms": Number(
        "100",
 ```

and consequently this function selects a default value without any errors being reported.

**Comment by philip-stoev** [comment]
Since multiple WITH blocks are allowed at different positions meaning different things, one can do:

```
$ set enum-reader={"type": "record", "name": "schema_enum", "fields": [ {"name": "f1", "type": { "type": "enum", "name": "enum1", "symbols" : ["E1", "E2", "E3", "E4", "E_DEFAULT"], "default": "E_DEFAULT" } } ] }

$ kafka-create-topic topic=resolution-enums

$ kafka-ingest format=avro topic=resolution-enums schema=${enum-reader} publish=true timestamp=1
{"f1": "E1" }

> CREATE MATERIALIZED SOURCE resolution_enums
  FROM KAFKA BROKER '${testdrive.kafka-addr}' TOPIC 'testdrive-resolution-enums-${testdrive.seed}'
  FORMAT AVRO USING CONFLUENT SCHEMA REGISTRY '${testdrive.schema-registry-url}'
  WITH (timestamp_frequency_ms = 10)
  ENVELOPE NONE
```

And not be alerted that the ```WITH``` section he has constructed applies to ```FROMAT AVRO``` and not to ```KAFKA BROKER``` and consequently the ```timestamp_frequency_ms``` value provided will be silently ignored.

**Comment by philip-stoev** [comment]
We had a user already hit this. I am setting the tag to P2 and also T-Correctness, because I can totally envison Mz silently doing the wrong thing either now or in the future with incoming data if some correctness-critical WITH option is silently ignored.

**Comment by philip-stoev** [comment]
This remains a problem.

**Comment by benesch** [comment]
@philip-stoev I believe this is all corrected now with the new option syntax. Could you take another pass?
