### ISSUE TITLE
result type from subtraction of two DATEs is INTERVAL in Mz, INTEGER in Postgres

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#6187]
### What version of Materialize are you using?

```
v0.7.2-dev (66530b9c2)
```

### What was the issue?

In Materialize, the result from subtracting of two DATEs is INTERVAL, but in Postgres it is INTEGER, as recorded in their documentation as well

### Is the issue reproducible? If so, please provide reproduction instructions.

In Mz:

```
materialize=> select pg_typeof(now()::date - now()::date);
 pg_typeof 
-----------
 interval
(1 row)
```

In Postgres:

```
pstoev=#  select pg_typeof(now()::date - now()::date);
 pg_typeof 
-----------
 integer
```

**Comment by OscarTHZhang** [comment]
I can take this ticket

**Comment by bjgbeelen** [comment]
@JLDLaughlin this is the reason that the `datediff` function in materialize-dbt-utils is failing. I thought I'd look up if there already was an issue here in github -> found it :-)

Because I think it makes more sense to solve it in Materialize then to try and make a workaround in the utils

**Comment by JLDLaughlin** [comment]
@bjgbeelen - thank you for doing my investigative work for me! If you're interested in contributing to Materialize, please feel free to take a look! Otherwise, we'll update here when it's fixed.
