### ISSUE TITLE
sql: repeat_row: panic: Negative multiplicity in constant result: -1

### ISSUE THREAD

**Issue by mjibson** [MaterializeInc/materialize#6188]
```
select * from (values ('a')), repeat(-1);
```

panics with:

```
ERROR panic: Negative multiplicity in constant result: -1
thread: <unnamed>
location: /home/mjibson/materialize/src/coord/src/coord.rs:2360:17
version: 0.7.2-dev (d8d974a0c8791fdae7abe0b1204d0749cbdc4563)
```

**Comment by frankmcsherry** [comment]
This looks like it could be as easy as changing an `assert` to a return of an `Err`.

**Comment by benesch** [comment]
This is already the case, but stating explicitly for the record: this is a low-pri panic because `repeat` is experimental. It is in fact experimental precisely because of sharp edges like this (#3820).
