### ISSUE TITLE
Enhance tail via portals

### ISSUE THREAD

**Issue by quodlibetor** [MaterializeInc/materialize#619]
Now that we support portals (#596) we have a place to stash server-side state for TAIL and related things.

There are a few ways that we can support tail, each of these could be pretty interesting for different perf/mem/expedience tradeoffs.

### Light memory probably easier to implement

* We could stash a timestamp in a portal, and every time someone does `TAIL <portal_name>` we could return compute and return each element since that timestamp -- not sure whether it would be easier to return compacted/not compacted values.

### More work when idle/less work on TAIL calls

* We could actually create a `TAIL`-like sink that computes values eagerly on each differential diff and do a moral-equivalent of a `mem::swap` every time we get a `TAIL` request from a client. This way we can definitely decide how to compact computed values.

### Live streaming/truly crazy

We could support sticking a socket in the portal and just push computed values to clients. I think we'd need to do some other protocol research to see how to actually push this to clients. There is definitely [some support via Listen][1] for this within the postgres protocol so that we don't need to poll on a tight loop.

### Addons

We could also enhance these by doing something like `TAIL <portal_name> WITH TIMESTAMPS` although that is an extension to sql that we should be sure that we're comfortable how it interacts with other places we could want something like `WITH TIMESTAMPS`.

[1]: https://www.postgresql.org/docs/11/sql-listen.html

**Comment by morsapaes** [comment]
The implementation of `SUBSCRIBE` (formerly known as `TAIL`) has changed significantly over the past years, so closing this issue as stale. cc @chaas
