### ISSUE TITLE
Finalize user options and terminology of Kafka exactly-once Sink 

### ISSUE THREAD

**Issue by aljoscha** [MaterializeInc/materialize#6213]
Right now, there are both the `consistency` option and the `exactly_once` option. You cannot have `exactly_once` without `consistency` but the other way round is allowed. 

Before releasing, we should think about the final set of options we want to provide and their naming.

**Comment by aljoscha** [comment]
@elindsey has said this on the topic before:

>  - I don’t think `consistency` is a well-named config option. I think that should be `consistency_topic` or something more explicit, and I think it gets more confusing now that we have an accompanying `exactly_once`
>  - I don’t think that consistency should imply eo. But I’m also not convinced that consistency should exist as an option - I don’t understand the use case for consistency topics or if we should even expose them as an option
>  - I think `exactly_once` is the closest thing to a name for this that makes sense across products; it seems to be the most common term within the ecosystem. I don’t love the name though, so if there’s something that is more clear (and more clear to people already using kafka, etc. - not just more clear within the context of mz), then I’m all for changing it
> like ruchir said, I do think eo should eventually be the default, so some of these config shennanigans will simplify. But I think it’ll be awhile before we’re there

**Comment by aljoscha** [comment]
@awang has said:

> as for alternate name brainstorming — maybe `deduplicate` ?  and `consistency` --> `emit_consistency_metadata`?

**Comment by aljoscha** [comment]
Note to self: sources have a `consistency` parameter that specifies the consistency *topic* to use. We should harmonise this between sources and sinks. Which we would do by changing the parameter to `consistency_topic` for both sources and sinks.

@elindsey @awang: I think we should still resolve this before the next release. I'm leaning towards a `consistency_topic` parameter. It's explicit and a bit boilerplate-y to have to specify both `exactly_once` and `consistency_topic` for sinks but I think it's ok. WDYT?

**Comment by elindsey** [comment]
That sounds good to me. Making it consistent and explicit seems like a good way to go; later we can always add implicit or default behavior if we want to cut down on boilerplate, but no reason to start there.

**Comment by awang** [comment]
sgtm too.  i like `consistency_topic`
