### ISSUE TITLE
Kafka exactly-once Sink is not actually transactional

### ISSUE THREAD

**Issue by aljoscha** [MaterializeInc/materialize#6214]
In tests, the exactly-once Kafka Sink doesn't use transactions because we never specify a `transactional.id`. The tests don't notice this because we're shutting down `materialized` at a good point. To notice anything we would have to "catch" it at a bad time, say when some of the messages are written but it's not finalized yet. We could do this with chaos/jepsen testing.

Also, you cannot currently specify a `transactional.id` because it's not one of the sanctioned options in `kafka_util::extract_config()`.

**Comment by elindsey** [comment]
Oof, nice catch! Looks like this was dropped in one of my merges - the transactional id should be set around where we process the exactly_once setting off of the sql statement and generate the initial kafka config. It shouldn't be user settable, we can use a persisted unique id from the catalog (I believe it has one that's already suitable but do not remember)

**Comment by aljoscha** [comment]
I think the `name: FullName` could work. *But*, we will get into problems with this once we have multiple parallel producers, and when/if we want to do active/active and/or blue/green deployments.

WDYT?

**Comment by aljoscha** [comment]
Also, we don't have to be too worried about it. If the id we decide on now turns out to not work we can easily change it since it's nothing user facing and changing it doesn't break things.

**Comment by aljoscha** [comment]
Ah, the `GlobalId` we get here is probably better for now: https://github.com/MaterializeInc/materialize/blob/4d1b4eaf4a4e3d8a31ea898835e1404e2ab095c3/src/dataflow/src/sink/kafka.rs#L236
