### ISSUE TITLE
(docs) I only want a materialized view to maintain results from the last X hours

### ISSUE THREAD

**Issue by msudberg** [MaterializeInc/materialize#6225]
Document best way to maintain results only from a limited time period (instead of entire aggregate).

Thread here: https://materializeinc.slack.com/archives/C015EV7MFGS/p1616615409022500

Possible answers:

* temporal filter
* aggregation by period

Concerns:

* intensive memory usage

SMEs: @ruf-io, @frankmcsherry

**Comment by morsapaes** [comment]
Seems covered in the new ["Temporal Filters" guide](https://materialize.com/docs/guides/temporal-filters/#main). Can we close the issue, @msudberg ?
