### ISSUE TITLE
Support for GROUPING SETS/ROLLUP/CUBE

### ISSUE THREAD

**Issue by andrioni** [MaterializeInc/materialize#6245]
`GROUPING SETS`/`ROLLUP`/`CUBE` is [a minor Postgres feature](https://www.postgresql.org/docs/current/queries-table-expressions.html) that can be helpful for building reports. It can easily be emulated by writing repeated statements + `UNION ALL`, but having native support would probably be more memory-efficient (and would make for nice syntax sugar).

**Comment by leonsmith** [comment]
Duplicate of https://github.com/MaterializeInc/materialize/issues/4301 ?

**Comment by andrioni** [comment]
Ah, indeed, nice catch, I completely missed that issue.
