### ISSUE TITLE
(docs) Create a Materialize glossary

### ISSUE THREAD

**Issue by msudberg** [MaterializeInc/materialize#6268]
The glossary should cover:

- Materialize-specific terms
- Database terms useful for understanding Materialize
- Streaming terms useful for understanding Materialize

We might eventually want to use this for pop-up definitions in other docs, but that's not necessary for the first cut.

**Comment by sys3175** [comment]
Hi @msudberg, I'd like to contribute here, so, do you already have a draft? Just checking, I'm also ready to start from scratch.
