### ISSUE TITLE
Documentation for CREATE SINK WITH has diverged from source

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#6279]
### What version of Materialize are you using?

```
v0.7.2-dev (1ae10066b)
```

### What was the issue?

There are a couple of issues on the following page: https://materialize.com/docs/sql/create-sink/

1. The list of supported WITH options on the page has diverged from what is in the source, which can be seen at:

https://github.com/MaterializeInc/materialize/blob/main/src/sql/src/kafka_util.rs#L139

2. The option is named ```sasl_mechanisms``` (plural) in the source but we refer to it as ```sasl_mechanism``` (singular) in the documentation.

3. The list of supported values for ```sasl_mechanisms``` is different in section "Kerberos WITH options" and in section "Kerberized Kafka details"

**Comment by msudberg** [comment]
Per @elindsey, I'm documenting `acks`, `enable_auto_commit`, `sasl_username`, and `sasl_password`, but not `transaction_timeout_ms`, which is for a feature that hasn't shipped yet (exactly once sinks).
