### ISSUE TITLE
Errors not propagated to SUBSCRIBE

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#6292]
### What version of Materialize are you using?

```
v0.7.2-dev (375d3a5a7)
```

### What was the issue?

If a client does a TAIL on a source that has errored out, the error is never reported to the client. Tail proceeds as if the error never happened at all. I think this is wrong.

### Is the issue reproducible? If so, please provide reproduction instructions.

In testdrive, create a source that has an error:

```
$ set null={"type": "record", "name": "field_null", "fields": [ {"name": "f1", "type": "null"} ] }
$ set int={"type": "record", "name": "field_int", "fields": [ {"name": "f1", "type": "int"} ] }

$ kafka-create-topic topic=tail-source-error

$ kafka-ingest format=avro topic=tail-source-error schema=${int} timestamp=1
{"f1": 123}

> CREATE MATERIALIZED SOURCE source_error
  FROM KAFKA BROKER '${testdrive.kafka-addr}' TOPIC 'testdrive-tail-source-error-${testdrive.seed}'
  FORMAT AVRO USING SCHEMA '${int}'
  ENVELOPE NONE

$ kafka-ingest format=avro topic=tail-source-error schema=${null} timestamp=1
{"f1": null}

$ kafka-ingest format=avro topic=tail-source-error schema=${int} timestamp=1
{"f1": 234}

! SELECT * FROM source_error;
avro deserialization error: IO error: UnexpectedEof
```

As you can see, SELECT-ing from such a source produces an error, as expected. Then ,in the postgesql client, do:

```
materialize=> COPY (TAIL source_error) TO STDOUT;
1617266299000	1	123
1617266299000	1	234
```

Rows ingested before and after the error are returned as if the error never happened. I think the TAIL should have errored out.

**Comment by philip-stoev** [comment]
`DROP` is also not reflected in the `TAIL` output, as much as dropping a source can be considered a "source error" situation.

**Comment by aljoscha** [comment]
On the current code base you can reproduce this by running `target/debug/testdrive test/testdrive/kafka-upsert-sources-key-decode-error.td` and then try to subscribe to `int2long`. You will get:
```
materialize=> COPY (SUBSCRIBE int2long) TO STDOUT;
1675419369553	1	1234	nokey1
```

That is the SUBSCRIBE works even though there are errors in there, which don't get reported.
