### ISSUE TITLE
Interrupted TAIL causes an already-deleted source to keep reading from a non-existing Kafka topic

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#6293]
### What version of Materialize are you using?

```
v0.7.2-dev (375d3a5a7)
```

### What was the issue?

This is really weird, but after a TAIL in progress been interrupted, deleting the source and the topic does not seem to prevent MZ from continuing to attempt to read from said topic. The log fills with messages such as:

```
2021-04-01T10:14:43.355211Z ERROR rdkafka::client: librdkafka: Global error: UnknownTopicOrPartition (Broker: Unknown topic or partition): testdrive-tail-source-error-3454290716 [0]: topic does not exist (Broker: Unknown topic or partition)    
```
even though the source has been deleted.

I guess a proper long-term fix for this would require client timeouts and transactional DDL:
- killing TAIL should properly abort and clean up on the server side
- DROPing the source should block or error out if there are pending queries/tails against that source.

### Is the issue reproducible? If so, please provide reproduction instructions.

To reproduce:

1. run this test:

```
$ set int={"type": "record", "name": "field_int", "fields": [ {"name": "f1", "type": "int"} ] }

$ kafka-create-topic topic=tail-source-error

> CREATE MATERIALIZED SOURCE source_error
  FROM KAFKA BROKER '${testdrive.kafka-addr}' TOPIC 'testdrive-tail-source-error-${testdrive.seed}'
  FORMAT AVRO USING SCHEMA '${int}'
  ENVELOPE NONE

! COPY (TAIL source_error) TO STDOUT;
abc
```
2. As the first execution hangs in COPY, use Ctrl +C to abort the test

3. Run the same test again. This will cause testdrive to delete both the source and the topic as being leftovers from the previous test.

4. Yet, observe as the log fills with lines such as:
```
2021-04-01T10:14:43.355211Z ERROR rdkafka::client: librdkafka: Global error: UnknownTopicOrPartition (Broker: Unknown topic or partition): testdrive-tail-source-error-3454290716 [0]: topic does not exist (Broker: Unknown topic or partition)    
```

**Comment by antiguru** [comment]
This also happens when tailing tables. Materialize doesn't prevent dropping tables that are currently tailed.
