### ISSUE TITLE
Properly determine timestamps when using the Debezium transaction topic

### ISSUE THREAD

**Issue by ruchirK** [MaterializeInc/materialize#6296]
Background (I'm going to file a few issues about Debezium, so I'll put a bit more background here):

Debezium supports sending transaction metadata (see: [here](https://debezium.io/documentation/reference/connectors/postgresql.html#postgresql-transaction-metadata)) along with replicated data.

At a high level this consists of two things

* a `transaction` topic that encodes information about open transactions, specifically the id, and the number of messages belonging to each transaction.
* Within each message, there's an additional struct that identifies the transaction id and the total order of that message within the transaction.

Materialize has prototype level support for ingesting Debezium sources with this transaction metadata (see: [here](https://github.com/MaterializeInc/materialize/blob/main/test/testdrive/timestamps-debezium-kafka.td) for an example test) and assigning incoming records timestamps in a way that respects the transactional semantics of the inputs, with some huge caveats.

The biggest caveat IMO, and the subject of this ticket is that Materialize assumes that records will come in order by transaction id, and doesn't support data where records from different transactions are interleaved.

For a specific example: If the transaction topic starts with

```
BEGIN TRANSACTION A
END TRANSACTION A - A CONTAINS 3 MESSAGES FROM foo
BEGIN TRANSACTION B
END TRANSACTION B - B CONTAINS 4 MESSAGES FROM foo
```

then the current code in Materialize assumes that all of the records in `foo` belonging to transaction A occurred at offsets `[0, 3)` in `foo`s data topic, and all of the messages belonging to transaction B occurred at offsets `[3, 7)` in `foo`'s data topic. I can't find anything in the Debezium docs to explicitly validate or invalidate that assumption.

Also a quick aside: transaction ids in all of this are encoded as strings, and are not guaranteed to be numbers or monotonically increase so Materialize currently maps transaction ids to timestamps by counting from 1 (i.e. the first transaction in the transaction topic gets timestamp 1, the second one gets timestamp 2, so on. This approach has pros and cons but fixing that is the subject of another ticket!)

Furthermore, the existing code makes the same kind of assumption if the transactions are interleaved in the transaction topic, e.g. like:

 ```
BEGIN TRANSACTION A
BEGIN TRANSACTION B
END TRANSACTION A - A CONTAINS 3 MESSAGES FROM foo
END TRANSACTION B - B CONTAINS 4 MESSAGES FROM foo
```
in which case I'm pretty sure the assumption that the messages from A would all be output before the messages from B is incorrect.

Concrete asks for this ticket:

0. Sanity check my understanding of both Debezium and the existing code in the timestamper. I'm still not empirically sure whether what we are doing is a correctness bug but I strongly think it is. Having some simple example where Materialize does the wrong thing would be really great
1. Change the timestamper thread in Materialize to report the mapping from `(debezium transaction id) -> (Materialize timestamp, number of messages expected from this table)`
2. Change the behavior when ingesting Debezium records with transaction metadata (in the code this is `BringYourOwn` consistency) to first decode the Avro message, read the inline transaction struct and use the transaction id contained there to determine the appropriate timestamp.
3. Change the behavior when we receive a new message to maintain a counter for "how many messages do we expect at this transaction id" and downgrade the capability to the min transaction id where we still expect to receive messages.
4. The inline transaction struct has a "total order in the txn" field - do we need to use that as a deduplication key?

Testing

I think the setup we've laid out has the following invariants:
a.) Given a sequence of N transactions in the `transaction` topic - Materialize should give the same results at all (0, N] timestamps for all permutations of data in the data topic.

b.) For a given set of N transactions, Materialize should give the same answers at time N for all permutations of the transaction topic and all permutations of the data topic (less sure about this one)

It would be really nice to get some brute force verification of those invariants on say - something like 10 transactions with 100 messages. I'm not super attached to a specific testing approach though, and more want to make sure our understanding of the invariants is correct.

cc: @cirego and @umanwizard

**Comment by cuongdo** [comment]
@cirego are you working on this? if so, please assign this to yourself

**Comment by cirego** [comment]
> @cirego are you working on this? if so, please assign this to yourself

Done!

**Comment by umanwizard** [comment]
I'll work on this in the meantime, while Chris is out.

**Comment by umanwizard** [comment]
After discussion with Ruchir we came to the conclusion that this is probably not urgent enough to be top pri.
