### ISSUE TITLE
DROP-ing the underlying source not propagated to FETCH/TAIL

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#6303]
### What version of Materialize are you using?

```
v0.7.2-dev (375d3a5a7)
```

### What was the issue?

If the underlying source is dropped while a cursor is active, FETCH does not error out:
- if the source is a VALUES view, FETCH continues to return stuff from that table(?!)
- if the source is a TABLE, FETCH retturns an empty result rather than an error
- if the source was a kafka source, FETCH returns an empty result set, rather than an error

### Is the issue reproducible? If so, please provide reproduction instructions.

```
$ kafka-create-topic topic=tail-fetch-after-drop

> CREATE MATERIALIZED SOURCE fetch_after_drop
  FROM KAFKA BROKER '${testdrive.kafka-addr}' TOPIC 'testdrive-tail-fetch-after-drop-${testdrive.seed}'
  WITH( timestamp_frequency_ms = 100 )
  FORMAT AVRO USING SCHEMA '${int}'
  ENVELOPE NONE

> BEGIN

> DECLARE c CURSOR FOR TAIL fetch_after_drop AS OF NOW();

$ kafka-ingest format=avro topic=tail-fetch-after-drop schema=${int} timestamp=1
{"f1": 123}

> FETCH 1 c WITH (timeout='2s');
<TS> 1 123

$ postgres-execute connection=postgres://materialize:materialize@${testdrive.materialized-addr}
DROP SOURCE fetch_after_drop;

! FETCH 1 c WITH (timeout='2s');
some-error
```
The last fetch should have returned an error,  but instead it returned an empty row.

**Comment by philip-stoev** [comment]
Here is an example with TAIL and TABLE and VIEW sources:

```
> CREATE TABLE t1 (f1 INTEGER);

> INSERT INTO t1 VALUES (123);

> CREATE MATERIALIZED VIEW v1 (f1) AS VALUES (123);

> SELECT * FROM t1;
123

> SELECT * FROM v1;
123

> BEGIN

> DECLARE c1 CURSOR FOR TAIL t1 WITH (SNAPSHOT = FALSE);

> DECLARE c2 CURSOR FOR TAIL v1 WITH (SNAPSHOT = FALSE);

> FETCH 1 c1 WITH (timeout='2s');

> FETCH 1 c2 WITH (timeout='2s');

# Drop the view in a separate connection
$ postgres-execute connection=postgres://materialize:materialize@${testdrive.materialized-addr}
DROP TABLE t1;
DROP VIEW v1;

> FETCH 1 c1 WITH (timeout='2s');

> FETCH 1 c2 WITH (timeout='2s');
```

The two final FETCH-es should have errored out in some way.

**Comment by philip-stoev** [comment]
@aljoscha This one is also about propagation of errors, though they are not errors of the stream.

**Comment by aljoscha** [comment]
I looked into how Postgres behaves here. It doesn't have `TAIL` but you can do a `DECLARE c1 CURSOR FOR SELECT * from t1;`.

Postgres doesn't allow dropping the table while the session/transaction that has a cursor on the table is ongoing.

So I see two solutions to this problem:

1. propagate an error to the ongoing TAIL when the table is dropped
2. don't allow dropping tables/views/what have you while there is a cursor

**Comment by uce** [comment]
@ggnall I'm assigning to you, because this seems to be an adapter issue (🙇🏼 for adding the label).

**Comment by ggnall** [comment]
(backlogged but on our radar)

**Comment by jkosh44** [comment]
@philip-stoev Was this fixed by https://github.com/MaterializeInc/materialize/pull/17476, or is this a different issue?

**Comment by jkosh44** [comment]
Closing because I believe this has been resolved. Feel free to re-open if you disagree.
