### ISSUE TITLE
Memory leak when collecting stats

### ISSUE THREAD

**Issue by umanwizard** [MaterializeInc/materialize#6313]
For nonzero values of `statistics_interval_ms`, we observe a memory leak of approximately 10 KB per kafka consumer per statistics interval.

The memory is allocated here: https://github.com/edenhill/librdkafka/blob/1a722553638bba85dbda5050455f7b9a5ef302de/src/rdkafka.c#L1606

We still aren't sure why it's never being freed.

**Comment by cirego** [comment]
I'll start looking at this unless you're already looking, @umanwizard?

**Comment by umanwizard** [comment]
I'm looking at it
