### ISSUE TITLE
Using FETCH from psycopg2 sometimes drops rows

### ISSUE THREAD

**Issue by jamii** [MaterializeInc/materialize#6316]
```
$ materialized -v
materialized v0.7.1 (f4bd159fa)
```
* [x] Linux release tarball

### Is the issue reproducible? If so, please provide reproduction instructions.

https://github.com/jamii/streaming-consistency/tree/00c0095177d454d0051b5e590bbcc124ca3f3bc1/materialize

Make sure to use that commit - I'm trying other approaches in later commits. There are instructions in the readme. 

### What was the issue?

I'm reading in json from a file source, parsing it in a materialized view and reading that view using the psycopg2/FETCH program in the docs (tail.py in my repo). All of the rows from the source appear in the view, but some of them don't appear in the output of fetch.

``` bash
$ wc -l tmp/*
   999801 tmp/accepted_transactions
  1000000 tmp/transactions

$ cat tmp/accepted_transactions | cut -d ' ' -f3 | cut -d')' -f1 | sort -h > out

$ cat tmp/transactions | cut -d ',' -f 1 | cut -d ' ' -f 2 > in

$ diff in out | wc -l
241
$ diff in out | head
989181,989184d989180
< 989180
< 989181
< 989182
< 989183
989437,989440d989432
< 989436
< 989437
< 989438
< 989439
$ diff in out | tail
< 999676
< 999677
< 999678
< 999679
999932,999936d999738
< 999931
< 999932
< 999933
< 999934
< 999935

$ psql postgres://materialize@localhost:6875/materialize
materialize=> select count(*) from accepted_transactions;
  count
---------
 1000000
(1 row)

$ unbuffer psql postgres://materialize@localhost:6875/materialize -c 'copy (tail accepted_transactions) to stdout'> tmp/accepted_transactions2 &
[2] 3495

$ wc -l tmp/accepted_transactions2
1000000 tmp/accepted_transactions2
```

**Comment by benesch** [comment]
@mjibson this seems up your alley.

**Comment by jamii** [comment]
Eugh, this is caused by buffered io. I caught it in the other example but didn't recognize it here because the records are produced out of order and it always ends cleanly at a \n.
