### ISSUE TITLE
DataGrip seems to be incompatible with Materialize

### ISSUE THREAD

**Issue by JakeMakesStuff** [MaterializeInc/materialize#6321]
### What version of Materialize are you using?

```
$ materialized -v
materialized v0.7.2-dev (0a76e9172)
```

### How did you install Materialize?

* [ ] Docker image
* [ ] Linux release tarball
* [ ] APT package
* [ ] macOS release tarball
* [ ] Homebrew tap
* [X] Built from source

### What was the issue?

Using DataGrip results in the following error:
![image](https://user-images.githubusercontent.com/23243233/113481394-442e8400-9491-11eb-8db3-5555ebcc6074.png)

### Is the issue reproducible? If so, please provide reproduction instructions.

Attempt connecting to a Materialize database from DataGrip.

**Comment by elindsey** [comment]
Thanks for the bug report - and sorry for the delay!

While tools like psql will work with mz today, there are portions of postgres' catalog (such as the shdescription you tripped over) that are not yet implemented. The end result is that pgjdbc will not yet work out of the box with Materialize.

We have a fork of the pgjdbc driver [here](https://github.com/MaterializeInc/pgjdbc/); there is some documentation in using it for Metabase [here](https://github.com/MaterializeInc/metabase-materialize-driver#step-1-use-the-forked-pgjdbc-driver-to-connect-to-materialize). Some users have had success using that with DataGrip.

https://github.com/MaterializeInc/materialize/issues/3727 is the tracking task for building out enough of the catalog to support pgjdbc (currently with the aim of supporting Metabase, but applicable to other projects relying on pgjdbc).

**Comment by benesch** [comment]
Just to link these up for posterity: #9720 is now tracking support for DataGrip specifically.
