### ISSUE TITLE
Kafka keytab file required, even if source doesn't use Kerberos

### ISSUE THREAD

**Issue by awang** [MaterializeInc/materialize#6337]
Low priority because there's an easy workaround, but the error message can be a bit confusing:

To reproduce: 
1. Setup a sasl-authenticated Kafka broker
2. Connect to it:
```
CREATE SOURCE kafka_test
FROM KAFKA BROKER <> TOPIC <>
WITH (security_protocol='SASL_PLAINTEXT',
sasl_username=<>,
sasl_password=<>,
sasl_mechanisms=<> ) FORMAT TEXT;
```

An error will be returned:
ERROR:  Can't seem to find local keytab cache. You must provide explicit sasl_kerberos_keytab or sasl_kerberos_kinit_cmd option.

3. Workaround:
Make a blank file:
touch /Users/awang/test/test.keytab

```
CREATE SOURCE kafka_test
FROM KAFKA BROKER <> TOPIC <>
WITH (security_protocol='SASL_PLAINTEXT',
sasl_username=<>,
sasl_password=<>,
sasl_mechanisms=<>,
sasl_kerberos_keytab='/Users/awang/test/test.keytab'
) FORMAT TEXT;
```

**Comment by umanwizard** [comment]
A bit higher priority because the workaround is most likely going away soon.

**Comment by antifuchs** [comment]
Huh, I may be missing something but are you using the right invocation there? In [this test](https://github.com/MaterializeInc/materialize/blob/50eb075dc97980b03fc4e512494a05b002d6efa5/test/kafka-sasl-plain/smoketest.td#L36-L46) we successfully create a sink without a keytab on the plain mechanism.

What exact sasl_mechanism did you use to create the source, @awang?

**Comment by awang** [comment]
Very possible that I'm doing something incorrectly!  

I'm using sasl_plain -- the exact steps to reproduce should be here: https://github.com/MaterializeInc/product/issues/98

**Comment by antifuchs** [comment]
Just ran this on the cloud & could repro. This fix works, however:

```
materialize=> CREATE SOURCE kafka_test
materialize-> FROM KAFKA BROKER 'kafkademo.materialize.io:9092' TOPIC 'nikhiltest'
materialize-> WITH (
materialize(>      sasl_mechanisms='PLAIN',
materialize(>      security_protocol='SASL_PLAINTEXT',
materialize(>      sasl_username='user',
materialize(>      sasl_password='Poxk8XF!ERgfX!rwM@FV'
materialize(> )
materialize-> FORMAT TEXT;
```

Note the `sasl_mechanism='PLAIN'` in there - it's what's missing in the invocation that failed & is present in the one that succeeded.

I'll adjust the error message to mention that argument - I think there may not be any other action needed.

**Comment by elindsey** [comment]
This error in librdkafka can only be hit if the mechanism is gssapi and no keytab is present. gssapi is the default mechamism. 

librdkafka cannot handle lowercase mechanism names, though we do support them - it sounds like we may have a bug in whatever bit of code is trying to convert lowercase mechanisms to uppercase, then it's dropping the config param and picking up the gssapi default. You might want to double-check the lowercase/uppercase config transforms in kafka_util.rs

**Comment by awang** [comment]
Thanks for this!  I seem to still be getting the error though -- with a build off of `7e4fbac08`:

```
materialize=> CREATE SOURCE kafka_test                                                                                                                                                                                          FROM KAFKA BROKER 'kafkademo.materialize.io:9092' TOPIC 'nikhiltest'                                                                                                                                                            WITH (security_protocol='SASL_PLAINTEXT',                                                                                                                                                                                       sasl_username='user',                                                                                                                                                                                                           sasl_password='Poxk8XF!ERgfX!rwM@FV')                                                                                                                                                                                           FORMAT TEXT;
ERROR:  Can't seem to find local keytab cache. With sasl_mechanisms='GSSAPI', you must provide an explicit sasl_kerberos_keytab or sasl_kerberos_kinit_cmd option.
```

However, this isn't as high a priority now that I know what I'm doing wrong -- for posterity, I think the error message is confusing when i inadvertently left off `sasl_mechanism`.  I think I previously tried it with the wrong WITH statement: `sasl_mechanism` (no "s").  It's a pretty confusing error so I still think it's worth fixing for posterity, though

**Comment by antifuchs** [comment]
Right - it is required to pass `sasl_mechanisms='PLAIN'`, otherwise it infers that you want GSSAPI, which requires the keytab.
