### ISSUE TITLE
Support kafka partioning via consumer groups

### ISSUE THREAD

**Issue by parisholley** [MaterializeInc/materialize#6353]
Use Case: Simple ETL

Right now, I see two ways of setting up a mz "cluster":

* HA, multiple nodes listen to the same topics and run same aggregations, put behind load balancer in case one goes down
* Each mz instance handles its own partition allowing:
  * Client to sum results across nodes
  * Split up kafka data in-memory across multiple nodes, write to new topic, use a single "roll-up" node to produce aggregations

In contrast to #6157, consumer groups need to be implemented like any other kafka consumer, only parse the partition it is assigned vs listening to them all.

Vertical scaling only goes so far :)

**Comment by elindsey** [comment]
Hey Paris, thanks for the feature request! I'm going to close this out as a duplicate - consumer groups are a small facet of a larger work item we have to implement a form of horizontal scalability. 🙂
