### ISSUE TITLE
Re-enable S3 SQS notifications testdrive tests

### ISSUE THREAD

**Issue by quodlibetor** [MaterializeInc/materialize#6355]
S3 has no guarantees about how long it takes for SQS notifications to get
set up. Even waiting 5 minutes isn't long enough to get failures down to below once a week.

Possible ideas for improving this (feel free to add more):

* delete and reconfigure the notification policy
* switch to using an sns -> sqs bridge? Seems likely to make it worse because of the extra backend infrastructure, but it's possible that the underlying code path is optimized by the AWS infra team?

**Comment by benesch** [comment]
![image](https://user-images.githubusercontent.com/882976/113740660-ea1b0200-96ce-11eb-90bf-ed55480ab700.png)

So if typically you have to wait 5m, atypically you have to wait... 6m? 10m? 15m? Anyway, it seems like this will never be quite reliable enough for a test that runs on every PR, but maybe we can have a nightly test that's happy to wait for like 15m?

**Comment by philip-stoev** [comment]
S3  and SQS are not supported on the Cloud. Closing this issue until such support is implemented and a new QA plan is decided upon.
