### ISSUE TITLE
CSV file source preserves double-quotes in header column name, making columns impossible to reference.

### ISSUE THREAD

**Issue by ruf-io** [MaterializeInc/materialize#6366]
### What version of Materialize are you using?

```
v0.7.1

```

### How did you install Materialize?

* [ ] Docker image
* [ ] Linux release tarball
* [ x] APT package
* [ ] macOS release tarball
* [ ] Homebrew tap
* [ ] Built from source

### What was the issue?

When a CSV file has double-quotation chars wrapping the column names in the header, they're kept in the column names in Materialize, making it impossible (or at least very difficult) to reference them.

Example CSV File:
```csv
"Name","Age"
"Roger",20
"Wanda",5
```

In Materialize:
```sql
CREATE SOURCE quoted_csv FROM FILE '/path/to/file.csv' FORMAT CSV WITH HEADER;
SHOW COLUMNS FROM quoted_csv
    name    | nullable |  type  
------------+----------+--------
 "Age"      | f        | text
 "Name"     | f        | text
 mz_line_no | f        | bigint
(3 rows)
```

Tried multiple forms of escaping the `"` to try and reference the column to no avail.

### Is the issue reproducible? If so, please provide reproduction instructions.

```
cat >> quoted.csv << EOF
"Name","Age"
"Roger",20
"Wanda",5
EOF
```
In Materialize:
```
CREATE SOURCE quoted_csv FROM FILE '/path/to/file.csv' FORMAT CSV WITH HEADER;
CREATE MATERIALIZED VIEW test3 AS SELECT "Name" AS Name FROM quoted_csv;
```

**Comment by elindsey** [comment]
This one's fixed by some of @bwm's recent work, so I'm closing it out ahead of bugfix day.
