### ISSUE TITLE
When upgrading to 0.7.1 my application breaks. (Last update of a Tail gets queued somewhere)

### ISSUE THREAD

**Issue by crohorner** [MaterializeInc/materialize#6369]
When upgrading to 0.7.1 my application breaks. What happens is that I no longer get the last update of a tail immediately. It is received, but then queued on the application side somewhere.I investigated the network packets, and the protocol implementation changed from 0.7.0 to 0.7.1. See the screenshots. Legend:  

*   <number> = Parse completion/Bind completion
*   B = Bind
*   C = Command completion
*   D = Describe/Data row
*   E = Execute
*   n = No data
*   P = Parse
*   s = Portal suspended
*   S = Sync
*   t = Parameter description
*   Z = Ready for query

The Vert.x PostgreSQL client will not pass the data row to the application if it is the last message that arrived. The data row is read and the column values are extracted.Which system has a broken message flow implementation: Materialize or Vert.x?

Attachments:<br/> [image (1).png](https://materializesupport.zendesk.com/attachments/token/wRxUogWgJXiaPhg19BebFP74m/?name=image+%281%29.png)<br/> [image (2).png](https://materializesupport.zendesk.com/attachments/token/GHzAGzSH10bUuiS595gtrSEpZ/?name=image+%282%29.png) gz#31

**Comment by umanwizard** [comment]
@mjibson are you the right person to take a look at whether this is our bug?

**Comment by frankmcsherry** [comment]
This may be unrelated, but @jamii recently used TAIL and encountered several "bad experiences" related to buffered channels. Things sorted themselves out once he un-buffered the io, but he had to learn about that twice, which seems like it might be error prone. Related issue (closed once he learned how to fix, but still maybe an ergo bug): https://github.com/MaterializeInc/materialize/issues/6316

**Comment by mjibson** [comment]
What queries are being executed here? Due to the portal suspension in the 0.7.0 trace I'd guess a FETCH? Can you tell us about the view the data is coming from as well?

**Comment by umanwizard** [comment]
FYI, issue is from the community slack: https://materializecommunity.slack.com/archives/C015KDVS7EV/p1617789775108000

**Comment by mjibson** [comment]
This was #6307 which has been fixed.
