### ISSUE TITLE
Spurious test error during test on slow hardware

### ISSUE THREAD

**Issue by petrosagg** [MaterializeInc/materialize#6373]
### What version of Materialize are you using?

```
$ materialized -v
v0.7.1
```

### What was the issue?

I got this test failure during a release build of v0.7.1 in a hackintosh VM. My computer was struggling with the VM so it might be a rare race condition that doesn't appear in normal testing. I'm documenting it here for me to investigate later.

### Is the issue reproducible? If so, please provide reproduction instructions.

Not sure. This the full cmdline that triggered it but it was part of a nixpkgs build.
```bash
cargo test -j 2 --release --target x86_64-apple-darwin --frozen -- --test-threads=2 --exact --skip test_client --skip test_client_errors --skip test_no_block
```

### Please attach any applicable log files.

![https://imgur.com/5cfNRWz.png](https://imgur.com/5cfNRWz.png)

**Comment by benesch** [comment]
Closing as ancient. Unmaterialized file sources are long gone.
