### ISSUE TITLE
docs: Cloud doc improvements

### ISSUE THREAD

**Issue by msudberg** [MaterializeInc/materialize#6374]
- Add links to volatile sources doc from demo

- Update PubNub demo instructions to include getting secret key (not urgent, because the current instructions work; but not ideal)
- Add mention of user/certificate sharing to “Connect page”
- Add link to SQL to Quickstart
- Make “Support” “Cloud Support”
- Add default specs for instances
- File sinks not supported
- Add sinks to demo

Deferred till Kafka stream is more stable:
- Add Kafka example

**Comment by awang** [comment]
Kafka isn't stable yet (the demo instance we're hosting the broker on keeps running out of ram), so that one is less stable

**Comment by msudberg** [comment]
Closed with https://github.com/MaterializeInc/materialize/pull/6493
