### ISSUE TITLE
process: what is the approval  process for a design doc?

### ISSUE THREAD

**Issue by benesch** [MaterializeInc/materialize#6376]
Both @frankmcsherry and I are big fans of the new design doc process but realized we don't have an official position on how a design doc gets accepted. Rust has a final comment period (FCP); we probably want to do something similar. An explicit "speak now or forever hold your peace" is useful for ensuring everyone has a chance to speak up but that progress doesn't stall out forever.

This issue tracks a) deciding what we want our FCP to look like, and b) adding a few words about it to the [design doc README](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md).

**Comment by benesch** [comment]
Other process suggestions, from a discussion with @umanwizard:

  * [ ] Require that all design doc PRs are announced when submitted in #eng-announce
  * [ ] Require that FCP (or whatever we call it) is also announced in #eng-announce

**Comment by cuongdo** [comment]
Also, I'd prefer being clearer regarding when we need a design doc. Possible triggers: length of time spent, > 1 engineer working on a project, changes to public interfaces or major private interfaces.
