### ISSUE TITLE
Multipart primary keys are not handled properly by the ENVELOPE UPSERT - second and subsequent parts ignored when ingesting

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#6386]
### What version of Materialize are you using?

```
v0.7.2-dev (57abd907c)
```

### What was the issue?

If a multi-part primary key is defined for a kafka source, the upsert check appears to be made only against the first part of the key.

The optimizer does see both primary key columns, so the metadata appears to be correctly copied over into the source definition.

### Is the issue reproducible? If so, please provide reproduction instructions.

```
$ set keyschema={
    "type": "record",
    "name": "Key",
    "fields": [
        {"name": "key1", "type": "string"},
        {"name": "key2", "type": "string"}
    ]
  }

$ set schema={
        "type" : "record",
        "name" : "test",
        "fields" : [
            {"name":"nokey", "type":"string"}
        ]
    }

$ kafka-create-topic topic=t1

$ kafka-ingest format=avro topic=t1 key-format=avro key-schema=${keyschema} schema=${schema} publish=true
{"key1": "key1val1", "key2": "key2val2"} {"nokey": "nokey1"}
{"key1": "key1val1", "key2": "key2val2"} {"nokey": "nokey2"}
{"key1": "key1val2", "key2": "key2val2"} {"nokey": "nokey3"}

> CREATE MATERIALIZED SOURCE t1
  FROM KAFKA BROKER '${testdrive.kafka-addr}' TOPIC
  'testdrive-t1-${testdrive.seed}'
  FORMAT AVRO USING CONFLUENT SCHEMA REGISTRY '${testdrive.schema-registry-url}'
  ENVELOPE UPSERT;

> SELECT * FROM t1;
key1val1 key2val2 nokey2
key1val2 key2val2 nokey3
```

This test injects 3 unique records but the ```SELECT``` returns only two. It seems that ```key2``` is discarded when deciding that record #2 is a new version of record #1

**Comment by wangandi** [comment]
I'm confused. I only see two unique keys in amongst the three records ingested, so the select statement should return 2 rows.
```
{"key1": "key1val1", "key2": "key2val2"} {"nokey": "nokey1"}
{"key1": "key1val1", "key2": "key2val2"} {"nokey": "nokey2"}
{"key1": "key1val2", "key2": "key2val2"} {"nokey": "nokey3"}
```

**Comment by philip-stoev** [comment]
Yes, my fault, I was injecting wrong records. I must have spaced out. Apologies again. It works as expected with proper data.
