### ISSUE TITLE
"column name is ambiguous" error on SELECT if key schema and value schema define the same column name

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#6390]
### What version of Materialize are you using?

```
v0.7.2-dev (57abd907c)
```

### What was the issue?

The user can define the same column name in the key schema and the value schema. I see this totally happening if the two schemas are generated from the same source or the key schema was generated as a subset of the value schema.

However, in MZ this will cause the creation of two columns in the source that have the same name. This can't be good -- at the very least it breaks column name resolution (as seen below) and makes the column impossible to reference in any context. Historically there have been a couple of panics in the optimizer if identical identifiers show up in the same context.

The workaround is to explicitly specify column names using ```CREATE SOURCE ... (key1, key2)``` syntax.

### Is the issue reproducible? If so, please provide reproduction instructions.

```
$ set key-schema={"type": "record", "name": "s1", "fields": [ {"name": "key", "type": "string"} ] }
$ set value-schema={"type": "record", "name": "s1", "fields": [ {"name": "key", "type": "string"} ] }

$ kafka-create-topic topic=key-value-conflict

$ kafka-ingest format=avro topic=key-value-conflict key-format=avro key-schema=${key-schema} schema=${value-schema} publish=true timestamp=1
{"key": "key1"} {"key": "key2"}

> CREATE MATERIALIZED SOURCE key_value_conflict
  FROM KAFKA BROKER '${testdrive.kafka-addr}' TOPIC 'testdrive-key-value-conflict-${testdrive.seed}'
  FORMAT AVRO USING CONFLUENT SCHEMA REGISTRY '${testdrive.schema-registry-url}'
  ENVELOPE UPSERT

> SELECT * FROM key_value_conflict
key1 key2

! SELECT key FROM key_value_conflict
column name "key" is ambiguous
```

As the final query shows, there are two columns named "key". Possible solutions:

- fail the CREATE SOURCE with the same error, ```column name "key" is ambiguous```
- have just a single column in the source; throw a source error if the two values ingested for the same column do not match.

**Comment by wangandi** [comment]
I think this is a duplicate of #3370.

**Comment by philip-stoev** [comment]
Yes, agreed.
