### ISSUE TITLE
test flake: protobuf kafka streaming-demo

### ISSUE THREAD

**Issue by danhhz** [MaterializeInc/materialize#6391]
It flaked on me twice in https://buildkite.com/materialize/tests/builds/16473#6c8813b2-7375-40fa-aca6-b2d55408e2f4 with the following:

```
C> waiting for schema-registry:8081 29 28 27 26 25 24 23 22 21 20 19 17 16 15 14 13 12 11 10 9 8 7 6 4 3 2 1 0Failed! Unable to connect to schema-registry:8081
--
  | Command failed! Uploading logs for debugging.
  | 2021-04-08 14:53:26 INFO   Found 1 files that match "services.log"
  | 2021-04-08 14:53:26 INFO   Creating (0-1)/1 artifacts
  | 2021-04-08 14:53:26 INFO   Uploading artifact 4a5ba27a-557f-426c-9bdc-3b7a24ba54e4 services.log (271923 bytes)
  | 2021-04-08 14:53:26 INFO   Successfully uploaded artifact "services.log"
  | 2021-04-08 14:53:28 INFO   Artifact uploads completed succesfully
  | 🚨 Error: The command exited with status 1
```

The third time, which passed, schema-registry came up in ~6s so it's not clear that this is a timeout issue. The only possibly related thing I dug up when I looked was https://github.com/MaterializeInc/materialize/issues/4223 where docker for mac ended up being underprovisioned. I also found https://github.com/MaterializeInc/materialize/pull/5587#issuecomment-791825199 but that one seems like kafka was actually misconfigured (whereas my PR that flaked didn't touch any of that).

@ruchirK it looks like you added this test, mind triaging?

**Comment by benesch** [comment]
So looking harder at that log, the schema registry never gets to the point where it says "server started", so it legitimately didn't come up. It's gotta be an ordering thing, where if Kafka boots fast enough then the schema registry also boots fast; but if Kafka boots slow, then the schema registry does some exponential backoff thing that slows it way down. I think it will eventually boot, if we give it enough time, so I opened a PR to just up the timeouts everywhere: https://github.com/MaterializeInc/materialize/pull/6406

**Comment by benesch** [comment]
This seems to have done the trick!
