### ISSUE TITLE
Support for `no_proxy` configuration

### ISSUE THREAD

**Issue by quodlibetor** [MaterializeInc/materialize#6405]
It is currently possible to configure a proxy in materialize by setting the curl-compatible env vars, but we don't support the equivalent `NO_PROXY` env var to bypass the proxy for specific hosts.

Possibly this is implementable using hyper's proxy crate -- I believe that creating a `Proxy` object with `Intercept::None` and a URI might work -- but this use case isn't clearly documented and it might be complex to verify.

**Comment by benesch** [comment]
Well, `NO_PROXY` looks like an absolute mess to support: https://about.gitlab.com/blog/2021/01/27/we-need-to-talk-no-proxy/

Go has a nice, tight, well-specified implementation of `NO_PROXY` support though that we could copy: https://github.com/golang/net/blob/master/http/httpproxy/proxy.go

**Comment by quodlibetor** [comment]
Yeah it looks *very* unpleasant. Based on [the implementation](https://github.com/tafia/hyper-proxy/blob/b392b5258029fb6b89486bf49812fc56c95378a6/src/lib.rs#L154-L165) in hyper-proxy we might be able to do this with an Intercept::Custom implementation.

**Comment by umanwizard** [comment]
@quodlibetor , @benesch do I understand correctly that the implementation of this is relatively easy, and it's figuring out the actual semantics of the variable that is hard?

If so, let's just pick one and document it well. Copying what golang or curl does seems fine.
