### ISSUE TITLE
release process should drop a new release header in release notes

### ISSUE THREAD

**Issue by antifuchs** [MaterializeInc/materialize#6409]
When we're doing the `bin/mkrelease --no-tag -b prepare-$next` step, we should drop a heading for the next release into the release notes doc, so that changes to that will logically belong to the "next" release go into the correct section. (It's probably also fine to make this a manual step, but it should happen as part of the first PR in the release process).

**Comment by benesch** [comment]
I now handle the creation of release notes entirely manually, so this is moot!
