### ISSUE TITLE
Avro migrations: default inside a map definition not respected, only outside of it

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#6433]
### What version of Materialize are you using?

```
v0.7.3-dev (d4208d69f)
```

### What was the issue?

The Avro spec allows for a ```default``` value to be specified inside a ```map``` type definition. This default is then used for records that do not have a value for that field. This however does not work in Materialize, the ```default``` must be outside of the map, in the ```field``` definition to be respected.

That is, this does not work:

```
{
   "fields" : [
      {
         "name" : "f1",
         "type" : {
            "default" : {
               "default_key" : "default_value"
            },
            "type" : "map",
            "values" : "string"
         }
      }
   ],
   "name" : "map_default",
   "type" : "record"
}
```

With the patch from https://github.com/MaterializeInc/materialize/issues/6153, the following error is reported:

```
avro deserialization error: Schema resolution error: Reader field `f1` not found in writer, and has no default
```

But his works:

```
{
   "fields" : [
      {
         "default" : {
            "default_key" : "default_value"
         },
         "name" : "f1",
         "type" : {
            "type" : "map",
            "values" : "string"
         }
      }
   ],
   "name" : "map_default",
   "type" : "record"
}
```

Note the different nesting level for the ```default``` value. A ```default``` inside an ```enum``` definition works as expected.

### Is the issue reproducible? If so, please provide reproduction instructions.
To reproduce:

```
$ set map-default={"type": "record", "name": "map_default", "fields": [ {"name": "f1", "type": { "type": "map", "values": "string", "default" : { "default_key" : "default_value" } } } ] }
$ set no-map={"type": "record", "name": "map_default", "fields": [ ] }

$ kafka-create-topic topic=map-default

$ kafka-ingest format=avro topic=map-default schema=${map-default} publish=true timestamp=1
{"f1" : { "key1" : "value1" } }

> CREATE MATERIALIZED SOURCE map_default
  FROM KAFKA BROKER '${testdrive.kafka-addr}' TOPIC 'testdrive-map-default-${testdrive.seed}'
  FORMAT AVRO USING CONFLUENT SCHEMA REGISTRY '${testdrive.schema-registry-url}'
  ENVELOPE NONE

$ kafka-ingest format=avro topic=map-default schema=${no-map} publish=true timestamp=1
{}

> SELECT f1 -> 'key1', f1 -> 'default_key' FROM map_default;
```

**Comment by umanwizard** [comment]
This seems like it could be a mistake in the spec, as they don't explain what `default` is supposed to mean here -- they only explain that for `default` in a record field definition. It's reasonable to assume that it means the same thing (use the given value as the field default value if the field is missing in the writer schema), but it doesn't seem to make much sense for that to be part of the type (what does it mean, for example, if the type isn't being used as a record field?)

Since the spec is confusing/incomplete, we should check what the official implementations do in this case and follow them.

**Comment by antiguru** [comment]
I think this is a mistake in the spec. The Avro parser does not use the `default` value defined on the type in any useful way. The `default` value on the field is correctly used as the field's default value. The following test within Avor fails as expected:

```java
  @Test
  public void materialize_test() {
    String typeDefault = "{\n" +
      "   \"fields\" : [\n" +
      "      {\n" +
      "         \"name\" : \"f1\",\n" +
      "         \"type\" : {\n" +
      "            \"default\" : {\n" +
      "               \"default_key\" : \"default_value\"\n" +
      "            },\n" +
      "            \"type\" : \"map\",\n" +
      "            \"values\" : \"string\"\n" +
      "         }\n" +
      "      }\n" +
      "   ],\n" +
      "   \"name\" : \"map_default\",\n" +
      "   \"type\" : \"record\"\n" +
      "}";
    String fieldDefault = "{\n" +
      "   \"fields\" : [\n" +
      "      {\n" +
      "         \"default\" : {\n" +
      "            \"default_key\" : \"default_value\"\n" +
      "         },\n" +
      "         \"name\" : \"f1\",\n" +
      "         \"type\" : {\n" +
      "            \"type\" : \"map\",\n" +
      "            \"values\" : \"string\"\n" +
      "         }\n" +
      "      }\n" +
      "   ],\n" +
      "   \"name\" : \"map_default\",\n" +
      "   \"type\" : \"record\"\n" +
      "}";
    Schema typeDefaultSchema = new Schema.Parser().parse(typeDefault);
    Schema fieldDefaultSchema = new Schema.Parser().parse(fieldDefault);
    assertEquals(typeDefaultSchema.getField("f1").defaultVal(), fieldDefaultSchema.getField("f1").defaultVal());
  }
```

Result:
```
java.lang.AssertionError: 
Expected :null
Actual   :{default_key=default_value}
```

Here is my research trail:
* Avro parser: [Schema::parse(...)](https://github.com/apache/avro/blob/68708e718c8f3731768644305b15fcdca2e30a77/lang/java/avro/src/main/java/org/apache/avro/Schema.java#L1635)
  * Default value is extracted from the [fields](https://github.com/apache/avro/blob/68708e718c8f3731768644305b15fcdca2e30a77/lang/java/avro/src/main/java/org/apache/avro/Schema.java#L1682).
* The default value on the type gets stored as a JSON property. I guess that's where all overflow data goes to. It could be that some other module uses the default in the additional JSON data.
* I added the test to [TestSchema](https://github.com/apache/avro/blob/68708e718c8f3731768644305b15fcdca2e30a77/lang/java/avro/src/test/java/org/apache/avro/TestSchema.java)

I'm inclined to closing the issue as WAI, but it could be there are other parsers which are a bit more flexible in what schema they accept. Let's keep it open to gather more opinions!

**Comment by philip-stoev** [comment]
I am fine with closing, it was a niche issue anyway.

**Comment by antiguru** [comment]
It seems the error was introduced with https://github.com/apache/avro/pull/662 and https://issues.apache.org/jira/browse/AVRO-2574. Should we raise it as a concern with Avro?

**Comment by uce** [comment]
@antiguru With my Apache hat on, I'd say yes, please 👍🏼

**Comment by umanwizard** [comment]
What’s the proper channel for reporting issues with the Avro spec? I’ve tried one or two times on the Avro users’ mailing list, but never got a response. Perhaps there’s a better channel for Avro implementors to discuss the spec?

**Comment by uce** [comment]
Creating an issue at https://issues.apache.org/jira/projects/AVRO/issues. If the Jira project requires special permissions for new users to create a ticket, I would suggest to write to the dev mailing list.

Since the PR linked by Moritz was done by a committer/PMC, I'd expect that we will get an answer soonish.

**Comment by antiguru** [comment]
I filed an issue: https://issues.apache.org/jira/browse/AVRO-3155
