### ISSUE TITLE
Fix timestamp binding compaction to do less work

### ISSUE THREAD

**Issue by ruchirK** [MaterializeInc/materialize#6436]
The current implementation of timestamp compaction does an excessive amount of work. See #6277 for more details and a few other small followups

**Comment by elindsey** [comment]
@cjubb39 how much of the existing timestamp compaction logic will survive your ts binding persist PR? Trying to figure out if this task is still relevant

**Comment by cjubb39** [comment]
my PR proper: all of it! My plan is to first make it basically / complete dead code, wait a couple days to hope that the change sticks -- and then, after that, remove everything!  I'll keep an eye on this task and hopefully we can close it out as moot pretty soon!
