### ISSUE TITLE
kafka-stats.td contains a hard-coded hostname "kafka", so fails outside of the testdrive mzcompose environment

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#6459]
### What was the issue?

The kafka-stats.td test expects that ```broker_name``` in the ```mz_kafka_broker_rtt``` table contains kafka. Unfortunately this is only true within the testdrive mzcompose environment but not:
- if you run testdrive locally
- if a container is used that contains kafka+zookeeper+schema_registry , which we need to be using for a third-party testing project.

@cirego 

### Is the issue reproducible? If so, please provide reproduction instructions.

Run the test locally, and not in a container.

```
> SELECT split_part(broker_name, '/', 1) FROM mz_kafka_broker_rtt ORDER BY...
rows didn't match; sleeping to see if dataflow catches up 50ms 75ms 112ms 169ms 253ms 380ms 570ms 854ms 1s 2s 3s 1s
kafka-stats.td:100:1: error: non-matching rows: expected:
[["kafka:9092"]]
got:
[["Ubuntu-2004-focal-64-minimal:9092"]]
Diff:
extra row: ["Ubuntu-2004-focal-64-minimal:9092"]
row missing: ["kafka:9092"]

     |
  99 | # Ignore the text after the '/' because that is autogenerated and not deterministic
 100 | > SELECT split_part(broker_name, '/', 1) FROM mz_kafka_broker_rtt ORDER BY broker_name;
     | ^
```

**Comment by cirego** [comment]
Oops! Will fix this up now!
