### ISSUE TITLE
Improve error handling for ENVELOPE DEBEZIUM without replica identity full

### ISSUE THREAD

**Issue by quodlibetor** [MaterializeInc/materialize#6463]
Currently we don't provide any errors or warnings if a debezium stream comes in and is not configured to use replica identity full. We should put the differential stream into an error state if we detect this situation, until #6392, at which point we should only error if we we're not in `DEBEZIUM UPSERT FULL` (or w/e) mode.

**Comment by benesch** [comment]
We no longer require `REPLICA IDENTITY FULL` when using `ENVELOPE DEBEZIUM`.
