### ISSUE TITLE
docs, cloud: Create demo for how to connect Cloud to BI tool (metabase)

### ISSUE THREAD

**Issue by msudberg** [MaterializeInc/materialize#6466]

**Comment by morsapaes** [comment]
Referencing this recent related thread (internal Slack): https://materializeinc.slack.com/archives/CU7ELJ6E9/p1638973998004200

**Comment by morsapaes** [comment]
All integration guides will be reviewed ahead of GA, including the [Metabase guide](https://materialize.com/docs/integrations/metabase/).
