### ISSUE TITLE
Better error handling for violations of CDCv2 format requirements

### ISSUE THREAD

**Issue by krishmanoh2** [MaterializeInc/materialize#6475]
version: v0.7.1

command:
      - --workers=${MZ_WORKERS:-1}
      - --differential-idle-merge-effort=1000
      - --timely-progress-mode=${MZ_TIMELY_PROGRESS_MODE:-demand}
      - --disable-telemetry
      - --experimental
environment:
      - MZ_LOG=pgwire=debug,info
      - MZ_DEV=1

## Panic error upon delete and insert at the same "time"

Using the Materialize CDC envelope format, we noticed that Materialize crashes when deleting and inserting an existing record in the same "time" (transaction id).

#### Topic setup
In a Kafka broker, create a `TEST_BUG` topic and set the following schema for the event's values: [split.avsc](./split.avsc).

#### Materialize source setup

Create the materialize source:

```sql
create materialized source test_bug from kafka broker '10.47.240.161:9092' topic 'TEST_BUG'
format avro using confluent schema registry 'http://10.47.240.161:8081' envelope materialize;
```

#### Messages production
Using the Kafka Avro producer in the Schema Regitry:

```bash
/usr/bin/kafka-avro-console-producer --bootstrap-server kafka:29092 --topic TEST_BUG --property value.schema.file=split.avsc
```

Insert first record:
```json
{"array":[{"data": {"ALLOCATION_DATE":"DATE","EXPECTED_REVENUE":0,"GUID":"0","ITEM_GUID":"0"},"time":0,"diff":1}]}
{"com.materialize.cdc.progress":{"lower":[0],"upper":[3],"counts":[{"time":0, "count":1}]}}
```

Delete and re-insert record:
```json
{"array":[{"data": {"ALLOCATION_DATE":"","EXPECTED_REVENUE":0,"GUID":"0","ITEM_GUID":"0"},"time": 4, "diff":-1}]}
{"array":[{"data": {"ALLOCATION_DATE":"","EXPECTED_REVENUE":0,"GUID":"0","ITEM_GUID":"0"},"time": 4, "diff": 1}]}
{"com.materialize.cdc.progress":{"lower":[3],"upper":[5],"counts":[{"time":0, "count":2}]}}
```

Upon sending the second set of messages, Materialize crashes with this.

materialized_1  | 2021-04-15T10:03:32.383605Z  INFO dataflow::source::kafka: Activating Kafka queue for TEST_BUG [0] (source u1/25) on worker 0
materialized_1  | 2021-04-15T10:03:32.441702Z  INFO coord::timestamp: Discovered 1 new (1 total) kafka partitions for topic TEST_BUG (source u1)
materialized_1  | 2021-04-15T10:03:34.222570Z ERROR panic: assertion failed: `(left == right)`
materialized_1  |   left: `-1`,
materialized_1  |  right: `1`
materialized_1  | thread: timely:work-0
materialized_1  | location: /cargo/git/checkouts/differential-dataflow-d065d23d797aa027/7bc5338/src/capture.rs:440:33
materialized_1  | version: 0.7.1 (f4bd159fa73d37d44f8ed3f1db13c0c2ff85566f)
materialized_1  | backtrace:
materialized_1  |    0: materialized::handle_panic
materialized_1  |              at var/lib/buildkite-agent/builds/buildkite-builders-i-09b2579864d2174d7-1/materialize/tests/src/materialized/src/bin/materialized/main.rs:651:21
materialized_1  |    1: core::ops::function::Fn::call
materialized_1  |              at usr/local/lib/rustlib/src/rust/library/core/src/ops/function.rs:70:5
materialized_1  |    2: std::panicking::rust_panic_with_hook
materialized_1  |              at rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panicking.rs:597:17
materialized_1  |    3: std::panicking::begin_panic_handler::{{closure}}
materialized_1  |              at rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panicking.rs:499:13
materialized_1  |    4: std::sys_common::backtrace::__rust_end_short_backtrace
materialized_1  |              at rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/sys_common/backtrace.rs:141:18
materialized_1  |    5: rust_begin_unwind
materialized_1  |              at rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panicking.rs:495:5
materialized_1  |    6: std::panicking::begin_panic_fmt
materialized_1  |              at rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panicking.rs:437:5
materialized_1  |    7: differential_dataflow::capture::source::build::{{closure}}::{{closure}}
materialized_1  |              at cargo/git/checkouts/differential-dataflow-d065d23d797aa027/7bc5338/src/capture.rs:440:33
materialized_1  |       timely::dataflow::operators::generic::builder_rc::OperatorBuilder<G>::build::{{closure}}::{{closure}}
materialized_1  |              at cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/ac0a326/timely/src/dataflow/operators/generic/builder_rc.rs:123:31
materialized_1  |       timely::dataflow::operators::generic::builder_rc::OperatorBuilder<G>::build_reschedule::{{closure}}
materialized_1  |              at cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/ac0a326/timely/src/dataflow/operators/generic/builder_rc.rs:163:26
materialized_1  |       <timely::dataflow::operators::generic::builder_raw::OperatorCore<T,L> as timely::scheduling::Schedule>::schedule
materialized_1  |              at cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/ac0a326/timely/src/dataflow/operators/generic/builder_raw.rs:203:9
materialized_1  |    8: timely::progress::subgraph::PerOperatorState<T>::schedule
materialized_1  |              at cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/ac0a326/timely/src/progress/subgraph.rs:656:30
materialized_1  |    9: timely::progress::subgraph::Subgraph<TOuter,TInner>::activate_child
materialized_1  |              at cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/ac0a326/timely/src/progress/subgraph.rs:338:26
materialized_1  |       <timely::progress::subgraph::Subgraph<TOuter,TInner> as timely::scheduling::Schedule>::schedule
materialized_1  |              at cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/ac0a326/timely/src/progress/subgraph.rs:304:17
materialized_1  |   10: timely::progress::subgraph::PerOperatorState<T>::schedule
materialized_1  |              at cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/ac0a326/timely/src/progress/subgraph.rs:656:30
materialized_1  |   11: timely::progress::subgraph::Subgraph<TOuter,TInner>::activate_child
materialized_1  |              at cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/ac0a326/timely/src/progress/subgraph.rs:338:26
materialized_1  |       <timely::progress::subgraph::Subgraph<TOuter,TInner> as timely::scheduling::Schedule>::schedule
materialized_1  |              at cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/ac0a326/timely/src/progress/subgraph.rs:304:17
materialized_1  |   12: timely::worker::Wrapper::step::{{closure}}
materialized_1  |              at cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/ac0a326/timely/src/worker.rs:747:57
materialized_1  |       core::option::Option<T>::map
materialized_1  |              at usr/local/lib/rustlib/src/rust/library/core/src/option.rs:453:29
materialized_1  |       timely::worker::Wrapper::step
materialized_1  |              at cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/ac0a326/timely/src/worker.rs:747:26
materialized_1  |   13: timely::worker::Worker<A>::step_or_park
materialized_1  |              at cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/ac0a326/timely/src/worker.rs:395:38
materialized_1  |   14: dataflow::server::Worker<A>::run
materialized_1  |              at var/lib/buildkite-agent/builds/buildkite-builders-i-09b2579864d2174d7-1/materialize/tests/src/dataflow/src/server.rs:424:13
materialized_1  |   15: dataflow::server::serve::{{closure}}
materialized_1  |              at var/lib/buildkite-agent/builds/buildkite-builders-i-09b2579864d2174d7-1/materialize/tests/src/dataflow/src/server.rs:206:13
materialized_1  |       timely::execute::execute::{{closure}}
materialized_1  |              at cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/ac0a326/timely/src/execute.rs:285:22
materialized_1  |       timely_communication::initialize::initialize_from::{{closure}}
materialized_1  |              at cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/ac0a326/communication/src/initialize.rs:285:33
materialized_1  |       std::sys_common::backtrace::__rust_begin_short_backtrace
materialized_1  |              at usr/local/lib/rustlib/src/rust/library/std/src/sys_common/backtrace.rs:125:18
materialized_1  |   16: std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}}
materialized_1  |              at usr/local/lib/rustlib/src/rust/library/std/src/thread/mod.rs:474:17
materialized_1  |       <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
materialized_1  |              at usr/local/lib/rustlib/src/rust/library/std/src/panic.rs:322:9
materialized_1  |       std::panicking::try::do_call
materialized_1  |              at usr/local/lib/rustlib/src/rust/library/std/src/panicking.rs:381:40
materialized_1  |       std::panicking::try
materialized_1  |              at usr/local/lib/rustlib/src/rust/library/std/src/panicking.rs:345:19
materialized_1  |       std::panic::catch_unwind
materialized_1  |              at usr/local/lib/rustlib/src/rust/library/std/src/panic.rs:396:14
materialized_1  |       std::thread::Builder::spawn_unchecked::{{closure}}
materialized_1  |              at usr/local/lib/rustlib/src/rust/library/std/src/thread/mod.rs:473:30
materialized_1  |       core::ops::function::FnOnce::call_once{{vtable.shim}}
materialized_1  |              at usr/local/lib/rustlib/src/rust/library/core/src/ops/function.rs:227:5
materialized_1  |   17: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
materialized_1  |              at rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/alloc/src/boxed.rs:1307:9
materialized_1  |       <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
materialized_1  |              at rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/alloc/src/boxed.rs:1307:9
materialized_1  |       std::sys::unix::thread::Thread::new::thread_start
materialized_1  |              at rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/sys/unix/thread.rs:71:17
materialized_1  |   18: start_thread
materialized_1  |   19: __clone
materialized_1  |
materialized_1  | materialized encountered an internal error and crashed.
materialized_1  |
materialized_1  | We rely on bug reports to diagnose and fix these errors. Please
materialized_1  | copy and paste the above details and file a report at:
materialized_1  |
materialized_1  |     https://materialize.com/s/bug
materialized_1  |

**Comment by krishmanoh2** [comment]
Schema  

[
  {
    "type": "array",
    "items": {
      "type": "record",
      "name": "update",
      "namespace": "com.materialize.cdc",
      "fields": [
        {
          "name": "data",
          "type": {
            "type": "record",
            "name": "data",
            "fields": [
              {
                "name": "ALLOCATION_DATE",
                "type": "string"
              },
              {
                "name": "EXPECTED_REVENUE",
                "type": "int"
              },
              {
                "name": "GUID",
                "type": "string"
              },
              {
                "name": "ITEM_GUID",
                "type": "string"
              }
            ]
          }
        },
        {
          "name": "time",
          "type": "long"
        },
        {
          "name": "diff",
          "type": "long"
        }
      ]
    }
  },
  {
    "type": "record",
    "name": "progress",
    "namespace": "com.materialize.cdc",
    "fields": [
      {
        "name": "lower",
        "type": {
          "type": "array",
          "items": "long"
        }
      },
      {
        "name": "upper",
        "type": {
          "type": "array",
          "items": "long"
        }
      },
      {
        "name": "counts",
        "type": {
          "type": "array",
          "items": {
            "type": "record",
            "name": "counts",
            "fields": [
              {
                "name": "time",
                "type": "long"
              },
              {
                "name": "count",
                "type": "long"
              }
            ]
          }
        }
      }
    ]
  }
]

**Comment by frankmcsherry** [comment]
This is in-spec for MzCDC, whose requirements are that the data should present at most one `diff` for each `(data, time)` pair. In effect, the data are required to be pre-consolidated, where accumulations for the same `(data, time)` are done beforehand. In the example, there is a +1 and a -1 for the same data and time, which should have been consolidated down to zero (and then suppressed).

This is an important part of the design, because we cannot otherwise distinguish `(data, time, +1)` and `(data, time, +1)` from *duplication* in the steam, which the format is meant to resist.

There is a separate question of whether we should be asserting when this invariant is violated, or how we should communicate observed format errors up. Differential dataflow does a fair bit of work on the implementation (its `capture.rs`) which doesn't understand "error streams" or the like. Also, some of the format errors cannot be detected (e.g. if the wrong numbers of updates are sent, the state can internally compact and a "multiple diffs" (bad) would be interpreted as a "duplication" (harmless) because we discarded the preceding value and cannot tell that it is in conflict.

**Comment by frankmcsherry** [comment]
The docs do not have information on the properties required by the format, beyond the format itself. That is almost certainly the heart of the issue here, that some users thought they were using it as intended but were surprised that it did not work.

We should improve the docs (perhaps this issue can be that, or perhaps we should start a new issue?).

**Comment by benesch** [comment]
Closing as stale. CDCv2 is no longer exposed to users.
