### ISSUE TITLE
Ingest from Kafka Topics : Allow for efficient initial loads when there is a big backlog of messages to be processed

### ISSUE THREAD

**Issue by krishmanoh2** [MaterializeInc/materialize#6486]
Assume the following scenario -

1. Mz is restarted.
2. Sources in kafka
3. Millions of messages need to be processed before mz can be current.
4. The default timestamp_frequency_ms is 1second. This results in slower processing of the initial batch as well as increased memory footprint.
5. While we can change the source definition to set timestamp_frequency_ms to higher values, this results in slower updates for the downstream views when mz is caught up.

Can we have a bootstrap option that allows for faster/efficient processing of the backlog and still maintain the low timestamp frequency when mz is caught up?

**Comment by awang** [comment]
Link to internal discussion where this came up (Week 58):  https://docs.google.com/document/d/1WD6jwAJizVMQhKxG3WY6bDKs_1Qn8-vok7Z60-LjHWA/edit#heading=h.oepnwz56nrio

**Comment by elindsey** [comment]
I'm closing this out; many of the perf characteristics and assumptions are focused on single node and not applicable to platform.
