### ISSUE TITLE
Sources that don't fully mirror the Kafka data

### ISSUE THREAD

**Issue by umanwizard** [MaterializeInc/materialize#651]
Currently when a source is created, we are storing every piece of data we get from the corresponding Kafka topic. Based on discussions with @cuongdo , @frankmcsherry , and @quodlibetor , we have identified a few scenarios in which this is not ideal:

* The topic schema may have many columns, of which only a small subset are relevant for any given query. (Example: app analytics/telemetry logging may contain tons of columns of redundant metadata for every event)

* The user may only be interested in a small subset of rows. (Example: the Kafka topic contains data relating to all of a company's customers, but the user only wants to analyze customer behavior in a particular country).

* The user may need the data in a slightly different format (Example: a timestamp field may be integer seconds since 1970-01-01, whereas the user needs it as a DateTime type)

In all of these cases, it is very wasteful of memory to create the entire source mirroring all the data, and then create views restricting or transforming it. Ideally there would be a way to create sources with only a subset of the data we actually need. We thought of a few ways to do this.

**Proposal 1**: Add projecting and filtering syntax when creating sources; e.g., `CREATE SOURCE 'foo' FROM 'kafka://bar' WITH COLUMNS A, B, C WHERE <expr>`. This has the advantage that it is simple and would not require much effort to implement. On the other hand, it lacks flexibility; in particular, there is no obvious way to add mapping functionality (third bullet point above) without making the syntax even more complicated.

**Proposal 2**: Change `CREATE SOURCE` (or leave it as it is, but create some new syntax like `CREATE NONMATERIALIZED SOURCE`) such that it only creates a mapping of the source name to the Kafka endpoint and schema, without actually mirroring any data. Data would only be stored once an actual view based on the source is created. To get the old behavior back, you could use `CREATE MATERIALIZED VIEW view_name AS SELECT * FROM source_name`. Every time a new view based on the source is created, a new dataflow operator is installed getting only the required columns and rows from Kafka, and the Kafka topic is read back from the beginning in order to populate it.

**Comment by frankmcsherry** [comment]
I believe this is complete?
