### ISSUE TITLE
Collate experimental features in docs

### ISSUE THREAD

**Issue by awang** [MaterializeInc/materialize#6512]
A user requested that we list what key features are enabled by starting Materialize with the `--experimental` flag (source caching, temporal filter, table persistence, etc).

**Comment by frankmcsherry** [comment]
I think there is some counter-pressure that we don't want to "document" experimental things. I'll let @benesch give the strongest opinion on this, but we want to be a bit careful about being super clear on our messaging here that any of these things could change at a moment's notice (or without notice).

**Comment by awang** [comment]
Definitely! My request is more of a change in how we present these features in our docs -- ie, if we are already publicly documenting that a feature is enabled by experimental, ￼￼￼￼￼it would be great to group them together in a single place, so users don't have to hunt across different pages in our docs

**Comment by benesch** [comment]
This seems fine if we're willing to mark the list of experimental features as non exhaustive. Maintaining an exhaustive list would be a bit against the spirit of experimental features (which is to free us of the maintenance burdens of a stable feature).

**Comment by morsapaes** [comment]
Closing this issue since we seem to have agreed on reserving `--experimental` for features we don't want to expose to users (_i.e._ as more of an internal flag). 

All features that are out of experimental but not fully stable and/or baked are marked as beta in the docs.
