### ISSUE TITLE
If BYO timestamp topic does not exist, timestamper thread exits

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#6554]
### What version of Materialize are you using?

```
v0.7.3-dev (7658bbf64)
```

### What was the issue?

Debezium appears to take up to 60 seconds to create the transactional consistency topic. If ```CREATE SOURCE``` is issued during that time, the folowing warning is logged:

```
2021-04-23T11:23:53.387448Z  WARN coord::timestamp: Consistency topic postgres.transaction does not exist; assuming it will exist soon    
```

so far , so good but then we get:

```
2021-04-23T11:23:53.447938Z ERROR coord::timestamp: Failed to process message Message consumption error: UnknownTopicOrPartition (Broker: Unknown topic or partition) 
```

Which I assume means the thread is now gone, as no further messages about retries are logged. The timestamp of the source never advances and the source can not be queried.

**Comment by cirego** [comment]
Regarding the 60 second creation time -- I've observed a number of delays in Debezium + Kafka and it's not always clear which component is to blame.

In this scenario, would it make more sense to purify the `SOURCE` creation statement to fail if consistency topic does not exist?

**Comment by philip-stoev** [comment]
Yes , I think it is safest to bail out at ```CREATE SOURCE``` time rather than wait for the topic to come up with all the attendant opportunities for race conditions. Thanks.

**Comment by elindsey** [comment]
BYO is gone
