### ISSUE TITLE
Minio S3 support

### ISSUE THREAD

**Issue by gedw99** [MaterializeInc/materialize#6568]
Materialized has support for s3 sources : https://materialize.com/docs/sql/create-source/ and it would be nice if i can use minio as a s3 source. 

Minio has a subscription mechanism to tell Materialized when a bucket record changes: https://docs.min.io/docs/minio-bucket-notification-guide.html

Minio has a Rust lib: https://github.com/minio/minio-rs so it can work with Materialized.
This lib includes notifications: https://github.com/minio/minio-rs/blob/master/src/minio/api_notification.rs
Its Apache license so prob ok for Materialized: https://github.com/minio/minio-rs/blob/master/LICENSE

**Comment by ruf-io** [comment]
Thanks for reporting @gedw99 - I'm curious, have you tried using minio as a Source as if it were S3, without the SQS notifications features? I assume minio S3 compatibility allows you to at least get that far.

Right now our main priority for Source integration work is going to be Postgres and message brokers, but we can leave this issue open and track interest to prioritize any Minio work.

**Comment by dantodor** [comment]
If I might add, there are also other services that offer S3 interface, like wasabi.com, or localstack ... is it possible to just expose the api endpoint as a config parameter ?

**Comment by benesch** [comment]
> If I might add, there are also other services that offer S3 interface, like wasabi.com, or localstack ... is it possible to just expose the api endpoint as a config parameter ?

I didn't tell you this, but there is an undocumented `endpoint` option that you can specify in the `WITH` clause that works like this. We're talking about officially documenting that, but in the meantime you're welcome to use it as long as you accept that it is not a configuration that we officially support.

**Comment by petrosagg** [comment]
Closing until we re-add S3 sources
