### ISSUE TITLE
Kafka misspelled

### ISSUE THREAD

**Issue by michael-hollander** [MaterializeInc/materialize#6575]
In the Ingesting data section:

Sources: Ingesting data

For Materialize to ingest data, it must read it from a source, of which there are two varieties:

    Streaming sources, like **_Kakfa_**

### What version of Materialize are you using?

```
$ materialized -v

```

### How did you install Materialize?

* [ ] Docker image
* [ ] Linux release tarball
* [ ] APT package
* [ ] macOS release tarball
* [ ] Homebrew tap
* [ ] Built from source

**Comment by awang** [comment]
Thanks for the report @michael-hollander!  For posterity, the typo can be found here: https://materialize.com/docs/overview/architecture/#sources-ingesting-data

**Comment by elindsey** [comment]
Thanks for the report! This one was fixed some time ago.
