### ISSUE TITLE
[test issue] Consolidation depends on the order of message arrivals between the source topic and the consistency topic

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#6584]
### What version of Materialize are you using?

```
materialized v0.7.3-dev (c8cfd0675)
```

### What was the issue?

@frankmcsherry @benesch 

This issue was discovered by our friends at that company.

The comments in ```consolidation.td``` seem to imply that updates made in individual transactions should remain separate and never be consolidated together. However, this is not always the case, depending on timing between the source topic and the consistency topic and the processing of the events from the two topics.

The test simulates the arrival of 3 independent transactions and expects that the sink will also report 3 separate updates. 

A single message is produced by the sink:
```
{"before":null,"after":{"row":{"num":5}}}
```

even though the expectation is that 3 separate messages will be produced:

```
{"before": null, "after": {"row": {"num": 3}}}
{"before": {"row": {"num": 3}}, "after": {"row": {"num": 4}}}
{"before": {"row": {"num": 4}}, "after": {"row": {"num": 5}}
```

At the same time, the test expects that TAIL will consolidate, which is confusing.

### Is the issue reproducible? If so, please provide reproduction instructions.

To reproduce:

1. Run Mzcompose in single core:
```
taskset -c 0 target/release/materialized --workers 1 --logical-compaction-window off
```

2. apply the following diff to ```consolidation.td``` to switch the order of ingestion between the two topics:

```
diff --git a/test/testdrive/consolidation.td b/test/testdrive/consolidation.td
index eb9055708..c5bcd4024 100644
--- a/test/testdrive/consolidation.td
+++ b/test/testdrive/consolidation.td
@@ -91,13 +91,6 @@ $ kafka-create-topic topic=tx
 # Ingest several updates that consolidate. Some of these updates are in one
 # transaction, and some of them are in their own transactions.
 
-$ kafka-ingest format=avro topic=nums schema=${nums-schema}
-{"before": null, "after": {"row": {"num": 1}}}
-{"before": {"row": {"num": 1}}, "after": {"row": {"num": 2}}}
-{"before": {"row": {"num": 2}}, "after": {"row": {"num": 3}}}
-{"before": {"row": {"num": 3}}, "after": {"row": {"num": 4}}}
-{"before": {"row": {"num": 4}}, "after": {"row": {"num": 5}}}
-
 $ kafka-ingest format=avro topic=tx schema=${tx-schema}
 {"status": "BEGIN", "id": "1", "event_count": null, "data_collections": null}
 {"status": "END", "id": "1", "event_count": {"long": 3}, "data_collections": {"array": [{"event_count": 3, "data_collection": "testdrive-nums-${testdrive.seed}"}]}}
@@ -106,6 +99,13 @@ $ kafka-ingest format=avro topic=tx schema=${tx-schema}
 {"status": "BEGIN", "id": "3", "event_count": null, "data_collections": null}
 {"status": "END", "id": "3", "event_count": {"long": 1}, "data_collections": {"array": [{"event_count": 1, "data_collection": "testdrive-nums-${testdrive.seed}"}]}}
 
+$ kafka-ingest format=avro topic=nums schema=${nums-schema}
+{"before": null, "after": {"row": {"num": 1}}}
+{"before": {"row": {"num": 1}}, "after": {"row": {"num": 2}}}
+{"before": {"row": {"num": 2}}, "after": {"row": {"num": 3}}}
+{"before": {"row": {"num": 3}}, "after": {"row": {"num": 4}}}
+{"before": {"row": {"num": 4}}, "after": {"row": {"num": 5}}}
+
 # Test that by default updates that occurred at the same time are consolidated,
 # but updates that occurred at distinct times are not.
 
```

And you will get the following failures:

```
Verifying results in Kafka topic nums-sink-u22-1619515837-9909957470588004119
consolidation.td:116:1: error: record 0 did not match
expected:
(
    None,
    Record(
        [
            (
                "before",
                Union {
                    index: 0,
                    inner: Null,
                    n_variants: 2,
                    null_variant: Some(
                        0,
                    ),
                },
            ),
            (
                "after",
                Union {
                    index: 1,
                    inner: Record(
                        [
                            (
                                "num",
                                Long(
                                    3,
                                ),
                            ),
                        ],
                    ),
                    n_variants: 2,
                    null_variant: Some(
                        0,
                    ),
                },
            ),
        ],
    ),
)

actual:
(
    None,
    Record(
        [
            (
                "before",
                Union {
                    index: 0,
                    inner: Null,
                    n_variants: 2,
                    null_variant: Some(
                        0,
                    ),
                },
            ),
            (
                "after",
                Union {
                    index: 1,
                    inner: Record(
                        [
                            (
                                "num",
                                Long(
                                    5,
                                ),
                            ),
                        ],
                    ),
                    n_variants: 2,
                    null_variant: Some(
                        0,
                    ),
                },
            ),
        ],
    ),
)
```

Essentially, the tests expects to get num = 3 first, but the sink produces num = 5 directly, that is, updates from multiple separate transactions have been consolidated together.

**Comment by frankmcsherry** [comment]
I'm looking at `consolidation.td`, and I'm not sure that I understand the error. First, `TAIL` doesn't seem to occur in the file.

The comments I think you mean are probably
```
# Disable logical compaction, to ensure we can view historical detail.
> ALTER INDEX materialize.public.nums_primary_idx
  SET (logical_compaction_window = 'off')
```
which should do what it says. Unfortunately, these comments pre-date the removal of `AS OF` from sink definitions, which is the only way that we guarantee that you will see historical detail. The query that would have been certain to present un-consolidated updates would be:
```
# TODO(benesch): re-enable when we support `CREATE SINK ... AS OF`.
# # Test that a Debezium sink created `AS OF 3` (the latest completed timestamp)
# # is fully consolidated.
# > CREATE SINK nums_sink FROM nums
#   INTO KAFKA BROKER '${testdrive.kafka-addr}' TOPIC 'nums-sink'
#   FORMAT AVRO USING CONFLUENT SCHEMA REGISTRY '${testdrive.schema-registry-url}'
#   AS OF 3
```
But, we've removed the `AS OF` modifier for sinks (https://github.com/MaterializeInc/materialize/pull/5866) so we no longer provide the guarantee that you will see all updates for a sink (or specifically, MZ will choose an `as_of` time, and you will only see updates from that time forward).

Does this line up with what you are seeing?

**Comment by philip-stoev** [comment]
@frankmcsherry . So the test is then incorrect in its expectations that the sink will have 1 message per transaction:

```
$ kafka-verify format=avro sink=materialize.public.nums_sink
{"before": null, "after": {"row": {"num": 3}}}
{"before": {"row": {"num": 3}}, "after": {"row": {"num": 4}}}
{"before": {"row": {"num": 4}}, "after": {"row": {"num": 5}}}
```

If so, then this part of the test needs to be removed. Or maybe the entire test is no longer relevant if there are no guarantees about being able to see the updates from  individual transactions separately?

There is TAIL in the test:

```
> BEGIN
> DECLARE cur CURSOR FOR TAIL nums AS OF 3
> FETCH ALL cur
timestamp  diff  num
--------------------
3          1     5
> COMMIT
```

**Comment by frankmcsherry** [comment]
> There is TAIL in the test:

Ah sorry, my search-for in VSCode had enabled case-sensitivity (`tail` does not exist, outside of `detail`). You are correct!

**Comment by frankmcsherry** [comment]
This `TAIL` does have an `AS OF`, so it would be wrong that it has a potentially ambiguous output. However, it looks like the error you are observing, `consolidation.td:116:1: error: record 0 did not match`, is not about `TAIL` but about the sink created at line `112`.

**Comment by philip-stoev** [comment]
@frankmcsherry yes, so the question is, can the sink legitimately return consolidated output or it is supposed to return individual outputs for individual transactions? If yes, then the test is incorrect . 

I guess from your explanations above the sink is free to return consolidated output, so the test needs to be fixed.

**Comment by philip-stoev** [comment]
This issue now affects the Nightly CI, no Antithesis involvement is required https://buildkite.com/materialize/nightlies/builds/950#018180bd-f427-4714-a5ec-0d4ef6c378a9

**Comment by uce** [comment]
@philip-stoev is assigned to fix the test issue. On top of that, should look into this in the context of #11503.

**Comment by philip-stoev** [comment]
The test was substantially rewritten by Petros in 

```
commit 15f427124abc5c5bebef5025a22b3cec2295730a
Author: Petros Angelatos <petrosagg@gmail.com>
Date:   Wed Feb 2 10:43:45 2022 +0100

    test: emit correct CDCv2 data in consolidation test
    
    Using BYO sources we were able to emit multiple updates for a given
```

so all the comments in this ticket are obsolete and only muddle the picture, with the exception of the one about this failure https://buildkite.com/materialize/nightlies/builds/950#018180bd-f427-4714-a5ec-0d4ef6c378a9 

I am closing this issue to avoid further confusion about what was tested before and what is being tested now. Will open a fresh ticket about any new failures going forward.
