### ISSUE TITLE
Transient Kafka broker failure causes source to permanently stop updating without erroring out

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#6586]
### What version of Materialize are you using?

```
materialized v0.7.3-dev (c8cfd0675)
```

### What was the issue?

May be related to the consistency topic ( see another interaction at #6555)

This issue was observed by our friends with the test.

If the kafka broker does not respond even for 10 seconds, materialized will print this in the log:

```
2021-04-27T11:37:42.539504Z  WARN librdkafka: librdkafka: REQTMOUT [thrd:GroupCoordinator]: GroupCoordinator/0: Timed out 1 in-flight, 0 retry-queued, 0 out-queue, 0 partially-sent requests    
2021-04-27T11:37:42.539554Z ERROR librdkafka: librdkafka: FAIL [thrd:GroupCoordinator]: GroupCoordinator: Ubuntu-2004-focal-64-minimal:9092: 1 request(s) timed out: disconnect (after 18016ms in state UP, 1 identical error(s) suppressed)    
2021-04-27T11:37:42.552139Z ERROR rdkafka::client: librdkafka: Global error: OperationTimedOut (Local: Timed out): GroupCoordinator: Ubuntu-2004-focal-64-minimal:9092: 1 request(s) timed out: disconnect (after 18016ms in state UP, 1 identical error(s) suppressed)    
```

There is no indication in the message or elsewhere what is going to happen, but in practice:
 - the source does not return an error but
 - no new messages will be ingested even after the broker has been restored 

Viewing the topic through a console consumer shows that newer messages are indeed available. ```mz_source_info``` will show that the timestamp has not advanced to the latest one available.

I added some printlns and it appears that (some sort of a) ```poll``` loop continues to run, so it does not seem that this is about the thread erroring out and exiting completely. Instead, I have a gut feeling that a message is being ingested and then discarded, which causes the BYO consistency thing to become desynchronized with respect to the data topic. We have at least one instance where we call ```poll()``` and then confidently discard the message.

### Is the issue reproducible? If so, please provide reproduction instructions.
To reproduce:

1. Run the ```consolidation.td``` test in a loop:

```bash
while ../../target/release/testdrive consolidation.td --default-timeout 45 ; do :; done
```

2. While the loop is running, stop and continue your kafka process:

```bash
export kafka_pid=$(ps aux | grep kafka.Kafka | grep java  | awk -F ' ' '{print $2}'); \
while [[ -n "$kafka_pid" ]] ; do echo "stopping $kafka_pid"; kill -SIGSTOP "${kafka_pid}" ; sleep 10 ; echo continuing ; kill -SIGCONT $kafka_pid ; sleep 10 ; done
```

3. After a minute, the testdrive will hang as follows:

```sql
> SELECT * FROM nums AS OF 2
query error didn't match; sleeping to see if dataflow produces error shortly 50ms 75ms 112ms 169ms 253ms 380ms 570ms 854ms 1s 2s 3s 4s 6s 10s 15s 22s 33s...
```

This is an indication that the timestamp "2" was not compacted as expected because no new timestamp has arrived to trigger the compaction.

4. Log in with the psql client:
```
materialize=> select * from nums;
 num 
-----
   5
(1 row)
```

num = 5 even though the source has num = 6 (unblock the kafka process with SIGCONT in order to read topics):

```json
{"before":null,"after":{"row":{"a":1}}}
{"before":{"row":{"a":1}},"after":{"row":{"a":2}}}
{"before":{"row":{"a":2}},"after":{"row":{"a":3}}}
{"before":{"row":{"a":3}},"after":{"row":{"a":4}}}
{"before":{"row":{"a":4}},"after":{"row":{"a":5}}}
{"before":{"row":{"a":5}},"after":{"row":{"a":6}}}
```

5. Restore the kafka broker with SIGCONT . Mz does not make progress at all.

**Comment by cuongdo** [comment]
@quodlibetor Where do we stand with this bug?

**Comment by cuongdo** [comment]
@quodlibetor we could use an update on this bug, as well as a plan to make progress

**Comment by quodlibetor** [comment]
## Was it in rdkafka?

The first thing that I investigated was exactly how it could be possible for rdkafka to
permanently disconnect. It is well-designed, though, and essentially always reconnects after any
timeout.

I started by adding a backtrace to the error handler that was generating some of the concerning
logs to see some relevant code paths:

```text
   3: rdkafka::client::native_error_cb
   4: _rd_kafka_poll_cb
   5: _rd_kafka_op_handle
   6: _rd_kafka_q_serve
   7: _rd_kafka_poll
   8: rdkafka::consumer::base_consumer::BaseConsumer<C>::poll_raw
   9: rdkafka::consumer::base_consumer::BaseConsumer<C>::poll
  10: coord::timestamp::kafka_get_next_message
```

Our entrypoint to getting messages from kafka is `BaseConsumer::poll` (in both [timestamp.rs](https://github.com/MaterializeInc/materialize/blob/ee6e7fc1ba1e481993f1d4fe290193ae375ad9e1/src/coord/src/timestamp.rs#L203) and [dataflow/./kafka.rs](https://github.com/MaterializeInc/materialize/blob/main/src/dataflow/src/source/kafka.rs#L278)). That eventually goes through the [`rd_kafka_poll`](https://github.com/edenhill/librdkafka/blob/1a722553638bba85dbda5050455f7b9a5ef302de/src/rdkafka.c#L3840-L3852)/[`rd_kafka_q_serve`](https://github.com/edenhill/librdkafka/blob/1a722553638bba85dbda5050455f7b9a5ef302de/src/rdkafka_queue.c#L434-L445), which on disconnect do occassionally call `rd_kafka_cgrp_revoke_all_rejoin`.

<details>
<summary>In particular, applying this patch to rdkafka-sys</summary>

```patch
diff --git a/src/rdkafka_cgrp.c b/src/rdkafka_cgrp.c
index 11345fdc..d763f44c 100644
--- a/src/rdkafka_cgrp.c
+++ b/src/rdkafka_cgrp.c
@@ -3845,6 +3845,8 @@ static void rd_kafka_cgrp_revoke_all_rejoin (rd_kafka_cgrp_t *rkcg,
             protocol == RD_KAFKA_REBALANCE_PROTOCOL_NONE) {
                 /* EAGER case (or initial subscribe) - revoke partitions which
                  * will be followed by rejoin, if required. */
+                rd_kafka_log(rkcg->rkcg_rk, LOG_WARNING, "REJOIN",
+                             "eager rejoin assignment lost=%d", assignment_lost);

                 if (assignment_lost)
                         rd_kafka_cgrp_assignment_set_lost(
@@ -3856,11 +3858,16 @@ static void rd_kafka_cgrp_revoke_all_rejoin (rd_kafka_cgrp_t *rkcg,
                  * outstanding rebalance op in progress. */
                 if (rkcg->rkcg_group_assignment &&
                     !RD_KAFKA_CGRP_WAIT_ASSIGN_CALL(rkcg)) {
+
+                        rd_kafka_log(rkcg->rkcg_rk, LOG_WARNING, "REJOIN", "using backoff");
+
                         rd_kafka_rebalance_op(
                                 rkcg,
                                 RD_KAFKA_RESP_ERR__REVOKE_PARTITIONS,
                                 rkcg->rkcg_group_assignment, reason);
                 } else {
+                        rd_kafka_log(rkcg->rkcg_rk, LOG_WARNING, "REJOIN", "no backoff");
+
                         /* Skip the join backoff */
                         rd_interval_reset(&rkcg->rkcg_join_intvl);
```

</details>

results in good logs:

```text
WARN librdkafka: librdkafka: SESSTMOUT [thrd:main]: Consumer group session timed out (in jss): revoking assignment and rejoining group
WARN librdkafka: librdkafka: REJOIN [thrd:main]: eager rejoin assignment lost=1
WARN librdkafka: librdkafka: REJOIN [thrd:main]: using backoff
```

So looking purely at rdkafka, it seems like it's doing the right thing.


## Are we just not getting the data?

Short answer: no.

This patch in `timestamp.rs`

```patch
index cf1e9b1b2..69f4c976d 100644
--- a/src/coord/src/timestamp.rs
+++ b/src/coord/src/timestamp.rs
@@ -282,6 +291,7 @@ fn update_source_timestamps(
                 // The first 5 bytes are reserved for the schema id/schema registry information
                 let mut bytes = &msg[5..];
                 let res = mz_avro::from_avro_datum(&DEBEZIUM_TRX_SCHEMA_VALUE, &mut bytes);
+                eprintln!("got result: {:?}", res);
                 match res {
                     Err(_) => {
                         // This was a key message, can safely ignore it
```

shows us getting the data as expected:

```text
got result: Ok(Record([("status", String("BEGIN")), ("id", String("1")), ("event_count", Union { index: 0, inner: Null,
t: Some(0) })]))
got result: Ok(Record([("status", String("END")), ("id", String("1")), ("event_count", Union { index: 1, inner: Long(3) n", String("testdrive-nums-4007002211")), ("event_count", Long(3))])]), n_variants: 2, null_variant: Some(0) })]))
2021-06-01T16:44:29.587028Z  WARN coord::timestamp: iterating over results [("testdrive-nums-4007002211", 3)]
2021-06-01T16:44:29.587112Z  WARN coord::timestamp: sending advance source timestamp id=u1 last_ts=19, last_offset=31 got result: Ok(Record([("status", String("BEGIN")), ("id", String("2")), ("event_count", Union { index: 0, inner: Null, t: Some(0) })]))
2021-06-01T16:44:29.587254Z  WARN coord::coord: advancing source timestamp AdvanceSourceTimestamp { id: User(1), update
2021-06-01T16:44:29.587295Z  WARN coord::coord: broadcasting AdvanceSourceTimestamp id=u1 update=BringYourOwn(Kafka(0), got result: Ok(Record([("status", String("END")), ("id", String("2")), ("event_count", Union { index: 1, inner: Long(1) n", String("testdrive-nums-4007002211")), ("event_count", Long(1))])]), n_variants: 2, null_variant: Some(0) })]))
2021-06-01T16:44:29.587550Z  WARN coord::timestamp: sending advance source timestamp id=u1 last_ts=20, last_offset=32 got result: Ok(Record([("status", String("BEGIN")), ("id", String("3")), ("event_count", Union { index: 0, inner: Null, t: Some(0) })]))
got result: Ok(Record([("status", String("END")), ("id", String("3")), ("event_count", Union { index: 1, inner: Long(1), n_variants: 2, null_variant: Some(0) }), ("data_collections", Union { index: 1, inner: Array([Record([("data_collection", String("testdrive-nums-820423295")), ("event_count", Long(1))])]), n_variants: 2, null_variant: Some(0) })]))
```

Additional investigation of the broadcast code does show the end messages making it into dataflow.

## Are we just not finding matching timestamps?

Again, no. Using a similar strategy, inserting some introspection code in [`find_matching_timestamp`](https://github.com/MaterializeInc/materialize/blob/1ce733297d68d95c1261065efb76a378826d49df/src/dataflow/src/source/mod.rs#L759-L770) shows us finding the exact same timestamps in both successfull and failed runs of the test.

## mz

point (3) is actually incorrect:

> 3. After a minute, the testdrive will hang as follows:
>
> ```
> > SELECT * FROM nums AS OF 2
> query error didn't match; sleeping to see if dataflow produces error shortly 50ms 75ms 112ms 169ms 253ms 380ms 570ms 854ms 1s 2s 3s 4s 6s 10s 15s 22s 33s...
> ```
>
> This is an indication that the timestamp "2" was not compacted as expected because no new
> timestamp has arrived to trigger the compaction.

that error happens because 2 was compacted when it wasn't *expected* to be compacted.

There is still a bug here though, because commenting out the 3 non-compaction tests still causes errors through the rest of the consolidation file.

**Comment by philip-stoev** [comment]
@quodlibetor that is a massive debugging effort, apologies for sending you on a wild goose chase! If this ```AS OF X``` thing complicates things, should I find another test that fails that does not rely on compaction -- from Antithesis testing it seems that tests unrelated to compaction are also failing in a similar manner.

There is at least one more bug -- librdkafka reports an ```ERROR``` in the log and then it does not report that the error has been resolved. Users will be very confused as to what has happened.

**Comment by quodlibetor** [comment]
the `AS OF X` issue didn't distract me for very long, I just thought it was worth pointing out, as mentioned there's definitely another bug. 

If you have an list of other tests that fail in similar ways that definitely might help me narrow down or expand my search, I'd appreciate any subset of them.

**Comment by aljoscha** [comment]
I snatched this one because I had a hunch about what might be the problem. I hope that's alright: :bow:
