### ISSUE TITLE
Postgres source: timestamptz unsupported

### ISSUE THREAD

**Issue by awang** [MaterializeInc/materialize#6600]
The Postgres source incorrectly disallows source tables of format `timestamptz`, even though Materialize supports them:

Postgres:
`create table foo (bar int, baz int, foobar timestamptz default current_timestamp);`

Materialize:
```
materialize=> create materialized source "test" FROM POSTGRES HOST 'host=localhost port=5452 ...' PUBLICATION 'mz_source' NAMESPACE 'public' TABLE 'foo';
CREATE SOURCE
materialize=> select * from test;
ERROR:  Source error: File IO: Unsupported data type Timestamptz
```

Tested on nightly build 0ae7cf3b1

**Comment by petrosagg** [comment]
The current implementation supports all datatypes that mz supports
