### ISSUE TITLE
s3 sources: Support for in-order reads

### ISSUE THREAD

**Issue by quodlibetor** [MaterializeInc/materialize#6606]
Currently our S3 sources don't guarantee anything about the order that they will read objects in, and we may read them in parallel and therefore out of order. 

We know that some formats (e.g. Cockroach CDC) can provide consistent snapshots at all points in time with in-order traversal, and we suspect that other folks _may_ prefer using guaranteed in-order traversal.

CC #4914

**Comment by benesch** [comment]
Closing as we no longer support S3 sources.
