### ISSUE TITLE
dbt-materialize: update CREATE macros to rename database objects instead of dropping them

### ISSUE THREAD

**Issue by JLDLaughlin** [MaterializeInc/materialize#6636]
Background can be found [here](https://github.com/MaterializeInc/materialize/issues/6622). 

When `CREATE`ing a new database object, most dbt adapters rename the previously existing object, if it exists. Currently, the dbt-materialize adapter simply `DROP`s any preexisting objects. Now that we can [rename materialized sources, views, and tables](https://github.com/MaterializeInc/materialize/pull/6623), we should update the adapter to match the others.

**Comment by morsapaes** [comment]
Closing in favour of #14671.
