### ISSUE TITLE
dbt-materialize: investigate "dbt seed" failure when run multiple times

### ISSUE THREAD

**Issue by JLDLaughlin** [MaterializeInc/materialize#6637]
A [user reported](https://materializecommunity.slack.com/archives/C01GHNWF690/p1619774951012100) that running [`dbt seed`](https://docs.getdbt.com/reference/commands/seed) multiple times results in an error. This issue is to update dbt-materialize's [`seed` macro](https://github.com/MaterializeInc/materialize/blob/main/misc/dbt-materialize/dbt/include/materialize/macros/materializations/seed.sql) to not error when called multiple times.

**Comment by elindsey** [comment]
Related https://github.com/MaterializeInc/materialize/issues/6622
