### ISSUE TITLE
sql: correctly disallow non-immutable functions in views

### ISSUE THREAD

**Issue by mjibson** [MaterializeInc/materialize#6660]
Currently `now`, `current_timestamp`, and `mz_uptime` disallow themselves from being in views. However other functions also should. For example:

```
materialize=> create materialized view v as select mz_internal.mz_session_id();
CREATE VIEW
materialize=> select * from v;
               ?column?               
--------------------------------------
 9a792279-ea34-4afd-8ea6-54b8d046f85d
(1 row)
materialize=> \q
(RESTART MZ)
~/materialize@work (main)$ m
psql (11.11, server 9.5.0)
Type "help" for help.
materialize=> select * from v;
               ?column?               
--------------------------------------
 64d8a7df-2499-4514-a3b6-1879d3d251fe
(1 row)
```

```
materialize=> create materialized view v2 as select current_user();
CREATE VIEW
materialize=> select * from v2;
 current_user 
--------------
 materialize
(1 row)
```

On restart:
```
materialized: corrupt catalog: failed to deserialize item u4 (materialize.public.v2_primary_idx): function current_user() does not exist
```

There are almost certainly others like this. These should be disallowed or cached somehow.

**Comment by benesch** [comment]
Marking this one as P0 as if it's still relevant it's an incident waiting to happen. @chaas @mjibson feel free to talk me down.

The good news: I can't reproduce this! I think it's been fixed! But someone more familiar with the code paths should double check, and make sure they feel good that we solved this properly, and not just ad hoc or accidentally for the two functions Matt posted in the original issue.

**Comment by mjibson** [comment]
These all got converted into (or wrap) `UnmaterializableFunc`s so are handled correctly.
