### ISSUE TITLE
Expose Kafka consumer max fetch size configuration

### ISSUE THREAD

**Issue by elindsey** [MaterializeInc/materialize#6686]
Related to https://github.com/MaterializeInc/materialize/issues/5952

Today Kafka sources are configured with 60s timeouts and ~134mb max fetch sizes. Higher fetch sizes tend to be better (trading off some memory for increased throughput), but this configuration may not work during bootstrap (when there's a lot of data to pull) for slow networks (such as over a WAN to a cloud hosted kafka). 

Exposing this configuration in the CREATE SOURCE WITH options will let us troubleshoot the next time a customer hits it.

**Comment by awang** [comment]
related: should we add a knob for the timeout?

**Comment by nharring-adjacent** [comment]
This parameter is now available.
