### ISSUE TITLE
Debezium upsert source may have time-ordering bugs

### ISSUE THREAD

**Issue by frankmcsherry** [MaterializeInc/materialize#6715]
**Frank McSherry** There is some other stuff in there too, e.g. when it receives (key, row) for a time that has not yet fully passed, it stashes it because it cannot yet know that it won't see some update "between" the old and new value.

**Brennan Vincent**  uh-oh, I don't think DEBEZIUM UPSERT does this part. Probably not breaking anything in practice right now but we should fix it

**Frank McSherry**  Ah, ok. I can file an issue, if this text is sufficient?

**Brennan Vincent**  it's sufficient for me at least to understand the issue. if someone else picks it up we can explain it to them 

---

I think the gist of the issue is that if the DBZ upsert source receives `(key, row)` pairs out of order, say at `time2` replacing something at `time0`, it should wait until `time2` completes, as it may need to 1. make sure that no update arrives at `time1` between the two, and 2. perhaps wait to see if other updates at `time2` but different offsets arrive (concurrent updates, that want to be deterministically tie-broken).

cc: @umanwizard

**Comment by umanwizard** [comment]
Yep, right now we are just respecting the order in which the operator receives things, which seems to match the order of timestamps in practice (at least for RT sources) . But timely in general doesn't guarantee that things will be delivered in timestamp order, so we should fix this for correctness's sake.

**Comment by frankmcsherry** [comment]
@mjibson is this fixed / expected to be fixed by #6712? Afaict my complaint is addressed, but you had a repro that you are more familiar with.
