### ISSUE TITLE
Reduce risk of errant view/query consuming all memory

### ISSUE THREAD

**Issue by cuongdo** [MaterializeInc/materialize#672]
Queries or views that result in cross products tend to cause Materialize to exhaust all available memory. On Linux systems, the OOM killer then kills materialized to prevent the entire system from going down.

For example, one variant of CH-benCHmark query 2 (#523) results in a cross product with our current optimization rules. It's also easy to forget to include a join condition, which results in a cross product.

One idea that came up while chatting with @frankmcsherry is to prevent dataflows from being created except when they're explicitly asked for. @benesch brought up the idea of refusing to execute anything with a cross join unless the query explicitly uses `CROSS JOIN`.

Because we lack durability for metadata (#33), the relative ease of crashing Materialize through memory exhaustion may be a serious annoyance during an evaluation process for Materialize.

**Comment by benesch** [comment]
We "fixed" this sufficiently with clusters in platform. Queries are now isolated to a `clusterd` process, and users can create clusters as they like for increased isolation. Clusters are still prone to OOMing, but we have plans to enable swap for graceful degradation instead (#17566).
