### ISSUE TITLE
doc: Explain Mz restart behavior for new users

### ISSUE THREAD

**Issue by msudberg** [MaterializeInc/materialize#6720]
New users are confused about what happens on Mz restart  and what kind of persistence is (isn't) offered.

- Source - We don't currently offer source persistence; we're planning to, but we don't have a timeline set. So basically retention here depends on what the source does. We will reread from Kafka from the beginning and from Kinesis as far back as the retention policy is configured (up to 1 year). For more info, see: Source volatility.
- Sink - Once exactly once sinks are implemented, we will eliminate duplication and see the behavior users expect.
- Views - will be reread and recreated (but only based on what’s in source) We preserve all the definitions in the catalog file (an sqlite file).

There lot of demand on sources until they're reread; we may want to officially recommend a delay or offset to avoid overloading systems on restart.  

SMEs: @ruchirK, @krishmanoh2

**Comment by benesch** [comment]
Fixed with platform.
