### ISSUE TITLE
update ExternalState tracking when unmaterialized Postgres sources are allowed

### ISSUE THREAD

**Issue by JLDLaughlin** [MaterializeInc/materialize#6723]
A week ago there was a [design doc and discussion](https://github.com/MaterializeInc/materialize/pull/6655) about how we should manage external state in Materialize. We decided that external state should be captured by a new enum that is stored in the Catalog and managed by the `coord` crate. [This PR](https://github.com/MaterializeInc/materialize/pull/6714) introduces the new `ExternalState` enum that is implemented just for Postgres sources.

However, the first iteration of `ExternalState` does not have any knowledge about per-source instance external state. This is okay in the short-term because we are only allowing users to create materialized Postgres sources. Because the sources are materialized, any views depending on a Postgres source will not need to spin up their own source instance. Instead, views can simply import the already materialized source. But, in the future when we allow unmaterialized Postgres sources (for performance reasons), the current implementation of `ExternalState` will no longer be sufficient. More concretely, for unmaterialized Postgres sources, we will need to track the upstream replication slot name for each source instance.

Note: we would not have to fiddle with this if we implemented [dynamic resource sharing](https://github.com/MaterializeInc/materialize/pull/6450) first!

**Comment by benesch** [comment]
Closing as stale, as #6714 never landed.
