### ISSUE TITLE
doc: Source + JSON info not consistent across sources or linked to jsonb type doc

### ISSUE THREAD

**Issue by msudberg** [MaterializeInc/materialize#6736]
The [jsonb type documentation](https://materialize.com/docs/sql/types/jsonb/) contains a lot of information you need to make best use of sources with JSON, but it's not linked from anywhere in the JSON source doc.

Request from @ruf-io.

**Comment by morsapaes** [comment]
I had a note about pointing to the [Postgres docs for JSON Functions & Operators](https://www.postgresql.org/docs/current/functions-json.html) and add an example, but if that page exists we should definitely link it!

**Comment by morsapaes** [comment]
Linked in the [JSON format section](https://materialize.com/docs/sql/create-source/#json) of `CREATE SOURCE`.
