### ISSUE TITLE
pg-cdc: tables added to the publication do not sync properly to an existing source

### ISSUE THREAD

**Issue by petrosagg** [MaterializeInc/materialize#6742]
The postgres source enumerates all the tables present in the specified publication once at startup and then switches to reading the replication stream. If a table is later added in the upstream database in the publication the source does not read its initial data leading to wrong results.

In order to handle this case the source would need to start a temporary replication slot, read the table and then read the slot forward until it catches up with the main one.

**Comment by benesch** [comment]
Fixed by https://github.com/MaterializeInc/materialize/pull/20277.
