### ISSUE TITLE
[Tracking] sql: refactor decimal type

### ISSUE THREAD

**Issue by sploiselle** [MaterializeInc/materialize#6761]
Our current implementation of decimals has a number of deficiencies, most
notable of which are miscalculations when doing multiplication and division. To
resolve this issue, we're doing to change the type's internal representation
from an `i128` with the scale tracked in an enum to instead use
[`rust-dec`](https://github.com/MaterializeInc/rust-dec/), a FFI over [`decNumber`](http://speleotrove.com/decimal/).

This issue tracks the remaining work to reach feature parity with decimals, as
well as provide links to other related docs.

### Background + Benchmarking

[Google docs](https://docs.google.com/document/d/1fCEz4MQn9SDIJFN-Punh-qXNRCkB4uNdfbVlcbgFHq0/edit#)

### Integration features

Feature | Done locally? | In PR
--------|----------------|-------
Set scale | y | #6784
Avro decode | y | 
Avro encode[<sup>1</sup>](#avro-encoding) | |
`To/FromSql`[<sup>2</sup>](#to-fromsql) | [in progress](https://github.com/sploiselle/materialize/tree/apd-to-fromsql) |
[Fix function selection](https://github.com/MaterializeInc/materialize/issues/7030) | | 

#### Avro encoding<a id="avro-encoding"></a>

`libdecnum` doesn't need to force values to have a specific scale, which means
it's unclear how to handle propagating schema information about unscaled decimal
columns into e.g. sinks. Debezium has an on-the-fly encoding from PostgreSQL,
wherein each value includes its scale in its payload, so I can only assume this
is possible, but I haven't yet dug around to find out the where and how within
Materialize.

#### `To/FromSql`<a id="to-fromsql"></a>

There's an impedance mismatch between `libdecnum` offering to provide "units" in
base 1,000 and the `To/FromSql`'s trait need for units in [base 10,000](https://github.com/diesel-rs/diesel/blob/bd13f2460/diesel/src/pg/types/numeric.rs#L23-L25). The
natural solution of using an `i128` as an intermediary value sadly doesn't seem
like it's totally viable because we offer a full 39 digits of precision, making
it not viable for any values whose coefficient exceeds `i128::MAX`.

Maybe the simplest thing is to just take the decimal number's units to base
1,000,000,000,000 (i.e 4 decimal units), and then slice those into 3 PG units?

Testing this will be much easier once we can rename `apd` to `decimal`, so am going to hold off on submitting this code until that is also done.

### Built-in functions

Function | In lib? | Done locally? | In PR
---------|---------|---------------|-------
`add_apd` | y | y | #6784
`sub_apd` | y | y | #6784
`mul_apd` | y | y | #6784
`div_apd` | y | y | #6784
`cast_apd_to_string` | y | y | #6784
`cast_string_to_apd` | y | y | #6784
`rescale_apd` | y | y | #6784
`sum_apd` | y | y | #6872
equality operators |[y](https://github.com/MaterializeInc/rust-dec/blob/master/dec/src/ordered.rs#L173-L195) | y | #6873 
`mod_apd` | [almost](https://github.com/MaterializeInc/rust-dec/blob/master/dec/src/decimal.rs#L1243-L1253) | y | #7013 
`neg_apd` | [y](https://github.com/MaterializeInc/rust-dec/blob/master/dec/src/decimal.rs#L620-L632) | y | #6882 
`abs_apd` | [y](https://github.com/MaterializeInc/rust-dec/blob/master/dec/src/decimal.rs#L760-L769) | [y](https://github.com/sploiselle/materialize/tree/apd-abs) | #7015 
`cast_int32_to_apd` | [y](https://github.com/MaterializeInc/rust-dec/blob/master/dec/src/decimal.rs#L382-L390) | [y](https://github.com/sploiselle/materialize/tree/apd-casts-int) | #7006
`cast_int64_to_apd` | [y](https://github.com/MaterializeInc/rust-dec/blob/master/dec/src/decimal.rs#L535-L542) |  [y](https://github.com/sploiselle/materialize/tree/apd-casts-int) | #7006
`cast_float32_to_apd` | n[<sup>3</sup>](#to-from-float) | | #7006
`cast_float64_to_apd` | n[<sup>3</sup>](#to-from-float) | | #7006
`cast_apd_to_float32` | n[<sup>3</sup>](#to-from-float) | | #7006
`cast_apd_to_float64` | n[<sup>3</sup>](#to-from-float) | | #7006
`cast_apd_to_int32` | [y](https://github.com/MaterializeInc/rust-dec/blob/master/dec/src/decimal.rs#L445-L453) | | #7006
`cast_apd_to_int64` | [y](https://github.com/MaterializeInc/rust-dec/blob/master/dec/src/decimal.rs#L445-L453) | | #7006
`cast_jsonb_to_apd` | y | [y](https://github.com/sploiselle/materialize/tree/apd-jsonb), but waiting on #7006 to land  |  #7027
`ceil_apd` | [y](https://github.com/MaterializeInc/rust-dec/blob/master/decnumber-sys/src/lib.rs#L338-L342) | [y](https://github.com/sploiselle/materialize/tree/rounding-functions), but need to bump `rust-dec` version | #6998 
`floor_apd` | [y](https://github.com/MaterializeInc/rust-dec/blob/master/decnumber-sys/src/lib.rs#L338-L342) | #6998 [y](https://github.com/sploiselle/materialize/tree/rounding-functions), but need to bump `rust-dec` version | #6998 
`round_apd_unary` | [y](https://github.com/MaterializeInc/rust-dec/blob/master/decnumber-sys/src/lib.rs#L338-L342) | [y](https://github.com/sploiselle/materialize/tree/rounding-functions), but need to bump `rust-dec` version | #6998 
`round_apd_binary` | [y](https://github.com/MaterializeInc/rust-dec/blob/master/decnumber-sys/src/lib.rs#L338-L342) | [y](https://github.com/sploiselle/materialize/tree/rounding-functions), but need to bump `rust-dec` version | #6998 
`exp_apd` | [y](https://github.com/MaterializeInc/rust-dec/blob/master/dec/src/decimal.rs#L820-L825) | [y](https://github.com/sploiselle/materialize/tree/apd-exp), waiting on `munge_apd` merge | #6962 
`ln_apd` | [y](https://github.com/MaterializeInc/rust-dec/blob/master/dec/src/decimal.rs#L1014-L1019) | [y](https://github.com/sploiselle/materialize/tree/apd-exp), waiting on `munge_apd` merge | #6962 
`log10_apd` | [y](https://github.com/MaterializeInc/rust-dec/blob/master/dec/src/decimal.rs#L1021-L1026) | [y](https://github.com/sploiselle/materialize/tree/apd-exp), waiting on `munge_apd` merge | #6962 
`log_apd` | [y](https://github.com/MaterializeInc/rust-dec/blob/master/dec/src/decimal.rs#L1028-L1034) | [y](https://github.com/sploiselle/materialize/tree/apd-exp), waiting on `munge_apd` merge | #6962 
`power_apd` | [y](https://github.com/MaterializeInc/rust-dec/blob/master/dec/src/decimal.rs#L1204-L1209) | [y](https://github.com/sploiselle/materialize/tree/apd-exp), waiting on `munge_apd` merge | #6962 
`sqrt_apd` | [y](https://github.com/MaterializeInc/rust-dec/blob/master/dec/src/decimal.rs#L1323-L1328) | [y](https://github.com/sploiselle/materialize/tree/apd-exp), waiting on `munge_apd` merge | #6962 
`max_apd` | y | | #6989
`min_apd` | y | | #6989
`mz_avg_promotion` | n/a | [y](https://github.com/sploiselle/materialize/tree/apd-mz-avg-promotion), but waiting on #7006 to land  | #7026

### To, From Floats <a id="to-from-float">

In the worst case we could go to a version of the coefficient and then do
division. Unclear what to do in cases with a coefficient that's "too large" to
produce as an e.g. `i128`.

**Comment by sploiselle** [comment]
### Acceptable input precision

Another area that needs fleshing out is our semantics for accepting input that exceeds our max precision (e.g. `1e40` or `1.234567890123456789012345678901234567890`). It struck me that we will be forced to generate inexact results in e.g. division, which produce irrational numbers, so we must accept rounding/inexactitude in some cases, but where and why?

- Division and multiplication would be severely limited in their usefulness if we forced results to be exact, e.g. you couldn't multiply two numbers with greater than 20 digits of precision, and you couldn't do division that generated irrational numbers.
- Addition and subtraction must also accept rounding in the case of e.g. `1e38 + 1e-39`, which we should probably round to `1e38`.
- Sum must remain totally invertible, though, which means we can never accept rounding in an intermediate result of `sum`; we can work around this by using a "double-wide" decimal with >78 digits of precision for aggregations. We've already prototyped this and seen it working, so 👌 there. e.g. in the case of `1e38 + 1e-39`, we will retain the exact result in the double-wide, but return the value to clients as `1e38`. This way if we ever receive a subtraction for `1e-39` in the future, we can safely apply it.

Given that we do accept rounding in some cases, can we safely round input? No because the input could get rounded en route to a `sum` operator, causing us to lose invertibility. It would be possible to round inputs' precision down iff there are trailing zeroes, though, e.g. trimming `1.234567890123456789012345678901234567890` to `1.23456789012345678901234567890123456789`. That seems like a corner case, though, and potentially creates situations that defy customers' intuition around the type's behavior; it's much easier to simply tell users that their inputs cannot exceed 39 digits of precision.

This is also similar to our current implementation that simply couldn't store values that exceeded its precision and rounding wasn't an option. Users' complaints around the type wasn't in its narrowness or inability to trim zeroes from the end of input, so I think this also validates strictly enforcing 39 digits of precision.

**Comment by sploiselle** [comment]
Bringing a conversation from [the benchmarking doc](https://docs.google.com/document/d/1fCEz4MQn9SDIJFN-Punh-qXNRCkB4uNdfbVlcbgFHq0/edit#heading=h.bf32mspqdcs6) into GH for more breathing room.

@frankmcsherry says re: a suggestion to change the "shape" of the benchmarking input and aggregations

> The aggregations one is similar: I think we thought there might be a big multiplier there due to the additional counts tracking inf, -inf, NaN, etc., and trying out a group-by with 10, 100, 1000 sums of decimal columns could show that off. That experiment would probably be cleanest without an upsert / indexed source, just feeding the `reduce` directly (so that it is the main source of memory).

Is this the general shape you're suggesting? Assuming we have records containing a key and 10 decimal values...

```
CREATE SOURCE source_aggregationtest
FROM KAFKA BROKER 'kafka:9092'
TOPIC 'aggregationtest'
FORMAT AVRO USING CONFLUENT SCHEMA REGISTRY 'http://schema-registry:8081'
ENVELOPE NONE;

CREATE VIEW aggregationtest AS SELECT
    sum(("OuterRecord")."DecValue0") AS dec0_sum,
    sum(("OuterRecord")."DecValue1") AS dec1_sum,
    sum(("OuterRecord")."DecValue2") AS dec2_sum,
    sum(("OuterRecord")."DecValue3") AS dec3_sum,
    sum(("OuterRecord")."DecValue4") AS dec4_sum,
    sum(("OuterRecord")."DecValue5") AS dec5_sum,
    sum(("OuterRecord")."DecValue6") AS dec6_sum,
    sum(("OuterRecord")."DecValue7") AS dec7_sum,
    sum(("OuterRecord")."DecValue8") AS dec8_sum,
    sum(("OuterRecord")."DecValue9") AS dec9_sum
FROM source_aggregationtest
GROUP BY ("Key1");
```

where `Key1` lets use control how many group we're `GROUP BY`ing.

**Comment by frankmcsherry** [comment]
Yes, that looks good. As the number of summed decimals increase, we get a better sense for the overhead of their accumulation in `reduce` code. Or, a sense for when it starts to become the upper bound that we expect (e.g. "only with 100 aggregates" or something like that).

**Comment by sploiselle** [comment]
Here are some notes about the expected semantics of rounding decimal values.

# Rounding semantics

Our proposed implementation of `decNumber`-backed numeric values provides 39
digits of precision (DOP). What happens to values that exceed those 39 digits?

If the value has > 39 DOP...

**+ >= 1e39**: This is simply an overflow, which we will enforce using the decimal
library's context type, and then checking for its overflow status.

**+ < 1e-39**: This is simply an underflow, " " " check for subnormal status.
Note that we could theoretically round something like 5e-40 to 1e-39 and retain
our semantics but ¯\_(ツ)_/¯.

**+ absolute values [1e-39, 1e39)**: Round to most significant digit possible
with 39 DOP, even if this means rounding to the nearest integer and truncating
all decimal values.

Implicit in this behavior is that significant digits < 1 are disposable by
rounding, but digits >= 1 are not.

## Preventing rounding

For some applications, these semantics might not be desirable, e.g. I can
imagine tracking some form of currency that supports fractional units with some
specified scale, and rounding those fractional units away is undesirable.

To offer a lever to prevent rounding, I suggest that specifying the APD type's
scale should force a coercion of all values to a representation that has some
exact number of fractional digits. In essence this provides a fixed scale of
values, whereas without a specified scale, the scale can be reduced from 39 to
0.

## Binary vs. aggregate operators

Performing aggregation over APD values requires states to be invertible when
values are retracted, e.g. if you overflow 39 digits of precision, you should be
able to return the aggregation to a non-overflown state by retracting some
values.

So, this means we simply cannot support rounding on sum operations because this
would cause us to lose some data in the values we've seen, preventing us from
accurately retracting values.

The proposed solution to this is aggregating into a "double wide" decimal
supporting >= 39 * 2 (78) DOP. This lets us accept values of min, max, and
closest to zero, without needing to round in the aggregator.

When we want to go from an aggregator to a datum, we can simply take the
39 most significant digits from the aggregator and return that as a datum.

This poses a kind of funny ergonomic issue, where rounding is visible to the
user, but the aggregated value's true value is obfuscated, i.e. you cannot see
any digits outside the 39 DOP of the single-wide. This means if you see that an
aggregator has a value of `123456789012345678901234567890123456789` and then
subtract it from the aggregate, the result could be
`.000000000000000000000000000000000000001`. Or conversely subtracting
`.000000000000000000000000000000000000001` from
`123456789012345678901234567890123456789` might be
`123456789012345678901234567890123456789` or
`123456789012345678901234567890123456788`.

This weirdness is simply this approach's inherent vice.

### Alternatives?

The most intuitive alternative would be aggregating into single-wide values.
Because we cannot support rounding in aggregation contexts, as mentioned above,
this would severely hamper the type's usability, as well as provide radically
different semantics for sum than for binary addition. For example, you would
have to scale the value to have the maximum scale of any value you had ever
seen, which quickly eats into the digits left of the decimal you could retain
before being forced to throw numeric field overflows.

### Mitigation?

It might be possible to expose the full aggregate value to users as output, but
e.g. not as input, to more accurately reflect their aggregations' states.

### Overflowing datums in aggregates

If the aggregate contains a digit > 1e38, we can return infinity as a signal
that the aggregate has exceeded a value representable by the datum. At this
point, users will need to learn to begin retracting values or risk overflowing
the aggregator.

### Overflowing aggregators

If you have a value whose addition to an aggregate causes the value to exceed
its maximum DOP (i.e. reaching values with a precision greater than 78 digits),
we will panic. To reach this state requires somewhat pathological input (`1e39`,
i.e. 10 * the maximum value we accept as input, + `1e-39`, smallest absolute
value we accept).

To make this even less likely, we can also pad the aggregator with an extra 3
digits of precision, meaning you must see a value with 81 digits of precision
before erroring.

### Rounding input + aggregates

Rounding inputs is deterministic, which means that we can retract values, even
if they're rounded.

**Comment by sploiselle** [comment]
Avro schemas require a [fixed precision and scale for decimals](http://avro.apache.org/docs/current/spec.html#Decimal); this wasn't an issue for decimals previously because the scale was intrinsic to the type's declaration, e.g. the scale defaulted to 0. However, the new implementation supports dynamically scaled values.

To work around this, I'm encoding values with an indeterminate scale as values with twice the precision and a scale of the max precision, i.e. akin to `decimal(78,39)`. This makes sure every possible valid 39-digit number can be represented in full fidelity. And, nicely, we already supported this type for use aggregations.

**Comment by sploiselle** [comment]
This [branch on my fork](https://github.com/sploiselle/materialize/tree/dec-apd-migration) now passes all sqllogictests 🎉

**Comment by sploiselle** [comment]
#7361 raises an interesting question: how should we handle encoding `Infinity` for PG clients? Our approach to aggregating numeric/apd values hinges on using `Infinity` to signal that the accumulator has a value too large to represent in a `Datum::Numeric`. However the PG numeric type doesn't support the notion of infinity, so we don't have a means of encoding this value.

The approach that seems the most sane is to simply send `+/-1E39` back to the client when we encounter an infinite value, which is 1 greater/less than the maximum value representable with our implementation. Clients will need to learn about this special value, but that is also true of `Infinity`. Returning a value this large also prevents users from plumbing this value back into Materialize because it exceeds the type's bounds; this is similar to the case with `Infinity`, which isn't valid input for the `numeric` type.

@mjibson @benesch Do either of you have thoughts? Glad to go into more detail if this isn't sufficient.

**Comment by mjibson** [comment]
I have a strong opinion here because I did this in cockroach: https://github.com/cockroachdb/cockroach/blob/a31df56204bb2ee0779137c4b73f2a5dd90d7251/pkg/sql/pgwire/types.go#L400 and have regretted it ever since. My position is: we should NOT allow datums to exist that are unencodable in postgres binary encoding.

You (and I previously) have just spent a ton of time fixing some deep fundamental issues to make a type behave like postgres. I encourage making that complete and disallowing the existence of unencodable datums. I think the solution to this problem is to remove numeric infinity wholesale, which means encoding doesn't have to care about it at all.

Another question I had is: I would have assumed the rust stuff would have raised this problem at compile time instead of runtime. Why was that the case?

**Comment by mjibson** [comment]
Also 100% comfortable doing this work in follow up and using the NaN encoding solution for now.

**Comment by mjibson** [comment]
Oh there's also a postgres diff somewhere where they consider adding numeric infinity so we could use the binary encoding proposed there? That's also a fine solution, and probably much easier than removing infinity wholesale.

**Comment by mjibson** [comment]
OHHH they added numeric infinity! https://github.com/postgres/postgres/blob/a9da1934e971b38ab360ce80a352fbfc4d2d986b/src/backend/utils/adt/numeric.c#L189 has all the details for this!

**Comment by sploiselle** [comment]
@mjibson tysm for dredging that up; really ideal, and will see how it shakes out. Otherwise using `NaN` seems realistic and a better solution overall.
