### ISSUE TITLE
sql: support role based access control

### ISSUE THREAD

**Issue by rjnn** [MaterializeInc/materialize#677]
this issue is filed for 'later', as it is not pressing, but this has come up in a few customer-facing conversations as enterprise requirements, and i wanted to write down my thoughts.

we need some notion of users, and metadata around those users in terms of fine-grained CREATE/DELETE/SELECT permissions, as well as having the ability to give selective read permissions tied to individual views. (This is doubly true if we're using the notion of 'databases'/'timespaces' to indicate shared notions of temporal advancement, which means that it gets somewhat decoupled with some traditional access controls that tie read permissions to databases).

**Comment by morsapaes** [comment]
This work is being tracked in #11579.
