### ISSUE TITLE
Support time travel queries using AS OF SYSTEM TIME syntax

### ISSUE THREAD

**Issue by frankmcsherry** [MaterializeInc/materialize#678]
Differential dataflow's arrangements are able to correctly maintain historical data behind "now", which is great because several visualization idioms want that sort of information. We don't currently have a way to present it.

cc @quodlibetor 

Many visualizations present measurements over time, because that leads to feelings of insight. A common view might be the maximum peek latency second-by-second over the past minute. 

Our interface to materialized is through point-in-time queries, but we maintain access to historical data out to the compaction window (by default, one minute, I believe). This means that we should be able to serve up historical information, without needing something like Prometheus to buffer up measurements for us. We might be delighted with Prometheus, but we might also want to provide this functionality ourselves.

One feature we would gain by doing this ourselves is *backfill*: if a new query is posed, something like Prometheus will only start collecting *new* data. However, differential has the ability to produce the history of the measurement from as far back as the compaction threshold. That could help to populate initially empty charts for new queries.

**Comment by benesch** [comment]
We've supported `AS OF` for quite a while!
