### ISSUE TITLE
[dataflow] Streamline loading of update streams in delta joins

### ISSUE THREAD

**Issue by frankmcsherry** [MaterializeInc/materialize#6789]
Our delta join implementation builds a dataflow path for each join input, each of which are then joined with various other relations. To avoid double counting, updates at the same `time` only "match" when fed by a relation with smaller index. This means that on start-up, massive volumes of data are introduced into each dataflow path at time `dataflow.as_of`, and all but the path for the first input are effectively discarded (they ultimately match no updates in the first relation, and get dropped). This is a substantial use of resources, CPU, memory, for something that has no effect.

The seeding of each of these dataflow paths happens at a very local moment, and we could certainly put in a filter there that suppresses updates that are both at `dataflow.as_of` and not from the first input. 
```rust
updates
    .inner
    .filter(move |(_, time, _)| source_relation == 0 || !as_of.elements().contains(&time))
    .as_collection()
```
This is still more expensive than we might like, as we still allocate the rows. Instead, we could move closer to the traces and avoid cloning the `Row`s in the first place:
```rust
trace
    .stream
    .unary(Pipeline, "AsCollection", move |_,_| move |input, output| {
        input.for_each(|time, data| {
            let mut session = output.session(&time);
            for wrapper in data.iter() {
                let batch = &wrapper;
                let mut cursor = batch.cursor();
                while let Some(_key) = cursor.get_key(batch) {
                    while let Some(val) = cursor.get_val(batch) {
                        cursor.map_times(batch, |time, diff| {
                            if source_relation == 0 || !as_of.elements().contains(&time.time) {
                                session.give((val.clone(), time.clone(), diff.clone()));
                            }
                        });
                        cursor.step_val(batch);
                    }
                    cursor.step_key(batch);
                }
            }
        });
    })
    .as_collection()
```
I *think* the above work, and they do give a substantial performance boost. For "point lookup" joins where the first relation is tiny compared to the others, it resulted in ~100x reduction in query time. For chonkier joins it was about a 2x reduction in time. It also substantially reduces the peak memory utilization.

The experiments above were all pretty ad-hoc, and want a more careful implementation. We should also wait for https://github.com/MaterializeInc/materialize/pull/6744 to land, as it changes the delta join implementation (in an orthogonal way, but no one wants conflicts in that code).

This would also be a good time to fuse `initial_closure` into this logic, which would allow a closure to be applied to the initial rows before they are cloned.

**Comment by asenac** [comment]
@frankmcsherry @philip-stoev any comments on testing for this? I was thinking in a sqllogic test querying the system tables checking for the message count.

**Comment by frankmcsherry** [comment]
It would be neat to be able to do that sort of test. Ultimately, this is a performance fix, and most of our infra isn't set up for testing that. 

You should be able to put together a query that will complete quickly with the fix and very slowly without (e.g. join 1 x 1M x 1M records). It could be that even loading the data is very slow though, so perhaps better bundled up as part of a collection of performance optimizations. I think this sort of test is ultimately pretty fragile, though.

I'd personally make sure we test correctness, and then verify and report on the improved performance. But that's just me.

**Comment by philip-stoev** [comment]
@asenac yes unfortinately at this time I can not offer anything performance-testing-wise except the counters exposed in the mz_* tables.

**Comment by asenac** [comment]
This difference in the behaviour after applying the patch/code above doesn't look right to me:

main:

```
materialize=> create table t1(f1 int, f2 int);
CREATE TABLE
materialize=> create index i1 on t1(f1);
CREATE INDEX
materialize=> create table t2(f1 int, f2 int);
CREATE TABLE
materialize=> create index i2 on t2(f1);
CREATE INDEX
materialize=> insert into t1 values (1, 2); insert into t2 select s, s from generate_series(0, 2000) as s;
INSERT 0 1
INSERT 0 2001
materialize=> create materialized view delta as select * from t1, t2 where t1.f1 = t2.f1;
CREATE VIEW
materialize=> select * from delta;
 f1 | f2 | f1 | f2 
----+----+----+----
  1 |  2 |  1 |  1
(1 row)

materialize=>
```

the code above:

```
materialize=> create table t1(f1 int, f2 int);
CREATE TABLE
materialize=> create index i1 on t1(f1);
CREATE INDEX
materialize=> create table t2(f1 int, f2 int);
CREATE TABLE
materialize=> create index i2 on t2(f1);
CREATE INDEX
materialize=> insert into t1 values (1, 2); insert into t2 select s, s from generate_series(0, 2000) as s;
INSERT 0 1
INSERT 0 2001
materialize=> create materialized view delta as select * from t1, t2 where t1.f1 = t2.f1;
CREATE VIEW
materialize=> select * from delta;
 f1 | f2 | f1 | f2 
----+----+----+----
(0 rows)

materialize=> select * from delta;
 f1 | f2 | f1 | f2 
----+----+----+----
(0 rows)

materialize=> select * from delta;
 f1 | f2 | f1 | f2 
----+----+----+----
(0 rows)

materialize=> select * from delta;
 f1 | f2 | f1 | f2 
----+----+----+----
(0 rows)

... // wait a few seconds

materialize=> create materialized view delta2 as select * from t1, t2 where t1.f1 = t2.f1;
CREATE VIEW
materialize=> select * from delta2;
 f1 | f2 | f1 | f2 
----+----+----+----
  1 |  2 |  1 |  1
(1 row)

materialize=> select * from delta;
 f1 | f2 | f1 | f2 
----+----+----+----
(0 rows)

materialize=> 
```

ie. if the materialized view is created soon after injecting the data, the expected matching record is missing from the output forever. If a second view with the same exact definition is created some time later, the record is present.

**Comment by frankmcsherry** [comment]
I agree this doesn't look good/right.

I think there are some intended invariants that we can check by looking at the data that should down each path. If you shrink the 2k side a bit, it should become clear whether the implementation has a big or the math does.

In meetings today, but happy to help async.

**Comment by asenac** [comment]
I guess one further improvement could be to fuse the logic in the MapFallible operator at the input of the HalfJoin operator inside the new UpdateStream operator (temporary name), ie. fusing 936 into 929 in the following graph:

![image](https://user-images.githubusercontent.com/1282736/119467392-c591ec80-bd45-11eb-83d8-2da8f2898d31.png)

Would that save us much?
