### ISSUE TITLE
BYO consistency: timestamper thread exits on Kafka timeout: source stalls

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#6792]
### What version of Materialize are you using?

```
materialized v0.7.4-dev (114b17ca0)
```

### What was the issue?

This was discovered by Antithesis. I have not been able to reproduce it outside of their platform, but hopefully the log lines tell the story.

What has happened is that a network failure was injected between Kafka and Materialize. Materialize reported the following:

```
[  196224] [   424.409907] [service_materialized]   [I] 2018-01-28T16:04:58.078152Z ERROR coord::timestamp: Failed to correctly parse messages from source u100; Failed to process message Message consumption error: OperationTimedOut (Local: Timed out)    
[  196241] [   424.410605] [service_materialized]   [I] 2018-01-28T16:04:58.079493Z  INFO coord::timestamp: Dropping Timestamping for Source u100. 
```

This causes the source to permanently fail to advance:

```
[  201235] [   729.019840] [fault_injector]         [I] [638.346544s] Generator Event - fuzzer sync: updated seed: in 47 + val 1487114100 = new 1487114075
[  201235] [   729.398693] [service_atp-testdrive]  [I] rows didn't match; sleeping to see if dataflow catches up 50ms 75ms 112ms 169ms 253ms 380ms 570ms 854ms 1s 2s 3s 4s 6s 10s 15s 22s 33s 49s 74s 78s
[  201235] [   729.572985] [service_atp-testdrive]  [I] avro-sinks.td:164:1: error: executing query failed: db error: ERROR: At least one input has no complete timestamps yet: [User(101)]
[  201235] [   729.573200] [service_atp-testdrive]  [I]      |
[  201235] [   729.573200] [service_atp-testdrive]  [I]  163 | 
[  201235] [   729.573200] [service_atp-testdrive]  [I]  164 | > SELECT * FROM input;
[  201235] [   729.573386] [service_atp-testdrive]  [I]      | ^
``` 

I think we are lucky in this case that the source never began producing so it kept returning the "At least one input has no complete timestamps yet: [User(101)]" error . However, I can also envision a scenario where the source has produced some data, then the timestamp has errored out, resulting in the source stalling permanently. I would say the latter scenario would be a liveness error of sorts, so I am tagging this with the consistency tag.

This issue is in the same mold as #6554, but the solutions would be different - in #6554, the source should fail right away whereas in here the solution would be to either retry more aggressively or fail the source with an appropriate error message.

### Is the issue reproducible? If so, please provide reproduction instructions.

Unfortunately only in Antithesis. Messing with kafka locally did not produce the desired string of events.

### Please attach any applicable log files.

The full log from all the participating containers is available. (internal name ```avro-sinks.td_164_1_ error_ executing query failed_ db error_ ERROR_ At least one input has no complete timestamps yet_ [User(101)].log```)

**Comment by cirego** [comment]
Hi @philip-stoev, thanks for the great writeup! I recently changed this behavior with #6616. As part of the discussion on that PR, we agreed to defer notifying the source on this type of error because we're planning to rework (remove?) the timestamper thread / source reader interface.

@ruchirK, I fear that I'm not remembering all of our conversation. Would you mind correcting any of my misunderstandings?

**Comment by ruchirK** [comment]
that all sounds right to me

**Comment by elindsey** [comment]
BYO is gone
