### ISSUE TITLE
pg-cdc: TRUNCATE on one table fails the entire source; error message does not say which table is to blame 

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#6812]
### What version of Materialize are you using?

```
v0.7.4-dev (82ae64f89)
```

### What was the issue?

```TRUNCATE``` on a single table in a publication causes the entire Pg source to error out, rather than just the view for this particular table. Furthermore, the error message on any ```SELECT``` against views derived from the source is like this:

```
Source error: File IO: source table got truncated
```
which implies that the table being SELECT-ed was the one that got truncated. In fact, it may have been some other table from the same publication.

Ideally errors such as ```table got truncated``` should only be inserted in the error stream of the view created based on the table, rather than erroring the entire source. If this is not technically feasible, then at least the error message should specify which Postgres table got truncated.

Separately from the error message, we need to document that TRUNCATE on any table in the publication affects the entire source, as it is not intuitive. Hence the docs-impact tag.

### Is the issue reproducible? If so, please provide reproduction instructions.

I will be pushing this test:

```
# Copyright Materialize, Inc. All rights reserved.
#
# Use of this software is governed by the Business Source License
# included in the LICENSE file at the root of this repository.
#
# As of the Change Date specified in that file, in accordance with
# the Business Source License, use of this software will be governed
# by the Apache License, Version 2.0.

#
# Test TRUNCATE
#

$ postgres-execute connection=postgres://postgres:postgres@postgres
ALTER USER postgres WITH replication;
DROP SCHEMA IF EXISTS public CASCADE;
CREATE SCHEMA public;

CREATE TABLE t1 (f1 INTEGER);
ALTER TABLE t1 REPLICA IDENTITY FULL;
INSERT INTO t1 VALUES (1);

CREATE PUBLICATION mz_source FOR ALL TABLES;

> CREATE MATERIALIZED SOURCE mz_source
  FROM POSTGRES HOST 'host=postgres port=5432 user=postgres password=postgres sslmode=require dbname=postgres'
  PUBLICATION 'mz_source';

> CREATE VIEWS FROM SOURCE mz_source;

> SELECT * FROM t1;
1

$ postgres-execute connection=postgres://postgres:postgres@postgres
TRUNCATE TABLE t1;

! SELECT * FROM t1;
source table got truncated
```

**Comment by petrosagg** [comment]
With the current architecture it's not possible to fine tune where the error goes but definitely agree we need to improve the error message and mention it in the docs.

**Comment by nharring-adjacent** [comment]
As of #10721 the error now indicates which table or tables Materialize received a truncate for.
