### ISSUE TITLE
pg-cdc: arrays, possibly other (complex) types not supported due to missing CAST implementations on the Mz side

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#6813]
### What version of Materialize are you using?

```
v0.7.4-dev (82ae64f89)
```

### What was the issue?

pg-cdc receives incoming data as text strings and relies on ```CAST``` to convert it to the appropriate type inside Materialize.

If the particular cast from string to the desired type is not available, the data can not be decoded and ```CREATE VIEWS``` fails.

### Is the issue reproducible? If so, please provide reproduction instructions.

On the postges side:

```
postgres=# create table t2 (f1 integer[]);
postgres=# insert into t2 values ('{1,2,3}');
```

On the mz side:

```
materialize=> create views from source mz_source1;
ERROR:  CAST does not support casting from text to integer[]
```
This is because the source has this data:

```
materialize=> select * from mz_source1;
  oid  |  row_data   
-------+-------------
 16390 | {"{1,2,3}"}
```

and ```"{1,2,3}"``` can not be cast to ```integer[]```:

```
materialize=> select '{1,2,3}'::integer[];
ERROR:  string literal does not support casting from text to integer[]
```

**Comment by sploiselle** [comment]
@philip-stoev Is this good to close now?

```sql
materialize=> select '{1,2,3}'::integer[];
  _int4  
---------
 {1,2,3}
(1 row)
```

**Comment by benesch** [comment]
Seems good to me.
