### ISSUE TITLE
pg-cdc: If CREATE SOURCE, CREATE VIEWS errors out, the name of the offending table is not provided.

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#6814]
### What version of Materialize are you using?

```
materialized v0.7.4-dev (82ae64f89)
```

### What was the issue?

```CREATE VIEWS``` may be used to create hundreds of even thousands of views, yet if the creation of any individual view fails, there is no indication as to which source table/view was the problematic one (except for error messages that already happen to contain the name of the problematic database object) .

### Is the issue reproducible? If so, please provide reproduction instructions.

For example:

```
materialize=> create views from source "mz_source1" ;
ERROR:  CAST does not support casting from text to integer[]
```

**Comment by philip-stoev** [comment]
Same applies to ```CREATE SOURCE```

**Comment by aljoscha** [comment]
@philip-stoev Do you still know how you originally provoked this into failing?

**Comment by benesch** [comment]
Closing as stale. `CREATE VIEWS` is no longer a thing.
