### ISSUE TITLE
pg-cdc: Arbitrary-precision NUMERIC not supported: "ERROR: precision for type numeric must be within [1-38], have 65535"

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#6821]
### What version of Materialize are you using?

```
v0.7.4-dev (5e4089e4d)
```

### What was the issue?

@petrosagg apoliges for not catching this during the previous PRs . Turns out that Postgres has arbitrary-precision NUMERIC value that causes ```CREATE VIEWS``` to fail.

I think an acceptable fix would be to convert arbitrary-precision ```NUMERIC``` to a ```DECIMAL(M,N)``` where M and N are chosen to be workable for a wider range of workloads -- e.g. N = 6 and M = max supported under the new decimal implementation. However, in this case, the data ingestion should fail if a value arrives where M > max (easy, this should be handled by the CAST), but also when N > 6 (which I think will be more tricky).

### Is the issue reproducible? If so, please provide reproduction instructions.
I will be pushing the following test:

```
# Copyright Materialize, Inc. All rights reserved.
#
# Use of this software is governed by the Business Source License
# included in the LICENSE file at the root of this repository.
#
# As of the Change Date specified in that file, in accordance with
# the Business Source License, use of this software will be governed
# by the Apache License, Version 2.0.

#
# Test arbitrary-precision NUMERIC
#


# Insert data pre-snapshot
$ postgres-execute connection=postgres://postgres:postgres@postgres
ALTER USER postgres WITH replication;
DROP SCHEMA IF EXISTS public CASCADE;
CREATE SCHEMA public;

CREATE TABLE t1 (f1 NUMERIC);
ALTER TABLE t1 REPLICA IDENTITY FULL;

INSERT INTO t1 VALUES (NULL), ('0.000000000000000000000000000001'), ('-1111111111111111111111111111111');

CREATE PUBLICATION mz_source FOR ALL TABLES;

> CREATE MATERIALIZED SOURCE mz_source
  FROM POSTGRES HOST 'host=postgres port=5432 user=postgres password=postgres sslmode=require dbname=postgres'
  PUBLICATION 'mz_source';

> SELECT COUNT(*) > 0 FROM mz_source;
true

> CREATE VIEWS FROM SOURCE mz_source;

# Insert the same data post-snapshot
$ postgres-execute connection=postgres://postgres:postgres@postgres
INSERT INTO t1 SELECT * FROM t1;

> SELECT pg_typeof(f1) FROM t1 LIMIT 1;
"numeric"

> SELECT * FROM t1;
-1111111111111111111111111111111
-1111111111111111111111111111111
0.000000000000000000000000000001
0.000000000000000000000000000001
```

The test may need to be adjusted to reality post-fix, as it uses a very wide "dynamic range" of the inserted values so to speak. As discussed above, maybe Mz can be made to support only a narrower range of precision + scale.

**Comment by petrosagg** [comment]
Shouldn't we just refuse to replicate this table if we don't support the datatype?

**Comment by philip-stoev** [comment]
Yes, on a second thought the error is safer than trying to figure out an appropriate scale and precision for the incoming data.

@petrosagg you are welcome to close the ticket if you prefer.

**Comment by petrosagg** [comment]
Sounds good. I'll close the issue and come back to it once we have support for these datatypes
