### ISSUE TITLE
pg-cdc: DROP DATABASE returns a Postgres error without labeling it as such, specifying the problematic source

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#6823]
### What version of Materialize are you using?

```
v0.7.4-dev (5e4089e4d) 
```

### What was the issue?

I got the following error on ```DROP DATABASE```

```
db error: ERROR: db error: ERROR: replication slot "materialize_f82fcf30adb640a1abba808a806cf87e" is active for PID 92: ERROR: replication slot "materialize_f82fcf30adb640a1abba808a806cf87e" is active for PID 92
```
The text of this error comes from Postgres, so the error message would be very confusing for a Mz user. Furthermore, it does not specify which Postgres source is to blame.

### Is the issue reproducible? If so, please provide reproduction instructions.

I only saw it once. I modified ```pg-cdc/mzcompose.yml``` to run tests randomly and then ran them:

```
diff --git a/test/pg-cdc/mzcompose.yml b/test/pg-cdc/mzcompose.yml
index b1572a019..960799a0e 100644
--- a/test/pg-cdc/mzcompose.yml
+++ b/test/pg-cdc/mzcompose.yml
@@ -30,6 +30,7 @@ services:
       - >-
         testdrive
         --materialized-url=postgres://materialize@materialized:6875
+        --shuffle-tests
         $$*
       - bash
     volumes:
```

### Please attach any applicable log files.

Nothing in the logs.

**Comment by petrosagg** [comment]
@JLDLaughlin this looks related to the slot drop code

**Comment by JLDLaughlin** [comment]
We should no longer see this as of https://github.com/MaterializeInc/materialize/pull/6886 and https://github.com/MaterializeInc/materialize/issues/6907!
