### ISSUE TITLE
storage/sources/postgres: test against multiple versions

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#6825]
Currently the test uses postgres 11, but there are also versions 12 and 13.

Creating a straightforward mzcompose workflow in the vain of kafka-matrix is prevented by the fact that 12 and 13 fail to start up with the current certificate setup -- their docker-entrypoint.sh requires that the certs are present on startup, but we install them in /docker-entrypoint-initdb.d/setup-postgres.sh which is called later.

**Comment by nrainer-materialize** [comment]
We are testing against other Postgres versions in the [release qualification pipeline.](https://buildkite.com/materialize/release-qualification/builds/)

<img width="444" alt="Bildschirmfoto 2024-06-04 um 14 56 32" src="https://github.com/MaterializeInc/materialize/assets/129728240/9344d505-8330-477e-b2de-b3d8ab61a821">
