### ISSUE TITLE
sql: multiple sources against the same Kafka topic are allowed, could cause an inconsistency

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#6878]
### What version of Materialize are you using?

```
v0.7.4-dev (cc35d6a79)
```

### What was the issue?

The consistency protections from https://github.com/MaterializeInc/materialize/pull/6532 apply only to multiple views on top of a single source. However, if multiple sources are created on top of a single Kafka topic, those can still return different results for the same timestamp, which would be inconsistent.

My suggestion is to prevent the creation of multiple sources against the same Kafka topic in order to prevent users from shooting themselves in the foot.

### Is the issue reproducible? If so, please provide reproduction instructions.

I was unable to reproduce the problem with a test but see #6532 and the attendant design document for a discussion.

```
$ kafka-create-topic topic=data

> CREATE MATERIALIZED SOURCE direct_source1
  FROM KAFKA BROKER '${testdrive.kafka-addr}' TOPIC 'testdrive-data-${testdrive.seed}'
  FORMAT AVRO USING SCHEMA '${schema}';

> CREATE MATERIALIZED SOURCE direct_source2
  FROM KAFKA BROKER '${testdrive.kafka-addr}' TOPIC 'testdrive-data-${testdrive.seed}'
  FORMAT AVRO USING SCHEMA '${schema}';

> CREATE MATERIALIZED VIEW direct_view1 AS SELECT a + 0 AS a FROM direct_source1;

> CREATE MATERIALIZED VIEW direct_view2 AS SELECT a + 0 AS a FROM direct_source2;

> CREATE MATERIALIZED VIEW check_v5 AS SELECT a + 0 AS a FROM direct_view1 EXCEPT ALL SELECT a - 0 AS a FROM direct_view2;
```

**Comment by benesch** [comment]
This is in spec. There are no consistency guarantees across different Kafka sources. I don't think we need to go out of our way to prevent users from creating multiple sources for the same Kafka source. There may be legitimate reasons that users do this (e.g., two different teams that want to ingest the same Kafka source in two different ways).
