### ISSUE TITLE
Have `MirRelationExpr::Constant` detect unique keys

### ISSUE THREAD

**Issue by wangandi** [MaterializeInc/materialize#6902]
https://github.com/MaterializeInc/materialize/blob/0d66b5c7689bca819653a7649aa28c8de6305a06/src/expr/src/relation/mod.rs#L253

Each column whose values are unique should be its own set of unique keys.
E.g. If these three rows comprise the constant statement, the set of keys should be `[[0], [1]]`, not `[[0, 1]]` or `[[0],[1],[0,1]`.
`(1, 1, 1), (2, 2, 1), (3,3,1)`

**Comment by umanwizard** [comment]
Closed by #6904
