### ISSUE TITLE
source Metadata fetch error: OperationTimedOut - Unable to fetch kafka metadata for topic

### ISSUE THREAD

**Issue by crohorner** [MaterializeInc/materialize#6916]
A user encounters a lot of `Unable to fetch kafka metadata for topic` errors. Disabling kerberos token requests resolved the issue, but there seems to be a real underlying issue, so creating this issue to track potential followon work.

[Internal] See for more details -- [https://materializecommunity.halp.com/tickets/14/slackRequesterThread](https://materializecommunity.halp.com/tickets/14/slackRequesterThread) gz#52. Note that a different user also encountered similar issues awhile ago and worked around it by switching from RHEL to Ubuntu 20.04

**Comment by ruchirK** [comment]
The proper engineering followup here is probably to rip out the kafka polling thread in the timestamper for real-time sources see #6322

**Comment by umanwizard** [comment]
@ruchirK still working on this? Or should we reassign?

**Comment by umanwizard** [comment]
@aljoscha Volunteered to take a look

**Comment by ruchirK** [comment]
Yeah sorry I have not been working on this. IMO rather than trying to debug this issue we should see if we can just move past metadata requests and instead use the stats callback to get the partition count info (which is the only reason we need this consumer afaik)

Feel free to reassign to Aljoscha

**Comment by aljoscha** [comment]
The metadata thread in the coordinator doesn't exist anymore. We'll open a new issue if/when we encounter any problems with the new implementation.
