### ISSUE TITLE
Unacceptable duplication of mzcompose.yml files

### ISSUE THREAD

**Issue by benesch** [MaterializeInc/materialize#6938]
There has been an proliferation of nearly identical mzcompose.yml files recently:

  - https://github.com/MaterializeInc/materialize/blob/main/demo/debezium/mzcompose.yml
  - https://github.com/MaterializeInc/materialize/blob/main/test/bench/aggregations/mzcompose.yml
  - https://github.com/MaterializeInc/materialize/blob/main/test/bench/avro-insert/mzcompose.yml
  - https://github.com/MaterializeInc/materialize/blob/main/test/bench/avro-upsert/mzcompose.yml
  - https://github.com/MaterializeInc/materialize/blob/main/test/bench/kafka-sink-avro-debezium/mzcompose.yml
  - https://github.com/MaterializeInc/materialize/blob/main/demo/chbench/mzcompose.yml
  - https://github.com/MaterializeInc/materialize/blob/main/test/chaos/mzcompose.yml

Evolving the mzcompose file format, updating the Debezium version, etc. is now very difficult. We need to be much more judicious with adding code to the repository, because having seven copies of nearly identical mzcompose files is not maintainable. 

Concretely, I don't think demo/debezium belongs in this repository, and we need to figure out how to make mzbench less duplicative.

**Comment by benesch** [comment]
For contrast, here is an example of a properly minimized mzcompose file: https://github.com/MaterializeInc/materialize/blob/main/test/catalog-compat/mzcompose.yml

A big problem with the proliferation that is occurring is it is leading to uncontrollable cargo culting. Most of the services and most of the environment variables in the existing Docker Compose files is unnecessary, but when the files are so large they're unmanageable, and folks are afraid to slim them down, and then the complexity just skyrockets and skyrockets.

**Comment by uce** [comment]
What do you think about adding a high-level best practices or style guide section to [mzbuild.md](https://github.com/MaterializeInc/materialize/blob/b401deb/doc/developer/mzbuild.md)? Ideally, we would have checks that prevent certain constructs, but I haven't checked yet how much we would be able to cover with automated checks.

**Comment by benesch** [comment]
So we have a bit of linting that looks for known problematic constructs and rejects them: https://github.com/MaterializeInc/materialize/blob/main/misc/python/materialize/mzcompose.py#L93

They're fairly primitive at the moment. Unfortunately a lot of it comes down to "don't include unnecessary {environment variables, volume specifications, exposed ports}", and it's hard to lint those as a rule. I'd be very down to put that statement somewhere! But I fear the best way to tackle this is to prune out all the unnecessary cruft from the existing mzcompose files, so that folks who copy and paste from existing mzcompose files have a better base to work off of.

**Comment by benesch** [comment]
We have a path forward here thanks to @philip-stoev! Details in #9809.
