### ISSUE TITLE
(docs) Add instructions for subscribing to S3->SNS->SQS notifications

### ISSUE THREAD

**Issue by ruf-io** [MaterializeInc/materialize#6946]
We have functionality that allows users to point MZ at a notification feed for S3 bucket updates, giving MZ the ability to ingest new objects as they appear in a a bucket: https://materialize.com/docs/sql/create-source/text-s3/#listening-to-sqs-notifications

BUT, AWS only allows you to link one SQS queue directly to a bucket, so if a user is already using the S3->SQS connection for something else, they can't create a second queue for Materialize.

The official AWS workaround is to use S3->SNS--fanout-->multiple SQS queues. There is a gotcha when doing things this way that you need to:

>enable raw message delivery for the SQS queue that you feed into materialized: https://docs.aws.amazon.com/sns/latest/dg/sns-large-payload-raw-message-delivery.html

- @quodlibetor 

We should document this in the  "Listening to SQS notifications" section on all S3 source pages, and include relevant links to AWS docs.

related slack thread: https://materializecommunity.slack.com/archives/C015KDVS7EV/p1622827710063500

**Comment by morsapaes** [comment]
Closing as stale, since we no longer support a s3 source.
