### ISSUE TITLE
sql: apd min, max

### ISSUE THREAD

**Issue by sploiselle** [MaterializeInc/materialize#6947]
The `apd` type needs to support min/max aggregate functions, which can be patterned off of the existing [max function for `float64`](https://github.com/MaterializeInc/materialize/blob/main/src/expr/src/relation/func.rs#L73-L83). We should get the built-in `min`/`max` functions for free for having implemented `Ord` on the underlying data type ([`OrderedDecimal<Decimal<N>>`](https://github.com/MaterializeInc/rust-dec/blob/master/dec/src/ordered.rs#L172-L194)).

The upstream tracking issue for apd functions is #6761 .

**Comment by antifuchs** [comment]
Taking this to pass on to Moritz later (:
