### ISSUE TITLE
apd: numbers not right-justified in psql client

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#6949]
### What version of Materialize are you using?

```
materialized v0.7.4-dev (a312dde63)
```

### What was the issue?

In the psql client, the ```apd``` data type is left-justified, like a string, and not right-justified like any other number. This may mean that the proper metadata is not being sent to the client?

### Is the issue reproducible? If so, please provide reproduction instructions.

```
materialize=> select '123.234'::apd union all select '0.0'::apd;
 ?column? 
----------
 0 <- left justified
 123.234
(2 rows)
```

Contrast with decimal:

```
materialize=> select '123.234'::decimal(20,10) union all select '0.0'::decimal(20,10);
    ?column?    
----------------
   0.0000000000 <- right justified
 123.2340000000
(2 rows)
```

And constrast with Postgres where ```APD``` has been defined as ```DOMAIN AS OF DECIMAL```:

```
pstoev=# select '123.234'::apd union all select '0.0'::apd;
   apd   
---------
 123.234
     0.0 <- right justified
(2 rows)
```

The final example tells me that the client is capable of right-justifying numbers even if they are not defined as a base numeric type that is explicitly hard-coded in the client(?)

**Comment by sploiselle** [comment]
Ah, yeah––this is because the data is currently getting sent back to the client as `text` because we haven't yet implemented the proper binary encoding for it to be read as a PG `numeric`. Will leave this issue open and assigned to myself as insurance that this gets resolved when we merge `apd` into `numeric` in MZ.
