### ISSUE TITLE
ORDER BY around a SELECT should be able to implicitly project columns

### ISSUE THREAD

**Issue by jamii** [MaterializeInc/materialize#696]
Both of these should work:

```
select k from kv order by v;
select k from kv group by k order by max(v);
```

I've tried to fix this and given up. Worth keeping in mind when we revisit how scoping / project should work.

**Comment by justinj** [comment]
Doesn't look like this was supposed to be closed

**Comment by benesch** [comment]
D’oh, thanks. I forget that GitHub mishandles “this does not fix #xxx.”
