### ISSUE TITLE
[durability]: Assess and document durability for Kafka upsert sources

### ISSUE THREAD

**Issue by frankmcsherry** [MaterializeInc/materialize#6990]
It would seem that with Kafka upsert sources, which are able to compact themselves without damaging their long-term interpretability of the data, and persisted source timestamps, we have the ability to claim some amount of durability. I think we probably don't actually have "durability" yet (e.g. the coordinator hasn't been trained to hold back SELECT answers until timestamps are durable) but we could start the process of assessing it.

If it turns out that there is at least one recommendable set up that provides the compelling parts of durability (say: bounded input re-reads on restart (due to upsert compaction), no durability/consistency artifacts, recommended egress (e.g. EOS)) then confirming, documenting, and explaining it seems like a valuable milestone.

**Comment by elindsey** [comment]
Closing, this one's not really relevant anymore given platform
