### ISSUE TITLE
De-experimentalize real time source exactly-once sinks

### ISSUE THREAD

**Issue by ruchirK** [MaterializeInc/materialize#7003]
Exactly once sinks (reuse kafka topic names as asked for in #2915 ) merged behind the experimental flag in #6926 but has some known flakiness as covered in #6978 -- lets fix the flakiness, do some more testing and get this out for real

- [x] #7598
- [x] further load and chaos tests, especially against RT sources. This will likely shake out some more concerns but the one known performance issue is the one I mentioned in the weekly meeting today
- [x] sinks hold back timestamp binding compaction for a source even when there are no new updates to be sinked (even though the source is advancing timestamps). This causes a memory and disk resource leak.
- [x] docs and release notes

## Optional next steps

- allow users to specify a per-source compaction window (maybe with ALTER SOURCE?) the way they can with ALTER INDEX right now a source's compaction window is always the mz-wide default

**Comment by cuongdo** [comment]
As this is a P1, what is the next step for this issue? Is it removing the nonce?

**Comment by ruchirK** [comment]
Sure:

theres a couple of small prs to fix the glitchiness issues

1. https://github.com/MaterializeInc/materialize/pull/7053
2. https://github.com/MaterializeInc/materialize/pull/7065

and then I'll merge a fix for https://github.com/MaterializeInc/materialize/issues/7072, and then this is ready for user testing.

Once we have user testing and are ready for de-experimentalizing I think we should make EOS sinks the default and get rid of the nonce stuff @aljoscha what do you think of that?

**Comment by aljoscha** [comment]
There is also https://github.com/MaterializeInc/materialize/issues/6035, and potentially other problems with EO sink performance. I do remember from testing a while back that there is a 20% (plus or minus) hit to performance with EO enabled in the sink.

I do agree with your suggestion, though!

**Comment by ruchirK** [comment]
@awang I spoke to Brennan about this but once #7072 and #7065 land (which I think can happen tomorrow) we are ready to have prospects play with exactly once sinks.

From my perspective, the remaining work to de-experimentalize the feature is

- extend our testdrive based tests to validate the contents of the consistency topic.
- further load and chaos tests, especially against RT sources. This will likely shake out some more concerns but the one known performance issue is the one I mentioned in the weekly meeting today
  - sinks hold back timestamp binding compaction for a source even when there are no new updates to be sinked (even though the source is advancing timestamps). This causes a memory and disk resource leak.
 - allow users to specify a per-source compaction window (maybe with `ALTER SOURCE`?) the way they can with `ALTER INDEX` right now a source's compaction window is always the mz-wide default
 - docs and release notes
 
 Longer term work for EOS:
 
 Frank had some thoughts for a simpler and more compartmentalized design that I absolutely think is worth exploring in the medium / longer term.

**Comment by ruchirK** [comment]
@awang exactly once sinks are ready for customer trials / ready to be documented as experimental. I'm going to assign this issue to @aljoscha now because he's going to own the rest of the de-experimentalization followups
