### ISSUE TITLE
s3: all keys from a single bucket are not ingested in a single transaction

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#7010]
### What version of Materialize are you using?

```
materialized v0.7.4-dev (7ee9c463b)

```
### What was the issue?

As @antiguru observed, individual keys from S3 are ingested separately, so they do not form a single transaction. Therefore, the user can see partial view of their data. 

### Is the issue reproducible? If so, please provide reproduction instructions.

@antiguru has reported seeing this visually as he worked on S3

**Comment by umanwizard** [comment]
Do we expect all elements of a given bucket to be at the same timestamp? We've never discussed this, AFAICT.

**Comment by umanwizard** [comment]
We've decided via discussion on Slack that this is not a bug.

**Comment by philip-stoev** [comment]
@umanwizard what about individual lines from within the same bucket? Should those share a timestamp?

**Comment by umanwizard** [comment]
The consensus was that that should be configurable by the user -- we wouldn't want to enable it by default due to the large perf impact.
