### ISSUE TITLE
[optimization] Introduce RelationExpr CSE

### ISSUE THREAD

**Issue by frankmcsherry** [MaterializeInc/materialize#7046]
Our analysis will inline `Let` expressions, but does no hard work to identify opportunities to create `Let` expressions that re-use expressions. Re-using expressions would result in fewer dataflow fragments, which results in less computation and less state maintained, at least from those fragements.

The downside of `Let` bindings is that we lose the opportunity to optimize expressions independently: we can only push down maps, filters, projections, etc if all of the `Get` uses have the same things to push down. At the moment, the `render` layer does this for us, but with #7001 we will not be doing that. If nothing else, we should re-introduce a CSE optimization in the final steps of dataflow optimization, to avoid regressions there.

**Comment by asenac** [comment]
The way in which I've approached this in QGM in the past is to let predicate pushdown transform duplicate the operator the predicate is being pushed down to, and then, run a transformation called `CTE discovery`, that finds common subgraphs in the query, including common sub-joins which results could be re-used.

If the same predicate happens to be pushed down through all the paths reaching a given operator, before CTE discovery we have a bunch of duplicated subgraphs, that CTE discovery can take care of.
