### ISSUE TITLE
Cleaning up S3 buckets after tests can fail

### ISSUE THREAD

**Issue by antiguru** [MaterializeInc/materialize#7090]
### What version of Materialize are you using?

https://buildkite.com/materialize/tests/builds/18370
```
cc344ba6ed (Pull Request #7033)

```

### What was the issue?

The test failed to delete the test buckets during cleanup:
```
error: Failed to clean up state at shut down: deleting S3 buckets: 1 errorsdeleting S3 buckets: 1 errors: Request ID: None Body: <?xml version="1.0" encoding="UTF-8"?>
<Error><Code>InternalError</Code><Message>We encountered an internal error. Please try again.</Message><RequestId>BHMSQWAXSPB4YPRV</RequestId><HostId>2qiNVxiKL83Lfkdd2pXUX1HTJMC3W1oRsj6C83mRZ3q5CzLAlbaPYifkaqofcZxUSK1WGw2WUXg=</HostId></Error>
 
1 errors were encountered during execution
files involved: esoteric/s3.td
```

https://buildkite.com/materialize/tests/builds/18370#00e56d84-58a6-4a08-b93c-815ace14e7cb/314-365

### Is the issue reproducible? If so, please provide reproduction instructions.

It cannot be reproduced unless we can predictably fail S3 (or localstack).

**Comment by benesch** [comment]
Closing as we no longer support S3 sources.
