### ISSUE TITLE
Support for Regex in S3 Sources

### ISSUE THREAD

**Issue by nmeagan11** [MaterializeInc/materialize#7136]
There is a use case where a user is storing data in JSON files in S3. Due to custom sharding across the JSON files, they may need to filter on multiple files in order to get the full dataset they're querying for. Currently, Materialize does support [pattern matching](https://materialize.com/docs/sql/create-source/json-s3/#patterns), but this does not cover the pattern search they need (waiting on feedback for what pattern is desired). Regex support would solve this.

**Comment by quodlibetor** [comment]
The more complete solution to this is #6605 , which will allow users to create a materialized view containing S3 object names to download. That view can filter S3 object names by regex (or any other SQL feature, including joining against other views).

**Comment by sploiselle** [comment]
s3 sources deprecated
