### ISSUE TITLE
[sql] `regexp_extract` arguments in opposite order to postgres `regexp_matches`

### ISSUE THREAD

**Issue by frankmcsherry** [MaterializeInc/materialize#7151]
Our `regexp_extract` takes the regular expression first and then the text. Postgres' `regexp_matches` takes the text first and then the regular expression.

**Comment by benesch** [comment]
They're different functions! `regexp_extract` is our own invention. I agree it'd be nice if it had hewed more closely to the similar PostgreSQL functions, but... changing at this point would cause some user pain that is probably not worth it.

**Comment by frankmcsherry** [comment]
Fair enough. Do we have the goal of matching postegres' `regexp_matches`, which would replace this and be an opportunity to match the syntax (and deprecate this in the process)?

**Comment by benesch** [comment]
They serve different purposes. `regexp_extract` is a weird thing of ours that statically analyzes a regex to determine how many capture groups it has, and then it guarantees you will have that many columns. It's pretty convenient for the cases where you have e.g. a log line with a fixed number of fields. 

`regexp_matches` by contrast always returns exactly one column containing a text array, as it doesn't require that it knows the regex at plan time. And then it might return anywhere from zero to _n_ rows, depending on how many times the regex matched.. but the capture groups _inside_ each match of the regex form the elements of the array. It's pretty weird. I mentioned this somewhere else but I think the story for "splitting words" is probably best with `regexp_split_to_table`?
