### ISSUE TITLE
Add support for `regexp_split_to_table`

### ISSUE THREAD

**Issue by frankmcsherry** [MaterializeInc/materialize#7153]
We have a method `regexp_extract` that is somewhat analogous to postgresql's `regexp_matches`, except that ours only returns the first matches and does not enumerate all matches. Our `regexp_extract` is confusingly in the "Table Functions" section of our documentation, despite only ever returning at most one row (I think this is because it can produce multiple columns).

It looks like an easy win to add the corresponding multiple-match variant that uses `captures_iter()` from the `regex` crate, rather than `captures()` which only returns the first match. 

This is related to existing issues on supporting string splitting (https://github.com/MaterializeInc/materialize/issues/3339) and `regexp_split_to_array` (https://github.com/MaterializeInc/materialize/issues/4714) which seems like it could produce the same result though much less directly.

**Comment by frankmcsherry** [comment]
This diff is what I'm using to get the multiple matches behavior:
```
mcsherry@gallustrate materialize % git diff
diff --git a/src/expr/src/relation/func.rs b/src/expr/src/relation/func.rs
index 133b61e29..cdbcc203f 100644
--- a/src/expr/src/relation/func.rs
+++ b/src/expr/src/relation/func.rs
@@ -645,15 +645,20 @@ fn jsonb_array_elements<'a>(
     }
 }
 
-fn regexp_extract(a: Datum, r: &AnalyzedRegex) -> Option<(Row, Diff)> {
+fn regexp_extract(a: Datum, r: &AnalyzedRegex) -> Vec<(Row, Diff)> {
     let r = r.inner();
     let a = a.unwrap_str();
-    let captures = r.captures(a)?;
-    let datums = captures
+    let mut result = Vec::new();
+    for captures in r.captures_iter(a) {
+        let datums = captures
         .iter()
         .skip(1)
         .map(|m| Datum::from(m.map(|m| m.as_str())));
-    Some((Row::pack(datums), 1))
+        result.push(
+            (Row::pack(datums), 1)
+        );
+    }
+    result
 }
 
 fn generate_series_int32(start: Datum, stop: Datum) -> Vec<(Row, Diff)> {
mcsherry@gallustrate materialize % 
```

**Comment by benesch** [comment]
> We have a method `regexp_extract` that is somewhat analogous to postgresql's `regexp_matches`, except that ours only returns the first matches and does not enumerate all matches. Our `regexp_extract` is confusingly in the "Table Functions" section of our documentation, despite only ever returning at most one row (I think this is because it can produce multiple columns).

Yeah, anything that produces more than one column has to be a table function.

> It looks like an easy win to add the corresponding multiple-match variant that uses `captures_iter()` from the `regex` crate, rather than `captures()` which only returns the first match.
> 
> This is related to existing issues on supporting string splitting (#3339) and `regexp_split_to_array` (#4714) which seems like it could produce the same result though much less directly.

I think `regexp_split_to_table` is the function you're looking for.

**Comment by frankmcsherry** [comment]
Is `regexp_split_to_table` a function that exists, or will soon exist? I don't personally mind the name, I just happened to learn about `regexp_matches` which we seem to partially support (it seems maybe PostgreSQL can use it in places we cannot? It doesn't seem to be the same function).

**Comment by wangandi** [comment]
I am confused about the desired behavior and syntax of `regexp_split_to_table`. 

The [postgres example](https://www.postgresql.org/docs/current/functions-matching.html#FUNCTIONS-POSIX-REGEXP) looks like this:

```
SELECT foo FROM regexp_split_to_table('the quick brown fox jumps over the lazy dog', '\s+') AS foo;
  foo   
-------
 the    
 quick  
 brown  
 fox    
 jumps 
 over   
 the    
 lazy   
 dog    
(9 rows)
```

The syntax of `regexp_extract` and Frank's example code above makes it look like the desired syntax behavior is:
```
SELECT * FROM regexp_split_to_table('(\s+)', 'the quick brown fox jumps over the lazy dog') AS foo;
column1
-------
  

 
 
 
 
 
 
(8 rows)
```
(The 8 rows are not empty; they each contain a string consisting of a single space.)

**Comment by benesch** [comment]
Hell yeah. Thanks @mjibson!
