### ISSUE TITLE
doc: document the CREATE INDEX statement to materialize an unmaterialized view

### ISSUE THREAD

**Issue by rjnn** [MaterializeInc/materialize#7163]
I wrote `CREATE VIEW foo` instead of `CREATE MATERIALIZED VIEW foo`.

I want to materialize it. I have to create an index. The `CREATE INDEX` docs don't tell me what to type in an obvious way that materializes my view.

**Comment by rjnn** [comment]
Turns out this is "CREATE DEFAULT INDEX ON ...".

**Comment by benesch** [comment]
![image](https://user-images.githubusercontent.com/882976/123375711-3ef44900-d557-11eb-92c1-904c452c83ab.png)

Was there something else you wanted to see in the docs?

**Comment by rjnn** [comment]
I think I was just blind.
