### ISSUE TITLE
Cannot query Materialize with psycopg2

### ISSUE THREAD

**Issue by awang** [MaterializeInc/materialize#7167]
### What version of Materialize are you using?

 v0.8.0 (b2fe225f1)

### How did you install Materialize?

curl -L https://binaries.materialize.com/materialized-v0.8.0-x86_64-apple-darwin.tar.gz

### What was the issue?

Psycopg2 returns `psycopg2.errors.InternalError_
psycopg2.errors.InternalError_: Unable to automatically determine a timestamp for your query; this can happen if your query depends on non-materialized sources.`.  Strangely, it works fine over psql.  I've also heard an anecdotal report that this is also happening to Metabase, which leads me to believe it's not specific to psycopg2.  I'm pretty sure other folks have successfully connected via psycopg2 and this works fine for me in 0.7.2, so i suspect this is a regression in 0.7.3 or 0.8

### Is the issue reproducible? If so, please provide reproduction instructions.

psql:
```
materialize=> create table foo(bar int, baz int);
CREATE TABLE
materialize=> insert into foo values(1, 2), (3, 4);
INSERT 0 2
materialize=> select * from foo;
 bar | baz 
-----+-----
   1 |   2
   3 |   4
(2 rows)
```

psycopg2 (over Flask):
```
from flask import Flask, jsonify
import psycopg2
import os

app = Flask(__name__)


try:
    con = psycopg2.connect(
        "host=localhost port=6875 dbname=materialize user=materialize"
        )


    @app.route('/')
    def test_page():
        cur = con.cursor()

        cur.execute('SELECT * FROM foo')
        rows = cur.fetchall()
        print(rows)

        return jsonify(rows)


except Exception as inst:
    print(type(inst))
    print(inst)
except:
    print('Error')
```

**Comment by benesch** [comment]
@mjibson this seems likely to be related to txn protocol changes?

**Comment by mjibson** [comment]
I think this is #6651.

**Comment by benesch** [comment]
There's no non-materialized source here though? But possibly you know better than I do!

**Comment by mjibson** [comment]
I am not able to reproduce this. Can you run `SHOW SOURCES;` and tell me if anything shows up there? My guess is you have a source there and that's what's causing the issue. 6651 still needs to be fixed, but I don't currently have a reason to believe that psycopg2 has any problems.

**Comment by awang** [comment]
weird!   it's an empty, vanilla materialize instance though (i wiped `mzdata` prior to encountering this):

```
materialize=> show sources;
      name      
----------------
 kinesis_source
(1 row)
```

**Comment by awang** [comment]
Interesting, thanks!  So, I have a kinesis source + materialized kinesis view.  Dropping that source+view fixed it.  

I'm about to hop on a call, but I'm going to run a few more tests later today to try and figure out what steps exactly to reproduce

**Comment by mjibson** [comment]
Unless it's different than 6551 I already know how to repro.

**Comment by awang** [comment]
thank you!  that fixed it
