### ISSUE TITLE
Consider alternative design of system tables for librdkafka statistics

### ISSUE THREAD

**Issue by benesch** [MaterializeInc/materialize#7172]
We currently expose two system tables with librdkafka metrics:

```
show columns from mz_kafka_broker_rtt;
     name      | nullable |  type  
---------------+----------+--------
 consumer_name | f        | text
 source_id     | f        | text
 dataflow_id   | f        | bigint
 broker_name   | f        | text
 min           | f        | bigint
 max           | f        | bigint
 avg           | f        | bigint
 sum           | f        | bigint
 cnt           | f        | bigint
 stddev        | f        | bigint
 p50           | f        | bigint
 p75           | f        | bigint
 p90           | f        | bigint
 p95           | f        | bigint
 p99           | f        | bigint
 p99_99        | f        | bigint
(16 rows)

materialize=> show columns from mz_kafka_consumer_partitions;
     name      | nullable |  type  
---------------+----------+--------
 consumer_name | f        | text
 source_id     | f        | text
 dataflow_id   | f        | bigint
 partition_id  | f        | text
 rx_msgs       | f        | bigint
 rx_bytes      | f        | bigint
 tx_msgs       | f        | bigint
 tx_bytes      | f        | bigint
 lo_offset     | f        | bigint
 hi_offset     | f        | bigint
 ls_offset     | f        | bigint
 app_offset    | f        | bigint
 consumer_lag  | f        | bigint
(13 rows)
```

These are basically rote flattenings of the statistics structs provided by librdkafka: https://github.com/edenhill/librdkafka/blob/master/STATISTICS.md

There are several things worth considering:

  1. The column names don't follow our convention for system tables (e.g. `cnt` instead of `count`).
  1. We're very tied to librdkafka's statistics shape. If we ever replace librdkafka as our Kafka library, we'll have to rework these tables, or at least go to some trouble to mash the new library's statistics format into this format.
  1. We go to a _lot_ of trouble to unpack all of these values and ship them around our logging infrastructure.

An alternative for consideration: what if we just shipped the raw statistics reported by librdkafka as a big bag of `jsonb`? That would increase our coupling to the librdkafka format only marginally, and reduce the maintenance burden of these tables to near zero. New librdkafka releases that add statistics would be immediately accessible upon upgrade.

cc @elindsey for thoughts

**Comment by elindsey** [comment]
That sounds like a great idea to me!
