### ISSUE TITLE
Is JSONB the right type for mz_metrics.labels?

### ISSUE THREAD

**Issue by benesch** [MaterializeInc/materialize#7173]
And similarly with `mz_metrics_histograms.labels`. Seems like these want to be `map[text => text]`, if possible! cc @antifuchs 

Perhaps blocked on #2997?

**Comment by antifuchs** [comment]
That's a good call - I think the main thing we want out of this table is to have the labels be query-able conveniently (e.g. SELECT the metrics where a source has a particular name). I wasn't aware of maps when I wrote this (seems to be an mz internal type? I don't find psql docs on it) - but considering the wealth of operators we have on map, that would be a good thing.

**Comment by benesch** [comment]
Yeah, it's a Materialize-specific thing we had to add to support ingesting Avro and such. We've got more work to do to make it useable, but I think it's ultimately the right call! Just wanted to double-check that you didn't intentionally avoid the map type for some reason I wasn't aware of!

**Comment by benesch** [comment]
Welp, this got "fixed" via the removal of `mz_metrics`.
