### ISSUE TITLE
Telemetry counts are reset to 0 after restart

### ISSUE THREAD

**Issue by uce** [MaterializeInc/materialize#7181]
### What version of Materialize are you using?

```
materialized v0.8.1-dev (da38e0c97)
```

### How did you install Materialize?

* [x] Built from source

### What was the issue?

Telemetry counts are reset after restart.

After creating a file source the telemetry report includes `"file":{"count": 1}`.

```json
 {"version":"0.8.1-dev","status":{"session_id":"696fd58a-a3a4-4789-87ee-1111bdbdb383","uptime_seconds":90,"num_workers":4.0,"sources":{"avroOcf":{"count":0},
"file":{"count":1},"kinesis":{"count":0},"postgres":{"count":0},"s3":{"count":0},"table":{"count":0}},"views":{"count":0},"sinks":{"tail":{"count":0},"kafka":{"count":0},"avroOcf":{"count":0}}}}
```

After `materialized` restarts, the count is reset to 0.

```json
{"version":"0.8.1-dev","status":{"session_id":"463d1e1c-9a48-42da-9d0a-8887a6012258","uptime_seconds":0,"num_workers":4.0,"sources":{"avroOcf":{"count":0},
"file":{"count":0},"kinesis":{"count":0},"postgres":{"count":0},"s3":{"count":0},"table":{"count":0}},"views":{"count":0},"sinks":{"tail":{"count":0},"kafka":{"count":0},"avroOcf":{"count":0}}}}
```

This could be by design, but our internal dashboard seems to assume that counts are not reset. cc @awang 

---

This has been discovered with @aljoscha during dogfooding day.

**Comment by benesch** [comment]
Oof, thanks! I have a rework of the telemetry stuff coming down the pipe that will shake this out.
