### ISSUE TITLE
Postgres cast is more lenient than Materialize 

### ISSUE THREAD

**Issue by uce** [MaterializeInc/materialize#7183]
### What version of Materialize are you using?

```
materialized v0.8.1-dev (da38e0c97)
```

### How did you install Materialize?

* [x] Built from source

### What was the issue?

Casting int Postgres seems more lenient than Materialize:

```sql
> CREATE TABLE data (ts timestamp, cluster_id text, data jsonb);

> INSERT INTO data (ts, cluster_id, data) VALUES ('2020-11-15 19:29:11.908896'::timestamp, '03b5ead9-dac7-4530-b3f7-f8db6942c34a', '{"version":"0.5.1"}');
```

#### Postgres

```sql
> SELECT cast(data->'status'->'num_workers' as int) FROM data WHERE cluster_id = '03b5ead9-dac7-4530-b3f7-f8db6942c34a';
 int4
------

(1 row)
```

#### Materialize

```sql
> SELECT cast(data->'status'->'num_workers' as int) FROM data WHERE cluster_id = '03b5ead9-dac7-4530-b3f7-f8db6942c34a';
ERROR:  internal error: column 0 is not of expected type ColumnType { nullable: false, scalar_type: Int32 }: Null
```

A workaround is to use `coalesce`:

```sql
> SELECT coalesce(cast(data->'status'->'num_workers' as int)) FROM data WHERE cluster_id = '03b5ead9-dac7-4530-b3f7-f8db6942c34a';
 coalesce
----------

(1 row)
```

While we ran into this with `jsonb`, it is probably a more general issue.

---

This has been discovered with @aljoscha during dogfooding day.

**Comment by benesch** [comment]
Hah, so this isn't a problem with our intended semantics of `CAST`; it's just a straight up programming error in Materialize. Whoops!

**Comment by benesch** [comment]
Here's a minimal repro: `select ('{}'::jsonb->'bad')::int;`

**Comment by benesch** [comment]
Even smaller: `select null::json::int;`
