### ISSUE TITLE
`at time zone` requires uppercase time zone

### ISSUE THREAD

**Issue by uce** [MaterializeInc/materialize#7185]
### What version of Materialize are you using?

```
materialized v0.8.1-dev (da38e0c97)
```

### How did you install Materialize?

* [x] Built from source

### What was the issue?

`extract` requires uppercase time zone.

#### Materialize

```sql
> SELECT now() at time zone 'utc';
ERROR:  invalid time zone 'utc'
```

It works as expected with an upper case `UTC`:

```sql
> SELECT now() at time zone 'UTC';
     date_part
-------------------
1624617940.289232
(1 row)
```

#### Postgres

```sql
>  SELECT now() at time zone 'utc';
     date_part
-------------------
1624617764.794288
(1 row)
```

---

This has been discovered with @aljoscha during dogfooding day.

**Comment by bjgbeelen** [comment]
It's not `extract` that requires the time zone, it's the `(_date_) at time zone _tz_` .
So the reconstruciton can be simplified:

```
materialize=> select now() at time zone 'utc';
ERROR:  invalid time zone 'utc'
materialize=> select now() at time zone 'UTC';
          timezone
----------------------------
 2021-06-25 12:19:18.051407
(1 row)
```

**Comment by uce** [comment]
@bjgbeelen I updated the title and description. Thanks for pointing it out 👍🏼

**Comment by petrosagg** [comment]
I added support to `chrono-tz` for case insensitive matching here https://github.com/chronotope/chrono-tz/pull/84
