### ISSUE TITLE
Replace deprecated `UPSERT FORMAT` syntax in docs

### ISSUE THREAD

**Issue by uce** [MaterializeInc/materialize#7187]
The railroad diagrams document the deprecated `UPSERT FORMAT`, but lack the new `KEY FORMAT ... VALUE FORMAT ...` syntax.

Example: https://materialize.com/docs/sql/create-source/text-kafka/

---

This has been discovered with @aljoscha during dogfooding day.

**Comment by msudberg** [comment]
The rr diagram is already fixed, but there was still a reference to UPSERT FORMAT in the details text.
