### ISSUE TITLE
Contribute TB's ChangeWriter upstream as a Debezium Server sink for Avro OCF

### ISSUE THREAD

**Issue by derekm** [MaterializeInc/materialize#7190]
TB's [ChangeWriter](https://github.com/MaterializeInc/materialize/blob/main/misc/tb/src/ChangeWriter.java) would make an excellent sink for Debezium Server:

https://debezium.io/documentation/reference/operations/debezium-server.html#_implementation_of_a_new_sink

Having support for on-disk Avro OCF files available as a sink in Debezium Server would likely simplify deployment and maintenance for Materialize as well as improve performance of TB (Debezium Server handles batches of records instead of individual records); benefits to the broader Debezium community notwithstanding.

I would be happy to help here, but the path looks pretty straight-forward.

**Comment by rjnn** [comment]
We are absolutely fine with that, if you are willing to do the porting. It's Apache-2 licensed so you should be good without anything more, but let me know if you need me to sign off on any CLA or such thing in order to facilitate it.

**Comment by elindsey** [comment]
I'm going to close this out, but feel free to reopen if you decide to do the porting work and have questions!
