### ISSUE TITLE
BI Tool Integration (Metabase, Superset): Regression in v0.8.0

### ISSUE THREAD

**Issue by morsapaes** [MaterializeInc/materialize#7193]
### What version of Materialize are you using?

```
v0.8.0
```

### How did you install Materialize?

* [x] Docker image

### What was the issue?

Running a `SELECT` statement on a materialized view (or source) within Metabase errors out with:

> Unable to automatically determine a timestamp for your query.

While trying to set up Superset with Materialize, the same error was thrown. In both cases, the issue was not present once downgraded to v0.7.0.

### Is the issue reproducible? If so, please provide reproduction instructions.

I first ran into this issue following the [Business Intelligence Demo walkthrough](https://materialize.com/docs/demos/business-intelligence/). Once you hit Metabase, just running: 

```sql
SELECT * FROM query01;
```
will lead to:

![Metabase Error](https://user-images.githubusercontent.com/23521087/123458405-511cc880-d5e5-11eb-9823-d4b6b43999fe.png)

Forcing a timestamp using `AS OF` returns results, but then occasionally fails with:

![Metabase 2](https://user-images.githubusercontent.com/23521087/123458170-08fda600-d5e5-11eb-8c35-ffa91d056d3b.png)

**Comment by benesch** [comment]
Hrm. This looks to be the same as #7167.

**Comment by morsapaes** [comment]
Missed it; I'll close this one, then. Thanks, @benesch !

**Comment by benesch** [comment]
I’d say leave it open! I’m not 100% sure.
