### ISSUE TITLE
Incorrectly allows trailing +/- after exponent

### ISSUE THREAD

**Issue by ruchirK** [MaterializeInc/materialize#7201]
Materialize allows

```
materialize=> select 1.5e+;
 ?column?
----------
      1.5
(1 row)

materialize=> select 1.5e-;
 ?column?
----------
      1.5
(1 row)
```

where postgres does not

```
Test=# select 1.5e-;
ERROR:  syntax error at or near "-"
LINE 1: select 1.5e-;
                   ^
Test=# select 1.5e+;
ERROR:  syntax error at or near "+"
LINE 1: select 1.5e+;
                   ^
```

curiously they both seem to allow strings like `1.5e` even though the documentation says "At least one digit must follow the exponent marker (e), if one is present." Materialize seems to just ignore the `e`

```
materialize=> select 2.5e;
 ?column?
----------
      2.5
(1 row)
```

whereas postgres turns it into the column name

```
Test=# select 2.5e;
  e
-----
 2.5
(1 row)
```

**Comment by benesch** [comment]
@sploiselle this seems like something that might shake out of your latest decimal changes?

**Comment by ruchirK** [comment]
I also noticed

```
materialize=> select pg_typeof(4.5e4);
 pg_typeof
-----------
 integer
(1 row)
```
In pg this is a `numeric` -- likely will also shake out of the decimal changes?
