### ISSUE TITLE
Enforce process separation between `coord` and `dataflow`

### ISSUE THREAD

**Issue by frankmcsherry** [MaterializeInc/materialize#7252]
Our code currently maintains idioms that the coordinator and dataflow modules are "distant" and largely sends "data" between the two rather than pointers into each others address space. However, there are some leaks of information, for example hooks to respond to user sessions without first returning through the coordinator.

It is probably worth shoring these up and at least mocking up the boundaries we would expect to have in a larger system. For example, requiring that transmissions between `coord` and `dataflow` in both directions implement `Serialize` and `Deserialize`, to ensure that our designs allow this in the future.

cc: @petrosagg

**Comment by uce** [comment]
This PR is probably related https://github.com/MaterializeInc/materialize/pull/7504.

**Comment by frankmcsherry** [comment]
I think this can now be closed, as we have `coordd` and `dataflowd` in CI.
