### ISSUE TITLE
[coordinator] Perform pre-dataflow optimization without arrangements

### ISSUE THREAD

**Issue by frankmcsherry** [MaterializeInc/materialize#7297]
The coordinator performs optimization of views (and source view things) with the indexes it has on hand when it receives the view creation command. These indexes may not reflect the indexes that will be available when the view is actually rendered, and indeed the view may be rendered multiple times as parts of multiple materializations. I believe there are parts of optimization that are "sticky" with respect to arrangements, in that bad information about what to use sticks around (I think we don't remove or re-consider `ArrangeBy` stages), which means that optimization with incorrect indexes may be permanently harmful.

**Comment by frankmcsherry** [comment]
I believe this happens now, but pinging @asenac for confirmation.

**Comment by asenac** [comment]
IIUC arrangements are only introduced by `JoinImplementation` transform that is not part of the list of optimizations performed on views (in `Optimizer::for_view`). `JoinImplementation` is performed now only on dataflows after view inlining.

**Comment by frankmcsherry** [comment]
I'm going to leave this open for now, with the goal of structurally preventing the use of arrangements (e.g. versions of `fn optimize()` with and without arrangements provided. For example, we do still create `for_view()` optimizations and then pass in the current arrangements, so anyone could introduce a dependence on current arrangements before dataflow rendering.

**Comment by frankmcsherry** [comment]
This has been fixed, in that the `optimize` call no longer takes arrangements as arguments. Arrangements are provided directly to the `transform` method, which is invoked only through whole-dataflow optimization.
