### ISSUE TITLE
failed to create postgres source

### ISSUE THREAD

**Issue by hseagle** [MaterializeInc/materialize#7298]
Unable to create postgres source according to instruction in the official document

I did the same test against version 0.8.0 and 0.8.1 and got the same errors messages.  

The following is how to reproduce it.

Execute the statement by using psql or mzcli

```sql
CREATE MATERIALIZED SOURCE "pg_demo_source" FROM POSTGRES CONNECTION 'host=localhost port=5432 user=wso2sp dbname=postgres password=wso2' PUBLICATION 'mz_source';
```
The output is always like this 

```
Expected HOST, found identifier "connection"
```

**Comment by awang** [comment]
Hi! Would you mind replacing CONNECTION with HOST and seeing if it works? Ie

`CREATE MATERIALIZED SOURCE "pg_demo_source" FROM POSTGRES HOST 'host=localhost port=5432 user=wso2sp dbname=postgres password=wso2' PUBLICATION 'mz_source';`

Apologies for the trouble you encountered, this is a temporary issue where our docs syntax doesn't match the current release -- HOST is correct for now, but we are changing it to CONNECTION in our next release (0.8.2, scheduled to go out next week).

**Comment by hseagle** [comment]
It works after using host instead of connection. thank you for your support
