### ISSUE TITLE
dataflow: add dataflow rendering to EXPLAIN plans

### ISSUE THREAD

**Issue by mjibson** [MaterializeInc/materialize#7301]
If there's a view with an index on a column, a point select on that column will be significantly faster. But an EXPLAIN will not surface the use of the index. We should add this information to EXPLAIN. In this case looking at the rendered dataflow will show index instead of scan. Users will be able to self-serve improve their queries better with this information.

### Update: 2022/02/08 

We added a rudimentary version of this in https://github.com/MaterializeInc/materialize/pull/8515. We were holding off documenting it, because it's very verbose and we expected to follow-up sooner. We didn't follow-up, it's still verbose, but came in handy a few times already, so I'm proposing the following sub-tasks:

- [ ] Rename `explain physical plan` to `explain dataflow plan`
- [ ] Add docs under `docs/sql/explain` following the existing structure (sections "Reading ...", "Operators in", and an extra warning that it's experimental)

There were various discussions in the pats to take a holistic look at `explain` output, but we didn't find a proper owner (cc @JLDLaughlin @andrioni). I think it's fine to do the above minimal things even if we expect things to change in the future.

**Comment by uce** [comment]
This is mostly ready on the dataflow side but requires adding the SQL commands and pretty printing (we probably need to discuss what we actually want in there).

**Comment by uce** [comment]
The initial work has been done, but we'll keep this open to scope out the follow-up tasks.

**Comment by aalexandrov** [comment]
@uce: can you put labels to the areas where the outstanding tasks fall? I've tentatively added `A-optimization` here but I'm not sure whether there is something more to be done there.

**Comment by aalexandrov** [comment]
A variant of this was done in #13137.
