### ISSUE TITLE
Source and Timestamp Consistency with Serializability

### ISSUE THREAD

**Issue by nmeagan11** [MaterializeInc/materialize#7323]
From #5073:

* INSERTs not persisted between restarts
* non-determinism in source reading (I think this is the "different views over the same non-materialized source can generate different timestamps"). I'm not clear on exactly how of if this breaks serializability. Maybe it's similar to inserts because things can change on restart?
* Other stuff?

**Comment by benesch** [comment]
This all got fixed in platform!
