### ISSUE TITLE
Protobuf Support for Schema Registry

### ISSUE THREAD

**Issue by nmeagan11** [MaterializeInc/materialize#7335]
Similar to using the [registry for Avro format](https://materialize.com/docs/sql/create-source/avro-kafka/#using-a-confluent-schema-registry), users want Protobuf support for SOURCE objects to use the schema registry.

**Comment by elindsey** [comment]
Some additional notes: currently the code for interacting with the schema registry is all intertwined with the avro decoding codepath (confluent schema registry didn't support non-avro schemas until ~April last year, so this was never really a concern).

This task is going to need to first un-entangle the reusable schema registry code (code to call the schema registry, possibly code for caching schemas, etc.) from the avro specific bits, then add protobuf support using that refactored piece as a building block. When refactoring we should keep in mind that we'll want to add json support later on as well.

**Comment by JLDLaughlin** [comment]
Protobuf + Confluent Schema Registry for sources is merged! The docs will be added shortly with https://github.com/MaterializeInc/materialize/pull/8155.

Embarrassingly, I'm just noticing that this issue mentions sinks as well. Are those also a P2, @nmeagan11 ?

**Comment by benesch** [comment]
I suspect that schema references are going to be quite common when using Protobuf—most Protobuf schemas in the wild that I've make heavy use of `import`s. We should test that schema references at least produce a reasonable error message if they reference other protobuf schemas. The well-known `Timestamp` message might be a good one to start with, since that one is _super_ common.

**Comment by nmeagan11** [comment]
Sinks are not P2 at the moment. I will update this issue specifically for sources, and create a new issue for sinks.

**Comment by JLDLaughlin** [comment]
Protobuf + CSR are complete for sources!
