### ISSUE TITLE
optimizer: difficult to understand row counts from seemingly simple plan

### ISSUE THREAD

**Issue by mjibson** [MaterializeInc/materialize#7371]
The following views on a 100k line file produce a [plan](https://materialize.com/memory-visualization/#eJytmm+LIzcSxr+Kcd7sgAOtarVa2pBALiQQwnEh5N3OEpyxZzOc117sWbgl7Hc/qW2VHrX+JZNeWOhp/dzqqnrUKpX053p3el6/Xu+e3p23H/5Y/Xl/XE3/7o+Xj79f792vHw4fL8/7829ablbifu2o30RP2nzlLsjI8XYxdP6C/IX86gorc7sYO39B/sIz4+gvPKyFv/CMVvbic3jNqX+5+vKb1fWVVm8uz58O+6/v17vt5Y/97n791v/SXCn3vqs3h+3v+4OlLvvj80p6yrYNf+9ZQ1eipn48ReUe7RM8JcvPsk+4vZeqvJcK7zW3UQhhBHYbXs60UH6qEg3UAh7tW2jP6FD2jhqYqkRNsTFl70xtN2oUFUogVTVhDKhsoZJR1UIVo7pssm27UbprPFCzwvRchwlKjM4tQoqN0XNjkGI7tC67W7MdpjKUggmmZa0JaEuChiVo5hJMUNahqejQsA5Na1CZmxj7rqvLbAI8OrcIqZ6p4nia2jw1Fr8jrs1TlfEEJtStnYAbKuoSnACP1gfVBHi0qMOpzVPz8ZQ8UHuU6jKbAI8WP+5Tm6eK42lq85QqB4XYDiqOp8iElrXEaN+SYM8S7OuDagI8WtFhzzrs6zPVBHi0JbOeZSbnFgEl2RhZGU+S7bA5QdHdnC90sjKegglJ7jE3QTI6tCQ4sAST/CJBWYdDRYcD63CoT1IT4NGWzAaWmZpbBJRiY1RlPCm2QxWTpanNU5XxFExQLWtVQFsSVCzBRvowAR6t6HBkHY71SWoCPNqS2cgyG+cWIcXG6Mp40myH7svu1myHroynYIJuWasD2pKgZgk20ocJ8GhFh4Z1aFqTlGExmpbMDMvMFDO/qe1Kia48nlybp6jobtfmqcp4YhMmqmaCAzzakKDgJEO00gfB6YNtKJssBFONScoBHm3IzAEeLWZ+U5unyuPJtd0oKq5ApjZPlccTmEAtaymgDQkKTjJEK30QnD5YhZRN7lmHfWOScoBHWzLrWWZ9OfNzbZ4qjyfXdqNkcQUytXmqMp6CCbJlrQxoS4KcZIhW+iA4fRCyokPJOhwak5QDPNqS2cAyG8qZn2vzVGU8DWzHUK53iIHtUJXxFExo1C8mwKMtCXKSIVrpg+D0QaiKDhXrcGxMUg7waEtmI8ssqVEgxcYk5Qmk2I6xvAIRI9uhK+MpmNCoX0yAR1sS5CRDtNIHwemD0BUdatahbk1SmsVoWjIzLLOkRoEUG5OUJ5BiO0x5BSIM22Eq4wlMaFnLi3/qGhIkTjKolT4Qpw/UlXXo2jzVmKQccENFQ2YO8Gg58yMuT1BSnkCK7UgqE1r1Ua9sS1KdmJFgSstqLgIQJVI0mkgHlJMNStOIOdozOtcjAcUVdJqPKxpU1wE5MjlX25xksSWVCrCaixSUFCmQYiuS+gTJDnvlGgUlNYoZGSxJydgSrgSQTJImE5GccFCSSsxJlqScSxLiEnZJZDJfxY9jRcpEZzHIKktLFYHiKgWlVQqg2IakQCEG7JRrFJTWKIa8GSkYmTEEcC5Dt4wCkFWY5BExyFkEJbsgIETFQkw2QOKnsQz/ytaP22GrPY3nXUpTh8BNm1GeK68MibOLv0ol+Wv0bjw4kqJEzIUNv3LaB0+rUVy8IF2xQIceCxUlvyF59R4OxB+Pu/3/Xn00erN6893p8PH98VV3t1ndLsXd27vVq6fd69X0szv7tNsjQBTfn89/5ykDPAUc/u/th8CMgcHRi8zQAQNi+fZiez3sH56fTscAE8CyBYOdQ+ENB3xDU2BMYHBMIqMEMDAcvz2ft8d3+9erX08ffgp0v7nNpqvz/uF03l3srzfXgD8+WUN2m4fT4XT++myv3I3rX/frLx4f7ZTQPT6GziCAcR/DZtW97PHTKLg9fmw4WYEDVezAH48/H7YP+4CCH7Fs+d3p+LB93h/tf2ZH8CcuKdDnI8QXFxT2eZfT4WkXPU8Bqxs2jTrAuiBbDbLFDc98wDUtFnDcMo37kEsEHPdas87R4EksiWYCrsGPWBLNBdyAP3G5gj43PTBDPeAGPk+mJWIDIjaFr4Bh9cabqbmAO2KhgMfbsXEf/T8PeLyPm3GOA8DwsRJw1wyoqQXctQcWl0LB5+4+MLIWcNcObF3EDgBYFzrXgcGN2nzAqVss4LjVG/dBSwSc6vOmA8BwVQ04gR+xlJsLOIE/++w06u4D09cD3vfAtkTcg4j7bC7g7gNjWgHvzWIBx23kqA8plgg47j9nnSPBk5gQZgIuwY+Y9eUCLsGf+ezP3QeG6gEf4GvQSP4cALAqdA7qxQ3mfMAHvVjAcYs66kN1SwRc1dNoBwTDlawGXIEflaoHXIE/VXYadfcDM0sCk4CP8DUYWyIeQcTjkO98BPXiIjEf8HFcLOC40oz7MEsEHPfNs87R4EndVwOuwY96qAdcgz91YRrV8NmfJYFJwA18DUxLxAZEbLJLBHcfGNUKuFGLBRy31uM+9AIBj/bkc86xwF2AqRZw2wyorAbctgObn0YFJIFilgTOAy4gCYw23bM2CQFwdong7gMzNAJuiaUCHm3bx32MSwQc9/vzzgFPkqgGnMCP1NcDTuBPyk+jApJAMUsCk4BDEhht6Gdt6kHEfX6JYO8DI1sB7+ViAccjAXEfaomA9/UihQOC4bKrBlyCHyXVAy7BnzI/jQpIAsUsCUwCDklgdFgga5MEEQ/5JYK9D0yj0uaIxQI+5CttrmGJgA/1IoUDwPBapc01B1RVK22uHdj8NCogCRSqWmlz7cC2RKxAxGN+iWDvA9OotDlisYCP+Uqba1gi4GOjSCFG8ORYq7S55oDqaqXNtQNbmEYhCRS6Wmlz7cC2RKxBxDq/RLD3A2NalTZLLBZwU6i02YYlAm4aRQphwJOmWmkTBvxo6pU2AZVL6vLTKEESSF290kaQBEYHKHI2WQDg/BLB3g+MaFXaLLFUwKMjGHEf9isyHYx4WRcPMnTRKFQQ1C2jYxxp0AmqltHpjEzQCaqXRPmplCARJKpX2wgSwehgRtYmGgDOLxPsfWBa1TZLbK6HHF4WkH7LffWFYptt2FxPXLywCxW6aNQqCEqX0fmQTMyhcBkd+8jFHAqYJPOzKUEuSLJecCPIBaNDH1mbJOhY5lcK9j4wrYKbJTbTIYoXfnh77moolNtsw2Y6z/HPe2gUKwhql9HZk0zEoXIZHSrJRRwqmJTfvnb3A6PqFTeCZDA6VZK1SYGKVX6pYO8DUyiC2Qb7tb2s9ofth8t+F36AGeEPh+0zPhiywuiMyX/++/35HChw+1ivbdAIfsfi4A+n8/ubQN/vj88/7T+Fn8CAG9Nv2L8+vQmnKN6+DT9zWwcvVh0nFKTrqT1B1Y90PrW394FJK2QzE77cn8+n8yX8eom1LmEi+Mv+HWpMW1eZmTTcEZjP68//B9C9p/w=) with 1.7 million records. There's a number of full record copies that loop back into a topk operator. The explain plans attached below don't help out all in understanding what's going on here. I would have expected the `killmail_results_root` index to be relatively simple since file sources are insert only so it should just need to hold onto the top 100 records and discard the rest? Is there a way to understand this better? Input file attached.

```
CREATE SOURCE zk_bytes_json
	FROM FILE '/home/mjibson/scratch/fit-mz/out.json'
	WITH (tail=true)
	FORMAT BYTES;

CREATE MATERIALIZED VIEW fits AS
	SELECT
		(data->'ID')::INT AS killmail,
		data
	FROM
		(SELECT CONVERT_FROM(data, 'utf8')::JSONB data FROM zk_bytes_json);
CREATE INDEX ON fits(killmail);

CREATE MATERIALIZED VIEW killmail_results_root AS
	SELECT
		data
	FROM
		fits
	ORDER BY
		killmail DESC
	LIMIT
		100;
```

```
materialize=> explain plan for view killmail_results_root;
                   Optimized Plan                   
----------------------------------------------------
 %0 =                                              +
 | Get materialize.public.fits (u2)                +
 | TopK group=() order=(#0 desc) limit=100 offset=0+
 | Project (#1)                                    +
 
(1 row)

Time: 0.489 ms
materialize=> explain plan for view fits;
                            Optimized Plan                            
----------------------------------------------------------------------
 Source materialize.public.zk_bytes_json (u1):                       +
 | Filter                                                            +
 | Project (#0, #1)                                                  +
                                                                     +
 Query:                                                              +
 %0 =                                                                +
 | Get materialize.public.zk_bytes_json (u1)                         +
 | Map strtojsonb(convert_from(#0, "utf8")), jsonbtoi32((#2 -> "ID"))+
 | Project (#3, #2)                                                  +
 
(1 row)

Time: 0.669 ms
```

[out.json.gz](https://github.com/MaterializeInc/materialize/files/6795945/out.json.gz)

**Comment by mjibson** [comment]
Doing some more experiments and it seems that for each 100k lines added, it results in an additional 5G memory use. The memory use makes it so I can't use it in production, which would have more than 6 million lines. But the problem is I now don't know what to do to improve this, and I suspect our users are in a similar situation.

**Comment by mjibson** [comment]
Ergh I just realized that the data has much more information in it than it needs, so that's certainly part of the reason here. Ignore that, but I still think the linked plan is really weird

**Comment by ruchirK** [comment]
So I think the memory usage part of this is because we currently only get monotonicity information from sources and not from indexes as well. In this case, since `killmail_results_root` is getting from `fits` - it doesn't know the data is append only and doesn't retract it. 

If that's correct then I think if you unmaterialized fits this would improve memory usage because now `killmail_results_root` would get from the source directly

(definitely not saying that's an actual fix - just a workaround)

**Comment by mjibson** [comment]
Making `fits` unmaterialized increased memory use. I also assume that the huge pile of topk arrangements is the big tree we create to split up max computation?  How complicated is it to pass monotonicity down to indexes?

**Comment by mjibson** [comment]
I also tried

```
CREATE SOURCE zk_bytes_json
	FROM FILE '/home/mjibson/scratch/fit-mz/out.json'
	WITH (tail=true)
	FORMAT BYTES;

CREATE MATERIALIZED VIEW killmail_results_root AS
	SELECT
		data
	FROM
		(SELECT CONVERT_FROM(data, 'utf8')::JSONB data FROM zk_bytes_json)
	ORDER BY
		(data->'ID')::INT DESC
	LIMIT
		100;
```

to see if depending on the source directly would improve things, but it quadrupled memory use -_-. We need to expose this (monotonicity) to users somehow, and probably more stuff too I don't know exists.

If I could imagine a world it'd be: I type `explain web plan for view v` and it spits out a shareable URL that has the memory visualizer but with bytes in addition to row counts, merged with the explain plan. Each explain/dataflow node is clickable and links to a public docs page describing what the operator does, it's performance and memory characteristics, and if it's a bad node or not, and how to make it a good node instead (maybe describing when the optimizer can't do this itself). Bad nodes are like cross join, or, in this example, topk with possible row retractions.

Here's my argument: when I look at a explain plan for an oltp database, I know "look for full table scans" as a first step. No one knows what to look for in materialize, and we need to teach them (and ourselves) what bad things exist, and how to fix them.

**Comment by mjibson** [comment]
Did some sleuthing and I think the monotonicity problem is happening because there's a Local dataflow component in a Get which always returns false for is_monotonic:

```
GET Global(User(1)), sources: {User(1)}
inner is_monotonic true: "%0 =\n| Get materialize.public.zk_bytes_json (u1)\n"
inner is_monotonic true: "%0 =\n| Get materialize.public.zk_bytes_json (u1)\n| Map strtojsonb(convert_from(#0, \"utf8\")), jsonbtoi32((#2 -> \"ID\"))\n"
GET Local(LocalId(0)), sources: {User(1)}
inner is_monotonic false: "%0 =\n| Get %? (l0)\n"
	topk monotonic: false
```

Any clue what's creating that local thing? My best guess is `(data->'ID')`. SQL:

```
CREATE SOURCE zk_bytes_json
        FROM FILE '/home/mjibson/scratch/fittin.gs-mz/short.json'
        WITH (tail=true)
        FORMAT BYTES;

CREATE VIEW to_json AS
	SELECT CONVERT_FROM(data, 'utf8')::JSONB data FROM zk_bytes_json;

CREATE VIEW fits AS
        SELECT
                (data->'ID')::INT AS killmail,
                data
        FROM
                to_json;

CREATE VIEW killmail_root AS
        SELECT
                killmail
        FROM
                fits
        ORDER BY
                killmail DESC
        LIMIT
                100;

CREATE MATERIALIZED VIEW killmail_results_root AS
        SELECT
                fits.data
        FROM
                killmail_root, fits
        WHERE
                killmail_root.killmail = fits.killmail;

```

**Comment by mjibson** [comment]
Here's the `Plan::Let` that I think is causing this. I have zero experience in this part of the code but it kinda looks like the json bytes -> string conversion might be the culprit here?

```
id: LocalId(0)

value: Get { id: Global(User(1)), mfp: MapFilterProject { expressions: [CallUnary { func: CastStringToJsonb, expr: CallBinary { func: ConvertFrom, expr1: Column(0), expr2: Literal(Ok(Row{[String("utf8")]}), ColumnType { scalar_type: String, nullable: false }) } }, CallUnary { func: CastJsonbToInt32, expr: CallBinary { func: JsonbGetString { stringify: false }, expr1: Column(2), expr2: Literal(Ok(Row{[String("ID")]}), ColumnType { scalar_type: String, nullable: false }) } }], predicates: [], projection: [0, 1, 2, 3], input_arity: 2 } }

body: Join { inputs: [ArrangeBy { input: Mfp { input: TopK { input: Get { id: Local(LocalId(0)), mfp: MapFilterProject { expressions: [], predicates: [], projection: [0, 1, 2, 3], input_arity: 4 } }, top_k_plan: Basic(BasicTopKPlan { group_key: [], order_key: [ColumnOrder { column: 3, desc: true }], limit: Some(100), offset: 0, arity: 4 }) }, mfp: MapFilterProject { expressions: [], predicates: [(4, CallUnary { func: Not, expr: CallUnary { func: IsNull, expr: Column(3) } })], projection: [0, 1, 2, 3], input_arity: 4 } }, keys: [[Column(3)]] }, Get { id: Local(LocalId(0)), mfp: MapFilterProject { expressions: [], predicates: [(4, CallUnary { func: Not, expr: CallUnary { func: IsNull, expr: Column(3) } })], projection: [0, 1, 2, 3], input_arity: 4 } }], plan: Linear(LinearJoinPlan { source_relation: 1, initial_closure: None, stage_plans: [LinearStagePlan { lookup_relation: 0, stream_key: [Column(3)], lookup_key: [Column(3)], closure: JoinClosure { ready_equivalences: [], before: SafeMfpPlan { mfp: MapFilterProject { expressions: [], predicates: [], projection: [2], input_arity: 8 } } } }], final_closure: None }) }
```

**Comment by frankmcsherry** [comment]
Does #7980 fix this for you @mjibson? (No rush to determine, but wanted to hand the baton back).

**Comment by mjibson** [comment]
I think it did fix it? Memory went from 17g to 10g and mem viz reports 8.2M records down to 3.6M. Thanks!

**Comment by mjibson** [comment]
I still want an easier way to figure this out though. I'm in support of more explain plans all around.
