### ISSUE TITLE
Always emit timestamp information in kafka sinks

### ISSUE THREAD

**Issue by ruchirK** [MaterializeInc/materialize#7384]
Currently, the kafka sink implementation only emits inline `timestamp` information about changes when `consistency_topic` is specified. This can be confusing for users as now the `consistency_topic` option _both_ causes writes to a consistency topic and causes the sink to emit timestamps when often users just want one of those two things to happen.

This also brings the behavior more in line with TAIL which always emits timestamps and optionally emits progress info.

cc: @umanwizard @aljoscha

**Comment by aljoscha** [comment]
Seems legit :+1:

**Comment by frankmcsherry** [comment]
We should probably document and commit to some sort of sink representation. It seems like this has the potential to be as much a back-compat issue as e.g. catalog representation (asking users to re-write a 1TB topic because we wrote weird stuff into it seems harder than reloading a catalog).

**Comment by aljoscha** [comment]
After thinking some more: emitting the timestamp could clash with existing fields that have the same name, we have the same problem for TAIL. We could try and only emit what users explicitly ask for, and make it easy to reify the timestamp and other internal fields we might have. `mz_logical_timestamp()` doesn't work for this right now because it cannot be used in static/write queries.

**Comment by ruchirK** [comment]
We don't need a separate field for kafka DBZ sinks because we can use the inline Debezium transaction metadata struct to contain timestamp info (but if we wanted a separate field I think we should do what TAIL does and call it `mz_timestamp` and mark that field name in the docs as reserved).

**Comment by bkirwi** [comment]
#14678 is planning to introduce a `mz-timestamp` header in the kafka records that are written to the sink, which replaces the current `transaction` field.

I understand that some formats, like debezium, may still want the transaction field -- if so, we should add that back in an envelope-specific way. (To avoid the risk of conflict aljoscha mentions above.)

**Comment by dseisun-materialize** [comment]
@bkirwi doing some backlog grooming. This still an issue?

**Comment by benesch** [comment]
This got fixed in the transition to platform.
