### ISSUE TITLE
apd: POW/EXP eturns NaN/Infinity rather than overflow for certain arguments

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#7393]
### What version of Materialize are you using?

```
materialized v0.8.3-dev (c462d82de)
```

### What was the issue?

Postgres returns an overflow error but we return NaN

### Is the issue reproducible? If so, please provide reproduction instructions.
```
materialize=> SELECT POW ('-2'::DECIMAL, 2111176704);
 pow 
-----
 NaN
(1 row)

```
contrast with:

```
pstoev=# SELECT POW ('-2'::DECIMAL, 2111176704);
ERROR:  value overflows numeric format
```

**Comment by philip-stoev** [comment]
EXP also has a related problem . I am mentioning here in order to avoid opening yet another fringe ticket. In Mz:
```
materialize=> SELECT EXP ( 1867 );
   exp    
----------
 Infinity
(1 row)
```

in Postgres:
```
pstoev=#  SELECT EXP ( 1867 );
ERROR:  value out of range: overflow
```

**Comment by sploiselle** [comment]
`SELECT EXP ( 1867 );` winds up calling `UnaryFunc::Exp`, which uses `f64`s. Another signal that we need to solve #5275. Will wind up closing this issue with that problem unsolved, given that there's another issue tracking the work.
