### ISSUE TITLE
apd: possibly garbage digit at end of the result when adding DOUBLE to APD

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#7394]
### What version of Materialize are you using?

```
 v0.8.3-dev (c462d82de)
```

### What was the issue?

This is a weird one which may merit some investigation:

```
materialize=> SELECT '1'::DOUBLE PRECISION + '+4.1'::DECIMAL;
      ?column?      
--------------------
 5.1000000000000005
(1 row)
```

I understand that the result of this operation is a floating point number and they are not exact but:

- postgresql and MySQL both return the naively-expected result of ```5.1``` out of this calculation
- In Mz, ```SELECT '1'::DOUBLE PRECISION + '+4.1'::DOUBLE PRECISION;```  returns ```5.1``` too
- according to https://www.exploringbinary.com/floating-point-converter/, 5.1 is encoded as ```5.0999999999999996447286321199499070644378662109375``` so I am not sure where the trailing ```000000000000005``` comes from, even though it is in the same position within the fractional part where the hm, accuracy? epsilon? of the floating-point representation kicks in.

**Comment by philip-stoev** [comment]
Here is another example:

```
materialize=>  SELECT '-5501696.1 '::DOUBLE PRECISION *'+2.3 '::DECIMAL;
      ?column?       
---------------------
 -12653901.030000001
(1 row)

materialize=>  SELECT '-550169.1 '::DOUBLE PRECISION *'+2.3 '::DECIMAL;
      ?column?       
---------------------
 -1265388.9300000002
(1 row)

materialize=>  SELECT '-55016.1 '::DOUBLE PRECISION *'+2.3 '::DECIMAL;
      ?column?       
---------------------
 -126537.03000000001
(1 row)

materialize=>  SELECT '-5501.1 '::DOUBLE PRECISION *'+2.3 '::DECIMAL;
      ?column?       
---------------------
 -12652.530000000002
(1 row)

materialize=>  SELECT '-550.1 '::DOUBLE PRECISION *'+2.3 '::DECIMAL;
      ?column?       
---------------------
 -1265.2300000000002
(1 row)

materialize=>  SELECT '-55.1 '::DOUBLE PRECISION *'+2.3 '::DECIMAL;
      ?column?       
---------------------
 -126.73000000000002
(1 row)
```

In Mz, all those numbers are slightly above the "correct" answer. In postgres, they are mostly either exact or slightly below:

```
pstoev=#  SELECT '-5501696.1 '::DOUBLE PRECISION *'+2.3 '::DECIMAL;
      ?column?       
---------------------
 -12653901.029999997
(1 row)

pstoev=#  SELECT '-550169.1 '::DOUBLE PRECISION *'+2.3 '::DECIMAL;
  ?column?   
-------------
 -1265388.93
(1 row)

pstoev=#  SELECT '-55016.1 '::DOUBLE PRECISION *'+2.3 '::DECIMAL;
      ?column?       
---------------------
 -126537.02999999998
(1 row)

pstoev=#  SELECT '-5501.1 '::DOUBLE PRECISION *'+2.3 '::DECIMAL;
 ?column?  
-----------
 -12652.53
(1 row)

pstoev=#  SELECT '-550.1 '::DOUBLE PRECISION *'+2.3 '::DECIMAL;
 ?column? 
----------
 -1265.23
(1 row)

pstoev=#  SELECT '-55.1 '::DOUBLE PRECISION *'+2.3 '::DECIMAL;
      ?column?       
---------------------
 -126.72999999999999
(1 row)

pstoev=#  SELECT '-5.1 '::DOUBLE PRECISION *'+2.3 '::DECIMAL;
      ?column?       
---------------------
 -11.729999999999999
(1 row)
```

**Comment by sploiselle** [comment]
This is sadly just a problem inherent in our `apd` to `f32` conversion in the library, which can be most clearly seen here:

```
materialize=> SELECT 2.3::float;
      ?column?
--------------------
 2.3000000000000003
```

The library doesn't include a native conversion to floats, so we have to do some [funny math on the coefficient units](https://github.com/MaterializeInc/rust-dec/blob/9b150defe10777c74d01140b96635d522400b68a/dec/src/decimal.rs#L730-L771). Given that floats are already imprecise, I didn't think the amount of error was too dramatic, but if it poses a concern, we could always launder the values through strings for a probably-more-accurate conversion.

**Comment by elindsey** [comment]
Closing this since it should've been fixed by 7425 (not sure why it didn't close automatically on merge)
