### ISSUE TITLE
Expressions with OR are not lifted, always evaluated after the join

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#7409]
### What version of Materialize are you using?

```
v0.8.3-dev (9195d2307)
```

### What was the issue?

For this query:

```
SELECT * FROM t1, t2
WHERE t1.f1 = 27
OR t1.f2 <= 1995
AND t1.f3 = t2.f3;
```

Postgres is capable of cooking up the following plan:

```
 Nested Loop  (cost=0.00..62.02 rows=1850 width=32)
   Join Filter: ((t1.f1 = 27) OR ((t1.f2 <= 1995) AND (t1.f3 = t2.f3)))
   ->  Seq Scan on t1  (cost=0.00..1.15 rows=1 width=16)
         Filter: ((f1 = 27) OR (f2 <= 1995))
   ->  Seq Scan on t2  (cost=0.00..28.50 rows=1850 width=16)
```

In other words, the WHERE clause is partially evaluated when scanning t1, even if that would let records through that would not match the complete WHERE clause (false positives). This reduces the size of the relation before it is fed into the join.

The complete WHERE clause is then evaluated over the product of the join, removing the false positives.

Materialize on the other hand evaluates the WHERE clause only after the join, which is now a cross join:

```
 %0 =                                               +
 | Get materialize.public.t1 (u83)                  +
 | ArrangeBy ()                                     +
                                                    +
 %1 =                                               +
 | Get materialize.public.t2 (u85)                  +
                                                    +
 %2 =                                               +
 | Join %0 %1                                       +
 | | implementation = Differential %1 %0.()         +
 | | demand = (#0..#5)                              +
 | Filter (((#2 = #5) && (#1 <= 1995)) || (#0 = 27))+
```

### Is the issue reproducible? If so, please provide reproduction instructions.

```
DROP TABLE t1 CASCADE;
DROP TABLE t2 CASCADE;
CREATE TABLE t1 (f1 INTEGER,f2 INTEGER, f3 TIMESTAMP);
INSERT INTO t1 VALUES (1),(2),(3),(4),(5),(6),(7),(8),(9),(10);
CREATE TABLE t2 (f1 INTEGER,f2 INTEGER, f3 TIMESTAMP);

ANALYZE t1;
ANALYZE t2;

EXPLAIN SELECT * FROM t1, t2
WHERE t1.f1 = 27
OR t1.f2 <= 1995
AND t1.f3 = t2.f3;
```

**Comment by philip-stoev** [comment]
@asenac reports that the EXPLAIN may be misleading and the filters may still be applied prior to the join. How can we make that visible?

I think something is still off since adding ```OR``` to the RQG grammar is a sure-fire way to start generating queries that take forever to complete (while still being fast in Postgres).

**Comment by frankmcsherry** [comment]
The LIR contains the results of predicate pushdown into join evaluation. Predicates will be pushed as close to the join inputs as they can be, but there is no provision for creativity about alternate evaluation strategies for predicates. If they can be moved closer to a source, they will be.

A cross join looks correct as the plan, in that whenever `t1.f1 = 27` is true all rows from `t2` match and must be produced with that row of `t1`. There is an alternate plan one can use where logical expressions are lowered, and .. in essence you separately determine collections that match the two `OR`'d conditions. For example, 
```
SELECT * FROM t1, t2
WHERE t1.f1 = 27
OR t1.f2 <= 1995
AND t1.f3 = t2.f3;
```
could become
```
--- First case; cross join but on reduced input.
SELECT * FROM t1, t2
WHERE t1.f1 = 27
UNION ALL
--- Second case, excluding results from first case. Inner join, on more data.
SELECT * FROM t1, t2
WHERE t1.f1 != 27
AND t1.f2 <= 1995
AND t1.f3 = t2.f3;
```

**Comment by uce** [comment]
This probably has the same root cause as #7682.

**Comment by ggevay** [comment]
After https://github.com/MaterializeInc/materialize/issues/14501, we have the predicate before the join the same way as Postgres:
```
materialize=> explain optimized plan as text for SELECT * FROM t1, t2
WHERE t1.f1 = 27
OR t1.f2 <= 1995
AND t1.f3 = t2.f3;
                    Optimized Plan                    
------------------------------------------------------
 Explained Query                                     +
   Filter ((#0 = 27) OR ((#2 = #5) AND (#1 <= 1995)))+
     CrossJoin type=differential                     +
       ArrangeBy keys=[[]]                           +
         Filter ((#0 = 27) OR (#1 <= 1995))          +
           Get materialize.public.t1                 +
       Get materialize.public.t2                     +
                                                     +
 Source materialize.public.t1                        +
   filter=(((#0 = 27) OR (#1 <= 1995)))              +
 Source materialize.public.t2                        +
```
