### ISSUE TITLE
Deployment guidelines

### ISSUE THREAD

**Issue by cuongdo** [MaterializeInc/materialize#742]
Regardless of whether we target on-prem deployments or cloud deployments, we need to develop a set of recommendations for how to deploy our software. Such guidelines may contain recommended EC2 instance types, minimum RAM, and swap sizing.

cc @sploiselle

**Comment by msudberg** [comment]
@krishmanoh2 - Do we have any rough guidelines on this I can adapt, or should we just meet to talk about it?

**Comment by krishmanoh2** [comment]
At this time, we have some rough guidelines. We can meet.

**Comment by morsapaes** [comment]
Closing, now that we're running on cloud! Related: we'll include a sizing guide in the documentation to support users with provisioning for sources and sinks.
