### ISSUE TITLE
[optimization] `UpdateLet` not called at the end of optimization

### ISSUE THREAD

**Issue by frankmcsherry** [MaterializeInc/materialize#7436]
The `UpdateLet` transform is the one that corrects any type information found at `Let` bindings to the corresponding `Get` locations. In the past, when these two were out of sync we would crash at the dataflow render stage, as reported in #7048. We no longer crash, because rendering ignores the type, but we are still reporting `MirScalarExpr`s that have incongruous types in the `Let` and `Get` expressions, and possibly missing optimization opportunities.

**Comment by uce** [comment]
Subsumed by #8888.
