### ISSUE TITLE
Create a way to control how timestamps are advanced

### ISSUE THREAD

**Issue by rjnn** [MaterializeInc/materialize#746]
Currently, the last message in a Kafka topic does not show up in the results of a view, due to Materialize waiting for the timestamp to be confirmed 'closed', which today is only advanced when Materialize sees a message with a superior timestamp, thus advancing the inferior timestamp through the system.

We need more flexibility around adding support for additional protocols for denoting which messages advance which timestamps, as well as some manual levers to move the timestamps forward in the absence of messages.

The first part of this is to simply designate a manual message such as `FLUSH SOURCE`, which declares all messages known to the system to be 'closed'.

The second part of this is to designate a flushing strategy upon source creation. The current (and perhaps default) strategy could be named `FLUSH ON INCREMENT`. Another strategy, one supported by CockroachDB and Flink, is to have explicit in-band flush messages with a `watermark` field (cockroachdb calls this `resolved`) which indicates what the timestamp is that is currently considered flushed. You could call this `FLUSH ON WATERMARK`.

I'm not particularly attached to my syntax scheme; I conjecture that @frankmcsherry is a better namer than me here.

I'd say that part one of this (explicit `FLUSH SOURCE` statements) is perhaps more important than sorting out the details of the latter.

**Comment by cuongdo** [comment]
We already have a way to create how timestamps are advanced, thanks to BYO timestamps.
