### ISSUE TITLE
Exactly-once sink retention

### ISSUE THREAD

**Issue by awang** [MaterializeInc/materialize#7491]
Now that [exactly-once sinks](https://github.com/MaterializeInc/materialize/issues/7073) are available, it might be interesting to allow `consistency_topic` (soon to be renamed) support keeping data for a fixed retention period or length.  

originally we were thinking along the lines of key based compaction since we only need the latest entry for bootstrapping, but we don’t think that actually works with the consistency topic format (separate begin/end records). so size based retention is probably the thing

**Comment by elindsey** [comment]
Closing, this worked with some small changes @aljoscha made in https://github.com/MaterializeInc/materialize/pull/7502
