### ISSUE TITLE
rt dbz sources should consult txn metadata topics if present

### ISSUE THREAD

**Issue by elindsey** [MaterializeInc/materialize#7537]
This is somewhat related to https://github.com/MaterializeInc/materialize/issues/1979

Debezium now has sidecar metadata topics that allow determining the transactional boundaries of the main data topic. When present, we should ingest these such that all records in the same txn are timestamped with the same value. We do this today for byo, but not for rt.

Note that https://github.com/MaterializeInc/materialize/issues/6296 is also somewhat relevant as we may not properly consume the metadata topic today.

**Comment by aljoscha** [comment]
I think we need to start treating real-time timestamping and BYO as orthogonal. What RT timestamping does is map from `FromTime` to `ToTime` (using the lingo from Franks reclocking doc). In case we only have RT timestamping and no BYO, using Kafka as an example, `FromTime` is `(partition_id, offset)` and `ToTime` is `Timestamp`, that is, we're mapping from Kafka offsets (including the partition) to real time.

We should think of BYO as an additional mapping step in front of RT timestamping: BYO maps from `(partition_id, offset)` to `TransactionId` (this doesn't exist like that today) and then RT timestamping can map from `TransactionId` to `Timestamp`. Or we just keep the `TransactionId` as timestamp but that's not super useful when trying to join with other sources.

**Comment by elindsey** [comment]
Fixed in Chae's recent dbz transaction metadata work

**Comment by james-johnston-thumbtack** [comment]
Did this feature actually land?  The documentation at https://materialize.com/docs/ingest-data/cdc-postgres-kafka-debezium/#transaction-support still says:

> Debezium provides [transaction metadata](https://debezium.io/documentation/reference/connectors/postgresql.html#postgresql-transaction-metadata) that can be used to preserve transactional boundaries downstream. We are working on using this topic to support transaction-aware processing in Materialize ([#7537](https://github.com/MaterializeInc/materialize/issues/7537))!

I couldn't locate other obvious Materialize documentation suggesting how to use this feature.  In particular, I would think I would need to have a way to configure Materialize with the name of the transaction topic.
