### ISSUE TITLE
Debezium sequence numbers are wrong

### ISSUE THREAD

**Issue by umanwizard** [MaterializeInc/materialize#7557]
There are various examples where we can't use the sequence numbers for deduplication, because they are the same on different records.

For example:

```
INSERT INTO brennan2 VALUES (1, 2), (3, 4);
```

Result in Kafka:

```
{"before":null,"after":{"tpch.public.brennan2.Value":{"a":{"int":1},"b":{"int":2}}},"source":{"version":"1.6.1.Final","connector":"postgresql","name":"tpch","ts_ms":1627401465527,"snapshot":{"string":"false"},"db":"tpch","sequence":{"string":"[\"54604320\",\"54604320\"]"},"schema":"public","table":"brennan2","txId":{"long":86302},"lsn":{"long":54604320},"xmin":null},"op":"c","ts_ms":{"long":1627401465687},"transaction":null}
{"before":null,"after":{"tpch.public.brennan2.Value":{"a":{"int":3},"b":{"int":4}}},"source":{"version":"1.6.1.Final","connector":"postgresql","name":"tpch","ts_ms":1627401465527,"snapshot":{"string":"false"},"db":"tpch","sequence":{"string":"[\"54604320\",\"54604320\"]"},"schema":"public","table":"brennan2","txId":{"long":86302},"lsn":{"long":54604384},"xmin":null},"op":"c","ts_ms":{"long":1627401465688},"transaction":null}
```

Note that this has produced multiple rows with the same sequence numbers: `"[\"54604320\",\"54604320\"]"`. Once we update Materialize to exclusively use the sequence numbers for deduplication, it will incorrectly drop the second row.

**Comment by umanwizard** [comment]
We can still disambiguate these by looking at the `lsn` field, which is apparently what we do now in Materialize (take the first coordinate from `sequence`, and then use `lsn` as the second coordinate):

```
        } else if pg_any {
            let last_commit_lsn = match sequence {
                Some(sequence) => sequence.get(0).cloned().expect("lastCommitLsn must exist"),
                None => None,
            };
            let lsn = lsn.ok_or_else(|| DecodeError::Custom("no lsn".to_string()))? as usize;
            RowCoordinates::Postgres {
                last_commit_lsn,
                lsn,
                total_order: None,
            }
```

So this is why things aren't obviously broken in Materialize. It seems like, for example, in the second case the sequence number should have been `"[\"54604320\",\"54604320\"]"`, rather than `"[\"54604320\",\"54604384\"]".

**Comment by petrosagg** [comment]
What is the purpose of `RowCoordinate`? If it's just to deduplicate then we can just use the pair `(transaction_id, total_order)`. If we also need to have the correct order then `(last_commit_lsn, total_order)` should totally order and all rows

**Comment by umanwizard** [comment]
Yes, it's true that we can use `(last_commit_lsn, total_order)`, but the idea of the sequence field in Debezium is that we should be able to just use `total_order`.

**Comment by petrosagg** [comment]
What is the purpose of RowCoordinate though? The nice thing about `(transaction_id, total_order)` is that it's independent of the debezium connector, it works just as well for MySQL

**Comment by umanwizard** [comment]
Assigning to Petros who is working on DBZ stuff.

Feel free to close if this is a dupe of something else.

**Comment by benesch** [comment]
This looks fixed to me? See [DBZ-3801](https://issues.redhat.com/browse/DBZ-3801) and https://github.com/debezium/debezium/pull/2563.
