### ISSUE TITLE
Upgrade dbt version support

### ISSUE THREAD

**Issue by awang** [MaterializeInc/materialize#7580]
A couple users of `dbt-materialize`  requested support for more recent versions of dbt -- I believe it is currently pinned to 18, whereas one user is looking for support for v19 and another asked about what will happen once v20 is released.

**Comment by benesch** [comment]
We should make it someone's responsibility to stay on top of these. Maybe with Slack notifications? But this took <5m, and undoubtedly we have spent many more minutes than that talking about doing this instead of just doing it.

**Comment by elindsey** [comment]
> whereas one user is looking for support for v19

The merged PR skipped 19 and put us on 20. @awang is that user you mentioned okay with 20, or do we need to go back and cut a version against 19 as well?

**Comment by awang** [comment]
I will check!

**Comment by awang** [comment]
Update: we checked with the users that requested this and all have replied that they're okay bypassing 19 and going straight to 20.

**Comment by nmeagan11** [comment]
This is done, closing.
