### ISSUE TITLE
Railroad diagram for format_spec is too wide

### ISSUE THREAD

**Issue by uce** [MaterializeInc/materialize#7663]
<img width="1772" alt="Screen Shot 2021-08-03 at 12 54 53" src="https://user-images.githubusercontent.com/1756620/128004106-4ffecbed-0a2d-4387-b17d-35f0c8e9b389.png">

-- https://materialize.com/docs/sql/create-source/avro-kafka/#format_spec

**Comment by morsapaes** [comment]
Good to have this tracked. AFAIK, this will be covered in our website overhaul soon-ish!
