### ISSUE TITLE
Add hint to sink diagnostics views

### ISSUE THREAD

**Issue by uce** [MaterializeInc/materialize#7691]
In case of loss of responsiveness it is not possible to run the diagnostics queries; sinking the diagnostics queries to an external system can allow users to still gather some data that might help with debugging.

**Comment by krishmanoh2** [comment]
Sinking to a file on disk would make it easier - especially if in CSV format.

**Comment by benesch** [comment]
See also https://github.com/MaterializeInc/materialize/issues/1573.

**Comment by antiguru** [comment]
Not relevant anymore.
