### ISSUE TITLE
Arranged data should de-duplicate key values

### ISSUE THREAD

**Issue by frankmcsherry** [MaterializeInc/materialize#778]
When we arrange data by key, we are selecting out some columns from the row. At the moment, we retain the entire row, including what are redundant copies of the key values. This need not be deeply problematic, but it is wasteful in the cases where there is not a substantial amount of additional data in the row (the relative waste is high).

I believe that from the key column identifiers, the key values, and the row values not in the key, we should be able to reconstruct the row itself. We should check that, but if so we should probably do that rather than repeat redundant data.

**Comment by frankmcsherry** [comment]
This was closed based on some work removing duplication in arrangements created as part of join processing, but I think the larger issue still exists for other arrangements. For example, I see a 2x memory difference between
```
create index foo for bar (column1)
```
and 
```
create default index for bar
```
The difference is that the former has a relatively small key, and so the duplication between the key and row is small. The latter duplicates the entire row in the key, and ends up using substantially more memory.

I don't think #220 is directly aimed at reducing this redundancy (if I'm wrong, we can re-close).

**Comment by uce** [comment]
Related to #6672. This issue is probably the more general one and we may want to close one of the two (depending on which one we pick up first).

**Comment by frankmcsherry** [comment]
We think this has been completed!
