### ISSUE TITLE
compile error when installing materialized v0.9.0 using homebrew

### ISSUE THREAD

**Issue by danhhz** [MaterializeInc/materialize#7812]
I did a `brew upgrade materialized`, which picked up and tried to install v0.9.0 and got the attached compile errors. Without looking too closely, it seems like stuff that's been stabilized in the newest version of rust, so maybe that just needs to be bumped in the brew formula somehow.

https://gist.github.com/danhhz/5041792da0c249ed8666bfec7eb1eb90

Initially assigning to @benesch (who did the latest release) for triage.

**Comment by danhhz** [comment]
Important to note for original issue: brew seems to be installing from source because I'm on an m1 mac

**Comment by danhhz** [comment]
Ended up diagnosing this with Nikhil. This is failing because we're apparently not allowed to specify which version of rust we get from homebrew and at the moment, it's at 1.53.0 while we require 1.54.0.

Nikhil suggested that we adopt the policy of holding off on bumping our min required rust version until homebrew is updated, which is potentially not too onerous given that they're pretty aggressive about it.

We also should ideally build an arm64 bottle when releasing.

Nikhil, I'll leave the decision on whether this issue is actionable or if it should be closed up to you.

**Comment by benesch** [comment]
Whew, ok, going to call this resolved. The one-liner not working is tracked by #7815. (There might be some bike shedding there, in which case this turns into a wontfix, which I guess is fine.) The build from source failing should be resolved by #7817, which added some text about not bumping to a version of Rust not supported by Homebrew. And providing bottles for M1 Macs is already tracked by #5917. That doesn't seem likely to happen anytime soon, unfortunately, but the work item is there.

Thanks for finding all this, Dan!
