### ISSUE TITLE
Timestamper: Kafka BYO sources are polled with timeout

### ISSUE THREAD

**Issue by antiguru** [MaterializeInc/materialize#7871]
### What version of Materialize are you using?

Current main: https://github.com/MaterializeInc/materialize/commit/4eaedbea4780244f5bbf595d0b50bb0270e079e1

### How did you install Materialize?

* Built from source

### What was the issue?

The timestamper queries a Kafka queue for Kafka BYO sources for timestamp updates. It poss the Kafka with a timeout of 60 milliseconds for each BYO Kafka source. This potentially causes multiple 60 millisecond delays, once for each source that doesn't have timestamp updates.

Relevant code: https://github.com/MaterializeInc/materialize/blob/e7867c93e21c05c24f1abef0132ccafe22123ace/src/coord/src/timestamp.rs#L235

Determine how to avoid this, for example by passing a zero duration, which turns the call into a non-blocking call.

### Is the issue reproducible? If so, please provide reproduction instructions.

Not reproduced, but observed from code.

**Comment by elindsey** [comment]
BYO is gone
