### ISSUE TITLE
Source reclocking

### ISSUE THREAD

**Issue by elindsey** [MaterializeInc/materialize#7873]
Today some sources present their natural timeline and some sources reclock into system time. Ideally this would be more uniform - eg. the majority of sources present logging data in their natural timeline (such as Kafka offsets or Postgres LSNs being visible in system table), but are reclocked into system time for downstream use.

Previous design doc touching on this https://github.com/MaterializeInc/materialize/pull/7422#event-5057751110

**Comment by elindsey** [comment]
Semi-blocked on https://github.com/MaterializeInc/materialize/issues/7417

**Comment by nmeagan11** [comment]
Should this be closed in favor of https://github.com/MaterializeInc/materialize/issues/11218?
