### ISSUE TITLE
soc2 review check

### ISSUE THREAD

**Issue by umanwizard** [MaterializeInc/materialize#7881]
please and thank you!

https://github.com/MaterializeInc/materialize/pull/7876
https://github.com/MaterializeInc/materialize/pull/7829
https://github.com/MaterializeInc/materialize/pull/7828
https://github.com/MaterializeInc/materialize/pull/7780
https://github.com/MaterializeInc/materialize/pull/7769

**Comment by benesch** [comment]
Signed off in #7880.
