### ISSUE TITLE
coord: handle_terminate doesn't clear txn_reads

### ISSUE THREAD

**Issue by mjibson** [MaterializeInc/materialize#7916]
This will cause any client that doesn't explicitly end it's transaction to block read tables from being compacted (until that connection id happens to be reused and a read txn is started on it).

**Comment by mjibson** [comment]
This shows up in release mode with the telemetry query because it uses its own coord_client and calls terminate.

**Comment by ruchirK** [comment]
idea: we should store the `std::time::Instant` each read txn object is created and every call to `maintence` we iterate through all pending read_txns and assert_or_log! for all read txns that have lived longer than .. 2 minutes / 5 minutes?

**Comment by mjibson** [comment]
Yes, that is an additional mitigation strategy. Might mess up some users who genuinely want a very long query. But would prevent users who accidentally leave their txns open without closing them. A tradeoff where we'd need to provide some knobs.
