### ISSUE TITLE
persistence: "persistence error: invalid meta at key: META" fatal error on startup

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#7924]
### What version of Materialize are you using?

```
ed424518a
```

### What was the issue?

After loading some data and then killing and restarting Mz a couple of times, it no longer starts up:

```
2021-08-19T10:42:00.735792Z  INFO materialized: booting server
materialized v0.9.1-dev (ed424518a)
OpenSSL 1.1.1k  25 Mar 2021
librdkafka v1.6.1
invoked as: MZ_DEV=1 target/release/materialized --experimental --persistent-user-tables --log-file stderr
os: Ubuntu 20.04 (focal) [64-bit]
cpus: 16 logical, 8 physical, 8 useful
cpu0: AMD Ryzen 7 3700X 8-Core Processor 2179MHz
memory: 67438780KB total, 3758265KB used
swap: 34325131KB total, 132580KB used    
materialized: persistence error: invalid meta at key: META
```
and that is it.

### Is the issue reproducible? If so, please provide reproduction instructions.

1. Load the DDL and INSERT statements from the archive gh7924.zip](https://github.com/MaterializeInc/materialize/files/7013835/gh7924.zip)

2. Once done. use Ctrl+C to kill Mz and then restart it, killing it repeatedly during statup. Shortly you will see the error above.
I have also attached the `mzdata` directory.

**Comment by ruchirK** [comment]
As dan and I discussed yesterday, we need to prevent partial writes to meta. I'll wire up the write / fsync / rename / fsync directory thing for writes to overwriteable keys.

**Comment by ruchirK** [comment]
looks like dan beat me to it #7935

**Comment by danhhz** [comment]
Oh whoops! I only did that because I was looking for bugs for bug day and found this on the august milestone issue. I hadn't even seen this issue yet 😆
