### ISSUE TITLE
persistence: files belonging to multiple tables are written even when inserting in a single table

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#7928]
### What version of Materialize are you using?

```
materialized v0.9.1-dev (ed424518a)
```

### What was the issue?

Even when inserting data in a single table, strace reports that multiple files belonging to multiple tables are being written to. In the space of a couple of seconds 342 files belonging to 8 different tables were written to ,even though the workload was only inserting into one of them.

### Is the issue reproducible? If so, please provide reproduction instructions.

1. Load the following data [dbt3-s0.01.zip](https://github.com/MaterializeInc/materialize/files/7014112/dbt3-s0.01.zip)

2. While the data is loading, capture the files being opened:
```
sudo strace -f -F -p 3514508 2>&1  |  grep openat | awk -F "\"*,\"*" '{print $2}' | grep -v proc > strace
```
3. Determine the number of unique files invovled:
```
cat strace | sort | uniq -c  | wc
```

**Comment by aljoscha** [comment]
Closing this because current persist/storage architecture has moved quite a bit beyond this.

@philip-stoev Please yell at me if you'd like to keep this open.

fyi @danhhz
