### ISSUE TITLE
sql: `CREATE HEALTH CHECK`

### ISSUE THREAD

**Issue by benesch** [MaterializeInc/materialize#7968]
The definition of whether Materialize is "caught up" is very fuzzy and varies from customer to customer. To date we've only found two definitions that make sense for all customers:

  * `materialized` is on and ready to accept connections, but may or may not be caught up. This is ascertained by `GET /status` returning 200 OK and already exists.
  * `materialized` is ready to serve linearizable reads—i.e, the frontiers of all the indexes are equal to or beyond the frontiers of all the indexes when `materialized` last ran.  The _definition_ here is the easy part. We're still very far away from having the right timestamping + persistence to actually provide this as a health check.

So, in the interim, I've been kicking around the idea of allowing users to specify their own health checks in SQL! Consider something like this:

```sql
CREATE HEALTH CHECK caught_up AS SELECT ... FROM mz_metrics WHERE ... ;
```

A health check is defined by a SQL query that returns exactly one row with one boolean column that indicates whether the server is healthy or not. To query a health check, users make a HTTP GET request to `/health/<name>`, which runs the specified health check query and returns 200 OK if the query returns true, 503 if the query returns false, and 500 if the query errors or produces the wrong number of rows.

Making the health check available over HTTP makes it easy to integrate with load balancers, Kubernetes, and other similar orchestration tools. And since the endpoint only returns a single bit of information, it'd be safe to expose via our new unauthenticated HTTP listener.

A bit funky, perhaps, but we think it could serve us well on Cloud.

cc @antifuchs @alex-hunt-materialize

**Comment by alex-hunt-materialize** [comment]
Adding some more context to this, I see this being very useful for (at least) the following cloud operations:
1. Canary deployments. We can check to see that materialized is actually functional at the application level, not just that the pod is running at the K8S level.
2. Exposing health status in the UI. The user won't need to stand up a complex monitoring system just to see that materialized is functional. Our current health display only shows the broad K8S pod status, which says almost nothing about materialized.
3. Qualitative assessments of certain materialized features/behavior. We can see how long it takes for a materialized instance to become usable after a restart, which can give valuable data for our eventual persistence and HA features. This is especially useful for scheduling forced maintenance windows. We don't want to schedule them every week if it takes the instance several days to become usable.

**Comment by benesch** [comment]
I ran this past @rjnn today and there was a certain reluctance to add this feature. An alternative to consider is pushing harder on getting that notion of linearizability baked in. I do think the ideal is a built-in readiness endpoint that tells you when your sources are at least as up to date as the last time you ran Materialize.

**Comment by chaas** [comment]
Closing this as obsolete with the current materialize cloud infra
