### ISSUE TITLE
Basic smoke test for Debezium and MSSQL

### ISSUE THREAD

**Issue by benesch** [MaterializeInc/materialize#7995]
We have customers who are using Debezium and MSSQL with Materialize. This deserves some test coverage ASAP.

Note that SQL Server is nicely packaged in Docker these days (https://hub.docker.com/_/microsoft-mssql-server), though we'll need to buy a license.

Assigning @nmeagan11 and @umanwizard for triage.

**Comment by philip-stoev** [comment]
I believe we are covered for testing purposes:

> SQL Server Developer edition lets developers build any kind of application on top of SQL Server. It includes all the functionality of Enterprise edition, but is licensed for use as a development and test system, not as a production server.

So I can work on a test.

**Comment by philip-stoev** [comment]
I made significant progress on this already, so I will see it to completion.

**Comment by philip-stoev** [comment]
Closed via  #7997
