### ISSUE TITLE
Support exposing the transaction isolation level

### ISSUE THREAD

**Issue by quodlibetor** [MaterializeInc/materialize#800]
JDBC wants us to expose this, which means other things will assume that we can expose this. [The code in jdbc](https://github.com/pgjdbc/pgjdbc/blob/69edc0b8f0985465af0ba0ee258f6b2564240232/pgjdbc/src/main/java/org/postgresql/jdbc/PgConnection.java#L808-L838).

We should figure out what we want to say, and if we want to say it.

**Comment by benesch** [comment]
Fixed in #3619.
