### ISSUE TITLE
Optimization: Negate lifting

### ISSUE THREAD

**Issue by wangandi** [MaterializeInc/materialize#8029]
From https://github.com/MaterializeInc/materialize/blob/1d9bfeee802be2a888ff5a6bb9898141e4298972/test/sqllogictest/column_knowledge.slt#L464 we see
```
%2 =
| Get %0 (l0)
| Negate
| Map 123, 234
| Project (#2, #3)

%3 =
| Get %0 (l0)
| Map 123, 234
| Project (#2, #3)

%4 =
| Union %2 %3
| Map null, null
```

The %2 and %3 should be able to perfectly cancel each other out. However, our UnionBranchCancellation code is only capable of canceling out the union when the negate is the last operation of the branch:

```
%2 =
| Get %0 (l0)
| Map 123, 234
| Project (#2, #3)
| Negate

%3 =
| Get %0 (l0)
| Map 123, 234
| Project (#2, #3)

%4 =
| Union %2 %3
| Map null, null
```

We should either:
* Have a transform that lifts Negates as high as possible that runs before UnionBranchCancellation.
* Allow UnionBranchCancellation to lift negates.

Related: Negate fusion #6476

**Comment by asenac** [comment]
#8141 implements the second option, lifting Negate operators in UnionBranchCancellation, but it leads to regressions in tpch.slt and chbench.slt tests.

**Comment by wangandi** [comment]
#7864 might fix this, not by lifting the negate but by pushing down the project.

**Comment by asenac** [comment]
I just pushed a different approach to #8141 where we don't lift the Negates but use a smarter way of comparing the union branches
