### ISSUE TITLE
Consistent naming of frequency/interval parameters

### ISSUE THREAD

**Issue by antiguru** [MaterializeInc/materialize#8043]
From https://github.com/MaterializeInc/materialize/pull/7929#pullrequestreview-738375143:
> This looks great. Pre 1.0 it would be great if we could rename --introspection-frequency as well, for full naming/unit consistency (:

Materialize defines several parameters named frequency which are in reality intervals. To avoid confusion, the parameters should be named accordingly.

Example: https://github.com/MaterializeInc/materialize/blob/main/src/materialized/src/bin/materialized/main.rs#L143

cc @antifuchs

**Comment by benesch** [comment]
I've got a draft patch for this locally. I'll try to find time to clean this up and ship it.

**Comment by chaas** [comment]
This has been fixed

**Comment by benesch** [comment]
For posterity, fixed in: https://github.com/MaterializeInc/materialize/pull/14422
