### ISSUE TITLE
persistence: TEMPORARY tables are persisted to disk

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#8071]
### What version of Materialize are you using?

```
v0.9.2-dev (b32aacef2)
```

### What was the issue?

`TEMPORARY` tables are persisted to disk whereas they should not be.

### Is the issue reproducible? If so, please provide reproduction instructions.

```
materialize=> create temporary table t1 (f1 text);
CREATE TABLE
materialize=> insert into t1 values (repeat('a', 1024*1024*1024));
```

then observe a 1 Gb file in `mzdata/persist/blob`

**Comment by aljoscha** [comment]
not relevant anymore.
