### ISSUE TITLE
Kafka sources with KEY FORMAT using the confluent schema registry can be unergonomic

### ISSUE THREAD

**Issue by quodlibetor** [MaterializeInc/materialize#8113]
The Kafka source type allows specifying formats that depend on the confluent schema registry for both the key and value formats. In the case where the user is actually *using* the registry for both keys and values they must specify the same schema registry config twice:

```sql
KEY FORMAT AVRO USING CONFLUENT SCHEMA REGISTRY '..'
VALUE FORMAT AVRO USING CONFLUENT SCHEMA REGISTRY '..'
```

This is annoying. We could get rid of this and only require the schema registry to be specified once. The biggest downside to allowing specifying the schema registry config twice is that our `format_spec` would be different depending on if it is inside a KEY/VALUE format clause vs if it's inside a bare FORMAT clause.

**Comment by benesch** [comment]
This got fixed with the introduction of `CREATE CONNECTION`.
