### ISSUE TITLE
sql: allow enabling all indexes on object

### ISSUE THREAD

**Issue by sploiselle** [MaterializeInc/materialize#8120]
Breaking off from #7442, it would be nice to let users name the objects that indexes are on, rather than being forced to name the individual objects themselves in `ALTER INDEX foo SET ENABLED`, i.e.

![alter_view](https://user-images.githubusercontent.com/41181/125852405-1382cb11-6f80-46f1-af02-4b98217470a0.png)

```
alter_view
         ::= 'ALTER' ( 'VIEW' | 'SOURCE' | 'INDEX' ) name 'ENABLE' 'DATAFLOWS' 'CASCADE'? ( 'DRY' 'RUN' )?
```

There is more discussion in #7442, but the final desired syntax maybe uses `INDEX` instead of `DATAFLOW` because we don't directly expose the concept of dataflow to users (whereas indexes are meant to be the user's proxy for interacting with dataflows).

**Comment by benesch** [comment]
We ended up removing disable user indexes mode, so no longer need to do this!
