### ISSUE TITLE
Memory accounting

### ISSUE THREAD

**Issue by cuongdo** [MaterializeInc/materialize#815]
Memory is Materialize's most precious resource, or at least tied with CPU for that honor. 

Sources, dataflows, and (soon) shared indices all contribute to our memory use. If Materialize is using an unexpected amount of memory, it's currently impossible for an end user to poke around and see if a subset of views and sources should be dropped or migrated to another Materialize cluster.

We should provide a means of easily understanding what user-created objects (sources, views, indices) are contributing to memory use.

**Comment by benesch** [comment]
Fixed by #18766.
