### ISSUE TITLE
Sources/Optimization: Figure out the intended way of handling `MirRelationExpr::DeclareKeys`

### ISSUE THREAD

**Issue by wangandi** [MaterializeInc/materialize#8159]
What are the rules that the optimizer should obey when handling `MirRelationExpr::DeclareKeys`? This is an open question from the projection pushdown PR: https://github.com/MaterializeInc/materialize/pull/7864#discussion_r701290494.

Looking at the way that `DeclareKeys` is handled in other transforms has just made me more confused. For one, projections cannot be lifted out of `DeclareKeys`:
https://github.com/MaterializeInc/materialize/blob/c9224501395aa9f558d5aa315f5f919a569d4243/src/transform/src/projection_lifting.rs#L267
But mapped literals can. https://github.com/MaterializeInc/materialize/blob/c9224501395aa9f558d5aa315f5f919a569d4243/src/transform/src/map_lifting.rs#L612
Also, the particular implementation of lifting mapped literals seems wrong because `keys` could potentially refer to the literals being lifted.  

In what scenarios can `DeclareKeys` be found? If `DeclareKeys` can only be found in the contexts
`DeclareKeys{Get{id, typ}, keys}` and `DeclareKeys{Constant{rows, typ}, keys}` respectively, then we can have a optimization at the very beginning that fuses them to become `{Get{id, typ.with_keys(keys)}` and `Constant{rows, typ.with_keys(keys)}` respectively.

**Comment by uce** [comment]
@umanwizard seems like the right person to answer some of these questions or at least help to move these questions forward.

**Comment by wangandi** [comment]
`DeclareKeys` were removed in #11463
