### ISSUE TITLE
At least one input has no complete timestamps yet

### ISSUE THREAD

**Issue by thbeh** [MaterializeInc/materialize#8163]
Hi, I am testing materialized with a very simple set of data, one table consisting of point of sale (POS) and another branch table. Both the table are in Postgres. I am trying to create a materialized view of POS joining with the branch but when I try to query the materialized table I always get - _**At least one input has no complete timestamps yet error.**_ What does this error mean? Please advice.

**Comment by ruf-io** [comment]
@thbeh Sorry we missed this! 

`At least one input has no complete timestamps yet` is _almost_ always a "transient" error that indicates the materialized view you are trying to select from is still being initialized, and running the exact same query a few moments later should fix it.

However, we have seen other edge cases where, for example, total lack of upstream events has also triggered the error.

Does waiting a bit longer after creating the materialization and re-running the query solve the problem? If not, can you share a bit more about your `CREATE SOURCE` and `CREATE MATERIALIZED VIEW` syntax and your schema?

**Comment by thbeh** [comment]
Waiting a bit does help solve the issue and also at times the first query gave the issue but the 2nd timed query normally does the trick. 

You have a fabulous product here and a see a potential missing piece between data engineering and consumption.
