### ISSUE TITLE
Error when creating kafka sink with avro schema on 0.9.2

### ISSUE THREAD

**Issue by aleduc** [MaterializeInc/materialize#8201]
### What version of Materialize are you using?
materialize: 0.9.2
schema-registry: confluentinc/cp-schema-registry:5.2.2

### How did you install Materialize?
* [x] Docker image

### What was the issue?
After updating from 0.9.0 to 0.9.2, we can't start materialize from scratch because of this error.
`SQL Error [XX000]: ERROR: error publishing kafka schemas for sink: unable to publish value schema to registry in kafka sink: server error 422: Unrecognized field: schemaType`

### Is the issue reproducible? If so, please provide reproduction instructions.
1.  Any matview
 `create materialized view test as
   select 1 as id,
             'text' as value;`
2. And sink 
`CREATE SINK test_sink
FROM test
INTO KAFKA BROKER 'brokers' TOPIC 'test_sink'
key (id)
with (partition_count=16,replication_factor=3)
FORMAT AVRO USING
CONFLUENT SCHEMA REGISTRY 'schema';`

**Comment by umanwizard** [comment]
@aleduc thanks for the report -- is there anything that seems relevant in the schema registry logs?

**Comment by aleduc** [comment]
@umanwizard I've double-checked logs in schema-registry and in materialize
1. In the registry I didn't find out anything, but we have ERROR log lvl only.
1. In materialize was empty too.(only start information message)

But I found out that topics in Kafka were created, after running the test script. 
In the prod version, we have pre-created topics and use the option `reuse_topic`, therefore I didn't notice it from the very beginning

**Comment by elindsey** [comment]
@aleduc would you mind curling the schema types endpoint on your registry? https://docs.confluent.io/platform/current/schema-registry/develop/api.html#get--schemas-types-

I suspect 5.2.2 predates schema type support, but would like to verify. 🙂

**Comment by umanwizard** [comment]
Should be fixed by #8204, but leaving this open until the fixed build actually gets deployed

**Comment by aleduc** [comment]
@elindsey Yes, you are right I got a 404 on this request(. We have to think about updating not only materialize

**Comment by umanwizard** [comment]
@aleduc I have just released 0.9.3, which should fix this issue. Please check and let us know.

Sorry about the disruption.

**Comment by aleduc** [comment]
@umanwizard great thanks for your work, we've successfully deployed the new version.  I'm surprised how fast you fixed it.
