### ISSUE TITLE
docs: SQL transaction statements + semantics

### ISSUE THREAD

**Issue by sploiselle** [MaterializeInc/materialize#8205]
We support transactions (i.e. `BEGIN; some statements; COMMIT;`), but lack docs for the semantics (i.e. write only or read only) and the syntax.

**Comment by mjibson** [comment]
Hard agree! My plan for the last many months has been to spend a while documenting all of this (including things like linearizability and timestamp selection) once we nail down how those will work. Do you think it makes sense to have separate pages, one documenting transaction semantics, and another describing uh time stuff? While they are related, they are also not exactly the same thing.

**Comment by sploiselle** [comment]
I like to think of each docs page as a kind of "MVP" to use the feature it describes, with pointers to additional assets that cover adjacent topics in depth. So I think we might be able to get away with more hand-wavy/light "time stuff" documentation in the v0 of the transaction semantics docs, but I think you're right that we will definitely need more full-fledged "time stuff" docs––hopefully that can also provide reference for things like `AS OF`.
