### ISSUE TITLE
`time` column from `mz_metric_histograms` not readable:  not of expected type ColumnType

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#8252]
### What version of Materialize are you using?

```
v0.9.4-dev (42c8871dc) 
```

### What was the issue?

It is not possible to select the `time` column from the `mz_metric_histograms` table once it has data in it.

### Is the issue reproducible? If so, please provide reproduction instructions.

```
materialize=> select count(*) from mz_metric_histograms;
 count 
-------
    34
(1 row)

materialize=> select time from mz_metric_histograms;
ERROR:  internal error: column 0 is not of expected type ColumnType { scalar_type: Timestamp, nullable: false }: TimestampTz(2021-09-13T08:51:14.913Z)
```

**Comment by philip-stoev** [comment]
The only query that references this table in our test suite does not reference all the columns:

./testdrive/prometheus.td:> SELECT COUNT(type) FROM mz_metric_histograms LEFT JOIN mz_metrics_meta USING (metric) WHERE type IS NULL;

**Comment by danhhz** [comment]
Given that this table is included in the background system tables test, please coordinate with persistence when the fix goes out.

Concretely, we'll want to bump the "ENCODING_VERSION" as part of the PR that fixes it, which is a failsafe we have to wipe the system tables test data. To minimize customer and cloud team disruption, we try to limit doing that to at most one release per month and our next window is the first week in January, so depending on what priority we assign this fix, we may want to hold merging it until then.

**Comment by chaas** [comment]
This table no longer exists, closing as obsolete
