### ISSUE TITLE
Can't use 'order' field inside records

### ISSUE THREAD

**Issue by maqroll** [MaterializeInc/materialize#8278]
### What version of Materialize are you using?

```
0.9.0
```

### How did you install Materialize?

 APT package

### What was the issue?

Materialize fails to parse queries involving a field named `order` inside a record (keyword collision?).

```
materialize=> select (payload).order.order_id from v;
ERROR:  Expected an identifier or a '*' after '.', found ORDER
LINE 1: select (payload).order.order_id from v;
                         ^

materialize=> select (payload).unknown from v;
ERROR:  field unknown not found in data type record(metadata: record(order_management_system: text?),order: record(order_id: text,store_id: text,parent_id: text?,external_id: text?,customer:...
```

**Comment by benesch** [comment]
Ah, yep, I'm afraid that's expected. See https://materialize.com/docs/sql/identifiers/#keyword-collision. As mentioned in that doc, the workaround is to wrap the word `order` in double quotes:

```sql
select (payload)."order".order_id from v;
```

**Comment by maqroll** [comment]
Thanks!!

**Comment by aljoscha** [comment]
As a workaround, could you use `"order"` to refer to the `order` field?

**Comment by benesch** [comment]
@elindsey noticed that PostgreSQL actually accepts this syntax without quotes, so reopening. I'll send a PR to fix.
