### ISSUE TITLE
sql-parser: can't select record field if name is keyword

### ISSUE THREAD

**Issue by JLDLaughlin** [MaterializeInc/materialize#8338]
### What version of Materialize are you using?

```
$ materialized -v
0.9.4
```

### How did you install Materialize?

* [ ] Docker image
* [ ] Linux release tarball
* [ ] APT package
* [ ] macOS release tarball
* [ ] Homebrew tap
* [X] Built from source
* [ ] Materialize Cloud

### What was the issue?

Working on [emitting protobuf data as records](https://github.com/MaterializeInc/materialize/pull/8317), I found that I'm unable to access fields within records if the field name belongs to our [keywords list](https://github.com/MaterializeInc/materialize/blob/main/src/sql-parser/src/keywords.txt).

### Is the issue reproducible? If so, please provide reproduction instructions.

Yes! I found this by trying to fix errors in the `billing-demo` caused by my PR. But, here's a quick way to reproduce locally:

```
# This is from our docs, and works.
materialize=> SELECT record, (record).f2 FROM (SELECT ROW(1, 2) AS record);
 record | f2
--------+----
 (1,2)  |  2
(1 row)

# We error correctly if field not found.
materialize=> SELECT record, (record).notkeyword FROM (SELECT ROW(1, 2) AS record);
ERROR:  field notkeyword not found in data type record(f1: integer,f2: integer)

# We error incorrectly for any keywords
materialize=> SELECT record, (record).seconds FROM (SELECT ROW(1, 2) AS record);
ERROR:  Expected an identifier or a '*' after '.', found SECONDS
LINE 1: SELECT record, (record).seconds FROM (SELECT ROW(1, 2) AS re...
                                                       ^
```

**Comment by JLDLaughlin** [comment]
Ah! So I can do this to fix my issue:
```
materialize=>  select (interval_start)."seconds" from billing_raw_data;
 seconds
---------
(0 rows)
```

This still seems potentially broken? But not an immediate priority.

**Comment by elindsey** [comment]
Odd, I thought this would be fixed by https://github.com/MaterializeInc/materialize/pull/8280

**Comment by benesch** [comment]
I just tried this on v0.9.3 and v0.9.4. I can reproduce the error exactly in v0.9.3, but not in v0.9.4 (and also not on the latest master). I know @JLDLaughlin's issue report claims this issue was present in v0.9.4 but I think that's probably a reporting error! Gonna close this out.
