### ISSUE TITLE
Flaky test in transactions.slt

### ISSUE THREAD

**Issue by uce** [MaterializeInc/materialize#8351]
The build in https://buildkite.com/materialize/tests/builds/21713 failed with:

```
  | OutputFailure:test/sqllogictest/transactions.slt:286
  | expected: Values(["db error: ERROR: transactions can only reference nearby relations; \"materialize.other.t\" referenced here, but only the following are available: \"materialize.public.t\", \"materialize.public.t5727\", \"materialize.public.t5727_primary_idx\", \"materialize.public.t_primary_idx\""])
  | actually: Values(["db error: ERROR: transactions can only reference nearby relations; \"materialize.other.t_primary_idx\" referenced here, but only the following are available: \"materialize.public.t\", \"materialize.public.t5727\", \"materialize.public.t5727_primary_idx\", \"materialize.public.t_primary_idx\""])
  | actual raw: []
```

Repeatedly running the test locally on 885bee003 is flaky:

```
$ cargo run --bin sqllogictest -- test/sqllogictest/transactions.slt
    Finished dev [unoptimized + debuginfo] target(s) in 0.16s
     Running `target/debug/sqllogictest test/sqllogictest/transactions.slt`
==> test/sqllogictest/transactions.slt
    FAIL: output-failure=2 success=69 total=71
FAIL: output-failure=2 success=69 total=71

$ cargo run --bin sqllogictest -- test/sqllogictest/transactions.slt
    Finished dev [unoptimized + debuginfo] target(s) in 0.16s
     Running `target/debug/sqllogictest test/sqllogictest/transactions.slt`
==> test/sqllogictest/transactions.slt
PASS: success=71 total=71
```

---

I'm marking this as a flaky test as I don't know what the underlying issue could be. Please feel free to update the issue title. 

cc @mjibson

**Comment by philip-stoev** [comment]
@mjibson if this is moved out ot SLT and into testdrive, then testdrive only requires a portion of the error message to match, that is, the test can be:

```
! SELECT ...
transactions can only reference nearby relations
```

and it will pass regardless of what the entire message was.

**Comment by benesch** [comment]
> @mjibson if this is moved out ot SLT and into testdrive, then testdrive only requires a portion of the error message to match, that is, the test can be:
> 
> ```
> ! SELECT ...
> transactions can only reference nearby relations
> ```
> 
> and it will pass regardless of what the entire message was.

SLT expected error messages are regexes, so it's possible to do without moving to testdrive. In this case though I think we should just squash the nondeterminism in the error message. I sent #8355 to do that.
