### ISSUE TITLE
Add optional namespace to CREATE SINK so generated Avro schemas will work with avrogen without modification

### ISSUE THREAD

**Issue by tgitchel** [MaterializeInc/materialize#8352]
### What version of Materialize are you using?

materialized v0.9.4 (29d003cae)

### How did you install Materialize?

* [ ] Docker image
* [ ] Linux release tarball
* [X] APT package
* [ ] macOS release tarball
* [ ] Homebrew tap
* [ ] Built from source
* [ ] Materialize Cloud

### What was the issue?

If you create a new SINK using Avro schemas, Materialize will create new schemas in schema registry.  These schemas do not contain the "namespace" property, so if you use these to create a class in your language of choice using the avrogen tool, it will fail.  You must manually add the namespace property to create the class, and then manually remove it from the generated class so that the comparison upon deserialization of sink messages will not fail.

### Is the issue reproducible? If so, please provide reproduction instructions.

Create a sink similar to this:

```
CREATE SINK SecurityMasterSink
FROM SecurityMasterUpdates
INTO KAFKA BROKER 'localhost:9092' topic 'SecurityMasterSink'
KEY ("DataSourceId", "ExternalId")
WITH (
reuse_topic = true,
client_id = 'Materialize',
security_protocol = 'SASL_PLAINTEXT',
sasl_mechanisms = 'scram-sha-256',
sasl_username = 'rpadmin',
sasl_password = 'RedPandaAdmin')
FORMAT AVRO USING CONFLUENT SCHEMA REGISTRY 'http://localhost:8081'
ENVELOPE UPSERT;
```

Check the schema registry for the schema.  The key from above looks like this:

```
"{
    "fields": [
        {
            "name": "DataSourceId",
            "type": "int"
        },
        {
            "name": "ExternalId",
            "type": "string"
        }
    ],
    "name": "row",
    "type": "record"
}
```

If there was a new WITH property similar to:

```
avro_classname = 'company.dept.messages.classname',
```

It would override the name and add the namespace to the schema to produce and output like this:

```
{
    "type": "record",
    "name": "classname-key",
    "namespace": "company.dept.messages",
    "fields": [
        {
            "name": "DataSourceId",
            "type": "int"
        },
        {
            "name": "ExternalId",
            "type": "string"
        }
    ]
}
```

Also notice that the fields normally would come last.

Could also separate class name and namespace for more flexibility.

```
avro_classname = 'classname',
avro_namespace = 'company.dept.messages',
```

**Comment by tgitchel** [comment]
I updated the name in the desired schema output above to include "-key" for the key schema.  The value schema name would be "classname".  Could also provide avro_keyname or similar property to specify explicit name.

**Comment by umanwizard** [comment]
@pH14 any interest in picking this one up?

**Comment by pH14** [comment]
Sure, taking a look
