### ISSUE TITLE
bootstrap reuse_topic kafka sinks in parallel

### ISSUE THREAD

**Issue by elindsey** [MaterializeInc/materialize#8356]
Kafka exactly-once sinks (EOS, ie. those created with reuse_topic) on restart need to read state from Kafka to determine the last written offsets so they know at what point to resume publishing.

That bootstrap process can take a bit of time for a single sink as the consistency topic needs to be scanned from the beginning, but there are ways to speed this up - namely by enabling Kafka compaction on the consistency topic.

A bigger problem is that currently, this process occurs synchronously, bootstrapping one EOS at a time until all have been hydrated. Thus, if bootstrap takes X seconds and there are Y reuse_topic sinks, materialize startup time ends up taking X * Y seconds. This is a particularly bad UX because it occurs during catalog bootstrap, meaning mz is not available and responsive for other work during this time.

This will require some thought and design work. Two initial strawmen to think about (neither of which I claim are ideal):
1. Keep the bootstrap within the coord, but fire off sink creation in parallel. May involve tokio threadpools to allow librdkafka to block if there isn't an async API for what we need, and could be a lot of complexity to take into the coord (an area that is already complex)
2. Push the bootstrap out of the coord and into the Kafka sink itself, modeling it within the sink's state machine. Given the librdkafka API, this would likely cause the workers to block during bootstrap, so we may only achieve `num_workers` level of parallelism. Would also need to think carefully about retries and how to surface errors back to the user.

Relevant code pointers are `coord.rs` bootstrap() fn calling into the coord's `sink_connector.rs` build_kafka().

**Comment by elindsey** [comment]
Relevant community discussion https://materializecommunity.slack.com/archives/C015KDVS7EV/p1631977290129700

**Comment by cjubb39** [comment]
Fixing #8544 (per-bootstrap sink) significantly decreased startup time so I'm going to push off this work which would likely introduce complexity without much benefit

**Comment by cjubb39** [comment]
I believe we can close this after #10094 which moves the initialization into the sink state machine itself -- which will run in parallel across workers.

The calls are made asynchronously via `tokio::spawn_blocking` so our parallelization is limited to the size of this threadpool -- which should be acceptable

**Comment by aljoscha** [comment]
agreed!
