### ISSUE TITLE
doc: Clarification on TOASTed value support for Postgres source

### ISSUE THREAD

**Issue by bpartridge** [MaterializeInc/materialize#8362]
From https://materialize.com/docs/sql/create-source/postgres/#restrictions-on-postgres-sources it appears TOAST columns aren't allowed regardless of whether the replica identity is FULL:

> Materialize does not support TOASTED values except in append-only tables. Practically speaking, you can include rows with TOASTED values as long as they are never updated or deleted, or you can disable TOAST on the original Postgres table. If a TOASTED column is updated, the source will enter an errored state that renders all per-table views inaccessible.

But per https://debezium.io/blog/2019/10/08/handling-unchanged-postgres-toast-values/ and https://debezium.io/documentation/reference/0.10/connectors/postgresql.html#toasted-values it seems that setting replica identity to FULL is a sufficient mitigation to allow the before-and-after of TOASTed columns to make it into the messages.

> One way, and certainly the easiest from a consumer’s perspective, is to avoid the situation in the first place. This can be achieved by using a "replica identity" of FULL for the Postgres table in question. Alternatively, the replica identity can be based on an index which comprises the TOAST-able column.

As far as I can tell, what we're worried about is the "unchanged TOAST" flag coming over the wire - which it seems in https://github.com/MaterializeInc/materialize/blob/f500d4e13f8b01d9800b2e2547faddf8d5a399b6/src/dataflow/src/source/postgres.rs#L247 is the thing that can cause us to enter the errored state? But shouldn't replica identity FULL prevent this bit from ever being set?

It appears this guidance landed in PR #7017, but is it possible that this was overly conservative? It seems counter to the guidance in the later comments in #3466 that indicated that FULL would be sufficient for Debezium.

We do a lot of runtime text processing and substring operations on large semi-frequently-updated text fields, so turning off TOAST on our production systems would be difficult - I imagine many other customers would feel the same way. But if replica identity FULL is recommended anyways, it almost seems like this might be a non-issue. Clarification on this could turn Materialize from something to consider experimenting with in the future, into a must-have part of our stack!

**Comment by petrosagg** [comment]
@bpartridge thank you for this report! I was surprised that debezium can handle these values because the replication protocol will send the "unchanged toast" placeholder even when setting `REPLICA IDENTITY FULL`.

However, after running some experiments and inspecting the traffic with Wireshark I saw that **both** the previous value AND the unchanged toast placeholder are being sent. So this has been a misunderstanding of the replication protocol on my side.

Thank you for raising this issue and nudging me into investigating it! I have fixed this issue in #8371 that will be included in the next release :)
