### ISSUE TITLE
sql-parser: update CREATE SOURCE and CREATE SINK syntaxes

### ISSUE THREAD

**Issue by JLDLaughlin** [MaterializeInc/materialize#8372]
Our current `CREATE SOURCE` and `CREATE SINK` syntaxes inherit the complexities of the external systems they connect to. For example, our current [`CREATE SINK`](https://materialize.com/docs/sql/create-sink/) syntax requires the user to provide [many Kafka-specific details](https://materialize.com/docs/sql/create-sink/#kafka-connector) that aren't directly relevant to the sink object itself. The messiness of stuffing all the relevant connector details into `CREATE [object]` syntax is not only ergonomically disappointing, it has contributed to [bugs](https://github.com/MaterializeInc/materialize/issues/8231). 

In the SQL team standup today, @benesch proposed an alternative. Users should have to create connection objects separately from their sources and sinks, and then reference those connection objects in their `CREATE` statements. For example, a sink that connects to Kafka would do something like:

```
> CREATE CONNECTION kafka_connection TO KAFKA ...;

> CREATE CONNECTION csr_connection TO CONFLUENT SCHEMA REGISTRY ...;

> CREATE SINK my_sink INTO kafka_connection USING csr_connection  ...;
```

This change will require:
1. Crafting the new connection objects. This entails creating various `CREATE CONNECTION` statements and corresponding catalog objects.
2. Updating the syntax for `CREATE SOURCE` and `SINK` to accept the new connection objects, performing any necessary syntax or AST migrations.

This will be a large change! But probably one that's better done sooner rather than later.

(@benesch, @sploiselle, and @mjibson for anything I might have missed!)

**Comment by benesch** [comment]
We're finally doing this! Superseded by #11504.
