### ISSUE TITLE
Introduce `AS OF AT LEAST <timestamp>` or equivalent

### ISSUE THREAD

**Issue by frankmcsherry** [MaterializeInc/materialize#8390]
Our `AS OF <timestamp>` modifier to `SELECT` provides the instruction that a query should be executed at a specific logical time. This can be a bit too specific for folks who want to execute a query at any available time at least `<timestamp>`, without needing to name the specific time. "The first available time at least `<timestamp>`" for example. 

Having to name a specific timestamp can be frustrating, and the best recommendation we have at the moment is to `SELECT .. AS OF ..` and respond to "data no longer available" errors with a `SELECT ..` query.

@mjibson had the take that `AS OF` could be repurposed to just mean this, which I'm personally less excited about, but if no users have bound to this yet that could be available (the term "as of" applies to e.g. as-of joins, appears in SQL specs on temporal queries, and .. either does or doesn't have some baggage attached to it).

**Comment by mjibson** [comment]
One user requested this when using a debezium envelope on a sink so that an observer of the sink's timestamps could be used in later SQL queries to ensure the data were present. That case currently isn't covered by our SQL linearizability goals (which exclude sinks from their guarantees).
