### ISSUE TITLE
sql-parser: remove buggy CREATE SINK consistency syntax

### ISSUE THREAD

**Issue by JLDLaughlin** [MaterializeInc/materialize#8411]
Our `CREATE SINK` syntax has a bug, [outlined here](https://github.com/MaterializeInc/materialize/issues/8231). We decided to [fix this bug](https://github.com/MaterializeInc/materialize/pull/8370) by parsing two different versions of the `CREATE SINK` syntax:
1. the buggy version
2. [a new, non-buggy version](https://materialize.com/docs/sql/create-sink/#sink_kafka_connector)

~~The purpose of leaving around the buggy syntax was to [avoid a syntax migration](https://materializeinc.slack.com/archives/CMHDK0DK8/p1632242364299100). Instead, we decided that we could deprecate the old syntax after X versions. This is a placeholder ticket to deprecate the buggy syntax in some number of releases in the future. (Definitely by 1.0, I'd assume!)~~

edit(aljoscha): We decided to remove the buggy syntax before M2, instead of deprecating.

**Comment by elindsey** [comment]
We should do this in M2 when we can still easily break backwards compat
