### ISSUE TITLE
protobuf: determine feature gaps in our current protobuf support

### ISSUE THREAD

**Issue by elindsey** [MaterializeInc/materialize#8413]
We have ~4 open tasks for high priority protobuf features:
* https://github.com/MaterializeInc/materialize/issues/7907
* https://github.com/MaterializeInc/materialize/issues/8297
* https://github.com/MaterializeInc/materialize/issues/8297
* https://github.com/MaterializeInc/materialize/issues/1611

Once those are complete, we should have basic protobuf support built out - meaning fundamental data types are support, importing schemas is supported, and the data presents as a Record inside of materialize. That should cover many/most of the protobuf use cases, but there are still gaps between that and full protobuf support.

This task is to investigate and understand the gaps. Following linked tasks, what else do we need to do to comfortably say we support [protobuf v3](https://developers.google.com/protocol-buffers/docs/reference/proto3-spec)?

A rough starting point of things we need to look at, from glancing through interchange/protobuf.rs:
* Groups (possibly these were deprecated in v3)
* Required
* oneof
* Maps
* Repeated/Message decode as jsonb - is that correct?
* I'm sure there are others

**Comment by benesch** [comment]
Closing as completed. While we still don't support maps or groups, we handle required, repeated, and nested fields correctly.
