### ISSUE TITLE
avro: improve schema resolution errors by logging schema ID

### ISSUE THREAD

**Issue by elindsey** [MaterializeInc/materialize#8415]
Today when a user hits a schema resolution error, they end up with a message like:
```
ERROR:  Decode error: Text: avro deserialization error: Schema resolution error: Reader field `foo` not found in writer, and has no default
```

This error message doesn't help users distinguish between what may be an issue in their environment and what may be a legitimate materialize bug. In particular, nothing in the error text will help them determine or troubleshoot issues like improper schema resolution.

The concrete thing that should be included are the identifiers of the schemas that failed to resolve. This sounds easy, but figuring out how to surface it nicely within the decoder will take a bit of work, because:
* not all schemas have IDs (depends on if we get them from csr, etc.) so deeper resolution codepaths will not still have the ID around
* not every failure will fail the full resolution - in particular, unions will do a series of resolutions on the union'd schemas and are only top level failures if none match
* resolution paths contain a lot of caching, so there'll be state hanging around

The core bit of code to consider is https://github.com/MaterializeInc/materialize/blob/main/src/avro/src/reader.rs#L589-L640

**Comment by umanwizard** [comment]
I would prefer not to have the avro crate know about schema IDs at all, because schema IDs are a confluent concept, not an Avro concept. I would much rather apply the schema IDs as extra context to the errors somewhere up the call stack from there.

**Comment by umanwizard** [comment]
It's maybe a slightly different issue, but a more fundamental change I'd recommend for this code is to track the path of the current node in the schema in order to give better error messages. "Field X.y.z has type {...} which failed to resolve against type {...}" is much better than just printing the debug impl of random rust structs like we do now.
