### ISSUE TITLE
Running AS OF NOW queries against a table incurs a metrics-scraping-interval=30s delay 

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#8425]
### What version of Materialize are you using?

```
v0.9.6-dev (f1783c5f6)
```
### What was the issue?

Issuing `SELECT ... AS OF NOW()` queries against a base table incurs an arbitrary unexplained delay that seems to be related to whether the table has values and when were they inserted.

The delay appears to be 30s or a portion thereof, and is dependent on the value of the metrics-scraping-interval setting. A setting of 1s allows the test to proceed faster, a setting of 900s makes it hang for that long.

### Is the issue reproducible? If so, please provide reproduction instructions.

```
materialize=> \timing on
Timing is on.
materialize=> DROP TABLE IF EXISTS t1 CASCADE;
DROP TABLE
Time: 17.982 ms
materialize=> CREATE TABLE t1 (f1 INTEGER);
CREATE TABLE
Time: 30.096 ms
materialize=> select * from t1 as of now();
 f1 
----
(0 rows)

Time: 19009.699 ms (00:19.010) <<<=== SLOW
materialize=> select * from t1 as of now();
 f1 
----
(0 rows)

Time: 29998.895 ms (00:29.999) <<<=== SLOW
materialize=> INSERT INTO t1 VALUES (1);
INSERT 0 1
Time: 0.438 ms
materialize=> select * from t1 as of now();
 f1 
----
  1
(1 row)

Time: 0.752 ms <<<=== FAST
materialize=> select * from t1 as of now();
 f1 
----
  1
(1 row)

Time: 29998.828 ms (00:29.999) <<<=== SLOW
materialize=> INSERT INTO t1 VALUES (2);
INSERT 0 1
Time: 0.393 ms
materialize=> select * from t1 as of now();
 f1 
----
  1
  2
(2 rows)

Time: 0.713 ms <<<=== FAST
materialize=> select * from t1 as of now();
 f1 
----
  1
  2
(2 rows)

Time: 29997.913 ms (00:29.998) <<<=== SLOW
```

**Comment by philip-stoev** [comment]
@antifuchs @antiguru FYI. Not sure who owns the metrics scraping thing.

**Comment by antiguru** [comment]
I'm inclined to say that this is working as expected, although it might be surprising to the user. We only update the timestamp of the metrics table whenever we scrape the metrics, so the `AS OF NOW` will only be fulfilled once the metrics are scraped again. This is the reason why for some tests we set the interval to faster than the default, e.g. 1s.

I'd definitely recommend adding some documentation about this behavior.

**Comment by philip-stoev** [comment]
@antiguru but why running an AS OF NOW query on some unrelated table depends on the timestamp of the metrics table?

**Comment by antiguru** [comment]
Oh, I didn't notice. I honestly can't say! Good that you caught it.

**Comment by danhhz** [comment]
Wild stab, does this still reproduce with `--disable-persistent-system-tables-test`?

**Comment by frankmcsherry** [comment]
This repros immediately for me. I did it manually, and it seems related to the amount of time until the next 30s tick, rather than e.g. 30s from the query. If I hold my breath for 20s, then query it comes back in ~10s.

I'm inclined to say it wants to head towards @mjibson for triage as it seems like it is some connection between how timestamps are picked, how `now()` is evaluated, and stuff like that.

**Comment by frankmcsherry** [comment]
These are the commands the `dataflow` layer sees, fwiw. One worker, I've suppressed the `AllowCompaction` messages:
```
COMMAND: AdvanceAllLocalInputs { advance_to: 1632504246434 }
COMMAND: Peek { id: User(9), key: None, conn_id: 1, timestamp: 1632504252338, finishing: RowSetFinishing { order_by: [], limit: None, offset: 0, project: [0] }, map_filter_project: SafeMfpPlan { mfp: MapFilterProject { expressions: [], predicates: [], projection: [0], input_arity: 1 } } }
COMMAND: Peek { id: User(9), key: None, conn_id: 1, timestamp: 1632504252338, finishing: RowSetFinishing { order_by: [], limit: None, offset: 0, project: [0] }, map_filter_project: SafeMfpPlan { mfp: MapFilterProject { expressions: [], predicates: [], projection: [0], input_arity: 1 } } }
COMMAND: Insert { id: System(4045), updates: [Update { row: Row{[String("mz_pg_sent_bytes"), String("counter"), String("total number of bytes sent to clients from pgwire")]}, timestamp: 1632504576439, diff: 1 }, Update { row: Row{[String("mz_pg_sent_rows"), String("counter"), String("total number of rows sent to clients from pgwire")]}, timestamp: 1632504576439, diff: 1 }, Update { row: Row{[String("mz_query_count"), String("counter"), String("total number of queries executed")]}, timestamp: 1632504576439, diff: 1 }, Update { row: Row{[String("mz_server_metadata_seconds"), String("gauge"), String("server metadata, value is uptime")]}, timestamp: 1632504576439, diff: 1 }] }
COMMAND: Insert { id: System(4045), updates: [Update { row: Row{[String("mz_pg_sent_bytes"), String("counter"), String("total number of bytes sent to clients from pgwire")]}, timestamp: 1632504576439, diff: 1 }, Update { row: Row{[String("mz_pg_sent_rows"), String("counter"), String("total number of rows sent to clients from pgwire")]}, timestamp: 1632504576439, diff: 1 }, Update { row: Row{[String("mz_query_count"), String("counter"), String("total number of queries executed")]}, timestamp: 1632504576439, diff: 1 }, Update { row: Row{[String("mz_server_metadata_seconds"), String("gauge"), String("server metadata, value is uptime")]}, timestamp: 1632504576439, diff: 1 }] }
COMMAND: AdvanceAllLocalInputs { advance_to: 1632504276441 }
COMMAND: AdvanceAllLocalInputs { advance_to: 1632504276441 }
```
The available input is at `1632504246434` and the peek is at `1632504252338` which is six seconds later (probably six seconds of lag between system start and me re-entering the command). But the next advanced input is `1632504276441` which is 30s later. So all tables are blocked for 30s, as they await the coordinator informing them they can advance their inputs.

**Comment by frankmcsherry** [comment]
Also weird, (ping @sploiselle) there are two identical `Peek` commands received. Not sure what is up there.

**Comment by frankmcsherry** [comment]
Anyhow, a casual read suggests that `SELECT` commands do not advance the inputs on which they depend. I'm not sure why they do not do this, but it means that they block until the next externally triggered advance happens.

**Comment by frankmcsherry** [comment]
More generally if you run with `--introspection-frequency off`, any `SELECT AS OF ..` query for a time at all in the future of the most recently advanced timestamp, e.g. `now()`, will block indefinitely until there is another table write. It just happened that the metrics table is the only one that writes without further user input.

**Comment by mjibson** [comment]
I'll take a look at this next week.
