### ISSUE TITLE
sql: support `WITH ORDINALITY`

### ISSUE THREAD

**Issue by mjibson** [MaterializeInc/materialize#8445]
Useful to preserve original order for, say, `unnest`.

https://www.postgresql.org/docs/current/functions-srf.html

**Comment by morsapaes** [comment]
This would be useful for cases like [this](https://materializecommunity.slack.com/archives/C015KDVS7EV/p1639703972312000):

"I'm trying to use `generate_subscripts` in unstable to add a column of indeces to a materialized view based off of a `jsonb` array column. So I have a view where one of the columns contains `jsonb` which happens to always be an array. I can unnest that column using `jsonb_array_elements`  but I really need to add that index number as well, and was hoping `generate_subscripts`  would do the trick. But alas:

```
materialize=> select jsonb_array_elements(results) from foo limit 2;
                             jsonb_array_elements
------------------------------------------------------------------------------
 {"title":"bar","type":"standard"}
 {"title":"baz","type":"standard"}
(2 rows)
```
```
materialize=> select generate_subscripts(results) from foo limit 2;
ERROR:  Cannot call function generate_subscripts(jsonb): arguments cannot be implicitly cast to any implementation's parameters; try providing explicit casts
```

`string_to_array`  is also not available, so I'm at a dead end here. Any ideas? In essence, I need to get an array from my `jsonb` array."
