### ISSUE TITLE
User support for SQL access to Kafka Event Headers

### ISSUE THREAD

**Issue by quodlibetor** [MaterializeInc/materialize#8446]
This is the last unspecced part of #1577. Support for the Headers portion of Kafka messages is useful to at least one user (https://github.com/MaterializeInc/materialize/issues/1577#issuecomment-928148451).

There are several possibilities for the design of how we expose Kafka headers to SQL.

* Include all headers as part of a `headers map[string => bytes]` and require users to explicitly extract and cast specific keys in downstream views.
* Provide an explicit allowlist as part of the source declaration like `INCLUDE HEADERS (key1, key2)`
* Provide an allowlist with type casting as part of the declaration `INCLUDE HEADERS (key1 as mykey int8, key2 string)`

Unexplored questions:

* Handling nullability
* Handling incorrect type casts
* Handling self-retracting envelopes

**Comment by andrioni** [comment]
The first approach has the benefit of supporting dynamically defined headers without having to redefine the source (and thus without having drop all already existing views), which seems desirable.

On not specifying type casting (or having it just as an option), it also moves potential error handling and decoding to users, which composes well with SQL: e.g. if we add an `avro_decode` function, users would be able to use it to decode Avro headers without requiring extra work on our side.

**Comment by benesch** [comment]
Closing, as Kafka sources support `INCLUDE HEADER` and `INCLUDE HEADERS` these days.
