### ISSUE TITLE
doc: dbt-materialize guide

### ISSUE THREAD

**Issue by ruf-io** [MaterializeInc/materialize#8447]
### For updates to existing documentation

**New Page:** We need a guide on maintaining your SQL in Materialize with dbt.

### For new documentation

**Reference Material:**
- Introducing Materialize and dbt https://materialize.com/introducing-dbt-materialize/
- dbt + Materialize demo: Running dbt’s jaffle_shop with Materialize
 https://materialize.com/dbt-materialize-jaffle-shop-demo/
- dbt-materialize readme https://github.com/MaterializeInc/materialize/tree/1ce733297d68d95c1261065efb76a378826d49df/misc/dbt-materialize
- materialize-dbt-utils https://github.com/MaterializeInc/materialize-dbt-utils

### Topics to cover

- What is dbt
  - Basic Info (links)
  - How it's normally used (batch context)
  - How it's used with Materialize
 - Example project [DEPENDENT ON PUBLISHING A DEMO]
 - Benefits of managing Materialize with dbt
   - Jinja, templating, modelling
   - Version-controlled SQL in GitHub
   - Testing
   - DAGs (visualizing dependencies)
   - Docs

**Comment by morsapaes** [comment]
Fixed in #8762.
