### ISSUE TITLE
doc: Ruby Materialize Cheatsheet/Guide

### ISSUE THREAD

**Issue by ruf-io** [MaterializeInc/materialize#8448]
### For updates to existing documentation

New page: Guide to interacting with Materialize from Ruby

### For new documentation

Start with the node.js guide structure. https://materialize.com/docs/guides/node-js/

Look for Ruby-standard postgres libraries and vet that they can interact with Materialize in all the required ways (especially `TAIL WITH FETCH`)

**Note:** It's probably limited usefulness to talk about Ruby without talking about Rails. But Rails opens up a lot more complexity (around connecting to Materialize from a Rails project using the multiple db connection features, and especially around creating and migrating views.). These could probably be separate guides.

**Comment by morsapaes** [comment]
Fixed in #11376.
