### ISSUE TITLE
doc: Guide/cheatsheet for Python

### ISSUE THREAD

**Issue by msudberg** [MaterializeInc/materialize#8458]
### For updates to existing documentation

New page: Guide to interacting with Materialize from Python

### For new documentation

Start with the node.js guide structure. https://materialize.com/docs/guides/node-js/

Look for Python-standard postgres libraries and vet that they can interact with Materialize in all the required ways (especially `TAIL WITH FETCH`)

**Comment by morsapaes** [comment]
Fixed in #11548.
