### ISSUE TITLE
doc: Java guide/cheatsheet

### ISSUE THREAD

**Issue by msudberg** [MaterializeInc/materialize#8459]
### For updates to existing documentation

New page: Guide to interacting with Materialize from Java

### For new documentation

Start with the node.js guide structure. https://materialize.com/docs/guides/node-js/

Look for Java-standard postgres libraries and vet that they can interact with Materialize in all the required ways (especially `TAIL WITH FETCH`)

**Comment by morsapaes** [comment]
Fixed in #11454.
