### ISSUE TITLE
doc: Add info on Materialize Cloud status

### ISSUE THREAD

**Issue by msudberg** [MaterializeInc/materialize#8460]
Add a "Materialize Cloud Status" link to the global footer for docs status.materialize.com and, on the cloud troubleshooting page, a section and note about status.materialize.com and the "subscribe to alerts" options there.

**Comment by bobbyiliev** [comment]
Closing this one as a link to the status page has already been added to the Support docs page and the footer:

<img width="1435" alt="image" src="https://user-images.githubusercontent.com/21223421/208491604-19b64821-bcab-46be-b0e7-54b5559e5467.png">
cc @morsapaes
