### ISSUE TITLE
individual tables compacted on different schedules, causing possible transaction inconsistency post-restart

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#8516]
### What version of Materialize are you using?

```
8b6bff298e247974128a7c225bb66182745e3067
```

### What was the issue?

We allow transactions to span multiple INSERT statements. This allows data to be inserted into multiple tables within the same transaction and all the inserts made will share the same timestamp.

However, upon restart, the inserts for some, **but not all** of the tables that participated in a transaction would be compacted and will start appearing under a new timestamp. Therefore, if before the restart both tables had records at timestamp X, after restart only one table has records at that timestamp.

### Is the issue reproducible? If so, please provide reproduction instructions.

1. We start this this setup:
```
> CREATE TABLE persistent_user_table1_for_sink (f1 INTEGER);

> CREATE TABLE persistent_user_table2_for_sink (f1 INTEGER);

> BEGIN

> INSERT INTO persistent_user_table1_for_sink VALUES (1);

> INSERT INTO persistent_user_table2_for_sink VALUES (1);

> COMMIT

> CREATE SINK persistent_user_table1_sink FROM persistent_user_table1_for_sink
  INTO KAFKA BROKER '${testdrive.kafka-addr}' TOPIC 'persistent-user-table1-sink-${testdrive.seed}'
  WITH (consistency_topic = 'persistent-user-table1-sink-consistency')
  FORMAT AVRO
  USING CONFLUENT SCHEMA REGISTRY '${testdrive.schema-registry-url}';

> CREATE SINK persistent_user_table2_sink FROM persistent_user_table2_for_sink
  INTO KAFKA BROKER '${testdrive.kafka-addr}' TOPIC 'persistent-user-table2-sink-${testdrive.seed}'
  WITH (consistency_topic = 'persistent-user-table2-sink-consistency')
  FORMAT AVRO
  USING CONFLUENT SCHEMA REGISTRY '${testdrive.schema-registry-url}';

> BEGIN

> INSERT INTO persistent_user_table1_for_sink VALUES (2);

> INSERT INTO persistent_user_table2_for_sink VALUES (2);

> COMMIT
```

2. Prior to restart, the respective sinks' topics have the following records that line up correctly:

```
{"before":null,"after":{"row":{"f1":{"int":1}}},"transaction":{"id":"1633344196706"}}
{"before":null,"after":{"row":{"f1":{"int":2}}},"transaction":{"id":"1633344197150"}}
```
and

```
{"before":null,"after":{"row":{"f1":{"int":1}}},"transaction":{"id":"1633344196706"}}
{"before":null,"after":{"row":{"f1":{"int":2}}},"transaction":{"id":"1633344197150"}}
```

So the two transactions are properly reflected for both tables with their separate timestamps.

3. However, after restart, the new topics look like this:
```
{"before":null,"after":{"row":{"f1":{"int":1}}},"transaction":{"id":"1633344196706"}}
{"before":null,"after":{"row":{"f1":{"int":2}}},"transaction":{"id":"1633344197150"}}
```

and

```
{"before":null,"after":{"row":{"f1":{"int":1}}},"transaction":{"id":"1633344197150"}} <- this record has a different timestamp now
{"before":null,"after":{"row":{"f1":{"int":2}}},"transaction":{"id":"1633344197150"}}
```

The first table's new topic looks exactly like its topic prior to the restart. However, the second table has had its timestamps compacted. So now for timestamp 1633344196706, there is only a record for the first table, even though both table participated in transaction at timestamp 1633344196706.

**Comment by philip-stoev** [comment]
This seems to be caused by compaction running in the background prior to the restart. If compaction is disabled after the restart, then the situation described above is preserved so that we can run this pair of queries:

```
materialize=> select * from  persistent_user_table2_for_sink as of 1633347052838;
 f1 
----
  1
(1 row)

materialize=> select * from  persistent_user_table1_for_sink as of 1633347052838;
 f1 
----
(0 rows)
```

So essentially for timestamp 1633347052838 one of the table has rows and the other does not, which is an atomicity violation that would never have been observed without the restart.

**Comment by ruchirK** [comment]
To my eyes this looks like two distinct issues

1. Kafka sinks don't communicate their as_of
2. It's possible to, by restarting and changing compaction options, ask queries about a table at a time t that is not at or in advance of the table's persisted compaction frontier, ie

```
materialize=> select * from  persistent_user_table1_for_sink as of 1633347052838;
 f1 
----
(0 rows)
```

this query should ideally return something like "invalid timestamp, not at or in advance of persisted compaction frontier <foo>"

Does that seem right or do you think I've missed something? I specifically don't think that tables being compacted at different rates is a bug because that seems baked in to how we handle compactions for in-memory relations as well.

**Comment by aljoscha** [comment]
If anything, this would be a coordinator/adapter problem now, but I think it's not an issue anymore.

@jkosh44 or @mjibson Do you have an opinion?

**Comment by jkosh44** [comment]
> We allow transactions to span multiple INSERT statements. This allows data to be inserted into multiple tables within the same transaction and all the inserts made will share the same timestamp.

This is no longer true, we disabled multi-table transaction a couple of months ago. So this isn't still an issue.
