### ISSUE TITLE
Cannot express float literals that are larger than max size of numeric

### ISSUE THREAD

**Issue by cjubb39** [MaterializeInc/materialize#8529]
### What version of Materialize are you using?
`materialized v0.9.7-dev`

### How did you install Materialize?
Build from source

### What was the issue?
(note that `SELECT '1e300'::float;` does match the behavior of postgresql)

From materialized:
```
materialize=> SELECT 1e300::float;
ERROR:  "1E300" is out of range for type numeric: exceeds maximum precision 39
```

From postgresql:
```
chae=# SELECT 1e300::float;
 float8
--------
 1e+300
(1 row)
```

**Comment by benesch** [comment]
I think this actually just fine! I’m loathe to say that number literals that don’t fit in a numeric get promoted to float8s, because that’s not a thing that happens in Postgres.

**Comment by cjubb39** [comment]
Ahh yes, I misunderstood and didn't realize that the behavior I noted in the issue is because our `numeric` type (max 38 digits) doesn't match postgresql's `numeric` type (very very large max number of digits).
