### ISSUE TITLE
Server-wide hang with reuse_topic=true if kafka is not responsive

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#8537]
### What version of Materialize are you using?

```
v0.9.6-dev
```

### What was the issue?

If Kafka is stopped while a reuse_topics=true sink is receiving updates, the following things happen:
- SELECTSs issues against the server, even to unrelated tables, hang.
- once kafka is restarted, data is no longer emitted to the sink

sinks with reus_topic=false behave as expected on both of those counts.

### Is the issue reproducible? If so, please provide reproduction instructions.

1.  To make testing easier, enable tables to be valid sources for reuse_topic sinks:
```
diff --git a/src/sql/src/plan/statement/ddl.rs b/src/sql/src/plan/statement/ddl.rs
index 3a347a2b6..e5d073569 100644
--- a/src/sql/src/plan/statement/ddl.rs
+++ b/src/sql/src/plan/statement/ddl.rs
@@ -1445,10 +1445,10 @@ fn kafka_sink_builder(
                 );
                 }
             } else if item.item_type() != CatalogItemType::Source {
-                bail!(
-                    "reuse_topic requires that sink input dependencies are sources, {} is not",
-                    item.name()
-                );
+                // bail!(
+                //     "reuse_topic requires that sink input dependencies are sources, {} is not",
+                //     item.name()
+                // );
             };
         }
```

2. Create a table source + a sink:
```
> CREATE TABLE ten (f1 INTEGER);

> INSERT INTO ten VALUES (1),(2),(3),(4),(5),(6),(7),(8),(9),(10);

> CREATE MATERIALIZED VIEW v1 AS SELECT a1.f1 + (10 * a2.f1) + (100 * a3.f1) + (1000 * a4.f1) AS f1 FROM ten AS a1, ten AS a2, ten AS a3, ten AS a4;

$ kafka-create-topic topic=s1 partitions=15

> CREATE SINK s1 FROM v1
  INTO KAFKA BROKER '${testdrive.kafka-addr}' TOPIC 's1-${testdrive.seed}'
  KEY (f1)
  WITH (reuse_topic=true)
  FORMAT AVRO USING CONFLUENT SCHEMA REGISTRY '${testdrive.schema-registry-url}'
```
3. Cause the sink to continously emit data:
```
while true; do sleep 0.1 ; echo -e "\\\timing on \n update ten set f1 = f1 + 10 ; update ten set f1 = f1 -10 ; " | psql  -p 6875 -h 127.0.0.1 -U materialize ; done
```

4. Kill kafka

5. Observe that the script from Step 4 is hung

6. Observe that issuing a select against e.g. a system table also hangs

7. Restart kafka

8. Observe that the topic of the sink no longer receives any messages.

**Comment by elindsey** [comment]
The interactivity portion of this is likely due to https://github.com/MaterializeInc/materialize/issues/6035

**Comment by cjubb39** [comment]
Fixing #6035 with #9909 does fix the interactivity issue.  That is: with that change, the script still continues to run and you're able to query system tables.
