### ISSUE TITLE
transition_on_txn_error not called on error in maybe_emit_progress, OOM ensues

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#8540]
### What version of Materialize are you using?

```
0.9.6-dev
```

### What was the issue?

I have a test that emits a lot of data to a Kafka reuse_topic=true sink. At some point Kafka starts to bork:

```
2021-10-05T10:25:26.917412Z ERROR librdkafka: librdkafka: TXNERR [thrd:main]: Current transaction failed in state CommittingTransaction: Transactional API operation (commit_transaction) timed out (_TIMED_OUT)    
```

The problem is that once this happens, Mz memory grows unbounded to an OOM. Since the librdkafka error above is not accompanied by any native Mz error messages, I assume the sink is not put properly in a failed state and thus compaction is prevented, which results in the OOM.

An uninformed look at the code shows that the code to `commit_transaction` in `produce_to_kafka` is checked for errors and `transition_on_txn_error` is called:

```
                    SendState::CommitTxn => {
                        let result = if s.transactional {
                            s.producer.commit_transaction(s.txn_timeout)
...
                        match result {
...
                            Err(e) => s.transition_on_txn_error(s.send_state, *ts, e),
                        } 
                    }
```

however, the call to `commit_transaction` in `maybe_emit_progress` is propagated upstream via the ? operator and is then eaten , producing just a debug-level message:

```
            if let Err(e) = s.maybe_emit_progress(input.frontier.frontier()) {
                // This can happen when the producer has not been
                // initialized yet. This also means, that we only start
                // emitting continuous updates once some real data
                // has been emitted.
                debug!("Error writing out progress update: {}", e);
            }
```

### Is the issue reproducible? If so, please provide reproduction instructions.

1. Patch Mz to allow tables to be used for reuse_topic sinks:
```
diff --git a/src/sql/src/plan/statement/ddl.rs b/src/sql/src/plan/statement/ddl.rs
index 3a347a2b6..e5d073569 100644
--- a/src/sql/src/plan/statement/ddl.rs
+++ b/src/sql/src/plan/statement/ddl.rs
@@ -1445,10 +1445,10 @@ fn kafka_sink_builder(
                 );
                 }
             } else if item.item_type() != CatalogItemType::Source {
-                bail!(
-                    "reuse_topic requires that sink input dependencies are sources, {} is not",
-                    item.name()
-                );
+                // bail!(
+                //     "reuse_topic requires that sink input dependencies are sources, {} is not",
+                //     item.name()
+                // );
             };
         }
```

2. Run this .td file:
```
> CREATE TABLE ten (f1 INTEGER);

> INSERT INTO ten VALUES (1),(2),(3),(4),(5),(6),(7),(8),(9),(10);

> CREATE MATERIALIZED VIEW v1 AS SELECT repeat('x', 16 * 1024) AS l, a1.f1 + (10 * a2.f1) + (100 * a3.f1) + (1000 * a4.f1) AS f1 FROM ten AS a1, ten AS a2, ten AS a3, ten AS a4;

> CREATE SINK s1 FROM v1
  INTO KAFKA BROKER '${testdrive.kafka-addr}' TOPIC 's1-${testdrive.seed}'
  KEY (f1)
  WITH (reuse_topic=true)
  FORMAT AVRO USING CONFLUENT SCHEMA REGISTRY '${testdrive.schema-registry-url}'

> CREATE SINK s2 FROM v1
  INTO KAFKA BROKER '${testdrive.kafka-addr}' TOPIC 's2-${testdrive.seed}'
  KEY (f1)
  WITH (reuse_topic=true)
  FORMAT AVRO USING CONFLUENT SCHEMA REGISTRY '${testdrive.schema-registry-url}'

> CREATE SINK s3 FROM v1
  INTO KAFKA BROKER '${testdrive.kafka-addr}' TOPIC 's3-${testdrive.seed}'
  KEY (f1)
  WITH (reuse_topic=true)
  FORMAT AVRO USING CONFLUENT SCHEMA REGISTRY '${testdrive.schema-registry-url}'

> CREATE SINK s4 FROM v1
  INTO KAFKA BROKER '${testdrive.kafka-addr}' TOPIC 's4-${testdrive.seed}'
  KEY (f1)
  WITH (reuse_topic=true)
  FORMAT AVRO USING CONFLUENT SCHEMA REGISTRY '${testdrive.schema-registry-url}'

> CREATE SINK s5 FROM v1
  INTO KAFKA BROKER '${testdrive.kafka-addr}' TOPIC 's5-${testdrive.seed}'
  KEY (f1)
  WITH (reuse_topic=true)
  FORMAT AVRO USING CONFLUENT SCHEMA REGISTRY '${testdrive.schema-registry-url}'
```

3. Flood the sink with stuff:
```
while true; do sleep 0.1 ; echo -e "\\\timing on \n update ten set f1 = f1 + 10 ; update ten set f1 = f1 -10 ; " | psql  -p 6875 -h 127.0.0.1 -U materialize ; done
```

4. Observe steady memory usage. Once the librdkafka error above happens, memory usage jumps and OOM ensues.

**Comment by philip-stoev** [comment]
@aljoscha  git praise reports your long hand in the code snippets cited above.

**Comment by aljoscha** [comment]
@ruchirK Could this be related to the issue you've been trying to debug?

**Comment by aljoscha** [comment]
@philip-stoev Do the Kafka logs report why it's not allowing transactions anymore. The motivation behind not putting the sink in a failed state was that committing these progress updates can fail without putting the sink into an invalid state. Another assumption was that failures would be temporary and that we could eventually make progress again. If Kafka would un-bork itself, I believe that this could make progress again, but I could be wrong.

**Comment by cjubb39** [comment]
Since this was opened, we've restructured kafka sinks (they're now async, there's no longer an explicit state machine) and revamped error handling.  That makes this specific issue moot.  The more general issue of "kakfa transactions don't work well via rdkafka" is currently also being worked on.  We also have plans in #12864 to change how we surface / handle errors in a much more thorough way.

Because of that, I don't think this is actionable any longer
