### ISSUE TITLE
panic: coord: unchecked add in builtin table updates

### ISSUE THREAD

**Issue by mjibson** [MaterializeInc/materialize#8588]
While in a branch, I left mz running for a few minutes and got a crash at https://github.com/MaterializeInc/materialize/blob/3ea77e7d80a32f936a5449f6d76f99f515a57692/src/coord/src/coord.rs#L3695 due to unchecked overflowed addition. I'm not exactly sure why the numbers got high enough to do that (possibly a bug in my branch), but we should probably protect against this somehow. Not sure how the error path stuff would work. This may be related to a proposal I have been making to prevent new timestamps from `get_write_ts` from being in advance of `now()`, so we'd need an error path in this function to handle that case too.

**Comment by chaas** [comment]
Code has been majorly refactored, closing as stale
