### ISSUE TITLE
loss of interactivity in reuse_topic sinks

### ISSUE THREAD

**Issue by elindsey** [MaterializeInc/materialize#8589]
reuse_topic was launched in beta and has started seeing some use. Early feedback/internal testing has pointed to a number of scenarios that end up looking roughly the same - multiple and/or high throughput sinks resulting in loss of interactivity or steadily increasing resource usage.

There are a few extremely plausible ways for us to land in such states:
* Error paths that lead to not compacting timestamp bindings (resulting in a gradual increase of CPU use in the coord)
* High throughput or multiple reuse_topic sinks that end up bogging the system down due to competing synchronous calls from timely workers
* Error paths from Kafka communication that throw us into a bad state and lead to gradual state accumulation or resource use

At this point we need to take a step back from investigating any single issue and focus on the areas where we need to add visibility such that we can make progress when these issues come in (ie. how can we answer questions like "what is the state of the sink?", "where is the coord spending its time?", etc. from data the user can easily gather), and focus on standing up an environment where we can more easily explore these issues - namely a longish running mz instance with steady input data and multiple reuse_topic sinks.

A few related tasks:
https://github.com/MaterializeInc/materialize/issues/8315
https://github.com/MaterializeInc/materialize/issues/8555
https://github.com/MaterializeInc/materialize/issues/8537
https://github.com/MaterializeInc/materialize/issues/8540

**Comment by elindsey** [comment]
No progress so far, but we will update this task when there is new. 🙂

**Comment by ruchirK** [comment]
@krpn we recently merged a change that should significantly improve the performance with `reuse_topic=true` sinks https://github.com/MaterializeInc/materialize/pull/9379 -- to set expectations, we don't think this fixes all of the underlying issues yet but this should significantly improve the performance / cpu usage should be a lot more stable / Materialize shouldn't hang anymore.
