### ISSUE TITLE
internal transform error: fixpoint looped too many times with many IN subqueries

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#8605]
### What version of Materialize are you using?

From the shell:

```
v0.9.8-dev (48182cc6b)
```

### What was the issue?

If a query contains 100 IN queries, a fixpoint error occurs:

```
> SELECT * FROM t1 AS a1 WHERE f1 IN (SELECT * FROM t1 WHERE f1 = a1.f1 AN...
rows didn't match; sleeping to see if dataflow catches up 50ms
<stdin>:190:1: error: executing query failed: db error: ERROR: internal transform error: fixpoint looped too many times Fixpoint {
    transforms: [
        ReductionPushdown,
        ReduceElision,
        LiteralLifting,
        RelationCSE,
        InlineLet {
            inline_mfp: false,
        },
        UpdateLet,
        FuseAndCollapse {
            transforms: [
                ProjectionExtraction,
                ProjectionLifting,
                Map,
                Negate,
                Filter,
                Project,
                Join,
                InlineLet {
                    inline_mfp: false,
                },
                Reduce,
                Union,
                UnionBranchCancellation,
                UpdateLet,
                RedundantJoin,
                FoldConstants {
                    limit: Some(
                        10000,
                    ),
                },
            ],
        },
    ],
    limit: 100,
} %0 =
| Get ? (u6174)
```

### Is the issue reproducible? If so, please provide reproduction instructions.

```
> CREATE TABLE t1 (f1 INTEGER);
> INSERT INTO t1 VALUES (1);
SELECT * FROM t1 AS a1 WHERE f1 IN (SELECT * FROM t1 WHERE f1 = a1.f1 AND f1 <= 1) AND f1 IN (SELECT * FROM t1 WHERE f1 = a1.f1 AND f1 <= 2) AND f1 IN (SELECT * FROM t1 WHERE f1 = a1.f1 AND f1 <= 3) AND f1 IN (SELECT * FROM t1 WHERE f1 = a1.f1 AND f1 <= 4) AND f1 IN (SELECT * FROM t1 WHERE f1 = a1.f1 AND f1 <= 5) AND f1 IN (SELECT * FROM t1 WHERE f1 = a1.f1 AND f1 <= 6) AND f1 IN (SELECT * FROM t1 WHERE f1 = a1.f1 AND f1 <= 7) AND f1 IN (SELECT * FROM t1 WHERE f1 = a1.f1 AND f1 <= 8) AND f1 IN (SELECT * FROM t1 WHERE f1 = a1.f1 AND f1 <= 9) AND f1 IN (SELECT * FROM t1 WHERE f1 = a1.f1 AND f1 <= 10) AND f1 IN (SELECT * FROM t1 WHERE f1 = a1.f1 AND f1 <= 11) AND f1 IN (SELECT * FROM t1 WHERE f1 = a1.f1 AND f1 <= 12) AND f1 IN (SELECT * FROM t1 WHERE f1 = a1.f1 AND f1 <= 13) AND f1 IN (SELECT * FROM t1 WHERE f1 = a1.f1 AND f1 <= 14) AND f1 IN (SELECT * FROM t1 WHERE f1 = a1.f1 AND f1 <= 15) AND f1 IN (SELECT * FROM t1 WHERE f1 = a1.f1 AND f1 <= 16) AND f1 IN (SELECT * FROM t1 WHERE f1 = a1.f1 AND f1 <= 17) AND f1 IN (SELECT * FROM t1 WHERE f1 = a1.f1 AND f1 <= 18) AND f1 IN (SELECT * FROM t1 WHERE f1 = a1.f1 AND f1 <= 19) AND f1 IN (SELECT * FROM t1 WHERE f1 = a1.f1 AND f1 <= 20) AND f1 IN (SELECT * FROM t1 WHERE f1 = a1.f1 AND f1 <= 21) AND f1 IN (SELECT * FROM t1 WHERE f1 = a1.f1 AND f1 <= 22) AND f1 IN (SELECT * FROM t1 WHERE f1 = a1.f1 AND f1 <= 23) AND f1 IN (SELECT * FROM t1 WHERE f1 = a1.f1 AND f1 <= 24) AND f1 IN (SELECT * FROM t1 WHERE f1 = a1.f1 AND f1 <= 25) AND f1 IN (SELECT * FROM t1 WHERE f1 = a1.f1 AND f1 <= 26) AND f1 IN (SELECT * FROM t1 WHERE f1 = a1.f1 AND f1 <= 27) AND f1 IN (SELECT * FROM t1 WHERE f1 = a1.f1 AND f1 <= 28) AND f1 IN (SELECT * FROM t1 WHERE f1 = a1.f1 AND f1 <= 29) AND f1 IN (SELECT * FROM t1 WHERE f1 = a1.f1 AND f1 <= 30) AND f1 IN (SELECT * FROM t1 WHERE f1 = a1.f1 AND f1 <= 31) AND f1 IN (SELECT * FROM t1 WHERE f1 = a1.f1 AND f1 <= 32) AND f1 IN (SELECT * FROM t1 WHERE f1 = a1.f1 AND f1 <= 33) AND f1 IN (SELECT * FROM t1 WHERE f1 = a1.f1 AND f1 <= 34) AND f1 IN (SELECT * FROM t1 WHERE f1 = a1.f1 AND f1 <= 35) AND f1 IN (SELECT * FROM t1 WHERE f1 = a1.f1 AND f1 <= 36) AND f1 IN (SELECT * FROM t1 WHERE f1 = a1.f1 AND f1 <= 37) AND f1 IN (SELECT * FROM t1 WHERE f1 = a1.f1 AND f1 <= 38) AND f1 IN (SELECT * FROM t1 WHERE f1 = a1.f1 AND f1 <= 39) AND f1 IN (SELECT * FROM t1 WHERE f1 = a1.f1 AND f1 <= 40) AND f1 IN (SELECT * FROM t1 WHERE f1 = a1.f1 AND f1 <= 41) AND f1 IN (SELECT * FROM t1 WHERE f1 = a1.f1 AND f1 <= 42) AND f1 IN (SELECT * FROM t1 WHERE f1 = a1.f1 AND f1 <= 43) AND f1 IN (SELECT * FROM t1 WHERE f1 = a1.f1 AND f1 <= 44) AND f1 IN (SELECT * FROM t1 WHERE f1 = a1.f1 AND f1 <= 45) AND f1 IN (SELECT * FROM t1 WHERE f1 = a1.f1 AND f1 <= 46) AND f1 IN (SELECT * FROM t1 WHERE f1 = a1.f1 AND f1 <= 47) AND f1 IN (SELECT * FROM t1 WHERE f1 = a1.f1 AND f1 <= 48) AND f1 IN (SELECT * FROM t1 WHERE f1 = a1.f1 AND f1 <= 49) AND f1 IN (SELECT * FROM t1 WHERE f1 = a1.f1 AND f1 <= 50) AND f1 IN (SELECT * FROM t1 WHERE f1 = a1.f1 AND f1 <= 51) AND f1 IN (SELECT * FROM t1 WHERE f1 = a1.f1 AND f1 <= 52) AND f1 IN (SELECT * FROM t1 WHERE f1 = a1.f1 AND f1 <= 53) AND f1 IN (SELECT * FROM t1 WHERE f1 = a1.f1 AND f1 <= 54) AND f1 IN (SELECT * FROM t1 WHERE f1 = a1.f1 AND f1 <= 55) AND f1 IN (SELECT * FROM t1 WHERE f1 = a1.f1 AND f1 <= 56) AND f1 IN (SELECT * FROM t1 WHERE f1 = a1.f1 AND f1 <= 57) AND f1 IN (SELECT * FROM t1 WHERE f1 = a1.f1 AND f1 <= 58) AND f1 IN (SELECT * FROM t1 WHERE f1 = a1.f1 AND f1 <= 59) AND f1 IN (SELECT * FROM t1 WHERE f1 = a1.f1 AND f1 <= 60) AND f1 IN (SELECT * FROM t1 WHERE f1 = a1.f1 AND f1 <= 61) AND f1 IN (SELECT * FROM t1 WHERE f1 = a1.f1 AND f1 <= 62) AND f1 IN (SELECT * FROM t1 WHERE f1 = a1.f1 AND f1 <= 63) AND f1 IN (SELECT * FROM t1 WHERE f1 = a1.f1 AND f1 <= 64) AND f1 IN (SELECT * FROM t1 WHERE f1 = a1.f1 AND f1 <= 65) AND f1 IN (SELECT * FROM t1 WHERE f1 = a1.f1 AND f1 <= 66) AND f1 IN (SELECT * FROM t1 WHERE f1 = a1.f1 AND f1 <= 67) AND f1 IN (SELECT * FROM t1 WHERE f1 = a1.f1 AND f1 <= 68) AND f1 IN (SELECT * FROM t1 WHERE f1 = a1.f1 AND f1 <= 69) AND f1 IN (SELECT * FROM t1 WHERE f1 = a1.f1 AND f1 <= 70) AND f1 IN (SELECT * FROM t1 WHERE f1 = a1.f1 AND f1 <= 71) AND f1 IN (SELECT * FROM t1 WHERE f1 = a1.f1 AND f1 <= 72) AND f1 IN (SELECT * FROM t1 WHERE f1 = a1.f1 AND f1 <= 73) AND f1 IN (SELECT * FROM t1 WHERE f1 = a1.f1 AND f1 <= 74) AND f1 IN (SELECT * FROM t1 WHERE f1 = a1.f1 AND f1 <= 75) AND f1 IN (SELECT * FROM t1 WHERE f1 = a1.f1 AND f1 <= 76) AND f1 IN (SELECT * FROM t1 WHERE f1 = a1.f1 AND f1 <= 77) AND f1 IN (SELECT * FROM t1 WHERE f1 = a1.f1 AND f1 <= 78) AND f1 IN (SELECT * FROM t1 WHERE f1 = a1.f1 AND f1 <= 79) AND f1 IN (SELECT * FROM t1 WHERE f1 = a1.f1 AND f1 <= 80) AND f1 IN (SELECT * FROM t1 WHERE f1 = a1.f1 AND f1 <= 81) AND f1 IN (SELECT * FROM t1 WHERE f1 = a1.f1 AND f1 <= 82) AND f1 IN (SELECT * FROM t1 WHERE f1 = a1.f1 AND f1 <= 83) AND f1 IN (SELECT * FROM t1 WHERE f1 = a1.f1 AND f1 <= 84) AND f1 IN (SELECT * FROM t1 WHERE f1 = a1.f1 AND f1 <= 85) AND f1 IN (SELECT * FROM t1 WHERE f1 = a1.f1 AND f1 <= 86) AND f1 IN (SELECT * FROM t1 WHERE f1 = a1.f1 AND f1 <= 87) AND f1 IN (SELECT * FROM t1 WHERE f1 = a1.f1 AND f1 <= 88) AND f1 IN (SELECT * FROM t1 WHERE f1 = a1.f1 AND f1 <= 89) AND f1 IN (SELECT * FROM t1 WHERE f1 = a1.f1 AND f1 <= 90) AND f1 IN (SELECT * FROM t1 WHERE f1 = a1.f1 AND f1 <= 91) AND f1 IN (SELECT * FROM t1 WHERE f1 = a1.f1 AND f1 <= 92) AND f1 IN (SELECT * FROM t1 WHERE f1 = a1.f1 AND f1 <= 93) AND f1 IN (SELECT * FROM t1 WHERE f1 = a1.f1 AND f1 <= 94) AND f1 IN (SELECT * FROM t1 WHERE f1 = a1.f1 AND f1 <= 95) AND f1 IN (SELECT * FROM t1 WHERE f1 = a1.f1 AND f1 <= 96) AND f1 IN (SELECT * FROM t1 WHERE f1 = a1.f1 AND f1 <= 97) AND f1 IN (SELECT * FROM t1 WHERE f1 = a1.f1 AND f1 <= 98) AND f1 IN (SELECT * FROM t1 WHERE f1 = a1.f1 AND f1 <= 99) AND f1 IN (SELECT * FROM t1 WHERE f1 = a1.f1 AND f1 <= 100);
```

There is no need to push this query into a regression test, as it will be exercised by a dedicated framework.

**Comment by philip-stoev** [comment]
Happens with uncorrelated queries too: ```SELECT * FROM t1 AS a1 WHERE f1 IN (SELECT * FROM t1 WHERE f1 <= 1) AND f1 IN (SELECT * FROM t1 WHERE f1 <= 2) AND f1 IN (SELECT * FROM t1 WHERE f1 <= 3) AND f1 IN (SELECT * FROM t1 WHERE f1 <= 4) AND f1 IN (SELECT * FROM t1 WHERE f1 <= 5) AND f1 IN (SELECT * FROM t1 WHERE f1 <= 6) AND f1 IN (SELECT * FROM t1 WHERE f1 <= 7) AND f1 IN (SELECT * FROM t1 WHERE f1 <= 8) AND f1 IN (SELECT * FROM t1 WHERE f1 <= 9) AND f1 IN (SELECT * FROM t1 WHERE f1 <= 10) AND f1 IN (SELECT * FROM t1 WHERE f1 <= 11) AND f1 IN (SELECT * FROM t1 WHERE f1 <= 12) AND f1 IN (SELECT * FROM t1 WHERE f1 <= 13) AND f1 IN (SELECT * FROM t1 WHERE f1 <= 14) AND f1 IN (SELECT * FROM t1 WHERE f1 <= 15) AND f1 IN (SELECT * FROM t1 WHERE f1 <= 16) AND f1 IN (SELECT * FROM t1 WHERE f1 <= 17) AND f1 IN (SELECT * FROM t1 WHERE f1 <= 18) AND f1 IN (SELECT * FROM t1 WHERE f1 <= 19) AND f1 IN (SELECT * FROM t1 WHERE f1 <= 20) AND f1 IN (SELECT * FROM t1 WHERE f1 <= 21) AND f1 IN (SELECT * FROM t1 WHERE f1 <= 22) AND f1 IN (SELECT * FROM t1 WHERE f1 <= 23) AND f1 IN (SELECT * FROM t1 WHERE f1 <= 24) AND f1 IN (SELECT * FROM t1 WHERE f1 <= 25) AND f1 IN (SELECT * FROM t1 WHERE f1 <= 26) AND f1 IN (SELECT * FROM t1 WHERE f1 <= 27) AND f1 IN (SELECT * FROM t1 WHERE f1 <= 28) AND f1 IN (SELECT * FROM t1 WHERE f1 <= 29) AND f1 IN (SELECT * FROM t1 WHERE f1 <= 30) AND f1 IN (SELECT * FROM t1 WHERE f1 <= 31) AND f1 IN (SELECT * FROM t1 WHERE f1 <= 32) AND f1 IN (SELECT * FROM t1 WHERE f1 <= 33) AND f1 IN (SELECT * FROM t1 WHERE f1 <= 34) AND f1 IN (SELECT * FROM t1 WHERE f1 <= 35) AND f1 IN (SELECT * FROM t1 WHERE f1 <= 36) AND f1 IN (SELECT * FROM t1 WHERE f1 <= 37) AND f1 IN (SELECT * FROM t1 WHERE f1 <= 38) AND f1 IN (SELECT * FROM t1 WHERE f1 <= 39) AND f1 IN (SELECT * FROM t1 WHERE f1 <= 40) AND f1 IN (SELECT * FROM t1 WHERE f1 <= 41) AND f1 IN (SELECT * FROM t1 WHERE f1 <= 42) AND f1 IN (SELECT * FROM t1 WHERE f1 <= 43) AND f1 IN (SELECT * FROM t1 WHERE f1 <= 44) AND f1 IN (SELECT * FROM t1 WHERE f1 <= 45) AND f1 IN (SELECT * FROM t1 WHERE f1 <= 46) AND f1 IN (SELECT * FROM t1 WHERE f1 <= 47) AND f1 IN (SELECT * FROM t1 WHERE f1 <= 48) AND f1 IN (SELECT * FROM t1 WHERE f1 <= 49) AND f1 IN (SELECT * FROM t1 WHERE f1 <= 50) AND f1 IN (SELECT * FROM t1 WHERE f1 <= 51) AND f1 IN (SELECT * FROM t1 WHERE f1 <= 52) AND f1 IN (SELECT * FROM t1 WHERE f1 <= 53) AND f1 IN (SELECT * FROM t1 WHERE f1 <= 54) AND f1 IN (SELECT * FROM t1 WHERE f1 <= 55) AND f1 IN (SELECT * FROM t1 WHERE f1 <= 56) AND f1 IN (SELECT * FROM t1 WHERE f1 <= 57) AND f1 IN (SELECT * FROM t1 WHERE f1 <= 58) AND f1 IN (SELECT * FROM t1 WHERE f1 <= 59) AND f1 IN (SELECT * FROM t1 WHERE f1 <= 60) AND f1 IN (SELECT * FROM t1 WHERE f1 <= 61) AND f1 IN (SELECT * FROM t1 WHERE f1 <= 62) AND f1 IN (SELECT * FROM t1 WHERE f1 <= 63) AND f1 IN (SELECT * FROM t1 WHERE f1 <= 64) AND f1 IN (SELECT * FROM t1 WHERE f1 <= 65) AND f1 IN (SELECT * FROM t1 WHERE f1 <= 66) AND f1 IN (SELECT * FROM t1 WHERE f1 <= 67) AND f1 IN (SELECT * FROM t1 WHERE f1 <= 68) AND f1 IN (SELECT * FROM t1 WHERE f1 <= 69) AND f1 IN (SELECT * FROM t1 WHERE f1 <= 70) AND f1 IN (SELECT * FROM t1 WHERE f1 <= 71) AND f1 IN (SELECT * FROM t1 WHERE f1 <= 72) AND f1 IN (SELECT * FROM t1 WHERE f1 <= 73) AND f1 IN (SELECT * FROM t1 WHERE f1 <= 74) AND f1 IN (SELECT * FROM t1 WHERE f1 <= 75) AND f1 IN (SELECT * FROM t1 WHERE f1 <= 76) AND f1 IN (SELECT * FROM t1 WHERE f1 <= 77) AND f1 IN (SELECT * FROM t1 WHERE f1 <= 78) AND f1 IN (SELECT * FROM t1 WHERE f1 <= 79) AND f1 IN (SELECT * FROM t1 WHERE f1 <= 80) AND f1 IN (SELECT * FROM t1 WHERE f1 <= 81) AND f1 IN (SELECT * FROM t1 WHERE f1 <= 82) AND f1 IN (SELECT * FROM t1 WHERE f1 <= 83) AND f1 IN (SELECT * FROM t1 WHERE f1 <= 84) AND f1 IN (SELECT * FROM t1 WHERE f1 <= 85) AND f1 IN (SELECT * FROM t1 WHERE f1 <= 86) AND f1 IN (SELECT * FROM t1 WHERE f1 <= 87) AND f1 IN (SELECT * FROM t1 WHERE f1 <= 88) AND f1 IN (SELECT * FROM t1 WHERE f1 <= 89) AND f1 IN (SELECT * FROM t1 WHERE f1 <= 90) AND f1 IN (SELECT * FROM t1 WHERE f1 <= 91) AND f1 IN (SELECT * FROM t1 WHERE f1 <= 92) AND f1 IN (SELECT * FROM t1 WHERE f1 <= 93) AND f1 IN (SELECT * FROM t1 WHERE f1 <= 94) AND f1 IN (SELECT * FROM t1 WHERE f1 <= 95) AND f1 IN (SELECT * FROM t1 WHERE f1 <= 96) AND f1 IN (SELECT * FROM t1 WHERE f1 <= 97) AND f1 IN (SELECT * FROM t1 WHERE f1 <= 98) AND f1 IN (SELECT * FROM t1 WHERE f1 <= 99) AND f1 IN (SELECT * FROM t1 WHERE f1 <= 100)
```

**Comment by asenac** [comment]
This no longer happens after #8582, which made fixpoints a soft limit.
