### ISSUE TITLE
Support logging SQL statements

### ISSUE THREAD

**Issue by andrioni** [MaterializeInc/materialize#8653]
It is helpful to be able to log only SQL statements, separately from regular log messages (e.g. in a separate file), both for debugging and for having an audit log.

A more sophisticated version of this would be to have queryable audit trail tables, e.g. like [BigQuery has](https://cloud.google.com/bigquery/docs/reference/auditlogs#bigqueryauditmetadata_examples).

**Comment by chaas** [comment]
Marking this as obsolete, in favor of the current audit log and upcoming statement log
