### ISSUE TITLE
doc: Review and update "Key Concepts" page

### ISSUE THREAD

**Issue by ruf-io** [MaterializeInc/materialize#8664]
### What pages are affected?

  * [Key Concepts](https://materialize.com/docs/overview/key-concepts/)

###  What needs to be changed or added?

- [x]   * Make sure the provided information is still accurate
- [x]   * Make sure new sources are mentioned
- [x]   * Make sure important new features are incorporated if necessary.

**Comment by ruf-io** [comment]
Notes on anticipated changes needed to page:

1. Add Sinks
2. Remove current discussion of Materialized Views, add  :new: Materialized Views (AKA Recorded Views)
3. Add diagrams to clarify (esp. Cluster/Replica)

**Comment by morsapaes** [comment]
The page has been updated to reference nu Materialize. A bigger refactor is needed once we're through with all foundational changes, but closing this issue for now.
