### ISSUE TITLE
Separate format decoding from envelope logic

### ISSUE THREAD

**Issue by elindsey** [MaterializeInc/materialize#8692]
Currently format decoding and envelope handling are fairly intertwined - the code contains many separate paths depending on the source/format/envelope, and the various combinations are hardcoded.

The intent is to separate format from envelope such that these can instead be pieced together and compatibility can be evaluated at runtime.

This is a necessary initial refactor for the debezium work just so all the logic can be in one self-contained place before it starts getting altered.

**Comment by aljoscha** [comment]
@petrosagg how relevant is this issue still?

**Comment by petrosagg** [comment]
There are still entangled bits in the code but I'd say this issue is 90% done and we could close it

**Comment by benesch** [comment]
> There are still entangled bits in the code but I'd say this issue is 90% done and we could close it

Sold.
