### ISSUE TITLE
Respect debezium transaction boundaries within a single topic

### ISSUE THREAD

**Issue by elindsey** [MaterializeInc/materialize#8693]
Debezium includes a 'transaction metadata' topic that expresses transaction boundaries within the data topic. For example, the txn metadata topic may say "data topic offsets 1-3 are from txn 1, data topic offsets 4-9 are from txn 2", and so on.

For correctness, this transaction metadata topic should drive our timestamping logic such that all data within a given transaction is assigned the same timestamp and flows through the system together. Today this is not the case - data within the same txn will get various different timestamps.

The transaction metadata topic may reference multiple data topics, but the scope of this task is limited to doing correct ts assignment for a single topic.

**Comment by cjubb39** [comment]
Note to self: be able to handle rollbacks from debezium

**Comment by nmeagan11** [comment]
Note: this should close out https://github.com/MaterializeInc/materialize/issues/6296.
