### ISSUE TITLE
persistence: All SELECTs hang after an I/O error during persistence

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#8740]
### What version of Materialize are you using?
```
a41738b7796eaf81d1ee9d81677ea21d571263a9
```

### What was the issue?

After an INSERT has failed due to an I/O error during persistence, following SELECTs, even on unrelated tables, hang forever. I think they should be returning data, if any, or , if this is not possible to do safely, return some sort of an error (as if the borked table is a source that has errored out)

### Is the issue reproducible? If so, please provide reproduction instructions.

1. Run an instrumented Mz binary as described in https://github.com/MaterializeInc/materialize/issues/8738
2. Run this:
```
echo -e "CREATE TABLE t1(f1 INTEGER);\n INSERT INTO t1 VALUES (1)\n; SELECT * FROM t1\n;" | psql -p 6875 -h 127.0.0.1 -U materialize
```
and it will hang forever.

AS OF NOW queries also hang. SELECTs against other tables also hang.

**Comment by philip-stoev** [comment]
After the I/O error is cleared, INSERTS against the table resume, but SELECTs remain hanging.

**Comment by aljoscha** [comment]
Closing this because current persist/storage architecture has moved quite a bit beyond this.

@philip-stoev Please yell at me if you'd like to keep this open.

fyi @danhhz
