### ISSUE TITLE
persist: get persistent Kafka source ready for beta testers

### ISSUE THREAD

**Issue by aljoscha** [MaterializeInc/materialize#8810]
Umbrella issue for getting the persistent Kafka source ready for beta testers.

### Bugs

- [x] #9509
- [x] #9330
- [x] #8891 
- [x] #8909
- [x] #9123
- [x] #9241
- [x] #9328
- [ ] persist: destroy persistent collections when a persistent source is dropped (maybe?)

### "Correctness" (in the sense of Frank's correctness document, but also a vaguer feeling of how things should be)

- [x] #9508
- [x] #9655
- [x] #8608
- [ ] persist: re-evaluate the `Codec` impls that are involved in the source: right now, theses are the codecs for `Row`, `DecodeError`, `SourceTimestamp`, and `AssignedTimestamp`
- [x] persist: re-consider emitting errors for seal failures: Right now, they are not added to the "err" collections because they seem somewhat transient, meaning we don't "wedge" indexes/views if/when seal errors occur. This is resolved (for now) by https://github.com/MaterializeInc/materialize/pull/9246
- [ ] persist: audit where and how we surface persistence errors in "err" collections: Persistence errors are not _definite_ (to use the lingo of the correction design doc) but rather transient. They therefore shouldn't be in the relational error collections. There is no better place to put them right now, so we might have to punt this issue.

### Performance

- [x] #8812
- [x] #8813
- [x] #9101

### Observability

- [ ] metrics: add a metric that allows tracking how many messages we have ingested/persisted: Right now, `mz_messages_ingested` only tracks messages ingested at the "raw" source, before going through persistence, where they might be held up while waiting to be persisted. The `avro-upsert` benchmark uses that metric to determine when all messages are ingested, but with persistence enabled this is no longer correct to do. Ideas here are to add a `mz_messages_persisted` and `mz_messages_replayed_from_persistence` (horribly long name, but you get the gist).

### Misc

- [ ] docs: document persistent Kafka Source
- [x] persist: de-experimentalize persistent Kafka Source: This depends on the other issues in #8810 being resolved first.
- [x] persist,dataflow: make persistent source rendering code generic over different source/envelope types: Right now, we hard-code the knowledge about the participating persistent collections and their types at the top of the source rendering code. We cannot do this if we want to support multiple sources and envelopes. What we instead need to do is store a list of participating persistent collections in the catalog, then the code that determines the common seal timestamp can just get the seal/upper from them, without knowing their types. The envelope/source-specific code can then get handles to the collections that it needs later. (this description is still somewhat TBD), see https://github.com/MaterializeInc/materialize/pull/8746#discussion_r733638638

### Optional
- [ ] persist: make `persist()` operator retryable by holding on to data until it is persisted
- [x] #8907 : This depends on the performance goals and is not something that we will likely do any time soon.

**Comment by ruchirK** [comment]
another performance thing I noticed today: `listen_source` only sends the data to worker 0 -- that might be a bottleneck in the future and we might want to partition the data across all workers (although we don't want to broadcast the updates N times either)

**Comment by danhhz** [comment]
@aljoscha anything here that's worth splitting out for M2?

**Comment by aljoscha** [comment]
The only one that seems worthwhile salvaging is:
 - persist: destroy persistent collections when a persistent source is dropped (maybe?)
   - I have a vague feeling that when we drop a shard (that is, advance the since to `[]`) there is no one around anymore to act as final (grim?) reaper and GC the remaining blobs/parts.

Regarding
 - persist: re-evaluate the Codec impls that are involved in the source: right now, theses are the codecs for Row, DecodeError, SourceTimestamp, and AssignedTimestamp
 - persist: audit where and how we surface persistence errors in "err" collections: Persistence errors are not definite (to use the lingo of the correction design doc) but rather transient. They therefore shouldn't be in the relational error collections. There is no better place to put them right now, so we might have to punt this issue.
 
I think there are still some thoughts about changing how we encode `Row`, but I don't think we need to keep track of this here. There is a bigger EPIC about error handling, so no need to keep this one.

The one remaining issue about metrics seems well covered by now, wdyt?

**Comment by aljoscha** [comment]
Closing this now because it has been subsumed by all the platform work.
