### ISSUE TITLE
PostgreSQL JDBC 42.3.0 results in error because initial statements moved to inside transaction

### ISSUE THREAD

**Issue by jstuyts** [MaterializeInc/materialize#8811]
### What version of Materialize are you using?
0.9.1

### How did you install Materialize?
* [X] Docker image
* [ ] Linux release tarball
* [ ] APT package
* [ ] macOS release tarball
* [ ] Homebrew tap
* [ ] Built from source
* [ ] Materialize Cloud

### What was the issue?
When I upgrade to version 42.3.0 of the [PostgreSQL JDBC driver](https://jdbc.postgresql.org/), Materialize returns the following error:
```
ERROR: SET extra_float_digits = 3 cannot be run inside a transaction block
```

The initial statements run by the driver were moved to inside a transaction in this pull request: https://github.com/pgjdbc/pgjdbc/pull/1977

### Is the issue reproducible? If so, please provide reproduction instructions.
Yes, connect to Materialize using the driver version given above.

**Comment by mjibson** [comment]
Fixed by #8845
