### ISSUE TITLE
doc: New page on monitoring Cloud deployments

### ISSUE THREAD

**Issue by TonyRippy** [MaterializeInc/materialize#8824]
### For updates to existing documentation

* What pages are affected?
Unclear. This might either be a new page, or a sub-page of https://materialize.com/docs/cloud/connect-to-cloud/. 

* What needs to be changed or added?
We have very basic in-product instructions for monitoring a Cloud deployment with Prometheus:
 
![Screenshot from 2021-10-27 17-48-04](https://user-images.githubusercontent.com/6686398/139152228-1aba4139-4b50-47d5-9645-a8246a8dfa57.png)

This tells how to _connect_, but it would be useful to expand on this a bit and possibly link to:
https://materialize.com/docs/ops/monitoring/#prometheus

Longer-term we will also need to add documentation for how to integrate Cloud with Datadog.

We also need to mention something along the lines of: "We want to make it possible to monitor Cloud Materialize using the same tools you use to monitor the rest of your monitoring pipeline."

**Comment by bobbyiliev** [comment]
Closing this one as it is no longer applicable. cc @morsapaes
