### ISSUE TITLE
Support "transactions"

### ISSUE THREAD

**Issue by quodlibetor** [MaterializeInc/materialize#885]
Metabase  in particular just issues "Start Transaction" before issuing queries to pg, and I recall seeing other kinds of services (e.g. hibernate) doing that as well to ensure that when multiple queries are issued they are looking at a consistent view of the data.

This can be broken into two parts: a "compat" part and a "feature" part.

* compat: just lie and say that we are starting a transaction
* feature: during a transaction all input sources our output views should get their current timestamp snapshotted (following similar tradeoffs as `PeekWhen`) and all peeks should be exactly at that time.

**Comment by benesch** [comment]
The spirit of this issue is very much intact, but a more detailed plan was written up by @mjibson in #5073, so I'm going to close this one out!
