### ISSUE TITLE
doc: Disabling user indexes in Cloud

### ISSUE THREAD

**Issue by TonyRippy** [MaterializeInc/materialize#8861]
### For updates to existing documentation

* What pages are affected?
https://materialize.com/docs/cloud/troubleshoot-cloud/

* What needs to be changed or added?
Thanks to https://github.com/MaterializeInc/cloud/issues/695, we have an additional way to troubleshoot workloads that unexpectedly consume all the CPU or memory. It should be added to the list of troubleshooting techniques, along with a link to https://materialize.com/docs/cli/#disable-user-indexes for more information.

**Comment by jseldess** [comment]
Outdated. Closing.
