### ISSUE TITLE
Kafka sources fail to ingest any data if persistence is enabled 

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#8891]
### What version of Materialize are you using?

```
5f2f9d0f3ee585bbfe82e1164da7a94db14f9c0e
```

### What was the issue?

If persistent kafka sources is enabled, the source does not ingest anything

### Is the issue reproducible? If so, please provide reproduction instructions.

Enable --persistent-kafka-source or patch the code to have it enabled by default:

```
diff --git a/src/materialized/src/bin/materialized/main.rs b/src/materialized/src/bin/materialized/main.rs
index 1591c43b5..9fbb9ef35 100644
--- a/src/materialized/src/bin/materialized/main.rs
+++ b/src/materialized/src/bin/materialized/main.rs
@@ -658,14 +658,7 @@ swap: {swap_total}KB total, {swap_used}KB used{swap_limit}",
             PersistStorage::try_from(args.persist_storage)?
         };
 
-        let kafka_upsert_source_enabled =
-            if args.experimental && args.persistent_kafka_upsert_source {
-                true
-            } else if args.persistent_kafka_upsert_source {
-                bail!("cannot specify --persistent-kafka-upsert-source without --experimental");
-            } else {
-                false
-            };
+        let kafka_upsert_source_enabled = true;
 
         let lock_info = format!(
             "materialized {mz_version}\nos: {os}\nstart time: {start_time}\nnum workers: {num_workers}\n",
```

2. Run the normal `kafka-upsert-sources.td` TD test that simply create a source and selects from it:
```
 TD_TEST=kafka-upsert-sources.td ./mzcompose run testdrive 
```

3. The test will fail as follows:
```
> SELECT * from avroavro
rows didn't match; sleeping to see if dataflow catches up 50ms 75ms 112ms 169ms 253ms 380ms 570ms 854ms 1s 2s 3s 1s
kafka-upsert-sources.td:50:1: error: executing query failed: db error: ERROR: At least one input has no complete timestamps yet: [User(2)]
     |
  49 | 
  50 | > SELECT * from avroavro
     | ^
!!! Error Report
1 errors were encountered during execution



### Please attach any applicable log files.

```
2021-11-01T18:28:37.539558Z ERROR persist::operators::stream: Error sealing conditional_seal(kafka-u1/29) (primary) up to 1635791317300: invalid seal for Id(3): 1635791317300 not at or in advance of current seal frontier Antichain { elements: [1635791317400] }    
2021-11-01T18:28:37.539612Z ERROR dataflow::render::sources: ("Error sealing conditional_seal(kafka-u1/29) (primary) up to 1635791317300: invalid seal for Id(3): 1635791317300 not at or in advance of current seal frontier Antichain { elements: [1635791317400] }", 1635791317300, 1)
```

**Comment by philip-stoev** [comment]
This is no longer reproducible, seems to have been  fixed by a very recent commit.

**Comment by aljoscha** [comment]
@philip-stoev For the record, this was fixed via https://github.com/MaterializeInc/materialize/pull/8879.
