### ISSUE TITLE
Figure out a better way to represent avro unions in Materialize

### ISSUE THREAD

**Issue by umanwizard** [MaterializeInc/materialize#8919]
Today for a field `f` with union type, e.g. `["int", "string"]`, we will generate two columns in Materialize: `f1` of type `int nullable`, and `f2` of type `text nullable`, and fill in whichever one is actually present in the data.

This is a bit gross and it'd be much nicer to just emit one field `f` that has the right type, but that would require us to support sum types in Materialize.

**Comment by benesch** [comment]
A proposal for sum types is in #6842.

**Comment by benesch** [comment]
I'm just going to close this in favor of https://github.com/MaterializeInc/materialize/issues/6842.
