### ISSUE TITLE
Push permutations into MFPs

### ISSUE THREAD

**Issue by antiguru** [MaterializeInc/materialize#8932]
Push projections into MFPs that wrap access to arranged data. There are some moments where we access arranged data without an MFP, but imo this should be considered a smell (copying entire rows, without first filtering and projecting them down).

This is a follow-up from #6672 and #8718.

**Comment by umanwizard** [comment]
If I understand this issue correctly, the idea is to avoid the following class of waste:

1. We have an arrangement with an associated permutation, so that when we access the arrangement, we have to call something like `Permutation::permute_on_place` for every row.
2. We apply an MFP immediately afterwards, meaning we might project out some of the datums we (wastefully) wrote in step 1.

Thus if the MFP could learn to do the permutation itself, we could avoid step 1 and the possible waste.

Does this description seem correct to you, @antiguru ?

**Comment by antiguru** [comment]
Yes, your understanding seems correct. MFPs can be permuted as they are, but currently we only permute them during the planning stage, but not anymore once they're rendered. In this case it's not entirely clear to me whether we'd want to keep this pattern or allow a permutation after planning, while rendering.

The reason for this is that I'm not sure that we know all permutations at planning time, or whether they'll only be known while rendering. Currently, permutations are attached to imported traces, which are only known at rendering time. The question we need to answer is whether the planner can know the permutation of a trace before importing it -- it knows the logical structure of the rows, but the actual permutation currently is a decision of the operator driving the arrangement.

I'd suggest adding a `permute` fn to MFP plans which allows to permute them according to a permutation. This would be the first step, and next we could see if we'd want to pull this up into the planning phase, or introduce a 'unfinished' MFP that needs to be explicitly permuted at rendering time to make sure that all permutations are actually applied.

**Comment by antiguru** [comment]
Here are some snippets which might help:

Gain access to the inner parts of the `SafeMfpPlan`:
```
+    impl std::ops::DerefMut for SafeMfpPlan {
+        fn deref_mut(&mut self) -> &mut Self::Target {
+            &mut self.mfp
+        }
+    }
```

Fn on `Permutation` to permute a `SafeMfpPlan`:
```
+
+    pub fn permute_mfp(&self, mfp: &mut SafeMfpPlan) {
+        let shuffle = self.permutation.iter().copied().enumerate().collect();
+        let input_arity = self.permutation.iter().max().map(|c| *c + 1).unwrap_or(0);
+        println!("permute_mfp {:?}", mfp);
+        println!("       self {:?}", self);
+        println!("    shuffle {:?}", shuffle);
+        mfp.permute(&shuffle, input_arity);
+        println!("        --> {:?}", mfp);
+    }
```

This should be possible then:
```
diff --git a/src/dataflow/src/server.rs b/src/dataflow/src/server.rs
index c369cc06f..34eacc243 100644
--- a/src/dataflow/src/server.rs
+++ b/src/dataflow/src/server.rs
@@ -868,7 +868,7 @@ where
                 timestamp,
                 conn_id,
                 finishing,
-                map_filter_project,
+                mut map_filter_project,
             } => {
                 // Acquire a copy of the trace suitable for fulfilling the peek.
                 let mut trace_bundle = self.render_state.traces.get(&id).unwrap().clone();
@@ -887,6 +887,11 @@ where
                     .errs_mut()
                     .set_physical_compaction(empty_frontier.borrow());
                 // Prepare a description of the peek work to do.
+
+                trace_bundle
+                    .permutation()
+                    .permute_mfp(&mut map_filter_project);
+
                 let mut peek = PendingPeek {
                     id,
                     key,
@@ -1289,9 +1294,9 @@ impl PendingPeek {
                 // for the arena above (the allocation would not be allowed
                 // to outlive the arena above, from which it might borrow).
                 let mut borrow = datum_vec.borrow_with_many(&[key, row]);
-                self.trace_bundle
-                    .permutation()
-                    .permute_in_place(&mut borrow);
+                // self.trace_bundle
+                //     .permutation()
+                //     .permute_in_place(&mut borrow);
                 if let Some(result) = self
                     .map_filter_project
                     .evaluate_into(&mut borrow, &arena, &mut row_builder)
```

This is recovered from some git stash, so might not apply as is anymore :)

**Comment by antiguru** [comment]
The `Permutation` type still exists and there are a few places that access data without providing a MFP. We should keep this issue around to fix the remaining places.
