### ISSUE TITLE
Avoid packing and immediately unpacking rows in `flat_map`

### ISSUE THREAD

**Issue by antiguru** [MaterializeInc/materialize#8933]
After #8718, we create a permuted row, which we pass to the logic provided to `flat_map`. In most cases, the logic will immediately unpack the row, which leads to a waste of work and resources.

I see two options to fix this:
* Provide a borrowed row aka. `DatumVecBorrow` to the closure, which represents the contents of the expected row.
* Provide a slice of `RefOrMut<Row>` together with a permutation to give the closure a chance to apply the permutation itself.

**Comment by umanwizard** [comment]
I'll take a look at this.

**Comment by umanwizard** [comment]
Nevermind, Moritz is already working on it
