### ISSUE TITLE
Tokio worker threads stuck on particular queries

### ISSUE THREAD

**Issue by atroche** [MaterializeInc/materialize#8978]
### What version of Materialize are you using?

I've found this behaviour both with the official 0.9.11 APT package release, and with a build of 0.9.12-dev I did myself (`f948a6681`).

### How did you install Materialize?

* [ ] Docker image
* [ ] Linux release tarball
* [ ] APT package
* [ ] macOS release tarball
* [ ] Homebrew tap
* [ ] Built from source
* [ ] Materialize Cloud

### What was the issue?

When I run this query:

```
SELECT
  timestamp AS "time",
  sense_battery AS metric
FROM flat_tel
where host = 'doniach'
ORDER BY time desc
limit 500;
```

The result never comes back (my psql client blocks and won't respond to ctrl-C except by printing `Cancel request sent`), and one of my CPU cores becomes pegged at 100% usage. `materialize-dashboard` indicates that it's a tokio worker thread:

![image](https://user-images.githubusercontent.com/29839/140660834-ea3e5153-8b36-49d4-abaf-d5c03b888355.png)

Curiously, when I run that same query with a limit of 400 or less, it returns almost instantly with no problems.

Every time I run one of these queries (with limit >= 500) it pegs another core. I've tried waiting overnight, but it doesn't help. The only way I've found to un-peg my CPU cores is by restarting materialized.

Here are the views I'm using: https://gist.github.com/atroche/0c139e11d4fffc2a00bcf11203dd995b.

I've also found that I have no problems when I run this very similar query, where the only difference is that I'm not filtering by `host`:

```
SELECT
  timestamp AS "time",
  sense_battery AS metric
FROM flat_tel
ORDER BY time desc
limit 50000;
```

Also, if I filter by host but don't order by time then there are no problems:

```
SELECT
  timestamp AS "time",
  sense_battery AS metric
FROM flat_tel
where host = 'doniach'
limit 5000;
```

**Comment by atroche** [comment]
I've uploaded my mzdata folder with `materialize.log` filtered to `trace`.

[mzdata.tar.gz](https://github.com/MaterializeInc/materialize/files/7493088/mzdata.tar.gz)

**Comment by asenac** [comment]
@atroche Thanks for reporting this issue.

I'm unable to find a query like the one in the description getting stuck in the logs provided. The ones with limit >= 500 are not exactly the one in the description but this one:

```
2021-11-07T21:02:55.100275Z TRACE pgwire::codec: cid=5 recv=Parse { name: "", sql: "SELECT\ntimestamp AS \"time\",\n  sense_pending_data\nFROM flat_tel\nwhere host = 'doniach'\norder by timestamp desc\nlimit 5000", param_types: [] }    
```

For all of those, I can see results being returned. Although there are two connections, 6 and 7, that after executing that query and returning 514 rows, disappear from the logs.

Would it be possible to attach `gdb` to the materialized process to get the stack trace of the leaked thread?

**Comment by antiguru** [comment]
Closing this issue because the architecture changed significantly since it was filed. If it still happens, feel free to open again or file a new issue. Thanks for the report!
