### ISSUE TITLE
Sqllogictests hang after ac707749653

### ISSUE THREAD

**Issue by antiguru** [MaterializeInc/materialize#8994]
### What version of Materialize are you using?

According to `git bisect`, this was introduced with ac707749653.

### What was the issue?

Sqllogictest hangs during tests. It seems to be a race condition between the coordinator and other threads, potentially the dataflow client. From my limited debugging, it seems the dataflow client won't be dropped.

The last statement is:

`SELECT ' '::text < ' '::text;`

### Is the issue reproducible? If so, please provide reproduction instructions.

`cargo run --bin sqllogictest --release -- test/sqllogictest/*.slt --workers 1 -vvv`

**Comment by mjibson** [comment]
I'm able to repro this. Investigating.

**Comment by antiguru** [comment]
Fixed by #9004
