### ISSUE TITLE
doc: You can create indexes on sequences of arbitrary expressions (not just columns)

### ISSUE THREAD

**Issue by msudberg** [MaterializeInc/materialize#9010]
### For updates to existing documentation

* What pages are affected?

https://materialize.com/docs/sql/create-index/

* What needs to be added?

- why is this useful?
- possible memory implications?
- examples

Background: https://materializeinc.slack.com/archives/CPNFV9CVB/p1636397821027100

SMEs: @umanwizard, @frankmcsherry

**Comment by morsapaes** [comment]
Duplicate of #10739. Fixed in #10744.
