### ISSUE TITLE
doc: Correct CREATE SINK Syntax

### ISSUE THREAD

**Issue by nmeagan11** [MaterializeInc/materialize#9040]
### For updates to existing documentation

* What pages are affected?

https://materialize.com/docs/sql/create-sink/

* What needs to be changed or added?

The railroad diagram on CREATE SINK is correct, but all the examples are using the old syntax. They should be updated to be like the following:
<pre><code>CREATE SINK hello_sink 
FROM hello 
INTO KAFKA BROKER 'localhost:9092' TOPIC 'hello-sink' 
CONSISTENCY (TOPIC 'hello-sink-consistency' FORMAT AVRO USING CONFLUENT SCHEMA REGISTRY 'http://localhost:8081') 
WITH (reuse_topic=true) 
FORMAT JSON;
</code></pre>

**Comment by morsapaes** [comment]
This has been fixed in #9041. We should double check if the `reuse_topic` guide is also using the outdated syntax, @msudberg .
