### ISSUE TITLE
Explain Kafka's GC's impact on materialized

### ISSUE THREAD

**Issue by sploiselle** [MaterializeInc/materialize#907]
From @frankmcsherry

> It occurs to me here that we'll want to make sure we explain to folks that Kafka's garbage collection has the potential to mess up materialized. If you load from an existing Kafka stream that has been garbage collected, you'll likely get garbage results out of materialized.

This should be documented in the `CREATE SOURCE` doc for the time being.

**Comment by msudberg** [comment]
@frankmcsherry @benesch Do you think this is covered by our existing doc on [compaction](https://materialize.com/docs/ops/deployment/#compaction) and the note on [Kafka log compaction requirements for the Debezium envelope](https://materialize.com/docs/sql/create-source/avro-file/#kafka-topic-requirements), or do we need additional doc?

**Comment by benesch** [comment]
I think that's good enough for now!
