### ISSUE TITLE
doc: HEADER is missing from COPY FROM

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#9072]
This page https://materialize.com/docs/sql/copy-from/ is missing a mention for the `HEADER` option, which is allowed under `FORMAT CSV`

```
COPY t FROM STDIN WITH (FORMAT CSV, QUOTE '|', ESCAPE '#', NULL 'NS', HEADER true)
```

**Comment by jseldess** [comment]
This has been documented in the meantime.
