### ISSUE TITLE
Using a Schema File for Consistency Topic in CREATE SINK

### ISSUE THREAD

**Issue by nmeagan11** [MaterializeInc/materialize#9078]
As seen in our [docs](https://materialize.com/docs/sql/create-sink/#consistency_format_spec), Materialize should be able to use either a schema file or the full schema registry for a consistency topic. For reference, Materialize currently outputs the following for schema files:

<pre><code>CREATE SINK hello_sink
FROM data_offset
INTO KAFKA BROKER 'localhost:9092' TOPIC 'hello-sink'
CONSISTENCY ( TOPIC 'hello-sink-consistency' FORMAT AVRO USING SCHEMA FILE '/tmp/schema' ) 
WITH (reuse_topic=true)
FORMAT JSON;
ERROR:  CONSISTENCY FORMAT AVRO USING SCHEMA FILE '/tmp/schema' not yet supported</code></pre>

**Comment by benesch** [comment]
Ah, ok, so looking at the code it looks like you are _required_ to specify `FORMAT AVRO USING CONFLUENT SCHEMA REGISTRY`. It doesn't really make sense to support `FORMAT AVRO USING SCHEMA FILE`, since you can just pull the defined schema out of the docs. But it would probably make sense to support a bare `FORMAT AVRO` (no `USING` anything) that emits the Avro bytes directly to the topic, without attempting to publish anything to the schema registry.

**Comment by elindsey** [comment]
It looks like there's two separate changes here:

1. The consistency topic is something that we want to control the format of, so it generally doesn't make sense taking the format in file form from the user. We need a docs change to update the railroad showing that only schema registry is supported.
2. It would be nice to support a mode where we're still controlling the format, but we don't require writing the format into csr - like Nikhil mentioned, something like `FORMAT AVRO` and then if users want to consume from the consistency topic they can refer to the schema published in docs (though few users will; the consistency topic primarily exists for materialize's consumption). This would be some work for sources and sinks (probably not a lot). I think this primarily affects JSON formatted reuse_topic Kafka sinks - FORMAT AVRO will almost certainly have a schema registry around already, and non-reuse_topic won't need a consistency topic.

**Comment by elindsey** [comment]
I don't think taking a file for schema makes sense anymore, but I'm leaving this open in case we want to add a static schema for the consistency topic instead of requiring csr (though that's very low priority).

**Comment by bkirwi** [comment]
#11216 removed the consistency topic, and the schema of its replacement is now fixed and private to materialize, so I believe we can close this out.
