### ISSUE TITLE
coordd/dataflowd: Only accept correct configurations

### ISSUE THREAD

**Issue by antiguru** [MaterializeInc/materialize#9083]
From #8947: If dataflowd is started with workers > 1, coord panics as follows unless it has the right --workers setting:

```
thread 'coordinator' panicked at 'assertion failed: count >= 0', /home/pstoev/antiguru-dataflow-client-trait-cluster/src/coord/src/coord.rs:1254:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by frankmcsherry** [comment]
I'm looking through the code now, but I hope that the coordinator eventually should not need to know the number of workers (the `Client` implementation can wrap this).

**Comment by antiguru** [comment]
We removed the `--workers` parameter from coord a while ago.
