### ISSUE TITLE
HIR ⇒ QGM ⇒ MIR support for `Get`

### ISSUE THREAD

**Issue by aalexandrov** [MaterializeInc/materialize#9136]
- For alignment with existing notation, we will name the `BaseTable` box as `Get` instead.
- As part of this issue, one needs to refine the fake `Catalog` implementation, so that the planner can resolve fake tables in the unit tests (see the `test.rs` logic `query_model`).

**Comment by wangandi** [comment]
@asenac Question: When translating the HIR for something like `SELECT * FROM t1 WHERE t1.f1 = 1 UNION ALL SELECT * FROM t1 WHERE t1.f1 = 2` to QGM, should I make sure that there is only one box for `Get t1`? Or is it ok to have multiple `Get t1` boxes, and the excess boxes will be removed at some future normalization/query rewrite stage?

**Comment by asenac** [comment]
I think it's better to keep a hashmap in the hir generator struct with those catalog items we have seen already, so all Gets point to the same box. Eventually we will also have the relation CSE-like transform, but I think this doesn't add too much complexity to the generator code and makes the output of the generator more readable.
