### ISSUE TITLE
Provide a way to extract system metadata/debugging info from one mz instance to another.

### ISSUE THREAD

**Issue by ruchirK** [MaterializeInc/materialize#9155]
We've had a script ( https://gist.github.com/ruchirK/568ea798a5e8ec2b343ebf6dd6f62541 ) that can extract a user's `mz_catalog` (note that this is not the sqlite file that stores source/view definitions, but the set of internal tables and differential logs that have metadata) via a sequence of `SELECT` queries, and let another person analyze the extracted data on another Materialize instance. This has proven really useful in a few instances because the system catalog contains a lot of [metadata](https://materialize.com/docs/sql/system-catalog/) about the currently running Materialize instance, and we have a lot of tooling such as the memory visualizer built on top of those. Empirically, there's been at least one case where using this script sped up the debugging cycle for a on-prem user as we didn't have to go back and forth asking them to show us the results of various queries / memory visualizations.

The script as it exists is a pain to use for multiple reasons. Users need to run the provided SQL queries with just the right `psql` incantation, and then the code to turn those results into a series of `CREATE TABLE` and `INSERT` statements is fiddly. I _think_ a nice starting point would be to have all of the select queries folded into one or two select statements that can live in Materialize as an unmaterialized system view, so that getting the data out is as simple as `SELECT * FROM this_view;` for the user.

I don't currently have better ideas for rehydrating a new mz instance with the extracted data.

There's some precedent for a command like this from cockroach https://www.cockroachlabs.com/docs/stable/cockroach-debug-zip.html

cc: @elindsey @uce @andrioni

**Comment by ruchirK** [comment]
This is also partially related to https://github.com/MaterializeInc/materialize/issues/1267

**Comment by benesch** [comment]
Fixed via platform, where we can execute this kind of debugging information directly against customer environments with their permission.
