### ISSUE TITLE
dataflow: flow control

### ISSUE THREAD

**Issue by antiguru** [MaterializeInc/materialize#9161]
The dataflow layer currently has no mechanism to prevent source operators from producing more output than the system can handle. This can help preventing loss-of-interactivity problems.

We'd need to add a mechanism that allows source operators to throttle the rate at which they produce data, probably by letting them observe the progress of computation through a source-independent interface.

**Comment by uce** [comment]
From the dataflow side, we should wait until we make more progress on ingestd before tackling this.
