### ISSUE TITLE
doc: feature description

### ISSUE THREAD

**Issue by AtelLex** [MaterializeInc/materialize#9174]
- 

### For updates to existing documentation

* What pages are affected?

* What needs to be changed or added?

### For new documentation

* Feature description

* Engineering ticket # (tracking ticket if one exists)

* Design documents such as technical specs, product specs, or test files
@materializer

**Comment by morsapaes** [comment]
Hey, @AtelLex! Could you please add a description to the issue (if opening the issue was intentional)?
