### ISSUE TITLE
Add UNIQUE KEYS field to all boxes

### ISSUE THREAD

**Issue by aalexandrov** [MaterializeInc/materialize#9180]
- `Get` boxes should have a dedicated field with that information.
- In general, this can be inferred as a derived attribute using the framework suggested in [#10237]().

**Comment by wangandi** [comment]
Unique keys have already been added to the Get box as of #9477, though its format has not been finalized. Unique keys have not yet been propagated to all boxes.

**Comment by wangandi** [comment]
More details here: https://github.com/MaterializeInc/materialize/pull/9715/files#r773591858
