### ISSUE TITLE
persist: No logging at all during recovery/startup 

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#9242]
### What was the issue?

There are no logging messages around recovery on startup. At the very least we need a message:
- when recovery starts
- (optionally) when the ingestion vs. retraction phases of the recovery start and complete
- when recovery completes and the source is all good to use

With large data sizes, recovery can take an arbitrary amount of time and therefore proper communication to the user is key. Other database products will give a clear indication that they are in a recovery state and will even provide a progress indicator of some sort in the logs.

At some later point I guess those would be different statuses of the source , e.g. "recovering", "ready", etc?

### Is the issue reproducible? If so, please provide reproduction instructions.

As revealed by #9123, recovery was actually making progress, albeit very slowly, but it was not reflected in the logs in any way.

**Comment by aljoscha** [comment]
Closing this because current persist/storage architecture has moved quite a bit beyond this.

@philip-stoev Please yell at me if you'd like to keep this open.

fyi @danhhz
