### ISSUE TITLE
Do something about imbalance on Kafka readers

### ISSUE THREAD

**Issue by umanwizard** [MaterializeInc/materialize#9244]
Long Slack discussion: https://materializeinc.slack.com/archives/C01BE3RN82F/p1637631684275200

Since the Kafka operators for a given topic only runs on as many workers as there are partitions, if they take non-trivial time, they can cause imbalance throughout the downstream operators, tanking performance.

We should find a way to address this problem, perhaps by moving them out of Timely entirely (this arises naturally from the plans for a separate `ingestd` service)

**Comment by benesch** [comment]
This is fixed thanks to roundtripping through persist. Compute dataflows can read from a source with more parallelism than is used during ingestion.
