### ISSUE TITLE
Protobuf + Confluent Schema Registry doesn't work

### ISSUE THREAD

**Issue by benesch** [MaterializeInc/materialize#9250]
If you create a Protobuf-formatted Kafka topic using the Confluent stack (e.g. `kafka-protobuf-console-producer`) and then attempt to read it with Materialize, it won't actually work. The Confluent stack will add the CSR magic to the start of each record, which Materialize doesn't expect.

The problem is that our tests don't use the Confluent stack. Our testdrive tests don't write the CSR magic, so it looks like everything works.

**Comment by benesch** [comment]
The problem is actually much worse than I thought. The CSR magic for protobuf messages is _different_ than it is for Avro messages. The question that I've been asking for a while is "how does the schema registry figure out _which_ protobuf message in a .proto file to use?" It turns out the answer is in the CSR magic.

Protobuf CSR magic starts with the same magic zero byte followed by a 32-bit schema ID. Then comes a zig zag var int indicating the number of elements in an array of zig zag var ints that immediately follows. This array specifies the index of the protobuf message in the .proto file; because protobuf messages can be nested, it needs to be an array rather than a single index. As an optimization, if the array is `[0]`, it is encoded as the byte `[0]` rather than `[0, 0]`.

This is kind of a disaster for us. Unlike with Avro, where topics are associated with a single shape, with Protobuf, topics are associated with a schema that contains _multiple_ shapes, and we won't know which are in play until we actually read messages out of the topic. That means it's impossible at `CREATE SOURCE` time to automatically determine which message to use to define the shape of the relation... and if the user is pushing two different messages through the topic, we're hosed.

I think we'll need to adjust the syntax of `CREATE SOURCE` to force the user to specify _which_ Protobuf message they mean. E.g. via a `MESSAGE` clause:

```
CREATE SOURCE ...
FORMAT PROTOBUF
USING CONFLUENT SCHEMA REGISTRY 'http://...' MESSAGE 'Blah'; 
```

(Today we assume that the first protobuf in the message is the relevant one.)

I'm not really sure what we do when we see a message in the topic with a `(schema_id, message_index)` header that doesn't match the one we saw when the `CREATE SOURCE` command ran. We could throw an error if it doesn't match exactly, which would be the safest option. But it would preclude people from ever updating their schema, even backwards compatibly... and it's not easy to determine whether a given `(schema_id, message_index)` pair corresponds to the same logic message as another `(schema_id, message_index)` pair. So maybe we just blindly accept whatever `(schema_id, message_index)` pairs we see, and hope it all check sout?

**Comment by benesch** [comment]
Here's the concrete proposal to make this _basically_ work. We leave the syntax alone, i.e.:

```sql
CREATE SOURCE ...
FORMAT PROTOBUF
USING CONFLUENT SCHEMA REGISTRY 'http://...'; 
```

We continue to assume that the first message in the .proto file fetched from the registry is the relevant one. But! If there are multiple messages in that .proto, we return an error during purification instead of allowing the `CREATE SOURCE` to proceed.

Then, in the dataflow layer, I propose that we ignore the `schema_id` in the CSR magic, on the theory that folks always evolve Protobuf messages backwards compatibly. But we decode the next `message_index` byte and check that it is 0. If it is not, we produce an error.

Testdrive needs to be adjusted so that the `kafka-ingest` action takes a `confluent-wire-format` argument:

```
$ kafka-ingest topic=name format=protobuf descriptor-file=file.pb message=.Message  confluent-wire-format=true
```

When this parameter is true, `kafka-ingest` should add the CSR magic with a dummy schema ID and a message ID of 0. That parameter should be set to true for the `kafka-ingest` calls in protobuf-import.td. That'll be enough to test that we're handling things properly in the happy case.

We should also add an additional test case, probably in a new file, that attempting to create a Protobuf source from a schema registry topic whose .proto file contains multiple messages fails as described above.

Sorry, a bit jumbled! @guswynn lemme know if any of that doesn't make sense.

**Comment by benesch** [comment]
Huh, on the bright side, it looks like we never documented this! No wonder no one has complained. So I guess the followup task here is to document this syntax.

**Comment by quodlibetor** [comment]
For posterity: currently testdrive does not emit confluent wire format magic for protobuf messages, and the protobuf decoding code does not have any knowledge of confluent wire format magic.
