### ISSUE TITLE
NO_PROXY environment variable is not checked for correctness

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#9265]
### What version of Materialize are you using?

From the shell:

```
b73f65e7c85cf3f51fc2408579c64afc2aeb5f63

```

### What was the issue?

You could set your e.g. NO_PROXY variable to an invalid value, such as one containing quotes and whatnot. Our current parsing algorithm will split it along the `,` delimiter, but will fail to notice that the hostnames thus produced are not valid.

### Is the issue reproducible? If so, please provide reproduction instructions.

set PROXY to some valid value and  NO_PROXY TO `'localstack'` (note quotes) . The proxy will be used for everything, including access to the localstack hostname.

**Comment by benesch** [comment]
So this is working as “intended” right now: https://github.com/MaterializeInc/materialize/blob/main/src/http-proxy/src/lib.rs#L105

As far as I know this is how other tools that support NO_PROXY handle invalid errors too. There just isn’t a great moment/channel to report those errors. Are you aware of any tools that do report errors with the NO_PROXY var?

**Comment by philip-stoev** [comment]
No, I have no supporting arguments for this. The only hypothetical concern is that by making a mistake in the NO_PROXY directive, traffic could be sent in an undesirable direction over the network, which would be a theoretical security risk.

In the absence of a precedent on how other tools handle this, I am closing this ticket.
