### ISSUE TITLE
sql: add a way to notify users of potentially dangerous things in created sinks/sources

### ISSUE THREAD

**Issue by aljoscha** [MaterializeInc/materialize#9333]
This has come up in the context of #8643 but could be useful for other things.

Right now, we only issue warnings in the logs, but those are easy to ignore. It would be better to issue a warning to users right in the SQL client, for example using a pgwire `NoticeResponse` as outlined in #4290.

**Comment by benesch** [comment]
Calling this one done, at last! @sploiselle added the infrastructure for in-planner notices in #20021 (what this issue was about, strictly speaking), and @bkirwi is changing the `warn!` log that inspired this issue in the first place to a notice in #20008.
