### ISSUE TITLE
Reconsider `Mir{Relation|Scalar}Expr::visit_*` method signatures

### ISSUE THREAD

**Issue by aalexandrov** [MaterializeInc/materialize#9334]
After the changes introduced by the PRs that resolve #9000 and #9332, the `visit_*` method variants defined on `MirRelationExpr` and `MirScalarExpr` accept infallible functions, but may still return a `RecursionLimitError`. Consequently, methods at the bottom of the call chain such as `visit_children` and `visit_mut_children` currently end with an `.expect(...)` call which might cause runtime panics.

We can resolve this issue in one of two ways:

1. Change the signature of all infallible `visit_` methods to `Result<(), TransformError>`.
2. Eliminate the possibility of `RecursionLimitError` returned during structured tree traversal.

The downside of (1), is that we will loosen the model for clients that know the passed `accept` function is infallible. The downside of (2) is that emulating the stack with an iterative solution might be slower than relying on the program stack. If this difference is too big, we can probably have two implementations and fallback to the iterative strategy only when needed.

Regardless of the solution, the commits in #9293 change a lot of client code to use `try_visit` instead of `visit`, and after this issue is closed this code can be reverted and the client callback functions simplified.

Once we have a solution here, we can proceed with #9396.

**Comment by aalexandrov** [comment]
I'm summarizing the result of a short spike where I attempted to implement all `MirScalarExprVisitor::*visit*` methods in an iterative manner.

```rust
diff --git a/src/expr/src/scalar/mod.rs b/src/expr/src/scalar/mod.rs
index 0079b1a5b..9a578f846 100644
--- a/src/expr/src/scalar/mod.rs
+++ b/src/expr/src/scalar/mod.rs
@@ -1031,13 +1031,80 @@ impl MirScalarExprVisitor {
         }
     }
 
+    /// Applies an infallible immutable `f` to each `expr` child of type `MirScalarExpr` in reverse order.
+    pub fn visit_children_rev<'a, F>(&self, expr: &'a MirScalarExpr, mut f: F)
+    where
+        F: FnMut(&'a MirScalarExpr),
+    {
+        match expr {
+            MirScalarExpr::Column(_) => (),
+            MirScalarExpr::Literal(_, _) => (),
+            MirScalarExpr::CallNullary(_) => (),
+            MirScalarExpr::CallUnary { expr, .. } => {
+                f(expr);
+            }
+            MirScalarExpr::CallBinary { expr1, expr2, .. } => {
+                f(expr2);
+                f(expr1);
+            }
+            MirScalarExpr::CallVariadic { exprs, .. } => {
+                for expr in exprs.iter().rev() {
+                    f(expr);
+                }
+            }
+            MirScalarExpr::If { cond, then, els } => {
+                f(els);
+                f(then);
+                f(cond);
+            }
+        }
+    }
+
+    /// Applies an infallible mutable `f` to each `expr` child of type `MirRelationExpr` in reverse order.
+    pub fn visit_mut_children_rev<'a, F>(&self, expr: &'a mut MirScalarExpr, mut f: F)
+    where
+        F: FnMut(&'a mut MirScalarExpr),
+    {
+        match expr {
+            MirScalarExpr::Column(_) => (),
+            MirScalarExpr::Literal(_, _) => (),
+            MirScalarExpr::CallNullary(_) => (),
+            MirScalarExpr::CallUnary { expr, .. } => {
+                f(expr);
+            }
+            MirScalarExpr::CallBinary { expr1, expr2, .. } => {
+                f(expr2);
+                f(expr1);
+            }
+            MirScalarExpr::CallVariadic { exprs, .. } => {
+                for expr in exprs.iter_mut().rev() {
+                    f(expr);
+                }
+            }
+            MirScalarExpr::If { cond, then, els } => {
+                f(els);
+                f(then);
+                f(cond);
+            }
+        }
+    }
+
     /// Post-order immutable infallible `MirScalarExpr` visitor for `expr`.
     pub fn visit_post<'a, F>(&self, expr: &'a MirScalarExpr, f: &mut F)
     where
         F: FnMut(&'a MirScalarExpr),
     {
-        self.visit_children(expr, |e| e.visit_post(f));
-        f(expr);
+        let mut stack = vec![Visit::Pre(expr)];
+        loop {
+            match stack.pop() {
+                Some(Visit::Pre(expr)) => {
+                    stack.push(Visit::Post(expr));
+                    self.visit_children_rev(expr, |e| stack.push(Visit::Pre(e)))
+                }
+                Some(Visit::Post(expr)) => f(expr),
+                None => break,
+            }
+        }
     }
 
     /// Post-order mutable infallible `MirScalarExpr` visitor for `expr`.
@@ -1045,8 +1112,17 @@ impl MirScalarExprVisitor {
     pub fn visit_mut_post<'a, F>(&self, expr: &'a MirScalarExpr, f: &mut F)
     where
         F: FnMut(&mut MirScalarExpr),
     {
-        self.visit_mut_children(expr, |e| e.visit_mut_post(f));
-        f(expr);
+        let mut stack = vec![VisitMut::Pre(expr)];
+        loop {
+            match stack.pop() {
+                Some(VisitMut::Pre(expr)) => {
+                    stack.push(VisitMut::Post(expr));
+                    self.visit_mut_children_rev(expr, |e| stack.push(VisitMut::Pre(e)))
+                }
+                Some(VisitMut::Post(expr)) => f(expr),
+                None => break,
+            }
+        }
     }
 
     /// A generalization of `visit_mut`. The function `pre` runs on a
@@ -1078,6 +1154,16 @@ impl CheckedRecursion for MirScalarExprVisitor {
     }
 }
 
+enum Visit<'a, T> {
+    Pre(&'a T),
+    Post(&'a T),
+}
+
+enum VisitMut<'a, T> {
+    Pre(&'a mut T),
+    Post(&'a mut T),
+}
+
 #[derive(
     Ord, PartialOrd, Clone, Debug, Eq, PartialEq, Serialize, Deserialize, Hash, MzEnumReflect,
 )]

```

Unfortunately, the `visit_mut_post` does not compile, because you cannot have mutable references to a parent and it's children at the same time. The solution can be probably made to work with some unsafe block.

**Comment by petrosagg** [comment]
Posting result of slack conversion:

> We can resolve this issue in one of two ways:

There is also a third way of using `stacker::maybe_grow` directly without adding the machinery of recursion limits that we use in the `sql` crate. This will keep allocating memory as necessary as the algorithm recurses just like an iterative solution would

**Comment by aalexandrov** [comment]
I agree that we should probably go with the `stacker::maybe_grow` because it's impossible to create a iterative mutable post-visit traversal as safe code in rust (the explicit stack that is modeled as a `Vec` in this solution will need to keep a mutable reference to both the parent node and all it's children).

**Comment by aalexandrov** [comment]
What remains to discuss here then is the type of `*visit*` methods that we want to generally provide for a recursively defined IR (such as `MirRelationExpr` and `MirScalarExpr`) and their behavior.

At the moment, based on the methods defined in `MirRelationExpr` and `MirScalarExpr`, we seem to have a space of available methods that is spanned by the following (otrhogonal) dimentions:

- Is the callback function fallible or not?
  - Yes (prefix `try_`).
  - No (prefix empty).
- Is the callback function mutable?
  - Yes (suffix 1 `_mut`).
  - No (suffix 1 empty).
- What is visited? Available options are:
  - non-recursive, visits only the children (suffix 2 `_children`), 
  - recursive, visits all nodes in pre-order / top-down (suffix 2 `_pre`), 
  - recursive, visits all nodes in post-order / bottom-up (suffix 2 `_post`).

In total, this results in 12 possible visit methods, and the location of each one on this coordinate system can be inferred from its name. For example:

- `try_visit_mut_children` is the variant for a fallible, mutable callback that visits only the children of the current node, and
- `visit_post` is the variant for an infallible, immutable callback that visits all nodes bottom-up.

All methods for a specific recursive type `T ∊ { MirRelationExpr, MirScalarExpr }` are implemented in a dedicated `${T}Visitor` struct which implements the `ore::stack::CheckedRecursion` trait. The corresponding `T` implementation has identical `$method` definitions with implementations that proxy to `${T}Visitor::new().${method}(...)`.

What remains to be fixed are the return types and stack safety guarantees of all recursive methods.

The current situation is as follows:

- Recursive visit methods that accept an fallible callback return a value of type `Result<(), E>`.
- Recursive visit methods that accept an infallible callback return a value of type `()`.

The stack safety guarantees follow these type restrictions. More specifically:

- Recursive visit methods that accept an fallible callback are wrapped in a `self.checked_recur( ... )` call.
- Recursive visit methods that accept an infallible callback are wrapped in a `ore::stack::maybe_grow( ... )` call.

This is somewhat odd, because the fallible variants will impose a hard limit on the maximum depth of the processed tree (currently 2048), while the infallible counterparts cannot do that and must resort to unbounded stack growth because there is no sane way to propagate the `RecursionLimitError` to their clients.

Possible ways of moving forward are:

1. Keep things as they are.
2. Change the return type of recursive visit methods that accept an infallible callback to `Result<(), RecursionLimitError>`.

**Comment by teskje** [comment]
From a recent discussion with @aalexandrov: We want to enforce the recursion limit also for infallible visitor methods (option 2 above). But we also expect adjusting all client code to handle the new possible error in one go would be a lot of work, so we will first deprecate the existing infallible visitor methods by renaming them with a `_deprecated` suffix. This gives us room to adjust the client code in smaller chunks, while new code can already start using the "correct" versions of the visitor methods.
