### ISSUE TITLE
QGM: Support for testing full range of scalar functions

### ISSUE THREAD

**Issue by wangandi** [MaterializeInc/materialize#9347]
The TestCatalog for QGM tests allow parsing most functions, but it cannot parse casts because that would require the TestCatalog to be able to parse types. See https://github.com/MaterializeInc/materialize/pull/9272#issue-1062576712

We could work around giving the TestCatalog full function parsing ability by the constructing an Hir*Expr directly, either using our existing DSL for creating Enums/Structs or using a combination of DSL and SQL.

**Comment by antiguru** [comment]
QGM work has been suspended.
