### ISSUE TITLE
Support Metabase

### ISSUE THREAD

**Issue by andrioni** [MaterializeInc/materialize#9373]
[Metabase](https://www.metabase.com/) is a popular open source data visualization/data exploration/BI tool.

This is an umbrella issue to track the work required to make Metabase work out of the box with Materialize, when using the Postgres connector (via pgjdbc).

Related issue: #3727

## Open issues
- [x] #9366
- [x] #9374
- [x] #9375
- [x] #9376

**Comment by chaas** [comment]
@morsapaes based on our docs we successfully support Metabase, and all the todos on this list are done. Am I good to close this out, or is there more work we want to track for Metabase?

**Comment by morsapaes** [comment]
This can be closed! There are no more blockers for Metabase. We've built a custom Metabase driver, so we'll track follow-up work in the [`metabase-materialize-driver`](https://github.com/MaterializeInc/metabase-materialize-driver) repo and open issues here when input from Surfaces is needed. Thanks, @chaas!
