### ISSUE TITLE
Postgres source receiving error: ERROR: invalid record length at 0/6AAF3E88: wanted 24, got 0

### ISSUE THREAD

**Issue by royroyisroy** [MaterializeInc/materialize#9409]
### What version of Materialize are you using?
```
v0.10.1-dev (eaa722e27)
```

### How did you install Materialize?

* [x] Docker image
* [ ] Linux release tarball
* [ ] APT package
* [ ] macOS release tarball
* [ ] Homebrew tap
* [ ] Built from source
* [ ] Materialize Cloud

### What was the issue?
received error when using postgres as source for a while.
```
ERROR:  Source error: materialize.public.mz_source: file IO: db error: ERROR: invalid record length at 0/6AAF3E88: wanted 24, got 0
```

```
> show create source mz_source;

materialize.public.mz_source | CREATE SOURCE "materialize"."public"."mz_source" FROM POSTGRES CONNECTION 'host=postgres port=5432 user=admin ...' PUBLICATION 'mz_source' SLOT 'materialize_fee00de42f934323a9973e2aa4fa5982'
(1 row)
```

### Is the issue reproducible? If so, please provide reproduction instructions.
no. happened twice

**Comment by petrosagg** [comment]
@royroyisroy could you describe a bit more your database setup? Searching online this seems to be coming from postgres itself when it finds a corrupted WAL log file. It's unclear if it's safe to ignore in materialize (some people suggest that it is on the internet), but I may be able to make sense of it with more information

**Comment by benesch** [comment]
Closing as stale. I don't think we've seen this since.
