### ISSUE TITLE
Materialized view only at most get updated once per second despite frequent insertion to postgres table

### ISSUE THREAD

**Issue by royroyisroy** [MaterializeInc/materialize#9410]
### What version of Materialize are you using?
```
       mz_version
-------------------------
 v0.10.1-dev (eaa722e27)

```

### How did you install Materialize?

* [x] Docker image
* [ ] Linux release tarball
* [ ] APT package
* [ ] macOS release tarball
* [x] Homebrew tap
* [x] #9411
* [ ] Materialize Cloud

### What was the issue?
basically I have created a materialized view (with postgres as a source).
The underlying table is inserted in a frequency like 100 insertion per second.
and when I run COPY (TAIL balance) TO STDOUT I can see that the it is only updated at a rate of 1 update / second.
even if I created a SINK from the materialized view to kafka broker,
I can still only see update messages at a rate of 1 update / second . which is really bad .
the materialzed view is super simple ( just a sum of two columns). (edited) 
8:42
the update frequency is so constant that I almost feel like this is hard coded to be 1 update / second
is there any configuration / limit that I can adjust to reflect more timely updates?

### Is the issue reproducible? If so, please provide reproduction instructions.
yes.  the underlying table is been updated at a rate of 100 insertion per seconds. but the sink only reflects at a rate of 1 update / second.
![image](https://user-images.githubusercontent.com/93712896/144539797-2474318b-1a2e-4611-9fc5-6d1b1bc62ece.png)

**Comment by ruf-io** [comment]
Hi @royroyisroy - You're right it is hardcoded. Take a look at the WITH option named [`timestamp_frequency_ms`](https://materialize.com/docs/sql/create-source/avro-kafka/#:~:text=for%20this%20feature.-,timestamp_frequency_ms,int,-Default%3A%201000.%20Sets) - I'm linking you to the Kafka Docs page but the same option can be used with any SOURCE including Postgres. 

(We need to update our documentation to reflect that.)

**Comment by msudberg** [comment]
Looks like we already did this back in October: https://github.com/MaterializeInc/materialize/pull/8659
