### ISSUE TITLE
panic: Attempted to downgrade a CapabilitySet with a frontier containing an element that was not beyond an element within the set

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#9419]
### What version of Materialize are you using?

From the shell:

```
???
```

### What was the issue?

This happened to me once as I was running the kafka persistence tests . Most likely an existing Mz container was repurposed when the tests were re-run.

### Is the issue reproducible? If so, please provide reproduction instructions.

TBD

**Comment by ruchirK** [comment]
I ran into this today as well.
