### ISSUE TITLE
TAIL: Communicate metadata independently of row data

### ISSUE THREAD

**Issue by antiguru** [MaterializeInc/materialize#9439]
Extend the communication protocol such that the dataflow layer sends structured initial metadata instead of encoding it implicitly into rows.

**Comment by frankmcsherry** [comment]
I believe this may be done. We do send structured metadata, and have the coordinator encode it in rows. @umanwizard to confirm.

**Comment by umanwizard** [comment]
I believe this is done too, unless I misinterpreted it.
