### ISSUE TITLE
Rework the internal TAIL protocol between dataflow and coordinator

### ISSUE THREAD

**Issue by antiguru** [MaterializeInc/materialize#9443]
The internal TAIL protocol for communicating updates from the dataflow layer back to the coordinator shows several deficits. It needs to improve the following:
* [x] #9442
* [x] #9440
* [x] #9439
* [x] #9446
* [x] #9479
* [x] #9502
* [ ] #10545

**Comment by umanwizard** [comment]
Should we remove #9441 from the list?

**Comment by antiguru** [comment]
I'm closing this issue because all but one task have been finished, and the last remaining task is of low priority.
