### ISSUE TITLE
TAIL: Create comprehensive test suite

### ISSUE THREAD

**Issue by antiguru** [MaterializeInc/materialize#9446]
Currently, tests for TAIL are limited to simple test drive tests. Test drive limits what we can test because the TAIL data encodes timestamps, which are different with every run. Test drive does not work well with such scenarios, relying on regex substitution to canonicalize data.

This makes it impossible to detect bugs based on errors in the timestamp logic through test drive. I propose the following to improve the situation:
* Create a Python-based test to validate timestamps.
* Tail from a source that ingests data in several steps.
* Validate that each intermediate output is well-formed:
  * Tails emit data in time-order
  * Tails are complete: they emit all data that should be visible
  * If progress updates are enabled, data is interleaved with progress updates
  * Progress updates follow frontier semantics: data before the progress update <= frontier, data following the progress update > frontier (for total orders, general partially-ordered time relevant at a later time)

**Comment by benesch** [comment]
> Currently, tests for TAIL are limited to simple test drive tests.

This isn't true, actually! There's a fairly comprehensive set of Rust tests for `TAIL` here: 

https://github.com/MaterializeInc/materialize/blob/978f0b6de2d6df2df2a6ee52de0877d4a6a81770/src/materialized/tests/sql.rs#L153-L781

Those would have to be adapted to run against a distributed coordd/dataflowd setup, but I think they cover everything you've listed!

**Comment by antiguru** [comment]
Oh, neat! I'll take a look at this.
