### ISSUE TITLE
sql: add support for `pg_type_is_visible`

### ISSUE THREAD

**Issue by mkysel** [MaterializeInc/materialize#9474]
```
pg_type_is_visible ( type oid ) → boolean

Is type (or domain) visible in search path?
```

**Comment by mkysel** [comment]
@sploiselle, @mjibson - I believe that our current RBAC rules would mean that all existing types are visible to all users. Does that mean that we can simply always return `TRUE`?

**Comment by mjibson** [comment]
It's also about search path. I think this function is almost identical to `pg_table_is_visible`. I think that function has a bug though, if there are multiple schemas with the same name.

**Comment by mkysel** [comment]
`pg_table_is_visible` is 
```(SELECT s.name = ANY(current_schemas(true))
                     FROM mz_catalog.mz_objects o JOIN mz_catalog.mz_schemas s ON o.schema_id = s.id
                     WHERE o.oid = $1)
```
OIDs should be unique, so the function should always be correct. But there is definitely some issues around finding the OID of a table (#9484). Luckily to us, I don't think that it prevents us from implementing pg_type_is_visible.
