### ISSUE TITLE
`pg_get_constraintdef` (function)

### ISSUE THREAD

**Issue by guswynn** [MaterializeInc/materialize#9483]
Existing support:

* We have a definition for [the `pg_constraint` table](https://github.com/MaterializeInc/materialize/blob/83afaf784ac21b9192a4a70aa8f3c6f732a37a97/src/coord/src/catalog/builtin.rs#L1569-L1601)
  * In particular, we guarantee that that table is always empty: https://github.com/MaterializeInc/materialize/blob/83afaf784ac21b9192a4a70aa8f3c6f732a37a97/src/coord/src/catalog/builtin.rs#L1598
  * **Unknown** to me is if we have the ability to even express constraints in materialize, nevermind support for exposing it in this way. It's plausible that a correct implementation of this function right now is just to return null, and add a comment to the `WHERE false` above stating that this needs to be updated when that table can be populated.

This is an example PR adding a SQL function, which doesn't relate to this except that it shows all the places in our codebase that need to be touched for this kind of thing: #9486 , and here's [an example of an always null function](https://github.com/MaterializeInc/materialize/blob/83afaf784ac21b9192a4a70aa8f3c6f732a37a97/src/sql/src/func.rs#L1588-L1593).

**Comment by andrioni** [comment]
Closed by #9494.
