### ISSUE TITLE
Push metadata demands into SourceOutput

### ISSUE THREAD

**Issue by quodlibetor** [MaterializeInc/materialize#9515]
Currently [`SourceOutput` contains some generic metadata](https://github.com/MaterializeInc/materialize/blob/89209f64e93ddfa513338bc4d47a327d40968655/src/dataflow/src/source/mod.rs#L125-L140) in addition to the value. The only thing that is guaranteed to exist for every source type is actually the value.

As a sketch, a different and significanlty more generic solution would be if every [`SourceConfig`](https://github.com/MaterializeInc/materialize/blob/89209f64e93ddfa513338bc4d47a327d40968655/src/dataflow/src/source/mod.rs#L87-L123) were provided with the metadata items required and emit them as a single row, with a `RelationDesc` (or a similiar structure) that explains how items should be extracted by envelope processing.

```rust
pub struct SourceConfig {
    // .. existing fields ..
    /// Which fields to insert in the metadata row
    metadata_items: MetadataVec,
    /// Extracted metadata description
    metadata_desc: RelationDesc,
}

/// A record produced by a source
#[derive(Clone, Serialize, Debug, Deserialize)]
pub struct SourceOutput<V>
where
    V: Data,
{
    /// The record's value
    pub value: V,
    /// All expected metadata
    pub metadata: Row
}
```

The exact efects on planning etc would need to be mapped out in more detail. This is related to, but distinct from, our desire to push generic demand information earlier into source decoding/config.

**Comment by benesch** [comment]
This has been thoroughly refactored since this issue was filed. The current `SourceOutput` has a `metadata: Row` field, as described by this issue.
