### ISSUE TITLE
Support SQLAlchemy's `get_pk_constraint` for pg dialect

### ISSUE THREAD

**Issue by andrioni** [MaterializeInc/materialize#9532]
`get_pk_constraint` is one of SQLAlchemy's [introspection functions](https://github.com/sqlalchemy/sqlalchemy/blob/8d28bd8d4a0acc209884d29729020506a46f8bd4/lib/sqlalchemy/dialects/postgresql/base.py#L3880-L3929), and it runs the following query for Postgres versions >= 8.4:

```sql
SELECT a.attname
FROM pg_attribute a JOIN (
    SELECT unnest(ix.indkey) attnum,
           generate_subscripts(ix.indkey, 1) ord
    FROM pg_index ix
    WHERE ix.indrelid = :table_oid AND ix.indisprimary
    ) k ON a.attnum=k.attnum
WHERE a.attrelid = :table_oid
ORDER BY k.ord
```

There is an alternative query without `unnest` or `generate_subscripts` for versions < 8.4, but since we declare ourselves to be PostgreSQL 9.6 (via `pg_catalog.version()`), we don't hit that codepath.

Related to #9245 (as this function is called by Superset).

Blocked by:
- [ ] #1546 
- [x] #9200

**Comment by chaas** [comment]
As per

https://github.com/MaterializeInc/materialize/pull/9988#issuecomment-1011314310

and the fact that I'm able to execute this query in the current version of Materialize, I'm marking this as fixed. Please reopen if that's not the case.
