### ISSUE TITLE
Upsert may store keys twice in upsert-tracking state

### ISSUE THREAD

**Issue by quodlibetor** [MaterializeInc/materialize#9551]
`upsert.rs` keeps a hash map of all the data we've ever seen around, we believe that it stores Kafka keys as both the key of the hashmap, and as the prefix of the row in the hashmap. Ideally we would not do that.

**Comment by ruchirK** [comment]
this was investigated in detail in this slack thread https://materializeinc.slack.com/archives/CMH6PG4CW/p1638353682246200 and relates to this github issue https://github.com/MaterializeInc/materialize/issues/9369

**Comment by aljoscha** [comment]
Gentle reminder that there is both `persistent_upsert()` and `upsert_core()`. So you might want to consider fixing both of these if both suffer from the same issue. `persistent_upsert()` started as a fork of `upsert_core()` and is the version that is used by persistent sources (only `KAFKA` with `ENVELOPE UPSERT` for now).

**Comment by guswynn** [comment]
`UPSERT` and `DEBEZIUM UPSERT` have been merged, the only outstanding impl is `persistent_upsert`, which is pending conversation with @aljoscha

**Comment by guswynn** [comment]
I think this is as efficient as its going to get, and `persistent_upsert` is long-dead
