### ISSUE TITLE
persistence: SELECTs against persisted tables and any dependent materialized views are delayed by up to min_step_interval

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#9608]
### What version of Materialize are you using?

From the shell:

```
v0.11.1-dev (3901cd3e1)
```

### What was the issue?

This is most likely known or expected but it does not have a specific tracking ticket.

Not just INSERTS, but also SELECTs against the persisted table and any derived materialized views are subject to a delay of up to min_step_interval. This happens even in the absence of any INSERT activity.

Therefore, if one has a small persisted table to hold e.g. a state code to state name mapping, it will impact the `SELECT` performance of any materialized views that use it.

The current default for the `min_step_interval` appears to be 1 second.

### Is the issue reproducible? If so, please provide reproduction instructions.

With `--timestamp-frequency 5s`:

```
materialize=> DROP SCHEMA public CASCADE;
DROP SCHEMA
materialize=> CREATE SCHEMA public;
CREATE SCHEMA
materialize=> \timing on
Timing is on.
materialize=> CREATE TABLE ten (f1 INTEGER);
CREATE TABLE
Time: 36.323 ms
materialize=> INSERT INTO ten VALUES (0),(1),(2),(3),(4),(5),(6),(7),(8),(9);
INSERT 0 10
Time: 8.749 ms
materialize=> 
materialize=> CREATE MATERIALIZED VIEW v1 AS
materialize->   SELECT
materialize->   a1.f1 +
materialize->   (a2.f1 * 10) +
materialize->   (a3.f1 * 100) +
materialize->   (a4.f1 * 1000) +
materialize->   (a5.f1 * 10000) AS f1
materialize->   FROM ten AS a1, ten AS a2, ten AS a3, ten AS a4, ten AS a5, ten AS a6;
CREATE VIEW
Time: 29.269 ms
materialize=> 
materialize=> SELECT COUNT(*) = 1000000 FROM v1;
 ?column? 
----------
 t
(1 row)

Time: 5008.213 ms (00:05.008) <- HERE
```

**Comment by sploiselle** [comment]
Just noting that spoke with @danhhz today and he said his team is aware of this issue and that he believes his team is capable of fixing it (i.e. doesn't sound like a Coord bug).

**Comment by aljoscha** [comment]
This should not be an issue anymore, with all the recent work around timestamp selection.

@jkosh44 Do you have an opinioin? Please re-open if you think this specific issue is still a thing.

fyi: @danhhz

**Comment by jkosh44** [comment]
This is fixed for tables, but may still exist to some extent for materialized views. #13840 covers the issue for materialized views though.
