### ISSUE TITLE
persist: crash with persistent kafka upsert source with a byte/text key

### ISSUE THREAD

**Issue by ruchirK** [MaterializeInc/materialize#9614]
I'm crashing with the following log output / stack trace

```
materialized v0.12.1-dev (54b2775d7) listening on 0.0.0.0:6875...
2021-12-15T19:01:04.823846Z  INFO coord::catalog: create source materialize.public.perf_upsert_source (u1)
2021-12-15T19:01:04.824143Z  INFO coord::catalog: create index materialize.public.perf_upsert_source_primary_idx (u2)
2021-12-15T19:01:04.835249Z  INFO coord::timestamp: Timestamping Source u1 with Real Time Consistency.
2021-12-15T19:01:04.837027Z  INFO coord::timestamp: Discovered 4 new (4 total) kafka partitions for topic perf-upsert-4part3 (source u1)
2021-12-15T19:01:04.934713Z  INFO dataflow::source::kafka: Activating Kafka queue for perf-upsert-4part3 [2] (source u1/29) on worker 0
2021-12-15T19:01:04.940017Z  INFO dataflow::source::kafka: Activating Kafka queue for perf-upsert-4part3 [1] (source u1/29) on worker 3
2021-12-15T19:01:04.940073Z  INFO dataflow::source::kafka: Activating Kafka queue for perf-upsert-4part3 [3] (source u1/29) on worker 1
2021-12-15T19:01:04.940286Z  INFO dataflow::source::kafka: Activating Kafka queue for perf-upsert-4part3 [0] (source u1/29) on worker 2
2021-12-15T19:01:07.124319Z ERROR panic: index out of bounds: the len is 2 but the index is 2
thread: timely:work-2
location: src/dataflow/src/render/upsert.rs:269:25
version: 0.12.1-dev (54b2775d7ae18656805d8d92e380cf4781927c27)
backtrace:
   0: backtrace::backtrace::trace
   1: backtrace::capture::Backtrace::new
   2: materialized::handle_panic
   3: core::ops::function::Fn::call
   4: std::panicking::rust_panic_with_hook
   5: std::panicking::begin_panic_handler::{{closure}}
   6: std::sys_common::backtrace::__rust_end_short_backtrace
   7: _rust_begin_unwind
   8: core::panicking::panic_fmt
   9: core::panicking::panic_bounds_check
  10: dataflow::render::upsert::evaluate::{{closure}}
  11: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &mut F>::call_once
  12: core::option::Option<T>::map
  13: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::next
  14: repr::row::Row::extend
  15: dataflow::render::upsert::evaluate
  16: dataflow::render::upsert::upsert::{{closure}}::{{closure}}
  17: core::result::Result<T,E>::and_then
  18: dataflow::render::upsert::upsert::{{closure}}
  19: <timely::dataflow::stream::Stream<S,D> as timely::dataflow::operators::map::Map<S,D>>::flat_map::{{closure}}::{{closure}}::{{closure}}::{{closure}}
  20: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &mut F>::call_once
  21: core::option::Option<T>::map
  22: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::next
  23: <core::iter::adapters::fuse::Fuse<I> as core::iter::adapters::fuse::FuseImpl<I>>::next
  24: <core::iter::adapters::fuse::Fuse<I> as core::iter::traits::iterator::Iterator>::next
  25: <core::iter::adapters::flatten::FlattenCompat<I,U> as core::iter::traits::iterator::Iterator>::next
  26: <core::iter::adapters::flatten::FlatMap<I,U,F> as core::iter::traits::iterator::Iterator>::next
  27: timely::dataflow::channels::pushers::buffer::Session<T,D,P>::give_iterator
  28: <timely::dataflow::stream::Stream<S,D> as timely::dataflow::operators::map::Map<S,D>>::flat_map::{{closure}}::{{closure}}::{{closure}}
  29: timely::dataflow::operators::generic::handles::InputHandle<T,D,P>::for_each
  30: <timely::dataflow::stream::Stream<S,D> as timely::dataflow::operators::map::Map<S,D>>::flat_map::{{closure}}::{{closure}}
  31: <timely::dataflow::stream::Stream<G,D1> as timely::dataflow::operators::generic::operator::Operator<G,D1>>::unary::{{closure}}::{{closure}}
  32: timely::dataflow::operators::generic::builder_rc::OperatorBuilder<G>::build::{{closure}}::{{closure}}
  33: timely::dataflow::operators::generic::builder_rc::OperatorBuilder<G>::build_reschedule::{{closure}}
  34: <timely::dataflow::operators::generic::builder_raw::OperatorCore<T,L> as timely::scheduling::Schedule>::schedule
  35: timely::progress::subgraph::PerOperatorState<T>::schedule
  36: timely::progress::subgraph::Subgraph<TOuter,TInner>::activate_child
  37: <timely::progress::subgraph::Subgraph<TOuter,TInner> as timely::scheduling::Schedule>::schedule
  38: timely::progress::subgraph::PerOperatorState<T>::schedule
  39: timely::progress::subgraph::Subgraph<TOuter,TInner>::activate_child
  40: <timely::progress::subgraph::Subgraph<TOuter,TInner> as timely::scheduling::Schedule>::schedule
  41: timely::worker::Wrapper::step::{{closure}}
  42: core::option::Option<T>::map
  43: timely::worker::Wrapper::step
  44: timely::worker::Worker<A>::step_or_park
  45: dataflow::server::Worker<A>::run
  46: dataflow::server::serve::{{closure}}
  47: timely::execute::execute::{{closure}}
  48: timely_communication::initialize::initialize_from::{{closure}}
  49: std::sys_common::backtrace::__rust_begin_short_backtrace
  50: std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}}
  51: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
  52: std::panicking::try::do_call
  53: ___rust_try
  54: std::panicking::try
  55: std::panic::catch_unwind
  56: std::thread::Builder::spawn_unchecked::{{closure}}
  57: core::ops::function::FnOnce::call_once{{vtable.shim}}
  58: std::sys::unix::thread::Thread::new::thread_start
  59: __pthread_start
  ```
  
  in debug immediately after ingesting the first few records. This runs fine without persisted sources. I'm on main (54b2775d7ae18656805d8d92e380cf4781927c27)
  
  + the follwing diff
  
  ```
  diff --git a/src/persist/src/operators/stream.rs b/src/persist/src/operators/stream.rs
index 9435735a9..0b2641a39 100644
--- a/src/persist/src/operators/stream.rs
+++ b/src/persist/src/operators/stream.rs
@@ -454,6 +454,9 @@ where
                                         pending_future.time,
                                     );

+                                    if pending_future.time > 5 {
+                                        let _ = condition_write.allow_compaction(Antichain::from_elem(pending_future.time - 5));
+                                    }
                                     let future = primary_write.seal(pending_future.time);

                                     pending_futures.push_back(PendingSealFuture::PrimarySeal(
@@ -523,6 +526,9 @@ where
                         PendingSealFuture::PrimarySeal(mut pending_future) => {
                             match Pin::new(&mut pending_future.future).poll(&mut context) {
                                 std::task::Poll::Ready(Ok(_)) => {
+                                    if pending_future.time > 5 {
+                                        let _ = primary_write.allow_compaction(Antichain::from_elem(pending_future.time - 5));
+                                    }
                                     log::trace!(
                                         "In {}, finished sealing primary collection up to {}",
                                         &operator_name,
diff --git a/test/performance/perf-upsert/src/main.rs b/test/performance/perf-upsert/src/main.rs
index d5ad80600..9c45380b7 100644
--- a/test/performance/perf-upsert/src/main.rs
+++ b/test/performance/perf-upsert/src/main.rs
@@ -151,7 +151,7 @@ async fn create_upsert_text_source(
             query_prefix
         )
     } else {
-        format!("{} FORMAT BYTES ENVELOPE NONE", query_prefix)
+        format!("{} FORMAT BYTES ENVELOPE UPSERT", query_prefix)
     };
     log::debug!("creating source=> {}", query);
```

I'm running materialize with

```
cargo run -- --dev -w 4 --log-file=stderr --experimental --persistent-kafka-upsert-source
```

and testing it with the perf-upsert test (test/performance/perf-upsert)

run with 

```
RUST_LOG=debug cargo run --release -- --message-count 400 --messages-per-second 50 --create-topic --kafka-topic=perf-upsert-4part3 --partitions 4 --replication-factor 1
```

**Comment by ruchirK** [comment]
It's still crashing if I run with one timely worker, with a single partition kafka topic.

**Comment by ruchirK** [comment]
`cargo run --bin testdrive --release -- test/testdrive/kafka-upsert-sources.td` this also crashes when Materialize is run with 1 worker, and persistent kafka upsert sources. I'm convinced this is a real bug and not some quirk of how I'm testing mz.

**Comment by ruchirK** [comment]
@philip-stoev once we figure out root cause here this is a nice candidate for a persistence kafka upsert test.

**Comment by danhhz** [comment]
I asked Ruchir offline if any of the existing testdrive tests would have caught this if they were simply run with experimental kafka source persistence on and he said that indeed one of them fails. One of my takeaways here is that, even without restarts, the two different upsert operator impls now seems like a source of possible bugs. As a result, in addition to a targeted regression test, it's probably worth running in CI the existing kafka test suite a second time with persistence on. Maybe @philip-stoev can help set that up if it's not straightforward

**Comment by aljoscha** [comment]
> `cargo run --bin testdrive --release -- test/testdrive/kafka-upsert-sources.td` this also crashes when Materialize is run with 1 worker, and persistent kafka upsert sources. I'm convinced this is a real bug and not some quirk of how I'm testing mz.

This is #9330, the test creates non-materialized sources and then creates multiple `MATERIALIZED VIEW`s on them. Meaning there will be multiple instances of that one persistent source, and that messes things up.

**Comment by ruchirK** [comment]
I edited the test to only create one materialized source, and it still crashes.

**Comment by ruchirK** [comment]
I'm 99% sure I have isolated the root cause and will have a pr up soon!

**Comment by philip-stoev** [comment]
@danhhz @ruchirK We are fully set up to have a nightly job that runs the normal .td tests  with --persistent-kafka-source, as we already do that for --persistent-user-tables, I was just waiting for #9330 to be moved out of the way before I install it, as it seems that the fix for that was imminent. 

I will check why the tests in kafka/persistence/kafka-sources did not catch this independently.

**Comment by aljoscha** [comment]
I'm afraid I should have explained more, the "fix" for #9330 will only mean that we spit out a useful error message when users try to create multiple instances of a single persistent source. We could (and maybe should) run all the kafka source tests with persistence by changing `CREATE SOURCE ...` to `CREATE MATERIALIZED SOURCE ...`. This will ensure that there is only one instance of a given source.

**Comment by philip-stoev** [comment]
Ok so it seems this crash is specific to `key-format=bytes` . This explains why it was not caught by `kafka/persistence/kafka-sources` as no such test exists there. I will add one as soon as this PR is merged.

With respect to:

> We could (and maybe should) run all the kafka source tests with persistence by changing CREATE SOURCE ... to CREATE MATERIALIZED SOURCE ...

that would require adding a one-off regexp replacement complication somewhere along the pipeline. I would rather wait for the fix for #9330  and the stock testdrive tests to be adjusted for the new reality.

**Comment by aljoscha** [comment]
We can change the relevant testdrive tests right now, if we think that it's ok to change `CREATE SOURCE` to `CREATE MATERIALIZED SOURCE`. (I think it is, for this small subset of tests.)

**Comment by philip-stoev** [comment]
@aljoscha ok will check into that tomorrow and move it forward along with the --persistent-kafka-upsert-source in nightly.

**Comment by ruchirK** [comment]
That makes sense @aljoscha sorry for the misunderstanding!

**Comment by aljoscha** [comment]
@danhhz It's not impossible but it would be very hard. A `CREATE MATERIALIZED SOURCE` really desugars into a `CREATE SOURCE foo` plus `CREATE DEFAULT INDEX ON foo`. And most of the source rendering code doesn't know in what context it is being invoked. Plus, users can create indexes later on, or drop them, so anything we do here would only work unless users mess with that.

**Comment by ruchirK** [comment]
Another idea I thought of last night -- just a spitball -- what if we exposed a WITH option to opt out of persistence on a per-source basis? We don't have to make it public but it could be a nice workaround iff we feel like 9330 is a long way away (I have no idea). Then we just have to edit the places in testdrive where we create a unmaterialized source?

**Comment by aljoscha** [comment]
I don't think #9330 will fix this, it will just make it so that you get an error message telling you that you should NOT have multiple instances of the source. The _real_ fix will be to move sources to an `ingestd` and therefore only ingest them once. I'm not sure we should spend time to try and make this use case work in the current world. It's the same reason why I think #8522 doesn't try to be clever but just rejects this case as an error. 😅

**Comment by ruchirK** [comment]
Yeah, I agree with that. What I'm saying is - the existing testdrive tests have multiple materializations of the same source, and it seems like if we want to run testdrive with persist we'll have to either:

a) change persist to handle that use case well (as you said, we don't want to do that)
b) change the tests to not have multiple materializations of the same source
c) wait for ingestd / some other solution that solves this problem externally to persist by only keeping one instance of each source
d) add some way for some sources to opt out of persistence, so that this issue doesn't happen for them.

I agree with you that c) is the _real_ solution. I was just trying to think through the minimally invasive changes we could make to run testdrive with persist asap, and I feel like d) fits the bill on that?
