### ISSUE TITLE
doc: consider providing guidance about IMDSv2

### ISSUE THREAD

**Issue by benesch** [MaterializeInc/materialize#9652]
### For updates to existing documentation

* What pages are affected?

Any page about Materialize's interaction with AWS, like S3 and Kinesis sources.

* What needs to be changed or added?

In v0.10.0, we switched from Rusoto to the official AWS SDK. The new SDK only supports IMDSv2, not IMDSv1. IMDSv2 has a security feature that prevents Docker containers from running on EC2 instances from accesing IMDSv2 by default (search [this page](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/configuring-instance-metadata-service.html) for "hop limit" for details).

We may want to offer guidance to users on how to configure their EC2 instances to use a larger hop limit. Then again, no external users have complained in the past few weeks, so maybe no one is deploying Materialize on EC2 + Docker. (Folks using EKS or ECS won't run into this, nor will folks deploying on EC2 without Docker.)

**Comment by umanwizard** [comment]
Discussing in slack with @morsapaes -- I think we can put something in the "Troubleshooting" page of the docs. We don't need to go into a ton of technical detail, just explain that it's a new Amazon security feature preventing tokens from being accessed from any host other than the ec2 instance itself.

**Comment by benesch** [comment]
No longer relevant with platform!
