### ISSUE TITLE
persistence: recovery slower than re-ingestion with --workers >= 8 , kafka partitions

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#9705]
### What version of Materialize are you using?

```
2ef0b1b82d7b55e0e276818062ab660abbafb82e
```

### What was the issue?

This is a known issue within the team, but I feel it deserves a dedicated ticket so that it can be tracked and discussed.

Basically recovery is single-threaded (as is with most databases), but re-ingestion is multi-threaded. So, for `-workers 8, 16` with a kafka upsert workload that contains only unique keys and partitions, re-ingestion is faster.

I understand that 100% unique keys is the absolute worst case when it comes to recovery, as compaction can not kick in, however Alessandro reports that real-life workloads will have up to 85% new keys vs. updates on existing keys.

With --workers 8:

```
NAME                      |    THIS     |    OTHER    |  Regression?  | 'THIS' is:
--------------------------------------------------------------------------------
...
KafkaRecovery             |      10.178 |       7.650 |    !!YES!!    | 33.0 pct   slower
```

With --workers 18:

```
feature-benchmark_mzdata
NAME                      |    THIS     |    OTHER    |  Regression?  | 'THIS' is:
--------------------------------------------------------------------------------
KafkaRecovery             |      12.824 |       8.015 |    !!YES!!    | 60.0 pct   slower
```

### Is the issue reproducible? If so, please provide reproduction instructions.

1. From `git@github.com:philip-stoev/materialize.git` clone `feature-benchmark` (unless merged already)
2. Run
```
cd test/feature-benchmark
FB_SCENARIO=KafkaRecovery THIS_OPTIONS="--persistent-user-tables --persistent-kafka-upsert-source --workers 8" OTHER_OPTIONS="--workers 8" ./mzcompose run feature-benchmark
```

**Comment by aljoscha** [comment]
Closing this because current persist/storage architecture has moved quite a bit beyond this.

@philip-stoev Please yell at me if you'd like to keep this open.

fyi @danhhz
