### ISSUE TITLE
peristence: retractions out of a join are delayed disproportionately

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#9706]
### What version of Materialize are you using?

From the shell:

```
2ef0b1b82d7b55e0e276818062ab660abbafb82e
```

### What was the issue?

There are known performance issues with persistence with DMLs and with SELECTs. However, it seems that there is another problem that can not be completely explained by the above -- if a DELETE causes large retractions in the output of a materialized view, Mz with perisistence enabled takes much longer for the output to come up to speed.

This delay is not there if persistence is not enabled and is much larger than the timestamp frequency and does not seem to be proportional to it -- the test behaves the same with timestamp frequencies 10ms and 100ms.

### Is the issue reproducible? If so, please provide reproduction instructions.

With the feature benchmark framework:

```
cd test/feature-benchmark
FB_SCENARIO=Retraction THIS_OPTIONS="--persistent-user-tables --persistent-kafka-upsert-source"  ./mzcompose run feature-benchmark

NAME                      |    THIS     |    OTHER    |  Regression?  | 'THIS' is:
--------------------------------------------------------------------------------
Retraction                |       3.097 |       1.267 |    !!YES!!    | 2.4 TIMES slower
```

With testdrive:

```
> DROP VIEW IF EXISTS v1;
rows match; continuing at ts 1640078336.748923
> DROP TABLE IF EXISTS ten;
rows match; continuing at ts 1640078336.7647915
> CREATE TABLE ten (f1 INTEGER);
rows match; continuing at ts 1640078336.8013334
> INSERT INTO ten VALUES (0),(1),(2),(3),(4),(5),(6),(7),(8),(9);
rows match; continuing at ts 1640078336.8098328
> CREATE MATERIALIZED VIEW v1 AS SELECT a1.f1 + (a2.f1 * 10) + (a3.f1 * 100) + (a4.f1 * 1000) + (a5.f1 * 10000) + (a6.f1 * 100000) FROM ten AS a1, ten AS a2, ten AS a3, ten AS a4, ten AS a5, ten AS a6
rows match; continuing at ts 1640078336.8379319
> SELECT COUNT(*) = 1000000 AS f1 FROM v1;
rows match; continuing at ts 1640078338.0530815
> /* A */ SELECT 1;
rows match; continuing at ts 1640078338.054034
> DELETE FROM ten;
rows match; continuing at ts 1640078338.167585
> /* B */ SELECT COUNT(*) FROM v1;
rows match; continuing at ts 1640078341.220381
testdrive completed successfully.
```

The disproportionate delay is the difference between the last two timestamps reported, that is, the time that it took for the `SELECT COUNT(*)` to converge back to zero.

**Comment by philip-stoev** [comment]
May be related to #9628 where retractions are slower with --workers 1 than with --workers N .

**Comment by aljoscha** [comment]
Closing this because current persist/storage architecture has moved quite a bit beyond this. The code that was behind this, and the command line flags are not there anymore.

@philip-stoev Please yell at me if you'd like to keep this open.

fyi @danhhz
