### ISSUE TITLE
avro: unfortunately named columns prevent sinks from being created

### ISSUE THREAD

**Issue by maddyblue** [MaterializeInc/materialize#9723]
### What version of Materialize are you using?

v0.11.1-dev

### What was the issue?

A column with a non-alphanumeric name cannot be used in an avro sink. This came to light with unnamed columns getting the `?column?` name, and the `?` character preventing some tests from working (see #9413). We should do some column name transformation to make this work, or at least improve the error message for users and say it's because of column names.

Relatedly, the code at https://github.com/MaterializeInc/materialize/blob/47c3d7260c13add758acb7f34052304a712bf97a/src/interchange/src/encode.rs#L37 no longer needs to worry about the None case, and we should remove that from being a possibility.

**Comment by andrioni** [comment]
>We should do some column name transformation to make this work, or at least improve the error message for users and say it's because of column names.

I'm personally in favor of improving the error messages and making the Avro limitation explicit, instead of subtly mangling column names, especially since users need to know the field names to read the Avro files afterwards.

**Comment by benesch** [comment]
#9762 removed most of the weird optionality around `ColumnName` handling, but now the Avro source needs to make some decisions about how to name columns for top-level non-record types. Addressing that should also be part of this issue! More context here: https://github.com/MaterializeInc/materialize/pull/9762#discussion_r775665485

**Comment by benesch** [comment]
Looks like this got duplicated by https://github.com/MaterializeInc/materialize/issues/16372. Regardless, I fixed this in https://github.com/MaterializeInc/materialize/commit/cac67b12e8513fdeed0b3d1932095de41f2bfa1b!
