### ISSUE TITLE
Tests should not depend on the presence of tags

### ISSUE THREAD

**Issue by benesch** [MaterializeInc/materialize#9724]
Tags are global mutable state that exist outside the source tree that is precisely tracked by Git. The upgrade test, and possibly others, modifies its behavior based on what tags exist. This is a bit scary, because pulling a new tag will actually _change_ the behavior of the test. 

This most recently presented with the release of v0.13. The addition of that tag meant that the upgrade test now created and dropped one too many replication slots and started failing. This wouldn't be so bad if the blast radius were limited to the PR that added that version to the list of all known versions; unfortunately, it broke _all_ open PR builds (and probably all historical builds) because the test's behavior changes as soon as `git fetch --all` is run.

cc @philip-stoev (but I'm planning to take this one unless you object)

**Comment by philip-stoev** [comment]
@benesch how would you like to change this?

I personally think that the test behaves correctly if seen from the following angle:
- new versions of the product can be considered "features"
- so once feature "vX.Y.Z" lands in the product, the upgrade test, being an integration test of sorts, tests the integration between this feature and everything else
- from this angle it would be acceptable for the test to be doing different (more) stuff after a tag lands.

A problem with tags that I see is that "git fetch --all" may fetch version tags that are "in the future" as compared to the branch you are testing, if that branch has fallen behind "main".

**Comment by benesch** [comment]
Yeah, I think the test automatically accounting for new releases is great!
I just want the list of tags to be determined by a list of versions that is
committed in the repository somewhere. We already have that list of
versions in doc/user/config.toml, so my proposal is that we pull the list
of versions to test from there, rather than from the list of tags.

**Comment by philip-stoev** [comment]
Ok perfect, understood, thanks!
