### ISSUE TITLE
Support \du

### ISSUE THREAD

**Issue by andrioni** [MaterializeInc/materialize#9730]
### Feature request

`\du` is the meta-command to list all roles/users of the database.
Part of #9721. The query for `\du` is:
```sql
SELECT r.rolname, r.rolsuper, r.rolinherit,
  r.rolcreaterole, r.rolcreatedb, r.rolcanlogin,
  r.rolconnlimit, r.rolvaliduntil,
  ARRAY(SELECT b.rolname
        FROM pg_catalog.pg_auth_members m
        JOIN pg_catalog.pg_roles b ON (m.roleid = b.oid)
        WHERE m.member = r.oid) as memberof
, r.rolreplication
, r.rolbypassrls
FROM pg_catalog.pg_roles r
WHERE r.rolname !~ '^pg_'
ORDER BY 1;
```

The query for `\du pattern` is:
```sql
SELECT r.rolname, r.rolsuper, r.rolinherit,
  r.rolcreaterole, r.rolcreatedb, r.rolcanlogin,
  r.rolconnlimit, r.rolvaliduntil,
  ARRAY(SELECT b.rolname
        FROM pg_catalog.pg_auth_members m
        JOIN pg_catalog.pg_roles b ON (m.roleid = b.oid)
        WHERE m.member = r.oid) as memberof
, r.rolreplication
, r.rolbypassrls
FROM pg_catalog.pg_roles r
WHERE r.rolname OPERATOR(pg_catalog.~) '^(pattern)$'
ORDER BY 1;
```

### Main issues
- [x] Support array constructor with subquery
- [ ] Support `pg_auth_members` (relation in `pg_catalog`)
- [x] Support `rolsuper` (column in `pg_roles`)
- [x] Support `rolinherit` (column in `pg_roles`)
- [x] Support `rolcreaterole` (column in `pg_roles`)
- [x] Support `rolcreatedb` (column in `pg_roles`)
- [x] Support `rolcanlogin` (column in `pg_roles`)
- [x] Support `rolconnlimit` (column in `pg_roles`)
- [x] Support `rolvaliduntil` (column in `pg_roles`)
- [x] Support `rolreplication` (column in `pg_roles`)
- [x] Support `rolbypassrls` (column in `pg_roles`)

**Comment by andrioni** [comment]
We do have support for the list constructors with a subquery (done in #8571), but not for the array one.

**Comment by jkosh44** [comment]
Array subquery support was added in https://github.com/MaterializeInc/materialize/pull/10700
