### ISSUE TITLE
timestamp-binding related crash on startup can not be avoided with any command-line option

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#9784]
### What version of Materialize are you using?

0.13.1-dev (078be6ebc91b78054bb43b8a1f10447dd567ad90)

### How did you install Materialize?

Built from source

### What was the issue?

A persistence-related crash on startup, such as #9777 is **not** prevented by **any** of those:
1. starting Mz with `--disable-user-indexes` 
2. starting it with `---persistent-kafka-upsert-source` disabled
3. removing the persist subdirectory

The only option to get this up and running is to nuke the entire `mzdata` directory, which is basically equivalent to reinstalling Mz on a clean machine.

Note that from the options above, the Cloud UI only allows for # 1 to be performed by the end user.

**Comment by aljoscha** [comment]
Note: this is not about _persistence_ persistence, but about the old way of storing timestamp bindings in SQLite. One way that users could resolve this is by going into the SQlite database and manually delete the offending bindings. It's not pretty, though.

**Comment by elindsey** [comment]
Enough has changed in this area with platform (persist changed, persistence paths moved, ts binding path moved, etc) that I'm going to close this one out.
