### ISSUE TITLE
Tailing rotating logs

### ISSUE THREAD

**Issue by orent** [MaterializeInc/materialize#9793]
### Feature request

Instead of just a filename, accept directory path + optional glob or regex pattern.

Some ideas:
* File ordering configurable by modification time, string sort or string with numbers (equivalent to ordering used by "ls -v").  Also sort by regex capture groups? Support month names?
* Ensure it supports the rotation and compression practices of common tools, specifically logrotate.
* Sanity check: maintain list of file names/sizes/timestamps/tail hash/head hash/inode. Identify and report anomalies (changes/appends to files which are lot latest in set, changes other than append, etc).
* Sanity check: parse some record timestamp formats and verify monotonic or near-monotonic.
* Sanity check failures configurable to issue warning or pause source.

**Comment by benesch** [comment]
Hi @orent, thanks for the feature request! We're currently focusing on Materialize Cloud, so just want to caveat that we won't be spending too much time on our log rotation infrastructure.

I _do_ think it'd be worth investigating increased compatibility with logrotate. I suspect we just need to handle either the `HUP` or `USR1` signal by reopening the log file.

**Comment by orent** [comment]
Supporting HUP is for for when you are the one *writing* to a log file.

I am talking about a SOURCE that is *reading* the tail of log files that are being rotated rather than a single file.

**Comment by benesch** [comment]
Oh, I see, I misunderstood. We've got an existing feature request for that: #3773.

Just to set expectations, the warning about the focus on Materialize Cloud still applies. We're investing our efforts into S3 sources these days rather than file sources.

**Comment by benesch** [comment]
I'm going to close this out so we can centralize the discussion on #3733. I've ported your comment over, though. Thanks very much for the use case and suggestions! When we do get around to #3733 we'll make sure the solution works well for the log-rotating case. If you've got any more thoughts, please leave them on #3733!
