### ISSUE TITLE
SLT stage in CI is passing even when some of the tests failed.

### ISSUE THREAD

**Issue by umanwizard** [MaterializeInc/materialize#9850]
### What version of Materialize are you using?

https://github.com/MaterializeInc/materialize/pull/9849 (based on 728a32c3 from Friday)

### How did you install Materialize?

Built from source

### What was the issue?

E.g.: https://buildkite.com/materialize/tests/builds/26047#05245879-fe0b-443f-a0ba-ece1636f3edc

**Comment by umanwizard** [comment]
@benesch I think this is because of 1e869d68e414e235313e53120a968be03cc6053d.

When we run Sqllogictest and it fails, that turns into a `CalledProcessError` in Python, which we replace with a `UIError` [here](https://github.com/MaterializeInc/materialize/blob/728a32c/misc/python/materialize/mzcompose.py#L458)  , which eventually gets printed and then swallowed. Thus Buildkite has no way of knowing that the step failed.

**Comment by umanwizard** [comment]
Can we perhaps just add a `sys.exit(1)` to the branch that prints the UIError?

**Comment by benesch** [comment]
Oof, sorry, thanks!
