### ISSUE TITLE
Handle SET NAMES alias for SET client_encoding

### ISSUE THREAD

**Issue by ruf-io** [MaterializeInc/materialize#9899]
### Feature request

Attempting to connect Prisma.io to Materialize currently fails because Prisma attempts to send `SET NAMES  'UTF8';` Which is postgres shorthand/alias for `SET client_encoding TO 'UTF8';` https://www.postgresql.org/docs/9.1/sql-set.html 

## Request

Make the shorthand version work!

### More Context: 

From [Community Slack](https://materializecommunity.slack.com/archives/C015KDVS7EV/p1641334158429700?thread_ts=1641236344.422000&cid=C015KDVS7EV):

I found out that SQL that causes the error is SET NAMES ' UTF8';  Which prisma sends when attempting to connect. According to https://www.postgresql.org/docs/9.1/sql-set.html  the correct syntax for the command is
SET [ SESSION | LOCAL ] configuration_parameter { TO | = } { value | 'value' | DEFAULT }
If i interpret this right, the { TO | = }part here is indeed optional and with normal postgres dbs the command works without this part. Would it be possible to adapt this in materialize?

[Internal Slack](https://materializeinc.slack.com/archives/C015RHB3LDR/p1641341021255400)

**Comment by benesch** [comment]
Fixed in #9900!
