### ISSUE TITLE
sql: Handle `SHOW TIME ZONE` as an alias for `SHOW TIMEZONE`

### ISSUE THREAD

**Issue by bobbyiliev** [MaterializeInc/materialize#9908]
### Feature request

In Postgres both `SHOW TIMEZONE` and `SHOW TIME ZONE` work identically, but in Materialize only `SHOW timezone` works:

```
materialize=> SHOW TIME ZONE;
ERROR:  Expected end of statement, found ZONE
LINE 1: SHOW TIME ZONE;
```

### Request

Make both versions work.

### Context

In some cases ORM libraries like Ruby's ActiveRecord ORM default to `SHOW TIME ZONE`.

**Comment by umanwizard** [comment]
@pH14 , this seems like a good first ramp-up task.
