### ISSUE TITLE
Standardize JSON parsing syntax across every example

### ISSUE THREAD

**Issue by ruf-io** [MaterializeInc/materialize#9935]
### What pages are affected?

Currently: 
- ~https://materialize.com/docs/sql/create-source/json-kafka~ (Fixed in [#10678](https://github.com/MaterializeInc/materialize/pull/10678))
- ~https://materialize.com/docs/sql/create-source/json-kinesis~ (Fixed in [#10914](https://github.com/MaterializeInc/materialize/pull/10914))
- ~https://materialize.com/docs/sql/create-source/json-s3~ (Fixed in [#10966](https://github.com/MaterializeInc/materialize/pull/10966))
- ~https://materialize.com/docs/sql/create-source/json-pubnub~ (Fixed in [#11726](https://github.com/MaterializeInc/materialize/pull/11726))
- ~https://materialize.com/docs/sql/create-source/json-file~ (Fixed in [#11614](https://github.com/MaterializeInc/materialize/pull/11614))

And https://materialize.com/docs/sql/types/jsonb/

### What needs to be changed or added?

We need to use a consistent syntax for going from raw data to parsed JSON everywhere.

We can decide on the right format in this issue thread.  I personally like the brevity of:

```sql
CREATE MATERIALIZED VIEW json_example AS
  SELECT
    jsonified.data->>'user_id' AS user_id,
    jsonified.data->>'disks_used' AS disks_used,
    jsonified.data->>'cpu_used_minutes' AS cpu_used_minutes
  FROM (SELECT text::JSONB AS data FROM json_source) AS jsonified;
```

But I want to make sure it works for all scenarios.

**Comment by ruf-io** [comment]
I just realized that example only works for strings. Need to decide on a format for other datatypes as well.

**Comment by benesch** [comment]
If this can wait until end of next week, let's get support for the [new PostgreSQL JSON syntax](https://blog.crunchydata.com/blog/better-json-in-postgres-with-postgresql-14) landed. Then it reduces to something like this:

```sql
CREATE MATERIALIZED VIEW json_example AS
  SELECT
    data['user_id']::int AS user_id,
    data['disks_used']::text AS disks_used,
    data['cpu_used_minutes']::float AS cpu_used_minutes
  FROM (SELECT text::jsonb AS data FROM json_source);
```

We also have this sample Rust program that takes a sample JSON datum and emits a materialized view definition for that datum: https://github.com/MaterializeInc/materialize/blob/main/play/json-flattened-view-gen/src/main.rs. I'd love to rewrite that in JavaScript and get it embedded in the docs somewhere. Paste in your sample JSON, get a materialized view definition out.

**Comment by benesch** [comment]
> We also have this sample Rust program that takes a sample JSON datum and emits a materialized view definition for that datum: https://github.com/MaterializeInc/materialize/blob/main/play/json-flattened-view-gen/src/main.rs. I'd love to rewrite that in JavaScript and get it embedded in the docs somewhere. Paste in your sample JSON, get a materialized view definition out.

I hacked this up on my flight: https://deploy-preview-9943--materializeinc.netlify.app/guides/json/ Try to imagine it with a fresh coat of paint!

**Comment by morsapaes** [comment]
Just started working on this, and after porting the getting started guides I'm a bit divided about what syntax to standardize the examples on. Subscripting is making me think _way_ too much about casting, like:

* Having to use JSON strings to compare against text output. If you miss the [remarks](https://materialize.com/docs/sql/types/jsonb/#remarks), this can easily lead to confusion (_e.g._ joining on a column that doesn't expect quoted strings on the other side of the relation and getting an empty result). This also makes output more confusing to parse (which, to be fair, mostly means that it looks _uglier_ in guides and demos than anything else).
* Doing some gymnastics to handle null values. If the source data has null values, you're forced to work around it with `jsonb_strip_nulls` (see [this thread](https://materializeinc.slack.com/archives/CMHDK0DK8/p1643818363880779)).

Overall, using the `jsonb` operators so far looks more convenient to me for _most_ situations, unless you're dealing with deeply nested JSON. This reads like a statement I should get punched in the face for, but it's bugging me so thought I'd get your take on it before moving any further @ruf-io @benesch.

**Comment by benesch** [comment]
> Overall, using the `jsonb` operators so far looks more convenient to me for _most_ situations, unless you're dealing with deeply nested JSON. This reads like a statement I should get punched in the face for, but it's bugging me so thought I'd get your take on it before moving any further @ruf-io @benesch.

Yeah, this seems totally fair to me. The fact that you get JSON strings instead of SQL strings with subscripting is a serious irritant. This is the shortest way I could come up with to combine subscripting with the goodness of the `->>` operator, but I'll grant it's pretty incomprehensible:

```
benesch=# select data['field']->>0 from (values ('{"field": null}'::jsonb), ('{"field": "string"}')) _ (data);
 ?column? 
----------
 
 string
(2 rows)
```

**Comment by benesch** [comment]
Ugh, I wish we had the bandwidth to do something like: https://github.com/MaterializeInc/materialize/issues/7186#issuecomment-984210788.

**Comment by morsapaes** [comment]
@petrosagg seemed keen to work on that. 👀 I was genuinely excited about subscripting, but as soon as I tried porting a couple of statements it turned out to be just a different kind of pain (though it looks much, much cleaner).

**Comment by morsapaes** [comment]
Closing this as all the examples now follow the same syntax. We should extend the examples with a note about handling encodings other than `utf-8` using [`decode`](https://materialize.com/docs/sql/functions/encode/#examples), since this has come up multiple times in the community (opened #12016 to track this).
