### ISSUE TITLE
Validate if transaction is in read-only mode before applying DDL/DML

### ISSUE THREAD

**Issue by andrioni** [MaterializeInc/materialize#9999]
Right now most DDL/DML statements are blocked in read-only transactions because [they are blocked in all transactions](https://github.com/MaterializeInc/materialize/blob/df96e2d83d63d2d3dc4f447bbece04c4126bedaa/src/coord/src/coord.rs#L1149-L1172), which is fine for now, but for extra safety we might want to add additional guards and ensure they are also explicitly blocked in read-only transactions.

The main motivation is to add another layer of protection to ensure users in BI tools (e.g. Metabase) that execute user queries in read-only transactions can't accidentally run mutations, even if we end up accepting those statements inside transactions.

**Comment by benesch** [comment]
Closing since this is about a hypothetical risk that's not yet come to pass. #20426 tracks
